### ISSUE TITLE
API add CNAME error

### ISSUE THREAD

**Issue by flfq** [PowerDNS/pdns#10033]
all version

```
curl -X POST --data '{"name":"example.org.", "kind": "Native", "masters": [], "nameservers": ["ns1.example.org.", "ns2.example.org."]}' -v -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones

curl -X PATCH --data '{"rrsets": [ {"name": "example.org.", "type": "CNAME", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "test.test.com", "disabled": false } ] } ] }' -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org.
```
return

{"error": "RRset example.org. IN CNAME: Conflicts with pre-existing RRset"}

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

If you open another ticket about this question, we will block you.

**Comment by flfq** [comment]
`curl -X PATCH --data '{"rrsets": [ {"name": "sub.example.org.", "type": "CNAME", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "test.test.com", "disabled": false } ] } ] }' -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org.`

is ok
`
curl -X PATCH --data '{"rrsets": [ {"name": "example.org.", "type": "CNAME", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "test.test.com", "disabled": false } ] } ] }' -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.org.
`
error

**add sub.example.org CNAME ok
add example.org CNAME error**

**Comment by Habbie** [comment]
Yes, you cannot have CNAME and other data on the same name.
