### ISSUE TITLE
dnsdist 1.6.0-alpha1 "handling auth for" log spam

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#10049]
- Program: dnsdist
 - Issue type: Bug report

### Short description
we use tools to monitor the state of dnsdist over the api every few seconds. 
Since dnsdist 1.6.0alpha1 these requests now cause  the log  being flodded with messages such as:

```
Feb 03 10:06:47 poike.switch.ch dnsdist[8976]: handling auth for /jsonstat
Feb 03 10:06:48 poike.switch.ch dnsdist[8976]: handling auth for /jsonstat
Feb 03 10:06:48 poike.switch.ch dnsdist[8976]: handling auth for /jsonstat
Feb 03 10:06:48 poike.switch.ch dnsdist[8976]: handling auth for /jsonstat
Feb 03 10:06:48 poike.switch.ch dnsdist[8976]: handling auth for /api/v1/servers/localhost
Feb 03 10:06:49 poike.switch.ch dnsdist[8976]: handling auth for /api/v1/servers/localhost
Feb 03 10:06:49 poike.switch.ch dnsdist[8976]: handling auth for /jsonstathandling auth for /jsonstat
Feb 03 10:06:49 poike.switch.ch dnsdist[8976]: handling auth for /api/v1/servers/localhost
Feb 03 10:06:49 poike.switch.ch dnsdist[8976]: handling auth for /jsonstat
```

### Environment

 - Operating system: centos7
 - Software version:  dnsdist 1.6.0-alpha1 (Lua 5.1.4 [LuaJIT 2.0.4])
 - Software source: compiled ourselves

### Steps to reproduce
 * make a request to the api
 * check the log

### Expected behaviour
no log entry (maybe unless some debug level is configured)

### Actual behaviour
log message for every request

### Other information
introcuced in https://github.com/PowerDNS/pdns/pull/9972/commits/fa7e8b5dd7f21d52cd21b5b7cb0e3b9f67558da6
```
static bool handleAuthorization(const YaHTTP::Request& req)
{
  cerr<<"handling auth for "<<req.url.path<<endl;
```

**Comment by rgacogne** [comment]
Nice catch!
