### ISSUE TITLE
Bind zone files fail if first A record is subdomain

### ISSUE THREAD

**Issue by andrewsmales** [PowerDNS/pdns#10059]
- Program: Authoritative
 - Issue type: Bug report

### Short description

I believe this is a bug - as far as I can see, BIND zone files are not required to be in a certain order. Always possible that I am missing something obvious though!

If the A records in a zone file start like this:

blog    IN    A    1.2.3.4
            IN    A    1.2.3.4

the server doesn't give an answer. Changing the order of those lines will fix it.    

### Environment

 - Operating system: Ubuntu 20.04.2 LTS
 - Software version: PowerDNS Authoritative Server 4.2.1 (C) 2001-2019 PowerDNS.COM BV
Feb 04 19:58:51 Using 64-bits mode. Built using gcc 9.2.1 20200202.
 - Software source: installed using apt install

### Steps to reproduce

1. Create zone file:
; BIND db file for example.com

$ORIGIN example.com.
$TTL 7200m

@       IN      SOA     ns1.example.com.      hostmaster.example.com. (
                        1612467987      ; serial number
                        18246           ; Refresh
                        1800            ; Retry
                        1814400         ; Expire
                        7200            ; Min TTL
)

blog        IN      A       1.2.3.4
        IN      A       1.2.3.4

2. 
set up Bind support in pdns

3. run:
nslookup
server yourserveraddress
example.com

### Expected behaviour

should show the IP address 1.2.3.4

### Actual behaviour

*** Can't find example.com: No answer

**Comment by mnordhoff** [comment]
What happens with a zone that has `NS` records?

**Comment by pieterlexis** [comment]
I believe there's an '@' missing on the line with the apex A record?

**Comment by andrewsmales** [comment]
> 
> 
> I believe there's an '@' missing on the line with the apex A record?

Ah, this seems to be the case, if I change it to:

blog IN A 1.2.3.4
@ IN A 1.2.3.4

it works. Our system was just kicking out files without that, and I did not know that was needed. Thanks!

**Comment by mind04** [comment]
blog IN A 1.2.3.4
IN A 1.2.3.4
will result is a duplicate a record for blog.example.com
