### ISSUE TITLE
Can't perform signature with dig +dnssec using an HSM

### ISSUE THREAD

**Issue by oli4a** [PowerDNS/pdns#10071]
- Program: Authoritative, compiled from source
 - Issue type: Bug report

### Short description
I'm trying to create a secure zone for DNSSEC queries by leveraging an HSM. I was able to setup the zone with a KSK and a ZSK, but I'm getting errors when using dig with the "+dnssec" flag. The issue seems to arise at the moment where a signature must be generated.

### Environment

I installed PowerDNS from source with pgsql as backend. Here is some basic information about my system:

```bash
$ uname -a
Linux testing 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Here are my PowerDNS installation steps:

```bash
$ git clone https://github.com/PowerDNS/pdns.git
$ cd pdns
$ git submodule update --init --recursive
$ autoreconf -vi
$ ./configure --enable-experimental-pkcs11 --disable-lua-records --with-modules="gpgsql"
$ make
$ sudo make install
$ sudo apt install pdns-backend-pgsql
```

### Steps to reproduce
Here are the steps I used to setup the zone (and I added a test record):

```bash
$ pdnsutil create-zone example.com
$ pdnsutil set-meta example.com SOA-EDIT-API INCREASE
$ pdnsutil set-meta example.com NOTIFY-DNSUPDATE 1
$ pdnsutil set-kind example.com master
$ pdnsutil import-zone-key example.com ksk.priv KSK active published
$ pdnsutil import-zone-key example.com zsk.priv ZSK active published
$ pdnsutil set-nsec3 example.com '1 1 1 -' narrow
$ pdnsutil rectify-all-zones
$ pdnsutil add-record example.com testcert CERT '1 1 0 tg9mtF2hUDAVOgOINJgLJXyHFicKrcdvy5Krhjfs+Mo='
```

Note that the content of "ksk.priv" and "zsk.priv" are similar to each other and resemble the following:

```
Private-key-format: v1.2
Algorithm: 13
Engine: qasm
Slot: SPA HSM
PIN: 1234
Label: KSK
PubLabel: KSK
```

After setting up the zone, I use two terminals, one to run the pdns_server and the other to send a "dig" command:

```bash
(first terminal) $ sudo .../pdns_server --daemon=no --local-port=5300
(second terminal) $ dig @localhost -p 5300 testcert.example.com cert +dnssec
```

### Expected behaviour
```bash
$ dig @localhost -p 5300 testcert.example.com cert +dnssec

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> @localhost -p 5300 testcert.example.com cert +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48934
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;testcert.example.com.	IN	CERT

;; ANSWER SECTION:
testcert.example.com. 3600	IN	RRSIG	CERT 13 3 3600 20210218000000 20210128000000 62153 example.com. 3ozzkuMGzLITs7EbeaUFTGS0xlKwlwqv7m4h43I8KeUEWNaD9u442WOX ytLiyPY+Ok8XXRRwNUl2DCJUSXVsPw==
testcert.example.com. 3600	IN	CERT	PKIX 1 0 tg9mtF2hUDAVOgOINJgLJXyHFicKrcdvy5Krhjfs+Mo=

;; Query time: 8 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Feb 08 12:25:08 EST 2021
;; MSG SIZE  rcvd: 211
```

### Actual behaviour
```bash
$ dig @localhost -p 5300 testcert.example.com cert +dnssec

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> @localhost -p 5300 testcert.example.com cert +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 1286
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;testcert.example.com.	IN	CERT

;; Query time: 16 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Feb 08 11:41:20 EST 2021
;; MSG SIZE  rcvd: 52
```

On the terminal running pdns_server, I get the following:
```bash
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key KSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key KSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key KSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key ZSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key ZSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key KSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key KSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key ZSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key ZSK
Feb 08 12:17:00 PKCS#11 operation C_FindObjectsInit failed: Internal error (0x5) ()
Feb 08 12:17:00 Cannot load PCKS#11 private key ZSK
Feb 08 12:17:00 PKCS#11 operation C_DigestInit failed: Internal error (0x5) ()
Feb 08 12:17:00 PKCS#11 operation C_DigestUpdate failed: No operation is taking place (0x91) ()
Feb 08 12:17:00 PKCS#11 operation C_DigestUpdate failed: No operation is taking place (0x91) ()
Feb 08 12:17:00 PKCS#11 operation C_DigestFinal failed: No operation is taking place (0x91) ()
```

### Other information
I believe this might be a bug with the PKCS#11 integration of PowerDNS, but it is very much possible that I'm missing something obvious. I've explored different potential reasons for this error, but so far I have been unsuccessful at finding the error. After some investigation, it seems that the function "FindObjects2" in pdns/pkcssigners.cc is unable to find the ZSK and the KSK, although they do exist on the HSM. Below are some potential solutions I tried to explore, in vain:

1 - Problem with database configuration
2 - Problem with the PKCS#11 library associated to the HSM
3 - Problem connecting the PKCS#11 library of the HSM and pdnsutil
4 - Attributes used to find the key

#### Problem with database configuration
When I run dig without the dnssec flag, it works well, so I know it's not a problem with my database configuration:

```bash
$ dig @localhost -p 5300 testcert.example.com cert 

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> @localhost -p 5300 testcert.example.com cert
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45891
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testcert.example.com.	IN	CERT

;; ANSWER SECTION:
testcert.example.com. 3600	IN	CERT	PKIX 1 0 tg9mtF2hUDAVOgOINJgLJXyHFicKrcdvy5Krhjfs+Mo=

;; Query time: 5 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Mon Feb 08 11:54:17 EST 2021
;; MSG SIZE  rcvd: 101
```

#### Problem with the PKCS#11 library associated to the HSM
I've been able to use the same PKCS#11 library and the same HSM with BIND9 and I was successful at performing signatures.

#### Problem connecting the PKCS#11 library of the HSM and pdnsutil
I was able to use the "pdnsutil hsm assign" and "pdnsutil hsm create-key" functions to create the keys on the HSM and that worked, so I know that the PKCS#11 interface of pdnsutil can talk to the HSM. However, regardless of if I use "import-zone-key" or "create-key", when I run "dig" I get the same error.

#### Attributes used to find the key
I thought that maybe the issue lied with the attributes used to find the key, but I've tried several combinations, some of which were extremely minimalist, and I keep running into the same problem.

**Comment by oli4a** [comment]
I found the solution to my problem! It turns out that pdns_server forked the process to the "pdns" user and therefore lost the environment variables required to talk to the HSM. To fix this issue, I needed to add a configuration file to /etc and make sure that the PKCS#11 library looks for this file as default to load various properties and environment variables. It is now working well.

**Comment by Habbie** [comment]
Thank you for reporting back!
