### ISSUE TITLE
lua-dns-script option with non-existing path is not fatal error

### ISSUE THREAD

**Issue by pspacek** [PowerDNS/pdns#10079]
- Program: Recursor
 - Issue type: Bug report

### Short description
Recursor starts up despite missing `lua-dns-script` file.

### Environment

 - Operating system: Arch Linux
 - Software version: gg2e63a37
 - Software source: compiled myself

### Steps to reproduce
1. set `lua-dns-script` option to a non-existing path
2. start recursor

### Expected behaviour
Error that file does not exist and recursor process exit.

### Actual behaviour
It starts up, logs a message, and goes on to processes DNS queries.
```
Feb 12 10:55:10 Unable to read configuration file from 'refuse.lua': No such file or directory
Feb 12 10:55:10 Loaded 'lua' script from 'refuse.lua'
```

**Comment by pspacek** [comment]
Also present in 4.4.2, custom build on Ubuntu 20.04.

**Comment by kpfleming** [comment]
#11818 is related to this.
