### ISSUE TITLE
Segmentation fault (core dumped) when running dnsdist client mode and dbpf:excludeRange

### ISSUE THREAD

**Issue by rage4** [PowerDNS/pdns#10090]
- Program: dnsdist
 - Issue type: Bug report

### Short description

dnsdist client mode crashes with "Segmentation fault (core dumped)" when using eBPF excludeRange

### Environment

 - Operating system: Ubuntu 16.04 LTS with HWE kernel
 - Software version: dnsdist 1.6.0-alpha0.326.master.gd799ea222
 - Software source: PowerDNS repository

### Steps to reproduce

1. setup dnsdist
2. add the following lines to config, restart
```
bpf = newBPFFilter(1024, 1024, 1024)
setDefaultBPFFilter(bpf)
bpf:blockQName(newDNSName("."))

dbpf = newDynBPFFilter(bpf)
dbpf:excludeRange({ "88.198.139.2/32", "88.198.139.3/32" })
registerDynBPFFilter(dbpf)

function maintenance()
 addBPFFilterDynBlocks(exceedQRate(100, 1), dbpf, 120)
 dbpf:purgeExpired()
end
```

3. run dnsdist -c

### Expected behaviour

correct access to dnsdist client console

### Actual behaviour

Segmentation fault (core dumped)

**Comment by rage4** [comment]
side note - as I'm aware the issue was there also in 1.5.x

**Comment by rgacogne** [comment]
Right, that's because `newDynBPFFilter(bpf)` returns `nullptr` (`nil`) in client mode, and then calling `excludeRange` on that pointer triggers a null pointer dereference.. 
We have seen that for other objects already, we can either return a mockup object or check for `nullptr` in all `BPFFilter` methods.

**Comment by pieterlexis** [comment]
I'm wondering if it would make sense to have multiple configs with all options enabled and test the client mode in our CI as well

**Comment by rgacogne** [comment]
> I'm wondering if it would make sense to have multiple configs with all options enabled and test the client mode in our CI as well

That would be very nice to have, yes.
