### ISSUE TITLE
dnsdist: Review performance impact of MaxQPSIPRule()

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#10124]
- Program: dnsdist
 - Issue type: Bug report / Feature request

### Short description
On current modest hardware dnsdist can easily handle a few hundred kqps of real-live traffic and easily sink 1Mqps towards a drop action rule. However during testing I discovered that MaxQPSIPRule() has quite a hefty performance penalty - which is of course not completely unexpected. However this seems to be locking-related as I don't see any CPU cores maxing out or coming even close to 50%. In fact CPU load even drops as packets seem to get lost earlier.
Based on that I'd propose to review MaxQPSIPRule() code. If no improvements are possible I'd suggest to document the overall impact of using this rule.

### Environment
 - Operating system: Ubuntu 20.04.2 LTS
 - Software version: dnsdist 1.5.1-1pdns.focal
 - Software source: PowerDNS repo

### Steps to reproduce
1. Configure dnsdist with multiple listeners on a single port
2. Add a drop action rule: `addAction(AllRule(),DropAction())`
3. Add a MaxQPSIPRule: e.g. `addAction(MaxQPSIPRule(3000, 32, 64),DropAction())`
4. Benchmark dnsdist with a traffic-replay of about 400kqps and watch UDP `InErrors` counters
5. Move the MaxQPSIPRule() up/down, notice hefty UDP loss and CPU load reduction when the rule triggers.

### Expected behaviour
No UDP drops, (slight) CPU usage increase.

### Actual behaviour
CPU usage reduction; UDP packet drops.

**Comment by rgacogne** [comment]
I don't see anything obviously bad at a quick glance, I will have to do some performance testing to investigate further. Still that rule uses a LRU internally and thus takes a lock for every lookup, so it _will_ have an impact on concurrency when many receiver threads are involved. We can't easily shard it either.
