### ISSUE TITLE
No Auth 4.4.0 packages for Ubuntu Xenial

### ISSUE THREAD

**Issue by rage4** [PowerDNS/pdns#10120]
- Program: Authoritative repository
 - Issue type: Bug report

### Short description

It seems that pdns auth 4.4.0 packages for Ubuntu 16.04 (xenial) are no longer available from repo even if repo says that they are there

### Environment

 - Operating system: Ubuntu 16.04

### Steps to reproduce

1. Check http://repo.powerdns.com/ubuntu/dists/xenial-auth-44/main/binary-amd64/Packages
2. Try to fetch http://repo.powerdns.com/ubuntu/pool/main/p/pdns/pdns-backend-geoip_4.4.0-1pdns.xenial_amd64.deb

### Expected behaviour

Packages should be available as before 

### Actual behaviour

Installation attempt fails with error 404

**Comment by thibmac** [comment]
Hi, jumping on this ticket to report that stretch repositories were not upgraded with the auth-4.4.1. It is still 4.4.0 :

`root@stretch_machine /etc/apt/sources.list.d# apt-cache policy pdns-server
pdns-server:
  Installed: 4.4.0-1pdns.stretch
  Candidate: 4.4.0-1pdns.stretch
  Version table:
 *** 4.4.0-1pdns.stretch 600
        500 http://repo.powerdns.com/debian stretch-auth-44/main amd64 Packages
        100 /var/lib/dpkg/status
     4.0.3-1+deb9u5 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org stretch/updates/main amd64 Packages
`

`root@buster_machine ~# apt-cache policy pdns-server
pdns-server:
  Installé : 4.4.1-1pdns.buster
  Candidat : 4.4.1-1pdns.buster
 Table de version :
 *** 4.4.1-1pdns.buster 600
        500 http://repo.powerdns.com/debian buster-auth-44/main amd64 Packages
        100 /var/lib/dpkg/status
     4.1.6-3+deb10u1 500
        500 http://sourcelist.local.perf1.net/debian buster/main amd64 Packages
`

**Comment by zmejuka** [comment]
It seems there will no further releases of 4.4.X for Xenial.

Here a bit more details:
https://www.mail-archive.com/pdns-users@mailman.powerdns.com/msg11298.html

**Comment by Habbie** [comment]
We have decided to support Xenial in 4.4 until Xenial goes EOL (in less than two months). Any missing packages will be restored soon.

Next week, we will post a full statement on EOLing various distribution versions.

**Comment by Habbie** [comment]
repo.powerdns.com now has auth 4.4.1 for Xenial and Stretch. The statement is coming next week (really!)
