### ISSUE TITLE
rec: rec_control confused by virtual service runtime directories

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#10123]
- Program: Recursor
 - Issue type: Bug report

### Short description
rec_control in 4.4.2 seems slightly confused by virtual service runtime directories (#9073). It tries to generate its temporary socket in `/var/run/pdns-recursor` which does not exist when not running a main instance.
Providing it with the correct socket-dir of the target instance helps. I'd assume it should figure that out by itself?

### Environment
 - Operating system: Ubuntu 20.04.2 LTS (yes, after I ran into #9485 on 18.04 ;p)
 - Software version: pdns-recursor 4.4.2-1pdns.focal
 - Software source: PowerDNS repo

### Steps to reproduce
```
# rec_control --config-name=recursor01 version
Fatal: Unable to generate local temporary file in directory '/var/run/pdns-recursor': No such file or directory
# rec_control --config-name=recursor01 --socket-dir=/var/run/pdns-recursor-recursor01 version
4.4.2
```

### Expected behaviour
Working without specifying socket directory.

### Actual behaviour
Requiring socket directory on command line (or likely in config).

### Other information
For Auth #9987 seems to be related.

**Comment by omoerbeek** [comment]
Since `rec_control` is run outside systemd control I do not see a way around this atm. @pieterlexis, anything to add?

**Comment by pieterlexis** [comment]
I _think_ trying to be smart will make the situation worse. A good 'workaround' is to set `socket-dir=/var/run/pdns-recursor-recursor01` in the config file. But changing that won't actually change the dir, as it is set on the commandline (overwriting the config file) by the service file. So tread carefully
