### ISSUE TITLE
dnsdist: Setting setCacheCleaningPercentage() breaks packetcache in the long run

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#10128]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Setting setCacheCleaningPercentage() to a value != 100 seems to break the packetcache - not immediately but in the long run, depending on the amount of queries, packetcache size and sharding. During runtime the packetcache fill level seems to become almost constant and the cache hit rate worse per minute.
I could be wrong but from a quick look at the code it seems [DNSDistPacketCache::purgeExpired](https://github.com/PowerDNS/pdns/blob/2753956a56928f6c996dc457340fb353bb5ee755/pdns/dnsdist-cache.cc#L312-L332) iterates over packetcache shards until it has cleaned sufficiently many entries. However I'd assume it manages to do this in the first few shards and never reaches the last causing these to fill up.
On a full shard `DNSDistPacketCache::insertLocked` seems to just drop the entry. Note that at this stage there doesn't seem to be a metric for this while it might be an interesting figure (but I might have missed it).
Sharding was introduced in 2b3eefc37bc815538059105c3c49d0e6b6f383f4, `setCacheCleaningPercentage()` earlier in f65ea0c29202c50561b0ca98fdbd1cb630b703b6 - guess `setCacheCleaningPercentage()` might need a review :wink:
Also proposing a metric for "full shards insert drops" in case there isn't one (and it still makes sense after this fix).

### Environment

 - Operating system: Ubuntu 20.04.2 LTS
 - Software version: dnsdist 1.5.1-1pdns.focal
 - Software source: PowerDNS repo

### Steps to reproduce
1. Set `setCacheCleaningPercentage(30)`
2. Let dnsdist run and feed it with some real-live traffic
3. Watch packet cache hit rate degrade over time

### Expected behaviour
setCacheCleaningPercentage() not having much impact on cache hit rate.

### Actual behaviour
Last packetcache shards seem to become filled up with no further entries / updates possible.

**Comment by rgacogne** [comment]
> I could be wrong but from a quick look at the code it seems DNSDistPacketCache::purgeExpired iterates over packetcache shards until it has cleaned sufficiently many entries. However I'd assume it manages to do this in the first few shards and never reaches the last causing these to fill up.

`d_expungeIndex` should ensure we always start with a shard that has not been scanned the last time, if any, though?

**Comment by rgacogne** [comment]
Should be fixed by #10133.
