### ISSUE TITLE
no multi-stars entry possible through api

### ISSUE THREAD

**Issue by vabtNfrance** [PowerDNS/pdns#10159]
Hello,

We are unable to add records with two stars to make records like *.*.example.net. Like in a previous issue (#3406), we have the message : "{"error": "Name '*.test.example.net.' contains unsupported characters"}".

 - Operating system: Centos 7.9
 - Software version: 4.1.14
 - Software source: epel repo for yum.

Test :
- I put the following in a test.json
`
{
        "rrsets": [
        {
                "name": "*.*.test.example.net.",
                        "type": "CNAME",
                        "ttl": 600,
                        "changetype": "REPLACE",
                        "records": [
                        {
                                "content": "server.domain.com.",
                                "disabled": false
                        }
                        ]
        }
        ]
}
`
- I use the following command
`
curl -X PATCH -k -H 'X-API-Key: ****' --data @/root/test.json https://172.16.98.1/api/v1/servers/localhost/zones/test.example.net
`
- I obtain the error : "{"error": "Name '*.test.example.net.' contains unsupported characters"}"

Thanks

**Comment by vabtNfrance** [comment]
These names are just examples, we have clients who have this need. They use multiples subdomains and by this way they can use preprod and dev "subsubdomain" (example) for each subdomains. Have you another solution to obtain the same result ?

**Comment by Habbie** [comment]
A single `*.` will match multiple subdomain levels.

**Comment by vabtNfrance** [comment]
Thank you for your awnser, we don't know that could works like this.

Have a nice day

**Comment by Habbie** [comment]
have a nice day!
