### ISSUE TITLE
DNSSEC for ALIAS RRs

### ISSUE THREAD

**Issue by klaus-nicat** [PowerDNS/pdns#10150]
- Program: Authoritative
 - Issue type: Bug report

### Short description
The responses of resolved ALIAS records are not signed, even when the zone has DNSSEC enabled.

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.4
 - Software source: self compiled

### Steps to reproduce
1. create zone alias.test
2. sign zone alias.test
3. add a.alias.test A 1.1.1.1
4. add alias.alias.test ALIAS www.rcodezero.at.
5. dig @sec1.rcode0.net a.alias.test +dnssec
```
;; ANSWER SECTION:
a.alias.test.           3600    IN      A       1.1.1.1
a.alias.test.           3600    IN      RRSIG   A 8 3 3600 20210318000000 20210225000000 31995 alias.test. vClNVUW0eNevsGIfMCx6H6ZVFOsjBvHeqzbMy1QT9Y8/8TOJa7qunmIf G+eApf9o9SesUU5PrDrHAFvuQzqrFgOduvGC8R9kRlm3stc3199Nv1C5 akfldZbW2Jn3iB3il0+5cKVTwYoP1267KatTdEslwjuneDmjujsdUOwv aE+kEpLulnUlVLTGVy2nkcrRLWTXIvYaiA9zzaqQpCfLkQ8OxaYDqrW8 ZAlE30ekIT9v0GS+7pM9xluHupqUu6+YMVNSoLn4BZfsf9DTEyw52Msg SJgkkDT2KJZ7RLu6nj3XoFMfx3LDcbiRCPXFwhSK89tE9SQq2tqZi7Ll SntF3w==
```
6. dig @sec1.rcode0.net alias.alias.test +dnssec
```
;; ANSWER SECTION:
alias.alias.test.       300     IN      A       131.130.254.77
```

### Expected behaviour
The resolved and synthesized A record (or AAAA) is fine, but there should also be a RRSIG RR for the A/AAAA record.

### Actual behaviour
RRSIG is missing

### Other information
I think technically there is no reason why not signing the synthesized record.

**Comment by klaus-nicat** [comment]
IIRC the same problem exists for DNAME repsonses

**Comment by Habbie** [comment]
Hi Klaus,

thank you for the reports, however:

> The responses of resolved ALIAS records are not signed, even when the zone has DNSSEC enabled.

Duplicate of #3838.

> IIRC the same problem exists for DNAME repsonses

DNAME-synthesised CNAMEs do not get signatures, this is correct behaviour.

**Comment by Habbie** [comment]
Here's a LUA-based workaround for ALIAS+DNSSEC: https://github.com/PowerDNS/pdns/wiki/Lua-Examples-(Authoritative)#using-lua-to-simulate-cname-like-behaviour-on-the-zone-apex

**Comment by klaus-nicat** [comment]
Thanks. Although I would prefer ALIAS+DNSSEC working out of the box. Is there some technical problem with it, or is it just not implemented.

Regarding the LUA example. I do not understand it: Someone asks www.example.com. PowerDNS follows the CNAME to example.com and finds the LUA records. At this point, what is qname:toString()? Will then LUA resolve www.www.example.com, or www.example.com which sounds like a loop?

**Comment by Habbie** [comment]
> Thanks. Although I would prefer ALIAS+DNSSEC working out of the box.

Yes, that's why it's still open in #3838.

> Is there some technical problem with it, or is it just not implemented.

Just not implemented yet.

> Regarding the LUA example. I do not understand it: Someone asks [www.example.com](http://www.example.com). PowerDNS follows the CNAME to example.com and finds the LUA records. At this point, what is qname:toString()? Will then LUA resolve [www.www.example.com](http://www.www.example.com), or [www.example.com](http://www.example.com) which sounds like a loop?

You're right, the example is broken! I have updated it now.

**Comment by klaus-nicat** [comment]
> Here's a LUA-based workaround for ALIAS+DNSSEC: https://github.com/PowerDNS/pdns/wiki/Lua-Examples-(Authoritative)#using-lua-to-simulate-cname-like-behaviour-on-the-zone-apex

When doing ALIAS resolving with LUA, is this synchronous and blocks the thread until the ALIAS target is resolved?

Answering myself (after testing): Yes, LUA DNS queries are synchronous and block the thread.
