### ISSUE TITLE
Recursive query DS and Trust Anchor.

### ISSUE THREAD

**Issue by brlumen** [PowerDNS/pdns#10166]
- Program: Recursor
 - Issue type: Bug report

### Short description
pdns-recursor ignores the trust anchor when processing an incoming recursive DS query.

### Environment

 - Operating system: Oracle Linux Server release 8.2
 - Software version: PowerDNS Recursor 4.5.0-alpha1
 - Software source: PowerDNS repository

### Steps to reproduce
Default settings, except: 
dnssec=validate

1.  `rec_control add-ta example.com 44030 8 2 D4C3D5552B8679FAEEBC317E5F048B614B2E5F607DC57F1553182D49 AB2179F7`  on powerdns-recursor; 
2. `dig DS example.com. @127.0.0.1`

### Expected behaviour
Powerdns-recursor should return DS from trust anchor.

### Actual behaviour
Powerdns-recursor returns DS from gtld servers.

### Other information
The mechanism for obtaining DS from trust anchor works correctly if it is performed as part of the dnssec validation of a simple A record request. That is, the stage of requesting DS from the parent of the zone is skipped and, apparently, the DS from the trust anchor is used. But if you execute a DS query, the recursor ignores the trust anchor and looks to the zone parent for a DS record.

**Comment by Habbie** [comment]
Hello,

I have to wonder what use a downstream validator would have for the configured TA as DS. It cannot validate it, right?

**Comment by brlumen** [comment]
The problem arises if another recursor acts as a client for powerdns-recursor that performs full forwarding of requests (for example, for bind, this is the forward directive) with dnssec validation enabled.
If he is asked, for example, A example.com, then during the dnssec validation process, he will generate a DS request for example.com, which I wrote about above.
Perhaps I did not correctly give the example using example.com and indicating that the TA is added only for example.com. I understand that using this domain I also need to add a TA for "com". I deliberately skipped this point so as not to overload the issue. Perhaps I should have used a more localized example like zone.local or something similar.

**Comment by Habbie** [comment]
`.local` is reserved for mDNS and cannot be used in DNS.

Can you please tell us about the -actual- setup you have and the -actual- problem you have, with your real configs, and no example domains? Thank you.

**Comment by brlumen** [comment]
I have an internal first level domain "s8." and several domains of the 2nd level, in particular one of them is group.s8. They are located on the powerdns-auth server.

Client requests are served by powerdns-recursor in which forward-zones-file is written which contains the line:
s8 = ip_powerdns-auth

One of the clients of powerdns-recursor is "bind9" with options:
forwarders {ip_powerdns-recursor}
dnssec-enable yes;
dnssec-validation auto;

If you send a request to dig A group.s8. @bind_ip_address +dnssec, then one of the queries will come to powerdns-recursor like DS s8.
The recursor will forward this request to the root servers, and receive an nxdomain response, which is natural, since "s8." does not exist.

Further, if you ask powerdns-recursor "A" for the "s8" record, it will return NXDOMAIN, since this negative answer will be in its cache from the previous stage (DS resolution stage at root servers).
Adding a TA for "s8" does not affect the behavior of the recursor.

Please, if again it is not clear - tell me, I will try to reformulate.

**Comment by Habbie** [comment]
Can you try setting `root-nx-trust=no` on the recursor?

**Comment by brlumen** [comment]
This option does not affect the output.
The only thing I noticed is that if you first ask `A s8` and then `DS s8`, a negative response from DS will no longer affect subsequent requests for `A s8`.
As far as I understand, this behavior was corrected in some release, I don't remember exactly in which one.

**Comment by brlumen** [comment]
That is, a negative response is not cached if there is already a positive response in the cache.

**Comment by brlumen** [comment]
In general, this is an indirect problem, most of all I am worried that I cannot sign the "gray" internal domain, because if dnssec validation occurs on the client, and the client generates DS, powerdns-recursor will not return DS from TA, but will send a request to the root servers on which, naturally, such information will not be.

**Comment by Habbie** [comment]
And, to be clear, your client also has the TA configured?

**Comment by brlumen** [comment]
No, clients only have standard TA for the root zone.

чт, 11 мар. 2021 г., 18:25 Peter van Dijk ***@***.***>:

**Comment by brlumen** [comment]
If the client had TA he would DS the request did not generate.

чт, 11 мар. 2021 г., 18:54 Grigoriy Ermolaev ***@***.***>:

**Comment by Habbie** [comment]
So, the client is validating, but does not have the TA? Then how can it accept data from your 'fake' zone? I'm just trying to understand the full picture here.

**Comment by brlumen** [comment]
Yes, you are right, really not. I did not take into account this fact.

чт, 11 мар. 2021 г., 19:07 Peter van Dijk ***@***.***>:

**Comment by Habbie** [comment]
Ok - so what does that leave us with? What is the problematic situation that we can help with?

**Comment by brlumen** [comment]
How can I resist accidental or intentional DS requests?

**Comment by brlumen** [comment]
Yes, I said that cache corruption is not so important, in light of a more significant problem, as at that time I thought the problem, but still?

**Comment by Habbie** [comment]
This looks like a support question now, so I'm closing this. Please read the following:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
