### ISSUE TITLE
rec: improve trace log time stamps

### ISSUE THREAD

**Issue by yantarou** [PowerDNS/pdns#10188]
- Program: Recursor
 - Issue type: Feature request

### Short description
Improve trace log time stamps.

### Usecase
Debugging failed queries.

### Description
Below an excerpt from a trace log:

2021-03-18T12:48:29.759398+08:00 [358534] ns2.opentransfer.com: Trying IP 98.130.253.226:53, asking 'ns2.opentransfer.com|A'
2021-03-18T12:48:29.759398+08:00 [358534] ns2.opentransfer.com: timeout resolving after 1504.94msec

It's a bit confusing that these two lines have the same timestamp, althogh 1.5 seconds passed between the events.

Would be great to have the real timestamp for each log message.

**Comment by pieterlexis** [comment]
@cmouse mentioned that we could also store a start timestamp and stamp each logline with the time delta from that start timestamp

**Comment by omoerbeek** [comment]
#9503 solves this iirc

**Comment by omoerbeek** [comment]
I think at least for the case where the timestamps are added by the application it is ok with that PR.

**Comment by pieterlexis** [comment]
yes, but the timestamps are added when we send the whole trace through the logger, so each line is timestamped with the time when the full trace was sent to the logger, not when the trace line occured

**Comment by yantarou** [comment]
Yes, I think you are right Pieter.

The timestamps in my example most likely come from rsyslog, and not from PowerDNS.

Having a delta timestamp prepended to the actual log message would be awesome. Actually even better than the full time, so that there is no need to mentally calculate how long each step took.

Most important is to avoid confusion.
(I was confused, but now I understand how it works.)

**Comment by omoerbeek** [comment]
AFAIKR, I changed that in the PR. But it might be wishful thinking.

**Comment by pieterlexis** [comment]
[here](https://github.com/PowerDNS/pdns/blob/336994c78abaf20eafe3fe0bb91f31ddf2657f82/pdns/pdns_recursor.cc#L1824-L1832) is where we send the trace to logger. The logger adds the timestamps.

the `LOG` macro doesn't do any timestamping and just writes to `d_trace` (an `std::ostringstream`), so no timestamp of when the actual message was sent is stored. #9503 doesn't address this.

**Comment by omoerbeek** [comment]
You are right. I know for sure I played with some code to change this (by remembering a timestamp for each line to be formatted later when writing the log) but it seems I never committed that code. Likely because I was not happy with it after all.

**Comment by omoerbeek** [comment]
Will be solved by structured logging code in the future.
