### ISSUE TITLE
pdnsutil bash_completion missing zones

### ISSUE THREAD

**Issue by eth-man** [PowerDNS/pdns#10191]
- Program: pdnsutil
 - Issue type: Bug report

### Short description
looks like pdnsutil missing the last zone with tab completions

### Environment
 - Operating system:  Ubuntu 18.04.5 LTS
 - Software version: pdnsutil 4.1.1
 - Software source: ubuntu repo

### Expected behavior
latest zone line showing with: pdnsutil list-all-zones but not with pdnsustil edit-zone \TAB\

**Comment by Habbie** [comment]
Hello! A few questions and notes:

1. pdns 4.1.1 is end of life. You can grab a newer version from https://repo.powerdns.com/
2. how did you install bash completion for pdnsutil? Ubuntu's package does not contain it.

**Comment by eth-man** [comment]
thanks , I will try it out
I'm not sure about the autocomplete maybe its already included :)
