### ISSUE TITLE
PowerDNS does not log unknown domains (any more)

### ISSUE THREAD

**Issue by Henniegl** [PowerDNS/pdns#1020]
In the past PowerDNS would log requests for unknown domains, since around two years it no longer does.
Please restore this possibility.

More details at http://powerdns.13854.n7.nabble.com/PowerDNS-3-1-does-not-log-quot-not-authoritative-for-quot-messages-td10333.html

**Comment by omoerbeek** [comment]
We did not have anybody requesting this for several years. Please re-open if you have a valid use-case.
