### ISSUE TITLE
4.1.14 to 4.2.3 - Failed to start PDNS Server

### ISSUE THREAD

**Issue by clusterx** [PowerDNS/pdns#10203]
upgraded from 4.1.14 to 4.2.3
pdns-backend-mysql
pdns-server

The following NEW packages will be installed:
pdns-backend-bind

I only use pdns-backend-mysql pdns-server with gmysql as backend, allow-axfr is set to linode's NS slave service

cat /etc/powerdns/pdns.d/pdns.local.gmysql.conf
launch=gmysql
gmysql-host=localhost
gmysql-dbname=xxxxxxxx
gmysql-user=xxxxxxxxx
gmysql-password=xxxxxxxxx

a new config file was created /etc/powerdns/pdns.d/bind.conf
and I had to delete bind.conf

Failed to start PowerDNS Authoritative Server
rm /etc/powerdns/pdns.d/bind.conf

I have also found following error messages after the upgrade
[code]
Fatal error: Trying to set unknown parameter 'disable-tcp'
Fatal error: Trying to set unknown parameter 'api-logfile'
[/code]

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
