### ISSUE TITLE
auth api: honor PUBLISH-CDS in response of /cryptokeys endpoint

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#10215]
- Program: Authoritative
 - Issue type: Feature request

### Short description
The `ds` JSON field of each key returned by the `/servers/{server_id}/zones/{zone_id}/cryptokeys` endpoint should honor the hash algorithms given by `PUBLISH-CDS` (or `default-publish-cds`).

### Usecase
Typically, the `ds` entries given in the JSON response are conveyed to the registry (for initial DNSSEC bootstrapping). As such, the returned hash algorithms can be expected to be the same as the ones in CDS records (for later key transitions).

We return the `ds` entries to our users, and don't want to return algorithm 1. We therefore have set `default-publish-cds=2,4` (which works for CDS), but we have to do manual filtering in our application when conveying the initial DS RRset.

### Description
See above. - I was unsure if this could be considered a bug, but I decided against file it as such.

Note that one could argue that `ds` should be renamed to `cds` if `PUBLISH-CDS` is honored. I would oppose that change, and instead take the algorithm list of `PUBLISH-CDS` to mean "list of hash algorithms that should get promoted into the DS RRset eventually". For the initial DS RRset (when bootstrapping the delegation), it would then be fair to honor this setting without renaming the field in the JSON schema.

**Comment by Habbie** [comment]
Hi Peter, we don't want to change the semantics of the API based on a mostly unrelated setting. A backwards compatible change would be to -add- `"cds"` to the API response, would that work for you?

**Comment by peterthomassen** [comment]
sure!

**Comment by peterthomassen** [comment]
or alternatively, one could add a boolean `api-ds-like-cds`, but at first sight that seems complicated (code-wise and conceptually) to me.

**Comment by Habbie** [comment]
> or alternatively, one could add a boolean `api-ds-like-cds`, but at first sight that seems complicated (code-wise and conceptually) to me.

I also pondered that but it does not feel like the right choice.

**Comment by peterthomassen** [comment]
btw, if we did what I proposed initially (change the behavior of `ds`), I wouldn't consider that a breaking change, especially on the transition from 4.x to 4.x+1. It is nowhere guaranteed which algorithms will be returned (as far as I can see). Also, if another hash algorithm becomes the recommended, would you not add it?

I also believe that an algorithm was removed in the past (GOST).

Just sharing my thoughts to help find the best solution. (Adding a data field adds complexity, so it's a trade-off and not automatically the best solution.) However, anything works for us (including not doing anything about this).

**Comment by Habbie** [comment]
> I also believe that an algorithm was removed in the past (GOST).

For build reasons, most people already did not have it. My feeling is that `"ds"` should be as complete as possible, without guessing at any intent.

**Comment by Habbie** [comment]
#10217
