### ISSUE TITLE
dnsdist: Get answers by LuaResponseAction()

### ISSUE THREAD

**Issue by 409567102** [PowerDNS/pdns#10235]
- Program: dnsdist
- Issue type: Feature request

**Short description**
In some cases need handle DNS Response answers(type A addr, type CNAME cname)  by LuaResponseAction().
Is there any way I don't know to get the answers in the server？

**Environment**
- Operating system: Debian 10.6
- Software version: dnsdist 1.5.1-1pdns.focal
- Software source: PowerDNS repo

**Comment by rgacogne** [comment]
I'm afraid you would have to parse the content of the response in Lua, as dnsdist does not know how to decode DNS record content. The packet starts at `DNSResponse.dh` and is `DNSResponse.len` bytes long.

**Comment by 409567102** [comment]
> I'm afraid you would have to parse the content of the response in Lua, as dnsdist does not know how to decode DNS record content. The packet starts at `DNSResponse.dh` and is `DNSResponse.len` bytes long.

OK,Got it
