### ISSUE TITLE
recursor gets in trouble when v4 and v6 for nameservers have different TTL and v6 is down

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#1024]
If the recursor caches both A and AAAA for a nameserver, and the A expires, and the AAAA is not actually reachable, it will not recover for that specific nameserver until the AAAA also expires.

This does not happen a lot in practice, but it is a nuisance. This issue was not present in 3.5-3.5.2 but it reappeared in 3.5.3 due to our usage of ANY to query both remote servers and the internal cache.

**Comment by Habbie** [comment]
Extended to rec-4.2.0 because we have not heard any operational complaints about this for a long time.

**Comment by omoerbeek** [comment]
We believe this has been solved. Re-open if there is evidence it is not.
