### ISSUE TITLE
lua script cause recursor crash

### ISSUE THREAD

**Issue by eldzee** [PowerDNS/pdns#10247]
- Program:  Recursor
 - Issue type: Bug report

### Short description

Recursor crash when accessing appliedPolicy.* during preoutquery in lua script

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.4.2
 - Software source: PowerDNS repository

### Steps to reproduce

1. make lua script, access dq.appliedPolicy.* during preoutquery, for example I tried to access the policyType
```
function dbg(msg)
        pdnslog(msg, pdns.loglevels.Debug)
end
function preresolve(dq)
        dbg("preresolve "..dq.qname:toString().." pol: "..dq.appliedPolicy.policyType)
        return false
end
function prerpz(dq)
        dbg("prerpz "..dq.qname:toString().." pol: "..dq.appliedPolicy.policyType)
        return false
end
function preoutquery(dq)
        dbg("preoutquery "..dq.qname:toString().. " pol: "..dq.appliedPolicy.policyType)
        return false
end
function postresolve(dq)
        dbg("preresolve "..dq.qname:toString().." pol: "..dq.appliedPolicy.policyType)
        return false
end
```

### Expected behaviour

doesn't crash
```
pdns_recursor[110116]: 3 [2/1] question for 'example.com|A' from 127.0.0.1:57388
pdns_recursor[110116]: prerpz example.com. pol: 0
pdns_recursor[110116]: preresolve example.com. pol: 0
pdns_recursor[110116]: preoutquery example.com. pol: 0
pdns_recursor[110116]: postresolve example.com. pol: 0
pdns_recursor[110116]: 3 [2/1] answer to question 'example.com|A': 1 answers, 1 additional, took 3 packets, 1922.56 netw ms, 1923.42 tot ms, 0 throttled, 1 timeouts, 0 tcp connections, rcode=
```

### Actual behaviour

program crash, respawned with different PID
```
pdns_recursor[110116]: 3 [3/1] question for 'example.com|A' from 127.0.0.1:38809
pdns_recursor[110116]: prerpz example.com. pol: 0
pdns_recursor[110116]: preresolve example.com. pol: 0
pdns_recursor[110205]: PowerDNS Recursor 4.4.2 (C) 2001-2020 PowerDNS.COM BV
pdns_recursor[110205]: Using 64-bits mode. Built using gcc 9.3.0 on Dec 11 2020 16:06:23 by root@13df42ca5baa.
pdns_recursor[110205]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
...
```

**Comment by rgacogne** [comment]
It's likely that `dq.appliedPolicy` is `nil`, one fix would be to check for that before accessing its members. We could overwrite all the Lua bindings for `DNSFilterEngine` members to check for a `nullptr`, I guess. We've had the same kind of issues in dnsdist and ended up doing that because users kept encountering that issue.

**Comment by omoerbeek** [comment]
What I find a bit puzzling is that accessing `dq.appliedPolicy` in the earlier interception functions did not crash according to the log.

**Comment by rgacogne** [comment]
`preoutquery` has a "fake" `DNSQuestion` object, I'm guessing that's the only place where `appliedPolicy` is a `nullptr`.
