### ISSUE TITLE
auth: attodot breaks presigned zones with @ in SOA

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#10254]
A user had a zone containing something like:

```
7bits.nl.		300	IN	SOA	lorentz.7bits.nl. hostmaster\@7bits.nl. 129 600 3600 604800 3600
```

plus an RRSIG over that. They loaded this zone into PowerDNS, as presigned. PowerDNS served it, and helpfully converted `\@` to `.`, making the RRSIG invalid.

We should either drop the `attodot` feature or make it smarter.

**Comment by RobinGeuze** [comment]
According to RFC1035: "A free standing @ is used to denote the current origin.". I would interpret this as only an @ with whitespace around it should be converted.

**Comment by Habbie** [comment]
Yes, agreed. `attodot` is only used for the SOA hostmaster field anyway.
