### ISSUE TITLE
[dnsdist] method getEDNSOptions on DNSResponse is nil

### ISSUE THREAD

**Issue by leshow** [PowerDNS/pdns#10262]
- Program:  dnsdist
 - Issue type: Bug report

### Short description
calling `getEDNSOptions()` in:

```
function response(dr)
    opts = dr:getEDNSOptions()
    return DNSResponseAction.None
end
addResponseAction(AllRule(), LuaResponseAction(response))
```

### Environment
 - Operating system: linux 5.11
 - Software version: dnsdist 1.5.1
 - Software source: aur https://aur.archlinux.org/packages/dnsdist/

### Steps to reproduce
put the above in a dnsdist.conf, start with:
```
dnsdist -l 127.0.0.1:1953 1.1.1.1 --config dnsdist.conf
```
in another terminal query:
```
dig @127.0.0.1 -p 1953 google.com 
// +noedns or not will not make a difference here
```
dnsdist will output
```
Marking downstream 1.1.1.1:53 as 'up'
> Polled security status of version 1.5.1 at startup, no known issues reported: OK
LuaResponseAction failed inside Lua, returning ServFail: [string "chunk"]:12: attempt to call method 'getEDNSOptions' (a nil value)
```

### Expected behaviour
`getEDNSOptions` should be callable and return a table of `EDNSOptionsView`

### Actual behaviour
the method does not appear to exist

### Other information
The docs say a `DNSResponse` "has all functions and members of `DNSQuestion`" and this method is available on `DNSQuestion` https://dnsdist.org/reference/dq.html#dnsresponse-object

Bit of a tangent here but, is it possible to mutate edns of a query through `getEDNSOption`? I'm not that familiar with lua but I'd like to add something to the opt section in this function

**Comment by rgacogne** [comment]
We are once again bitten by `LuaWrapper` not supporting inheritance. I'll add the binding for the `DNSResponse` object as well.

> Bit of a tangent here but, is it possible to mutate edns of a query through getEDNSOption? I'm not that familiar with lua but I'd like to add something to the opt section in this function

No, you will need to parse and edit the raw data using `Lua` if you want to edit the content of the response.
