### ISSUE TITLE
Memory  Leak in BackendMakers().report(new *)

### ISSUE THREAD

**Issue by 0x34d** [PowerDNS/pdns#10261]
- Program: pdnsutil
 - Issue type: Bug report {Memory Leak}

### Short description
Running pdnsutil Under valgrind Debugger Show up Memory Leak

### Environment
 - Operating system: Mint
 - Software version:  Git Live
 - Software source: https://github.com/PowerDNS/pdns

### Steps to reproduce
1. ./configure
2. make
3. valgrind --leak-check=full ./pdnsutil

### Expected behaviour
==201783== 
==201783== HEAP SUMMARY:
==201783==     in use at exit: 152 bytes in 3 blocks
==201783==   total heap usage: 4,618 allocs, 4,615 frees, 1,671,993 bytes allocated
==201783== 
==201783== 40 bytes in 1 blocks are definitely lost in loss record 1 of 3
==201783==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==201783==    by 0xF52F80: Bind2Loader::Bind2Loader() (bindbackend2.cc:1495)
==201783==    by 0xF4FBAE: __static_initialization_and_destruction_0(int, int) (bindbackend2.cc:1506)
==201783==    by 0xF4FBDA: _GLOBAL__sub_I_bindbackend2.cc (bindbackend2.cc:1506)
==201783==    by 0xF9883C: __libc_csu_init (in /home/x34d/Desktop/pdns/pdns/pdnsutil)
==201783==    by 0x56D603F: (below main) (libc-start.c:264)
==201783== 
==201783== 40 bytes in 1 blocks are definitely lost in loss record 2 of 3
==201783==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==201783==    by 0xF80320: RandomLoader::RandomLoader() (randombackend.cc:130)
==201783==    by 0xF7F04E: __static_initialization_and_destruction_0(int, int) (randombackend.cc:139)
==201783==    by 0xF7F07A: _GLOBAL__sub_I_randombackend.cc (randombackend.cc:139)
==201783==    by 0xF9883C: __libc_csu_init (in /home/x34d/Desktop/pdns/pdns/pdnsutil)
==201783==    by 0x56D603F: (below main) (libc-start.c:264)
==201783== 
==201783== 72 bytes in 1 blocks are definitely lost in loss record 3 of 3
==201783==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==201783==    by 0xF75FDA: gMySQLLoader::gMySQLLoader() (gmysqlbackend.cc:182)
==201783==    by 0xF6BD5D: __static_initialization_and_destruction_0(int, int) (gmysqlbackend.cc:190)
==201783==    by 0xF6BD89: _GLOBAL__sub_I_gmysqlbackend.cc (gmysqlbackend.cc:190)
==201783==    by 0xF9883C: __libc_csu_init (in /home/x34d/Desktop/pdns/pdns/pdnsutil)
==201783==    by 0x56D603F: (below main) (libc-start.c:264)
==201783== 
==201783== LEAK SUMMARY:
==201783==    definitely lost: 152 bytes in 3 blocks
==201783==    indirectly lost: 0 bytes in 0 blocks
==201783==      possibly lost: 0 bytes in 0 blocks
==201783==    still reachable: 0 bytes in 0 blocks
==201783==         suppressed: 0 bytes in 0 blocks
==201783== 
==201783== For lists of detected and suppressed errors, rerun with: -s
==201783== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)

### Other information
Application Leak Memory While Calling 
BackendMakers().report(new *)

Possibly : BackendMakers().report() Function has Leak Memory

It's Not a Security Bug !

**Comment by Habbie** [comment]
Thanks for the report! Because this only happens once at startup, we do not consider it an important leak. The `pdns.supp` and `.valgrindrc` in the git root (so one dir up from where you tested) suppress this one.

So I'm closing this. Thank you again.
