### ISSUE TITLE
Set the `query_address` field of Dnstap messages

### ISSUE THREAD

**Issue by hasei** [PowerDNS/pdns#10265]
- Program:  Recursor
 - Issue type: Feature request

### Short description

Set the `query_address` field of Dnstap log messages.

### Usecase
When receiving Dnstap log messages from more than one recursor, you can identify them by their IP addresses. If you have a direct TCP connection between recursor and log receiver, the recursor IP address is available as source address of the connection.

In our setup we have an intermediary system that we do not control that relays those message to us. Due to that setup, we cannot simply take the recursor IP addresses from the TCP connections since we just see the one from the intermediary system. That makes us unable to identify the different recursors since the Dnstap message itself does not contain such information and we rely on the IP address for identification.

### Description

The `query_address` field of a Dnstap log message identifies the questioning instance in form of its IP address and should be set in order to provide that information to the log receiver.

**Comment by omoerbeek** [comment]
Maybe, ss a workaround (and if you control the source generating the dnstap message), you can set set `server-id`. The value will be filled in as the `identity` field in the dnstap message.

**Comment by hasei** [comment]
Thanks, that can work as a workaround.

Since we identify by IP address, I need to add some glue to map `server-id` to IP and maintain that mapping table.  Still, having the recursor IP address in the Dnstap message is the favored (long term) solution and would be highly appreciated.
