### ISSUE TITLE
Compile error on MacOS 10.15.7 for recursor

### ISSUE THREAD

**Issue by zhangshanfen9** [PowerDNS/pdns#10270]
- Program: Recursor 
 - Issue type: Bug report

### Short description

Error while making.
```
  CXXLD    pdns_recursor
Undefined symbols for architecture x86_64:
  "MOADNSParser::init(bool, std::__1::basic_string_view<char, std::__1::char_traits<char> > const&)", referenced from:
      AXFRRetriever::getChunk(std::__1::vector<DNSResourceRecord, std::__1::allocator<DNSResourceRecord> >&, std::__1::vector<DNSRecord, std::__1::allocator<DNSRecord> >*, unsigned short) in axfr-retriever.o
      MOADNSParser::MOADNSParser(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ixfr.o
      MOADNSParser::MOADNSParser(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in pdns_recursor.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pdns_recursor] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

### Environment

 - Operating system: MacOS 10.15.7
 - Software version: Latest
 - Software source: PowerDNS repository, compiled yourself

### Steps to reproduce

1. `cd pdns/pdns/recursordist/`
2. `autoreconf -vi`
2. `./configure --with-modules="" --disable-lua-records --with-libcrypto=/usr/local/Cellar/openssl@1.1/1.1.1h CFLAGS="-g -O0"`
3.  `make -j 32`

### Expected behaviour

Compile successfully
### Actual behaviour

Compile error

**Comment by omoerbeek** [comment]
1) You are using a pdns auth configure line for the recursor
2) MacOS is not a actively supported platform
3) A missing `std::string_view` suggests you are using an too old C++ version, but your report lacks the configure output
5) I do compile our tree on MacOS Intel (Big Sur) once in a while, using some `brew` installed libraries and tools with the following configure setup:
```
export CC=clang
export CXX=clang++
export CXXFLAGS="-Wno-unused-command-line-argument"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
./configure --enable-unit-tests
```
6) I'm closing this issue because of 2).
