### ISSUE TITLE
auth: rfc2136handler allows adding CDS/CDNSKEY when direct-dnskey=no

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#10321]
- Program: Authoritative
 - Issue type: Bug report

### Short description
https://github.com/PowerDNS/pdns/blob/master/pdns/rfc2136handler.cc#L102 checks for DNSKEY, but not for CDS/CDNSKEY

### Environment
n/a

### Steps to reproduce
n/a

### Expected behaviour
When direct-dnskey=no (and not presigned), rfc2136handler should not accept CDS/CDNSKEY records

### Actual behaviour
CDS/CDNSKEY records are accepted, only DNSKEY is rejected

**Comment by Habbie** [comment]
#10514 expands the filter. Alternatively, we could remove the filter. Thoughts?

**Comment by peterthomassen** [comment]
I would find it unintuitive to accept such records if direct-dnskey=no.

In the case of accepting them, how would you describe the meaning of the direct-dnskey flag?

**Comment by Habbie** [comment]
That still leaves `direct-dnskey` as influencing whether or not they are served.

**Comment by Habbie** [comment]
> I would find it unintuitive to accept such records if direct-dnskey=no.

I can follow that. I also realised that the current code silently ignores the additions, which I also don't think is intuitive.

**Comment by peterthomassen** [comment]
hm, indifferent. IIRC, the API accepts them even if the flag is off, right? In that case, consistency may be a good idea.

**Comment by Habbie** [comment]
> hm, indifferent. IIRC, the API accepts them even if the flag is off, right? In that case, consistency may be a good idea.

Indeed, the API does not check at all. I'll remove the check.

**Comment by peterthomassen** [comment]
Consistency works both ways :-p
