### ISSUE TITLE
Client responses created by `DNSAction.Spoof` are not logged by `DnstapLogResponseAction`

### ISSUE THREAD

**Issue by flintinatux** [PowerDNS/pdns#10331]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

Client responses created by `DNSAction.Spoof` are not logged by `DnstapLogResponseAction`.

### Environment

 - Operating system:  Debian Buster
 - Software version: 1.6.0-rc1
 - Software source: PowerDNS repository 

### Steps to reproduce

1.  Include the following (or similar) in your `dnsdist.conf`.  (I simplified it to just what's needed to repro.)
```lua
local dnstap = newFrameStreamTcpLogger('127.0.0.1:8053')
addAction(AllRule(), DnstapLogAction('dnsdist', dnstap))
addResponseAction(AllRule(), DnstapLogResponseAction('dnsdist', dnstap))

local hosts = { ['example.com.'] = '0.0.0.0' }

local spoofHosts = function (response)
  local ip = hosts[response.qname:toString()]

  if ip then
    return DNSAction.Spoof, ip
  else
    return DNSAction.None
  end
end

addAction(AllRule(), LuaAction(spoofHosts))
```
2.  Make a DNS request for `example.com` (or some other domain in the `hosts` table.

### Expected behaviour

The `CLIENT_QUERY` and `CLIENT_RESPONSE` should **BOTH** be logged via `dnstap`.

### Actual behaviour

The `CLIENT_RESPONSE` is **NOT** logged via `dnstap`.  Only the `CLIENT_QUERY` is logged.

### Other information

The only work-around I can think of is to run two instances of `dnsdist`.  One to act as the entrypoint and do `dnstap` logging, forwarding on to a second that does the spoofing.  Because forwarded requests are all logged correctly.  I'm open to other suggestions or work-arounds, but the issue above was unexpected, so it still feels like a bug to me.

**Comment by rgacogne** [comment]
Rules added via `addResponseRule()` are only applied to responses sent by a backend. If you want to match responses generated by dnsdist, you can use `addSelfAnsweredResponseAction` [1] instead:

```
addSelfAnsweredResponseAction(AllRule(), DnstapLogResponseAction('dnsdist', dnstap))
```

[1]: https://dnsdist.org/rules-actions.html#addSelfAnsweredResponseAction

**Comment by flintinatux** [comment]
That worked!  I'm so glad I asked.  Apparently I missed that entire section of the docs.  Closing this, because...
> "It's not a bug.  It's a feature!"  :wink:
