### ISSUE TITLE
auth: lua records - default timeout for ifportup and ifurlup is not 2s like said in the documentation

### ISSUE THREAD

**Issue by dmachard** [PowerDNS/pdns#10357]
- Program: Authoritative
 - Issue type: Bug report

### Environment
 - Software version: powerdns/pdns-auth-44
 
### Short description

The default timeout  for  ifportup and ifurlup functions is not 2 seconds like said in the [documentation ](https://doc.powerdns.com/authoritative/lua-records/functions.html#ifportup) but 1s.
=> timeout: Maximum time in seconds that you allow the check to take (**default 2**)

After take a look to the code source, the default value is 1s when the timeout is not provided (and also confirmed with some tests)
- https://github.com/PowerDNS/pdns/blob/master/pdns/lua-record.cc#L92
- https://github.com/PowerDNS/pdns/blob/master/pdns/lua-record.cc#L126

I can make a PR to fix the documentation or change the default value to 2 in code source
What is the good default value for you ?

Denis

**Comment by mnordhoff** [comment]
`pdns/minicurl.hh` _does_ use `2`, though.

**Comment by dmachard** [comment]
I agree but if my understanding is correct, the default value `2` is overwrited respectively in the function `checkURL` and `checkTCP` in `pdns/lua-record.cc`.

**Comment by rgacogne** [comment]
Looks that way indeed. I guess it's better to update the documentation than risk breaking existing setups, but let's see if @Habbie has an opinion :)

**Comment by Habbie** [comment]
Bumping the default in the code to 2s, and adding an note to upgrading.rst, seems right to me. Thanks!
