### ISSUE TITLE
Problem with add/edit records in a zone 

### ISSUE THREAD

**Issue by sdebarun** [PowerDNS/pdns#10354]
Hi,
Seeing this https://github.com/PowerDNS/pdns/issues/7745, I am trying to add a txt record in a zone. I am also following the documentation here https://doc.powerdns.com/authoritative/http-api/zone.html#zone-endpoints. BUt this does not work for me. since there is no example I am trying to figure it out myself. So my patch request is going here : api/v1/servers/localhost/zones/test.myzone.test. with json body
```
{
    "rrsests" :[
    {
                "changetype" : "REPLACE",
                "name" : "bimi1.dist.notamiq.dev",
                "type" : "TXT",
                "records" :[{
                    "content" : "v=BIMI1; l=https://app.notamiq.dev/asset-image-pub/OQ-NDE-MzY; a=self;",
                    "disabled" : false
                }]
    }
    ]
}
```

but it says an error `{
    "error": "No rrsets given in update request"
}`

Please help me with the problem or provide me some examples so that I can follow. 
I am using Postman to learn to use the api.

**Comment by mnordhoff** [comment]
I'm not sure what the correct JSON is supposed to be, but what you pasted says "rrsests", not "rrsets".

If that's not it, can you repost this question in the IRC channel or mailing list? https://www.powerdns.com/opensource.html

**Comment by sdebarun** [comment]
Ah!! My mistake and a silly one. I have updated the spelling but now it says     "error": "DNS Name 'test1.test.myzone.test' is not canonical"

**Comment by mnordhoff** [comment]
It might require a trailing . in the name.

But please take this conversation to one of the support channels.

**Comment by sdebarun** [comment]
where is that? please direct me .
Thanks ,

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
