### ISSUE TITLE
dnsdist - Unable to modify qname in LuaAction

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/pdns#10358]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Attempting to modify the DNS query in a LuaAction results in no changes
In order to facilitate migration from our on-site Spamhaus rbldnsd to the DQS service, we need to rewrite queries to use a different domain.  This is being attempted by using a dnsdist LuaAction, but the Lua fails when trying to write back to the qname attribute.

### Environment

 - Operating system: linux
 - Software version:  dnsdist-1.5.1-1pdns.el7.x86_64
 - Software source: repo

### Steps to reproduce
Using configuration file:
```
function redirectDQS( q )
  local s = q.qname:toString()
  warnlog("Old name is " .. s )
  s = s:gsub( 'spamhaus', 'ourlicensekeygoesinhere.sbl-xbl.dq.spamhaus.net' )
  warnlog("new name is " .. s )
  q.qname = newDNSName(s)
  warnlog("New query is " .. q.qname:toString() )
  return DNSAction.Allow
end
addAction("spamhaus.",LuaAction(redirectDQS))
topRule()
```
Running `dig @localhost 2.0.0.127.spamhaus.` should result in the query being rewritten to use DQS and give a 127.0.0.2 reply.

### Expected behaviour
Expect to get a 127.0.0.2 reply from the DQS service

### Actual behaviour
NXDOMAIN response, as query not rewritten, and logs show:
```
May  4 23:43:54 ausmta02 dnsdist[21359]: Old name is 2.0.0.127.spamhaus.
May  4 23:43:54 ausmta02 dnsdist[21359]: new name is 2.0.0.127.ourspamhauslicensekey.sbl-xbl.dq.spamhaus.net.
May  4 23:43:54 ausmta02 dnsdist[21359]: New query is 2.0.0.127.spamhaus.
```

### Other information
Note that I've sanitised the logs above by removing the license key.
Is there a different way this should be done?

**Comment by phonedph1** [comment]
This is a support question really but I will answer anyways.

You can do this in recursor by setting a CNAME answer and then triggering a `followCNAMERecords`

Look at https://docs.powerdns.com/recursor/lua-scripting/hooks.html and an example like

```        
if malwareset:check(dq.qname) then
		dq:addAnswer(pdns.CNAME, "xs.powerdns.com.")
        	dq.rcode = 0
        	dq.followupFunction="followCNAMERecords"    -- this makes PowerDNS lookup your CNAME
        	return true;
end   
```

You would do a preresolvehook(dq) and if it matches your spamhaus add a CNAME answer of the 'new' name (s = s:gsub( 'spamhaus', 'ourlicensekeygoesinhere.sbl-xbl.dq.spamhaus.net' )), which the recursor would then follow. This will 'leak' your key to the thing doing the queries but that might be fine in your case.

Join us back in IRC if you need further help as this will probably be closed.

**Comment by rgacogne** [comment]
Closing as changing the `qname` is indeed not supported by dnsdist. Please turn that into a feature request if needed, but I'm afraid we will probably not support that feature soon.
