### ISSUE TITLE
How to record requests dropped by the backend DNSserver.

### ISSUE THREAD

**Issue by DengLZ** [PowerDNS/pdns#10363]
![image](https://user-images.githubusercontent.com/9841643/117251223-f08bcd80-ae76-11eb-8d74-dc2310a93a99.png)

------- Ways to add logs
addAction(AllRule(),LogAction("/var/log/dnsdist/dnsdist_query.log",false,false,false,false,true))
addResponseAction(AllRule(),LogResponseAction("/var/log/dnsdist/dnsdist_response.log",false,false,false,true))
--------

There is no record of drop in this log /var/log/dnsdist/dnsdist_response.log.
I want to record these dropped requests. What should I do?

**Comment by rgacogne** [comment]
I'm afraid this is not supported in dnsdist. Please open a feature request (or convert that issue into one, but then please respect the template that you removed) if needed.

**Comment by DengLZ** [comment]
Can I find the reason for the dorp request through other methods?
I want to know why these requests were dropped.

**Comment by rgacogne** [comment]
If you have very low traffic, which seems to be the case, you could have a look at `grepq("10000ms")` using the console. It will show you the queries that were answered in 10s or more, with `T.O` as latency for the ones that you are looking for.
Note that it will only tell you that the backend did not respond to these queries. Why it did not is something you will have to investigate on the backend.

**Comment by rgacogne** [comment]
I'm closing this since it now looks like a support question and our GitHub issue tracker is for bug reports and feature requests.  Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

**Comment by DengLZ** [comment]
ok.  thank you very much
