### ISSUE TITLE
Searching via API gives Internal Server Error

### ISSUE THREAD

**Issue by steschuser** [PowerDNS/pdns#10369]
- Program: Authoritative, 
 - Issue type: Bug report

### Short description
A call to /search-data fails with Internal Server Error

### Environment

 - Operating system: Debian GNU/Linux 10 (buster)
 - Software version: pdns-server                          4.1.6-3+deb10u1 
 - Software source: apt 
 -  MySQL: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Steps to reproduce
1. curl  -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/search-data?q=foo

### Expected behaviour
Get some search results

### Actual behaviour
Internal Server Errorr

### Other information
I switched loglevel to Info and get the following Information
`May 07 11:48:52 db01 pdns_server[26857]: gmysql Connection successful. Connected to database 'pdns' on 'localhost'.
May 07 11:48:52 db01 pdns_server[26857]: HTTP ISE for "/api/v1/servers/localhost/search-data": Exception: GSQLBackend unable to execute query: Could not get next result from mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE name LIKE ? OR content LIKE ? LIMIT ?: Commands out of sync; you can't run this command now
`

The query works fine with mysql
`# mysql pdns -e 'SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE name LIKE "%" OR content LIKE "%" LIMIT 10' | wc -l
11
`

Can I provide additional Information ?
Thanks in advance for taking a look...

**Comment by zeha** [comment]
This is probably caused by some other, earlier operation. Many such bug fixes went into the code since 4.1.6. Can you try a newer version, possibly from repo.powerdns.com?

**Comment by steschuser** [comment]
I can certainly try.
Do you recommend the master branch or is 4.4 the last stable ?

Thx for you time

**Comment by zeha** [comment]
> Do you recommend the master branch or is 4.4 the last stable ?

4.4.x is the current stable branch.

**Comment by steschuser** [comment]
works in 4.4.x

thanks again
