### ISSUE TITLE
dnsdist: Error while parsing a NOTIFY query when useClientSubnet=true is set

### ISSUE THREAD

**Issue by slowr** [PowerDNS/pdns#10409]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

Basically as stated in the title. I have a server that has `useClientSubnet=true` and whenever it receives a NOTIFY message it errors out and drops the query.

The exception message is this and it's similar for TCP/UDP:
```
Got an error while parsing a UDP query from 127.0.0.1:34963, id 19538: slowRewriteQueryWithExistingEDNS() should not be called for queries that have no EDNS
```

### Environment

 - Operating system: Ubuntu 20.04 Linux
 - Software version: commit 69eddfc8e07143912448b989da79231cbb5ad27e (Tue May 11 15:25:08 2021 +0200)
 - Software source: Compiled myself

### Steps to reproduce

1. Run dnsdist with a server with the following configuration:
```
newServer({
  address="127.0.0.1:5300",
  useClientSubnet=true,
})
setLocal("0.0.0.0:5300")
setACL({"0.0.0.0/0", "::/0"})
```
2. Trigger a DNS server to send a NOTIFY message 

### Expected behaviour

dnsdist should parse NOTIFY message, append insert the ECS option and forward to the server

### Actual behaviour

drops the packet when a NOTIFY is received with the exception message provided above

### Other information

The issue comes from this check in the code
https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdist-ecs.cc#L587

It seems that the code falsely think that the incoming packet has a EDNS header and fails in the `slowRewriteQueryWithExistingEDNS` function.

**Comment by slowr** [comment]
This check feels very weird to me.
```
if (ntohs(dh->ancount) != 0 || ntohs(dh->nscount) != 0 || (ntohs(dh->arcount) != 0 && ntohs(dh->arcount) != 1)) {
```

I think it needs to be an `&&` when checking towards the `arcount`?

**Comment by rgacogne** [comment]
Introduced in f8a01c441b4dda0288800ab6ed5e475111219e94.
