### ISSUE TITLE
Please start building Debian bullseye packages

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#10406]
- Program: Authoritative + Recursor + dnsdist
 - Issue type: Feature request

### Short description
Please start building packages for Debian bullseye. I expect it to be "around the corner".

### Usecase

New OS support

### Description

repo.powerdns.com should have bullseye packages for all current versions + head.

Thanks!

**Comment by zeha** [comment]
Note: 32bit archs on bullseye have sizeof time_t == 4, so no packages for those!

**Comment by CTassisF** [comment]
Debian Bullseye was released this past saturday: https://www.debian.org/releases/bullseye/

Looks like repo.powerdns.com is still missing Bullseye packages: https://repo.powerdns.com/debian/dists/

**Comment by nivex** [comment]
`bullseye-auth-45` and `bullseye-dnsdist-16` now exist in the repo. I have been using the former for a couple days now with no apparent ill effects. It was mentioned recently on IRC that `bullseye-rec-45` is still pending.

`master` builds for all three also exist now.

**Comment by Ramshield** [comment]
@nivex Any idea about Raspbian Bullseye packages? Or should I open another issue?

**Comment by kpfleming** [comment]
Keep in mind that the most recent releases of the PowerDNS suite don't support Raspbian at all, since it is a 32-bit platform (with a 32-bit `time_t` structure). This means that there won't be builds of PowerDNS Auth 4.5.x for Raspbian at all, I believe.

The Bullseye support in the package builders is being added to the 'current' release branches; in order to produce Raspbian Bullseye packages of Auth 4.4.x that support would need to be backported into the auth-4.4.x branch.

**Comment by Ramshield** [comment]
And DNSdist 1.6 for Raspbian Bullseye? :)

**Comment by Habbie** [comment]
dnsdist 1.6 also requires 64 bit `time_t`

**Comment by Ramshield** [comment]
So there are possibilities for 64 bit Raspbian (https://www.raspberrypi.org/forums/viewtopic.php?t=275370). I guess once this is a bit more stable, could we get DNSdist 1.6 and PowerDNS Auth 4.5.x ? I'd be happy to open a new issue to keep track of this.

**Comment by Habbie** [comment]
>  64 bit Raspbian

I wonder if 64 bit Raspberry Pi OS is binary compatible with Debian arm64. Do you know?

**Comment by Ramshield** [comment]
I do not I'm afraid, and the only Raspberry PI I have is running 32-bit.

**Comment by kpfleming** [comment]
Unless you actually need the packages that Raspbian provides which the other distros do not (primarily multimedia related), you should consider using a 'regular' distro for your servers providing DNS services :)

**Comment by Habbie** [comment]
+1 to that.

**Comment by stintel** [comment]
As an alternative, OpenWrt has 64 bit images for RPi 3/4 and has packages for dnsdist 1.6.0 and auth 4.5.1.

**Comment by Ramshield** [comment]
> Unless you actually need the packages that Raspbian provides which the other distros do not (primarily multimedia related), you should consider using a 'regular' distro for your servers providing DNS services :)

Fair enough for a production environment, but for a small home environment? 
I run PiHole and to distribute DNS evenly (and provide a bit better uptime in case I need to reboot one of my pihole servers) I use DNSdist so my girlfriend doesn't get mad when I mess around with DNS lol! 
Hopefully you guys are willing to provide 64-bit packages for Raspbian in the future!

**Comment by kpfleming** [comment]
Pi-hole is supported on Fedora, Debian, and Ubuntu on Raspberry Pi systems.

**Comment by nivex** [comment]
What are the remaining blockers on `bullseye-rec-45`?

**Comment by zeha** [comment]
Given I've now checked out the repo page, currently:
- repo.powerdns.com lists instructions for bullseye-rec-45
- but in /debian/dists/, bullseye-rec-45 is missing

(Wild guess: need a new version stamped to trigger a build that makes it into that suite.)

**Comment by Habbie** [comment]
We've done several releases of all products for 64 bit Bullseye, so I'm closing this.
