### ISSUE TITLE
Dynamic Server Group discovery based on A DNS record for usage in Kubernetes

### ISSUE THREAD

**Issue by lukasmrtvy** [PowerDNS/pdns#10413]
- Program:  dnsdist 
 - Issue type: Feature request

### Short description

Would be nice to have a Dynamic Server Group discovery based on A DNS record. 

### Usecase

Usage in Kubernetes.

### Description

You can deploy PowerDNS recusor/auth as a headless service in Kubernetes, that means that instances are "behind" pseudo service represented as ip adresses of pods/instances in single A name, which is usually in form of service.namespace.svc.cluster.local. Would be nice to have a piece of LUA code that will discover hosts based on single A record. Internal DNS is handled usually via CoreDNS, so that will work. 

Architecture:
```
dnsdist loadbalancer service -> dnsdist pods -> pdns headless service -> pdnds pods
```
Config:
```
newServer({a_dns_address="pdns-headless.pdns.svc.cluster.local.", pool="group1"})
```

Thanks

**Comment by Habbie** [comment]
#9875 is related.

https://github.com/PowerDNS/pdns/blob/master/dockerdata/dnsdist-resolver.lua (plus the `.py`) is code you could deploy today to get this feature.

**Comment by phonedph1** [comment]
#7553 as well

**Comment by lukasmrtvy** [comment]
@Habbie Seems that https://github.com/PowerDNS/pdns/blob/master/dockerdata/dnsdist-resolver.lua does not work as expected

```
(1) do: resolver = require 'dnsdist-resolver'
(2) do: resolver.servers['cloudflare.com'] = { pool = 'group1' }
(3) do: resolver.maintenance()
(4) wait a few seconds
(5) do: resolver.maintenance()
(6) do: showServers()
```
returns only single IP address, instead of two:
```
dig A cloudflare.com

; <<>> DiG 9.16.1-Ubuntu <<>> A cloudflare.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25262
;; flags: qr rd ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;cloudflare.com.                        IN      A

;; ANSWER SECTION:
cloudflare.com.         0       IN      A       104.16.133.229
cloudflare.com.         0       IN      A       104.16.132.229

;; Query time: 0 msec
;; SERVER: 172.27.96.1#53(172.27.96.1)
;; WHEN: Sun May 16 11:46:16 CEST 2021
;; MSG SIZE  rcvd: 78
```

**Comment by Habbie** [comment]
Can you please test #10414?

**Comment by lukasmrtvy** [comment]
@Habbie 👋 its working, even for ipv6 nameservers.

**Comment by bondar-aleksandr** [comment]
team, could you please provide me with exact steps I need to take to take to dynamically add real-servers based preiodically?
what should I set in real-server config section? thanks in advance
