### ISSUE TITLE
rec: for the NOD lookup, ponder a "fire and forget" mode

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#10425]
NOD lookups ignore the result, so it does not make sense to wait for it: waiting wastes resources in rec.
Suggested by @paddg

**Comment by omoerbeek** [comment]
I thought about this and it does seem doable, but a bit more complex than you might think:

1. Only the latest query for the qname/qtype as requested by the client should be fire & forget; all other queries should be waited for because their results (NS etc) are needed to do the final query.
2. In theory it is possible (nut unlikely) that intermediate queries are the same as the qname/qtype requested byu the client.
3. Likely the call chain from `doResolveNoQNameMinimization` to `doResolveAt` should get a flag to indicate we're not interested in the result. This flag is then passed to `doResolveAtThisIP` and `asyncresolveWrapper` and then maybe placed in the `ResolveContext` so that `lwres.cc` can use it but the signature of `asyncresolve` does not change.

Now I actually have to write this code to see if this plan works. Don't know yet if this is going to make 4.6.

**Comment by omoerbeek** [comment]
After some experiments and discussion in #10849 the conclusion is: faf can be done with a dnsdist helper and we would like to have a way to signal NOD event using protobuf and/or dnstap. protobuf client/answer message already carries the NOD info, but the ability to only send out messages on NOD events is useful.

**Comment by omoerbeek** [comment]
#12047 implements s dnstap signalling for NOD/NDR events.

**Comment by paddg** [comment]
Thank you!
