### ISSUE TITLE
SVCB: 'generic' syntax fails for known types

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#10443]
Good (66 is unknown to us):

```
pdnsutil --config-dir=. raw-lua-from-content SVCB '1 . key66="\032\001\013\184\000\000\000\000\000\000\000\000\\\\,\000"'
"\000\001\000\000B\000\016\032\001\013\184\000\000\000\000\000\000\000\000\092\092\044\000"
```

Bad (we know 6 as `ipv6hint`):
```
pdnsutil --config-dir=. raw-lua-from-content SVCB '1 . key6="\032\001\013\184\000\000\000\000\000\000\000\000\\\\,\000"' 
�\'or: Unable to convert presentation address ' 
```

A better readable version of 'bad':
```
pdnsutil --config-dir=. raw-lua-from-content SVCB '1 . key6="\065\066\067\068\069\070\071"'
Error: Unable to convert presentation address 'ABCDEFG'
```

instead of taking the value as something to put on the wire, we still try to parse it as a (v6) presentation address.

**Comment by pieterlexis** [comment]
> This feels quite similar to #804

The same kind of thinking is the root cause, different code paths though

**Comment by pieterlexis** [comment]
Discussed with @Habbie

Right now, the SVCParams are stored in a 'native' format (IP addresses as ComboAddress, port as uint16_t, etc). This means that all the parsers do way too much work. We should store the SVCParams as wireformat internally.
