### ISSUE TITLE
NOTIFY not signed when (TSIG)

### ISSUE THREAD

**Issue by Kind-der-Nacht** [PowerDNS/pdns#1044]
NOTIFY for domains using TSIG should also be signed.

**Comment by spinza** [comment]
I have a dual view bind dns setup needing to be notified by PowerDNS of changes.  PowerDNS sends notification but bind has no way to tell which view the notification is for and chooses incorrectly based on IP rather than TSIG.

**Comment by pieterlexis** [comment]
Fixed in #2591
