### ISSUE TITLE
Does it support functions similar to "bind view"

### ISSUE THREAD

**Issue by skycyan** [PowerDNS/pdns#10444]
## PowerDNS
Does it support functions similar to "Bind view" ?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
