### ISSUE TITLE
pdnsutil function - re-generate new serial for all zones at once

### ISSUE THREAD

**Issue by clusterx** [PowerDNS/pdns#10458]
It seems pdnsutil rectify-all-zones has no effect when using gmysql, the serials stay same and the slave NS are not updated
therefore it would be nice if there was a working pdnsutil function to generate a new serial for all zones at once

**Comment by Habbie** [comment]
Hello,

I repeat: this is not a support forum. This is for reporting bugs or requesting features. When you want to report a bug, or request a feature, please use the template provided.
