### ISSUE TITLE
pdnsutil rectify-all-zones - no effect

### ISSUE THREAD

**Issue by clusterx** [PowerDNS/pdns#10457]
Debian10
PDNS server v4.3 (gmysql)

I use PDNS without DNSSEC as a master, the slaves are linode NS.
It seems pdnsutil rectify-all-zones has no effect, the serials stay the same and the slave NS are not updated.
How can I do an increase-serial for all zones without adding DNSSEC entrys?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
