### ISSUE TITLE
Pdns 4.1.6, mysql backend login bug

### ISSUE THREAD

**Issue by edgar-diaz-orellana** [PowerDNS/pdns#10472]
- Program: Backend Mysql can't log in, bug is on reading the password too complex 
 - Issue type: Bug report

### Short description
When you had the mysqlbackend on debian 10, and try to bring up the daemon, there are tons of connections attempt from the pdns server, syslogs shows as successful connection 
"pdns_server[2496]: gmysql Connection successful. Connected to database 'pDNS' on 'localhost'."

on the other side at mysql level log you had this.
2021-06-06 20:49:05 5875 [Warning] Aborted connection 5875 to db: 'pDNS' user: 'pdns_daemon' host: 'localhost' (Got an error reading communication packets)

after further investigation, i decide to move out the user grant from this login to 

grant select on pDNS.* to 'pdns_daemon'@localhost identified by '$zd8.kFy0Mv';

to This 

grant select on pDNS.* to 'pdns_daemon'@localhost identified by 'zF3.kaB3Gb6lKFy0Mv';

after updating the config file and restart everything goes well.

### Environment

 - Operating system: Debian 10, Linux version 4.19.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27)
 - Software version:  PowerDNS Authoritative Server 4.1.6 (C) 2001-2018 PowerDNS.COM BV
 - Software source:  Debian Official Stable Repository

### Steps to reproduce
1.  install blank system, install  pdns-backend-mysql and mysql
2. try using same grants, 
3. attempt to bring up the pdns daemon.

### Expected behaviour
fixup the reading credentials from the config file to accept Complex passwords

### Actual behaviour
failing to bring up daemon

**Comment by Habbie** [comment]
Hello! Thank you for your extensive report. Sadly, I cannot figure out what bug you are trying to report.

` "pdns_server[2496]: gmysql Connection successful. Connected to database 'pDNS' on 'localhost'."` does not look like 'failure to bring up daemon'.

Furthermore, you are using an unsupported version: https://doc.powerdns.com/authoritative/appendices/EOL.html

If you can show us the problem on a newer version, we'll happily take a look.
