### ISSUE TITLE
powerdns have support this config?

### ISSUE THREAD

**Issue by haiwan-xm** [PowerDNS/pdns#10485]
![image](https://user-images.githubusercontent.com/45061573/121311897-6e8c3a00-c937-11eb-8416-01f2bdff2ed2.png)
if we add this 
1 
![image](https://user-images.githubusercontent.com/45061573/121312045-92e81680-c937-11eb-88da-973af0709a2b.png)
2
![image](https://user-images.githubusercontent.com/45061573/121312152-abf0c780-c937-11eb-9680-e2b12cb9d717.png)
![image](https://user-images.githubusercontent.com/45061573/121312173-b0b57b80-c937-11eb-9d7f-ff872f4fdba8.png)

we add same name point  no  same content  happen error.

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
