### ISSUE TITLE
Dnsdist reports metrics about down upstream servers

### ISSUE THREAD

**Issue by hhoffstaette** [PowerDNS/pdns#10500]
- Program: dnsdist
 - Issue type: Bug report
   (more an observation of unexpected behaviour; whether it qualifies as bug is a matter of perspective. :)

### Short description
I noticed that server metrics (e.g. for latencies) are still reported even when an ustream server
is in the "down" state. This is confusing to me, and IMHO the values other than server_status
should be dropped from the metrics as long as the server is down. I believe this would be a more
accurate representation of things.
A related followup problem is whether the statistics for the server in question should be
zeroed out when it goes down; otherwise metrics would continue to report the old stale latencies
when the server comes back (even though they would then adjust eventually).

### Environment

 - Operating system: Linux
 - Software version: dnsdist 1.6.0
 - Software source: self-compiled

### Steps to reproduce
1. set an active server to "down" after some use
2. get metrics, see stale latencies

### Expected behaviour
No latency metrics as long as the server is dead 

### Other information
My original problem - Grafana would show "valid" but stale latencies even for a dead server - could
be kind-of-solved with a hack: instead of simply displaying the latency, I multiply the latency value with
server_status (i.e. 0 or 1). This gives me either the value or a 0-measurement as long as the server is
dead (which can take arbitrarily long, of course).
Still, not reporting the stale metrics in the first place seems cleaner to me.
I briefly looked into the code and found the part in dnsdist_web.cc where I could add an
additional if-condition to verify the server state and then suppress the latency metrics - easy enough.
But the longer I thought about this, the more I asked myself what should happen when
the server comes back. Should the latency metrics continue where they left off? Start from 0?

I can gladly make a PR with the necessary check to drop metrics from dead servers, but first wanted to
hear what other people think.
Thanks for dnsdist :)

**Comment by rgacogne** [comment]
> IMHO the values other than server_status should be dropped from the metrics as long as the server is down. I believe this would be a more accurate representation of things.

In theory I agree with you, although I wonder if all the metrics collector would be fine with the metric disappearing. Any idea?

> A related followup problem is whether the statistics for the server in question should be zeroed out when it goes down; otherwise metrics would continue to report the old stale latencies when the server comes back (even though they would then adjust eventually).

That sounds like a good idea. I'm a bit worried about someone using the latency in a custom load-balancing policy and suddenly sending all queries to a server that just came back up because its latency would be zero, but I guess it could be solved by handling zero as a special case, which would not be a bad idea anyway.

**Comment by hhoffstaette** [comment]
>> IMHO the values other than server_status should be dropped from the metrics as long as the server is down.
>> I believe this would be a more accurate representation of things.
> 
> In theory I agree with you, although I wonder if all the metrics collector would be fine with the metric disappearing. Any idea?

If nothing gets reported then samples in those time series are just missing at that point in time, no problem.
We could also report 0 by default, but IMHO that would be wrong since 0 is not nothing. ;)
I'll start hacking on it.

**Comment by rgacogne** [comment]
> If nothing gets reported then samples in those time series are just missing at that point in time, no problem.

Neat :)

> We could also report 0 by default, but IMHO that would be wrong since 0 is not nothing. ;)

I agree, 0 would be misleading.

> I'll start hacking on it.

Great, thanks! :+1:
