### ISSUE TITLE
SERVFAIL with HTTPS record (lmdb backend)

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#10521]
- Program: Authoritative
 - Issue type: Bug report

### Short description
With `example.com IN HTTPS 0 foo.bar.com.`, queries are answered with SERVFAIL when a) the backend is lmdb, b) the zone is presigned (retrieved via AXFR). (Not sure if this is a necessary and/or sufficient set of conditions.)

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.4.0-1pdns.bionic
 - Software source: PowerDNS repository

### Steps to reproduce
@Habbie already reproduced (IRC on June 22, 2021).

**Comment by peterthomassen** [comment]
Log says:

```
```

**Comment by Habbie** [comment]
> With `example.com IN HTTPS 0 foo.bar.com.`, queries are answered with SERVFAIL when a) the backend is lmdb, b) the zone is presigned (retrieved via AXFR). (Not sure if this is a necessary and/or sufficient set of conditions.)

b) is not a condition. The record pointing outside the containing zone is :-)
