### ISSUE TITLE
dnsdist: LMDB changes only on every second commit

### ISSUE THREAD

**Issue by membero** [PowerDNS/pdns#10542]
- Program: dnsdist
 - Issue type: Bug report

### Short description
When using dnsdist with LMDB, changes in LMDB only show up in dnsdist on every second LMDB commit.

### Environment

 - Operating system: Debian 10 (Buster)
 - Software version: dnsdist 1.6.0 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
 - Software source: https://repo.powerdns.com/ -> "Debian 10 (Buster)" -> "dnsdist - version 1.6.X"

### relevant configuration for LMDB

This configuration is just for testing. It does not make sense in real live.

```
kvsDomains = newLMDBKVStore('/var/spool/dnsdist/data.mdb', 'zones')

addAction(AllRule(), KeyValueStoreLookupAction(kvsDomains, KeyValueLookupKeySuffix(2, false), 'kvs-domain-result'))
addAction(TagRule('kvs-domain-result', ''), RCodeAction(DNSRCode.REFUSED))
addAction(TagRule('kvs-domain-result', 'default'), RCodeAction(DNSRCode.NXDOMAIN))
```

### Steps to reproduce
1. Start dnsdist with an empty LMDB.
2. dig @127.0.0.1 test1.com
3. Add an entry "test1.com" "default" to the zones Db.
4. dig @127.0.0.1 test1.com
5. Add an entry "test2.com" "default" to the zones Db.
6. dig @127.0.0.1 test1.com

### Expected behaviour
The first dig returns REFUSED since test1.com is not in LMDB.
The second and third dig should return NXDOMAIN.

### Actual behaviour
The first and second dig return REFUSED.
The third dig, after making another change to LMDB, then correctly returns NXDOMAIN.
dig @127.0.0.1 test2.com also returns NXDOMAIN after this.

### Other information
This behavior repeats, a third entry created after this does not change the behavior of dig, a fourth one instantly shows up and also causes the third one to show up.
Just creating and then commiting an LMDB transaction does not cause a previously created zone entry to affect dnsdist.
Neither does commiting a transaction where mdb del was called for a nonexistent entry.
But a commit where mdb put was called with an already existing entry, also not changing the content of LMDB, does update dnsdist.

**Comment by Habbie** [comment]
Hello! Can you please share your code for adding entries to the DB?

**Comment by membero** [comment]
Hi Habbie,

we tested two different methods. First our own code based on https://github.com/ahupowerdns/lmdb-safe:

`auto env = getMDBEnv(#PathToLmdb#, 0, 0600);`
`auto zonesDbi = env->openDB("zones", MDB_CREATE);`
`auto transaction = env->getRWTransaction();`
`transaction->put(zonesDbi, #ZoneName#, "default");`
`transaction->commit();`

Second we tried a cli tool from here: https://github.com/2nd/lmdb-cli

`go run main.go --name zones --db PathToDb`
`put #ZoneName# default`

**Comment by rgacogne** [comment]
I'm afraid I can't reproduce the issue. I tried with the following python script:
```python
import lmdb

env = lmdb.open('/tmp/data.mdb', map_size=1024*1024, max_dbs=1024, subdir=False)
db = env.open_db(key=b"zones")
with env.begin(db=db, write=True) as txn:
    key = b'powerdns.com'
    value = b"default"
    txn.put(key, value)
```

And the dnsdist configuration you supplied above, except for the the path that was updated to /tmp/data.mdb'. Any change is immediately picked up by dnsdist in my tests.
I also reviewed the code and I don't see how dnsdist could end up with a stale value, since we open a new RO transaction for every lookup and do not cache anything except for `MDB_env`, which should not be an issue.

**Comment by membero** [comment]
Indeed I see that with the python script it works as expected.

After some further debugging and testing we found that our implementation did not use MDB_NOSUBDIR. It is strange that we could reliable reproduce this behaviour. So its our fault and not a bug in dnsdist.

Sorry for bothering.

**Comment by rgacogne** [comment]
Thanks for reporting back! If you think it would make sense for dnsdist to support opening a LMDB database without `MDB_NOSUBDIR` please open a (short, no need for many words) feature request so we don't forget :)
