### ISSUE TITLE
dnsdist: Ponder trying to raise RLIMIT_MEMLOCK automatically when eBPF is requested

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#10566]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
Most systems set `RLIMIT_MEMLOCK` to 64k, which is not enough for most usage (decent-sized maps). We could check and try to raise that value to `1024` when an eBPF object is created.

**Comment by rgacogne** [comment]
And/or add this in the systemd unit file:
```
[Service]
LimitMEMLOCK=infinity
```

**Comment by rgacogne** [comment]
For example, checking the current value of `RLIMIT_MEMLOCK` and trying to raise it if needed, at the beginning of the BPFFilter constructor here: https://github.com/PowerDNS/pdns/blob/4565c442fc60134d5608c141d6a23cf750b80f2f/pdns/bpf-filter.cc#L321

**Comment by yog-singh** [comment]
There's a hard limit on different systems on the maximum memory that can be allocated. To change the limit it needs to be explicitly added to `/etc/security/limits.conf`.
We can set the hard limit to a specific value in the above limit conf and then eBPF filter when gets constructed the soft limit can be increased.

**Comment by rgacogne** [comment]
Implemented in #11554.
