### ISSUE TITLE
auth: make it possible to view and remove supermasters via API/pdnsutil

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/pdns#10582]
- Program: Authoritative
 - Issue type: Feature request

### Short description

While there is a possibility to add a supermaster via pdnsutil, there currently is no way to view the list of supermasters or remove them. This wasn't much of a problem since the only backends that did superslave functionality used SQL storage which could be easily editted, but #10569 adds support to the LMDB backend for supermasters, which makes manual editting much harder.

### Usecase

I want to be able to view which supermasters there are and delete them, using pdnsutil and ideally also via the API.

**Comment by Habbie** [comment]
Now that we have catalog zones, we will not be adding new code for supermaster/autoprimary users.
