### ISSUE TITLE
Consider auth NS records we receive from parent domains for recursor NS cache

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#10594]
- Program: Recursor
 - Issue type: Feature request

### Short description
When resolving a name, powerdns-recursor should consider adding NS records it receives from "parent" (closer to .) name servers to the NS cache for a zone. 

### Usecase
Resolve domains which are misconfigured, but where we could know where and and how to get the proper answer.

#### Given:
Imaging example.tld having NS ns.foo.tld  at the .tld TLD. The zone (served by ns.foo.tld) has an A record for www.example.tld 10.10.10.10, and has NS records for example.tld set to NS ns.bar.tld. ns.bar.tld doesn't answer on queries to www.example.tld.

#### Observed behaviour:
The first time (empty cache) pdns-rec must resolve www.example.tld, it succeeds: pdns-rec will ask ns.foo.tld and accept the result. Hence, the client gets a result.

When processing the first result, PowerDNS will cache the NS records it receives from ns.foo.tld as the (only) NS records for example.tld, so it stores ns.bar.tld as the NS for example.tld.

This means that the second query for eg. mail.example.tld will use the cached NS set – consisting of only ns.bar.tld – which doesn't reply.

### Description
PowerDNS should add both NSs to the cache set. The first NS (ns.foo.tld) is received from a trusted "parent" which sends a record we trust (and use in the case of an empty cache). Why not add it to the cache?

I know that in the case above, the domain is misconfigured. And that we shouldn't encourage this behaviour. But when I look at the failures that are reported to me for people using pdns-resolver, this issue 

However, other resolvers (both closed and open source) are able to resolve www.example.tld perfectly fine in this case.

I considered reporting this as a bug instead of a feature request, as the PowerDNS behaviour depends on the state of the cache.

**Comment by rgacogne** [comment]
> PowerDNS should add both NSs to the cache set. The first NS (ns.foo.tld) is received from a trusted "parent" which sends a record we trust (and use in the case of an empty cache). Why not add it to the cache?

That would mean mixing authoritative and non-authoritative data and returning that mix to clients, which IMHO would violate the RFC.
Our current cache cannot keep both the authoritative and non-authoritative sets for a given name and type, and merging the two of them is not a viable option.

**Comment by rgacogne** [comment]
To be clear I'm not against the idea of using the non-authoritative, parent-side NS RRSET, perhaps as a fallback when the child-side NSs failed. I'm just pointing out that we need to think this through rather than rushing a fix :)

**Comment by franklouwers** [comment]
The parent-side would be "authoritative" in that we trust it's authority to delegate. So while technically maybe not authoritative(as no soa example.tld), it's not 'non-authoritative': this is a a result we trust and use.

Agree that using it as a fallback might be the better option.

**Comment by Habbie** [comment]
> it's not 'non-authoritative'

I see what you're saying, but it's important to call things what they are, and the parent side NSes are non-authoritative.

**Comment by franklouwers** [comment]
It's equally as important to point out that these are different from other "non-authoritative" responses. I am not arguing that we should consider adding non-auth replies to the cache. I am arguing that we should consider adding trusted (and used, in the case where the cache is empty) replies to the cache.

**Comment by rgacogne** [comment]
The fact that they are not authoritative has implications, for example it is not DNSSEC-signed even if the parent and child zones are signed, and if we mix the records in an answer any RRSIG will of course be invalid.

**Comment by omoerbeek** [comment]
Mixing auth and non-auth records in a single recordset in the cache (which will potentially be sent to clients) will cause too much trouble. But we can think of other ways to remember NS records received from the parent and use them if the child provided NS records do not lead to success.

**Comment by franklouwers** [comment]
Am willing to contribute $$ to increase priority if it helps.

**Comment by omoerbeek** [comment]
We will try to spend some time on this trying to come up with a solution that does not add too much complexity and does not affect well-configured domains. But due to general work-load do not expect solutions to be implemented in short term.
