### ISSUE TITLE
“refresh almost expired” feature for dnsdist

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#10600]
- Program: dnsdist 
 - Issue type: Feature request

### Short description

It would be nice if one can profit from Recursor's “refresh almost expired” feature even if there is a caching dnsdist in front of the Recursor.

### Usecase

We have dnsdist processes in front of our Recursor processes, which is great! Unfortunately the dnsdist cache makes the “refresh almost expired” feature of the Recursor completely ineffective.

### Description

A solution, I could imagine is, to give the dnsdist packet cache the same feature as  the Recursor have: "refresh-on-ttl-perc".

But you guys may have  a better solution.

**Comment by rasgard** [comment]
Hi @rgacogne 
Regarding the function added with https://github.com/PowerDNS/pdns/pull/12400, this may not be very helpful if you have more than one resolver backend. There should be a real 'refresh almost expired' feature.

**Comment by paddg** [comment]
@rasgard, you could use `setServerPolicy(whashed)`, to ensure that the "correct" backend is addressed.

**Comment by rgacogne** [comment]
I'm not sure I follow your reasoning. I'm guessing, but it would be better if you could elaborate, that you mean we will end up requesting the almost expired record from only one resolver, and it might not be the one that will be queried for the next query coming in for that record, which would result in a miss. How do you imagine a "real" refresh almost expired feature in dnsdist would fix this?

**Comment by rasgard** [comment]
yes I expect that some of the querys will not be answerd by the same backend and result in longer responses but i have to check setServerPolicy(whashed) thanks

**Comment by rasgard** [comment]
Sorry, I should have read the manual again :)  I have observed this problem since 2021....
thank you @rgacogne @paddg

**Comment by rgacogne** [comment]
You might also want to have a look at `chashed`, which delivers consistent hashing even when servers are added or removed: https://dnsdist.org/guides/serverselection.html#chashed

**Comment by rgacogne** [comment]
I'm closing this feature request for now, as I don't think we will get a better solution than the one implemented in #12400. I'm of course happy to re-open if someone disagrees and suggests a better solution, especially if it comes with a pull request ;-)
