### ISSUE TITLE
remote backend hard-closing connection on result:false to not-implemented getAllDomains

### ISSUE THREAD

**Issue by benaryorg** [PowerDNS/pdns#10614]
- Program: Authoritative
 - Issue type: Bug report

### Short description

In absence of a more concise documentation on the SHOULD behavior of a remote backend (unix connector), my backend returns `{"result":false}` to which pdns seems to respond by closing the connection.

### Environment

 - Operating system: Gentoo
 - Software version: pdns-4.5.0
 - Software source: Gentoo portage ebuild, with `USE=remote -*` 

### Steps to reproduce

This configuration:

```
api=no
remote-connection-string=unix:path=/var/run/lxddns/lxddns2.sock
launch=remote
local-address=$ipv4, $ipv6
setgid=pdns
setuid=pdns
loglevel=9
```

Start a unix-connector on the other side which answers to `initialize` with `result:true` and to `getAllDomains` with `result:false`.

### Expected behaviour

I wouldn't want pdns to ask for all domains in the firstplace but hey, if that's what's best/easiest/fastest internally go for it.
However if from other end of that unix socket the answer is `{"result":false}` then the expected behavior is to fall back to querying using `lookup` or whatever other method (which in my case should eventually fallback to `lookup` because my backend only supports `initialize` and `lookup`.

### Actual behaviour

So as you can see I put a `2` in the path of that unix socket.
Reason is, I plugged in socat between the two to see what's going on in detail.
I'll be explaining the output of said socat:

```bash
socat -ddd -v -v unix-listen:/var/run/lxddns/lxddns2.sock,fork
```

```
2021/07/27 22:24:12 socat[30112] I socat by Gerhard Rieger and contributors - see www.dest-unreach.org
2021/07/27 22:24:12 socat[30112] I This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit. (http://www.openssl.org/)
2021/07/27 22:24:12 socat[30112] I This product includes software written by Tim Hudson (tjh@cryptsoft.com)
2021/07/27 22:24:12 socat[30112] I setting option "fork" to 1
2021/07/27 22:24:12 socat[30112] E "/var/run/lxddns/lxddns2.sock" exists
2021/07/27 22:24:12 socat[30112] N exit(1)
```

So far so good, we've got ourselves a running socat, nothing special there.
Now I restart pdns, so we can see *something*, despite the server being constantly hammered on by a script on my other host querying that specific server using *dig* (and not getting any meaningful response).

```
2021/07/27 22:28:02 socat[25165] I accept(5, {1, AF=1 "<anon>"}, 2) -> 6
2021/07/27 22:28:02 socat[25165] N accepting connection from AF=1 "<anon>" on AF=1 "/var/run/lxddns/lxddns2.sock"
2021/07/27 22:28:02 socat[25165] I permitting connection from AF=1 "<anon>"
2021/07/27 22:28:02 socat[25165] N forked off child process 32403
2021/07/27 22:28:02 socat[25165] I close(6)
```

There's the incoming connection on fd 6.

```
2021/07/27 22:28:02 socat[25165] I still listening
2021/07/27 22:28:02 socat[25165] N listening on AF=1 "/var/run/lxddns/lxddns2.sock"
2021/07/27 22:28:02 socat[32403] I just born: child process 32403
2021/07/27 22:28:02 socat[32403] I close(4)
2021/07/27 22:28:02 socat[32403] I close(3)
2021/07/27 22:28:02 socat[32403] I just born: child process 32403
2021/07/27 22:28:02 socat[32403] I close(5)
2021/07/27 22:28:02 socat[32403] N opening connection to AF=1 "/var/run/lxddns/lxddns.sock"
2021/07/27 22:28:02 socat[32403] I socket(1, 1, 0) -> 5
2021/07/27 22:28:02 socat[32403] N successfully connected from local address AF=1 "[…]"
```

The outgoing connection is also there, after all socat is only proxying here.

```
2021/07/27 22:28:02 socat[32403] I resolved and opened all sock addresses
2021/07/27 22:28:02 socat[32403] N starting data transfer loop with FDs [6,6] and [5,5]
```

So FD6 is pdns, and FD5 is my piece of code (lxddns).

```
> 2021/07/27 22:28:02.592053  length=81 from=0 to=80
{"method": "initialize", "parameters": {"path": "/var/run/lxddns/lxddns2.sock"}}
2021/07/27 22:28:02 socat[32403] I transferred 81 bytes from 6 to 5
< 2021/07/27 22:28:02.593103  length=16 from=0 to=15
{"result":true}
2021/07/27 22:28:02 socat[32403] I transferred 16 bytes from 5 to 6
```

Initialize works like a charm, so far so good.

```
> 2021/07/27 22:28:02.593213  length=70 from=81 to=150
{"method": "getAllDomains", "parameters": {"include_disabled": true}}
2021/07/27 22:28:02 socat[32403] I transferred 70 bytes from 6 to 5
< 2021/07/27 22:28:02.593401  length=17 from=16 to=32
{"result":false}
2021/07/27 22:28:02 socat[32403] I transferred 17 bytes from 5 to 6
```

This is what my code is supposed to do when it doesn't implement getAllDomains, right?
Implementing it isn't feasible with that particular piece of code as it queries a third-party backend the full range of values of which cannot be known at start-up.

```
2021/07/27 22:28:02 socat[32403] N socket 1 (fd 6) is at EOF
2021/07/27 22:28:02 socat[32403] I shutdown(5, 1)
```

So now this, pdns closes the connection just like that.

```
2021/07/27 22:28:02 socat[32403] N socket 2 (fd 5) is at EOF
```

In response my code logs something to stderr about the connection closing and closing itself as the socket is at EOF for my code.

```
2021/07/27 22:28:02 socat[32403] I shutdown(6, 1)
2021/07/27 22:28:02 socat[32403] I shutdown(6, 2)
2021/07/27 22:28:02 socat[32403] I shutdown(5, 2)
2021/07/27 22:28:02 socat[32403] N exiting with status 0
2021/07/27 22:28:02 socat[25165] N childdied(): handling signal 17
2021/07/27 22:28:02 socat[25165] I childdied(signum=17)
2021/07/27 22:28:02 socat[25165] I childdied(17): cannot identify child 32403
2021/07/27 22:28:02 socat[25165] I waitpid(): child 32403 exited with status 0
2021/07/27 22:28:02 socat[25165] I waitpid(-1, {}, WNOHANG): No child processes
2021/07/27 22:28:02 socat[25165] I childdied() finished
```

The rest is connection fluff by socat.

### Other information

I really don't know what my backend is *supposed* to do and why it isn't even hit by the queries pdns is receiving.
PowerDNS is receiving queries I'm pretty sure of that as none of my DNS records changed and this very setup worked a few days ago, though getting it to work like that for some time required a seemingly random amount of random restarts of powerdns, by service, and dependency services.

At this point I just can't help but thinks this is a bug, pretty much everything indicates that there should be queries coming to my backend but there are none, and whenever there are, they aren't lookups, they're something the backend doesn't implement and no attempt to fallback to the required methods is being made.

The source code of lxddns can be found over at [benaryorg/lxddns](https://github.com/benaryorg/lxddns), however I can assure you that it responds without any problem when presented with a `lookup`-method query.
Effectively it responds to everything but a `lookup` or `initialize` with `result:false`, the latter a `result:true` and lookup is handled intricately to yield something like that:

```
> {"method":"lookup","zone_id":0,"parameters":{"qtype":"AAAA","qname":"[…]"}}
< {"result":[{"qtype":"AAAA","qname":"[…]","content":"[…]","ttl":16}]}
```

**Comment by Habbie** [comment]
Did your backend work with version 4.4.x?

**Comment by benaryorg** [comment]
> Did your backend work with version 4.4.x?

I downgraded just now and `4.4.1-r1::gentoo` worked fine *after a couple restarts* (half a dozen or so?).
After upgrading back to `4.5.1::gentoo` I couldn't get it to work after several restarts although I can't be certain about it being deterministically broken, but from the looks of it it seems to be a 4.5 thing then.

**Comment by mind04** [comment]
The "result" for getAllDomans is an array of domaininfo. "false" does not match remotebackend's expectations.

Disabling the zone-cache should avoid getAllDomains method use. Or add the method in your backend so you can benefit from this cache.

**Comment by benaryorg** [comment]
I fully agree that documentation is a little sparse on this, and I can confirm that  `zone-cache-refresh-interval=0` fixed the issue.
However seeing as the option is not valid in 4.4, one must take care when upgrading, and there is no future-proof way to guard against this in 4.4, unless I'm missing something.
