### ISSUE TITLE
Can't add localhost authoritive server to DNSDist

### ISSUE THREAD

**Issue by SirConius** [PowerDNS/pdns#10645]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
Im trying to run a PowerDNS Authoritive server and a DNSDist server next to each other in docker.
My configuration does work because if I create the Authoritive server on a different machine DNSdist shows the status as "UP"
But when I make a new machine, with the same config. On the same Docker instance it doesnt show as UP but as DOWN

I can access the webserver page on the "localhost pdns auth server"

### Environment

 - Operating system: Debian 10 running docker
 - Software version: PowerDNS 4.4.1 and dnsdist 1.1.0
 - Software source: psitrax/powerdns and psitrax/powerdns

### Steps to reproduce
1. Create new docker instance.
2. docker cp the config to the container
3. restart the machine
4. add new server to the dnsdist config
5. reboot dnsdist
6. error...

### Expected behaviour
To show the localhost powerdns server as UP

### Actual behaviour
It shows down.

### Other information
![Schermafbeelding 2021-08-13 142824](https://user-images.githubusercontent.com/40295254/129357412-6dcc0296-ec3b-43ba-81f2-e19e8d17edaf.png)

###PowerDNS Config
`allow-axfr-ips=10.10.0.0/24`

`api=yes`
`api-key=<api-key>`

`cache-ttl=60`

`config-dir=/etc/pdns`
`include-dir=/etc/pdns/conf.d`

`daemon=no`

`disable-axfr=no`
`distributor-threads=1`

`guardian=yes`

`launch=gmysql`
`gmysql-host=<database_host>`
`gmysql-port=3306`
`gmysql-dbname=<database>`
`gmysql-user=<username>`
`gmysql-password=<password>`
`gmysql-dnssec=yes`

`local-address=0.0.0.0`
`local-port=53`

`loglevel=3`

`master=yes`

`negquery-cache-ttl=60`

`setgid=pdns`
`setuid=pdns`

`socket-dir=/var/run`

`version-string=powerdns`

`webserver=yes`
`webserver-address=0.0.0.0`
`webserver-port=8081`
`webserver-allow-from=0.0.0.0/0,::/0`
`webserver-password=<password>`

###DNSDist Config
`addLocal("0.0.0.0")`
`setACL("0.0.0.0/0")`

`newServer({address="10.10.0.121:5353", order=1, weight=1, name="[PROD NODE]"})`
`newServer({address="127.0.0.1:5353", order=2, qps=5000, name="[TEST NODE]"})`
`setServerPolicy(firstAvailable)`

`setVerboseHealthChecks(true)`
`webserver("0.0.0.0:80", "<password>", "<api-key>")`

`addAction(MaxQPSIPRule(5), DelayAction(100))`
`addAction(MaxQPSIPRule(25), DropAction())`

###Docker Portainer:
![afbeelding_2021-08-13_143900](https://user-images.githubusercontent.com/40295254/129358325-4c52d3a2-bafe-485d-a936-3638019818c0.png)

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
