### ISSUE TITLE
auth: "pdns_control ccount" output formatted incorrectly

### ISSUE THREAD

**Issue by radub2012** [PowerDNS/pdns#10686]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

Not really an application-breaking bug, but "pdns_control ccount" outputs data incorrectly:
`negative queries: 206, queries: 78packets: 0`

No comma and spacing between the value of "queries", and the "packets" field.

### Environment

 - Operating system: CentOS 7 x86_64
 - Software version: PowerDNS Authoritative Server 4.5.1
 - Software source: PowerDNS repository

### Steps to reproduce

1. `pdns_control ccount`

### Expected behaviour

`negative queries: 206, queries: 78, packets: 0`

### Actual behaviour

`negative queries: 206, queries: 78packets: 0`

### Other information

Confirmed by Habbie via IRC.

**Comment by Habbie** [comment]
fixed in #12367
