### ISSUE TITLE
pdnsutil check-zone+no-DNSSEC bindbackend leads to wrong error about retrieving metadata

### ISSUE THREAD

**Issue by JohnKiller** [PowerDNS/pdns#10684]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Single authoritative server with single BIND zone file works on 4.4 but on 4.5 produces this error:

       [Error] Unable to retrieve metadata for zone example.com

### Environment
 - Operating system: Debian 10
 - Software version: 4.5
 - Software source: PowerDNS debian repository

### Steps to reproduce
1. Install `pdns-backend-bind` and `pdns-server`
2. Update `pdns.conf`:

```
    launch=bind
    bind-config=/etc/powerdns/named.conf
```

3. Update `named.conf`:

```
    zone "example.com" {
        type master;
        file "/etc/powerdns/example.com.zone";
    };
```

4. Update `example.com.zone`:

```
	$ORIGIN example.com.
	$TTL 86400
	@       SOA     dns1.example.com.       hostmaster.example.com. (
					2001062501 ; serial
					21600      ; refresh after 6 hours
					3600       ; retry after 1 hour
					604800     ; expire after 1 week
					86400 )    ; minimum TTL of 1 day
	;
	;
			NS      dns1.example.com.
			NS      dns2.example.com.
	dns1    A       10.0.1.1
			AAAA    aaaa:bbbb::1
	dns2    A       10.0.1.2
			AAAA    aaaa:bbbb::2
	;
	;
	@       MX      10      mail.example.com.
			MX      20      mail2.example.com.
	mail    A       10.0.1.5
			AAAA    aaaa:bbbb::5
	mail2   A       10.0.1.6
			AAAA    aaaa:bbbb::6
	;
	;
	; This sample zone file illustrates sharing the same IP addresses for multiple services:
	;
	services        A       10.0.1.10
					AAAA    aaaa:bbbb::10
					A       10.0.1.11
					AAAA    aaaa:bbbb::11

	ftp     CNAME   services.example.com.
	www     CNAME   services.example.com.
	;
```

### Expected behaviour
`pdnsutil check-all-zones` should succeed

### Actual behaviour
Fails with this error:

```
Sep 01 10:51:23 [bindbackend] Done parsing domains, 0 rejected, 1 new, 0 removed
[Error] Unable to retrieve metadata for zone example.com
Checked 19 records of 'example.com', 1 errors, 0 warnings.
Checked 1 zones, 1 had errors.
```

### Other information
Zone copied from https://docs.fedoraproject.org/en-US/Fedora/12/html/Deployment_Guide/s2-bind-zone-examples.html

**Comment by Habbie** [comment]
Yep, that's broken. Will investigate.

**Comment by Habbie** [comment]
Introduced in #8813.

This does not affect serving, so I'm going to edit the issue title a bit.
