### ISSUE TITLE
dnsdist: get a quick overview of a pool from api not implemented in version 1.6.0

### ISSUE THREAD

**Issue by dmachard** [PowerDNS/pdns#10691]
- Program: dnsdist
 - Issue type: Bug report

### Short description

The [documentation](https://dnsdist.org/guides/webserver.html#get--api-v1-servers-localhost-pool?name=pool-name) said the that the resource "GET /api/v1/servers/localhost/pool?name=pool-name" is new in version 1.6.0 but after some tests with dnsdist 1.6.0, this endpoint is not available (404 not found). Perhaps it's just a typo error in documentation and it will be available in the version 1.7.0?

```
# /usr/bin/dnsdist --version
dnsdist 1.6.0 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
Enabled features: cdb dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt ebpf fstrm ipcipher libsodium lmdb protobuf re2 recvmmsg/sendmmsg snmp systemd
```

**Comment by Habbie** [comment]
I see the code on master but indeed not on `rel/dnsdist-1.6.x`. rgacogne will have to tell us if a backport was planned.

**Comment by rgacogne** [comment]
A backport to 1.6.x is indeed planned, but the documentation still needs to be fixed since I won't be able to backport it magically into 1.6.0 :-)
