### ISSUE TITLE
dnsdist doh frontend tag injection

### ISSUE THREAD

**Issue by 7c** [PowerDNS/pdns#10715]
### Short description
having a DNS  over HTTP and Nginx in front with the config `addDOHLocal("127.0.0.1:8053", nil, nil, "/", { reusePort=true })`: it would be really good to inject tags to queries with parameters. Imagine DOH endpoint is `https://domain.com/tag=tagname` and we would then inject the tag 'tagname' into dns query. Then we might do actions based on the tags.

### Usecase
I want to allow our users to implement their own block lists, imagine user1 creates a list named 'user1_list' and this list might be in LMDB database with all corresponding Suffixes. Then I could give user1 the URL https://domain.com/?tag=user1_list - then this user would inject a tag to every dns query

### Description
imagine a family who does not want youtxbe.com  might create a custom list and create own blocks on dns level. 

Thanks for considering

**Comment by rgacogne** [comment]
Note that you can already do that by writing a bit of Lua code, using `DNSQuestion:getHTTPQueryString`[1]. For example:
 ```Lua
function myfunc(dq)
  print(dq:getHTTPQueryString())
  dq:setTag("http-query-string", dq:getHTTPQueryString())
  return DNSAction.None
end

addAction(AllRule(), LuaAction(myfunc))
```

Of course the query string will not contain the content of the `tag` parameter, you will still need to write a bit of code to extract the value of the parameter you are interested in.

[1]: https://dnsdist.org/reference/dq.html?#DNSQuestion:getHTTPQueryString

**Comment by 7c** [comment]
i agree, this feature is obviously already part of dnsdist. appreciate
