### ISSUE TITLE
don't depend on libsodium just for password comparisons

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#10739]
Since #10157, a few more binaries than before depend on libsodium. I understand from @pieterlexis that this is not necessary just for constant time password comparisons, because libcrypto also offers those. Perhaps we can be smarter about the dep.

**Comment by rgacogne** [comment]
Do we already link libcrypto in? In that case it would make sense to prefer it indeed.

**Comment by Habbie** [comment]
`ixfrdist` is the one I looked at and it now links both, indeed.

**Comment by rgacogne** [comment]
We already prefer `CRYPTO_memcmp` over `sodium_memcmp` when available, so I guess we did not have actually have the libcrypto development headers available, checking.

**Comment by rgacogne** [comment]
Right, I added libsodium has a dependency for building ixfrdist in 43c8ce99b6546e087e2361ec9e8f3e9eb42189df, but I guess Otto's branch in #10738 is older than that. So what do we prefer, OpenSSL or libsodium?

**Comment by omoerbeek** [comment]
> Right, I added libsodium has a dependency for building ixfrdist in [43c8ce9](https://github.com/PowerDNS/pdns/commit/43c8ce99b6546e087e2361ec9e8f3e9eb42189df), but I guess Otto's branch in #10738 is older than that. So what do we prefer, OpenSSL or libsodium?

Right, I used my moslty unused laptop for that tree and did not update the base branch correctly before creating the PR branch. Should be fie now.

**Comment by Habbie** [comment]
> So what do we prefer, OpenSSL or libsodium?

I assume I can 90% answer that with 'whatever is already present for another reason', but that does not solve the ixfrdist case. I see we have sodium on EL7 and up, and on all other distros we care about, so..

ixfrdist really is an outlier. All other software we ship pretty much always depends on both libs already.

I'm fine with closing this ticket and doing nothing :-)

**Comment by rgacogne** [comment]
Closing this since we already prefer `CRYPTO_memcmp` over `sodium_memcmp` when available.
