### ISSUE TITLE
powerdns port 53 is closed while pdns status running

### ISSUE THREAD

**Issue by mateors** [PowerDNS/pdns#10736]
- Program: Authoritative
 - Issue type: Unable to connect to port 53

### Short description
PowerDNS setup was done properly and i can check pdns is running using netstat -tapn|grep 53

I have changed the following to /etc/powerdns/pdns.conf
local-address=74.208.181.199
local-ipv6=::
local-port=53
query-local-address=
setgid=pdns
setuid=pdns

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: PowerDNS Authoritative Server 4.2.1
 - Software source: Operating system repository (apt install pdns-server & apt install pdns-backend-mysql)

### Steps to reproduce

1. 
# Unable to connect port 53
nc -z -v 74.208.181.199 53
*Output:* nc: connect to 74.208.181.199 port 53 (tcp) failed: Connection timed out

2. 
netstat -tapn|grep 53
*Output:*
tcp        0      0 74.208.181.199:53       0.0.0.0:*               LISTEN      121748/pdns_server  
tcp6       0      0 :::53                   :::*                    LISTEN      121748/pdns_server

3. 

### Expected behaviour
Connection to 74.208.181.199 53 port [tcp/domain] succeeded!

### Actual behaviour
nc: connect to 74.208.181.199 port 53 (tcp) failed: Connection timed out

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
