### ISSUE TITLE
rec: RPZ config changes should handle deletes in a proper way

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#10741]
- Program: ,Recursor,
 - Issue type: Bug report

### Short description

When the lua config is reloaded after `RPZPrimary` lines are deleted the `delayedThreads` vector still holds values for the deleted lines. This is at least a memory leak but might have other bad effects.
Maybe there are more places where deleting RPZ related lines in the config causes issues.

This part of config processing should be adapted with very clearrules about the lifetime and ownership of the objects involved.

**Comment by rgacogne** [comment]
Just a nit but I wouldn't call that a leak, as it doesn't grow over time but instead retain the values from the initial configuration even after they are no longer useful.

**Comment by omoerbeek** [comment]
I was thinking about the case were the uses repeatedly reloads the RPZ config.

**Comment by rgacogne** [comment]
Isn't the vector a temporary then?

**Comment by omoerbeek** [comment]
> Isn't the vector a temporary then?

`delayedLuaThreads` is a local var in `serviceMain` which is effectively a global. It is passed by ref to `loadRecursorLuaConfig` and `startLuaConfigDelayedThreads`.

**Comment by rgacogne** [comment]
Isn't the reload handled by `RecursorControlParser::getAnswer`? It looks to me like the path in `serviceMain` is only called once, but it might be wrong.

**Comment by omoerbeek** [comment]
Hmm, you're right. But the the call in `rec_channel_rec.cc` is a potential issue.

**Comment by omoerbeek** [comment]
To suimmarize:
the `delayedThreads` locla var in `serviceMain` gets the initial config, which has an infinite lifetime.
The one used for reloading in rec_chanel_rec.cc is a local var with limited lifetime. So the calls to the thread function should copy the objects.

**Comment by rgacogne** [comment]
> So the calls to the thread function should copy the objects.

Yes. And it might make sense to clear the content of the `delayedThreads` variable in `serviceMain` after returning from `loadRecursorLuaConfig`.

**Comment by omoerbeek** [comment]
I think everything is OK since the get<N>() calls in `startLuaConfigDelayedThreads` all return values and no refs. Currently double checking that.

**Comment by omoerbeek** [comment]
Closing this, as the issue is not actually there.
