### ISSUE TITLE
dnsdist cookie aggregation (non-hashing) failure

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#10750]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
Setting a cache to "cookieHashing=false" does not do what is expected - cookie results are "bad" for most queries, and the cookie from the first query is returned instead of the most recent query.

### Environment
 - Operating system: Linux
 - Software version: RH
 - Software source: 1.6 distro

### Steps to reproduce
Set "cookieHashing=false" on a packet cache that is filled from ECS-enabled backends.  Perform a query with a cookie. Perform the identical query a few more times. Many will result in "bad" cookie results.

### Expected behaviour
The answers from the back end will be identical, and should return the cookie from the query.

### Actual behaviour
See below.

### Other information
Here is the result from a repeated query to 9.9.9.11 (which adds ECS as part of the pool) - this qname/result was in the cache already.  First result works, second and onwards gives mostly "bad" answers as different backends are queried even though the data (including ECS results) is the same from the backend systems.
Note: we have mitigated this by moving back to "cookieHashing=true" for those packet caches, so this is not reproducable at this time on our infrastructure.
```
dig @9.9.9.11 cakepop-upstream.g.aaplimg.com
;; Warning: Client COOKIE mismatch

; <<>> DiG 9.16.19 <<>> @9.9.9.11 cakepop-upstream.g.aaplimg.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51615
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 5b77e8c9971c8a44773f5fcb614a42b3934bfa17cf1bb0d6 (bad)
;; QUESTION SECTION:
;cakepop-upstream.g.aaplimg.com.	IN	A

;; ANSWER SECTION:
cakepop-upstream.g.aaplimg.com.	3 IN	A	17.253.21.205
cakepop-upstream.g.aaplimg.com.	3 IN	A	17.253.21.204

;; Query time: 112 msec
;; SERVER: 9.9.9.11#53(9.9.9.11)
;; WHEN: Tue Sep 21 20:38:23 UTC 2021
;; MSG SIZE  rcvd: 119
```

**Comment by rgacogne** [comment]
To clarify, does any of your backends send EDNS cookie in responses? If that's the case, I'm afraid the behaviour is expected as we simply can't ignore the content of cookies then, as described in the upgrade guide:
```
This only works if the backend is not returning any answer containing EDNS Cookies, otherwise the wrong cookie might be returned to a client. To prevent this, the cookieHashing=true parameter might be passed to newPacketCache() so that cookies are hashed, resulting in separate entries in the packet cache.
```

**Comment by johnhtodd** [comment]
There are no cookies send by the EDNS-ECS backends as far as I know. They are BIND in this particular limited test case - I looked at the packets, and there did not seem to be any cookies in the responses.

**Comment by rgacogne** [comment]
I'm a bit lost, then, because that cookie in the response had to come from somewhere:
```
; COOKIE: 5b77e8c9971c8a44773f5fcb614a42b3934bfa17cf1bb0d6 (bad)
```

**Comment by rgacogne** [comment]
So the backend did send a cookie, right? It was the same one that the client sent, but it was reflected back in the response by the backend?

**Comment by rgacogne** [comment]
I checked and this seems to be Bind's default behaviour indeed, unless `answer-cookie no;` is set. I guess it would make sense to be able to (optionally, so setups where the backend is never sending back a cookie don't pay the price) check whether a response contains a DNS cookie before inserting it into the packet cache.

**Comment by rgacogne** [comment]
This can be implemented as a rule:
```lua
addResponseAction(EDNSOptionRule(EDNSOptionCode.COOKIE), SetSkipCacheResponseAction())
```
so I'm not going to add more complexity for now.
