### ISSUE TITLE
MySQL Master-Master Replication breaks 

### ISSUE THREAD

**Issue by steschuser** [PowerDNS/pdns#10752]
- Program: Authoritative
 - Issue type: Bug report

### Short description
We have two servers, each running a pdns_server.
Both have mysql backend configured and the mysql is a master-master setup.
Also, both are configured to receive DNS Updates via IXR

This works fine, except this single time when replication stopped on duplicate key
The errorlog / binlog entry for that is:
```
2021-09-17 3:54:23 82 [ERROR] Slave SQL: Duplicate entry '0-172521' for key 'PRIMARY', Gtid 0-2-273605, Internal MariaDB error code: 1062
2021-09-17 3:54:23 82 [Warning] Slave: Duplicate entry '0-172521' for key 'PRIMARY' Error_code: 1062
```
```
    at 98754597
    #210917 3:54:23 server id 1 end_log_pos 98754597 CRC32 0x7e118c21 Annotate_rows:
    #Q> update domains set last_check=1631843663 where id=1728
    #210917 3:54:23 server id 1 end_log_pos 98754666 CRC32 0x99b3a354 Table_map: `pdns`.`records` mapped to number 2392
    at 98754666
    #210917 3:54:23 server id 1 end_log_pos 98754729 CRC32 0xf6b0af57 Table_map: `pdns`.`domainmetadata` mapped to number 2395
    at 98754729
    #210917 3:54:23 server id 1 end_log_pos 98754787 CRC32 0xd48c5bac Table_map: `pdns`.`cryptokeys` mapped to number 2751
    at 98754787
```

### Environment

 - Operating system:  Debian 11
 - Software version:  4.41
 - Software source:  PowerDNS Repository

### Expected behaviour
Should work :)

Any help? Any more Info I can provide?
Best regards,
Steffen

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
