### ISSUE TITLE
returned a packet we could not parse over UDP

### ISSUE THREAD

**Issue by qp1983** [PowerDNS/pdns#10762]
- Program:  Recursor 
 - Issue type: Bug report

### Environment

 - Operating system: CentOS Linux release 7.9.2009
 - Software version: PowerDNS Recursor 4.6.0-alpha0.931.master.ge3d0a04ec
 - Software source: compiled yourself

### Steps to reproduce

1.
vi recursor.conf
local-address=0.0.0.0
local-port=5300
security-poll-suffix=
setgid=pdns-recursor
setuid=pdns-recursor
disable-packetcache
packetcache-ttl=0
dnssec=off
trace=servfail

2.
[root@localhost ~]# dig @127.0.0.1 -p 5300 tcsy.tpddns.cn

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> @127.0.0.1 -p 5300 tcsy.tpddns.cn
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 8231
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tcsy.tpddns.cn.                        IN      A

;; Query time: 376 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Sun Sep 26 11:05:58 CST 2021
;; MSG SIZE  rcvd: 43

3.
Sep 26 11:05:58 [1] tpddns.cn: Trying to resolve NS 'ns.cernet.net' (1/8)
Sep 26 11:05:58 [1] Nameserver ns.cernet.net IPs: 202.112.0.44(0.00ms)
Sep 26 11:05:58 [1] tpddns.cn: Resolved 'cn' NS ns.cernet.net to: 202.112.0.44
Sep 26 11:05:58 [1] tpddns.cn: Trying IP 202.112.0.44:53, asking 'tpddns.cn|A'
Sep 26 11:05:58 [1] tpddns.cn: Got 5 answers from ns.cernet.net (202.112.0.44), rcode=0 (No Error), aa=0, in 46ms
Sep 26 11:05:58 [1] tpddns.cn: accept answer 'tpddns.cn|NS|ns2.tpddns.cn.' from 'cn' nameservers? ttl=86400, place=2 YES!
Sep 26 11:05:58 [1] tpddns.cn: accept answer 'tpddns.cn|NS|ns1.tpddns.cn.' from 'cn' nameservers? ttl=86400, place=2 YES!
Sep 26 11:05:58 [1] tpddns.cn: accept answer 'ns1.tpddns.cn|A|52.83.168.73' from 'cn' nameservers? ttl=86400, place=3 YES!
Sep 26 11:05:58 [1] tpddns.cn: accept answer 'ns2.tpddns.cn|A|52.83.170.238' from 'cn' nameservers? ttl=86400, place=3 YES!
Sep 26 11:05:58 [1] tpddns.cn: OPT answer '.' from 'cn' nameservers
Sep 26 11:05:58 [1] tpddns.cn: determining status after receiving this packet
Sep 26 11:05:58 [1] tpddns.cn: got NS record 'tpddns.cn' -> 'ns2.tpddns.cn.'
Sep 26 11:05:58 [1] tpddns.cn: got NS record 'tpddns.cn' -> 'ns1.tpddns.cn.'
Sep 26 11:05:58 [1] tpddns.cn: status=did not resolve, got 2 NS, looping to them
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tpddns.cn: Step4 Resolve A result is No Error/0/2
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tpddns.cn: Delegation seen, continue at step 1
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Checking if we have NS in cache for 'tcsy.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: no valid/useful NS in cache for 'tcsy.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Checking if we have NS in cache for 'tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: NS (with ip, or non-glue) in cache for 'tpddns.cn' -> 'ns2.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: within bailiwick: 1,  in cache, ttl=86400
Sep 26 11:05:58 [1] tcsy.tpddns.cn: NS (with ip, or non-glue) in cache for 'tpddns.cn' -> 'ns1.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: within bailiwick: 1,  in cache, ttl=86400
Sep 26 11:05:58 [1] tcsy.tpddns.cn: We have NS in cache for 'tpddns.cn' (flawedNSSet=0)
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tpddns.cn: Step1 Ancestor from cache is tpddns.cn
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tcsy.tpddns.cn: Step2 New child
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tcsy.tpddns.cn: Step3 Going to do final resolve
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Wants NO DNSSEC processing, auth data in query for A
Sep 26 11:05:58 [1] tcsy.tpddns.cn: No cache hit for 'tcsy.tpddns.cn|A', trying to find an appropriate NS record
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Checking if we have NS in cache for 'tcsy.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: no valid/useful NS in cache for 'tcsy.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Checking if we have NS in cache for 'tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: NS (with ip, or non-glue) in cache for 'tpddns.cn' -> 'ns2.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: within bailiwick: 1,  in cache, ttl=86400
Sep 26 11:05:58 [1] tcsy.tpddns.cn: NS (with ip, or non-glue) in cache for 'tpddns.cn' -> 'ns1.tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: within bailiwick: 1,  in cache, ttl=86400
Sep 26 11:05:58 [1] tcsy.tpddns.cn: We have NS in cache for 'tpddns.cn' (flawedNSSet=0)
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Cache consultations done, have 2 NS to contact
Sep 26 11:05:58 [1] tcsy.tpddns.cn.: Nameservers: ns1.tpddns.cn(0.00ms), ns2.tpddns.cn(0.00ms)
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Trying to resolve NS 'ns1.tpddns.cn' (1/2)
Sep 26 11:05:58 [1] Nameserver ns1.tpddns.cn IPs: 52.83.168.73(0.00ms)
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Resolved 'tpddns.cn' NS ns1.tpddns.cn to: 52.83.168.73
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Trying IP 52.83.168.73:53, asking 'tcsy.tpddns.cn|A'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: ns1.tpddns.cn (52.83.168.73) returned a packet we could not parse over UDP, trying sibling IP or NS
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Trying to resolve NS 'ns2.tpddns.cn' (2/2)
Sep 26 11:05:58 [1] Nameserver ns2.tpddns.cn IPs: 52.83.170.238(0.00ms)
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Resolved 'tpddns.cn' NS ns2.tpddns.cn to: 52.83.170.238
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Trying IP 52.83.170.238:53, asking 'tcsy.tpddns.cn|A'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: ns2.tpddns.cn (52.83.170.238) returned a packet we could not parse over UDP, trying sibling IP or NS
Sep 26 11:05:58 [1] tcsy.tpddns.cn: Failed to resolve via any of the 2 offered NS at level 'tpddns.cn'
Sep 26 11:05:58 [1] tcsy.tpddns.cn: failed (res=-1)
Sep 26 11:05:58 [1] QM tcsy.tpddns.cn.|A child=tcsy.tpddns.cn: Step3 Final resolve: Server Failure/0
Sep 26 11:05:58 3 [1/1] answer to question 'tcsy.tpddns.cn|A': 0 answers, 1 additional, took 4 packets, 367.986 netw ms, 375.433 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=2

4. 
[root@localhost ~]# dig @52.83.168.73 tcsy.tpddns.cn
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> @52.83.168.73 tcsy.tpddns.                                                                                                                                                              cn
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34199
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;tcsy.tpddns.cn.                        IN      A

;; ANSWER SECTION:
tcsy.tpddns.cn.         900     IN      A       220.174.125.35

;; Query time: 46 msec
;; SERVER: 52.83.168.73#53(52.83.168.73)
;; WHEN: Sun Sep 26 11:09:18 CST 2021
;; MSG SIZE  rcvd: 48

[root@localhost ~]# dig @52.83.170.238 tcsy.tpddns.cn
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> @52.83.170.238 tcsy.tpddns                                                                                                                                                              .cn
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31408
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;tcsy.tpddns.cn.                        IN      A

;; ANSWER SECTION:
tcsy.tpddns.cn.         900     IN      A       220.174.125.35

;; Query time: 47 msec
;; SERVER: 52.83.170.238#53(52.83.170.238)
;; WHEN: Sun Sep 26 11:09:27 CST 2021
;; MSG SIZE  rcvd: 48

### Expected behaviour

dig @127.0.0.1 -p 5300 tcsy.tpddns.cn
tcsy.tpddns.cn.         900     IN      A       220.174.125.35
### Actual behaviour

dig @127.0.0.1 -p 5300 tcsy.tpddns.cn
tcsy.tpddns.cn.         900     IN      A 

errorlog:
ns1.tpddns.cn (52.83.168.73) returned a packet we could not parse over UDP, trying sibling IP or NS
ns2.tpddns.cn (52.83.170.238) returned a packet we could not parse over UDP, trying sibling IP or NS
tcsy.tpddns.cn: Failed to resolve via any of the 2 offered NS at level 'tpddns.cn'
tcsy.tpddns.cn: failed (res=-1)
QM tcsy.tpddns.cn.|A child=tcsy.tpddns.cn: Step3 Final resolve: Server Failure/0
answer to question 'tcsy.tpddns.cn|A': 0 answers, 1 additional, took 4 packets, 317.011 netw ms, 324.318 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=2

**Comment by hlindqvist** [comment]
As can be seen in your `dig` output, `dig` also observed the breakage.  
Indicated by this warning message at the top:
 ```;; Warning: Message parser reports malformed message packet.```

Seemingly some EDNS-related breakage as `+noedns` seems to make that warning in the `dig` output go away. 

It appears that it's really the authoritative side that is broken here.  
See also https://ednscomp.isc.org/ednscomp/481901d922 where seemingly everything relating to EDNS gets *malformed* as status code.

**Comment by omoerbeek** [comment]
Indeed. Both `dig` and the recursor find the packet malformed. `dig` only shows (part of) the reply since `besteffort` is on by default. As the recursor has no business guessing what the content of a malformed packet should be, I'm closing this issue. The problem should be addressed on the authoritative side.

**Comment by qp1983** [comment]
Thanks!
