### ISSUE TITLE
LIBCRYPTO_LDFLAGS ignored for linking pdns_control

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#10801]
- Program: Authoritative,
 - Issue type: Bug report

### Short description

I am trying to build Auth, on macOS, with a homebrew-provided openssl.

### Environment

 - Operating system: macOS 11.6
 - Software version: HEAD f761dbcb539ee2848186e4f5336af3f728bc22e6
 - Software source: github

### Steps to reproduce

1. `./configure '--with-modules=gpgsql gsqlite3 bind lmdb' --with-dynmodules= PKG_CONFIG_PATH=/opt/homebrew/opt/openssl/lib/pkgconfig:/opt/homebrew/opt/sqlite3/lib/pkgconfig --with-boost=/opt/homebrew --with-lmdb=/opt/homebrew --enable-unit-tests`
2. `make`

### Expected behaviour

pdns_control gets linked

### Actual behaviour

```
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++17 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGLIBDIR=\"/usr/local/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -D__APPLE_USE_RFC_3542 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -g -O2 -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls  -Wl,-pie  -lcrypto   -o pdns_control arguments.o dnslabeltext.o dnsname.o dynloader.o dynmessenger.o logger.o misc.o qtype.o statbag.o unix_utility.o
libtool: link: g++ -std=c++17 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGLIBDIR=\"/usr/local/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -D__APPLE_USE_RFC_3542 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -g -O2 -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -Wl,-pie -o pdns_control arguments.o dnslabeltext.o dnsname.o dynloader.o dynmessenger.o logger.o misc.o qtype.o statbag.o unix_utility.o -Wl,-bind_at_load  -lcrypto
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Other information

```
egrep '^LIBCRYPTO_' config.log
LIBCRYPTO_INCLUDES='-I/opt/homebrew/Cellar/openssl@1.1/1.1.1l/include'
LIBCRYPTO_LDFLAGS='-L/opt/homebrew/Cellar/openssl@1.1/1.1.1l/lib'
LIBCRYPTO_LIBS='-lcrypto'
```

**Comment by zeha** [comment]
Note that `-L/opt/homebrew/Cellar/openssl@1.1/1.1.1l/lib` is missing from the ld invocation.

**Comment by zeha** [comment]
@pieterlexis maybe you have comments :-)

**Comment by pieterlexis** [comment]
Can you find the pdnsutil rule in the generated Makefile (or upload that file)?

**Comment by rgacogne** [comment]
Does this help?
```diff
diff --git pdns/Makefile.am pdns/Makefile.am
index fa995c5c1..771fe0cc7 100644
--- pdns/Makefile.am
+++ pdns/Makefile.am
@@ -1479,6 +1479,11 @@ pdns_control_SOURCES = \
        statbag.cc \
        unix_utility.cc
 
+pdns_control_LDFLAGS = \
+       $(AM_LDFLAGS) \
+       $(DYNLINKFLAGS) \
+       $(LIBCRYPTO_LDFLAGS)
+
 if UNIT_TESTS
 noinst_PROGRAMS = testrunner
 if HAVE_BOOST_GE_148
 ```

**Comment by pieterlexis** [comment]
> Can you find the pdnsutil rule in the generated Makefile (or upload that file)?

Oh, `pdns_control`. Yes, then Remi's fix might work. But why does it need libcrypto?

**Comment by rgacogne** [comment]
I might not need it, but I guess it inherits `-lcrypto` from the generic `AM_LDFLAGS` and only realizes later that it's not actually needed.
```
AM_LDFLAGS = \
        $(PROGRAM_LDFLAGS) \
        $(LIBCRYPTO_LIBS) \
        $(THREADFLAGS)
```

**Comment by zeha** [comment]
> @zeha Does Remi's patch make it work for you?

@pieterlexis yes!
