### ISSUE TITLE
auth: backend creation before chroot() is causing startup failures

### ISSUE THREAD

**Issue by swegener** [PowerDNS/pdns#10829]
Commit d5385b3570b0d8c13626dcb4cd8fe5fc344db16d from issue #9464 creates backend instances before complete initialization like chroot()+chdir() and dropping privileges is done.
This causes backends that open files, like the gsqlite3 backend, to fail during startup.

This seems to be some unintended side-effect of the implementation.

**Comment by Habbie** [comment]
I'll be honest, I thought we didn't even have `chroot` any more. Can you tell us why you are using it?
