### ISSUE TITLE
Change "forward-zones" or "forward-zones-recurse" dynamicly

### ISSUE THREAD

**Issue by laurretang** [PowerDNS/pdns#10850]
- Program: Recursor
 - Issue type: Feature request

### Short description
Right now, whether requested domain should be queried to which ns server depends on the configuration (auth-zones, forward-zones,forward-zones-recurse) in recursor.conf.
There could be another way to change "forwarded ns" dynamicly

### Usecase
The pdns-recursor server(172.16.0.53) and a internal pdns server(172.16.0.153) are deployed in a local net(172.16.0.0/16), where several pcs configed 17216.0.53 as local dns are located in 172.16.0.0/16 too.
There is a domain named "test.com", and ip of its auth server is unstable, which is located on the internet and can not be modified.
So we can config forward-zones-recurse=test.com=8.8.8.8
It works OK, but if there is a subdomain named "diff.test.com", which need to be forwarded to the internal pdns server 172.16.0.153, that's the problem.

### Description
I read source codes and find the "forwarded ns" is decided in function getBestNSNamesFromCache().
Maybe there could be another way to change "forwarded ns" through Lua script or some else.

**Comment by laurretang** [comment]
> It's already possible to update the forward-zones list using the recursor's REST API.

There could be some misunderstanding.
In my case, some subdomains (eg. diff.test.com) should be forwarded to another ns server, while other subdomains should be forwarded the public dns (eg. 8.8.8.8).

**Comment by laurretang** [comment]
> I think I would approach this problem using dnsdist.

Do you mean config addActionw with RegexRule and actions for the special subdomains?

**Comment by omoerbeek** [comment]
I think I would use `SuffixMatchNodeRule`. Anyway, this is something to be discussed in other channels as this is more a support question than a feature request.
See https://www.powerdns.com/opensource.html 
I'm closing this.
