### ISSUE TITLE
test-dnsdist-regression (tsan) testAdvancedIncludeDirAllowed AssertionError: None != <DNS message, ID 12631>

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#10906]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

Pulling the latest `master` (0fd971037e42ce7a91ee80951f367fcda84c97e1) into a fork resulted in a failure of https://github.com/powerdns/pdns/blob/0fd971037e42ce7a91ee80951f367fcda84c97e1/.github/workflows/build-and-test-all.yml#L293 (?)

### Environment

 - Operating system: <details><summary>Ubuntu</summary>
Current runner version: '2.283.3'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20211017.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211017.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211017.0</details>
 - Software version: master
 - Software source: compiled by GitHub Action Runner

### Steps to reproduce
1. Fork repository
2. Fetch latest master
3. Get 🔔 
4. Read logs and ask if this is expected/known

### Expected behaviour
✅ 

### Actual behaviour

```
  === nosetests log ===
  ........................................................F.............................................................................................................................................................................................................................................................................................................................................................................................................................................................
  ======================================================================
  FAIL: Advanced: includeDirectory()
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/pdns/pdns/regression-tests.dnsdist/test_Advanced.py", line 1020, in testAdvancedIncludeDirAllowed
      self.assertEqual(receivedResponse, expectedResponse)
  AssertionError: None != <DNS message, ID 12631>
  -------------------- >> begin captured stdout << ---------------------
  reading data
  72
  b'9\x9b\x81\x00\x00\x01\x00\x01\x00\x00\x00\x00\nincludedir\x08advanced\x05tests\x08powerdns\x03com\x00\x00\x01\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x0e\x10\x00\x04\xc0\x00\x02\x01'
  False
  queue empty
  True
  Got from queue
  None
  
  --------------------- >> end captured stdout << ----------------------
  
  ----------------------------------------------------------------------
  Ran 502 tests in 1273.146s
  
  FAILED (failures=1)
  === end of nosetests log ===
  Error: Process completed with exit code 1.
```

**Comment by omoerbeek** [comment]
Old and likely not relevant anymore. If it happens again, please re-open.
