### ISSUE TITLE
dnsdist: setLocal() overrides addDOHLocal() but not addTLSLocal() in dnsdist.config

### ISSUE THREAD

**Issue by vincejv** [PowerDNS/pdns#10934]
- Program:, dnsdist 
 - Issue type: Bug report

### Short description

When setLocal() comes after addDOHLocal() and addTLSLocal(), it overrides the addDOHLocal() settings, but **not** the addTLSLocal() settings

### Environment
 - Operating system: Ubuntu 20.04.3 LTS
 - Software version: dnsdist 1.4.0 (Lua 5.2.4)
 - Software source: Operating system repository

### Steps to reproduce
1. Set dnsdist.conf to the following
```
addTLSLocal("0.0.0.0", "/etc/letsencrypt/.../fullchain.pem", "/etc/letsencrypt/.../privkey.pem", 
     { doTCP=true, reusePort=true, tcpFastOpenSize=64 })
addDOHLocal("0.0.0.0:15123", nil, nil, "/dns-query", { doTCP=true, reusePort=true, tcpFastOpenSize=64 })
setLocal("127.0.0.1:5336")
```
2. Start dnsdist

### Expected behaviour

dnsdist will only listen for DO53 on 5336

### Actual behaviour

dnsdist listens on 853 for DOT and 5336 for DO53

### Other information

I figured that this is an unintended behavior because setLocal() should also override addTLSLocal settings, not just addDOHLocal settings

**Comment by rgacogne** [comment]
We actually changed the behaviour of `setLocal` in 1.5.0 to not override `addDOHLocal` either, as most users expected `setLocal` to only override `addLocal` statements. I think the best option might be to get rid of `setLocal` entirely, and I'll ponder deprecating it in 1.7.0.

**Comment by vincejv** [comment]
got it, thanks @rgacogne, seems like it's a known issue closing this now.
