### ISSUE TITLE
Recursor: Wrong EDE when DNSKEY signatures have expired

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#10936]
- Program: Recursor
 - Issue type: Bug report

### Short description
When resolving servfail.nl|AAAA, the recursor returns a SERVFAIL with EDE code 9 (DNSKEY missing) instead of code 7 (signature expired).

The EDE code definitions in RFC 8917:

7:

> The resolver attempted to perform DNSSEC validation, but no signatures are presently valid and some (often all) are expired.

9:

> A DS record existed at a parent, but no supported matching DNSKEY record could be found for the child.

9 is wrong because the DNSKEY belonging to the DS record in the parent exists. However, because all signatures in the zone are expired (including the DNSKEY ones), see [dnsviz](https://dnsviz.net/d/servfail.nl/YX_JZA/dnssec/).

### Environment
 - Operating system: Arch Linux
 - Software version: master at b1f97a4cc7d2d9197fbb7b2745a255dc65860023
 - Software source: Compiled myself

### Steps to reproduce
1. `./pdns_recursor --local-port=5301  --socket-dir=. --extended-resolution-errors --dnssec=validate`
2. `dig @127.0.0.1 -p5301 servfail.nl +rec +dnssec +ad +endsopt=15`

### Expected behaviour
EDE option 6 in the response.

### Actual behaviour
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
; EDE: 9 (DNSKEY Missing)
```

### Other information
The trace shows we see the right condition:

```
Nov 01 16:05:31 Signature is expired (inception: 1586339579, inception skew: 60, expiration: 1586350379, now: 1635779131)
Nov 01 16:05:31 Validation did not succeed!
```

From some discussions:

* `checkSignatureWithKey` does not distinguish between the various cases
* It looks like `validateDNSKeysAgainstDS` falls into the return `vState::BogusNoValidDNSKEY` case
* it should take into consideration why `checkSignatureWithKey` decided a sig was invalid

**Comment by omoerbeek** [comment]
> EDE option 6 in the response.

I think this should be 7?
