### ISSUE TITLE
Python Sphinx failing make in Recursor

### ISSUE THREAD

**Issue by InputOutputZ** [PowerDNS/pdns#10942]
- Program: Recursor
 - Issue type: Building failure.

### Short description
Running make command fails at generating documentation using sphinx.

### Environment
 - Operating system: Linux/centOS 7
 - Software version: rec-4.6.0-alpha2, python3.9, gcc 8
 - Software source: PDNS Git.

### Steps to reproduce
1- ./configure
2- make

### Expected behaviour
Successful make 

### Actual behaviour
```
Running Sphinx v1.8.5
building [mo]: targets for 0 po files that are specified
building [man]: 1 source files given on command line
updating environment: 99 added, 0 changed, 0 removed
/root/pdns/pdns/recursordist/.venv/lib64/python3.6/site-packages/changelog/sphinxext.py:331: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  bold('The name of the builder is: %s' % app.builder.name), nonl=True)
The name of the builder is: man
Exception occurred:
  File "/root/pdns/pdns/recursordist/.venv/lib64/python3.6/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-07ex39d3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[2]: *** [pdns_recursor.1] Error 2
make[2]: Leaving directory `/root/pdns/pdns/recursordist'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/pdns/pdns/recursordist'
make: *** [all] Error 2
```

### Other information
It seems, other projects over the last period had issues with recent sphinx update, per following source.
https://github.com/sphinx-doc/sphinx/issues/9727. Docutils version had to be 0.17.

I was able to ignore deprecation warning errors using make --ignore-errors or modifying sphinxext.py. file with appending at top
```
import warnings
warnings.filterwarnings("ignore")
```

**Comment by omoerbeek** [comment]
Should be fixed by #10902

**Comment by InputOutputZ** [comment]
I think this is not committed to rec-4.6.0-alpha2 as well as dnsdistdist and auth, refer to https://github.com/PowerDNS/pdns/blob/rec-4.6.0-alpha2/pdns/recursordist/docs/requirements.txt.

With thanks.

**Comment by omoerbeek** [comment]
Indeed, it's not in rec-4.6.0-alpha2, but it will bne in the next pre-release, likely rec-4.6.0-beta1 due next week.

**Comment by SivaKesava1** [comment]
#10902 indeed fixes the issue, but is there a way to `configure` the repository without `sphinx` (like `./configure --without-sphinx` or some other way)? That would be really helpful for auto-building the repo at an earlier commit without modifying any of the requirements files.
