### ISSUE TITLE
auth+recursor build: systemd runtimedirectory feature detection is reversed

### ISSUE THREAD

**Issue by ozopz** [PowerDNS/pdns#10958]
It turns out that we are shipping `%t` in the systemd unit file for EL7, but not for Debian10. We should be shipping it for Debian10, and it's unclear whether we should be shipping `%t` for EL7. It is clear that EL7.6 does not support it, but we don't know about EL7.9. In any case the logic in `recursordist/Makefile.am` for adding the `%t` is reversed from what it should be.

auth appears to have the same issue.

-@Habbie

------------------

 - Program: Recursor
 - Issue type: Bug report

### Short description
Hi, I'm currently using pdns recursor 4.4.0 alpha and I want to upgrade to 4.5+, the issue I experience
is that upon upgrading the service shuts down because my hint-file points to /dev/null
I do that because I have a closed environment that uses a forward-zones file
with no root servers, so I dont need a hint file.
I tried to point the hint-file to itself (. NS example , example A 127.0.0.1) and the service started.
Unfortunatly the service couldnt solve any queries after this change.
Can you create an option to direct the hint-file to /dev/null like in 4.4.0 alpha for higher verisons?

### Environment
 - Operating system: RHEL 7.6
 - Software version: 4.4.0-alpha1
 - Software source: PowerDNS repository

### Steps to reproduce
1. recursor.conf settings : 
allow-from=x.x.x.x/x
daemon=False
forward-zones-file = /etc/pdns-recursor/forward-zones.conf
hint-file=/dev/null
quiet=yes
local-port=53
non-local-bind=True
logging-facility=0
security-poll-suffix=
2. Thats it, this conf wont work in higher versions.

### Expected behaviour
The service should stay running and solve queries.

### Actual behaviour
The service shuts down and tries to restart constantly providing the next message:
Running IPv4 only but no IPv4 root hints
Priming cache failed, stopping
### Other information
I tried to use 4.5.6 and 4.4.6 and the issue accured on both versions.

**Comment by omoerbeek** [comment]
Did you try not setting a hint file?

**Comment by ozopz** [comment]
> Did you try not setting a hint file?

I tried it, the service starts up but cant answer queries.

**Comment by omoerbeek** [comment]
With no hint-file: start the recursor with --trace and show us the log

**Comment by ozopz** [comment]
> With no hint-file: start the recursor with --trace and show us the log

Here is the last part of the logs (rest of the log looks fine and without errors).
```
Insufficient number of filedescriptors available for max-mthreads*threads setting! (4096 < 4121), reducing max-mthreads to 2035
Problem with socket directory %t/pdns-recursor: itdoes not exist or cannot access; see https://docs.powerdns.com/recursor/upgrade.html#x-to-4-3-0-or-master
```

**Comment by omoerbeek** [comment]
So did you read the mentioned URL? The last log line does not have anything to do with hint files. Plesse fix that before anything else.

**Comment by pieterlexis** [comment]
What is the value of `socket-dir` in your recursor.conf? And have you updated/overridden the service file in any way (`/etc/systemd/systemd/pdns-recursor*`)?

**Comment by ozopz** [comment]
> So did you read the mentioned URL? The last log line does not have anything to do with hint files. Fix that before anything else. https://docs.powerdns.com/recursor/upgrade.html#socket-dir-changed will get you to the exact spot.

I've read it, unfortunatly the explanation there is unclear to me, I'm having trouble with making the service work properly again.

> What is the value of `socket-dir` in your recursor.conf? And have you updated/overridden the service file in any way (`/etc/systemd/systemd/pdns-recursor*`)?

I dont have the 'socket-dir' option defined in my conf, so its the default value.
When I updated from 4.4.0-alpha I noticed that in the service file the 'socket-dir=%t/pdns-recursor' appeared, other than that nothing changed in the service file between the versions.

**Comment by omoerbeek** [comment]
You seem to be running an older systemd that the one that is expected.

Our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.
