### ISSUE TITLE
Nov 27 14:27:38 Lua record reported: Exception thrown by a callback function called by Lua: Unable to convert presentation address 'cname.com'

### ISSUE THREAD

**Issue by sddwt** [PowerDNS/pdns#11040]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using lua record:
return pickwrandom({{1,'x.com'}, {2,'mcn.com'}})
then nslookup -qt=cname cname.com
then server shows error:
Nov 27 14:27:38 Lua record reported: Exception thrown by a callback function called by Lua: Unable to convert presentation address 'x.com'

### Environment

 - Operating system: centos7.9
 - Software version: 4.2.3
 - Software source: PowerDNS repository

### Expected behaviour
I would like to correctly resolve the cname return.
Could you tell me how to achieve that? Thanks.

**Comment by sddwt** [comment]
I think pickwrandom doesn't support cname type.

**Comment by mnordhoff** [comment]
Unfortunately, it only supports IP addresses.

If you know Lua, you could write something similar to `pickwrandom` that supports arbitrary strings.

(Someone else recently ran into this with `pickrandom`, but I don't think an issue was filed.)

**Comment by sddwt** [comment]
> pickrandom

Thank you. I think I can do something same as `pickwrandom`.

**Comment by sddwt** [comment]
bty, is there a way to include a public lua file? I don't think it's a good idea to claim a function in every lua record?
Thanks.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
