### ISSUE TITLE
PDNS LDAP/SQL Configuration Backend

### ISSUE THREAD

**Issue by Mose-** [PowerDNS/pdns#11112]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description

The ability to have configurations stored in LDAP/SQL backends in addition to flat file configurations.
### Usecase

Similar to postfix, the ability to store application configuration data in various backends.
### Description

As an example, postfix offers robust configuration options. You can configure postfix to read configurations from a variety of sources, including LDAP & SQL which are aggregated by the service:

```
alias_maps = hash:/etc/aliases, ldap:/etc/postfix/ldap-aliases.cf, mysql:/etc/postfix/mysql-aliases.cf
```

I think incorporating configuration options such as postfix does above would be a powerful feature for the PDNS software stack. In larger environments, especially MSP's storing much of the configuration data in LDAP/SQL backends provides huge management options. This would allow for concepts such as profiles that groups of PDNS servers to read configuration data from a centralized repository during service start up.

In closing, I realize this would be outside of the standard software development track, however I strongly believe such options would promote increased adoption of PDNS, especially in todays automation & virtualized environments.

**Comment by Habbie** [comment]
Hello, I don't think I understand your request. Postfix allows you to store user data in databases; PowerDNS also allows that. What are you asking for that PowerDNS does not already does?

**Comment by Mose-** [comment]
PDNS stores configuration settings in `/etc/pdns/pdns.conf` & `/etc/pdns/recursor.conf`. The DNS zones & RR records themselves are stored in various database backends.

What I am suggesting is to consider adding support to PDNS software that would permit storing the configuration settings  themselves in DB backends (i.e. [pdns.conf](https://gist.github.com/Habbie/5466611)).

```
dn: dc=example,dc=com,ou=dns,dc= mycompany,dc=com
objectClass: top
objectClass: PdnsConfig
dc: example
PdnsAllow-axfr-ips: 0.0.0.0/0
PdnsAllow-recursion: 0.0.0.0/0
PdnsConfig-name: cluster1
PdnsDaemon: no
....
```

This would allow the config settings themselves to be stored in LDAP/SQL that could be read from those sources on service start up. In larger environments, this would be a preferable centralized management then having to enlist external tools such as ansible or puppet to push flat file updates and is easier integrated in modern DevOps environments.

**Comment by Habbie** [comment]
That sounds like something somebody could write a wrapper for, to generate the files at startup.

**Comment by Habbie** [comment]
> That sounds like something somebody could write a wrapper for, to generate the files at startup.

Sticking with this view, closing.
