### ISSUE TITLE
dnsdist: Caching of invalid NOTIFY responses might prevent valid NOTIFY

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#11135]
- Program: dnsdist
 - Issue type: Bug report

### Short description
dnsdist in front of an Auth server seems to put refused notify responses in its packet cache based on `temporaryFailureTTL` regardless of source which prevents a following valid notify from reaching the Auth server.

### Environment
 - Operating system: Ubuntu 20.04
 - Software version: 1.6.1-1pdns.focal
 - Software source: PowerDNS repo

### Steps to reproduce
1. Put pdns behind dnsdist with PROXY protocol and configure packet cache
2. Send DNS notify from non-primary IP
3. Send DNS notify from primary IP

### Expected behaviour
2nd notify from proper primary IP reaching the Auth server and not being handled by packet cache.

### Actual behaviour
2nd notify handled by packet cache and resulting in immediate REFUSED response.

### Other information
This might be a bit of a not very common edge case, especially as it needs the PROXY protocol (or another way to pass the real client IP to Auth) - but it still blocks valid NOTIFY messages for the duration of `temporaryFailureTTL`. On the other hand this behavior makes some sense when considering how a packet cache works..
I could think of some configuration workarounds of not caching SOA messages that are notifies or using a lower `temporaryFailureTTL` for these. I ended up using the following action:
```
 addAction(AndRule({OpcodeRule(DNSOpcode.Notify), QTypeRule(DNSQType.SOA)}), SetSkipCacheAction())
```
Given that valid notifies are (of course) not cached I guess the proper solution might be not to cache "refused" replies for incorrect ones - or cache them based on source IP however that might be a more complicated topic.. especially as all other Auth replies (in my use case) are not source-dependent so the whole fancy ECS handling is not in use.
The current behavior might have certain side-effects on timely secondary NS updates when faced with a continuous stream of invalid notifies.
I wonder if this needs a fix or if we are fine with adding some documentation about that behavior, e.g. to [`pdns/pdns/dnsdistdist/docs/advanced/axfr.rst`](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/docs/advanced/axfr.rst) - but that might be missed.
(I just noticed that this file might need an update to mention the PROXY protocol or other ways of passing client information)

**Comment by rgacogne** [comment]
Thanks for reporting this!

On one hand I think it would make sense not to cache `NOTIFY` responses by default in dnsdist, of course, since it will never do the right thing in front of an authoritative server. On the other hand it might be useful to cache these in front of a recursor, although the PowerDNS recursor itself is learning how to handle some `NOTIFY` messages (https://github.com/PowerDNS/pdns/pull/10751).
I will think about it, and it would be nice to add a few words in the documentation already so that your work-around is documented.
