### ISSUE TITLE
Request to support specifying port for authoritative master/slave setup

### ISSUE THREAD

**Issue by guicailiao** [PowerDNS/pdns#11130]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Could we support specifying port for authoritative master notifying authoritative slaves in master/slave setup. 
According to below codes,  current logic is:
1.  query nameservers or A records for the zone to be notified.
2.  use hard coded port `53` .
3.  notify the slaves according to the ip together with port `53`.
https://github.com/PowerDNS/pdns/blob/rel/auth-4.6.x/pdns/mastercommunicator.cc#L55-L74 

### Justification
Since we already support [using custom port](https://doc.powerdns.com/authoritative/settings.html#local-address) in DNS service provided by powerdns authoritative,  support setting custom port in master/slave mode for customers is convenient and helpful. 

master/slave setup(appendix): 
https://doc.powerdns.com/authoritative/modes-of-operation.html#autoprimary-automatic-provisioning-of-secondaries 

### Usecase
We could use custom port in powerdns authoritative service and use custom port for master/slave sync.

### Description
We could simply add a config setting(axfr-notify-port for example), and use it in below codes.
https://github.com/PowerDNS/pdns/blob/rel/auth-4.6.x/pdns/mastercommunicator.cc#L66

**Comment by zeha** [comment]
IIRC you can have that today, by setting `also-notify` to ip:port.

**Comment by guicailiao** [comment]
Thanks @zeha,  

It works for notifying.

 But the slaves still try to query  master authoritative with port 53, and it failed then.

**Comment by zeha** [comment]
On the secondaries you have to add the port into the zone’s “masters” field.

**Comment by guicailiao** [comment]
Thanks for your help.


Do you mean the `supermasters` table of authoritative slave server?
I have changed it but it doesn't work. 

Would you please be more clear about ading port in to zone's "masters" field?

**Comment by guicailiao** [comment]
after running below commands in secondary authoritative, it works.
```
pdnsutil change-slave-zone-master corp.com 10.26.161.10:5300
```

Does that means we could not use supermaster feature if we use customized port for authoritative?
