### ISSUE TITLE
dnsdist: setRCodeRatio Warning mechanism doesn't seem to work

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#11131]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
The  Warning parameter in the `setRCodeRatio()` function, isn't triggered

### Environment
 - Operating system: Centos 8
 - Software version: 1.6.1
 - Software source:  PowerDNS repository
 - 
### Steps to reproduce
1. Configure dnsdist with:
```
local dbr = dynBlockRulesGroup()
dbr:setRCodeRatio(DNSRCode.NXDOMAIN, 0.9, 10, "Exceeded NXD ratio", 60, 1, DNSAction.Drop, 0.1)

function maintenance()
  dbr:apply()
end
```

2. Try to trigger the Warning by querying random names returning an NXDomain, alternated with entries that do return a value. Don't forget to disable your packetCache for the test.

### Expected behaviour
As long as more than 10% but less than 90% of the queries return an NXDomain, I would expect a Warning to be issued. This should be visible in the system logs, as in the `showDynBlocks()` output. The test above should generate 50% NXDomains so the Warning should trigger.

### Actual behaviour
No warning is triggered. By skipping the "correct" lookup and thus pushing the ratio above 90%, we do see the block happening.

### Other information
See info to be provided by @omoerbeek  and @dwfreed 

While looking at the issue, might clarify the docs as well (double vs int, example code?)

**Comment by omoerbeek** [comment]
https://github.com/PowerDNS/pdns/blob/72fdd54cb41f3857d761a774df933410848459a1/pdns/dnsdist-dynblocks.hh#L180
Is supect. It should likely test for `d_warningRatio` and not `d_warningRate`. Also comparing it to `ratioExceeded`, maybe `warningRatioExceeded` should also test for `d_enabled`?

**Comment by dwfreed** [comment]
> https://github.com/PowerDNS/pdns/blob/72fdd54cb41f3857d761a774df933410848459a1/pdns/dnsdist-dynblocks.hh#L180
> 
> 
> Is supect. It should likely test for `d_warningRatio` and not `d_warningRate`. Also comparing it to `ratioExceeded`, maybe `warningRatioExceeded` should also test for `d_enabled`?

Yep, `d_warningRate` is initialized to 0 in the call to the constructor for `DynBlockRule` and never updated after:

https://github.com/PowerDNS/pdns/blob/c00526be332259774d2d66d0826377042b48aea5/pdns/dnsdist-dynblocks.hh#L160
https://github.com/PowerDNS/pdns/blob/c00526be332259774d2d66d0826377042b48aea5/pdns/dnsdist-dynblocks.hh#L77

Guessing this was just a copy/paste of the `DynBlockRule` implementation, and someone missed updating that test.  Checking `d_enabled` as first short-circuit would also be a good idea, as `DynBlockRatioRule` also has a zero-argument constructor that has it set to false.
