### ISSUE TITLE
pdnsutil edit-zone won't take no for an answer

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#11142]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When editing a zone, and not increasing serial, pdnsutil will not accept no for answer whether I want to increase serial or not.

### Environment
 - Operating system: Debian GNU/Linux 10 (buster)
 - Software version: 4.7.0-alpha0.15.master.g4d441189b
 - Software source: PowerDNS repository

### Steps to reproduce
1. Edit existing zone
2. Make change
3. Do not update serial
4. Save & quit
5. Answer 'n' to the question `You have not updated the SOA record! Would you like to increase-serial?`
### Expected behaviour
I expect it to apply changes.

### Actual behaviour
`You have not updated the SOA record! Would you like to increase-serial?`

### Other information

This was the real zone name as I was doing testing...

```
# pdnsutil edit-zone test.unit
Checked 4 records of 'test.unit', 0 errors, 0 warnings.
Detected the following changes:
+*.test.unit 3600 IN A 1.2.3.4

You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
n
You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
n
You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
n
You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
n
You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
n
You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit:
y
(a)pply these changes, (e)dit again, (r)etry with original zone, (q)uit: a
Adding empty non-terminals for non-DNSSEC zone 'test.unit', 2 updates
```

**Comment by Habbie** [comment]
Broken since #10513.

Additionally, I just noticed that responding `e` for edit, then making no -additional- edits and closing the editor, exits pdnsutil, discarding all changes.
