### ISSUE TITLE
dnsdist webserver issues

### ISSUE THREAD

**Issue by lgwapnitsky** [PowerDNS/pdns#11149]
When setting a password and API key in the latest dnsdist (as of 2022-01-06), I'm receiving the following on startup:

```
Jan 06 09:12:32 dnsdist dnsdist[890]: Fatal Lua error: [string "chunk"]:4: This function requires at most 1 parameter(s)
                                      stack traceback:
                                              [C]: in function 'webserver'
                                              [string "chunk"]:4: in main chunk

```

Additionally, when not specifying either password or api key, I'm unable to access the webserver on any port

```
webserver("0.0.0.0:9999", "password", "12345")  

```

**Comment by Habbie** [comment]
https://dnsdist.org/reference/config.html#webserver mentions

> Changed in version 1.6.0: The password parameter is now optional. The use of optional parameters is now deprecated. Please use setWebserverConfig() instead.

However, https://dnsdist.org/guides/webserver.html still has the old, now broken, syntax.

I'll mark this is as a documentation ticket so we can fix that.

**Comment by lgwapnitsky** [comment]
great, thank you.

Any ideas on why it's not responding on the port for the web server?
Vanilla install of ubuntu 20.04 with only dnsdist installed

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
nevermind.  it was the acl

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*
