### ISSUE TITLE
pdnsutil create-zone not follow the pdns.conf mode

### ISSUE THREAD

**Issue by navotera** [PowerDNS/pdns#11193]
**Environment**
PowerDNS : 4.5

 - Program: pdnsutil create-zone
 - Issue type: Feature request

### Short description
When creating zone with pdnsutil create-zone command, although the server is configured as master / primary as we have configured on the pdns.conf : 
<pre>
config-dir=/etc/powerdns
setuid=pdns
setgid=pdns
**primary=yes**
</pre> 

It still does not save to pdns.domains table as type **MASTER** but still uses the default type as: **NATIVE**. 

<pre>
+----+-----------+--------+------------+--------+-----------------+---------+
| id | name      | master | last_check | type   | notified_serial | account |
+----+-----------+--------+------------+--------+-----------------+---------+
|  1 | domain.com |        |       NULL | NATIVE |            NULL |         |
+----+-----------+--------+------------+--------+-----------------+---------+
</pre>

### Usecase
I think this command should follow the type based on the chosen mode on the pdns.conf. 
Or it should be provided some parameter on pdnsutil create-zone for example 
  `pdnsutil create-zone domain.com MASTER`

Thanks

**Comment by cmouse** [comment]
You can workaround this with

```
pdnsutil create-zone foo.com
pdnsutil set-kind foo.com primary
```

**Comment by cmouse** [comment]
The setting `primary=yes` enables primary functionality, it does not necessarily mean that all zones should be created or be primary zones.

**Comment by navotera** [comment]
Thank you for your suggestions.
