### ISSUE TITLE
Fix OpenSSL 3 deprecation warnings

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#11198]
#11196 fixes building with OpenSSL 3, but the compile emits a ton of deprecation warnings. We should deal with those before they turn into errors or removals.

**Comment by fredmorcos** [comment]
Fixed by #12401, #12411, #12412, #12414, #12423, #12462, #12501, #12502, #12513, #12514, #12515, #12516, #12524, #12527, #12540 and #12550

**Comment by fredmorcos** [comment]
Fixed by #12401, #12411, #12412, #12414, #12423, #12462, #12501, #12502, #12513, #12514, #12515, #12516, #12524, #12527, #12540 and #12550
