### ISSUE TITLE
User level api token

### ISSUE THREAD

**Issue by zozo6015** [PowerDNS/pdns#11192]
- Program: Authoritative 
 - Issue type: Feature request

### Short description
I would like to have an user level api access with the user having it's own token to manage the zones that are tied to it's account.
### Usecase
In the offering we have kubernetes and using the certmanager would be impossible at this moment because that would mean to give out our generally used API token.

### Description

Would be nice to have an user level API where the user can generate an API key to manage it's own zones. This API would work exactly as the general api but would be limited to the zones that are managed by the user.

**Comment by Habbie** [comment]
We have no plans to do this - perhaps https://github.com/catalyst/powerdns-auth-proxy is useful?
