### ISSUE TITLE
dnsdist: net-snmp-config.h may define HAVE_LIBSSL, breaking non-libssl builds

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#11204]
While we use `HAVE_ LIBSSL` internally to see if we are building & linking against OpenSSL. However, `net-snmp-config.h` may also define `HAVE_LIBSSL`. This then reaches `dnsdist-lua.cc` (which includes `dnsdist.hh` which includes `dnsdist-snmp.hh`) resulting in:

```
dnsdist-lua.cc:2789:29: error: 'libssl_load_engine' was not declared in this scope
```

when building -with- SNMP but -without- OpenSSL.

Possible fixes:
- rename our define to `PDNS_HAVE_LIBSSL`
- refactor a bunch of things so the defines from `net-snmp-config.h` don't affect our code so much
-

**Comment by tomarcade** [comment]
Currently reaching this behavior. Is there a workaround for successful building with installed OpenSSL and net-snmp?

**Comment by rgacogne** [comment]
I guess the easiest work-around would be to enable DNS over TLS (`--enable-dns-over-tls`) or DNS over HTTPS (`--enable-dns-over-https`) in dnsdist so that `HAVE_LIBSSL` is set in our own `config.h` in addition to `net-snmp-config.h`.

**Comment by tomarcade** [comment]
@rgacogne : Yes, that works, thank you.
