### ISSUE TITLE
dnsdist: Add an option to create BPF maps without launching the filter

### ISSUE THREAD

**Issue by MiniPierre** [PowerDNS/pdns#11209]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Now that BPF maps can be pinned and used by external program, the fact that the dnsdist BPF filter still block IP could be troublesome

### Usecase
Using an external program to perform TC based on values inserted in the dnsdist BPF map, I came with the issue that when a client IP is blocked, the client that get a TC answer and retry with TCP is blocked by the dnsdist BPF program

### Description
It would be useful to have an option that let dnsdist populate maps (using DynBPFFilter for example) but not run the associated program.

**Comment by rgacogne** [comment]
Looks like I forgot to add that to the document but `newBPFFilter` now takes a fourth optional boolean parameter, `external`, which should not load the internal eBPF program when set to `true`. Would you be able to test that?

**Comment by MiniPierre** [comment]
When I switch `external` back to false, I've got the same error, but I can use my external program after re-deleting maps and restart dnsdist

**Comment by MiniPierre** [comment]
Okay I see, with `external` set to true you create maps with a different index/value type than when it is created with false

**Comment by rgacogne** [comment]
You are right, it does update the value type. You can look at the XDP sample in contrib for the new format which allows having different actions per entry: https://github.com/PowerDNS/pdns/blob/master/contrib/xdp-filter.ebpf.src#L100

**Comment by rgacogne** [comment]
I see that the `uint8_t` on the enum stayed in that file, which might be an issue if you are not using a compiler accepting that extension. I should get rid of it.

**Comment by rgacogne** [comment]
It also changes the key type for the qname map, the new one being close to what you were using initially, if I remember correctly.

**Comment by MiniPierre** [comment]
I know, I developed it :smile: 
How does the DynBPFFilter set the corresponding dns_action when a BPFFilterDynBlock does block an IP ?

**Comment by rgacogne** [comment]
> I know, I developed it

Yeah, you did :)

**Comment by rgacogne** [comment]
> How does the DynBPFFilter set the corresponding dns_action when a BPFFilterDynBlock does block an IP ?

It depends on how you use the Dynamic Blocks:
- `BPFFilter::block` now accepts an optional action
- the `DynBlockRulesGroup::set*` also accept an action

Any reason you are still using a `BPFFilterDynBlock` and not a `DynBlockRulesGroup`? I did not know it was still used.

**Comment by MiniPierre** [comment]
No specific reason, it is something we used and I performed my tests with this old configuration, we'll have a look at the DynBlockRulesGroup

**Comment by MiniPierre** [comment]
Anyway, thanks for your answers, I'll try to make everything work together tomorrow and close the issue if everything's fine

**Comment by rgacogne** [comment]
At the very least I need to fix the documentation, so please report back but don't close the issue just yet if you don't mind!

**Comment by MiniPierre** [comment]
No problem, I'll do that

**Comment by MiniPierre** [comment]
Hey, seems that everything's working as expected

**Comment by rgacogne** [comment]
Great, thanks for the feedback!

**Comment by MiniPierre** [comment]
I actually have a problem with the fact that my enum is not typed with uint8_t, you were right with changing it in the XDP example. I have to find a way to make it work

**Comment by MiniPierre** [comment]
Found a way to ensure that the returned dns_action is typed as uint8_t, everything's working fine now
Thank you for implementing this, it will help us a lot

**Comment by rgacogne** [comment]
I finally merged the documentation update in #11548, closing this now.
