### ISSUE TITLE
Ignore unnecessary notifies

### ISSUE THREAD

**Issue by gringus** [PowerDNS/pdns#1120]
Recently I came across interesting problem with notifies and bind backend. Our setup consist of Bind master and PowerDNS 3.3 slaves. PowerDNS slaves are configured with:

<pre>
slave=yes
bind-config=/etc/pdns/bind.conf
</pre>

statements. Zones are defined as:

<pre>
zone "example.com" IN {
        type slave;
        file "slave/example.com.zone";
        masters { 10.0.0.1; };
};
</pre>
The thing is that PowerDNS accepts all notifes and tries to process them as they arrive. It accepts notifies for zones it doesn't know about (not configured) from any host (not master). In such scenario I'm able to send notify for zone foo.com from any host and PowerDNS will try to get SOA from the host which sent notify. PowerDNS will wait up to 3s and move on to the next notify. Sample log lines:

<pre>
Nov 22 13:09:31 kvm-01 pdns[12772]: Received NOTIFY for foo.com from 10.146.69.21 for which we are not authoritative
Nov 22 13:09:35 kvm-01 pdns[12772]: Error resolving SOA or NS for foo.com at: 10.146.69.21: Timeout waiting for answer from 10.146.69.21
</pre>

PowerDNS should ignore notifies for zones it doesn't slave and accept them only from defined master(s) (and not other hosts).

**Comment by Habbie** [comment]
Fixed by merge of #1953
