### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by thb007** [PowerDNS/pdns#11229]
![$X{{PW3{2$DE4P3`VTE_27K](https://user-images.githubusercontent.com/17548936/150637498-5341a733-2cef-45aa-b697-5ce3bca6cb03.png)

![L)0KO~}B_QG9 UF0)B0A{24](https://user-images.githubusercontent.com/17548936/150637508-e129b7d6-b959-4236-8ee7-211f1b5618fb.png)

![B7~BEE WZ_D82)OWI4`OZ(0](https://user-images.githubusercontent.com/17548936/150637511-de2b7ebd-0083-46b0-b039-f8b255cc7466.png)

**Comment by mnordhoff** [comment]
Because the file is in `/etc/powerdns/recursor.d/`, Recursor is probably trying to **also** parse it as an included configuration file.

Try moving it to `/etc/powerdns/` (and updating `forward-zones-path` with the new path).

**Comment by omoerbeek** [comment]
Or rename the`forward.conf` file to not have a `.conf` suffix

**Comment by omoerbeek** [comment]
The issue tracker is not for support questions, see https://docs.powerdns.com/recursor/#getting-support
I'm closing this ticket.

**Comment by thb007** [comment]
> The issue tracker is not for support questions, see https://docs.powerdns.com/recursor/#getting-support I'm closing this ticket.

Why can't this be resolved

![NV%E}K1~_I (G@NMWS8L9B](https://user-images.githubusercontent.com/17548936/150638226-59565702-cd3f-451b-9da5-3d4da4f3da2a.png)

**Comment by thb007** [comment]
@omoerbeek

**Comment by omoerbeek** [comment]
Please read what I wrote in my previous comment
