### ISSUE TITLE
Cannot access virtual instance socket with pdns_control because of control socket name mismatch

### ISSUE THREAD

**Issue by elbaby** [PowerDNS/pdns#11228]
- Program: Authoritative  
 - Issue type: Bug report

### Short description
`pdns_control` uses _always_ `pdns.controlsocket` as the control socket name (irregarding of the virtual instance). However, `pdns_server` sets the control socket name as `pdns-INSTANCE_NAME.controlsocket` when using virtual instances.

### Environment

 - Operating system: Debian 11
 - Software version: 4.5.2
 - Software source: PowerDNS repository

### Steps to reproduce

1. Configured virtual instance EXTERNO in `/etc/powerdns/pdns-EXTERNO.conf`
2. Started virtual instance with `sudo systemctl start pdns@EXTERNO.service`
3. Was able to access backend with `sudo -u pdns pdnsutil --config-name EXTERNO <command>` without a problem
4. Tried to control server with `sudo -u pdns pdns_control --socket-dir=/var/run/pdns-EXTERNO current-config` but didn't work
5. Also tried `sudo -u pdns pdns_control --config-name=EXTERNO --socket-dir=/var/run/pdns-EXTERNO current-config` but didn't work either (though, from the docs, I understand that the `--config-name` option is to _change_ the instance name, and not to refer to it

### Expected behaviour

The command should've shown the EXTERNO instance configuration

### Actual behaviour

I get the following error in the terminal:
```
Fatal error: Unable to connect to remote '/var/run/pdns-EXTERNO/pdns.controlsocket': No such file or directory
```

### Other information

After checking, the actual socket created by the instance is `/var/run/pdns-EXTERNO/pdns-EXTERNO.controlsocket`

I tried to look for either a command line option to set the socket _name_ in either pdns_server or pdns_control, but I can only configure the socket _directory_.

There doesn't seem to be an option to change the socket name in `pdns.conf`

This is my configuration file: [pdns-EXTERNO.conf](https://github.com/PowerDNS/pdns/files/7916094/pdns-EXTERNO.conf.txt)

**Comment by elbaby** [comment]
I cloned the repo and browsed the code. I don't consider myself able to modify/compile the source, test it and create a merge request, but I think I spotted where to fix the problem.

In [ rec_control.cc lines 103-104](../blob/master/pdns/rec_control.cc#L103) I think is where `pdns_server` sets the control socket name (taking into account the **config-name**).

However, in [dynloader.cc lines 96-106](../blob/master/pdns/dynloader.cc#L96) `pdns_control` sets the control socket name as `pdns.controlsocket` without considering the **config-name**.

**Comment by candlerb** [comment]
In dynloader.cc:

```
int main(int argc, char **argv)
{
  string s_programname="pdns";
...
  if(::arg()["config-name"]!="") 
    s_programname+="-"+::arg()["config-name"];
...
  socketname += "/" + s_programname + ".controlsocket";
```

**Comment by elbaby** [comment]
> I don't think that is correct. In dynloader.cc:
> 
> ```
> int main(int argc, char **argv)
> {
>   string s_programname="pdns";
> ...
>   if(::arg()["config-name"]!="") 
>     s_programname+="-"+::arg()["config-name"];
> ...
>   socketname += "/" + s_programname + ".controlsocket";
> ```

You're right.

I must have done something wrong in my tests. I checked for the THIRD time and it works.

I'm very sorry for the noise here. Closing the issue.

**Comment by Habbie** [comment]
Thank you for reporting back!

**Comment by elbaby** [comment]
I **just** found out my mistake.

`pdnsutil`'s `--config-name` option accepts that the name be separated from the option name by either a space or an `=` sign.

That is, you can either use **`pdnsutil --config-name MAIN`**  or **`pdnsutil --config-name=MAIN`** and both work.

However, `pdns_control` _requires_ you to put the `=` sign.

That is, **`pdns_cotntrol --config-name=MAIN`** works, wherever `pdns_cotntrol --config-name MAIN` does **not**.

**Comment by Habbie** [comment]
I've renamed and reopened this ticket for that inconsistency. I vaguely recall we already had a ticket about it already but I cannot find it right now.
