### ISSUE TITLE
Could anyone help me? When I set up Server PowerDNS-admin already and I assigned 2 DNS server(PowerDNS server and 8.8.8.8) on my pfsence. Ubuntu, phone(android, ios) can not assess all dns record Accept only Window.

### ISSUE THREAD

**Issue by Pechsopha** [PowerDNS/pdns#11230]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
