### ISSUE TITLE
PowerDNS not working for ubuntu, phone(android, ios) Accept only Windows. In the case happen when I assigned 2 DNS server to pfsence like PowerDNS-admin Server and other one is 8.8.8.8

### ISSUE THREAD

**Issue by Pechsopha** [PowerDNS/pdns#11237]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

**Comment by Pechsopha** [comment]
anyone help me please?

**Comment by setharnold** [comment]
Hello, GitHub issues are for bug reports, not support requests.

You can find support on the powerdns mail lists, powerdns irc channel, as well as generic support communities like https://serverfault.com

However, before going to those resources, please read https://betterfm.org/smart-questions.html for advice on how to get help. There's nothing in this issue that's really useful for anyone would could help you -- you'll need a much better description of what you've done, what you expected to happen, what actually happened, etc, before anyone could actually provide help.

Thanks

**Comment by omoerbeek** [comment]
This is the second time you ask the same question here. Please read the answers and follow the advice, do not ask here again.
