### ISSUE TITLE
Add libmdbx as storage backed

### ISSUE THREAD

**Issue by erthink** [PowerDNS/pdns#11246]
It may be interesting about [Erigon (Ethereum) was switched from LMDB to MDBX](https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta#switch-from-lmdb-to-mdbx) year ago.

Historically, [libmdbx](https://github.com/erthink/libmdbx) is a deeply revised and extended descendant of the LMDB.
Some added features:
- Automatic on-the-fly database size adjustment, both increment and reduction.
- Automatic continuous zero-overhead database compactification.
- Up to 30% faster than LMDB in CRUD benchmarks.
- Keys could be more than 2 times longer than LMDB.
- `mdbx_chk` utility for database integrity check.
- Zero-length for keys and values.
- Support for opening databases in the exclusive mode, including on a network share.
- etc, see [Improvements beyond LMDB](https://github.com/erthink/libmdbx#improvements-beyond-lmdb).

---
The [C API Reference](https://erthink.github.io/libmdbx/group__c__api.html).

The [C++ API Reference](https://erthink.github.io/libmdbx/namespacemdbx.html):
- [Transactions](https://erthink.github.io/libmdbx/classmdbx_1_1txn.html).
- [map-handles](https://erthink.github.io/libmdbx/structmdbx_1_1map__handle.html).
- [Cursors](https://erthink.github.io/libmdbx/classmdbx_1_1cursor.html).

**Comment by Habbie** [comment]
We have no plans to do this. We might accept a PR, but please check with us before taking on that task.
