### ISSUE TITLE
auth: make lmdb mapsize configurable

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#11243]
Right now it's hardcoded to 16 gigabyte (or 100 megabyte on 32 bit systems).

**Comment by fireangel403** [comment]
I have checked importing 33 GB zone records and the import crashes after 16GB 

```
pdnsutil load-zone example.com example.zone
Zone 'example.com' exists already, replacing contents
Error: putting data: MDB_MAP_FULL: Environment mapsize limit reached
```

I updated the config file (`/etc/powerdns/pdns.conf`) to as per the following:

```
launch=lmdb
lmdb-filename=/var/lib/powerdns/pdns.lmdb
lmdb-sync-mode=nometasync
lmdb-map-size=128000

reuseport=yes
receiver-threads=8
max-cache-entries=14000000
```

`service pdns restart`

Same error.

`Error: putting data: MDB_MAP_FULL: Environment mapsize limit reached`

It seems that` lmdb-map-size=128000 `has no effect.

PDNS Version: 4.8.0

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
