### ISSUE TITLE
Responding to A/AAAA record for domains without zone records

### ISSUE THREAD

**Issue by HcKTR** [PowerDNS/pdns#11244]
- Program: Authoritative 
 - Issue type: Feature request

### Short description

If there is no zone record, it should respond to an A request to the Authoritative server with a specified ip address.
### Usecase

Even if there is no zone record on pdns_server, I only want to respond to A requests. I want to respond to incoming requests with a specified ip address.
### Description

It can be a setting value like on the https://doc.powerdns.com/authoritative/settings.html page.
Sample:
no-zone-redirect-a
IP Address
Default: Unset
If there is no zone record, A requests should be answered for the specified ip address.

**Comment by Habbie** [comment]
What is the use case for this? It sounds like something that could be done with a custom backend (via pipe/lua2/remotebackend).

**Comment by klaus-nicat** [comment]
Adding a Root zone '.' that has a wildcard for A/AAAA could work. But can PDNS-Auth handle a Root zone? How to configure such a zone in DB-backend - name=""?

**Comment by Habbie** [comment]
> Adding a Root zone '.' that has a wildcard for A/AAAA could work. But can PDNS-Auth handle a Root zone? How to configure such a zone in DB-backend - name=""?

name=`.` I believe, and auth should be able to handle that, but it's not a legal setup. Even ignoring DNSSEC for a moment, some resolvers will hate it.

**Comment by HcKTR** [comment]
'.' Do I succeed when I save a zone with a wildcard? 
Zone name= .
Record type= A
Record content= ipaddress

**Comment by Habbie** [comment]
I answered that above, but our Github issue tracker is not for support questions, so I'm closing this.
