### ISSUE TITLE
Allow force execution of `lua-axfr-script` (or similar option) without AXFR notification

### ISSUE THREAD

**Issue by kaplanben** [PowerDNS/pdns#11311]
- Program: Authoritative
 - Issue type: Feature request

### Short description
When using `lua-axfr-script` add the ability to force execute the LUA script even when no AXFR are received (maybe even on a per zone basis)

### Usecase
We have a central PDNS slave(s) receiving updates from few thousands of PDNS masters (and zones).
While most are fairly active, many are static zones with lilttle changes and far a part.

### Description
When enabling a `lua-axfr-script` for whatever reason (in our case we need to change the SOA values), we don't see a way to execute the script without waiting for each zone to have a change and to cause an AXFR notification for the SOA to be updates on the central slave.

So the script solve an issue we have on new zones or active zones (with frequent changes) but we can't apply this on 100% of our managed zones and are left with whatever issue the script is trying to solve on the static zones.

It would be great if there was a way to manually/forcefully execte the script at least one time for each zone to apply the desired changes (even using cli tool like `pdns_control` is good enougth as this is a one time migration process).

Probably the script would need to be restructure as it will need to be applied on the PDNS backend instead of each record from AXFR packets, but in our case if would help a lot managing our fleet.

**Comment by Habbie** [comment]
As far as I can tell, `pdns_control retrieve` can do this today. Is there something I'm missing in that case?

**Comment by kaplanben** [comment]
@Habbie that's great! not sure how I missed that option (and confirm it works as expected). closing...
