### ISSUE TITLE
Extra query rrsets parameter for the GET zone endpoint

### ISSUE THREAD

**Issue by coudenysj** [PowerDNS/pdns#11331]
- Program: restapi
 - Issue type: Feature request

### Short description

It would be nice to have an extra filter parameter to filter the returned rrsets in the `/servers/{server_id}/zones/{zone_id}` endpoint.

We have zones with a lot of rrsets (411868 at the time of writing) and do not always need all the information.

### Usecase

We would like to avoid fetching all the rrsets in zones for performance reasons. The current zone returns 74MB over the wire.

### Description

Maybe we could add a filter option [here](https://github.com/zeha/pdns/blob/72fdd54cb41f3857d761a774df933410848459a1/docs/http-api/swagger/authoritative-api-swagger.yaml#L169-L196).

**Comment by coudenysj** [comment]
I've tried to mitigate the problem by using the Search endpoint, but that still takes up to 15s to respond.

For now I've settled upon using dig to query the NS, but that is only a solution for enabled records (which is fine for now).

**Comment by coudenysj** [comment]
#11409

**Comment by Habbie** [comment]
ah! I forgot we had an open request for this. Does #11409 meet your needs?

**Comment by coudenysj** [comment]
I would need to test it, but I think it does :)

**Comment by Habbie** [comment]
OK! I'll close this one for now. Thanks!
