### ISSUE TITLE
How can I combine ifportup pickclosest with round robin for one record?

### ISSUE THREAD

**Issue by ehztdlefaoyxbekwo** [PowerDNS/pdns#11342]
Hi,

I currently have this set:
INSERT INTO records (domain_id, name, type, content, ttl)
VALUES (
  1,
  'example.com',
  'LUA',
  'A "ifportup(80, {''1.1.1.1'', ''2.2.2.2'', ''3.3.3.3'', ''4.4.4.4''}, {selector=''pickclosest''})"',
  600
);

But how do I make it that if x is closer to 1.1.1.1, they would either connect to 1.1.1.1 or 1.1.1.2 as a round robin record?

I tried
INSERT INTO records (domain_id, name, type, content, ttl)
VALUES (
  1,
  'example.com',
  'LUA',
  'A "ifportup(80, {[''1.1.1.1'', ''1.1.1.2''], ''2.2.2.2'', ''3.3.3.3'', ''4.4.4.4''}, {selector=''pickclosest''})"',
  600
);
but that didnt work.

Thanks.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
