### ISSUE TITLE
need lua scripting disable cache lookup for query

### ISSUE THREAD

**Issue by hamzakilic** [PowerDNS/pdns#11345]
- Program: Recursor
 - Issue type: Feature request

### Short description

I need a lua scripting feature that  disables cache lookup for queries from a client, but set answer in cache after response. It will work exactly opposite of dq.variable
### Usecase

prepare cache for other clients.

**Comment by rgacogne** [comment]
Out of curiosity, why do you need to disable cache lookups if you want to warm the cache?

**Comment by omoerbeek** [comment]
Yes, could you please elaborate what your exact use case is? Only if we understand what you are trying to achieve we can appreciate feature your request.

**Comment by hamzakilic** [comment]
I want to hit cache for most queried domains allways. when a fqdn  ttl is going to timeout, I want to query that domain for putting with refreshed ttl in cache again, and when queried from someone again, hit cache. 
Implementation can be 
with lua or  just using with a configuration parameter like dont_lookup_cache_networks.

**Comment by omoerbeek** [comment]
Since 4.5 we have built-in functionality very much like that. See https://docs.powerdns.com/recursor/settings.html#refresh-on-ttl-perc

**Comment by hamzakilic** [comment]
thanks for that feature, I missed it. but activating that feature on all servers for all domains can be a problem. I am also using dnsdist for load balancing same queries to same server. I am open to any suggestion. I am trying  to cache hit for most used domains.

**Comment by paddg** [comment]
> but activating that feature on all servers for all domains can be a problem.

What do you mean by that?

**Comment by omoerbeek** [comment]
The extra load this causes is only a tiny bit more than an ordinary fetch after expiry.

Names that are not queried within the special TTL period won't be refetched early, only names that are queried will be refetched, and multiple queries within the special period won't trigger extra refetches. Names will be refetched a bit earlier than they would otherwise, but that is the only difference.

**Comment by hamzakilic** [comment]
> > but activating that feature on all servers for all domains can be a problem.
> 
> What do you mean by that?

I am planning to run  10 servers

**Comment by hamzakilic** [comment]
thanks @omoerbeek  for clear explanation. I understood how it is working. I think this feature does what I need. Thanks for your help. I am closing this issue
