### ISSUE TITLE
SRV and TXT queries missing from statistics

### ISSUE THREAD

**Issue by maxadamo** [PowerDNS/pdns#11369]
- Program: Recursor
 - Issue type: SRV and TXT records are missing from statistics

### Short description

On this page (or in the JSON object) there is no mention of SRV record: https://doc.powerdns.com/recursor/metrics.html#metricnames

### Usecase

Build metrics for each type of record.

**Comment by omoerbeek** [comment]
Please be more specific. What command did you use to retrieve stats and what was the output? I have no trouble seeing stats for the mentioned qtypes here, see below for a piece of `curl -v -H 'X-API-Key: xxx' http://127.0.0.1:8082/api/v1/servers/localhost/statistics  | jq .` output.

Also: there is a template asking you a few things like version and platform. We cannot help without that information.

```
...

  {
    "name": "response-by-qtype",
    "type": "MapStatisticItem",
    "value": [
      {
        "name": "A",
        "value": "130709"
      },
      {
        "name": "NS",
        "value": "71"
      },
      {
        "name": "SOA",
        "value": "58"
      },
      {
        "name": "PTR",
        "value": "2171"
      },
      {
        "name": "MX",
        "value": "88"
      },
      {
        "name": "TXT",
        "value": "1695"
      },
      {
        "name": "AAAA",
        "value": "89789"
      },
      {
        "name": "SRV",
        "value": "196"
      },
      {
        "name": "NAPTR",
        "value": "88"
      },
      {
        "name": "DS",
        "value": "828"
      },
      {
        "name": "SSHFP",
        "value": "41"
      },
      {
        "name": "DNSKEY",
        "value": "649"
      },
      {
        "name": "SVCB",
        "value": "1"
      },
      {
        "name": "HTTPS",
        "value": "29075"
      }
    ]
  },
....
```

**Comment by maxadamo** [comment]
hey @omoerbeek . Thanks for your reply. 
Now I understand what happened: I am playing with test, and in test I do not have any SRV, TXT record and the empty dict was not showing. 
On the other hand, creating a dict object with the value set to zero will help to:
1. know in advance the name of these values (they are not documented here: https://doc.powerdns.com/recursor/metrics.html#metricnames)
2. create our scripts. The way around, I have to parse the data and raise an exception if the data is missing. 
For instance, I mean something as follows: 
```json
{
  "name": "SRV",
  "value": "0"
}
```

**Comment by omoerbeek** [comment]
Documentation is indeed lacking with respect to these values. The names reported are the offical qtype names as documented in various RFCs. For unknown names, TYPExxxx is used where xxxx is a decimal value.

Reporting zero values is not very useful, as there are 2^16 = 65536 possible qtypes, most of the  being zero all the time.

**Comment by maxadamo** [comment]
clear enough :smile_cat:  I understand. It's a big number
Maybe one not in the documentation, to explain this behavior is enough. I'm gonna close the ticket. 
Thanks for your help.
