### ISSUE TITLE
dnsdist: docs for SVCRecordParameters mention invalid alpn value

### ISSUE THREAD

**Issue by stirnim** [PowerDNS/pdns#11387]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
The documentation for [SVCRecordParameters](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/docs/reference/svc.rst) mention the SVCParams list. The description of the key/value pair for alpn contains "doh" instead of "dot" as an example. "doh" is an invalid value.

The following pull request fixes this: https://github.com/PowerDNS/pdns/pull/11385

**Comment by Habbie** [comment]
thanks!
