### ISSUE TITLE
dnsdist: Proxy support for DOH Downstream servers

### ISSUE THREAD

**Issue by dtouzeau** [PowerDNS/pdns#11412]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
HTTP Proxy support for DOH 

### Usecase
The use of DOH backends requires a direct connection to public HTTP servers.
If you want to use an HTTP proxy for logging and security reasons, the option is not available.
Also, a basic proxy login would be appreciated to identify requests from dnsdist

**Comment by rgacogne** [comment]
It looks like a duplicate of https://github.com/PowerDNS/pdns/issues/10793

**Comment by dtouzeau** [comment]
#10793 is related to use nghttp as a workaround
It is only a workaround when you using a limited DOH downstream server and have performance issue on a stressed service.
Best is to integrate Proxy connection directly into the same process.

**Comment by rgacogne** [comment]
To me #10793 is about adding proxy support to DoH downstream servers, and happens to suggest a work-around in the meantime :)
