### ISSUE TITLE
Can pdns Authoritative set up a rpz?

### ISSUE THREAD

**Issue by laurretang** [PowerDNS/pdns#11424]
- Program: Authoritative
 - Issue type: Feature request

### Short description

Can we set up a rpz (response policy zone) through pdns Authoritative?

### Description

As we known, rpz is common used if we have self-hosted services.
And In a big platform, All the three recursor, dnsdist and Authoritative are used.
The self-hosted services should be figured out in recursor phase, rather than Authoritative.
Now recursor can configure rpzPrimary from rpz master, but how can I set up a rpz master?
Maybe we could use bind9 like https://www.linuxbabe.com/redhat/response-policy-zone-rpz-bind-centos.
But I wanna know can Authoritative do so as well? Thank you.

**Comment by omoerbeek** [comment]
An RPZ zone is just like any zone, set it up in a (private) auth all your  recursors can use it.

**Comment by omoerbeek** [comment]
Also:
our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

**Comment by laurretang** [comment]
> An RPZ zone is just like any zone, set it up in a (private) auth all your recursors can use it.

In a common zone, a record can be added when it is under the zone.
pdnsutil create-zone gslb.com ns1.gslb.com
pdnsutil add-record gslb.com rpz1 A 3600 1.1.1.1
pdnsutil add-record gslb.com rpz2 A 3600 2.2.2.2

But can we config some records of different zones into one zone?

Thank you.

**Comment by omoerbeek** [comment]
Yes you can.
I'm closing this, see comment above.

**Comment by laurretang** [comment]
> Yes you can. I'm closing this, see comment above.

Thank you.
I did launch bind backend with bind-config  a rpz file with named style.
I think it works, but the bind-config is only readable, inconvenient to update.

**Comment by laurretang** [comment]
Thank you.
I did launch bind backend with bind-config  a rpz file with named style.
I think it works, but the bind-config is only readable, inconvenient to update.
