### ISSUE TITLE
Config item allow-from from web-api does not take effect

### ISSUE THREAD

**Issue by laurretang** [PowerDNS/pdns#11439]
- Program: Recursor,
 - Issue type: Bug report

### Short description
Config item allow-from from http://ip:port/api/v1/servers/localhost/config/allow-from does not take effect.

### Environment

 - Operating system: CentsOS 7.9
 - Software version: PowerDNS Recursor 4.5.7
 - Software source: PowerDNS repository

### Steps to reproduce

**1. Install pdns-recursor 4.5.7**
curl -o /etc/yum.repos.d/powerdns-rec-45.repo https://repo.powerdns.com/repo-files/centos-rec-45.repo
yum install -y pdns-recursor

**2. config webserver**
[root@vm18 pdns-recursor]# mkdir -p /var/run/pdns-recursor/ && chown -R pdns-recursor:pdns-recursor /var/run/pdns-recursor/
[root@vm18 pdns-recursor]# cat recursor.conf
local-address=172.16.0.18,192.168.200.18

setgid=pdns-recursor
setuid=pdns-recursor

webserver=yes
webserver-port=8084
api-key=xxxxxxxxxx
api-config-dir=/var/run/pdns-recursor/
webserver-address=192.168.200.18
webserver-allow-from=127.0.0.1,::1,192.168.200.0/24
webserver-loglevel=detailed

log-common-errors=yes
log-rpz-changes=yes
loglevel=6

forward-zones-recurse = .=8.8.8.8

lua-config-file=/etc/pdns-recursor/config.lua
disable-packetcache=no
dnssec=off

**3. start service and config allow-from**
[root@vm18 ~]# systemctl start pdns-recursor
[root@vm18 ~]# curl -H 'X-API-Key: xxxxxxxxxx' http://192.168.200.18:8084/api/v1/servers/localhost/config/allow-from
{"name": "allow-from", "value": ["10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]}
[root@vm18 ~]# 
[root@vm18 ~]# curl -H 'X-API-Key: xxxxxxxxxx' http://192.168.200.18:8084/api/v1/servers/localhost/config/allow-from -X PUT --data '{ "name": "allow-from", "value": ["122.196.0.0/16"] }' 
_{"name": "allow-from", "value": ["10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]}

[root@vm18 ~]# cat /var/run/pdns-recursor/allow-from.conf
# Generated by pdns-recursor REST API, DO NOT EDIT
allow-from-file=
allow-from=
allow-from+=122.196.0.0/16

### Expected behaviour
_{"name": "allow-from", "value": ["122.196.0.0/16"]}

### Actual behaviour
_{"name": "allow-from", "value": ["10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]}

### Other information
As described in https://doc.powerdns.com/recursor/http-api/endpoint-servers-config.html
Docs >Built-in Webserver and HTTP API>Configuration endpoint
PUT /api/v1/servers/:server_id/config/:config_setting_name
Change a single setting
Note: Only [allow-from] and [allow-notify-from] can be set.

Here is the code of function apiServerConfigAllowFrom in ws-recursor.cc. It seems that the put json netmasks are just wrote into the file, but are not take effect,

static void apiServerConfigAllowFrom(HttpRequest* req, HttpResponse* resp)
{
  if (req->method == "PUT") {
    Json document = req->json();

    auto jlist = document["value"];
    if (!jlist.is_array()) {
      throw ApiException("'value' must be an array");
    }

    NetmaskGroup nmg;
    for (auto value : jlist.array_items()) {
      try {
        nmg.addMask(value.string_value());
      } catch (const NetmaskException &e) {
        throw ApiException(e.reason);
      }
    }

    ostringstream ss;

    // Clear allow-from-file if set, so our changes take effect
    ss << "allow-from-file=" << endl;

    // Clear allow-from, and provide a "parent" value
    ss << "allow-from=" << endl;
    ss << "allow-from+=" << nmg.toString() << endl;

    apiWriteConfigFile("allow-from", ss.str());

    **### parseACLs();**

    // fall through to GET
  } else if (req->method != "GET") {
    throw HttpMethodNotAllowedException();
  }

  // Return currently configured ACLs
  vector<string> entries;
  t_allowFrom->toStringVector(&entries);

  resp->setJsonBody(Json::object {
    { "name", "allow-from" },
    { "value", entries },
  });
}

**Comment by laurretang** [comment]
Here are the detailed logs:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee Request details:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee  POST params:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   { "name": "allow-from", "value": ["122.196.0.0/16"] }:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee  Headers:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   accept: */*
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   content-length: 53
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   content-type: application/x-www-form-urlencoded
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   host: 192.168.200.18:8084
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   user-agent: curl/7.29.0
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   x-api-key: UnicloudAPI@123
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee  Full body:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   { "name": "allow-from", "value": ["122.196.0.0/16"] }
Mar 22 15:36:30 vm18 pdns_recursor: Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee Response details:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee  Headers:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   access-control-allow-origin: *
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   Connection: close
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   Content-Length: 168
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   Content-Type: application/json
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   Server: PowerDNS/4.5.7
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   X-Content-Type-Options: nosniff
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   X-Frame-Options: deny
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   X-Permitted-Cross-Domain-Policies: none
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   X-XSS-Protection: 1; mode=block
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee  Full body:
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee   {"name": "allow-from", "value": ["10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]}
Mar 22 15:36:30 vm18 pdns_recursor: [webserver] e55b189f-d700-4505-9e77-0cee14af25ee 192.168.200.18:46676 "PUT /api/v1/servers/localhost/config/allow-from HTTP/1.1" 200 524

**Comment by omoerbeek** [comment]
`parseACLs()` is supposed to pick up the changes. Will investigate.
