### ISSUE TITLE
Annoying "Unable to send NOD lookup" logging

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#11440]
- Program:  Recursor
 - Issue type: Feature request

### Short description

We use `new-domain-tracking=yes` and the `new-domain-lookup=` setting. Recently we see a lot of "`Unable to send NOD lookup`" messages in the journal. For example:

```
Mär 22 10:39:33 node06 pdns-recursor[10505]: msg="Unable to send NOD lookup" oserror="DNSName too long" subsystem="nod" level=11 prio=3 ts="1647941973.921" qname="3.1o18sr00nq7pn93op374q845r8pq4o1122ss8378q6opn2nq760155rnr97sp52.rsop5r741q033393648s2sn6o9n0510q8op620ssqq223q2q3nr17q8nq8842rp.q50p5p8728s281523r5nno08r0nn0n2o89o33on7r970o9576q7rpn4rss.05ss2ppsno1p451o.i.00.s.sophosxl.net"
```
I guess the reason in simply because this domain name plus our `new-domain-lookup` setting is in sum too long.

### Usecase

These many journal entries are annoying. One possible solution would be to add `sophosxl.net` to `new-domain-whitelist`. But that wouldn't really be sustainable.

### Description

It would be nice if this error message could be suppressed. Or if the message would be declared as info instead of error?

**Comment by omoerbeek** [comment]
My first thought is to log only if `log-comon-errors` is set. Would that work for you?

**Comment by paddg** [comment]
> My first thought is to log only if `log-comon-errors` is set. Would that work for you?

Yes. Would be a good solution for us. 👍
