### ISSUE TITLE
dnsdist: too many file open errors on `dnsdist -e 'reloadAllCertificates()'`

### ISSUE THREAD

**Issue by yannk** [PowerDNS/pdns#11441]
- Program: dnsdist
 - Issue type: Bug report

### Short description
too many file open errors upon `dnsdist -e 'reloadAllCertificates()'`

### Environment
 - Operating system:  FreeBSD 12.2-RELEASE-p12
 - Software version: dnsdist 1.7.0 (Lua 5.2.4)
Enabled features: cdb dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt ipcipher libsodium lmdb protobuf re2 recvmmsg/sendmmsg
 - Software source: self-compiled 

### Steps to reproduce
- start dnsdist with DoH frontends and take significant traffic 
- issue dnsdist -e 'reloadAllCertificates()'

### Expected behaviour
The certs are reloaded without an error in the logs.

### Actual behaviour
logs complains the certs are not reloaded:

```
Error reloading certificates for frontend 0.0.0.0:443: Error setting up TLS context for DoH listener on '0.0.0.0:443': An error occurred while trying to load the TLS server certificate file: /var/run/dnsdist/cert.ecdsa
35731973120:error:02001018:system library:fopen:Too many open files:/usr/gsrc/crypto/openssl/crypto/bio/bss_file.c:288:fopen('/var/run/dnsdist/cert.ecdsa','r')
35731973120:error:20074002:BIO routines:file_ctrl:system lib:/usr/gsrc/crypto/openssl/crypto/bio/bss_file.c:290:
35731973120:error:140DC002:SSL routines:use_certificate_chain_file:system lib:/usr/gsrc/crypto/openssl/ssl/ssl_rsa.c:596:
Error reloading certificates for frontend 0.0.0.0:443: Error setting up TLS context for DoH listener on '0.0.0.0:443': An error occurred while trying to load the TLS server certificate file: /var/run/dnsdist/cert.ecdsa
```

### Other information

The system should have plenty of available fds for this
```
# sysctl kern.openfiles kern.maxfiles
kern.openfiles: 83714
kern.maxfiles: 12571305
```

The process itself is not limited:

```
# procstat rlimit 69130
  PID COMM             RLIMIT                  SOFT             HARD
69130 dnsdist          cputime             infinity         infinity
69130 dnsdist          filesize            infinity         infinity
69130 dnsdist          datasize               32768 MB         32768 MB
69130 dnsdist          stacksize             524288 KB        524288 KB
69130 dnsdist          coredumpsize        infinity         infinity
69130 dnsdist          memoryuse           infinity         infinity
69130 dnsdist          memorylocked          131072 KB        131072 KB
69130 dnsdist          maxprocesses           89999            89999
69130 dnsdist          openfiles              11049 K          11049 K
69130 dnsdist          sbsize              infinity         infinity
69130 dnsdist          vmemoryuse          infinity         infinity
69130 dnsdist          pseudo-terminals    infinity         infinity
69130 dnsdist          swapuse             infinity         infinity
69130 dnsdist          kqueues             infinity         infinity
69130 dnsdist          umtxp               infinity         infinity
```

**Comment by setharnold** [comment]
Does this line ...

```
69130 dnsdist          openfiles              11049 K          11049 K
```

... mean that the process is allowed to have eleven million files open? (`11049*1024/12571305 == 0.900...` which is a strong suggestion that it really is in the eleven million range, but these are guesses, I didn't see anything in the procstat manpage to describe what exactly the `K` means.)

**Comment by yannk** [comment]
Yes,

```
# procstat --libxo:J rlimit 69130 | jq '.procstat.rlimit["69130"].openfiles'
{
  "soft_limit": 11314170,
  "hard_limit": 11314170
}
```

**Comment by rgacogne** [comment]
Any chance you would be able to trace the dnsdist process via `truss` so we can see exactly what is happening? We are not opening the file directly but asking `libcrypto` to do that for us, so I'm afraid there is no information available to dnsdist at this point, apart from the lines we logged :-/

**Comment by yannk** [comment]
Unfortunately, `truss` alters the working state `dnsdist` by, I assume, slowing it down significantly, and timeouts are served... I'll try to get a trace on a idle server, but on a idle server the problem doesn't occur.

**Comment by setharnold** [comment]
How about `dtruss`?

https://www.brendangregg.com/dtrace.html
https://www.brendangregg.com/DTrace/dtruss_example.txt
https://www.brendangregg.com/DTrace/dtruss

**Comment by yannk** [comment]
Yeah I had done a `dtruss` too, I will investigate  more when time permits.
