### ISSUE TITLE
dnsdist: rpz support

### ISSUE THREAD

**Issue by dtouzeau** [PowerDNS/pdns#11446]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
There is no mention of rpz support for dnsdist, for PowerDNS recursor yes but it seems that dnsdist did no support rpz file

**Comment by dtouzeau** [comment]
Can try 

can you confirm that 

Did the Documentation mention that lmdb stores records by replacing dots by the lenght of the suffix subsets ?

```
\3sub\6domain\8powerdns\3com\0
\6domain\8powerdns\3com\0
\8powerdns\3com\0
```

**Comment by rgacogne** [comment]
Just for the record, there is also no way for dnsdist to fulfill the NSIP and NSDNAME targets of the RPZ specifications, as it does not do any recursive resolution.
