### ISSUE TITLE
WKS RR is 

### ISSUE THREAD

**Issue by klaus-nicat** [PowerDNS/pdns#11468]
- Program: Authoritative
 - Issue type: Bug report

### Short description
The documentation https://doc.powerdns.com/authoritative/appendices/types.html reports as WKS as "Supported Record Types". This is wrong and should be removed. WKS was half implemented long ago (type=WKS but still base64 encoding) and finally removed in fa23972a8cadfd648ae75c0a47f7a514b30293c8

**Comment by omoerbeek** [comment]
That reminds me that ZONEMD should be added (and maybe more?).
