### ISSUE TITLE
Hi! , I have a problem We have no authority over zone

### ISSUE THREAD

**Issue by webabdes** [PowerDNS/pdns#11469]
system environment:centos7 mysql5.6 geoip powerdns4.6
https://doc.powerdns.com/authoritative/lua-records/index.html
I ran the sql statement as per the above example and also ran powerdns successfully
But now there is an error We have no authority over zone 'domain'
Thank you and best regards

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
