### ISSUE TITLE
account empty when creating a domain from API

### ISSUE THREAD

**Issue by demarcq** [PowerDNS/pdns#11486]
Hi,
Since I updated to pdns 4.6.1, the domains created from API don't have any account.

{"soa_edit_api" : "DEFAULT","name":"test.com.","dnssec":false, "kind": "MASTER", "masters": [], "account":"noviris","nameservers": ["ns1.bdmi.net.", "ns2.bdmi.net."]}

I also tried to update domain with : {"account":"noviris"} and get a 204.

But the account is not provided in the permission table but domains contenting : 

[domains]
  | 4129 | test.com |   | NULL | MASTER | 2022032901 | noviris
-- | -- | -- | -- | -- | -- | -- | --

**Comment by Habbie** [comment]
> But the account is not provided in the permission table but domains contenting :

What's the permission table?

**Comment by Habbie** [comment]
Given that the dump from the domains table does show the account, and my question went unanswered, I am assuming this is a problem with some other piece of software. Closing this ticket.
