### ISSUE TITLE
recursor could accept notify and update RPZ and/or auth zones 

### ISSUE THREAD

**Issue by laurretang** [PowerDNS/pdns#11490]
- Program: Recursor
 - Issue type: Feature request

### Short description
Rather than refresh rpz zones periodly, recursor can accept notify and update from dns auth

### Usecase
Once receive a zone change notification from auth, recursor do update zone info in time.

### Description
Recursor Version：4.6.1

As described in https://doc.powerdns.com/recursor/lua-config/rpz.html, we can config dns rec to refresh a rpz zone periodly.
The confige example in lua-config-file is as follows:
`rpzPrimary("172.16.0.19:5353", "default.rpz" , {refresh=300})`

Trigger a notify from auth（172.16.0.19）:  _pdns_control notify default.rpz_
Logs are shown here:
Mar 31 08:09:06 vm19 pdns_server: Notification request for zone 'default.rpz' received from operator
Mar 31 08:09:06 vm19 pdns_server: Queued also-notification of domain 'default.rpz' to 172.16.0.18:53
Mar 31 08:09:41 vm19 pdns_server: Notification for default.rpz to 172.16.0.18:53 failed after retries

We expect recursor to accept the notify and update next

Athough we can config refresh as small as we can (such 1 second), I think do notify is a better way to update in time.
Furthermore, the new feature of allow-notify-from and allow-notify-for to wipe cache from 4.6.0 can be considered in rpz scope.

**Comment by kpfleming** [comment]
Have you configured `allow-notify-for` in your recursor for `default.rpz`? Please paste a copy of your recursor configuration and the logs from the same time when the NOTIFY was sent.

**Comment by laurretang** [comment]
> Have you configured `allow-notify-for` in your recursor for `default.rpz`? Please paste a copy of your recursor configuration and the logs from the same time when the NOTIFY was sent.

[root@vm18 pdns-recursor]# cat recursor.conf
server-id=ldns1
local-address=172.16.0.18
pdns-distributes-queries=yes
distributor-threads=2
threads=4
reuseport=yes
cpu-map=0=0 1=1
max-total-msec=5000

setgid=pdns-recursor
setuid=pdns-recursor
webserver=yes
webserver-port=8084
api-key=xxxxxxxx
api-config-dir=/var/run/pdns-recursor-data
include-dir=/var/run/pdns-recursor-data
webserver-address=172.16.0.18
webserver-allow-from=127.0.0.1,::1,172.16.0.0/24
webserver-loglevel=detailed

log-common-errors=yes
log-rpz-changes=yes
loglevel=9

forward-zones = testgslb.com=172.16.0.19

lua-config-file=/etc/pdns-recursor/config.lua

disable-packetcache=no
refresh-on-ttl-perc=10
max-cache-ttl=43200
packetcache-ttl=600
packetcache-servfail-ttl=6
minimum-ttl-override=6

dnssec=process

allow-notify-for=default.zone
allow-notify-from=172.16.0.19

[root@vm18 pdns-recursor]# cat config.lua 
zoneToCache(".", "url", "https://www.internic.net/domain/root.zone", { refreshPeriod = 86400 })
rpzPrimary("172.16.0.19:5353", "default.rpz" , {refresh=300)
addNTA("testgslb.com", "forward zone without dnssec")


No log is recorded during the time
Mar 30 18:08:52 vm18 pdns-recursor: Getting IXFR deltas for default.rpz from 172.16.0.19:5353, our serial: 30
Mar 30 18:13:52 vm18 pdns-recursor: Getting IXFR deltas for default.rpz from 172.16.0.19:5353, our serial: 30

**Comment by laurretang** [comment]
For sure, the recursor server can receive the notify message.
And I captured four notifications in 0s, 3s, 8s and 17s.

**Comment by kpfleming** [comment]
Thanks for the details. @omoerbeek has made it clear in IRC that the existing code can't handle RPZ (or auth zones), so this is definitely a feature request as you've indicated.

By the way your 'allow-notify-for' says 'default.zone' but your RPZ is named 'default.rpz'. Even if this feature gets implemented, having mismatched names won't work :)

**Comment by kpfleming** [comment]
It is a bit surprising that the recursor log doesn't have any entries showing that the NOTIFY was received; there is extensive logging in that code.

**Comment by laurretang** [comment]
> Thanks for the details. @omoerbeek has made it clear in IRC that the existing code can't handle RPZ (or auth zones), so this is definitely a feature request as you've indicated.
> 
> By the way your 'allow-notify-for' says 'default.zone' but your RPZ is named 'default.rpz'. Even if this feature gets implemented, having mismatched names won't work :)

Thanks for your reminding of my misspell in 'allow-notify-for' :) 
Hope to realize this feature, which auth can notify to update RPZ or Auth zones.

Meanwhile, after fix configuration,I do more notified wipe tests on both RPZ and Auth phases.
And I found out "allow-notify-for" and "allow-notify-from" are Inconvenient for RPZ zones.
Further look into the code, I config the 'quite' to 'no', then notified recursor logs come as well.

**Phase Auth ZONE: unigslb.com**
**Show zone info, dig test, load and wipe packet cache success**
[root@vm19 ~]# pdnsutil list-zone unigslb.com
$ORIGIN .
unigslb.com	3600	IN	SOA	a.misconfigured.dns.server.invalid hostmaster.unigslb.com 1 10800 3600 604800 3600
unigslb.com	3600	IN	NS	ns1.unigslb.com.
unigslb.com	3600	IN	NS	ns2.unigslb.com.
ns1.unigslb.com	3600	IN	A	3.3.3.3
ns1.unigslb.com	3600	IN	A	4.4.4.4
ns2.unigslb.com	3600	IN	A	3.3.3.3
ns2.unigslb.com	3600	IN	A	4.4.4.4
www.unigslb.com	600	IN	A	1.1.1.1
www.unigslb.com	600	IN	A	2.2.2.2

[root@vm19 ~]# dig @172.16.0.18 www.unigslb.com +short
1.1.1.1
2.2.2.2
[root@vm19 ~]# pdns_control notify unigslb.com

**Here are the logs of Auth:**
Apr  1 10:20:18 vm19 pdns_server: Remote 172.16.0.18 wants 'www.unigslb.com|A', do = 1, bufsize = 1232: packetcache MISS
Apr  1 10:20:26 vm19 pdns_server: Notification request for zone 'unigslb.com' received from operator
Apr  1 10:20:26 vm19 pdns_server: Queued notification of domain 'unigslb.com' to 3.3.3.3:53
Apr  1 10:20:26 vm19 pdns_server: Queued notification of domain 'unigslb.com' to 4.4.4.4:53
Apr  1 10:20:26 vm19 pdns_server: Queued also-notification of domain 'unigslb.com' to 172.16.0.18:53
Apr  1 10:20:27 vm19 pdns_server: Notification for unigslb.com to 3.3.3.3:53 failed after retries
Apr  1 10:20:27 vm19 pdns_server: Notification for unigslb.com to 4.4.4.4:53 failed after retries
Apr  1 10:20:28 vm19 pdns_server: Removed from notification list: 'unigslb.com' to 172.16.0.18:53 (was acknowledged)
PS: 3.3.3.3 and 4.4.4.4 are the addresses of ns.unigslb.com

**Here are the logs of Rec:**
Apr  1 10:20:17 vm18 pdns-recursor: 4 [2/1] question for 'www.unigslb.com|A' from 172.16.0.19:41073
Apr  1 10:20:17 vm18 pdns-recursor: 4 [2/1] answer to question 'www.unigslb.com|A': 2 answers, 1 additional, took 1 packets, 2.004 netw ms, 2.163 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=0, dnssec=Insecure
Apr  1 10:20:26 vm18 pdns-recursor: 6 got NOTIFY for unigslb.com from 172.16.0.19:11682
Apr  1 10:20:26 vm18 pdns-recursor: 6 [3/1] answer to non-rd question 'unigslb.com|SOA': 0 answers, 0 additional, took 0 packets, 0 netw ms, 0 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=0
Apr  1 10:20:26 vm18 pdns-recursor: Wiped caches for unigslb.com: 2 records; 0 negative records; 2 packets


**Phase RPZ ZONE: default.rpz**
**Show zone info, dig test, load packet cache success, but failed to wipe**
[root@vm19 ~]# pdnsutil list-zone default.rpz
$ORIGIN .
default.rpz	3600	IN	SOA	a.misconfigured.dns.server.invalid hostmaster.default.rpz 30 10800 3600 604800 3600
localip.example.com.default.rpz	1200	IN	A	172.16.0.18
localip.example.com.default.rpz	1200	IN	A	172.16.0.17
19.200.168.192.in-addr.arpa.default.rpz	360	IN	PTR	localip.example.com

[root@vm18 pdns-recursor]# rec_control dump-rpz default.rpz default.rpz.file
done
[root@vm18 pdns-recursor]# cat default.rpz.file 
default.rpz. IN SOA fake.RPZ. hostmaster.fake.RPZ. 30 10800 600 3600000 604800
19.200.168.192.in-addr.arpa.default.rpz. 360 IN PTR localip.example.com.
localip.example.com.default.rpz. 1200 IN A 172.16.0.17
localip.example.com.default.rpz. 1200 IN A 172.16.0.18

[root@vm19 ~]# dig @172.16.0.18 localip.example.com. +short
172.16.0.17
172.16.0.18
[root@vm19 ~]# dig @172.16.0.18 localip.example.com. +short
172.16.0.17
172.16.0.18

[root@vm18 pdns-recursor]# rec_control dump-rpz default.rpz default.rpz.file
[root@vm18 pdns-recursor]# cat /tmp/cache3 | grep localip.example.com. 
localip.example.com. 410 A  ; tag 0 udp

[root@vm19 ~]# pdns_control notify default.rpz
[root@vm19 ~]# pdns_control notify example.com.
Failed to add to the queue - see log
PS: We can not add the "actual" records as ture zones in auth.

**Here are the logs of Auth:**
Apr  1 10:35:42 vm19 pdns_server: Notification request for zone 'default.rpz' received from operator
Apr  1 10:35:42 vm19 pdns_server: Queued also-notification of domain 'default.rpz' to 172.16.0.18:53
Apr  1 10:35:44 vm19 pdns_server: Removed from notification list: 'default.rpz' to 172.16.0.18:53 (was acknowledged)
Apr  1 10:38:45 vm19 pdns_server: Notification request for zone 'example.com.' received from operator
Apr  1 10:38:45 vm19 pdns_server: No such domain 'example.com' in our database

**Here are the logs of Rec:**
Apr  1 10:34:09 vm18 pdns-recursor: msg="Getting zone by URL" subsystem="ztc" level=0 ts="1648780449.295" zone="."
Apr  1 10:34:09 vm18 pdns-recursor: msg="RPZ load in progress" subsystem="rpz" level=2 prio=6 ts="1648780449.300" nrecords="0" primary="172.16.0.19:5353" zone="default.rpz"
Apr  1 10:34:53 vm18 pdns-recursor: 4 [1/1] question for 'localip.example.com|A' from 172.16.0.19:46050
Apr  1 10:34:53 vm18 pdns-recursor: 4 [1/1] answer to question 'localip.example.com|A': 6 answers, 1 additional, took 0 packets, 0 netw ms, 0 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=0, dnssec=Indeterminate
Apr  1 10:35:14 vm18 pdns-recursor: 4 question answered from packet cache tag=0 from 172.16.0.19:50994
Apr  1 10:35:42 vm18 pdns-recursor: 4 got NOTIFY for default.rpz from 172.16.0.19:11682
Apr  1 10:35:42 vm18 pdns-recursor: 4 [2/1] answer to non-rd question 'default.rpz|SOA': 0 answers, 0 additional, took 0 packets, 0 netw ms, 0 tot ms, 0 throttled, 0 timeouts, 0/0 tcp/dot connections, rcode=0
Apr  1 10:35:42 vm18 pdns-recursor: Wiped caches for default.rpz: 0 records; 0 negative records; 0 packets
Apr  1 10:39:09 vm18 pdns-recursor: Getting IXFR deltas for default.rpz from 172.16.0.19:5353, our serial: 30


Caches can be wiped for auth zones, while failed for rpz zones.
For subzone of default.rpz are cached as name of "actual" domain, which can not be matched with zone name "default.rpz" in the wipe commands.

As far as I can understand, wipe instruction from auth notify is "same" with comamnd "rec_control wipe-cache".
[root@vm18 pdns-recursor]# rec_control wipe-cache default.rpz.$
wiped 0 records, 0 negative records, 0 packets

Actually, we need the wipe instructions for "actual" domains, such as:
[root@vm18 pdns-recursor]# rec_control wipe-cache localip.example.com.$
wiped 0 records, 0 negative records, 1 packets

**Comment by omoerbeek** [comment]
With the upcoming 5.1.0 release, recursor wil be able to handle notifies for a number of cases:

- arbitrary names, set via settings (causing cache flushes on notify)
- when defining a forward zone in a file or via the REST API (also casuing cache flushed on notify)
- RPZ zones retrieved from an auth can be sent a notify, resulting in a SOA check and potential update if the SOA check indicates the zone is out-of-date.

Two cases remain: auth zones and local file RPZ zones. As these both need local file system based actions to be updated, handling notifies does not make a lot of sense IMO. After modifying the file, a `rec_control reload-zones` can be done to trigger the reload. 

So I am closing the ticket.  If youfind a valid use case to handle notifies for auth zones or file based RPZs, please re-open the ticket and describe the use case.
