### ISSUE TITLE
outgoing timeouts report is likely spurious

### ISSUE THREAD

**Issue by vzuevsky** [PowerDNS/pdns#11502]
- Program: Recursor
 - Issue type: Bug report

### Short description
We run a busy pdns recursor: about 25kQPS with 2 threads re-using linux port. Every 30 minutes outgoing timeouts reported in the syslog indicates >2QPS of timed out outgoing queries. I got the address of the culprit name server with
`rec_control top-timeouts`
and tcpdumped 80k packets between our recursor and the offender (25% of all timeouts). Wireshark analysis showed no latency greater than 60ms on the wire. No unanswered requests either. I hypothesize, therefore, a pdns bug either in reporting or, worst-case, a race losing requests before they are actually sent. Thoughts?

### Environment

 - Operating system: 
 Linux xx 5.4.0-45-generic #49~18.04.2-Ubuntu SMP
 - Software version: 
 ```
# pdns_recursor --version
Apr 04 20:09:44 PowerDNS Recursor 4.3.1 (C) 2001-2020 PowerDNS.COM BV
Apr 04 20:09:44 Using 64-bits mode. Built using gcc 7.5.0 on May  8 2020 11:44:22 by root@c2c81a43694e.
Apr 04 20:09:44 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Apr 04 20:09:44 Features: fcontext libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libcrypto-eddsa lua nod protobuf dnstap-framestream sodium
Apr 04 20:09:44 Configured with: " '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--sysconfdir=/etc/powerdns' '--enable-unit-tests' '--with-lua=luajit' '--with-libcap' '--with-libsodium' '--with-protobuf=yes' '--enable-dnstap' '--without-net-snmp' '--disable-silent-rules' '--with-service-user=pdns' '--with-service-group=pdns' '--enable-systemd' '--with-systemd=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/pdns/pdns-recursor-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/pdns/pdns-recursor-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security'"
 - Software source: <!-- e.g. Operating system repository, PowerDNS repository, compiled yourself -->
```

### Steps to reproduce
I saw similar complaints on various stackexchanges - presumably any busy recursor would have this issue.

**Comment by vzuevsky** [comment]
I would be grateful for any guidance how to better troubleshoot it. For example, I do not feel confident to enable logging on production system as I suspect it could influence latency for production traffic.

**Comment by rgacogne** [comment]
A good start would be to upgrade to at least 4.3.7, as one of the issue fixed in 4.3.6 (https://github.com/PowerDNS/pdns/pull/9707) bear some resemblance to this.

**Comment by vzuevsky** [comment]
Thanks Remi @rgacogne it sounds exactly like my "worst-case" idea because we indeed handle many identical requests. Let us try.

**Comment by omoerbeek** [comment]
So how's this after upgrading?

**Comment by vzuevsky** [comment]
@omoerbeek I upgraded to the latest release and it helped. Please, feel free to close. Many Thanks!
