### ISSUE TITLE
No systemd support in builder-pdns-oraclelinux-8-amd64 docker image

### ISSUE THREAD

**Issue by alm-nl** [PowerDNS/pdns#11520]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Bug report

### Short description
After building new PowerDNS packages (using ./builder/build.sh buildprocess) it shows that packages can be tested using a docker-image. When I try to install it inside the container using rpm and dnf it shows an error message about not being booted with systemd.

### Environment
 - Operating system: Oracle Linux 8.5 x86_64
 - Software version: 4.6.1
 - Software source: git clone -b auth-4.6.1 https://github.com/PowerDNS/pdns.git (but also tried with git clone -b rel/auth-4.6.x https://github.com/PowerDNS/pdns.git, but this didn't make any difference)

### Steps to reproduce
1. git clone -b auth-4.6.1 https://github.com/PowerDNS/pdns.git
2. git submodule init
3. git submodule update
4. sudo ./builder/build.sh -v -m authoritative oraclelinux-8-amd64  # It also happens when leaving out -m authoritative, when building everything
5. docker run -it --rm builder-pdns-oraclelinux-8-amd64:latest
6. cd /dist/x86_64/                                                       # inside the docker container
7. rpm -i pdns-4.6.1-1pdns.el8.x86_64.rpm                 # inside the docker container
8. dnf localinstall pdns-4.6.1-1pdns.el8.x86_64.rpm    # inside the docker container
9. systemctl status                                                        # inside the docker container

### Expected behaviour
Be able to run installation without systemd error messages

### Actual behaviour
Error messages appear when running commands 7, 8 and 9 above:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
With step 8 it installs the package, but still shows the error/warning message during the process.

### Other information
I've tested the packages on another Oracle Linux 8.5 x86_64 vm that I installed to test the PowerDNS installation and the packages itself work just fine (although only tested with pdns and pdns-backend-mysql packages from this build) using dnf localinstall.
I'm not sure if the docker image was downloaded or created during the build process, when running the command to run the container it does not seem to download anything.

**Comment by Habbie** [comment]
Thank you for your very extensive and clear bug report. However, we have no plans to fix systemd support inside upstream OS images. So, I am very sorry, but I am closing this.

> I'm not sure if the docker image was downloaded or created during the build process, when running the command to run the container it does not seem to download anything.

The image is created during the build process, based on the upstream image (in this case, `oraclelinux:8`).
