### ISSUE TITLE
response stats do not reflect packet cache hits

### ISSUE THREAD

**Issue by maxadamo** [PowerDNS/pdns#11534]
- Program: Recursor
 - Issue type: Bug report

### Short description

![image](https://user-images.githubusercontent.com/1710103/163232918-33ff3b4e-ce98-4c03-b59c-428a14a1cf55.png)

Statistics seem to throw bogus numbers. I can't prove it, but I have some clue:
1. you can see in the Grafana panel that NXDOMAINs are more than A. 
2. right today I migrated from Unbound to PowerDNS and the A records went down from 20 thousand per minute to 200. 

Either Unbound or PowerDNS, are throwing the wrong numbers, but since point 1 is also true, I tend to believe that PowerDNS is throwing the wrong numbers. 

### Environment
 - Operating system: Ubuntu 20.04
 - Software version:  PowerDNS recursor 4.5.9
 - Software source: `deb [arch=amd64] http://repo.powerdns.com/ubuntu focal-rec-45 main`
### Steps to reproduce

1. Since your tools provides only cumulative statistics, I am using a custom script, which does some arithmetic operations to throw statistics per minute
2. from the json object I am grabbing: `nxdomain-answers`, `A`, `AAAA`, `SRV` ...

**Comment by phonedph1** [comment]
You should maybe try setting up https://blog.powerdns.com/2014/12/11/powerdns-graphing-as-a-service/ to confirm or deny your own calculations.

**Comment by omoerbeek** [comment]
Please tell us *exactly* which numbers (json keys) you are retrieving and how you are doing your computations.

Without that information, we cannot tell what is going on.

**Comment by maxadamo** [comment]
@omoerbeek , this is the endpoint where I fetch the JSON: 
```
http://127.0.0.1:8082/api/v1/servers/localhost/statistics
```

and I get the following keys (in this case they are cumulative, and you can see that `nxdomain-answer` is higher than `A`):
```json
  ...[CUT...
  {
    "name": "nxdomain-answers",
    "type": "StatisticItem",
    "value": "50077"
  },
  ...[CUT...
  {
    "name": "response-by-qtype",
    "type": "MapStatisticItem",
    "value": [
      {
        "name": "A",
        "value": "50020"
      },
      ...[CUT...
      {
        "name": "PTR",
        "value": "6216"
      },
      {
        "name": "MX",
        "value": "339"
      },
      {
        "name": "TXT",
        "value": "2241"
      },
      {
        "name": "AAAA",
        "value": "16517"
      },
      {
        "name": "SRV",
        "value": "11925"
      }
      ...[CUT...
    ]
  },
```

**Comment by omoerbeek** [comment]
What you are seeing is an effect of how the stats are collected. `nxdomain-answers` is incremented on each `NxDomain` answer sent to a client, while the `response-by-qtype` stats are only updated on packetcache misses.  This has to be re-evaluated some day.
In the meantime, you can use the `response-by-rcode` item with name `Non-Existent domain` to get a count that is line with how `response-by-qtype`  is incremented, i.e. only on packet cache miss.

**Comment by maxadamo** [comment]
and response-by-rcode is empty in my case:
```json
  {
    "name": "response-by-rcode",
    "type": "MapStatisticItem",
    "value": []
  }
```
but these numbers from the recursor are not in line with the numbers below from dnsdist (you have to divide by 3, the number of backends). I am using the python module `dnsdist_console`
```json
  "queries": "24435822",
  "empty-queries": "0",
  "rdqueries": "24435726",
```

Maybe dnsdist was running 1 hour before, but it's millions vs peanuts. But I'm not understanding the "packetcache misses" that you have mentioned.

**Comment by maxadamo** [comment]
this is dnsdist on one backend: 
```json
    {
      "#": "0",
      "name": "prod-consul01",
      "address": "xxx.xxx.xxx.xxx:5300",
      "state": "up   64",
      "qps": "6.5",
      "qlim": "0",
      "ord": "1",
      "wt": "1",
      "queries": "8187944",
      "drops": "237",
      "drate": "0.0",
      "lat": "0.3",
      "outstanding": "0",
      "pools": ""
    },
```

**Comment by phonedph1** [comment]
From the docs: "The Packet Cache contains previous answers sent to clients. If a question comes in that matches a previous answer, this is sent back directly.

The Packet Cache is consulted first, immediately after receiving a packet. This means that a high hitrate for the Packet Cache automatically lowers the cache hitrate of subsequent caches."

So packet cache hit == no increase in (some) metrics.

If you disable it `disable-packetcache=yes` you probably get numbers you expect (although if you have caching turned on in dnsdist you should see low packet cache hits on the recursor side to begin with, generally).

**Comment by maxadamo** [comment]
@phonedph1 thanks a lot. Disabling `packetcache` I get the numbers that I was expecting. But `packetcache` seems to be a cool feature. 
1. this is not a bug and I am going to close the issue. 
2. note taken. I discuss it internally and I take a decision accordingly.

**Comment by omoerbeek** [comment]
I do not agree this is not a bug. ATM I'm not sure if this easy to fix in tyhe way that packet cache hits are also counted, but I sure want to get back to this to see what is possible. The least thing we can do is to document things better.
So reopening and changing the title.

**Comment by maxadamo** [comment]
When I closed this issue I thought about the same thing. Ideally, there should also be a number indicating the cache usage (which was quite high in my case).

**Comment by omoerbeek** [comment]
> When I closed this issue I thought about the same thing. Ideally, there should also be a number indicating the cache usage (which was quite high in my case).

IMO that is a different topic, we already have `packetcache-hits` and `packetcache-misses`.

I made a draft PR, which should be evaluated for performance impact before freview and merging.

**Comment by omoerbeek** [comment]
Moved to a future milestone. We have some more fundamental of stats collecting brewing. But it won't make 4.8.
