### ISSUE TITLE
Fail to get AXFR or IXFR responses for ECS request

### ISSUE THREAD

**Issue by laurretang** [PowerDNS/pdns#11542]
- Program: Authoritative, dnsdist, recursor
 - Issue type: Bug report

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. Config Auth: local-port=5353 
    create one zone named default.rpz, add some records, set tsig keys. Set the loglevel to 7 debug.
2. Config DNSDIST on the same vm of Auth: newServer({address="172.16.0.52:5353", qps=10000, **useClientSubnet=true**, checkInterval=3600)
3. Config Recursor: rpzPrimary("172.16.0.52", "default.rpz" , {refresh=10, tsigname='rpz', tsigalgo='hmac-md5', tsigsecret='it's hidden here'})
4. Close all the firewalld and iptables
5. Wait the Recursor to send axfr and ixfr requests.
6. Use tcpdump to capture reqs and rsps.

### Expected behaviour
Recursor can get axfr and ixfr responses.

### Actual behaviour
1. Recursor send AXFR request to Dnsdist.
2. Dnsdist forward AXFR to Auth with the OPT ECS
3. Auth send FIN and close the connection, without any logs output.
4. At last, Recursor output log: Apr 15 15:02:23 vm54 pdns-recursor: msg="Unable to load RPZ zone, will retry" subsystem="rpz" level=1 prio=4 ts="1650006143.075" exception="Remote nameserver closed TCP connection" from="172.16.0.52" refresh="10" zone="default.rpz"

### Other information
**If I set dnsdist useClientSubnet to false, the axfr and ixfr process works well.**
I think there must be some problems in Auth, and I will add more logs in function TCPNameserver::doConnection to check further

**Comment by laurretang** [comment]
Auth version: 4.5.1
Dnsdist version: 1.6.1
Recursor version: 4.6.2

**Comment by rgacogne** [comment]
Setting `useClientSubnet=true` tells dnsdist to alter the query's payload to either insert an additional EDNS Client Subnet option into an existing EDNS OPT record, or to create such a record if does not exist already. Unfortunately doing that breaks the TSIG signature, since that signature is designed to protect the integrity of the DNS payload.
You could consider upgrading your authoritative server to 4.6.x which supports using the proxy protocol instead of ECS to forward the initial client IP address to the server, see https://docs.powerdns.com/authoritative/settings.html#proxy-protocol-from
Since the proxy protocol payload is prepended before the DNS payload it should not break the TSIG signature: https://dnsdist.org/advanced/passing-source-address.html#proxy-protocol

**Comment by laurretang** [comment]
> Setting `useClientSubnet=true` tells dnsdist to alter the query's payload to either insert an additional EDNS Client Subnet option into an existing EDNS OPT record, or to create such a record if does not exist already. Unfortunately doing that breaks the TSIG signature, since that signature is designed to protect the integrity of the DNS payload. You could consider upgrading your authoritative server to 4.6.x which supports using the proxy protocol instead of ECS to forward the initial client IP address to the server, see https://docs.powerdns.com/authoritative/settings.html#proxy-protocol-from Since the proxy protocol payload is prepended before the DNS payload it should not break the TSIG signature: https://dnsdist.org/advanced/passing-source-address.html#proxy-protocol

Thank you.
In another way, may I use allow-axfr-ips instead of TSIG key to protect the relationship of master<->recursors?

**Comment by rgacogne** [comment]
> In another way, may I use allow-axfr-ips instead of TSIG key to protect the relationship of master<->recursors?

You can use `allow-axfr-ips` to allow all XFR requests coming from dnsdist to be accepted by the auth, but then any access checks need to be done on dnsdist's side: https://dnsdist.org/advanced/axfr.html
Note that this will ensure that requests not coming from your recursor's IPs will be refused, but will not protect the integrity of the RPZ zone during transfer.

**Comment by laurretang** [comment]
> Note that this will ensure that requests not coming from your recursor's IPs will be refused, but will not protect the integrity of the RPZ zone during transfer.

Okay, thanks for your reminding.
