### ISSUE TITLE
Tsig Replication not working from Bind to Powerdns

### ISSUE THREAD

**Issue by whitepiratebaku** [PowerDNS/pdns#11540]
Hello, we are trying to migrate from Bind master/slave setup to Powerdns Bind backend (we just need lua records). We are using Tsig keys and dnssec. I setted up all but bind keeps denying Powerdns, same configuration works between two Powerdns Bind Backend with TSIG keys. So is tsig replication supposed to work  between simple Bind and Powerdns Bind backend?

**Comment by Habbie** [comment]
Yes, that is supposed to work.

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
