### ISSUE TITLE
Ubuntu 22.04 (jammy) repo

### ISSUE THREAD

**Issue by pfak** [PowerDNS/pdns#11568]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description
@Habbie mentions there are jammy packages available, but no repo on https://repo.powerdns.com

### Usecase
Using PowerDNS on Ubuntu 22.04 (jammy)

### Description
Publish packages for jammy on https://repo.powerdns.com

**Comment by Habbie** [comment]
If anybody needs jammy packages right now, we do daily `master` builds - you can find them at https://github.com/PowerDNS/pdns/actions/workflows/builder.yml?query=branch%3Amaster

**Comment by m4k5ym** [comment]
Doesn't change this much.

I got a fresh installed jammy with master repo configured and it doesn't get any further due to unsolvable dependencies:

```
# apt install pdns-server
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pdns-server : Depends: libboost-program-options1.71.0 but it is not installable
               Depends: libssl1.1 (>= 1.1.1) but it is not installable
               Recommends: pdns-backend-bind but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Also there are no jammy packages available in master repo at all:

![grafik](https://user-images.githubusercontent.com/38684218/164784397-22f9a521-12eb-44d2-973a-e83492c76976.png)

**Comment by julienbriault** [comment]
Do you have any idea when the packages will be released for Ubuntu 22.04?

**Comment by oxc** [comment]
Is there anything I can do to help with this? I would be happy to provide patches to infra files, if that is possible and helpful.

**Comment by aerique** [comment]
I'll have a talk with @Habbie about it tomorrow.

**Comment by aerique** [comment]
We've run into this issue on the Builder: https://stackoverflow.com/questions/71941032/why-i-cannot-run-apt-update-inside-a-fresh-ubuntu22-04

So far it looks like we need to upgrade Docker there but I don't want to just do that without talking it through.

**Comment by aerique** [comment]
@Habbie updated the build host yesterday and we now have `jammy-master repos for auth, rec and dnsdist.

**Comment by oxc** [comment]
Cool, thanks! Will this also get repos for stable versions?

**Comment by Habbie** [comment]
> Cool, thanks! Will this also get repos for stable versions?

On the next releases of each (Recursor 4.7.0, Auth 4.7.0-alpha2, dnsdist 1.7.3 or 1.8.0).

**Comment by Habbie** [comment]
Thanks! We're tracking that in #10596, and text would be welcome.

**Comment by git-noise** [comment]
> 
ah indeed I thought that had ring a bell in my mind, but I forgot to search for existing threads. Added some answer elements in #10596.
Best,
