### ISSUE TITLE
dnsdist: missing latency metric when a server is down

### ISSUE THREAD

**Issue by hhoffstaette** [PowerDNS/pdns#11583]
- Program: dnsdist
 - Issue type: Bug report

### Short description
After updating from 1.7.0 to 1.7.1 I noticed that a server that has failed its liveliness check is correctly marked "down", but no longer reports its latency metric as 0; instead the metric is missing. This is a change in behaviour from 1.7.0.
The metric reappears when the server is set to "up" again.

### Environment
 - Operating system: Gentoo, kernel 5.15.35
 - Software version: dnsdist 1.7.1
 - Software source: self-compiled (I maintain my own package)

### Steps to reproduce
1. set server to down
2. inspect metrics, see server status as 0 (correct) but missing latency instead of 0

### Expected behaviour
Latency should be 0 for a server that is temporarily down.

**Comment by rgacogne** [comment]
Isn't that the case since https://github.com/PowerDNS/pdns/pull/10508 ?

**Comment by hhoffstaette** [comment]
> Isn't that the case since #10508 ?

Yes..I'm sorry, confusion on my part; you are completely correct. The _real_ problem is actually a bug in Grafana, which no longer displays missing metrics as 0 _even when told to do so_.
