### ISSUE TITLE
PowerDNS doesn´t show SOA request

### ISSUE THREAD

**Issue by jhonnypaco** [PowerDNS/pdns#11593]
The issues doesn't exist in a blog or comments.

 - Program: Authoritative, 
 - Issue type: Bug Report: The powerDNS server doesn´t show SOA authority section.
### Short description
The request to PowerDNS server "dig @200.7.160.10 umsa.bo soa +norec" doesn't work, all parameters are public

### Environment

 - Operating system: Debian 11
 - Software version: PowerDNS Authoritative Server 4.5.4 (C) 2001-2022 PowerDNS.COM BV
 - Software source: Operating system repository and PowerDNS repository.

### Steps to reproduce

1. When execute the next command in the master server "pdnsutils check-zone umsa.bo"
2. The answer was:
root@master:~# pdnsutil check-zone umsa.bo
Apr 29 11:59:41 [bindbackend] Parsing 0 domain(s), will report when done
Apr 29 11:59:41 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Apr 29 11:59:41 Query 94870761653616: select id,name,master,last_check,notified_serial,type,account from domains where name=?
Apr 29 11:59:41 Query 94870761653616: 157 usec to execute
Apr 29 11:59:41 Query 94870761653616: 231 total usec to last row
Apr 29 11:59:41 Lookup for 'SOA' of 'umsa.bo' within zoneID -1
Apr 29 11:59:41 Found no authoritative zone for 'umsa.bo' and/or id -1

### Expected behaviour
Using another domain por example "dig @200.75.160.20 megalink.com soa +norec", the answer show me this
root@master:~# dig @200.75.160.20 megalink.com soa +norec

; <<>> DiG 9.16.1-Ubuntu <<>> @200.75.160.20 megalink.com soa +norec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4073
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;megalink.com.                  IN      SOA

;; ANSWER SECTION:
megalink.com.           86400   IN      SOA     ns2.megalink.com. jcgalvez.megalink.com. 2022032301 28800 7200 2419200 7200

;; AUTHORITY SECTION:
megalink.com.           86400   IN      NS      ns4.megalink.com.
megalink.com.           86400   IN      NS      ns2.megalink.com.
megalink.com.           86400   IN      NS      ns3.megalink.com.
megalink.com.           86400   IN      NS      ns5.megalink.com.

;; ADDITIONAL SECTION:
ns2.megalink.com.       86400   IN      A       200.75.160.20
ns3.megalink.com.       86400   IN      A       185.101.97.183
ns4.megalink.com.       86400   IN      A       94.76.213.198
ns5.megalink.com.       86400   IN      A       88.99.13.51

;; Query time: 16 msec
;; SERVER: 200.75.160.20#53(200.75.160.20)
;; WHEN: Fri Apr 29 16:04:25 UTC 2022
;; MSG SIZE  rcvd: 222

### Actual behaviour
root@dns:/etc/powerdns# dig @200.7.160.10 umsa.bo soa +norec

; <<>> DiG 9.16.27-Debian <<>> @200.7.160.10 umsa.bo soa +norec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37662
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;umsa.bo.                       IN      SOA

;; ANSWER SECTION:
umsa.bo.                3600    IN      SOA     marte.umsa.bo. admdns.umsa.bo. 2022031908 3600 1800 604800 86400

;; Query time: 0 msec
;; SERVER: 200.7.160.10#53(200.7.160.10)
;; WHEN: Fri Apr 29 10:59:40 -04 2022
;; MSG SIZE  rcvd: 85

### Other information
The topology of DNS servers are Master/Slave, the master doesn´t public DNS server, but the two slaves are public 200.7.160.10 and 200.7.170.100.
I am no shure if this issues is a bug, may be possible config missing, but I don´t found anything blogs about that

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
