### ISSUE TITLE
Same SERIAL on multiple Zone

### ISSUE THREAD

**Issue by maxihoster** [PowerDNS/pdns#11617]
- Program: Authoritative, 
 - Issue type: Bug report

### Short description
Creation new zone use the same SERIAL on multiple zone

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.7.0
 - Software source: 
1. Connect WHMCS with API to PowerDNS
2. Create New zone
3. Zone have the same serial

### Expected behaviour
I want have each zone and his own serial

### Other information
If we do the same thing I mean create new zone with PowerDNS-Admin, we have the same issue...

**Comment by omoerbeek** [comment]
It's perfectly fine for two zones to have the same serial, as a serial only has meaning for a specific zone. So I am wondering what problem you have with two zones having the same serial.

**Comment by maxihoster** [comment]
If I understand correctly, I can have 400 domains with the same serial number? Which is my case, because I created 400 zones yesterday...

Does this have any impact on safety or operation? Because in these 400 domains, the SOA record has the same serial number

**Comment by omoerbeek** [comment]
That is no problem. Serial are used to indicate the zone's content has clanged. Serials are not used to identify zones.

**Comment by omoerbeek** [comment]
Closing this as it is not an actual issue.
