### ISSUE TITLE
dnsdist: DoT and DoH should have option to respond based on server SNI

### ISSUE THREAD

**Issue by w3goodies** [PowerDNS/pdns#11622]
- Program: dnsdist
 - Issue type: Feature request

### Short description
At this moment dnsdist's DoT and DoH can only respond on single domain on a single IP address.

### Usecase
Let's say we've test.example.com and test2.example.com and we want both of them to listen on DoT and DoH, to process queries differently for both, on a single server and single global IP Address. 

```
addTLSLocal('0.0.0.0', "/test.example.com/fullchain.pem", "/test.example.com/privkey.pem")
addDOHLocal('0.0.0.0', "/test.example.com/fullchain.pem", "/test.example.com/privkey.pem")
```

This is the current way and it will process test.example.com DoT and DoH requests appropriately, but unless we've a different global IP address, it's not possible to add any other domain name. How can we add test2.example.com? Since we can only provide single certificate and key.

Something like SNI option in addTLSLocal and addDOHLocal could prove useful like this:

```
addTLSLocal('0.0.0.0', "test.example.com/fullchain.pem", "test.example.com/privkey.pem", {sni="test.example.com"})
addTLSLocal('0.0.0.0', "test2.example.com/fullchain.pem", "test2.example.com/privkey.pem", {sni="test2.example.com"})
addDOHLocal('0.0.0.0', "test.example.com/fullchain.pem", "test.example.com/privkey.pem", {sni="test.example.com"})
addDOHLocal('0.0.0.0', "test2.example.com/fullchain.pem", "test2.example.com/privkey.pem", {sni="test2.example.com"})
```

It would listen on single 853 and 443, and process both of them based on SNI. 

### Description
Currently, I can do this while having Nginx as the reverse proxy:

```
stream {
  map $ssl_preread_server_name $dotBackend {
    **test**.example.com  127.0.0.1:854;
    **test2**.example.com  127.0.0.1:855;
  }

  server {
    listen 0.0.0.0:853;

    proxy_connect_timeout 1s;
    proxy_timeout 10s;

    proxy_pass $dotBackend;
    ssl_preread on;
  }

  map $ssl_preread_server_name $dohBackend {
    test.dnsforfamily.com  127.0.0.1:954;
    test2.dnsforfamily.com  127.0.0.1:955;
  }

  server {
    listen 0.0.0.0:443;

    proxy_connect_timeout 1s;
    proxy_timeout 10s;

    proxy_pass $dohBackend;
    ssl_preread on;
  }
}
```

And listening in dnsdist like this:
```
addTLSLocal('127.0.0.1:854', "/test.example.com/fullchain.pem", "/test.example.com/privkey.pem")
addDOHLocal('127.0.0.1:954', "/test.example.com/fullchain.pem", "/test.example.com/privkey.pem")
addTLSLocal('127.0.0.1:855', "/test2.example.com/fullchain.pem", "/test2.example.com/privkey.pem")
addDOHLocal('127.0.0.1:955', "/test2.example.com/fullchain.pem", "/test2.example.com/privkey.pem")

```

It would be better if dnsdist provides such feature natively without any reverse proxy overhead.

We can also solve this issue without any proxy overhead, if we use certificate with multiple SANs or wildcard certificates and using dnsdist as it is.

**Comment by rgacogne** [comment]
So I'm not sure what the gain is compared to a certificate with multiple Subject Alt Name entries, which are very easy to get these days? `SNIRule` [1] then allows handling queries to different endpoints in a specific way.

[1]: https://dnsdist.org/rules-actions.html#SNIRule

**Comment by rgacogne** [comment]
I'm closing this since the use-case is not clear to me, please reach out if you still need this!
