### ISSUE TITLE
Implement RefuseAction()

### ISSUE THREAD

**Issue by w3goodies** [PowerDNS/pdns#11623]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Since dnsdist have DropAction, NoneAction, AllowAction, DelayAction, and others, it makes appropriate sense to also implement RefuseAction().

**Comment by Habbie** [comment]
Is https://dnsdist.org/rules-actions.html#RCodeAction what you are looking for?

**Comment by w3goodies** [comment]
> Is https://dnsdist.org/rules-actions.html#RCodeAction what you are looking for?

Yes, that's how I did it but I was merely telling it would be more code consistent if we've all the functions related to DNSAction.* constants.

- DNSAction.Allow => AllowAction()
- DNSAction.Delay => DelayAction()
- DNSAction.Drop => DropAction()
- DNSAction.HeaderModify => ??
- DNSAction.None => NoneAction()
- DNSAction.Nxdomain => ??
- DNSAction.Pool => PoolAction()
- DNSAction.Refused => ??
- DNSAction.ServFail => ??
- DNSAction.Spoof => SpoofAction()
- DNSAction.SpoofPacket => SpoofPacketAction()
- DNSAction.SpoofRaw => SpoofRawAction()
- DNSAction.Truncate => ??
- DNSAction.NoRecurse => NoRecurseAction()

I think if we have DropAction(), then RefuseAction() and ServFailAction() should also be available.

**Comment by rgacogne** [comment]
I'm afraid I don't really understand why it would make sense to have one action for each possible DNS rcode when we already have a generic one that can handle all DNS rcodes, including ones that have not been defined yet. To me it feels like a lot of code duplication for no gain.
