### ISSUE TITLE
Consider using `libxdp` and full `libbpf` for XDP/AF_XDP programs

### ISSUE THREAD

**Issue by Y7n05h** [PowerDNS/pdns#11636]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Add `libxdp` and full `libbpf` in dnsdist

### Description

Now dnsdist use `ext/libbpf/libbpf.h`for XDP program. But this is only a small part of libbpf. This is missing a lot of helper functions useful for `AF_XDP`. So in order to use `AF_XDP` to improve the performance of dnsdist, it is necessary to use [`libxdp`](https://github.com/xdp-project/xdp-tools/). But libxdp depends on libbpf, so in order to use libxdp also need libbpf. So can we consider adding full libbpf to use libxdp?

Or do we not use `libxdp` for the now, just use the full `libbpf`? At present, XDP related functions have been migrated to [`libxdp`](https://github.com/xdp-project/xdp-tools/) and marked as deprecated(https://github.com/libbpf/libbpf/commit/277846bc6c15b603c8fdfbd757700443c95a4a96) in libbpf, but they can still be used.

**Comment by rgacogne** [comment]
I'm totally fine with making `libxdp` and `libbpf` requirements for `AF_XDP` (of course we still need to be able to build without these, especially on "not-linux"). Our use of `libbpf.h` in `ext/` is a hack anyway, perhaps we can only use it if the proper `libbpf` is not available?

**Comment by Y7n05h** [comment]
@rgacogne I'm really sorry, I know little about `automake` and `autoconf` and I just didn't seem to get it right. Can you help with this work?

**Comment by Y7n05h** [comment]
> Sure! I suggest you focus on getting `AF_XDP` working on a branch, without worrying about what happens when the libs are not available, and I can show you how to handle that properly later!

That's great. Thank you.

**Comment by rgacogne** [comment]
Closing this entry since it is/will be handled in https://github.com/PowerDNS/pdns/pull/11652
