### ISSUE TITLE
PDNSutil report no delegation for zone

### ISSUE THREAD

**Issue by basd82** [PowerDNS/pdns#11649]
Hi when i edit domain in my example dikkenberg.net and i get an error no delegation in parrent. 
This primary for this zone:

```
root@pdns1:~# pdnsutil edit-zone dikkenberg.net
May 26 06:53:29 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
[Error] No delegation for zone 'dikkenberg.net' in parent '.'
Checked 36 records of 'dikkenberg.net', 1 errors, 0 warnings.
There was a problem with your zone
Options are: (e)dit your changes, (r)etry with original zone, (a)pply change anyhow, (q)uit:
q
root@pdns1:~# pdnsutil --version
pdnsutil 4.7.0-alpha1.241.master.g9ff864a39
```

I think this error is in error, or should be at least an warning

**Comment by mnordhoff** [comment]
Why does the nameserver have a root zone? _Does_ it have a `net` or `dikkenberg.net` delegation?

It _is_ an error...

**Comment by basd82** [comment]
> Why does the nameserver have a root zone? _Does_ it have a `net` or `dikkenberg.net` delegation?
> 
> You may have reason to ignore it, but it _is_ an error...

I checked i dont have .net zone

Strainge enoufh i  don't see "." in zone list 
with : 
pdnsutil list-all-zones

but when i use the rest interface query all zones:

  {
"account": "bas",
"dnssec": true,
"edited_serial": 0,
"id": "=2E",
"kind": "Native",
"last_check": 0,
"masters": [],
"name": ".",
"notified_serial": 0,
"serial": 0,
"url": "/api/v1/servers/localhost/zones/=2E"
},

i din't add a . zone

**Comment by Habbie** [comment]
> Strainge enoufh i don't see "." in zone list
> with :
> pdnsutil list-all-zones

Are you sure?



> i din't add a . zone

Well, apparently somebody did.

I'm closing this as it does not appear to be a bug.
