### ISSUE TITLE
Implement metrics for ProxyMapping

### ISSUE THREAD

**Issue by SrX** [PowerDNS/pdns#11648]
- Program: Recursor
- Issue type: Feature request

### Short description
Add metrics for ProxyMapping

### Usecase
Visual inspection of ProxyMapping usage.

### Description
Expose metrics via Prometheus and rec_control about queries that were processes by ProxyMapping thing.

**Comment by omoerbeek** [comment]
I'm planning to work on this soon. What kind of metrics were you thinking off? 

I can see two approaches:

- a counter of queries handled by ProxyMapping based on source address and another counter for domain specific mapping performed. 
- a pair of counters per `addProxyMapping` line, one  for a subnet match and one for a domain match. 

The latter is more complex, but would give insight which `addProxyMapping` lines are actually used.

**Comment by SrX** [comment]
Indeed the 2nd one is the preferred, it represents the "match & apply of proxymapping" feature. But if it makes to complex and can impact in the performance, the 1st one could work.
