### ISSUE TITLE
Zone creation returns an error, creates the zone locally.

### ISSUE THREAD

**Issue by rlewkowicz** [PowerDNS/pdns#11670]
Reproduce:
```
cat <<EOF > `pwd`/recursor.tmp
local-address=0.0.0.0,::
include-dir=/etc/powerdns/recursor.d
api-config-dir=/etc/powerdns/recursor.d
EOF
docker run \
-e PDNS_RECURSOR_API_KEY='s3cret' \
-p 8082:8082 -p 53:53 \
-v `pwd`/recursor.tmp:/etc/powerdns/recursor.conf \
powerdns/pdns-recursor-44
```
```
 curl --location --request POST 'http://127.0.0.1:8082/api/v1/servers/localhost/zones' \
--header 'X-API-Key: s3cret' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "kind": "Native",
    "name": "test.local.",
    "recursion_desired": false
}'
```
output:
```
{"error": "Could not find domain 'test.local'"}
```

The zone exists on disk. Am I missing something?

**Comment by kpfleming** [comment]
Is `pdns-recursor-44` an image with PowerDNS Recursor 4.4.x in it? If so, that's already EOL and you should probably test with something newer.

**Comment by rlewkowicz** [comment]
@kpfleming you can swap that with master and it will do the same thing 
`pdns-recursor-master`

**Comment by phonedph1** [comment]
set auth-zones= and then it will work

**Comment by phonedph1** [comment]
specifically from the docs:

To properly process new zones, the following conditions must be true:

forward-zones, forward-zones-recurse and/or auth-zones settings must be set (possibly to the empty string) in a configuration file. These settings must not be overridden on the command line. Setting these options on the command line will override what has been set in the dynamically generated configuration files.

**Comment by rlewkowicz** [comment]
Personally, I was exploring this as a shim for external dns. I'm used to working in cloud environments, so I know what the end game is, but I don't always understand the underlying concepts. Now I have to build and understand these components my self. 

PowerDNS, and VinylDNS both provide these highly functional compose files out of the box, but they take a long time to build. So the "quickstarts" in both cases are very time and compute intensive. 

I didn't understand the concepts of recursors and authoritative servers. If you're here, there's a good chance, you're not looking to set up a recursor, you're looking to set up an auth server. 

Both assets will respond similarly to api requests, but you'll hit a wall with the recursor. 

You want something like this:

```
docker run -d \
-e PDNS_AUTH_API_KEY='s3cret' \
-p 8081:8081 -p 53:53 -p 53:53/udp \
powerdns/pdns-auth-47
```
