### ISSUE TITLE
Fix forward mapping when loading entries from an `etc-hosts` file

### ISSUE THREAD

**Issue by fredmorcos** [PowerDNS/pdns#11690]
- Program: Recursor
 - Issue type: Bug report

### Short description
Description by @omoerbeek: https://github.com/PowerDNS/pdns/pull/11682#issuecomment-1149744457

> I did not look at the code yet, but did a few tests.
> 
> Looking at at an example `/etc/hosts` containing
> 
> ```
> 194.109.6.2     p
> 194.109.6.3     p
> 2001:888:0:7::2 p
> 2001:888:0:7::2 q
> ```
> 
> I see that `dig -t A p` succeeds but has one record. `dig -t AAAA p` gives me an empty answer section. `dig -t AAAA q` works and gives me a single record.
> 
> In an ideal world the forward mapping would work for all cases: two answer records for `dig -t A p`, one record for `dig -t AAAA p` and one record for `dig -t AAAA q`.
> 
> Having both an IPv4 and an IPv6 address for the same name _is_ very common. So it would be nice if we would handle at least that case.
> 
> I don't know if this is feasible with the current structure, I guess it would mean merging domains in some cases.
> 
> The reverse (PTR) mapping should give only the first name encountered for each address. This seems to work as expected.

https://github.com/PowerDNS/pdns/pull/11682#issuecomment-1149781192

> To be clear, the behavior above is already present in master, so it is not a regression.

### Environment
 - Operating system: N/A
 - Software version: master
 - Software source: any

### Steps to reproduce
Available in the description above.

### Expected behaviour
Available in the description above.

### Actual behaviour
Available in the description above.

### Other information

**Comment by sspans** [comment]
Just ran into this as well. 

Was looking forward to using the ipv6 support in 4.8, but without support for duplicated hostnames that's a bit painful.

**Comment by sspans** [comment]
Dig output from after patch:

```
sten@zem:~$ dig @::1 -p 5300 ANY p

; <<>> DiG 9.16.33-Debian <<>> @::1 -p 5300 ANY p
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34905
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;p.				IN	ANY

;; ANSWER SECTION:
p.			86400	IN	NS	localhost.
p.			86400	IN	A	194.109.6.2
p.			86400	IN	A	194.109.6.3
p.			86400	IN	AAAA	2001:888:0:7::2
p.			86400	IN	SOA	localhost. root. 1 604800 86400 2419200 604800
```
