### ISSUE TITLE
secpoll.zone says 'known vulnerabilities' for auth-4.7.0-alpha1

### ISSUE THREAD

**Issue by ZaphodB** [PowerDNS/pdns#11721]
- Program: Authoritative
 - Issue type: Bug report

### Short description
secpoll.zone lists "3 Unsupported pre-release (known vulnerabilities)" for auth-4.7.0-alpha1.security-status which made me wonder whether there were known vulnerabilities in said version or whether maybe i missed an update.
While "Unsupported pre-release" is correct i think it should not mention known vulnerabilities there.
@Habbie mentioned that this message was in error.

### Environment
 - Operating system: Debian bullseye/11.3
 - Software version: 4.7.0~alpha1-1pdns.bullseye
 - Software source: PowerDNS repository

### Steps to reproduce
1. install 4.7.0~alpha1-1pdns.bullseye

### Expected behaviour
The secpoll feature should not mention known vulnerabilities.

### Actual behaviour
message logged: Jun 24 11:06:05 shinjuku pdns_server[3728946]: PowerDNS Security Update Mandatory: Unsupported pre-release (known vulnerabilities)

**Comment by Habbie** [comment]
Otto points out that this is correct because 4.7.0-alpha1 does not have the fix for https://docs.powerdns.com/authoritative/security-advisories/powerdns-advisory-2022-01.html
