### ISSUE TITLE
Add actual last-seen latency to dump-nsspeeds output in recursor

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#11736]
- Program: Recursor
 - Issue type: Feature request

### Short description
In the results of "rec_control dump-nsspeeds /path/to/filename" it would be useful to have the actual last sampled latency as an additional field on each IP address output in the command. Currently, the "latency" is actually a decaying, computed figure instead of the actual latency as seen by the recursor to the distant authoritative server - this is confusing and not very useful for  obvious external automated analysis.

### Usecase
It is interesting (and sometimes required) to understand the latency figures for remote authoritative servers. When network changes are performed, it would be useful in bulk fashion to see what happens before and after a change is implemented when looking at authoritative answers.  Trivial parsing of the text output of dump-nsspeeds can be performed quickly, if that data existed. Currently there is no automated way to do this at scale with data obtained from the resolver (without extensive dnstap, protobuf, or pcap data evaluation) but the resolver is very close to having that data but doesn't quite store what is required for the analysis.  Doing packet captures or log analysis with external tool add-ons are heavy and requires significant code implementation; putting the real figure in the dump-nsspeeds result seems to be much more elegant and automatic, and this work is already being done by the recursor.  Using a running average of results over X seconds (or Y ringbuffer results?) is also an option that would be even better, but requires then at least two data points for each authoritative server - the average, and number of samples collected so that the next result can be averaged into the average. This averaged method may be more complex than necessary, though it would smooth outliers, which may or may not be a desirable result.  If an average is used, then you might as well go "all the way" and do min, max, average, and standard deviation for the sample interval.

### Description
For the purposes of this request, the decaying latency figure can remain the same (and no code change seems to be required there.)

One possible output model would be to add actual latency with a "/" following the computed/decaying latency figure. The exact method by which this is reported in the output is not strongly preferred. Perhaps an entirely different "rec_control" command is warranted. Example using the inclusion-by-/ model:

anyns.pch.net -> 204.61.216.4/14.109665/15.993292 2001:500:14:6004:ad::1/520.199158/533.821582

**Comment by mnordhoff** [comment]
FWIW, Unbound tracks (among other things) the smoothed RTT and its variability.

https://www.nlnetlabs.nl/documentation/unbound/info-timeout/
