### ISSUE TITLE
Redhat 9 build support

### ISSUE THREAD

**Issue by istiak101** [PowerDNS/pdns#11753]
Ref: https://github.com/PowerDNS/pdns-builder/issues/60

- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description
Redhat 9 and 1:1 forks are now GA for some time. Any plan to add support for it in PowerDNS official repository?
https://repo.powerdns.com/el/x86_64/

https://developers.redhat.com/articles/2022/05/18/whats-new-red-hat-enterprise-linux-9
https://almalinux.org/blog/almalinux-9-now-available/
https://en.euro-linux.com/blog/eurolinux-9-0-released/

### Usecase
PowerDNS repository for Redhat 9 and Redhat 9 based distro.

### Additional context

As CentOS switched from being a downstream distro to a upstream distro of Redhat. RHEL rpms should not built with CentOS docker image anymore for RHEL 9.

https://github.com/PowerDNS/pdns-builder/tree/master/demo/builder-support/dockerfiles

I propose to build this with AlmaLinux docker image.
https://hub.docker.com/_/almalinux

**Comment by Habbie** [comment]
I started this work on CentOS 9 Stream some time ago, but never finished it. Back then, a lot of dependencies were missing. If somebody would pick up the work in https://github.com/Habbie/pdns/commits/centos-9-stream (or submit something fresh), this would help us deliver EL9 packages to the repo quicker.

> I propose to build this with AlmaLinux docker image.

We are currently standardised on Oracle Linux for building, but this should be a one-line difference in the builder-support Dockerfile.

**Comment by Habbie** [comment]
(I see Oracle Linux 9 is not on Docker Hub yet, so basing the work on Alma might indeed make sense for now.)

**Comment by istiak101** [comment]
I will try building the spec and see what dependencies are missing and possibly create a repository for those dependency. As I am not official proven packager of Fedora/EPEL I can't update those packages. Some packages in Fedora/EPEL are not that active. I will see what I can do to manage those dependency.

I think GeoIP can be replaced with Libmaxminddb which is currently in Appstream repository.

https://github.com/Habbie/pdns/commit/9036b23ab13fed37f43c618f6088a236b20d2c17
https://github.com/PowerDNS/pdns/blob/master/m4/pdns_with_geo.m4

**Comment by Habbie** [comment]
> create a repository for those dependency.

While that is much appreciated, we'd rather drop a backend than add another repo, if we have to choose.

**Comment by Habbie** [comment]
I started the work on this yesterday. Incidentally Oracle Linux 9 is on the Docker Hub now, so I could build on that immediately.

Unfinished work in #11788 - testing welcome!

**Comment by istiak101** [comment]
Thank you very much.

**Comment by Habbie** [comment]
You're welcome! Please let us know if you run into any problems with it.

**Comment by Habbie** [comment]
And, to be clear, indeed I removed libgeoip and left libmaxminddb in, and luajit became available meanwhile, so there were no dependency issues in the end.

**Comment by Habbie** [comment]
> I built both EL8 and EL9 aarch64 in rhel+epel mock chroot with the spec file. Initial build failed for both as mock chroot didn't have perl and hostname in EL8. And for EL9 I was having `cannot determine a size for time_t`. Adding gcc-c++ for EL9 fixed that.

ok - we install `"@Development Tools"` which includes the C++ compiler. I'm somewhat surprised your mock did not have that.

> Removing this even for EL8, EL7 would make sense

Also makes sense to me, but I know some users generate their own databases, so I don't want to take that feature away from them.
