### ISSUE TITLE
useClientSubnet Ignored

### ISSUE THREAD

**Issue by meluvalli** [PowerDNS/pdns#11767]
Hello, when I use useClientSubnet=true, it's ignored.  Everything shows from localhost still.

My Config:
```
		setLocal("127.0.0.1:5353")

		-- allow query from all IP addresses
		addACL('0.0.0.0/0')

		-- add a DoH resolver listening on port 443 of all interfaces
		addDOHLocal("0.0.0.0:443", "/etc/dnsdist/certificate/fullchain.cer", "/etc/dnsdist/certificate/cert.key", { "/" }, { doTCP=true, reusePort=true, tcpFastOpenSize=0 })

		-- downstream resolver
		newServer({address="127.0.0.1:53",qps=5, name="resolver1", useClientSubnet=true})
```

Is this a bug?

**Comment by rgacogne** [comment]
Hello,

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
