### ISSUE TITLE
Slave 'Error resolving SOA or NS' if master used 'zone-cache-refresh-interval >0'

### ISSUE THREAD

**Issue by zoomer85** [PowerDNS/pdns#11786]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Some time ago i am upgrade pdns from 4.3 to 4.6.  
I am using hidden master and several slaves.

### Environment
 - Operating system: Ubuntu 20.04
 - Software version: 4.6.2
 - Software source: PowerDNS repository

### Steps to reproduce
If master used default value for new option `zone-cache-refresh-interval=300` or any not `0` value , slaves can't get first AXFR.  
But if after not good AXFR i try to get AXFR from slave with dig, all working fine.  
If set `zone-cache-refresh-interval=0`, this fully disable this option and all AXFR working good every time.  

### Expected behaviour
I want working AXFR with `zone-cache-refresh-interval` option.

### Actual behaviour
If master use `zone-cache-refresh-interval` option, first AXFR from any slave not working (produced no answers) and zone not transferring in the future.

### Other information
```
master - Queued also-notification of domain '12.22.192.22.in-addr.arpa' to 192.168.0.11:53
slave1 - Received NOTIFY for 12.22.192.22.in-addr.arpa from 192.168.0.10 for which we are not authoritative, trying supermaster
slave1 - Error resolving SOA or NS for 12.22.192.22.in-addr.arpa at: 192.168.0.10: Query to '192.168.0.10' for SOA of '12.22.192.22.in-addr.arpa' produced no answers
master - Removed from notification list: '12.22.192.22.in-addr.arpa' to 192.168.0.11:53 (was acknowledged)
```

Actual master config
```
socket-dir=/var/run/pdns
launch=bind
allow-axfr-ips=127.0.0.1,192.168.0.11
config-dir=/etc/powerdns
disable-axfr=no
expand-alias=yes
gmysql-dbname=xxx
gmysql-host=192.168.0.9
gmysql-password=xxx
gmysql-port=3306
gmysql-user=xxx
launch=gmysql
local-address=127.0.0.1,192.18.0.10
local-port=53
loglevel=5
max-tcp-connections=100
only-notify=192.18.0.11
primary=yes
receiver-threads=2
resolver=127.0.0.1:5300
version-string=powerdns
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=127.0.0.1,::1
webserver-loglevel=none
```

**Comment by mind04** [comment]
Related to #11638. 
Notify is sent before a new zone is present in the zone-cache.
