### ISSUE TITLE
How to enable DNSSEC with backend odbc

### ISSUE THREAD

**Issue by nedngo** [PowerDNS/pdns#11787]
Hi verybody!
I using backend odbc but i dont enable dnssec. How to enable?
Thank all!

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
