### ISSUE TITLE
Handle any-to-tcp like Google does it

### ISSUE THREAD

**Issue by Fusl** [PowerDNS/pdns#1179]
any-to-tcp=yes on the recursor just sends a truncated (tc) flag back with no response within. A dig ANY . @re.cu.rs.or +notcp +ignore therefor just send's 17 bytes back to me (differs for each domain and i think also for each source ip).

However. If any-to-tcp is set to yes, the recursor always answers UDP-ANY-Queries with a truncated but and no real answer. This is good as it prevent's DNS amplification and DRDoS attacks in a way that matters.

So what i think would still be a more better thing than truncating all ANY-Queries is exactly this, what Google is also doing with their Public DNS Servers.

Why?

As (hopefully) anyone knows, UDP is the fastest (but most insecure) protocol in the www and therefor i think that queries are answered faster with this improvement.
Also most DNS clients out there are configured to first try queries via UDP and then fallback to TCP.
When i set any-to-tcp=no, query the recursor 50 times and calculate the average response time, i get 47.24ms
But, when i set any-to-tcp=yes and do the same thing again, i get 92.84. (Tested three times in a row (set to no, set to yes, no, yes, no, yes) and i get similar results every time.)

So, how does it work exactly/what do we need to change?

Set a timeout for an ANY whitelist to x seconds (any-to-tcp-udp-seconds), x queries (any-to-tcp-udp-queries), x answered queries (any-to-tcp-udp-answers) or all of them. (I think Google is doing x queries, where x is a random positive integer). The Recursor has it's whitelist table for ANY queries over UDP.

If the recursor receives a query on tcp, then: Answer it and put the source IP address into the whitelist table (with timestamp = current timestamp, udpqueriesrcvd = 0 and udppacketssent = 0).

If the recursor receives a query on udp, check if the set parameters in the config file match the conditions.
-> If conditions met: Answer query normal via UDP as if any-to-tcp hasn't been set. Increase udpqueriesrcvd +1 and udppacketssent with the packets sent in this answer.
-> If conditions are not met: Drop the source IP from the whitelist table and return a truncated 0 length answer. With this answer, most DNS client out there retry in TCP mode.

**Comment by Habbie** [comment]
Patches or Lua scripts welcome. Closing this, thank you!
