### ISSUE TITLE
DNSProxy complete ALIAS timeout

### ISSUE THREAD

**Issue by zhungdongmei** [PowerDNS/pdns#11796]
Background: 
  1. use powerdns-4.2.1, install as Authoritative Server
  2. set pdns.conf resolver= x.x.x.x and expand-alias=yes
  
Problem:
in this week , it resolve all ALIAS timeout suddenly and can't revert exclude restart . 
But we dig @`resolver `in server machine is ok.

pdns log ,only have timeout log like:  
   **pdns_server: Jul 19 06:12:10 Recursive query for remote [ip:port] with internal id 1 was not answered by backend within timeout, reusing id**
only have timeout log, no send error or receive error log

Could you give me some suggestion or  other information??

**Comment by klaus-nicat** [comment]
If it happens again I guess you have to use tcpdump to see if queries are sent to the resolver, if there are answers or not, and then analyze what is going on.

**Comment by Habbie** [comment]
This ticket is useless. The few logging lines you included have been corrupted. Also, you are running an outdated, unsupported version.

We are closing this. If you have a bug to report in a supported version, we will be here.

**Comment by banoleb** [comment]
@zhungdongmei 
This is exactly what it means that the resolver for the alias is not always responding or is overloaded.
This also leads to the dropping of regular requests.
If the auth server can't resolve an alias, it begins to  try to do so multiple times, and as a result, other requests suffer (they simply get dropped). so be careful when using alias))
i use pdns-auth-48:4.8.4 and have the same problem sometimes
