### ISSUE TITLE
dnsdist cannot hijack AAAA type DNS equest.

### ISSUE THREAD

**Issue by DengLZ** [PowerDNS/pdns#11806]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description

addAction("www.dnsdist.org.", SpoofAction({"10.0.2.2"}))

The above line configuration can only hijack DNS requests of type A, and cannot hijack DNS requests of type AAAA.

The reference configuration is as follows
![image](https://user-images.githubusercontent.com/9841643/181412660-5844a832-cb94-47a2-ba55-af6e596993d9.png)

### Environment

 - Operating system:  centos7
 - Software version:  1.6.0
 - Software source: 

### step 1
DNS server ip 
10.0.9.64

Related configuration
addAction("www.dnsdist.org.", SpoofAction({"10.0.2.2"}))

### step 2
dig -t A www.dnsdist.org @10.0.9.64

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> -t A www.dnsdist.org @10.0.9.64
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37788
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.dnsdist.org.		IN	A

;; ANSWER SECTION:
www.dnsdist.org.	60	IN	A	10.0.2.2

;; Query time: 0 msec
;; SERVER: 10.0.9.64#53(10.0.9.64)
;; WHEN: Thu Jul 28 11:25:00 CST 2022
;; MSG SIZE  rcvd: 60

### step 3
dig -t AAAA www.dnsdist.org @10.0.9.64

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> -t AAAA www.dnsdist.org @10.0.9.64
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1744
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.dnsdist.org.		IN	AAAA

;; ANSWER SECTION:
www.dnsdist.org.	86400	IN	CNAME	dnsdist.org.
dnsdist.org.		86400	IN	AAAA	2a03:b0c0:2:d0::4ab:8001

;; Query time: 340 msec
;; SERVER: 10.0.9.64#53(10.0.9.64)
;; WHEN: Thu Jul 28 11:25:06 CST 2022
;; MSG SIZE  rcvd: 75

**Comment by phonedph1** [comment]
Sure it can if you give it something respond with, eg, `addAction("www.dnsdist.org.", SpoofAction({"10.0.2.2","::5"}))`

If you want to 'block' `AAAA` when you don't provide that you need to use a combination of other rules.

**Comment by DengLZ** [comment]
thank you for your reply!
