### ISSUE TITLE
dnsdist docs: hash or not hash cookie

### ISSUE THREAD

**Issue by nils-wisiol** [PowerDNS/pdns#11810]
- Program: dnsdist
 - Issue type: Bug report

### Short description
The docs on cookie hashing are unclear and perhaps wrong.

### [Current Docs](https://dnsdist.org/reference/config.html) Wording

> cookieHashing=false: bool - Whether EDNS Cookie values will be hashed, resulting in separate entries for different cookies in the packet cache. This is required if the backend is sending answers with EDNS Cookies, otherwise a client might receive an answer with the wrong cookie.
> skipOptions={}: Extra list of EDNS option codes to skip when hashing the packet (if cookieHashing above is false, EDNS cookie option number will already be added to this list).

### Expected behaviour
Not doing anything, from above I am assuming that `cookieHashing=false` and thus EDNS cookies will not be hashed.

### Actual behaviour
Without additional config, I get replies with bad cookies after the 1st time. (Frist time was okay.) Changing the config to `cookieHashing=true`, cookies are okay on the first and second time.

**Comment by zeha** [comment]
> This is required if the backend is sending answers with EDNS Cookies, otherwise a client might receive an answer with the wrong cookie.

This is pretty clear to me... but maybe it could use better wording?

**Comment by nils-wisiol** [comment]
Admittedly, reading it again helped, but I will create a tiny PR for this anyway.

**Comment by rgacogne** [comment]
Thanks for the PR, I'm closing this issue now :)
