### ISSUE TITLE
auth: Empty nsec3param fails with dnssec=false

### ISSUE THREAD

**Issue by nvaatstra** [PowerDNS/pdns#11824]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

If you send a zone to the Auth API with nsec3param="" and dnssec="false", you get an error:
`{"error": "NSEC3PARAMs provided for zone 'example.com.', but zone is not DNSSEC secured."}`

Real world implication of this behaviour is encountered while exporting data from one Auth via API, then attempting to import it into another Auth via API.

When I export a zone created with mostly defaults:
```
{
    "name":"example.com.",
    "kind": "Master",
    "masters": [],
    "nameservers": [],
    "rrsets": []
}
```

Then exporting it via API results in:
```
{
    "account": "",
    "api_rectify": false,
    "dnssec": false,
    "edited_serial": 2022080301,
    "id": "example.com.",
    "kind": "Master",
    "last_check": 0,
    "master_tsig_key_ids": [],
    "masters": [],
    "name": "example.com.",
    "notified_serial": 0,
    "nsec3narrow": false,
    "nsec3param": "",
    "rrsets": [
        {
            "comments": [],
            "name": "example.com.",
            "records": [
                {
                    "content": "a.misconfigured.dns.server.invalid. hostmaster.example.com. 2022080301 10800 3600 604800 3600",
                    "disabled": false
                }
            ],
            "ttl": 3600,
            "type": "SOA"
        }
    ],
    "serial": 2022080301,
    "slave_tsig_key_ids": [],
    "soa_edit": "",
    "soa_edit_api": "DEFAULT",
    "url": "/api/v1/servers/localhost/zones/example.com."
}
```
Note: The export has nsec3param="" and dnssec="false"

Which I then cannot import into another Auth via API:
```
HTTP/1.1 422 Unprocessable Entity

{"error": "NSEC3PARAMs provided for zone 'example.com.', but zone is not DNSSEC secured."}
```

### Environment

 - Software version: 4.6.2
 - Software source: PowerDNS Docker image

### Steps to reproduce

1. Send (POST) this JSON to {AUTH API ENDPOINT}/api/v1/servers/localhost/zones

```
{
    "name":"example.com.",
    "kind": "Master",
    "masters": [],
    "nameservers": [],
    "rrsets": [],
    "dnssec": false,
    "nsec3param": ""
}
```

### Expected behaviour

Zone created, no errors

### Actual behaviour

Error thrown:
`{"error": "NSEC3PARAMs provided for zone 'example.com.', but zone is not DNSSEC secured."}`

**Comment by Habbie** [comment]
We should treat empty nsec3param as absent nsec3param in this case.

**Comment by Habbie** [comment]
#11917 contains a very narrow workaround that should make the export/import path work. A cleaner fix, eventually, would be to leave out dnssec parameters in a non-dnssec export, and to make sure the parameters are cleaned in the database on a non-dnssec import/update.
