### ISSUE TITLE
selinux on el9 blocks pdns-backend-mysql from using the network

### ISSUE THREAD

**Issue by zerocarbthirty** [PowerDNS/pdns#11846]
- Program: Authoritative, 
 - Issue type: Bug report

### Short description
pdns authoritative version 4.6.2 using pdns-backend-mysql cannot connect to a remote mysql host running 8.0.28

### Environment

 - Operating system:  AlmaLinux 9
Name         : pdns
Version      : 4.6.2
Release      : 1.el9
Architecture : x86_64
Size         : 9.6 M
Source       : pdns-4.6.2-1.el9.src.rpm
Repository   : @System
From repo    : epel

### Steps to reproduce

configured PDNS as such:

launch=gmysql
load-modules=gmysql
local-address=172.16.0.15
gmysql-host=172.16.0.13
gmysql-port=3306
gmysql-dbname=pdns_new
gmysql-user=pdns_new_testing
gmysql-password=redacted

and then started PDNS.

### Expected behaviour
I would expect that pdns would be able to connect to the host at 172.16.0.13 via 3306.

### Actual behaviour
Aug 10 14:29:26 ns3 pdns_server[8250]: gmysql Connection failed: Unable to connect to database: ERROR 2002 (HY000): Can't connect to server on '172.16.0.13' (13)
Aug 10 14:29:26 ns3 pdns_server[8250]: Caught an exception instantiating a backend: Unable to launch gmysql connection: Unable to connect to database: ERROR 2002 (HY000): Can't connect to server on '172.16.0.13' (13)
Aug 10 14:29:26 ns3 pdns_server[8250]: Cleaning up
Aug 10 14:29:26 ns3 pdns_server[8250]: Fatal error: Unable to launch gmysql connection: Unable to connect to database: ERROR 2002 (HY000): Can't connect to server on '172.16.0.13' (13)

### Other information

Basic connectivity and authentication testing...

[root@ns3 log]# telnet 172.16.0.13 3306
Trying 172.16.0.13...
Connected to 172.16.0.13.
Escape character is '^]'.
J
8.0.287iw@A.
J

mysql -h172.16.0.13 -updns_new_testing -predacted pdns_new
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 57
Server version: 8.0.28 Source distribution

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables
    -> ;
+---------------------+
| Tables_in_pdns_new |
+---------------------+
| comments            |
| cryptokeys          |
| domainmetadata      |
| domains             |
| records             |
| supermasters        |
| tsigkeys            |
+---------------------+
7 rows in set (0.00 sec)

Does the built in mysql for the backend not support caching_sha2_password?

Is there any way to get a verbose/debug output from the backend?

**Comment by zerocarbthirty** [comment]
Looks like this may be default selinux blocking whatever library you guys are using from connecting as running:

setenforce 0

on the pdns 4.6.2 server allows it to connect. 

I will see if I can figure out what specifically I need to set in selinux to get this to work so maybe you can document it.

**Comment by setharnold** [comment]
Check `dmesg` or auditd logs for `avc` entries; I believe selinux emits those when denying access.

**Comment by zerocarbthirty** [comment]
Here is what I needed to do to get this to work in alma9
setsebool -P pdns_can_network_connect_db 1
ausearch -c 'pdns_server' --raw | audit2allow -M my-pdnsserver
semodule -X 300 -i my-pdnsserver.pp

Not sure if this is something that the RPM can do itself or not. It's a fairly safe bet that if someone is installing pdns-backend-mysql that they want it to be able to connect to the network.

**Comment by Habbie** [comment]
I believe selinux policies are packaged upstream in Alma and/or EPEL, and I believe the fix should also go there.

**Comment by Habbie** [comment]
There's no work for us to do here. If anybody files something upstream, do please comment here so people can maybe find it.
