### ISSUE TITLE
DNSTAP: dnstapFrameStreamServer only logs resolver query/response, not client query/response

### ISSUE THREAD

**Issue by mrbaixg** [PowerDNS/pdns#11868]
- Program: Recursor 
 - Issue type: Bug report

### Short description

I configured dnstapFrameStreamServer function in the lua script to enable DNSTAP function, which is working so far. I can receive DNSTAP logs of packets during the recursive process, but no query/response with the client is logged with this function. 

Is this intended? Is there a way to log client queries/responses as well?

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.7.0
 - Software source: compiled myself to enable dnstap feature 

### Steps to reproduce

1. compile the software to enable dnstap feature
2. configure the dnstapFrameStreamServer function
3. receive logs at the dnstap receiver side.

### Expected behaviour
Receive logs of all kinds, including resolver query/response and client query/response

### Actual behaviour
Only resolver queries/responses are logged.

**Comment by omoerbeek** [comment]
This works as documented in https://docs.powerdns.com/recursor/lua-config/protobuf.html#logging-in-dnstap-format-using-framestreams. We might add client side logging one day, see #6373.
