### ISSUE TITLE
Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgpsqlbackend.so

### ISSUE THREAD

**Issue by mrzepa** [PowerDNS/pdns#11861]
- Program: pdns_server and pdns-backend-pgsql
 - Issue type: Bug report

### Short description
PowerDNS will not start with the postgresql backend enabled. Looks like the file libgpsqlbackend.so does not exist.

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.2.1-1build2 500
 - Software source: http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages

### Steps to reproduce
1. Install the packages pdns-server and pdns-backend-pgsql
2. follow instructions for adding postgresql to the pdns.conf:3. 

- launch=gpsql
- gpgsql-user=powerdns
- gpgsql-password=*****
- gpgsql-dbname=powerdns

3. imported the schema to postgresql

### Expected behaviour
Service should start.

### Actual behaviour
Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgpsqlbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgpsqlbackend.so: cannot open shared object file: No such file or directory

### Other information
When I check the directory, that file does not exist.
root@linux01://usr/lib/x86_64-linux-gnu/pdns# ls -l
total 420
-rw-r--r-- 1 root root 260296 Feb  3  2020 libbindbackend.so
-rw-r--r-- 1 root root 116904 Feb  3  2020 libgpgsqlbackend.so
-rw-r--r-- 1 root root  47424 Feb  3  2020 librandombackend.so

However a very similarly named file does exist "libgpgsqlbackend.so". I tried to symlink libgpsqlbackend.so to libgpgsqlbackend.so but that did not work either.

**Comment by Habbie** [comment]
> launch=gpsql

Try `launch=gpgsql` - note the extra `g`

**Comment by mrzepa** [comment]
Thank you. Looks like there is some bad documentation out there (or older documentation).
All is good now.

**Comment by Habbie** [comment]
Thank you for reporting back. Do you know where that bad documentation is? (It's not older - the name of this backend has never changed.)
