### ISSUE TITLE
Release for Rasbian Bullseye

### ISSUE THREAD

**Issue by LeePorte** [PowerDNS/pdns#11888]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description

Currently there is no builds in the apt repos for Rasbian Bullseye, this has been the current Rasbian release for a while now. Please could you look at adding Bullseye to the release 

### Usecase

I'd like to be able to install from the apt repositories onto a pi running Rasbian Bullseye

**Comment by Habbie** [comment]
We have no plans to support 32 bit Raspberry Pi OS bullseye, as time_t is also 32 bit on that distribution - see https://blog.powerdns.com/2021/03/26/upcoming-package-removals/

For 64 bit Raspberry Pi OS, our (I know it's taking long) ARM64 build plans (#8655) should cover that. So I'm closing this ticket.
