### ISSUE TITLE
Ubuntu jammy repo

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#11880]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Bug report

### Short description
if you visit `repo.powerdns.com` you will se a reference to store the asc key in the outdated apt-key style.

### Environment
 - Operating system: Ubuntu
 - Software version: Jammy
 - Software source: repo.powerdns.com

### Steps to reproduce
1. See above
2. 
### Expected behaviour
a guide to store keys as GPG in the default keyrings

### Actual behaviour
See above

### Other information
I would like to create a MR with the following suggestion to the docs, if someone could give me directions for the right location

```bash
# Outcomment the the keyfile you would like to use.
# First key is to Stable releases, Second key is for master releases.

# KEY="FD380FBB" # Stable
# KEY="CBC8B383" # Maser
PGP_URI="https://repo.powerdns.com/"
REPO_URI="http://repo.powerdns.com/ubuntu"
KEY_LOC="/usr/share/keyrings"

curl "$PGP_URI/$KEY-pub.asc" | gpg --dearmor | sudo tee "$KEY_LOC/$KEY.gpg" >/dev/null
curl "$PGP_URI/$KEY-pub.asc" | gpg --dearmor | sudo tee "$KEY_LOC/$KEY.gpg" >/dev/null
echo -e "deb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI `lsb_release -cs`-auth-master main\ndeb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI `lsb_release -cs`-rec-master main\ndeb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI `lsb_release -cs`-dnsdist-master main" | sudo tee /etc/apt/sources.list.d/pdns.list
echo -e "Package: dnsdist*\nPin: origin repo.powerdns.com\nPin-Priority: 600\n" | sudo tee /etc/apt/preferences.d/pdns
echo -e "Package: pdns-*\nPin: origin repo.powerdns.com\nPin-Priority: 600\n" | sudo tee /etc/apt/preferences.d/dnsdist
```

**Comment by kpfleming** [comment]
Already in the works in #10596.

**Comment by Habbie** [comment]
I'd ask you to comment your suggestion in #10596, but it is my understanding that writing in `/usr` as an admin is always bad. Anyway, I'm closing this as we're already discussing this in the other ticket.
