### ISSUE TITLE
Exiting because communicator thread died with error: virtual void GSQLBackend::getUpdatedMasters

### ISSUE THREAD

**Issue by csergey88** [PowerDNS/pdns#11892]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

After upgrade pdns service restart infinitely with error 
` 
"Exiting because communicator thread died with error: virtual void GSQLBackend::getUpdatedMasters(std::vector<DomainInfo>&, std::unordered_set<DNSName>&, CatalogHashMap&) unable to retrieve list of master domains: Could not prepare statement: select d.id, d.name, d.type, d.notified_serial,d.options, d.catalog,r.content from records r join domains d on r.domain_id=d.id and r.name=d.name where r.type='SOA' and r.disabled=0 and d.type in ('MASTER', 'PRODUCER'): Unknown column 'd.options' in 'field list'"
`
### Environment

 - Operating system: Ubuntu 18.04
 - Software version: PowerDNS Authoritative Server 4.8.0-alpha0.104.master.ga9c0faa25
 - Software source: PowerDNS repository

**Comment by mind04** [comment]
pleas update your schema https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/4.3.0_to_4.7.0_schema.mysql.sql

**Comment by csergey88** [comment]
Thank you
