### ISSUE TITLE
Adding an option to change the custom RRSIG signature validity in DNSSEC

### ISSUE THREAD

**Issue by Ashiq5** [PowerDNS/pdns#11893]
- Program: Authoritative 
 - Issue type: Feature request

### Description
I am using PowerDNS as an authoritative server for my domain and while trying to enable DNSSEC, the signing worked fine but I did not seem to find any option for changing the custom signature validity for the created RRSIGs. Right now, it is set to 3 weeks and after looking at the code, it seems like this is fixed at PowerDNS. Please correct me if I am wrong. Is there any way to change the validity period of the signature as BIND provides? Maybe by providing an argument to the _secure-zone_ command. Thanks.

### Usecase
The requested features should give the user an option to use a custom signature validity period.

**Comment by Habbie** [comment]
Currently, no such feature exists. We also have no plans for it. If you have good reasons to want this, please describe them in a comment.
