### ISSUE TITLE
dnsdist Ubuntu 22.04 stable release

### ISSUE THREAD

**Issue by LeePorte** [PowerDNS/pdns#11900]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
A stable release for Ubuntu 22.04 Jammy Jellyfish

### Usecase
I'd like to upgrade some of my servers to Ubuntu 22.04 since the .1 release has now dropped.

### Description
I'd like to have a stable release of dnsdist to match with auth and recursor in advance of upgrading my servers in order to reduce the chance of breakages occuring. Is there a timeline for cutting a stable release of dnsdist for 22.04?

**Comment by Habbie** [comment]
dnsdist packages for 22.04 will appear with the next dnsdist release, which I believe might be soon

**Comment by omoerbeek** [comment]
Fixed in #11742
