### ISSUE TITLE
compiling fails in auth-4.8.0-alpha0 and auth-4.7.0-beta1 while auth-4.6.3 works

### ISSUE THREAD

**Issue by InputOutputZ** [PowerDNS/pdns#11902]
Hi there,

I'm reporting an issue with compiling PowerDNS authoritative server, in both releases auth-4.8.0-alpha0 and auth-4.7.0-beta1 while compiling using the same configuration completes successfully in auth-4.6.3.

Program: Authoritative
Issue type: Bug report

Operating system:  centOS, OpenSSL 3.0.5
Software version: 7
Software source: compiled yourself

### Steps to reproduce
1. autoreconf -vi
2. ./configure --with-libssl --with-boost --enable-systemd --enable-dns-over-tls --with-modules='bind gmysql gsqlite3' --with-libdecaf --with-mysql-lib
3. make

## Expected behaviour
Completes compilation

### Actual behaviour
Returns the following:-

```
In file included from ../../pdns/dnsbackend.hh:45,
                 from ../../pdns/ueberbackend.hh:33,
                 from ../../pdns/dnsseckeeper.hh:34,
                 from bindbackend2.cc:40:
../../pdns/sha.hh:119:41: error: 'EVP_MD_CTX_free' was not declared in this scope
   std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)> mdctx;
                                         ^~~~~~~~~~~~~~~
../../pdns/sha.hh:119:41: note: suggested alternative: 'EVP_MD_CTX_create'
   std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)> mdctx;
                                         ^~~~~~~~~~~~~~~
                                         EVP_MD_CTX_create
../../pdns/sha.hh:119:57: error: template argument 2 is invalid
   std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)> mdctx;
                                                         ^
../../pdns/sha.hh: In constructor 'pdns::SHADigest::SHADigest(unsigned int)':
../../pdns/sha.hh:65:49: error: 'EVP_MD_CTX_free' was not declared in this scope
     mdctx(std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>(EVP_MD_CTX_new(), EVP_MD_CTX_free))
                                                 ^~~~~~~~~~~~~~~
../../pdns/sha.hh:65:49: note: suggested alternative: 'EVP_MD_CTX_create'
     mdctx(std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>(EVP_MD_CTX_new(), EVP_MD_CTX_free))
                                                 ^~~~~~~~~~~~~~~
                                                 EVP_MD_CTX_create
../../pdns/sha.hh:65:65: error: template argument 2 is invalid
     mdctx(std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>(EVP_MD_CTX_new(), EVP_MD_CTX_free))
                                                                 ^
../../pdns/sha.hh:65:67: error: 'EVP_MD_CTX_new' was not declared in this scope
     mdctx(std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>(EVP_MD_CTX_new(), EVP_MD_CTX_free))
                                                                   ^~~~~~~~~~~~~~
../../pdns/sha.hh:65:67: note: suggested alternative: 'EVP_MD_CTX_init'
     mdctx(std::unique_ptr<EVP_MD_CTX, decltype(&EVP_MD_CTX_free)>(EVP_MD_CTX_new(), EVP_MD_CTX_free))
                                                                   ^~~~~~~~~~~~~~
                                                                   EVP_MD_CTX_init
../../pdns/sha.hh:70:15: error: invalid operands of types 'int' and 'std::nullptr_t' to binary 'operator=='
     if (mdctx == nullptr) {
         ~~~~~~^~~~~~~~~~
../../pdns/sha.hh:86:33: error: request for member 'get' in '((pdns::SHADigest*)this)->pdns::SHADigest::mdctx', which is of non-class type 'int'
     if (EVP_DigestInit_ex(mdctx.get(), md, NULL) == 0) {
                                 ^~~
../../pdns/sha.hh: In member function 'void pdns::SHADigest::process(const string&)':
../../pdns/sha.hh:98:32: error: request for member 'get' in '((pdns::SHADigest*)this)->pdns::SHADigest::mdctx', which is of non-class type 'int'
     if (EVP_DigestUpdate(mdctx.get(), msg.data(), msg.size()) == 0) {
                                ^~~
../../pdns/sha.hh: In member function 'std::string pdns::SHADigest::digest()':
../../pdns/sha.hh:108:34: error: request for member 'get' in '((pdns::SHADigest*)this)->pdns::SHADigest::mdctx', which is of non-class type 'int'
     if (EVP_DigestFinal_ex(mdctx.get(), reinterpret_cast<unsigned char*>(md_value.data()), &md_len) == 0) {
                                  ^~~
make[4]: *** [Makefile:616: bindbackend2.lo] Error 1
make[4]: Leaving directory '/root/pdns/modules/bindbackend'
make[3]: *** [Makefile:517: all] Error 2
make[3]: Leaving directory '/root/pdns/modules/bindbackend'
make[2]: *** [Makefile:518: all-recursive] Error 1
make[2]: Leaving directory '/root/pdns/modules'
make[1]: *** [Makefile:584: all-recursive] Error 1
make[1]: Leaving directory '/root/pdns'
make: *** [Makefile:515: all] Error 2
```

**Comment by mind04** [comment]
Openssl 3.0.5 and CentOS is an interesting combination.
What is the source of your openssl version?

**Comment by InputOutputZ** [comment]
> Openssl 3.0.5 and CentOS is an interesting combination.
> What is the source of your openssl version?

git?

**Comment by Habbie** [comment]
> git?

You're not sure?

**Comment by InputOutputZ** [comment]
> > git?
> 
> You're not sure?

No, I'm sure, I compiled it from github repository few days ago, and all binaries worked just fine with it?

**Comment by Habbie** [comment]
What flags did you compile openssl with?

**Comment by InputOutputZ** [comment]
> What flags did you compile openssl with?

These flags:-
` ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib `

am I missing enable-scrypt?

**Comment by InputOutputZ** [comment]
> Can you provide a full reproduction? So all installed software starting from a clean EL7 install?

I installed different packages using yum and other manually from repositories and I can't think off the top of my head all of them yet here is what I think matters

Boost
`git clone https://github.com/boostorg/boost.git --recursive
cd boost
git checkout boost-1.81.0
./bootstrap.sh --prefix=/usr/local/include/boost
./b2 install`

Libdecaf
```
wget https://pilotfiber.dl.sourceforge.net/project/ed448goldilocks/libdecaf-1.0.0.tgz
tar -xzf libdecaf-1.0.0.tgz
cd libdecaf-1.0.0
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/
make
make test
make install
ln -s /usr/local/lib64/libdecaf.so.0 /usr/lib64/libdecaf.so.0
ln -s /usr/local/lib64/libdecaf.so /usr/lib64/libdecaf.so
ldconfig
```

Openssl
```
git clone https://github.com/openssl/openssl.git
cd openssl && git checkout openssl-3.0.5
./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib
make -j4
make test -j4
make install -j4
```

I tried Openssl with scrypt and it seems that it wont make any difference.
`./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl enable-scrypt shared zlib`

powerDNS Auth
```
cd ~/pdns
git checkout auth-4.8.0-alpha0
autoreconf -vi
./configure --with-libssl --with-boost=/usr/local/include/boost --enable-systemd --enable-dns-over-tls --with-modules='bind gmysql gsqlite3' --with-libdecaf --with-mysql-lib=/lib64
make
make install
```

**Comment by Habbie** [comment]
Thank you, but these are partial instructions - I don't see any yum install commands, for example. Can you provide -full- instructions so we can easily reproduce the issue?

Are you sure PowerDNS is even finding the right OpenSSL install?

**Comment by InputOutputZ** [comment]
> Thank you, but these are partial instructions - I don't see any yum install commands, for example. Can you provide -full- instructions so we can easily reproduce the issue?
> 
> Are you sure PowerDNS is even finding the right OpenSSL install?

No problem.

Sorry, in terms of yum I installed the following

```
yum install lua lua-devel boost boost-devel ragel ragel-devel libedit libedit-devel flex-devel texinfo libsodium-devel libfstrm LMDB net-snmp re2 TinyCDB
yum install fstrm deltarpm
yum install --nogpgcheck libuv libuv-devel libh2o-evloop libh2o
yum install libcap-devel bcc-tools mruby mruby-devel
```

I'm confident PowerDNS, its finding the OpenSSL, otherwise would've thrown more errors, given the other ssl package its 1.0.2k.

**Comment by Habbie** [comment]
This is CentOS 7? What compiler did you use?

**Comment by Habbie** [comment]
Ok.. so can we please have -full- instructions to re-recreate your build environment?

**Comment by InputOutputZ** [comment]
> Ok.. so can we please have -full- instructions to re-recreate your build environment?

I have good news. I made sure to follow your OpenSSL linking advice and managed to compile PowerDNS Auth, successfully. I think the issue was introduced in this commit https://github.com/PowerDNS/pdns/commit/74848abffcf2e5aa56f9bf1928559a387f72bb63. I had two versions of OpenSSL installed and in such instance, make references the old one headers and fetch it in bindbackend2.cc.

Please close this issue if you deem it as resolved, otherwise let me know if there is any further information should I provide.

Zakaria.

**Comment by Habbie** [comment]
Ah! Thank you for reporting back. Indeed, I'll close this. If you can comment your final solution (I assume it was an extra argument to `./configure`), that might be helpful for anybody else that wants to mix things like this.

**Comment by InputOutputZ** [comment]
No problem, thanks for your help and sure, here is what I did, before starting compiling, I created symbolic link for the target Openssl using

```
mv /usr/include/openssl/  /usr/include/opensslold && ln -s /usr/local/openssl/include/openssl /usr/include/
```

and after successful compilation and installation, I reverted such changes using the following

```
rm /usr/include/openssl && mv /usr/include/opensslold /usr/include/openssl
```

Also, not sure if true, I suspected make clean, doesn't properly clean the repo and I had to redownload the source, for each installation as well as reinstalled Openssl with enable-scrypt. Maybe this did help in avoiding some other issues, just in case some might experience undeservedly, here its the tip.

Once more, thanks Peter for giving me such chance to clear things up 👍 .

**Comment by Habbie** [comment]
Thanks!
