### ISSUE TITLE
IXFR response should be sent in one message

### ISSUE THREAD

**Issue by Korkman** [PowerDNS/pdns#1191]
The current implementation of IXFR in PowerDNS always falls back to AXFR and sends the response in multiple messages. This leads to client-side parsing problems not present with other DNS. An easy to test example for this is the ISC BIND tool "dig".

Reproduction:

Allow AXFR for localhost in configuration:
```
allow-axfr-ips=127.0.0.1
```

Query PowerDNS with a serial lower than current SOA:
```
dig -t IXFR=2014010100 @localhost your-zone.com
```

Current behavior:

dig will print the complete response, but hang and timeout.

Expected behavior:

dig should close the connection.

Fix proposal:

Send all information in one message.

**Comment by Habbie** [comment]
Given that this has been fixed in all dig versions for almost two years now, I am closing this. Thank you!
