### ISSUE TITLE
Debian packages should not use release codenames in package versions

### ISSUE THREAD

**Issue by dwfreed** [PowerDNS/pdns#11925]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Bug report

### Short description
Debian packages currently use Debian release codenames in package versions.  When upgrading between Debian releases without a corresponding upgrade in pdns/dnsdist version, the package versions are the same except for the release codename, which is not necessarily in alphabetical order, and so may require a downgrade.  Downgrades are officially unsupported by Debian; they may work, they may not, you get to keep the pieces when it breaks kind of thing.  Using the release version number instead of codename would avoid this issue.

### Environment
 - Operating system: Debian 10 (Buster), 11 (Bullseye)
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install Debian 10 (Buster)
2. Install a pdns or dnsdist version from the PowerDNS repository that is available in both Debian 10 and 11
3. Upgrade to Debian 11 (Bullseye), including adjusting sources.list for the PowerDNS repo to use the bullseye versions

### Expected behaviour
Apt should automatically upgrade pdns/dnsdist from the buster version to the bullseye version without any intervention.

### Actual behaviour
Apt does not upgrade pdns/dnsdist by itself, keeping the buster version as "newer"; using aptitude and manually adjusting the upgrade to include "downgrading" pdns/dnsdist from the buster version to the bullseye version works.

### Other information
This is the code that sets the codename:

https://github.com/PowerDNS/pdns-builder/blob/4fb9eccff293c532f762947696c426fc9c1dd33a/helpers/build-debs.sh#L47-L60

Instead of using `${VERSION_CODENAME}` here, you could use something like `${ID}.${VERSION_ID}` which will work for all versions of both Debian and Ubuntu, except for Debian Testing.  For Debian Testing, you can use the existing `PRETTY_NAME` regex to extract the codename, and then install `distro-info-data` and grep `/usr/share/distro-info/debian.csv` for the codename, and the first column will be the version number.

This issue also applies to Ubuntu, but their codenames are alphabetical, and only rollover once every 13 years; however, upgrading from xenial (16.04) to bionic (18.04) was also broken in the same way at the time.

**Comment by ianbmacdonald** [comment]
Glad to see this one already underway.   We were surprised that the bullseye package used a version that contained the Debian 10 codename after the repo update and then realized we were not in sync with the repo with everything uptodate. 

A quick check of the apt policy stopped the search for an apt hold or broken preference rule, as the issue is in the versioning schema. 

```
apt policy pdns-recursor
pdns-recursor:
  Installed: 4.8.2-1pdns.buster
  Candidate: 4.8.2-1pdns.buster
  Version table:
 *** 4.8.2-1pdns.buster 100
        100 /var/lib/dpkg/status
     4.8.2-1pdns.bullseye 600
        500 http://repo.powerdns.com/debian bullseye-rec-48/main amd64 Packages
     4.4.2-3 500
        500 http://ftp.us.debian.org/debian bullseye/main amd64 Packages
```
Workaround was a straightforwad apt override specifying the version, and there were a few buster dependencies holding on to old libraries, so the packages are different, even though we had no functional issues. 

```
apt install pdns-recursor=4.8.2-1pdns.bullseye
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libboost-context1.67.0 libboost-filesystem1.67.0 libboost-system1.67.0 libmariadb3 libperl5.28 libsnmp30 mariadb-common mysql-common perl-modules-5.28
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libboost-context1.74.0 libboost-filesystem1.74.0
The following NEW packages will be installed:
  libboost-context1.74.0 libboost-filesystem1.74.0
The following packages will be DOWNGRADED:
  pdns-recursor
0 upgraded, 2 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 3293 kB of archives.
After this operation, 4128 kB of additional disk space will be used.
Do you want to continue? [Y/n]

```
 As noted in similar report for docker, this is probably pretty straightforwards to move to something similar to
~debian.11.0~bullseye
~ubuntu.22.04.0~jammy

https://github.com/docker/docker-ce-packaging/pull/701
