### ISSUE TITLE
[DNSdist] - Feature request - UDPonly 53 on forward

### ISSUE THREAD

**Issue by watchix** [PowerDNS/pdns#11967]
Hi,

 - Issue type: Feature request

### Short description
Forward all udp/tcp 53, DoT, DoH queries to an UDP 53 only to the backserver.

### Usecase
In case the backserver don't support tcp,DoT or DoH, but only old 53 udp. :sob: 

### Description
An option like `UDPonly=BOOL`

**Comment by watchix** [comment]
Hi @rgacogne ,

Thanks for your reply, i'm agree with your response about the backend server to support rfc7766 ...
But our DNS provider don't reply about our many queries to support DoT/DoH... and we can't change for a another DNS provider.

I'm sorry to be a "noob" about DNS protocol, but how a query initiate from UDP to UDP 53 can be too large to be sent over UDP ? this protocol support fragmentation.

Regards,

**Comment by klaus-nicat** [comment]
> I'm sorry to be a "noob" about DNS protocol, but how a query initiate from UDP to UDP 53 can be too large to be sent over UDP ? this protocol support fragmentation.

Yes, UDP supports fragmentation. But fragmented UDP DNS responses are vulnerable to attacks. That's why the https://dnsflagday.net/2020/ was happening. Since then, most (big) auth DNS providers do not support UDP fragmentation for DNS anymore, but force clients to UDP.

**Comment by kpfleming** [comment]
s/UDP/TCP/ in the last sentence fragment.

**Comment by klaus-nicat** [comment]
> s/UDP/TCP/ in the last sentence fragment.
Thanks, fixed.

**Comment by omoerbeek** [comment]
Thanks for adding the reason why buffer sizes are restricted to avoid UDP fragmentation.

Trying to make it extra clear: dnsdist has no issues to accept a DoT/DoH queries and forward them over TCP to port 53 as plain text. A backend can choose to support DoT or DoH, but *must* support both plain text UDP and TCP to port 53.

**Comment by watchix** [comment]
Ok... so is there a way or a new feature to forward 53 tcp, DoT and DoH to an another backend server ?

53 (udp) => Backendserver-01
53 (tcp) => Backendserver-02
853 / 443 => Backendserver-03

Regards,

**Comment by omoerbeek** [comment]
There is https://dnsdist.org/rules-actions.html#TCPRule . But I'm wondering why you would want this setup.

On a more general level:

Our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
