### ISSUE TITLE
[DNSdist] - DoT queries not correct with forwarder who don't support DoT

### ISSUE THREAD

**Issue by watchix** [PowerDNS/pdns#11964]
Hello,

I'm running DNSdist who forward to a provider (adult filtering) who don't support DoT and DoH (udp 53 only...)

So i did this configuration :
`newServer({address="52.209.xx.xx:53", name="Adult-Filter-Provider",  weight=100, checkType="A", checkName="www.google.com.", checkTimeout=200, checkInterval=20, pool=""})`

But when i'm trying my DNSdist :
- udp 53 => adult-content.com => filtered ip : OK
- tcp 53/853 => adult-content.com => correct ip : NOK
- tcp 443 => adult-content.com => correct ip : NOK

If DNSdist forward to a provider who support DoT and DoH all is ok :
`newServer({address="1.1.1.3:53", name="Adult-Filter-CloudFlare",  weight=100, checkType="A", checkName="www.google.com.", checkTimeout=200, checkInterval=20, pool=""})`

Is it a bug from my version ? 
`dnsdist 1.5.1 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])`
![DNSdist-bug](https://user-images.githubusercontent.com/2278299/190506228-0f51eb2a-8145-4c37-b3dc-74395829a298.jpg)

**Comment by rgacogne** [comment]
Incoming queries received over Do53 TCP or DoT are forwarded over Do53 TCP (or DoT/DoH depending on how the backend has been configured), not Do53 UDP. If your provider does not support Do53 TCP they should fix that, as required by rfc7766.

**Comment by watchix** [comment]
Hi @rgacogne,

Thanks for your reply.

I found in the doc an option : `TCPonly=BOOL -- Always forward queries to that backend over TCP, never over UDP`
Is there an option like `UDPonly=BOOL` to force forward on 53 UDP only ?

Regards,

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

Also, you are commenting on a closed ticket - such comments tend to get ignored and/or forgotten.

(also, no, there is no such option as far as I know)
