### ISSUE TITLE
Preserve pdns-recursor cache on restart

### ISSUE THREAD

**Issue by netravnen** [PowerDNS/pdns#11985]
- Program: Recursor
 - Issue type: Feature request

### Short description

Preserve pdns-recursor cache on restart. E.g. `rec_control dump-cache` exists today. Introduce a way to dump the cache to a temp file before restart, and restore the dumped cache contents after restart.

### Usecase

Operating a PowerDNS recursor in a larger network that build up a large cache over time, that hits the default limit of 1.000.000 entries easily.

It would be beneficial to be able to preserve the recursor cache contents (as a snapshot) between daemon restarts.

Restarts are sometimes necessary to update the running configuration of the daemon. Which changes slightly over longer periods of time. And requires daemon restarts to be applied to the running recursor daemon.

### Description

Preserve ALL cached records between daemon restarts.

One suggestion is to use a local cache dump to preserve the cache,

1. Stop servecing clients.
2. Dump cached records temp file. Including remaining TTL stored in cache.
3. Stop and start recursor daemon.
4. Load cached records temp file into daemon memory.
5. Start serving clients again.

Another example could be to keep a copy of the cache in, for example, a redis cache. Which _could_ be shared between multiple pdns-recursors.
I.e. instead of (or in parallel to) keeping a local in-memory record cache, keep the record cache in an independant in-memory database of the pdns-recursor daemon.

**Comment by omoerbeek** [comment]
The primitives to achieve this have been implemented in the upcoming 5.2.0

**Comment by teotikalki** [comment]
@omoerbeek There is a big difference between 'this is implemented' and 'The primitives to achieve this have been implemented'. It's a bit like the difference between 'there is a driveable car' and 'there are some auto parts'.

I'm really happy that you implemented primitives that would ALLOW for this feature request in the same way that someone who wants to drive is happy that car parts exist...

Marking this as 'completed' is about as accurate as calling a house 'move-in ready' right after the framers finish the shell.
