### ISSUE TITLE
broken link for jdnssec-tools  in regression test README

### ISSUE THREAD

**Issue by darnuria** [PowerDNS/pdns#11997]
Broken link for: jdnssec-verifyzone (http://www.verisignlabs.com/dnssec-tools/)

 - Program: Regression test
 - Issue type: Bug report

https://github.com/PowerDNS/pdns/blob/master/regression-tests/README.md?plain=1#L10

The repository can be found here: https://github.com/dblacka/jdnssec-tools

## PR

If it's Ok I can make a PR to change the 404 to https://github.com/dblacka/jdnssec-tools

Found with @alarig.

**Comment by rgacogne** [comment]
> If it's Ok I can make a PR to change the 404 to https://github.com/dblacka/jdnssec-tools

I see that @Habbie has already contributed to this repository so that makes sense to me, yes!
