### ISSUE TITLE
pdns_recursor: Improve logging for "label too long to append" errors to include the domain name. 

### ISSUE THREAD

**Issue by dcid** [PowerDNS/pdns#12014]
- Program: Recursor (versions 4.6 and 4.7+)
 - Issue type: Feature request

First of all, thanks for PowerDNS and the great work you guys do. We are using it on our network very successfully handling billions of requests per day.

The problem we have (very minimal) is related to this error message that shows up whenever we reload it:

Sep 25 20:04:01 server pdns_recursor-2[30871]: label too long to append
Sep 25 20:04:01 server pdns_recursor-2[30871]: label too long to append
Sep 25 21:04:04 server syslogd: last message repeated 7 times

Since the logging doesn't tell what domain is causing it, we can't fix it. Ideally, it would be great if it showed the domain name that is causing the problem. Like:

Sep 25 20:04:01 server pdns_recursor-2[30871]: label too long to append on domain name: example.com

That allow us to troubleshoot and fix the problem. I looked at the code base and I think that by modifying dnsname.cc (line 69) from:

```throw std::range_error("label too long to append");```

to:

```throw std::range_error("label too long to append on domain name: " + string(p));```

Should solve it. White at it, it might be good to do the same thing for:

```throw std::range_error("name too long to append: " + string(p));```

Thanks!

**Comment by omoerbeek** [comment]
I have a (slight) worry this could potentially spam the log with very long labels. Will look into this.
