### ISSUE TITLE
Web render problem when using pdns recursor

### ISSUE THREAD

**Issue by GW-Admin** [PowerDNS/pdns#12062]
Hi ,

I'm looking a way to troubleshoot for a website that load incomplete when forwarding using recursor, I've been check all the configuration back and fort, but can't find some thing wrong with configuration.

When using PDNS Recursor for forwarding
![image](https://user-images.githubusercontent.com/115074358/194028792-66f86c5a-2d29-4063-9f1a-be01ea0debc6.png)

vs

When using some public DNS 
![image](https://user-images.githubusercontent.com/115074358/194029594-02ef0048-dae5-4381-80de-6b57b8501934.png)

Here is my recursor configuration

allow-from=172.17.92.0/24, 192.168.92.0/24, 192.168.201.0/24, 192.168.77.0/24, 192.168.32.254/30
disable-syslog=no
forward-zones=gws.local=192.168.92.8:53
forward-zones-recurse=.=203.142.82.222:53;203.142.84.222:53
local-address=192.168.92.21
local-port=53
threads=8
new-domain-log=yes
dnssec=off

**Comment by rgacogne** [comment]
Hi,

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
