### ISSUE TITLE
Set truncated bit from postresolve lua function

### ISSUE THREAD

**Issue by Fusl** [PowerDNS/pdns#1207]
Hi,

i really want to set the truncated but from a postresolve script within the return statement. I asked in the IRC if this is possible:

    <Fusl> can i somehow set the tc bit within a lua script on the recursor?
    <Habbie> Fusl, not currently, feature request welcome

Would be very great if this is going to be implemented in the near future.

**Comment by Habbie** [comment]
We cannot actively support features that are required specifically for the running of open resolvers. Closing this.
