### ISSUE TITLE
rec: trace-regex logs don't translate qtype

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#12089]
- Program: rec
 - Issue type: Bug report

### Short description
Ignore the name, the qtype was A. Sorry for the confusion. :D 

```Oct 13 11:09:17 what-the-AAAA.com: Trying IP 192.26.92.30:53, asking 'what-the-AAAA.com|1'```

### Environment
 - Operating system: Debian something
 - Software version: latest from git
 - Software source: compiled myself

### Steps to reproduce
1. rec_control trace-regex '.*' and view log

### Expected behaviour
Should be ```Oct 13 11:09:17 what-the-AAAA.com: Trying IP 192.26.92.30:53, asking 'what-the-AAAA.com|A'```

### Actual behaviour
```Oct 13 11:09:17 what-the-AAAA.com: Trying IP 192.26.92.30:53, asking 'what-the-AAAA.com|1'```

### Other information
When run with ``--trace`` it works fine.

```Oct 13 11:11:11 [1] what-the-AAAA.com: Trying IP 192.12.94.30:53, asking 'what-the-AAAA.com|A'```

**Comment by phonedph1** [comment]
The ones that do work still explicitly call ```DNSRecordContent::NumberToType(thing)``` so there are about 7-8 spots that don't.

**Comment by omoerbeek** [comment]
For log streams there is an operator that converts `QType` value to their string representation. We do not have that for string streams, which `trace-regex` uses. We can either do explicit `.toString()` or implement:
```
inline std::ostream& operator<<(std::ostream& stream, QType qtype)
{
  return stream << qtype.toString();
}
```
