### ISSUE TITLE
How to update boost

### ISSUE THREAD

**Issue by EduRuizDK** [PowerDNS/pdns#12116]
Newer versions 4.7.0 require a newer version of _boost_, but not all repositories are updated.
So the better way is downloading and compiling from www.boost.org (version 1.80.0 when I post this message)
But when compiling _boost_ with b2 there is a linker problem with C++ version 11 and ABI compatibility, so you must compile adding **-D_GLIBCXX_USE_CXX11_ABI=0**
Change line boost_1_80_0/tools/build/src/engine/build.sh:326
```
-B2_CXXFLAGS_RELEASE="-O2 -s"
+B2_CXXFLAGS_RELEASE="-O2 -s -D_GLIBCXX_USE_CXX11_ABI=0"
```

**Comment by Habbie** [comment]
We do not recommend building boost by hand if it can be avoided. Also, this bug tracker is not a place to randomly document how to build specific libraries.
