### ISSUE TITLE
Recursor 4.7.3 Failed to update root NS records, RCODE=2

### ISSUE THREAD

**Issue by hellweiss** [PowerDNS/pdns#12112]
PowerDNS Recursor 4.7.3
hint-file=no in recusror.conf

Error in /var/log/messages

Failed to update root NS records, RCODE=2

Recursor should not try to update root NS Records if hint-file=no

**Comment by omoerbeek** [comment]
It is not *that* simple. If the recursor need to resolve names (i.e. not everything is forwarded), it still needs root NS records, as it walks the tree from the root. To be able to diagnose this, we need your *full* recursor.conf.

**Comment by hellweiss** [comment]
recursor.conf:
forward-zones-file=/usr/local/etc/pdns/forward-zones.conf
hint-file=no

forwartd-zones.conf:
+.=9.9.9.9, 149.112.112.112

**Comment by omoerbeek** [comment]
Using this configuration, I cannot reproduce. I see successful retrieval of root NS records and additional records from quad9.
Can you run with `--trace` and upload the *full* log?

**Comment by hellweiss** [comment]
This is solved.
After doing the Trace as you requested it looks like Quad9 is limiting DNS Requests. If the limit is reached no
additional Requests are allowed for some time.  Also outgoing timeout counters went up quick.

Switched to Google DNS Service (8.8.8.8, 8.8.4.4) all looking good for now.

Thanks for your Help.

**Comment by omoerbeek** [comment]
Any particular reason why you are sending everything to forwarders? PowerDNS recursor itself is perfectly capable of doing the resolving itself. That way you are not as depdendent on single other parties.

**Comment by hellweiss** [comment]
IT-Security Team wants us to not use the ROOT Servers. (shrug)
