### ISSUE TITLE
rec: startup race can happen that provokes a.root-servers.net to go Bogus on statup

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#12160]
This is a return of #6138
I can provoke it of I only only use the `a` and `j` `root-servers` as these return `aa` answers for `DS`queries:

```
$ dig root-servers.net DS @j.root-servers.net +dnssec

; <<>> DiG 9.10.6 <<>> root-servers.net DS @j.root-servers.net +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51491
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1472
;; QUESTION SECTION:
;root-servers.net.		IN	DS

;; AUTHORITY SECTION:
root-servers.net.	3600000	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022102600 14400 7200 1209600 3600000

;; Query time: 173 msec
;; SERVER: 192.58.128.30#53(192.58.128.30)
;; WHEN: Thu Nov 03 10:40:17 CET 2022
;; MSG SIZE  rcvd: 105
```
`a.root-servers.net` sometimes does. So the set of NS that show the `aa` response is different from  three years ago.

During thread startup, the threads that handle queries start already doing so while the priming of the root in the handler thread is still underway.

Also, the initial priming does not enforce the the `net. NS` records to be retrieved by calling `primeRootNSZones`, as the housekeeping does.

These things together can cause an early `a.root-servers.net|A` query to find no `.net|A` records in the cache, hitting the #6138 scenario.

To provoke: use `dnssec=validate` and `qname-minimization=no`, restart a few times with dnsdist healthcheck to the recursor  active.

**Comment by omoerbeek** [comment]
Some thoughts:
- Reordering startup of threads won't work, as the housekeeping `primeRootNSZones` call needs at least worker threads to be active.
- We *could* postpone starting the distributor threads, but then we still have the case `pdns-distributes-queries=no`
- Likely the easiest way is to drop queries  in `handleNewUDPQuestion` and `handleNewTCPQuestion` until housekeeping indicates with bool var that `primeRootNSZones` has run.
- Easiest workaround: do not set `qname-minimization=no`

**Comment by omoerbeek** [comment]
The drop incoming packets until ready works for the specific case, but it breaks a lot of regression tests that do not expect that. Some more thought needed.

**Comment by omoerbeek** [comment]
I am wondering if the code to detect if we missed a cut could be made to fix this case so that `SyncRes` draws the right conclusion (zone is Insecure) without depending on the `.net NS` record set being in cache or not (without getting my head spinning...)

**Comment by rgacogne** [comment]
> I am wondering if the code to detect if we missed a cut could be made to fix this case so that `SyncRes` draws the right conclusion (zone is Insecure) without depending on the `.net NS` record set being in cache or not (without getting my head spinning...)

In theory this would be the right way to fix this issue indeed, but I have not checked whether this is actually achievable without adding a fair amount of complexity (or special casing the root-servers.net case which seems like a bad idea).

**Comment by omoerbeek** [comment]
Special casing will not work I suppose, in theory there could be more auths that are both authoritative for a Secure zone and an Insecure subzone that trigger this case.

**Comment by omoerbeek** [comment]
[log.txt](https://github.com/PowerDNS/pdns/files/9937266/log.txt)

**Comment by rgacogne** [comment]
Right, so we have:
- `.` is secure
- `net.` is secure
- `root-servers.net.` is insecure

The offending servers are authoritative for `.` and `root-servers.net.` but not `net.`, so they reply to a query for `root-servers.net.` `DS` with an unsigned `AA=1` `NODATA`. We do check if we missed a cut but since we are looking at a `AA=1` answer for a `DS`, we expect the answer to come from the parent-side, ie `net.` which is indeed signed.
The problem here is that we do not realize that the answer is coming from the child-side, as we usually take great care of not sending `DS` queries to the `NS` for the zone itself, but to the parent `NS`.
I guess we would need to look at the `SOA` in the response to realize that this answer comes from the child zone, and thus that we need to either discard it (no-one cares about a `DS` answer from the child, IMHO) or check if we missed two cuts (so not skip one level)?

Quick note: that this issue happens when we have missed two cuts, and the `NS` to be authoritative for the zone two levels above but not for the one just above.

**Comment by mnordhoff** [comment]
Then you're relying on an insecure zone's `SOA` record to be correct, which is (in general) not always the case...

Maybe it's fine to say an operator can't do something broken and something this complex at the same time...

**Comment by omoerbeek** [comment]
Pondering the idea to modify `getDSRecords()` to always use QM.

**Comment by omoerbeek** [comment]
A quick test shows that could work. Will explore this idea further later this week.

**Comment by omoerbeek** [comment]
Some notes on:
- Using the firewall blocking all root servers except `a`, we hit the log case bacause the a root soemtimes answers with a delegation, and sometimes with the NODATA response.
- Restricting to the `j` root (which always answers with NODATA atm) causes a SERVFAIL on master when the race is lost:
```Nov 07 11:25:42 msg="Sending SERVFAIL during resolve" error="Server Failure while retrieving DS records for root-servers.net" subsystem="syncres" level="0" prio="Notice" tid="2" ts="1667816742.818" ecs="" mtid="1" proto="udp" qname="a.root-servers.net" qtype="A" remote="192.168.178.19:56590"```

[logOnlyJ.txt](https://github.com/PowerDNS/pdns/files/9950613/logOnlyJ.txt)

- With the PR applied it correctly resolves `a.root-servers.net` always.
