### ISSUE TITLE
PowerDNS recursor: reply sometimes with NX-Domain (negative records problem)

### ISSUE THREAD

**Issue by Tim-herbie** [PowerDNS/pdns#12189]
- Program: Recursor
 - Issue type: Bug report

### Short description

When the recursor is requestet, he reply with a NX-Domain instead of requesting the configured dns-server in the "forward-zones-recurse" file. After I wiped the cache for this domain, it works again for a five minutes.

### Environment
PowerDNS Version: 4.6.3
Backend: PostgreSQL (pdns authentication server)
DNSSEC: no
Operating System: Oracle Linux 8.4 -> EOL?
Software source: https://repo.powerdns.com/repo-files/centos-rec-46.repo"

### short description of the construct: 
We have two powerdns recursor´s and a authoritative servers. The recursor´s are only responsible to forward the dns requests to the authoritative server (if it is a self hosted and configured domain in the auth) or to the public servers.

### What have we do: 
Since August 29th 11:45am, we have a issue with our powerdns recursor´s in the datacenter. First, we didn´t changed or updated anything known in this whole construct

### Expected behaviour
If a client requests the powerdns-recursor for a a-record of mydomain.local, the recursor will ask the configured dns-server (active directory server) in the "forward-zones-recurse" file and reply to the client with the answer.

### Actual behaviour
Sometimes it works, but sometimes the powerdns recursor reply with a "NX-Domain" and I don´t understand why. I captured via wireshark all the traffic and can say, that the recursor don´t ask the active directory server), he replied directly with a NX-Domain. The wired thing is, that if a client reply e.q. abc.mydomain.local, it works perfekt. The issue happens only on the mydomain.local.

### Workaround
After we noticed the issue, we had much problems in our enviroment and a restart of the powerdns-recursor solves the issue for a short time. A bit later, I fount out, that I can solve this problem also for a short time, when I wipe the cache of the recursor with the following command: sudo rec_control wipe-cache mydomain.local. .

Here the answer:
wiped 2 records, 2 negative records, 3 packets

Because of this, I can say, that when the "negative record" will be removed from the cache, it works for maybe 5-30minutes and then I have the same problems again. At the moment, I created a cronjob, wich executes the wipe command every five minutes, but this is only a workaround. I don´t know, where I can see the "negative records" and why they are.

### Additional informations:
I found also out, that when the ttl for the domain mydomain.local expires, then I got the NX-Domain reply.

All domains and ips are invented, because this issue happens in a productive company.

If you need any informations, don´t hesitate to ask!

**Comment by phonedph1** [comment]
Providing your full config is the only way to tell what is happening, with proper names (doubt you are using mydomain.local). 

In the past various combinations of root-nx-trust and/or dnssec have led to things like this.

**Comment by omoerbeek** [comment]
> All domains and ips are invented, because this issue happens in a productive company.

Please read https://blog.powerdns.com/?s=out+in+the+open

**Comment by Tim-herbie** [comment]
`#################################
# allow-from    If set, only allow these comma separated netmasks to recurse
#
allow-from=192.168.0.0/16, 212.75.60.121/32

#################################
# allow-from-file       If set, load allowed netmasks from this file
#
# allow-from-file=

#################################
# allow-trust-anchor-query      Allow queries for trustanchor.server CH TXT and negativetrustanchor.server CH TXT
#
# allow-trust-anchor-query=no

#################################
# any-to-tcp    Answer ANY queries with tc=1, shunting to TCP
#
# any-to-tcp=no

#################################
# api-config-dir        Directory where REST API stores config and zones
#
# api-config-dir=

#################################
# api-key       Static pre-shared authentication key for access to the REST API
#
api-key=ABCDEFGHIJKLM

#################################
# auth-zones    Zones for which we have authoritative data, comma separated domain=file pairs
#
# auth-zones=

#################################
# carbon-instance       If set overwrites the the instance name default
#
# carbon-instance=recursor

#################################
# carbon-interval       Number of seconds between carbon (graphite) updates
#
# carbon-interval=30

#################################
# carbon-namespace      If set overwrites the first part of the carbon string
#
# carbon-namespace=pdns

#################################
# carbon-ourname        If set, overrides our reported hostname for carbon stats
#
# carbon-ourname=

#################################
# carbon-server If set, send metrics in carbon (graphite) format to this server IP address
#
# carbon-server=

#################################
# chroot        switch to chroot jail
#
# chroot=

#################################
# client-tcp-timeout    Timeout in seconds when talking to TCP clients
#
# client-tcp-timeout=2

#################################
# config-dir    Location of configuration directory (recursor.conf)
#
config-dir=/etc/pdns-recursor

#################################
# config-name   Name of this virtual configuration - will rename the binary image
#
# config-name=

#################################
# cpu-map       Thread to CPU mapping, space separated thread-id=cpu1,cpu2..cpuN pairs
#
# cpu-map=

#################################
# daemon        Operate as a daemon
#
# daemon=no

#################################
# delegation-only       Which domains we only accept delegations from
#
# delegation-only=

#################################
# disable-packetcache   Disable packetcache
#
# disable-packetcache=no

#################################
# disable-syslog        Disable logging to syslog, useful when running inside a supervisor that logs stdout
#
# disable-syslog=no

#################################
# distribution-load-factor      The load factor used when PowerDNS is distributing queries to worker threads
#
# distribution-load-factor=0.0

#################################
# distribution-pipe-buffer-size Size in bytes of the internal buffer of the pipe used by the distributor to pass incoming queries to a worker thread
#
# distribution-pipe-buffer-size=0

#################################
# distributor-threads   Launch this number of distributor threads, distributing queries to other threads
#
# distributor-threads=0

#################################
# dnssec        DNSSEC mode: off/process-no-validate (default)/process/log-fail/validate
#
dnssec=process-no-validate

#################################
# dnssec-log-bogus      Log DNSSEC bogus validations
#
# dnssec-log-bogus=no

#################################
# dont-query    If set, do not query these netmasks for DNS data
#
dont-query=127.0.0.0/8, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32

#################################
# dont-throttle-names   Do not throttle nameservers with this name or suffix
#
# dont-throttle-names=

#################################
# dont-throttle-netmasks        Do not throttle nameservers with this IP netmask
#
# dont-throttle-netmasks=

#################################
# ecs-add-for   List of client netmasks for which EDNS Client Subnet will be added
#
# ecs-add-for=0.0.0.0/0, ::/0, !127.0.0.0/8, !10.0.0.0/8, !100.64.0.0/10, !169.254.0.0/16, !192.168.0.0/16, !172.16.0.0/12, !::1/128, !fc00::/7, !fe80::/10

#################################
# ecs-cache-limit-ttl   Minimum TTL to cache ECS response
#
# ecs-cache-limit-ttl=0

#################################
# ecs-ipv4-bits Number of bits of IPv4 address to pass for EDNS Client Subnet
#
# ecs-ipv4-bits=24

#################################
# ecs-ipv4-cache-bits   Maximum number of bits of IPv4 mask to cache ECS response
#
# ecs-ipv4-cache-bits=24

#################################
# ecs-ipv6-bits Number of bits of IPv6 address to pass for EDNS Client Subnet
#
# ecs-ipv6-bits=56

#################################
# ecs-ipv6-cache-bits   Maximum number of bits of IPv6 mask to cache ECS response
#
# ecs-ipv6-cache-bits=56

#################################
# ecs-minimum-ttl-override      Set under adverse conditions, a minimum TTL for records in ECS-specific answers
#
# ecs-minimum-ttl-override=0

#################################
# ecs-scope-zero-address        Address to send to whitelisted authoritative servers for incoming queries with ECS prefix-length source of 0
#
# ecs-scope-zero-address=

#################################
# edns-outgoing-bufsize Outgoing EDNS buffer size
#
# edns-outgoing-bufsize=1232

#################################
# edns-subnet-whitelist List of netmasks and domains that we should enable EDNS subnet for
#
# edns-subnet-whitelist=

#################################
# entropy-source        If set, read entropy from this file
#
# entropy-source=/dev/urandom

#################################
# etc-hosts-file        Path to 'hosts' file
#
# etc-hosts-file=/etc/hosts

#################################
# export-etc-hosts      If we should serve up contents from /etc/hosts
#
# export-etc-hosts=off

#################################
# export-etc-hosts-search-suffix        Also serve up the contents of /etc/hosts with this suffix
#
# export-etc-hosts-search-suffix=

#################################
# forward-zones Zones for which we forward queries, comma separated domain=ip pairs
#
forward-zones-recurse=mydomain.local=192.168.1.1:53, mydomain2.local=192.168.1.1:53, mydomain3.local=192.168.5.20:53, .=8.8.8.8;8.8.4.4

#################################
# forward-zones-file    File with (+)domain=ip pairs for forwarding
#
# forward-zones-file=

#################################
# forward-zones-recurse Zones for which we forward queries with recursion bit, comma separated domain=ip pairs
#
# forward-zones-recurse=

#################################
# gettag-needs-edns-options     If EDNS Options should be extracted before calling the gettag() hook
#
# gettag-needs-edns-options=no

#################################
# hint-file     If set, load root hints from this file
#
# hint-file=
# hint-file=/usr/share/dns/root.hints

#################################
# include-dir   Include *.conf files from this directory
#
# include-dir=
# only works in 4.3 !
# include-dir=/etc/powerdns/recursor.d

#################################
# latency-statistic-size        Number of latency values to calculate the qa-latency average
#
# latency-statistic-size=10000

#################################
# local-address IP addresses to listen on, separated by spaces or commas. Also accepts ports.
#
local-address=192.168.1.100

#################################
# local-port    port to listen on
#
local-port=53

#################################
# log-common-errors     If we should log rather common errors
#
# log-common-errors=no

#################################
# log-rpz-changes       Log additions and removals to RPZ zones at Info level
#
# log-rpz-changes=no

#################################
# log-timestamp Print timestamps in log lines, useful to disable when running with a tool that timestamps stdout already
#
# log-timestamp=yes

#################################
# logging-facility      Facility to log messages as. 0 corresponds to local0
#
# logging-facility=0   (rsyslog_conf file needs to be configured)

#################################
# loglevel      Amount of logging. Higher is more. Do not set below 3
#
loglevel=5

#################################
# lowercase-outgoing    Force outgoing questions to lowercase
#
# lowercase-outgoing=no

#################################
# lua-config-file       More powerful configuration options
#
# only works in 4.3 !
# lua-config-file=/etc/powerdns/recursor.lua

#################################
# lua-dns-script        Filename containing an optional 'lua' script that will be used to modify dns answers
#
# lua-dns-script=

#################################
# lua-maintenance-interval      Number of seconds between calls to the lua user defined maintenance() function
#
# lua-maintenance-interval=1

#################################
# max-cache-bogus-ttl   maximum number of seconds to keep a Bogus (positive or negative) cached entry in memory
#
# max-cache-bogus-ttl=3600

#################################
# max-cache-entries     If set, maximum number of entries in the main cache
#
# max-cache-entries=1000000

#################################
# max-cache-ttl maximum number of seconds to keep a cached entry in memory
#
# max-cache-ttl=86400

#################################
# max-concurrent-requests-per-tcp-connection    Maximum number of requests handled concurrently per TCP connection
#
# max-concurrent-requests-per-tcp-connection=10

#################################
# max-generate-steps    Maximum number of $GENERATE steps when loading a zone from a file
#
# max-generate-steps=0

#################################
# max-mthreads  Maximum number of simultaneous Mtasker threads
#
# max-mthreads=2048

#################################
# max-negative-ttl      maximum number of seconds to keep a negative cached entry in memory
#
# max-negative-ttl=3600

#################################
# max-packetcache-entries       maximum number of entries to keep in the packetcache
#
# max-packetcache-entries=500000

#################################
# max-qperq     Maximum outgoing queries per query
#
# max-qperq=50

#################################
# max-recursion-depth   Maximum number of internal recursion calls per query, 0 for unlimited
#
# max-recursion-depth=40

#################################
# max-tcp-clients       Maximum number of simultaneous TCP clients
#
# max-tcp-clients=128

#################################
# max-tcp-per-client    If set, maximum number of TCP sessions per client (IP address)
#
# max-tcp-per-client=0

#################################
# max-tcp-queries-per-connection        If set, maximum number of TCP queries in a TCP connection
#
# max-tcp-queries-per-connection=0

#################################
# max-total-msec        Maximum total wall-clock time per query in milliseconds, 0 for unlimited
#
# max-total-msec=7000

#################################
# max-udp-queries-per-round     Maximum number of UDP queries processed per recvmsg() round, before returning back to normal processing
#
# max-udp-queries-per-round=10000

#################################
# minimum-ttl-override  Set under adverse conditions, a minimum TTL
#
# minimum-ttl-override=0

#################################
# network-timeout       Wait this number of milliseconds for network i/o
#
# network-timeout=1500

#################################
# new-domain-db-size    Size of the DB used to track new domains in terms of number of cells. Defaults to 67108864
#
# new-domain-db-size=67108864

#################################
# new-domain-history-dir        Persist new domain tracking data here to persist between restarts
#
# new-domain-history-dir=/var/lib/pdns-recursor/nod

#################################
# new-domain-log        Log newly observed domains.
#
# new-domain-log=yes

#################################
# new-domain-lookup     Perform a DNS lookup newly observed domains as a subdomain of the configured domain
#
# new-domain-lookup=

#################################
# new-domain-pb-tag     If protobuf is configured, the tag to use for messages containing newly observed domains. Defaults to 'pdns-nod'
#
# new-domain-pb-tag=pdns-nod

#################################
# new-domain-tracking   Track newly observed domains (i.e. never seen before).
#
# new-domain-tracking=no

#################################
# new-domain-whitelist  List of domains (and implicitly all subdomains) which will never be considered a new domain
#
# new-domain-whitelist=

#################################
# no-shuffle    Don't change
#
# no-shuffle=off

#################################
# non-local-bind        Enable binding to non-local addresses by using FREEBIND / BINDANY socket options
#
# non-local-bind=no

#################################
# nothing-below-nxdomain        When an NXDOMAIN exists in cache for a name with fewer labels than the qname, send NXDOMAIN without doing a lookup (see RFC 8020)
#
# nothing-below-nxdomain=dnssec

#################################
# nsec3-max-iterations  Maximum number of iterations allowed for an NSEC3 record
#
# nsec3-max-iterations=2500

#################################
# packetcache-servfail-ttl      maximum number of seconds to keep a cached servfail entry in packetcache
#
# packetcache-servfail-ttl=60

#################################
# packetcache-ttl       maximum number of seconds to keep a cached entry in packetcache
#
# packetcache-ttl=3600

#################################
# pdns-distributes-queries      If PowerDNS itself should distribute queries over threads
#
# pdns-distributes-queries=yes

#################################
# processes     Launch this number of processes (EXPERIMENTAL, DO NOT CHANGE)
#
# processes=1

#################################
# protobuf-use-kernel-timestamp Compute the latency of queries in protobuf messages by using the timestamp set by the kernel when the query was received (when available)
#
# protobuf-use-kernel-timestamp=

#################################
# public-suffix-list-file       Path to the Public Suffix List file, if any
#
# public-suffix-list-file=

#################################
# qname-minimization    Use Query Name Minimization
#
# qname-minimization=yes

#################################
# query-local-address   Source IP address for sending queries
#
# query-local-address=0.0.0.0

#################################
# query-local-address6  Source IPv6 address for sending queries. IF UNSET, IPv6 WILL NOT BE USED FOR OUTGOING QUERIES
#
# query-local-address6=

#################################
# quiet Suppress logging of questions and answers
#
quiet=True

#################################
# reuseport     Enable SO_REUSEPORT allowing multiple recursors processes to listen to 1 address
#
# reuseport=no

#################################
# rng   Specify random number generator to use. Valid values are auto,sodium,openssl,getrandom,arc4random,urandom.
#
# rng=auto

#################################
# root-nx-trust If set, believe that an NXDOMAIN from the root means the TLD does not exist
#
# root-nx-trust=yes

#################################
# security-poll-suffix  Domain name from which to query security update notifications
#
security-poll-suffix=secpoll.powerdns.com.

#################################
# serve-rfc1918 If we should be authoritative for RFC 1918 private IP space
#
# serve-rfc1918=yes

#################################
# server-down-max-fails Maximum number of consecutive timeouts (and unreachables) to mark a server as down ( 0 => disabled )
#
# server-down-max-fails=64

#################################
# server-down-throttle-time     Number of seconds to throttle all queries to a server after being marked as down
#
# server-down-throttle-time=60

#################################
# server-id     Returned when queried for 'id.server' TXT or NSID, defaults to hostname, set custom or 'disabled'
#
# server-id=

#################################
# setgid        If set, change group id to this gid for more security. When running inside systemd, use the User and Group settings in the unit-file!
#
setgid=pdns-recursor

#################################
# setuid        If set, change user id to this uid for more security. When running inside systemd, use the User and Group settings in the unit-file!
#
setuid=pdns-recursor

#################################
# signature-inception-skew      Allow the signature inception to be off by this number of seconds
#
# signature-inception-skew=60

#################################
# single-socket If set, only use a single socket for outgoing queries
#
# single-socket=off

#################################
# snmp-agent    If set, register as an SNMP agent
#
# snmp-agent=no

#################################
# snmp-master-socket    If set and snmp-agent is set, the socket to use to register to the SNMP master
#
# snmp-master-socket=

#################################
# soa-minimum-ttl       Don't change
#
# soa-minimum-ttl=0

#################################
# socket-dir    Where the controlsocket will live, /var/run/pdns-recursor when unset and not chrooted
#
# socket-dir=

#################################
# socket-group  Group of socket
#
# socket-group=

#################################
# socket-mode   Permissions for socket
#
# socket-mode=

#################################
# socket-owner  Owner of socket
#
# socket-owner=

#################################
# spoof-nearmiss-max    If non-zero, assume spoofing after this many near misses
#
# spoof-nearmiss-max=20

#################################
# stack-size    stack size per mthread
#
# stack-size=200000

#################################
# statistics-interval   Number of seconds between printing of recursor statistics, 0 to disable
#
statistics-interval=60

#################################
# stats-api-blacklist   List of statistics that are disabled when retrieving the complete list of statistics via the API
#
# stats-api-blacklist=

#################################
# stats-carbon-blacklist        List of statistics that are prevented from being exported via Carbon
#
# stats-carbon-blacklist=

#################################
# stats-rec-control-blacklist   List of statistics that are prevented from being exported via rec_control get-all
#
# stats-rec-control-blacklist=

#################################
# stats-ringbuffer-entries      maximum number of packets to store statistics for
#
# stats-ringbuffer-entries=10000

#################################
# stats-snmp-blacklist  List of statistics that are prevented from being exported via SNMP
#
# stats-snmp-blacklist=

#################################
# tcp-fast-open Enable TCP Fast Open support on the listening sockets, using the supplied numerical value as the queue size
#
# tcp-fast-open=0

#################################
# threads       Launch this number of threads
#
threads=4

#################################
# trace if we should output heaps of logging. set to 'fail' to only log failing domains
#
trace=fail

#################################
# udp-source-port-avoid List of comma separated UDP port number to avoid
#
# udp-source-port-avoid=11211

#################################
# udp-source-port-max   Maximum UDP port to bind on
#
# udp-source-port-max=65535

#################################
# udp-source-port-min   Minimum UDP port to bind on
#
# udp-source-port-min=1024

#################################
# udp-truncation-threshold      Maximum UDP response size before we truncate
#
# udp-truncation-threshold=1232

#################################
# unique-response-db-size       Size of the DB used to track unique responses in terms of number of cells. Defaults to 67108864
#
# unique-response-db-size=67108864

#################################
# unique-response-history-dir   Persist unique response tracking data here to persist between restarts
#
# unique-response-history-dir=/var/lib/pdns-recursor/udr

#################################
# unique-response-log   Log unique responses
#
# unique-response-log=yes

#################################
# unique-response-pb-tag        If protobuf is configured, the tag to use for messages containing unique DNS responses. Defaults to 'pdns-udr'
#
# unique-response-pb-tag=pdns-udr

#################################
# unique-response-tracking      Track unique responses (tuple of query name, type and RR).
#
# unique-response-tracking=no

#################################
# use-incoming-edns-subnet      Pass along received EDNS Client Subnet information
#
# use-incoming-edns-subnet=no

#################################
# version-string        string reported on version.pdns or version.bind
#
# version-string=PowerDNS Recursor 4.3.0-alpha3.203.master.ga717a3d1e (built Dec  4 2019 11:45:08 by root@d7cbb91b18dc)

#################################
# webserver     Start a webserver (for REST API)
#
webserver=yes

#################################
# webserver-address     IP Address of webserver to listen on
#
# webserver-address=192.168.1.100
webserver-address=127.0.0.1  #this is the default

#################################
# webserver-allow-from  Webserver access is only allowed from these subnets
#
webserver-allow-from=127.0.0.1  #this is the default

#################################
# webserver-loglevel    Amount of logging in the webserver (none, normal, detailed)
#
webserver-loglevel=none

#################################
# webserver-password    Password required for accessing the webserver
#
webserver-password=ABCDEFGHIJKLM

#################################
# webserver-port        Port of webserver to listen on
#
webserver-port=1234

#################################
# write-pid     Write a PID file
#
# write-pid=yes

#################################
# xpf-allow-from        XPF information is only processed from these subnets
#
# xpf-allow-from=

#################################
# xpf-rr-code   XPF option code to use
#
# xpf-rr-code=0
`

**Comment by omoerbeek** [comment]
I doubt that is the actual config file. Please attach it instead of pasting it inline.

**Comment by Tim-herbie** [comment]
[pdns recursor config.txt](https://github.com/PowerDNS/pdns/files/10004634/pdns.recursor.config.txt)

**Comment by omoerbeek** [comment]
If you have a recursor in that state, can you do: 

`rec_control trace-regex thedomain`

then do A query for that name using dig and collect the trace lines from the log and attach it here.

And then switch off tracing:

`rec_control trace`

**Comment by Tim-herbie** [comment]
Okay, I will try, I tested it on a test server- it works. On the productive server, it will genereate realls much logs.

**Comment by omoerbeek** [comment]
We have a hypothesis on what could be going on. A DS query to a recursive forwarded domain could trigger this. 

We have code to "protect" negcache entries being created from DS queries for forwarded domains, but that code does not get triggered for recursive forwards at the moment.

If that assumption is true, you could try a configuration where you forward your local zones _without_ recursive flag, and then everything else recursive, as you are forwarding to a mixed set: authoritative for you local domains, but the rest to a recursive forwarding target.

That would look like:
```
forward-zones=mydomain=ip1, mydoimain2=ip, etc
forward-zones-recurse=.=8.8.8.8 etc
```

BTW: the recursor itself is perfectly capable of doing recursion itself, the recursive forwarding to quad8 is not _needed_, unless you have special reasons to want it.

**Comment by Tim-herbie** [comment]
Thank you so far!

Here are some logs. I would say, that this is the problem:

`Nov 15 15:34:16 pdns-rec1-dc pdns-recursor[293504]: 2 [2003834/2] question for 'mydomain.local|A' from 192.168.20.44:58041`

`Nov 15 15:34:16 pdns-rec1-dc pdns-recursor[293504]: [2003834] mydomain.local: Wants DNSSEC processing, auth data in que.ry for 1`

`Nov 15 15:34:16 pdns-rec1-dc pdns-recursor[293504]: [2003834] mydomain.local: Entire name 'mydomain.local' is negatively cached via 'global' for another 2992 seconds`

`Nov 15 15:34:16 pdns-rec1-dc pdns-recursor[293504]: [2003834] mydomain.local: updating validation state with negative cache content for mydomain.local to Indeterminate`

I will try your hypothesis the next days. I keep you up to date.

**Comment by Tim-herbie** [comment]
Hi! First of all, I have to apologize, that I am not allowed to publish the original logs. I am working in a big company and some logs are too sensitive. But I will give my best, to give you all the required logs, informations to help also other people, who have this same issue.

But I have good news. @omoerbeek I would say, that you are right. Here are some more logs, I hope, that I send the right one. Here you can see, that the host 192.168.20.44 request the powerdns-recursor for exactly the domain "mydomain.local". When this happens, the recursor does not forward this to the dns-server for mydomain.local. Instead, the recursor forward this to the configured public dns-server. After the TTL expired for this domain, it stops working for mydomain.local

Attachted the logs.
[logs.txt](https://github.com/PowerDNS/pdns/files/10021628/logs.txt)

Only after the TTL had expired did it stop working for me. So I would say, that we have found the root cause for that.

The next step for me is to talk with the server owner, which request the "DS" and change the powerdns-recursor configuration as you suggestet.

I will keep you up to date.

**Comment by Habbie** [comment]
> First of all, I have to apologize, that I am not allowed to publish the original logs. I am working in a big company and some logs are too sensitive.

Let's be very clear about something. Our support policy is: no editing. Show original configs, show original logs. That you think you can just ignore the policy, and *lie about it*, because otherwise you won't get help, is an asshole move. Let me repeat that for emphasis: you lied to us to get your free help. This is never acceptable.

That your company has a policy where you cannot publish these logs, does not mean: the open source project will just have to deal with a user that rudely ignores the policy and lies about it. It means: you are not getting support.

(In this case, you got lucky you reported a real bug that we managed to figure out, and thus will fix.)

Your apologies are way, way late. This is not how you deal with the free support resources in an open source project.
