### ISSUE TITLE
auth: 'Consumer' zone created via API gets synthesized SOA record

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#12205]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Creation of a 'Consumer' catalog zone via the API results in an AXFR failure because the zone receives an synthesized SOA RR which will very likely have a serial higher than the primary's SOA serial.

### Environment
 - Operating system: Debian Bookworm
 - Software version: 4.7.2
 - Software source: self-compiled using PowerDNS builder

### Steps to reproduce
1. Use API to create a 'Consumer' zone, without specifying any SOA details (as none should be necessary).
2. Run 'pdnsutil list-zone <zone>'.
3. See SOA record in output which does not match SOA record from primary (also note that an error is emitted in the log/journal because the local SOA serial is higher than the primary SOA serial).

### Expected behaviour
SOA record should not be synthesised, as a 'Consumer' zone is similar in behavior to a 'Slave' zone.

### Actual behaviour
Zone AXFR fails due to SOA serial being incorrect.

### Other information
I've found the code in `ws-auth.cc` which is responsible for this; it only checks the zone kind for 'Slave' and does not check for 'Consumer'.

I'll open two PRs to address this:

* For `rel/auth-4.7.x` I'll just patch ws-auth.cc to have the correct zone kind tests.
* For `master` I'll lift `DomainKind` and its conversion/classification functions out of `DomainInfo` into a class-wrapped-enum, and then update all of the users to use the new class. This should help avoid this type of problem in the future as direct comparisons against the zone 'kind' would only be needed in very specific circumstances.

**Comment by Habbie** [comment]
Fixed in #12285 (and #12291)
