### ISSUE TITLE
Add an "allow-query" option for pdns-recursor to selectively negate "dont-query"

### ISSUE THREAD

**Issue by nneul** [PowerDNS/pdns#12217]
- Program: Recursor
 - Issue type: Feature request

### Short description
Please add a configuration option that will allow selectively overriding dont-query. I suggest "allow-query" or "permit-query". 

### Usecase
Currently, dont-query has an aggressive (good) default, however, this makes it annoying to add an exception, such as listing a small number of 10.x addresses for which delegation is internally approved.

I specifically do NOT want to hard code them into forward-zones/forward-zones-recurse since I want our internal recursors to look at our upstream (though internal) dns servers for any delegations. 

I understand I can adjust the dont-query default, but that just expands out into ugliness to subtract a couple of single addresses from an entire 10.0.0.0/8 dont-query default. 

### Description

Check the "allow-query" setting immediately for a match immediately prior to checking the "dont-query" setting. If address matches, ignore the setting in "dont-query".

Alternatively:   If there is already a way to do this, please consider this a documentation update request to add a reference to the documentation for "dont-query" setting here: https://docs.powerdns.com/recursor/settings.html#dont-query

**Comment by dwfreed** [comment]
`dont-query` is backed by a `NetmaskGroup`, so presumably can be negated in the same way; ie, `10.0.0.0/8, !10.0.0.0/24` should block 10/8 except the first /24

**Comment by nneul** [comment]
Thank you, I'll give that a try.

**Comment by omoerbeek** [comment]
Should already bepossible, more a question of documentation.
