### ISSUE TITLE
PowerDNS cannot handle reverse DNS lookups for private IPs

### ISSUE THREAD

**Issue by mingkwind** [PowerDNS/pdns#12215]
### Short description
PowerDNS cannot handle reverse DNS lookups for private IPs.

### Environment
 - Operating system: Ubuntu 20.04.3
 - Software version: PowerDNS Authoritative Server 4.7.2
 - Software source:  PowerDNS repository, compiled by myself 

### Steps to reproduce
1. Start PowerDNS. The recursor.conf configuration options are as follows.
```
local-address=127.0.0.1
local-port=53
setgid=root
setuid=root
allow-from=0.0.0.0/0
dnssec=off
pdns-distributes-queries=no
forward-zones=.=127.0.0.1
forward-zones-recurse=.=127.0.0.1
```
2. Use dig to do a reverse DNS lookups for one private IP.
Just like this:
```bash
 dig -x 172.16.1.1  @127.0.0.1 -p 53
```

### Expected behaviour
Just like other dns servers such as bind \ dnsmasq \ smartdns \ knot do iteratively querying the upstream domain name server for the reverse DNS lookups  and return the packet with the Rcode 0 which means the packet is NOERRAR.

### Actual behaviour
The result of the dig show this:
```
; <<>> DiG 9.16.1-Ubuntu <<>> -x 172.16.1.1 @127.0.0.1 -p 53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 1552
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;1.1.16.172.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
16.172.in-addr.arpa.	3600	IN	SOA	localhost. root. 1 604800 86400 2419200 604800

;; Query time: 1 msec
;; SERVER: 127.0.0.1#5356(127.0.0.1)
;; WHEN: Sun Nov 20 16:16:39 CST 2022
;; MSG SIZE  rcvd: 101
```
We can find that the status of the header is NXDOMAIN, and  it return the resonse packet directly without iteratively querying the upstream domain name server.

**Comment by omoerbeek** [comment]
https://docs.powerdns.com/recursor/settings.html#dont-query

Also:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
