### ISSUE TITLE
[Feature request] DNST & TLSADOT RRTYPES

### ISSUE THREAD

**Issue by HLFH** [PowerDNS/pdns#12224]
- Program: Authoritative
 - Issue type: Feature request

### Short description
The original DNS over TLS (RFC7858) and DNS over HTTPS (RFC8484) specifications were limited to client-to-resolver traffic. The remaining privacy component is recursive-to-authoritative servers. This [Internet Draft](https://datatracker.ietf.org/doc/html/draft-dickson-dprive-adot-auth-06) is designed to provide a solution to this problem.

### Usecase
Therefore, it would be great to support the DNST & TLSADOT RRTYPES and provide authenticated DNS over TLS to Authoritative Servers.

### Description
[Internet Draft](https://datatracker.ietf.org/doc/html/draft-dickson-dprive-adot-auth-06)

**Comment by Habbie** [comment]
This internet draft is expired, and no code points have been assigned for it, to my knowledge. So there is no incentive -or- possibility to implement. Sorry.
