### ISSUE TITLE
pdnsutil delete-tsig-key does not work with lmdb

### ISSUE THREAD

**Issue by lazat77** [PowerDNS/pdns#12223]
Issue type: Bug report of pdnsutil and lmdb backend

When I issue 

pdnsutil list-tsig-keys I have 2 keys with the same name.

tsig-transfermykeys. hmac-sha512. Wxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
mykey2-test. hmac-sha512. Wyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=
mykey2-test. hmac-sha256. Wyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=

When i issue

pdnsutil delete-tsig-key mykey2-test 
console says: Deleted TSIG key mykey2-test.

problem 1.
If  after that lists keys pdnsutil list-tsig-keys
all 3 keys are still there.

problem 2.
If I delete a bougus non existent key lets say "thiskeydoesnotexcist" pdnsutil still says that it deleted. 
I guess it should say non excistent key  thiskeydoesnotexcist

This bug seams to be related to https://github.com/PowerDNS/pdns/pull/1520

Im using  pdnsutil --version pdnsutil 4.7.2
With lmdb backend.
AlmaLinux release 9.0 (Emerald Puma) with repo 

PowerDNS repository for PowerDNS Authoritative Server - version 4.7.X (stable)
baseurl=http://repo.powerdns.com/el/$basearch/$releasever/auth-47

 

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by rgacogne** [comment]
Possibly fixed by https://github.com/PowerDNS/pdns/pull/11755 but I did not test.
