### ISSUE TITLE
Remove zombie/dead zones on superslave server

### ISSUE THREAD

**Issue by lovelord83** [PowerDNS/pdns#12246]
Good Evening, 

is there a way to be noticed on master's GUI (or slave) of zombie/dead zones in superslave server?

Everytime I forgot to manually delete a zone from superslave and I notice that watching total domain count, I need to diff export from 

```
pdnsutil list-all-zones primary > out1 (on master) 
diff
pdnsutil list-all-zones secondary > out2 (on slave)
```

automatic pruning of zombie/dead zones on superslave will be great, but even just notice that domain not served anymore is enough really.

Any advice or idea about it?

**Comment by rgacogne** [comment]
Hello,

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
