### ISSUE TITLE
Select default type for new zones

### ISSUE THREAD

**Issue by lovelord83** [PowerDNS/pdns#12247]
Is there a way to select default zone type for a server instead specify it everytime I enter a new zone in my master? I'd like to pre-select type:master everytime instead asking for native/master/slave options (with native pre-selected).

Really can't find any settings in general options about that.

**Comment by rgacogne** [comment]
Hello,

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
