### ISSUE TITLE
auth, dnsdist: TSIG, ECS conflict, causing auth REFUSED

### ISSUE THREAD

**Issue by kescherCode** [PowerDNS/pdns#12259]
- Program: Authoritative, dnsdist 
 - Issue type: Bug report

### Short description

My setup involves PowerDNS Authoritative Server behind dnsdist, also using the Proxy Protocol.
When an incoming query is signed with TSIG, which is required for RFC2136 updates for Let's Encrypt, and ECS is set by dnsdist from either client information or forwarded by an upstream resolver, the response is refused with rcode `REFUSED` (5).

### Environment

 - Operating system: Arch Linux
 - Software version: PowerDNS Authoritative Server 4.7.2, dnsdist 1.7.2
 - Software source: Arch repositories, AUR 

### Steps to reproduce

1. Enable proxy protocol, accept forwarded ECS by dnsdist in Authoritative server, enable proxy protocol for same downstream server, forward ECS in dnsdist 
2. Set TSIGs that are allowed to update certain dns records (with a custom lua policy) 
3. Try to query the SOA record on the domain you're trying to update [as done here](https://github.com/certbot/certbot/blob/3d0c2abd3b3139f1fc0b35c36c8887a24204f87a/certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py#L224), or try sending an RFC2136 update, with a TSIG signature  

### Expected behaviour

I would expect the SOA record to be returned, or the update to be successful.

### Actual behaviour

Response refused with rcode `REFUSED` coming from the authoritative server.

### Other information

Disabling ECS for queries affected by this fixes this. I am currently working around this precise issue by having the following in my dnsdist config:

```
addAction(OrRule({OpcodeRule(DNSOpcode.Update), QTypeRule(DNSQType.SOA)}), SetDisableECSAction())
```

~~I am unsure if the proxy protocol interacts with this at all – I haven't been able to test that.~~

**Comment by Habbie** [comment]
Adding ECS in dnsdist breaks TSIG. (Perhaps the dnsdist docs should mention this!)

What I don't get is why you're doing ECS *and* proxy protocol - what is the purpose of ECS here?

**Comment by kescherCode** [comment]
@Habbie the purpose of ECS is to have the authoritative server do GeoIP lookups and respond with different record based on the result of these. The purpose of the proxy protocol is to check the incoming resolver IP against a list of resolvers that are allowed to receive certain records (debugging)

**Comment by rgacogne** [comment]
Are you sure you need both? The authoritative server should be able to use the information present in the proxy protocol payload to do the GeoIP lookups.
The problem is that a TSIG signature covers all the records present in the DNS payload, so adding or altering the OPT record to add the EDNS Client Subnet information will invalidate the TSIG signature, and there is not much that dnsdist can do about that.

**Comment by hlindqvist** [comment]
In an attempt of potentially reducing confusion: 

If you configure dnsdist to *change* ECS (changing the contents of the message, which then breaks TSIG), the ECS data will now match the Proxyv2 data, not providing any real additional value.

If what you just want is just for the authoritative server sitting behind dnsdist to to *use* ECS data in queries coming in from big resolvers, say a query coming in via `8.8.8.8`, dnsdist should just leave any already present ECS data alone (a behavior which would not affect TSIG).

**Comment by kescherCode** [comment]
Interesting, I did try to set this up before but the proxy protocol just wouldn't set the client subnet. This seems to have changed – I don't know when exactly that behaviour would've changed, but I'll take it. I guess that makes this issue no longer affect me, so, thanks, @rgacogne @hlindqvist!

I will close this issue to instead make a feature request for a `TsigRule()` / `TSIGRule()` in dnsdist. This is not an issue in auth, but with the way ECS and TSIG work and thus conflict.
