### ISSUE TITLE
The resolution result of DNS Recursor is NXDOMAIN, but in fact the domain name has a resolution result in com domain

### ISSUE THREAD

**Issue by zjs604381586** [PowerDNS/pdns#12261]
- Program: Recursor
 - Issue type: Bug report

### Short description

* I need to resolve such a domain name **scbe.ybvip.com**，the ns of **ybvip.com** is **ns3.dnsv4.com. and ns4.dnsv4.com**， but the resolution result of **scbe.ybvip.com** is not configured in these two &&NS domain names, The analysis result of **scbe.ybvip.com** is in the **NS of com**.
* When there are these two NSs of the **ybvip.com** domain name in the dns recursor cache, **dig scbe.ybvip.com** will return **NXDOMAIN**; 
* when there is no NS cache of **ybvip.com** in the dns recursor or the cache expires, it will return correct from the NS of com analysis results. 
### Environment

 - Operating system: **Linux debian 10**
 - Software version: **rec-4.8.0-rc1**

### Expected behaviour

The parsing result of **dig scbe.ybvip.com** is correct every time, and there is no such thing as **NXDOMAIN**
### Actual behaviour

 in most cases, parsing **dig scbe.ybvip.com will return NXDOMAIN**

**Comment by zjs604381586** [comment]
The resolution of scbe.ybvip.com obtained from these two NSs has always been NXDOMAIN, so can the recursor go to com to resolve when there is no result in resolving the domain name in the NS cache of the recursor?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by zjs604381586** [comment]
I may think this is a defect in processing resolution. After all, many people may configure the domain name as I described, and this domain name is just one of them I encountered

**Comment by omoerbeek** [comment]
No, you are misunderstanding things. Please read what @Habbie wrote and follow that.
