### ISSUE TITLE
Classless in-addr.arpa delegation broken

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#123]
It seems in certain cases PowerDNS does not volunteer the CNAME it has
when asked for a PTR; which will break sites with rfc2317
(http://www.ietf.org/rfc/rfc2317.txt) setup.

We are running r950 out of the SVN trunk with a patch for #118
(http://wiki.powerdns.com/cgi-bin/trac.fcgi/ticket/118).

So for example we have a BIND master with a zone file that looks
something like this:

```
$TTL 3600
$ORIGIN 222.12.69.in-addr.arpa.
@               IN      SOA     sonic.net. hostmaster.sonic.net. (
                       2006121401      ; serial
                       3600            ; refresh
                       300             ; retry
                       1209600          ; expire
                       3600 )          ; minimum ttl
               IN      NS      a.auth-ns.sonic.net.
               IN      NS      b.auth-ns.sonic.net.
               IN      NS      c.auth-ns.sonic.net.
0-255           IN      NS      ns1.quantact.com.
0-255           IN      NS      ns2.quantact.com.
2               IN      CNAME   2.0-255.222.12.69.in-addr.arpa.
```

If you ask the BIND master for the reverse you get the CNAME and glue records:

```
[augie@augnix ~]$ dig -x 69.12.222.2 @mns1.sonic.net +norecurse
;; ANSWER SECTION:
2.222.12.69.in-addr.arpa. 3600  IN      CNAME   2.0-255.222.12.69.in-addr.arpa.
;; AUTHORITY SECTION:
0-255.222.12.69.in-addr.arpa. 3600 IN   NS      ns1.quantact.com.
0-255.222.12.69.in-addr.arpa. 3600 IN   NS      ns2.quantact.com.
;; ADDITIONAL SECTION:
ns1.quantact.com.       172121  IN      A       64.142.109.250
ns2.quantact.com.       172121  IN      A       64.151.119.219
```

But if you ask one of the PowerDNS authoritative slaves you only get the glue:

```
[augie@augnix ~]$ dig -x 69.12.222.2 @a.auth-ns.sonic.net +norecurse
;; AUTHORITY SECTION:
0-255.222.12.69.in-addr.arpa. 3600 IN   NS      ns1.quantact.com.
0-255.222.12.69.in-addr.arpa. 3600 IN   NS      ns2.quantact.com.
```

The pertinent bits in the PowerDNS slave DBs look like this:

```
mysql> select name,type,content from records where domain_id = 17603
and type = 'NS';
+------------------------------+------+---------------------+
| name                         | type | content             |
+------------------------------+------+---------------------+
| 222.12.69.in-addr.arpa       | NS   | a.auth-ns.sonic.net |
| 222.12.69.in-addr.arpa       | NS   | b.auth-ns.sonic.net |
| 222.12.69.in-addr.arpa       | NS   | c.auth-ns.sonic.net |
| 0-255.222.12.69.in-addr.arpa | NS   | ns1.quantact.com    |
| 0-255.222.12.69.in-addr.arpa | NS   | ns2.quantact.com    |
+------------------------------+------+---------------------+
```

and

```
mysql> select name,type,content from records where content =
'2.0-255.222.12.69.in-addr.arpa';
+--------------------------+-------+--------------------------------+
| name                     | type  | content                        |
+--------------------------+-------+--------------------------------+
| 2.222.12.69.in-addr.arpa | CNAME | 2.0-255.222.12.69.in-addr.arpa |
+--------------------------+-------+--------------------------------+
```

**Comment by realpepio** [comment]
Hello,
I'm having same issue with rfc2317.txt classless in-addr.arpa delegation.
Tested with:
 pdns-4.5.2-1pdns.el8.x86_64 / pdns-backend-mysql-4.5.2-1pdns.el8.x86_64
  and
 pdns-4.6.0-0.beta1.1pdns.el8.x86_64 / pdns-backend-mysql-4.6.0-0.beta1.1pdns.el8.x86_64
 
 r@s1:~$ dig -t PTR 129.12.11.10.in-addr.arpa. @10.1.1.1

; <<>> DiG 9.16.1-Ubuntu <<>> -t PTR 129.12.11.10.in-addr.arpa. @10.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 27562
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;129.12.11.10.in-addr.arpa.     IN      PTR

;; Query time: 151 msec

r@s1:~$ dig -t CNAME 129.12.11.10.in-addr.arpa. @10.1.1.1

; <<>> DiG 9.16.1-Ubuntu <<>> -t CNAME 129.12.11.10.in-addr.arpa. @10.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40038
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;129.12.11.10.in-addr.arpa.     IN      CNAME

;; ANSWER SECTION:
129.12.11.10.in-addr.arpa. 86400 IN     CNAME   129.128-26.12.11.10.in-addr.arpa.

;; Query time: 143 msec


r@s1:~$ dig -t NS 128-26.12.11.10.in-addr.arpa. @10.1.1.1

; <<>> DiG 9.16.1-Ubuntu <<>> -t NS 128-26.12.11.10.in-addr.arpa. @10.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 50693
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;128-26.12.11.10.in-addr.arpa.  IN      NS

;; Query time: 147 msec

Here is a sample zone conf to reproduce:
MariaDB [powerdns]> select * from domains where id=57;
+----+-----------------------+--------+------------+--------+-----------------+---------+
| id | name                  | master | last_check | type   | notified_serial | account |
+----+-----------------------+--------+------------+--------+-----------------+---------+
| 57 | 12.11.10.in-addr.arpa | NULL   |       NULL | MASTER |            NULL | NULL    |
+----+-----------------------+--------+------------+--------+-----------------+---------+
1 row in set (0.000 sec)

MariaDB [powerdns]> select * from records where domain_id=57;
+------+-----------+------------------------------+-------+--------------------------------------------------------------+-------+------+-------------+----------+-----------+------+
| id   | domain_id | name                         | type  | content                                                      | ttl   | prio | change_date | disabled | ordername | auth |
+------+-----------+------------------------------+-------+--------------------------------------------------------------+-------+------+-------------+----------+-----------+------+
| 2089 |        57 | 12.11.10.in-addr.arpa        | SOA   | ns01.test.com test.test.com 2022011208 3600 900 604800 86400 | 86400 | NULL |  1641990695 |        0 | NULL      |    1 |
| 2090 |        57 | 12.11.10.in-addr.arpa        | NS    | ns01.test.com                                                | 86400 |    0 |  1641990720 |        0 | NULL      |    1 |
| 2091 |        57 | 12.11.10.in-addr.arpa        | NS    | ns02.test.com                                                | 86400 |    0 |  1641990735 |        0 | NULL      |    1 |
| 2092 |        57 | 128-26.12.11.10.in-addr.arpa | NS    | ns01.subnet.com                                              | 86400 |    0 |  1641990795 |        0 | NULL      |    1 |
| 2093 |        57 | 128-26.12.11.10.in-addr.arpa | NS    | ns02.subnet.com                                              | 86400 |    0 |  1641990809 |        0 | NULL      |    1 |
| 2094 |        57 | 129.12.11.10.in-addr.arpa    | CNAME | 129.128-26.12.11.10.in-addr.arpa                             | 86400 |    0 |  1641990840 |        0 | NULL      |    1 |
+------+-----------+------------------------------+-------+--------------------------------------------------------------+-------+------+-------------+----------+-----------+------+
6 rows in set (0.000 sec)

MariaDB [powerdns]> 

Is something wrong there?

**Comment by realpepio** [comment]
The issue above has been resolved.
It was caused by a wrong DB structure version.
