### ISSUE TITLE
Dnsdist rules and actions reference documentation is not part of the reference guide

### ISSUE THREAD

**Issue by hlindqvist** [PowerDNS/pdns#12300]
- Program: dnsdist docs 
 - Issue type: Bug report

### Environment

 - Operating system: any
 - Software version: 1.7.3
 - Software source: https://dnsdist.org/reference/index.html

### Steps to reproduce

1. Navigate to the dnsdist reference documentation at https://dnsdist.org/reference/index.html
2. Attempt to find rules and actions
3. ??

### Expected behaviour

I expect there to be reference documentation for the fundamental concepts of rules and actions in the reference guide

### Actual behaviour

There is nothing to be found about rules and actions in the reference guide.

The *Packet Policies* section however, after going through a bit of conceptual explanation, shifts over to effectively reference documentation: https://dnsdist.org/rules-actions.html#rule-generators
But that whole page is categorized by the leading explanatory text, leaving crucial parts of the reference documentation stranded outside of the reference guide.

### Other information

Maybe split *Packet Policies* in two parts, moving the reference part of it into the reference section?

**Comment by omoerbeek** [comment]
I suggest moving the `Rule Generators` (containing only deprecated functions) and `Managing Rules` sections somewhere else. It is more logical to have the `Matching Packets (Selectors)` and `Actions` sections earlier in the policy page.
