### ISSUE TITLE
powerdns recursive run lua file multiple times?

### ISSUE THREAD

**Issue by Melih4ybar** [PowerDNS/pdns#12312]
- Program: Recursor 
 - Issue type: Bug report

### Short description
powerdns-recursor calls lua file 3 times view in 'tail -f /var/log/syslog'

### Environment

 - Operating system: Debian bullseye (11.5.0)
 - Software version: 4.4.2
 - Software source: Operating system repository 

### Steps to reproduce

1.  Restart the powerdns-recursor service and view the log file in terminal with 'tail -f /var/log/syslog'
2.  In the powerdns-recursor config file, just an extra 'pdns-script-file=/etc/powerdns/test.lua' is added and it says "pdnslog('Hi, Lua is running')" in the file.
3.   When I restarted powerdns-recursor, I noticed that it was calling the lua file 3 times in the terminal. When I check this situation with "math.random()", the math.random results are equal in the lua file written 3 times.

### Expected behaviour

The main problem is when I define an array and try to save the domain names in it using preresolve 'logArray[dq.qname:toString()]' like here. I tried to share my problem with you, as I understand it, as if it is adding it to another array randomly, as if there are 2 different arrays and some domain names are written to the LogA array and some to the LogB array.

### Actual behaviour

![Screenshot_1](https://user-images.githubusercontent.com/80976083/206802430-53acaa5e-8786-4ff3-b417-0022713da0b6.png)

**Comment by omoerbeek** [comment]
Hello,

It is very rude to contact developers on the private email address. Also:

Our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by Ramshield** [comment]
Or even contacting non-developers...

**Comment by Habbie** [comment]
@Melih4ybar I understand you are still spamming random people with emails about your question. Please stop.

**Comment by franklouwers** [comment]
Got this mail as well. As a Certified PowerDNS consultant, I am happy to help, will reply with my consulting rates via mail.

**Comment by omoerbeek** [comment]
> Or even contacting non-developers...

Very true. I replied to this after getting reports from team members. I did not know that other contributors were contacted as well.
