### ISSUE TITLE
'pdnsutil edit-zone' doesn't work in RHEL

### ISSUE THREAD

**Issue by v1shnya** [PowerDNS/pdns#12338]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

'pdnsutil edit-zone' doesn't work in RHEL

### Environment

 - Operating system: RHEL 8.5
 - Software version: PowerDNS 4.7.2
 - Software source: RPM

### Steps to reproduce

```
[/home/dev]$ EDITOR='/usr/bin/vi'
[/home/dev]$ export EDITOR
[/home/dev]$ echo $EDITOR
/usr/bin/vi
[/home/dev]$ sudo pdnsutil edit-zone test.com
Dec 19 11:01:13 godbc Connection successful
Dec 19 11:01:14 godbc Connection successful
sh: editor: command not found
Error: Editing file with: 'editor /tmp/pdnsutil-WkU2Nl', perhaps set EDITOR variable: Operation now in progress
```
### Other information

I belive that the problem is related to the CHAR* to STRING assignment in the code. 
See it started from the line https://github.com/PowerDNS/pdns/blob/master/pdns/pdnsutil.cc#L1188
```
  string editor="editor";
  if(auto e=getenv("EDITOR")) // <3
    editor=e;
```
Function `char* getenv (const char* name)` returns CHAR* that can't be just assigned to STRING. Need to use type conversion
`editor=str(e);`

**Comment by omoerbeek** [comment]
It is also very possible that the environment provided by sudo does not provide EDITOR.

**Comment by v1shnya** [comment]
```
[/home/dev]$ EDITOR='/usr/bin/vi'
[/home/dev]$ echo $EDITOR
/usr/bin/vi
[/home/dev]$ sudo  echo $EDITOR
/usr/bin/vi
```
using `sudo `I still can see EDITOR variable

**Comment by v1shnya** [comment]
Was wrong, assignment `editor=e` is correct. By the way, the same issue is also seen on Ubuntu - can't specify EDITOR envvar.

So, for me it looks like  the problem is in the `if(auto e=getenv("EDITOR"))` statement

**Comment by pieterlexis-tomtom** [comment]
this works for me (on Arch):

```
sudo -E EDITOR=vim pdnsutil edit-zone $ZONE
```

Does this (with your favorite editor) work on RHEL?

**Comment by Habbie** [comment]
> [/home/dev]$ sudo  echo $EDITOR

this expands `$EDITOR` before invoking sudo

**Comment by omoerbeek** [comment]
Try sudo sh -c "echo  'PATH=$PATH EDITOR=$EDITOR'"

**Comment by omoerbeek** [comment]
Try `sudo sh -c "echo PATH=\$PATH EDITOR=\$EDITOR"`

**Comment by v1shnya** [comment]
```
[/home/dev]$ sudo sh -c "echo PATH=\$PATH EDITOR=\$EDITOR"
PATH=/sbin:/bin:/usr/sbin:/usr/bin EDITOR=
```

Yes, `sudo -E EDITOR=vim pdnsutil edit-zone test.com` works!
Thank you! and point taken, will read about sudo  invocation ;)
