### ISSUE TITLE
LUA dblookup for records other than QType other than LUA

### ISSUE THREAD

**Issue by pfak** [PowerDNS/pdns#12358]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Presently `dblookup`  in an `IN LUA` record only supports LUA lookups. It would be helpful if it could support looking up for example `A`, `AAAA` QType so that the IN LUA record can reference other records instead of IP addresses.

### Usecase
To be able to use DNS records instead of IP addresses in `ifurlup` in `LUA` QType.

### Description
Record example:
```
IN LUA A ifurlup("luarecord.example.com", {dblookup("host1.example.com.", "A"), dblookup("host2.example.com", "A")})
```

**Comment by Habbie** [comment]
> Presently `dblookup` in an `IN LUA` record only supports LUA lookups.

it's `include`, which looks up -and executes- LUA records.

**Comment by pfak** [comment]
The build that @Habbie provided me works as I envisioned for this feature request. 

Examples of what I did:

1. Expose online PowerDNS-Admin instance:

```
dns IN LUA A "ifurlup('https://dns.example.com/powerdns-admin/login', {dblookup('ns1.example.com', 'A'), dblookup('ns2.example.com', 'A'), dblookup('ns3.example.com', 'A')}, {stringmatch='PowerDNS-Admin', selector='hashed'})"
dns IN LUA AAAA "ifurlup('https://dns.example.com/powerdns-admin/login', {dblookup('ns1.example.com', 'AAAA'), dblookup('ns2.example.com', 'AAAA'), dblookup('ns3.example.com', 'AAAA')}, {stringmatch='PowerDNS-Admin', selector='hashed'})"
```

2. Return IP address to connect to my home network for WireGuard listening on OpenWrt (I did not use `ifportup` because it does not support ordering, and I needed to return the first result if it is up):

```
IN A "ifurlup('http://remote.example.com/', {dblookup('isp1.remote.example.com', 'A'), dblookup('isp2.remote.example.com', 'A')}, {stringmatch='LuCI - Lua Configuration Interface', selector='hashed'})"
```

**Comment by Habbie** [comment]
> The build that @Habbie provided me works as I envisioned for this feature request.

that's #12359

**Comment by Habbie** [comment]
> that's #12359

which was merged!

**Comment by peterthomassen** [comment]
Unlike with `resolve()`, it seems like the `type` argument of `dblookup` must be a string (i.e. `pdns.A` etc. can't be used). I'm not sure how difficult it would be to add that option, but it would be a nice addition. :-)

**Comment by Habbie** [comment]
Oh, that's a good point, I did not realise this inconsistency.

Adding it is hard, changing it is easy. We don't usually do breaking changes so late but this is a very new feature so I assume we don't have too many users yet.

**Comment by Habbie** [comment]
#13860
