### ISSUE TITLE
PowerDNS need's answer any query with an "A" record when no A or cName Record Found

### ISSUE THREAD

**Issue by mhktanbir** [PowerDNS/pdns#12379]
I have setup a DNS server with centos 7 & powerDNS letest. All things are working fine. but I want to do a thing that will be share a A record for every domain which is no listed on this DNS server, that means when there are no cName or A record in this server.

As lke this DNS server: The DNS (162.214.41.44) server can answer any query with a default IP. See the example: Test1 on 162.214.41.44 this server
https://i.stack.imgur.com/yxa7y.png

Test2 on 162.214.41.44 this server
https://i.stack.imgur.com/GKBft.png

But when I enter same query on my DNS server than it's show this result: See this result of my DNS server 103.148.14.114
https://i.stack.imgur.com/LQuKS.png

How can I configure this DNS server that give a dafault Answer on every Query?

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
