### ISSUE TITLE
pdnsutil delete-tsig-key doesn't actually delete anything when running against LMDB backend (also duplicating keys)

### ISSUE THREAD

**Issue by nneul** [PowerDNS/pdns#12394]
- Program: Authoritative
 - Issue type: Bug report

### Short description
pdnsutil delete-tsig-key says it's deleting, but then doesn't actually delete anything

pdnsutil generate-tsig-key creating duplicate keys (I realize this is separate, but highly likely it's the same underlying issue in LMDB interaction)

### Environment
 - Operating system: Ubuntu 20
 - Software version: 4.7.2
 - Software source: pdns repo

Running with LMDB backend.

*NOTE* It works properly with a mysql backend.
 
### Steps to reproduce

```
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil generate-tsig-key test1 hmac-sha512
Create new TSIG key test1 hmac-sha512 EXAMPLEKEY==
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil list-tsig-keys
test1. hmac-sha512. EXAMPLEKEY==
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil delete-tsig-key test1
Deleted TSIG key test1
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil list-tsig-keys
test1. hmac-sha512. EXAMPLEKEY==

root@pdns-authoritative02:~# systemctl restart pdns.service

pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil list-tsig-keys
test1. hmac-sha512. EXAMPLEKEY==

```

### Expected behaviour
After issuing delete-tsig-key would expect it to be gone from the list.

### Actual behaviour
Key still defined/present in database.

### Suspected related issue

It appears to not be enforcing uniqueness:

```
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil generate-tsig-key test1 hmac-sha512
Create new TSIG key test1 hmac-sha512 NjXqPHgDhVdCayj6uDCBmkZAnqzknUANwmlxavkxf5UXq7/glzxCc/dGIgp+oKONkkspkKvzmK6Kg+zSrjwPXw==
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil generate-tsig-key test1 hmac-sha512
Create new TSIG key test1 hmac-sha512 HiErY2GCOLd/NP0IvzgGf2kW/ysi8QyhMEJlt5/vDZe7LANtVrf26OOuWs4fqssJs66YR8BOl2oJP+Jb+eFvuw==
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil generate-tsig-key test1 hmac-sha512
Create new TSIG key test1 hmac-sha512 x7jk/nRzHSMYRiuXFHSNJtyQKYNBrJnggsf+r4Gn8LbylEH9hsQgs80+QlolBj+ANl2iBrrSKNFvNALY5eZLNQ==
pdns@pdns-authoritative02:/home/ubuntu$ pdnsutil list-tsig-keys
test1. hmac-sha512. ZOcdxKaw65N19i7d+W2BZcdZmt9loDUz1T+XFZXKHOcEYkCpmFMf2eEosZd7nvcg3GV0afq66eDuFaScD0XCEQ==
test1. hmac-sha512. NjXqPHgDhVdCayj6uDCBmkZAnqzknUANwmlxavkxf5UXq7/glzxCc/dGIgp+oKONkkspkKvzmK6Kg+zSrjwPXw==
test1. hmac-sha512. HiErY2GCOLd/NP0IvzgGf2kW/ysi8QyhMEJlt5/vDZe7LANtVrf26OOuWs4fqssJs66YR8BOl2oJP+Jb+eFvuw==
test1. hmac-sha512. x7jk/nRzHSMYRiuXFHSNJtyQKYNBrJnggsf+r4Gn8LbylEH9hsQgs80+QlolBj+ANl2iBrrSKNFvNALY5eZLNQ==
```

This *ALSO* works fine on mysql backend,  only showing with LMBD. 

I suspect that both have the same underlying cause like not having the expected "key" for the database table, so if it's deleting for delete or for uniqueness, it's not actually finding the right record.

**Comment by mnordhoff** [comment]
TSIG key deletion is issue #12223/PR #12322.

I don't know about the generation issue.
