### ISSUE TITLE
startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument

### ISSUE THREAD

**Issue by secure-xxx** [PowerDNS/pdns#12390]
- Program: Recursor
 - Issue type: Bug report

### Short description
Running recursor in k8s cluster, all works fine, but after one week have this messages:
"startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument"

Due this messages, recursor_serfail counter started to grow, but manual nslookup the above entires was passed successfully (?)
In the same time we have another k8s hihgload instance with recursor, it works fine.

### Environment
 - Operating system: k8s
 - Software version on problem instance: 1.23
 - Software version on NOproblem instance: 1.21
 - Software source: https://github.com/chrisss404/powerdns

### Steps to reproduce
1. Running recursor throughout week

### Actual behaviour

Dec 29 17:30:19 msg="If using IPv6, please raise sysctl net.ipv6.route.max_size to a size >= 16384" subsystem="config" level="0" prio="Error" tid="0" ts="1672335019.378" current="4096"
Dec 30 09:27:02 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="3" ts="1672392422.037" ecs="" exception="PDNSException" mtid="3719" proto="udp" qname="x1.c.lencr.org" qtype="A" remote="127.0.0.1:46864"
Dec 31 18:10:30 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="3" ts="1672510230.871" ecs="" exception="PDNSException" mtid="10867" proto="udp" qname="mail.ru" qtype="A" remote="127.0.0.1:46864"
Jan 02 08:53:08 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="2" ts="1672649588.292" ecs="" exception="PDNSException" mtid="27298" proto="udp" qname="portal.mail.ru" qtype="A" remote="127.0.0.1:46864"
Jan 02 13:15:11 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="2" ts="1672665311.648" ecs="" exception="PDNSException" mtid="28948" proto="udp" qname="ub.myteam.vmailru.net" qtype="A" remote="127.0.0.1:46864"
Jan 03 07:33:37 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="2" ts="1672731217.781" ecs="" exception="PDNSException" mtid="34006" proto="udp" qname="downloads.upd.kaspersky.com" qtype="A" remote="127.0.0.1:46864"
Jan 03 21:03:13 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="3" ts="1672779793.155" ecs="" exception="PDNSException" mtid="24304" proto="udp" qname="docdoc.pro" qtype="A" remote="127.0.0.1:46864"
Jan 04 11:13:09 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="2" ts="1672830789.901" ecs="" exception="PDNSException" mtid="42542" proto="udp" qname="ssl.gstatic.com" qtype="A" remote="127.0.0.1:46864"
Jan 05 05:16:11 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="3" ts="1672895771.545" ecs="" exception="PDNSException" mtid="30148" proto="udp" qname="mail.ru" qtype="A" remote="127.0.0.1:46864"
Jan 06 13:01:29 msg="startDoResolve problem" error="Resolver binding to local query client socket on 0.0.0.0: Invalid argument" subsystem="syncres" level="0" prio="Error" tid="3" ts="1673010089.764" ecs="" exception="PDNSException" mtid="36305" proto="udp" qname="ips1.unifi-ai.com" qtype="AAAA" remote="127.0.0.1:46864"

**Comment by omoerbeek** [comment]
Please try to reproduce with our offial Docker image, available grom [ hub.docket.com.](https://hub.docker.com/search?q=powerdns%2Fpdns-recursor)](https://hub.docker.com/search?q=powerdns%2Fpdns-recursor)

**Comment by secure-xxx** [comment]
Thanks for quickly answer, Image builds from dockerfile and use official repo
https://github.com/chrisss404/powerdns/blob/master/recursor/Dockerfile

**Comment by omoerbeek** [comment]
We cannot support Docker images defined by others. Contact @chrisss404, or reproduce the issue with out official Docker image.

**Comment by secure-xxx** [comment]
Thanks, i will check and give feedback

**Comment by Habbie** [comment]
We're closing this until we get a similar report using our official images or packages.
