### ISSUE TITLE
DNS not resolving (Recursor Not working as expected)

### ISSUE THREAD

**Issue by sidantaa** [PowerDNS/pdns#12409]
Hi everyone,

I am getting issue while forwarding queries for public DNS through PDNS. I have tried configuring pdns recursor and now able to resolve public DNS **youtube.com** but beside this none of the public domain worked at all!!! Strange thing is even the **google.com** is not resolving but **youtube.com** is fine.  The configuration i have tried is:

###### pdns.conf File ######
local-address=127.0.0.1
local-port=5300

###### pdns-recursor/recursor.conf   File ######
 forward-zones=test.com.np=127.0.0.1:5300,.=8.8.8.8
local-address=0.0.0.0

**Note: test.com.np is my private dns zone and beside this i want all the domain to be resolved to google DNS i.e. 8.8.8.8**

Please, assist me on this case. Is there any configuration issue or am i missing something? I am unable to find related knowledgebase for this case. 

Also, configuration files have been attached to this case below.
[pdns.txt](https://github.com/PowerDNS/pdns/files/10389063/pdns.txt)
[recursor.txt](https://github.com/PowerDNS/pdns/files/10389064/recursor.txt)

Best regards,
sidantaa

**Comment by omoerbeek** [comment]
Hello,  

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
