### ISSUE TITLE
misc.cc addCMsgSrcAddr no implementation selected on Hurd

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#1242]
misc.cc addCMsgSrcAddr has an #ifdef; #ifdef; but not #else #error , and on Hurd none of the ifdefs seem to match, giving this warning:

````
misc.cc: In function 'void addCMsgSrcAddr(msghdr*, void*, ComboAddress*)':
misc.cc:816:42: warning: 'cmsg' may be used uninitialized in this function [-Wmaybe-uninitialized]
     msgh->msg_controllen = cmsg->cmsg_len;
                                          ^
````

**Comment by Habbie** [comment]
Unless this is an actual Debian blocker, I do not have a huge interest in running perfectly on Hurd :) Closing.
