### ISSUE TITLE
Lua Records: Support of empty answers on filterForward()

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#12436]
- Program: Authoritative
 - Issue type: Feature request

### Short description

Return empty answers from  [`filterForward()`](https://doc.powerdns.com/authoritative/lua-records/functions.html#filterForward) for addresses in the `NetmaskGroup` argument, instead of `0.0.0.0` or `::0`.

### Usecase

We'd like to use [`createForward()`](https://doc.powerdns.com/authoritative/lua-records/functions.html#createForward) in conjunction with [`filterForward()`](https://doc.powerdns.com/authoritative/lua-records/functions.html#filterForward). Up to now we have answered queries for addresses outside our networks with an empty answer. [`filterForward()`](https://doc.powerdns.com/authoritative/lua-records/functions.html#filterForward) responds with `0.0.0.0` or `::0` by default in this case. Since we do not want to change the usual behavior of our DNS servers, it would be nice if we could continue do so. 

### Description

In addition, [`filterForward()`](https://doc.powerdns.com/authoritative/lua-records/functions.html#filterForward) should accept `''` (empty string) as the `fallback` argument and it should respond with a empty answer in this case.

**Comment by Habbie** [comment]
I'll see what I can do, and otherwise I hope we can ship some fun new features in a 4.9 alpha soon. I'll try to keep them backportable :)

**Comment by paddg** [comment]
Is this still planned for 4.9? I ask because no new milestone was set.

**Comment by Habbie** [comment]
Oops. I'll see what I can do!

**Comment by Habbie** [comment]
#13879 :)
