### ISSUE TITLE
authoritative server won't answer for zone if it's missing delegation in parent zone

### ISSUE THREAD

**Issue by nneul** [PowerDNS/pdns#12430]
- Program: Authoritative
 - Issue type: Bug report

### Short description
This is debatable on whether it's valid data, but behavior feels improper to me. If you have example.com and subzone.example.com as separate zones in a pdns authoritative server, and the NS's for subzone are missing in example.com -- the authoritative server won't answer any requests for content of subzone.example.com.

If this were being resolved through a recursor, behavior would be completely valid/expected, but when talking to an authoritative server, it doesn't seem like it should be relevant or care that the parent zone doesn't have a delegation -- that server might not even BE the authoritative server for that parent zone. 

### Environment
 - Operating system: ubuntu 20.04 lts
 - Software version: 4.7.2
 - Software source: pdns repo

### Steps to reproduce
Create two zones in primary, parent and child
Don't delegate to the child
Add full set of records in the child zone, including NS records pointing to that same authoritative instance
Try to resolve any record in the child zone, you'll get NXDOMAIN

### Expected behaviour
Records should resolve, regardless of validity of content in parent zone.

### Actual behaviour
NXDOMAIN on all lookups.

### Other information
Clearly for an overall "valid" set of config the delegation records should be there, and that was fix for the symptom I saw -- but, I don't believe the server should behave this way. An authoritative server should answer for all zones that it is authoritative for, regardless of the configuration or content of any other zones on that same server.

**Comment by klaus-nicat** [comment]
Are you sure? I never saw this issue in PDNS yet (sill on 4.6.4). At least with an SQL backend, PowerDNS just performs "select * from records where type=SOA and name=qname" to find the zone that is responsible to answer the query. Hence, this query would return the subzone.example.com zone and PDNS would use this zone to serve the query. Hence, PDNS does not even know/care that there can be also example.com zone in the DB.

Which backend are you using?

**Comment by pfak** [comment]
Cannot reproduce on `4.8.0~alpha0+authluadblookup.871.gad4de1e5b-1pdns.bionic amd64` with `gmysql` backend.

**Comment by mnordhoff** [comment]
N.B.: Even when the authoritative servers have no bugs, a missing parent-side delegation may upset some resolvers* if you're not using DNSSEC, and _will_ break the child zone if you are using DNSSEC.

* systemd-resolved

**Comment by nneul** [comment]
I was doing direct query against the authoritative server itself, using LMDB backend - no other resolvers involved.  Only change I made from 'no response' to 'working' was to add the delegations. 

Let me see if I can "break it" by removing the delegation temporarily.

**Comment by nneul** [comment]
AH, I just realized I may have been missing a detail in the steps that could be relevant -- the particular authoritative server I was looking at was a secondary for the zones. Sorry that's probably important to the reproduction. 

I was validating pointing to the secondary, and was validating that the records fully existed in the secondary with 'pdnsutil list-zone'.

Let me try to reproduce fully.

**Comment by nneul** [comment]
Well, it doesn't reproduce now... I'll just close this, cause I'm inclined to agree with your assessment. If I manage to reproduce cleanly, I'll re-open, but maybe it was just something else in the woodwork and me changing the upstream/parent "wiggled it loose".
