### ISSUE TITLE
Default udp-size for received packets

### ISSUE THREAD

**Issue by idealeer** [PowerDNS/pdns#12449]
For the udp-size of received responses from authoritative
servers, we found the default of PowerDNS Recursor is
<=1,232, while the other software, such as BIND9, Unbound,
and Knot Resolver, support a response larger than 4,096.
For the packet sent to clients, 1,232 is good to prevent
large response causing amplification attacks as PowerDNS
Recursor does.

Do you think PowerDNS Recursor should keep the same
max size for received packets out of compatibility and
robustness?

**Comment by phonedph1** [comment]
Are you suggesting that with `edns-outgoing-bufsize=1232` you have servers ignoring you and sending large packets, and you expect PowerDNS recursor to accept these? 

It would be suggested you open this using the template provided so it's clear what the issue is, otherwise might be best to come chat on IRC or the mailing lists.

**Comment by omoerbeek** [comment]
Please read https://www.dnsflagday.net/2020/

**Comment by omoerbeek** [comment]
Also I think you are wrong (or misunderstanding things), the default advertised bufsize to auths by unbound, knot and bind is 1232, just like PowerDNS Recursor.

**Comment by idealeer** [comment]
right. the default advertised bufsize is all 1,232. but bind, unbound, and knot will accept a response with size larger than 1,232 even 4,096 after testing.

should we recommend them not do this or make powerdns the same?

**Comment by omoerbeek** [comment]
I don;t think that is wise. Form the flag day document:
```
Authoritative DNS servers MUST NOT send answers larger than the requested EDNS buffer size!
``` 
Unless there are _very_ good reasons, we should not cater for non-conforming auths.

**Comment by mnordhoff** [comment]
IIRC, one other nameserver supports illegal large responses mainly because, with how their packet handling code is designed, accepting them is easier than rejecting them.

**Comment by idealeer** [comment]
Sure. I'll try to contact the other software vendors. Tks.
