### ISSUE TITLE
skip auth requirement on dnsdist embedded webserver

### ISSUE THREAD

**Issue by dch** [PowerDNS/pdns#12440]
- Program: dnsdist
 - Issue type: Feature request

### Short description

Add an off-by-default option for the webserver to allow unauthenticated viewing

### Usecase

Skip auth popups for 5+ dnsdist servers when I want to see what they're up to.

### Description

The embedded dnsdist dashboard is great. But when you need to open many of them
on different servers to check something, it gets annoying. This can be worked
around by using an HTTP proxy that adds the header, but it would be better
not to have to do this in the first place.

The webserver is both readonly and has no filesystem access, only making calls to:

- GET /api/v1/servers/localhost
- GET /jsonstat

**Comment by rgacogne** [comment]
Looks like a duplicate of https://github.com/PowerDNS/pdns/issues/10360 ? I'm OK with adding that option, to be clear, but no-one has written the code yet :)

**Comment by dch** [comment]
duped by myself :facepalm:
