### ISSUE TITLE
SRV with 'empty' names gets slaved as double-dot

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#1244]
Such a record:
````
_root._tcp.dc           IN      SRV     0 0 0 .
````

becomes:
````
_root._tcp.dc   3600    SRV     0       0 0 ..
````

Can be seen in ``regression-tests/zones/test.com-slave`` after a ``bind-presigned`` test run.

**Comment by Habbie** [comment]
Confirmed in 6576051d03a5f25c0cf8f4848d0ae2eb665aedfa
