### ISSUE TITLE
recursor server to get forward-zone list from auth server database

### ISSUE THREAD

**Issue by mhazan01** [PowerDNS/pdns#12463]
is there any way, assuming both services runs on the same server, for the recursor server to get it's ""forward-zone" list directly updated from the database of the auth server ? i dont want to have to edit config file every time i add a new local domain or i'd go back to bind.

**Comment by kpfleming** [comment]
Now that PowerDNS Auth supports `catalog` zones, it's conceivable that the recursor could subscribe to them and use them as a way to populate `forward-zones`.

**Comment by omoerbeek** [comment]
First, I do not like your tone. If you want to get help, being nice helps.

You do not tell anyhing about your setup. I can see two solutions:

1. Make sure your zone's nameservers can be reached by rec on their public addresses. That way, you do not have to configure anything.
2. If that is not possible you can use th API to admin forward zones.
3. We would likely accept a good PR to do this with catalog zones, but we currently have no plans to implement this ourselves.

**Comment by hlindqvist** [comment]
> Now that PowerDNS Auth supports `catalog` zones, it's conceivable that the recursor could subscribe to them and use them as a way to populate `forward-zones`.

If catalog zone infrastructure were to be added to Recursor, `allow-notify-for` would probably also be a good fit for consuming catalog data.

**Comment by kpfleming** [comment]
Well, interesting news... I find myself with abundant free time over the next few weeks, so I'm going to work on this in hopes that it can land in the 4.9.0 recursor release. On Monday or Tuesday I'll review the recursor codebase and then propose an implementation plan here for review.

**Comment by kpfleming** [comment]
I have begun working on this in #12865.

**Comment by omoerbeek** [comment]
Done in 5.2.0
