### ISSUE TITLE
GitHub action workflows with on: schedule should honor repository variables to allow owners to disable them

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#12498]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description

* There are 5 daily crons, 4 of which are not cheap
* Because it runs on all forks with actions enabled and there aren't many ways for a repository owner to provide input
* Add an opt-in per file variable to control whether a workflow should do work when run from `on: schedule`

### Environment

 - Operating system: 
 - Software version: 
 - Software source: GitHub PowerDNS repository (or a fork, linked to the fork network or not)

### Steps to reproduce

1. Fork pdns
2. Enable workflow actions 
3. Wait a day
4. Check the actions log

### Expected behaviour
Each scheduled workflow should say "skipped" or similar and use no significant CPU time

### Actual behaviour

https://github.com/jsoref/pdns/actions/runs/4069181815/jobs/7008749997#step:7:6294
(A lot of CPU time was spent and I got a failure notification)

### Other information
* https://docs.github.com/en/actions/learn-github-actions/variables
* `if: github.event.schedule` && (variable)

**Comment by rgacogne** [comment]
Would using `if: github.repository == 'PowerDNS/pdns'` in the steps make sense, instead of a variable? GitHub's documentation [1] suggests it should work fine.

[1]: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

**Comment by Habbie** [comment]
> Would using `if: github.repository == 'PowerDNS/pdns'` in the steps make sense, instead of a variable? GitHub's documentation [1](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) suggests it should work fine.

It would, but the ticket came out of a discussion where we considered that a suboptimal solution. The variable would allow fork owners to opt in if they wanted to.

**Comment by Habbie** [comment]
That said, the current situation is worse, and adding `if: github.repo....` would be a decent temporary solution.

**Comment by rgacogne** [comment]
Alright, I'll add conditions with a variable then.
