### ISSUE TITLE
Recursor Every few days there will be a crash of kernel memory access exception

### ISSUE THREAD

**Issue by zjs604381586** [PowerDNS/pdns#12509]
- Program:  Recursor 
 - Issue type: Every few days there will be a crash of kernel memory access exception
 - bt info:
 (gdb) bt
```
    #0  0x00005626b7a3bf5c in ?? ()
    #1  0x00005626b7ab1c23 in ?? ()
    #2  0x00005626b7a9b58e in ?? ()
    #3  0x00005626b7a9d059 in ?? ()
    #4  0x00005626b7aa00f4 in ?? ()
    #5  0x00005626b796c5f0 in ?? ()
    #6  0x00005626b7984da6 in ?? ()
    #7  0x00005626b793f76c in ?? ()
    #8  0x00007f3c54acd1ef in make_fcontext () from /lib/x86_64-linux-gnu/libboost_context.so.1.67.0
    #9  0x0000000000100010 in ?? ()
    #10 0x0000000000000061 in ?? ()
    #11 0x00007f3b40122a80 in ?? ()
    #12 0x00007f3b400000d0 in ?? ()
    #13 0x626c7367046c6d2d in ?? ()
    #14 0x64636e7579736b08 in ?? ()
    #15 0x3300006d6f63036e in ?? ()
    #16 0x2e6a00006d6f6303 in ?? ()
 ```
- sysinfo error log:

        kernel: [10198523.856108] traps: rec/worker[3372914] general protection fault ip:55a3ec08cf5c sp:7f6b50440110 error:0 in pdns_recursor[55a3ebd39000+460000]
        kernel: [10205849.404244] traps: rec/worker[2308035] general protection fault ip:5626b7a3bf5c sp:7f3b40619cf0 error:0 in pdns_recursor[5626b76e8000+460000]

### Short description
 The investigation found that error: 0 means that the kernel space address access failed，boost version 1.67，Doubt whether it is necessary to upgrade the boost version？

### Environment

 - Operating system: debian 10 , kernal version： 5.4.56  x86_64
 - Software version: rec-4.8.0
 - Software source:  rec-4.8.0  self compiled 

### Expected behaviour
normal operation

### Actual behaviour
occasional crash

**Comment by omoerbeek** [comment]
Please upgrade, this is almost certainly  https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2023-01.html

If you subscribe the the announce mailinglist (https://www.powerdns.com/mailing-lists.html) you get announcements of releases.

**Comment by zjs604381586** [comment]
4.8.1 What are the specific revisions submitted?

**Comment by omoerbeek** [comment]
You can read the changelog in the usual place: https://docs.powerdns.com/recursor/changelog/

**Comment by zjs604381586** [comment]
When I finished modifying the code builder deb package, I encountered such an error, how to solve it, thank you very much 
    
       Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/n/net-snmp/libsnmp-dev_5.7.3+dfsg-5+deb10u3_amd64.deb 404 Not Found [IP: 146.75.114.132 80]

I see on deb official website have **[libsnmp-dev_5.7.3+dfsg-5+deb10u4_arm64.deb]**(http://deb.debian.org/debian-security/pool/updates/main/n/net-snmp/libsnmp-dev_5.7.3+dfsg-5+deb10u4_arm64.deb)

**Comment by omoerbeek** [comment]
Please show the exact steps you did and provide the full log.
