### ISSUE TITLE
pdns_control and rec_control don't reflect security polling TXT values

### ISSUE THREAD

**Issue by rsaeks** [PowerDNS/pdns#12506]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
pdns_control and rec_control are unable to translate the security polling host TXT values correctly and show resolution failed instead of actual values.

### Environment
 - Operating system: CentOS 9 Stream
 - Software version: PDNS Authoritative is 4.6.2, PDNS Recursor is 4.7.2
 - Software source: PDNS Repositories

### Steps to reproduce
1. Run each DNS check for the respective version via the CLI with:

```
dig auth-4.6.2.security-status.secpoll.powerdns.com TXT
dig recursor-4.7.2.security-status.secpoll.powerdns.com TXT
```

2. Compare results to corresponding PDNS command line values with:

```
pdns_control show security-status
rec_control get security-status
```

### Expected behaviour
Status values to match

### Actual behaviour
Command line values returned with pdns_control and rec_control both show 0 instead of the correct value corresponding to the result of the DNS query commands:

```
dig auth-4.6.2.security-status.secpoll.powerdns.com TXT

; <<>> DiG 9.16.23-RH <<>> auth-4.6.2.security-status.secpoll.powerdns.com TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13397
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;auth-4.6.2.security-status.secpoll.powerdns.com. IN TXT

;; ANSWER SECTION:
auth-4.6.2.security-status.secpoll.powerdns.com. 60 IN TXT "1 OK"

;; Query time: 64 msec
;; SERVER: 192.168.40.20#53(192.168.40.20)
;; WHEN: Fri Feb 03 11:17:47 CST 2023
;; MSG SIZE  rcvd: 93
```
```
pdns_control show security-status
0
```

```
dig recursor-4.7.2.security-status.secpoll.powerdns.com TXT

; <<>> DiG 9.16.23-RH <<>> recursor-4.7.2.security-status.secpoll.powerdns.com TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39121
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;recursor-4.7.2.security-status.secpoll.powerdns.com. IN	TXT

;; ANSWER SECTION:
recursor-4.7.2.security-status.secpoll.powerdns.com. 60	IN TXT "1 OK"

;; Query time: 77 msec
;; SERVER: 192.168.40.20#53(192.168.40.20)
;; WHEN: Fri Feb 03 11:19:42 CST 2023
;; MSG SIZE  rcvd: 97
```

```
rec_control get security-status
0
```

### Other information
Tested DNS lookups across a variety of machines to rule-out host resolution. Tested on three different PDNS servers and all have the same result.

**Comment by phonedph1** [comment]
What do the logs say for security poll? rec 4.7.2 works fine for me (this is also old and you should upgrade).

```
Feb 03 19:05:10 Polled security status of version 4.7.2, no known issues reported: OK
Feb 03 19:05:51 Received rec_control command 'get security-status' via controlsocket
```

```
[root@8b249e1736e8 /]# rec_control --socket-dir=/var/tmp get security-status
1
```

**Comment by omoerbeek** [comment]
Also: what does `rec_control get-parameter security-poll-suffix` show? If it shows an empty string, you switched off security polling in your config.

**Comment by rsaeks** [comment]
There don't appear to be any entries related to the security status polling in the log, even when running the command manually. The default config is in place where local0 is used for logging and I searched through the messages log file.

Running the provided command as is

`rec_control --socket-dir=/var/tmp get security-status`

returns

`Fatal: Unable to connect to remote '/var/tmp/pdns_recursor.controlsocket': No such file or directory`

Updating the command to reflect the path of the socket:

`rec_control --socket-dir=/var/run/pdns-recursor/ get security-status` returns 

`0`

Also, running:

`rec_control get-parameter security-poll-suffix` returns unknown. This is also the case when running it agains pdns:

`pdns_control show security-poll-suffix`
`Unknown`

If 4.7.2 is old and should be upgraded then the DNS TXT record should return a value of 3 instead of a value of 1.

**Comment by omoerbeek** [comment]
You need to replace `--socket-dir` with the correct location of your control socket. Please also look at your recursor logs, it should show the invocations of `rec_control`, as shown above.
Please share you full config and the locations of your config files and do not paraphrase command output, show the exact command you typed including output. e.g. `rec_control` does not output `Unknown` on an unknown parameter, it says: `xyz not known`.

**Comment by omoerbeek** [comment]
BTW, you are mixing up the commands. `pdns_control show` is for showing metrics, not for showing configuration values. 
Lets solve one issue at the time and concentrate on the recursor for now.

**Comment by omoerbeek** [comment]
This issue is almost certain a support issue. Therefore:

Our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by rsaeks** [comment]
> You need to replace `--socket-dir` with the correct location of your control socket. 

As previously stated, the --socket-dir command was updated with the correct location of the control socket.


> Please also look at your recursor logs, it should show the invocations of `rec_control`, as shown above. 

As previously stated "There don't appear to be any entries related to the security status polling in the log"

> Please share you full config 

allow-from=RemovedForSecurity
api-key=RemovedForSecurity
forward-zones=d35.org=127.0.0.1:5300
forward-zones+=glencoeschools.org=127.0.0.1:5300
forward-zones+=classroom.google.com=127.0.0.1:5300
forward-zones+=encrypted.google.com=127.0.0.1:5300
forward-zones+=glencoecentral.org=127.0.0.1:5300
forward-zones+=glencoesouth.org=127.0.0.1:5300
forward-zones+=glencoewest.org=127.0.0.1:5300
forward-zones+=rpz.zone=127.0.0.1:5300
forward-zones+=www.google.com=127.0.0.1:5300
forward-zones+=swupd.d35.org=127.0.0.1:5300
forward-zones+=32.239.216.in-addr.arpa=127.0.0.1:5300
forward-zones+=40.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=41.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=42.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=43.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=44.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=48.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=51.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=56.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=57.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones+=1.20.172.in-addr.arpa=127.0.0.1:5300
forward-zones+=relay-autodetect.lsfilter.com=127.0.0.1:5300
forward-zones+=mask.icloud.com=127.0.0.1:5300
forward-zones+=mask-h2.icloud.com=127.0.0.1:5300
forward-zones-recurse=.=1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4
local-address=0.0.0.0
logging-facility=1
loglevel=4
setgid=pdns-recursor
setuid=pdns-recursor
webserver=yes
webserver-address=RemovedForSecurity
webserver-allow-from=RemovedForSecurity
webserver-port=RemovedForSecurity

> and the locations of your config files 

`/etc/pdns-recursor/`

> and do not paraphrase command output, show the exact command you typed including output. e.g. `rec_control get-parameter xyz` does not output `Unknown` on an unknown parameter, it says: `xyz not known`.

rec_control get-parameter security-poll-suffix
security-poll-suffix=""

**Comment by omoerbeek** [comment]
to help people finding thsi issue:

The last line reveals that secpoll polling is switched off. Presumably the reporter is running a distro version (which often switch secpolling off) and not something from repo.powerds.com. See https://docs.powerdns.com/recursor/settings.html#security-poll-suffix and https://docs.powerdns.com/recursor/security.html#security-polling

**Comment by rsaeks** [comment]
This is being installed via the epel repo. 

Based on the documentation from https://docs.powerdns.com/recursor/settings.html#security-poll-suffix with the default value being: secpoll.powerdns.com and this setting not modified in the configuration, the behavior should follow what is in the posted documentation of the value being secpoll.powerdns.com rather than ""

This is an inconsistency from documentation to behavior.

**Comment by phonedph1** [comment]
`Software source: PDNS Repositories`

Kind of hard to help at this rate.

**Comment by Habbie** [comment]
> Software source: PDNS Repositories

This is not the EPEL repositories. You led us on a wild goose chase. Please be more careful next time!

**Comment by omoerbeek** [comment]
> This is an inconsistency from documentation to behavior.

Third-party distributions can change defaults and it's their responsibility to document that.
