### ISSUE TITLE
luabackend fails on FreeBSD i386

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#1252]
Will see if I can investigate further with a vmware install of 10.0-RELEASE-i386.

Here is (part) of the log from redports:

	gmake[4]: Entering directory `/work/a/ports/dns/powerdns-devel/work/PowerDNS-pdns-8e1c18b/modules/luabackend'
	  CXX      luabackend.lo
	  CXX      minimal.lo
	  CXX      reload.lo
	  CXX      lua_functions.lo
	  CXX      master.lo
	  CXX      private.lo
	  CXX      slave.lo
	  CXX      supermaster.lo
	  CXX      dnssec.lo
	In file included from lua_functions.cc:20:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from dnssec.cc:19:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from slave.cc:19:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from supermaster.cc:19:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from master.cc:19:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	gmake[4]: *** [slave.lo] Error 1
	gmake[4]: *** Waiting for unfinished jobs....
	gmake[4]: *** [supermaster.lo] Error 1
	gmake[4]: *** [master.lo] Error 1
	gmake[4]: *** [dnssec.lo] Error 1
	lua_functions.cc:289: error: redefinition of 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)'
	lua_functions.cc:241: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)' previously defined here
	In file included from luabackend.cc:18:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from reload.cc:19:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	In file included from minimal.cc:18:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	gmake[4]: *** [luabackend.lo] Error 1
	gmake[4]: *** [lua_functions.lo] Error 1
	gmake[4]: *** [reload.lo] Error 1
	gmake[4]: *** [minimal.lo] Error 1
	In file included from private.cc:18:
	luabackend.hh:161: error: 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, int&)' cannot be overloaded
	luabackend.hh:158: error: with 'bool LUABackend::getValueFromTable(lua_State*, const std::string&, time_t&)'
	gmake[4]: *** [private.lo] Error 1
	gmake[4]: Leaving directory `/work/a/ports/dns/powerdns-devel/work/PowerDNS-pdns-8e1c18b/modules/luabackend'
	gmake[3]: *** [all-recursive] Error 1
	gmake[3]: Leaving directory `/work/a/ports/dns/powerdns-devel/work/PowerDNS-pdns-8e1c18b/modules'
	gmake[2]: *** [all-recursive] Error 1
	gmake[2]: Leaving directory `/work/a/ports/dns/powerdns-devel/work/PowerDNS-pdns-8e1c18b'
	gmake[1]: *** [all] Error 2
	gmake[1]: Leaving directory `/work/a/ports/dns/powerdns-devel/work/PowerDNS-pdns-8e1c18b'
	===> Compilation failed unexpectedly.

**Comment by RvdE** [comment]
pull #1255 updated

**Comment by Habbie** [comment]
#1255 merged
