### ISSUE TITLE
Auth: Generic MySQL backend with incorrectly configured ssl=yes hangs the Auth process

### ISSUE THREAD

**Issue by nvaatstra** [PowerDNS/pdns#12528]
- Program: Authoritative
 - Issue type: Bug report

### Short description
If you configure Auth with  `gmysql-ssl=yes` but your MySQL database does not support SSL, I would expect errors to be logged by Auth and for Auth to either run without the MySQL backend or exit. Currently, it causes Auth to appear to be running and no errors are logged. The logging includes these lines:

```
Feb 10 09:39:26 UDP server bound to 0.0.0.0:5353
Feb 10 09:39:26 TCP server bound to 0.0.0.0:5353
Feb 10 09:39:26 [webserver] Listening for HTTP requests on [::]:8083
```

 However, Auth does not respond to:
- Queries over UDP
- Queries over TCP
- Request made to the webserver

It appears the Auth process is stuck and even after 10+ minutes the Auth logging remains silent.

### Environment

 - Operating system: N/A
 - Software version: 4.7.3
 - Software source: powerdns/pdns-auth-47:4.7.3 at dockerhub

### Steps to reproduce

1. Run MySQL database with no ssl support
2. Run Auth with `gmysql-ssl=yes`
3. Try to access Do53 TCP/UDP and webserver

### Other information
Changing the config to `gmysql-ssl=no` (the correct configuration for this test setup) and restarting Auth leads to a properly functioning Auth. Modifying parameters such as `zone-cache-refresh-interval` & `loglevel` did not lead to a difference in behaviour and/or relevant information being logged.

**Comment by pieterlexis** [comment]
The auth sets `CLIENT_SSL` in the `client_options` when calling `mysql_real_connect`. The [docs](https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-connect.html) tell you not to do this:

> CLIENT_SSL: Use SSL (encrypted protocol). Do not set this option within an application program; it is set internally in the client library. Instead, use [mysql_options()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-options.html) or [mysql_ssl_set()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-ssl-set.html) before calling [mysql_real_connect()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-connect.html).

**Comment by rgacogne** [comment]
I also suspect we might need to set `MYSQL_OPT_CONNECT_TIMEOUT`, which we currently don't use.

**Comment by pieterlexis** [comment]
I have an untested (but compiled) patch here: https://gist.github.com/pieterlexis/ec5a9660119227988778eea14e3e9805

**Comment by Habbie** [comment]
> I also suspect we might need to set `MYSQL_OPT_CONNECT_TIMEOUT`, which we currently don't use.

in my testing, we timeout after 2x10 seconds without it, but I'll add it anyway
