### ISSUE TITLE
dnsdist: Having the ability to add EDNS Extended Errors to responses

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#12572]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
It would be very useful to be able to add EDNS Extended Errors to responses, self-generated or not.
https://github.com/PowerDNS/pdns/pull/7636 implemented a very early draft as an action, which probably makes sense since we can also apply actions to self-generated answers.

**Comment by johnhtodd** [comment]
Just adding a +1 here - we (speaking for Quad9) would be very interested in seeing this able to create synthetic results, as well as pass through EDE from back-end resolvers. Note/ticket for reference from the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1446077&q=ede&can=2
