### ISSUE TITLE
dnsdist: 1.8.0-rc1 (and current git) confused by any binds?

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#12581]
- Program: dnsdist
 - Issue type: Bug report

### Environment
 - Operating system: Debian 
 - Software version:  git current
 - Software source: compiled myself

### Steps to reproduce
```
controlSocket("127.0.0.1:5900")
addLocal("0.0.0.0:53")
addLocal("[::]:53")
newServer({address="9.9.9.9"})
```

```
dig foo @127.0.0.2
```

### Expected behaviour
Response from 127.0.0.2 without error in dig.

### Actual behaviour
```
$ dig foo @127.0.0.2
;; reply from unexpected source: 127.0.0.1#53, expected 127.0.0.2#53
```
```
13:06:34.970669 IP 127.0.0.1.50968 > 127.0.0.2.53: 34634+ [1au] A? foo. (44)
13:06:35.243499 IP 127.0.0.1.53 > 127.0.0.1.50968: 34634$ 0/1/1 (130)
```

### Other information
1.8.0-rc1 on RHEL 7 exhibits the same issue. We've also got responses from v6 addresses (hosted on lo) instead of ::1, and from addresses on eth0 where the query was sent to an address on lo.

**Comment by phonedph1** [comment]
This works at 3372321249830832072f28df23cd75e0cc4d0138, trying to work my way forward to find where it breaks

**Comment by phonedph1** [comment]
Actually even this gets responses from the wrong place,

```
--addLocal("0.0.0.0:53")
--addLocal("[::]:53")
addLocal("127.0.0.1:53")
addLocal("127.0.0.2:53")
```

**Comment by phonedph1** [comment]
Maybe something in #12003?

**Comment by rgacogne** [comment]
I suspect either a problem when we harvest the destination address, or that address not being properly passed around during the processing. I'm on it!

**Comment by rgacogne** [comment]
I have reproduction, and it looks like it doesn't happen on self-generated answers (spoof, cache-hits) so it looks like the address is not properly passed around.
