### ISSUE TITLE
OpenSSL/SHA-related build failure on macOS

### ISSUE THREAD

**Issue by fredmorcos** [PowerDNS/pdns#12583]
Probably unrelated to this PR, but I get this on macOS:

```
In file included from unixconnector.cc:28:
In file included from ./remotebackend.hh:29:
In file included from ../../pdns/dnsbackend.hh:45:
../../pdns/sha.hh:25:10: fatal error: 'openssl/sha.h' file not found
```

Some configure output related to openssl:

```
checking whether compiling and linking against OpenSSL's libcrypto works... yes
checking for RAND_bytes... yes
checking for RAND_pseudo_bytes... yes
checking for CRYPTO_memcmp... yes
checking for OPENSSL_init_crypto... yes
checking for EVP_MD_CTX_new... yes
checking for EVP_MD_CTX_free... yes
checking for RSA_get0_key... yes
checking whether EVP_PKEY_CTX_set1_scrypt_salt is declared... yes
checking for /usr/local/Cellar/openssl@3/3.0.8/include/openssl/ecdsa.h... yes
...
configure: Configured with:  '--with-modules=bind lmdb pipe remote gsqlite3' '--with-lmdb=/usr/local/Cellar/lmdb/0.9.30' 'CFLAGS=' 'LDFLAGS=' 'PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig'
...
configure: OpenSSL ecdsa: yes
```

I disabled the remote backend as a workaround.

_Originally posted by @wojas in https://github.com/PowerDNS/pdns/issues/12546#issuecomment-1434120375_

**Comment by fredmorcos** [comment]
@wojas I can't reproduce this on Linux and I don't see it on any of our CI runs (Linux too).
Could you rebase on the latest master, and if it still persists try to bisect it?

Otherwise I would need more information like the OpenSSL version. It's strange that `openssl/sha.h` cannot be found, it's been in OpenSSL since ages. So either your OpenSSL is built without the SHA API somehow (???), or the paths given by pkg-config are incorrect?

Btw, I have never touched `pdns/sha.hh` in any of my PRs. It seems that @omoerbeek is the last one to make changes to it.

I also noticed a weird behavior with it, in emacs with clangd, the `#if defined(HAVE_EVP_MD_CTX_NEW) && defined(HAVE_EVP_MD_CTX_FREE)` lines are marked out, meaning `HAVE_EVP_MD_CTX_NEW` and `HAVE_EVP_MD_CTX_FREE` are not defined even though I'm building against OpenSSL 3.0 and it's of course complaining about `EVP_MD_CTX_destroy` missing (but not about `EVP_MD_CTX_create`!).

**Comment by omoerbeek** [comment]
I can reproduce on macOS with OpenSSL 3, OpenSSL 1.1 is fine. Probably most effective if I take over.

**Comment by fredmorcos** [comment]
Awesome, thank you @omoerbeek. Let me know if you need anything from me.
