### ISSUE TITLE
pdns 3.3.1 doesn't start when IPv6 is disabled

### ISSUE THREAD

**Issue by gergelyimre** [PowerDNS/pdns#1259]
I'm disabling IPv6 by default on CentOS 6.x machines, I don't currently need it, and I like it disabled. Kernel boot param ipv6.disable=1.

I just installed pdns auth 3.3.1 on a CentOS box with IPv6 disabled and it doesn't start. Error message:

Feb  3 21:02:25 mail pdns[25476]: Exiting because communicator thread died with STL error: Creating local resolver socket for ::, does your OS miss IPv6?: Bad file descriptor

My pdns.conf is pretty basic, no IPv6 stuff in it.

Related to #1258 .

**Comment by Habbie** [comment]
Fixed by merge of #2893
