### ISSUE TITLE
auth LMDB: inconsistent handling of comments in the API

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#12630]
- Program: Authoritative
 - Issue type: Bug report/Convenience enhancement

### Short description
The LMDB backend does not support comments. PUTting data with comments in them, even if it's an empty list, yields an error. GETting data does include an empty list.

We should either not put the empty list in responses, or ignore an empty list on requests, so that PUTting what you GETted (got) works. I'm leaning towards the ignore.

**Comment by zeha** [comment]
ignore (on the backend side?) seems fine.
