### ISSUE TITLE
question about multiple backend

### ISSUE THREAD

**Issue by blissnmx** [PowerDNS/pdns#12644]
Ask a question, for multiple backend configurations, obviously failover is not supported, that is, the powerdns service is still unavailable after the first backend fails
Question 1: What is the correct application scenario for multiple backend configurations?
Question 2: Is there a plan to support failover of multiple backends?

Please help to answer ,thanks.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
