### ISSUE TITLE
auth API: Showing a notice if using "priority"

### ISSUE THREAD

**Issue by Bodenhaltung** [PowerDNS/pdns#12657]
- Program: Authoritative
 - Issue type: Feature request

### Short description
API calls with "priority" ignoring this key, which is correct because the key was removed.

A response with a notice or an error (maybe, could break a lot) if the "priority" key is present would be helpful.

**Comment by Habbie** [comment]
I'll try the error in alpha2, can always undo that before 4.9.0 final. I'm not sure we have a way to do a notice.
