### ISSUE TITLE
Prevent creation of subzones

### ISSUE THREAD

**Issue by Tozzje** [PowerDNS/pdns#1266]
I would like to propose a feature where PowerDNS forbids the creation of subzones. We use PowerDNS with supermaster feature for our hosting servers. Resellers have the ability to add domains as they please, and they can now create subzones in existing zones.

eg. we host our domains on ns1.example.com, a reseller could create a hosting account for ns1.example.com causing ns1.example.com to change IP address. Another example is www records. Customer X could create an account for www.customerY.com, causing www.customerY.com to change IP address.

Ideally PDNS would check if the new zone falls in an already existing zone. If so, the creation of the zone should be denied.

**Comment by Habbie** [comment]
Not going to be a powerdns feature. Contributed triggers welcome.
