### ISSUE TITLE
Pdns-recursor problem

### ISSUE THREAD

**Issue by medina6** [PowerDNS/pdns#12681]
I set up a pdns-recursor on the new server and transferred it from the old server to the new one, changed the IP address of the new one like that of the old server. The syslog gives these errors: msg="Sending SERVFAIL during resolve" error="Too much time waiting for tests1blog.murlali.meet-backup.fsf.org|A, timeouts: 5, throttles: 4, queries: 7, 7676msec" subsystem="syncres" level="0" pr>
: msg="Sending SERVFAIL during resolve" error="Too much time waiting for demo1722.telus-b.meet-backup.fsf.org|A, timeouts: 5, throttles: 4, queries: 6, 7502msec" subsystem=" syncres" level="0" prio>
: msg="Sending SERVFAIL during resolve" error="Too much time waiting for download60.userwww.meet-backup.fsf.org|A, timeouts: 5, throttles: 4, queries: 6, 7502msec" subsystem="syncres" level="0" pr> only such errors

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

(note that the `fsf.org` name servers are down, and it looks your logs indicate somebody is actively attacking them through your recursor. I suggest you identify and block the offending users on all your resolvers.)
