### ISSUE TITLE
Update primary server details in consumer-driven secondary 'content' zones

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#12714]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Updates to primary server address and/or port in catalog zone on secondary server could/should update same information in secondary zones.

### Usecase
1. On a primary server, create a producer zone, some primary zones, and put those primary zones into the catalog zone.
2. On a secondary server, create a consumer zone, with the address/port of the primary server.
3. Ensure that NOTIFY+AXFR are used for replication between the servers.
4. Wait for the secondary server to create secondary zones for the zones in the catalog.
5. Change the IP address or port number of the primary server.
6. On the secondary server, make the corresponding change in the consumer zone (ONLY in the consumer zone).
7. Make a change in the contents of one of the primary zones on the primary server.
8. Watch as the secondary server attempts to AXFR the zone after receiving a NOTIFY but fails because the content zone (unlike the catalog zone) still has the old address/port for the primary server.

### Description
Provide an opt-in configuration mechanism to have changes in the primary server details, when applied to a catalog zone, automatically applied to all content zones which are 'owned' by that catalog zone. Discuss whether this should be the default :-)

**Comment by mind04** [comment]
Step 6.5 is missing, fetch the catalog.

**Comment by kpfleming** [comment]
Thanks, that's good to know. This could be just a small change in pdnsutil then, causing it to automatically fetch the catalog zone if certain details of the consumer zone are changed.

**Comment by kpfleming** [comment]
Ahh. So then this ends up being a 'docs' issue... I'll put together a PR for the 'catalog zones' section of the docs.
