### ISSUE TITLE
rec: NOD/UDR removed from Debian/Ubuntu packages

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#12715]
- Program: Recursor
 - Issue type: Bug report

### Short description
I just upgraded from `4.9.0~alpha0+master.1173.gddb2c379c-1pdns.focal` to `4.9.0~alpha0+master.1198.g14372b052-1pdns.focal`. Aside from the expected changes, all of the `new-domain-*` and `unique-domain-*` settings disappeared from the default `recursor.conf`. Did those features get disabled? Was that supposed to happen?

If this was unintended, it's probably fallout from #10072, but I don't know.

(I do not use those features, so it doesn't matter to me, but still.)

### Environment
 - Operating system: Ubuntu 20.04 amd64
 - Software version: `4.9.0~alpha0+master.1198.g14372b052-1pdns.focal`
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install Recursor
2. `sudo grep new-domain /etc/powerdns/recursor.conf`
3. `sudo grep unique-domain /etc/powerdns/recursor.conf`

### Expected behaviour
NOD and UDR settings.

### Actual behaviour
Not that.

### Other information
Not a Debian packaging expert, but f1766172de104560fc4676ace93682dd1af1dabd appears to make a lot of boilerplate changes. However, it does change:

```
-# Only disable luajit on arm64
-ifneq ($(DEB_HOST_ARCH),arm64)
-CONFIGURE_ARGS += --with-lua=luajit
-else
-CONFIGURE_ARGS += --with-lua=lua5.3
-endif
```

to

```
+               --with-lua \
```

Maybe Lua isn't being detected properly?

**Comment by mnordhoff** [comment]
The build log for https://builder.powerdns.com/#/builders/97/builds/2839 shows:

```
configure: Features enabled
configure: ----------------
configure: Lua: luajit
configure: OpenSSL ECDSA: yes
configure: ed25519: yes
configure: ed448: yes
configure: Protobuf: yes
configure: SNMP: yes
configure: systemd: yes
configure: nod: yes
configure: dnstap: yes
configure: DNS over TLS: yes
configure: OpenSSL: yes
configure: libcurl: yes
configure: Context library: Boost Context
```

https://builder.powerdns.com/#/builders/97/builds/2844 shows:

```
#31 133.8 configure: Features enabled
#31 133.8 configure: ----------------
#31 133.8 configure: Lua: luajit
#31 133.8 configure: OpenSSL ECDSA: yes
#31 133.8 configure: ed25519: yes
#31 133.8 configure: ed448: yes
#31 133.8 configure: Protobuf: yes
#31 133.8 configure: SNMP: yes
#31 133.8 configure: systemd: yes
#31 133.8 configure: nod: no
#31 133.8 configure: dnstap: yes
#31 133.8 configure: DNS over TLS: yes
#31 133.8 configure: OpenSSL: yes
#31 133.8 configure: libcurl: yes
#31 133.8 configure: Context library: Boost Context
```

I don't know why, though...

**Comment by dwfreed** [comment]
NOD depends on boost-filesystem; #10072 switched from using libboost-all-dev to using specific -dev packages, and didn't include boost-filesystem.

**Comment by mnordhoff** [comment]
I just checked the build logs for Debian Buster and Ubuntu Jammy and it affects them too.
