### ISSUE TITLE
dnsdist: high CPU usage (150-200%) when gateway/routes disappear since 1.8.0

### ISSUE THREAD

**Issue by hhoffstaette** [PowerDNS/pdns#12711]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Since dnsdist-1.8.0 there seems to be a change in behaviour in case of a router disconnect/IPv6 prefix change. I run dnsdist as proxy/cache for external DNS servers (at my ISP and others), with a mix of IPv4 and IPv6 servers. Unlike the v4 servers, the v6 servers are broken when my DSL line disconnects & I receive a new prefix (typically in the middle of the night), so an elaborate monitoring script detects this and properly restarts v6-related services when the new prefix is available. This has been working fine for a while, and still does.
However, I noticed that 1.8.0 seems to **really** dislike the change in routing, and at least two threads (probably UDP request sender & availability checker?) start spinning like crazy - see the attached image. This definitely wasn't the case with 1.7.x.

### Environment
 - Operating system: Linux, kernel 6.2.x
 - Software version: 1.8.0
 - Software source: self-compiled package

### Steps to reproduce
1. run dnsdist
2. remove route to upstream server / power-cycle router

### Expected behaviour
Changed IP addresses shouldn't make threads go crazy.

### Actual behaviour
![dnsdist-cpu](https://user-images.githubusercontent.com/499973/229301400-595effc1-9480-42dd-ac87-719bb6376a0d.png)
As you can see the DSL line went down at ~3:26 and dnsdist went into overdrive. DSL reconnection takes a while and my IPv6-prefix-detector only runs every 5 minutes, but eventually it restarts dnsdist and things are back to normal.

### Other information
I understand that detecting topology changes was discussed in the past (e.g. via netlink) and that it would be quite a bit of work; however threads burning CPU seems like an avoidable problem.

**Comment by zeha** [comment]
I've seen a similar cpu hog the other day - didn't have time to repro it yet.

**Comment by rgacogne** [comment]
I wonder if this is caused by https://github.com/PowerDNS/pdns/pull/11830

Le 1 avril 2023 21:21:39 UTC, Chris Hofstaedtler ***@***.***> a écrit :

**Comment by hhoffstaette** [comment]
Last night I had another reconnect and this time I didn't get the spike - _obviously_, since I created this ticket. :zany_face: 
Only changes were:
- I previously had setUDPMultipleMessagesVectorSize(8) enabled, though I'm not sure how that would matter
- the reconnect was rather quick this time

:shrug:

**Comment by omoerbeek** [comment]
If it happens again, try to run `strace` on the process, that will very likely shed some light on the root cause.

**Comment by hhoffstaette** [comment]
> If it happens again, try to run `strace` on the process, that will very likely shed some light on the root cause.

Rebuilt without LTO/stripping, pulled my DSL line out of the router and voila: 200% CPU time (so it wasn't due to recmmsg, as expected):
```
$strace -f -p $(cat /run/dnsdist/dnsdist.pid)
...
[pid  9744] <... recvfrom resumed>0x7f074c000b70, 4096, 0, NULL, NULL) = -1 EBADF (Bad file descriptor)
[pid  9743] <... recvfrom resumed>0x7f0744000b70, 4096, 0, NULL, NULL) = -1 EBADF (Bad file descriptor)
[pid  9744] recvfrom(-1,  <unfinished ...>
[pid  9743] recvfrom(-1,  <unfinished ...>
[pid  9744] <... recvfrom resumed>0x7f074c000b70, 4096, 0, NULL, NULL) = -1 EBADF (Bad file descriptor)
[pid  9743] <... recvfrom resumed>0x7f0744000b70, 4096, 0, NULL, NULL) = -1 EBADF (Bad file descriptor)
[pid  9744] recvfrom(-1,  <unfinished ...>
[pid  9743] recvfrom(-1,  <unfinished ...>
...
```
![perf-top](https://user-images.githubusercontent.com/499973/229366461-5b7ee58e-72d6-474b-af63-e1ba2fadcba7.png)

I hope this helps.

**Comment by rgacogne** [comment]
Thanks, that's very helpful!

It looks like two UDP responder threads, processing UDP responses from backends, are busy looping asking the kernel to get a UDP datagram on an invalid (-1) socket descriptor.

Le 2 avril 2023 16:40:02 UTC, "Holger Hoffstätte" ***@***.***> a écrit :

**Comment by rgacogne** [comment]
I can reproduce the issue by manually removing the default IPv6 route on my system. https://github.com/PowerDNS/pdns/pull/12726 should fix it.
