### ISSUE TITLE
dnsdist: class StatNode metrics are not accessible out-of-the-box from DynBlockRulesGroup:setSuffixMatchRuleFFI() visitor function

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#12724]
- Program:  dnsdist 
 - Issue type: Code and/or  documentation improvement 

### Short description

The [`class StatNode`](https://dnsdist.org/reference/config.html?highlight=statnode#StatNode) metrics are not accessible from the [`DynBlockRulesGroup:setSuffixMatchRuleFFI()`](https://dnsdist.org/reference/config.html?highlight=statnode#DynBlockRulesGroup:setSuffixMatchRuleFFI) `visitor` function out of the box. And they are not documented.

### Steps to reproduce
The dynamic block rule [`:setSuffixMatchRuleFFI()`](https://dnsdist.org/reference/config.html?highlight=setsuffixmatchruleffi#DynBlockRulesGroup:setSuffixMatchRuleFFI) of the [DynBlockRulesGroup](https://dnsdist.org/reference/config.html?highlight=statnode#DynBlockRulesGroup) object calls the `visitor` function. The function receives a `StatNode` object representing the stats of the nodes.

But it is not possible to access these metrics out of the box like with the [`:setSuffixMatchRule()`](https://dnsdist.org/reference/config.html?highlight=setsuffixmatchrule#DynBlockRulesGroup:setSuffixMatchRule) variant. 

It is possible to access them in a complicated way. The functions are defined in the [dnsdist-lua-inspection-ffi.hh](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh#L26-L46) file. One have to define them again within the Lua file:
```
ffi.cdef[[
 ...
]]
```
Then you can use them with the `statNode` argument.

But not only that. The return value of the functions is sometimes not Lua compatible and must be converted.

### Expected behaviour

Straight and documented way to access the metric values from the ring buffer nodes within the visitor function.

### Actual behaviour

is very complicated.

**Comment by rgacogne** [comment]
We clearly need to document these functions indeed. Unfortunately I don't think we can make them easier to use, this is a drawback of the Lua FFI interface which is much, much faster but also feels like writing C, because it does actually pretty much call C functions with a very thin layer to interact with the "regular" Lua code.

**Comment by paddg** [comment]
Ok, understood. Maybe one thing, I have to (re)define the functions, which are already defined in  [dnsdist-lua-inspection-ffi.hh](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh#L26-L46) to access the ringbuffer metrics within the visitor function in order to use them:

```c
local ffi = require("ffi")
-- copied from dnsdist-lua-inspection-ffi.hh
ffi.cdef[[
  typedef struct dnsdist_ffi_stat_node_t dnsdist_ffi_stat_node_t;

  uint64_t dnsdist_ffi_stat_node_get_queries_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_noerrors_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_nxdomains_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_servfails_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_drops_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_bytes(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_hits(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  unsigned int dnsdist_ffi_stat_node_get_labels_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  void dnsdist_ffi_stat_node_get_full_name_raw(const dnsdist_ffi_stat_node_t* node, const char** name, size_t* nameSize) __attribute__ ((visibility ("default")));

  unsigned int dnsdist_ffi_stat_node_get_children_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));

  uint64_t dnsdist_ffi_stat_node_get_children_queries_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_noerrors_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_nxdomains_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_servfails_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_drops_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_bytes_count(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));
  uint64_t dnsdist_ffi_stat_node_get_children_hits(const dnsdist_ffi_stat_node_t* node) __attribute__ ((visibility ("default")));

  void dnsdist_ffi_state_node_set_reason(dnsdist_ffi_stat_node_t* node, const char* reason, size_t reasonSize) __attribute__ ((visibility ("default")));
]]
```
Is there no way to avoid this?

**Comment by rgacogne** [comment]
> This is kind of possibly dangerous code redundancy. Is there no way to avoid this?

There definitely is, we can automatically export these definitions into the Lua environment like we do for other FFI definitions.

Thinking about this a bit more, I wonder if we could write a pure Lua wrapper around these functions to provide a better interface. It might take some time but I'll look into what can be done.

**Comment by rgacogne** [comment]
I'm closing this the automatic export of these definitions has been implemented in https://github.com/PowerDNS/pdns/pull/12923.
The better interface via a pure Lua wrapper will likely be shared with our customers only, at least in the beginning.
