### ISSUE TITLE
Primary operation with IPv6

### ISSUE THREAD

**Issue by fansari** [PowerDNS/pdns#12736]
- Program: pdns server
 - Issue type: Bug report

### Short description

I want to run the internal communication between master and slave in a primary operation scenario run with IPv6 (MySQL backend).

### Environment

 - Operating system: CentOS Stream 9 (x86_64)
 - Software version: 4.7.3
 - Software source:  http://repo.powerdns.com/el/$basearch/$releasever/auth-47
 
### Steps to reproduce

1. on master: configure "allow-axfr-ips" and "also-notify" to IPv6 of slave in /etc/pdns/pdns.conf
2. on slave: configure "allow-axfr-ips", "allow-dns-update-from" and "allow-notify-from" with IPv6 of master
3. on slave: set ip in table "supermasters" of powerdns database to IPv6 of master
4. on slave: set "master" from your test domain  (or "primary" in GUI) to IPv6 of master
5. add or remove a record of your test domain on the master and check whether the slave is updated

### Expected behaviour

The slave should be accesses with its IPv6 address and updated.

### Actual behaviour

This does not work. For some reason the master is always trying to notify the IPv4 of the SOA.
But: when I try a retrieve (AXFR, either by GUI or with pdns_control) it works.

**Comment by Habbie** [comment]
Can you please paste:

* your full configs (unedited except for passwords)
* startup logs
* logs that show the issue

**Comment by fansari** [comment]
Meanwhile I could figure out the cause of the issue. The firewall rules did not allow to pass UDP traffic for port 53 (both directions) between master and slave. After I have fixed this the slave receives the zone update automatically.

In order to enforce IPv6 I have set "only-notify=::/0" in pdns.conf.
