### ISSUE TITLE
Unintuitive error messages

### ISSUE THREAD

**Issue by s---p** [PowerDNS/pdns#1275]
Error messages specific to executed queries are quite uninformative where they came from:

```
Feb  6 18:18:42 cs01 pdns[9215]: Unable to parse record during incoming AXFR of '10.in-addr.arpa' (std::exception): boost::too_few_args: format-string referred to more arguments than were passed

Feb  6 18:14:15 cs01 pdns[6487]: Unable to AXFR zone '10.in-addr.arpa' from remote '10.x.x.x' (AhuException): GSQLBackend unable to feed record: Failed to execute mysql_query, perhaps connection died? Err=1: The target table records of the INSERT is not insertable-into
```

Please provide additional logging info; e.g. when some try{}/query throws an error, include the name of the erroneous query.

Vesion: pdns 3.3.1
Source: static build from powerdns.com
Backends: mysql-dnssec

**Comment by pieterlexis** [comment]
I think many error messages were fixed in the 3.3 - 4.0 time frame. Please open a new issue if you discover these issues in 4.X.
