### ISSUE TITLE
gmysql backend isnt safe for use on clustered db's

### ISSUE THREAD

**Issue by ITJamie** [PowerDNS/pdns#12760]
- Program: Authoritative
 - Issue type: Bug report

### Short description
issue with gmysql failing to find domain after adding to db. using a clustered db (galera + proxysql frontend).
We believe that the domain insert transaction hasnt synced to all nodes in the galera/mysql server, then it attempts (and fails) to find that domain record, the domain is left in a bad state in the db as it never makes the SOA. 
the domain will exist in the domains table but it will not have created an SOA record related to it

### Environment

 - Operating system: almalinux 8.6
 - Software version: 4.7.3
 - Software source: PowerDNS repository

### Steps to reproduce

1. setup mariadb with galera and front with proxysql
2. route all write requests to a specific set of galera hosts, route all read requests across the full cluster
3. attempt to create a zone with the api, sometimes it will fail (it may take many attempts to hit this bug)

### Expected behaviour
zone to be created with an soa record

### Actual behaviour
domain gets created in domains table but no soa record is added to the records table

### Other information
logs from an example failure:
```
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03 Request details:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03  POST params:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   {"name":"example_domain.com.","kind":"MASTER","nameservers":[]}:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03  Headers:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   accept: */*
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   content-length: 54
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   content-type: application/x-www-form-urlencoded
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   host: <redacted>:8081
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   x-api-key: <redacted>
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03  Full body:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   {"name":"example_domain.com.","kind":"MASTER","nameservers":[]}
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03 Handling request "/api/v1/servers/localhost/zones"
Apr 18 09:34:46 ns1 pdns_server[1222321]: gmysql Connection successful. Connected to database 'powerdns_prod' on '<redacted>'.
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: select id,name,master,last_check,notified_serial,type,options,catalog,account from domains where name=?
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: 1086 usec to execute
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: 1125 total usec to last row
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937218896: insert into domains (type,name,master,account,last_check,notified_serial) values(?,?,?,?,NULL,NULL)
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937218896: 2788 usec to execute
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: select id,name,master,last_check,notified_serial,type,options,catalog,account from domains where name=?
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139633144939552: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139633144939552: 1239 usec to execute
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: 1891 usec to execute
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139631937447552: 1918 total usec to last row
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139633144939552: 1359 total usec to last row
Apr 18 09:34:46 ns1 pdns_server[1222321]: Query 139633144949072: select kind,content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=?
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03 Result for "/api/v1/servers/localhost/zones": 422, body length: 76
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03 Response details:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03  Headers:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   access-control-allow-origin: *
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   Connection: close
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   Content-Length: 76
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   Content-Type: application/json
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   X-Content-Type-Options: nosniff
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   X-Frame-Options: deny
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   X-Permitted-Cross-Domain-Policies: none
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   X-XSS-Protection: 1; mode=block
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03  Full body:
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03   {"error": "Creating domain 'example_domain.com.' failed: lookup of domain ID failed"}
Apr 18 09:34:46 ns1 pdns_server[1222321]: [webserver] c3693b15-1d0b-44f4-b053-bdf643774b03 <redacted>:39266 "POST /api/v1/servers/localhost/zones HTTP/1.1" 422 425
```

We see two options for solving this (inside powerdns, we could write a rule in proxysql to route all read requests from powerdns to a specific galera node, but that would remove the point of proxysql for load balancing across the mysql cluster)
 - re-attempt checking for the domain (get-all-domain-metadata-query)  after failure, maybe with a small time backoff
 - adjust the domain insert query (insert-zone-query) to return the id of the inserted object, that way the id is known and removes the need to run the (get-all-domain-metadata-query) query to get the id which is used for adding related records
 
 We are seeing this happen about once a day across a few hundred zone inserts a day
 
 some db data
 domains: `SELECT * FROM powerdns_prod.domains where name = <redacted>;`
 ```
 id,name,master,last_check,type,notified_serial,account,options,catalog
6851,<redacted>,,NULL,MASTER,NULL,,NULL,NULL
```

records: `SELECT * FROM powerdns_prod.records where domain_id = 6851;`
```
id,domain_id,name,type,content,ttl,prio,disabled,ordername,auth

```

**Comment by zeha** [comment]
`get-all-domain-metadata-query` is not used to read the domain ID. Its used to read the metadata table.

**Comment by ITJamie** [comment]
apologies, i should have mentioned `info-zone-query` i believe. i believe its the query ran after a zone is created?

**Comment by zeha** [comment]
> apologies, i should have mentioned `info-zone-query` i believe. i believe its the query ran after a zone is created?

a lot of queries run after the transaction creating the zone, and they often do not use the domain.id as a lookup key. If a database indicates a successful COMMIT, it makes some durability guarantees. gsqlbackend and pdns core rely on these guarantees.

Creating a record in one TX, committing, and then not being able to find that record by name very much violates all assumptions about durability.

**Comment by zeha** [comment]
Just to make sure everyone's on the same page, today, creating a domain works like this:

- make a new UeberBackend
- use the UeberBackend to find a real backend willing to create a domain "row", and actually create that domain row (in an implicit transaction)
- use the UeberBackend to 1) read the domain row including the domain id, and 2) get a handle to the real backend
- start a backend transaction (translates into a real sql transaction) for the zonename and domain.id(!), fill the zone records, set metadata, etc, commit
- use the UeberBackend to read various domain settings and return them to the client

Changing that means doing work on long-standing items on the internal (core<>backend) API wishlist.

**Comment by XANi** [comment]
That's a Galera thing I'm afraid. I had it throw locking errors on absolutely simple, un-blockable (under single node mysql) queries.

We have admin panel connected to master + DNS servers being slaves and that works very well

**Comment by Bodenhaltung** [comment]
> unfortunately in the world of clustering, there can be delays, Ironically i think pdns being as fast as it is means it can get a select query in before the rest of the cluster has synced, since we only see this once every day or so its very much an unlucky timing situation.

This is not how Galera works, there is no such thing like "seconds behind master".
Galera is a fast as the slowest node [1].

And especially with Transactions:

> Transactions are either applied to every node or not at all. [2]

Is your ProxySQL maybe using caching?

Or do you have some transactions Errors in MySQL (`SHOW ENGINE innoDB STATUS`)?

From my expierience (and opinion) it is a good Idea, even it is a Multimaster Cluster, to only use one Node for Writes, via ProxySQL or HA Proxy etc. and the other Members as "Backup".
If you need to split you should split by the reading Queries across the other Node(s).

How many QPS in MySQL do you have?
And how many are Writes or Reads? I assume you have over 90% of Reads? 

[1] https://galeracluster.com/library/kb/detecting-slow-node.html
[2] https://galeracluster.com/library/faq.html

**Comment by XANi** [comment]
Could be just pdns caching negative requests.

**Comment by technischeHilfskraft** [comment]
We had the same problem. 
The ProxySQL configuration distinguishes between read and write access. This can lead to error 422 if the SOA record has not yet been committed by Galera.
The solution is to configure ProxySQL for failover. All requests are directed to a node in the Galera cluster; if that node is unavailable, the next node is used.
