### ISSUE TITLE
[powerdn-recursor]: dq:setRecords({}) called in postresolve() won't remove cname records

### ISSUE THREAD

**Issue by guicailiao** [PowerDNS/pdns#12774]
- Program: Recursor
 - Issue type: Bug report

### Short description
After adding postresolve() script which changes to return single A record, it still returns the original records plus the newly added A record. If no cname is added for qname, it works well. 

### Environment

 - Operating system: ubuntu 18.04
 - Software version:   4.8.4-1pdns.bionic
 - Software source:  PowerDNS repository

### Steps to reproduce
1.  Add the below script to a file and assigned it to  `lua-dns-script`  in `etc/powerdns/recursor.conf`
```
      function ip_str_to_int(str)
        local o1,o2,o3,o4 = str:match("(%d%d?%d?)%.(%d%d?%d?)%.(%d%d?%d?)%.(%d%d?%d?)")
        return 2^24*o1 + 2^16*o2 + 2^8*o3 + o4
      end

      function postresolve(dq)
        qnameString = dq.qname:toString()
        pdnslog("qnameString: " ..qnameString)
        if qnameString:match("google[.]com[.]?$") then
          -- Get all A records
          local records = dq:getRecords()
          local all_a_records = {}
          for k,v in pairs(records) do
            if v.type == pdns.A then
              table.insert(all_a_records, v:getContent())
            end
          end
          -- Sort A records and find the A records to return
          table.sort(all_a_records)
          local index = ip_str_to_int(dq.remoteaddr:toString())%table.getn(all_a_records)
          local a_record_to_return = all_a_records[index+1]
          dq:setRecords({})
          dq:addAnswer(pdns.A, a_record_to_return, 1)
          return true
        end
        return false
      end
```

2. Add rpz file with below record.
you can add below rpz config to rpz file, and then add lua script to load it.

content in db.rpz
```
$TTL  600
@  IN  SOA  localhost. root.localhost. (
      1682672748  ; Serial
      604800     ; Refresh
        86400    ; Retry
      2419200    ; Expire
      604800 )   ; Negative Cache TTL
;
@  IN  NS  localhost.
@  IN  A  127.0.0.1
@  IN  AAAA  ::1

single.google.com           IN  CNAME   google.com
```

content in recursor.lua
```
rpzFile("/etc/powerdns/db.rpz")
```

config in recursor.conf
```
lua-config-file=/etc/powerdns/recursor.lua
```

### Expected behaviour
`dig single.google.com @127.0.0.1` should also return single A record

### Actual behaviour

```
guicai@sh-pdns-recursor-dev-001:~$ dig single.google.com @127.0.0.1

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> single.google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63707
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;single.google.com.		IN	A

;; ANSWER SECTION:
single.google.com.	600	IN	CNAME	google.com.
google.com.		166	IN	A	108.177.97.100
google.com.		166	IN	A	108.177.97.113
google.com.		166	IN	A	108.177.97.102
google.com.		166	IN	A	108.177.97.139
google.com.		166	IN	A	108.177.97.138
google.com.		166	IN	A	108.177.97.101
single.google.com.	1	IN	A	108.177.97.139

;; Query time: 44 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 28 09:10:42 UTC 2023
;; MSG SIZE  rcvd: 172

guicai@sh-pdns-recursor-dev-001:~$ dig google.com @127.0.0.1

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43235
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		1	IN	A	108.177.97.139

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Apr 28 09:10:48 UTC 2023
;; MSG SIZE  rcvd: 55
```
### Other information
I tried using `function postresolve_ffi(handle)` with `ffi.C.pdns_postresolve_ffi_handle_clear_records(handle)` and `ffi.C.pdns_postresolve_ffi_handle_add_record()`. It has the same issue.

**Comment by omoerbeek** [comment]
This might be an unexpected interaction of RPZ with Lua.  Will look into this soon.

Wondering if setting `dq.appliedPolicy.policyKind = pdns.policykinds.NoAction` makes a difference.

On a side note: doing regex matching on names is not very efficient. Consider using a https://docs.powerdns.com/recursor/lua-scripting/dnsname.html#dns-suffix-match-group
Also: it is probably easier to do `records = getRecords()`; filter out the records you do not want and then call `setRecords(records)`.

**Comment by omoerbeek** [comment]
Setting `dq.appliedPolicy.policyKind = pdns.policykinds.NoAction` does indeed seem to have the right effect.
This is because custom RPZ containing CNAME records get special treatment *after* postresolve. The `NoAction` assignment prevents that.

I do wonder what you are trying to achieve though by this Lua code. The recursor already shuffles the records, so if a client picks the first they will not all use the same A. (Queries getting a hit from the packet cache will get the same order as other recent queries,  I would not worry though, as these answers typically have a relative short TTL).

If really needed setting `dq.variable` can be used to avoid putting the results into the packet cache. Each client query will then get a different order of A records. Killing the packet cache is generally not good for performance, though.

Anyway, this seems  to be more of a support issue than a bug. So I'm closing this with the following standard message:

```
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
```

**Comment by guicailiao** [comment]
Thanks, omoerbeek

Thanks for your debugging and suggestions.  I was trying to make the client always get the same IP for docker tool, which requires hitting the same target(docker tool pulling images from docker registry). 

I will try `dq.appliedPolicy.policyKind = pdns.policykinds.NoAction`

**Comment by guicailiao** [comment]
Thanks omoerbeek again for your help.

After adding `dq.appliedPolicy.policyKind = pdns.policykinds.NoAction`,  works as expected.
