### ISSUE TITLE
rec-main.cc: Remove NOLINT(readability-function-cognitive-complexity) 

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#12791]
PR #12790 actually fixes the high complexity warnings locally, but currently our CI uses clang-12 which does not understand `readability-function-cognitive-complexity.IgnoreMacros`, so the complexity of functions using `SLOG` is higher in CI.

This issue is a reminder to remove the markers in `rec-main.cc` once our CI gets smarter (uses clang >= 13).

**Comment by Habbie** [comment]
we have 13 now except in the coverity scan

**Comment by Habbie** [comment]
@omoerbeek this looks fixed, agree?

**Comment by omoerbeek** [comment]
yes.
