### ISSUE TITLE
dnsdist: SpoofAction hardcodes qclass IN, should copy the qclass from the query

### ISSUE THREAD

**Issue by christofchen** [PowerDNS/pdns#12801]
- Program: dnsdist
 - Issue type: Feature request (maybe a bug...)

### Short description

When spoofing a record intended for another qClass, the response is sent with qClass IN. dig complains about a malformed response then.

` addAction(AndRule{makeRule("lb.id"), QTypeRule(DNSQType.TXT), QClassRule(DNSClass.CHAOS)}, SpoofRawAction("\017dns-test-cc-pa3-1",{ttl=0}))`

### Usecase

In a anycast setup, i would like to learn the hostname of the dnsdist instance reached. So i try to spoof a TXT record "lb.id" with the name of the loadbalancer in the class CHAOS. 

### Description

I am not sure if there is worth to make the class in the response configurable. So i propose to copy the class from the request packet, instead of initializing the response with "IN". 

If this feature/bugfix is ok from a design perspective, i can try to send a pull request later.

**Comment by rgacogne** [comment]
Hi! Thanks for reporting this! We tend to assume that the class is `IN` in too many places, I'm afraid :-/
I agree it would make sense to copy the class of the query for the spoofed records, yes. I cannot think, from the top of my mind, of a case where we would want to generate a record for a different class than the one of the incoming query.
