### ISSUE TITLE
mysql backend: add on option to set wait_timeout

### ISSUE THREAD

**Issue by clementmoulin** [PowerDNS/pdns#12817]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Add an option to mySQL backend to enable powerdns to send:
`SET SESSION wait_timeout = X;`
when connecting to mySQL.

### Usecase
Certain servers are configured with a default wait_timeout set to a low value to avoid connection saturation. For instance, our mySQL is configured with a wait_timeout of 60 seconds since it's mostly used for website purposes, and 60 seconds is considered sufficient. However, PowerDNS requires indefinite connection retention, and unfortunately, it's not possible to configure the wait_timeout default for a specific user in mySQL.

**Comment by Habbie** [comment]
Can you see if `gmysql-group` is a suitable workaround for you?

**Comment by clementmoulin** [comment]
I'm not familiar with mysql "group" connection.
https://dev.mysql.com/doc/refman/8.0/en/resource-groups.html is the related documentation right ?
If I'm right, I don't see any option to change `wait_timeout` for a specific group, only ressources limitations.

**Comment by Habbie** [comment]
ah, no, that's the wrong page. groups are explained here: https://dev.mysql.com/doc/refman/8.0/en/option-files.html

**Comment by clementmoulin** [comment]
OK. I made some tests, and I haven't been able to setup a different `wait_timeout` for group, since `wait_timeout` is a server system variable and can only by defined in `[mysqld]` section.

**Comment by Habbie** [comment]
Ok, it looks like indeed this cannot be set via my.cnf. I'm thinking about adding a feature similar to `mysql --init-command=...`, how does that sound?

**Comment by Habbie** [comment]
> PowerDNS requires indefinite connection retention

by the way, what makes you say this?

**Comment by isotopp** [comment]
If you really want "indefinite connections", you could run an idle query (`select 1`) every x seconds.

You can also detect disconnect, reconnect as needed and not keep a connection open all the time.

**Comment by clementmoulin** [comment]
> > PowerDNS requires indefinite connection retention
> 
> by the way, what makes you say this?

"requires" is not really adequates here. It reconnects automatically hopefully :)
It's just that currently I can see every minute "force" disconnections for powerdns in mysqld.log :)

**Comment by isotopp** [comment]
You can set a global `wait_timeout` if the messages bother you, if you have adequate permissions. The default is 28800 seconds, 8 hours. 

**If the value has been changed on your database server instance, this has probably been done for a reason, and you should be talking to the person who made the change and ask.**

```
mysql [localhost:8033] {msandbox} ((none)) > select @@global.wait_timeout;
+-----------------------+
| @@global.wait_timeout |
+-----------------------+
|                 28800 |
+-----------------------+
1 row in set (0.00 sec)

mysql [localhost:8033] {msandbox} ((none)) > set @@global.wait_timeout = 86400;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8033] {msandbox} ((none)) > select @@global.wait_timeout;
+-----------------------+
| @@global.wait_timeout |
+-----------------------+
|                 86400 |
+-----------------------+
1 row in set (0.00 sec)
```

Setting a global server variable as shown will affect all subsequent connections, as session version of this variable is inherited by the global value on connect. This change will be kept until the server restarts.

MySQL 8 also allows you to change the value permanently, using `SET PERSIST`, documented [here](https://dev.mysql.com/doc/refman/8.0/en/persisted-system-variables.html) and [here](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-persisted-variables-table.html).

```
mysql [localhost:8033] {msandbox} ((none)) > set persist wait_timeout = 86400;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8033] {msandbox} ((none)) > select * from performance_schema.persisted_variables;
+---------------+----------------+
| VARIABLE_NAME | VARIABLE_VALUE |
+---------------+----------------+
| wait_timeout  | 86400          |
+---------------+----------------+
1 row in set (0.01 sec)
```

Note that the interactive client I am using here is not using `wait_timeout`, but `interactive_timeout`, because it sets ` CLIENT_INTERACTIVE` in its call to `mysql_real_connect()`. So I cannot `select @@session.wait_timeout` with the command line client and get reasonable results.

But I can

```python
(venv) kris@server:~/sandboxes/msb_8_0_33$ ./stop
(venv) kris@server:~/sandboxes/msb_8_0_33$ ./start
(venv) kris@server:~/sandboxes/msb_8_0_33$ cat testing.py
#! /usr/bin/env python

import MySQLdb

db_config = dict(
        host = "127.0.0.1",
        port=8033,
        user="msandbox",
        passwd="msandbox",
        db="kris",
)

db = MySQLdb.connect(**db_config)
c = db.cursor()

sql = "select @@session.wait_timeout as s"
c.execute(sql)
rows=c.fetchall()
for row in rows:
    print(f"{row=}")
(venv) kris@server:~/sandboxes/msb_8_0_33$ ./testing.py
row=(86400,)
```

and demonstrate that things do indeed work across server restarts.

**Comment by mind04** [comment]
> Ok, it looks like indeed this cannot be set via my.cnf. I'm thinking about adding a feature similar to `mysql --init-command=...`, how does that sound?

init-command is allowed in my.cnf so I see no need for such an option

```
[pdns]
init-command='set session wait_timeout = 1234'
```
in .my.cnf and
```
gmysql-group=pdns
```
in your config does the job

**Comment by Habbie** [comment]
ah! well spotted. I hope that doesn't overwrite our `mysql_options(&d_db, MYSQL_INIT_COMMAND, "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED");`


@clementmoulin can you try the `init-command` suggestion in `my.cnf`?

**Comment by Habbie** [comment]
closing this as, as far as I can see, there is no work to be done here

**Comment by clementmoulin** [comment]
Sorry for my (very) late feedback: it works with the group option

For other users, please note that you should update my.cnf on client side (host running powerdns) and not server side !
