### ISSUE TITLE
dnsdist: security check fails

### ISSUE THREAD

**Issue by networkmaster** [PowerDNS/pdns#12843]
* Program: DNSDist
* Issue type: bug 

Short Description: 
The installed version of DNSDIst from the ubuntu repo fails because of the string used for the check

Usecase:
Out of the box install of the program and alerting to future upgrades

Description: 
On a new install of DNSDist, the metrics page is showing a "0" result for the security check and the following is shown in the log
May 17 04:28:43 dnsdist1-1 dnsdist[88331]: Error while retrieving the security update for version dnsdist-1.6.1-1build1.Ubuntu: Unable to get a valid Security Status update
May 17 04:28:43 dnsdist1-1 dnsdist[88331]: Not validating response for security status update, this is a non-release version.

root@dnsdist1-1:/var/log# apt list --installed | grep dnsdist
dnsdist/jammy,now 1.6.1-1build1 amd64 [installed]
root@dnsdist1-1:/var/log# uname -a
Linux dnsdist1-1 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Expected behavior: 
That the security check return ok for versions where the distro has compiled in a version OR show a different status to suggest it is handled externally by the OS repo

**Comment by omoerbeek** [comment]
https://docs.powerdns.com/recursor/security.html#security-polling says status 0 means: could not poll.

**Comment by networkmaster** [comment]
DNSDist is a different product to recursor. In DNSDist, 0 is an error condition https://dnsdist.org/statistics.html#security-status

**Comment by omoerbeek** [comment]
It's formulated differently, but basically the same. 0 means that no security status could be obtained. The distribution has overridden the default value of `https://dnsdist.org/reference/config.html?highlight=poll#setSecurityPollSuffix`. There's nothing we can do about that.

**Comment by networkmaster** [comment]
[DNSDist.conf.txt](https://github.com/PowerDNS/pdns/files/11793762/DNSDist.conf.txt)
Attached
It was an out of the box Ubuntu install and then some settings changed for IPs etc etc.

**Comment by mnordhoff** [comment]
I didn't install it to make sure, but I think Ubuntu ships a `dnsdist.conf` like:

```
-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

-- disable security status polling via DNS
setSecurityPollSuffix("")

```

If that's correct, they expect you to disable polling so it won't poll with the modified Ubuntu version number.

**Comment by networkmaster** [comment]
Can confirm my settings do not have setSecurityPollSuffix("") either and is flagging the issue. 
HOWEVER an out of the box install on Ubuntu DOES have this setting - but it kinda, sorta defeats the purpose - it would be nice if i could enable this with support 




`cat /etc/dnsdist/dnsdist.conf
-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

-- disable security status polling via DNS
setSecurityPollSuffix("")
`

**Comment by omoerbeek** [comment]
Ubuntu does two things: it modifies the version string and disables polling in the default config. There's not a lot we can do about that.

Consider using a version from or own repo (see https://repo.powerdns.com), which has working security polling out of the box.
