### ISSUE TITLE
dnsdist: metrics to count failures for health-check domain for the backend server

### ISSUE THREAD

**Issue by SrX** [PowerDNS/pdns#12846]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Shows now many failures for health-check domain happed for each of the backed

### Usecase
Be able to monitor if domains used to perform a health-check in a backend reported as failed. That should help to detect network loss or health-check target eventual failure before the backed is marked as down.

### Description
Get a metrics that shows now many failures for health-check domain happed for each of the backend server.

**Comment by rgacogne** [comment]
We need to be careful that the set of domains used for the health-checks would then needs to be bounded, otherwise we have an issue, for example if someone uses a random prefix for each health-check query.

**Comment by SrX** [comment]
I would base the metrics on healcheck per backed, no adding the domain to prometheus metric. Once failures where detected by health check, we do print to logs the domain name.
