### ISSUE TITLE
dnsdist: cleanup the packetcache when notify is received

### ISSUE THREAD

**Issue by SrX** [PowerDNS/pdns#12847]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Cleanup the packet-cache when notify is received. 

### Usecase
- When dnsdist is in front of auth servers and pc enabled, that would help to purge "old" zone data.
- When dnsdist is in front of recursor and pc is enabled, auth can send a NOTIFY to recursor to wipe-up from the cache records, dnsdist in this case will stay with old data, but it should be purged to be able to cache the new domain response.

### Description
dnsdist has to select the PC and purge the entries for all domains under the zone from NOTIFY packet.

**Comment by phonedph1** [comment]
Did you try to do this in Lua already because it feels like something that is already easily done

**Comment by phonedph1** [comment]
I'm sure you can make this better (like modify the response so you don't need the second rule), but something as simple as this will do it:

```
function flushCache(dq) 
  errlog("Got notify for " .. dq.qname:toString())
  a = getPool(""):getCache():toString()
  getPool(""):getCache():expungeByName(dq.qname, DNSQType.ANY, true)
  z = getPool(""):getCache():toString()
  errlog("Went from " .. a .. " to " .. z)
  return DNSAction.None
end

addAction(AndRule({makeRule("127.0.0.1"),  OpcodeRule(DNSOpcode.Notify)}), LuaAction(flushCache))
addAction(AndRule({makeRule("127.0.0.1"),  OpcodeRule(DNSOpcode.Notify)}), RCodeAction(DNSRCode.NOERROR))
```

```
Got notify for google.com.
Went from 2/100000 to 1/100000
Got notify for com.
Went from 1/100000 to 0/100000
grepq('')
Time    Client                                          Protocol     Server       ID    Name                      Type  Lat.   TC RD AA Rcode
-23.8   127.0.0.1:44375                                 DoUDP                     25509 google.com.               A               RD    Question
-23.8   127.0.0.1:44375                                 DoUDP        9.9.9.9:53   25509 google.com.               A     36.9      RD    No Error. 6 answers
-17.5   127.0.0.1:51318                                 DoUDP                     1162  microsoft.com.            A               RD    Question
-17.4   127.0.0.1:51318                                 DoUDP        9.9.9.9:53   1162  microsoft.com.            A     29.8      RD    No Error. 5 answers
-15.9   127.0.0.1:51260                                 DoUDP                     36410 google.com.               SOA                   Question (Notify)
-15.9   127.0.0.1:51260                                 -            Cache        36410 google.com.               SOA   0.0             No Error. 0 answers
-14.5   127.0.0.1:43856                                 DoUDP                     2771  com.                      SOA                   Question (Notify)
-14.5   127.0.0.1:43856                                 -            Cache        2771  com.                      SOA   0.0             No Error. 0 answers
> 
```

**Comment by SrX** [comment]
Thank you for the hint, it's a good starting point.

This feature may require to duplicated NOTIFY to multiple backends, I think a TeeAction maybe used here.
Flushing the packet cache for the server pool associated with the backend, in case backend send a "NOERROR" answer.

```
--replicate notify to muliple back-ends
addAction(AndRule({makeRule("127.0.0.1"),  OpcodeRule(DNSOpcode.Notify)}), TeeAction("10.0.0.1"))
addAction(AndRule({makeRule("127.0.0.1"),  OpcodeRule(DNSOpcode.Notify)}), TeeAction("10.0.0.2"))

-- flush the cache if back-end has answered with NOERRROR
addResponseAction(AndRule({OpcodeRule(DNSOpcode.Notify), RCodeRule(DNSRCode.NOERROR)}), LuaResponseAction(flushCache))
```
Getting multiple responses for NOTIFY should not be an issue.

Incoming rules:
```
> showRules()
#   Name                             Matches Rule                                                     Action
...
4                                          0 (Src: 127.0.0.1/32) && (opcode==4)                       tee to 10.0.0.1:53
5                                          0 (Src: 127.0.0.1/32) && (opcode==4)                       tee to 10.0.0.2:53
>
```

Response rules:
```
> showResponseRules()
#   Name                             Matches Rule                                                     Action
0                                          0 (opcode==4) && (rcode==No Error)                         Lua response script
```

Would be great to perform this actions asynchronous way, to avoid blocking blocking the thread meanwhile cache is flushed, or the packet cache could be under the lock, as flush is done by suffix.

**Comment by rgacogne** [comment]
> Would be great to perform this actions asynchronous way, to avoid blocking blocking the thread meanwhile cache is flushed, or the packet cache could be under the lock, as flush is done by suffix.

One way to do that might be to add the domain to flush to a Lua list, and process that list in the `maintenance` function, perhaps?

**Comment by SrX** [comment]
> One way to do that might be to add the domain to flush to a Lua list, and process that list in the `maintenance` function, perhaps?

That's a great idea, I'll take it account.

**Comment by rgacogne** [comment]
Closing this for now as we have a workaround using Lua, and I'm not sure doing it in C++ would actually be better.
