### ISSUE TITLE
Please publish bookworm repositories

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#12852]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description
Debian bookworm is -almost- out, please start providing repositories.

### Usecase
Packages for Debian 12 really.

### Description

I think most things are already in place, just the packages need publishing?

**Comment by 24fpsDaVinci** [comment]
seconded, it would be nice if we could try out beta packages on bookworm beta

**Comment by Habbie** [comment]
> I think most things are already in place, just the packages need publishing?

yes I think so!



> seconded, it would be nice if we could try out beta packages on bookworm beta

you can get daily builds (of the master branch) from https://github.com/PowerDNS/pdns/actions/workflows/builder.yml for now

**Comment by Habbie** [comment]
fixing #11925 would be nice, but I think doing that somewhat later would also work

**Comment by Habbie** [comment]
auth-4.8 now has a bookworm repo. Others will follow soon (likely whenever they get a new release)

**Comment by omoerbeek** [comment]
Done
