### ISSUE TITLE
PDNS Upgrade fails - XFR initiated but no longer performed

### ISSUE THREAD

**Issue by clusterx** [PowerDNS/pdns#12853]
**Program:** Authoritative
**Issue type:** Bug report

**Short description**
upgraded PDNS server from 4.3.2 1 to 4.7.4 afterwards AXFR/IXFR is being initiated but no longer performed.
I use Hetzner and Linode secondary DNS services w/ the respective system which worked before the upgrade.
Same happens even if I create a new test zone it just show a transfer initiated message, nothing else.
check-all-zones and pdns start w/ --loglevel=9 no errors are shown, it seems to hang:

May 25 14:12:45 ns1 pdns_server[27387]: IXFR-out zone 'domain.tld', client 'xxx.xxx.xxx.xxx', transfer initiated with serial 2023052502
May 25 14:12:45 ns1 pdns_server[27387]: AXFR-out zone 'domain.tld', client 'xxx.xxx.xxx.xxx', transfer initiated
May 25 14:12:45 ns1 pdns_server[27387]: IXFR-out zone 'domain.tld', client 'xxx.xxx.xxx.x', transfer initiated with serial 2023052502
May 25 14:12:45 ns1 pdns_server[27387]: AXFR-out zone 'domain.tld', client 'xxx.xxx.xxx.x', transfer initiated
May 25 14:12:45 ns1 pdns_server[27387]: IXFR-out zone 'domain.tld', client 'xxx.xx.xx.x', transfer initiated with serial 2023052502
May 25 14:12:45 ns1 pdns_server[27387]: AXFR-out zone 'domain.tld', client 'xxx.xx.xx.x', transfer initiated

**gmysql parameters**
launch=gmysql
gmysql-host=localhost
gmysql-port=3306
gmysql-dbname=xxxxx
gmysql-user=xxxxxx
gmysql-password=xxxxxxx
gmysql-dnssec=no

**executed after upgrade**
ALTER TABLE domains ADD options VARCHAR(64000) DEFAULT NULL;
ALTER TABLE domains ADD catalog VARCHAR(255) DEFAULT NULL;
ALTER TABLE domains MODIFY type VARCHAR(8) NOT NULL;
CREATE INDEX catalog_idx ON domains(catalog);

**Environment**
Operating system: Debian Buster
Software version: 4.7.4 / gmysql
Software source: Repositories

**Comment by clusterx** [comment]
strange, it seems the secondary records are updated
dig testxxx3.com soa @ns1-3.mydns.tld 
2023052500 28800 7200 1209600 86400, serial & other stuff matches for all 3 zones ...

But logs only show as "transfer initiated" e.g.
transfer initiated with serial 2023052500

PDNS v. 4.3 has always shown "acknowledged" after  initiated ...
did I missed something and how can I activate these log acknowledged confirmations?

**Comment by clusterx** [comment]
it seems to be ignored in standard logging, after explicit log settings are set, the finished output are shown:

May 26 11:48:20 ns1 pdns_server[18711]: AXFR-out zone 'domain.tld', client 'xxx.xx.xx.x', AXFR finished
May 26 11:48:21 ns1 pdns_server[18711]: Removed from notification list: 'domain.tld' to xxx.xxx.xxx.xxx:53 (was acknowledged)
May 26 11:48:21 ns1 pdns_server[18711]: Removed from notification list: 'domain.tld' to xxx.xxx.xxx.x:53 (was acknowledged)
May 26 11:48:21 ns1 pdns_server[18711]: Removed from notification list: 'domain.tld' to xxx.xx.xx.x:53 (was acknowledged)

settings:
allow-unsigned-autoprimary=yes
allow-unsigned-notify=yes
allow-unsigned-supermaster=yes
send-signed-notify=no
**log-dns-queries=yes**
**log-timestamp=yes**
**loglevel=4**
master=yes
**query-logging=yes**

**Comment by clusterx** [comment]
I have tested again with a clean installation ...
Notifications and AXFR/IXFR operations only work with the following settings:

log-dns-queries=yes
log-timestamp=yes
loglevel=5
query-logging=yes
disable-syslog=no

Can that be used in productive use or is there a better solution?

**Comment by Habbie** [comment]
> Can that be used in productive use or is there a better solution?

You can use that in production.
