### ISSUE TITLE
auth: Provide secure default for allow-axfr-ips

### ISSUE THREAD

**Issue by terrorobe** [PowerDNS/pdns#1287]
According to @Habbie the default outbound axfr security model looks like this:

outbound axfr is allowed
1. from allow-axfr
2. from automatic hole punching we do for hosts we notified
3. from TSIG
4. from per-domain ALLOW-AXFR-FROM
4b. which can include AUTO-NS as value, allowing all listed NSes

which can cause surprises because allow-axfr is set to "0/0,::/0" by default which means the whole world can AXFR.

I'd suggest to set the default value of allow-axfr-ips to "127.0.0.1,::1" as well as documenting the above list (especially Point 2) in the master/slave documentation.

**Comment by omoerbeek** [comment]
Looks fixed already.
