### ISSUE TITLE
rec: optimize RPZ memory usage

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#12870]
Currently a single RPZ line translates into `Policy` object that takes more than 100 bytes. A big RPZ (one million records) takes more than 100 megabytes.

There are a couple of things that could be optimized:

1. `d_custom` could move to a unique pointer, only allocated if actual custom records are present. Current size of the field is 24, would become 8.
2. `d_trigger` is only used if a hit has occurred. No need to store these in the in memory RPZ Policy. Ponder an `AppliedPolicy` struct, that includes or extends the existing `Policy` without the `d_trigger` field and ads `d_trigger` itself. Saving: 24 bytes per `Policy` object. `Syncres` would use `ApliedPolicy` but the in-memory objects would be `Policy`.
3. Same for `d_hit`: also saves 24 bytes per `Policy`.

Total saving: 16 + 24 + 24 is 64 bytes per `Policy object`. So this cuts the memory usage for RPZ roughly in half.

**Comment by hlindqvist** [comment]
Some related observations (from a pure user perspective): 

* It seems to me that pdns-rec is quite eager to load all the new versions of all zones in parallell with the all the existing zone data before freeing the previous zone versions. Could this also be managed somehow to optimize for less peak memory usage?
I have for instance run into situations where pdns-rec on more memory-constrained machines couldn't even start unless I remove the `seedFile` option as it would first load all the old versions and then effectively double up via AXFR, needing seemingly 2x the normal memory all at once.

* As one can quite easily load a few blocklists and end up with pdns-rec using a few gigabytes of memory for RPZ alone (and effectively needing ~double that sometimes as per above), would for example LMDB-backed RPZ be a viable option to consider as well?

**Comment by omoerbeek** [comment]
Adapting the code to not have two copies in memory at all is hard, as we want to be able to roll back if the processing of the new data fails. But I do believe one simple optimization is possible: the old copy can be thrown away earlier. If I'm correct, the old copy now stays in memory until a new iteration update cycle is done.

Completely rewriting the RPZ code to use LMDB is not something we'll do soon as it would mean more or less rewriting the whole subsystem.

**Comment by hlindqvist** [comment]
> Adapting the code to not have two copies in memory at all is hard, as we want to be able to roll back if the processing of the new data fails. But I do believe one simple optimization is possible: the old copy can be thrown away earlier. If I'm correct, the old copy now stays in memory until a new iteration update cycle is done.

Yes, if that is possible it sounds like it could really help in addressing the situation where the entire memory usage seems to double (as opposed to 2x an individual zone that is being updated).  

> Completely rewriting the RPZ code to use LMDB is not something we'll do soon as it would mean more or less rewriting the whole subsystem.

Makes sense. Just throwing the idea in there.

**Comment by omoerbeek** [comment]
Biggest memory usage issue is being addressed in #13462

**Comment by omoerbeek** [comment]
A derived object will not work due to the fact that tLuaWrapper cannot handle that. But two `unique_ptr`s to the fields that are only filled on demand should work. See also
