### ISSUE TITLE
Problem with LUA records

### ISSUE THREAD

**Issue by seanfulton** [PowerDNS/pdns#12887]
I have not had much luck with LUA on PowerDNS in general, but this is really puzzling me.

This is for a dual data center configuration. The goal is to point "test" to an IP in the local network. In other words, if I request the IP for test from 10.10.4.X/24, I will get 10.10.4.111; if I request the IP for test from a machine on 10.10.20.X/24, I will get 10.10.20.111. Otherwise, I will get 10.10.20.222.

Despite hours of tweaking, the only consistent result I get is 10.10.20.222, regardless of which network I am on, using either nslookup or dig.

Zone file:
test	IN LUA	A ( "view({ {{'10.10.4.0/24'}, {'10.10.4.111'}},{{'10.10.20.0/24'}, {'10.10.20.111'}},{{'0.0.0.0/0'}, {'10.10.20.222'}} })")

I initially did not have the LUA back-end loaded into PDNS, and so I installed and loaded that but not change.

pdns.conf:
bind-config=/etc/pdns/bind.conf
cache-ttl=0
consistent-backends=yes
daemon=yes
edns-subnet-processing=yes
enable-lua-records=yes
geoip-database-files=/etc/pdns/GeoLite2-City.mmdb
launch=bind,lua2,geoip
#launch=bind,geoip
query-cache-ttl=0
query-logging=yes
setgid=pdns
setuid=pdns
local-address=127.0.0.1
local-port=5300
loglevel=9
enable-lua-records

I get the same result whether I include lua in my pdns.conf or not.

Any help would be appreciated:
sean

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by Habbie** [comment]
> I have not had much luck with LUA on PowerDNS in general, but this is really puzzling me.

Also, don't open like this. Nobody likes a whiner.

**Comment by seanfulton** [comment]
> 

If you want to send me to the user list that's fine, but there was no need for the snarky comment.  It makes the whole project look bad to anyone who might want to use it.

As I said, I've had trouble getting LUA scripts to work with PowerDNS. For the sake of anyone else trying to get this working, I will outline why and and include the solution, because it's not obvious from the documentation.

Perhaps you would consider adding this to the documentation.

We are running pdns, dnsdist, and pdns-recursor on the same machine(s). It's a cluster of five machines. 

In order for the LUA examples listed here:
https://doc.powerdns.com/authoritative/backends/geoip.html
and here:
https://doc.powerdns.com/authoritative/lua-records/index.html
and here:
https://archive.fosdem.org/2019/schedule/event/dns_powerdns_lua_record/attachments/slides/3075/export/events/attachments/dns_powerdns_lua_record/slides/3075/FOSDEM_2019_LUA_records.pdf

To work, you need to pass the client's IP address through the entire stack. It's not enough to simply configure them in pdns, you have to tell dnsdist to pass the client-IP, and the pdns-recursor.

Add the following to 
pdns.conf:
edns-subnet-processing=yes
enable-lua-records=yes

dnsdist.conf (add useClientSubnet to your newServer commands):
newServer({address='127.0.0.1:5300', pool='auth', useClientSubnet=true})
newServer({address='127.0.0.1:5301', pool='recursor', useClientSubnet=true})

pdns-recursor.conf:
edns-subnet-whitelist=0.0.0.0/0
use-incoming-edns-subnet=yes

**Comment by Habbie** [comment]
> there was no need for the snarky comment

It was not meant to be snarky. Nothing about it was sarcastic or intended to be humorous.

> I will outline why and and include the solution

Thank you, this is much appreciated!

> it seems to consider queries sent directly to the authoritave server without going through dnsdist and the recursor.

indeed, this is the most common use case.
