### ISSUE TITLE
fatal error: 'curl/curlver.h' file not found

### ISSUE THREAD

**Issue by liang-hiwin** [PowerDNS/pdns#12886]
In the static compilation of Recursor, I need this problem, I suspect it is a bug

I encountered this problem when compiling Recursor statically. I suspected it was a bug. Through the error prompt, I found minicurl.hh in the source code, and the code on line 28 was in the commented state.
![5AR~{D BQ2)9Z XXNJYF9 N](https://github.com/PowerDNS/pdns/assets/17548936/44b1f3aa-b8fb-4d56-9816-2c2b06c6674d)

```
1 warning generated.
  CXX      rec-tcounters.o
  CXX      rec-tcp.o
  CXX      rec-tcpout.o
  CXX      rec-zonetocache.o
In file included from rec-zonetocache.cc:36:
./minicurl.hh:28:10: fatal error: 'curl/curlver.h' file not found
#include <curl/curlver.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Makefile:1680: rec-zonetocache.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/opt/bulid/pdns-recursor-4.9.0-beta1.4.master.g06aab7637'
make[1]: *** [Makefile:1804: all-recursive] Error 1
make[1]: Leaving directory '/opt/bulid/pdns-recursor-4.9.0-beta1.4.master.g06aab7637'
make: *** [Makefile:1347: all] Error 2

```

**Comment by zeha** [comment]
You seem to have deleted the template and provided zero useful information.

This GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question and belongs into the other PowerDNS online communities: IRC and mailing lists.
Please see https://www.powerdns.com/opensource.html for information about those.
