### ISSUE TITLE
Can DNSDIST continue to recursive request to the backend dns service after hijacking a cname?

### ISSUE THREAD

**Issue by zjs604381586** [PowerDNS/pdns#12882]
- Program: dnsdist 
 - Issue type: Feature request

### Short description

Can DNSDIST continue to recursive request to the backend dns service after hijacking a cname?

### Usecase

For example, dnsdist.conf has such a hijacking cname configuration
cat /etc/dnsdist/dnsdist.conf
**addAction(makeRule("source.example.com"),  SpoofCNAMEAction(spoof1.example.com"))**

Currently the return value of my **dig source.example.com** response is:

; <<>> DiG 9.11.5-P4-5.1+deb10u8-Debian <<>> @127.0.0.1 source.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12689
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;source.example.com.		IN	A

;; ANSWER SECTION:
**source.example.com.	60	IN	CNAME	spoof1.example.com.**

### Description

For example, **the A record of spoof1.example.com. is 1.1.1.1**, and the answer I expect is：
; <<>> DiG 9.11.5-P4-5.1+deb10u8-Debian <<>> @127.0.0.1 source.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12689
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;source.example.com.		IN	A

;; ANSWER SECTION:
**source.example.com.	60	IN	CNAME	spoof1.example.com.**
**spoof1.example.com.   60   IN       A             1.1.1.1**

**Comment by setharnold** [comment]
I suspect this will need a bit more explanation about what you're trying to accomplish for anyone to offer advice or know what kind of feature to add. Thanks

**Comment by zjs604381586** [comment]
@setharnold I updated the detailed description, please check，thank you

**Comment by setharnold** [comment]
Oh that's much better, thanks :) If I've understood your question correctly, I don't think that is possible:

https://en.wikipedia.org/wiki/CNAME_record

> If a CNAME record is present at a node, no other data should be present; this ensures that the data for a canonical name and its aliases cannot be different. (RFC 1034 section 3.6.2, RFC 1912 section 2.4) The exception is when [DNSSEC](https://en.wikipedia.org/wiki/DNSSEC) is being used, in which case there can be DNSSEC related records such as RRSIG, NSEC, etc. (RFC 2181 section 10.1)

**Comment by Habbie** [comment]
dnsdist cannot do this. PowerDNS Recursor can. Please read the template below.

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by mengxifl** [comment]
I need this method but . You konw you can use lua to do it.
this is my scirpt 
main.lua
```
newServer( {address="8.8.8.8:53",name="outside1",checkName="google.com",pool="example",maxCheckFailures=1 } )
local cnameConfig = {
  { dns="www.example.com", cname="www.example1.com", pool="example1" },
}

dofile("/runningConfig/scirpt_cname.lua")
createCNAMERecord( cnameConfig )
```

/runningConfig/scirpt_cname.lua
```
function createCNAMERecord ( CNAMEConfig )
  for i, v in ipairs(CNAMEConfig) do
    createCNAMEAction( v.dns, v.cname, v.pool )
  end
end

function createCNAMEAction (dns, cname, pool)
  addAction(
    QNameRule(cname),PoolAction( pool ) )
  addAction(
    QNameRule(dns),
    LuaAction(
      function (dq)
        dq = processCNAME("query", dq, dns, cname )
        return DNSAction.Pool, pool
      end
    )
  )
  addResponseAction(
    QNameRule(cname),
    LuaResponseAction(
      function (dr)
        dr = processCNAME( "response", dr, "", "" )
        return DNSResponseAction.None
      end
    )
  )
end


local
queryName = ""
function processCNAME ( step, dnsConfig, trueQueryDNS, cnameDNS  )
  if queryName == "" and step == "query" then
    queryName = trueQueryDNS
    dnsConfig:changeName( newDNSName(cnameDNS) )
    return dnsConfig
  end

  if queryName ~= "" and step == "response"  then
    dnsConfig:changeName( newDNSName(queryName)  )
    queryName = ""
    return dnsConfig
  end
  return dnsConfig
end

```
I think this may help you
