### ISSUE TITLE
FD380FBB-pub.asc certificate has expired on June 7th

### ISSUE THREAD

**Issue by juanfumagalli87** [PowerDNS/pdns#12894]
# hello user, please read this:

You can either redownload the keys from the same place, or, if you're using apt-key, try `apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com` (this also works on Debian).

With apologies, the PowerDNS team.

### original ticket below this line

<hr>

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description
FD380FBB-pub.asc certificate has expired on June 7th and we are not able to download packages.

### Environment
 - Operating system: Ubuntu 20.04 "Focal Fossa" 
 - Software version: 4.8.X (stable)
 - Software source: PowerDNS repository

### Steps to reproduce
1. curl https://repo.powerdns.com/FD380FBB-pub.asc | sudo apt-key add
2. sudo apt-get update

### Expected behavior
update packages

### Actual behaviour
Err:9 http://repo.powerdns.com/ubuntu focal-rec-48 InRelease                               
  The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
W: GPG error: http://repo.powerdns.com/ubuntu focal-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
E: The repository 'http://repo.powerdns.com/ubuntu focal-rec-48 InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Other information
apt-key list 
pub   rsa4096 2015-06-09 [SC] [expired: 2023-06-07]
      9FAA A557 7E8F CF62 093D  036C 1B0C 6205 FD38 0FBB
uid           [ expired] PowerDNS Release Signing Key <powerdns.support@powerdns.com>

**Comment by PenelopeFudd** [comment]
Also to verify:
```
$ curl -sS https://repo.powerdns.com/ | grep PGP | head -n1

              Packages in the versioned repositories are signed with PGP key-id <a href="FD380FBB-pub.asc">0xFD380FBB</a>

$ curl -sS https://repo.powerdns.com/FD380FBB-pub.asc | gpg --list-packets | grep -e 'sig created' -e 'key expires after'

	hashed subpkt 2 len 4 (sig created 2015-06-09)
	hashed subpkt 9 len 4 (key expires after 8y0d0h0m)

$ date -d@$(( $(date -d"2015-06-09" +%s) + 8 * 365 * 86400 ))

Wed 07 Jun 2023 12:00:00 AM PDT
```

**Comment by 662KDV** [comment]
Same behavior on Ubuntu 22.04.

**Comment by MachineITSvcs** [comment]
I came here to create the same issue. Glad someone beat me to it. Hopefully it gets some visibility soon. Also on Ubuntu 22.04

**Comment by PenelopeFudd** [comment]
This is why it's a bad idea to have certificates and keys that expire far in the future; everyone forgets how to renew them.  😃

**Comment by Habbie** [comment]
Thank you all for reporting, and apologies for the inconvenience. I have extended the expiry by 3 years and we will deploy a more robust solution before -that- time passes.

Testing is welcome! Either redownload the keys from the same place, or, if you're using `apt-key`, try `apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com`

We'll do some announcements soon.

**Comment by dwfreed** [comment]
For PDNS's future reference, postgres has a great implementation of a third party package repo (at least for Debian family, which is all I care about)

**Comment by plachetka** [comment]
http://repo.powerdns.com/debian buster-metronome-master InRelease
  The following signatures were invalid: EXPKEYSIG FF389421CBC8B383 PowerDNS Automatic Signing Key <powerdns.support@powerdns.com>

Please also update the files also therefore. Thanks!

**Comment by plachetka** [comment]
> @plachetka did you redownload the keys? You can reuse the original instructions from repo.powerdns.com

Yes, everything was fine for the other repos: buster-rec-47, buster-dnsdist-17 and buster-auth-47.

apt error: _The repository 'http://repo.powerdns.com/debian buster-metronome-master InRelease' is not signed._

**Comment by Habbie** [comment]
release repos (-47, -17, etc.) have one key (FD380FBB). master repos have another key (CBC8B383). Did you refresh both keys?

**Comment by PenelopeFudd** [comment]
> Thank you all for reporting, and apologies for the inconvenience. I have extended the expiry by 3 years and we will deploy a more robust solution before -that- time passes.
> 
> Testing is welcome! Either redownload the keys from the same place, or, if you're using `apt-key`, try `apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com`

1. TIL that updating a key's expiry date doesn't change the key's ID, watching for the key ID to change on http://repo.powerdns.com/ was a waste of time.  😄 
2. `Extended the expiry by 3 years` = `made it expire in 11 years instead of 8 years`:
 
```
$ curl -sS https://repo.powerdns.com/FD380FBB-pub.asc | gpg --list-packets | grep -e created -e expires

	version 4, algo 1, created 1433861228, expires 0
	version 4, created 1686203943, md5len 0, sigclass 0x13
	hashed subpkt 2 len 4 (sig created 2023-06-08)
	hashed subpkt 9 len 4 (key expires after 11y0d15h11m)

$ date -d@$(( 1686203943 + 11 * 365 * 86400 + 15 * 3600 + 11 * 60 ))

Mon 05 Jun 2034 02:10:03 PM PDT
```
Time to set a calendar reminder!  😃

**Comment by Habbie** [comment]
```
$ date -d@$(( 1433861228 + 11 * 365 * 86400 + 15 * 3600 + 11 * 60 ))
Sun Jun  7 07:58:08 CEST 2026
```

**Comment by PenelopeFudd** [comment]
Oh, ok.  I'm fairly new to deciphering GPG's expiry dates, so after calculating the first expiry date correctly, I thought I had figured out which fields to add together.  Evidently not!  🥲 

BTW, could you paste the commands used for extending an expiry date, or where to find the commands?  I had a tough time finding commands for determining the expiry date, and even then I got it wrong.  ☹️

**Comment by Habbie** [comment]
Determining (simpler, harder to get wrong):

```
$ curl -sS https://repo.powerdns.com/FD380FBB-pub.asc | gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096/0x1B0C6205FD380FBB 2015-06-09 [SC] [expires: 2026-06-07]
      9FAAA5577E8FCF62093D036C1B0C6205FD380FBB
uid                             PowerDNS Release Signing Key <powerdns.support@powerdns.com>
```

Extending: `gpg --edit-key` (on a privkey), then type `expire`.

**Comment by EasyG0ing1** [comment]
I just issued

```Bash
sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
```

But am getting this error:
```Bash
W: GPG error: http://repo.powerdns.com/debian buster-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
E: The repository 'http://repo.powerdns.com/debian buster-rec-48 InRelease' is not signed.
```

**Comment by EasyG0ing1** [comment]
@Habbie - Please forgive my ignorance, doing manual builds in linux is not my forte' ... you said:

> release repos (-47, -17, etc.) have one key (FD380FBB). master repos have another key (CBC8B383). Did you refresh both keys?

How does one go about actually doing this?

**Comment by Habbie** [comment]
> How does one go about actually doing this?

your apt-key command should have covered what you needed. Was there any output from it?

**Comment by EasyG0ing1** [comment]
@Habbie Here is the text shot of it:

```Bash
vyos_bld@cfa4b8a5f9d6:/vyos$ sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
Executing: /tmp/apt-key-gpghome.609YtVrIXY/gpg.1.sh --refresh-keys --keyserver keyserver.ubuntu.com
gpg: refreshing 9 keys from hkp://keyserver.ubuntu.com
gpg: key EF0F382A1A7B6500: "Debian Stable Release Key (9/stretch) <debian-release@lists.debian.org>" not changed
gpg: key EDA0D2388AE22BA9: "Debian Security Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" not changed
gpg: key E0B11894F66AEC98: "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" not changed
gpg: key DCC9EFBF77E11517: "Debian Stable Release Key (10/buster) <debian-release@lists.debian.org>" not changed
gpg: key 4DFAB270CAA96DFA: "Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: key DC30D7C23CBBABEE: "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: key 605C66F00D6C9793: "Debian Stable Release Key (11/bullseye) <debian-release@lists.debian.org>" not changed
gpg: key A48449044AAD5C5D: "Debian Security Archive Automatic Signing Key (11/bullseye) <ftpmaster@debian.org>" not changed
gpg: key 73A4F27B8DD47936: "Debian Archive Automatic Signing Key (11/bullseye) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 9
gpg:              unchanged: 9
```

**Comment by Habbie** [comment]
That suggests that you did not use apt-key to install the powerdns keys originally. Can you try following the curl/apt-key instructions on repo.powerdns.com again?

**Comment by EasyG0ing1** [comment]
@Habbie - OK, I'm actually following the instructions for building an ISO for VyOS using their pre-made Docker environment so you are correct since I never followed any instructions from powerdns.com, but I'll go do that now.

☺

**Comment by setharnold** [comment]
@EasyG0ing1 try:

```
cd /etc/apt/trusted.gpg.d
sudo wget https://repo.powerdns.com/FD380FBB-pub.asc
```

**Comment by EasyG0ing1** [comment]
@setharnold - OK so I did that followed by:

```Bash
sudo apt-key add FD380FBB-pub.asc
```
Then tried my build again but get the same errors.

@Habbie - From `repo.powerdns.com` I did the following:

```Bash
sudo pico /etc/apt/sources.list.d/pdns.list
```
Added this into that file:
> deb [arch=amd64] http://repo.powerdns.com/debian stretch-auth-master main

Then 
```Bash
sudo pico /etc/apt/preferences.d/pdns
```
And placed this into that file:
> Package: pdns-*
> Pin: origin repo.powerdns.com
> Pin-Priority: 600

Then
```Bash
curl https://repo.powerdns.com/CBC8B383-pub.asc | sudo apt-key add - &&
sudo apt-get update &&
sudo apt-get install pdns-server
```

And got this error (There were several at first and I was able to install some but these for some reason I cannot reconcile):
```Bash
The following packages have unmet dependencies:
 pdns-server : Depends: libboost-program-options1.62.0 but it is not installable
               Depends: libcurl3 (>= 7.16.2) but it is not installable
               Depends: libsodium18 (>= 0.6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by EasyG0ing1** [comment]
@Habbie @setharnold - I think I fixed it ... following Seths instructions, I just grabbed `CBC8B383-pub.asc` and added it to the keyring and I'm off and running.

**Comment by EasyG0ing1** [comment]
So I tried downloading and adding `https://repo.powerdns.com/CBC8B383-pub.asc` as well as `https://repo.powerdns.com/FD380FBB-pub.asc` then I did another

```Bash
sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
```

And this time it gave me:

```Bash
gpg: key 1B0C6205FD380FBB: "PowerDNS Release Signing Key <powerdns.support@powerdns.com>" 1 new signature
```
But I am still getting this during my build:
```Bash
W: GPG error: http://repo.powerdns.com/debian buster-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
E: The repository 'http://repo.powerdns.com/debian buster-rec-48 InRelease' is not signed.
```

**Comment by setharnold** [comment]
There's no need to use `apt-key` when you put the `.asc` files in `/etc/apt/trusted.gpg.d/` -- `apt-key` manages a single keyring file, in a manner that might have made sense two decades ago, but doesn't make much sense today.

**Comment by EasyG0ing1** [comment]
@setharnold 

OK, so based on that, I did this:
```Bash
cd /etc/apt/trusted.gpg.d/
sudo rm CBC*
sudo rm FD*
sudo apt-key del CBC8B383
sudo apt-key del FD380FBB
sudo wget https://repo.powerdns.com/FD380FBB-pub.asc
sudo wget https://repo.powerdns.com/CBC8B383-pub.asc
cd /vyos
sudo make iso
```
Only to get this:
```Bash
W: GPG error: http://repo.powerdns.com/debian buster-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
E: The repository 'http://repo.powerdns.com/debian buster-rec-48 InRelease' is not signed.
```

I'm working inside of a Docker pre-made build environment if that matters at all.

**Comment by PenelopeFudd** [comment]
> I just issued
> 
> ```shell
> sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
> ```
> 
> But am getting this error:
> 
> ```shell
> W: GPG error: http://repo.powerdns.com/debian buster-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
> E: The repository 'http://repo.powerdns.com/debian buster-rec-48 InRelease' is not signed.
> ```

It turns out that `apt-key` is old and almost completely deprecated.  Now the work is done with just wget or curl:
```shell

curl -sS https://repo.powerdns.com/FD380FBB-pub.asc \
  | sudo tee /etc/apt/trusted.gpg.d/pdns.asc

echo 'deb [signed-by=/etc/apt/trusted.gpg.d/pdns.asc arch=amd64] http://repo.powerdns.com/ubuntu jammy-dnsdist-18 main' \
  | sudo tee /etc/apt/sources.list.d/pdns.list

cat << EOF | sudo tee /etc/apt/preferences.d/dnsdist
Package: dnsdist*
Pin: origin repo.powerdns.com
Pin-Priority: 600
EOF

sudo apt-get update && sudo apt-get install dnsdist
```
(Adapted from the dnsdist instructions at the bottom of https://repo.powerdns.com/ )

**Comment by EasyG0ing1** [comment]
@PenelopeFudd - Thank you for that ... after the last command, I get this back:

```Bash
The following packages have unmet dependencies:
 dnsdist : Depends: libc6 (>= 2.34) but 2.28-10+deb10u2 is to be installed
           Depends: libgcc-s1 (>= 3.3.1) but it is not installable
           Depends: libgnutls30 (>= 3.7.2) but 3.6.7-4+deb10u10 is to be installed
           Depends: libre2-9 (>= 20131024+dfsg) but it is not installable
           Depends: libsnmp40 (>= 5.9.1+dfsg) but it is not installable
           Depends: libssl3 (>= 3.0.0~~alpha1) but it is not installable
           Depends: libstdc++6 (>= 11) but 8.3.0-6 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Habbie** [comment]
@EasyG0ing1 your issue is entirely unrelated to the key expiry. Please keep it out of this thread. Thanks!

**Comment by EasyG0ing1** [comment]
@Habbie @PenelopeFudd @setharnold 

I just want to thank all of you for your time in trying to help me figure this out and my apologies for the thread take-over.

**Comment by Habbie** [comment]
(you may be able to find help via mailing list or IRC, see https://www.powerdns.com/powerdns-community )

**Comment by EasyG0ing1** [comment]
@Habbie Im convinced this has more to do with this build environment and the scripts involved than anything else ... it's the only thing that makes sense. This is not a complicated issue ... keys were expired - now they aren't ... its a no-brainer and so in that context, this problem does not belong here. Thank you again, if I'll check out that link if I get to my wits end.

☺

**Comment by spirillen** [comment]
This little snippet might help ubuntu users, if you don't use it as is, it should be giving you a pretty good idea for how to solve the gpg-key update / Install procedure.

```bash
#!/usr/bin/env bash
# Outcomment the the keyfile you would like to use.
# First key is to Stable releases, Second key is for master releases.
# License: GNU AGPLv3
# Copyright @spirillen 

# Pick your poison|wapon (key)
# KEY="FD380FBB" # Stable
KEY="CBC8B383" # Maser

PGP_URI="https://repo.powerdns.com/"
REPO_URI="http://repo.powerdns.com/ubuntu"
KEY_LOC="/usr/share/keyrings"

if [ -f "$PGP_URI/$KEY-pub.asc" || "$PGP_URI/$KEY.asc" ]; then
    sude rm -f "$PGP_URI/$KEY-pub.asc" "$PGP_URI/$KEY.asc"
fi

if [ -f /etc/apt/sources.list.d/pdns.list ]; then
    sude rm -f /etc/apt/sources.list.d/pdns.list
fi

curl "$PGP_URI/$KEY-pub.asc" | gpg --dearmor | sudo tee "$KEY_LOC/$KEY.gpg" >/dev/null
echo -e "deb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI 'lsb_release -cs'-auth-master main\ndeb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI 'lsb_release -cs'-rec-master main\ndeb [signed-by=$KEY_LOC/$KEY.gpg] $REPO_URI 'lsb_release -cs'-dnsdist-master main" | sudo tee /etc/apt/sources.list.d/pdns.list
# echo -e "Package: dnsdist*\nPin: origin repo.powerdns.com\nPin-Priority: 600\n" | sudo tee /etc/apt/preferences.d/pdns
# echo -e "Package: pdns-*\nPin: origin repo.powerdns.com\nPin-Priority: 600\n" | sudo tee /etc/apt/preferences.d/dnsdist
```

**Comment by jsoref** [comment]
Fwiw, this is what I saw:

```
Err:8 https://repo.powerdns.com/ubuntu jammy-auth-47 InRelease
  The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
Get:19 http://ca.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [20.0 kB]
Err:9 https://repo.powerdns.com/ubuntu jammy-dnsdist-master InRelease
  The following signatures were invalid: EXPKEYSIG FF389421CBC8B383 PowerDNS Automatic Signing Key <powerdns.support@powerdns.com>
...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.powerdns.com/ubuntu jammy-rec-48 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.powerdns.com/ubuntu jammy-auth-47 InRelease: The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.powerdns.com/ubuntu jammy-dnsdist-master InRelease: The following signatures were invalid: EXPKEYSIG FF389421CBC8B383 PowerDNS Automatic Signing Key <powerdns.support@powerdns.com>
W: Failed to fetch https://repo.powerdns.com/ubuntu/dists/jammy-rec-48/InRelease  The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
W: Failed to fetch https://repo.powerdns.com/ubuntu/dists/jammy-auth-47/InRelease  The following signatures were invalid: EXPKEYSIG 1B0C6205FD380FBB PowerDNS Release Signing Key <powerdns.support@powerdns.com>
W: Failed to fetch https://repo.powerdns.com/ubuntu/dists/jammy-dnsdist-master/InRelease  The following signatures were invalid: EXPKEYSIG FF389421CBC8B383 PowerDNS Automatic Signing Key <powerdns.support@powerdns.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by muslu** [comment]
Hi;

Solution for Ubuntu 20.04 and 22.04: 

`apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com`

`apt update; apt upgrade -y`


tested and approved

**Comment by Habbie** [comment]
You forgot to `sudo`

**Comment by spirillen** [comment]
> You forgot to `sudo`

still not changing anything as you can see other keys got upgraded, only way is to manually import it as in https://github.com/PowerDNS/pdns/issues/12894#issuecomment-1586164114

**Comment by Habbie** [comment]
> still not changing anything as you can see

I do not see you using `sudo` for `apt-key` in the video. (Also, please use copy/paste next time instead of a video)

**Comment by Habbie** [comment]
As this problem has been resolved on our end, I'm closing this ticket. Any further problems should be support questions, and will be handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.
