### ISSUE TITLE
auth: master: misleading axfr error message when disable-axfr is enabled

### ISSUE THREAD

**Issue by terrorobe** [PowerDNS/pdns#1290]
When running a master with disable-axfr you get the following messages:

master: AXFR of domain 'slave.test' failed: not authoritative

slave: Unable to AXFR zone 'slave.test' from remote '62.178.148.62' (resolver): AXFR chunk with a non-zero rcode 9

Code: https://github.com/PowerDNS/pdns/blob/20010d040efcd3d578c16af4681a30b2c749d665/pdns/tcpreceiver.cc#L554

**Comment by pieterlexis** [comment]
Fixed in 8090f5a2e8
