### ISSUE TITLE
Ability to remove zone from catalog zone with pdnsutil

### ISSUE THREAD

**Issue by wwijkander** [PowerDNS/pdns#12903]
- Program: Authoritative
 - Issue type: Feature request

### Short description
As far as I can see there's no way to remove a zone from a catalog zone with pdnsutil

### Usecase
For troubleshooting, moving zones between or away from catalog zones

### Description
Support for something like `pdnsutil unset-catalog example.com catz.invalid`

Thanks for all the great work on PowerDNS! <3

**Comment by dwfreed** [comment]
It's not documented, but you can set the catalog to the empty string (ie, `pdnsutil set-catalog example.com ""`), and it's the same as unsetting the catalog.

**Comment by wwijkander** [comment]
> It's not documented, but you can set the catalog to the empty string (ie, `pdnsutil set-catalog example.com ""`), and it's the same as unsetting the catalog.

Thanks for the hint! Should I open a PR to document this?

**Comment by rgacogne** [comment]
Fixed by #12908 (thanks!).
