### ISSUE TITLE
dnsdist docker writes wrong configuration to _api.conf

### ISSUE THREAD

**Issue by Houtworm** [PowerDNS/pdns#12915]
The current dnsdist docker container writes the following line to /etc/dnsdist/conf.d/_api.conf

webserver("0.0.0.0:8083", 'APIKEY', 'APIKEY', {}, '0.0.0.0/0')

but the webserver function only accepts 1 parameter. so it should be;

webserver("0.0.0.0:8083")

I found the error is here

https://github.com/PowerDNS/pdns/blob/master/dockerdata/startup.py

I will try to create a PR for it

**Comment by Houtworm** [comment]
https://github.com/PowerDNS/pdns/pull/12916

**Comment by rgacogne** [comment]
Fixed in #12916, thanks!
