### ISSUE TITLE
Easy way to support restart logging for FreeBSD

### ISSUE THREAD

**Issue by KVInventoR** [PowerDNS/pdns#12914]
Hi everyone, 

We are using FreeBSD as the general operating system for our DNS infrastructure.
Also, we are using dnsdist with the next version:

```
dnsdist 1.8.0 (Lua 5.4.4)
Enabled features: cdb dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt fstrm ipcipher libeditr libsodium lmdb outgoing-dns-over-https(nghttp2) protobuf re2 recvmmsg/sendmmsg snmp
```

This version we installed from ports.

What is the current issue?
In our configuration, we have line:
`addAction(AllRule(),LogAction("/var/log/dnsdist-full.log", false))` 
which gives us the possibility to log all DNS queries, but we would like to use newsyslog for rotation all dnsdist logs.

Unfortunately, our configuration doesn't work:
`/var/log/dnsdist-full.log      root:wheel      640  3     1000 *     JC        /var/run/dnsdist.pid` 
because /var/run/dnsdist.pid contains pid file for supervisor, and default behaviour for newsyslog:

https://man.freebsd.org/cgi/man.cgi?query=newsyslog.conf&sektion=5&manpath=freebsd-release-ports
```
signal  This optional field specifies the signal that will	be sent	to the
	     daemon process (or	to all processes in a process group, if	the U
	     flag was specified).  If this field is not	present, then a	SIGHUP
	     signal will be sent.  Signal names	must start with	"SIG" and be
	     the signal	name, e.g., SIGUSR1.  Alternatively, signal can	be the
	     signal number, e.g., 30 for SIGUSR1.
```
I also found this PR, which was implemented, but it's a little incompatible with newsyslog, and it will be good, to have possibility to reload all logging inside dnsdist after retrieving some signal from main system.
https://github.com/PowerDNS/pdns/pull/10527

Is there any another way, how we can solve log rotation for dnsdist?

**Comment by rgacogne** [comment]
I'm afraid the issue you are having comes from the way the startup script on FreeBSD works, which is outside of our control and is maintained by the FreeBSD maintainer: https://cgit.freebsd.org/ports/tree/dns/dnsdist/files/dnsdist.in

I see the PID file is written using the `P` option to `daemon`, and the man page [1] suggests that this writes the supervisor PID indeed. It looks like you could modify that script to also write the child PID to a file using the `-p` option instead. Good luck! 

[1]: https://man.freebsd.org/cgi/man.cgi?daemon(8)
