### ISSUE TITLE
auth: lmdb hard-splits long LUA records into 255 byte segments that are recombined with spaces

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#12937]
- Program: Authoritative
 - Issue type: Bug report

### Short description
As already documented for AXFRs ([here](https://doc.powerdns.com/authoritative/lua-records/)) long LUA records get split into 255 byte segments on AXFRs. When re-combining these segments this is done with a space, causing LUA parsing errors when this segmentation hits code - this was already covered in other bug reports such as #8517 and #12845.
However this is not only the case for AXFR but also when storing data in lmdb. For me a `pdnsutil b2b-migrate` action from gmysql to lmdb happily separated quite some LUA code which I then had to manually fix, splitting it in proper places instead of the hard limit.
As discussed this could just be documented however I think it might be more feasible to just split LUA code at existing spaces within that code instead of the hard limit at 255 bytes. That way the space character introduced later when recombining would no longer break code but appear at more or less "expected" places.

### Environment

 - Operating system: Ubuntu 20.04 LTS
 - Software version: 4.8.0-1pdns.focal
 - Software source: PowerDNS repo

### Steps to reproduce
1. Set-up lmdb backend
2. Add long LUA record (>255 bytes) via `pdnsutil b2b-migrate` / `pdnsutil edit-zone` / API ..
3. Try to query the record
4. List zone contents and notice a hard segment split at 255 bytes

### Expected behaviour
Not breaking LUA code.

### Actual behaviour
Broken LUA code - hard segmentation at 255 byte boundaries which introduces a space at that position before parsing.

### Other information
As discussed.

**Comment by Habbie** [comment]
how do you feel about #14021?

**Comment by aj-gh** [comment]
Looks good, thanks.
