### ISSUE TITLE
Are there any plans for a `pdns-backend-lmdb` package in the `Alpine Linux APK Repository`?

### ISSUE THREAD

**Issue by YoungjuWang** [PowerDNS/pdns#12940]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Description

I want to use lmdb backend  with Alpine Linux. but There is no package about lmdb backend.

Are there any plans for a `pdns-backend-lmdb` package in the `Alpine Linux APK Repository`?
https://pkgs.alpinelinux.org/packages?name=pdns-backend-lmdb&branch=edge&repo=&arch=&maintainer=

**Comment by Habbie** [comment]
I did in fact write this on my TODO list last week.

Maybe you can try filing a merge request?

**Comment by YoungjuWang** [comment]
Hi, @Habbie
I can't find the code to push the backend package to the Alpine repository, let me know where it is and I'll try.

**Comment by Habbie** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/pdns

**Comment by hlindqvist** [comment]
MR at https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/58774

**Comment by Habbie** [comment]
Thanks! Approved there. Will close here if merged there.
