### ISSUE TITLE
pdns_control show foo does not error

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#1295]
$ ./pdns_control --socket-dir=. show udp6-queries
    0
    $ ./pdns_control --socket-dir=. show foo
    0

(should also check rec_control)

**Comment by Whissi** [comment]
Also, the help says
```
# pdns_control --config-dir=/etc/powerdns help
[...]
show <statistic>                 show a specific statistic or * to get a list
[...]
```
but
```
# pdns_control --config-dir=/etc/powerdns show *
Wrong number of parameters
# pdns_control --config-dir=/etc/powerdns version
3.4.2
```

**Comment by rubenk** [comment]
You'll need to quote the '*' since it's expanded by your shell.
```
sudo pdns_control  show  '*'
corrupt-packets=0,deferred-cache-inserts=0,deferred-cache-lookup=0,dnsupdate-answers=0,dnsupdate-changes=0,dnsupdate-queries=0,dnsupdate-refused=0,packetcache-hit=0,packetcache-miss=4,packetcache-size=0,query-cache-hit=0,query-cache-miss=14,rd-queries=4,recursing-answers=0,recursing-questions=0,recursion-unanswered=0,security-status=0,servfail-packets=0,signatures=0,tcp-answers=0,tcp-queries=0,timedout-packets=0,udp-answers=4,udp-answers-bytes=204,udp-do-queries=0,udp-queries=3,udp4-answers=4,udp4-queries=4,udp6-answers=0,udp6-queries=0,key-cache-size=1,latency=59,meta-cache-size=2,qsize-q=0,signature-cache-size=0,sys-msec=2443,uptime=0,user-msec=713,
```

**Comment by Whissi** [comment]
You are right, my fault. But *pdns_control(8)* says
```
show <variable>
              Show a single statistic, as present in the output of the list command.
```
It is mentioning a dedicated *list* command which is working but not documented in the man page itself nor in pdns_control's help.

Because an asterisk is a problematic character, shouldn't we add the *list* command to the man page and pdns_control help and also use the same help text from the *show* command in man page in pdns_control's help?

**Comment by rubenk** [comment]
list is documented now, it wasn't in 3.4.2.

**Comment by rubenk** [comment]
Since * is so probematic, how about adding 'show all' instead?

**Comment by Whissi** [comment]
:+1: but when we already have a dedicated and documented *list* command, this is not needed I think.
I'll check current master later and fill a new bug/PR if I think something could be improved.

**Comment by rubenk** [comment]
Great, thanks!
