### ISSUE TITLE
LUA : pickwrandom method not always resturning values , WHY ?

### ISSUE THREAD

**Issue by DavidRadan** [PowerDNS/pdns#12958]
- Program: Authoritative, 4.8 ( Mariadb Backend ) 
 - Issue type: Bug report

### Short description

Hello ,
We have the LUA function below that should distribute the requests among all these ip addreses , but for some reasom sometimes the address comes empty 
`"pickwrandom({ {15, '1.1.1.0' }, {15,  '1.1.1.1' } , {35, '1.1.1.2' },{35, '1.1.1.3'}  }) "`
### Environment

 - Operating system: AlmaLinux 9.2 (Turquoise Kodkod)
 - Software version: 4.8
 - Software source: PowerDNS  repo

### Steps to reproduce

1. Created LUA A record .
2. added "pickwrandom({ {15, '1.1.1.0' }, {15,  '1.1.1.1' } , {35, '1.1.1.2' },{35, '1.1.1.3'}  }) " in LUA script
3. tried to use https://www.nslookup.io/ or nslookup utility sometimes ( happens once in 20 times )  the record not returing any IP address .

### Expected behaviour

No record is returned once in 20-30 times 

### Actual behaviour

We have checked logs ( log level 9 )  no errors can be found .... 
Please check the image link below :
https://ibb.co/LkBT15r

OUR SLAVE PDNS.CONF :

**********************************************************************
server-id=server name deleted
allow-notify-from=ip1,ip2,ip3
launch=gmysql,geoip
geoip-database-files=/usr/share/GeoIP/GeoLite2-Country.mmdb
autosecondary=yes
master=no
loglevel=9
secondary=yes
disable-syslog=no
disable-axfr=no
security-poll-suffix=
guardian=yes
gmysql-host=127.0.0.1
gmysql-port=3306
gmysql-dbname=pDB
gmysql-user=user
gmysql-password=password
gmysql-dnssec=no
local-address=IPLOCAL,127.0.0.1
local-port=53
setgid=pdns
setuid=pdns
slave-cycle-interval=60
log-dns-details=on
logging-facility=0
log-dns-queries=yes
query-cache-ttl=300
enable-lua-records=yes
webserver=yes
webserver-address=127.0.0.1
api=yes
**********************************************************************

**Comment by Habbie** [comment]
Thank you for filling out the template. However, it seems you missed a comment:

> Before filing your ticket, please read our 'out in the open' support policy at https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/

**Comment by Habbie** [comment]
Also, it would be great if you could show `dig` output showing the problem. We cannot debug based on information from a lookup website.

**Comment by omoerbeek** [comment]
To illustrate why is is important to show, _exact, unedited_ configuration: I had a similar issue and it turned out to be a subtle syntax (whitespace) error in one of the IP addresses. So please show the _exact_ LUA record as it is stored in your database. Anything other wastes our and your time.

**Comment by DavidRadan** [comment]
Dear @Habbie 
My appologies for not following the rules , I will pay attention to the detailes next time .
I have tried to repreduce this issue via dig withnot much success otherwise i would attach this in the ticket .

Dear @omoerbeek 
Thanks for your detailed reply  ,Please find below is the excat lua record, I have copied this from the database column  :

A "pickwrandom({ {15, '1.1.1.1' }, {15,  '2.2.2.2' } , {35, '3.3.3.3' },{35, '4.4.4.4'}  }) "

Regards,
David

**Comment by Habbie** [comment]
> I have tried to repreduce this issue via dig with not much success otherwise i would attach this in the ticket .

Please show us the output of your "not much success"

**Comment by DavidRadan** [comment]
I think i have found something in the logs , I see many errors from pdns_server with the following error ,i'm sure that it musbe related ! what could cause such error ??

Jun 30 16:39:48 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 192.241.200.163: Timeout reading data
Jun 30 18:06:22 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 192.241.221.13: Timeout reading data
Jun 30 22:45:07 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 36.225.136.74: Timeout reading data
Jul 01 01:06:34 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 192.241.230.9: Timeout reading data
Jul 01 03:11:17 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 162.243.129.34: Timeout reading data
Jul 01 16:38:07 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 198.199.100.40: Did not fulfill read from TCP due to EOF
Jul 02 01:19:19 ns-02.  pdns_server[163888]: TCP Connection Thread died because of network error: Error reading DNS data from TCP client 198.199.117.128: Timeout reading data


https://ibb.co/YXxBqXS

Regards,
David 


dig 


 dig @82.x.x.x test.test.com

; <<>> DiG 9.11.26-RedHat-9.11.26-6.el8 <<>> @82.x.x.x test.test.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26474
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;mtest.test.com. IN      A

;; ANSWER SECTION:
test.test.com. 1800 IN  A       1.1.1.1

;; Query time: 6 msec
;; SERVER: 82.x.x.x#53(82.x.x.x)
;; WHEN: Mon Jul 03 15:42:28 IDT 2023
;; MSG SIZE  rcvd: 74

**Comment by Habbie** [comment]
> My appologies for not following the rules , I will pay attention to the detailes next time .

You said this.



> dig @82.x.x.x test.test.com

And then you did this.

If you're unwilling to show us real data, we are unable to help. Furthermore, as there is no indication this is a bug, I'm closing this ticket.

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
