### ISSUE TITLE
Lua records are working, but client variables don't appear to be set.

### ISSUE THREAD

**Issue by PenelopeFudd** [PowerDNS/pdns#12986]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Lua is working, but the client variables don't seem to be accessible:

### Environment

 - Operating system: Ubuntu 20.04.4 LTS
 - Software version: PowerDNS Authoritative Server 4.7.4 
 - Software source: PowerDNS repository

### Steps to reproduce
1. Add `enable-lua-records=yes` to pdns.conf
2. Restart pdns_server
3. Add these records to a zone named `example.org`:
```
test.example.org   60      IN      LUA     TXT ";pdnslog('test running'); return who"
test2.example.org  60      IN      LUA     TXT ";pdnslog('test2 running'); return type(who)"
test3.example.org  60      IN      LUA     TXT ";pdnslog('test3 running'); return who.toString()"
test4.example.org  60      IN      LUA     TXT ";pdnslog('test4 running'); local x=newDN('test4.example.org');return x:toString()"
test5.example.org  60      IN      LUA     TXT ";pdnslog('test5 running'); pdnslog('test5 who='..(who.toString())); return '5.5.5.5'"
```
4. Try `dig +short @127.0.0.1 test.example.org txt` for each of the records above.

### Expected behaviour

I'd like to see the value of the `who` variable.

### Actual behaviour

For test.example.org, the string `test running` appears in the syslog but no record is returned.
For test2, the string `test2 running` is logged, and "userdata" is returned.  (As another test, type(xyzzy) gave "nil")
For test3, the string `test3 running` is logged, but no record is returned.
For test4, the string `test4 running` is logged, and "test4.example.org" is returned.
For test5, the string `test5 running` is logged, but nothing else, and no record is returned.

### Other information

```
# cat pdns.conf

setgid=pdns
setuid=pdns
launch=gsqlite3,geoip
gsqlite3-database=/var/lib/powerdns/external/pdns.sqlite3
geoip-database-files=/var/lib/GeoIP/GeoLite2-Country.mmdb
local-address=127.0.0.1
allow-notify-from=127.0.0.1/32
allow-axfr-ips=127.0.0.1/32
trusted-notification-proxy=127.0.0.1/32
socket-dir=/var/run/pdns_server
version-string=external_view
primary=yes
autosecondary=yes
secondary=yes
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=127.0.0.1/8
webserver-password=$scrypt$ln=10,p=1,r=.......
webserver-port=8080
webserver-print-arguments=yes
api=yes
api-key=$scrypt$ln=10,p=1,r=..........
loglevel=5
log-dns-details=yes
log-dns-queries=yes
edns-subnet-processing=yes
dnsupdate=yes
allow-dnsupdate-from=127.0.0.0/8
default-soa-content=ns1.example.org hostmaster.@ 0 10800 3600 604800 3600
xfr-cycle-interval=1
query-cache-ttl=5
cache-ttl=5
enable-lua-records=yes
```

**Comment by Habbie** [comment]
All these query results are expected based on your code. Your syslog should also have errors for test, test3 and test5 though.

So:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by PenelopeFudd** [comment]
Please realize there's a fine (nay, blurry) line between bug reports and support questions, yes?
In this case, the bug might be "not enough examples in the documentation".  :-)
