### ISSUE TITLE
auth: records aren't shuffled in the responses for TCP queries

### ISSUE THREAD

**Issue by thestinger** [PowerDNS/pdns#13003]
- Program: Authoritative
 - Issue type: Bug report

### Short description

Records aren't shuffled in the responses for TCP queries but rather they're always returned in the same order. This will have an impact on load balancing if the resolver querying the server always uses the first response or does round-robin instead of randomizing the order.

### Environment
 - Operating system: Arch Linux
 - Software version: 4.8.1-1
 - Software source: Operating system repository

### Steps to reproduce

I think this will occur with any PowerDNS setup, but this is ours:

https://github.com/GrapheneOS/ns1.grapheneos.org

We use the GeoIP backend and Lua records, but this occurs for regular records too.

You can easily reproduce this querying anything with multiple answers via TCP. For example:

```bash
for i in {1..10}; do drill -t releases.grapheneos.org @ns2.grapheneos.org; done
```

Alternatively:

```bash
for i in {1..10}; do dig +tcp releases.grapheneos.org @ns2.grapheneos.org; done
```

### Expected behaviour

Responses via TCP should be randomized like responses via UDP.

### Actual behaviour

The order of records is the same every time when queried via TCP.

### Other information

This isn't impacted by the packet cache, query cache or `consistent-backends`. I have not yet tried other backends, but I don't see a way it could be specifically caused by the GeoIP backend.

This change appears to have been a side effect of avoiding shuffling in AXFR from all the way back in 2005:

e9dd48f9018ef291849c881d88faa66baab5c592

```diff
-  if(!arg().mustDo("no-shuffle")) {
+  if(!d_tcp && !arg().mustDo("no-shuffle")) {
```

**Comment by Habbie** [comment]
it might make sense to have a `d_xfr` flag next to `d_tcp`. Want to try your hand at writing a patch?
