### ISSUE TITLE
dnsdist: Ponder adding a better accessor for rules

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#13007]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
Currently, if one wants to get the number of matches of a given rule from Lua, the only option is to use `getAction(<rule number>):getStats()['']` which requires finding the position of the rule first.
It would be better if:
- `addAction` returned a reference to the created rule
- `getAction` accepted a UUID and/or a rule name

A bit unrelated but `getTopRules` and friends seems to return a `vector` instead of a Lua array, which makes them useless.

**Comment by jacobbunk** [comment]
Notice that `getStats()` appears to only be implemented for TeeAction() at this time.
