### ISSUE TITLE
pdns-tools: Multiple tools missing from package description

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#13016]
- Program: Authoritative / pdns-tools
 - Issue type: Bug report / Cosmetics

### Short description
[`pdns-tools` package descriptions for Debian / Ubuntu](https://github.com/PowerDNS/pdns/blob/29d9168874867c712da624bc4173b62f07cb79bf/builder-support/debian/authoritative/debian-buster/control#L55) don't list all tools contained within `pdns-tools` which is a bit confusing when looking for a specific tool (such as `calidns` or `sdig`).

### Other information
The following tools seem to be missing from the description section of the control file.
I could submit a PR if you're happy with these descriptions.

calidns: Resolver benchmark tool
dnspcap2calidns: PCAP conversion tool
dnspcap2protobuf: PCAP conversion tool
dumresp: Dummy DNS responder
nproxy: DNS notification proxy
pdns_notify: Simple tool for sending DNS notifies
sdig: dig-like tool supporting DoH, DoT, PROXY-protocol and XPF
stubquery: Stub resolver query tool

**Comment by Habbie** [comment]
> I could submit a PR if you're happy with these descriptions.

That would be great!
