### ISSUE TITLE
calidns build fails due to missing libarc4random.la

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#13025]
- Program: calidns
 - Issue type: Bug report

### Short description

`calidns` fails to build, probably due to a similar build issue as fixed for the recursor in PR #13022 

### Environment
 - Operating system: Ubuntu 22.04
 - Software version: latest master (015dbc1)
 - Software source: compiled yourself

### Steps to reproduce

```
cd pdns/ && make -j2 calidns
```

### Expected behaviour

Successful compilation.

### Actual behaviour

```
#33 [pdns 18/24] RUN cd pdns/ && make -j2 calidns && mv calidns /usr/local/bin/calidns
#33 sha256:15ef7bc9daede7749919b4cfa73853a8fa868c6d2b2e93fbfc12259098de5805
#33 0.429   CXX      base32.o
#33 0.430   CXX      base64.o
#33 0.864   CXX      calidns.o
#33 1.366   GEN      dnslabeltext.cc
#33 1.371   CXX      dnsname.o
#33 5.396   CXX      dnsparser.o
#33 9.714   CXX      dnsrecords.o
#33 14.28   CXX      dnswriter.o
#33 18.89   CXX      ednsoptions.o
#33 21.71   CXX      ednssubnet.o
#33 24.03   CXX      iputils.o
#33 28.58   CXX      logger.o
#33 29.82   CXX      misc.o
#33 31.81   CXX      nsecrecords.o
#33 36.25   CXX      qtype.o
#33 37.89   CXX      rcpgenerator.o
#33 39.32   CXX      sillyrecords.o
#33 44.85   CXX      statbag.o
#33 46.34   CXX      svc-records.o
#33 49.73   CXX      unix_utility.o
#33 52.18   CXX      dnslabeltext.o
#33 55.28   CXXLD    calidns
#33 55.41 libtool:   error: cannot find the library '../ext/arc4random/libarc4random.la' or unhandled argument '../ext/arc4random/libarc4random.la'
#33 55.41 make: *** [Makefile:2996: calidns] Error 1
#33 ERROR: executor failed running [/bin/sh -c cd pdns/ && make $PDNS_MAKEFLAGS calidns && mv calidns /usr/local/bin/calidns]: exit code: 2
```

### Other information

Related to PR #13022

**Comment by wojas** [comment]
Running `make -C ext` before the make resolves the issue.

Leaving this open in case a better build fix is desired or docs need to be updated, but feel free to close it if not.

**Comment by omoerbeek** [comment]
We only document the toplevel procedure (.e. the dir you run `autoreconf -vi` and `./configure` in. I don't think it's worth the time to document how to build  specific targets, especially as the build system is likely to change.
