### ISSUE TITLE
Protobuf logging: include worker ID and cache information

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#13020]
- Program: Recursor, dnsdist
 - Issue type: Feature request

### Short description

Extend the DNSMessage protobuf logs with information about:

- Worker (thread) ID
- Cache hit information
- An maybe Process ID

### Usecase

When debugging issues using the event logs, it is very useful to have information about:

- Which worker handled the query, to inspect patterns that involve the same worker.
- Whether the query was cached, and if it was served from the packet cache or the query cache.

Both dnsdist and the recursor already allows setting the `serverIdentity` field to distinguish between multiple instances on the same host:

- dnsdist since 1.3.3 with `setServerIdentity`.
- recursor with `server-id`, defaulting to the hostname.

### Description

Draft fields that could be added to the DNSMessage:

```proto
optional uint64 workerId = ...;    // could be a thread ID
optional bool packetCacheHit = ...;
optional uint32 outgoingQueries = ...;  // indirectly tells you if it was served from the query cache
```

The `workerId` would do the same when pinpointing to a specific worker. This can be useful for debugging packet cache related issues.

The `packetCacheHit` would tell if the query was served from the packet cache.

For the query cache, a boolean would not suffice, because the response may require several lookups. Instead the number of outgoing queries could be reported. This can be helpful when analysing response latency. A value of 0 would mean that the query was served entirely from cache, with no outgoing queries.

It may also be useful to add:

```proto
optional uint64 processId = ...;
```
 
Although a `serverIdentity` is already present and could be used to distinguish between multiple instance on the same host, it defaults to the hostname of the server and may not have been explicitly overridden per instance on all deployments. A PID would offer an alternative way to distinguish between instances on the same host, and would allow tracking when the instance was restarted.

**Comment by omoerbeek** [comment]
Implemented in  #14257
