### ISSUE TITLE
Unable to set hint-file to 'no' or 'no-refresh'

### ISSUE THREAD

**Issue by Teddyhoang** [PowerDNS/pdns#13053]
- Program: Recursor 
 - Issue type: Bug report

### Short description

I want to disable the processing of root hint by setting hint-file in my config file to no

```
api-config-dir=/etc/powerdns/recursor.d
api-key=changeme
config-dir=/etc/powerdns
daemon=yes
disable-syslog=no
forward-zones=example.com=x.x.x.x:53

#
hint-file=`no-refresh`
#

local-address=0.0.0.0
local-port=53
log-timestamp=yes
logging-facility=1
loglevel=6
setgid=pdns
setuid=pdns
```
But when i restart recursor give me error tell that "Unable to open file 'no': No such file or directory: No such file or directory"

### Environment

 - Operating system:  Ubuntu 22.04 LTS
 - PowerDNS recursor version: 4.8.4 

### Steps to reproduce

1.  stop recursor service
2.  change hint-flie in config file to 'no'
3.  start recursor service

### Expected behaviour

- PowerDNS Recursor start normal
- root hint disable

### Actual behaviour

- Unable to start Recursor
- hint-file recognize value as path

**Comment by rgacogne** [comment]
`no-refresh` has been introduced in 4.9, as stated in the documentation [1], and you are running 4.8.4. `no` should work, though, have you tried without the `'`s which are not supported?

[1]: https://docs.powerdns.com/recursor/settings.html#hint-file

**Comment by Teddyhoang** [comment]
Thank for your replies
