### ISSUE TITLE
[Recursor] Add priority for forward-zone

### ISSUE THREAD

**Issue by Teddyhoang** [PowerDNS/pdns#13069]
- Program: Recursor 
 - Issue type: Feature request

### Short description

Add options priority of zones in forward-zones features
### Usecase

I want to configure in forward-zones with priority order:
- my_zones_domains=my_ip_powerdns [1]
- *(exclude_my_zones_domains)=ip_dns_domain [2]
- *(exclude_my_zones_domains)=8.8.8.8;8.8.4.4 [3]

### Description

As i understand recursor now set up priority by response time. If both servers have answer, take the first priority answer. If just second priority have answer then take the second priority answer.

**Comment by omoerbeek** [comment]
The forwarding matching takes the most specific forwarding domain matching the name queried. It then decides between the IPs given for that domain based on response times. We don't plan for anything more complex. You should consider using dnsdist, which has many ways to specify forwarding policies.
