### ISSUE TITLE
recursor: total cache hit rates missing

### ISSUE THREAD

**Issue by terrorobe** [PowerDNS/pdns#1307]
Verify if the assumption is right:

if you have 94% PC hits, 6% PC misses and
10% recordcache hits, 90% recordcache misses

this should mean that 10% of the PC misses were hits in the record cache, so the total cache hit rate should be 94.6%.

If this approach is correct, please document and maybe expose as additional statistics value.

**Comment by pieterlexis** [comment]
@Habbie is this assumption correct?

**Comment by Habbie** [comment]
Don't know offhand, to be fair.

**Comment by pieterlexis** [comment]
I'm fixing up the stats-page for the recursor.. so I'll test

**Comment by omoerbeek** [comment]
You can compute all kind of aggregate numbers indeed. A tool used to view the stats can compute and display these, depending on what the operator wants to see.
