### ISSUE TITLE
listen-on iface ?

### ISSUE THREAD

**Issue by lejeczek** [PowerDNS/pdns#13081]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Description

Hi guys.

I'm coming from ISC bind as a complete newbie to PowerDNS thus it's very likely - though I sroogled & braved the net - that I'm missing what I believed was most basic & common, namely **listen-on** interface.
But if it really is **not** possible, not implemented then - and I am puzzled why would it be only me asking for this, really? - I'd urge to have PowerDNS enhanced by this simple albeit powerful feature.

many thanks, L.

**Comment by Habbie** [comment]
Hello! It is unclear to me what you are asking for. What are you trying to accomplish?

**Comment by lejeczek** [comment]
Wow - an amateur would say, I'm saying - how strange indeed that nomenclature common some place might be alien in other places :) I was expecting that - like pretty much any software which has to do with networking - I'd be able to tell PowerDNS to bind to/listen on a specific net iface.
I see **port** is configurable via configs but I failed - and I sroogled as I confessed - to find anything on iface, but it's possible that I'm failing miserably.

**Comment by Habbie** [comment]
What would the equivalent BIND config look like?

**Comment by omoerbeek** [comment]
You seem to suggest that bind can do what yo want, but looking through https://bind9.readthedocs.io/en/latest/reference.html#namedconf-statement-listen-on I don't see it.

**Comment by lejeczek** [comment]
`listen-on port 53 { 127.0.0.1; }`

**Comment by Habbie** [comment]
auth, rec: `local-address=127.0.0.1:53`. dnsdist: see the docs about `setLocal` or `addLocal`.

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by lejeczek** [comment]
But still, this one last, quick question - can PowerDNS use an actual net interface name as oppose to IP address?

**Comment by Habbie** [comment]
dnsdist's `addLocal`/`setLocal` takes an interface argument. Auth and rec have no such support.
