### ISSUE TITLE
packaging: get rpm defaults in line with what epel does

### ISSUE THREAD

**Issue by terrorobe** [PowerDNS/pdns#1310]
Use /etc/pdns & /etc/pdns-recursor as config paths

/var/lib/mysql/mysql.sock seems to be the official path to the mysql socket directory by now, not /var/run/mysqld/mysqld.sock

**Comment by Habbie** [comment]
Can somebody check if this is fixed now?

**Comment by pieterlexis** [comment]
> Use /etc/pdns & /etc/pdns-recursor as config paths

We do this

> /var/lib/mysql/mysql.sock seems to be the official path to the mysql socket directory by now, not /var/run/mysqld/mysqld.sock

We use the MySQL client libraries defaults if there are no settings made (we don't ship settings-files for the backends in the rpms)
