### ISSUE TITLE
recursor systemd unit: time-sync.target causes ordering loop, startup fails

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#13115]
- Program: Recursor
 - Issue type: Bug report

### Short description
#12248 added `time-sync.target` to the `After=` line of the recursor systemd unit. This is causing breakage, at least on one system, during boot:

```
Aug 14 09:34:27 node23 systemd[1]: nss-lookup.target: Found ordering cycle on pdns-recursor@3.service/start
Aug 14 09:34:27 node23 systemd[1]: nss-lookup.target: Found dependency on time-sync.target/start
Aug 14 09:34:27 node23 systemd[1]: nss-lookup.target: Found dependency on chronyd.service/start
Aug 14 09:34:27 node23 systemd[1]: nss-lookup.target: Found dependency on nss-lookup.target/start
Aug 14 09:34:27 node23 systemd[1]: nss-lookup.target: Job pdns-recursor@3.service/start deleted to break ordering cycle starting with nss-lookup.target/start
```

### Environment

 - Operating system: SLES15-SP4
 - Software version: 4.9.0
 - Software source: 

### Steps to reproduce
1. upgrade from 4.8.x to 4.9.0

### Expected behaviour
Recursor starts.

### Actual behaviour
Recursor does not start on boot.

### Other information
Removing `time-sync.target` from the line allows Recursor to start again.

**Comment by zeha** [comment]
I'm wondering why pdns-recursor.service.in has both `Wants=nss-lookup.target` and `Before=nss-lookup.target` tho.

**Comment by kpfleming** [comment]
Yeah, `Before` should be sufficient.

**Comment by paddg** [comment]
> On that system `pdns-recursor.service` has a dependency on `nss-lookup.target`? That seems broken.
> 
> This is also an 'instance' unit of `pdns-recursor.service`, it would be useful to know if the admin has put any overrides against that unit (or against `nss-lookup.target`).

I'm the admin. Unfortunately I'm not familiar with the dependencies in the systemd units. But I'm happy to look something up if you give me specific instructions. What do you mean by unit overrides?

**Comment by kpfleming** [comment]
Thanks; those overrides aren't affecting the dependency resolution. :-)

**Comment by paddg** [comment]
Yes, just didn't want to hide it

**Comment by paddg** [comment]
> ### Expected behaviour
> 
> Recursor starts.
> ### Actual behaviour
> 
> Recursor does not start.

That is not completely right. The problem only occurs when booting.

**Comment by Habbie** [comment]
> That is not completely right. The problem only occurs when booting.

thanks, edited

**Comment by omoerbeek** [comment]
There are several issues mentioned with the unit file. It would be wonderful if somebody familiar with the subject cold prepare a PR fixing the issues mentioned. Thanks in advance!

**Comment by paddg** [comment]
I've compared the dnsdist and the pdns-recursor unitfiles.

Recursor:
```
Wants=network-online.target nss-lookup.target
Before=nss-lookup.target
After=network-online.target time-sync.target
```

dnsdist:
```
Wants=network-online.target
After=network-online.target time-sync.target
```

If I change the Recursor unit file to the dnsdist version (removing the "Before" line), the issue disappears.

**Comment by omoerbeek** [comment]
Thanks! I'll prepare a PR.
