### ISSUE TITLE
consistent-backend property for remote HTTP backends doesn't work as expected

### ISSUE THREAD

**Issue by glebkin** [PowerDNS/pdns#13140]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Hi, I'm using remote HTTP backend for lookups and I would like to receive lookup requests with specific qtype rather than qtype=ANY.
I found the following option - https://doc.powerdns.com/authoritative/settings.html#consistent-backends and set it to `no` in pdns.conf, but it doesn't work.
Power DNS still sends ANY requests to my backend.

### Environment
 - Operating system: macOS aarch64
 - Software version: master
 - Software source: compiled from master branch

### Steps to reproduce
1. Config:
```
launch=remote
remote-connection-string=http:url=http://host.docker.internal:8082/api/v1,timeout=2000
consistent-backends=no
receiver-threads=10
log-dns-queries=yes
log-dns-details=yes
loglevel=6
query-cache-ttl=0
local-address=0.0.0.0
local-port=53
zone-cache-refresh-interval=0
api=yes
webserver=true
webserver-address=0.0.0.0
webserver-port=8090
webserver-allow-from=0.0.0.0/0
```
2. Run `dig -p 53 @127.0.0.1 example.com A`

### Expected behaviour
PowerDNS makes `/api/v1/lookup/example.com/A` request to our HTTP backend

### Actual behaviour
PowerDNS makes `/api/v1/lookup/example.com/ANY` request to our HTTP backend

### Other information
I found the following code in packethandler.cc, which is invoked before lookup:
```B.lookup(QType(QType::ANY), target, d_sd.domain_id, &p);```
https://github.com/PowerDNS/pdns/blob/master/pdns/packethandler.cc#L1577

So, `d_handle.qtype=s_doANYLookupsOnly ? QType::ANY : qtype;` inside of lookup function makes no sense
https://github.com/PowerDNS/pdns/blob/master/pdns/ueberbackend.cc#L639

**Comment by Habbie** [comment]
> I found the following option - https://doc.powerdns.com/authoritative/settings.html#consistent-backends and set it to `no` in pdns.conf, but it doesn't work.

Setting it to `no` does not mean PowerDNS will always ask for the exact type. It only means PowerDNS is -allowed- to do that, if it wanted to.

You will have to handle ANY queries in your backend, sorry.
