### ISSUE TITLE
dnsdist: frontend-noerror/nxdomain/servfail metrics not counting cache hits anymore

### ISSUE THREAD

**Issue by qvr** [PowerDNS/pdns#13148]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Global `frontend-*` metrics no longer seem to count cache hits. Likely related to the cache hit accounting change in #12405

### Environment
 - Operating system: RHEL
 - Software version: 1.8.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. Run dnsdist with cache, blast queries
2. Check metrics, compare cache-hits/misses, responses and the different frontend metrics.

### Expected behaviour
Cache hits would be counted in the different `frontend-*` metrics.

### Actual behaviour
Only non cache hits are counted, ie. the frontend metrics are actually backend metrics. :-)

```
cache-hits                                 31599155    latency10-50                                  654685
cache-misses                                3310691    latency100-1000                               103331
..
dyn-blocked                                       0    responses                                   34903454
empty-queries                                  3754    rule-drop                                          0
fd-usage                                        222    rule-nxdomain                                      0
frontend-noerror                            3297434    rule-refused                                       0
frontend-nxdomain                            282505    rule-servfail                                      0
frontend-servfail                             32702    rule-truncated                                     0
```

**Comment by rgacogne** [comment]
I have not been able to reproduce this on master, testing 1.8.0 now.

**Comment by qvr** [comment]
> Reproduced on 1.8.0 when `recvmmsg/sendmmsg` support is enabled via `setUDPMultipleMessagesVectorSize()`.

Ah, that makes sense, as we indeed run with `setUDPMultipleMessagesVectorSize(10)`, so I guess we only see 1 metric increase per 10 queries. That rate also happens to be almost exactly our cache hit rate, so my bad for the wrong interpretation. :-)
