### ISSUE TITLE
Catalog group editing does not increment the SOA serial in the catalog zone

### ISSUE THREAD

**Issue by velechac** [PowerDNS/pdns#13204]
- Program: Authoritative 
 - Issue type: Bug report

### Short description
If a catalog group is modified in a member zone, the SOA serial is not incremented in the corresponding catalog zone and slaves are not notified of that change.

### Environment

 - Operating system: Ubuntu 20.04.6
 - Software version: 4.7.4 (PostgreSQL backend is used)
 - Software source: PowerDNS repository

### Steps to reproduce

1. Set up an environment with a catalg zone and a member zone
2. Let slave servers configure member zone (optional)
3. Change the group in the member zone, e.g. via pdnsutil
    ```
    pdnsutil set-option example.com producer group testgroup
    ```

### Expected behaviour
The SOA serial in the catalog zone should be incremented in the same way as it is when listing or delisting a member zone.

### Actual behaviour
SOA serial is not incremented and these changes are not notified to slave servers.

**Comment by mind04** [comment]
I can confirm the issue. Group is missing from the catalog hash calculation.

A possible workaround is to remove the CATALOG-HASH metadata from the catalog zone after modifying group data.

For the record, the pdnsutil command above is missing 'group' and should be like this:
```
pdnsutil set-option example.com producer group testgroup
```

**Comment by velechac** [comment]
> For the record, the pdnsutil command above is missing 'group' and should be like this:
> 
> ```
> pdnsutil set-option example.com producer group testgroup
> ```
Thank you, I've fixed it. My mistake when I replaced the real member domain and group.

**Comment by Habbie** [comment]
> when I replaced the real member domain and group.

Please note that the issue template explicitly asked you not to do that.
