### ISSUE TITLE
dnsdist: add selected backend IP in DNSResponse

### ISSUE THREAD

**Issue by dmachard** [PowerDNS/pdns#13201]
- Program: dnsdist
 - Issue type: Feature request

### Short description

It would be useful to get the selected backend IP in the DNSResponse for DNStap/Protobuf logging purpose.

### Usecase

I want to be able to filter replies per backend IP from DNS logs, to facilitate traffic debugging

### Description

Since dnsdist 1.8, the [pool](https://dnsdist.org/reference/dq.html?highlight=dnsquestion#DNSQuestion.pool) attribute is available and it can be added in DNStap or Protobuf messages (with extra field) to get more details regarding pools routing in DNS logs. In the same way, it will be useful to also have the selected backend IP. 

I took a look to the code, I can make a pull request for that but I prefer to check with you if you are OK with this idea.

**Comment by rgacogne** [comment]
The general idea makes sense to me! A Lua binding to read `DNSResponse::d_downstream` would be nice, and making it exportable to DNStap/Protobuf as well.
