### ISSUE TITLE
auth4.8 doesnot build with boost1.53.0  for boost::noncopyable

### ISSUE THREAD

**Issue by C2python** [PowerDNS/pdns#13219]
- Program: Authoritative
 - Issue type: Bug report

### Short description

Doesnot build auth4.8 with boost1.53.0  g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)  centos7 

### Environment
 - Operating system:  centos7
 - Software version: auth4.8
 - Software source: compiled myself

### Steps to reproduce
1. git clone pdns
2. install deps with boost-devel 1.53.0 g++ (GCC) 9.3.1
3. autoreconf -vi
4. ./configure --prefix=/usr/local/powerdns --enable-verbose-logging  --with-libcurl  --enable-lua-records 
5. make
6. then errors

<img width="568" alt="image" src="https://github.com/PowerDNS/pdns/assets/10085996/9a223dc3-92b0-47ff-9ee2-e56a30b6bd22">

It seems that it not included boost/noncopyable.hpp. When I add this hpp in some file, it will passed.

**Comment by Habbie** [comment]
Can you try with boost169 and devtoolset-11?

**Comment by C2python** [comment]
Solution:
I build and install boost 1.69 from source. It work fine.
Boost169 from EPEL  will be installed in /usr/include/boost169/boost. cause this error.

**Comment by omoerbeek** [comment]
https://github.com/PowerDNS/pdns/blob/master/builder-support/specs/pdns.spec is used to build our packages. It uses the following for CentoS7:
```
export CPPFLAGS=-I/usr/include/boost169
export LDFLAGS=-L/usr/lib64/boost169
```
This should enable you to use the EPEL installed boost as well.

**Comment by C2python** [comment]
Update:
I install boost169 from EPEL. Then, create symbolic as:
ln -s /usr/include/boost169/boost /usr/include/
ln -s  /usr/lib64/boost169/libboost_* /usr/lib64/

Also work fine.

**Comment by C2python** [comment]
> https://github.com/PowerDNS/pdns/blob/master/builder-support/specs/pdns.spec is used to build our packages. It uses the following for CentoS7:
> 
> ```
> export CPPFLAGS=-I/usr/include/boost169
> export LDFLAGS=-L/usr/lib64/boost169
> ```
> 
> This should enable you to use the EPEL installed boost as well.

Yeah, this work fine. Thank you!
