### ISSUE TITLE
rec-5.0.0-alpha1 doesn't respect SYSCONFDIR in settings/cxxsettings-generated.cc (generated by table.py + generate.py)

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#13259]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description
When passing --sysconfdir=/usr/local/etc/pdns to configure, in 4.9.1 the directory set will be used as the location for the configuration files.
In 5.0.0-alpha1 a file is generated through 2 (?) python scripts, settings/table.py and settings/generate.py, which set a static default value of '/etc/powerdns'.

### Environment

 - Operating system: FreeBSD 13.2-RELEASE
 - Software version: 5.0.0-alpha1
 - Software source: PowerDNS generated tarball

### Steps to reproduce

1. Run configure with the --sysconfigdir=<dir> argument
2. Run (g)make install
3. Start the recursor 

### Expected behaviour

Load information from the directory that was set in --sysconfigdir

### Actual behaviour
It used default values, since there is no configuration file to load in /etc/powerdns (the directory doesn't exist on my machine)

### Other information

I patched both table.py and generate.py so it will respect SYSCONFDIR. Both patches can be found here:
https://www.cainites.net/files/powerdns/patch-settings_generate.py
https://www.cainites.net/files/powerdns/patch-settings_table.py

**Comment by omoerbeek** [comment]
Thanks for the issue and diffs. I do think the diffs are not complete, as the part that generates Rust code is not done. This will affect the code which determines if a YAML value has the default value.

**Comment by omoerbeek** [comment]
> Thanks for the issue and diffs. I do think the diffs are not complete, as the part that generates Rust code is not done. This will affect the code which determines if a YAML value has the default value.

Indeed. There's a slight complication as the rust compiler does not know about things like `-DSYSCONFDIR`.
