### ISSUE TITLE
webserver logs went missing

### ISSUE THREAD

**Issue by appliedprivacy** [PowerDNS/pdns#13291]
- Program: Recursor
 - Issue type: Bug report

### Short description

We used to have these events in our logs, but now we no longer have them when we fetch metrics:

```
[webserver] <uuid> 127.0.0.1:29022 "GET /metrics HTTP/1.0" 200 38276
```

### Environment
 - Operating system: Debian 12
 - Software version: 4.9.1
 - Software source: PowerDNS repository

### Steps to reproduce

1.  fetch metrics from the webserver endpoint
1.  watch the (absent) logs

### Expected behaviour

A log line like this when we curl the webserver:

```
[webserver] <uuid> 127.0.0.1:29022 "GET /metrics HTTP/1.0" 200 38276
```

### Actual behaviour

No log entries when fetching metrics.

### Other information

recursor.conf:

```
config-dir=/etc/powerdns
setuid=pdns
setgid=pdns

aggressive-nsec-cache-size=0
allow-from=127.0.0.0/8,109.70.100.0/24
dnssec=validate
dnssec-log-bogus=no
edns-padding-from=127.0.0.0/8,109.70.100.0/24
edns-padding-mode=padded-queries-only
extended-resolution-errors=yes
local-address=127.0.0.1:54,109.70.100.125:53,109.70.100.136:53
log-common-errors=no
log-rpz-changes=no
log-timestamp=yes
loglevel=3
structured-logging=no
max-busy-dot-probes=5
max-cache-entries=10000000
max-concurrent-requests-per-tcp-connection=1000
max-packetcache-entries=500000
new-domain-tracking=no
nothing-below-nxdomain=dnssec
pdns-distributes-queries=no
qname-minimization=yes
query-local-address=109.70.100.125,2a03:e600:100::178
quiet=yes
refresh-on-ttl-perc=10
threads=16
version-string=PowerDNS Recursor
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=127.0.0.1,::1
webserver-loglevel=normal
webserver-password=$scrypt$ln=10,p=1,r=8$....

lua-config-file=/etc/powerdns/config.lua

```

We also tried:
```
webserver-loglevel=detailed
```

**Comment by omoerbeek** [comment]
Normal webserver request are logged at level `Notice` (old logging) or `Info` (structured logging). As you have set `loglevel` to 3 both these levels are filtered out. So this does not seem to be a regression.

**Comment by omoerbeek** [comment]
@appliedprivacy any observation? Otherwise I'll close.

**Comment by appliedprivacy** [comment]
We agree that this can be closed.
