### ISSUE TITLE
arm64: eBPF rules never hits 

### ISSUE THREAD

**Issue by pettai** [PowerDNS/pdns#13306]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description
While testing eBPF filtering on a vanilla Ubuntu 22.04 jammy arm64 with the debian-based package of dnsdist 1.8, I never get rule hits. I’ve configured the arm64 system exactly the same as on an amd64 system that works fine (the ebpf rules hits and blocks), but no ebpf rule ever hits on the arm64 machine.

### Environment

 - Operating system: Ubuntu 22.04 jammy arm64
 - Software version: dnsdist 1.8.x
 - Software source: https://packages.debian.org/trixie/dnsdist, readily built packages in repo here: https://launchpad.net/~pettai/+archive/ubuntu/testing 

### Steps to reproduce

I've tested with methods from the docs:
https://dnsdist.org/advanced/ebpf.html

### Expected behaviour

The above examples hits and works on amd64 but not on the arm64 system

### Actual behaviour

There are no rule hits logged
```
> bpf:getStats()
bad.example.com. 255: 0
```

**Comment by rgacogne** [comment]
I'm afraid I cannot reproduce this issue :-/
I have compiled dnsdist 1.9.0-alpha1 on Ubuntu 22.04.3 inside an Arm64 VPS from Hetzner's cloud. The CPU is:
```
# lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           Neoverse-N1
    Model:              1
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r3p1
    BogoMIPS:           50.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 cr
                        c32 atomics fphp asimdhp cpuid asimdrdm
                         lrcpc dcpop asimddp ssbs
NUMA:
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-3
Vulnerabilities:
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec store bypass:    Mitigation; Speculative Store Bypass di
                        sabled via prctl
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Mitigation; CSV2, BHB
  Srbds:                Not affected
  Tsx async abort:      Not affected
```
dnsdist was compiled with `./configure` resulting in:
```
configure: Configuration summary
configure: =====================
configure:
configure: dnsdist configured with: (no options)
configure:
configure: CC: gcc (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0)
configure: CXX: g++ -std=c++17 (g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0)
configure: LD: /usr/bin/ld
configure: CFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O3 -Wall -Wextra -Wshadow -Wno-unused-parameter -fvisibility=hidden -g -O2
configure: CPPFLAGS:
configure: CXXFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O3 -Wall -Wextra -Wshadow -Wno-unused-parameter -Wmissing-declarations -Wredundant-decls -fvisibility=hidden -g -O2
configure: LDFLAGS: -Wl,-z -Wl,relro -Wl,-z -Wl,now  -rdynamic
configure: LIBS:
configure: BOOST_CPPFLAGS:
configure:
configure: Features enabled
configure: ----------------
configure: Lua: luajit
configure: Protobuf: yes
configure: systemd: no
configure: ipcipher: yes
configure: libedit: yes
configure: libsodium: no
configure: DNSCrypt: no
configure: dnstap: no
configure: re2: no
configure: SNMP: no
configure: DNS over TLS: no
configure: DNS over HTTPS (DoH): no
configure: h2o-evloop: no
configure: nghttp2: no
configure: cdb: no
configure: lmdb: no
configure:
```
and
```
# ./dnsdist --version
dnsdist 1.9.0-alpha1 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
Enabled features: ebpf ipcipher libedit protobuf recvmmsg/sendmmsg

```

Full configuration:
```
addLocal('159.69.20.47:8053')
setACL({'redacted'})

bpf = newBPFFilter({ipv4MaxItems=1024, ipv6MaxItems=1024, qnamesMaxItems=1024})
setDefaultBPFFilter(bpf)
dbpf = dynBlockRulesGroup()
dbpf:setQueryRate(3, 3, "Exceeded query rate", 10, DNSAction.Drop)
dbpf:setResponseByteRate(50, 5, "Exceeded resp BW rate", 10, DNSAction.Drop)

function maintenance()
        dbpf:apply()
end

newServer('9.9.9.9')
```

After sending a few queries from the IP allowed in the ACL, I get:
```
Inserting dynamic block for 78.202.236.73/32 for 10 seconds: Exceeded resp BW rate
> bpf:getStats()
78.202.236.73: 7
```
and the queries are indeed dropped.

**Comment by rgacogne** [comment]
Blocking based on the qname also works for me:
```
addLocal('159.69.20.47:8053')
setACL({'redacted'})

bpf = newBPFFilter({ipv4MaxItems=1024, ipv6MaxItems=1024, qnamesMaxItems=1024})
bpf:blockQName(newDNSName("evildomain.com"), 255)
setDefaultBPFFilter(bpf)
dbpf = dynBlockRulesGroup()
dbpf:setQueryRate(3, 3, "Exceeded query rate", 10, DNSAction.Drop)
dbpf:setResponseByteRate(50, 5, "Exceeded resp BW rate", 10, DNSAction.Drop)

function maintenance()
        dbpf:apply()
end

newServer('9.9.9.9')

```

```
> bpf:getStats()
evildomain.com. 255: 1
```

**Comment by pettai** [comment]
`dnsdist 1.8.1 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
Enabled features: cdb dns-over-tls(openssl) dns-over-https(DOH) dnscrypt ebpf fstrm ipcipher libedit libsodium lmdb outgoing-dns-over-https(nghttp2) protobuf re2 recvmmsg/sendmmsg snmp systemd`

I will try with your configuration to see how that works

**Comment by pettai** [comment]
Ok, the "modern"-type configuration using dynBlockRulesGroup() works for me too.
But it's not reported as eBPF in the logs, nor in the webserver GUI, both just shows it as a "regular" dynBlock 
(which I suppose also is true, since it's stated in the docs that a normal block rule is insert as well, in-case the eBPF machinary would fail...)

```
> showDynBlocks()
What                      Seconds   Blocks Warning    Action               Reason
X.X.X.X/32                10     5904 false      Drop                 Exceeded resp BW rate
```

(AFAIK ebpf rules/logs never carry a /mask)

`bpf:getStats()` shows the Drops though, so that's great.

**Comment by pettai** [comment]
Documentation https://dnsdist.org/advanced/ebpf.html is outdated, should be updated to conform with how eBPF blocking should be configured using dynBlockRulesGroup()
Also, the eBPF logging / webserver "Kernel-based dyn blocked netmask" never shows, that's the real issue

**Comment by rgacogne** [comment]
Thank you for testing and reporting back! https://github.com/PowerDNS/pdns/pull/13310 will update the documentation and make it more clear whether a dynamic block is eBPF-based or not.
As for the webserver output, I'm not sure how it actually works with the new syntax since I don't think we can use `registerDynBPFFilter` anymore. I'll have a look.

**Comment by rgacogne** [comment]
I could do that, of course, but I would really prefer fixing it :)

**Comment by rgacogne** [comment]
Now done in #13310 as well.
