### ISSUE TITLE
missing sysv init script in pdns-recursor 4.9

### ISSUE THREAD

**Issue by wwuck** [PowerDNS/pdns#13343]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor 
 - Issue type: Bug report

### Short description
I am running pdns-recursor `4.8.5-1pdns.bullseye` on multiple systems running Debian 11 with sysvinit init system and also some systems running Devuan 4 with sysvinit init system.  When I upgrade pdns-recusor to `4.9.1-1pdns.bullseye` I can no longer start pdns-recursor daemon.  It looks like `/etc/init.d/pdns-recursor` was removed somewhere in between these versions.

### Environment

 - Operating system: Debian 11.1
 - Software version: 4.9.1-1pdns.bullseye
 - Software source: PowerDNS repository 

### Steps to reproduce

1. Install Debian 11 with sysvinit init system or Devuan 4 with default init system choice (sysvinit).
2. Install latest pdns-recursor 4.8 from powerdns repository.
3. Upgrade pdns-recursor to 4.9 from powerdns repository.

### Expected behaviour

pdns-recusor service/daemon starts successfully.

### Actual behaviour

```console
# service pdns-recursor start
pdns-recursor: unrecognized service
# cat /etc/init.d/pdns-recursor
cat: /etc/init.d/pdns-recursor: No such file or directory
```

### Other information

I have read through all the changelogs for pdns-recursor 4.8 and 4.9 and I couldn't see any changes relating to sysv init.

**Comment by omoerbeek** [comment]
The Changelog ref is https://docs.powerdns.com/recursor/changelog/4.9.html#change-ee77e80e00b96ce7dfcd04a9ff7949d6
The removal of the sysv init script should have been mentioned explicitly, I suppose.

**Comment by omoerbeek** [comment]
Not that I know of. It's a matter of reducing maintenance burden for us.
