### ISSUE TITLE
rec: ponder introducing an ACL for RD=0 queries

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#13386]
Currently we handle RD=0 queries for all client allowed to send queries. We might restrict those queries, to make cache snooping harder.

Options are

- always disallow RD=0 queries
- only allow RD=0 queries for client addresses in `allow-rd0-from` ACL
- make `allow-rd0-from` dynamically settable via the REST API, like the existing `allow-from` and `allow-notify-from`.
- action on disallow: either drop or answer REFUSED
IMO, a settable ACL is nice (default empty), but I see little need for the REST API part. 

This is what others do:

- Knot has global switch with answer REFUSED, default: RD=0 is not allowed.
- Unbound has it tied to an ACL, action (refuse/drop)depends on other ACLs
- BInd has an ACL for this (allow-query-cache, exact semantics depend on if it is configured for recursion only, auth only or mixed), from reading it I think REFUSED is answered for non allowed RD=0 queries.

**Comment by rgacogne** [comment]
I still think this is security theater, because you can still determine whether an answer is in the cache by looking at the returned TTL or by measuring the response time. So if we really want to invest time in this feature, I would go with a single global switch to disable `RD=0` queries and be done with it.

**Comment by omoerbeek** [comment]
Agreed, though with RD=1 queries you also potentially modify the cache while snooping, so some analysis methods become harder.

**Comment by omoerbeek** [comment]
A question is how to handle RD=0. Currently the code is structured in such a way that disallowed queries are just dropped and while doing the query validation steps we do not have an existing way to answer `Refused`. I figure we can do a couple of things:

1) Drop the RD=0 query if not allowed, this can be done once we know we have a header, so very early.
2) Do the actual processing, and then late in then process check the `rd` flag and if needed answer with an empty response and rcode `Refused`. Advantage: simple to implement, disadvantage: the resolving work is done for nothing.
3. Implement a new function to answer `Refused` early in the processing. Advantage: might be useful for other/future cases as well. Disadvantage: extra work to implement.

**Comment by mnordhoff** [comment]
(And there's the minor problem for DNS admins on older OSes that old versions of 'dig +trace' make RD=0 root NS queries.)

**Comment by omoerbeek** [comment]
I went for option 2 with a shortcut at the "preresolve" spot.

**Comment by paddg** [comment]
Part of our "ratelimit" strategy in dnsdist is a `MaxQPSIPRule()` with a `SetNoRecurseAction()`  because it's not as strict as the `DropAction()` and still doesn't put a lot of load on the Recursor. This would break with the new default. Therefore we will probably accept the disadvantage of easier cache snooping.

**Comment by omoerbeek** [comment]
> Part of our "ratelimit" strategy in dnsdist is a `MaxQPSIPRule()` with a `SetNoRecurseAction()` because it's not as strict as the `DropAction()` and still doesn't put a lot of load on the Recursor. This would break with the new default. Therefore we will probably accept the disadvantage of easier cache snooping.

Would it work for you to refuse incoming RD=0 in dnsdist, so you catch the snooping attempt? The traffic between dnsdist and recursor then can still include RD=0 queries, but only when RD=0 is set by dnsdist.

Also,  a general warning for others reading this: in the recursor, if an RD=0 query does not find a cached entry, you will get an answer with no answer records and rcode `NoError`, aka a `NoData` answer. This is a legit answer, but *not* reflecting reality. So only do this when you've evaluated it works for your use-case.

**Comment by omoerbeek** [comment]
https://kb.isc.org/docs/aa-00482 has some on it. It's not harming you but there are (albeit somewhat far-fetched) scenarios where one client could determine something about the activity of other clients.

**Comment by hlindqvist** [comment]
> Also, a general warning for others reading this: in the recursor, if an RD=0 query does not find a cached entry, you will get an answer with no answer records and rcode `NoError`, aka a `NoData` answer. This is a legit answer, but _not_ reflecting reality. So only do this when you've evaluated it works for your use-case.

This sounds like something that should really be fixed regardless the outcome of this question?

**Comment by omoerbeek** [comment]
> > Also, a general warning for others reading this: in the recursor, if an RD=0 query does not find a cached entry, you will get an answer with no answer records and rcode `NoError`, aka a `NoData` answer. This is a legit answer, but _not_ reflecting reality. So only do this when you've evaluated it works for your use-case.
> 
> This sounds like something that should really be fixed regardless the outcome of this question?

The big question is what do you think it *should* answer?

**Comment by hlindqvist** [comment]
From my user perspective, I find RD=0 processing more surprising than not

> > > Also, a general warning for others reading this: in the recursor, if an RD=0 query does not find a cached entry, you will get an answer with no answer records and rcode `NoError`, aka a `NoData` answer. This is a legit answer, but _not_ reflecting reality. So only do this when you've evaluated it works for your use-case.
> > 
> > 
> > This sounds like something that should really be fixed regardless the outcome of this question?
> 
> The big question is what do you think it _should_ answer?

Something that cannot be misinterpreted as an answer to the question. 
Possibly SERVFAIL for this scenario (ideally with some more detailed EDE info), and probably REFUSED for the "RD=0 not accepted at all" scenario (which I think would be the more sane default behavior).

**Comment by omoerbeek** [comment]
Refused (when disallowing RD=0 completely) is taking care of by the associated PR.

I tried to find RFC information about what should be answered but did not find it so far. Maybe somebody has a reference?
