### ISSUE TITLE
tcp-out-max-queries parameter not respected

### ISSUE THREAD

**Issue by Pantoofle** [PowerDNS/pdns#13467]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description

The `tcp-out-max-queries` parameter is described as "Maximum total number of queries per outgoing TCP/DoT connection"
However, when using DoT, even with `tcp-out-max-queries = 1`, some TCP connections are used to send 2 queries.

### Environment

 - Operating system: Ubuntu 22.04.3 LTS
 - Software version: 4.6.0 (edit. Same behavior with 4.9.2)
 - Software source: OS repository

### Steps to reproduce

1. Add `tcp-out-max-queries = 1` to `recursor.conf`  to limit 1 query per connection
2. Add `dot-to-auth-names` to force the use of DoT for some domains
3. Start Wireshark to capture the traffic, and group by TCP conversation
4. `dig` for a domain reachable with DoT
5. Wait a few seconds
6. `dig` for a different domain, but managed by the same nameserver

### Expected behaviour

Since `tcp-out-max-queries = 1`, the recursor should:
- Open one TCP connection, resolve the first domain, close the connection
- Open a second TCP connection to resolve the second domain

### Actual behaviour

In this sandbox example, `ns1.example.net` is authoritative for `foo.net` and `bar.net`.

![tcp-reuse](https://github.com/PowerDNS/pdns/assets/22241764/17f22552-5430-4672-a9ba-0953f797aa4a)

In this capture above, the Recursor queries `ns1.example.net`, sends a query to `foo.net`, gets the `A` record, and more than 2 seconds later, uses the same TCP connection to query for `bar.net` and only then closes the connection.

**Comment by omoerbeek** [comment]
Recursor 4.6.0 is EOL. Please upgrade and try to reproduce.

**Comment by Pantoofle** [comment]
Tested with 4.9.2 stable from repo.powerdns.com. Same behavior.

**Comment by omoerbeek** [comment]
This code in `rec`tcpout.c` looks suspect: it is called to save an open connection for later. If we processed one query, `connection.d_numqueries` is incremented to one. But the condition checks for >, likely this should be >=
The effect is that the store is done, and the connection remains a candidate for re-use.
```
  ++connection.d_numqueries;
  if (s_maxQueries > 0 && connection.d_numqueries > s_maxQueries) {
    return;
  }
```

**Comment by omoerbeek** [comment]
As a workaround, setting `tcp-out-max-idle-per-auth` to zero should have the same effect. Do note that not reusing TCP connections (especially DoT) is hard on resources.

**Comment by Pantoofle** [comment]
Thanks a lot, I'll use this workaround

>  Do note that not reusing TCP connections (especially DoT) is hard on resources.

Yes, I'm only using it to measure and compare performances in a controlled sandbox environment. Not in a production setup
