### ISSUE TITLE
dnsdist: Unreachable carbon servers cause tight cpu-intense carbon loop after a few hours

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#13519]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Our carbon endpoint crashed, refusing further connections. dnsdist nicely backed off and ended up with a 10 minutes backoff intervall. However it looks like after a few hours this exploded, causing it to run into a very tight cpu-consuming carbon loop with no sleep/backoff at all anymore - using about 60-85% of a single core just for that purpose.

### Environment

 - Operating system: Ubuntu 20.04.6 LTS
 - Software version:  1.8.2-1pdns.focal
 - Software source: PowerDNS repository

### Steps to reproduce

1. Configure dnsdist with a single carbonServer destination and a 30s interval
2. Stop the receiving endpoint
3. Wait a few hours (or artificially let the system time run faster)

### Expected behaviour

dnsdist keeping the 10min backoff interval

### Actual behaviour
dnsdist slowly going to the 10min interval within approximately 20 minutes. Then after about 9 hours it will end up with no backoff sleep anymore, starting to run a tight and rather cpu-intense carbon loop after that point.

### Other information
Code around [here](https://github.com/PowerDNS/pdns/blame/808a6f25e472d16b860e36efb33ea961f4cdad58/pdns/dnsdist-carbon.cc#L278)
Log excerpt:
```
Nov 17 16:03:15 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:03:47 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:04:51 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:06:59 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:11:15 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:19:47 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:29:47 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 17 16:39:47 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
(..)
Nov 18 00:39:50 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 00:49:50 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 00:59:50 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:09:50 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:09:54 xy dnsdist[917]: message repeated 77 times: [ Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused]
Nov 18 01:09:54 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:09:59 xy dnsdist[917]: message repeated 128 times: [ Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused]
Nov 18 01:09:59 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:10:00 xy dnsdist[917]: message repeated 20 times: [ Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused]
Nov 18 01:10:00 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:10:00 xy dnsdist[917]: Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused
Nov 18 01:10:00 xy dnsdist[917]: message repeated 3 times: [ Problem sending carbon data to 172.x.x.x:2003: failed in writen2: Connection refused]
```

Note: This happened on all of our dnsdist instances.

**Comment by omoerbeek** [comment]
Possibly the bug is `backOff` gets larger than `INT_MAX` while `sleep` takes an `int` as argument. The lare value wraps to a negative value, which will get you a failing sleep call (`errno = EINVAL`). So no sleep at all.

**Comment by aj-gh** [comment]
I guess it's somewhere around the backOffTmp calculation as that's based on the consecutiveFailures count which is I guess _the_ thing to increase over time..

**Comment by omoerbeek** [comment]
This testprogram

```
#include <unistd.h>

#include <iostream>
#include <cmath>
#include <cstdint>
#include <ctime>
#include <limits>

int
main()
{
        uint8_t consecutiveFailures = 200;
        const time_t maxBackOff = 10 * 60;
        /* maximum interval between two attempts is 10 minutes */
        time_t backOff = 1;
        double backOffTmp = std::pow(2.0, static_cast<double>(consecutiveFailures));
        if (backOffTmp != HUGE_VAL && static_cast<uint64_t>(backOffTmp) <= static_cast<uint64_
t>(std::numeric_limits<time_t>::max())) {
          std::cerr << "backOffTmp is " << backOffTmp << std::endl;
          backOff = static_cast<time_t>(backOffTmp);
          std::cerr << "backOff is " << backOff << std::endl;
          if (backOff > maxBackOff) {
            backOff = maxBackOff;
          }
        }
        if (consecutiveFailures < std::numeric_limits<decltype(consecutiveFailures)>::max()) {
          consecutiveFailures++;
        }
        std::cerr << "backOff is " << static_cast<unsigned int>(backOff) << std::endl;
        sleep(backOff);
        std::cerr << "Errno is " << errno << std::endl;
}
```
Prints:
```
backOffTmp is 1.60694e+60
backOff is -9223372036854775808
backOff is 0
Errno is 0
```

**Comment by aj-gh** [comment]
It triggered after the 64th attempt on one of the hosts.

**Comment by omoerbeek** [comment]
So while the code tries to be careful, there still is a wrap around, that is noty caught by the condition.

**Comment by omoerbeek** [comment]
Pondering to rewrite the code to do something similar to this, whcih avoids the double arithmetic:

```C
 const unsigned int maxBackOff = 10 * 60;
 unsigned int backOff = maxBackOff;
 if (consecutiveFailures <= 31) {
  backOff = 1 << consecutiveFailures;
 }
 backOff = std::min(maxBackOff, backOff);
```

**Comment by rgacogne** [comment]
Indeed, at 63 is correctly detected as too large, but then the next iterations overflow..

Otto, your solution looks fine to me, thanks! I can work with that tomorrow, unless of course you want to open a pull request before that :)

**Comment by omoerbeek** [comment]
The issue is in the `static_cast<uint64_t>(backOffTmp) <= static_cast<uint64_t>(std::numeric_limits<time_t>::max())` expression, the first cast is casting to a type that is not used for the actual conversion. But rather than trying to fix that, lets go for the solution above. I'm away for the rest of the morning though.

**Comment by rgacogne** [comment]
No problem, I'll take it from there. Thanks!
