### ISSUE TITLE
dnsdist responses statistic wrong

### ISSUE THREAD

**Issue by chriwoa1** [PowerDNS/pdns#13526]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

dnsdist_cache_hits (about 40000 atm) and dnsdist_responses (about 40000 atm) seem to be almost equal although dnsdist_cache_misses (about 3000 atm) is much lower. I would assume that dnsdist would not send more queries to the backends (powerdns) than cache_misses.

### Environment

 - Operating system: OL 9.2
 - Software version: dnsdist-1.8.2-1pdns.el8.x86_64
 - Software source: PowerDNS repository

### Steps to reproduce

compare cache_hits, cache_misses and responses

### Expected behaviour

cache_misses and responses should be much lower than cache_hits

### Actual behaviour

responses and cache_hits are almost equal. cache_misses is much lower

### Other information

![grafik](https://github.com/PowerDNS/pdns/assets/130663118/548ec1b4-b07a-44b9-ab4a-85c4a1c80f30)
![grafik](https://github.com/PowerDNS/pdns/assets/130663118/031bee5a-deb3-4a1f-9a62-6ac29e8a141d)
![grafik](https://github.com/PowerDNS/pdns/assets/130663118/018694dc-59c8-4ddc-a4aa-fef5a9c798b0)
![grafik](https://github.com/PowerDNS/pdns/assets/130663118/495a73ce-2394-48cf-8933-21afdffe5f3d)

**Comment by rgacogne** [comment]
Since 1.8.0 the `responses` metric is also incremented on cache hits, and the documentation has not been properly updated to reflect that. I'll fix it.
