### ISSUE TITLE
Wildcard sibling glue records missing

### ISSUE THREAD

**Issue by SivaKesava1** [PowerDNS/pdns#13540]
- Program: Authoritative 
 - Issue type: Bug report

### Short description
PowerDNS, in general, returns sibling glue records. In the following special case where wildcards are involved, then it does not return the IP records.

### Environment

 - Operating system: Ubuntu Jammy
 - Software version: Authoritative Server 0.0.27087.0.master.g8314f12e92.dirty
 - Software source: GitHub (compiled from source)
 
### Steps to reproduce
Consider the following sample zone file:
|                    |           |                                                          |
|--------------------|-----------|----------------------------------------------------------|
| test.        | 500  SOA  | ns1.outside.edu. root.test. 3 86400 7200 604800 300 |
| test.        | 500  NS   | ns1.outside.edu.                                         |
| *.test.    | 500 A| 1.1.1.1                                        |
| a.test.    | 500 NS | foo.test.                                          |

For the query `<ex.a.test, A>` the answer from the PDNS server is:
```
"rcode NOERROR",
          "flags QR",
          ";QUESTION",
          "ex.a.test. IN A",
          ";ANSWER",
          ";AUTHORITY",
          "a.test. 500 IN NS foo.test.",
          ";ADDITIONAL"
```

### Expected/Actual behaviour
NSD and Knot use the wildcard record to synthesize an IP record for `foo.test` and return it in the additional section. PowerDNS, if the wildcard record was just an IP record for `foo.test` then it would return this sibling glue record. 
Bind has a long-standing issue with sibling glue records - https://gitlab.isc.org/isc-projects/bind9/-/issues/2384

**Comment by Habbie** [comment]
Nice find! I do wonder if any users would care. Adding this functionality would have a small performance impact.

**Comment by SivaKesava1** [comment]
Thank you. Yeah, I'm not sure either about how common these cases are. Bind seems to not return the records even in cases without wildcards, and that seems to be going fine for them.

**Comment by Habbie** [comment]
Then we definitely should not make our packets bigger than they already are. Thank you for your report. I'm closing this, but this text will of course be findable for anybody who wonders about this.
