### ISSUE TITLE
confusing messages from .deb init script when not root

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#1356]
Various subcommands of /etc/init.d/pdns (dump, status) will say "not running" instead of "no permission" or the like when run as non-root.

**Comment by pieterlexis** [comment]
We no longer ship SysV init scripts for 4.X and this issues do not affect 3.4 in such a way that is becomes unusable. We should perhaps mention this behaviour in the 3.x docs and be done with it

**Comment by zeha** [comment]
The extra "tools" need a new home though. Status being broken as non-root could possibly just be ignored.
