### ISSUE TITLE
The qsize-q metric in pdns auth lags behind reality

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#1359]
The qsize-q metric only gets updated once every 250 queries, which means it might stay 'stuck' on a high level on servers otherwise receiving little traffic. The distributor code a little too magic to couple the semaphore to the statistics engine. But perhaps the whole distributor should go.

**Comment by mind04** [comment]
fixed in f06d0693c88b4be6fcee8add77a6ee1bef0
