### ISSUE TITLE
Error 500 when querying zones via API

### ISSUE THREAD

**Issue by HNJBB** [PowerDNS/pdns#13616]
- Program: Authoritative
 - Issue type: Bug report

### Short description
All zones are returning Error 500 - Internal Server Error when queried via the API

All other API queries are working as expected.   This server was recently updated f

### Environment
 - Operating system: Ubuntu 22.04.3 LTS
 - Software version: 4.8.3
 - Software source: PowerDNS repository

### Steps to reproduce
Perform API Query against a zone e.g. /api/v1/servers/localhost/zones/zonenamehere.com

### Expected behaviour
Zone details are to be returned.

### Actual behaviour
- Dec 13 13:13:05 Done launching threads, ready to distribute questions
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02 Request details:
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02  Headers:
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   ___internal-request-id: cc7ad0d6-d6b8-43e1-896e-3c0cc1068bbf
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   accept: */*
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   accept-encoding: gzip, deflate
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   accept-language: en-GB,en;q=0.9,en-US;q=0.8
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   connection: keep-alive
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   host: 10.255.65.141:8081
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   x-api-key: <REMOVED>
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02  No body
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02 Handling request "/api/v1/servers/localhost/zones/monitoring.local"
- Dec 13 13:13:08 gmysql Connection successful. Connected to database 'powerdns' on 'localhost'.
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02 Error result for "/api/v1/servers/localhost/zones/monitoring.local": 500
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02 Response details:
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02  Headers:
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   Connection: close
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   Content-Length: 21
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   Content-Type: text/plain; charset=utf-8
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02  Full body:
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02   Internal Server Error
- Dec 13 13:13:08 [webserver] 1cf39530-1ccc-456d-9d64-1ed6f2da5a02 192.168.250.2:7837 "GET /api/v1/servers/localhost/zones/monitoring.local HTTP/1.1" 500 139

### Other information
Running check-all-zones shows that there is 'No NS record at zone apex' for two of the zones on the server.  But I don't think this is relevant to the issue.

**Comment by kpfleming** [comment]
If this server 'was recently updated' was the necessary schema migration performed?

**Comment by HNJBB** [comment]
Thanks Kevin, looks like that was missed.  I've applied the Schema Migration and all is well now.
