### ISSUE TITLE
addDOH3Local should use port 443

### ISSUE THREAD

**Issue by hlindqvist** [PowerDNS/pdns#13639]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

`addDOH3Local` should use port 443 by default.

### Environment

 - Operating system: any
 - Software version: 1.9.0-pre / master
 - Software source: any 

### Steps to reproduce

1. Use `addDOH3Local`  in dnsdist.conf without specifying a port
2. Observe what port is bound (or read the documented default in [`addDOH3Local`](https://dnsdist.org/reference/config.html#addDOH3Local))

### Expected behaviour

Port 443 would be expected to be used.

### Actual behaviour

Port 853 is used. 

### Other information

The "spirit of DoH" (as I understand it, at least) is to "just look like normal HTTPS", and at least so far the norm for h3 seems to be to stick to :443 as much as possible. 
Repurposing the DoT/DoQ port for DoH (w/ h3) instead outright telegraphs that this is encrypted DNS.

**Comment by rgacogne** [comment]
Thanks, it looks like a bug indeed!
