### ISSUE TITLE
dns64distdist

### ISSUE THREAD

**Issue by axu-trex** [PowerDNS/pdns#13644]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
Please add actions for DNS64 (fake ptr and aaaa records)

### Usecase
I would like to use dnsdist as a front end load balancer for a group of resolvers. Currently I have to run separate resolvers for DNS64 and normal DNS. I would like to replace the dedicated DNS64 resolvers with a single rule in the dnsdist load balancers that use the full pool of my normal back end resolvers.

### Description

The pdns_recursor already supports DNS64, but I think those functions will need to be modified a bit before adopting them into dnsdist.

If this feature already exists, then please improve the dnsdist.org documentation so it is easier to find.

**Comment by rgacogne** [comment]
Hi! I'm afraid I'm not convinced dnsdist is the right place to implement DNS64, let me explain why:
- dnsdist is a load-balancer to its core: it knows how to route incoming queries to a backend, and route the response back to the initial requestor. It also knows how to generate some static responses by itself, but this support is really limited ;
- generating fake `PTR` and `AAAA` records involves actual resolving: for example for `AAAA` it means resolving the requested `AAAA`, and if the response is a `NODATA` resolving the corresponding `A` and finally generating a new response based on the resolved `A` ;
- dnsdist has limited DNS parsing and generation abilities, but in this specific case they might be enough ;
- but, it does not know how to resolve a name. It doesn't even have the code to generate a new query to a backend during the processing of a response, and no way of associating the response back to the initial query later.

I think it boils down to: doing DNS64 requires DNS recursion, so it has to be done by a DNS resolver, not by a load-balancer.

**Comment by axu-trex** [comment]
DNS64 does not require resolving. It's a pretty mechanical operation:

* AAAA response comes in as NXDOMAIN, and the query is tagged as DNS64
* replace query QTYPE AAAA -> A and resend it
* A response with DNS64 tag comes in
 * successful -> call the built-in faker function to convert it into the AAAA response
 * fail -> replace QTYPE back A -> AAAA

And PTR handling is even more primitive.

All of the above logic can be done in Lua, just as long as the faker functions are copied from the recursor to dnsdist.

**Comment by rgacogne** [comment]
> DNS64 does not require resolving. It's a pretty mechanical operation:
> 
>     * **AAAA** response comes in as NXDOMAIN, and the query is tagged as DNS64
> 
>     * replace query QTYPE **AAAA** -> **A** and resend it
> 
>     * **A** response with DNS64 tag comes in
>       
>       * successful -> call the built-in faker function to convert it into the **AAAA** response
>       * fail -> replace QTYPE back **A** -> **AAAA**
> 
>     * send the response back to client
> 
> 
> And PTR handling is even more primitive.
> 
> All of the above logic can be done in Lua, just as long as the faker functions are copied from the recursor to dnsdist.

Well we can argue as whether this is called resolving or not, but as I said we don't have the code to implement this in dnsdist, and I believe this kind of code doesn't belong in a load-balancer. Now if someone want to actually open a pull request that is concise enough I will consider it.
