### ISSUE TITLE
Unclear discovery of h3 when using addDOH3Local

### ISSUE THREAD

**Issue by hlindqvist** [PowerDNS/pdns#13640]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

Normally discovery of h3 endpoints works via the h2 Alt-Svc frame, the `Alt-Svc` HTTP header or more recently `HTTPS` records. Neither Alt-Svc mechanism seems to be readily available when using `addDOH3Local`. 
I think the header specifically can be manually added via `customResponseHeaders` in [`addDOHLocal`](https://dnsdist.org/reference/config.html#addDOHLocal) but if this is the intended setup I think clear documentation ([here](https://dnsdist.org/guides/dns-over-http3.html)?) of this would be very helpful to reduce confusion.

### Environment

 - Operating system: any
 - Software version: 1.9.0-pre / master
 - Software source: any 

### Steps to reproduce

1. Configure dnsdist using `addDOHLocal` and `addDOH3Local` normally to enable h2 as well as h3 support
2. Point an h3 capable client at `https://dns.example/dns-query` (the above dnsdist)

### Expected behaviour

It should find the h3 endpoint

### Actual behaviour

It has no means of finding the h3 endpoint other than potentially via `HTTPS` lookup (provided the client even supports that, and such a record has been added in DNS)

### Other information

I believe something like
```
customResponseHeaders={ ["alt-svc"]= "h3=\":443\"" }
```
could serve as documentation example for how to add the alt-svc header in `addDOHLocal`, if that is the intended config.

From a user perspective it feels like it would probably really make more sense if h3 was a feature of `addDOHLocal` rather than a separate thing, possibly with automatic Alt-Svc handling between the protocols. However, I assume there is a technical reason for this split.

**Comment by rgacogne** [comment]
More than a technical reason, it's that we want to be as neutral as possible by default, not adding anything that it's not required to the response we received from the backend. But you are 100% right that we at least need to document how to advertise HTTP/3 support, probably in the `addDOHLocal` documentation indeed, and with a mention in the one for `addDOH3Local`.

**Comment by hlindqvist** [comment]
> More than a technical reason, it's that we want to be as neutral as possible by default, not adding anything that it's not required to the response we received from the backend. But you are 100% right that we at least need to document how to advertise HTTP/3 support, probably in the `addDOHLocal` documentation indeed, and with a mention in the one for `addDOH3Local`.

Ok, thanks for the clarification!

On the specific note of that split between DOH and DOH3 and some of the current feature disparity between them: should there be a way to specify the `urls`, `customResponseHeaders` etc also in `addDOH3Local`, and should there be a `showDOH3Frontends`, `showDOH3ResponseCodes`  to show stats? (and DOH3ResponseMap things, etc, unless those work with both?)

**Comment by rgacogne** [comment]
> On the specific note of that split between DOH and DOH3 and some of the current feature disparity between them: should there be a way to specify the `urls`, `customResponseHeaders` etc also in `addDOH3Local`, and should there be a `showDOH3Frontends`, `showDOH3ResponseCodes` to show stats? (and DOH3ResponseMap things, etc, unless those work with both?)

It's planned but it will take some time for the DoH3 code to come to feature parity with the existing DoH one.

**Comment by rgacogne** [comment]
By the way `showDOH3Frontends` exists, but it's not documented, I'll fix it.
