### ISSUE TITLE
dnsdist:  DoQ and Doh3 are sent with UDP protocol type in protobuf messages

### ISSUE THREAD

**Issue by dmachard** [PowerDNS/pdns#13673]
- Program: dnsdist
 - Issue type: Bug report

### Short description

Perhaps it's not a issue but currently DoQ and Doh3 queries are sent through  protobuf messages with `UDP` protocol type. It's not wrong but it does not allow them to be follow them.

### Environment
 - Software version: dnsdist 1.9.0-alpha4

### Steps to reproduce

Configuration used

```
setLocal('0.0.0.0:53', { reusePort=true })
addDOQLocal('0.0.0.0:853', '/etc/dnsdist/cert.pem', '/etc/dnsdist/key.pem')
addDOH3Local('0.0.0.0:443', '/etc/dnsdist/cert.pem', '/etc/dnsdist/key.pem')

rl = newRemoteLogger("192.168.1.17:6001")
addAction(AllRule(),RemoteLogAction(rl, nil, {serverID="dnsdist"}))
```

### Expected behaviour

Specific protocol types for each one

**Comment by hlindqvist** [comment]
> It's not wrong but it does not allow them to be follow them.

I think it's very clear that it's wrong, as it is not DNS over UDP.

Probably relevant:
https://github.com/dnstap/dnstap.pb/blob/master/dnstap.proto#L67  DoQ has its own type, presumably "DoH3" is still just DoH.

**Comment by rgacogne** [comment]
Yep, it's a bug. Contrary to dnstap for which we cannot decide by ourselves, I think we want a separate value for DoH3 in our own protobuf format.
