### ISSUE TITLE
API Enhancement: zone filter

### ISSUE THREAD

**Issue by Falci** [PowerDNS/pdns#13739]
- Program: rest-api 
 - Issue type: Feature request

### Short description
Add optional filter options to `/api/v1/servers/:server/zones/:zone` like `name` and `type`
Example: `/api/v1/servers/localhost/zones/example.com?name=something.example.com.&type=DS` 

### Usecase
It's a bit slow to retrieve all the records of a zone when it has too much "subdomains" (names).

### Description
We have too much subdomains (names under a zone). In order to update the DS/NS records of one we need first to retrieve them all.
It could be faster and cheaper (bandwidth) to filter and return only the subset of records I really need.
I tried to make each of these subdomains their own zone, but them them won't support DS/NS records.

Related to #2482, but the solution provided (basically "use another software") isn't satisfactory

**Comment by sksz** [comment]
It will be very helpful feature!

**Comment by melissavoegeli** [comment]
I'm looking for a few things to work on and started with this ticket.  However when I began implementing this feature I noticed something similar already exists?  Let me know if I am misunderstanding what is being requested, but here is an example to demonstrate my confusion:

I populated some records into my database in an effort to implement an API solution for more fine grain filtering by record name and record type.

```
sqlite> select * from records;
2|1|test.example.org|A|192.168.0.5|3600|0|0||1
4|1|derp.example.org|A|192.168.0.5|3600|0|0||1
6|1|herp.example.org|A|192.168.0.5|3600|0|0||1
8|1|cool.example.org|MX|mailserver1.com|3600|10|0||1
9|1|example.org|SOA|a.misconfigured.dns.server.invalid hostmaster.example.org 2024071005 10800 3600 604800 3600|3600|0|0||1
```

`$ curl -vv -X GET 'http://localhost:8081/api/v1/servers/localhost/zones/example.org.' -H 'X-API-KEY: changeme'`

Yields:
```
{
  "account": "",
  "api_rectify": false,
  "catalog": "",
  "dnssec": false,
  "edited_serial": 2024071005,
  "id": "example.org.",
  "kind": "Native",
  "last_check": 0,
  "master_tsig_key_ids": [],
  "masters": [],
  "name": "example.org.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "test.example.org.",
      "records": [
        {
          "content": "192.168.0.5",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "herp.example.org.",
      "records": [
        {
          "content": "192.168.0.5",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "derp.example.org.",
      "records": [
        {
          "content": "192.168.0.5",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    },
    {
      "comments": [],
      "name": "cool.example.org.",
      "records": [
        {
          "content": "10 mailserver1.com.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "MX"
    },
    {
      "comments": [],
      "name": "example.org.",
      "records": [
        {
          "content": "a.misconfigured.dns.server.invalid. hostmaster.example.org. 2024071005 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    }
  ],
  "serial": 2024071005,
  "slave_tsig_key_ids": [],
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/example.org."
}
```

The proposed solution to filter these results is provide the params `type` and `name`, however is that any different than this solution that already exists?:

`$ curl -vv -X GET 'http://localhost:8081/api/v1/servers/localhost/zones/example.org.?rrset_type=MX&rrset_name=cool.example.org.' -H 'X-API-KEY: changeme'`


```
{
  "account": "",
  "api_rectify": false,
  "catalog": "",
  "dnssec": false,
  "edited_serial": 2024071005,
  "id": "example.org.",
  "kind": "Native",
  "last_check": 0,
  "master_tsig_key_ids": [],
  "masters": [],
  "name": "example.org.",
  "notified_serial": 0,
  "nsec3narrow": false,
  "nsec3param": "",
  "rrsets": [
    {
      "comments": [],
      "name": "cool.example.org.",
      "records": [
        {
          "content": "10 mailserver1.com.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "MX"
    }
  ],
  "serial": 2024071005,
  "slave_tsig_key_ids": [],
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/example.org."
}
```

The referenced code is located here: https://github.com/PowerDNS/pdns/blob/master/pdns/ws-auth.cc#L449-L463

**Comment by Habbie** [comment]
Thank you for that excellently researched comment! Indeed the feature as requested here is implemented. Closing this ticket.
