### ISSUE TITLE
auth: keys set for server

### ISSUE THREAD

**Issue by pinocc01** [PowerDNS/pdns#13769]
for catalog work, all zone may be same key
like this set in bind
```
server ip {
        keys{ tsig-key; };
};
```

**Comment by setharnold** [comment]
Hello, I'm afraid I don't understand what you'd like help with, or are proposing. Maybe the maintainers will have a better idea, maybe not, but I guess they'll want more information, too.

When you file an issue, there's a template that suggests what would be useful for a good report. I suggest looking at that template again and using it to fill out more of this issue -- is this a feature request? a bug report? does this cause an error? if so, what error? what version are you using? etc.

Thanks

**Comment by pinocc01** [comment]
> Hello, I'm afraid I don't understand what you'd like help with, or are proposing. Maybe the maintainers will have a better idea, maybe not, but I guess they'll want more information, too.
> 
> When you file an issue, there's a template that suggests what would be useful for a good report. I suggest looking at that template again and using it to fill out more of this issue -- is this a feature request? a bug report? does this cause an error? if so, what error? what version are you using? etc.
> 
> Thanks

feature request,: a key set for a server , no need set for each zone of a server
thx

**Comment by pinocc01** [comment]
both bind and knot can set key for a server, 
for example knot dns conf like this

```
remote:
  - id: primary
    address: 2000:2::1
    key: tsig-key
```

when catalog works, no need set key zone belong to the server, cause they may same
or you must get tsig-key from catalog custom property
