### ISSUE TITLE
dnsdist 1.9 Debian/Bookworn 

### ISSUE THREAD

**Issue by StenStensonSten** [PowerDNS/pdns#13810]
- [ ] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [ ] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

After upgrading to 1.9 on Debian Bookwork syslog reports following

Feb 17 10:48:38 dns02-ix dnsdist[2472280]: Error while retrieving the security update for version dnsdist-1.9.0.38.master.g22c29777a: Unable to get a valid Security Status update
Feb 17 10:48:38 dns02-ix dnsdist[2472280]: Not validating response for security status update, this is a non-release version.

### Environment

 - Operating system: Debian Bookworn
 - Software version: 1.9
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by omoerbeek** [comment]
This looks like you installed a master version, and not a 1.9 release. What repo did you use exactly?

**Comment by StenStensonSten** [comment]
doh my bad, you are correct.
