### ISSUE TITLE
Authserver, Recursor and dnsdist containers logging credentials on startup

### ISSUE THREAD

**Issue by maresac** [PowerDNS/pdns#13838]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description

Each of the components (using the official Docker images) print their whole configuration on startup, including plain text credentials such as the built-in webserver API key and password or the auth backend db password. Anyone with read-access to container logs can use these credentials to access the backend database and/or use the components' APIs exposed through the built-in webservers. 

### Environment

 This affects container images for the Auth Server, Recursor and dnsdist from https://hub.docker.com/u/powerdns

### Steps to reproduce

Run components with official Docker images, providing API keys and other credentials through environment variables.

### Expected behaviour

In production environments, credentials should not be logged unmasked.

### Actual behaviour

Plain text credentials are accessible in container logs. The whole configs are printed by the Python script used on startup:
* https://github.com/PowerDNS/pdns/blob/master/dockerdata/startup.py#L54
* https://github.com/PowerDNS/pdns/blob/master/dockerdata/startup.py#L66

### Other information

I would propose to either redact the credentials when printing the config or remove the print statements altogether. I can submit a PR if you let me know what you prefer :)

**Comment by Habbie** [comment]
Thanks for the report, that's an excellent point. I'd love a PR to only do the print if some debugging env var is set.

**Comment by Habbie** [comment]
(if you feel like doing a PR that can do redaction, that would be even better, but it's a harder job, because that script doesn't know about all secret variables, just some of them)

**Comment by maresac** [comment]
Great, I'll see what I can come up with. PR will follow soon.

**Comment by Habbie** [comment]
fixed in #13849, thanks!
