### ISSUE TITLE
Recursor only logs empty statistics

### ISSUE THREAD

**Issue by SjonHortensius** [PowerDNS/pdns#13843]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor 
 - Issue type: Bug report

### Short description
I only get useless, empty statistics printed in my logs

### Environment

 - Operating system: arch linux
 - Software version: `4.8.*`, `4.9.*`, `5.0.*`
 - Software source: [archlinux repository](https://gitlab.archlinux.org/archlinux/packaging/packages/powerdns-recursor/-/blob/main/PKGBUILD?ref_type=heads)

### Steps to reproduce

1. start recursor through sd unit
2. configure `statistics-interval=86400`
3. see empty logs (only headers)

### Expected behaviour
If there is no data, I expect no output. If there is data, I expect to see it

### Actual behaviour
```
Feb 28 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 28 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 28 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 28 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 28 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 28 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 28 10:04:45 pdns_recursor[778836]: Periodic QPS report
Feb 29 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 29 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 29 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 29 10:04:45 pdns_recursor[778836]: Periodic statistics report
Feb 29 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 29 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 29 10:04:45 pdns_recursor[778836]: Queries handled by thread
Feb 29 10:04:45 pdns_recursor[778836]: Periodic QPS report
Mar 01 10:04:45 pdns_recursor[778836]: Periodic statistics report
Mar 01 10:04:45 pdns_recursor[778836]: Periodic statistics report
Mar 01 10:04:45 pdns_recursor[778836]: Periodic statistics report
Mar 01 10:04:45 pdns_recursor[778836]: Periodic statistics report
Mar 01 10:04:45 pdns_recursor[778836]: Queries handled by thread
Mar 01 10:04:45 pdns_recursor[778836]: Queries handled by thread
Mar 01 10:04:45 pdns_recursor[778836]: Queries handled by thread
Mar 01 10:04:45 pdns_recursor[778836]: Periodic QPS report
```

**Comment by omoerbeek** [comment]
I suppose you are using the `systemd-journal` structured logging backend. To view the full entries, use `journalctl`, see https://docs.powerdns.com/recursor/appendices/structuredlogging.html#the-systemd-journal-backend

Alternative, use the default structured logging backend, which logs the full messages as text.

**Comment by SjonHortensius** [comment]
Ah, right. That data is somehwa hidden when using the SD backend. Thanks for the hint!
