### ISSUE TITLE
sendmsg error on OpenBSD: Resource temporarily unavailable

### ISSUE THREAD

**Issue by kuon** [PowerDNS/pdns#13857]
- Program:  Auth server
 - Issue type: Bug report

### Short description
When running the auth server behind dnsdist on OpenBSD, I see a lot of those in the log:

```
Error sending reply with sendmsg (socket=4, dest=127.0.0.1:8880): Resource temporarily unavailable
```

### Environment
 - Operating system: OpenBSD 7.4
 - Software version: 4.8.2
 - Software source: OpenBSD package

Version:

```
Mar 04 15:52:53 PowerDNS Authoritative Server 4.8.2 (C) 2001-2022 PowerDNS.COM BV
Mar 04 15:52:53 Using 64-bits mode. Built using clang 13.0.0  on Oct  6 2023 23:44:26 by _pbuild@amd64.ports.openbsd.org..
Mar 04 15:52:53 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Mar 04 15:52:53 Features: libcrypto-ecdsa libcrypto-ed25519 libcrypto-eddsa lua lua-records protobuf sodium curl DoT 
Mar 04 15:52:53 Built-in modules: bind
Mar 04 15:52:53 Configured with: " '--disable-shared' '--with-modules=bind' '--with-sqlite3' '--with-dynmodules=gsqlite3 gmysql gpgsql ldap' '--with-lua=lua53' '--enable-lua-records' '--disable-hardening' '--enable-tools' '--enable-ixfrdist' '--without-gnutls' '--enable-dns-over-tls' '--with-mysql=/usr/local' '--with-pg-config=/usr/local/bin/pg_config' '--prefix=/usr/local' '--sysconfdir=/etc/pdns' '--mandir=/usr/local/man' '--infodir=/usr/local/info' '--localstatedir=/var' '--disable-silent-rules' '--disable-gtk-doc' 'CC=cc' 'CFLAGS=-O2 -pipe -g' 'LDFLAGS=-L/usr/local/lib' 'CPPFLAGS=-I/usr/local/include -I/usr/local/heimdal/include' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -g' 'YACC=yacc' 'KRB5_LIBS=-L/usr/local/heimdal/lib -lkrb5'"
``` 

### Steps to reproduce

Dnsdist listens on port 53, auth on port 5300, this message occurs during normal operation about every 5 seconds

### Expected behaviour
No error

### Actual behaviour
The error message in the log does not seem to affect normal operations

### Other information

Dnsdist config:

```
-- public IP for authoritative server
setLocal('xxxxx:53')
addLocal('[xxxxx::2]:53')

-- local IP for recursive server
addLocal('[xxxxx::1]:53')
addLocal('10.1.1.1:53')
addLocal('127.0.0.1:53')


setACL({'0.0.0.0/0', '::/0'}) -- Allow all IPs access

newServer({address='127.0.0.1:5300', pool='auth'})
newServer({address='127.0.0.1:5301', pool='recursor'})
newServer({address='127.0.0.1:5302', pool='recursor64'})


local_dual_stack_nets = newNMG()
local_dual_stack_nets:addMask('10.0.0.0/8')
local_dual_stack_nets:addMask('127.0.0.1/32')
local_dual_stack_nets:addMask('xxxxx:/48')

local_ipv6_nets = newNMG()
local_ipv6_nets:addMask('xxxxx:/64')

force_ipv4_net = newNMG()
force_ipv4_net:addMask('10.203.0.0/16')

-- Refuse AAAA and HTTPS requests for ipv4 only hosts (for VPN)
addAction(
  AndRule({
    OrRule({
      QTypeRule(DNSQType.AAAA),
      QTypeRule(DNSQType.HTTPS)
    }),
    NetmaskGroupRule(force_ipv4_net)
  }),
  RCodeAction(DNSRCode.REFUSED)

-- Refuse zone transfer
addAction(OrRule({QTypeRule(DNSQType.AXFR), QTypeRule(DNSQType.IXFR)}), RCodeAction(DNSRCode.REFUSED))

-- Always send SOA to auth
addAction(QTypeRule(DNSQType.SOA), PoolAction("auth"))



-- IPv6 networks goes to DNS64 recursor
addAction(NetmaskGroupRule(local_ipv6_nets), PoolAction('recursor64'))

-- Local network are allowed to ask the recursor
addAction(NetmaskGroupRule(local_dual_stack_nets), PoolAction('recursor'))

-- External requests goes to authoritative
addAction(AllRule(), PoolAction('auth'))
```

Pdns config:

```
local-address=127.0.0.1
local-port=5300
launch=gsqlite3
gsqlite3-database=/var/db/pdns/pdns.sqlite3
gsqlite3-dnssec=true
gsqlite3-pragma-synchronous=FULL
gsqlite3-pragma-journal-mode=DELETE
master=no
loglevel=5
enable-lua-records=yes
edns-subnet-processing=yes
only-notify=
dnsupdate=yes
lua-dnsupdate-policy-script=/etc/pdns/check-dynupdates.lua
webserver=yes
webserver-address=10.10.1.1
webserver-port=5353
webserver-allow-from=10.10.0.0/16
resolver=127.0.0.1:5301
expand-alias=yes
api=yes
api-key=xxx
default-soa-edit=EPOCH
allow-axfr-ips=
```

**Comment by omoerbeek** [comment]
AFAIK, this is a long standing bug in OpenBSD. In the multi-threaded case, if two UDP send(2) calls on the same socket happen simultaneously this error will appear for one of the threads.

**Comment by omoerbeek** [comment]
Another thing to look at: OpenBSD has a tight default buffer size for UDP: `net.inet.udp.sendspace=9216` which might cause an actual `EAGAIN (The socket is marked non-blocking or the MSG_DONTWAIT flag is set and the requested operation would block)`. 
The recursor and dnsdir enlarge this buffer space, but auth does not seem to do that.

**Comment by omoerbeek** [comment]
@kuon: Can you try runnnig with `sysctl net.inet.udp.sendspace=204800`  and see if the log entries are reduced?

**Comment by omoerbeek** [comment]
Did some more investigation and I do not think increasing the UDP send buffer size helps.

I have made a test program that creates two threads that write to a single non-blocking socket simultaneously. On OpenBSD, even the first call to send of a thread can hit EAGAIN. On Linux, it also show it can hit that, but only after many packets have been written.

The hypothesis is that on Linux, UDP datagrams get queued, and at some point the kernel decides the buffer is full and returns EAGAIN.
On OpenBSD, this can happen any time: if another thread is calling send simultaneously. This has been confirmed by studying the ktrace of the test program.

Test program attached:

```
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <fcntl.h>
#include <err.h>
#include <string.h>
#include <unistd.h>

#include <thread>

#define NUM 2

int sockets[1];

void
opensocket()
{
	sockets[0] = socket(AF_INET, SOCK_DGRAM, 0);
	if (sockets[0] < 0) 
		err(1, "socket");
	int flags = fcntl(sockets[0],F_GETFL,0);
	if (flags < 0 || fcntl(sockets[0], F_SETFL, flags | O_NONBLOCK) < 0)
		err(1, "fcntl");
}


void
send(int sock, const struct sockaddr *addr, socklen_t sz)
{
	while (true) {
		int ret;
		while (true) {
			ret = sendto(sock, "hi", 2, 0, addr, sz);
#if 0
			if (ret != 2 && errno == EAGAIN)
				continue;
#endif
			break;
		}
		if (ret != 2) 
			warn("sendto");
	}
}

int
main(int argc, char *argv[])
{
	struct addrinfo hints, *res;
	
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_DGRAM;
	hints.ai_protocol = IPPROTO_UDP;

	int ret = getaddrinfo(argv[1], NULL, &hints, &res);
	if (ret != 0)
		errx(1, "getaddrinfo: %s", gai_strerror(ret));

	opensocket();

	struct sockaddr addr = *res->ai_addr;
	((struct sockaddr_in*)&addr)->sin_port = htons(53);

	for (int i = 0; i < NUM; i++) {
		auto thread = std::thread([=]() { send(sockets[0], &addr, sizeof(addr)); });
		thread.detach();
	}
	sleep(100);
}
```

**Comment by kuon** [comment]
> @kuon: Can you try runnnig with `sysctl net.inet.udp.sendspace=204800` and see if the log entry rate is reduced? (I have the anwer already, no more need to try that)

I did try nonetheless and I can confirm it didn't change anything.

**Comment by omoerbeek** [comment]
OK, to summarize my findings

- On Linux we are seeing EAGAIN, but only after quite some packets have been sent to the socket in a tight loop.
- On OpenBSD we also see EAGAIN, but nly if two threads happen to call send siumultaneously
- On macOS test test prophram did not produce any error
- On FreeBSD I see ENOSPACE errors, this is likely equivalent to the Linux case, just a different error code.

I have to think a bit on the best approach to handle this, as all systems seem a bit different (and only OpenBSD is really affected as the error occurs often there and not so much on other systems).

**Comment by kuon** [comment]
If you need me to run a test program on my different OpenBSD machines, let me know, I'll be happy to help.

**Comment by omoerbeek** [comment]
It turns out we have an OpenBSD specific fix in the recursor, which is already well-tested. PR #13867 uses that fix in the authoritative server as well.

**Comment by omoerbeek** [comment]
> If you need me to run a test program on my different OpenBSD machines, let me know, I'll be happy to help.

Thanks, but as I am (also) an OpenBSD developer I have plenty of machines running OpenBSD.
