### ISSUE TITLE
API insert multiple TXT records

### ISSUE THREAD

**Issue by celevra** [PowerDNS/pdns#13881]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative 
 - Issue type: Bug report

### Short description

```
curl -X PATCH --data '{"rrsets": [ {"name": "_acme-challenge.mydomain.com.", "type": "TXT", "ttl": 3600, "changetype": "REPLACE", "records": [ {"content": "\"bliblablub\"", "disabled": false } ] } ] }' -H "X-API-Key: xxxx" http://127.0.0.1:8081/api/v1/servers/localhost/zones/mydomain.com.
curl -X PATCH --data '{"rrsets": [ {"name": "_acme-challenge.mydomain.com.", "type": "TXT", "ttl": 3600, "changetype": "REPLACE", "records": [ {"content": "\"bliblablub2\"", "disabled": false } ] } ] }' -H "X-API-Key: xxxx" http://127.0.0.1:8081/api/v1/servers/localhost/zones/mydomain.com.
```

just bliblablub2 will be present because "REPLACE" deletes the old one.
i think there should be a "CREATE" type to force a new TXT record

### Environment

 - Operating system: Ubuntu
 - Software version: 4.2.1-1build2
 - Software source: OS 

### Steps to reproduce
```
curl -X PATCH --data '{"rrsets": [ {"name": "_acme-challenge.mydomain.com.", "type": "TXT", "ttl": 3600, "changetype": "REPLACE", "records": [ {"content": "\"bliblablub\"", "disabled": false } ] } ] }' -H "X-API-Key: xxxx" http://127.0.0.1:8081/api/v1/servers/localhost/zones/mydomain.com.
curl -X PATCH --data '{"rrsets": [ {"name": "_acme-challenge.mydomain.com.", "type": "TXT", "ttl": 3600, "changetype": "REPLACE", "records": [ {"content": "\"bliblablub2\"", "disabled": false } ] } ] }' -H "X-API-Key: xxxx" http://127.0.0.1:8081/api/v1/servers/localhost/zones/mydomain.com.

dig -t TXT _acme-challenge.mydomain.com.
```

### Expected behaviour

multiple TXT entries

### Actual behaviour

replaces all existing ones with the new request

### Other information

yes i know that i could query the existing one and put them inside the rrsets array, but than i would need an extra api call, why doesnt just a force create exists?

**Comment by Habbie** [comment]
> i think there should be a "CREATE" type to force a new TXT record

We have no plans for this, sorry.
