### ISSUE TITLE
add a new record by powerdns-authoritative api and some wrong records in the mysql

### ISSUE THREAD

**Issue by oyJouokong** [PowerDNS/pdns#13956]
### Short description
when i have use the api of powerdns-authoritative to add a record

the record 's rr has multi points as "`test.example.com.cn`"
and my zone is "`ppy.rpz`"
and it will add success
but i found some mysql records is like this:

 |id          | domain_id | name                                     | type  | content        | ttl      | prio   | disabled | ordername | auth |
 |771946 | 19286        | test.example.com.cn.ppy.rpz | A       | 192.168.0.1  | 60     | 0        |        0     | NULL          |    1 |
 |771947 | 19286        | example.com.cn.ppy.rpz 	  | NULL | NULL           | NULL | NULL |        0     | NULL          |    1 |
 |771948 | 19286        | com.cn.ppy.rpz         	          | NULL | NULL           | NULL | NULL |        0     | NULL          |    1 |
 |771949 | 19286        | cn.ppy.rpz             	          | NULL | NULL           | NULL | NULL |        0     | NULL          |    1 |

Is there any possibility of triggering an anomaly? When I delete this record test.example.com.cn.ppy.rpz, the data with null type above will be deleted along with it.

### Environment

powerdns 4.4.1

### Expected behaviour
only has one record as:
 |771946 | 19286        | test.example.com.cn.ppy.rpz | A       | 192.168.0.1  | 60     | 0        |        0     | NULL          |    1 |

### Actual behaviour
get more type is null records, Is there a risk?

looking forward for your response ,thanks!

**Comment by micheloe** [comment]
This is perfectly normal, as PowerDNS auth needs a way to determine there is something below `cn.ppy.rpz`, to avoid answering with `NXDOMAIN` while it should answer with an empty response when `cn.ppy.rpz` is queried. This should be done all the way up to `example.com.cn.ppy.rpz`.

PowerDNS auth 4.4.1 is EOL, you should upgrade to to at least 4.7.x (4.9 is recommended). This belongs in the Discussions section.

**Comment by oyJouokong** [comment]
> This is perfectly normal, as PowerDNS auth needs a way to determine there is something below `cn.ppy.rpz`, to avoid answering with `NXDOMAIN` while it should answer with an empty response when `cn.ppy.rpz` is queried. This should be done all the way up to `example.com.cn.ppy.rpz`.
> 
> PowerDNS auth 4.4.1 is EOL, you should upgrade to to at least 4.7.x (4.9 is recommended). This belongs in the Discussions section.

That is, I don't need to worry about these null data types. I can use them normally, right? Is it because my rr for records has too many points, causing this? i had found that if there less than two points it will not cause this happens

**Comment by micheloe** [comment]
> That is, I don't need to worry about these null data types. I can use them normally, right? Is it because my rr for records has too many points, causing this? i had found that if there less than two points it will not cause this happens

Right, they are even required for normal, correct operation.

**Comment by oyJouokong** [comment]
> > That is, I don't need to worry about these null data types. I can use them normally, right? Is it because my rr for records has too many points, causing this? i had found that if there less than two points it will not cause this happens
> 
> Right, they are even required for normal, correct operation.

thanks!

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
