### ISSUE TITLE
Log file location (linux)

### ISSUE THREAD

**Issue by kisst** [PowerDNS/pdns#1396]
There is no option to setup logfile on linux systems.
All log related config options are:

  --logfile=...
        Logfile to use (Windows only)
  --logging-facility=...
        Log under a specific facility
  --loglevel=...
        Amount of logging. Higher is more. Do not set below 3

The only way to have a proper setup if you start to play with the loglevel and the syslog, really this should be an basic option on ANY system.

Even more confusing the fact that this is part of the default distro config ( at least on the debian family )  but it's ignored, and not even prompt any error about it, or have a notes in the comment section that this works only on win or something.

**Comment by istiak101** [comment]
If anyone want a log file from stdout you can do in this way. Systemd 240 or newer versions can do this. Add below lines to your service file.

```
StandardOutput=append:/var/log/pdns.log
StandardError=append:/var/log/pdns.log
```
