### ISSUE TITLE
Conflicts with pre-existing RRset

### ISSUE THREAD

**Issue by oyJouokong** [PowerDNS/pdns#13961]
### Short description
i have a zone like '`example.rpz`'
and there is a type of A record as
storage.example.rpz IN A 192.168.0.0.1

and then i want to add a type of TXT record like:
storage.example.rpz IN TXT "region=cn"

and the api response get an error as:
RRset storage.example.rpz. IN TXT: Conflicts with pre-existing RRset

### Environment
powerdns 4.4.1

### Expected behaviour
different type of record can add success 

### Actual behaviour
can not add record of TXT for same rr

is there any limit here?

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by Habbie** [comment]
> Support questions are handled
> in our other online communities

and, since recently, [Discussions](https://github.com/PowerDNS/pdns/discussions/)
