### ISSUE TITLE
dnsdist: no well-defined way to return "no server available" when using setServerPolicyLuaFFIPerThread

### ISSUE THREAD

**Issue by karelbilek** [PowerDNS/pdns#13977]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Feature request
 

### Short description
I am writing a custom setServerPolicyLuaFFIPerThread policy.

https://dnsdist.org/guides/serverselection.html#lua-server-policies

I have noticed it's not well defined, how should the lua policy handle cases, when there is no server selected - for example, no server is up.

### Usecase
The case when there is no usable server is an edge-case; when there is no server available, there are usually some deeper problems that will also cause other issues.

However, there should still be _some_ way to signal it.

### Description

I could do one of the following:
* do lua `error("no server")`
* return -1 and let the C++ vector at throw an exception
* return 0 and call it a day, as there will be more deep issue somewhere when all servers are down
* return random ID

The C++ policies do this:

https://github.com/PowerDNS/pdns/blob/f4473506ae3251aa73a2976018cd55061e29d538/pdns/dnsdistdist/dnsdist-lbpolicies.cc#L50

I am not that well-versed in C++ to tell what will happen later when this line is invoked, and how to achieve the same thing when using Lua FFI threads. The Lua code will end up here

https://github.com/PowerDNS/pdns/blob/fa40293c0634f2749799b9d513aa1a675e63da14/pdns/dnsdistdist/dnsdist-lbpolicies.cc#L382

**Comment by rgacogne** [comment]
Thanks a lot for reporting this, and the wonderful quality of the report! 
I'll look into it today or tomorrow, but at a quick glance I believe it would make sense to treat any value larger than the number of candidate backends as "no backend available" and thus return `{}` instead of throwing an exception.

**Comment by karelbilek** [comment]
I will add.

the non-FFI lua can always "fall back" to leastOutstanding/other policies, as I see for example here

https://github.com/sysadminblog/dnsdist-configs/blob/master/orderedLeastOutstanding.lua

```lua
	-- Double check the server list has a value/is defined. I don't think this should
	-- ever happen, but you can't be too safe. If it has no value, then return the server
	-- list.
	if serverlist[lowest] == nil then
		return leastOutstanding.policy(servers, dq)
	end
```

however, that doesn't seem to be available from the FFI per thread policies.

**Comment by rgacogne** [comment]
No, you cannot directly call the `least outstanding` policy from an FFI policy, but you could do what it does by looking at `dnsdist_ffi_server_get_outstanding` for each server.
