### ISSUE TITLE
[DOC] recursor/lua-scripting/netmask.html: confusing formatting

### ISSUE THREAD

**Issue by grinapo** [PowerDNS/pdns#13978]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)
- [X] I have spent multiple brain cells on figuring out what it's about ;-)

 - Program: Recursor documentation
 - Issue type: Bug report

### Short description
Multiple pages of the current documentation has very confusing formatting. An example from netmask.html:

```
Deprecated since version v4.3.0: True if the netmask is an IPv6 netmask.
:isIPv6() → bool
-------
Deprecated since version v4.3.0: True if the netmask is an IPv6 netmask.
:match(address) → bool
  True if the address passed in address matches
```

I guess the `<hr/>` is at a very confusing position, since it seems like `:match()` was deprecated, but reading it a few times it turns out that the sentence below the separator actually part of the verb above the separator (`isIPv6()`). This is true for multiple entries.

### How it should look like instead?
Obvious solution would be use `HR` to separate verbs, and keep all related information between the same two `HR`s, like

```
----
Deprecated since v1234: we don't foo anymore

:foo(address) -> bool
   Do the Foo.
---
```

### Example page
- https://doc.powerdns.com/recursor/lua-scripting/netmask.html

**Comment by omoerbeek** [comment]
Thank for the report, thr mentioned PR should fix the formatting errors.
