### ISSUE TITLE
Hello I need your help about lua scripts

### ISSUE THREAD

**Issue by 370569218** [PowerDNS/pdns#14053]
Hello I need your help about lua scripts
I need to implement such a function through lua: when the user requests all TXT parsing, use the specified authoritative server such as 8.8.8.8 to answer and return the reply record to the user

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests.
Your question looks like a support question. Support questions are
handled in our other online communities: Github discussions, IRC
and our mailing lists. Please see https://www.powerdns.com/opensource.html
for information about those.

We are closing this ticket. Comments will likely be ignored.
