### ISSUE TITLE
auth, rec: no ECDSA with OpenSSL 3.3

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#14084]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
In OpenSSL 3.3 (at least as packaged in Alpine Edge and Debian Experimental), `pkg-config libcrypto --variable=prefix` returns nothing instead of `/usr`. This causes us to fail to find `ecdsa.h`

### Environment
 - Operating system: Alpine Edge, Debian Experimental (both as of today0
 - Software version: auth 4.9, rec 5, probably others
 - Software source: tarballs

### Steps to reproduce
1. build as usual

### Expected behaviour
Working ECDSA, passing tests.

### Actual behaviour
`checking for /include/openssl/ecdsa.h... no`

and the generic signers test fails. Note the path, it's missing `/usr` at the beginning.

### Other information
`--with-libcrypto=/usr` works around the issue

**Comment by rgacogne** [comment]
Might be related to https://github.com/openssl/openssl/issues/23569

**Comment by rgacogne** [comment]
There was a big refactoring in https://github.com/openssl/openssl/commit/2ac569a67b9d0980efa2d8061a6a61e0645f37a7, clearly. I'm not going to dive into that for now.
