### ISSUE TITLE
Documentation of query-local-address for recursor promises things it doesn't appear to do

### ISSUE THREAD

**Issue by berthubert** [PowerDNS/pdns#14148]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program:  Recursor
 - Issue type: Bug report

### Short description
https://doc.powerdns.com/recursor/settings.html#query-local-address suggests that the query-local-address can contain subnets and even negations. This does not appear to be true though.

### Environment
Documentation

### Steps to reproduce
Read the documentation, feel disappointed

### Expected behaviour
Well maybe to support subnets for security, or maybe fix documentation

**Comment by Habbie** [comment]
(with reference to `outgoing-interface` in https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html)

**Comment by Habbie** [comment]
looks like we introduced the doc error in 9883d3f9f2f754f5102bbc1a5e7a4ccfae7b24b7

**Comment by omoerbeek** [comment]
The type is `LType.ListSubnets`, the docs are generated, so it gets the default description. Have to check if the type should change or the docs overridden.
