### ISSUE TITLE
Docker entrypoint script logs secrets

### ISSUE THREAD

**Issue by pschichtel** [PowerDNS/pdns#14149]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description

When using .j2 templates in the container that render files containing secrets (e.g. DB credentials), then those will be logged in their entirety after rendering.

See: https://github.com/PowerDNS/pdns/blob/b09f376f227af016c474d95a3cd09d2e75438ad1/dockerdata/startup.py#L70

### Environment

docker

### Steps to reproduce

1. Mount a .j2 file into /etc/powerdns/templates.d and add it to the `TEMPLATE_FILES` env var
2. Watch the container log for the contents of the rendered template
3. 

### Expected behaviour
Given that any of these templates might eventually contain some sort of secret, I would not have expected these to be logged.

### Actual behaviour
All rendered templates are logged.

**Comment by Habbie** [comment]
Thank you for reporting this! It was fixed in #13849, so I'm closing this ticket.
