### ISSUE TITLE
[rec] Error handling in gettag()

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#14180]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description

There's no proper error handling in the `gettag()` LUA function.  Resolving succeeds, but the error isn't logged anywhere.

### Environment
 - Operating system: Linux Centos 7
 - Software version: 4.9.5
 - Software source: compiled myself but should be like PowerDNS repository

### Steps to reproduce

1. Enable lua scripting in pdns-recursor
2. Add a gettag() function which fails (eg try to do something with a nil var)
3. Launch a query

### Expected behaviour
Log the error in stdout, just as when I make a LUA code error in eg. `preresolve()`.

### Actual behaviour
No logs, no error, resolving succeeds normally.

### Other information
When looking at the docs, I stumbled upon this in the DQ docs:

> tag
> The packet-cache tag set via gettag(), or 0 if it has not been set.

Besides erroring, there is no way to set no tag and tag 0 is a valid tag. To the user who's not 100% aware of this, the above docs suggest it's possible to set "no tag" or/and that 0 would be an illegal tag id. While on the docs, we might document that valid tag range is between 0 and the maximum of `unsigned int` in the C++ env of the package builder (likely to be 2**32-1).

**Comment by omoerbeek** [comment]
0 is the default value the PC tag. If `gettag` is not called or `gettag_ffi` is called but it does not set a tag, the tag value remains 0. This could be explained better indeed.

**Comment by omoerbeek** [comment]
wrt logging: does things change if you enable `log-common-errors`?

**Comment by franklouwers** [comment]
This is the minimal lua test file I crafted to test this issue:

```lua
function gettag(remoteip, ednssubnet, localip, qname, qtype, ednsoptions, tcp, proxyprotocolvalues)
  pdnslog('[gettag] before the error')
  error("[gettag] error error abort")
  pdnslog('[gettag] after the error')
  return 1
end

function preresolve(dq)
  pdnslog('[preresolve] before the error')
  -- error("error error abort line 10")
  pdnslog('[preresolve] after the error')
  return false
end
```

When running as above (so the second `error()` statement commented out), I get this in the logs:

```
msg="[gettag] before the error" subsystem="lua" level="0" prio="Warning" tid="7" ts="1715842577.574"
msg="[preresolve] before the error" subsystem="lua" level="0" prio="Warning" tid="7" ts="1715842577.575"
msg="[preresolve] after the error" subsystem="lua" level="0" prio="Warning" tid="7" ts="1715842577.575"
```

So the second `pdnslog()` in the `gettag` function isn't called. The error makes the function to stop continuing, but there's no error (also note that resolution just works).

For comparison, when I uncomment the `error()` statement in `preresolve()`, I do see the error in preresolve, and resolution fails. 

---

When flipping `log-common-errors` to on, I do see the error reported as:

```
msg="[gettag] before the error" subsystem="lua" level="0" prio="Warning" tid="3" ts="1715842972.981"
msg="Error parsing a query packet for tag determination, setting tag=0" error="[string \"chunk\"]:3: [gettag] error error abort
stack traceback:
        [C]: in function 'error'
        [string \"chunk\"]:3: in function <[string \"chunk\"]:1>" subsystem="in" level="0" prio="Warning" tid="3" ts="1715842972.981" exception="std;:exception" proto="udp" qname="google.com" remote="127.0.0.1:39952"
msg="[preresolve] before the error" subsystem="lua" level="0" prio="Warning" tid="3" ts="1715842972.981"
msg="[preresolve] after the error" subsystem="lua" level="0" prio="Warning" tid="3" ts="1715842972.981"
```

(Resolution still succeeds)

Is there a reason why logging errors in `gettag` depends on `log-common-errors` while in `preresolve` it doesn't? If there is (eg: "it doesn't interfere with resolution"), we should at least document that, both on the `gettag()` page _and_ the `log-common-errors` page.

As for the remark on the other doc about tag 0: yes, I understood that while playing with it, but I feel docs could be improved there.

**Comment by omoerbeek** [comment]
The `log-common-errors` thing is likely because of https://github.com/PowerDNS/pdns/blob/6e22f6423cf41b5b1dddad830e7c89da064a5e51/pdns/recursordist/rec-main.cc#L2310

In general I believe it is not right to hide these kind of errors.

Related to some other issue I am working on changibng this and making sure pdns-distributes-queries yes and no work in the same way.
