### ISSUE TITLE
dnsdist: discrepancy between `Server.upStatus` and `Server:isUp()` when server is administratively down

### ISSUE THREAD

**Issue by gjherbiet** [PowerDNS/pdns#14217]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description
When a server is administratively set to down (using [`Server:setDown()`](https://dnsdist.org/reference/config.html#Server:setDown), there is a discrepancy between [`Server.upStatus`](https://dnsdist.org/reference/config.html#Server.upStatus) and [`Server:isUp()`](https://dnsdist.org/reference/config.html#Server:isUp):

* `Server.upStatus` returns `true`
* `Server:isUp()` returns `false`

### Environment

 - Operating system: Debian 12
 - Software version: 1.9.4 
 - Software source: PowerDNS repository
 
 ```txt
# dnsdist -V
dnsdist 1.9.4 (Lua 5.1.4 [LuaJIT 2.1.0-beta3])
Enabled features: AF_XDP cdb dns-over-quic dns-over-http3 dns-over-tls(gnutls openssl) dns-over-https(h2o nghttp2) dnscrypt ebpf fstrm ipcipher libedit libsodium lmdb protobuf re2 recvmmsg/sendmmsg snmp systemd
 ```

### Steps to reproduce

Using `dnsdist -c`:
```
> showServers()
#   Name               Address                                 State     Qps    Qlim        Ord         Wt    Queries   Drops Drate   Lat   TCP Outstanding Pools
0   server.example.com [2001:db8::1]:53                           up     0.0       0          1          1          0       0   0.0     -     -           0 
> tostring(getServer(0).upStatus)
true
> tostring(getServer(0):isUp())
true
> getServer(0):setDown()
> showServers()
#   Name               Address                                 State     Qps    Qlim        Ord         Wt    Queries   Drops Drate   Lat   TCP Outstanding Pools
0   server.example.com [2001:db8::1]:53                         DOWN     0.0       0          1          1          0       0   0.0     -     -           0 
> tostring(getServer(0).upStatus)
true
> tostring(getServer(0):isUp())
false
```

### Expected behaviour

* `Server.upStatus` returns `false`
* `Server:isUp()` returns `false`

### Actual behaviour

* `Server.upStatus` returns `true`
* `Server:isUp()` returns `false`

### Other information

If this is the behaviour intended by the developers, then this shall be clearly indicated in [the `Server` class documentation](https://dnsdist.org/reference/config.html#Server) in order not to mislead users.

**Comment by rgacogne** [comment]
Right, the documentation is terrible here. `upStatus` is basically the last known state based on health-checks. `isUp()` checks if there is an administrative status override (forced `UP` or `DOWN`)  in which case it returns this status, and otherwise returns `upStatus`.
If you are willing to open a PR fixing the documentation that would very much appreciated :)
