### ISSUE TITLE
Improve docker image names and tags

### ISSUE THREAD

**Issue by zadjadr** [PowerDNS/pdns#14238]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request

### Short description

The current docker images have names that can not be easily maintained via automation (e.g. renovatebot).

Usually the image tag should be the version defining information, while the image name does not have any reference to a "version". In powerdns' case we see something like https://hub.docker.com/r/powerdns/pdns-auth-49 which indicates a major version of `49`.

### Usecase

I want to be able to do major version updates using renovatebot.

### Description

Build images with a name of e.g. `powerdns/pdns-auth` and `semvar` as versioning scheme e.g. `49.4.9`.

**Comment by Habbie** [comment]
This discussion is already happening in #12068, so I'm closing this. It is likely we'll change the naming schema at some point. Thanks!
