### ISSUE TITLE
direct RRSIG queries suck

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#1426]
@mind04 points out that (a) direct RRSIG is "broken" in various other places  (b) that he has been returning NOTIMP to direct RRSIG queries for a year, without trouble.

The only real reason I know of to support direct RRSIG queries is that this broken Nagios plugin relies on it: http://dns.measurement-factory.com/tools/nagios-plugins/check_zone_rrsig_expiration.html

Suggestion: have these people fix their plugin; then drop direct RRSIG support. If people get this broken plugin from Debian (who for their own infra run a fixed version!) this is not our problem.

ORIGINAL TICKET CONTENT FOLLOWS (title was: direct RRSIG query to secure delegations returns RRSIG NS)

Under `start-test-stop 5300 bind-dnssec wait`: 

```
$ dig +dnssec rrsig dsdelegation.example.com @127.0.0.1 -p 5300 |grep RRSIG | awk '{print $5 " " $12}'
NS example.com.
DS example.com.
NSEC example.com.
```

(output shows type and signer name). NS should not be in there.

Not sure we should really care.

**Comment by cjhenck** [comment]
Would you consider re-opening this?  Supporting direct RRSIG queries would make it possible to create validating stub resolvers that work when recursives don't support the DO bit.

**Comment by Habbie** [comment]
> Would you consider re-opening this? Supporting direct RRSIG queries would make it possible to create validating stub resolvers that work when recursives don't support the DO bit.

Do those exist?

**Comment by mind04** [comment]
If they do they suck.
There is also no way to get NSEC3 records without a DO bit. So proving the non existence of a DS is most of the time impossible.

Please do not provide a gun big enough to shoot whole limbs in pieces.

**Comment by Habbie** [comment]
I also realised nsec/nsec3 after reopening. Closing again.

**Comment by cjhenck** [comment]
> Do those exist?

They seem to, or at least very well might. There hasn't been wide client-side adoption of DNSSEC to date, and reducing the likelihood of problems for implementers should be a good goal on its own.

> Please do not provide a gun big enough to shoot whole limbs in pieces.

Not sure I understand the analogy. I would think proving that a known target DS is poisoned has greater value than proving nothing at all?

**Comment by Habbie** [comment]
> reducing the likelihood of problems for implementers should be a good goal on its own

An implementer that does direct RRSIG queries has a massively increased likelihood of problems. Such an implementer will be unable to validate any insecure delegation, for example - which means an attacker can just fake up an insecure delegation to mess with anything, even if actually signed.

**Comment by cjhenck** [comment]
Ah got it that makes sense. Fair enough.  Thanks for the insight.

**Comment by Habbie** [comment]
No problem, thank you for understanding!
