### ISSUE TITLE
API: dnssec support (Auth)

### ISSUE THREAD

**Issue by xbgmsharp** [PowerDNS/pdns#1433]
DNSSEC is not implemented yet.
https://github.com/PowerDNS/pdnsapi/blob/master/api_spec.md#post-2

I wish to use the API instead of talking direct database access.
Mainly because it generate valid zone data and the zone will be properly "rectified".

How can I help to get it implement?

[edit] Response by Habbie follows

We need:
- [x] key management
- [ ] metadata management (SOA-EDIT, NSEC3PARAM)
- [ ] rectification

The first two should be easy - and if we tell people to run rectify from cron, or say 'DNSSEC only supported in AXFR-out or NARROW mode', the first two already help a lot of people.

For rectification - we currently have incremental rectify code in the 2136 handler. It would be great to factor that out of there so we can reuse it for the API.

**Comment by Habbie** [comment]
PR #3417 is related

**Comment by stbuehler** [comment]
Given the [documentation for `PATCH`][1] and the other zone **modification** requests doesn't mention how broken this is I'd consider this a bug, not an enhancement.  Also this is a really serious limitation of the API.

[1]: https://doc.powerdns.com/authoritative/http-api/endpoint-zones.html#patch--api-v1-servers--server_id-zones--zone_id

**Comment by zeha** [comment]
This should all be part of 4.1.0 already, just behind the rectify flag.
