### ISSUE TITLE
Complement AXFR-SOURCE with NOTIFY-SOURCE?

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#1436]
Should we complement AXFR-SOURCE (slave option) with NOTIFY-SOURCE (master option), allowing us to define per-domain level notification source IP? This would assist with multihomed systems which might need to notify using, say, internal IP or specific IP for legacy purposes.

**Comment by Habbie** [comment]
We'll revisit this if somebody actually needs it.

**Comment by PeterN** [comment]
Well, I think I need this, especially with IPv6 where privacy addresses get used instead of the fixed address.

**Comment by Habbie** [comment]
> Well, I think I need this, especially with IPv6 where privacy addresses get used instead of the fixed address.

On a server?
