### ISSUE TITLE
recursor: [BUG(?)] Dashboard does not show real remote ip

### ISSUE THREAD

**Issue by dermalikmann** [PowerDNS/pdns#14364]
### Short description
We are using two pdns  recursors behind two dnsdist servers. We noticed that the recursor webui / dashboard is showing only the  dnsdist IP addresses, instead of the real remote IPs, even though we enabled the proxy protocol (both in dnsdist with `useProxyProtocol = true` and in the recursors with `proxy_protocol_from`.

### Environment
OS: RHEL 9.4
dnsdist: v1.9.4
pdns-recursor: v5.1.0-beta1

### Config / steps to reproduce

```
#> head /etc/dnsdist/dnsdist.conf
newServer({address="172.16.1.57", name="neu1", weight=1, useProxyProtocol=true})
newServer({address="172.16.2.57", name="neu2", weight=1, useProxyProtocol=true})
setServerPolicy(wrandom)
controlSocket("127.0.0.1:5199")
setKey("REDACTED")
setLocal("0.0.0.0")
setSecurityPollSuffix("")
webserver("0.0.0.0:8083")
```

```
#> cat /etc/pdns-recursor/recursor.yml
incoming:
  allow_from: []
  listen:
    - 127.0.0.1
    - 172.16.1.57
  port: 53
  proxy_protocol_from:
    - 172.16.0.0/16

logging:
  quiet: true

recursor:
  include_dir: /etc/pdns-recursor/recursor.d
  setgid: pdns-recursor
  setuid: pdns-recursor

webservice:
  address: 172.16.1.57
  allow_from:
    - 0.0.0.0/0
  api_key: REDACTED
  loglevel: none
  password: REDACTED
  port: 8082
  webserver: true
```

### Expected behaviour
Be able to see the true client IPs instead of loadbalancing proxies

**Comment by rgacogne** [comment]
This issue sounds a lot like https://github.com/PowerDNS/pdns/pull/14340, any chance you could test if it fixes the issue for you?

**Comment by dermalikmann** [comment]
I sadly cant test this rn, as I don't have to option to build it myselt right now (maybe tomorrow) and using one of the artifacts does not work, as they seem to be dependent on `libboost_context.so.1.74.0` which is not available in the epel9 repositories.

**Comment by omoerbeek** [comment]
I think there's some confusion, which artifacts are you talking about?
Anyway, I triggered a package build for the rel/5.0.x branch, which includes the fix. Will let you know when it's ready. Our CI seems to be pretty busy atm...

**Comment by omoerbeek** [comment]
Hmm I see you are running 5.1.0-beta1. In that case you can try the auto-built master branch, which can be downloaded from https://downloads.powerdns.com/autobuilt/recursor/5.1.0-beta1.89.master.g610b25bcd/pdns-recursor-5.1.0-beta1.89.master.g610b25bcd-el-9.tar.bz2

**Comment by dermalikmann** [comment]
I just tested this, and it seems to work!

Thank you very much for the fix. I consider this issue closed now :)
