### ISSUE TITLE
pdns_server --version writes to STDERR instead of STDOUT

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#14455]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative
 - Issue type: Bug report

### Short description
`pdns_server --version` writes its output to STDERR.  In my opinion this is wrong because there is no error. It is also not consistent with dnsdist and Recursor.

### Environment

 - Software version: PowerDNS Authoritative Server 4.9.0

### Steps to reproduce
```
pdns_server --version 2>/dev/null
```
does not show anything, which is wrong.

### Expected behaviour
It would be nice if `pdns_server --version`  would write to STDOUT instead of STDERR

### Actual behaviour
`pdns_server --version` writes to STDERR

**Comment by omoerbeek** [comment]
This should be consistent for all products.
Fixing this requires some plumbing in `showProductVersion()` and friends, which now are hardcoded to use logging, which used the C++ stream `clog`, which is sent to `stderr`.

**Comment by omoerbeek** [comment]
Fixed in #14518

**Comment by paddg** [comment]
Thank you!
