### ISSUE TITLE
 auth API: Include cause of Internal Server Error in response body

### ISSUE THREAD

**Issue by jvns** [PowerDNS/pdns#14637]
- Program: Authoritative API
 - Issue type: Feature request

### Short description

When I get an internal server error from the PowerDNS API, it doesn't include any information about specifics of the error in the HTTP response itself -- I need to hunt through the logs to find an explanation. 

For example, in #14564, the response body on the 500 is just "Internal Server Error", but the logs are much more specific about the nature of the error:

> Sep 09 08:29:04 [webserver] 5cef8303-60bc-435b-8eac-3b01d92ce5f1 HTTP ISE for "/api/v1/servers/localhost/zones/example.com.": Exception: GSQLBackend unable to delete RRSet test9.example.com|A: Error while retrieving SQLite query results: database is locked (5)

### Usecase

I'm getting a few "Internal Server Error"s in my website that's using PowerDNS, but because the API doesn't report the nature of the error I'm not able to figure out what's going on.

I don't save my logs anywhere so I can't look it up in the logs. (though likely I'll change that to be able to track down the error)

**Comment by Habbie** [comment]
Can you try sending `Accept: application/json`? That appears to help here in a somewhat contrived test.

**Comment by jvns** [comment]
Thanks for the suggestion, will try that! If I send `Accept: application/json` in the test example from https://github.com/PowerDNS/pdns/issues/14564, I get this response body instead which doesn't add more information, but I can try implementing it in my application more generally and maybe it'll help.

```
{"error": "Internal Server Error"}
```

**Comment by Habbie** [comment]
ah yes you are right, I had already patched a few things before I realised the accept header might matter. I'll see if I can PR something soon.

**Comment by Habbie** [comment]
#14670
