### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [PowerDNS/pdns#14635]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing PowerDNS application as shown [here](https://elest.io/open-source/powerdns). I think it would be a great idea if we can add it to official readme/documentation here. I would appreciate it if you can guide me to correct file where I can add this.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/powerdns)

**Comment by Habbie** [comment]
hi there! We cannot endorse specific providers in our docs. For a commercial conversation, please head over to https://www.powerdns.com/contact-us

good luck!
