### ISSUE TITLE
PowerDNS Authoritative Webserver authentication is not working

### ISSUE THREAD

**Issue by John222** [PowerDNS/pdns#14672]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Webserver password authentication is not working. As soon a password is set, the access to the http webserver is not possible anymore. As response a 401 is always returned.

### Environment
 - Operating system: RHEL 9
 - Software version: 4.9.1-1pdns.el9
 - Software source: PowerDNS repository

### Steps to reproduce
1. Set the ```webserver-password``` variable inside the ```/etc/pdns/pdns.conf``` configuration file. For example set as password 'password'
2. Trying to access the url http://127.0.0.1:8081/ with curl ```curl -u "user:password" http://127.0.0.1:8081/```

### Expected behaviour
The statistics page should be displayed

### Actual behaviour
Receiving the following output:

```Unauthorized```

**Comment by kpfleming** [comment]
This is true of all configuration items in the auth configuration, I believe: none of them need to be enclosed in quotes, so if they are those quotes are part of the value.

**Comment by John222** [comment]
I gonna close the ticket now. Thank you for the quick reply.
