### ISSUE TITLE
Recursor package build downloads Rust twice

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#14748]
Installing it twice makes sense as far as I can see - we need Rust during sdist and during the actual package build (if I am not mistaken). Downloading it twice is a waste. Perhaps we can COPY the file from the previous stage, or keep it in a shared volume?

Sidenote: both downloads use curl with a progress bar which causes hundreds of loglines in CI. `--silent --show-errors` would probably make sense there.

**Comment by omoerbeek** [comment]
I don't think rust is used for a the make sdist target, but we do check if rust is available during configure, so installing it in the sdist stage it is not easily avoidable. I'll take a look into the progress bar and double downloading.
