### ISSUE TITLE
dnsdist: Building our package with Quiche is broken on CentOS-based systems

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#14757]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

Upgrading the Rust compiler to 1.81.0 had the unexpected side-effect to embed the `SONAME` inside the `Quiche` shared library, which we try hard not to have, because RPM is then very unhappy about the library dependency.
I tracked it to https://github.com/rust-lang/rust/pull/126094#issuecomment-2377778398, with a fix for the regression already available in Rust's main branch: https://github.com/rust-lang/rust/pull/130960

I'm a bit unsure how to proceed. @omoerbeek, would it be possible to downgrade Rust to 1.80.1 until a new version of Rust including the fix is available?

**Comment by omoerbeek** [comment]
Sure, I'll do that in a minute.

**Comment by rgacogne** [comment]
Fixed by #14758, as demonstrated by https://github.com/PowerDNS/pdns/actions/runs/11235546149 Thanks, Otto!
