### ISSUE TITLE
PDNS authoritative server ID column overrun for records

### ISSUE THREAD

**Issue by ronnybremer** [PowerDNS/pdns#14798]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative
 - Issue type: Bug report

### Short description
Using MySQL as a backend the ID column did overflow after many years of operation. ID column is current type "INT" and hit the ceiling at 2147483646.

### Environment

 - Operating system: Rocky Linux 8
 - Software version: 4.6.4
 - Software source: OS repo

### Steps to reproduce

1. let it run for a long time with lots of dynamic updates coming in through AXFR
2. monitor the MAX(ID) value in the DB on the records table
3. see it reaching the maximum INT value

### Expected behaviour
maybe using BIGINT?

### Actual behaviour
INT column did reach the maximum value

### Other information
maybe there is a way to "re-org" the table, but I wouldn't know if the ID column from the records table is referenced somewhere else.

**Comment by ronnybremer** [comment]
unable to xfr zone (PDNSException): GSQLBackend unable to feed record bsl.ch.almanid.com|NS: Could not execute mysql statement: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth) values (?,?,?,?,?,?,?,?,?): Duplicate entry '2147483647' for key 'records.PRIMARY'

**Comment by Habbie** [comment]
> maybe using BIGINT?

the schema has said BIGINT since 4.1.0. Did you miss part of a schema migration?

**Comment by ronnybremer** [comment]
@Habbie uhm ... that would be possible, I will verify it. Thank you for the hint!

**Comment by ronnybremer** [comment]
grrr ... thank you again @Habbie! The schema was modified before, but the 3.4 to 4.1 was never executed. I did that now and the issue immediately went away.
