### ISSUE TITLE
Recursor latency increased 600% after updating from 48 to 51

### ISSUE THREAD

**Issue by romantomjak** [PowerDNS/pdns#14832]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description
Hello! 👋 

First of all - big thanks for making this software. I just wanted to drop a quick note on
a possible performance regression after updating debian repo from 48 to 51.

Query latency increased from 4ms to about 35ms on average after the upgrade with
no changes in config from my side.

### Environment
 - Operating system: Debian 6.1.0-26-amd64
 - Software version: 5.1.2
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install recursor from 48 repo
2. Run some queries and measure latency
3. Install recursor from 51 repo
4. The measured latency should now increase

### Expected behaviour
I expected latency to roughly stay the same

### Actual behaviour
Latency increased increased 600%

### Other information

Before update latency hovers at 4ms
<img width="718" alt="image" src="https://github.com/user-attachments/assets/d32eb77a-8a35-48f6-a90a-7c353028017d">

After update latency does not go below 15ms and peaks at 40ms
<img width="722" alt="image" src="https://github.com/user-attachments/assets/413525c0-18c3-4c32-b5e0-b822170fb2e1">

Answer buckets
<img width="721" alt="image" src="https://github.com/user-attachments/assets/7bf86a12-75c4-4337-a862-abf165b3cba1">

Prometheus queries for the graphs:
```promql
avg_over_time(pdns_recursor_x_our_latency[$__rate_interval])
avg_over_time(pdns_recursor_qa_latency[$__rate_interval])

increase(pdns_recursor_answers0_1[$__rate_interval])
increase(pdns_recursor_answers1_10[$__rate_interval])
increase(pdns_recursor_answers10_100[$__rate_interval])
increase(pdns_recursor_answers100_1000[$__rate_interval])
increase(pdns_recursor_answers_slow[$__rate_interval])
```

recursor.conf
```ini
# See https://doc.powerdns.com/recursor/settings.html

local-address=...
allow-from=...

refresh-on-ttl-perc=10

max-negative-ttl=300

lua-dns-script=/var/lib/powerdns/adblock.lua

forward-zones-recurse=...

webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=...
webserver-password=...
```

adblock.lua
```lua
driver = require "luasql.sqlite3"
env = assert( driver.sqlite3() )
con = assert(env:connect("/var/lib/powerdns/adblock.db"))

function preresolve(dq)
    domain = dq.qname:toStringNoDot()

    while domain ~= "" do
        local sth = assert(con:execute(string.format("SELECT 1 FROM domains WHERE name = '%s'", con:escape(domain))))
        if sth:fetch() then
            dq.variable = true -- disable packet cache
            dq.rcode = pdns.NXDOMAIN
            dq:addAnswer(pdns.TXT, "\"dropped by adblock\"", 1) -- for debugging
            return true
        end
        domain = domain:gsub("^[^.]*%.?", "")
    end

    return false
end
```

**Comment by phonedph1** [comment]
What is measuring "Query latency"?

**Comment by romantomjak** [comment]
Apologies, just updated the issue. This is measured by prometheus via the `/metrics` exposed by the powerdns webserver

**Comment by phonedph1** [comment]
Any clues in the pdns_recursor_answers* metrics (or the auth4/auth6 separate ones)?

**Comment by omoerbeek** [comment]
Please show your configuration.

It might a case of https://docs.powerdns.com/recursor/performance.html#threading-and-distribution-of-queries (specific allythe Imbalance section). Please show some lines of the reported periodic stats.

There were also changes in the way metrics are computed between 4.8 and 5.1, but we need more data to decide what is going on.

Do you have any measures of latency seen by clients?

**Comment by omoerbeek** [comment]
I edited the stats to make the more readable. They look reasonable at first sight. Though `failed-host-entries` is a bit high and `taskqueue-expired` as well.

Can you push stats to our public metronome server?
Something like:

```
carbon-ourname=yourrecname
carbon-server=37.252.122.50
```
This allows us to seen most relevant stats, often it reveals something.
Check https://metronome1.powerdns.com to see examples and your stats once enabled.

If that does not reveal anything I'm going to try to reproduce (that will be tomorrow earliest). I might need your sqlite DB for proper reproduction.

**Comment by omoerbeek** [comment]
Oh, and please show `rec_control top-timeouts`

**Comment by romantomjak** [comment]
Sure, I've set `carbon-ourname` to `pdns.recursor.gh-issue-14832` 👍 


```sh
$ rec_control top-timeouts
Over last 2070 entries:
4.30%	205.251.193.96
4.06%	205.251.197.100
3.82%	205.251.193.127
3.57%	205.251.197.116
3.19%	205.251.192.166
2.80%	205.251.197.213
2.75%	205.251.192.248
2.61%	205.251.197.38
2.37%	205.251.196.72
2.32%	205.251.193.178
1.93%	205.251.192.153
1.74%	205.251.197.248
1.59%	205.251.192.159
1.55%	47.241.207.18
1.55%	205.251.196.174
1.50%	205.251.192.235
1.45%	205.251.196.48
1.40%	47.241.207.16
1.40%	205.251.197.41
1.30%	64.98.148.18

52.80%	rest
```

**Comment by romantomjak** [comment]
I've uploaded the [adblock.db to backblaze](https://f002.backblazeb2.com/file/0a242dcd75-pdns/adblock.db) in case you need it

**Comment by mnordhoff** [comment]
Almost all of those IPs — the ones in `205.251.192.0/21` — are from Amazon’s Route 53 DNS service. Do you know why it’s not responding reliably? AWS is not having a massive global DNS outage today.

For example, does “`mtr -4 -r -w -c 60 205.251.193.96`” work? (Note that Amazon’s network can be a bit funny and mtr or traceroute can have issues even if normal traffic works.)

Or what does “`dig +norecurse slackb.com ns @205.251.193.96`” output (picking a random domain hosted on that nameserver)?

I don’t think `slackb.com` is in that blocklist, but I might be mistaken, or maybe another domain is. This is wild speculation — and the last time I speculated wildly about something, I was wrong — but maybe some of the “timeouts” are related to how blocked queries are accounted for?

**Comment by omoerbeek** [comment]
I don't see your server coming through yet on https://metronome1.powerdns.com/

**Comment by romantomjak** [comment]
hmm, interesting. Im not getting anything back from that IP. I cancelled the mtr because there was no output

```
$ mtr -4 -r -w -c 60 205.251.193.96
Start: 2024-11-07T10:49:53+0000
^C

$ dig +norecurse slackb.com ns @205.251.193.96
;; communications error to 205.251.193.96#53: timed out
;; communications error to 205.251.193.96#53: timed out
^C

$ ping 205.251.193.96
PING 205.251.193.96 (205.251.193.96) 56(84) bytes of data.
^C
--- 205.251.193.96 ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8190ms

```

**Comment by romantomjak** [comment]
omoerbeek I restarted the service but for some reason it didn't pick up the new config 🤔 I did a start/stop just now and looks like it appears on the list now!

**Comment by romantomjak** [comment]
Ok, I think it didn't like dots in the name (which docs warn against "Be careful not to include any dots in this setting, unless you know what you are doing." 😅 I changed it to just `gh-issue-14832` and I [can see it in the list now](https://metronome1.powerdns.com/?server=pdns.gh-issue-14832.recursor&beginTime=-7200)

**Comment by mnordhoff** [comment]
It's unusual to be unable to dig or ping/mtr one of the world's larger DNS services. Do only some zones and nameservers fail or all of them?

Is there a firewall blocking ICMP, or intercepting some DNS traffic?

Or a BGP routing issue with Amazon?

Hard to imagine network issues being related to a PowerDNS upgrade, but it is odd.

**Comment by omoerbeek** [comment]
Fixing the reachability of Route 53 servers is important of course.

My hypothesis is that the network issues already existed with the 4.8 recursor, but is now more visible in the metrics.
A cause could be https://docs.powerdns.com/recursor/settings.html#bypass-server-throttling-probability, resulting in more attempts at contacting the unreachable auths than before. I'll spend some time to confirm or refute that hypothesis tomorrow.

**Comment by romantomjak** [comment]
My firewall is pretty basic and I'm not blocking any hosts explicitly. I can receive replies if I ping hosts on the internet. I'll dig a bit more to see which hosts exactly are failing.

Yeah, potentially. I've raised this with my ISP so they take a look too

**Comment by omoerbeek** [comment]
Did a couple of test runs with both 4.8 and 5.1

- With no auth IPs blocked
- With some Route53 IPs blocked
- With many Route53 auths blocked

I saw nothing like the increase in reported latency between 4.8 and 5.1 like you did. Actually, in all test runs 5.1 had a bit lower reported latency.

So I'm not sure what is causing your reported latency to be higher. Some guesses

- Your Lua code matters (I did not test yet with your Lua script)
- Your `forward-zones-recurse=... ` config matters. Please show it!
- For some other reason the unreachable auths have a bigger impact on measured latency in 5.1 than on 4.8, in manner not covered by my test. Maybe your query traffic is much different from my test set (I took a capture of the DNS traffic to a resolver in my local LAN as test set)

Probably it's best to leave this for a moment until the routing to Route53 is fixed and see how that influences the reported latency.

**Comment by romantomjak** [comment]
Sure, the `forward-zones-recurse` is set to `forward-zones-recurse=home.arpa=127.0.0.2:53` which points to a powerdns authoritative server that handles my private zones.

I also did a quick test on `rec_control top-timeouts` output and I'm not getting any DNS replies from the whole 205.251.192.0/21. Thanks everyone for looking into this, but I'm starting to think this one might be for my ISP. I'll report back when I hear from them.

**Comment by omoerbeek** [comment]
OK, in that case (forwarding to an authoritative server) you should normally use `forward-zones` and not `forward-zones-recurse`, though in your use-case the difference probably does not matter.

**Comment by omoerbeek** [comment]
Closing as it is extremely likely this was an local issue.
