### ISSUE TITLE
dnsdist: add DNSQType GSS-TSIG

### ISSUE THREAD

**Issue by tomwijnroks** [PowerDNS/pdns#14839]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Add DNSQType for GSS-TSIG so these type of DNS requests can be refused in dnsdist to prevent unnecessary logging.

### Usecase
Refuse GSS-TSIG requests to dnsdist when the GSS-TSIG feature was not compiled in PowerDNS. When GSS-TSIG was not compiled in PowerDNS every GSS-TSIG request logs the following message:
```
Nov 11 15:22:52 ns1 pdns_server[3681960]: GSS-TSIG request but not feature not compiled in
```
### Description
It seems it is already possible to refuse these requests with `DNSQType.TKEY`, so I'm not sure if a specific `DNSQType.GSSTSIG` type is _really_ necessary.

I've also caputered some of these requests but the pcap contains sensitive data, which I'm not allowed to upload publicly. If this pcap file can help and there is a way to share it privately, please let me know.

**Comment by Habbie** [comment]
There's no GSS-TSIG qtype in DNS at all. If blocking TKEY does the job for you, I'm not sure there's any work left for us.

**Comment by tomwijnroks** [comment]
I was not really sure about this because the TSIG type also exists, which does not prevent these requests.

Thank you for your fast reponse, this issue can be closed.

**Comment by patrickpoortman** [comment]
https://github.com/PowerDNS/pdns/blob/98128bb78a44349504592ca6780ad0e4594293f9/pdns/tkey.cc#L74

Is the log level `error` correct for this case?  As the function is not compiled. And anybody can trigger this message.

**Comment by Habbie** [comment]
> And anybody can trigger this message.

Agreed, we should log it less, or make it optional.
