### ISSUE TITLE
auth: reduce logging for "GSS-TSIG request but feature not compiled in"

### ISSUE THREAD

**Issue by patrickpoortman** [PowerDNS/pdns#14841]
- Program:  auth 
 - Issue type: Feature request

### Short description
Reduce logging output when GSS-TSIG requests are made to auth when the GSS-TSIG feature was not compiled in PowerDNS to prevent unnecessary logging. Or make this log message optional.

### Usecase
For each GSS-TSIG request made there is a log entry made at the error level, when it is not part of the compile options.
```
Nov 11 15:22:52 ns1 pdns_server[3681960]: GSS-TSIG request but not feature not compiled in
```

### Description
Reduce the loglevel to info or implement a way to filter the log output being written to the logfiles. 
Currently the error is defined here; https://github.com/PowerDNS/pdns/blob/98128bb78a44349504592ca6780ad0e4594293f9/pdns/tkey.cc#L74

This issue has been created based on the comment in https://github.com/PowerDNS/pdns/issues/14839#issuecomment-2468467498

**Comment by omoerbeek** [comment]
Two lines above the same. Level should probably be "Debug". I'll make a PR (I am the author iirc).

**Comment by omoerbeek** [comment]
Actually, this is an auth issue, not a dnsdist issue, I'll edit it a bit.
