### ISSUE TITLE
Some errors in the PowerDNS Recursor documentation

### ISSUE THREAD

**Issue by egnun** [PowerDNS/pdns#14860]
Hello, PowerDNS folks, 

I found some errors in the documentation.

### Environment
 - Operating system: GNU+Linux
 - Software version: 4.9.9
 - luajit: 2.1.1707061634
 - Software source:Operating system repository

The first errors are in the ["The DNSName object":](https://doc.powerdns.com/recursor/_sources/lua-scripting/dnsname.rst.txt)

1. In the very first codeblock it  says:
`name2:chopoff() …`
that should be:
`name2:chopOff()…`

2. Also, the `print(…)` statements don't seem to work
I don't know, if I don't know enough about Lua or if I may have misconfigured something, but the print statements don't have an output in the logfile/journald.
Replacing them with `pdnslog(<stuff to print>)` seems to work though.
E.g. instead of
`print(myname:wirelength()) -- prints "17"`
just:
`pdnslog(myname:wirelength()) -- prints "17"`

I've also found an error in the ["Operating PowerDNS Recursor"](https://doc.powerdns.com/recursor/running.html)

Here it says 
> "By setting [logging.quiet](https://doc.powerdns.com/recursor/yamlsettings.html#setting-yaml-logging-quiet) to true …

There you are linking to the new YAML style settings, which is confusing, since it's the only time you do that.

I hope this helps.

P.S.: I would've submitted a PR with the fixes, but it seems, that you don't have your documentation in a public repo (like Nitrokey or Nextcloud have ;-)

**Comment by omoerbeek** [comment]
1. Correct
2. Indeed, it us  better to use `pdnslog`, as some supervisors like systemd tent to "hide" output.
3. Old stytle settings are on their way out, but I agree there should be some consistency in a page.

The doc sources can be found in pdns/pdns/recursordist/docs
