### ISSUE TITLE
Long LUA broken moving from gpg to lmdb

### ISSUE THREAD

**Issue by mw-0** [PowerDNS/pdns#14875]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative 
 - Issue type: Bug report

### Short description
I have been using gpg backend and have been testing moving to LMDB.  When i run b2bmigrate i find a long LUA line is split in a breaking way.  I see there was a patch i thought would fix this on 4.9.1 merged but i still have an issue.

### Environment

 - Operating system:  debian12
 - Software version: 4.9.1 
 - Software source: PowerDNS repository

### Steps to reproduce
This is the entry i get after migrate:
aaa.tests.bob.net 60 IN LUA CNAME ";if(continent('EU')) then return 'aaaeu.tests.bob.net' elseif(continent('NA')) then return 'aaaus.tests.bob.net' elseif(continent('SA')) then return 'aaaus.tests.bob.net' elseif(continent('AS')) then return 'aaaas.tests.bob.net' else return 'aaarw.tests.b" "ob.net' end"
Its a length issue as i can reduce the size.  I also tried to edit the entry and it still splits on this point.  

### Expected behaviour
aaa.tests.bob.net 60 IN LUA CNAME ";if(continent('EU')) then return 'aaaeu.tests.bob.net' elseif(continent('NA')) then return 'aaaus.tests.bob.net' elseif(continent('SA')) then return 'aaaus.tests.bob.net' elseif(continent('AS')) then return 'aaaas.tests.bob.net' else return 'aaarw.tests.bob.net' end"

### Actual behaviour
When i try and return this entry i get this in the logs:
Nov 24 22:44:53 Lua record (aaa.tests.bob.net|CNAME) reported: When parsing CNAME trailing data was not parsed: '   ob.net'

### Other information
My settings are:
    lmdb-filename=/lmdb/db
    lmdb-shards=1
    lmdb-random-ids=yes
    lmdb-flag-deleted=yes
    lmdb-lightning-stream=yes

**Comment by Habbie** [comment]
> I see there was a patch i thought would fix this on 4.9.1 merged but i still have an issue.

Did you enable that feature, by setting `lua-records-insert-whitespace=no` ?

**Comment by mw-0** [comment]
> > I see there was a patch i thought would fix this on 4.9.1 merged but i still have an issue.
> 
> Did you enable that feature, by setting `lua-records-insert-whitespace=no` ?

Hi,

This does resolve my issue.  Many Thanks
