### ISSUE TITLE
dnsdist is starting new TSL/TCP connection every second to a DoH backend and resetting old connection

### ISSUE THREAD

**Issue by karelbilek** [PowerDNS/pdns#14914]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description
When I add DoH backend, dnsdist is sending RST packets to the backend every second. It is also resetting the connections and starting new TLS and TCP connections instead of keeping the old connection.

I don't think it's the intended behavior?

If it is the intended behavior, is it described somewhere? Why is it intended to start a new connection?

### Environment

 - Operating system: Debian Linux
 - Software version: dnsdist 1.9.7
 - Software source: PowerDNS repository

### Steps to reproduce

1. Empty debian, install dnsdist package from repo
2. add
    ```
   newServer({address="8.8.8.8:443", tls="openssl", subjectName="dns.google", dohPath="/dns-query", validateCertificates=true})
     ```
     to `/etc/dnsdist/dnsdist.conf`, restart service. (This works with other DNS providers too, not related to Google DNS.)
3. `sudo tcpdump -w all.pcap` (or ` sudo tcpdump -w rst.pcap 'tcp[tcpflags] & (tcp-rst) !=0'` to see the resets)
4. open the pcaps in wireshark

### Expected behaviour

There will be one TLS / TCP connection in a pool that will be reused, and the healthchecks will be sent on that connection. 

### Actual behaviour

Every second, you can see RST packet being sent, and you can see a new TLS / TCP connection being done.

This trips our internal metrics, and it's generally strange behaviour.

I can replicate it on different servers, it doesn't seem related to network or specific OS.

### Other information

I don't see any option about how long should the TCP connection be. If I miss it and there is just some switch to set that the connection should take longer and not keep starting/ending, I can of course set it. But I don't think creating new TLS connection every healthcheck is correct?

**Comment by rgacogne** [comment]
Are you sure you are not looking at the connections made by the health-check mechanism? We don't reuse existing TCP connections for these because we might miss an issue where the backend doesn't accept new TCP connections if we did.

**Comment by karelbilek** [comment]
Yeah the behavior is as described in https://github.com/PowerDNS/pdns/issues/12771#issuecomment-1532746482

And the lazy checks work as expected.

I think I will close this, thanks

**Comment by rgacogne** [comment]
Thank you for reporting back, much appreciated!
