### ISSUE TITLE
dnsdist: Queries to DoH listeners seem to trigger packet cache lookup collisions when ECS enabled

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#14959]
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist
 - Issue type: Bug report

### Short description
DoH queries seem to trigger packet cache lookup collisions instead of cache hits when ECS is enabled

### Environment
 - Operating system: Ubuntu 24.04 LTS
 - Software version: dnsdist 1.9.7
 - Software source: PowerDNS repository

### Steps to reproduce
1. Configure backend (e.g. pdns-recursor) and enable ECS with `useClientSubnet=true`
2. Add packet cache with `parseECS=true`
3. Add DoH listener
4. Send similar DoH queries, e.g. with sdig: `sdig https://127.0.0.1/dns-query 443 test.com a recurse`
5. Check packet cache statistics

### Expected behaviour
All test queries except for the first should basically become packet cache hits and not fall through to the backend.

### Actual behaviour
The first query is a cache miss, causes 1 packet cache entry. All further queries are "lookup collisions" and cause queries towards the backend.
Similar UDP queries hit the cache as expected.

```
> getPool(''):getCache():printStats()
Entries: 1/3000000
Hits: 0
Misses: 1
Deferred inserts: 0
Deferred lookups: 0
Lookup Collisions: 18
Insert Collisions: 0
TTL Too Shorts: 0
Cleanup Count: 1
```

### Other information
As discussed.

**Comment by rgacogne** [comment]
I have been able to reproduce the issue (note that you need a backend that is actually sending back an EDNS Client Subnet scope set to 0 otherwise everything works as expected), I expect to have a fix soon.
