### ISSUE TITLE
Avoid concurrent transfers for the same zone

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#1502]
In some situations, PowerDNS queues and performs multiple zone transfers for the same zone. If the zone transfer is the first zone transfer and there are concurrent zone transfers, the zone may be inserted twice into the records table.

Please see the thread http://mailman.powerdns.com/pipermail/pdns-users/2014-July/010710.html for a detailed problem description.

**Comment by ahupowerdns** [comment]
```
  {
    Lock l(&d_lock);
    if(d_inprogress.count(domain)) {
      return; 
    }
    d_inprogress.insert(domain);
  }
```
This got addressed in april 2016.

**Comment by klaus3000** [comment]
Any reason why this was not backported to 3.4?

**Comment by ahupowerdns** [comment]
Because 3.x does not get bugfixes anymore -> https://doc.powerdns.com/md/end-of-life/
In addition, the authoritative server has very few users that support the development, so we can't devote too many resources to older releases.

**Comment by klaus3000** [comment]
In April 2016 4.0 was not released yet ;-)
Thanks for the reference, now I know how to fix it myself.
