### ISSUE TITLE
REST api for PowerDNS with mysql backend

### ISSUE THREAD

**Issue by theikkila** [PowerDNS/pdns#1537]
Hi!

I'd like you to know that I've been developing REST-api for PowerDNS with mysql backend.
https://github.com/theikkila/powerful-api

I'm planning for simple frontend application using that API.
It would be nice to hear some feedback from other developers.

**Comment by zeha** [comment]
I think there's nothing for us to do?

**Comment by Habbie** [comment]
Agreed. Feel free to put useful links on the wiki!
