### ISSUE TITLE
pdns_control retrieve <ROOT>

### ISSUE THREAD

**Issue by jenslink** [PowerDNS/pdns#1541]
pdns_control retrieve does not work with a root dns zone.

In PowerDNS '' is used for the root zone and '' dose not work as zone name for pdns_controll.

**Comment by Habbie** [comment]
Please retest this on master if you can!

**Comment by pieterlexis** [comment]
works on current master:

```
$ ./pdns/pdns_control --config-dir=../pdns-conf/3 retrieve .
Added retrieval request for '.' from master 192.5.5.241
```
