### ISSUE TITLE
Master queries backends for slave zones

### ISSUE THREAD

**Issue by rubenk** [PowerDNS/pdns#1570]
My master (mysql backend), queries for slave zones once every minute:
select id,name,master,last_check,type from domains where type='SLAVE'

I have slave=no set, so it shouldn't do that.

**Comment by ahupowerdns** [comment]
I have checked against git master and it no longer shows that behaviour.

56a4f068        ( Aki Tuomi     2015-08-25 06:51:01 +0300       714)  // not unless we are slave
56a4f068        ( Aki Tuomi     2015-08-25 06:51:01 +0300       715)  if (!::arg().mustDo("slave")) return;

is likely what fixed this.

**Comment by rubenk** [comment]
Ok, thanks for checking Bert!
