### ISSUE TITLE
convert from djbdns to powerdns mysql backend

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#16]
converting djbdns file to powerdns mysql backend, writed in PHP. Where I have to send first version?

**Comment by redhatjobin** [comment]
@Habbie  Could you please tell me from where i can get this ?

**Comment by Habbie** [comment]
I don't have it; in general we recommend using AXFR as the migration method!

**Comment by Habbie** [comment]
If the original author indeed sent it to pdns-users it should be in the archives, by the way.

**Comment by Bashar** [comment]
what about using tinydnsbackend to migrate from djbdns to powerdns?

**Comment by Habbie** [comment]
you should be able to use `pdnsutil b2b-migrate` (or `pdnssec` on 3.x) with that, yes.
