### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#1607]
For the following reasons, the following stuff has been suggested:

Reasons:
* test building log to syslog, where it's not useful
* systemd captures stdout + syslog

Suggestions:
* --log-stdout=on/off (better name?)
* --log-syslog=on/off

Or some combination of those (--log-dest?)

**Comment by jemshad** [comment]
Option to disable syslog logging would be great.

**Comment by eht16** [comment]
I support adding an option like --log-stdout=on/off, or better --log-stderr because pdns-recursor actually logs to stderr when not running in daemon-mode.

For now, I worked around the problem by adding `StandardError=null` to the systemd unit file and so I don't get duplicate logs any longer.

**Comment by nhooyr** [comment]
would love to see this in the next release.

**Comment by zeha** [comment]
In the meantime, Debian has changed the systemd unit file to say `Type=forking` and changed `--daemon=no` to `--daemon=yes`. This has some benefits, and I'd suggest Debian users to do the same, for now. (Benefits include startup error tracking in systemd).

**Comment by Habbie** [comment]
Decision: switch to `Type=forking` with `--daemon` in our packages now. At low priority, implement `--disable-syslog` or similar.
