### ISSUE TITLE
Error in upgrade documentation

### ISSUE THREAD

**Issue by cmol** [PowerDNS/pdns#1639]
Hi

I'm doing an upgrade to our powerdns setup, and just noticed that on the page:
http://doc.powerdns.com/html/from3.1to3.2.html
, the mysql lines for removing the index only runs if the DNSSEC version of the database is in place.

Besides that I feel that the upgrade page to 3.0, could use some information on how to upgrade to the DNSSEC db schema.
http://doc.powerdns.com/html/upgrades.html
I am not upgrading to a DNSSEC version of the code, but it just occurred to me that I couldn't really find any documentation on the DNSSEC DB prior to the 3.4 release upgrade page.

/ Claus

**Comment by Habbie** [comment]
We have entirely new upgrade SQL files now, that I believe are correct for any versions people would still be running. Closing this, if you disagree, please comment and we will reopen!
