### ISSUE TITLE
Migration Guide for folks coming from BIND

### ISSUE THREAD

**Issue by QuinnyPig** [PowerDNS/pdns#1705]
As per @ahupowerdns, this is a gentle ping to ensure that building a migration guide / quickstart for people familiar with BIND doesn't fall off of the radar.

**Comment by pieterlexis** [comment]
I think this is documented at: https://doc.powerdns.com/md/authoritative/migration/#from-zonefiles-to-powerdns

Please let us know if there is something missing.
