### ISSUE TITLE
gmysql backend lowercase txt records not noticed by check-zone

### ISSUE THREAD

**Issue by nivadis** [PowerDNS/pdns#1722]
HeyHey,

using gmysql backend with MySQL 5.6.19 and PowerDNS 3.3.1 on debian wheezy.

How to reproduce (test example):
1. pdnssec check-zone says everything is fine with 25 Records
2. a new record is inserted in pdns.records with type = 'txt' (lowercase)
3. pdnssec check-zone says everything is fine with 25 Records, again
4. testing a pdnssec rectify-zone
5. pdnssec check-zone says everything is fine with 25 Records, again
6. changing txt into TXT (uppercase) 
7. pdnssec check-zone says everything is fine with 26 Records

Same tested with SPF-Records, TLSA

**Comment by Habbie** [comment]
fixed in 8ce0dc75730
