### ISSUE TITLE
If pdns recursor chroots, reload-acls can't find the allow-from files anymore

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#1728]
To solve this, either we should commit to reading those files *after* we chroot, so that the paths are correct always, or we should try to remove the chroot part from the files (tricky).

**Comment by Habbie** [comment]
@pieterlexis didn't you do some work in this area?

**Comment by pieterlexis** [comment]
yes, we now flat-out refuse to reload when chrooted

**Comment by Habbie** [comment]
I think that warrants closing this ticket.
