### ISSUE TITLE
Fix for:  Request to queue notification for domain 'xxxx' was processed, but no valid nameservers or ALSO-NOTIFYs found message

### ISSUE THREAD

**Issue by wouterprins** [PowerDNS/pdns#1833]
Observed the following message on multiple domains after upgrading from pdns 3.3.1 to 3.4 on debian (using the static builds) using the gmysql backend without dnssec, gmysql_dnssec=no.
--
Request to queue notification for domain 'xxxx' was processed, but no valid nameservers or ALSO-NOTIFYs found. Not notifying!
--
The domains work fine on 3.3.1, debugged on irc with cmouse and the issue appears to be related to the disabled column value, the column was set to NULL instead of '0'. When the value is NULL it displays the above message, fixed all domains by setting the disabled column to the '0'.

**Comment by Habbie** [comment]
Not sure what to do about this. There is only so much we can do to compensate for not following upgrade instructions... Closing.
