### ISSUE TITLE
Wrong  "int" on statistics page

### ISSUE THREAD

**Issue by xbulat** [PowerDNS/pdns#1844]
Hello
Version server
pdns-server                          3.3-2

In queries vars used wrong variable length
"
Uptime: 21 days
Queries/second, 1, 5, 10 minute averages: 1.19e+03, 1.18e+03, 1.18e+03. Max queries/second: 2.88e+03
Cache hitrate, 1, 5, 10 minute averages: 42.8%, 42.8%, 42.8%
Backend query cache hitrate, 1, 5, 10 minute averages: 49.2%, 49.3%, 49.2%
Backend query load, 1, 5, 10 minute averages: 1.55e+03, 1.55e+03, 1.55e+03. Max queries/second: 2.93e+03
Total queries: 422792629. Question/answer latency: 0ms
"

**Comment by Habbie** [comment]
Fixed in #5116
