### ISSUE TITLE
PIPE Backend - "unable to receive data from coprocess"

### ISSUE THREAD

**Issue by muzuco** [PowerDNS/pdns#1849]
Hi, I'm trying to use a pipe backend with python and I'm wondering that "DATA" responses need a particular format.
I referred a sample perl backend from PowerDNS manual.
(http://stderr.org/doc/pdns-doc/html/backends-detail.html)

So I made the response part of scirpt like below:
stdout.write("DATA\t"+qname+"\t"+qclass+"\t"+"A\t3600\t"+id+"\t1.2.3.4\n")

But the logs are:
[PIPEBackend] unable to receive data from coprocess. Child closed pipe
Backend reported permanent error which prevented lookup (Child closed pipe), aborting
Backend error: Child closed pipe

What I have to fix for it?

**Comment by macrokernel** [comment]
Hi muzuco, 

Have you been able to resolve the issue? I have the same problem. Could you please share your solution?

Thanks
