### ISSUE TITLE
Metadata item LUA-AXFR-SCRIPT prio not handled

### ISSUE THREAD

**Issue by HofWesley** [PowerDNS/pdns#1857]
Hi

It seems that when using a LUA-AXFR-SCRIPT metadata item the value of prio (priority) is not handled at the end of axfrfilter when returning resp to PowerDNS.

We are running version 3.4.1

Is it possible to create a fix for this version ? 

Thanks in advance!

**Comment by Habbie** [comment]
fixed in 0f2f9992c08
