### ISSUE TITLE
zone2sql generating empty string for zones without $ORIGIN

### ISSUE THREAD

**Issue by masterofthebrain** [PowerDNS/pdns#1859]
If a given zonefile does not have $ORIGIN and there is no --zone-name specified zone2sql will generate SQL that has the domain name as an empty string.
I cannot really see a usecase for this and I would expect an error telling me to specify the zone name because it could not infer it automatically. While being at it -it would also be nice if --zone-name did some basic checking on what a sensible zone name might look like right now it blindly seems to accept everything.

**Comment by Habbie** [comment]
Duplicated by #2838 which has more detail, closing this one, thank you!
