### ISSUE TITLE
pdns_recursor crashes on OSX

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#1863]
Both on Yosemite (tested by me) and on Mavericks (tested by Habbie), pdns_recursor with the basic configuration crashes after a while.

Some crash traces:
- http://pastie.org/private/raweiud9jjairrecatv2cg
- http://pastie.org/9687237
- http://pastie.org/9687654

As valgrind doesn't seem to work on 10.10, I have no valgrind results, but Habbie did get a valgrind trace on 10.9

**Comment by Habbie** [comment]
Are you able to test this with current master?

**Comment by ahupowerdns** [comment]
this has been fixed a few times now
