### ISSUE TITLE
API: Exceptions not properly handled

### ISSUE THREAD

**Issue by syphernl** [PowerDNS/pdns#1871]
I am trying out the API with a call like:
```
curl -X POST --data '{"name":"example.org", "kind": "Native", "masters": [], "nameservers": ["ns1.example.org", "ns2.example.org"]}' -v -H 'X-API-Key: changeme' http://127.0.0.1:8081/servers/localhost/zones | jq .
```

On a default pdns setup this results in a response of:
```
parse error: Invalid numeric literal at line 1, column 9
```

The logs of the DNS-server show the following:
```
Nov 11 12:16:16 pdns-master pdns[13776]: Query: select id,name,master,last_check,notified_serial,type from domains where name='example.org'
Nov 11 12:16:16 pdns-master pdns[13776]: Query: insert into domains (type,name) values('NATIVE','example.org')
Nov 11 12:16:16 pdns-master pdns[13776]: HTTP ISE for "/servers/localhost/zones": Exception: Database error trying to insert new domain 'example.org': Failed to execute mysql_query, perhaps connection died? Err=1: Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
```

It should probably instead output a false / error response rather than this undescriptive message.

Strangely, if I manually insert the entry:
```
insert into domains (type,name) values('NATIVE','example.org')
```

It adds the domain just fine.

Specs: MariaDB 10.0.14 + pdns-static 3.4.1-1

**Comment by zeha** [comment]
`parse error: Invalid numeric literal at line 1, column 9` is an error message written by `jq`, not PowerDNS. pdns has a semi-correct handling here: it responds with status 500, Content-Type set to text/plain, and a text body of "Internal Server Error". This is similar to other error states (e.g. 404), where we don't even dispatch to the API code.
