### ISSUE TITLE
pdns_server fails to run as slave for root zone

### ISSUE THREAD

**Issue by cfra** [PowerDNS/pdns#1875]
I have pdns_server 3.4.1 (deb package downloaded from downloads.powerdns.com) set up to run as a slave for the root zone using the bind backend:

    zone "." {
        type slave;
        file "/etc/powerdns/zones/root.zone";
        masters {
            192.0.32.132; # xfr.lax.dns.icann.org
            2620:0:2d0:202::132;

            192.0.47.132; # xfr.cjr.dns.icann.org
            2620:0:2830:202::132;
        };
    };

However this fails with the following error in the zone transfer:
    
    Unable to feed record during incoming AXFR of '': out-of-zone data 'abogado' during AXFR of zone ''

It sounds a bit like the issue described in http://powerdns.13854.n7.nabble.com/Slaving-Opennic-zones-using-bind-backend-td8009.html

**Comment by pieterlexis** [comment]
This works in the current master
