### ISSUE TITLE
gmysql: Include best practice triggers sql file with package

### ISSUE THREAD

**Issue by syphernl** [PowerDNS/pdns#1881]
Ref #1880 

It would be nice if the pdns packages would contain an sql file with the "best practice triggers" to automatically update the `change_date` field whenever a record is added, updated or removed.

The first two I have already found which seem to be working.

Record creation:

```
CREATE TRIGGER pdns_trig_records_insert BEFORE INSERT ON records FOR EACH ROW SET NEW.change_date = UNIX_TIMESTAMP();
```

Record update:

```
CREATE TRIGGER pdns_trig_records_update BEFORE UPDATE ON records FOR EACH ROW SET NEW.change_date = UNIX_TIMESTAMP();
```

Deletions are more complex since it'll (most likely) need to update the `change_date` for the SOA record.

**Comment by dmportella** [comment]
using triggers is a really bad idea this should be managed by the code base and not mysql.

**Comment by Habbie** [comment]
> using triggers is a really bad idea this should be managed by the code base and not mysql.

This we can do for edits via `pdnsutil` and the REST API; we cannot do it for direct SQL updates.
