### ISSUE TITLE
Recursor API: Invalid "experimental-api-config-dir must be set" error

### ISSUE THREAD

**Issue by syphernl** [PowerDNS/pdns#1883]
I am trying the "experimental" API for the recursor, but while creating a zone it returns an error stating:
```
Config Option "experimental-api-config-dir" must be set
```

This option *is* set to a directory, which exists and is accessible for the pdns user:
```
root@dns:/etc/powerdns# grep experimental-api-config-dir recursor.conf 
# experimental-api-config-dir	Directory where REST API stores config and zones
experimental-api-config-dir=/etc/powerdns/zones
```

When running `pdns_recursor` with the `--experimental-api-config-dir=/etc/powerdns/zones` flag it is working, then complains about the `recursion_desired` setting. It appears that it may not be reading the config (properly)?

I'm running your prebuilt package `pdns-recursor 3.6.2-1` on Ubuntu 14.04.

**Comment by zeha** [comment]
I guess we need more info than that; e.g. your full command line and config file. Removing 'web' tag for now.

**Comment by Habbie** [comment]
Not enough information, closing.
