### ISSUE TITLE
Please dump cache over socket

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#1885]
Given new security features in init systems (e.g. systemd's `PrivateTmp`, and others), having a daemon write to an admin-controlled path is likely to get harder / impossible.

Please add support for `rec_control dump-cache` to send the cache over the control socket, instead of directly writing the contents to a file.

(If `pdns_control` has a similar thing, same concern...)

**Comment by omoerbeek** [comment]
Different solution in #9468, same result.
