### ISSUE TITLE
pdns control socket should be made after chroot

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#191]
pdns process creates a control socket. In chroot mode, the creation is done before chrooting, thus causing pdns to lose access to it. To fix this, one should make pdns create socket after chrooting. 

Aki Tuomi

**Comment by pieterlexis** [comment]
related #268 (this issue affects both the auth and the rec)

The order then should be:
- chroot()
- drop privileges
- (possibly) create subdirectories (as `socket-dir` now resides **inside** the chroot)
- Create PID and socket

Other stuff:
- update pidfile magic in initscript
- Update docs to reflect this change

We might want to target this for 4.0, as it is a possibly breaking change

**Comment by pieterlexis** [comment]
A working patch for the recursor is available at https://github.com/pieterlexis/pdns/tree/issue-191-RecursorControlSocketAfterChroot
