### ISSUE TITLE
OS X remote http was not working

### ISSUE THREAD

**Issue by gotlium** [PowerDNS/pdns#1922]
Hi, remote backend was not working with http on OS X 10.9.5 (on Linux all is fine)
When I make pdns, I got this lines:

    # installation file: https://downloads.powerdns.com/releases/pdns-3.4.1.tar.bz2 
    $ ./configure --prefix=/usr/local/Cellar/pdns/3.4.1 --with-modules=remote 
    $ make && make install

    Making all in yahttp
    Making all in yahttp
    make[6]: Nothing to be done for `all'.
    make[6]: Nothing to be done for `all-am'.
    Making all in rapidjson
    make[5]: Nothing to be done for `all'.
    make[5]: Nothing to be done for `all-am'.

possible that a problem with YaHTTP?

When I run pdns and make some request, I see "Exception caught when receiving" without any details:

    $ run-pdns 

    Dec 09 05:05:07 Reading random entropy from '/dev/urandom'
    Dec 09 05:05:07 This is a standalone pdns
    Dec 09 05:05:07 Listening on controlsocket in '/tmp/pdns.controlsocket'
    Dec 09 05:05:07 UDP server bound to 127.0.0.1:53
    Dec 09 05:05:07 TCP server bound to 127.0.0.1:53
    Dec 09 05:05:07 PowerDNS Authoritative Server 3.4.1 (jenkins@autotest.powerdns.com) (C) 2001-2014 PowerDNS.COM BV
    Dec 09 05:05:07 Using 64-bits mode. Built on 20141209050155 by gotlium@mb-gotlium.local, clang 6.0 (clang-600.0.56).
    Dec 09 05:05:07 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
    Dec 09 05:05:07 Polled security status of version 3.4.1 at startup, no known issues reported: OK
    Dec 09 05:05:07 Listening for HTTP requests on 127.0.0.1:8081
    Dec 09 05:05:07 Creating backend connection for TCP
    Dec 09 05:05:07 Master/slave communicator launching
    Dec 09 05:05:07 About to create 3 backend threads for UDP
    Dec 09 05:05:07 No new unfresh slave domains, 0 queued for AXFR already
    Dec 09 05:05:07 No master domains need notifications
    Dec 09 05:05:07 Done launching threads, ready to distribute questions
    Dec 09 05:06:05 Remote 127.0.0.1 wants 'example.com|A', do = 0, bufsize = 512: packetcache MISS
    Dec 09 05:06:05 Exception caught when receiving
    Dec 09 05:06:05 Exception caught when receiving
    Dec 09 05:06:05 Exception caught when receiving

PowerDNS Configuration:

    log-dns-details=yes
    log-dns-queries=yes
    query-logging=yes
    loglevel=9
 
    webserver=yes
    webserver-port=8081
    
    local-address=127.0.0.1
    local-port=53

    launch=remote
    remote-connection-string=http:url=https://localhost:8080/dns

My config was working on Linux without problems. 
That a full installation log on OS X 10.9.5 https://gist.github.com/gotlium/1a43bfe3f50468106c1e

**Comment by Habbie** [comment]
@cmouse any thoughts?

**Comment by cmouse** [comment]
tcpdump pcap could help

**Comment by Habbie** [comment]
remotebackend http tests pass on my 10.10 mac today. Closing ticket.
