### ISSUE TITLE
On FreeBSD 9, our -pie compilation for PowerDNS recursor fails and we don't detect that in ./configure

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2037]
g++ -fno-strict-aliasing -Iext/rapidjson/include -I/usr/home/ahu/pdns/pdns/pdns-recursor-git-f635ed7+/ext/polarssl/include -Wall -fPIE -fPIC -DPIE -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -I/usr/local/include/ -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o version.o version.cc
g++ syncres.o misc.o unix_utility.o qtype.o logger.o arguments.o lwres.o pdns_recursor.o recursor_cache.o dnsparser.o dnswriter.o dnsrecords.o rcpgenerator.o base64.o zoneparser-tng.o rec_channel.o rec_channel_rec.o selectmplexer.o sillyrecords.o dns_random.o pubsuffix.o ext/polarssl/library/aes.o dnslabeltext.o lua-pdns.o lua-recursor.o randomhelper.o recpacketcache.o dns.o reczones.o base32.o nsecrecords.o json.o ws-recursor.o ws-api.o version.o responsestats.o webserver.o ext/yahttp/yahttp/reqresp.o ext/yahttp/yahttp/router.o rec-carbon.o secpoll-recursor.o optional/kqueuemplexer.o   -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie    -o pdns_recursor
/usr/bin/ld: syncres.o: relocation R_X86_64_TPOFF32 against `t_sstorage' can not be used when making a shared object; recompile with -fPIC
syncres.o: could not read symbols: Bad value
Makefile:135: recipe for target 'pdns_recursor' failed

FreeBSD f9amd64

**Comment by cmouse** [comment]
This looks again, that configure has been called without STATIC=semi or STATIC=all.

**Comment by paddg** [comment]
Yes, this is true. I did it this way:

    ./configure
    make OPTFLAGS="-O3" LUA=1 STATIC=semi LUA_CPPFLAGS_CONFIG="-I/usr/include/" LUA_LIBS_CONFIG="-llua -rdynamic"

If I run configure with

    STATIC=semi ./configure

`make` works fine.

Is it somewhere documented how to build the Recursor?
