### ISSUE TITLE
On SuSE linux with gcc 4.3, recursor compilation with PIE also fails

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2055]
Related to #2037 - it appears we our ./configure detection script detects working PIE when it don't.

g++  -Iext/rapidjson/include
-I/root/tmp/pdns-recursor-git-auth-3.4.0-695-gd64ce86/ext/polarssl/include
-Wall -fPIE -fPIC -DPIE -D_FORTIFY_SOURCE=2 -fstack-protector --param
ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -D_GNU_SOURCE
-DHAVE_STRCASESTR -I/usr/include/ -DPDNS_ENABLE_LUA -DHAVE_LUA
-DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o
version.o version.cc
gcc syncres.o misc.o unix_utility.o qtype.o logger.o arguments.o lwres.o
pdns_recursor.o recursor_cache.o dnsparser.o dnswriter.o dnsrecords.o   
rcpgenerator.o base64.o zoneparser-tng.o rec_channel.o rec_channel_rec.o
selectmplexer.o sillyrecords.o dns_random.o pubsuffix.o
ext/polarssl/library/aes.o dnslabeltext.o lua-pdns.o lua-recursor.o
randomhelper.o recpacketcache.o dns.o reczones.o base32.o nsecrecords.o
json.o ws-recursor.o ws-api.o version.o responsestats.o webserver.o
ext/yahttp/yahttp/reqresp.o ext/yahttp/yahttp/router.o rec-carbon.o
secpoll-recursor.o lua-iputils.o optional/epollmplexer.o   -pthread
-Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -lm  -Wl,-Bstatic -lstdc++ -llua
-rdynamic -lgcc -Wl,-Bdynamic -static-libgcc -lm -lc -ldl -o pdns_recursor
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld:
/usr/lib64/gcc/x86_64-suse-linux/4.3/libstdc++.a(ctype.o): relocation
R_X86_64_32S against `vtable for std::ctype<wchar_t>' can not be used
when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.3/libstdc++.a: could not read
symbols: Bad value

**Comment by darix** [comment]
only static builds are affected. shared library builds should work just fine.

**Comment by cmouse** [comment]
Didn't we already disable pie for static/semistatic for recursor. I clearly remember we did.

**Comment by cmouse** [comment]
https://github.com/PowerDNS/pdns/blob/master/pdns/configure-recursor#L48

**Comment by Habbie** [comment]
probably fixed by c10dd99
