### ISSUE TITLE
Documentation: per domain metadata needs better docs & examples

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2057]
https://doc.powerdns.com/md/authoritative/domainmetadata/ - what does 'PRESIGNED' need as a value? Do the NOTIFY things include port numbers or not?

**Comment by jpmens** [comment]
Does PRESIGNED even have to exist? i.e. if presigned zone is AXFRd into PowerDNS and PRESIGNED is *not* set, what happens?

**Comment by jpmens** [comment]
From IRC chat:

* it sets it
* is it is NOT axfred in but you use zone2sql or pdnssec load-zone
* also, even if axfr-ed in, powerdns needs to store the presigned bit somewhere
* What if it's AXFR and there is signing stuff but it's incomplete or bogus? => your problem
