### ISSUE TITLE
Documentation: inconsistent formatting of backend- options

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2059]
in backend-generic-mypgsql/

**Comment by tfarina** [comment]
@jpmens Which formatting options are inconsistent in
https://github.com/PowerDNS/pdns/blob/51df5deafbf97cee89c7ac2c50fbb9246d89cf57/docs/markdown/authoritative/backend-generic-postgresql.md?

Assuming that is the doc you are referring to by backend-generic-mypgsql.

**Comment by jpmens** [comment]
Asking me this after over a year ... ?!
How on earth should I recall? I gave it a glance but can't see anything untowards.
