### ISSUE TITLE
Security status update fails

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2060]
```Jan 09 00:59:57 Could not retrieve security status update for 'git-20150108-5369-943b2f7' on 'auth-git-20150108-5369-943b2f7.security-status.secpoll.powerdns.com.', RCODE = Non-Existent domain```

**Comment by Habbie** [comment]
This is basically intentional - we are not going to build a database of the security status of every git commit. However, I agree this is could be less confusing/scary.

**Comment by jpmens** [comment]
Disable for git versions? 

```
if (!strncmp(version, "auth-git-", ...))
```

**Comment by zeha** [comment]
Out of tree builds give a version of "UNKNOWN", please also take this into account.

**Comment by jpmens** [comment]
Is this completely mixed up now or am I misinterpreting the meaning of `rec` in this message issued by pdns AUTH?

```
Could not retrieve security status update for 'git-rec-3.7.0-294-g15f841f+' on 'auth-git-rec-3.7.0-294-g15f841f_.security-status.secpoll.powerdns.com.', RCODE = Non-Existent domain
```

**Comment by Habbie** [comment]
This decodes as 'on the branch you are on, the most recent tag is rec-3.7.0 and you are 294 commits beyond that tag'. This is confusing because .0 releases of both auth and rec come from the same master branch.

**Comment by jpmens** [comment]
I think this _phoning home_ should be opt-in by default; in other words, change the behavior to not do the security query unless explicitly configured to do so.

**Comment by zeha** [comment]
Except then nobody enables it and one could just delete the code altogether.

**Comment by jpmens** [comment]
Fine with me. ;-)

<pedantic mode="on">
Even if it's there, how many system administrators are actually going to monitor their logs for that? Considering there are still (many?) 2.x "customers" out there, that indicates, to me at least, that they don't even monitor mailing lists, etc.

**Comment by Habbie** [comment]
The secpoll code now explicitly handles git releases separately. Closing!
