### ISSUE TITLE
autoserial and dnsupdate don't work together

### ISSUE THREAD

**Issue by mtremer** [PowerDNS/pdns#2066]
Hello guys,

thanks for adding support for RFC 2136.

I think I found a minor issue with using that in conjunction with autoserial. Every time some record is added and/or changed by using the nsupdate command, the SOA record is updated and the serial is changed. You can select multiple ways in which that is done, but none of that seems to honour the autoserial setting (the serial is just 0 and if that is required, it will be computed by using the largest "change_date" value of any record of that zone).

In order to support autoserial I suppose that only two very simple things need to be done:
1) If the serial is 0, don't change it.
2) change_date of the new or changed record must be set accordingly. Currently it is NULL.

That should be it. Is there any reason why this is not supported right now?

**Comment by Habbie** [comment]
Hello! Thank you for trying 2136, it can use some testing :)

autoserial is not used a lot; I don't think we even considered it during 2136 development. In any case, the general way to make autoserial work is to install a trigger that actually populates the column (either on the updated record, or on the SOA); such a trigger would also work with 2136, covering request number 2)

Please let us know if that part works for you; then we can discuss part 1) which for now appears to make sense :)

**Comment by Habbie** [comment]
Pinging @cyclops1982.

**Comment by mtremer** [comment]
Hey Peter,

thanks for looking into this.

Do you think that using a trigger in the database is the best solution? It will certainly work, but it is nowhere else used in PowerDNS. Usually PowerDNS itself takes care of updating all required fields (e.g. the ordername). Are there any difficulties why you want to move this out of PowerDNS and into the database?

I find the autoserial feature very useful when managing many zones with lots of updates (i.e. dynamic DNS) and I wouldn't really want to lose it for RFC 2136.

**Comment by Habbie** [comment]
The reason this lives in the database is that autoserial was designed to adhere to local policy; I should point out that you can change the 'max(change_date)' query from pdns.conf, and I believe some autoserial users do this.

I understand your usecase; can I ask what's updating change_date for you right now (for your non-2136 updates)?

**Comment by mtremer** [comment]
Sure you can :)

I am using a web application that does that for me. It receives updates from client programs that update dynamic DNS records and has got a GUI that people can use to manage their zones. Every time a record is changed the change_date field will be updated as well in that statement.

The query simply looks like: UPDATE records SET content = "...", change_date = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) WHERE id = X

That is all I need to do in my application as the autoserial feature takes care of updating the SOA record.

Changing the update statement is what I could do of course. It is just that I kind of expected PowerDNS to do this automatically and hence opened this bug. Autoserial is all about automation, isn't it?

**Comment by Habbie** [comment]
Thanks for explaining. A tip: think about what happens if you lose a user and remove his entry; your SOA might go down!

I don't have an immediate definitive idea for fixing autoserial+2136. One random thought is to have a 'DO-NOT-TOUCH' SOA-EDIT value, in which case the admin is expected to manage autoserial - or as you say, make '0' simply mean that.

I'll leave this ticket open to invite thoughts from others, and I'm sure we'll get somewhere good.

**Comment by mtremer** [comment]
```
[root@rice-oxley pdns]# git diff
diff --git a/pdns/rfc2136handler.cc b/pdns/rfc2136handler.cc
index a90a7ed15b03..4e6b0b80b550 100644
--- a/pdns/rfc2136handler.cc
+++ b/pdns/rfc2136handler.cc
@@ -948,6 +948,11 @@ void PacketHandler::increaseSerial(const string &msgPrefix, const DomainInfo *di
   fillSOAData(rec.content, soa2Update);
   int oldSerial = soa2Update.serial;
 
+  // No change of the serial required if the zone is using
+  // the autoserial feature (#2066)
+  if (oldSerial == 0)
+    return;
+
   vector<string> soaEdit2136Setting;
   B.getDomainMetadata(di->zone, "SOA-EDIT-DNSUPDATE", soaEdit2136Setting);
   string soaEdit2136 = "DEFAULT";
```

I think that PowerDNS simply should leave the serial untouched if it is zero. I have not tested the code above, but I guess it should look like the patch above.

**Comment by Habbie** [comment]
Please try it, if you dare :)

**Comment by mtremer** [comment]
Tested. Works for me.

**Comment by Habbie** [comment]
Awesome! How about a PR?

**Comment by mtremer** [comment]
Can do. We should just resolve the other part first...

**Comment by Habbie** [comment]
Related: #1881

**Comment by mtremer** [comment]
If we add this to the default database layout I am perfectly fine with using triggers. I just wanted to avoid creating a use case that is hard to maintain for me. If more people us that, I have no objection to this at all.

As I am using PostgreSQL I created these:

```
CREATE FUNCTION pdns_autoserial_update_change_date() RETURNS trigger
    LANGUAGE plpgsql STRICT
    AS $$BEGIN
  SELECT 1 FROM domains WHERE id = NEW.domain_id AND type = 'NATIVE' OR type = 'MASTER';
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  NEW.change_date = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::integer;
  RETURN NEW;
END;$$;

CREATE FUNCTION pdns_autoserial_update_soa() RETURNS trigger
    LANGUAGE plpgsql STRICT
    AS $$BEGIN
  IF OLD.change_date IS NULL OR OLD.type = 'SOA' THEN
    RETURN OLD;
  END IF;

  SELECT 1 FROM domains WHERE id = OLD.domain_id AND type = 'NATIVE' OR type = 'MASTER';
  IF NOT FOUND THEN
    RETURN OLD;
  END IF;

  UPDATE records SET change_date = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) WHERE domain_id = OLD.domain_id AND type = 'SOA';
  RETURN OLD;
END;$$;

CREATE TRIGGER pdns_autoserial_update_change_date_trigger BEFORE INSERT OR UPDATE ON records FOR EACH ROW EXECUTE PROCEDURE pdns_autoserial_update_change_date();
CREATE TRIGGER pdns_autoserial_update_soa_trigger AFTER DELETE ON records FOR EACH ROW EXECUTE PROCEDURE pdns_autoserial_update_soa();
```

How do you feel about this?

**Comment by mtremer** [comment]
There you go. I refined the SQL functions a bit and made them easier to read.

I only added the triggers for PostgreSQL. I am sure there is someone around who is familiar with the other supported databases to add those triggers as well so that we can add them to the default database layout.
