### ISSUE TITLE
pdns_control manpage error

### ISSUE THREAD

**Issue by bitkat** [PowerDNS/pdns#2085]
Installed pdns 3.4.1. (from package) on FreeBSD 10.1-RELEASE

The manpage for pdns_control documents a *status* command which does not seem to work.
However, on that same page, an otherwise undocumented *list* command is mentioned in passing (under *show*), which does in fact work.

Please document *list* and remove *status* from the manpage.

**Comment by bitkat** [comment]
Also, the documented *cycle* doesn't work; the undocumented *reload* does... 
Is the correct man page installed with the port?

**Comment by Habbie** [comment]
`cycle` requires guardian mode; the manpage has been updated to note that (after 3.4.1)

**Comment by Habbie** [comment]
* [ ] document `reload`
* [ ] document that `status` requires guardian mode
* [ ] document `list`

**Comment by pieterlexis** [comment]
interestingly, `list` isn't even shown when you run `pdns_control help`

**Comment by Habbie** [comment]
Apparently the aliasing of `list` to `show *` is in pdns_control, not in pdns_server (!)

**Comment by ahupowerdns** [comment]
the raisins, they are hysterical!
