### ISSUE TITLE
multiple carbon-servers

### ISSUE THREAD

**Issue by zozo6015** [PowerDNS/pdns#2093]
Can we have the ability to have powerdns send data to multiple carbon-servers?

**Comment by cmouse** [comment]
This could be solved with a script, too.

**Comment by Habbie** [comment]
@cmouse do you happen to have such a script, or know of one?

**Comment by cmouse** [comment]
Yes. I happen to have such script, https://github.com/cmouse/pdns-carbon-proxy

**Comment by Habbie** [comment]
That's to HTTP :)

**Comment by cmouse** [comment]
Oh right, well, no I don't have one *now*, but it's not very hard to make one.
