### ISSUE TITLE
Reconsider RSA defaults

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2095]
`pdnssec secure-zone` currently defaults to algo 8 with a 2048 bit KSK and a 1024 bit ZSK. The way PowerDNS currently works and is deployed by most people, the KSK/ZSK split makes no sense, other than slightly reducing load on validators (which does not strike me as an important argument).

Suggestions:
1. drop the 1024 bit ZSK (thus increasing overall security and reducing DNSKEY RRset size)
2. increase the ZSK to 2048 (similarly increasing security; increasing DNSKEY RRset size; less (or posisbly just different) confusion about the lack of key split)

**Comment by X-Cli** [comment]
I completely subscribe to your security analysis: current deployments do not benefit from KSK/ZSK splitting. I also confirm that several information security gov agencies publicly document that RSA 1024 should not be used.
Therefore, I, hat-off, would recommend to use a RSA 2048 CSK by default.

**Comment by Habbie** [comment]
Follow up question for anybody reading this - CSK with or without SEP set?

**Comment by jpmens** [comment]
CSK as 257; I think that would make things clearer for people who've read that SEP bit is the trust anchor for the zone. (Though I know it's not required, e.g. `dig co.uk dnskey` :-)

**Comment by Habbie** [comment]
Yes, 257 is clearer but it's good to know validators won't choke on it, given that `co.uk` runs with 256 :)

**Comment by Habbie** [comment]
@ahupowerdns has just made the executive decision to go ECDSA, which to me means that most split-key arguments are falling away as well.

**Comment by jpmens** [comment]
Executive Decision? You asked for _votes_! ;-)

**Comment by Habbie** [comment]
Pondering 13 vs. 14. Key flags probably 256. Should fix #3068 to go with this.

**Comment by Habbie** [comment]
13 (ecdsa256), key flags 256, one key. Now on master.
