### ISSUE TITLE
DKIM, SPF both need a wild card 

### ISSUE THREAD

**Issue by nickytcom** [PowerDNS/pdns#2100]
This post was updated on Jan 19, 2015; 11:28am.
I am looking for a solution so that I may use PDNS while publishing DKIM and SPF's TXT Type with a wild card asterisk symbol, *

Since PDNS databases the domain zones, how is it possible to use the asterisk symbol for DKIM and SPF if the database won't accept a duplicate name (selector)?

Thank you for your help
Thanks, Nick

**Comment by cmouse** [comment]
Can you please elaborate like, say, with an example what does not work?

**Comment by nickytcom** [comment]
I'm trying to set up SPF and DKIM so that they both can 'pass ok' with any sub-domain.  I need to put an asterisks symbol for the name of both these TXT entries.  However I can only insert one TXT file with the name *  

So how can I make both DKIM and SPF use the same name, or selector to accommodate random sub-domains.   

Thanks for the quick reply

**Comment by cmouse** [comment]
Er, this sounds more like an issue with your schema. Which backend are you using? Can you provide details of the error message(s) you receive? Which version of PowerDNS?

**Comment by nickytcom** [comment]
Sent you an email with a screen shot

**Comment by cmouse** [comment]
This looks like this is error in poweradmin, not powerdns. There is no restriction that I know of that prevents this

**Comment by nickytcom** [comment]
If you’re suggestion is to maybe change my schema, that’s okay.  I would put an @ symbol for the SPF? and stop using sub-domains?

**Comment by cmouse** [comment]
MySQL backend does not use @ symbol to mean "domain".

**Comment by nickytcom** [comment]
Ah I see the poweradmin in the DNS Console.  I checked all boxes and restart pdns service.  When I try to add SPF named * it removes the TXT entry that was there before.

**Comment by cmouse** [comment]
This is likely a PowerAdmin bug. Can you try adding it directly to the MySQL database?

**Comment by nickytcom** [comment]
Give me a bit of time and I will reply with answer.

**Comment by cmouse** [comment]
I tested this myself. 
```
mysql> select * from records where type = 'SPF';
+----+-----------+-------------+------+--------------+------+------+-------------+-----------+------+----------+
| id | domain_id | name        | type | content      | ttl  | prio | change_date | ordername | auth | disabled |
+----+-----------+-------------+------+--------------+------+------+-------------+-----------+------+----------+
| 94 |         5 | *.cmouse.fi | SPF  | "test-spf-a" |  300 | NULL |        NULL | NULL      | NULL |        0 |
| 95 |         5 | *.cmouse.fi | SPF  | "test-spf-b" |  300 | NULL |        NULL | NULL      | NULL |        0 |
+----+-----------+-------------+------+--------------+------+------+-------------+-----------+------+----------+
2 rows in set (0.00 sec)
```

and

```
~$ dig spf foobar.cmouse.fi @localhost -p5300
;; ANSWER SECTION:
foobar.cmouse.fi.       300     IN      SPF     "test-spf-b"
foobar.cmouse.fi.       300     IN      SPF     "test-spf-a"
```

**Comment by nickytcom** [comment]
Okay thank you I will look at how I'm inserting the TXT Type entries.

**Comment by Habbie** [comment]
Closing this as it does not appear to be a PowerDNS issue. Please let us know if you have trouble.
