### ISSUE TITLE
Feature request: RRL support

### ISSUE THREAD

**Issue by pavel-odintsov** [PowerDNS/pdns#2103]
Hello, folks!

Do you have any plans for RRL feature? Amplification attacks is a pain of the Internet for 2 years but there are not ways to mitigate amplifications over PowerDNS because it lacks RRL support.

Feature any-to-tcp is part of solution but amplification can be achieved with multiple long MX records like used by Gmail:
```
host -t mx google.com
google.com mail is handled by 30 alt2.aspmx.l.google.com.
google.com mail is handled by 40 alt3.aspmx.l.google.com.
google.com mail is handled by 50 alt4.aspmx.l.google.com.
google.com mail is handled by 10 aspmx.l.google.com.
google.com mail is handled by 20 alt1.aspmx.l.google.com.
```

Or TXT records with DKIM/SPF information:
```
 host -t txt yandex.ru
yandex.ru descriptive text "v=spf1 redirect=_spf.yandex.ru"
yandex.ru descriptive text "6755629c673e589fb935b0aecd77bd4e"
yandex.ru descriptive text "mailru-verification: 530c425b1458283e"
```

Very exciting support of RRL I found in NSD server. It works perfectly and configured very simply.

Thank you for attention!

**Comment by Habbie** [comment]
Hello Pavel,

please see http://tinyurl.com/pdnsripe69 and #1471 !

**Comment by pavel-odintsov** [comment]
Awesome!  I have no other words!

But I have some consideration about performance of LUA for calculating avg rps.

Do you plans to integrate this engine in PowerDNS recursor and PowerDNS auth both?

**Comment by Habbie** [comment]
The PR text mentions it would be nice to -at least- provide a wrapper to make auth RRL scripts easy to use in the Recursor; I'm not sure where that will end exactly.

Lua is very fast; but we will be sure to do benchmarks when we have efficient scripts, and if necessary, we will offload some of the magic to C++.

**Comment by pavel-odintsov** [comment]
Nice to hear this! We are waiting this feature!

**Comment by Habbie** [comment]
Testing and inspiration are welcome - you can build the branch right now if you like :)

**Comment by Habbie** [comment]
Closing this as #1471 covers it all. Please add any comments there if you feel they are missing.
