### ISSUE TITLE
SOA-EDIT has no simple increment (++)

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2115]
The description of SOA-EDIT has no "just increment this by one, please" setting, [as far as I can see](https://doc.powerdns.com/md/authoritative/domainmetadata/). 

I think this would be good to have. (Even though I know most/many people like the YYYYMMDDnn thing.)

**Comment by Habbie** [comment]
(Context: the same modes are used for SOA-EDIT-API, and there +1 would make sense as there's actual state) (Also need to put SOA-EDIT-API on the linked page)

**Comment by jpmens** [comment]
The expression "*serial number from the backend*" in following text from the linked page makes no sense to me in the context of `SOA-EDIT-API` as it *is modifying* the serial number:

> INCEPTION-INCREMENT (available since 3.3): Uses YYYYMMDDSS format for SOA serial numbers. If the SOA serial from the backend is within two days after inception, it gets incremented by two (the backend should keep SS below 98). Otherwise it uses the maximum of the backend SOA serial number and inception time in YYYYMMDD01 format. This requires your backend zone to use YYYYMMDDSS as SOA serial format. Uses localtime to find the day for inception time

**Comment by zeha** [comment]
When #2286 gets merged, I think this is basically obsolete -- SOA-EDIT itself should not get an INCREASE thing.
