### ISSUE TITLE
cross compile on openwrt

### ISSUE THREAD

**Issue by debiansid** [PowerDNS/pdns#2119]
how can I compile ipk of pdns for my openwrt router? thanks!
root@debiansid:~/build/pdns-3.4.1# ./configure --build=x86_64-unkown-linux --without-lua –host=mips-openwrt-linux-uclibc
configure: error: invalid variable name: `–host'

**Comment by Habbie** [comment]
Instead of `--host`, you typed a unicode dash ('U+2013 EN DASH'), causing this error. Closing ticket.

**Comment by Habbie** [comment]
Do let us know if you run into any additional issues for your cross compile!

**Comment by debiansid** [comment]
make CC=mips-openwrt-linux-gcc LD=mips-openwrt-linux-ld CXX=mips-openwrt-linux-g++ AR=mips-openwrt-linux-ar RANLIB=mips-openwrt-linux-ranlib 

End up with mtasker.cc: In member function 'bool MTasker<EventKey, EventVal>::schedule(timeval*)':                   mtasker.cc:335:37: error: there are no arguments to 'swapcontext' that depend on a template parameter, so a declaration of 'swapcontext' must be available [-fpermissive]               if(swapcontext(&d_kernel, uc)) { // swaps back to the above point 'A'                                                                ^                                make: *** [syncres.o] Error 1

**Comment by Habbie** [comment]
Can you
* pass those variables to configure instead of make, please
* show more context around the mtasker error? You shouldn't need mtasker.cc unless you passed `--enable-tools`

**Comment by debiansid** [comment]
CC=mips-openwrt-linux-gcc CXX=mips-openwrt-linux-g++ AR=mips-openwrt-linux-ar RANLIB=mips-openwrt-linux-ranlib CXXFLAGS=-I../boost_1_57_0/ ./configure --prefix=/home/admin/build/pdns-openwrt --host=mips-openwrt-linux --disable-tools  


 make  CC=mips-openwrt-linux-gcc CXX=mips-openwrt-linux-g++ RANLIB=mips-openwrt-linux-ranlib  

I have to pass those variables in configure and make or it will use Linux's g++.

Btw I am trying to cross compile recursor for openers.

**Comment by debiansid** [comment]
make CC=mips-openwrt-linux-gcc CXX=mips-openwrt-linux-g++ AR=mips-openwrt-linux-ar RANLIB=mips-openwrt-linux-ranlib

PLEASE READ: If you get an error mentioning #include <boost/something.hpp>, please read README
PLEASE READ: for an easy fix!

echo '#ifndef VERSION_GENERATED_H' > version_generated.h
echo '#define VERSION_GENERATED_H' >> version_generated.h
echo '#include "config.h"' >> version_generated.h
echo '#define PDNS_VERSION VERSION' >> version_generated.h
echo '#define BUILD_DATE "20150127040609"' >> version_generated.h
echo '#define BUILD_HOST "admin@debiansid.localdomain"' >> version_generated.h
echo '#endif //!VERSION_GENERATED_H' >> version_generated.h
mips-openwrt-linux-g++  -I../boost_1_57_0/ -Iext/rapidjson/include -I/home/admin/build/pdns-recursor-3.6.2/ext/polarssl-1.3.2/include -Wall -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' -c epollmplexer.cc -o optional/epollmplexer.o ; true
In file included from mtasker.hh:113:0,
                 from syncres.hh:21,
                 from epollmplexer.cc:7:
mtasker.cc: In member function 'int MTasker<EventKey, EventVal>::sendEvent(const EventKey&, const EventVal*)':
mtasker.cc:245:37: error: there are no arguments to 'swapcontext' that depend on a template parameter, so a declaration of 'swapcontext' must be available [-fpermissive]
   if(swapcontext(&d_kernel,userspace)) { // swaps back to the above point 'A'
                                     ^
mtasker.cc:245:37: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
mtasker.cc: In member function 'void MTasker<EventKey, EventVal>::makeThread(void (*)(void*), void*)':
mtasker.cc:272:16: error: there are no arguments to 'getcontext' that depend on a template parameter, so a declaration of 'getcontext' must be available [-fpermissive]
   getcontext(uc);
                ^
mtasker.cc:281:133: error: there are no arguments to 'makecontext' that depend on a template parameter, so a declaration of 'makecontext' must be available [-fpermissive]
   makecontext (uc, (void (*)(void))threadWrapper, 6, thispair.first, thispair.second, start, d_maxtid, valpair.first, valpair.second);
                                                                                                                                     ^
mtasker.cc: In member function 'bool MTasker<EventKey, EventVal>::schedule(timeval*)':
mtasker.cc:335:37: error: there are no arguments to 'swapcontext' that depend on a template parameter, so a declaration of 'swapcontext' must be available [-fpermissive]
         if(swapcontext(&d_kernel, uc)) { // swaps back to the above point 'A'
                                     ^
mips-openwrt-linux-g++  -I../boost_1_57_0/ -Iext/rapidjson/include -I/home/admin/build/pdns-recursor-3.6.2/ext/polarssl-1.3.2/include -Wall -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o syncres.o syncres.cc
In file included from mtasker.hh:113:0,
                 from syncres.hh:21,
                 from syncres.cc:26:
mtasker.cc: In member function 'int MTasker<EventKey, EventVal>::sendEvent(const EventKey&, const EventVal*)':
mtasker.cc:245:37: error: there are no arguments to 'swapcontext' that depend on a template parameter, so a declaration of 'swapcontext' must be available [-fpermissive]
   if(swapcontext(&d_kernel,userspace)) { // swaps back to the above point 'A'
                                     ^
mtasker.cc:245:37: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
mtasker.cc: In member function 'void MTasker<EventKey, EventVal>::makeThread(void (*)(void*), void*)':
mtasker.cc:272:16: error: there are no arguments to 'getcontext' that depend on a template parameter, so a declaration of 'getcontext' must be available [-fpermissive]
   getcontext(uc);
                ^
mtasker.cc:281:133: error: there are no arguments to 'makecontext' that depend on a template parameter, so a declaration of 'makecontext' must be available [-fpermissive]
   makecontext (uc, (void (*)(void))threadWrapper, 6, thispair.first, thispair.second, start, d_maxtid, valpair.first, valpair.second);
                                                                                                                                     ^
mtasker.cc: In member function 'bool MTasker<EventKey, EventVal>::schedule(timeval*)':
mtasker.cc:335:37: error: there are no arguments to 'swapcontext' that depend on a template parameter, so a declaration of 'swapcontext' must be available [-fpermissive]
         if(swapcontext(&d_kernel, uc)) { // swaps back to the above point 'A'
                                     ^
make: *** [syncres.o] Error 1

**Comment by Habbie** [comment]
Are you building recursor from an auth tarball? Please clarify exactly what you are doing. I also recall that `swapcontext` needs recent libs/headers to work on ARM.

**Comment by debiansid** [comment]
I am trying to cross compile the recursor from here /home/admin/build/pdns-recursor-3.6.2; for my mips openwrt router

**Comment by Habbie** [comment]
Please show us your build environment, including version numbers of your whole cross compiling chain, libraries, headers, etc.

**Comment by debiansid** [comment]
admin@debiansid:~/openwrt/staging_dir$ ls -arlt
total 20
drwxrwxr-x  5 admin admin 4096 Jan 22 09:20 .
drwxr-xr-x 13 admin admin 4096 Jan 22 10:20 host
drwxrwxr-x 18 admin admin 4096 Jan 26 05:41 ..
drwxr-xr-x 12 admin admin 4096 Jan 26 05:41 toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2
drwxrwxr-x 11 admin admin 4096 Jan 26 05:41 target-mips_34kc_uClibc-0.9.33.2

**Comment by debiansid** [comment]
admin@debiansid:~$ cd build/pdns-recursor-3.6.2/
admin@debiansid:~/build/pdns-recursor-3.6.2$ CC=mips-openwrt-linux-gcc CXX=mips-XXFLAGS=-I../boost_1_57_0/ ./configure --prefix=/home/admin/build/pdns-openwrt -
Testing dependencies and compiler.
mips-openwrt-linux-g++ -I../boost_1_57_0/ -I../boost_1_57_0/ -Iext/rapidjson/inc -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc
mips-openwrt-linux-g++ -I../boost_1_57_0/ -I../boost_1_57_0/ -Iext/rapidjson/include -I/home/admin/build/pdns-recursor-3.6.2/ext/polarssl-1.3.2/include -Wall -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'  pdns_hw.cc -o pdns_hw

/bin/sh: line 1: ./pdns_hw: cannot execute binary file: Exec format error
Could compile binary, but not run it, read README please
admin@debiansid:~/build/pdns-recursor-3.6.2$ file pdns_hw
pdns_hw: ELF 32-bit MSB  executable, MIPS, MIPS32 rel2 version 1, dynamically linked (uses shared libs), not stripped

**Comment by debiansid** [comment]
./configure returns good, pdns_hw is for mips,

**Comment by Habbie** [comment]
./pdns_hw not running on your build box is not weird :)

Can you check changelogs for your uclibc to see if swapcontext should be supported on ARM in your version?

**Comment by Habbie** [comment]
If swapcontext is not supported, either try a different (uc)libc, or try building the recursor from our libco branch at https://github.com/PowerDNS/pdns/tree/libco

**Comment by Habbie** [comment]
I checked, there is no released version of uClibc with *context support. So, either try a different libc, or try our libco branch, please.

**Comment by debiansid** [comment]
ok, thanks. libco branch does not have "configure", is there a way to cross compile it?

**Comment by debiansid** [comment]
ok I tried your libco branch it needs libssp support which openwrt  disabled now.so, mission impossible for me.
would you please nicely fork an Openwrt support version of recursor? I especially like its web interface.thanks

**Comment by debiansid** [comment]
ok,switched to toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19, it compiling, I will let you know the result. thanks

**Comment by debiansid** [comment]
file pdns_recursor
pdns_recursor: ELF 32-bit MSB  shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.16, not stripped
-rwxrwxr-x 1 admin admin 2578671 Jan 27 13:05 pdns_recursor
-rw-rw-r-- 1 admin admin   27500 Jan 27 13:05 rec_control.o
-rwxrwxr-x 1 admin admin  295123 Jan 27 13:05 rec_control

succeed!! but I need to strip it.

**Comment by Habbie** [comment]
:cake:

**Comment by debiansid** [comment]
Habbie， I tried to strip it , it still almost 2MB, is there a way to make it smaller? such as disable lua modules?

**Comment by Habbie** [comment]
You can try compiling with -Os or -Oz. I don't think you built with Lua.

**Comment by debiansid** [comment]
mips-openwrt-linux-g++ syncres.o misc.o unix_utility.o qtype.o logger.o arguments.o lwres.o pdns_recursor.o recursor_cache.o dnsparser.o dnswriter.o dnsrecords.o rcpgenerator.o base64.o zoneparser-tng.o rec_channel.o rec_channel_rec.o selectmplexer.o sillyrecords.o dns_random.o pubsuffix.o ext/polarssl/library/aes.o ext/polarssl/library/base64.o dnslabeltext.o lua-pdns.o lua-recursor.o randomhelper.o recpacketcache.o dns.o reczones.o base32.o nsecrecords.o json.o ws-recursor.o ws-api.o version.o responsestats.o webserver.o ext/yahttp/yahttp/reqresp.o ext/yahttp/yahttp/router.o rec-carbon.o secpoll-recursor.o lua-iputils.o iputils.o optional/epollmplexer.o   -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie    -o pdns_recursor
those are parts of pdns_recursor I guess.

**Comment by Habbie** [comment]
They are, and you can't really remove any of those. But the lua-*.o files are almost empty if you don't build with Lua (and if you did build with Lua, it would be using liblua.so anyway).

We're sorry, but the recursor is pretty big.

**Comment by debiansid** [comment]
Ok I see.thanks for your time.I will try to run it on my home router anyway. Let's see how it goes.

**Comment by Habbie** [comment]
Good luck!

**Comment by debiansid** [comment]
Hi Habbie
I tried to compile it in Openwrt SDK, it will be compiled into ipk format. compiling was good, 
when it tried to strip  and execute pdns_recursor, error came out.

I am wondering if there any code in source to do those 2 steps.

thanks


make[4]: Leaving directory `/home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1'
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -I/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/usr/include -I/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/include -I/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/usr/include -I/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -I/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/usr/include -I/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/include -I/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/usr/include -I/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/include " LDFLAGS="-L/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/usr/lib -L/home/admin/openwrt/staging_dir/target-mips_34kc_eglibc-2.19/lib -L/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/usr/lib -L/home/admin/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_eglibc-2.19/lib " make -C /home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/. AR=mips-openwrt-linux-gnu-ar AS="mips-openwrt-linux-gnu-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float" LD=mips-openwrt-linux-gnu-ld NM=mips-openwrt-linux-gnu-nm CC="mips-openwrt-linux-gnu-gcc" GCC="mips-openwrt-linux-gnu-gcc" CXX="mips-openwrt-linux-gnu-g++" RANLIB=mips-openwrt-linux-gnu-ranlib STRIP=mips-openwrt-linux-gnu-strip OBJCOPY=mips-openwrt-linux-gnu-objcopy OBJDUMP=mips-openwrt-linux-gnu-objdump SIZE=mips-openwrt-linux-gnu-size CROSS="mips-openwrt-linux-gnu-" ARCH="mips" DESTDIR="/home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install"  install;
make[4]: Entering directory `/home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1'
mkdir -p /home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install//usr/sbin/
mv pdns_recursor /home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install//usr/sbin/
strip /home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install//usr/sbin//pdns_recursor
strip: Unable to recognise the format of the input file `/home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install//usr/sbin//pdns_recursor'
make[4]: *** [install] Error 1


/bin/sh: /home/admin/openwrt/build_dir/target-mips_34kc_eglibc-2.19/pdns-recursor/pdns-recursor-3.7.0-rc1/ipkg-install//usr/sbin//pdns_recursor: cannot execute

**Comment by debiansid** [comment]
by editing Makefile, i removed strip and execute lines , it works. I get pdns_recursor_3.7.0-rc1-1_ar71xx.ipk

**Comment by debiansid** [comment]
turns out ，autoconf creates Makefile from Makfile.in , I made a patch to change Makefile.in, turned off strip and mv to cp, it is compiling again.
