### ISSUE TITLE
Docs on authoritative back-ends should specify if compiled in by default

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2133]
I found it quite confusing to chose between `geo` and `geoip` back-ends; the former is compiled into the offering at powerdns.com whereas the latter isn't.

Current download from contains the following modules compiled in:

```
pdns_server --list-modules
Modules available:
bind
geo
gmysql
gpgsql
gpgsql2
gsqlite3
lua
mydns
opendbx
pipe
random
tinydns
```

The documentation should (or could) specify whether a back-end is baked in or not.

**Comment by Habbie** [comment]
related to #1923

**Comment by jpmens** [comment]
Documentation should also attempt to explain the differences, advantages, disadvantages between the `geo` and `geoip` back-ends.
