### ISSUE TITLE
geo back-end: problem with CIDR in zone file?

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2134]
I have added the following two entries to the zone file for the `geo` back-end:

```
10.1.1.204/32 :127.0.0.56:be
10.1.1.203/32 :127.0.1.20:de
```

Queries from those respective IPs (over IPv4) do not consistently answer: sometimes I get the configured CNAME RR for `be`, at other times I get the CNAME for `de`. I haven't been able to determine why this is.

**Comment by jpmens** [comment]
`"PowerDNS Authoritative Server 3.4.1 (jenkins@autotest.powerdns.com built 20141030110054 root@autotest.powerdns.com)"`

**Comment by pieterlexis** [comment]
The Geo backend is removed from 4.0 onward.
