### ISSUE TITLE
Allow overriding gpgsql connect string

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2138]
Right now we support a subset of valid postgres connect string keys, notably excluding anything related to SSL/TLS. We should allow the user to specify the whole string.

The only hard part in this is hiding the password from logging (which is easy right now because we know where it is).

**Comment by zeha** [comment]
I guess one could log the output of PQconninfoParse (filtered for password) instead.

**Comment by Habbie** [comment]
nice!
