### ISSUE TITLE
PowerDNS crashing - binary logging not possible

### ISSUE THREAD

**Issue by poiuty** [PowerDNS/pdns#2154]
```
Jan 30 05:46:43 mail pdns[31543]: Exiting because communicator thread died with error: GSQLBackend unable to refresh domain_id 843: Failed to execute mysql_query, perhaps connection died? Err=1: Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
```
When in /etc/mysql/my.cnf => set binlog_format = ROW => work and stop crashing.
MySQL percona-server-server-5.6 (= 5.6.22-71.0-726.wheezy)

**Comment by ahupowerdns** [comment]
Hi poiuty,

PowerDNS needs to exit if it finds a catastrophic inability to communicate
with the database. The guardian will then restart PowerDNS, giving it a
chance to maybe connect to a fixed database server.

We might need to document that BINLOG_FORMAT=STATEMENT is not compatible
with PowerDNS perhaps, I'm not a MySQL expert.

Are these standard MySQL settings? 

	Bert

**Comment by poiuty** [comment]
It`s happend when we use replication.
some bind9 (masters) <= pdns(slave one) and mysql(master) => pdns(slave two) and mysql(slave).

Crash on master MySQL.
binlog_format => STATEMENT (default)
```
# Replication settings
server-id = 1
log_bin                 = /var/log/mysql/mysql-bin.log
expire_logs_days        = 10
max_binlog_size         = 100M
binlog_do_db            = dns
```
If change binlog_format => ROW or MIXED => no crash and work well.

**Comment by Habbie** [comment]
This is documented for upgrades in https://doc.powerdns.com/html/from3.3to3.3.1.html

Treating this as a doc update request for non-upgrade installs.

**Comment by poiuty** [comment]
I take sql dump from https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/

**Comment by pieterlexis** [comment]
PowerDNS does not crash on this anymore and the BINLOG_FORMAT is documented in the [Backend](https://doc.powerdns.com/md/authoritative/backend-generic-mysql/#using-mysql-replication) docs
