### ISSUE TITLE
Where is the "secpoll zonefile"?

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2164]
Your "up to date secpoll zonefile" as described [in the blog](http://blog.powerdns.com/2014/10/22/powerdns-security-status-polling/) is 404. ;-)

**Comment by jpmens** [comment]
Found it at [https://github.com/PowerDNS/pdns/blob/master/docs/secpoll.zone](https://github.com/PowerDNS/pdns/blob/master/docs/secpoll.zone). 

Typo in link. Blog says `https://github.com/PowerDNS/pdns/blob/master/pdns/docs/secpoll.zone`

**Comment by Habbie** [comment]
Got moved by 215573184347f77fbfe6611e94f89a53a20cdce5. Blog post updated. Thanks!
