### ISSUE TITLE
Separate ChangeLog for Recursor and Authoritative DNS

### ISSUE THREAD

**Issue by svetlyak40wt** [PowerDNS/pdns#2166]
Right now both products have [single changelog](https://github.com/PowerDNS/pdns/blob/master/docs/markdown/changelog.md.raw) and it is blow my mind because versions are different.

It would be more convenient to track changes in each of these products. And also they could be easily tracked via [allmychanges.com](http://allmychanges.com/p/soft/powerdns/) or similar services.

**Comment by svetlyak40wt** [comment]
I'll send a pull-request if you are ready to improve changelog.

**Comment by Habbie** [comment]
Hi! Thanks for the suggestion. I am not opposed to it. @pieterlexis may have an opinion :)

In any case I would suggest waiting just a bit, we have two releases (auth 3.4.2 and recursor 3.7.0) planned very soon, and it would be tricky to have the split happen meanwhile.

**Comment by pieterlexis** [comment]
I agree, even though the codebase does have some overlap, we separate most of the ducumentation anyway.

**Comment by svetlyak40wt** [comment]
Cool, then I'll separate them after 3.4.2 and 3.7.0 releases, ok?

**Comment by Habbie** [comment]
We have no releases planned shortly, now is a great time to mess with the docs!

**Comment by pieterlexis** [comment]
I think we'll do this post-4.0.0. So from 4.0.1 onward we'll have this separated

**Comment by svetlyak40wt** [comment]
Good news, Peter! Thank you!

**Comment by Habbie** [comment]
@pieterlexis assigning this to you just like the other one seconds ago

**Comment by pieterlexis** [comment]
ref: #5481

**Comment by pieterlexis** [comment]
done!
