### ISSUE TITLE
Domain more recent than master, our serial 0 > their serial <large number>

### ISSUE THREAD

**Issue by Genesis2001** [PowerDNS/pdns#2168]
Domain '[mydomain]' more recent than master, our serial 0 > their serial 3933516418

> [08:05:14] Habbie: Genesis2001, the issue is that we treat an absent domain as having serial 0
> [08:05:19] Habbie: Genesis2001, this is a bug

I've got a supermaster setup on one machine, and a slave ("ns1") setup on another which has my supermaster listed.

The serial for the zone was larger than 2^31

> [08:05:53] Genesis2001: also on the [supermaster], in my domains table for that domain, notified_serial is negative too
> [08:05:55] Genesis2001: o.o
> [08:05:58] Habbie: negative!
> [08:06:10] Habbie: -1786032770 ?
> [08:06:16] Genesis2001: -361450878

---

> [08:07:38] Habbie: then please file two tickets
> [08:07:57] Habbie: for now i'd recommend changing your serial to something smaller than 2^31

OS: Debian
OS: Version: 7.8 (Wheezy)
PDNS version: 3.4.1 (wheezy-backports)

**Comment by pieterlexis** [comment]
should be fixed with #2982

**Comment by Genesis2001** [comment]
Hmmm. Loooong bug. I think I actually worked around this by using a different serial scheme than I was at the time I encountered this bug.

I think I was using a long-numeric-date serial (ie: 20150202HHMMSS format). I now just use a simple `UNIX_TIMESTAMP()+1` serial in my SQL. :)
