### ISSUE TITLE
relro support not detected on openSUSE_13.2-x86_64

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2172]
For some reason, our relro detection script does not work on openSUSE, discovered by @darix

**Comment by darix** [comment]
```$LD``` is not set, which leads to:

```
+ ld_help='./configure: line 5330: --help: command not found'  
```

hth :)

**Comment by darix** [comment]
workaround applied for now:

https://build.opensuse.org/package/rdiff/server:dns/pdns?linkrev=base&rev=107
