### ISSUE TITLE
API should send 403 not 400 on incorrect API KEY

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2179]
The web API sends 400 error code now if API key is wrong, which is wrong. It should send 403 instead.

400 Bad Request
    The server cannot or will not process the request due to something that is perceived to be a client error.

403 Forbidden
    The request was a valid request, but the server is refusing to respond to it. Unlike a 401 Unauthorized response, authenticating will make no difference.

**Comment by pieterlexis** [comment]
401 makes more sense in my opion, as authenticating (by using the **correct** API key) does make a difference. A 403 makes more sense if the user's IP isn't listed in `webserver-allow-from`

**Comment by pieterlexis** [comment]
Hrm, rereading RFC 2616 (the section on the 401), clarifies your point better:
```
   The request requires user authentication. The response MUST include a
   WWW-Authenticate header field (section 14.47) containing a challenge
   applicable to the requested resource. The client MAY repeat the
   request with a suitable Authorization header field (section 14.8). If
   the request already included Authorization credentials, then the 401
   response indicates that authorization has been refused for those
   credentials.
```

We don't use the `Authorization` header, so 403 makes sense (RFC-wise :smile: )
