### ISSUE TITLE
recursor does not forward zone correctly?

### ISSUE THREAD

**Issue by debiansid** [PowerDNS/pdns#2183]
my setup is like this
port:40 dnscrypt-proxy 
port:5300 unbound almost same configuration as recursor.
port:5301 pdns-recursor with forward.conf like this
+youtube.com=127.0.0.1:40
+hulu.com=127.0.0.1:40
+huluim.com=127.0.0.1:40
+muzu.tv=127.0.0.1:40
+netflix.com=127.0.0.1:40
+pandora.com=127.0.0.1:40
+pandora.tv=127.0.0.1:40
+.=127.0.0.1:40

based my very simple test, I found my recursor does not forward zone to port40;
in the meantime, 

root@YesRouter:/etc/powerdns# dig www.youtube.com -p5301

; <<>> DiG 9.9.4 <<>> www.youtube.com -p5301
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3426
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        86353   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 476    IN      CNAME   youtube-ui-china.l.google.com.
youtube-ui-china.l.google.com. 207 IN   A       198.100.153.138

;; Query time: 4 msec
;; SERVER: 127.0.0.1#5301(127.0.0.1)
;; WHEN: Wed Feb 04 17:08:47 CST 2015
;; MSG SIZE  rcvd: 114

root@YesRouter:/etc/powerdns# dig www.youtube.com @5300
dig: couldn't get address for '5300': not found
root@YesRouter:/etc/powerdns# dig www.youtube.com -p5300

; <<>> DiG 9.9.4 <<>> www.youtube.com -p5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14201
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        85783   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 284    IN      CNAME   youtube-ui-china.l.google.com.
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.139
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.138
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.102
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.101
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.113
youtube-ui-china.l.google.com. 180 IN   A       173.194.72.100

;; Query time: 385 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Wed Feb 04 17:18:16 CST 2015
;; MSG SIZE  rcvd: 205

root@YesRouter:/etc/powerdns# dig www.youtube.com -p40

; <<>> DiG 9.9.4 <<>> www.youtube.com -p40
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42408
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        86349   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 850    IN      CNAME   youtube-ui-china.l.google.com.
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.113
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.100
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.138
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.139
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.101
youtube-ui-china.l.google.com. 130 IN   A       173.194.72.102

;; Query time: 115 msec
;; SERVER: 127.0.0.1#40(127.0.0.1)
;; WHEN: Wed Feb 04 17:08:50 CST 2015
;; MSG SIZE  rcvd: 205

**Comment by ahupowerdns** [comment]
Hi - I don't know what 'forward.conf' is, it is not something we made. I just checked, this works as expected: forward-zones=youtube.com=127.0.0.1:40. Can you show the output of your PowerDNS startup, and the output of trying to resolve youtube with --trace enabled.

**Comment by ZaphodB** [comment]
Do you have https://doc.powerdns.com/md/recursor/settings/#forward-zones-file in your recursor.conf pointing to your forward.conf?

**Comment by debiansid** [comment]
forward-zones-file=/etc/powerdns/forward.conf
root@YesRouter:/etc/powerdns# /etc/init.d/pdns-recursor start
Starting PowerDNS recursing nameserver: Feb 04 17:30:59 PowerDNS Recursor 3.7.0-rc1 (jenkins@autotest.powerdns.com) (C) 2001-2015 PowerDNS.COM BV
Feb 04 17:30:59 Using 32-bits mode. Built on 20150202145632 by admin@debiansid.localdomain, gcc 4.8.3.
Feb 04 17:30:59 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Feb 04 17:30:59 Reading random entropy from '/dev/urandom'
Feb 04 17:30:59 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 115.238.145.6/32, 110.188.32.172/32
Feb 04 17:31:00 Will not send queries to: 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
Feb 04 17:31:00 PowerDNS Recursor itself will distribute queries over threads
Feb 04 17:31:00 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Feb 04 17:31:00 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Feb 04 17:31:00 Reading zone forwarding information from '/etc/powerdns/forward.conf'
Feb 04 17:31:00 Done parsing 2353 forwarding instructions from file '/etc/powerdns/forward.conf'
Feb 04 17:31:00 Inserting rfc 1918 private space zones
Feb 04 17:31:00 Listening for UDP queries on 127.0.0.1:5301
Feb 04 17:31:00 Enabled TCP data-ready filter for (slight) DoS protection
Feb 04 17:31:00 Listening for TCP queries on 127.0.0.1:5301
Feb 04 17:31:00 Calling daemonize, going to background
started

root@YesRouter:/etc/powerdns# dig +trace www.youtube.com -p5301

; <<>> DiG 9.9.4 <<>> +trace www.youtube.com -p5301
;; global options: +cmd
.                       394870  IN      NS      c.root-servers.net.
.                       394870  IN      NS      k.root-servers.net.
.                       394870  IN      NS      i.root-servers.net.
.                       394870  IN      NS      j.root-servers.net.
.                       394870  IN      NS      a.root-servers.net.
.                       394870  IN      NS      h.root-servers.net.
.                       394870  IN      NS      m.root-servers.net.
.                       394870  IN      NS      e.root-servers.net.
.                       394870  IN      NS      g.root-servers.net.
.                       394870  IN      NS      b.root-servers.net.
.                       394870  IN      NS      l.root-servers.net.
.                       394870  IN      NS      f.root-servers.net.
.                       394870  IN      NS      d.root-servers.net.
;; Received 241 bytes from 127.0.0.1#5301(127.0.0.1) in 66 ms


looks like recursor is looking it from root server which is not I want coz here we have serious dns poisoning.

**Comment by ahupowerdns** [comment]
and now the --trace output please.

**Comment by debiansid** [comment]
openwrt only has dig +trace only show me these
root@YesRouter:/etc/powerdns# dig www.youtube.com -p5301 +trace

; <<>> DiG 9.9.4 <<>> www.youtube.com -p5301 +trace
;; global options: +cmd
.                       394122  IN      NS      c.root-servers.net.
.                       394122  IN      NS      k.root-servers.net.
.                       394122  IN      NS      i.root-servers.net.
.                       394122  IN      NS      j.root-servers.net.
.                       394122  IN      NS      a.root-servers.net.
.                       394122  IN      NS      h.root-servers.net.
.                       394122  IN      NS      m.root-servers.net.
.                       394122  IN      NS      e.root-servers.net.
.                       394122  IN      NS      g.root-servers.net.
.                       394122  IN      NS      b.root-servers.net.
.                       394122  IN      NS      l.root-servers.net.
.                       394122  IN      NS      f.root-servers.net.
.                       394122  IN      NS      d.root-servers.net.
;; Received 241 bytes from 127.0.0.1#5301(127.0.0.1) in 66 ms

**Comment by ahupowerdns** [comment]
no, add --trace or 'trace' to recursor.conf please.

**Comment by debiansid** [comment]
root@YesRouter:/etc/powerdns# /usr/sbin/pdns_recursor --trace
Feb 04 18:00:21 PowerDNS Recursor 3.7.0-rc1 (jenkins@autotest.powerdns.com) (C) 2001-2015 PowerDNS.COM BV
Feb 04 18:00:21 Using 32-bits mode. Built on 20150202145632 by admin@debiansid.localdomain, gcc 4.8.3.
Feb 04 18:00:21 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Feb 04 18:00:21 Reading random entropy from '/dev/urandom'
Feb 04 18:00:21 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 115.238.145.6/32, 110.188.32.172/32
Feb 04 18:00:22 Will not send queries to: 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
Feb 04 18:00:22 PowerDNS Recursor itself will distribute queries over threads
Feb 04 18:00:22 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Feb 04 18:00:22 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Feb 04 18:00:22 Reading zone forwarding information from '/etc/powerdns/forward.conf'
Feb 04 18:00:23 Done parsing 2353 forwarding instructions from file '/etc/powerdns/forward.conf'
Feb 04 18:00:23 Inserting rfc 1918 private space zones
Feb 04 18:00:23 Listening for UDP queries on 127.0.0.1:5301
Feb 04 18:00:23 Enabled TCP data-ready filter for (slight) DoS protection
Feb 04 18:00:23 Listening for TCP queries on 127.0.0.1:5301
Feb 04 18:00:23 Calling daemonize, going to background
root@YesRouter:/etc/powerdns# dig www.youtube.com -p5301 +trace

; <<>> DiG 9.9.4 <<>> www.youtube.com -p5301 +trace
;; global options: +cmd
.                       392706  IN      NS      k.root-servers.net.
.                       392706  IN      NS      f.root-servers.net.
.                       392706  IN      NS      j.root-servers.net.
.                       392706  IN      NS      a.root-servers.net.
.                       392706  IN      NS      g.root-servers.net.
.                       392706  IN      NS      h.root-servers.net.
.                       392706  IN      NS      m.root-servers.net.
.                       392706  IN      NS      b.root-servers.net.
.                       392706  IN      NS      d.root-servers.net.
.                       392706  IN      NS      e.root-servers.net.
.                       392706  IN      NS      c.root-servers.net.
.                       392706  IN      NS      i.root-servers.net.
.                       392706  IN      NS      l.root-servers.net.
;; Received 241 bytes from 127.0.0.1#5301(127.0.0.1) in 87 ms


and I set trace=on in recursor.conf too.

**Comment by ahupowerdns** [comment]
and now check the log for the actual --trace output, or run pdns with --daemon=no to get it on screen. I need this long output to see what might be going wrong.

**Comment by debiansid** [comment]
;; connection timed out; no servers could be reached

last line of output.

**Comment by debiansid** [comment]
Feb 04 18:03:48 1 [1/1] question for 'www.youtube.com.|A' from 127.0.0.1
Feb 04 18:03:48 [1] www.youtube.com.: Looking for CNAME cache hit of 'www.youtube.com.|CNAME'
Feb 04 18:03:48 [1] www.youtube.com.: No CNAME cache hit of 'www.youtube.com.|CNAME' found
Feb 04 18:03:48 [1] www.youtube.com.: No cache hit for 'www.youtube.com.|A', trying to find an appropriate NS record
Feb 04 18:03:48 [1] www.youtube.com.: Cache consultations done, have 1 NS to contact
Feb 04 18:03:48 [1] www.youtube.com.: Nameservers: +127.0.0.1:40(0.00ms)
Feb 04 18:03:48 [1] www.youtube.com.: Trying to resolve NS '+127.0.0.1:40' (1/1)
Feb 04 18:03:48 [1] www.youtube.com.: Domain has hardcoded nameserver(s)
Feb 04 18:03:48 [1] www.youtube.com.: Resolved 'youtube.com.' NS +127.0.0.1:40 to: 127.0.0.1
Feb 04 18:03:48 [1] www.youtube.com.: Trying IP 127.0.0.1:40, asking 'www.youtube.com.|A'
Feb 04 18:03:48 [1] www.youtube.com.: Got 9 answers from +127.0.0.1:40 (127.0.0.1), rcode=0 (No Error), aa=0, in 458ms
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'www.youtube.com.|CNAME|youtube-ui.l.google.com.' from 'youtube.com.' nameservers? YES!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui.l.google.com.|CNAME|youtube-ui-china.l.google.com.' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.138' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.101' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.139' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.102' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.113' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: accept answer 'youtube-ui-china.l.google.com.|A|173.194.72.100' from 'youtube.com.' nameservers? NO!
Feb 04 18:03:48 [1] www.youtube.com.: skipping OPT answer '.' from 'youtube.com.' nameservers
Feb 04 18:03:48 [1] www.youtube.com.: determining status after receiving this packet
Feb 04 18:03:48 [1] www.youtube.com.: status=got a CNAME referral, starting over with youtube-ui.l.google.com.
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Looking for CNAME cache hit of 'youtube-ui.l.google.com.|CNAME'
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: No CNAME cache hit of 'youtube-ui.l.google.com.|CNAME' found
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: No cache hit for 'youtube-ui.l.google.com.|A', trying to find an appropriate NS record
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Cache consultations done, have 1 NS to contact
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Nameservers: +202.98.96.68:53(50.09ms)
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Trying to resolve NS '+202.98.96.68:53' (1/1)
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Domain has hardcoded nameserver(s)
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Resolved '.' NS +202.98.96.68:53 to: 202.98.96.68
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Trying IP 202.98.96.68:53, asking 'youtube-ui.l.google.com.|A'
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: Got 2 answers from +202.98.96.68:53 (202.98.96.68), rcode=0 (No Error), aa=0, in 45ms
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: accept answer 'youtube-ui.l.google.com.|CNAME|youtube-ui-china.l.google.com.' from '.' nameservers? YES!
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: accept answer 'youtube-ui-china.l.google.com.|A|99.192.225.151' from '.' nameservers? YES!
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: determining status after receiving this packet
Feb 04 18:03:48 [1]  youtube-ui.l.google.com.: status=got a CNAME referral, starting over with youtube-ui-china.l.google.com.
Feb 04 18:03:48 [1]   youtube-ui-china.l.google.com.: Looking for CNAME cache hit of 'youtube-ui-china.l.google.com.|CNAME'
Feb 04 18:03:48 [1]   youtube-ui-china.l.google.com.: No CNAME cache hit of 'youtube-ui-china.l.google.com.|CNAME' found
Feb 04 18:03:48 [1]   youtube-ui-china.l.google.com.: Found cache hit for A: 99.192.225.151[ttl=1522]
Feb 04 18:03:48 1 [1/1] answer to question 'www.youtube.com.|A': 3 answers, 0 additional, took 2 packets, 503.856 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0

**Comment by debiansid** [comment]
the reason I set forward .=202.98.96.68 which is my local ISP DNS server is that I need CDN friendly DNS resolving.

**Comment by debiansid** [comment]
FYI twitter.com is good.

Feb 04 18:10:14 1 [3/1] question for 'www.twitter.com.|A' from 127.0.0.1
Feb 04 18:10:14 [3] www.twitter.com.: Looking for CNAME cache hit of 'www.twitter.com.|CNAME'
Feb 04 18:10:14 [3] www.twitter.com.: No CNAME cache hit of 'www.twitter.com.|CNAME' found
Feb 04 18:10:14 [3] www.twitter.com.: No cache hit for 'www.twitter.com.|A', trying to find an appropriate NS record
Feb 04 18:10:14 [3] www.twitter.com.: Cache consultations done, have 1 NS to contact
Feb 04 18:10:14 [3] www.twitter.com.: Nameservers: +127.0.0.1:40(0.74ms)
Feb 04 18:10:14 [3] www.twitter.com.: Trying to resolve NS '+127.0.0.1:40' (1/1)
Feb 04 18:10:14 [3] www.twitter.com.: Domain has hardcoded nameserver(s)
Feb 04 18:10:14 [3] www.twitter.com.: Resolved 'twitter.com.' NS +127.0.0.1:40 to: 127.0.0.1
Feb 04 18:10:14 [3] www.twitter.com.: Trying IP 127.0.0.1:40, asking 'www.twitter.com.|A'
Feb 04 18:10:14 [3] www.twitter.com.: Got 4 answers from +127.0.0.1:40 (127.0.0.1), rcode=0 (No Error), aa=0, in 154ms
Feb 04 18:10:15 [3] www.twitter.com.: accept answer 'www.twitter.com.|CNAME|twitter.com.' from 'twitter.com.' nameservers? YES!
Feb 04 18:10:15 [3] www.twitter.com.: accept answer 'twitter.com.|A|185.45.5.32' from 'twitter.com.' nameservers? YES!
Feb 04 18:10:15 [3] www.twitter.com.: accept answer 'twitter.com.|A|185.45.5.43' from 'twitter.com.' nameservers? YES!
Feb 04 18:10:15 [3] www.twitter.com.: skipping OPT answer '.' from 'twitter.com.' nameservers
Feb 04 18:10:15 [3] www.twitter.com.: determining status after receiving this packet
Feb 04 18:10:15 [3] www.twitter.com.: status=got a CNAME referral, starting over with twitter.com.
Feb 04 18:10:15 [3]  twitter.com.: Looking for CNAME cache hit of 'twitter.com.|CNAME'
Feb 04 18:10:15 [3]  twitter.com.: No CNAME cache hit of 'twitter.com.|CNAME' found
Feb 04 18:10:15 [3]  twitter.com.: Found cache hit for A: 185.45.5.32[ttl=16] 185.45.5.43[ttl=16]
Feb 04 18:10:15 1 [3/1] answer to question 'www.twitter.com.|A': 3 answers, 0 additional, took 1 packets, 154.214 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0

**Comment by paddg** [comment]
Am 04.02.2015 um 11:08 schrieb debiansid:
> =202.98.96.68 which is my local ISP DNS server

Which seems to be an open resolver with a very slow response behavior
and a high packet loss rate!

**Comment by ahupowerdns** [comment]
The problem is that PowerDNS does not follow the CNAME chain as it does not trust your forwarder for youtube-ui-china.l.google.com. This is probably a bug in PowerDNS forwarding. But if you forward this domain name to your china proxy as well, it works.

**Comment by debiansid** [comment]
I am sure I already forward google.com to dnscrypt-proxy too.you mean I should do it to YouTube-ui-china.l.google.com?

**Comment by debiansid** [comment]
@paddg,exactly it is local ISP resolver with DNS poisoning.

**Comment by debiansid** [comment]
Ahupowerdns,there are many came of foreign websites which are serving images/css/js from Akamai/amazon ,they will have same situation.

**Comment by ahupowerdns** [comment]
debiansid, I understand your issue, and I think we need to do better. This patch will probably help you:

diff --git a/pdns/syncres.cc b/pdns/syncres.cc
index e688531..8c83442 100644
--- a/pdns/syncres.cc
+++ b/pdns/syncres.cc
@@ -1047,7 +1047,7 @@ int SyncRes::doResolveAt(set<string, CIStringCompare> nameservers, string auth,
           continue;
         }
           
-        if(dottedEndsOn(i->qname, auth)) {
+        if(dottedEndsOn(i->qname, auth) || sendRDQuery) {
           if(lwr.d_aabit && lwr.d_rcode==RCode::NoError && i->d_place==DNSResourceRecord::ANSWER && ::arg().contains("delegation-only",auth)) {
             LOG("NO! Is from delegation-only zone"<<endl);
             s_nodelegated++;

**Comment by debiansid** [comment]
Thanks I will build it with your patch and let you know the result

**Comment by debiansid** [comment]
@ahupowerdns 
it works!! thanks!!
BTW, will you merge it into rc2?


root@YesRouter:~# dig www.youtube.com -p5301

; <<>> DiG 9.9.4 <<>> www.youtube.com -p5301
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49239
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        47878   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 859    IN      CNAME   youtube-ui-china.l.google.com.
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.113
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.139
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.101
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.102
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.138
youtube-ui-china.l.google.com. 139 IN   A       173.194.72.100

;; Query time: 246 msec
;; SERVER: 127.0.0.1#5301(127.0.0.1)
;; WHEN: Wed Feb 04 19:36:20 CST 2015
;; MSG SIZE  rcvd: 194
