### ISSUE TITLE
REST API: more metadata from domains table?

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2188]
Enhancement request.

(I'm still trying to understand the use of the `comments` table (related to #2064); comments are obtainable only when the whole zone is retrieved which seems a bit of a waste.)

I think the API (`servers/localhost/zones`) should list the `account` column of the domains table.

In addition to that, what I'd very much like to see are additional columns a customer creates. For example:

```
ALTER TABLE domains ADD cust VARCHAR(80);
UPDATE domains SET cust = 'something1' WHERE id = 2;
```

followed by 

```
curl -s -XGET -H 'X-API-Key: otto' http://192.168.1.114:8081/servers/localhost/zones
```
```json
[
  {
    "last_check": 0,
    "id": "example.net.",
    "url": "/servers/localhost/zones/example.net.",
    "name": "example.net",
    "kind": "Master",
    "dnssec": false,
    "masters": [],
    "serial": 2015012903,
    "notified_serial": 2015012903,
   "cust" : "something1"     <------------
  },
```

The precondition would be that a column name doesn't clobber an existing JSON element the API currently uses. Alternatively, the API could prefix with with `x-`.

**Comment by zeha** [comment]
`account` is done; having custom fields in there will be ... interesting.

**Comment by jpmens** [comment]
I glanced at the hard-coded SQL queries in the code. "Interesting" is an understatement...

`account` is already very valuable for us, thank you.

**Comment by jpmens** [comment]
`domains.account` is already very useful for which I thank you. I am closing this as completed.
