### ISSUE TITLE
REST API: why don't records [] inherit from rrset [] ?

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2194]
It appears that _records_ don't inherit from _rrset_. In the `PATCH` example below, if I omit, say, the `name` elements from each of the records, an error is raised.

```
{"error":"Key 'name' not present or not a String"}
```

As an RRset must have identical owner names, types and TTL, it would seem more logical to me to keep these as part of the _rrset_ and not have to tediously repeat the data within each record.

```json
{
  "rrsets": [
    {
      "comments": [
        {
          "content": "This set is for $cust1",
          "account": "test1"
        }
      ],
      "records": [
        {
          "priority": 0,
          "type": "DS",
          "ttl": 3600,
          "name": "sub.p01.aa",
          "disabled": false,
          "content": "62555 8 2 1d5bc41ce88d27a08057b25ae26cd0db51afa2c38a666bc85f9a8f8ce830cfa0"
        },
        {
          "priority": 0,
          "type": "DS",
          "ttl": 3600,
          "name": "sub.p01.aa",
          "disabled": false,
          "content": "11741 12 3 4feebf42250e2e673bf8a1680e9d96339de05a8a374d8e262638993bec7ce8d8"
        }
      ],
      "changetype": "REPLACE",
      "type": "DS",
      "name": "sub.p01.aa"
    }
  ]
}
```

**Comment by zeha** [comment]
To answer your question from the title: because the code handling this is shared, and doesn't necessarily know that you're replacing an existing rrset. Nevertheless, this is a valid enhancement proposal.

**Comment by zeha** [comment]
We did that (in a slightly different way) in 4.0.0-alpha2. Thanks!
