### ISSUE TITLE
Support for root zone in auth (master & slave)

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2225]
Does PowerDNS Authoritative (3.4.2) officially support a root (`.`) zone both as a master and as a slave?

We're experiencing issues with slaving a root zone defined as follows in the MySQL back-end:

```
SELECT id, name, length(name), master, type FROM domains;
+----+---------------------------------+--------------+-------------------+-------+
| id | name                            | length(name) | master            | type  |
+----+---------------------------------+--------------+-------------------+-------+
| 40 |                                 |            0 | 100.96.34.11:5353 | SLAVE |

```

* Slaving `.` from an OpenDNSSEC server produces the following log entry. (Other zones work fine)
```
 While checking domain freshness: Query to '100.96.34.11:5353' for SOA of '' produced no results (RCode: Server Failure)
```
* There seems to no way to instruct _pdns_control_ to retrieve a root zone:
```
$ pdns_control retrieve ''
syntax: retrieve domain
$ pdns_control retrieve '.'
Domain '.' unknown
$ pdns_control retrieve "''"
Domain '''' unknown
$ pdns_control retrieve ' '
syntax: retrieve domain
```

Are these bugs, or am I trying to do something which isn't supposed to work? :-)

Related to #2216

**Comment by Habbie** [comment]
It's something we've never really tried to support, but we do consider these issues to be bugs. Because of https://tools.ietf.org/html/draft-ietf-dnsop-root-loopback-01#appendix-B I was already planning to start taking this seriously sometime soon. Your ticket is valid :)

**Comment by jpmens** [comment]
See also https://github.com/PowerDNS/pdns/issues/1541

**Comment by jpmens** [comment]
I'm seeing this fail with 3.4.2 against OpenDNSSEC as mentioned earlier, but 3.4.1 works against same ODS version. Also, both 3.4.2 and latest git-20150212-5520-988e0ac transfer fine from an NSD. 


```
Feb 12 19:34:07 1 slave domain needs checking, 0 queued for AXFR
Feb 12 19:34:07 Received serial number updates for 1 zones, had 0 timeouts
Feb 12 19:34:07 Domain '' is stale, master serial 9, our serial 0
Feb 12 19:34:07 Initiating transfer of '' from remote '192.168.1.112'
Feb 12 19:34:07 No master domains need notifications
Feb 12 19:34:07 AXFR started for ''
Feb 12 19:34:07 Transaction started for ''
Feb 12 19:34:07 AXFR done for '', zone committed with serial number 9
Feb 12 19:34:07 Done launching threads, ready to distribute questions
```

**Comment by jpmens** [comment]
It turns out the error-message is misleading: adding a SLAVE zone which doesn't exist on the master produces the diagnostic:

```
INSERT INTO domains (name, master, type) VALUES ('rijsttafel', '192.168.1.112', 'SLAVE');
```

```
pdns[12008]: While checking domain freshness: Query to '192.168.1.112' for SOA of '' produced no results (RCode: Server Failure)
```

**Comment by jpmens** [comment]
Can I somehow convince you to support a trailing dot on CLI utilities, even though that would be inconsistent with database _content_?

I just wasted 20 minutes ...

```
$ pdnssec check-zone .
[error] No SOA record present, or active, in zone '.'
Checked 0 records of '.', 1 errors, 0 warnings.


$ pdnssec check-zone ''
Checked 14 records of '', 0 errors, 0 warnings.
```

The `[error]` drove me mad... How about `[error] No such zone`?  ;-)

**Comment by pieterlexis** [comment]
This works in the current master
