### ISSUE TITLE
please build dnsgram with --enable-tools

### ISSUE THREAD

**Issue by Zugschlus** [PowerDNS/pdns#2245]
Hi,

please add dnsgram to the appropriate line in pdns/Makefile.am to have dnsgram built as well with configure --enable-tools was used. This was verified to work ;-)

Greetings
Marc

**Comment by ahupowerdns** [comment]
github HEAD appears to have this:
```
if TOOLS
bin_PROGRAMS += \
        dnsbulktest \
        dnsgram \
        dnsreplay \
```

or am I wrong?

**Comment by rubenk** [comment]
@ahupowerdns is right, it's 53ea4fab80d6.
