### ISSUE TITLE
dnsscope does not grok files written by dnscap

### ISSUE THREAD

**Issue by Zugschlus** [PowerDNS/pdns#2246]
Hi,

dnsscope does not grok the pcap files written by dnscap (https://www.dns-oarc.net/tools/dnscap) which seem to be missing the Ethernet header - they're raw IP only. It would be really nice if dnsscope and other PowerDNS related tools that can read pcap files would grok this format.

Greetings
Marc

**Comment by ahupowerdns** [comment]
Could you provide a sample file for us that needs to work?

**Comment by Zugschlus** [comment]
Sent in e-mail to support at powerdns.com - couldn't figure out quickly enough how to do a binary attachment
