### ISSUE TITLE
Support for single host override

### ISSUE THREAD

**Issue by mrjester888** [PowerDNS/pdns#2249]
Scenario:  example.com is hosted on Route53 with a lot of dynamic entries.  I want to inject a few hosts records into example.com without hosting the zone internally.  Because of the dynamic nature, maintaining it as a separate view is not sustainable.

The entries I want to create are CNAMEs pointed to host.sub.domain.tld  
eg. ns0.example.com CNAME ns0.int.example.com

Currently, I have this working with auth-zone files.  The zone is the name of the host, ns0.example.com, with an apex entry of "@ IN CNAME host.sub.domain.tld"

This is working to meet my needs currently.

**Comment by Habbie** [comment]
Does the ALIAS support in git master cover your needs?
