### ISSUE TITLE
Botan 1.11.* Support

### ISSUE THREAD

**Issue by James-TR** [PowerDNS/pdns#2250]
Would it be possible to add support for the current Botan development series?

**Comment by Habbie** [comment]
It might help if you can show some output of how things are failing with it.

**Comment by James-TR** [comment]
So far it looks like I need to force the compiler to use C++11

**Comment by James-TR** [comment]
https://gist.github.com/James-TR/26124edb6c4c302cf6a5 fancy schmancy build failure

**Comment by Habbie** [comment]
Is this still a thing, especially with #5498?

**Comment by randombit** [comment]
At this point 1.11 is a closed/unsupported development branch. You want 2.x

**Comment by pieterlexis** [comment]
you are right!
