### ISSUE TITLE
Please clarify difference between "quit" and "quit-nicely"

### ISSUE THREAD

**Issue by Whissi** [PowerDNS/pdns#2267]
I think it is very uncommon to have two ways to end a daemon (especially when you have a command named `quit-nicely` which sounds better than just "quit" but which isn't used in the runscripts in source). So please clarify the difference between `_quit_` and `_quit-nicely_` which can be called using `rec_control`.

From my understanding `quit` calls `_exit()` and `quit-nicely` calls `exit()` ... but when should we use which command?

If we want to keep two ways to end pdns/pdns_recursor we should add documentation and give recommendation to package maintainers which one they should use for normal shutdown in their init system.

**Comment by omoerbeek** [comment]
With the changes in #8521 the distinction is now bigger: `quit-nicely` stops threads but lets them finish their current work and release their reources and then does exit(0). While `quit` exits the process as soon as possible, letting the OS doing the cleanup of resources. The former case might takes some time.
