### ISSUE TITLE
Compile pdns-recursor-git-rec-3.7.0-153-g55693f8 failed.

### ISSUE THREAD

**Issue by hongyi-zhao** [PowerDNS/pdns#2272]
Hi all,

I cloned the git source of pdns on my Debian Wheezy, then using the following step to compile it:
------------------------
1- Installation of some depended tools:
sudo apt-get install ragel zip pandoc libboost-dev
2- obtain the source:
$ git clone https://github.com/PowerDNS/pdns.git pdns.git
3- Obtain the source code for pdns-recursor:
werner@debian:~/pdns.git/pdns$ ./dist-recursor
4- Compile the  pdns-recursor:
werner@debian:~/pdns-recursor-git-rec-3.7.0-153-g55693f8$ ./configure
werner@debian:~/pdns-recursor-git-rec-3.7.0-153-g55693f8$ STATIC=semi ./configure ; STATIC=semi make all

At this step, I meet the following errors:
make: *** No rule to make target `rapidjson/document.h', needed by `pdns_recursor.o'.  Stop.

Any hints on this issue?

Regards
------------------------

**Comment by Habbie** [comment]
Hello,

I cannot reproduce this issue on Ubuntu 14.04. Can you please provide full output of the commands you are running?

**Comment by hongyi-zhao** [comment]
Ok, see the following:

-------------------
werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ STATIC=semi ./configure
Testing dependencies and compiler.
Using make to build
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' -MM -MG *.cc *.hh > dep
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' pdns_hw.cc -o pdns_hw

Everything ok, now run make using same settings (if any) you passed ./configure

werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ STATIC=semi make all
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' -MM -MG *.cc *.hh > dep

PLEASE READ: If you get an error mentioning #include <boost/something.hpp>, please read README
PLEASE READ: for an easy fix!

g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o syncres.o syncres.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o misc.o misc.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o unix_utility.o unix_utility.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o qtype.o qtype.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o logger.o logger.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o arguments.o arguments.cc
g++  -Iext/rapidjson/include -I/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"'   -c -o lwres.o lwres.cc
make: *** No rule to make target `rapidjson/document.h', needed by `pdns_recursor.o'.  Stop.

--------------------

ps. The os info of mine is listed as follows:

werner@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

Regards

**Comment by Habbie** [comment]
Can you put the file `dep` on https://gist.github.com/ and post the URL here?

**Comment by hongyi-zhao** [comment]
see here:
https://gist.github.com/hongyi-zhao/18037981308aca304a73

Regards

**Comment by Habbie** [comment]
Can you show `ls -al /home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson/include` ?

**Comment by hongyi-zhao** [comment]
See the following:

--------------
werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ ls
-al
/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson/include
ls: cannot access
/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson/include:
No such file or directory
werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ ls
-al
/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson
ls: cannot access
/home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson:
No such file or directory
werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ ls
-al /home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext
total 8
drwxr-xr-x 2 werner werner 4096 Feb 23 15:04 .
drwx------ 8 werner werner 4096 Feb 23 18:42 ..
werner@debian:~/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8$ ls
-al /home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/
total 2000
drwx------ 8 werner werner   4096 Feb 23 18:42 .
drwxr-xr-x 4 werner werner   4096 Feb 23 18:34 ..
-rw-r--r-- 1 werner werner  12604 Feb 23 15:04 arguments.cc
-rw-r--r-- 1 werner werner   4834 Feb 23 15:04 arguments.hh
-rw-r--r-- 1 werner werner 129160 Feb 23 18:42 arguments.o
-rw-r--r-- 1 werner werner   3478 Feb 23 15:04 base32.cc
-rw-r--r-- 1 werner werner    177 Feb 23 15:04 base32.hh
-rw-r--r-- 1 werner werner    882 Feb 23 15:04 base64.cc
-rw-r--r-- 1 werner werner    182 Feb 23 15:04 base64.hh
drwxr-xr-x 2 werner werner   4096 Feb 23 15:04 build-scripts
-rw-r--r-- 1 werner werner   2517 Feb 23 15:04 cachecleaner.hh
-rw-r--r-- 1 werner werner    122 Feb 23 15:04 config.h
-rwxr-xr-x 1 werner werner   1606 Feb 23 15:04 configure
drwxr-xr-x 2 werner werner   4096 Feb 23 15:04 contrib
-rw-r--r-- 1 werner werner  18091 Feb 23 15:04 COPYING
-rw-r--r-- 1 werner werner  10868 Feb 23 18:42 dep
-rw-r--r-- 1 werner werner   3762 Feb 23 15:04 devpollmplexer.cc
-rw-r--r-- 1 werner werner   7197 Feb 23 15:04 dns.cc
-rw-r--r-- 1 werner werner   8393 Feb 23 15:04 dns.hh
-rw-r--r-- 1 werner werner   5324 Feb 23 15:04 dnslabeltext.cc
-rw-r--r-- 1 werner werner   2554 Feb 23 15:04 dnslabeltext.rl
-rw-r--r-- 1 werner werner  19584 Feb 23 15:04 dnsparser.cc
-rw-r--r-- 1 werner werner   9246 Feb 23 15:04 dnsparser.hh
-rw-r--r-- 1 werner werner   1187 Feb 23 15:04 dns_random.cc
-rw-r--r-- 1 werner werner    141 Feb 23 15:04 dns_random.hh
-rw-r--r-- 1 werner werner  15789 Feb 23 15:04 dnsrecords.cc
-rw-r--r-- 1 werner werner  17752 Feb 23 15:04 dnsrecords.hh
-rw-r--r-- 1 werner werner  10661 Feb 23 15:04 dnswriter.cc
-rw-r--r-- 1 werner werner   4810 Feb 23 15:04 dnswriter.hh
-rw-r--r-- 1 werner werner   4063 Feb 23 15:04 epollmplexer.cc
drwxr-xr-x 2 werner werner   4096 Feb 23 15:04 ext
-rw-r--r-- 1 werner werner   5062 Feb 23 15:04 iputils.cc
-rw-r--r-- 1 werner werner  12069 Feb 23 15:04 iputils.hh
-rw-r--r-- 1 werner werner   4292 Feb 23 15:04 json.cc
-rw-r--r-- 1 werner werner   1980 Feb 23 15:04 json.hh
-rw-r--r-- 1 werner werner   3796 Feb 23 15:04 kqueuemplexer.cc
-rw-r--r-- 1 werner werner   3547 Feb 23 15:04 lock.hh
-rw-r--r-- 1 werner werner   3944 Feb 23 15:04 logger.cc
-rw-r--r-- 1 werner werner   3702 Feb 23 15:04 logger.hh
-rw-r--r-- 1 werner werner  37352 Feb 23 18:42 logger.o
-rw-r--r-- 1 werner werner   8439 Feb 23 15:04 lua-iputils.cc
-rw-r--r-- 1 werner werner  10320 Feb 23 15:04 lua-pdns.cc
-rw-r--r-- 1 werner werner   1310 Feb 23 15:04 lua-pdns.hh
-rw-r--r-- 1 werner werner   9371 Feb 23 15:04 lua-recursor.cc
-rw-r--r-- 1 werner werner   2082 Feb 23 15:04 lua-recursor.hh
-rw-r--r-- 1 werner werner   6770 Feb 23 15:04 lwres.cc
-rw-r--r-- 1 werner werner   2221 Feb 23 15:04 lwres.hh
-rw-r--r-- 1 werner werner  41832 Feb 23 18:42 lwres.o
-rw-r--r-- 1 werner werner   4641 Feb 23 18:35 Makefile
-rw-r--r-- 1 werner werner   4531 Feb 23 15:04 Makefile.in
-rw-r--r-- 1 werner werner  21826 Feb 23 15:04 misc.cc
-rw-r--r-- 1 werner werner  14651 Feb 23 15:04 misc.hh
-rw-r--r-- 1 werner werner 110912 Feb 23 18:42 misc.o
-rw-r--r-- 1 werner werner   4849 Feb 23 15:04 mplexer.hh
-rw-r--r-- 1 werner werner  14572 Feb 23 15:04 mtasker.cc
-rw-r--r-- 1 werner werner   3894 Feb 23 15:04 mtasker.hh
-rw-r--r-- 1 werner werner   1408 Feb 23 15:04 namespaces.hh
-rw-r--r-- 1 werner werner    798 Feb 23 15:04 NOTICE
-rw-r--r-- 1 werner werner   7443 Feb 23 15:04 nsecrecords.cc
drwxr-xr-x 2 werner werner   4096 Feb 23 15:14 optional
-rw-r--r-- 1 werner werner   1422 Feb 23 15:04 pdnsexception.hh
-rw-r--r-- 1 werner werner    552 Feb 23 15:04 pdns_hw.cc
-rw-r--r-- 1 werner werner   6135 Feb 23 15:04 pdns_recursor.1
-rw-r--r-- 1 werner werner  83171 Feb 23 15:04 pdns_recursor.cc
-rwxr-xr-x 1 werner werner   1839 Feb 23 15:04 pdns-recursor.init.d
-rw-r--r-- 1 werner werner   4876 Feb 23 15:04 portsmplexer.cc
-rw-r--r-- 1 werner werner   5725 Feb 23 15:04 powerdns-example-script.lua
-rw-r--r-- 1 werner werner  94739 Feb 23 15:04 pubsuffix.cc
-rw-r--r-- 1 werner werner     64 Feb 23 15:04 pubsuffix.hh
-rw-r--r-- 1 werner werner   2524 Feb 23 15:04 qtype.cc
-rw-r--r-- 1 werner werner   5200 Feb 23 15:04 qtype.hh
-rw-r--r-- 1 werner werner  41952 Feb 23 18:42 qtype.o
-rw-r--r-- 1 werner werner    939 Feb 23 15:04 randomhelper.cc
-rw-r--r-- 1 werner werner  13761 Feb 23 15:04 rcpgenerator.cc
-rw-r--r-- 1 werner werner   2791 Feb 23 15:04 rcpgenerator.hh
-rw-r--r-- 1 werner werner   1240 Feb 23 15:04 README
-rw-r--r-- 1 werner werner   1714 Feb 23 15:04 rec-carbon.cc
-rw-r--r-- 1 werner werner   4480 Feb 23 15:04 rec_channel.cc
-rw-r--r-- 1 werner werner   1448 Feb 23 15:04 rec_channel.hh
-rw-r--r-- 1 werner werner  24897 Feb 23 15:04 rec_channel_rec.cc
-rw-r--r-- 1 werner werner   3954 Feb 23 15:04 rec_control.1
-rw-r--r-- 1 werner werner   3311 Feb 23 15:04 rec_control.cc
-rw-r--r-- 1 werner werner   3076 Feb 23 15:04 recpacketcache.cc
-rw-r--r-- 1 werner werner   1981 Feb 23 15:04 recpacketcache.hh
-rw-r--r-- 1 werner werner  13235 Feb 23 15:04 recursor_cache.cc
-rw-r--r-- 1 werner werner   3264 Feb 23 15:04 recursor_cache.hh
-rw-r--r-- 1 werner werner  15581 Feb 23 15:04 reczones.cc
-rw-r--r-- 1 werner werner   2039 Feb 23 15:04 responsestats.cc
-rw-r--r-- 1 werner werner    488 Feb 23 15:04 responsestats.hh
drwxr-xr-x 2 werner werner   4096 Feb 23 15:04 rrd
-rw-r--r-- 1 werner werner   1847 Feb 23 15:04 secpoll-recursor.cc
-rw-r--r-- 1 werner werner    238 Feb 23 15:04 secpoll-recursor.hh
-rw-r--r-- 1 werner werner   3182 Feb 23 15:04 selectmplexer.cc
-rw-r--r-- 1 werner werner   7658 Feb 23 15:04 sillyrecords.cc
-rw-r--r-- 1 werner werner   8808 Feb 23 15:04 sstuff.hh
-rw-r--r-- 1 werner werner  47287 Feb 23 15:04 syncres.cc
-rw-r--r-- 1 werner werner  17742 Feb 23 15:04 syncres.hh
-rw-r--r-- 1 werner werner 582248 Feb 23 18:42 syncres.o
drwxr-xr-x 2 werner werner   4096 Feb 23 15:04 sysdeps
-rw-r--r-- 1 werner werner   9983 Feb 23 15:04 unix_utility.cc
-rw-r--r-- 1 werner werner  21120 Feb 23 18:42 unix_utility.o
-rw-r--r-- 1 werner werner   4678 Feb 23 15:04 utility.hh
-rw-r--r-- 1 werner werner   3299 Feb 23 15:04 version.cc
-rw-r--r-- 1 werner werner    211 Feb 23 18:42 version_generated.h
-rw-r--r-- 1 werner werner   1342 Feb 23 15:04 version.hh
-rw-r--r-- 1 werner werner  11466 Feb 23 15:04 webserver.cc
-rw-r--r-- 1 werner werner   4252 Feb 23 15:04 webserver.hh
-rw-r--r-- 1 werner werner   8368 Feb 23 15:04 ws-api.cc
-rw-r--r-- 1 werner werner   1642 Feb 23 15:04 ws-api.hh
-rw-r--r-- 1 werner werner  21712 Feb 23 15:04 ws-recursor.cc
-rw-r--r-- 1 werner werner   2163 Feb 23 15:04 ws-recursor.hh
-rw-r--r-- 1 werner werner  13177 Feb 23 15:04 zoneparser-tng.cc
-rw-r--r-- 1 werner werner   2185 Feb 23 15:04 zoneparser-tng.hh
--------------

Regards

2015-02-23 19:24 GMT+08:00 Peter van Dijk <notifications@github.com>:

> Can you show ls -al
> /home/werner/pdns-recursor/pdns-recursor-git-rec-3.7.0-153-g55693f8/ext/rapidjson/include
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2272#issuecomment-75525895>.
>



-- 
Hongyi Zhao <hongyi.zhao@gmail.com>
Xinjiang Technical Institute of Physics and Chemistry
Chinese Academy of Sciences
GnuPG DSA: 0xD108493

**Comment by Habbie** [comment]
Hello,

please post this in a gist, or use correct markdown formatting. The output is unreadable via email.

**Comment by Habbie** [comment]
Also, output of dist-recursor is missing, can you add it?

**Comment by hongyi-zhao** [comment]
Finally, I tried the following steps, and comipled it successfully:

1- Install the depended packages involved:

sudo apt-get install build-essential asciidoc xmlto zip pandoc libboost-dev
subversion libboost-all-dev bison flex ragel pkg-config libtolua++5.1-dev

2- Do the following operations step-by-step:

$ git clone https://github.com/PowerDNS/pdns.git pdns.git
werner@debian:~/pdns-recursor/pdns.git$ git pull
werner@debian:~/pdns-recursor/pdns.git$ git reset --hard
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./bootstrap
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./configure
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./dist-recursor
werner@debian:~/pdns-recursor/pdns.git/pdns$ cd
pdns-recursor-git-rec-3.7.0-155-gc9726b1/
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$

werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$
./configure
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$
make
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$
sudo make install

3- See the following info:

werner@debian:~/pdns-recursor/pdns.git$ sudo pdns_recursor
Feb 23 21:21:07 Unable to parse configuration file
'/etc/powerdns/recursor.conf'
Feb 23 21:21:07 PowerDNS Recursor git-rec-3.7.0-155-gc9726b1
(werner@debian.Home) (C) 2001-2015 PowerDNS.COM BV
Feb 23 21:21:07 Using 64-bits mode. Built on 20150223204407 by
werner@debian.Home, gcc 4.7.2.
Feb 23 21:21:07 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it according to the terms of
the GPL version 2.
Feb 23 21:21:07 Reading random entropy from '/dev/urandom'
Feb 23 21:21:07 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8,
100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128,
fc00::/7, fe80::/10
Feb 23 21:21:07 Will not send queries to: 127.0.0.0/8, 10.0.0.0/8,
100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128,
fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24,
203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32,
0.0.0.0, ::
Feb 23 21:21:07 PowerDNS Recursor itself will distribute queries over
threads
Feb 23 21:21:07 If using IPv6, please raise sysctl net.ipv6.route.max_size,
currently set to 4096 which is < 16384
Feb 23 21:21:07 NOT using IPv6 for outgoing queries - set
'query-local-address6=::' to enable
Feb 23 21:21:07 Inserting rfc 1918 private space zones
Feb 23 21:21:07 Exception: Resolver binding to server socket on port 53 for
127.0.0.1: Address already in use

werner@debian:~/pdns-recursor/pdns.git$ sudo rec_control
syntax: rec_control [options] command, options as below:

  --config-dir=...
    Location of configuration directory (recursor.conf)
  --config-name=...
    Name of this virtual configuration - will rename the binary image
  --help
    Provide this helpful message
  --process=...
    When controlling multiple recursors, the target process number
  --socket-dir=...
    Where the controlsocket will live
  --timeout=...
    Number of seconds to wait for the recursor to respond


As you can see, I just have not configed it any more.  But from these
informations, it hints that its compile and installed successfully ;-)

So, I think the original issues I posted here in this thread should be
something ralated to lacking of depended packages.

Regards

2015-02-23 20:25 GMT+08:00 Peter van Dijk <notifications@github.com>:

> Also, output of dist-recursor is missing, can you add it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2272#issuecomment-75532730>.
>



-- 
Hongyi Zhao <hongyi.zhao@gmail.com>
Xinjiang Technical Institute of Physics and Chemistry
Chinese Academy of Sciences
GnuPG DSA: 0xD108493

**Comment by hongyi-zhao** [comment]
Finally, I tried the following steps, and comipled it successfully:

1- Install the depended packages involved:

sudo apt-get install build-essential asciidoc xmlto zip pandoc libboost-dev subversion libboost-all-dev bison flex ragel pkg-config libtolua++5.1-dev

2- Do the following operations step-by-step:

$ git clone https://github.com/PowerDNS/pdns.git pdns.git
werner@debian:~/pdns-recursor/pdns.git$ git pull
werner@debian:~/pdns-recursor/pdns.git$ git reset --hard
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./bootstrap
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./configure
werner@debian:~/pdns-recursor/pdns.git/pdns$ ./dist-recursor
werner@debian:~/pdns-recursor/pdns.git/pdns$ cd pdns-recursor-git-rec-3.7.0-155-gc9726b1/
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$ ./configure
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$ make
werner@debian:~/pdns-recursor/pdns.git/pdns/pdns-recursor-git-rec-3.7.0-155-gc9726b1$ sudo make install

3- See the following info:

werner@debian:~/pdns-recursor/pdns.git$ sudo pdns_recursor
Feb 23 21:21:07 Unable to parse configuration file '/etc/powerdns/recursor.conf'
Feb 23 21:21:07 PowerDNS Recursor git-rec-3.7.0-155-gc9726b1 (werner@debian.Home) (C) 2001-2015 PowerDNS.COM BV
Feb 23 21:21:07 Using 64-bits mode. Built on 20150223204407 by werner@debian.Home, gcc 4.7.2.
Feb 23 21:21:07 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Feb 23 21:21:07 Reading random entropy from '/dev/urandom'
Feb 23 21:21:07 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
Feb 23 21:21:07 Will not send queries to: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
Feb 23 21:21:07 PowerDNS Recursor itself will distribute queries over threads
Feb 23 21:21:07 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Feb 23 21:21:07 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Feb 23 21:21:07 Inserting rfc 1918 private space zones
Feb 23 21:21:07 Exception: Resolver binding to server socket on port 53 for 127.0.0.1: Address already in use

werner@debian:~/pdns-recursor/pdns.git$ sudo rec_control
syntax: rec_control [options] command, options as below:

  --config-dir=...
    Location of configuration directory (recursor.conf)
  --config-name=...
    Name of this virtual configuration - will rename the binary image
  --help
    Provide this helpful message
  --process=...
    When controlling multiple recursors, the target process number
  --socket-dir=...
    Where the controlsocket will live
  --timeout=...
    Number of seconds to wait for the recursor to respond


As you can see, I just have not configed it any more.  But from these informations, it hints that its compile and installed successfully ;-)

So, I think the original issues I posted here in this thread should be something ralated to lacking of depended packages.

Regards

**Comment by Habbie** [comment]
Ok, thank you for letting us know! Glad this got resolved.
