### ISSUE TITLE
  recursor does not forward correctly with any-to-tcp=yes?

### ISSUE THREAD

**Issue by hongyi-zhao** [PowerDNS/pdns#2275]
Hi all,

I compiled the PowerDNS Recursor git-rec-3.7.0-155-gc9726b1, and use it for some tests with the following settings, while leaving all the other settings commented out as they are:

-------------
```
any-to-tcp=yes
daemon=no
 forward-zones-file=/home/werner/forward2.conf
 local-address=127.0.0.1:1053
 trace=on
```
---------------

The content of the file /home/werner/forward2.conf is as follows (only one line in it):

```
+.=8.8.8.8,8.8.4.4
```

Then I start the pdns_recursor with the following command:
```
$ sudo pdns_recursor
```

and do the following testings:

1- Send the tcp dns query to 8.8.8.8 for youtube.com:

```
werner@debian:~$ dig +tcp youtube.com @8.8.8.8
;; communications error to 8.8.8.8#53: connection reset
```

I'm from china.  You can see that the gfw resets the query and I cann't get any results.

2- Let the pdns_recursor query 8.8.8.8 for the youtube.com with my above settings used in recursor.conf:

----------------
```
werner@debian:~$ dig -p1053 youtube.com

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> -p1053 youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59947
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;youtube.com.			IN	A

;; ANSWER SECTION:
youtube.com.		2330	IN	A	216.70.104.88

;; Query time: 46 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Tue Feb 24 12:40:15 2015
;; MSG SIZE  rcvd: 45
```
-----------------

As you can see, this time I obtain a answer: 216.70.104.88, which is not correct and not agree with the results obtained by query the 8.8.8.8 directly, i.e., resetted by firewall, given nothing to me.

In my mind, with the any-to-tcp=yes option setted in the recursor.conf, we should obtain the same result as we query the nameserver with `dig +tcp'.

For your information, I give some of the trace information of pdns_recursor here:

-------------
```
Feb 24 12:40:15 2 [1/1] question for 'youtube.com.|A' from 127.0.0.1
Feb 24 12:40:15 [1] youtube.com.: Looking for CNAME cache hit of 'youtube.com.|CNAME'
Feb 24 12:40:15 [1] youtube.com.: No CNAME cache hit of 'youtube.com.|CNAME' found
Feb 24 12:40:15 [1] youtube.com.: No cache hit for 'youtube.com.|A', trying to find an appropriate NS record
Feb 24 12:40:15 [1] youtube.com.: Cache consultations done, have 2 NS to contact
Feb 24 12:40:15 [1] youtube.com.: Nameservers: +8.8.8.8:53(0.00ms), +8.8.4.4:53(112.71ms)
Feb 24 12:40:15 [1] youtube.com.: Trying to resolve NS '+8.8.8.8:53' (1/2)
Feb 24 12:40:15 [1] youtube.com.: Domain has hardcoded nameserver(s)
Feb 24 12:40:15 [1] youtube.com.: Resolved '.' NS +8.8.8.8:53 to: 8.8.8.8
Feb 24 12:40:15 [1] youtube.com.: Trying IP 8.8.8.8:53, asking 'youtube.com.|A'
Feb 24 12:40:15 [1] youtube.com.: Got 1 answers from +8.8.8.8:53 (8.8.8.8), rcode=0 (No Error), aa=0, in 45ms
Feb 24 12:40:15 [1] youtube.com.: accept answer 'youtube.com.|A|216.70.104.88' from '.' nameservers? YES!
Feb 24 12:40:15 [1] youtube.com.: determining status after receiving this packet
Feb 24 12:40:15 [1] youtube.com.: answer is in: resolved to '216.70.104.88|A'
Feb 24 12:40:15 [1] youtube.com.: status=got results, this level of recursion done
Feb 24 12:40:15 2 [1/1] answer to question 'youtube.com.|A': 1 answers, 0 additional, took 1 packets, 45.458 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
```
-------------
 
Why does this happen?

Could you please give me some hints?

Regards

**Comment by Habbie** [comment]
Hello,

1. please try formatting your issues correctly using github Markdown (I have now edited yours for 
readability)
2. `any-to-tcp` means queries from clients that ask for `ANY` will get redirected to `TCP`. It has no influence on the outgoing transport of the Recursor
3. I don't understand what problem you are trying to solve - you want the Recursor to also get the 'connection reset'? What good would that do?

**Comment by hongyi-zhao** [comment]
1. Thanks for this hints.  I haven't known that thing -- Markdown -- till these days.  I've taken a look on it grammer and will try it ;-)
2. Thanks for your explanation on the function of any-to-tcp.  It is I that misunderstanded it.  I just think that with this switch set to yes, the recursor will use to tcp to query the upstream dns servers, i.e., the forwarders.
3. I just want to obtain the result using tcp as query method  to connecting from the recursor  to the remote dns server.  Just as the things done by using the +tcp switch of dig or the  "tcp-upstream: yes" used in the unbound.
Does this possible by using pdns_recursor?

Regards

**Comment by Habbie** [comment]
3. Sorry, this is not currently a feature we have. Please always feel free to file a feature request, but do keep in mind that "I just want to" is a bad motivator.

Closing this ticket.
