### ISSUE TITLE
Limit number of crypto libraries

### ISSUE THREAD

**Issue by darix** [PowerDNS/pdns#2342]
When building all the tools and daemons currently coming from the powerdns project, you can or have to use _4_ crypto libraries by now.

Supporting multiple crypto libraries is fine. Requiring them at the same time, is something that should be reconsidered.

* cryptopp
* botan
* polarssl
* libsodium

**Comment by ahupowerdns** [comment]
we require exactly zero of these system wide, and we have no in-tree AES implementation left.

Feel free to pick which libraries, which could be zero, you want to support.

**Comment by darix** [comment]
We don't have to start the whole discussion about intree libraries again. Those just mask the problem but not resolve it. And the intree AES isn't gone that long. But I will happily remove it from the list.

**Comment by ahupowerdns** [comment]
please state the problem you have. If the problem is that we have lots of flexibility, we can't solve it for you. If the problem is that we impose a lot of dependencies on you, let us know exactly which ones hurt.

**Comment by darix** [comment]
e.g. for building dnsdist with the last tarball you gave me, i need _2_ crypto libraries to pass the configure script. Habbie mentioned that polarssl there might be a mistake and only libsodium is really required. But what about e.g. pdns auth. Do i only need one out of polarssl/botan/cryptopp or is polarssl always required but i can pick between botan and cryptopp for the rest? Currently i have the impression the later is the case.

As you are in spring cleaning atm, he asked me to have ticket to have this tracked.

**Comment by ahupowerdns** [comment]
darix, the current (from yesterday) tarball requires neither polarssl nor libsodium. Please don't confuse the issue. We need polarssl always in recursor (and we carry our own copy which you can use), and the rest is optional.

**Comment by darix** [comment]
Ruben asked me to clarify:

1. the main reason for this ticket is to review the list maybe libraries have caught up and actually can handle most cases why you needed/supported more than one library in the past.
2. if the evaluation is done. document pros and cons of each library as proposed in #2343.
3. it might be useful to have something like ```pdns{_server,sec} --supported-algos``` to list, which libraries are used and which algorithms are covered by them. especially interesting for doing pdns support on distros with crippled crypto libraries.

If nothing changes in the end and we come out with the documentation, I will be a happy camper too.
