### ISSUE TITLE
MX record no working when I'm using Amazon Elastic loadbalener DNS for domain

### ISSUE THREAD

**Issue by lijumathew** [PowerDNS/pdns#2351]
Hello 

our domain is hosted on Amazon Elastic Loadbalencer and hence we need to set  domain root record  to CNAME value instead of "A" type IP record. So we do not have any 'A' type record to pointing a domain. We are using CNAME record of Amazon ELB DNS to serve our website.  

When I'm adding  new MX record on these hosted domain, it will not work even though I can updated the values over PowerDNS  web ui without any errors showing. When I nag the mx record entry it allways showing the domain  DNS. Not any mx records

[root@rc-025 ~]# host -t mx test.info
test.info is an alias for ORLB-1832sdsdasd.us-west-1.elb.amazonaws.com.
[root@rc-025 ~]#  

Note:  This is ORLB-1832sdsdasd.us-west-1.elb.amazonaws.com. amazon loadbalencer DNS  record name. 

![image](https://cloud.githubusercontent.com/assets/11440320/6638144/bb506b9e-c9a8-11e4-868d-8d04f1d90c18.png)

Can you pls help me how can i activate the email service of the domain which is using Amazon loadbalencer DNS recod managed in PowerDNS software ? Is there any other technique ? 
Because i'm hosting few domains in powerdns server and I need to make activate the email service  asap.

Pls help

Thanks
Liju

**Comment by Habbie** [comment]
Hello Liju,

putting a CNAME on your apex (which you call the 'root') is not possible in DNS. You need to ask Amazon how to deal with this situation.

Closing ticket.

**Comment by lijumathew** [comment]
Hi Habbie

I can able to see the sites are working fine if i putting CNAME on my apex (root )record. So this is working. Subdomains are also working using powerdns. The only issue is neither MX record nor TXT record does not work once I put CNAME on domain apex. 

Do you have any work around ?

Thank you for your speedy response.

Thanks
Liju

**Comment by Habbie** [comment]
Hello Liju,

no, I do not have a workaround, and your configuration is invalid. While it may appear to work now, this is pure luck and it could break any time. I have asked another Amazon user to see if he has any thoughts; but you really should take this up with Amazon yourself.

**Comment by Habbie** [comment]
One more thing - in our git master branch we do have ALIAS support but it's mostly untested. If you feel like experimenting, give it a shot.

**Comment by lijumathew** [comment]
Hi Habbie

Thank you for the reply. 

Really I need to workout  this plan as I have many domains which currently using this CNAME apex and working correctly as of now.  Do you add  this features in next version  ? I'm using poweradmin v 2.1.6  verion now.

Thanks
Liju

**Comment by Habbie** [comment]
Hello,

this feature may come in a future release, but this will not be very soon.

**Comment by lijumathew** [comment]
Thank you Habbie

I'm eagerly waiting for that since we have more than 250 happy customers are using your service now.

Thanks
Liju
