### ISSUE TITLE
dnsdist startup error

### ISSUE THREAD

**Issue by debiansid** [PowerDNS/pdns#2356]
Fatal error: Exception thrown by a callback function called by Lua
just use the default configuration.

any idea?

**Comment by ahupowerdns** [comment]
Can you try again against latest tarball or git? There may have been a
mismatch between our shipped dnsdistconf.lua and dnsdist itself. It works
here now.

**Comment by Habbie** [comment]
dnsdist is a moving target, this ticket is 6 weeks old. closing.
