### ISSUE TITLE
CNAME's to long AWS names don't resolve in pdns 3.4.x

### ISSUE THREAD

**Issue by ibridge-pdns** [PowerDNS/pdns#2372]
I see a strange issue with CNAME's to long AWS names.
The CNAME's show up in a zone transfers but don't resolve with dig.

our setup is:
in AWS we use the following RPM's:
pdns-3.4.1-1.el6.MIND.x86_64
pdns-recursor-3.7.1-1.el6.x86_64
pdns-backend-mysql-3.4.1-1.el6.MIND.x86_64
the backend is mysql.
I am running on Amazon Linux AMI release 2014.09 (~ centos 6)
the RPM's are dowloaded from https://www.monshouwer.eu/download/3rd_party/pdns/el6/x86_64/

I succesfully reproduced the issue with 
pdns-3.4.3-1.el6.MIND.x86_64.rpm  
pdns-backend-mysql-3.4.3-1.el6.MIND.x86_64.rpm

The issue in details:
with a zone transfer I have:
robert.ton.rsg.         300     IN      CNAME   awseb-e-j-awsebloa-m5n3za8f47rv-36455982.eu-west-1.elb.amazonaws.com.
```
dig robert.ton.rsg a 
; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.36.amzn1 <<>> @10.214.0.11 robert.ton.rsg a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45607
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;robert.ton.rsg.                        IN      A

;; AUTHORITY SECTION:
.                       2517    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2015032300 1800 900 604800 86400

;; Query time: 9 msec
;; SERVER: 10.214.0.11#53(10.214.0.11)
;; WHEN: Mon Mar 23 09:43:23 2015
;; MSG SIZE  rcvd: 107
```

other CNAME's work fine
```
; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.36.amzn1 <<>> @10.214.0.11 robert2.ton.rsg a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64108
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;robert2.ton.rsg.               IN      A

;; ANSWER SECTION:
robert2.ton.rsg.        300     IN      CNAME   dnsprdapp03.man.rsg.
dnsprdapp03.man.rsg.    3600    IN      A       10.214.8.11

;; Query time: 7 msec
;; SERVER: 10.214.0.11#53(10.214.0.11)
;; WHEN: Mon Mar 23 09:43:17 2015
;; MSG SIZE  rcvd: 79
```

**Comment by ibridge-pdns** [comment]
Sorry I forgot to mention, that we are not using DNSSEC

**Comment by ahupowerdns** [comment]
Can you make the amazon CNAME shorter and see if it starts working? I wonder if only the length is the problem. If you make it shorter, Amazon won't have the name of course, but at some point you should start getting answers from them. Can you run pdnssec check-zone on your zone?

**Comment by ibridge-pdns** [comment]
I can see it is the same issue as #2312
Shorten the name doesn't help, resolving cnames which points to not AUTH zones just does't work.

**Comment by ahupowerdns** [comment]
try dig +norecurs and see what changes please.

**Comment by ibridge-pdns** [comment]
dig +norecurs works fine, just as it should.
Is there a version in which this is resolved? Or is it a bug in dig?

**Comment by ibridge-pdns** [comment]
Is there a workaround how to make a cname to a domain for which we are not auth

**Comment by cmouse** [comment]
@ibridge-pdns can you show us the data in question, single row from database is sufficient at this point. I tried replicating your issue with latest master, but was not able to. I added row:

```
| id | domain_id | name                                     | type    | content                                                                                                                                                                                                                                            | ttl  | prio | change_date | ordername | auth | disabled |
| 97 |         5 | test.cmouse.fi                           | CNAME   | awseb-e-j-awsebloa-m5n3za8f47rv-36455982.eu-west-1.elb.amazonaws.com                                                                                                                                                                               |  300 | NULL |        NULL | NULL      | NULL |        0 |
```

to my test database and was able to resolve it.

If you can provide more details on your setup it would help a lot.

**Comment by ibridge-pdns** [comment]
Hi Ari.
the record is
mysql> select * from records where name='pushdserver.ton.rsg';
+------+-----------+---------------------+-------+-------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| id   | domain_id | name                | type  | content
                                                | ttl  | prio | change_date
| disabled | ordername | auth |
+------+-----------+---------------------+-------+-------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
| 4467 |        15 | pushdserver.ton.rsg | CNAME |
awseb-e-j-AWSEBLoa-172FKP7KS1G9B-1125328689.eu-west-1.elb.amazonaws.com |
 300 |    0 |        NULL |        0 | NULL      |    1 |
+------+-----------+---------------------+-------+-------------------------------------------------------------------------+------+------+-------------+----------+-----------+------+
1 row in set (0.00 sec)

as far as I can see the difference is in the auth field.
We are authoratative for the zone ton.rsg, not for amazon.com

kind regards,
Robert


Met vriendelijke groet,

*Robert de Nijs*
Senior ICT Specialist

*Randstad Groep Nederland bv*
Diemermere 25, 1112 TC Diemen
P.O. Box 12600, NL-1100 AP Amsterdam
T +31 (0)20 569 56 82

robert.de.nijs@randstadgroep.nl <//robert.de.nijs@randstadgroep.nl>

www.tempo-team.nl
www.yacht.nl
www.randstad.nl



On Mon, Apr 27, 2015 at 11:35 AM, Aki Tuomi <notifications@github.com>
wrote:

> @ibridge-pdns <https://github.com/ibridge-pdns> can you show us the data
> in question, single row from database is sufficient at this point. I tried
> replicating your issue with latest master, but was not able to. I added row:
>
> | id | domain_id | name                                     | type    | content                                                                                                                                                                                                                                            | ttl  | prio | change_date | ordername | auth | disabled |
> | 97 |         5 | test.cmouse.fi                           | CNAME   | awseb-e-j-awsebloa-m5n3za8f47rv-36455982.eu-west-1.elb.amazonaws.com                                                                                                                                                                               |  300 | NULL |        NULL | NULL      | NULL |        0 |
>
> to my test database and was able to resolve it.
>
> If you can provide more details on your setup it would help a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-96584347>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by cmouse** [comment]
Can you run pdnssec check-zone ton.rsg

Despite the name, it does not require DNSSEC.

**Comment by cmouse** [comment]
Also, it appears your DNS server thinks it's authoritative for root zone. This will break resolution of any non-local names.

**Comment by ibridge-pdns** [comment]
Hi Ari,

pdnssec -v check-zone ton.rsg retruns:
Checked 13 records of 'ton.rsg', 0 errors, 0 warnings.


​kind regards,

​Robert


On Tue, Apr 28, 2015 at 2:49 PM, Aki Tuomi <notifications@github.com> wrote:

> Can you run pdnssec check-zone ton.rsg
>
> Despite the name, it does not require DNSSEC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97050837>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by Habbie** [comment]
The machine at 10.214.0.11 you are querying - what is listening on port 53 on that IP? Is it pdns or pdns-recursor?

**Comment by ibridge-pdns** [comment]
Hi Ari,
a dig @127.0.0.1 . ns  at my dns server returns the root dns servers......
The dns server is also corfigured as pdns-recursor on a different port
(5300)
I personally believe the issue is in the pdns-recursor 3.7.1

​kind regards,

Robert


On Tue, Apr 28, 2015 at 2:50 PM, Aki Tuomi <notifications@github.com> wrote:

> Also, it appears your DNS server thinks it's authoritative for root zone.
> This will break resolution of any non-local names.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97051185>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by ibridge-pdns** [comment]
Hi Pieter
on port 53 pdns is listening
pdns-recursor is listening on 127.0.0.1:5300

​kind regards,
Robert​


On Tue, Apr 28, 2015 at 2:57 PM, Peter van Dijk <notifications@github.com>
wrote:

> The machine at 10.214.0.11 you are querying - what is listening on port 53
> on that IP? Is it pdns or pdns-recursor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97052330>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by cmouse** [comment]
You should setup this so that recursor listens on port 53, and auth listens on port 5300. You can then add forward-zones or forward-zones-recurse=rsg=127.0.0.1:5300.

Also remove the root zone from your auth server.

**Comment by ibridge-pdns** [comment]
Hi Ari,
It took me a while to set it up and you are right: it solves my problem of
querying long aws names.
But it also intodruces new issues:
As  ton.rsg is used for ddns pdns-recursor is caching ton.rsg records. This
is not desirable after ddns updates.
A zone transfer dig @127.0.0.1 ton.rsg axfr doesn't work.

​kind regards,


*Robert de Nijs*
Senior ICT Specialist

*Randstad Groep Nederland bv*
Diemermere 25, 1112 TC Diemen
P.O. Box 12600, NL-1100 AP Amsterdam
T +31 (0)20 569 56 82

robert.de.nijs@randstadgroep.nl <//robert.de.nijs@randstadgroep.nl>

www.tempo-team.nl
www.yacht.nl
www.randstad.nl



On Tue, Apr 28, 2015 at 3:05 PM, Aki Tuomi <notifications@github.com> wrote:

> You should setup this so that recursor listens on port 53, and auth
> listens on port 5300. You can then add forward-zones or
> forward-zones-recurse=rsg=127.0.0.1:5300.
>
> Also remove the root zone from your auth server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97054145>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by cmouse** [comment]
if you are running your auth server in port 5300, you need to use
dig -p5300 axfr zonename @localhost

To remediate caching, you can use low ttl, or consider getting another IP address for the AUTH server so that you don't have to keep the recursor in front of it.

**Comment by ibridge-pdns** [comment]
Hi Ari,
I am getting your point. Yes separate recursion and authoritative DNS would
indeed solve the (long) cname issue.

But this would shift complexity to the DNS clients, they would have to know
for which DNS action which DNS server to use.
Even a relative short TTL would create outages.

What I am trying to achive id:
to run windows servers in AWS (amazon) those server are using DDNS to
register themselves to DNS on a private DNS domain.
They are also using those DNS servers for resolving.
Within AWS we are also using Linux servers in the same private DNS domain
which are using the same DNS servers for resolving.

So I am looking for an authoritative DNS server capable to do DDNS and
recursion.
PDNS with pdns-recursor is just doing that with the exception of resolving
cnames to external domains.

​kind regards,

Robert​

On Tue, Apr 28, 2015 at 5:53 PM, Aki Tuomi <notifications@github.com> wrote:

> if you are running your auth server in port 5300, you need to use
> dig -p5300 axfr zonename @localhost <https://github.com/localhost>
>
> To remediate caching, you can use low ttl, or consider getting another IP
> address for the AUTH server so that you don't have to keep the recursor in
> front of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97114441>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by cmouse** [comment]
Actually it can do that as well, but you had configured '.' zone to your auth claiming authority over all DNS names. There can other issues though if you put your recursor behind auth, but you can try again, just make sure you do not claim authority over '.' zone.

**Comment by Habbie** [comment]
With recursor behind auth, even without the '.' zone, these CNAMEs to external will not work.

**Comment by ibridge-pdns** [comment]
dig +norecurse will work in that setup


Met vriendelijke groet,

*Robert de Nijs*
Senior ICT Specialist

*Randstad Groep Nederland bv*
Diemermere 25, 1112 TC Diemen
P.O. Box 12600, NL-1100 AP Amsterdam
T +31 (0)20 569 56 82

robert.de.nijs@randstadgroep.nl <//robert.de.nijs@randstadgroep.nl>

www.tempo-team.nl
www.yacht.nl
www.randstad.nl



On Wed, Apr 29, 2015 at 3:00 PM, Peter van Dijk <notifications@github.com>
wrote:

> With recursor behind auth, even without the '.' zone, these CNAMEs to
> external will not work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-97419161>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.

**Comment by Habbie** [comment]
I just re-read this whole thread and I cannot find an actual powerdns issue. Closing this ticket.

If I missed something, please let me know.

**Comment by ibridge-pdns** [comment]
Thank you for your feedback.
I am not happy with your answer. We are running powerdns in Amazon because
Amazon doesn't support DDNS

In my opinion when you are running Powerdns in a DDNS setup it is logical
to use the same pdns servers for resolving.
Thus you want to run a pdns-recusor on a different port than 53 and use
that to resolve everything beside your own domains.
In this setup CNAMES to non authoratative domains fail. If there is no
misconfiguration then it must be a bug.
(We are running pdns 3.4.6 and recursor 3.7.3)


kind regards,
Robert de Nijs


On Mon, Sep 28, 2015 at 5:30 PM, Peter van Dijk <notifications@github.com>
wrote:

> I just re-read this whole thread and I cannot find an actual powerdns
> issue. Closing this ticket.
>
> If I missed something, please let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2372#issuecomment-143778832>.
>

-- 
The information contained in this e-mail communication is solely intended 
for the person/legal person to whom it has been sent, and as it may contain 
information of a personal or confidential nature, it may not be made public 
by virtue of law, regulations or agreement. If someone other than the 
intended recipient should receive or come into possession of this e-mail 
communication, he/she will not be entitled to read, disseminate, disclose 
or duplicate it. If you are not the intended recipient, you are requested 
to inform the sender of this e-mail message of this immediately, and to 
destroy the original e-mail communication. Neither Randstad Holding nv nor 
its subsidiaries accept any liability for incorrect and incomplete 
transmission or delayed receipt of this e-mail.
