### ISSUE TITLE
Make path variables configurable during build

### ISSUE THREAD

**Issue by jemshad** [PowerDNS/pdns#2373]
Currently, the following variables are hard coded in the Makefile.in. 

LOCALSTATEDIR
SYSCONFDIR
SBINDIR
BINDIR

Would be good to have this configurable as command line parameters during configure step.

**Comment by cmouse** [comment]
Those are configured by ./configure, you can pass --sysconfdir=/something.

**Comment by Habbie** [comment]
For recursor?

On 23 March 2015 15:01:19 CET, Aki Tuomi <notifications@github.com> wrote:
>Those are configured by ./configure, you can pass
>--sysconfdir=/something. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/2373#issuecomment-85010016

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by jemshad** [comment]
Don't think passing on command line works.

./configure --sysconfdir=/opt/conf/powerdns --sbindir=/opt/sbin --bindir=/opt/bin         
Testing dependencies and compiler.
Using make to build
g++  -Iext/rapidjson/include -I/home/jemshad/Downloads/pdns-recursor-3.7.1/ext/polarssl/include -Wall -fPIE -DPIE -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' -MM -MG *.cc *.hh > dep
g++  -Iext/rapidjson/include -I/home/jemshad/Downloads/pdns-recursor-3.7.1/ext/polarssl/include -Wall -fPIE -DPIE -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' pdns_hw.cc -o pdns_hw

**Comment by cmouse** [comment]
Yeah didn't notice you ment recursor. Happily it is not very difficult to fix.

**Comment by cmouse** [comment]
@jemshad can you test this please?

**Comment by jemshad** [comment]
I think you need one more change to make it happen.

82c82
<  arg=${keyval%=*}
---
>  arg=${keyval%=*}; arg=$(echo ${arg#--} | tr '[:lower:]' '[:upper:]')

would do it, I believe.

**Comment by jemshad** [comment]
Here is the change required to make it work, I believe.

82c82
<  arg=${keyval%=*}
---
>  arg=${keyval%=*}; arg=$(echo ${arg#--} | tr '[:lower:]' '[:upper:]')

Jemshad

On Tue, Mar 24, 2015 at 1:19 AM, Aki Tuomi <notifications@github.com> wrote:

> @jemshad <https://github.com/jemshad> can you test this please?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerDNS/pdns/issues/2373#issuecomment-85166469>.
>



-- 

"I know Karate, Kung-Fu and 47 other dangerous words!"

**
            \|||/
            (o

o




)
*+**~~~~~~~~~~~~*(_)

*~~*

Ooo*~~+*

|

Jemshad O K          |
|

Ph: +91-98452-53832 * |*
+*~~~~~~~*

Ooo*~~~~~~~~~~~~*+
           |__|__|
            || ||
           ooO Ooo

-- 
_____________________________________________________________
The information contained in this communication is intended solely for the 
use of the individual or entity to whom it is addressed and others 
authorized to receive it. It may contain confidential or legally privileged 
information. If you are not the intended recipient you are hereby notified 
that any disclosure, copying, distribution or taking any action in reliance 
on the contents of this information is strictly prohibited and may be 
unlawful. If you have received this communication in error, please notify 
us immediately by responding to this email and then delete it from your 
system. The firm is neither liable for the proper and complete transmission 
of the information contained in this communication nor for any delay in its 
receipt.

**Comment by cmouse** [comment]
ah i wasn't trying to replicate autotools here

**Comment by cmouse** [comment]
@jemshad not sure if you read the patch correctly. The correct usage is

```
./configure LOCALSTATEDIR=/path/to/foo SYSCONFDIR=/path/to/foo
make  LOCALSTATEDIR=/path/to/foo SYSCONFDIR=/path/to/foo
```

as it replicates how it's intended to be used in the first place.

**Comment by jemshad** [comment]
ah ok, my bad. As the usual convention is to provide the prefix and other arguments in lower case, I was trying to replicate the same behavior here.

**Comment by cmouse** [comment]
@jemshad no worries, it's complicated.

**Comment by ahupowerdns** [comment]
recursor moved to real autoconf, and I checked, this works now.
