### ISSUE TITLE
SOA-EDIT-API INCEPTION-INCREMENT increments serial by 2 on every update

### ISSUE THREAD

**Issue by sid3windr** [PowerDNS/pdns#2377]
PowerDNS Auth 3.4.3

We configured NSEdit and set our domains to INCEPTION-INCREMENT.

Docs say: "Uses YYYYMMDDSS format for SOA serial numbers. If the SOA serial from the backend is within two days after inception, it gets incremented by two (the backend should keep SS below 98)."

However, our current serial is 2015031970, when updating PowerDNS sets it to 2015031972.

**Comment by zeha** [comment]
I've reproduced this (on 3.4.x), but don't understand the why parts of this yet.

**Comment by jpmens** [comment]
FWIW, SOA serial increments correctly by one upon 2136 updates on zone configured with `SOA-EDIT-DNSUPDATE=INCEPTION-INCREMENT`
