### ISSUE TITLE
Is it possiable to wipe cache by using regexp/wildcard for mathing multiple domains?

### ISSUE THREAD

**Issue by hongyi-zhao** [PowerDNS/pdns#2390]
Hi all,

I want to use rec_control to wipe some entries from its cache.  But according to the manual of  rec_control the command is described as follows:

wipe-cache DOMAIN [DOMAIN] [...]

If I want to wipe serveral DOMAINs from cache with one running of  rec_control command, I must write all of these DOMAINs with the space separed entries, i.e., like this:

sudo rec_control wipe-cache youtube.com yahoo.com google.com ...

So, I want to know  whether it is possiable to wipe cache by using regexp/wildcard for mathing multiple domains?

Regards

**Comment by ahupowerdns** [comment]
No this is not possible right now as it requires a full scan of the cache,
which takes too long (it is a locked operation). Sorry!

**Comment by shinsterneck** [comment]
Maybe something like this will help you, but like mentioned above it may not be something you want to do on a very large cache ...

1. dump the cache to file
2. run regex filter over file and get your domains filtered out
3. run wipe-cache with list of filtered domains...

below a one liner to get you started (this will list the domains found through via regex):

(export REGEX="^example\.com\.$"; export DFN=`mktemp -u`; /usr/bin/rec_control dump-cache $DFN > /dev/null ; cut -d' ' -f1 $DFN | sort | uniq | grep -e "$REGEX")

and this will do the same, except also pass the domains list on to rec_control wipe-cache:

(export REGEX="^example\.com\.$"; export DFN=`mktemp -u`; /usr/bin/rec_control dump-cache $DFN > /dev/null ; cut -d' ' -f1 $DFN | sort | uniq | grep -e "$REGEX") | xargs /usr/bin/rec_control wipe-cache

Regards,
Shin

**Comment by hongyi-zhao** [comment]
Thanks for your hints.

Regards

**Comment by Habbie** [comment]
This is unlikely to happen soon. Closing ticket.
