### ISSUE TITLE
check-zone should warn if zone name is too long for NSEC3

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2402]
_pdnssec_'s `check-zone` should check if a zone name is so long that no NSEC3 can fit in it > 255. Similarly, `set-nsec3` should refuse to do so if that would be the case.

**Comment by jpmens** [comment]
Full story of how this came about [is here](https://issues.opendnssec.org/browse/SUPPORT-159)

**Comment by Habbie** [comment]
5155 10.1 also mentions this
