### ISSUE TITLE
Bind backend does not read ALSO-NOTIFY from SQLite

### ISSUE THREAD

**Issue by denschub** [PowerDNS/pdns#2421]
The bind backend does not read ALSO-NOTIFY settings from SQLite on DNSSEC secured zones, which could result in out-of-sync zones

**Comment by Habbie** [comment]
This is because (a) `alsoNotifies` in `DNSBackend` is an empty virtual (b) `alsoNotifies` in `bindbackend.cc` only picks up the stuff from `named.conf`

**Comment by mnordhoff** [comment]
Fixed in #7989?

**Comment by zeha** [comment]
> Fixed in #7989?

Yup.
