### ISSUE TITLE
Feature request: don't use /dev/urandom as entropy source

### ISSUE THREAD

**Issue by paultheweird** [PowerDNS/pdns#2423]
While starting PowerDNS 3.4.3 on OpenBSD (preview port, not in ports tree yet), I see the following in the logs:

```
[weerd@pom] $ pdns_server
Apr 10 18:15:36 Reading random entropy from '/dev/urandom'
```

Opening files in `/dev/` can be problematic in chroot environments or in fd-exhausted scenarios. Better to use the `arc4random` family of functions to get random data (see http://www.openbsd.org/cgi-bin/man.cgi?query=arc4random for details). This could be implemented either via the portable code present in LibreSSL (available under a very liberal license) or simply on systems that support it via autoconf.

Thanks!

**Comment by rubenk** [comment]
Atlhough I'd love to use this, it seems it's not that portable yet.
LibreSSL currently turns it of for freebsd, netbsd and darwin: https://github.com/libressl-portable/portable/blob/master/configure.ac#L256

**Comment by omoerbeek** [comment]
With the new dns_random (upcoming), this is mostly solved. There are a few places were random() is used, mostly in utilities. Those are not harmful and require a bit more work to eliminate, because using dns_random() there introduces dependencies on libsodium and or libcrypto.
