### ISSUE TITLE
Auth API: HTTP 500 on list zones

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2434]
PowerDNS authoritative, version 3.4.2 (autotest) with a MySQL back-end only reports HTTP code 500 for

```bash
curl -XGET -H 'X-API-Key: xxx' http://192.168.17.82:8071/servers/localhost/zones
```

```
Apr 20 09:21:54 m1 pdns[12558]: HTTP: Handling request "/servers/localhost/zones"
Apr 20 09:21:54 m1 pdns[12558]: gmysql Connection successful. Connected to database 'pdns' on '10.24.34.11'.
Apr 20 09:21:54 m1 pdns[12558]: gmysql Connection successful. Connected to database 'pdns' on '10.24.34.11'.
Apr 20 09:21:54 m1 pdns[12558]: HTTP ISE for "/servers/localhost/zones": STL Exception: basic_string::substr
Apr 20 09:21:54 m1 pdns[12558]: HTTP: Error result for "/servers/localhost/zones": 500
```

Performing a `GET` on a single zone works.

**Comment by zeha** [comment]
Please produce a dump of your domains table and all SOA records for those domains.

**Comment by jpmens** [comment]
Occurs on `pdns-static-3.4.4snapshot20150414_5680_cb2753a-1` as well.

**Comment by jpmens** [comment]
Culprit is the following zone:

```
SELECT name, LENGTH(name), type FROM domains WHERE id = 14;
+------+--------------+--------+
| name | LENGTH(name) | type   |
+------+--------------+--------+
|      |            0 | MASTER |
+------+--------------+--------+
```

Deleting that from the database "fixes" the issue, as does this SQL:

```
UPDATE domains SET name = 'bla' WHERE id = 14;
```

**Comment by jpmens** [comment]
I was under the impression this had been "fixed" in https://github.com/PowerDNS/pdns/issues/2216

**Comment by zeha** [comment]
#2216 / #2280 is not part of 3.4.x (yet?)

**Comment by jpmens** [comment]
Something that was merged on March 2nd is not in an autotest RPM built on 20150414? Then /me *definitely* doesn't understand how this works.

**Comment by cmouse** [comment]
is it merged on the auth-3.4.2 branch?

**Comment by jpmens** [comment]
`Habbie merged commit 20feb44 into PowerDNS:master from zeha:api-root-zone on Mar 2`.

Isn't _master_ what autotest builds? Please excuse my ignorance!

**Comment by Habbie** [comment]
autotest builds master and rel/*; in this case, you managed to grab a snapshot off of rel/auth-3.4.4. Now that you know this, it should be easy to find a recent master build.

**Comment by Habbie** [comment]
https://autotest.powerdns.com/job/auth-git/5676/ is the most recent master build

**Comment by jpmens** [comment]
Thank you. I cannot test non-static builds, so I will close this confident that it was fixed.
