### ISSUE TITLE
Blackhole and exclusion support for pdns

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#244]
Adds support for blackholing networks/addresses, this means that all packets from blackholed networks are dropped, and all TCP connections are closed immediately after accept().

This patch also changes behaviour of NetmaskGroup and friends by allowing use of ! to negate match. F.ex. 

blackhole=!127.0.0.1/32,127.0.0.0/8 would allow from localhost, but not from localnet.

**Comment by pieterlexis** [comment]
Is this a nice to have for 4.0?

**Comment by Habbie** [comment]
I have trouble seeing why we should do this instead of iptables

**Comment by pieterlexis** [comment]
closing then :)
