### ISSUE TITLE
[AUTH] Enabling tools installs binaries which shouldn't be installed

### ISSUE THREAD

**Issue by darix** [PowerDNS/pdns#2465]
According to @ahupowerdns  the following tools shouldn't be installed:

- dnsdist
- nsec3dig
- saxfr

**Comment by Habbie** [comment]
What version?

**Comment by mind04** [comment]
I agree on removal of dnsdist (already gone on master), 
But the other tools should stay. saxfr is used for monitoring in some very large installations, for example.

**Comment by darix** [comment]
@Habbie 3.4.4

**Comment by rubenk** [comment]
* calidns?

**Comment by pieterlexis** [comment]
I don't see why these tools shouldn't be installed, PowerDNS was asked for `--with-tools` during configure, I'll add a `install-no-tools` target that won't install the tools but will install everything else.

**Comment by rubenk** [comment]
We have --enable-tools, so by definition --disable-tools or --enable-tools=no should also work, or am I missing something?

**Comment by pieterlexis** [comment]
@rubenk, I'm also currently pondering that.... I'm inclined to close this ticket. If you want tools, you get tools

**Comment by rubenk** [comment]
All I recall is that some of these were internal development tools, and they didn't build on all platforms.

If that's not an issue anymore, yes, close it! :)

**Comment by pieterlexis** [comment]
I think they build everywhere, for calidns we check if we have `recv_mmsg`. Or do you have examples?

**Comment by rubenk** [comment]
No, not at the moment.
