### ISSUE TITLE
VPATH builds broken

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2477]
It is no longer possible to do build directory and build there. Root cause is that during configure C++11 tests we run into LuaContext missing.

```
conftest.cpp:17:56: fatal error: pdns/ext/luawrapper/include/LuaContext.hpp: No such file or directory
   #include "pdns/ext/luawrapper/include/LuaContext.hpp"
```

**Comment by pieterlexis** [comment]
Isn't the c++ 2011 detection broken if we need LUA for it?

**Comment by pieterlexis** [comment]
in `/m4/ax_cxx_compile_stdcxx_11.m4`:

```
m4_define([_AX_CXX_COMPILE_STDCXX_11_testbody], [[                               
 #include <thread>                                                              
 #include "pdns/ext/luawrapper/include/LuaContext.hpp"   
```

**Comment by cmouse** [comment]
it could be argued that it should not depend on lua

**Comment by Habbie** [comment]
It depends on Lua because there was no other suitable test at the time

**Comment by pieterlexis** [comment]
We're going to import the latest macro from GNU because of that :)
