### ISSUE TITLE
Botan/SoftHSM conflict

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2496]
When we build with Botan, but also load SoftHSM via pkcs11, there is a potential crash on exit (https://gist.github.com/anonymous/d717b5ad1e1cf92c41c8); this happens because SoftHSM also uses Botan, and deinitializes it while we still have some objects active.

**Comment by Habbie** [comment]
HM/Maik on #powerdns point out that the library init/deinit became a no-op in Botan 1.11.14. Perhaps we can upgrade to it (including a related softhsm upgrade) on travis?

**Comment by zeha** [comment]
Botan is gone in 4.2.
