### ISSUE TITLE
hostname -f in Makefiles

### ISSUE THREAD

**Issue by fobser** [PowerDNS/pdns#2503]
Similar to pull request #2502.
pdns/Makefile-recursor and pdns/Makefile.am use hostname -f. I don't know how to fix this though.
Turns out this only logs errors, the build continues. I was under the impression that the build was failing, but that was a different problem. So not really important.

**Comment by rubenk** [comment]
The fix should be the same as for #2505.

**Comment by fobser** [comment]
I'm not really familiar with Makefiles, So what would be the correct syntax?
Like this?
build_host := $(shell id -u -n)@$(shell hostname -f || shell hostname)

I don't know why those lines use "shell"...

**Comment by rubenk** [comment]
$() is for make variables, you're probably thinking of $() in shell context.
to make it clear to Make that you want something run through a shell you need to use the $(shell ...) syntax. So $(shell hostname -f || hostname) should be enough.
