### ISSUE TITLE
OpenBSD needs YACC="/usr/local/bin/bison -y" for configure

### ISSUE THREAD

**Issue by fobser** [PowerDNS/pdns#2504]
Without it:
[...]
checking for bison... yacc
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/egrep
checking if bison is the parser generator... no
configure: error: bison is missing and you don't have ./pdns/bindparser.cc. Please install bison

I suspect the problem is that yacc is in the path before bison:
$ whereis {yacc,bison}     
/usr/bin/yacc
/usr/local/bin/bison

**Comment by rubenk** [comment]
Strange, this works for me (OpenBSD 5.7, rel/auth-3.4.5 branch).
Can you share more details? Are you building from git and if so what commit? Please share config.log as well.

**Comment by fobser** [comment]
Yes, forgot to mention, this is from git. It's not an issue with release tarballs because they contain bindparser.cc. So I'm doing the whole ./bootstrap autohell song and dance.

config.log is not really helpful: http://sha256.net/dump/pdns-bison-config.log

**Comment by rubenk** [comment]
Which git branch?

Thanks for the config.log, it is certainly helpful:
```
pdns_configure_args=' '\''--disable-shared'\'' '\''--with-modules=geo bind'\'' '\''--with-sqlite3'\'' '\''--with-dynmodules=gsqlite3 gmysql gpgsql ldap'\'' '\''--without-lua'\'' '\''--enable-botan1.10'\'' '\''--disable-hardening'\'' '\''--enable-unit-tests'\'' '\''--with-mysql=/usr/local'\'' '\''--with-pgsql=/usr/local'\'' '\''--with-pgsql-includes=/usr/local/include/postgresql'\'' '\''--prefix=/usr/local'\'' '\''--sysconfdir=/etc/pdns'\'' '\''--mandir=/usr/local/man'\'' '\''--infodir=/usr/local/info'\'' '\''--localstatedir=/var'\'' '\''--disable-silent-rules'\'' '\''--disable-gtk-doc'\'' '\''CC=cc'\'' '\''CFLAGS=-O2 -pipe'\'' '\''LDFLAGS=-L/usr/local/lib'\'' '\''CPPFLAGS=-I/usr/local/include'\'' '\''YACC=yacc'\'' '\''CXX=c++'\'' '\''CXXFLAGS=-O2 -pipe'\'''
```
Why do you set YACC in your environment?

**Comment by fobser** [comment]
On 05/06/15 22:51, Ruben Kerkhof wrote:
> Which git branch?

master. I'm not trying to create a package out of it.
For that I'm tracking releases. But with the move to c++11
I want to be prepared once 4.x is released.

> 
> Thanks for the config.log, it is certainly helpful:
> ```
> pdns_configure_args=' '\''--disable-shared'\'' '\''--with-modules=geo bind'\'' '\''--with-sqlite3'\'' '\''--with-dynmodules=gsqlite3 gmysql gpgsql ldap'\'' '\''--without-lua'\'' '\''--enable-botan1.10'\'' '\''--disable-hardening'\'' '\''--enable-unit-tests'\'' '\''--with-mysql=/usr/local'\'' '\''--with-pgsql=/usr/local'\'' '\''--with-pgsql-includes=/usr/local/include/postgresql'\'' '\''--prefix=/usr/local'\'' '\''--sysconfdir=/etc/pdns'\'' '\''--mandir=/usr/local/man'\'' '\''--infodir=/usr/local/info'\'' '\''--localstatedir=/var'\'' '\''--disable-silent-rules'\'' '\''--disable-gtk-doc'\'' '\''CC=cc'\'' '\''CFLAGS=-O2 -pipe'\'' '\''LDFLAGS=-L/usr/local/lib'\'' '\''CPPFLAGS=-I/usr/local/include'\'' '\''YACC=yacc'\'' '\''CXX=c++'\'' '\''CXXFLAGS=-O2 -pipe'\'''
> ```
> Why do you set YACC in your environment?
> 

because configure --help tells me to. Or do you mean why I try to set
YACC at all? Because otherwise configure fails because it picks up yacc
but really wants bison.

**Comment by rubenk** [comment]
Does it still not detect bison if you don't set YACC?

**Comment by fobser** [comment]
Uhm, no, see the output of configure in my very first comment, that's *without* YACC set.

**Comment by rubenk** [comment]
Attach the config.log from a failing attempt to detect bison then please.

**Comment by pieterlexis** [comment]
I think `m4/pdns_check_bison.m4` is the problem here, we check for `AC_PROG_YACC` using `AC_REQUIRE`. But then we set the `pdns_cv_prog_bison` variable to `no` when: 

```
AS_IF([$YACC --version 2>/dev/null | $EGREP -q '^bison ']
```

And when `pdns_cv_prog_bison` is `no`, we check if `pdns/bindparser.cc` exists, which it doesn't in a git checkout. So I think we should fix this script to also accept yacc is that generates the correct output?

**Comment by Habbie** [comment]
As far as I know, `bison -y` is the only thing that actually works for us.

**Comment by fobser** [comment]
It's no problem to use bison on OpenBSD
* it's only needed when building from git, which I don't plan to do for the OpenBSD package
* the port infrastructure handles this just fine

However, I was told that it's a bug if bison is not detected automatically and I should  report it.
Feel free to just close this issue if it's not worth the effort to fix this corner case. I for sure don't know how to fix it ;)

**Comment by rubenk** [comment]
If there's an issue it's certainly worth fixing.
You will need to provide data however, so again, please share your config.log.

**Comment by fobser** [comment]
I already did in https://github.com/PowerDNS/pdns/issues/2504#issuecomment-99604885 
I just recreated it to make sure I did it correctly the first time:
http://sha256.net/dump/pdns-bison-config.log2

The diff between the two config.log files is trivial.

The problem is AC_PROG_YACC, as https://github.com/PowerDNS/pdns/issues/2504#issuecomment-99768439 points out

**Comment by Habbie** [comment]
@fobser we'd like to see a log of a configure run where you do not pass YACC=

**Comment by fobser** [comment]
Sorry, I'm an idiot. Those config.log were generated without **me** setting YACC=.
However, it turns out something in OpenBSD's port infrastructure sets it for me.
If I run configure by hand all is fine.
Sorry for the noise.

**Comment by Habbie** [comment]
Thanks for checking!
