### ISSUE TITLE
Please add API logging configuration

### ISSUE THREAD

**Issue by seitzbg** [PowerDNS/pdns#2505]
I would like to be able to specify a location for the API log be it syslog or a file, and what level to log.  One use case would be to have it log requests / responses for debugging or audit purposes.

Please support separate logging destination for API and log all request attributes including debug level if configured.

**Comment by davy-cousin** [comment]
I need log  responses too。

**Comment by sshipway** [comment]
We also would like this feature for security.  I am surprised there is not already a way to get a log of API calls.

**Comment by setharnold** [comment]
I'm just a bystander, but could this logging be provided by eg an nginx or similar proxy?

**Comment by sshipway** [comment]
@setharnold Unfortunately not, because the proxy would only log the endpoint, not the JSON request body, so you wouldn't know the details of what was being done.  Though it would be better than nothing.

**Comment by pieterlexis** [comment]
The webserver can log requests and responses by setting `webserver-loglevel=detailed`, these logs are sent to stdout/logger (systemd journal) and are prefixed with `[webserver]`

**Comment by sshipway** [comment]
We are running powerdns-admin under gunicorn, behind Apache httpd, so we can't do this effectively.  The Apache sec2 module allows POST content logging, but along with screeds of other unwanted data rather than a simple log of API requests.  pdnsa already has a logging option, it would have been helpful to be able to log API calls separately, and with more clarity

**Comment by pieterlexis** [comment]
>  it would have been helpful to be able to log API calls separately, and with more clarity

This is why the log line is prefixed. Your logshipper can do the filtering
