### ISSUE TITLE
dnsdist: update README/sample config links in announcement blog

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#2519]
the announcement blog post for dnsdist ( http://blog.powerdns.com/2015/03/11/introducing-dnsdist-dns-abuse-and-dos-aware-query-distribution-for-optimal-performance/  contains multiple broken links to README / sample.config files. the links point to the ahupowerdns github repository and return 404, for example https://github.com/ahupowerdns/pdns/blob/dnsname/pdns/README-dnsdist.md

It may be worth updating these as this blog post is the first google result for "dnsdist". dnsdist.org is currently only the 5th result.

**Comment by ahupowerdns** [comment]
Thank you very much @gryphius! Updated the blog with the right links, and am adding more links to dnsdist.org here and there to 'SEO' it up. Thanks!
