### ISSUE TITLE
Deprecate geobackend discussion

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#2523]
We have the GeoIP backend that is beteer. The original author of the Geo backend tells us to drop the Geo backend. We need discussion on this.

**Comment by cmouse** [comment]
GeoIP backend does not currently work with travis due to yaml issues. Perhaps discussion should involve how to configure geoip backend as well or should we find a travis-compatible yaml parser? =)

**Comment by Habbie** [comment]
If we have geoip with yaml in our semistatic builds this is acceptable for now, to me.

**Comment by pieterlexis** [comment]
This has been fixed with the merge of #2411
