### ISSUE TITLE
ask : sample perl backend while(<>)

### ISSUE THREAD

**Issue by hdr420** [PowerDNS/pdns#2556]
Hi , I want to ask about sample perl backend. 

#!/usr/bin/perl -w
use strict;

$|=1;                   # no buffering

my $line=<>;
chomp($line);

unless($line eq "HELO\t1") {
    print "FAIL\n";
    print STDERR "Received '$line'\n";
    <>;
    exit;
}
print "OK   Sample backend firing up\n";    # print our banner

while(<>)
{
    print STDERR "$$ Received: $_";
    chomp();
    my @arr=split(/\t/);
    if(@arr<6) {
        print "LOG  PowerDNS sent unparseable line\n";
        print "FAIL\n";
        next;
    }

    # note! the qname is what PowerDNS asks the backend. It need not be what the internet asked PowerDNS!
    my ($type,$qname,$qclass,$qtype,$id,$ip)=split(/\t/);

    if(($qtype eq "SOA" || $qtype eq "ANY") && $qname eq "example.com") {
        print STDERR "$$ Sent SOA records\n";
        print "DATA $qname  $qclass SOA 3600    -1  ns1.example.com ahu.example.com 2008080300 1800 3600 604800 3600\n";
    }
    if(($qtype eq "NS" || $qtype eq "ANY") && $qname eq "example.com") {
        print STDERR "$$ Sent NS records\n";
        print "DATA $qname  $qclass NS  3600    -1  ns1.example.com\n";
        print "DATA $qname  $qclass NS  3600    -1  ns2.example.com\n";
    }
    if(($qtype eq "TXT" || $qtype eq "ANY") && $qname eq "example.com") {
        print STDERR "$$ Sent NS records\n";
        print "DATA $qname  $qclass TXT 3600    -1  \"hallo allemaal!\"\n";
    }
    if(($qtype eq "A" || $qtype eq "ANY") && $qname eq "webserver.example.com") {
        print STDERR "$$ Sent A records\n";
        print "DATA $qname  $qclass A   3600    -1  1.2.3.4\n";
        print "DATA $qname  $qclass A   3600    -1  1.2.3.5\n";
        print "DATA $qname  $qclass A   3600    -1  1.2.3.6\n";
    }
    elsif(($qtype eq "CNAME" || $qtype eq "ANY") && $qname eq "www.example.com") {
        print STDERR "$$ Sent CNAME records\n";
        print "DATA $qname  $qclass CNAME   3600    -1  webserver.example.com\n";
    }

    print STDERR "$$ End of data\n";
    print "END\n";
}

I customize this script and I realize that when I use 'dig' command this script will loop twice , and when i use 'nslookup' command the script will loop like 7 times. Can anyone tell me why this happen? or I make a mistake in my configuration . Thanks

**Comment by ahupowerdns** [comment]
No, this is very normal. PowerDNS needs to query the backend multiple times for one DNS query, and nslookup sends many queries itself.

**Comment by hdr420** [comment]
@ahupowerdns thanks for the quick respond , can you explain why PowerDNS needs to query the backend multiple times ?

**Comment by ahupowerdns** [comment]
Please go read https://doc.powerdns.com/md/appendix/backend-writers-guide/ . DNS needs to check multiple things, like if there is a SOA record or a CNAME etc. The backends are backends, not DNS engines.

**Comment by hdr420** [comment]
@ahupowerdns thank you so much , it's really help me
