### ISSUE TITLE
dnsdist-0.0.147gd5b4f7f fedora 22 missing lua-devel not detected

### ISSUE THREAD

**Issue by jaredmauch** [PowerDNS/pdns#2564]
if the lua-devel package is not installed it's not properly detected and reported as fatal when building with fedora 22.

eg:

make[2]: Entering directory '/home/jared/dnsdist-0.0.147gd5b4f7f'
  CXX      dnsdist.o
In file included from dnsdist.hh:2:0,
                 from dnsdist.cc:23:
ext/luawrapper/include/LuaContext.hpp:55:19: fatal error: lua.hpp: No such file or directory

installing lua-devel corrects this build issue

**Comment by pieterlexis** [comment]
Interesting, I was under the impression we check for this. Could you pastebin your config.log? I'll have a look at this issue tomorrow.

**Comment by jaredmauch** [comment]
Sure.  I got this from configure output before I added the package:

checking whether we will be linking in Lua... auto
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for chosen LUA... not found

I'll grab the log and post it in a bit.

**Comment by jaredmauch** [comment]
http://puck.nether.net/~jared/dnsdist-no-lua.config.log.txt

**Comment by mrqwer88** [comment]
Hello.

How I see I have same problem with debian 8.
configure failed with
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for chosen LUA... not found
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... no
checking whether g++ supports C++11 features with -std=gnu++0x... no
configure: error: *** A compiler with support for C++11 language features is required.

without lua headers and I try to fix issue with g++.

But after install liblua5.2-dev it confugure good - 
checking for LUA... no
checking for LUA... yes
checking for chosen LUA... lua5.2
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pdns/ext/yahttp/Makefile
config.status: creating pdns/ext/yahttp/yahttp/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
