### ISSUE TITLE
reduce ttl per second

### ISSUE THREAD

**Issue by newbie21** [PowerDNS/pdns#2565]
hi I want to ask about ttl, When I query the A record from my backend , the ttl did not decrease. I set the ttl 3600 and it's still 3600. Can you tell me what's the reason?

**Comment by pieterlexis** [comment]
Hello newbie21,

This behaviour is correct for the authoritative server. It does not reduce TTLs as this is the job of the recursor doing the lookup. The PowerNDS recursor does decrease the TTL correctly based on how log the record is in its cache.

**Comment by newbie21** [comment]
hello @pieterlexis thanks for the answer. When i tried to use pdns-recursor i realize that in recursor.conf there is no auth-can-lower-ttl. Can you help me what should I configure in recursor.conf to reduce the cache ttl?

**Comment by pieterlexis** [comment]
It would really help if you would describe exactly what you're trying to achieve, your setup and versions of PowerDNS.

What I gather from your last message is that you want a maximum TTL for all records in your recursor cache. This can be done by setting the [max-cache-ttl](https://doc.powerdns.com/md/recursor/settings/#max-cache-ttl) setting in `recursor.conf`.

**Comment by newbie21** [comment]
I customize this perl sample backend (https://doc.powerdns.com/md/authoritative/backend-pipe/) and store all my zone file in postgresql.
what i am trying to achieve is my cache ttl is reducing. I guess i make a mistake in my configuration.
My pdns-recursor version is 3.7.3.
Can you tell me what should i do in my configuration?

**Comment by pieterlexis** [comment]
Your question does not really make sense, the perl-script for the pipe backend is for the authoritative server. The recursor is only [scriptable in Lua](https://doc.powerdns.com/md/recursor/scripting/).

Further more, if you save records in PostgreSQL, you could just use the [PostgreSQL backend](https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/). And if you control the domain, you might as well just lower the TTL of the records.

But I might misunderstand what you are trying, what is you masterplan (apart from "lowering the cache ttl") with this whole setup?

**Comment by newbie21** [comment]
I think i misunderstand how pdns work.
What i am trying to do is make an authoritative server and store the records in database and i want to cache the query results.
I'm still confuse in cache and lowering the ttl.

**Comment by cmouse** [comment]
You probably want to use PowerDNS auth server then.

**Comment by newbie21** [comment]
@cmouse @pieterlexis i think i get it now, thanks a lot
