### ISSUE TITLE
dnsdist crashed on incorrect domain name in addQPSLimit

### ISSUE THREAD

**Issue by mrqwer88** [PowerDNS/pdns#2573]
Hello.
I try it with dnsdist-0.1.tar.gz from http://xs.powerdns.com/dnsdist/ and with build from git repo (commit 5ff02da0600734ba670c647c8c180cece7434118 at Mon Jun 8 12:29:33 2015 +0200).
With both version it crashed on
```
> addQPSLimit( "spb.ru", 20)
Exception thrown by a callback function called by Lua: Fatal pdns error: Unable to convert 'spb.ru' to a netmask

> addQPSLimit( "google.com", 20)
Exception thrown by a callback function called by Lua: Fatal pdns error: Unable to convert 'google.com' to a netmask

```

With dot at the end name it work good.
It looks like bad exception, with same error in domain name in addDomainBlock it work nice - 
```
> addDomainBlock( "google.com")
Exception thrown by a callback function called by Lua: Unable to parse DNS name 'google.com': cs=2
> 

```

**Comment by ahupowerdns** [comment]
Ok, thank you - I thought I had that fixed yesterday, but maybe I did not commit/pushed the fix yet to this branch.

**Comment by ahupowerdns** [comment]
ok, pull request with the fixes in there has been sent, now waiting tests. Will merge when done!

**Comment by ahupowerdns** [comment]
should be fixed now in master, can you check?

**Comment by mrqwer88** [comment]
Yes - it fixed now.
After pull and recompile - 
```
> addQPSLimit( "spb.ru", 20)
Exception thrown by a callback function called by Lua: Unable to convert 'spb.ru' to a netmask
> addQPSLimit( "google.com", 20)
Exception thrown by a callback function called by Lua: Unable to convert 'google.com' to a netmask
>
```
without crashed all dnsdist.

Thank you!
