### ISSUE TITLE
`hostname -f` errors on OpenBSD [was: Illumos & Solaris systems]

### ISSUE THREAD

**Issue by jeffpc** [PowerDNS/pdns#2579]
At the very least the recursor build system uses hostname to bake user@host type strings into config files and binaries.  Understandably, it wants the FQDN.  With GNU hostname, specifying `-f` or `--fqdn` does that.  Unfortunately, the hostname command on Illumos-derived systems doesn't understand any options:

```
SYNOPSIS
       /usr/bin/hostname [name-of-host]
```

If run as a privileged user, any argument will be used as the new hostname.  So, `hostname -f` will set the hostname to `-f`.  This is definitely not what the user wanted.

Since Illumos started off as a fork of OpenSolaris, the same warning applies to all versions of OpenSolaris as well as Solaris 10 and older.  I have no idea if `hostname` changed in Solaris 11 as Solaris 11 and Illumos diverged quite a bit.

**Comment by rubenk** [comment]
Any idea how you get the FQDN on Solaris?

**Comment by jeffpc** [comment]
The more I look into it, the more I think that FQDN is a weird concept.  The hostname set by the administrator via hostname(1) can be totally unrelated to DNS/NIS/etc.  The admin *can* set the hostname to a FQDN...or some partial "prefix".

I'd suggest to just take `hostname` output as is on Illumos, OpenSolaris, and Solaris10 and older.  Like I said originally, I have no idea what Solaris11 is up to.

**Comment by pieterlexis** [comment]
#2646 should fix this once merged

**Comment by Habbie** [comment]
@jeffpc we merged #2646, can you comment on the fix in it?

**Comment by jeffpc** [comment]
Looking at the pull request change, it looks better.  It won't clobber the hostname.  Thanks.

Just as an FYI, domainname(1) is not a DNS domain name but rather a NIS domain name (http://illumos.org/man/1m/domainname).  For example:

```
$ domainname

$ hostname
meili
```

This will result in a "meili."  It's not great, but I'm happy enough given that it no longer does `hostname -f`.

**Comment by Habbie** [comment]
Thanks! Closing :)

**Comment by Habbie** [comment]
Reopened for OpenBSD:
```
hostname: unknown option -- f
usage: hostname [-s] [name-of-host]
```
