### ISSUE TITLE
Harmonize configuration options

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2587]
We should harmonize configuration options, such as 
```
--gsqlite3-database=
--gmysql-dbname=
```
choose either one and use that on all backends. same for many other options.

also we should choose either "disable"/"enable" and deprecate the old options in favor for new ones.

**Comment by Habbie** [comment]
The idea is good but the example is bad. One is a file name, the other is a database name.

**Comment by pieterlexis** [comment]
I think the example is good, most pieces of software (e.g. [Django](https://docs.djangoproject.com/en/1.8/ref/settings/#databases)) use the same name in their config for both sqlite and mysql (where one must be a path and the other a string)

**Comment by Habbie** [comment]
I looked it up, indeed Django does that. I think that is terrible :)

**Comment by Habbie** [comment]
Change is painful. Not doing this!
