### ISSUE TITLE
transfer-encoding set to chunked when response body is empty on api calls

### ISSUE THREAD

**Issue by jbweber** [PowerDNS/pdns#2601]
When performing a DELETE against a zone I'm seeing the following response

HTTP/1.1 201 No Content
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Content-Length: 0
Server: PowerDNS/3.4.4

With an empty response body the transfer-encoding should not be set to chunked. It's causing my python requests based http client to fail as it attempts to parse a response body which won't exist.

I'm currently handling this by removing the response header using haproxy if the content-length is 0, but I have some situations where it would be nice to use the api without it being behind haproxy.

**Comment by ahupowerdns** [comment]
Hi @jbweber, asking @cmouse if he has an opinion. Aki? I wonder where the fix should be. jbweber, do you have a copy of the error python gives you? might be inspiring.

**Comment by zeha** [comment]
I agree that this is broken.

**Comment by cmouse** [comment]
Fixed on upstream.

**Comment by cmouse** [comment]
v0.1.6 released
