### ISSUE TITLE
Possible problem with the packet cache of pdns

### ISSUE THREAD

**Issue by sahideler** [PowerDNS/pdns#2606]
Hi powerdns,

In regards to this thread
http://mailman.powerdns.com/pipermail/pdns-users/2011-April/007644.html

After upgrading from an ancient pdns installation to the latest, I encountered the same problem as described in the mailing thread.
[root@ns2 pdns]# rpm -qa | grep pdns
pdns-recursor-3.7.3-1.el6.MIND.x86_64
pdns-3.4.5-1.el6.MIND.x86_64
pdns-tools-3.4.5-1.el6.MIND.x86_64
pdns-backend-mysql-3.4.5-1.el6.MIND.x86_64
OS: REL 6.3 x86_64

That is, on a specific domain I receive an answer, or not an answer (tcpdump 0/0/ refused-) and it flips between an answer for a few queries, then a certain amount of seconds with no answers.

When I query the recursor directly, it always returns the correct answer.
When I run the recursor in spam mode (quiet=no) I see that the request which do get passed from pdns, get resolved succesfully. But I was missing quite a few of them.
As such my focus became the pdns config/setup. 
After setting recursive-cache-ttl=0 the behavior was corrected, pdns now also always returned the correct answer.

The strange thing is, I've only found this behavior with one specific domain name, which happens to be one of the most requested -- it is queried frequently by our all our equipment and instances worldwide and as such was receiving a 50-70% failure rate. I could not find another domain which was giving me the same problem. As such I don't really know at what point this starts breaking, except that it might have to be a frequently queried domain name. 

Best regards,

Stefan

**Comment by ahupowerdns** [comment]
As we will be removing the auth recursor= feature, this bug will go away too.
