### ISSUE TITLE
Trailing whitespace considered as error

### ISSUE THREAD

**Issue by sid3windr** [PowerDNS/pdns#2611]
```
[Error] Following record had a problem: example.com IN SOA example.luciad.com example.luciad.com 2015061830 28801 14400 360000 86400 
[Error] Error was: All data was not consumed
```

A trailing space on the SOA record made the zone unusable as the SOA could not be parsed.

Could perhaps be useful to be tolerant of spaces, both in SOA and other record content.

**Comment by Habbie** [comment]
Fixing this would increase the potential impact of #2429, just as a note.
