### ISSUE TITLE
Move the API path for 4.0

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#2612]
As 4.0 will be the release where the API is no longer marked as "experimental", we need to have a stable endpoint for the then-current API. My current suggestion is using `/api/v1/`. This allows us to carry a stable API to 4.1, 4.2 etc. A totally new (or expanded) API could be developed at `/api/v2/`.

@zeha, @jpmens: comments, suggestions, improvements?

**Comment by jpmens** [comment]
Very sensible, and I believe that's what people do. :+1:

**Comment by cmouse** [comment]
:+1:

**Comment by zeha** [comment]
This is one of the things people do when they need to support multiple API versions in parallel. Do we need to?

I suspect we could get away by keeping a discovery endpoint semi-stable and do a version check there (/servers/localhost already exposes version and stuff).
