### ISSUE TITLE
API should expose ringbuffers

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#2617]
Right now it's impossible to retrieve the contents of the ringbuffers from the StatBag using the API. The 'normal' webserver displays them at e.g. the `/?ring=queries` page. It'd be really handy if we could get these in JSON format out of the API.

A suggestion for the url: `/servers/:server_id/statistics/ring`, the JSON request-body may then contain:

```
{
  "rings": ["query", "noerror-queries"]
}
```

The response could be:

```
[
  {
    "type": "ringbuffer",
    "name": "queries",
    "description": "UDP Queries Received",
    "value": [{"GOOGLE.COM/A": 800}, {"POWERDNS.COM/AAAA": 750}]
  },
  {
    "type": "ringbuffer",
    "name": "noerror-queries",
    "description": "Queries for existing records, but for type we don't have",
    "value": [{"GOOGLE.COM/AAAA": 10}, {"POWERDNS.COM/CAA": 2}]
  }
]
```

Where the "value" is a list which is sorted by amount.....

**Comment by zeha** [comment]
Need to iterate a bit more on how this should look...
(I'd like to keep `/servers/:server_id/statistics/...` free for `/servers/:server_id/statistics/:statistic_item`, but maybe this can be the start of that?)

**Comment by pieterlexis** [comment]
that makes sense, but why not then *also* dump these stats when requesting `/servers/:server_id/statistics`. That way `/servers/:server_id/statistics/noerror-queries` also works?

That way the ringbuffer data is not in another namespace than the counters data.

**Comment by zeha** [comment]
Yeah. Hmm, maybe we should finish thinking this through before merging #2603

**Comment by zeha** [comment]
With the new commit that I've just pushed to 2603, stats would now look like this:

Simple stats
----------------

```json
  {
    "type": "StatisticItem",
    "name": "udp6-answers",
    "value": "0"
  },
```

By-something stats
-------------------------

```json
  {
    "type": "MapStatisticItem",
    "name": "queries-by-qtype",
    "value": [
      {
        "name": "A",
        "value": "1"
      }
    ]
  },
```

Ringbuffers
--------------

```json
  {
    "type": "RingStatisticItem",
    "name": "logmessages",
    "size": "10000",
    "value": [
      {
        "name": "About to create 3 backend threads for UDP",
        "value": "1"
      },
      {
        "name": "Creating backend connection for TCP",
        "value": "1"
      },
      {
        "name": "Done launching threads, ready to distribute questions",
        "value": "1"
      }
    ]
  },
```

**Comment by pieterlexis** [comment]
looks sweet, how's the URL path?

**Comment by zeha** [comment]
For now this is all part of /.../statistics - and I have some doubts if this is a good idea (ringbuffers could be x-times larger then the other stat items).

Supporting /.../statistics/:name is the next thing to do.

**Comment by zeha** [comment]
Does anyone have comments on my ringbuffer size concern?

**Comment by ahupowerdns** [comment]
for now I think we can live with a megabyte of data, I've done worse.

**Comment by Habbie** [comment]
Merging #2603 fixed this, right?

**Comment by zeha** [comment]
Yes!
