### ISSUE TITLE
Pipebackend can cause weird error if misconfigured

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2619]
$ ../pdns/pdnssec --config-name=pipe --config-dir=. help
Error: Command '' cannot be executed: No such file or directory

pdns-pipe.conf
```
module-dir=./modules
launch=pipe
pipebackend-command=
pipebackend-abi-version=4
```

**Comment by Habbie** [comment]
I'm not sure what to do about this. The error seems pretty clear to me.

**Comment by cmouse** [comment]
Maybe validate that the pipe-command is executable or at least not empty?
