### ISSUE TITLE
Recursor compilation on Debian gcc 4.7 fails with STATIC=semi

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#2621]
Works if STATIC is not set. Since i am building packages to distribute to other machines it would be nice to get the static compilation working.

```
 -Iext/rapidjson/include -I/root/src/pdns-new/pdns-recursor-3.7.3/ext/polarssl/include -Wall  -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=4 -O3   -pthread -Iext/yahttp -D_GNU_SOURCE -DHAVE_STRCASESTR -I/usr/include/lua5.1   -DPDNS_ENABLE_LUA -DHAVE_LUA -DSYSCONFDIR='"/etc/powerdns/"' -DLOCALSTATEDIR='"/var/run/"' -D_FORTIFY_SOURCE=2  -c -o iputils.o iputils.cc
gcc syncres.o misc.o unix_utility.o qtype.o logger.o arguments.o lwres.o pdns_recursor.o recursor_cache.o dnsparser.o dnswriter.o dnsrecords.o rcpgenerator.o base64.o zoneparser-tng.o rec_channel.o rec_channel_rec.o selectmplexer.o sillyrecords.o dns_random.o pubsuffix.o ext/polarssl/library/aes.o ext/polarssl/library/base64.o dnslabeltext.o lua-pdns.o lua-recursor.o randomhelper.o recpacketcache.o dns.o reczones.o base32.o nsecrecords.o json.o ws-recursor.o ws-api.o version.o responsestats.o webserver.o ext/yahttp/yahttp/reqresp.o ext/yahttp/yahttp/router.o rec-carbon.o secpoll-recursor.o lua-iputils.o iputils.o optional/epollmplexer.o -fPIE -pie -Wl,-z,relro -Wl,-z,now  -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -fstack-protector --param ssp-buffer-size=4  -lm  -Wl,-Bstatic -lstdc++ -llua5.1   -lgcc -Wl,-Bdynamic -static-libgcc -lm -lc -ldl -o pdns_recursor
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.7/libstdc++.a(compatibility.o): relocation R_X86_64_32 against `_ZTIN10__cxxabiv115__forced_unwindE' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.7/libstdc++.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [pdns_recursor] Error 1
make[1]: Leaving directory `/root/src/pdns-new/pdns-recursor-3.7.3'
dh_auto_build: make -j1 returned exit code 2
make: *** [binary] Error 2
```

**Comment by pieterlexis** [comment]
Hi,

Could you provide us with:

* The version of the recursor
* Where you got the sources
* The command-invocation you used to configure and build
* The OS you're running on
* The output of `g++ --version`

**Comment by janeczku** [comment]
**Build system**
Recursor 3.7.3 sources from Debian jessie-backports repository https://packages.debian.org/jessie-backports/pdns-recursor
OS: Debian 7 64bit
g++ (Debian 4.7.2-5) 4.7.2

**Build steps**
1. Added `export STATIC := semi` to `debian/rules`
2. Run `fakeroot debian/rules binary`

**Comment by pieterlexis** [comment]
Ah, the debian sources are not meant to build semi-static releases from. For one, in our repository we have a wrapper for [g++](https://github.com/PowerDNS/pdns/blob/master/build-scripts/semistaticg%2B%2B) and our own homebrew [semistatic build script](https://github.com/PowerDNS/pdns/blob/master/build-scripts/build-recursor-semistatic) that does all the semistatic magic.

Also, we don't recommend (or support) building the semi-static packages. If you want to run a semistatic variant, We'd recommend you use the package provided on [our website](https://www.powerdns.com/downloads.html) or build a normal package using the modern sources (or upgrade the OS :wink:).

Another option is to clone the repo, checkout the branch/tag you want and go from there (but we don't support building the semistatic).
