### ISSUE TITLE
Lookups not domain specific

### ISSUE THREAD

**Issue by spinza** [PowerDNS/pdns#2623]
If multiple domains exist on the same database lookups will match any record in the records table.  Even ones not from the domain in question.  I.e. lookups are not filtered by the relevant domain.

I wanted to store multiple versions of the same domain in the records table but couldn't do it because lookups would match records from the other version even though I made sure the domain queries only returned the relevant domain to pdns.

Lookups should really also filter by the relevant domain.

**Comment by spinza** [comment]
I solved it by creating a records and domain mysql view in my backend that filters out the records and pointing queries to those views.

**Comment by pieterlexis** [comment]
Hi,

In order to understand this issue, could you please provide us with the following: 
* Your `pdns.conf` (without passwords etc.)
* An example of database records (from both the `domains` and the `records` table that trigger this issue for you
* The DNS query you send to your namesever
* The answer to thet query
* What you expected the answer to be

We'd like to be able to reproduce this issue.

**Comment by spinza** [comment]
I had two domains with the same name in the database. 
I had changed all queries on the domains table in the configs to only return one of the domains to pdns.
pdns returned records from the other domain when I looked up.  
So it ignores domain_id when looking up in the records table.
I worked around this by creating a mysql view on records and domains to only return the relevant records.

**Comment by pieterlexis** [comment]
Hi,

This is exactly how PowerDNS works, see the [docs](https://doc.powerdns.com/md/authoritative/internals/#how-powerdns-translates-dns-queries-into-backend-queries) and our recent [blogpost](http://blog.powerdns.com/2015/06/23/what-is-a-powerdns-backend-and-how-do-i-make-it-send-an-nxdomain/) on backends.

The `domain_id` is used to get all the records of a domain for an AXFR.

Closing this issue.
