### ISSUE TITLE
When out-of-zone-additional-processing is set to no, the response still indicates an Additional Section

### ISSUE THREAD

**Issue by grahamhayes** [PowerDNS/pdns#2634]
When `out-of-zone-additional-processing=no` the following is returned from the PowerDNS server.

It does not have an additional section, but has the flag set in the packet.

    vagrant@vagrant-ubuntu-trusty-64:~/devstack$ dig @192.168.27.100 sub.example.com.

    ; <<>> DiG 9.9.5-3ubuntu0.1-Ubuntu <<>> @192.168.27.100 sub.example.com.
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38205
    ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
    ;; WARNING: recursion requested but not available

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 2800
    ;; QUESTION SECTION:
    ;sub.example.com.       IN  A

    ;; AUTHORITY SECTION:
    sub.example.com.    3600    IN  NS  ns.provider.com.

    ;; Query time: 2 msec
    ;; SERVER: 192.168.27.100#53(192.168.27.100)
    ;; WHEN: Thu Jul 09 17:30:47 UTC 2015
    ;; MSG SIZE  rcvd: 71

**Comment by Habbie** [comment]
It's not a flag - it's a counter. The one it is counting is the OPT PSEUDOSECTION you see above. If you query with +noedns it goes away and the counter should be zero.

If the counter really was wrong, dig would complain loudly.

Closing ticket.
