### ISSUE TITLE
Unable to find backend willing to host

### ISSUE THREAD

**Issue by odessky** [PowerDNS/pdns#2643]
Hi
I was setup master pdns and it is work fine.
Now I try setup slave pdns and configure it for get zones from master in supermaster mode.
For this I run on my slave pdns mysql db:
insert into supermasters values ('10.0.0.1', 'n1.example.com', 'admin');

But when I try sent notify, I get this error:
Jul 16 09:20:31 cs21385 pdns[2326]: Unable to find backend willing to host example.com for potential supermaster 10.0.0.1. 4 remote nameservers: 
Jul 16 09:20:31 cs21385 pdns[2326]: ns2.example.com
Jul 16 09:20:31 cs21385 pdns[2326]: ns1.example.com
Jul 16 09:20:31 cs21385 pdns[2326]: 10.0.0.2
Jul 16 09:20:31 cs21385 pdns[2326]: 10.0.0.1

This is manual axfr on slave:
; <<>> DiG 9.9.5-3ubuntu0.3-Ubuntu <<>> axfr example.com. @10.0.0.1
;; global options: +cmd
example.com.		86400	IN	SOA	ns1.example.com. hostmaster.example.com. 2015071605 10800 3600 604800 600
ns1.example.com.	86400	IN	A	10.0.0.1
ns2.example.com.	86400	IN	A	10.0.0.2
example.com.		86400	IN	A	10.0.0.1
example.com.		86400	IN	NS	ns1.example.com.
example.com.		86400	IN	NS	ns2.example.com.
www.example.com.	86400	IN	CNAME	example.com.
example.com.		86400	IN	SOA	ns1.example.com. hostmaster.example.com. 2015071605 10800 3600 604800 600
;; Query time: 26 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Thu Jul 16 09:21:13 MSK 2015
;; XFR size: 8 records (messages 3, bytes 330)

Can you explain me where I miss?

**Comment by cmouse** [comment]
You have a typo in your supermaster table. 'n1.example.com' is not 'ns1.example.com'

**Comment by odessky** [comment]
Thank you very much :)
