### ISSUE TITLE
Idea: vizone command which loads & edits zone from DB

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#2650]
I wouldn't have dared suggest this here, but my understanding of [this thread](https://twitter.com/jpmens/status/623425681691660292) is that I should, so here's the man page for it. ;-)

```txt
NAME
   vizone - loads a specific PowerDNS zone into editor

SYNOPSIS
  vizone zone

DESCRIPTION
  vizone loads the specified zone from a PowerDNS back-end database into
  $EDITOR in master zone file format.  After editing the zone and writing
  back the temporary file, vizone checks the result for errors. If the
  temporary copy is error-free, vizone saves the records back into the
  back-end database, otherwise, $EDITOR is re-opened and comments in the
  zone file (;) describe the error.

BACKENDS
  vizone can be configured to read the back-end database directly (for
  environments which don't use the PowerDNS API), use the RESTful API,
  and use RFC 2136 updates if PowerDNS is thusly configured.

SEE ALSO
  nsupdate(1), nsdiff(1)

```

**Comment by hlindqvist** [comment]
What about simply using AXFR to load the data? Makes it more generic.

I did a similar thing in the past at https://github.com/hlindqvist/dnstools/blob/master/ddns-edit-zone.py (which has unfortunately fallen apart somewhat with later dnspython versions).

**Comment by jpmens** [comment]
Good stuff!

**Comment by cmouse** [comment]
What we really need is nsdiff that outputs nsupdate input. :)

**Comment by ahupowerdns** [comment]
Even without diff this is nice BTW. Am working on it.
On Jul 22, 2015 8:26 AM, Aki Tuomi <notifications@github.com> wrote:What we really need is nsdiff that outputs nsupdate input. :)

**Comment by fanf2** [comment]
@cmouse have a look at http://dotat.at/prog/nsdiff/

nsdiff now comes with an nsvi wrapper for editing dynamic zones.

**Comment by cmouse** [comment]
Nice. Thanks

**Comment by Habbie** [comment]
`pdnsutil edit-zone` pretty much covers this now. Let me know if anyone disagrees and I'll reopen :)
