### ISSUE TITLE
"Wrong" Sql execution

### ISSUE THREAD

**Issue by RoyBellingan** [PowerDNS/pdns#2656]
I was profiling query execution and I've noticed this

if I do a simple dig dgpr.it @seisho.us  the log says 
```
Jul 27 22:17:22 Remote 5.39.84.121 wants 'dgpr.it|A', do = 0, bufsize = 1680: packetcache MISS
```
On the MySQL side first is executed this
```
select content,ttl,prio,type,domain_id,name from records where type='SOA' and name='dgpr.it'
```
wich is classified as basic-query in https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/#queries-and-settings

than the requested record
```
select content,ttl,prio,type,domain_id,name from records where name='dgpr.it' and domain_id=2 
```
is requested NOT using the basic-query as documented but via the any-id-query

This lead to mysql reading ALL the zones in the site, and filtering out the relevent one by powerdns.

The traffic and load increase may be negligible but this behaviour block the use of more complex query. 

(yes other than disabling DOWN server I'm trying to do a first level load balancing with dns, with 30 sec ttl ecc, I'm also using HA Proxy, but I would like to avoid to point user to a server and than tunnel to another).

**Comment by RoyBellingan** [comment]
I was digging in the code and found this 

https://github.com/PowerDNS/pdns/blob/f4ece5adc6e7ef47c83f56133c37522d9c7be546/pdns/backends/gsql/gsqlbackend.cc#L900

Where it seems that in the run to get the A record the passed qtype is the problem.

Tomorrow I'll try to run in debug mode to catch more info.

void GSQLBackend::lookup(const QType &qtype,const DNSName &qname, DNSPacket *pkt_p, int domain_id)
{
  try {
    if(qtype.getCode()!=QType::ANY) {
      if(domain_id < 0) {
        d_query_stmt = d_NoIdQuery_stmt;
        d_query_stmt->
          bind("qtype", qtype.getName())->
          bind("qname", qname);
      } else {
        d_query_stmt = d_IdQuery_stmt;
        d_query_stmt->
          bind("qtype", qtype.getName())->
          bind("qname", qname)->
          bind("domain_id", domain_id);
      }
    } else {
      // qtype==ANY
      if(domain_id < 0) {
        d_query_stmt = d_ANYNoIdQuery_stmt;
        d_query_stmt->
          bind("qname", qname);
      } else {
        d_query_stmt = d_ANYIdQuery_stmt;
        d_query_stmt->
          bind("qname", qname)->
          bind("domain_id", domain_id);
      }
    }

**Comment by RoyBellingan** [comment]
Long Story Short
Change this
https://github.com/PowerDNS/pdns/blob/6526a08dabca42a451eba29f5a8732b0b8732005/pdns/packethandler.cc#L1231

(B.lookup(QType(QType::ANY), target, p, sd.domain_id);)

With this
    
B.lookup(QType(p->qtype.getCode()), target, p, sd.domain_id);

Description follows ..

As said the first run is for a SOA record

Called from https://github.com/PowerDNS/pdns/blob/6526a08dabca42a451eba29f5a8732b0b8732005/pdns/packethandler.cc#L1159
To check authority

If successfull the program advance to https://github.com/PowerDNS/pdns/blob/6526a08dabca42a451eba29f5a8732b0b8732005/pdns/packethandler.cc#L1231

// see what we get..
B.lookup(QType(QType::ANY), target, p, sd.domain_id);

here it discardes the query request type!!

(The query type is in p->qtype.getCode();)

So it fetches all and continue to a loop 

This if is catched on the correct row
https://github.com/PowerDNS/pdns/blob/6526a08dabca42a451eba29f5a8732b0b8732005/pdns/packethandler.cc#L1244

      if((p->qtype.getCode() == QType::ANY || rr.qtype == p->qtype) && rr.auth) 
        weDone=1;

Later this weDone activate the effective filtering of the row here
https://github.com/PowerDNS/pdns/blob/6526a08dabca42a451eba29f5a8732b0b8732005/pdns/packethandler.cc#L1339

        if((p->qtype.getCode() == QType::ANY || rr.qtype == p->qtype) && rr.qtype.getCode() && rr.auth) {
          r->addRecord(rr);
          haveRecords = true;
        }

I don't know how to run the test, mostly because now it is 3:42 AM...

But some quick check make me believe the code is ok with this fix.

**Comment by Habbie** [comment]
Hello Roy,

> This lead to mysql reading ALL the zones in the site, and filtering out the relevent one by powerdns.

This is incorrect - domain_id and name limit the result set to just the records with that name, in that zone. 

Furthermore, backend queries are supposed to be ANY - this allows us to easily distinguish NODATA and NXDOMAIN. Your patch will likely turn a NODATA NOERROR into NXDOMAIN.

http://blog.powerdns.com/2015/06/23/what-is-a-powerdns-backend-and-how-do-i-make-it-send-an-nxdomain/ may be interesting reading for you.

Closing this ticket. Please feel free to open tickets for other issues!

**Comment by RoyBellingan** [comment]
Hy Habbie.
Ok about this, so powerdns will filter the result.

 Please amend the documentation.

https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/


Because due to this behaviour this query is not used

basic-query

Default: select content,ttl,prio,type,domain_id,disabled,name,auth from records where type='%s' and name='%s' This is the most used query, needed for doing 1:1 lookups of qtype/name values. First %s is replaced by the ASCII representation of the qtype of the question, the second by the name.

**Comment by Habbie** [comment]
Hello Roy,

if you feel the documentation is incorrect (I don't see it), please feel free to file a pull request for it. You can browse to docs/ inside our github tree and use the Edit button right there, if you like.
