### ISSUE TITLE
forward to another dns server based on subnet

### ISSUE THREAD

**Issue by hdr420** [PowerDNS/pdns#2661]
i want to ask, can pdns forward to another dns server based on network.
for example 172.17.16.8 will be forwarded to DNS A and 172.17.17.8 will be forwarded to DNS B.

**Comment by pieterlexis** [comment]
Hi @hdr420,

PowerDNS by itself cannot do this, you could run multiple instances with different config on different IPs to accomplish this. Another solution is to use [dnsdist](https://dnsdist.org), but that is still experimental software.
