### ISSUE TITLE
drop privileges before creating the controlsocket

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#268]
Imho you should drop root privs before creating a control-socket and pidfile. This automatically requires a writable /var/run/powerdns (e.g.) for the configured user to write its control socket and pidfile in.

**Comment by pieterlexis** [comment]
Doing this will disallow the use of `socket-owner` and `socket-group` and makes the socket owned by the user running the process or the one set with `set-uid`/`set-gid`. This is inflexible.
