### ISSUE TITLE
Update blog post to recommend people to use metronome1

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#2680]
When googling for carbon server, you get http://blog.powerdns.com/2014/12/11/powerdns-graphing-as-a-service/

Also, metronome1 has no IPv6 address mentioned in the page.

**Comment by pieterlexis** [comment]
After we point new people to the new machine, we still need to figure out how to

1. Migrate the current data
2. Find a way to forward the traffic from the old machine at that point

We don't want to lose data :smile:

**Comment by Habbie** [comment]
blogpost was updated by @ahupowerdns
