### ISSUE TITLE
Api search issues

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#2685]
The flowing issues are present in the gsql code:

- d_query uninitialized in GSQLBackend::searchRecords() (master/auth-3.4.6)
- search string is passed without escaping (unlowered?) to db in GSQLBackend::searchRecords() and  GSQLBackend::searchRecords() (auth-3.4.6) 

I also wonder why this line is different in the regression-tests (master <->  auth-3.4.6)

https://github.com/PowerDNS/pdns/blob/rel/auth-3.4.6/regression-tests.api/test_Zones.py#L988
https://github.com/PowerDNS/pdns/blob/master/regression-tests.api/test_Zones.py#L988

**Comment by zeha** [comment]
zone_id = 22 looks like garbage to me...

**Comment by Habbie** [comment]
Suggestion: back out the feature for 3.4.6 - getting it right is many hours of work and there is no actual need to provide features there.

**Comment by Habbie** [comment]
#2673 #2674 for reference

**Comment by zeha** [comment]
Looks like all of this is fixed on master?
