### ISSUE TITLE
Looking for an initial dnsdist.conf 

### ISSUE THREAD

**Issue by cpu82** [PowerDNS/pdns#2693]
Hi,

We want to add an initial dnsdist.conf as simple as possible.

Any recommendation or point me out to some good examples would be helpful.

Thanks,
--CJPM

**Comment by sid3windr** [comment]
It's hard to have a default config file if you don't know where to fire queries off to, but how about:

```
newServer{address="8.8.8.8"}
newServer{address="8.8.4.4"}
```

This will simply create a default pool with 2 Google recursive DNS servers and forward all queries onto there.

**Comment by pieterlexis** [comment]
The dnsdist usecase is too wide for a single configfile, the examples in the readme should give a startingpoint.
