### ISSUE TITLE
PowerDNS Auth 3.4.5 installs dnsdist with --enable-tools switch

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#2695]
FreeBSD recently got a new port for the new dnsdist. Unfortunately this conflicts with the dns/powerdns port when you select the option to install additional tools, since pdns auth also comes with a (possibly?) broken version of dnsdist.

On FreeBSD a lot of ports use 'make install' to install software, so I'd like to request removal of dnsdist from the Makefile.

Thanks in advance.

**Comment by cpu82** [comment]
In the meanwhile, I can add `CONFLICTS= powerdns-[0-9]*` to `dnsdist/Makefile`

**Comment by Habbie** [comment]
closed by merge of #2699 and #2700

**Comment by RvdE** [comment]
a PR to update PowerDNS auth to 3.4.6 has been submitted, so the CONFLICTS is not necessary
