### ISSUE TITLE
Please add --version to rec_control and any other pdns utility it is missing from :)

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#270]
Please add --version to rec_control and any other pdns utility it is missing from.

From pdns_recursor:

(2:44pm) [seitz@renoir] [~] >  pdns_recursor --version
version: 3.2-rc1

**Comment by pieterlexis** [comment]
Let's also create manpages, docs (using the manpages), and `--help` while adding --version

- [ ] calidns
- [ ] dnsbulktest
- [ ] dnsdist
- [ ] dnsgram
- [ ] dnsreplay
- [ ] dnsscan
- [ ] dnsscope
- [ ] dnstcpbench
- [ ] dnswasher
- [ ] dumresp
- [ ] notify
- [ ] nproxy
- [ ] nsec3dig
- [ ] pdns_recursor
- [ ] pdnssec
- [ ] pdns_server
- [ ] rec_control
- [ ] zone2json
- [ ] zone2ldap
- [ ] zone2sql

**Comment by pieterlexis** [comment]
related: #294 #516
