### ISSUE TITLE
Please provide resilient config dumping tool

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#2724]
Please provide a tool that reads the PowerDNS config in the same way as pdns_server or pdns_recursor would, and writes it in a simple format to stdout.

Additionally it should report unknown config settings as errors, but not completely refuse to dump the config.

Usecases:
- distro package upgrades
- automated DB configuration from packages

**Comment by zeha** [comment]
Auth got --config=check and --config. Recursor --config=check request is in #9543 
Lets close this for now.

**Comment by Habbie** [comment]
it's not 9543
