### ISSUE TITLE
Default carbon-ourname won't replace dots with underscores

### ISSUE THREAD

**Issue by friek** [PowerDNS/pdns#2726]
As documented on [this documentation page](https://doc.powerdns.com/md/common/logging/#sending-to-carbongraphitemetronome), pdns recursor is supposed to replace the dots in a hostname with underscores. Instead, it strips everything after the first dot, leaving only the first part of the hostname as carbon-ourname.

It may be related to [this patch](https://github.com/PowerDNS/pdns/pull/2381).

**Comment by ahupowerdns** [comment]
so after some thinking, I think it is worth changing this even though it will break some setups. We might get too many collisions now between recursor.delft.corp  and recursor.denhaag.corp.

**Comment by omoerbeek** [comment]
Fixed
