### ISSUE TITLE
auth-zones appears to be broken in recursor on master

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2728]
It is as if lookups don't get to the auth zone at all. 

Suggestion:
* write an auth-zone test on a working version (like 3.7.3)
* forward-port it to master
* presumably watch it break
* possibly even fix it

**Comment by pieterlexis** [comment]
We already have a regression test for auth-zones indirectly. `regression-tests.recursor/answer-in-local-auth` tests the code added in #2604, that checks per-record in an answer if we are auth for a zone. Will test for a direct query though

**Comment by Habbie** [comment]
Sigh. My fork was 133 commits behind. Nothing to see here, move along :(
