### ISSUE TITLE
Why is modules/Makefile.am different in master compared to release/tagged version

### ISSUE THREAD

**Issue by shinsterneck** [PowerDNS/pdns#2731]
I noticed this when I tried to rebase a pull request --onto a tag/release version of pdns to create patch version that applies to a specific tag instead of master. What makes the below change?

master branch modules/Makefile.am shows multiline 

```
SUBDIRS= @moduledirs@

DIST_SUBDIRS = \
        bindbackend \
        geoipbackend \
        gmysqlbackend \
        goraclebackend \
        gpgsqlbackend \
        gsqlite3backend \
        ldapbackend \
        lmdbbackend \
        luabackend \
        mydnsbackend \
        opendbxbackend \
        oraclebackend \
        pipebackend \
        randombackend \
        remotebackend \
        tinydnsbackend

```

but in release or tagged version the Makefile.am files looks like this: (e.g: auth-3.4.6)

```
SUBDIRS=@moduledirs@
DIST_SUBDIRS=bindbackend db2backend geobackend gmysqlbackend goraclebackend gpgsqlbackend gsqlite3backend ldapbackend luabackend mydnsbackend opendbxbackend oraclebackend pipebackend tinydnsbackend remotebackend randombackend lmdbbackend geoipbackend

```

**Comment by zeha** [comment]
Because master is not 3.4.x, and master receives changes, f.e. a0a4ca43e07e10cb82ab81b604e757321f83a650

**Comment by shinsterneck** [comment]
Thanks for your quick response @zeha !

based on your response I am trying to understand now how a pull request into master gets into a release.
My pull request for masters has the Makefile.am (multiline version) and this should be working, but who or what changes this to match the non-master verison when a release is made? Or should I base the pull request on something else in the first place?

**Comment by zeha** [comment]
To quote from CONTRIBUTING.md#pull-request-guidelines:

> A pull request, at the least, should have:
> ...
> * Be filed against the master branch before any release branch

It appears the decision on features landing on already open release branches is made on a case-by-base basis. (I'm not with PowerDNS.COM B.V. ...)

**Comment by Habbie** [comment]
Hello Shin,

new features, like your backend, go onto master, and end up in a future release from there.

**Comment by shinsterneck** [comment]
Hi Habbie,

ok thanks I understood that part. I guess it was just a timing issue because auth-3.4.6 was recently released so I thought that it was based on a recent master as well. But I guess it was based on a even earlier state of master, right? Or do you merge into master and then selectivly into release branches?

Regards,
Shin

**Comment by Habbie** [comment]
3.4.6 descends from 3.4.0 with very selective backporting of stuff from master, so it is indeed quite old except for the few backported things. As you say, we merge into master and then selectively into release branches.

**Comment by shinsterneck** [comment]
Hi Habbie,

Got it! Thanks a lot for your clarification!

Regards from Japan,
Shin
