### ISSUE TITLE
Boost detection fails on Solaris

### ISSUE THREAD

**Issue by UX-admin** [PowerDNS/pdns#2745]
Boost (1.38) is installed in /opt/something/lib and /opt/something/lib/64. The ./configure fails because of line 93 in m4/boost.m4 ("tr -s '\n' ' ' |"). When this line is removed, Boost is detected without problems. If this line is present, Boost detection fails causing ./configure to fail as well.

Details:
https://github.com/PowerDNS/pdns/commit/4c8049e9d1e8a6aa822b47ee37dda08b05f79662#commitcomment-13086287

**Comment by pieterlexis** [comment]
Is this still an issue with the latest boost.m4?

**Comment by UX-admin** [comment]
Just tried with latest 4.1.0 and yes this is still an issue and will continue to be an issue so long as that "tr -s '\n' ' ' |" is boost.m4.

I have a patch which removes this line and can get past that particular failure, but it seems that there are now additional regressions:

checking for Boost headers version >= 1.35.0... /opt/something/include/boost-1_38
checking for Boost's header version... 1_38
checking for the toolset name used by Boost for g++... gcc61 -gcc
checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... no
configure: error: Boost Program Options library not found

**Comment by UX-admin** [comment]
Found out that this latest regression is due to my change of the compiler (!!!) from GCC 4.7 to GCC 6.1. While that's not PowerDNS's fault, I would seriously urge migrating away from Boost since it encodes the compiler version in the generated shared object libraries, which means that any time anyone upgrades their GCC compilers, they must rebuild Boost and then re-link all software which depends on it or continue delivering every Boost version they ever delivered.

**Comment by UX-admin** [comment]
To clarify, the original bug reported here is still a problem in addition to this new discovery I just made.

**Comment by UX-admin** [comment]
Opened https://github.com/tsuna/boost.m4/issues/116.
