### ISSUE TITLE
Load Balancing also for A and AAAA record

### ISSUE THREAD

**Issue by RoyBellingan** [PowerDNS/pdns#2747]
Having powerdns acting as a first level load balancing could be quite good due to the already replicated nature of the DNS system (multiple NS for each site ecc)

The prio field is already used, but only for the MX record type, it could be used also for serving the A and AAAA record.

This technique is already used by a lot of big caliber web site, a quick dig youtube.com / twitter.com / facebook.com will reveal ttl from 300 - 25 and most of the time a single IP returned. Or a small pool which rotate for example

s3:~ # dig twitter.com

;; ANSWER SECTION:
twitter.com.            11      IN      A       199.16.156.70
twitter.com.            11      IN      A       199.16.156.198
twitter.com.            11      IN      A       199.16.156.102
twitter.com.            11      IN      A       199.16.156.230

s3:~ # dig twitter.com
;; ANSWER SECTION:
twitter.com.            5       IN      A       199.16.156.38
twitter.com.            5       IN      A       199.16.156.230
twitter.com.            5       IN      A       199.16.156.198
twitter.com.            5       IN      A       199.16.156.70

199.16.156.102 has ben replaced by 199.16.156.38
 
So if a server goes down the disabled record is set to 1, if load goes up prio is reduced and so on.

**Comment by pieterlexis** [comment]
I'm pretty sure this can be done using the pipe or Lua backends. Also, [dnsdist](http://dnsdist.org) could maybe help in this regard?

**Comment by RoyBellingan** [comment]
Some preliminary code

https://gist.github.com/RoyBellingan/dddf713b28936f735910

In short the field prio IF GREATER THAN 0 is used to create a pool, in this pool only one is picked up, probability depends on the weight (the more the higher).

If prio is 0 or NULL the record is always appended
