### ISSUE TITLE
no notifies are sent out after dyn dns update

### ISSUE THREAD

**Issue by trefzer** [PowerDNS/pdns#2755]
if I update a domain via nsupdate (RFC2136) the serial number is incremented (even if nothing changes). But no notify to slave servers is triggered.
This leads to the situation, that slave servers are not in sync with the master (at least for the SOA serial number).

Version in use: pdns on debian jessie, 3.4.1-4+deb8u3
Backend: sqlite (for dynds domain), additional backend bind (for other slave servers).

**Comment by pieterlexis** [comment]
hi @trefzer,

* Are the slaves as NS records in the zone (or as `ALSO-NOTIFY` metadata)?
* Is `master=yes` set in `pdns.conf`?
* Has this worked before?

**Comment by trefzer** [comment]
- NS records are set. (I already tried with also-notify which does not change anything.
- yes master=yes is set
- not sure if this worked before, since it's a new dyndns setup.

running pdns_control notify domain notifies the slave correctly.
I also tried to change SOA-EDIT-DNSUPDATE which does not change the behaviour.

**Comment by trefzer** [comment]
found the error, type of domain was NATIVE, instead of MASTER !
Sorry.
