### ISSUE TITLE
When retrieving glue for a NS with two in-domain servers, we give up too easily because of 'don't use nameserver to resolve itself' rule

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2758]
wq.lc

wq.lc.                  86400   IN      NS      ns02.alexmue.info.
wq.lc.                  86400   IN      NS      ns01.alexmue.info.

to resolve, the .info servers give us the following:

;; AUTHORITY SECTION:
alexmue.info.           86400   IN      NS      ns02.alexmue.info.
alexmue.info.           86400   IN      NS      ns01.alexmue.info.

;; ADDITIONAL SECTION:
ns01.alexmue.info.      86400   IN      A       212.24.112.158
ns02.alexmue.info.      86400   IN      A       37.120.166.169

Let's assume PowerDNS tries to resolve via ns02 first, we don't believe the
glue, we are trying to get an AA=1 answer for the query.

212.24.112.158 (ns01) does not provide such an answer:

13:11:21.210634 IP 192.168.1.54.32962 > 212.24.112.158.53: 63993+ [1au] A? ns02.alexmue.info. (46)
13:11:21.238809 IP 212.24.112.158 > 192.168.1.54: ICMP 212.24.112.158 udp port 53 unreachable, length 82

So we would skip to the other server, ns02 (37.120.166.169) which is active,
and would provide a valid answer. However our logic stops us from using ns02
to resolve the IP address of ns02!

Next up, we will try to resolve via ns01. We won't ask ns01 (212.24.112.158)
itself, and should then ask ns02. This gives us the right IP address for
ns01 and ns02.

We then ask ns01. And as noted before, ns01 is down! We won't try ns02 again 
for wq.lc since we tried it already.

Servfail!

---

In another scenario, we try ns01 first. We won't ask ns01 for the IP address
of ns01, so we ask ns02. This gives us the correct IP address of ns01 and
ns02, which we both cache.

We then ask ns01 (for which we have the IP address) for wq.lc, this returns
the port unreachable error.

Next up we ask ns02 for which we have the IP address, this works, and we get
the IP address of wq.lc.

Works.

**Comment by Habbie** [comment]
Is this still a problem after all the changes we've done since?

**Comment by rgacogne** [comment]
Yes, I'm currently investigating this since the OVH outage of this morning took down two of my nameservers :)
