### ISSUE TITLE
Incompatibility between gmysql backend and two mydns backends

### ISSUE THREAD

**Issue by cgonzalez** [PowerDNS/pdns#2759]
I have a problem with PowerDNS when using more than one mydns backend.

Right now I have a PowerDNS instance with one gmysql and one mydns backend and all is working as expected. But if i add a second mydns backend then the gmysql backend fails with this error message:

```
Sep 23 10:55:30 9654c2f01b81 pdns[2218]: Backend error: lookup() passed zoneId = 38 but no such zone!
Sep 23 10:55:30 9654c2f01b81 pdns[2218]: Backend reported permanent error which prevented lookup (lookup() passed zoneId = 38 but no such zone!), aborting
```

This is similar to the problem reported here: http://mailman.powerdns.com/pipermail/pdns-users/2014-January/010430.html

I'm using pdns-3.4.6-1.el7.MIND.x86_64 on CentOS 7. I'm NOT using DNSSEC.

**Comment by cgonzalez** [comment]
Further testing shows that PowerDNS 3.4.6 can't handle multiple backends of any type (ej. two mydns or two gmysql backends). ¿Is this a bug or is by design?

**Comment by cmouse** [comment]
can you show your configuration file?

**Comment by cgonzalez** [comment]
This is my current config, using one gmysql backend andd two mydns backend.
```
setuid=pdns
setgid=pdns

allow-recursion=127.0.0.0/8,10.200.0.0/16,172.17.0.0/16
recursor=8.8.8.8

launch=gmysql:backend1,mydns:backend2,mydns:backend3

gmysql-backend1-host=powerdns_backend1.centos7_systemd.lazos.docker
gmysql-backend1-user=powerdns
gmysql-backend1-password=********
gmysql-backend1-dbname=powerdns

mydns-backend2-host=powerdns_backend2.centos7_systemd.lazos.docker
mydns-backend2-user=powerdns
mydns-backend2-password=********
mydns-backend2-dbname=mydns_hosting1

mydns-backend3-host=powerdns_backend3.centos7_systemd.lazos.docker
mydns-backend3-user=powerdns
mydns-backend3-password=********
mydns-backend3-dbname=mydns_hosting2
```

**Comment by cmouse** [comment]
and you have different zones on each backend? They are not sharing zones?

**Comment by cgonzalez** [comment]
Zones are different on each backend.

**Comment by cmouse** [comment]
have you tested with just two gsql backends?

**Comment by cgonzalez** [comment]
Not really. I've tested with two mydns backends and two pipe backends.

I'm trying to configure a single PowerDNS secondary server for multiple primary servers (one PowerDNS with gmysql backend and several cPanel using MyDNS). I'm using MySQL replication.

**Comment by cmouse** [comment]
Just asking so that we can somehow reduce this problem. I'll see if we can replicate this issue.
