### ISSUE TITLE
API: strange behavior when adding record of the same type and name

### ISSUE THREAD

**Issue by hurquiza** [PowerDNS/pdns#2763]
Say, I want to add the following records:

@ IN NS 3600 ns1.domain.com.
@ IN NS 3600 ns2.domain.com.
@ IN NS 3600 ns3.domain.com.
@ IN NS 3600 ns4.domain.com.

If I send an API request, changetype REPLACE it will only "add" the last record, overwriting the previous ones.

How can I add several RRs with the same name and type without using a not yet coded CREATE changetype?

Thanks!

**Comment by Habbie** [comment]
Can you please show your actual API request, responses, and database contents before and after the request? Thanks!

**Comment by hurquiza** [comment]
Oh this was 100% my lousy code fault, I'm sorry! Thanks for the quick answer though!

**Comment by Habbie** [comment]
Thank you for the update, we appreciate it!
