### ISSUE TITLE
error on info-all-master-query assert

### ISSUE THREAD

**Issue by allspark** [PowerDNS/pdns#2766]
Hi

in https://github.com/PowerDNS/pdns/blob/master/pdns/backends/gsql/gsqlbackend.cc#L405 is the assertion for 5 cols, the query requests 6 cols id,name,master,last_check,notified_serial and type

**Comment by Habbie** [comment]
@cmouse

**Comment by cmouse** [comment]
The default queries have been fixed on #2711

**Comment by allspark** [comment]
but here the statement selects 6 cols
https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/gmysqlbackend.cc#L102

**Comment by cmouse** [comment]
Our test suite has missed this somehow. Thanks, I'll look at it

**Comment by pieterlexis** [comment]
Closed in #2800
