### ISSUE TITLE
notify delays

### ISSUE THREAD

**Issue by xavs** [PowerDNS/pdns#2772]
Using pdns 3.4.6 in ubuntu
I noticed some delays in sending notifies master-slave, where we would like to see nearly instant notification. Correct me if I'm wrong but it looks like the check for updated domains that need to send notifies is dependant on slave-cycle-interval, as it is left outside the inner loop that sleeps one second.
https://github.com/PowerDNS/pdns/blob/master/pdns/communicator.cc#L113
Would it be better to be able to set a timer for the call to "masterUpdateCheck"?

If that's not the case, could you point me on why could we be seeing 20+ seconds delay between the API call to insert and the notifies to the slave?
thanks

**Comment by xavs** [comment]
anyone?

**Comment by Habbie** [comment]
I can confirm that slave-cycle-interval in fact also decides when a master checks for serials. Is lowering it a problem for you? Also, if you are using the API, have you considered forcing a notify through it?

**Comment by xavs** [comment]
Thanks, yes, confirming that is enough, as now we can have the master to cycle that value with a lower setting, guaranteeing a maximum delay of maybe 10 seconds. 
Thanks for the response

**Comment by Habbie** [comment]
Thanks, treating this as a doc issue then, that will be covered by #2787, so closing this!
