### ISSUE TITLE
Alphabetic Case Support

### ISSUE THREAD

**Issue by FedericoOlivieri** [PowerDNS/pdns#2784]
I was running a DNS test (from https://www.grc.com/dns/dns.htm) on my PowerDNS recursor server. From the result I could see the "Alphabetic Case" test. I din't know about this feature. Below is reported what the same website says

Alphabetic Case:
The DNS system is not sensitive to alphabetic case, so the domain “WWW.GRC.COM” is identical to “www.grc.com”. DNS is designed to ignore but preserve the alphabetic case used in queries and replies. This creates an opportunity for a DNS resolver to add additional unknown bits of “entropy” to its queries by randomly changing the case of any alphabetic characters in the queried domain name. When replies are received, only the valid replying nameserver that received the mixed-case query could know the proper case for its reply. No spoofing server would know. This would give a clever resolver another way to reject spoofed replies. We know of no nameservers that are deliberately mixing case in this way, but through this test we are helping you to keep your eye out for any.

I had a look to PDNS website but I didn't find any relevant information to understand if pdns support this feature (from the test result seems not supported)

Could be nice implement this feature on Power DNS. Hope that this help

Federico

**Comment by Habbie** [comment]
I'm confused, did the test say your recursor is failing this?

On October 10, 2015 7:43:39 PM GMT+02:00, FedericoOlivieri <notifications@github.com> wrote:
>I was running a DNS test (from https://www.grc.com/dns/dns.htm) on my
>PowerDNS recursor server. From the result I could see the "Alphabetic
>Case" test. I din't know about this feature. Below is reported what the
>same website says
>
>Alphabetic Case:
>The DNS system is not sensitive to alphabetic case, so the domain
>“WWW.GRC.COM” is identical to “www.grc.com”. DNS is designed to ignore
>but preserve the alphabetic case used in queries and replies. This
>creates an opportunity for a DNS resolver to add additional unknown
>bits of “entropy” to its queries by randomly changing the case of any
>alphabetic characters in the queried domain name. When replies are
>received, only the valid replying nameserver that received the
>mixed-case query could know the proper case for its reply. No spoofing
>server would know. This would give a clever resolver another way to
>reject spoofed replies. We know of no nameservers that are deliberately
>mixing case in this way, but through this test we are helping you to
>keep your eye out for any.
>
>I had a look to PDNS website but I didn't find any relevant information
>to understand if pdns support this feature (from the test result seems
>not supported)
>
>Could be nice implement this feature on Power DNS. Hope that this help
>
>Federico
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/2784

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by cmouse** [comment]
The feature works so that recursor randomizes outgoing query casing and accepts answers with correct casing only.

**Comment by cmouse** [comment]
Not sure how to identify whether upstream server supports this...

**Comment by Habbie** [comment]
Oh right, this is a feature request for outgoing queries. Understood!

On October 10, 2015 8:37:32 PM GMT+02:00, Aki Tuomi <notifications@github.com> wrote:
>The feature works so that recursor randomizes outgoing query casing and
>accepts answers with correct casing only.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/2784#issuecomment-147115189

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by FedericoOlivieri** [comment]
Hi,

Yes, the test failed. You can try with any PDNS recursor (or with my if you want 87.81.223.210) 
I think is related to the query reply received from upstream server: is a anti-spoof system

@cmouse How did you tested this feature? If it works, how is it possible that the test failed?

Thanks

**Comment by Habbie** [comment]
no, our recursor does not do this. Unbound has it as an optional feature - and I suspect the default being 'off' is on purpose.

**Comment by FedericoOlivieri** [comment]
Ok, there is any particular reason why is it in "off" as default? Is it possible to enable it on unbound side?
Thanks

**Comment by Habbie** [comment]
I don't know - unbound is not our product.

**Comment by FedericoOlivieri** [comment]
Hi,
I think that the scenario is different (as I understood - not sure)

When DNS recursor send query to authoritative server, it randomizes the lower an upper case characters - "DNS resolver to add additional unknown bits of “entropy” to its queries by randomly changing the case of any alphabetic characters in the queried domain name" - 
Then, when DNS resolver receive response from authoritative server it should very and match the lower/upper cases in the reply - " When replies are received, only the valid replying nameserver that received the mixed-case query could know the proper case for its reply " 
That give more protection against spoofing - " No spoofing server would know. This would give a clever resolver another way to reject spoofed replies"

No matter if the authoritative serve support this feature, I would like to understand if pdns recursor supports this feature for queries/reply between recursor and authoritative server.

Hope this can help

Federico

**Comment by Habbie** [comment]
That is how we are interpreting the question, and the answer is no, it does not support that.

**Comment by FedericoOlivieri** [comment]
Ok :) Perfect. Do you think is a valid feature to be implemented? 

Regards

**Comment by Habbie** [comment]
1. we don't know whether it works in practice - I understand unbound has a lot of code to deal with auths that do not support it
2. I am not sure this feature is useful in practice - we are pretty spoof resilient already

More information about 1 would help, but right now I am leaning towards a solid 'no'.

**Comment by FedericoOlivieri** [comment]
H think you can find some useful information and link to RFC 
https://tools.ietf.org/html/rfc4343

Anyway, thanks for your reply and time 
Federico

**Comment by cmouse** [comment]
The hard problem is knowing in advance if the remote auth is going to preserve case or not. Otherwise we'd have to accept all downcase answer in addition of correctly cased reply which would not really be helpful.

**Comment by Habbie** [comment]
I just found out we had this feature in the past, and it broke way too many things. Sorry, we're going for 'no' on this.
