### ISSUE TITLE
Newly created softhsm tokens are not visible to existing pdns_server processes

### ISSUE THREAD

**Issue by abenea** [PowerDNS/pdns#2823]
I don't know if this is a bug in softhsm 2.0 or in pdns. The C_ GetSlotList documentation states:

> Even if C_ GetSlotList is successfully called this way, it may or may not be the case that the changed slot list will be successfully recognized depending on the library implementation.  On some platforms, or earlier PKCS11 compliant libraries, it may be necessary to successfully call C_Initialize or to restart the entire system.

Currently the only way to force softhsm 2.0 to reload the tokens created by other processes seems to be calling C_Finalize and then C_Initialize.

**Comment by cmouse** [comment]
Fixed in #2825 and #2826 (for 3.4.7). The suggested thing to do here is to run with --guardian to allow PowerDNS restart and repair any PKCS#11 issues. This is probably safest and most reliable thing to do here given how diverse the behaviour of PKCS#11 drivers are.
