### ISSUE TITLE
gpgsqlbackend named incorrectly in make file

### ISSUE THREAD

**Issue by denver24312** [PowerDNS/pdns#2842]
When trying to run make, get the following error:

Making all in gpgswlbackend
/bin/bash: line 20: cd: gpgswlbackend: No such file or directory

**Comment by ahupowerdns** [comment]
which version? where are you building from? tar.gz? where did you get it? 
Thanks!

**Comment by denver24312** [comment]
Did a clone from this repository about an hour ago.  Ran bootstrap, configure then make.

**Comment by ahupowerdns** [comment]
can you check if you ran `./configure --with-modules="gpgswlbackend"` perhaps?

**Comment by denver24312** [comment]
argh - my bad sorry for the distraction - that's exactly what I did

**Comment by ahupowerdns** [comment]
no problem! enjoy PowerDNS!
