### ISSUE TITLE
Document local-address=0.0.0.0 in pdns_recursor documentation

### ISSUE THREAD

**Issue by UX-admin** [PowerDNS/pdns#2873]
Sometimes due to automation of configuration management, it is desirable to have the `pdns_recursor` listen on all interfaces. This appears to work by setting `local-address=0.0.0.0` option, but the [pdns_recursor documentation](https://doc.powerdns.com/md/manpages/pdns_recursor.1/) does not document this functionality under `local-address=...` setting.

It would be ideal if the same were also documented in the manual page for `pdns_recursor`.

**Comment by cmouse** [comment]
That's the default value, but you also need to set local-ipv6=::

**Comment by UX-admin** [comment]
In pdns_recursor 3.7.3, the default value is 127.0.0.1, so the daemon does not answer on any other addresses:

`Nov 07 20:26:33 Listening for UDP queries on 127.0.0.1:53
Nov 07 20:26:33 Listening for TCP queries on 127.0.0.1:53
Nov 07 20:26:33 Calling daemonize, going to background`

If this has changed in a newer version, it would also be desirable to document that, as that would constitute a change in semantics.

**Comment by pieterlexis** [comment]
the default of 127.0.0.1 is, as far as I can quickly see, in place since 2006 (commit 01ed3112ec9e1c23e0d7e580de60687ee8f05d66), which was released in version 3.0 of the recursor (by the look of it).

I agree we can put this in the manpage (it is in the regular documentation: https://doc.powerdns.com/md/recursor/settings/#local-address)

**Comment by UX-admin** [comment]
While `local-address=...` is documented in both, what is not documented is what setting `local-address=0.0.0.0` does, which is what I raised this issue about.

**Comment by zeha** [comment]
What `0.0.0.0` does is documented in ip(7).

**Comment by UX-admin** [comment]
On which operating system?
A quick string search of "0\.0\.0\.0" in **ip(7P)** comes up empty.

**Comment by zeha** [comment]
Apparently your enterprise OS' docs don't indicate that `INADDR_ANY` is defined to `0.0.0.0` on that very same OS. You can find more info on the special addresses in the [Linux ip(7)](http://linux.die.net/man/7/ip) manpage.

**Comment by Habbie** [comment]
What ip(7) definitely does not explain is that our daemons can reply to questions from the right IP even if routing would default to a different source.

On November 8, 2015 10:46:29 PM GMT+01:00, Christian Hofstaedtler <notifications@github.com> wrote:
>Apparently your enterprise OS' docs don't indicate that `INADDR_ANY` is
>defined to `0.0.0.0` on that very same OS. You can find more info on
>the special addresses in the [Linux
>ip(7)](http://linux.die.net/man/7/ip) manpage.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/2873#issuecomment-154876677

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Habbie** [comment]
@UX-admin can you please submit a patch with updated text to https://github.com/PowerDNS/pdns/blob/a93951216527ceac52c41cd5c7b6bb333996a523/docs/markdown/recursor/settings.md and https://github.com/PowerDNS/pdns/blob/a93951216527ceac52c41cd5c7b6bb333996a523/docs/manpages/pdns_recursor.1.md? You probably know whether this feature actually works on your system.

Closing this one, thanks!
