### ISSUE TITLE
Recursor: Don't overwrite initscript

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#2879]
It would be very nice of the pdns-recursor Makefile not to overwrite the pdns-recursor initscript on every "make install" given that it might already exist, might have site-specific modifications or point to recursor binaries located in a different installation path.
The current behaviour is defined with OS_SPECIFIC_INSTALL in pdns/sysdeps-recursor/Linux.inc
Maybe install it only if it doesn't exist yet, otherwise display a message?

Src: pdns-recursor-3.7.3
OS: CentOS 6.7

**Comment by pieterlexis** [comment]
not a problem with packages, only on builds

**Comment by pieterlexis** [comment]
We no longer install initscripts from make
