### ISSUE TITLE
dnsdist tab-completion dies easily for some reason on foreground process

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2901]

**Comment by ahupowerdns** [comment]
To reproduce, start like this:
$ ./dnsdist -C ./dnsdistconf.lua 
..

then on the > prompt, type:
> showP<tab><tab>

Now remove the P:
> show<tab><tab>

and nothing happens.
If you leave out the showP line, everything works.

**Comment by pieterlexis** [comment]
This also happens when connecting as a client to a running server
