### ISSUE TITLE
Documentation on threads and statistics

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#293]
Document how the statistics are calculated when running with multiple threads

**Comment by omoerbeek** [comment]
@Habbie: I was looking into this and wondering what particular information you would like to see. To me, the only thing worth mentioning is: almost all metrics are aggregated over multiple threads and reported as such, and the only exception is `cpu-msec-thread-N` which is reported per thread.

**Comment by Habbie** [comment]
Tickets dated 'Apr 26, 2013' with my name on them were most likely not actually written by me. I did something dumb by doing the import from Trac as myself, on Apr 26, 2013 :)

So, I have no context for this very short ticket and perhaps you should just close it.

**Comment by omoerbeek** [comment]
OK, closing; I do have some minor doc update wrt settings though, will PR soon.
