### ISSUE TITLE
the longer pdns is running the intervals of notify are also increasing

### ISSUE THREAD

**Issue by stasic** [PowerDNS/pdns#2930]
A long running instance of pdns is going to delay nofities for a quite long period.

```
pdns_control version
3.4.7
pdns_control uptime
3.91 days
date "+%T.%N"
08:38:54.344707148
DOMAIN='put_here_your_domain'
NAMESERVER='put_here_your_slave_nameserver'
tcpdump -li eth0 "ip and port 53 and host $NAMESERVER" | grep -e $DOMAIN -e 'notify' &
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
pdns_control notify-host $DOMAIN $NAMESERVER
09:08:21.091863 IP ... 18467 notify [b2&3=0x2400] SOA? ...
```

two days later I didn't saw any notify within 70 minutes and i cycled pdns

```
pdns_control uptime
5.8 days
pdns_control cycle
ok
```

here my config:

```
config-dir=/etc/powerdns
daemon=yes
guardian=yes
local-port=53
master=yes
setgid=pdns
setuid=pdns
recursor=no
slave=yes
slave-cycle-interval=1800
slave-renotify=yes
socket-dir=/var/run
version-string=powerdns
retrieval-threads=4
```

**Comment by stasic** [comment]
@Habbie @cmouse

**Comment by Habbie** [comment]
Can you include logging?

**Comment by cmouse** [comment]
Can you also include domains table and records table contents for this domain?

**Comment by stasic** [comment]
log at uptime 3.91 days
> Nov 23 08:38:47 dns-ext pdns[24112]: Notification request to host 193.171.255.77 for domain '1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa.' received
> Nov 23 19:39:20 dns-ext pdns[24112]: Received spurious notify answer for '1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa' from 193.171.255.77:53

log at uptime 5.8 days
> Nov 24 12:06:28 dns-ext pdns[24112]: Notification request to host 193.171.255.77 for domain '1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa.' received
> Nov 24 13:20:15 dns-ext pdns[24112]: Notification request to host 193.171.255.77 for domain '1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa.' received

> pdnssec check-zone 1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa
> Checked 6 records of '1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa', 0 errors, 0 warnings.


select * from domains where name='1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa';
id|name|master|last_check|type|notified_serial|account
1029|1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||MASTER|2015111700|

select * from records where domain_id =1029;
id|domain_id|name|type|content|ttl|prio|change_date|ordername|auth|disabled
215072446|1029|1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|NS|ns5.univie.ac.at|86400|0|1418910298||t|f
215072447|1029|1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|NS|ns10.univie.ac.at|86400|0|1418910345||t|f
215072448|1029|2.3.1.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|PTR|icoe.aco.net|86400|0|1418910374|0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 2|t|f
215072449|1029|0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072450|1029|0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072451|1029|0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072452|1029|0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072453|1029|0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072454|1029|0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072455|1029|0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072456|1029|0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072457|1029|0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072458|1029|0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072459|1029|0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072460|1029|0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072461|1029|0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072462|1029|1.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f
215072463|1029|3.1.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|||||||t|f

**Comment by cmouse** [comment]
Have you left out SOA record intentionally? It is not strictly necessary, but is recommended.

**Comment by stasic** [comment]
no, not intentionally!
select * from records where domain_id =1029 limit 1;
id|domain_id|name|type|content|ttl|prio|change_date|ordername|auth|disabled
215072445|1029|1.0.0.0.1.0.1.0.8.2.6.0.1.0.0.2.ip6.arpa|SOA|ns10.univie.ac.at domain-admin.univie.ac.at. 2015111700 28800 7200 604800 86400|86400|0|1418910319||t|f

**Comment by cmouse** [comment]
notifications are automatically sent only if last_notified < soa serial. Otherwise nothing is done. You can try this by resetting last_notified to NULL.

**Comment by Habbie** [comment]
To be clear, SOA record IS strictly necessary :)

On November 25, 2015 2:18:34 PM GMT+01:00, Aki Tuomi <notifications@github.com> wrote:
>Have you left out SOA record intentionally? It is not strictly
>necessary, but is recommended.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/2930#issuecomment-159604971

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by stasic** [comment]
> update domains set notified_serial = NULL where id=1029;
> UPDATE 1
> date "+%T.%N"
> 15:34:39.839131327

now I am waiting for pnds to send out NOTIFIES

**Comment by stasic** [comment]
the first NOTIFY for this zone was send out 04:44:21.964721 that's really late!

>pdns_control uptime
>1.79 days

**Comment by stasic** [comment]
I have an older version of pdns which isn't behaving this way. Maybe it's an regression?
> pdns_control version
> 3.4.1
> pdns_control uptime
> 2.3 months
> date "+%T.%N"
> 09:16:13.904524234
> tcpdump -li eth0 "ip and port 53 and host $NAMESERVER" | grep -e $DOMAIN -e 'notify' &
> pdns_control notify-host $DOMAIN $NAMESERVER
> Added to queue
> 09:16:35.008004 IP ...

**Comment by Habbie** [comment]
Is this still a problem with 4.1.0 or master?

**Comment by stasic** [comment]
I changed my setup and deleted a round 450 zones and it fixed this issue too. Maybe I'm lucky in finding an old backup of my database and I can test it with a newer version. I'll report back.

**Comment by Habbie** [comment]
Closing this; please let us know if it still happens!
