### ISSUE TITLE
Logging...lots of logging

### ISSUE THREAD

**Issue by zedaprime** [PowerDNS/pdns#2933]
Any way to change the logging level/verbosity?

So had some fun today.  Forgot that we are running thin on VM disk space.  So the 4Gb VM partition filled up within a day of use.  The syslog service has been tweaked so the symptoms are taken care of.

[kburke@dnsdist1b log]$ ps aux|grep dns
root     17951  0.0  0.1 664648  6672 ?        Ssl  Nov24   1:01 /usr/bin/dnsdist -d -p /var/run/dnsdist.pid

http://repo.powerdns.com/centos/$basearch/$releasever/dnsdist-master/debug
dnsdist-0.0.248gfcc8fef-1pdns.el6.x86_64

[kburke@dnsdist1a log]$ cat /etc/redhat-release
CentOS release 6.7 (Final)

Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got answer from 204.13.40.14:53, relayed to 162.247.88.153:48234, took 762.597 usec
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got query from 65.183.132.142:40934, relayed to 204.13.40.14:53
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got answer from 204.13.40.14:53, relayed to 65.183.132.142:40934, took 531.321 usec
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got query from 204.13.42.10:50356, relayed to 204.13.40.14:53
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got answer from 204.13.40.14:53, relayed to 204.13.42.10:50356, took 9520.28 usec
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got query from 65.183.145.162:39781, relayed to 204.13.40.14:53
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got answer from 204.13.40.14:53, relayed to 65.183.145.162:39781, took 919.219 usec
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got query from 204.13.46.162:51671, relayed to 204.13.40.14:53
Nov 25 14:07:05 dnsdist1a dnsdist[17648]: Got answer from 204.13.40.14:53, relayed to 204.13.46.162:51671, took 758.885 usec

**Comment by ahupowerdns** [comment]
hi - can you check with ps aux or ps -ef that dnsdist was not started with '-v' on the command line? Thanks.

**Comment by ahupowerdns** [comment]
oh oops you had pasted that already, sorry

**Comment by zedaprime** [comment]
:-)

**Comment by ahupowerdns** [comment]
zedaprime, could you see if a current package from http://repo.powerdns.com/ misbehaves in the same way? This looks like a package from september or possibly july, a lot has changed since then.

**Comment by zedaprime** [comment]
Its like magic...the patch is ready before i need it :-)

Yup, just checked the other pair.  They are on a barley used IP for some beta testing.  And what do you know but running dnsdist-0.0.341g61d1b96-1pdns.el6.x86_64 the message file is tiny.  

Guess I had this in testing for too long, thanks for your time ;-)

I will update the older pair soon.

**Comment by Habbie** [comment]
Some old versions would log verbosely if -p was used. Fixed 22 oct in 2cd2829360bf20ea304bd0c9680155934a67c2b0
