### ISSUE TITLE
recursor 3.7.x branch probably messes up reporting EMFILE

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2937]
```  
// returning -1 means: temporary OS error (ie, out of files), -2 means OS error
  int getSocket(const ComboAddress& toaddr, int* fd)
  {
```
However - lwres.cc thinks -1 is an error to be blamed on toaddr. This means EMFILE cause throttling!

Fixed in 4.0, this bug looks like it is present in 3.7.x as well.

**Comment by Habbie** [comment]
2ee280cfa4d6aaed243d0f994b201c9ac75925f0

**Comment by Habbie** [comment]
I carefully analyzed the unfixed code in 3.7.3 and identified two painful flows. 2ee280c fixes both and has now been cherry-picked onto rel/rec-3.7.4 as d2d4926
