### ISSUE TITLE
recursor 3.7.3 likely also neglects to reserve file descriptors

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2938]
Much like 4.0 did in 7e4a5bcca2c3cf6fa41664b3b606b3b9cc9f1b1a it appears likely we autorequest filedescriptors based on 0 running numWorkerthreads since we only set that AFTER this call.

**Comment by Habbie** [comment]
Confirmed same issue in 3.7.3, committed as fd4871c for 3.7.4
