### ISSUE TITLE
Improve reliance of option parser

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#294]
The recursor currently diverts silently from expected behavior when not providing an '=' to arguments on the CLI. This is very ambiguous for people coming from getopt-style tools since it's optional in these.

For example:

```
# Start pdns_recursor on port 5300
pdns_recursor --local-port=5300
# Start pdns_recursor on random port
pdns_recursor --local-port 5300
```

In comparison to ls (as example), which behaves identical in every case:

```
training11:~# ls
config  dnsreplay  luascripts  powerdns  zonefiles
training11:~# ls -I '*dns*'
config  luascripts  zonefiles
training11:~# ls --ignore='*dns*'
config  luascripts  zonefiles
training11:~# ls --ignore '*dns*'
config  luascripts  zonefiles
training11:~#
```

**Comment by omoerbeek** [comment]
This particular instance is fixed.
```
$ pdns_recursor --local-port 5300 
Fatal: non-option on the command line, perhaps a '--setting=123' statement missed the '='?
```
For auth as well. dnsdist seems to accept both forms.
