### ISSUE TITLE
qps setting for newServer is confusing

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#2946]
When a new server is added to dnsdist as follows:

```
newServer{address="8.8.8.8", qps=3}
```

the qps limit is only applied when the serverPolicy is set to `firstAvailable`, while not incorrect, it is confusing.

```
14:12:38 < ahu> if we rename qps to firstQPS
14:12:40 < ahu> perhaps that helps
14:13:21 < lieter> I think it will, then you could have a globalQPS as well
```

**Comment by janeczku** [comment]
Are there any good reasons why the QPS limit should not be globally honored by all policies?

**Comment by rgacogne** [comment]
I'm not sure it would play well with some of them, especially the round-robin and weight-based ones. Perhaps it might make sense for `leastOutstanding`, although I have the feeling it kind of defeats the point of using it in the first place. For now I'll update the documentation.

**Comment by rgacogne** [comment]
#3731 clarifies a bit the current situation.
