### ISSUE TITLE
mbedtls does ecdsa as well, we don't use it

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2958]
pdns_recursor _needs_ ecdsa to be successful (cloudflare friends), it is in mbedtls as well as in botan. Unless we want to force a botan dependency, we should implement ecdsa signers/verifiers based on mbedtls as well.

**Comment by Habbie** [comment]
presumably fixed in #3074, could use a check.

**Comment by Habbie** [comment]
We switched to openssl and dropped mbedtls. Closing ticket.
