### ISSUE TITLE
use pdnssec load-zone during testing?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2968]
Benefits:
- faster than zone2sql on some backends (the difference on ODBC is major)
- not limited to SQL or to the backends zone2sql supports
- no tool deps (`mysql`, `sqlite3`)

Downsides:
- even less testing of the already abysmal state of zone2sql
- can't load `nztest.com` due to out of zone data
- may do cleanup that we do not want for testing (`double.example.com` comes to mind)

**Comment by pieterlexis** [comment]
> even less testing of the already abysmal state of zone2sql

We could also drop `zone2sql` and make it a command for `pdnsutil` (perhaps even symlinking it and testing if argv[0] is zone2sql)?

> can't load nztest.com due to out of zone data

Should we allow people to shoot themselves in the foot in the first place?

> may do cleanup that we do not want for testing (double.example.com comes to mind)

We don't _have_ to test this for every backend right? The zone2XXX tests could be moved to regression-tests.nobackend?

**Comment by Habbie** [comment]
> > even less testing of the already abysmal state of zone2sql
> We could also drop `zone2sql` and make it a command for `pdnsutil` (perhaps even symlinking it and testing if argv[0] is zone2sql)?

That would make it an alias for `load-zone`, I think users do want the option to use `zone2sql` in situations.

> > can't load nztest.com due to out of zone data
> Should we allow people to shoot themselves in the foot in the first place?

No, but our tests require that -we- be allowed to ;)

> > may do cleanup that we do not want for testing (double.example.com comes to mind)
> We don't _have_ to test this for every backend right? The zone2XXX tests could be moved to regression-tests.nobackend?

Valid, both for `nztest.com` and `double.example.com`.

**Comment by pieterlexis** [comment]
> That would make it an alias for load-zone, I think users do want the option to use zone2sql in situations.

load-zone doesn't output SQL right?

**Comment by Habbie** [comment]
> `load-zone` doesn't output SQL right?

Yes, that was my point. Because `zone2sql` outputs SQL and does not talk to the database, it does not have to be part of `pdnsutil`.

**Comment by Habbie** [comment]
Mostly downsides to this. Let's not.
