### ISSUE TITLE
topSomething(...) off by one?

### ISSUE THREAD

**Issue by mmakaay** [PowerDNS/pdns#2981]
Maybe it is by design, maybe it is something that is dictated by Lua script, but when doing this:

    > topQueries(3)
       1  mail.makaay.nl.                           784 26.5%
       2  gitaar.net.                               324 11.0%
       3  ns3.gitaar.net.                           312 10.6%
       4  Rest                                     1533 51.9%

I would have expected the top 3.
Is this expected or an off by one issue?

**Comment by mmakaay** [comment]
Ah forget it, I tripped over the "Rest" aggregate line, considering it incorrectly as the fourth query.
Sorry for the disturbance, nothing to see here, move along!

**Comment by Habbie** [comment]
Thank you for closing!
