### ISSUE TITLE
dnsdist (at least) webserver does nothing on raspberry pi

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#2988]
it reads a request successfully to the socket, it arrives correctly in yahttp, but then yahttp claims it can't extract a request out of it.  It feeds the string wholly to the AsyncThing. Unsure what is going on.

RPI is of course not a large target audience, but this might be harboring a bug that we only trigger on overloaded CPUs or so, which might make it relevant.

**Comment by Habbie** [comment]
I may be able to dig into this tomorrow - I recall @rgacogne had a partial fix? Can anybody who knows update with the current state?

**Comment by ahupowerdns** [comment]
It works fine now! Close #2988.
On Dec 5, 2015 18:57, Peter van Dijk <notifications@github.com> wrote:I may be able to dig into this tomorrow - I recall @rgacogne had a partial fix? Can anybody who knows update with the current state?
