### ISSUE TITLE
devpollmplexer doesn't compile

### ISSUE THREAD

**Issue by jeffpc** [PowerDNS/pdns#3000]
sys/devpoll.h relies on sigset_t being already defined so we need to include sys/signal.h *before* including sys/devpoll.h.

This failure is masked by the fact that `devpollmplexer.cc` is optional and if it fails to compile, pdns falls back to `select`.  (The Makefile rule is of the form: `$(CXX) ... || true`.)

https://github.com/jeffpc/pdns/commit/9a39e6ddf05bdd1c64b72d8b4603ccdd29fb92ce

**Comment by jeffpc** [comment]
ok, 3.7.4 got it; master is still a WIP (I can't get it to complie at the moment)

**Comment by pieterlexis** [comment]
blocked by #3028
