### ISSUE TITLE
b71b60e breaks sendto on OpenBSD(&others?)

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3009]
```
Dec 07 11:19:09 Error sending reply with sendmsg (socket=4, dest=127.0.0.1:31360): Invalid argument
```

commit link b71b60ee73ef3c86f80a2179981eda2e61c4363f

**Comment by Habbie** [comment]
recursor not tested

**Comment by Habbie** [comment]
As requested by @ahupowerdns: indeed this is for the `local-address=0.0.0.0` default; with `127.0.0.1` the error goes away and answers come out.

**Comment by pieterlexis** [comment]
@Habbie you've tested openbsd recently, is this still an issue?

**Comment by Habbie** [comment]
#3962 fixes this.
