### ISSUE TITLE
ENT cleanups in the gsql code

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#3024]
There are several issues with the generic SQL code regarding Empty Non-Terminals:

* The `insert-empty-non-terminal-query` and `insert-ent-query` queries are redundant
* (according to @mind04) we rely too much on the default schema:

```
< mind04> we rely a lot on defaults in the sql schema
< mind04> and we can avoid this
< mind04> insert-ent-query should set NULL on ordername for example
```
This has to be investigated and fixed before the release of 4.0.0.

**Comment by zeha** [comment]
insert-ent-query could also go, no? (just bind ordername as NULL?)

**Comment by pieterlexis** [comment]
@zeha https://github.com/PowerDNS/pdns/pull/3037/files#diff-9e876ee3939f228eeb7d22ee7c6225f8R64 ?

**Comment by zeha** [comment]
You reduced from 3 queries to 2. I think it can be reduced to 1 :smile: 
insert-empty-non-terminal-query + insert-ent-query + insert-ent-order-query -> only insert-empty-non-terminal-order-query

**Comment by pieterlexis** [comment]
ah, yes :)
