### ISSUE TITLE
Secondary root zone in Recursor out of the box

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#3042]
This is a feature requests for slaving the root zone in the Recursor out of the box as described in
https://tools.ietf.org/html/draft-wkumari-dnsop-dist-root-01

**Comment by paddg** [comment]
Related document:
https://tools.ietf.org/html/rfc7706

**Comment by bionicman** [comment]
Hello. Perhaps it would be better guided Knot Resolver implementation: https://knot-resolver.readthedocs.io/en/stable/modules.html#root-on-loopback-rfc-7706

**Comment by mnordhoff** [comment]
FYI, RFC 7706 has been obsoleted by RFC 8806.

https://www.rfc-editor.org/rfc/rfc8806.html
https://tools.ietf.org/html/rfc8806

**Comment by omoerbeek** [comment]
See #10246
