### ISSUE TITLE
qname tostring function

### ISSUE THREAD

**Issue by stutiredboy** [PowerDNS/pdns#3043]
in readme.md

```
DNSName related:
newDNSName(name): make a DNSName based on this .-terminated name
member isPartOf(dnsname): is this dnsname part of that dnsname
member tostring(): return as a human friendly . terminated string
```

but when i use:
```
print("query", qname.tostring())
```
will got error log on dnsdist console:

```
Got an error in UDP question thread: [string "chunk"]:12: This function requires at least 3 parameter(s)
```

is I use this function in wrong way? 

Thanks.

**Comment by ahupowerdns** [comment]
please try qname:tostring() and let us know if that does work.

**Comment by ahupowerdns** [comment]
Ok, there was another bug hiding behind that! Can you try a92a04d too?

**Comment by stutiredboy** [comment]
1. patch https://github.com/PowerDNS/pdns/commit/a92a04dbddf91cbcb6765f72962aacbe577da0d2
2. replace `qname.tostring` to `qname:tostring`

it's work now. 

Thanks.
