### ISSUE TITLE
Disable a zone / domain / record

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#305]
Currently PowerDNS is missing a standard and supported way to disable a zone/domain/record, similar to bind (with which one could comment out entries or entire zones).

This could be accomplished right now by adding a `disabled` field to the respective tables and customizing the queries (like the "basic-query") with adding " AND disabled = 0", but this is in no way standard.

This is necessary to have some consistency for administration tools (like PowerAdmin for example). Also, administrators find it cumbersome to delete/restore a zone having for example over 100 entries manually.

**Comment by huglester** [comment]
@ahupowerdns maybe this has changed? and the is this support by default?

**Comment by ahupowerdns** [comment]
@huglester yes.
