### ISSUE TITLE
`pipe-regex` for remote-backend with http connector

### ISSUE THREAD

**Issue by romaincointepas** [PowerDNS/pdns#3065]
Is there currently a way to only use the remote-backend (http) for a subset of queries (same as `pipe-regex` for the `pipe` backend)?

**Comment by cmouse** [comment]
yes, you can return false for any domain you don't like (implement it at your end)

**Comment by romaincointepas** [comment]
Oh, good to know. However, wouldn't this affect performance as the script would be run for all queries (compared to the pipe-regex that just bypass the pipe backend)?

**Comment by cmouse** [comment]
Probably. But implementing pipe-regex in remotebackend is awfully lot more difficult, since remotebackend actually implements the backend API over some protocol, whereare pipe backend uses special protocol.

**Comment by Habbie** [comment]
Closing this as it seems like too much work for the benefit. Thank you for the suggestion!
