### ISSUE TITLE
zone2sql is  broken in 0.0.507g91b52eb-1pdns.trusty

### ISSUE THREAD

**Issue by sndrsmnk** [PowerDNS/pdns#3067]
Running 'zone2sql --gmysql --zone=./zone.db --zone-name=example.tld' with zone2sql from the .deb-release version mentioned in the subject parses just the SOA-record and then stops, logging only 'processed 1 zone, 1 record' to STDERR, and only the 'insert into domains' and one 'insert into records' line.

The zone2sql from the latest pdns-static package works fine and parses all records from the same zone.db file.

No additional errors are logged. It just stops after the SOA.

**Comment by Habbie** [comment]
Are you able/allowed to share the real file and real arguments? Or something that shows it at least?

On December 20, 2015 10:04:25 PM GMT+01:00, Sander Smeenk <notifications@github.com> wrote:
>Running 'zone2sql --gmysql --zone=/zonedb --zone-name=exampletld' with
>zone2sql from the deb-release version mentioned in the subject parses
>just the SOA-record and then stops, logging only 'processed 1 zone, 1
>record' to STDERR, and only the 'insert into domains' and one 'insert
>into records' line
>
>The zone2sql from the latest pdns-static package works fine and parses
>all records from the same zonedb file
>
>No additional errors are logged It just stops after the SOA
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/3067

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
