### ISSUE TITLE
Auth ships without PKCS#11 support

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#3110]
Would it be possible to distribute Auth 4.0 with PKCS#11 support enabled?

**Comment by Habbie** [comment]
Only if we drop Botan (#2496); now that mbed gives us ECDSA this would just cost us GOST. I'm willing to give this some thought :)

**Comment by cmouse** [comment]
Botan only conflicts with softhsm. Not pkcs#11 in general.

**Comment by Habbie** [comment]
Oh, that is true of course.

**Comment by cmouse** [comment]
I could check if this happens with softhsm2.

**Comment by Habbie** [comment]
Please do. Meanwhile I realised that even if PKCS11 in general does not conflict with Botan, shipping PKCS11+Botan means people cannot use SoftHSM with that build, right?

**Comment by cmouse** [comment]
People should not use SOFTHSM in production anyways.

**Comment by Habbie** [comment]
softhsm2 supports openssl, I read.

**Comment by Habbie** [comment]
1. Start shipping p11; tell people not to use softhsm with these packages.
2. Get GOST support from something other than botan
3. Drop botan from packages
