### ISSUE TITLE
Recursor not binding properly to IPv6 address

### ISSUE THREAD

**Issue by murrant** [PowerDNS/pdns#3130]
It seems to truncate the last part of the address.
PDNS Recursor: 3.7.3
Linux: 4.2.5-1-ARCH

config:
```
local-address=2001:5f8:7f0d:2001::a24
```

netstat -ln:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp6       0      0 2001:5f8:7f0d:2001:::53 :::*                    LISTEN
udp6       0      0 2001:5f8:7f0d:2001:::53 :::*
```

**Comment by Habbie** [comment]
Please see if it looks correct in `ss -l`

**Comment by murrant** [comment]
I thought that might be the issue.  Silly netstat was just truncating the address.  Thanks Habbie.
Now to go see why it won't answer IPv6 requests :D
