### ISSUE TITLE
[dnsdist] Expose NetmaskGroup related functions in Lua API

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#3144]
User should be able to create and populate NetmaskGroups and match CA's against it.

```Lua
nmg = newNMG()
nmg:addMask("192.168.0.1/24")
nmg:match(ComboAddress)
```

**Comment by ahupowerdns** [comment]
Good news, this was already there, and documented in:
https://github.com/PowerDNS/pdns/pull/3134/files

close #3144

**Comment by ahupowerdns** [comment]
wait, I see this is about dnsdist, sorry. Will look into it.

**Comment by janeczku** [comment]
@ahupowerdns Thanks for adding this! :smile:
