### ISSUE TITLE
Build systems hostname is determined at the wrong time

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#3159]
This is only done during the `autoreconf`, while it should (also) be done during configure. We could do this in the m4 for the reproducible build.

**Comment by Habbie** [comment]
initially reported by @benv666

**Comment by zeha** [comment]
Probably doesn't matter for reproducible, as BUILD_HOST doesn't end up in the binary.

**Comment by pieterlexis** [comment]
@zeha : if reproducible is disabled, we set it :)
