### ISSUE TITLE
pdnsutil create-zone doesn't create SOA -> zone in bad state

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3168]
```
% cat pdns.conf
launch=gsqlite3
gsqlite3-dnssec=on
gsqlite3-database=pdns.sqlite3
% cat modules/gsqlite3backend/schema.sqlite3.sql | sqlite3 pdns.sqlite3
% ./pdns/pdnsutil --config-dir=. create-zone example.org               
Creating 'example.org.'
% sqlite3 pdns.sqlite3                                                 
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> select * from domains;
1|example.org|||NATIVE||
sqlite> select * from records;
sqlite> ^D
% ./pdns/pdnsutil --config-dir=. list-zone example.org
% ./pdns/pdnsutil --config-dir=. secure-zone example.org
Securing zone with default key size
Adding ZSK with algorithm ecdsa256
Zone example.org. secured
No SOA known for 'example.org.', is such a zone in the database?
```

**Comment by zeha** [comment]
(And then, "list-keys all" doesn't really work.)

**Comment by pieterlexis** [comment]
interesting, `pdnsutil create-zone` only adds a native domain (in the first backend it finds) but neither the function in the ueberbackend nor the gsql backend will add SOA records (which makes sense, as that is another task).

The error is thrown during rectify, but there is nothing to rectify in the zone... 

I think the best course of action is to warn the user after create-zone that records (at least a SOA) will need to be added. And refuse to secure/rectify zones without a proper SOA record.

**Comment by zeha** [comment]
Actually adding the SOA should be easy (with feedRecord). I'll see to prepare a patch later on.

Adding the SOA ensures everything treats the domain as existing, incl. secure-zone, list-keys, API, ...

**Comment by pieterlexis** [comment]
I was considering that, but what about the TTL and other values (`default-soa-email`, `default-soa-name` and `default-ttl` will do a large part for you, but not all)

**Comment by zeha** [comment]
i'd just put in 0 for the serial and other stuff can default to whatever we use as default elsewhere.

**Comment by zeha** [comment]
As @ahupowerdns points out, serial of 1 should be better (0=magic)

**Comment by satishdotpatel** [comment]
[root@dns1 ~]# pdnsutil increase-serial 10.10.in-addr.arpa
No SOA for zone '10.10.in-addr.arpa'


I am getting this error, I have thousand of records on this zone and its in production how do i add SOA in prod machine?
