### ISSUE TITLE
geobackend doesn't build in current git master

### ISSUE THREAD

**Issue by Whissi** [PowerDNS/pdns#3171]
Hi,

I am trying to build from facc2e52456fe15510e3cc9b1c66799c0afce05d (using `--with-dynmodules=bind geo pipe random tinydns`) but it fails with

```
Making all in geobackend
/bin/sh: line 20: cd: geobackend: No such file or directory
Makefile:499: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
```

**Comment by Habbie** [comment]
Hi,

the geobackend was removed. We suggest you look at the geoipbackend instead. Sorry!

**Comment by Whissi** [comment]
So then there's an issue in the build system because it shouldn't start building something which was removed (=incomplete removal). Should I fill another issue? :)

**Comment by Habbie** [comment]
Yes, we've been without input validation on that for 15 years. You're the second to notice it this week. Please feel free to file an issue, yes!
