### ISSUE TITLE
Getting local port in Lua with Recursor v4 

### ISSUE THREAD

**Issue by jstrika** [PowerDNS/pdns#3177]
I'm trying to get a local port on which PDNS received request. With command ``loc:toString` I get only IP address. When I tried to get a local port using: `loc:toStringWithPort()` , I get an error: " PIPE function we executed created exception: [string "chunk"]:6: attempt to call method 'toStringWithPort' (a nil value)"

Is there a way to get a port? Here is my sample code: 

```
badips = newNMG()
badips:addMask("127.1.0.0/16")

function ipfilter(rem, loc, dh)
        print("Received at ", loc:toStringWithPort())
        return badips:match(rem)
end
```

version: PowerDNS Recursor 4.0.0-alpha1

**Comment by ahupowerdns** [comment]
Hi,

I added toStringWithPort() as a primitive locally but am finding out that the 'local' address does not HAVE a port number filled out. Turns out the kernel does not tell us. We do know however since we bound to a port, but it might be a bit more work to get this data. Will keep you posted.

**Comment by jstrika** [comment]
Hi Bert and thanks for quick response.

I don't know if it will make a difference, but did you try if kernel is returning port in any of these cases:
1. local-address=10.22.22.114:53
2. local-address=0.0.0.0:53
3. local-address=127.0.0.1:53

BTW: my initial request was for Recursor but after watching your DNS-OARC presentation, we would like to be able to get a local address and port in DNSdist as well !

**Comment by ahupowerdns** [comment]
Hi @jstrika, https://github.com/ahupowerdns/pdns/tree/local-fixes has the fixes, including for dnsdist! Waiting for checks to complete.

**Comment by jstrika** [comment]
@ahupowerdns response is superb. I'll start testing shortly

**Comment by ahupowerdns** [comment]
merged, if it works for you, please close this issue! packages on https://repo.powerdns.com/

**Comment by jstrika** [comment]
Hmm... I tried Ubuntu 14.04 "Trusty Tahr" > PowerDNS Recursor - master branch package, but I'm getting the same error. Are all packages compiled with a new commit, or I have to build it from source?

**Comment by ahupowerdns** [comment]
Can you show a script that doesn't work, and the error you get?

Also exact package you are running.

Thanks!

	Bert

**Comment by jstrika** [comment]
I downloaded Ubuntu 14.04 "Trusty Tahr" > PowerDNS Recursor - master branch package as instructed at https://repo.powerdns.com/
```
yum install epel-release yum-plugin-priorities &&
curl -o /etc/yum.repos.d/powerdns-rec-master.repo https://repo.powerdns.com/repo-files/centos-rec-master.repo &&
yum install pdns-recursor

#/pdns_recursor --version
Jan 08 15:50:58 PowerDNS Recursor 0.0.542g558bf6a (C) 2001-2015 PowerDNS.COM BV
Jan 08 15:50:58 Using 64-bits mode. Built using gcc 4.8.4 on Jan  6 2016 11:13:56 by root@49adb7620424.
```

Lua Script is simple:
```
function ipfilter(rem, loc, dh)
        print("ipfilter called, rem: ", rem:toString(), "locPort: ",loc:toStringWithPort())
        return false
end
```

The error message: "PIPE function we executed created exception: [string "chunk"]:2: attempt to call method 'toStringWithPort' (a nil value)"

**Comment by ahupowerdns** [comment]
for reasons which aren't the best, it is tostringWithPort() and tostring() in dnsdist (different case). Sorry for that!

**Comment by ahupowerdns** [comment]
@jstrika, I just checked against 'master', it works here with your script. could you maybe use this package to check: https://builder.powerdns.com/files/recursor/deb/pdns-recursor_0.0.542g558bf6a-1pdns.trusty_amd64.deb

**Comment by ahupowerdns** [comment]
@jstrika I have just learned our builders dropped behind and that package is old. Please wait a big @pieterlexis is on it!

**Comment by jstrika** [comment]
No problem, that make sense...

**Comment by pieterlexis** [comment]
latest version is  now in the repository, please `apt-get update && apt-get dist-upgrade`

**Comment by jstrika** [comment]
Thanks @pieterlexis. I did update and both "toStringWithPort()" and "getPort()" are now working! I will do more testing this afternoon.

@ahupowerdns , thank you for quick response. I wanted to test dnsdist as well, and i saw your message that I should use "tostringWithPort()" (different case). Before we spend time too much time on dnsdist, I wanted to ask:
* Is "getPort" is also supported in dnsdist?
* If we use blockFilter() or addLuaAction(), we can access "remote" but how we can get access to "local" (IP/port)?
* Are you planing to add more query functions in dnsdist? For example ipfilter and preresolve.
* Is there any way to append prefix to qname before sending to server. For example if we receive powerdns.com to forward www.powerdns.com to servers.

Maybe these dnsdist questions should be moved to another thread, since some of them are beyond "toStringWithPort()" issue...

**Comment by ahupowerdns** [comment]
Hi Jovan - getPort is also in dnsdist. the 'local' information is currently not yet available in dnsdist and that would be great as a separate ticket to remind us.
About dnsdist and ipfilter and preresolve, ipfilter is effectively blockFilter, preresolve is no stage in dnsdist: it just forwards.
About the prefixing, I contacted you separately to find out your usecase. 

Can you close this issue if your testing is successful?

**Comment by jstrika** [comment]
@ahupowerdns thank you for answers. I tested both and it is working as expected. In case others want to test:

* In __pdns_recursor__, both remote and local address and port are accesible:
```
function preresolve(dq)
        print("preresolve","called from "..dq.remoteaddr:toString().." received on "..dq.localaddr:toString().." port "..dq.localaddr:getPort())
        return false
end

function ipfilter(rem, loc, dh)
        print("ipfilter","called from "..rem:toString().." received on "..loc:toString().." port "..loc:getPort())
        return false
end
```

 * In __dnssist__, you can access only remote address and port:
```
function blockFilter(rem, qname, qtype, dh)
        print("blockFilter","called from "..rem:tostring().." port "..rem:getPort())
        return false
end
```

Regarding "local" support in dnsdist I created a new ticket at: https://github.com/PowerDNS/pdns/issues/3198
