### ISSUE TITLE
to the uninitiated, --without-modules sounds identical to --with-(dyn)modules=''

### ISSUE THREAD

**Issue by jeffpc** [PowerDNS/pdns#3185]
When trying to build pdns auth 4.0.0-alpha1, I used `--without-modules` to just get a quick build.  This failed because of #3172.  @zeha suggested using `--with-(dyn)modules=''`.  This worked, however to the uninitiated, an empty list of modules sounds the same as building without modules.

Since pdns without any backends is useless, perhaps `--without-modules` should really be an alias for `--with-modules='bind random' --with-dynmodules='pipe'`.  Alternatively, `--without-modules` could error out and suggest that the user should specify some minimum set of modules via `--with-modules` and `--with-dynmodules`.

(I reached for `--without-modules` because the build failed due to missing mysql libs/utils/etc.  It's a bit strange that `gmysql` is enabled by default.)

**Comment by Habbie** [comment]
Some clarifications:
1. #3172 is not the reason, it is about a related issue in the same code
2. making `--without-modules` an alias that gives you 3 modules makes no sense to me; erroring out sounds better than that.
3. MySQL is the original PowerDNS selling point, but maybe we can ponder changing the default, it is no longer as obviously the right default as it once was

**Comment by Habbie** [comment]
milestoned alpha2 because of item my item 3

**Comment by Habbie** [comment]
Only item 3 is left now, and I think it's not a terrible default. Closing this.
