### ISSUE TITLE
set SEP flag on combined key?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3194]
Via http://tools.ietf.org/html/rfc6781#section-3.2.3

> Therefore, it is suggested that the SEP flag be set on keys
> that are used as KSKs and not on keys that are used as ZSKs, while in
> those cases where a distinction between a KSK and ZSK is not made
> (i.e., for a Single-Type Signing Scheme), it is suggested that the
> SEP flag be set on all keys.

**Comment by pieterlexis** [comment]
This will mean that the key is shown as a KSK in the e.g. the output of `pdnsutil show-zone`. 

Secondly, we use the `keyOrZone` word in `KeyMetaData` when the flags-value is 257. Even though this key 'just' being a single-type ZSK.

**Comment by Habbie** [comment]
Then perhaps we need to improve that code :)

**Comment by pieterlexis** [comment]
maybe we could change fill `keyOrZone` with `true` if the key is in `getEntryPoints()` _and_ there is a another key with the same algo not in `getEntryPoints()`. (This function is added in #3124). I'll try to fix this issue in that PR.
