### ISSUE TITLE
In dnsdist local address and port are not exposed in Lua

### ISSUE THREAD

**Issue by jstrika** [PowerDNS/pdns#3198]
In `dnsdist --version` : 0.0.g5a3409c  , configuration file has support for Lua functions but "local" address and port are not accessible.

In example blockFilter(remote, qname, qtype, dh) from https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistconf.lua we can access "remote" address and port using ` remote:tostring(), remote:tostringWithPort(), remote:getPort()` but not the "local" address and port.

Since dnsdist was recently introduced and not yet widely implemented, did you consider keeping consistency with new pdns v4 and pass "dq" native object instead of strings like: blockFilter(dq) ? That way the community can benefit from "portable" sample code between 2 products and use someting like: `dq.remoteaddr:toStringWithPort().." to "..dq.localaddr:getPort()`

**Comment by rgacogne** [comment]
With the merge of #3233, dnsdist now uses a DNSQuestion `dq`, as close as possible as the PDNS4 one. The "local" address and port are available in this new object. Thank you for the suggestion!

**Comment by jstrika** [comment]
Fantastic, thank you!
