### ISSUE TITLE
Changeset r1714 isn't ideal

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#320]
Changeset r1714 to introduce inline ASM isn't ideal and a little wrong.

The correct descrition of the problem is that the !__sync_fetch_and_* functions are compiler builtins and only available on GCC >= 4.1 (other compiler have different availability).

So using !__sync_fetch_and_* on old GCC will fail. For example on old MacOS X Leopard (Apple GCC 4.0.x) or on RHEL-super-stable-but-outdated-sh*t. On RHEL you are prop. also bitten by this:
http://www.redhat.com/archives/rhelv5-list/2007-April/msg00092.html
I read it as if you do not take spec. care, you get GCC 3.4 as C++ compiler, prop. for endless compatiblility.

The code should prop. look like this:

```
#if defined(__GNUC__) && ( __GNUC__ < 4 || __GNUC_MINOR__ < 1 )
# if defined( __i386__ ) || defined( __x86_64__ )
static int atomic_exchange_and_add( unsigned int * pw, int dv ) 
{ 
   // int r = *pw; 
   // *pw += dv; 
   // return r; 
   int r; 

   __asm__ __volatile__ (
      "lock xadd %1, %0" : 
      "=m"( *pw ), "=r"( r ): // outputs (%0, %1), the '+' constrain does not work relaiable with all GCC versions 
      "m" ( *pw ), "1"( dv ): // inputs (%3 == %1) 
      "cc" // clobbers 
   ); 
   return r; 
} 
# else
#  error Your GCC is to old and no Arch override for __sync_fetch_and_add was given
# endif
#else
static int atomic_exchange_and_add( unsigned int * pw, int dv ) 
{ 
   return __sync_fetch_and_add(pw, dv); 
} 
#endif
```

The upside of leaving the !__sync_fetch_and_add to the compiler buildin is that the compiler understands what you want to do, so for example if you do not use the return value it maybe can use another instruction.

**Comment by Habbie** [comment]
@ahupowerdns is this still a problem we need to deal with?

**Comment by zeha** [comment]
Maybe all that old compiler support code should just go, as c++11 is now required?
