### ISSUE TITLE
./configure: line 6487: AX_LIB_SOCKET_NSL: command not found

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3203]
On master.

./configure: line 6487: AX_LIB_SOCKET_NSL: command not found

Can be seen f.e. in https://travis-ci.org/PowerDNS/pdns/jobs/101472988 line 1373

**Comment by zeha** [comment]
@cmouse :)

**Comment by cmouse** [comment]
It was in autoconf-archives. I can copy it to m4.
