### ISSUE TITLE
Wildcard A record combined with named other type record

### ISSUE THREAD

**Issue by fridi77** [PowerDNS/pdns#3206]
Hi all,

Let me start with an example of what I think goes wrong and is a bug in PowerDNS. IP addresses and domain names are made up.

definition of records:
*.example.com A 123.45.67.89
test.example.com TXT test

Now, when I perform an A record lookup for test.example.com, I would expect it should return 123.45.67.89. At least BIND does, and I've read some related RFC's, but I think PowerDNS handles this incorrect. PowerDNS can't find a corresponding A record, once a record of another type exists with the requested name. It's not only with a TXT record, I've tested this with MX records also so I suspect PowerDNS does this with all types of other records.

The current version we use is packaged with Debian 7:
#pdns_control version
3.4.1
.. with BIND configs as backend. 

I've also tested this with version 3.4.7 in another setup with a MySQL backend. I'm not using DNSSEC.

Regards,
Frido Otten

**Comment by Habbie** [comment]
Hello Frido,

I'm sorry to say this behaviour is correct, and if you look closely, you will notice BIND does the same. Closing ticket.
