### ISSUE TITLE
Deprecate the INCEPTION, INCEPTION-WEEK, EPOCH SOA-EDIT values?

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#3210]
The first two are not recommended for use and the last one is marked 'Don't combine this with AXFR' in the docs.

**Comment by Habbie** [comment]
I just told a user to pdns_control retrieve every minute; EPOCH would have the same benefit for some people. I suggest keeping EPOCH in.

**Comment by Habbie** [comment]
I'm not aware of use cases for the other two :)

**Comment by Habbie** [comment]
To be clear I'm not -against- dropping EPOCH, it's just that i can vaguely think of a usecase at least. Deprecation in 4.0 to see who complains might be a nice idea.

**Comment by jon617** [comment]
I currently use EPOCH in PowerDNS version 4.0.  Easy to convert an epoch time to human time, and I like having unlimited DNS updates per day.  DEFAULT's format of YYYYMMDDxx seems to be limited to 99 updates per day (YYYYMMDD01 to YYYYMMDD99).  Suppose I can change to using INCREASE, which has no limit, but removes the ability of converting the unix timestamp to human time.  Just my $0.02.

**Comment by james-stevens** [comment]
**Please** fix EPOCH so it can be used with non-PowerDNS servers

The current implementation is just a bad joke - all it does is return the current unixtime - which is simply ridiculous and leads to AXFR returning a higher SOA Serial than a standard UDP query !?!?!?!?!?

What it should do is capture the unixtime at the point a change is made and store it, like it would store the SOA Serial if you has used INCREMENT

**Comment by james-stevens** [comment]
> To be clear I'm not -against- dropping EPOCH, it's just that i can vaguely think of a usecase at least. Deprecation in 4.0 to see who complains might be a nice idea.

Many TLDs use UnixTime as the SOA Serial - it means, if the zone is out-of-date, you can easily tell how out-of-date it is without having to create a separate timestamp record.

The failure of the RFC SOA Serial (YYYYMMDDNN) means you are limited to 100 updates per day - not acceptable for a TLD and many large zones - we do 300 to 500 updates per day
