### ISSUE TITLE
dnsdist no longer supports ^R?

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3227]
As noted by @ahupowerdns dnsdist with libedit no longer does ^R history search.

Check/fix.

**Comment by rgacogne** [comment]
FWIW, it works on Arch with libedit 20150325_3.1.

**Comment by zeha** [comment]
Can confirm that it works on Debian sid with libedit2 3.1-20150325-1+b1.

@ahupowerdns where did you notice ^R support gone missing?

**Comment by gryphius** [comment]
it stopped working on centos6. I tried before updating and now after the update ctrl-r doesn't work anymore.

```
---> Package dnsdist.x86_64 0:0.0.598g5a3409c-1pdns.el6 will be updated
---> Package dnsdist.x86_64 0:0.0.629g439b8c5-1pdns.el6 will be an update
```

**Comment by rgacogne** [comment]
@gryphius Do you happen to know what the libedit version on CentOS 6 is?

**Comment by gryphius** [comment]
@rgacogne libedit-2.11-4.20080712cvs.1

**Comment by gryphius** [comment]
adding the following line to `~/.editrc` fixes ctrl-r for me:
```
bind "^R" em-inc-search-prev
```
workaround suggested by @rgacogne in IRC

**Comment by zeha** [comment]
Maybe the workaround for centos6 should just go into the documentation?
