### ISSUE TITLE
recursor 4.x does not build on FreeBSD because of missing c++2011 flag

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3246]
@mischapeters discovered we don't set the right C++-2011 flag in sysdeps/FreeBSD.inc. Doing the naive thing works:

22:12 <ahu> -CXXFLAGS+=-I/usr/local/include/ -DHAVE_STRCASESTR
22:12 <ahu> +CXXFLAGS+=-I/usr/local/include/ -DHAVE_STRCASESTR -std=gnu++11

**Comment by pieterlexis** [comment]
Should be fixed when #3075 is fixed

**Comment by ahupowerdns** [comment]
fixed for now
