### ISSUE TITLE
Recursor tries to find Lua in the wrong places on FreeBSD

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3247]
The right place right now appears to be -I/usr/local/include/lua51
Also, the library is now called -llua-5.1 and not -llua51
Found by @mischapeters on FreeBSD 10.2

**Comment by zeha** [comment]
Is there a pkg-config file for lua on FreeBSD? (I see that the lua pkg-config filename isn't standardised across distros, but having a list of pkg-config filenames to probe for is probably less worse than having a list of include files and lib paths to probe for...)

**Comment by mischapeters** [comment]
I believe there is.

Mischa

**Comment by zeha** [comment]
Could you figure out the filename for us, please? :)

**Comment by mischapeters** [comment]
It seems that the pc files started shipping with Lua 5.2, not 5.1.

/usr/ports/lang/lua52/files/lua-5.2.pc.in
/usr/ports/lang/lua53/files/lua-5.3.pc.in

Mischa

**Comment by Habbie** [comment]
https://svnweb.freebsd.org/ports/head/lang/lua51/pkg-plist?revision=372700&view=markup shows one for 5.1

**Comment by zeha** [comment]
FreeBSD: lua-5.1.pc lua-5.2.pc lua-5.3.pc luajit.pc
Debian: lua51.pc lua-5.2.pc lua-5.3.pc (and lua53.pc) luajit.pc
Arch: lua5.1.pc lua52.pc 
Fedora: lua.pc

**Comment by mischapeters** [comment]
pkg:~ # locate lua-5.1.pc

pkg:~ # locate lua-5.2.pc
/usr/ports/lang/lua52/files/lua-5.2.pc.in

pkg:~ # locate lua-5.3.pc
/usr/ports/lang/lua53/files/lua-5.3.pc.in

Mischa

**Comment by ahupowerdns** [comment]
resolved for now for freebsd 10.2, will be addressed more properly when we autoconf recursor.
