### ISSUE TITLE
Compilation with gpgsql module: cannot find -lnsl

### ISSUE THREAD

**Issue by Soullivaneuh** [PowerDNS/pdns#3250]
I'm trying compiling powerdns with gpgsql module for PostreSQL on Alpine linux (Docker) and I get this following error:

```bash
CXXLD  pdns_server
/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lnsl
collect2: error: ld returned 1 exit status
Makefile:1379: recipe for target 'pdnssec' failed
make[4]: *** [pdnssec] Error 1
make[4]: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lnsl
```

What is the lib `nsl`?

You can see the related PR here: https://github.com/dockervan/powerdns/pull/2

And the failing Travis job: https://travis-ci.org/dockervan/powerdns/jobs/102682305#L589-L590

**Comment by zeha** [comment]
Please attach config.log and output of a build with `make V=1`.
libnsl is a solaris thing, usually.

**Comment by Soullivaneuh** [comment]
> Please attach config.log

Where should I find this file?

**Comment by Soullivaneuh** [comment]
Here the log with `make V=1`: https://travis-ci.org/dockervan/powerdns/jobs/102784204#L880

**Comment by zeha** [comment]
Given this is a build against musl, I assume this is #1967. You'll need the referenced patches or 4.0.

**Comment by Soullivaneuh** [comment]
> You'll need the referenced patches

Do this patch of the PR https://github.com/PowerDNS/pdns/pull/1990 will work on 3.4?

Can we just compile this needed library? Where can I find it?

**Comment by zeha** [comment]
> Do this patch of the PR https://github.com/PowerDNS/pdns/pull/1990 will work on 3.4?

That's for you to find out. I'd think it would.

**Comment by Soullivaneuh** [comment]
The patch is actually not working with latest 3.4 version.

You will be able to see results here: https://travis-ci.org/dockervan/powerdns/jobs/103065381

**Comment by Soullivaneuh** [comment]
@James-TR said this patch works also on 3.4 (https://github.com/PowerDNS/pdns/issues/1967#issuecomment-68139637).

Any chance to have it on a new patch version?
