### ISSUE TITLE
dnsdist: Socket I/O not working in main Lua context

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#3252]
It seems one cannot perform Socket I/O in the main Lua context. Is this by design or something that should be working?

**This returns a "temporary failure in name resolution" error for the `http.request`**
> dnsdistconf.lua

```Lua
local http = require("socket.http")
local r, e = http.request("http://www.google.com")
if response == nil then
	warnlog(e)
end

controlSocket("0.0.0.0")
webserver("0.0.0.0:8083", "geheim2")
addLocal("0.0.0.0:5200")
setKey("MXNeLFWHUe4363BBKrY06cAsH8NWNb+Se2eXU5+Bb74=")
warnlog(string.format("Script starting %s", "up!"))
newServer("8.8.4.4") 
```

**The same operation works when called within a Lua Action**
> dnsdistconf.lua

```Lua
http = require("socket.http")
controlSocket("0.0.0.0")
webserver("0.0.0.0:8083", "geheim2")
addLocal("0.0.0.0:5200")
setKey("MXNeLFWHUe4363BBKrY06cAsH8NWNb+Se2eXU5+Bb74=")
warnlog(string.format("Script starting %s", "up!"))
newServer("8.8.4.4") 

function testHandler(remote, qname, qtype, dh, len)
    local r, e = http.request("http://www.google.com")
    if response == nil then
        warnlog(e)
    end
    return DNSAction.None, ""
end

addLuaAction("0.0.0.0/0", testHandler)
```

**Comment by ahupowerdns** [comment]
can you strace the process while this happens at startup?

**Comment by rgacogne** [comment]
FWIW, it works for me with the current head and lua 5.2 on Arch Linux (testing 'r' against nil instead of 'response').

**Comment by janeczku** [comment]
I updated to the current head and can confirm that this is not an issue anymore.

**Comment by ahupowerdns** [comment]
(just one note, if you are going to do http from a *handler*, performance is going to be horrible! It will block all of dnsdist for each packet!)

**Comment by janeczku** [comment]
@ahupowerdns Yeah i know. I am doing Unix socket calls though, hence the blocking should be minimal - but i am still looking for a better way to do per query remote calls. I am quite keen to try out the asynchronous UDP querying in Recursor Lua. I noticed that https://github.com/PowerDNS/pdns/blob/master/pdns/lua-recursor.cc contains the UDPQueryResponse Lua wrapper code. Does that mean that there will be yet another 3.X release with that feature before 4.X goes stable?

**Comment by ahupowerdns** [comment]
No, there will not be a 3.x release with UDPQueryResponse in there. 3.x is bugfixes & security only from now on. We're working hard on releasing 4.0.0!

**Comment by janeczku** [comment]
Sounds good :+1:
