### ISSUE TITLE
Make the API URL discoverable

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#3253]
In the docs for the v3.0 API, 'URL: /' is mentioned. which would return the full path to the API. That seems to have changed in 4.0, to 'URL: /api/v1'. But that already includes a version in the path. I'm guessing that's not what you want.

So, I'd suggest that a GET /api/ returns the same values as 'api/v1', and that tools (such as nsedit) can always do that to construct the full URL to the current API.

I have been looking into fixing it myself, but I think it would be wise to make it a (default) compile-time option since most of the PowerDNS suite seems to be using that API-path.

**Comment by zeha** [comment]
I'm having a bit of a trouble with that - what will a client that only speaks v1 do when we point those urls to v2?

**Comment by stbuehler** [comment]
I think the basic goal should be that the "base" API URL stays the same (so no configuration changes are necessary in the client), and that version compatibility is ensured.

I see the following options:
- have a "discovery" page at the base URL listing all supported versions in a JSON array (probably exactly one)
- have the server send an HTTP header (only for error pages?) for each supported version (probably exactly one) defining the base URI for that version, like 'X-API-V1-URL: /api/v1'
- have clients send all supported versions in a HTTP header; server rejects unless it finds its own version. All versions use the same URIs.

If the server always only supports one version, the client can cache the version long term - if the server upgrades the client gets an error and flushes the cached version.
If the server might support more than one version, the client should either cache only short term, or the server must send all supported versions in each reply.

**Comment by tuxis-ie** [comment]
@zeha Incompatability is the clients responsability, if you ask me.

@stbuehler I think the first option is the safest and simplest, for both the pdns-end as for the clients.

**Comment by zeha** [comment]
As discussed on IRC, I expect complete non-backwards-compat breakage if we bump the version, so don't rely on API v1 staying in the list. But then at least you know you're talking to a server speaking another language. :)

**Comment by tuxis-ie** [comment]
Yes, we're clear on that. Thanks!
