### ISSUE TITLE
Connecting to dnsdist console prints 'Added downstream 0.0.0.0'

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3257]
pi@raspberrypi ~/pdns/pdns/dnsdistdist $ sudo ./dnsdist -C plus.conf -c
Read configuration from 'plus.conf'
"Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0
Added downstream server 0.0.0.0:0"

This comes from the constructor, which also opens sockets and stuff. We should probably not be creating those objects in client mode.

**Comment by rgacogne** [comment]
I guess the reason we do is that newServer() returns a DownstreamState, so not returning anything might cause an error if the returned value is used later in the configuration. Do you think we should change that?

**Comment by ahupowerdns** [comment]
well, I don't know about the solution. I do know we are creating actual network connections to 0.0.0.0 now which is pretty odd in client mode. So a solution might be to recognize 'fake' entries?
