### ISSUE TITLE
pdns-recursor: Use the source netmask provided by the client for edns-client-subnet queries

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#3262]
According to [draft-ietf-dnsop-edns-client-subnet-00](https://tools.ietf.org/html/draft-ietf-dnsop-edns-client-subnet-00#section-6.1) para 6.1 a recursive resolver may take into account a edns-client-subnet option included in the query from a client. In that case the source netmask provided by the client will be used in the subsequent query to the authoritative nameserver.

Currently, in the following scenario an incorrect client source netmask will be provided to the nameserver because pdns recursor disregards the edns source netmask in the query from dnsdist:

```

  ┌─STUB RESOLVER─┐                                          
  │               │                                          
  │ 192.168.0.10  │                                          
  └───────────────┘                                          
         │                                                   
         │query: www.powerdns.com                            
         │                                                  
         ▼                                                   
  ┌───DNSDIST────┐ ┌─────────────────────────────────────┐   
  │              │ │newServer({address="10.173.1.20:54", │   
  │              │ │useClientSubnet=true})               │░░░
  │ 10.173.1.10  │ └─────────────────────────────────────┘░░░
  │              │    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  │              │    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  └──────────────┘                                           
         │                                                   
         │edns-client-subnet                                 
         │  192.168.0.0/24                                   
         │                                                   
         ▼                                                   
  ┌PDNS RECURSOR─┐ ┌─────────────────────────────────────┐   
  │              │ │edns-subnet-whitelist="powerdns.com" │   
  │              │ └─────────────────────────────────────┘░░░
  │ 10.173.1.20  │    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  │              │    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  │              │                                           
  └──────────────┘                                           
         │                                                   
         │edns-client-subnet                                 
         │  10.173.1.0/24                                    
         │                                                   
         ▼                                                   
  ┌──NAMESERVER──┐                                           
  │              │                                           
  └──────────────┘                                           
```

**Comment by pieterlexis** [comment]
Reading section 6.1 of that document leads me to the following conclusions:

1. If a resolver gets a subnetmask of `0`, it is requested not to add ends subnet information (paragraph 3)
2. A resolver can ignore all the edns subnet options from a client (stub resolver) (paragraph 4)

I'd think adding an option like `process-incoming-edns-subnet` with 3 options:

- `no` -- Ignore all EDNS subnet options in incoming queries
- `zero-only` -- Ignore all EDNS subnet options except the zero subnet
- `passthrough` -- If EDNS subnet options are set, pass then along

Comments?

**Comment by rgacogne** [comment]
Please be aware that this section has significantly changed in the last revision of the document [1]. It seems to be mostly consistent with your conclusions, though. 

[1]: https://tools.ietf.org/html/draft-ietf-dnsop-edns-client-subnet-06#section-7.1

**Comment by janeczku** [comment]
Interesting. The main change seems to be that it is now MANDATORY to process the subnetmask EDNS client subnet option in incoming queries.

So the hardcoded behavior of the recursor should be:

`subnetmask == 0`: Don't include ECS option in outgoing query OR use the recursor's IP 
`subnetmask > 0`: Pass along if shorter than 24

And the configurable behavior:

option `use-incoming-edns-subnet-addr`

* `no` -- ignore the EDNS subnet option source address in incoming queries
* `yes` -- pass along EDSN subnet option source address

**Comment by janeczku** [comment]
@rgacogne @pieterlexis Will this make it into into v4? Would be great!
