### ISSUE TITLE
Drop automatic algo 5->algo 7 upgrade

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#3267]
Right now, `DNSSECKeeper::getKeys()` fakes algo 7 when it finds a zone with key algo 5 and NSEC3 semantics. This means that the database content is actually inconsistent with the output of the nameserver. We should

4.0.0:
- [x] Have `pdnsutil check-zone` warn about this

4.1.0:
- [x] Log a warning when such a key is read

4.2.0:
- [ ] Remove the code that fakes this
- [ ] Have `pdnsutil check-zone` error about this
- [ ] ~~Have a `pdnsutil fix-algo ZONE` command to fix this in the database~~

**Comment by pieterlexis** [comment]
I consider adding a deprecation warning for this in 4.0 and doing the actual change in 4.1.

**Comment by pieterlexis** [comment]
Having a fix-zone would mean we'd have to rewrite the whole content field in the database. This is more trouble than it is worth. We'll just have check-zone warn about this.

**Comment by Habbie** [comment]
Reopened this and rearranged the TODO list.

**Comment by pieterlexis** [comment]
So we do need to add a deprecation warning in the log when reading a 'wrong key' at runtime. Added to the list.

**Comment by Habbie** [comment]
Interestingly, nobody has ever mentioned seeing the log message. I suspect this is not happening widely. Let's kill it all in 4.3!
