### ISSUE TITLE
Recursor: udpQueryResponse broken in 4.x Lua code

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#3276]
Setting any of
```Lua
dq.udpQueryDest
dq.udpCallback
dq.udpQuery
```
will result in the following error:
> STL error (www.example.com./A from 127.0.0.1): No setter found

Also, the code that handles `udpQueryResponse` results in an endless loop as it doesn't actually evaluate the callback function:
https://github.com/PowerDNS/pdns/blob/master/pdns/lua-recursor4.cc#L388-L406

**Comment by ahupowerdns** [comment]
thank you - unsure where that code went, fixing it now.

**Comment by janeczku** [comment]
FYI: I ported kvresp.cc to Go (sorry, not a Python guy myself :sweat_smile:)
https://github.com/janeczku/kvresp

**Comment by ahupowerdns** [comment]
ok - as an update, I'm about 75% done fixing the Lua part of the story. I also sent you email btw, but since our mailserver died, I may not see it!

**Comment by janeczku** [comment]
:+1: prima
