### ISSUE TITLE
dnsdist - crash with Assertion `is_valid(m_buff)' failed.

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3277]
Hello,

I have three crashes today:

Jan 21 09:11:30 rzt-lvs1 dnsdist[25367]: dnsdist: /usr/include/boost/circular_buffer/details.hpp:303: boost::cb_details::iterator<Buff, Traits>& boost::cb_details::iterator<Buff, Traits>::operator++() [with Buff = boost::circular_buffer<Rings::Response>; Traits = boost::cb_details::nonconst_traits<std::allocator<Rings::Response> >]: Assertion `is_valid(m_buff)' failed.
Jan 21 09:11:30 rzt-lvs1 systemd[1]: dnsdist.service: main process exited, code=killed, status=6/ABRT
Jan 21 09:11:30 rzt-lvs1 systemd[1]: Unit dnsdist.service entered failed state.

Debian 8.2, dnsdist 0.0.651g10f702c, up to 200qps, 500 qps in peaks, 4 servers in the pool, basic config with just these dynnamic blocks:

function maintenance()
    addDynBlocks(exceedNXDOMAINs(50, 10), "Exceeded query rate with NXDOMAIN response (50q/10s)", 30)
    addDynBlocks(exceedServfails(20, 10), "Exceeded query rate with SERVFAIL response (20q/10s)", 30)
end

With regards
Ales

**Comment by ahupowerdns** [comment]
https://twitter.com/PowerDNS_Bert/status/690112291644268546 we are on it!

**Comment by rygl** [comment]
I can see it with 0.0.658g9c737f8 as well:

Jan 21 12:34:22 rzt-lvs1 dnsdist[22515]: dnsdist: /usr/include/boost/circular_buffer/details.hpp:303: boost::cb_details::iterator<Buff, Traits>& boost::cb_details::iterator<Buff, Traits>::operator++() [with Buff = boost::circular_buffer<Rings::Response>; Traits = boost::cb_details::nonconst_traits<std::allocator<Rings::Response> >]: Assertion `is_valid(m_buff)' failed.
Jan 21 12:34:22 rzt-lvs1 systemd[1]: dnsdist.service: main process exited, code=killed, status=6/ABRT
