### ISSUE TITLE
Debian package - systemd unit file overwritten unconditionally when upgrading

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3282]
Hello,
I have found out that whenever I upgrade to latest dnsdist package from pdns Debian repo, my customized unit file /lib/systemd/system/dnsdist.service is always overwritten by the package unit file. Original file is not backed up to .dpkg-old. IMHO users could be prompted what to do here...
Thanks
Ales

**Comment by pieterlexis** [comment]
For systemd, user changes must be made in `/etc/systemd/system/*.service` see also the [systemd documentation](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path)

**Comment by rygl** [comment]
Thanks & sorry.
