### ISSUE TITLE
Build dnsdist on openwrt

### ISSUE THREAD

**Issue by debiansid** [PowerDNS/pdns#3294]
Is it possible to port dnsdist on openwrt?

**Comment by ahupowerdns** [comment]
I don't know. If you have a recent compiler toolchain, then it should work. But embedded platforms sometimes leave out surprising things. The hardest requirement may be g++ 4.8+ and a recentish Boost.

**Comment by ahupowerdns** [comment]
dnsdist uses around 6MB of memory at runtime, probably less on a 32 bit platform, so we should be good on that front.

**Comment by ahupowerdns** [comment]
openwrt appears to have a very recent gcc these days

**Comment by Habbie** [comment]
@debiansid what is your opkg package source? (see opkg.conf)

**Comment by debiansid** [comment]
@Habbie official one.

**Comment by Habbie** [comment]
@debiansid this does not tell me anything useful. What's in your opkg.conf?

**Comment by debiansid** [comment]
@Habbie 
dest root /
dest ram /
tmplists_dir ext 
/var/opkg-listsoption 
overlay_root /overlay

**Comment by Habbie** [comment]
Ah, so there really is a default. Can you find out the URL, if necessary just from installing a package and noting the output of opkg?

**Comment by debiansid** [comment]
opkg update
Downloading http://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/designated_driver_base.
Downloading http://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/telephony/Packages.gz

**Comment by debiansid** [comment]
Or you can set to any url that contains packages

**Comment by Habbie** [comment]
Of course, but the URL helps me understand what platform and environment you are in. Thanks. We intend to look into opkg packaging sometime soon (but don't expect packages this week).

**Comment by debiansid** [comment]
@Habbie thanks,I also have x86 based openwrt

**Comment by James-TR** [comment]
I have created a package for dnsdist-1.3.3 in the OpenWRT 'packages' feed on GitHub in PR openwrt/packages#9031 which is pending review

**Comment by pieterlexis** [comment]
Fixed by @James-TR in https://github.com/openwrt/packages/pull/9031
