### ISSUE TITLE
Got an error in UDP question thread: Found compressed label, instructed not to follow & others

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3304]
Hi,
after extending my playground to a huge pool of mobile clients I can see thousands of errors like:

`Jan 25 17:57:58 ctx-lvs1 dnsdist[18460]: Got an error in UDP question thread: Found compressed label, instructed not to follow`

With lower rate I can see:
`Jan 25 17:57:53 ctx-lvs1 dnsdist[18460]: Got an error in UDP question thread: Found an invalid label length in qname`

And couple of these:

`Jan 25 15:31:20 ctx-lvs1 dnsdist[18460]: Got an error in UDP question thread: name too long to append`

I suppose that it could be just an indication of a malformed query but I am reporting it for sure...

Ales

**Comment by rygl** [comment]
dnsdist 0.0.666g889e865

**Comment by ahupowerdns** [comment]
could you make a guess which fraction of your queries generate this error? 0.1%?

**Comment by rygl** [comment]
very small... I have this error once per 2-3 sec. Comparing to 25k qps it is 4e-05. If you add some more details (IP, query ID) to the log (would be useful in general) I could capture the incoming traffic and find the particular query.

**Comment by rgacogne** [comment]
As a reminder, we need to add (optionally?) the source IP and query ID to this error message when possible.

**Comment by rgacogne** [comment]
The initial report was caused by malformed queries, and we recently added the source IP and query ID to this error message.
