### ISSUE TITLE
./configure doesn't check for pandoc

### ISSUE THREAD

**Issue by cyclops1982** [PowerDNS/pdns#3306]
HI,

./configure completes succesfully without pandoc, but building doesn't:

```
  CXXLD    libpipebackend.la
make[3]: Leaving directory `/data/home/cyclops/dev/pdns/modules/pipebackend'
make[3]: Entering directory `/data/home/cyclops/dev/pdns/modules'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/data/home/cyclops/dev/pdns/modules'
make[2]: Leaving directory `/data/home/cyclops/dev/pdns/modules'
Making all in codedocs
make[2]: Entering directory `/data/home/cyclops/dev/pdns/codedocs'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/data/home/cyclops/dev/pdns/codedocs'
Making all in docs
make[2]: Entering directory `/data/home/cyclops/dev/pdns/docs'
echo "You need pandoc to generate the manpages"
You need pandoc to generate the manpages
exit 1
make[2]: *** [pdnsutil.1] Error 1
make[2]: Leaving directory `/data/home/cyclops/dev/pdns/docs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/home/cyclops/dev/pdns'
make: *** [all] Error 2
```

**Comment by pieterlexis** [comment]
Hi @cyclops1982,

When running from git this is needed, when the user has a tarball, it contains the manpages already and no pandoc is needed. powerdns can still be built with `make -C pdns`, but I agree we should perhaps fail is pandoc is not installed and the generate manpages are missing

**Comment by benv666** [comment]
Yesterday I tried to build pdns 4.0.1 from the release tarball on a Slackware64 machine without pandoc. Configure correctly detected the lack of pandoc and went through fine.
My slackbuild build script starts off with a 'make clean' however, which removed the provided manpages from the tarball after which make broke on the doc directory due to a lack of pandoc.
