### ISSUE TITLE
./configure doesn't check for yacc

### ISSUE THREAD

**Issue by cyclops1982** [PowerDNS/pdns#3307]
Hi,

./configure doesn't check for the presense of yacc, resulting in this error:
make[2]: Entering directory `/data/home/cyclops/dev/pdns/pdns'
  YACC     bindparser.cc
../build-aux/ylwrap: line 113: yacc: command not found
make[2]: *** [bindparser.cc] Error 1
make[2]: Leaving directory `/data/home/cyclops/dev/pdns/pdns'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/home/cyclops/dev/pdns'
make: *** [all] Error 2

Obviously minor issue as it's clear that the bison package is needed to compile powerdns. But would be nice if configure checked that.

**Comment by pieterlexis** [comment]
it should check this, are you running form git or a tarball? And is this auth or recursor?

**Comment by cyclops1982** [comment]
from git, building auth.

**Comment by pieterlexis** [comment]
Hi, doing the same I get the following error from `./configure`:

```
checking for egrep... /bin/grep -E
checking if bison is the parser generator... no
configure: error: bison is missing and you don't have ./pdns/bindparser.cc. Please install bison
```

I started with the docker ubuntu:trusty image,  and did an `apt-get update && apt-get dist-upgrade`. After this I installed `git`, `autoconf` , `libtool`, `pkg-config`, ran `./bootstrap` and `./configure`.

Could you provide a more complete reproduction instruction?

**Comment by cyclops1982** [comment]
Hi,

Since i took an old repro and did a `git pull` to update it, i think my configure still had cache around. After a `git clean`, i get the same result.

So, my bad!
