### ISSUE TITLE
dnsdist - crash with terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3314]
Hi,

`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: terminate called after throwing an instance of 'std::bad_alloc'`
`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: what():  std::bad_alloc`
`Jan 28 09:54:30 ctx-lvs1 systemd[1]: dnsdist.service: main process exited, code=killed, status=6/ABRT`
`Jan 28 09:54:30 ctx-lvs1 systemd[1]: Unit dnsdist.service entered failed state.`

dnsdist 0.0.667gdee7181

Ales

**Comment by ahupowerdns** [comment]
rygl, how long was it up for when this happened? Also, could we seduce you to drop by the #powerdns IRC channel? https://www.powerdns.com/opensource.html has the details (search for irc)

**Comment by rygl** [comment]
~ 2 days. Give me some time for irc... have to finish something.

**Comment by rgacogne** [comment]
Sure, thank you! Anything relevant in your logs? By any chance, would you happen to be exporting metrics via carbon?

**Comment by ahupowerdns** [comment]
(we export memory usage, is why)

**Comment by rygl** [comment]
Seems that not. Just a lot of:
`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: Got an error in UDP question thread: Found compressed label, instructed not to follow`
`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: Got an error in UDP question thread: Found compressed label, instructed not to follow`
`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: Got an error in UDP question thread: Found compressed label, instructed not to follow`
`Jan 28 09:54:30 ctx-lvs1 dnsdist[23424]: terminate called after throwing an instance of 'std::bad_alloc'`

And a lot of UDP checksum errors:
`[Thu Jan 28 11:00:31 2016] UDP: bad checksum. From 10.93.41.91:59405 to 93.153.117.33:53 ulen 35`
`[Thu Jan 28 11:01:13 2016] UDP: bad checksum. From 10.77.105.95:54290 to 93.153.117.33:53 ulen 46`

A.

**Comment by rygl** [comment]
I will try carbon, I ma not using it...yet

**Comment by rgacogne** [comment]
If you don't have an existing setup, you might want to look at metronome [1]. It's very easy to set up.

[1]: https://github.com/ahupowerdns/metronome

**Comment by rygl** [comment]
I am failing to compile it. I downloaded the zip from the link above and followed instructions

`rygl@congo:~/devel/metronome-master$ make`
`fatal: Not a git repository (or any of the parent directories): .git
g++ -Wall -O3 -ggdb -I. -I yahttp/yahttp  -pthread -MMD -MP -DYAHTTP_MAX_URL_LENGTH=16384 -std=gnu++0x    -c -o metronome.o metronome.cc`
`In file included from metronome.cc:2:0:`
`iputils.hh:36:34: fatal error: boost/lexical_cast.hpp: No such file or directory`
 `#include <boost/lexical_cast.hpp>`
                                  ^
`compilation terminated.`
`<builtin>: recipe for target 'metronome.o' failed`
`make: *** [metronome.o] Error 1`

**Comment by rygl** [comment]
...And have one more crash with an identical error:

**Comment by ahupowerdns** [comment]
rygl, can you check your memory usage for your busy dnsdists? is it increasing steadily? you can get this with dumpStats() on the console, memory-usage I think.

**Comment by rygl** [comment]
Yes, it is increasing:
`root@ctx-lvs1:~# for i in {1..25}; do dnsdist -c -e 'dumpStats()' | grep real-memory-usage ; sleep 5 ;done`
`empty-queries                    12    real-memory-usage           91152384`
`empty-queries                    12    real-memory-usage           91373568`
`empty-queries                    12    real-memory-usage           91590656`
`empty-queries                    12    real-memory-usage           91799552`
`empty-queries                    12    real-memory-usage           91987968`
`empty-queries                    12    real-memory-usage           92205056`
`empty-queries                    12    real-memory-usage           92401664`
`empty-queries                    14    real-memory-usage           92610560`
`empty-queries                    14    real-memory-usage           92815360`
`empty-queries                    14    real-memory-usage           93016064`
`empty-queries                    14    real-memory-usage           93286400`
`empty-queries                    14    real-memory-usage           93630464`
`empty-queries                    14    real-memory-usage           93880320`
`empty-queries                    14    real-memory-usage           94097408`
`empty-queries                    14    real-memory-usage           94314496`

The 2nd site does not do it:

`root@rzt-lvs1:~# for i in {1..25}; do dnsdist -c -e 'dumpStats()' | grep real-memory-usage ; sleep 5 ;done`
`empty-queries               2011849    real-memory-usage           42045440`
`empty-queries               2011889    real-memory-usage           42045440`
`empty-queries               2012183    real-memory-usage           42045440`
`empty-queries               2012223    real-memory-usage           42045440`
`empty-queries               2012520    real-memory-usage           42045440`

Hope this helps..

**Comment by ahupowerdns** [comment]
ok - if you could (privately) share the script you are running on the leaking node, that would be great. This per our 'exceptional support' for dnsdist early deployments. powerdns.support@powerdns.com

**Comment by rgacogne** [comment]
@rygl If you haven't seen that issue again since the initial report, I'd propose we close this for now.

**Comment by rygl** [comment]
Feel free to close it.
A.

**Comment by rgacogne** [comment]
Thanks, please don't hesitate to re-open it if you have the slightest indication that the issue still exists.
