### ISSUE TITLE
pdnsutil list-zones does not list zones that haven't got a SOA record yet (4.0.0)

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3318]
this is because the SQL demands a SOA record:
select domains.id, domains.name, records.content, domains.type, domains.master, domains.notified_serial, domains.last_check, domains.account from domains LEFT JOIN records ON records.domain_id=domains.id AND records.type='SOA' AND records.name=domains.name WHERE records.disabled=0 OR :include_disabled

If you just created a slave zone, and it hasn't retrieved yet, it is invisible. Unsure if this can be solved from SQL?

**Comment by hlindqvist** [comment]
Based on the query, it appears that currently such a zone would be included if you could specify `include_disabled`. I don't know if it makes sense for it to count as disabled per se, and there doesn't currently exist a way to specify include_disabled via pdnsutil.

If you always want zones with no SOA to be included (may or may not make sense if there are other scenarios where that query is used) you could so something like `... WHERE records.id IS NULL OR records.disabled=0 OR :include_disabled`.

**Comment by ahupowerdns** [comment]
@hlindqvist thank you for this insight, it worked!

**Comment by zeha** [comment]
Zones with no SOA are severely broken and expose different, inconsistent behaviour in various parts of core, as seen during API development. Tread with care :-)

**Comment by ahupowerdns** [comment]
(zones without SOA are also freshly configured slave zones - it is weird if they don't appear in list-all-zones)
