### ISSUE TITLE
dnsdist - dynBlock logs just the first hit

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3323]
Hi,
let's have a simple  maintenance function:
```
function maintenance()
        addDynBlocks(exceedQRate(20, 5), "Exceeded query rate", 3)
        addDynBlocks(exceedNXDOMAINs(5, 5), "Exceeded query rate with NXDOMAIN response", 3)
end
```

The issue is that just 1st hit is being logged. If I run a test with queries in a loop, the dynBlock is being installed and is expiring but without any notice to the log.

A.

**Comment by ahupowerdns** [comment]
well this was by design - otherwise you get loads of repeated notifications for the same IP address. Or is this not what you mean? The design is that per IP address you get one notification when we install the block. If the block expires and it gets reinstated, then you'd get another notification.
