### ISSUE TITLE
pdnsutil needs to be linked with the same lua lib as pdns_server

### ISSUE THREAD

**Issue by a6502** [PowerDNS/pdns#3330]
pdnsutil currently is not linked with the $(LUA_LIBS), which causes the weird error of a libluabackend.so seeming to load correctly and then not being able to 'require' a lua-module that is a shared library itself.

adding $(LUA_LIBS) to pdnsutil_LDADD fixes that problem.

no patch/pr because i have no idea how to fix this in the automake world.

**Comment by Habbie** [comment]
Can you show your full configure line, and the output of `make V=1`  after removing `pdnsutil`, `pdns_server` and the luabackend `.so` file?

On February 3, 2016 5:33:38 PM GMT+01:00, Wieger Opmeer <notifications@github.com> wrote:
>
>pdnsutil currently is not linked with the $(LUA_LIBS), which causes the
>weird error of a libluabackendso seeming to load correctly and then not
>being able to 'require' a lua-module that is a shared library itself
>
>adding $(LUA_LIBS) to pdnsutil_LDADD fixes that problem
>
>no patch/pr because i have no idea how to fix this in the automake
>world
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/3330

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by a6502** [comment]
Note: it was using the pdns-4.0.0~alpha1 debian source package..

  $ ./configure --host=x86_64-linux-gnu --build=x86_64-linux-gnu --prefix=/usr --sysconfdir=/etc/powerdns --mandir=${prefix}/share/man --infodir=${prefix}/share/info --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib --with-dynmodules=bind ldap pipe gmysql gpgsql gsqlite3 geoip lua mydns remote tinydns --with-modules= --with-system-mbedtls --with-pgsql-includes=/usr/include/postgresql --disable-cryptopp --enable-botan1.10 --enable-tools --enable-unit-tests --enable-reproducible

wieger@Galway:~/src/pdns-4.0.0~alpha1$ make V=1
make  all-recursive
make[1]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1'
Making all in ext
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext'
Making all in yahttp
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp'
Making all in yahttp
make[4]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp/yahttp'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp/yahttp'
make[4]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp'
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp'
Making all in rapidjson
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/rapidjson'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/rapidjson'
Making all in json11
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/json11'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext/json11'
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/ext'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext'
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/ext'
Making all in modules
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules'
Making all in bindbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/bindbackend'
make  all-am
make[4]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/bindbackend'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/bindbackend'
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/bindbackend'
Making all in ldapbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/ldapbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/ldapbackend'
Making all in pipebackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/pipebackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/pipebackend'
Making all in gmysqlbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gmysqlbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gmysqlbackend'
Making all in gpgsqlbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gpgsqlbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gpgsqlbackend'
Making all in gsqlite3backend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gsqlite3backend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/gsqlite3backend'
Making all in geoipbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/geoipbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/geoipbackend'
Making all in luabackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/luabackend'
/bin/bash ../../libtool  --tag=CXX   --mode=link x86_64-linux-gnu-g++  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='"4.0.0~alpha1-1.Debian"' -std=gnu++11 -module -avoid-version -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z,relro -o libluabackend.la -rpath /usr/lib/x86_64-linux-gnu/pdns dnssec.lo lua_functions.lo luabackend.lo master.lo minimal.lo private.lo reload.lo slave.lo supermaster.lo -llua5.3 
libtool: link: rm -fr  .libs/libluabackend.la .libs/libluabackend.lai .libs/libluabackend.so
libtool: link: x86_64-linux-gnu-g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o  .libs/dnssec.o .libs/lua_functions.o .libs/luabackend.o .libs/master.o .libs/minimal.o .libs/private.o .libs/reload.o .libs/slave.o .libs/supermaster.o   -llua5.3 -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/5/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o  -O2 -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro   -Wl,-soname -Wl,libluabackend.so -o .libs/libluabackend.so
libtool: link: ( cd ".libs" && rm -f "libluabackend.la" && ln -s "../libluabackend.la" "libluabackend.la" )
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/luabackend'
Making all in mydnsbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/mydnsbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/mydnsbackend'
Making all in remotebackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/remotebackend'
make  all-am
make[4]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/remotebackend'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/remotebackend'
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/remotebackend'
Making all in tinydnsbackend
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/tinydnsbackend'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules/tinydnsbackend'
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/modules'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules'
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/modules'
Making all in codedocs
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/codedocs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/codedocs'
Making all in docs
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/docs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/docs'
Making all in pdns
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/pdns'
make  all-am
make[3]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1/pdns'
/bin/bash ../libtool  --tag=CXX   --mode=link x86_64-linux-gnu-g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/x86_64-linux-gnu/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='"4.0.0~alpha1-1.Debian"' -std=gnu++11 -pie  -pthread -export-dynamic   -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z,relro -o pdnsutil arguments.o backends/gsql/gsqlbackend.o base32.o base64.o bindlexer.o bindparser.o dbdnsseckeeper.o dnsbackend.o dns.o dnslabeltext.o dnsname.o dnspacket.o dnsparser.o dns_random.o dnsrecords.o dnssecinfra.o dnssecsigner.o dnswriter.o dynlistener.o ednssubnet.o gss_context.o iputils.o json.o logger.o misc.o nsecrecords.o packetcache.o pdnsutil.o mbedtlssigners.o qtype.o randomhelper.o rcpgenerator.o serialtweaker.o signingpipe.o sillyrecords.o statbag.o ueberbackend.o unix_utility.o zoneparser-tng.o botan110signers.o botansigners.o   ssqlite3.o  -ldl -lmbedcrypto  -lboost_program_options -L../ext/yahttp/yahttp -lyahttp -lbotan-1.10   -lsqlite3    
libtool: link: x86_64-linux-gnu-g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/x86_64-linux-gnu/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fstack-protector-strong -Wformat -Werror=format-security "-DPACKAGEVERSION=\"4.0.0~alpha1-1.Debian\"" -std=gnu++11 -pie -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -o pdnsutil arguments.o backends/gsql/gsqlbackend.o base32.o base64.o bindlexer.o bindparser.o dbdnsseckeeper.o dnsbackend.o dns.o dnslabeltext.o dnsname.o dnspacket.o dnsparser.o dns_random.o dnsrecords.o dnssecinfra.o dnssecsigner.o dnswriter.o dynlistener.o ednssubnet.o gss_context.o iputils.o json.o logger.o misc.o nsecrecords.o packetcache.o pdnsutil.o mbedtlssigners.o qtype.o randomhelper.o rcpgenerator.o serialtweaker.o signingpipe.o sillyrecords.o statbag.o ueberbackend.o unix_utility.o zoneparser-tng.o botan110signers.o botansigners.o ssqlite3.o -Wl,--export-dynamic  -ldl -lmbedcrypto -lboost_program_options -L../ext/yahttp/yahttp /home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp/yahttp/.libs/libyahttp.a -lbotan-1.10 /usr/lib/x86_64-linux-gnu/libsqlite3.so -pthread
/bin/bash ../libtool  --tag=CXX   --mode=link x86_64-linux-gnu-g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/x86_64-linux-gnu/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='"4.0.0~alpha1-1.Debian"' -std=gnu++11 -pie  -pthread -export-dynamic  -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z,relro -o pdns_server arguments.o auth-carbon.o backends/gsql/gsqlbackend.o base32.o base64.o bindlexer.o bindparser.o common_startup.o communicator.o dbdnsseckeeper.o dns.o dns_random.o dnsbackend.o dnslabeltext.o dnsname.o dnspacket.o dnsparser.o dnsproxy.o dnsrecords.o dnssecinfra.o dnssecsigner.o dnswriter.o dynhandler.o dynlistener.o ednssubnet.o gss_context.o iputils.o json.o logger.o lua-auth.o lua-pdns.o lua-iputils.o mastercommunicator.o misc.o nameserver.o nsecrecords.o packetcache.o packethandler.o mbedtlssigners.o qtype.o randomhelper.o rcpgenerator.o receiver.o resolver.o responsestats.o responsestats-auth.o rfc2136handler.o secpoll-auth.o serialtweaker.o signingpipe.o sillyrecords.o slavecommunicator.o statbag.o tcpreceiver.o tkey.o ueberbackend.o unix_semaphore.o unix_utility.o version.o webserver.o ws-api.o ws-auth.o zoneparser-tng.o botan110signers.o botansigners.o   ssqlite3.o  -ldl -lmbedcrypto  -L../ext/yahttp/yahttp -lyahttp -lbotan-1.10   -lsqlite3   -llua5.3  
libtool: link: x86_64-linux-gnu-g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/x86_64-linux-gnu/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fstack-protector-strong -Wformat -Werror=format-security "-DPACKAGEVERSION=\"4.0.0~alpha1-1.Debian\"" -std=gnu++11 -pie -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -o pdns_server arguments.o auth-carbon.o backends/gsql/gsqlbackend.o base32.o base64.o bindlexer.o bindparser.o common_startup.o communicator.o dbdnsseckeeper.o dns.o dns_random.o dnsbackend.o dnslabeltext.o dnsname.o dnspacket.o dnsparser.o dnsproxy.o dnsrecords.o dnssecinfra.o dnssecsigner.o dnswriter.o dynhandler.o dynlistener.o ednssubnet.o gss_context.o iputils.o json.o logger.o lua-auth.o lua-pdns.o lua-iputils.o mastercommunicator.o misc.o nameserver.o nsecrecords.o packetcache.o packethandler.o mbedtlssigners.o qtype.o randomhelper.o rcpgenerator.o receiver.o resolver.o responsestats.o responsestats-auth.o rfc2136handler.o secpoll-auth.o serialtweaker.o signingpipe.o sillyrecords.o slavecommunicator.o statbag.o tcpreceiver.o tkey.o ueberbackend.o unix_semaphore.o unix_utility.o version.o webserver.o ws-api.o ws-auth.o zoneparser-tng.o botan110signers.o botansigners.o ssqlite3.o -Wl,--export-dynamic  -ldl -lmbedcrypto -L../ext/yahttp/yahttp /home/wieger/src/pdns-4.0.0~alpha1/ext/yahttp/yahttp/.libs/libyahttp.a -lbotan-1.10 /usr/lib/x86_64-linux-gnu/libsqlite3.so -llua5.3 -pthread
make[3]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/pdns'
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1/pdns'
make[2]: Entering directory '/home/wieger/src/pdns-4.0.0~alpha1'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1'
make[1]: Leaving directory '/home/wieger/src/pdns-4.0.0~alpha1'

**Comment by Habbie** [comment]
Can you show `ldd` output for `pdns_server`, `pdnsutil` and `libluabackend.so` please?

**Comment by pieterlexis** [comment]
closing for lack or response
