### ISSUE TITLE
Additional logging/statistic for DNSSEC failures in recursor

### ISSUE THREAD

**Issue by cyclops1982** [PowerDNS/pdns#3334]
Hi,

I would like it if the recursor provided some logging when validation of a domain fails.
After having a quick look, it seems that some logging around line 800 and below in pdns_recursor.cc makes sense. Obviously, this logging would be at a loglevel where verbose output is requested.

A statistic for it might also make sense, so that when a big frequently used domain fails, you might see a spike in your statistics as well.

**Comment by paddg** [comment]
You'd have an increase in servfail metric if the validation of important domains fails. But yes, a validation failure metric in addition would be very useful. Also for monitoring alerts.

**Comment by pieterlexis** [comment]
Current releases of the recursor have DNSSEC validation statistics and can report Bogus in the log.
