### ISSUE TITLE
Please revert a79ce884a004a423c203597749475e4d5fb004a7

### ISSUE THREAD

**Issue by rubenk** [PowerDNS/pdns#3369]
I'm not sure what issue it fixed, but imho there are a few issues with this change:
- We lost the check for inet_aton in libresolv
- It adds -lnsl to LIBS if libsocket contains socket, regardless of if it is needed. It isn't if gethostname is in libc and not in libnsl.
- It first looks for socket in libsocket, and if it doesn't find it in libsocket, it looks for it in libsocket again.

**Comment by pieterlexis** [comment]
@cmouse  ?

**Comment by cmouse** [comment]
There were problems finding the correct libs in some other system.  This check was taken from autoconf archives.

**Comment by Habbie** [comment]
Do we know what systems? Because reverting looks like a win from here.

**Comment by cmouse** [comment]
Pull #3218

**Comment by cmouse** [comment]
Also #3127

**Comment by cmouse** [comment]
I mean #3187
