### ISSUE TITLE
pdnsutil fails silently when not authorized to access the backend

### ISSUE THREAD

**Issue by maikzumstrull** [PowerDNS/pdns#3387]
```
root@cbk130544:~# pdnsutil show-zone sys11cloud.net
root@cbk130544:~# sudo -u pdns pdnsutil show-zone sys11cloud.net
This is a Native zone
Zone is not actively secured
Metadata items: None
No keys for zone 'sys11cloud.net.'.
root@cbk130544:~#
```

Backend configuration:
```
launch=gpgsql

gpgsql-host=/var/run/postgresql
gpgsql-dbname=pdns
gpgsql-user=pdns
```

The password wasn't redacted; none is specified or needed, because PostgreSQL uses unix permissions with sockets. Anything running as "pdns" can access, anyone else (including root) cannot. The exit status is 1, it just doesn't say anything.

**Comment by ahupowerdns** [comment]
hi maik - can you check if any of the config.d files did specify a backend to load that did work? Not that this makes the bug any less severe. "launch+=" may have loaded a bind backend perhaps.

**Comment by maikzumstrull** [comment]
```
root@cbk130544:~# pdns_control current-config | grep include
# include-dir	Include *.conf files from this directory
include-dir=
root@cbk130544:~#
```

I turned config includes off to avoid special surprises. I've now removed all files except pdns.conf from /etc/powerdns to be extra sure, no difference.
