### ISSUE TITLE
Fix LDAP docs

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3391]
* [x] no longer mark it unsupported (perhaps even stress that it is supported now - perhaps even mention 'supported in 4.x' in the 3.x docs)
 * [x] pick up all the docs from http://www.linuxnetworks.de/doc/index.php/PowerDNS_ldapbackend and instead mention that -that wiki- is now deprecated
 * [ ] correct things that are wrong

**Comment by Habbie** [comment]
Work started in https://github.com/Habbie/pdns/tree/ldapdocs

**Comment by Habbie** [comment]
First two boxes checked. Docs now make basic sense. Did not fact check yet, volunteer work welcome ;)

**Comment by pieterlexis** [comment]
could you PR this up?

**Comment by Habbie** [comment]
from master:
```
commit 66d521bedcbac9cc3acd8a3818b88c916659f5e2
Merge: f659cc0 f86f8f8
Author: Pieter Lexis <pieter.lexis@powerdns.com>
Date:   Thu Apr 7 11:08:17 2016 +0200

    Merge remote-tracking branch 'habbie/ldapdocs' into docupdates
```
