### ISSUE TITLE
Checking keys in OpenSSL is expensive

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#3409]
As discused with @Habbie @rgacogne and @cmouse

The current OpenSSL signer does increase the CPU usage 5-10 times. After some investigation it turns out RSA_check_key() is the one to blame. Without this check CPU is back at normal (compared to mbed) levels.

Problems:
- RSA_check_key() and most likely EC_KEY_check_key() are expensive
- we fromiscmap a LOT (every query?)

Questions:
- Is the check necessary (in fromiscmap)
- Can we reduce the number of  fromiscmap invocations (for example, only if there is no signature cached)  Does not solve the CPU increase at startup or Thursdays
- Move the check to check-zone or 'check-keys' ?

**Comment by rgacogne** [comment]
I've done some quick tests and I am under the impression that `fromISCMap()` is not called a lot, mostly because of the key-cache, but I'm probably missing something.
