### ISSUE TITLE
under high load, dnsdist sometimes sends back wrong (old?) answer

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3416]
To reproduce, setup dnsdist with four backends in the default configuration and replay traffic to it at very high rate. It may be that we send back very very old answers this way. In any case, we should do better checking and rely less on the ID field matching.

**Comment by rgacogne** [comment]
#3433 should improve the situation, but perhaps we should also increase the default value of `g_maxOutstanding` in order to reduce the reusing rate.

**Comment by rgacogne** [comment]
We now check that the response matches the initial query, and `g_maxOutstanding` has been increased, closing.
