### ISSUE TITLE
fix Lua and LDAP backend class names

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3424]
LUABackend -> LuaBackend
LdapBackend -> LDAPBackend

not doing this now because it will break all the PRs (for LDAP at least)

**Comment by zeha** [comment]
Related yak: gXXSqlBackend -> GXXSQLBackend?

**Comment by Habbie** [comment]
Are you suggesting GMYSQLBackend?

**Comment by zeha** [comment]
No, casing of XX probably shouldn't change.

**Comment by Habbie** [comment]
I think I like the lowercase g, or more importantly, I'm not sure I care enough about g vs. G to want to change things :)

**Comment by Habbie** [comment]
Let's just not.
