### ISSUE TITLE
lowercase-outgoing: port to 4.x, test, document

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3441]
As merged without docs and tests in #3350.

**Comment by Habbie** [comment]
Also (I thought we had a separate ticket but I can't find it), port this to 4.x.

**Comment by pieterlexis** [comment]
How do you propose we test this? Running 2 recursors, one with this setting one without and letting the auth print the query it got from the recursor?

**Comment by Habbie** [comment]
![](https://40.media.tumblr.com/25ab5de9391a5b283c03abd8d04e9959/tumblr_o3i9pfhRHq1s9iq8zo1_250.png)

**Comment by Habbie** [comment]
I don't have a better idea :)

**Comment by Habbie** [comment]
It looks like our recursor testing is going to involve multiple recursors anyway, for various reasons :)
