### ISSUE TITLE
zone2sql failing on last line of zone file

### ISSUE THREAD

**Issue by ethanmullins** [PowerDNS/pdns#3462]
I've been having this issue for awhile, trying to import zones from simpledns on windows. zone2sql says it has a fatal error on the last line of the file. I've made sure that the last line isn't blank, is there anything else I should check for?

root@ns1:/home/ethan# zone2sql --gpgsql --named-conf=named.conf > zone.sql

Fatal error: Error in bind configuration 'named.conf' on line 140: syntax error

**Comment by zeha** [comment]
Please check if you have unix-style or windows-style files (\n vs. \r\n line endings).

**Comment by ethanmullins** [comment]
It does appear that they have windows line endings, I was unaware that this could even happen. Is there a good way to convert all of my zone files over?

**Comment by ethanmullins** [comment]
After a few conversions using: 

awk '{ sub("\r$", ""); print }' windows.txt > unix.txt

As well as dos2unix, it still seems to be throwing out the same error on the last line

**Comment by pieterlexis** [comment]
could you please show the named.conf contents?

**Comment by ethanmullins** [comment]
This is an example of a shorter named.conf that I have: 

;$; Updated with Simple DNS Plus Record Editor module v. 5.2.115.0 at 10 May 2014 01:29:47 -0400
$TTL 86400
@		IN SOA	( ns1. ; Primary DNS server
			  hostmaster.celeritynetworks.com. ; Responsible person
			  2014051001   ; Serial number
			  86400        ; Refresh
			  3600         ; Retry
			  777600       ; Expire
			  3600       ) ; Minimum TTL
		A	198.1.87.70
		NS	ns1.celeritynetworks.com.
		NS	ns2.celeritynetworks.com.
		MX	10 mail.celeritynetworks.net.
mail		CNAME	@
smtp		CNAME	@
webmail		CNAME	@
www		CNAME	@

All of my zone files fail on the last line

**Comment by ethanmullins** [comment]
Here is an example of a shorter named.conf that I have:

;$; Updated with Simple DNS Plus Record Editor module v. 5.2.115.0 at 10 May 2014 01:29:47 -0400
$TTL 86400
@		IN SOA	( ns1. ; Primary DNS server
			  hostmaster.celeritynetworks.com. ; Responsible person
			  2014051001   ; Serial number
			  86400        ; Refresh
			  3600         ; Retry
			  777600       ; Expire
			  3600       ) ; Minimum TTL
		A	198.1.87.70
		NS	ns1.celeritynetworks.com.
		NS	ns2.celeritynetworks.com.
		MX	10 mail.celeritynetworks.net.
mail		CNAME	@
smtp		CNAME	@
webmail		CNAME	@
www		CNAME	@

**Comment by ethanmullins** [comment]
Here's the contents of the file:
![capture](https://cloud.githubusercontent.com/assets/5787886/13358642/58e293c6-dc7e-11e5-80c6-959845386d10.PNG)

**Comment by pieterlexis** [comment]
this is a zonefile, not a named configuration file. could you please paste the contents of the named.conf here?

**Comment by pieterlexis** [comment]
closing for lack of response
