### ISSUE TITLE
dnsdist turn timeout into serving up stale cache data

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3470]
If a backend is overloaded and timing things out, it might make sense for us to serve up some expired data from the cache if we have it, up to a configurable point. Astounding amounts of records use 5 or 60 second TTLs. If backend is down, we might want to serve up that data a few minutes longer (configurable).

**Comment by ahupowerdns** [comment]
(extra idea: do the same thing for no-policy, so if all backends are known to be down)

**Comment by rgacogne** [comment]
`dnsdist` now supports using expired entries from the cache for the no-policy case when `setStaleCacheEntriesTTL(n)` is set to a non-zero value. It does not support the timed out case yet, mostly because timeouts are currently handled in `healthChecksThread`, and I don't like the idea of sending responses from there.

**Comment by mzealey** [comment]
Can we have this on the pdns recursor too for instances like eg the Dyn outage? I see unbound has added this functionality a few days ago.

**Comment by rgacogne** [comment]
@mzealey I would suggest opening a separate feature request, as this one is about dnsdist only.

**Comment by rgacogne** [comment]
Thinking about this feature a bit more, I'm no longer sure this makes sense:
- we already have an option to serve from stale data if we have no servers available
- after dnsdist detects a timeout it is usually much too late for an actual client: at least two full seconds have passed and the client either retried or gave up

Therefore I'm closing this feature request. Please let me know if you disagree and I'll reconsider :)
