### ISSUE TITLE
pdnsutil Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yerrysherry** [PowerDNS/pdns#3480]
Hallo,

Trying to role out version  4.0.0~alpha2-1pdns.trusty on vagrant with postgresql backend.

Standard installation of postgresql. I did not change any settings. Installation of the database:

postgres=# create user powerdns WITH PASSWORD '1234';
postgres=# create database pdns OWNER powerdns;

Then followed : https://doc.powerdns.com/md/authoritative/howtos/#basic-setup-configuring-database-connectivity for creating the tables and inserting the records from "example.com"

Pdns settings for postgresql: 
cat /etc/powerdns/pdns.d/pdns.local.gpgsql.conf
```
# PostgreSQL Configuration
#
# Launch gpgsql backend
launch=gpgsql
# gpgsql parameters
gpgsql-host=localhost
gpgsql-port=
gpgsql-dbname=pdns
gpgsql-user=powerdns
gpgsql-password=1234
gpgsql-dnssec=yes
```
```
tail /var/log/syslog
Feb 28 16:50:51 vagrant-ubuntu-trusty-64 pdns[6070]: Backend reported condition which prevented lookup (GSQLBackend lookup query: Fatal error during query: SELECT content,ttl,prio,type,domain_id,disabled::int,name,auth::int FROM records WHERE disabled=false and type=$1 and name=$2: ERROR:  permission denied for relation records#012) sending out servfail
Feb 28 16:51:24 vagrant-ubuntu-trusty-64 kernel: [  583.313250] traps: pdnsutil[6094] general protection ip:7fdd15d60e0c sp:7fffe7e27e88 error:0 in libc-2.19.so[7fdd15cde000+1bb000]
Feb 28 16:52:54 vagrant-ubuntu-trusty-64 kernel: [  674.336757] traps: pdnsutil[6105] general protection ip:7fce8833676b sp:7fffa564fc30 error:0 in libpq.so.5.6[7fce88326000+2b000]
Feb 28 16:56:46 vagrant-ubuntu-trusty-64 kernel: [  906.373322] traps: pdnsutil[6137] general protection ip:7fa998f9676b sp:7ffdf0bd2180 error:0 in libpq.so.5.6[7fa998f86000+2b000]
Feb 28 16:59:42 vagrant-ubuntu-trusty-64 kernel: [ 1082.366685] traps: pdnsutil[6148] general protection ip:7f79084e876b sp:7ffd0a6917e0 error:0 in libpq.so.5.6[7f79084d8000+2b000]
Feb 28 17:00:39 vagrant-ubuntu-trusty-64 kernel: [ 1139.734019] traps: pdnsutil[6157] general protection ip:7fb25849376b sp:7ffddff68440 error:0 in libpq.so.5.6[7fb258483000+2b000]
Feb 28 17:12:44 vagrant-ubuntu-trusty-64 kernel: [ 1865.755778] traps: pdnsutil[6328] general protection ip:7efe5c45f76b sp:7ffc115538f0 error:0 in libpq.so.5.6[7efe5c44f000+2b000]
```

All pdnsutil command give a segmentation fault.
```
root@pdns:~# pdnsutil rectify-zone example.com
Segmentation fault (core dumped)
root@pdns:~# pdnsutil list-all-zones
Segmentation fault (core dumped)
```

Probably, can not connect to the database

Regards,
Gerrit

**Comment by Habbie** [comment]
I notice a 'permission denied' in your log indeed, and you should fix that. However, we should not crash so bluntly on that!

On February 28, 2016 6:18:44 PM GMT+01:00, yerrysherry <notifications@github.com> wrote:
>Hallo,
>
>Trying to role out version  4.0.0~alpha2-1pdns.trusty on vagrant with
>postgresql backend.
>
>Standard installation of postgresql. I did not change any settings.
>Installation of the database:
>
>postgres=# create user powerdns WITH PASSWORD '1234';
>postgres=# create database pdns OWNER powerdns;
>
>Then followed :
>https://doc.powerdns.com/md/authoritative/howtos/#basic-setup-configuring-database-connectivity
>for creating the tables and inserting the records from "example.com"
>
>Pdns settings for postgresql: 
>cat /etc/powerdns/pdns.d/pdns.local.gpgsql.conf
># PostgreSQL Configuration
>#
># Launch gpgsql backend
>launch=gpgsql
># gpgsql parameters
>gpgsql-host=localhost
>gpgsql-port=
>gpgsql-dbname=pdns
>gpgsql-user=powerdns
>gpgsql-password=1234
>gpgsql-dnssec=yes
>
>tail /var/log/syslog
>Feb 28 16:50:51 vagrant-ubuntu-trusty-64 pdns[6070]: Backend reported
>condition which prevented lookup (GSQLBackend lookup query: Fatal error
>during query: SELECT
>content,ttl,prio,type,domain_id,disabled::int,name,auth::int FROM
>records WHERE disabled=false and type=$1 and name=$2: ERROR: 
>permission denied for relation records#012) sending out servfail
>Feb 28 16:51:24 vagrant-ubuntu-trusty-64 kernel: [  583.313250] traps:
>pdnsutil[6094] general protection ip:7fdd15d60e0c sp:7fffe7e27e88
>error:0 in libc-2.19.so[7fdd15cde000+1bb000]
>Feb 28 16:52:54 vagrant-ubuntu-trusty-64 kernel: [  674.336757] traps:
>pdnsutil[6105] general protection ip:7fce8833676b sp:7fffa564fc30
>error:0 in libpq.so.5.6[7fce88326000+2b000]
>Feb 28 16:56:46 vagrant-ubuntu-trusty-64 kernel: [  906.373322] traps:
>pdnsutil[6137] general protection ip:7fa998f9676b sp:7ffdf0bd2180
>error:0 in libpq.so.5.6[7fa998f86000+2b000]
>Feb 28 16:59:42 vagrant-ubuntu-trusty-64 kernel: [ 1082.366685] traps:
>pdnsutil[6148] general protection ip:7f79084e876b sp:7ffd0a6917e0
>error:0 in libpq.so.5.6[7f79084d8000+2b000]
>Feb 28 17:00:39 vagrant-ubuntu-trusty-64 kernel: [ 1139.734019] traps:
>pdnsutil[6157] general protection ip:7fb25849376b sp:7ffddff68440
>error:0 in libpq.so.5.6[7fb258483000+2b000]
>Feb 28 17:12:44 vagrant-ubuntu-trusty-64 kernel: [ 1865.755778] traps:
>pdnsutil[6328] general protection ip:7efe5c45f76b sp:7ffc115538f0
>error:0 in libpq.so.5.6[7efe5c44f000+2b000]
>
>
>All pdnsutil command give a segmentation fault.
>
>root@pdns:~# pdnsutil rectify-zone example.com
>Segmentation fault (core dumped)
>root@pdns:~# pdnsutil list-all-zones
>Segmentation fault (core dumped)
>
>Probably, can not connect to the database
>
>Regards,
>Gerrit
>
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/3480

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by pieterlexis** [comment]
most likely an uncaught exception somewhere

**Comment by cmouse** [comment]
Feb 28 16:52:54 vagrant-ubuntu-trusty-64 kernel: [ 674.336757] traps: pdnsutil[6105] general protection ip:7fce8833676b sp:7fffa564fc30 error:0 in libpq.so.5.6[7fce88326000+2b000]
