### ISSUE TITLE
Proper HTTP Status code for domain exists error (via POST)

### ISSUE THREAD

**Issue by Naroj** [PowerDNS/pdns#3482]
a 'create domain' action returns a 200 (HTTP status code) when a domain exists already. Since the client makes a 'mistake' i would suggest to throw a 4xx code. 

Source: RFC 2616, section 10.4.
Section 10.4.10 tells us a 409 is meant for a conflict. This looks like a suitable code to me.

**Comment by zeha** [comment]
From my testing, we return a 422, and not a 200. Can you confirm on 4.0.0?

**Comment by pieterlexis** [comment]
Closing due to lack of response. Please reopen when needed.
