### ISSUE TITLE
pdnsutil trailing dot inconsistency

### ISSUE THREAD

**Issue by maikzumstrull** [PowerDNS/pdns#3484]
pdnsutil functions that write records (e.g. add-zone) write record contents into PostgreSQL with trailing dots.
pdnsutil check-zone warns when record contents have trailing dots.

One of these should probably be changed.

**Comment by pieterlexis** [comment]
yes, we should not write the trailing dot into the db storage.

**Comment by henri9813** [comment]
Hello, 

Why ? 

Is not compliant with the RFC 1034 .

Do you have a valid reason to not store the trailing dot ? 

Best regards

**Comment by Habbie** [comment]
Hello @henri9813,

you have commented on a closed ticket, and your question is not a bug report or feature request (if it was, we would suggest you open a new ticket).

For support and explanation, please find us on IRC or our mailing lists. Details are at https://www.powerdns.com/opensource.html
