### ISSUE TITLE
Introduce disabled/enabled flag for entire zone

### ISSUE THREAD

**Issue by Naroj** [PowerDNS/pdns#3488]
In the telco world it is very useful to have a boolean for disabling/enabling a zone. It is nice we have it for records but it's more relevant for an entire zone. Since not all customers pay on time and we would be glad to not apply hacks (like renaming a zone to <zone>.<ext>.disabled).

**Comment by Habbie** [comment]
This works today, I believe, by disabling the SOA. Can you check?

**Comment by Naroj** [comment]
I will, is it an idea to mention this in the documentation?

**Comment by Habbie** [comment]
Sure

**Comment by Naroj** [comment]
It works!

**Comment by Habbie** [comment]
Good! If you like, you can edit the documentation right here on github (docs/markdown/...) and send us an update.
