### ISSUE TITLE
recursor: Certain new cache entries seem to end up with very large negative cache ttls

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#3489]
For some reason certain new query cache entries seem to get added with a very large negative cache ttl (as visible in a rec_control dump-cache).

Freshly started pdns-recursor.

Example query: dig 27.45.108.in-addr.arpa ns

rec_control dump-cache shows:

> 27.45.108.in-addr.arpa. -1456861684 IN NS ns8.verizon.net. ;
> 27.45.108.in-addr.arpa. -1456861684 IN NS ns5.verizon.net. ;
> 27.45.108.in-addr.arpa. -1456861684 IN NS ns6.verizon.net. ;
> 27.45.108.in-addr.arpa. -1456861684 IN NS ns7.verizon.net. ;

dig returns a decreasing TTL on repeating queries, so this seems to be fine - unless packetcache is disabled, so query-cache use is forced in which case the TTL stays at 86400 and a trace shows fresh outgoing queries on every attempt, bypassing the query cache.

Trace doesn't show anything obvious (for me):
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: Resolved '45.108.in-addr.arpa.' NS ns8.verizon.net. to: 68.238.96.72
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: Trying IP 68.238.96.72:53, asking '27.45.108.in-addr.arpa.|NS'
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: Got 5 answers from ns8.verizon.net. (68.238.96.72), rcode=0 (No Error), aa=1, in 140ms
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: accept answer '27.45.108.in-addr.arpa.|NS|ns7.verizon.net.' from '45.108.in-addr.arpa.' nameservers? 1 YES!
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: accept answer '27.45.108.in-addr.arpa.|NS|ns8.verizon.net.' from '45.108.in-addr.arpa.' nameservers? 1 YES!
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: accept answer '27.45.108.in-addr.arpa.|NS|ns5.verizon.net.' from '45.108.in-addr.arpa.' nameservers? 1 YES!
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: accept answer '27.45.108.in-addr.arpa.|NS|ns6.verizon.net.' from '45.108.in-addr.arpa.' nameservers? 1 YES!
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: OPT answer '.' from '45.108.in-addr.arpa.' nameservers
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: determining status after receiving this packet
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: answer is in: resolved to 'ns7.verizon.net.|NS'
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: answer is in: resolved to 'ns8.verizon.net.|NS'
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: answer is in: resolved to 'ns5.verizon.net.|NS'
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: answer is in: resolved to 'ns6.verizon.net.|NS'
> Mar 01 20:54:01 [1] 27.45.108.in-addr.arpa.: status=got results, this level of recursion done`

Repeating queries show no cache hits:
> Mar 01 20:57:25 1 [8/1] question for '27.45.108.in-addr.arpa.|NS' from 212.142.63.181
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: Wants NO DNSSEC processing
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: Looking for CNAME cache hit of '27.45.108.in-addr.arpa.|CNAME'
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: No CNAME cache hit of '27.45.108.in-addr.arpa.|CNAME' found
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: No cache hit for '27.45.108.in-addr.arpa.|NS', trying to find an appropriate NS record
> (..)
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: Trying IP 71.252.0.72:53, asking '27.45.108.in-addr.arpa.|NS'
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: Got 5 answers from ns5.verizon.net. (71.252.0.72), rcode=0 (No Error), aa=1, in 106ms
> (..)
> Mar 01 20:57:25 [8] 27.45.108.in-addr.arpa.: status=got results, this level of recursion done

Version: pdns-recursor git master

**Comment by aj-gh** [comment]
Seems to affect only NS entries.

Other examples:
101.110.68.in-addr.arpa
dns.br
messaging.aol.com
www1.hp.com

**Comment by Habbie** [comment]
this is on revision 37bf0698a60643eae849aae92724a95896821137
