### ISSUE TITLE
api failure, ttl not set or not an integer

### ISSUE THREAD

**Issue by celevra** [PowerDNS/pdns#3492]
Hi,

if i use your example on the newest version of pdns

```
ns html # curl -X PATCH --data '{"rrsets": [ {"name": "test.example.net.", "type": "A", "changetype": "REPLACE", "records": [ {"content": "127.0.0.1", "disabled": false, "name": "test.example.net.", "ttl": 3600, "type": "A" } ] } ] }' -H 'X-API-Key: mykey' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.net. | jq .
```

i get the error

```
{
  "error": "Key 'ttl' not an Integer or not present"
}
```

**Comment by Habbie** [comment]
Indeed, ttl moved outside of the records object. Looks like we missed a doc update there (https://doc.powerdns.com/md/httpapi/README/)

@celevra if you feel like it, you can edit here: https://github.com/PowerDNS/pdns/blob/master/docs/markdown/httpapi/README.md

**Comment by celevra** [comment]
thanks for pointing in the right direction ;-)

**Comment by gtmtech** [comment]
Isn't that the point of having /v1, /v2 in the API - so when you break the API, you change the version of it? 

Have raised a bug with the terraform powerdns provider, as it seems to result in this error, hence I am expecting that terraform implicitly adheres to powerdns3 style interface.

**Comment by zeha** [comment]
The experimental API in PowerDNS 3.x is not the same as the /v1 API that you see today in PowerDNS 4.0.0.
