### ISSUE TITLE
dnsdist can add EDNS Client Subnet, but does not strip it out on return 

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3515]
so if we add an EDNS Client Subnet in dnsdist so the backend auth knows the 'real' IP address, this auth server may well reply with an EDNS Client Subnet *response* (which is great). But if the original client did not ask for it, they will be confused. And for the record, PowerDNS Recursor 4.x *was* confused.

So dnsdist should probably strip out the edns client subnet again on response, unless it was present in the original. Modulo override etc.

This is not a 'this week' issue, but eventually it most be solved.

**Comment by rgacogne** [comment]
Ok, we already strip the EDNS OPT RR from the response if there was none in the query, but we don't strip the ECS option if there was no ECS option in the query, because I expected that clients would simply ignore it. It turns out I was wrong, I'll look into it.
