### ISSUE TITLE
sdig Aborted (core dumped)

### ISSUE THREAD

**Issue by yerrysherry** [PowerDNS/pdns#3517]
pdns=> select * from domains;
 id |    name     | master | last_check |  type  | notified_serial | account
----+-------------+--------+------------+--------+-----------------+---------
  1 | example.com |        |            | NATIVE |                 |
(1 row)

pdns=> select * from records;
 id | domain_id |         name          | type |         content         |  ttl  | prio | change_date | disabled | ordername | auth
----+-----------+-----------------------+------+-------------------------+-------+------+-------------+----------+-----------+------
  1 |         1 | example.com           | SOA  | localhost ahu@ds9a.nl 1 | 86400 |      |             | f        |           | t
  2 |         1 | example.com           | NS   | dns-us1.powerdns.net    | 86400 |      |             | f        |           | t
  3 |         1 | example.com           | NS   | dns-eu1.powerdns.net    | 86400 |      |             | f        |           | t
  7 |         1 | example.com           | MX   | mail.example.com        |   120 |   25 |             | f        |           | t
  5 |         1 | mail.example.com      | A    | 192.0.2.12              |   120 |      |             | f        | mail      | t
  6 |         1 | localhost.example.com | A    | 127.0.0.1               |   120 |      |             | f        | localhost | t
  4 |         1 | www.example.com       | A    | 192.0.2.10              |   120 |      |             | f        | www       | t
  8 |         1 | tas.example.com       | A    | 192.0.2.13              |   120 |      |             | f        |           | t
 11 |         1 | hond.example.com      | A    | 192.0.2.11              |   120 |      |             | f        |           | t
 12 |         1 | nukoffie.example.com  | A    | 192.0.2.15              |   120 |      |             | f        |           | t
(10 rows)

pdns=>

vagrant@pdns4:~$ sdig @localhost 53 nukoffie.example.com A
terminate called after throwing an instance of 'PDNSException'
Aborted (core dumped)

vagrant@pdns4:~$ sudo cat   /var/log/syslog
...
Mar  6 15:32:33 pdns4 pdns[1304]: Could not retrieve security status update for '4.0.0~alpha2-1pdns.trusty.Ubuntu' on 'auth-4.0.0_alpha2-1pdns.trusty.Ubuntu.security-status.secpoll.powerdns.com.', RCODE = Non-Existent domain

Indeed, I did not create a reverse dns, but the program should not do a core dump.

**Comment by ahupowerdns** [comment]
thank you!
