### ISSUE TITLE
forward-zones multiple addresses bug.

### ISSUE THREAD

**Issue by adsquaired** [PowerDNS/pdns#3523]
Version: PowerDNS Recursor 3.7.3
OS: RHEL 6.7
Release: 1.el6

The recursor was configured with two entries in the forward-zone directive. 
Ex:
```
forward-zones=domain.com=<IP1>;<IP2>
```

While capture packets leaving the server I do not see the second address in use at all. 
When sticking the first IP address into an ip route blackhole the second server does not pick up the requests.

The documentation on the PowerDNS website does not explain the functionality of the directive only that is supports multiple addresses.

**Comment by adsquaired** [comment]
Hi guys, 

Are there any status updates on this? Is there a bug confirmation?

**Comment by pieterlexis** [comment]
Hi,

Confirmed on current master. At the moment it looks like the first server is used during the resolve and I think I know where this goes wrong
