### ISSUE TITLE
Unify writing for settings related to DNS updates (minor nit)

### ISSUE THREAD

**Issue by sid3windr** [PowerDNS/pdns#3525]
Currently 3 settings are available for DNS updates:
- allow-dns-update-from
- dnsupdate
- forward-dnsupdates

So it's spelled "dnsupdate" twice, and "dns-update" once. For 4.x this could be rectified. Not sure if it is possible or advisable to alias the old directive(s).

**Comment by sid3windr** [comment]
Now that I look at them again, maybe singular vs plural could also be unified :)

**Comment by pieterlexis** [comment]
It looks like this was a documentation issue only, code was singular and without dash.
