### ISSUE TITLE
Building pdns-recursor fails on arm64, s390x because of missing boost-context

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3531]
Debian stretch has (at the time of writing) boost 1.58 which has no implementation of Boost.Context for arm64 or s390x.

The configure check doesn't seem to work in that it just fails fatally and doesn't choose the fallback implementation.

Note that the Debian libboost-context1.58-dev packages exist but are empty on arm64, s390x.

**Comment by Habbie** [comment]
Should be fixed by #3554
