### ISSUE TITLE
PowerDNS Recursor 4.0.0 Alpha 2: ./configure fails

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#3536]
```
...
checking boost/context/all.hpp usability... no
checking boost/context/all.hpp presence... yes
configure: WARNING: boost/context/all.hpp: present but cannot be compiled
configure: WARNING: boost/context/all.hpp:     check for missing prerequisite headers?
configure: WARNING: boost/context/all.hpp: see the Autoconf documentation
configure: WARNING: boost/context/all.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: boost/context/all.hpp: proceeding with the compiler's result
checking for boost/context/all.hpp... no
configure: error: cannot find boost/context/all.hpp
```
It seems only Boost<1.59 is affected.
[config_log.txt](https://github.com/PowerDNS/pdns/files/167303/config_log.txt)

**Comment by zeha** [comment]
Do you have the libboost-context* packages installed? (Not sure what their exact names are on SUSE.)

**Comment by paddg** [comment]
Yes
`i | libboost_context1_58_0 | The Boost::Context runtime library `

**Comment by pieterlexis** [comment]
This does compile on debian jessie which has Boost 1.55. It looks like we need to have a different test during configuring to set the correct context manager.

**Comment by nlyan** [comment]
This was introduced in 1.58.0 when they introduced execution_context (which we don't use). This only occurs because we use Boost.m4's builtin BOOST_CONTEXT macro. I'm currently already considering removing that anyway, since it's woeful and causing build issues on ARM64 and many other architectures.

**Comment by nlyan** [comment]
Found a Boost bug report on this, for reference

https://svn.boost.org/trac/boost/ticket/11223

I can fix this easily by just testing for the fcontext header directly, which I am leaning toward doing anyway.
