### ISSUE TITLE
pdns-recursor: compiler warning

### ISSUE THREAD

**Issue by rubenk** [PowerDNS/pdns#3542]
```
  CXX      version.o
validate-recursor.cc: In function 'vState validateRecords(const std::vector<DNSRecord>&)':
validate-recursor.cc:52:5: warning: 'state' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if(state == Bogus) return state;
     ^~
```

**Comment by tfarina** [comment]
@Habbie can we initialize |state| to Indeterminate to fix this warning?

**Comment by Habbie** [comment]
I don't know - if we knew it was that simple we would have done it! :)

**Comment by pieterlexis** [comment]
fixed in master [here](https://github.com/PowerDNS/pdns/commit/2e921ec6961500a5b59b4eb8d3d408e7825cd174#diff-fef7c910d4cc10297b505baec7342022R44)
