### ISSUE TITLE
our centos6 builders fail on builder.powerdns.com (dnsdist, recursor, auth)

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3559]
510 Processing files: dnsdist-0.0.824gce4ef9b-1pdns.el6.x86_64
511 error: File must begin with "/": GPLv2
512 error: File must begin with "/": COPYING

https://builder.powerdns.com/#/builders/39/builds/520/steps/6/logs/stdio

**Comment by pieterlexis** [comment]
@rubenk any ideas?

**Comment by rubenk** [comment]
Ah yes, CentOS 6 probably doesn't have the %license macro yet. See https://fedorahosted.org/fpc/ticket/411#comment:11 for an example of how to fix this.

**Comment by pieterlexis** [comment]
The recursor builds fine on centos 6 and the auth fails because of a weird boost error. Will fix the centos 6 builds of dnsdist
