### ISSUE TITLE
Add an --nsec3 parameter to pdnsutil secure-zone

### ISSUE THREAD

**Issue by ekohl** [PowerDNS/pdns#3575]
By adding a parameter you remove the need to run two commands. I would expect the result of
```pdnsutil secure-zone --nsec3 $domain``` to equal ```pdnsutil secure-zone $domain && pdnsutil set-nsec3 $domain```.

**Comment by Habbie** [comment]
This is hairy. Doesn't it need parameters? How do you use 'defaults'? Why not type two commands? Not sure we should do this :)

**Comment by ekohl** [comment]
I think you're right. I think we'll just wait for the API to support creating zones with dnssec and nsec3.
