### ISSUE TITLE
Could not retrieve security status update

### ISSUE THREAD

**Issue by nntu** [PowerDNS/pdns#3604]
hi, i have prolem : 
Mar 22 09:17:17 mail pdns_recursor[29203]: Mar 22 09:17:17 Could not retrieve security status update for '3.6.2-2+deb8u2.Debian' on 'recursor-3.6.2-2_deb8u2.Debian.security-status.secpoll.powerdns.com.', RCODE = Server Failure

**Comment by pieterlexis** [comment]
Hi @nntu,

I've checked our nameserver logs, we have not send out a SERVFAIL for that name in the last 2 days. This could indicate an issue with your local network or a resolver (should you user forwarding) in the network. If you start the recursor with the [`trace`](https://doc.powerdns.com/md/recursor/settings/#trace) option enabled, you should be able to see why this query fails in your logs. You can also add this log here.
