### ISSUE TITLE
Strange behavior in CommunicatorClass::queueNotifyDomain 3.4.8

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#3646]
Hi!

I added some log messages to the NOTIFY logic and I think I found a bug:

```
    B->lookup(QType(QType::NS),domain);
    while(B->get(rr))
      nsset.insert(rr.content);
L<<Logger::Warning<<"Found "<<nsset.size()<<" NS records"<<endl;

    for(set<string>::const_iterator j=nsset.begin();j!=nsset.end();++j) {
      vector<string> nsips=fns.lookup(*j, B);
L<<Logger::Warning<<"Found "<<nsips.size()<<" IPs for NS records"<<endl;
      if(nsips.empty())
        L<<Logger::Warning<<"Unable to queue notification of domain '"<<domain<<"': nameservers do not resolve!"<<endl;
      else
        for(vector<string>::const_iterator k=nsips.begin();k!=nsips.end();++k) {
          const ComboAddress caIp(*k, 53);
          if(!d_preventSelfNotification || !AddressIsUs(caIp)) {
            if(!d_onlyNotify.match(&caIp))
              L<<Logger::Info<<"Skiped notification of domain '"<<domain<<"' to "<<*j<<" because it does not match only-notify."<<endl;
            else
{
L<<Logger::Warning<<"Inserting to ips: "<<caIp.toStringWithPort()<<" "<<endl;
              ips.insert(caIp.toStringWithPort());
}
          }
        }
    }
```

And the result looks strange. The zone tld-box.com has 4 NS records. But the logic detects for every NS record 4 IP addresses, although there is only 1 IP per NS record:

Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: AXFR done for 'tld-box.com', zone committed with serial number 264
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: gpgsql Connection successful. Connected to database 'regdns' on 'localhost'.
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Found 4 NS records
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Found 4 IPs for NS records
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::14]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::14]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::14]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::14]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Found 4 IPs for NS records
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.80:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.80:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.80:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.80:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Found 4 IPs for NS records
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::15]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::15]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::15]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: [2a02:850:4:3::15]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Found 4 IPs for NS records
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.81:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.81:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.81:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Inserting to ips: 83.136.32.81:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Queued notification of domain 'tld-box.com' to 83.136.32.80:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Queued notification of domain 'tld-box.com' to 83.136.32.81:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Queued notification of domain 'tld-box.com' to [2a02:850:4:3::14]:53
Apr  1 13:01:33 cc-regdev-sbg1 pdns[21086]: Queued notification of domain 'tld-box.com' to [2a02:850:4:3::15]:53

I am not a C++ guy, but this looks strange. I would expect only 1 IP per NS iteration.

**Comment by zeha** [comment]
This is caused by `getaddrinfo` returning the NS IPs multiple times, but also mostly a cosmetic issue.

**Comment by zeha** [comment]
Actually, the IPs that are notified are stored in a set, making them unique. I don't think there's anything left to do here.

**Comment by klaus3000** [comment]
I am fine with that. I just wanted to let you know that something here is not perfect. Feel free to close it.
