### ISSUE TITLE
disable implicit notifications

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#3647]
Hi!

In issue #1340 I asked about explicit notify and it was closed due to the "allow-notify" option. But the "only-notify" option is not suitable for my use cases, it would only be a bad workaround.

So what is the problem with only-notify? only-notify works on IP addresses/masks. Thus, before evaluating if the target is allowed, the target has to be resolved:
1. fetching NS records from the backend (probably fast)
2. resolving the host names (from fast to terrible slow).

With 2., PowerDNS suddenly becomes dependent on external systems, eg. resolver. If PowerDNS hosts customer zones and customers may put arbitrary hostnames in their NS records (eg a host name whose authoritative nameserver is not responding), PowerDNS waits several seconds (in my case 30 seconds) until the (stub?) resolver gives up.

In our setup we hosts 100.000s of customer zones and we do not have control over their NS records. Thus, if we allow to slave zones from our PowerDNS (we do not need NOTIFYs to the hosts in the NS, but only ALSO-NOTIFY.) by enabling slave-renotify=yes, someone could hurt our PowerDNS and PowerDNS may become very slow waiting for unneeded host resolving. Thus, disabling these NOTIFYs with only-notify blocking this NOTIFYs is not suitble for scenarios like ours.

Thus, I again propose a new option:
notify=yes # default: current behavior, implicit (triggered by NS records) and explicit (also-notify)
notify=no # never send NOTIFYs
notify=explicit # only send NOTIFYs to host specified with ALSO-NOTIFY metadata and also-notify=

I will send a pull request too.

**Comment by pieterlexis** [comment]
`notify=no` would overlap with `master=no` (i.e. the combination `master=no` and `notify=yes` makes no sense). A `notify-type={default,explicit}` option might make more sense

**Comment by klaus3000** [comment]
That would be fine too for me. We just should agree on the naming and I will send another pull request.

**Comment by zeha** [comment]
As a temporary thing, you could set a short timeout in /etc/resolv.conf and possibly use resolvers with a short timeout.

**Comment by zeha** [comment]
If I understand you right, you don't even want `master=yes`, is that correct?

**Comment by klaus3000** [comment]
In my setup I only have slave zones which I "reslave" (PowerDNS is a bump in the wire). But the option is useful for masters too. Eg. if you distribute the zone to the slaves with other means (eg. DB replication) but need to have some also-notifys.

**Comment by klaus3000** [comment]
I just created another pull request for notify-type, see #3649

**Comment by klaus3000** [comment]
This issue would be resolved by accepting 
https://github.com/PowerDNS/pdns/pull/3890

**Comment by klaus3000** [comment]
Issue resolved by https://github.com/PowerDNS/pdns/pull/4861
