### ISSUE TITLE
Please consider making pdns Type=notify instead of Type=simple

### ISSUE THREAD

**Issue by maikzumstrull** [PowerDNS/pdns#3665]
The pdns.service systemd unit currently specifies that pdns is Type=simple. This means that systemd assumes PowerDNS is ready and followup units with After=pdns.service should be started *immediately* after the `pdns_server` process is spawned.

I would recommend changing this to Type=notify, which would make systemd wait until PowerDNS notifies it that it is ready and serving - the listening sockets have been bound and the backends initialized.

The required code change is to call https://www.freedesktop.org/software/systemd/man/sd_notify.html when PowerDNS is ready to serve, if available. If this call doesn't happen in the main process but in a fork, the `NotifyAccess` option needs to be adjusted in the unit file.

**Comment by pieterlexis** [comment]
note, WIP code for dnsdist is [available](https://github.com/pieterlexis/pdns/tree/dnsdist-systemd-notify-support)

**Comment by pieterlexis** [comment]
fixed in master
