### ISSUE TITLE
dnsdist: send client information to back-end

### ISSUE THREAD

**Issue by icy** [PowerDNS/pdns#3686]
I have a dns resolver that's behind a `dnsdist`.I expect `dnsdist` to work as a `reverse proxy` for my `dns resolver` which isn't designed for high performance purpose.

The problem is that my `dns resolver` only sees `dnsdist`'s address when it receives queries from `dnsdist`. This information is important in my set up, and I haven't figured out how to make it up. A simple idea is to rewrite the dns query, like this

1. Client asks `dnsdist` to resolve `example.net`
2. `dnsdist` asks my resolver to resolve `<client-ip>+example.net`

This would require a simple `queryHook()` (or kind of) in `dnsdist`.

Could you please support this?

Thanks a lot

**Comment by Habbie** [comment]
Hello @icy,

please look for `useClientSubnet` in the docs at http://dnsdist.org/README/ - it was designed exactly for your use case!

**Comment by icy** [comment]
Thanks a ton, @Habbie . I didn't read that carefully :)

**Comment by icy** [comment]
hi @Habbie ,

I use `dnsdist` as a load balancing for two back-ends, and it seems the problem comes up again. My configuration is like this

````
newServer({address="172.31.0.2"})

-- Good
newServer({address="127.0.0.1:5300", pool="test", useClientSubnet=true})

-- Bad: Back-end can't see real-ip of client.
-- newServer({address="172.31.0.3:5300", pool="test", useClientSubnet=true})
-- newServer({address="172.31.0.4:5300", pool="test", useClientSubnet=true})

addPoolRule({"test.net."}, "test")
````

(Here, `dnsdist` is running on `172.31.0.3` and in the good configuration I can use `127.0.0.1`)

Thanks!

**Comment by icy** [comment]
Hi again,

It seems that my back-end couldn't handle `EDNS` support. It is another problem now :(

**Comment by icy** [comment]
Hi @Habbie,

Can `blockFilter` modify the client's query before forwarding it to the back-end? (as I mentioned in the first post, I expted `blockFilter` to add a suffix to the client, like `<client-ip>+query`.)

Thanks a lot!

**Comment by Habbie** [comment]
@icy no, it can't. EDNS subnet was designed for your purpose, please use it.

**Comment by icy** [comment]
Thanks again, @Habbie . My back-end doesn't support EDNS unfortunately. :(

**Comment by Habbie** [comment]
@icy maybe you should replace your backend with one of our fine products? :)
