### ISSUE TITLE
JSON API not usable with strict HTTP parsers

### ISSUE THREAD

**Issue by johnyb** [PowerDNS/pdns#3723]
I've been playing around with the JSON API using nodejs. Today I tried again on a slightly newer stack and realized, I am not able to talk to the JSON API any longer. I found out, that there have been a few fixes in the http parser library of nodejs and it's more strict to the HTTP standard, now. Especially it fails when both headers `Content-Length` and `Transfer-Encoding: chunked` are present at the same time.

**Steps to reproduce:**
1. Have a pdns instance with HTTP API enabled
2. use nodejs http module to query the API

**Expected results:**
nodejs client can talk to the API

**Actual results:**
nodejs client fails with `HPE_UNEXPECTED_CONTENT_LENGTH` error code

------

More details can be found at request/request#2091 and [here](http://stackoverflow.com/questions/35525715/http-get-parse-error-code-hpe-unexpected-content-length).

I worked around this issue by downgrading to node 5.5.x, for now. Another way to work around would be an HTTP proxy that filters out the unneeded (and wrong) header.

**Comment by ahupowerdns** [comment]
Can you check if this is still the case against 4.x? Packages are available on https://repo.powerdns.com/ - we cleaned up a lot of things there. Thanks!

**Comment by johnyb** [comment]
I was about to come up with a little more details … :) I started development against the 4.x packages, yes. I had this working a while back, so I setup the 3.x branch, again. But it also fails.

I just published my configuration in [docker-pdns-minimal](https://github.com/johnyb/docker-pdns-minimal). The master branch is on the 4.x packages from repo.powerdns.com. After that I created the pdns3 branch, rolling back to the 3.x branch. Both branches show this issue.

I also just pushed my latest code to https://github.com/johnyb/yapdnsui/tree/develop, it works because of the downgrade to node 5.5, but it does not, when using node:latest tag in the Dockerfile.

Give me a minute and I write some minimal JS code that demonstrates the issue, so only the the pdns setup is needed to reproduce this issue.

**Comment by ahupowerdns** [comment]
ok, thank you!

**Comment by johnyb** [comment]
As promised a small snippet that can be pasted to the node console:

```
request = require('http').request({ port: '8081', hostname: '172.18.0.2', path: '/api/v1/servers', headers: { 'X-API-Key': 'mimimi' }}, (r) => console.log('Yay, working', r)).on('error', (e) => console.log(e));
request.end();
```

This can be reproduced using any recent nodejs version (even node 0.10 has this strict http parser shipped nowadays -_-), so the only way to work around this is to downgrade to an unsupported version (which is easy in a docker environment, so I'm quite glad to have this set up ;))

**Comment by zeha** [comment]
@cmouse can you have a look?

**Comment by cmouse** [comment]
Sure. Takes till next week though.

**Comment by johnyb** [comment]
I've been quickly reading through the sources of pdns and yahttp. I could not find any obvious places in pdns, where `transfer-encoding` or `content-length` is set, so I guess both headers are set in yahttp. So probably this is not a bug in pdns itself.

In https://github.com/cmouse/yahttp/blob/master/yahttp/reqresp.cpp#L222 something like:

```C++
if (iter->first == "content-length" && sendChunked) { iter++; continue; }
```

should do the trick. I'm not sure, this might break any other code, though. It might be more clean to only touch the headers, if initially set by the library itself.

**Comment by cmouse** [comment]
Fixed in upstream.
