### ISSUE TITLE
cross-compiling for openwrt error

### ISSUE THREAD

**Issue by debiansid** [PowerDNS/pdns#3725]
I just tried to cross compile recursor for openwrt x86 with musl  here is my error info, please help.
thanks

```
make[3]: *** No rule to make target 'boost/foreach.hpp', needed by 'responsestats.o'.  Stop.
make[3]: Leaving directory '/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3'
Makefile:59: recipe for target '/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built' failed
make[2]: *** [/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built] Error 2
make[2]: Leaving directory '/home/storage/openwrt-x86/package/openwrt-pdns-recursor'
package/Makefile:195: recipe for target 'package/openwrt-pdns-recursor/compile' failed
make[1]: *** [package/openwrt-pdns-recursor/compile] Error 2
make[1]: Leaving directory '/home/storage/openwrt-x86'
/home/storage/openwrt-x86/include/toplevel.mk:192: recipe for target 'package/openwrt-pdns-recursor/compile' failed
make: *** [package/openwrt-pdns-recursor/compile] Error 2
```

**Comment by Habbie** [comment]
Do you have boost installed in your cross environment, including headers?

On April 17, 2016 3:17:21 PM GMT+02:00, debiansid <notifications@github.com> wrote:
>I just tried to cross compile recursor for openwrt x86 with musl  here
>is my error info, please help.
>thanks
>
>make[3]: *** No rule to make target 'boost/foreach.hpp', needed by
>'responsestats.o'.  Stop.
>make[3]: Leaving directory
>'/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3'
>Makefile:59: recipe for target
>'/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built'
>failed
>make[2]: ***
>[/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built]
>Error 2
>make[2]: Leaving directory
>'/home/storage/openwrt-x86/package/openwrt-pdns-recursor'
>package/Makefile:195: recipe for target
>'package/openwrt-pdns-recursor/compile' failed
>make[1]: *** [package/openwrt-pdns-recursor/compile] Error 2
>make[1]: Leaving directory '/home/storage/openwrt-x86'
>/home/storage/openwrt-x86/include/toplevel.mk:192: recipe for target
>'package/openwrt-pdns-recursor/compile' failed
>make: *** [package/openwrt-pdns-recursor/compile] Error 2
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/3725

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by debiansid** [comment]
this is my boost configure status

Performing configuration checks

    - 32-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : yes (cached)
    - lockfree boost::atomic_flag : no  (cached)
    - has_icu builds           : no  (cached)
    - iconv (libc)             : no  (cached)
    - iconv (separate)         : yes (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
    - compiler-supports-visibility : yes (cached)
    - compiler-supports-ssse3  : yes (cached)
    - compiler-supports-avx2   : yes (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : not building
    - context                  : building
    - coroutine                : not building
    - coroutine2               : not building
    - date_time                : building
    - exception                : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : not building
    - iostreams                : not building
    - locale                   : building
    - log                      : building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : not building
    - signals                  : building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

**Comment by debiansid** [comment]
after correct the location of boost, 
I got this error which means there is no Context support in musl, is there a fix to this?
pdns_recursor.o: In function `MTasker<PacketID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::sendEvent(PacketID const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*)':
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9sendEventERKS0_PKS6_[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9sendEventERKS0_PKS6_]+0xb7): undefined reference to `swapcontext'
pdns_recursor.o: In function `MTasker<PacketID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::schedule(timeval*)':
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8scheduleEP7timeval[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8scheduleEP7timeval]+0x66): undefined reference to `swapcontext'
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8scheduleEP7timeval[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8scheduleEP7timeval]+0x227): undefined reference to `swapcontext'
pdns_recursor.o: In function `MTasker<PacketID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::waitEvent(PacketID&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned int, timeval*)':
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9waitEventERS0_PS6_jP7timeval[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE9waitEventERS0_PS6_jP7timeval]+0x13f): undefined reference to `swapcontext'
pdns_recursor.o: In function `MTasker<PacketID, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::makeThread(void (*)(void*), void*)':
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10makeThreadEPFvPvES8_[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10makeThreadEPFvPvES8_]+0x2c): undefined reference to `getcontext'
pdns_recursor.cc:(.text._ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10makeThreadEPFvPvES8_[_ZN7MTaskerI8PacketIDNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10makeThreadEPFvPvES8_]+0x8c): undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
Makefile:142: recipe for target 'pdns_recursor' failed
make[3]: *** [pdns_recursor] Error 1
make[3]: Leaving directory '/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3'
Makefile:59: recipe for target '/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built' failed
make[2]: *** [/home/storage/openwrt-x86/build_dir/target-i386_i486_musl-1.1.14/pdns-recursor/pdns-recursor-3.7.3/.built] Error 2
make[2]: Leaving directory '/home/storage/openwrt-x86/package/openwrt-pdns-recursor'
package/Makefile:195: recipe for target 'package/openwrt-pdns-recursor/compile' failed
make[1]: *** [package/openwrt-pdns-recursor/compile] Error 2
make[1]: Leaving directory '/home/storage/openwrt-x86'
/home/storage/openwrt-x86/include/toplevel.mk:192: recipe for target 'package/openwrt-pdns-recursor/compile' failed
make: *** [package/openwrt-pdns-recursor/compile] Error 2

**Comment by Habbie** [comment]
Hi, can you please use \``` around log output?

**Comment by debiansid** [comment]
I found alpine linux is based on musl too, so I install alpine linux x86, compiling recursor, and copied binary to openwrt , it worked.

**Comment by debiansid** [comment]
btw, I did same on dnsdist too, but it's Cache hitrate: is always 0%, is anything wrong with my conf?

-- accept DNS queries on UDP/5200 and TCP/5200
addLocal("0.0.0.0:53")


-- fix up possibly badly truncated answers from pdns 2.9.22
truncateTC(true)

warnlog(string.format("Script starting %s", "up!"))

-- define the good servers
newServer("192.168.88.1:5301", 2)  -- 2 qps

**Comment by rgacogne** [comment]
Hi,

> btw, I did same on dnsdist too, but it's Cache hitrate: is always 0%, is anything wrong with my conf?

Nothing except that you did not enable the cache, which is off by default. See http://dnsdist.org/README/#caching
