### ISSUE TITLE
dnsdist should think about what to do with notifications and axfr

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#3759]
So I just ran into this - when dnsdist is in front of a slave server, it receives & passes on notifications, which then get misunderstood ('who is this 127.0.0.1 master server?').

We actually have a powerdns setting for this, trusted-notification-proxy or so. Something similar goes for AXFR requests to master servers.

We should at the very least write a chapter about this and probably also think about adding relevant features.

**Comment by rgacogne** [comment]
Fixed in #3975.
