### ISSUE TITLE
Unable to create long TXT records

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#376]
TXT records can be up to 64k long per the specs (though not all resolvers or clients actually handle this much).

in modules/pipebackend/coprocess.cc we have the following that limits the input from the pipe backend process to 1024 chars:

 void CoProcess::receive(string &receive)
 {
  char line[1024];
  memset(line,0,1024);
 ...

  if(!fgets(line,1023,d_fp))
     throw AhuException("Child closed pipe");

Tweaking this would allow us to have larger TXT responses.

**Comment by indolering** [comment]
@Habbie I'm trying to track down the TXT length limits imposed by different DNS servers.  Looking at [the code](https://github.com/PowerDNS/pdns/blob/master/modules/pipebackend/coprocess.cc#L163), it appears as if the limit checking was just removed.

Was this moved to somewhere else in the code?  Could you give me some hints to figure this out?

**Comment by Habbie** [comment]
@indolering as the first line of this issue states, the limit is 64 kilobytes, as per RFC1035.

**Comment by indolering** [comment]
@Habbie but there is usually an implementation specific limit, I believe that Bind's is 2MB.

**Comment by Habbie** [comment]
@indolering no; the RFC limit is 64k, no implementation can go beyond that.

If you want to discuss more, please use our community support facilities https://www.powerdns.com/opensource.html or, of course, the community support facilities of products like BIND.

**Comment by indolering** [comment]
> no; the RFC limit is 64k, no implementation can go beyond that.
Err, 2KB!

> If you want to discuss more, please use our community support facilities

Ahh, fantastic!  Sorry for spamming your notification feed.
