### ISSUE TITLE
pdns_control show error

### ISSUE THREAD

**Issue by dimsua** [PowerDNS/pdns#3761]
powerdns: pdns-static-3.3.3-1.x86_64
os: centos 6 x86_64
Sometimes pdns_control dont return correct value for variable, for example:

pdns_control show packetcache-hit
148906190

after

pdns_control show packetcache-hit
corrupt-packets=1910514,deferred-cache-inserts=4015009,deferred-cache-lookup=2061934,latency=0,packetcache-hit=148908565,packetcache-miss=111755182,packetcache-size=366930,qsize-q=1,query-cache-hit=175234051,query-cache-miss=254868399,recursing-answers=0,recursing-questions=0,security-status=0,servfail-packets=24062,tcp-answers=7898,tcp-queries=12218,timedout-packets=1703,udp-answers=261600971,udp-queries=351375601,udp4-answers=232923458,udp4-queries=232981562,udp6-answers=28679198,udp6-queries=28677343,

after server restart all fork fine 3-5 days

**Comment by Habbie** [comment]
We have had several fixes in this area since 3.3.3 - can you try with 3.4.8 or one of the 4 alphas? Closing ticket for now.
