### ISSUE TITLE
Use hostname in carbon-server setting

### ISSUE THREAD

**Issue by mallniya** [PowerDNS/pdns#3763]
Hi, as I can see:
https://doc.powerdns.com/md/authoritative/settings/#carbon-server
carbon-server setting for now only can be defined as an IP. My installation does not utilize hostname, but IP works.
I wonder if enabling use of hostname in carbon-server setting is possible?
Yes, I do understand, that we talk about setting which uses domain name as a value, while setting is one of name server itself. But, for example, zone of graphite server can differ from one, that using pdns server is supported by.

**Comment by pieterlexis** [comment]
As you already mention, using a hostname for settings might lead to chicken-and-egg issues. To prevent this, hostnames are simply not allowed.

**Comment by mallniya** [comment]
>  As you already mention, using a hostname for settings might lead to chicken-and-egg issues.

...and might not, as I understand. For example, when pdns is using to support the same zone, as graphite server belongs to. So can this preposition taken as a feature request?
Or, in case avoiding hostname usage in any form is critical, could it be option to use more than one graphite server? I mean mechanism, that will take 2 and more IP's and rotate them in round-robin manner, while sending metrics to one of them.

**Comment by pieterlexis** [comment]
It looks like the recursor (4.0 and up) already has support for multiple carbon servers. The authoritative server does not. I created #3782 for this purpose.

**Comment by mallniya** [comment]
@pieterlexis, thank you.
