### ISSUE TITLE
Database backends should have configurable timeouts

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#3774]
Timeout for MySQL was increased in #3707, but should be configurable for the database backends.

**Comment by Habbie** [comment]
Indeed - #3707 cannot go into a final release like this, the timeouts are there for a reason and that reason is detecting DB failure during normal read only serving of auth data.

**Comment by pieterlexis** [comment]
This is fixed in #3788, should this be backported to 3.4.9?

**Comment by Habbie** [comment]
If somebody wants it they can ask for it :) Closing this one
