### ISSUE TITLE
libgmysqlbackend.so

### ISSUE THREAD

**Issue by HostioSolutions** [PowerDNS/pdns#3780]
Ubuntu 16.04 with MariaDB 10.1

Apr 26 18:15:00 ns1 pdns[2121]: Guardian is launching an instance
Apr 26 18:15:00 ns1 pdns[2121]: Reading random entropy from '/dev/urandom'
Apr 26 18:15:00 ns1 pdns[2121]: Loading '/usr/lib/powerdns/libgmysqlbackend.so'
Apr 26 18:15:00 ns1 pdns[2121]: Unable to load module '/usr/lib/powerdns/libgmysqlbackend.so': /usr/lib/powerdns/libgmysqlbackend.so: cannot open shared object file: No such file or directory
Apr 26 18:15:00 ns1 pdns[2121]: DNSBackend unable to load module in gmysql
Apr 26 18:15:01 ns1 pdns[2062]: Our pdns instance exited with code 1, respawning

root@ns1:/# apt-get install pdns-backend-mysql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pdns-backend-mysql is already the newest version (4.0.0~alpha2-3build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ns1:/#

**Comment by Habbie** [comment]
This looks like a support question, please use IRC or the pdns-users mailing list.

On April 26, 2016 6:16:09 PM GMT+02:00, Joeri Frantz <notifications@github.com> wrote:
>Ubuntu 16.04 with MariaDB 10.1
>
>Apr 26 18:15:00 ns1 pdns[2121]: Guardian is launching an instance
>Apr 26 18:15:00 ns1 pdns[2121]: Reading random entropy from
>'/dev/urandom'
>Apr 26 18:15:00 ns1 pdns[2121]: Loading
>'/usr/lib/powerdns/libgmysqlbackend.so'
>Apr 26 18:15:00 ns1 pdns[2121]: Unable to load module
>'/usr/lib/powerdns/libgmysqlbackend.so':
>/usr/lib/powerdns/libgmysqlbackend.so: cannot open shared object file:
>No such file or directory
>Apr 26 18:15:00 ns1 pdns[2121]: DNSBackend unable to load module in
>gmysql
>Apr 26 18:15:01 ns1 pdns[2062]: Our pdns instance exited with code 1,
>respawning
>
>root@ns1:/# apt-get install pdns-backend-mysql
>Reading package lists... Done
>Building dependency tree       
>Reading state information... Done
>pdns-backend-mysql is already the newest version
>(4.0.0~alpha2-3build1).
>0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>root@ns1:/# 
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/3780

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by christianbur** [comment]
same problem after upgate form Ubuntu 14.04 TLS to Ubuntu 16.04 TLS. 
Wath's the problem?

root@server:/# ls -al /usr/lib/powerdns
ls: cannot access '/usr/lib/powerdns': No such file or directory

during the upgrade i had a Problem with the packet  "pdns-backend-mysql"

**Comment by christianbur** [comment]
very strange, the Ubuntu 16.04 LTS an Alpha as prod version.

pdns_server --version
May 26 17:57:57 PowerDNS Authoritative Server 4.0.0-alpha2 (C) 2001-2016 PowerDNS.COM BV

**Comment by christianbur** [comment]
The parameter "module-dir=/usr/lib/powerdns" in  pdns.conf is the problem. 

default config: /usr/share/pdns-server/pdns.conf

**Comment by Habbie** [comment]
If the default config that ubuntu ships is broken, please take it up with them, or their upstream Debian. Reopening this ticket to track that.

**Comment by HostioSolutions** [comment]
To fix this problem you should use:
module-dir=/usr/lib/x86_64-linux-gnu/pdns

**Comment by Habbie** [comment]
No, please remove the module-dir setting completely, or another upgrade might break you again.

**Comment by christianbur** [comment]
the default configuration in Ubuntu 16.04 LTS is correct, the problem occurs when you take on the old configuration of ubuntu 14:04 TLS during the upgrade.

**Comment by rudyrockstar** [comment]
Just posting this as it can be useful addressing the "Unable to load module '/usr/lib/powerdns/libgmysqlbackend.so': " issue. You can build your dependency from the source. This for FreeBSD using Mariadb backend having installed the Mariadb client and PowerDNS server.

mkdir $HOME/pdnslib;cd $HOME/pdnslib;fetch https://downloads.powerdns.com/releases/pdns-4.0.3.tar.bz2;gunzip *;tar xf*;./configure --with-modules="bind gmysql";make;cd $HOME

[ su to root(BSD) ]

cp pdnslib/pdns-4.0.3/modules/gmysqlbackend/.libs/libgmysqlbackend.so /usr/local/lib/pdns/;service pdns restart

enjoi

**Comment by samuelgray** [comment]
@rudyrockstar Many, many thanks!! 
I'm running FreeBSD 10.3, and this solution worked perfectly, word for word.

**Comment by tobiascapin** [comment]
I tried those instructions but I had this error:
```
May 15 13:20:01 Reading random entropy from '/dev/urandom'
May 15 13:20:01 Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
May 15 13:20:01 Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so: undefined symbol: _ZN10DNSBackend7getAuthEP9DNSPacketP7SOADataRK7DNSName
May 15 13:20:01 DNSBackend unable to load module in gmysql
```

**Comment by Habbie** [comment]
@tobiascapin your pdns_server and libgmysqlbackend versions are not the same.

This is not a support channel. For support, please find us on the mailing lists or IRC channel via https://www.powerdns.com/opensource.html

**Comment by jakesilly** [comment]
My powerdns server runs as user 'pdns' but the file permissions are set to root:root... simple permissions swap fixed this problem for me.
chown -R pdns:pdns /usr/lib/x86_64-linux-gnu/pdns

mailinglists and IRC are so 1999 :(

**Comment by Habbie** [comment]
> chown -R pdns:pdns /usr/lib/x86_64-linux-gnu/pdns

This is absolutely terrible advice. Do not ever do this.

> mailinglists and IRC are so 1999 :(

Please kindly take your complaining elsewhere.
