### ISSUE TITLE
Add config option to disable bi-hourly recursor stats

### ISSUE THREAD

**Issue by ThiefMaster** [PowerDNS/pdns#3781]
A setting to increase the interval for them or disable them altogether would be nice.

For example, I have a script that monitors my logfiles for "unusual" entries every hour and send me an email of such entries. The recursor is only running for localhost, i.e. I'm not some ISP who wants to monitor DNS performance, cache sizes, etc.

For now I simply blacklisted `stats: *` log entries from `pdns_recursor` in my monitoring tool which works fine, but I think it'd be nicer if I could simply disable them - after all, I can send SIGUSR1 if I want to get the stats at some point.

**Comment by Habbie** [comment]
Fixed in #5271
