### ISSUE TITLE
Getting "error": "Key 'name' not present or not a String" when creating a record

### ISSUE THREAD

**Issue by linuxus** [PowerDNS/pdns#3787]
Hello,
I'm getting this error ("error": "Key 'name' not present or not a String") when I attempt to create new A type records via API. Here is the JSON data:
```
{"rrsets": [
  {"name": "controller.ai.local.",
   "type": "A",
   "ttl": 86400,
   "changetype": "REPLACE",
   "records": [ {"content": "192.168.1.107", "disabled": false} ]
  },
  {"name": "compute1.ai.local.",
   "type": "A",
   "ttl": 86400,
   "changetype": "REPLACE",
   "records": [ {"content": "192.168.1.108", "disabled": false} ]
  }
  ]
}
```
Also I'm running 4.0.0.Alpha1

**Comment by zeha** [comment]
I think this is fixed in alpha2. Please try with that :-)

**Comment by linuxus** [comment]
Hi zeha,
thanks for the input. I'm running Terraform provisioner for PowerDNS and if I switch this to Alpha2 there is another issue due to ttl error. When I update my PDNS to Alpha2 I get an error with Key 'ttl' is not an integer or not present"... looks like the ttl block is moved outside of the payload but I'm not sure. I have an issue open with Terraform as well for this: https://github.com/hashicorp/terraform/issues/6056.

**Comment by zeha** [comment]
Indeed, ttl is an rrset property, not a record one. This was incorrect before alpha2.

**Comment by linuxus** [comment]
Thanks again... I think I'll move it to 3.4 version and wait until Terraform pdns is updated to support Alpha2 and beyond as I'm currently blocked with my infrastructure deployment which usually consist of CD (Continuous Deployment). I'm hoping someone can do a PR on the Terraform side and I don't have to make backend changes.
