### ISSUE TITLE
DNSDist adddynblock needs to be more generic

### ISSUE THREAD

**Issue by thekoma** [PowerDNS/pdns#3790]
Would be very useful to have an option more flexible than adddynblock
Something like adddynrule where we should provide rule like Delay and Pool insertion per a specific time.

**Comment by thekoma** [comment]
At last! 7 years! 👴

Joking 🤣🤣🤣
 Good job guys!

**Comment by rgacogne** [comment]
Yeah, I don't know how I managed to miss that issue when we fixed it, sorry about that!

**Comment by thekoma** [comment]
No worries! 
You made me jiggle as I had completely forgot about the issue and changed 4 jobs in the meantime.
Reading this gave me many memories 😀
