### ISSUE TITLE
Please replace purl.js with something maintained

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#3799]
https://github.com/allmarkedup/purl says:

> Purl (A JavaScript URL parser) v2.3.1
> PLEASE NOTE: THIS PACKAGE IS NO LONGER MAINTAINED. There are plenty of great alternatives such as URI.js which I suggest you check out instead.

Used as pdns/recursordist/html/js/purl.js

**Comment by zeha** [comment]
Or in case it's not actually used, just drop it?

**Comment by Habbie** [comment]
At a quick glance I'm not sure it's being used at all.

**Comment by rgacogne** [comment]
The "magic" integration with jQuery makes it hard to be 100% sure, but I can't find any usage and at first sight I don't see any issue in the web interface after removing it. No error/warning in chrome's JS console either. I'm all for dropping it.

**Comment by ahupowerdns** [comment]
dropping in progress
