### ISSUE TITLE
recursor complaining about 'Insufficient number of filedescriptors'

### ISSUE THREAD

**Issue by medea61** [PowerDNS/pdns#3811]
Recursor requires more FDs (4096 as it seems) than CentOS per-default offers. 

Systemd can be instructed to raise the ulimit at process-start when creating this file:
/etc/systemd/system/pdns-recursor.service.d/limits.conf
and put in this contents:
--snip
[Service]
LimitNOFILE=4096
--snap

Would be cool if your rpm-builds could including/installing that file...

**Comment by pieterlexis** [comment]
This is easy to add to the unitfile, we'll do that after #3764 is merged.
