### ISSUE TITLE
PowerDNS gives wrong Serial from SOA record

### ISSUE THREAD

**Issue by prismanet** [PowerDNS/pdns#3828]
Hi,

We're currently running PowerDNS Authoritative 3.4.8 on master and slaves. PowerDNS Recursor 3.7.3 is also running on all hosts. Backend is SQLite. We have about 100 domains. Running CentOS 6.7 and PowerDNS RPMs were used for install.

The issue we're facing is that when we query the SOA record from a domain the servers are authoritative for, the serial is increased by 2 from its value in the database. For example, a domain for which its SOA record has a serial of "2016050401" in the database. PowerDNS will answer "2016050403" to all requests. 

The biggest issue this cause is that slaves will have a different Serial than Masters which will cause some consistency issues because Slaves update their SOA with the serial received from the master when queried which adds 2. 

Does anybody else have the same issue?

Thanks!
Sylvain

**Comment by Habbie** [comment]
(1) `grep -r soa-edit /etc/powerdns`
(2) `SELECT * FROM domainmetadata WHERE kind LIKE 'SOA%';

please :)

**Comment by prismanet** [comment]
Hi,

Thanks for the quick feedback. I thought of that too so I removed the soa-edit and soa-edit-api from the domainmetadata table for one domain with no luck. Here's the info you requested.

[root@TEL0003 ~]# grep -r soa-edit /etc/powerdns
/etc/powerdns/pdns.conf:default-soa-edit=INCEPTION-INCREMENT
/etc/powerdns/pdns.conf:# default-soa-edit      Default SOA-EDIT value
/etc/powerdns/pdns.conf:# default-soa-edit=
/etc/powerdns/pdns.conf:# default-soa-edit-signed       Default SOA-EDIT value for signed zones
/etc/powerdns/pdns.conf:# default-soa-edit-signed=

For the select, I haven't included all the domains as they are all configured the same.
1	42	SOA-EDIT-API	INCEPTION-INCREMENT
2	42	SOA-EDIT	INCEPTION-INCREMENT
3	13	SOA-EDIT	INCEPTION-INCREMENT
4	13	SOA-EDIT-API	INCEPTION-INCREMENT
5	12	SOA-EDIT	INCEPTION-INCREMENT
6	12	SOA-EDIT-API	INCEPTION-INCREMENT
7	149	SOA-EDIT	INCEPTION-INCREMENT
8	149	SOA-EDIT-API	INCEPTION-INCREMENT
9	148	SOA-EDIT	INCEPTION-INCREMENT
10	148	SOA-EDIT-API	INCEPTION-INCREMENT
11	14	SOA-EDIT	INCEPTION-INCREMENT
12	14	SOA-EDIT-API	INCEPTION-INCREMENT
13	15	SOA-EDIT	INCEPTION-INCREMENT
14	15	SOA-EDIT-API	INCEPTION-INCREMENT
15	16	SOA-EDIT	INCEPTION-INCREMENT
16	16	SOA-EDIT-API	INCEPTION-INCREMENT

**Comment by Habbie** [comment]
If you are using `INCEPTION-INCREMENT`, please see https://doc.powerdns.com/md/authoritative/dnssec/#soa-edit-ensure-signature-freshness-on-slaves to understand why you are getting the +2.

I'm closing this ticket now as it looks like a support question and we have the pdns-users mailing list (https://mailman.powerdns.com/mailman/listinfo/pdns-users) for those. If you feel you are spotting a bug -given- `INCEPTION-INCREMENT`, please comment so and I will reopen this ticket.

**Comment by prismanet** [comment]
Thanks Habbie. Isn't the SOA-EDIT related to zone/record creation and slave updates?

The issue I'm facing is when I query the master server with nslookup for the SOA record, the response I'm getting is different than what sits in the database. For example, if you query the SOA record of soeuropesoclose.com, you'll get a serial of 2016050604 but inside the database the SOA is 2016050602.

You can query the master server at 209.171.113.250.

Thanks!
Sylvain

**Comment by prismanet** [comment]
Hi,

I had to make an update on the domain I gave you for testing and I can no longer reproduce the error I was getting. I'll make more tests and come back if need be. You can leave the ticket closed.

Thanks!
Sylvain
