### ISSUE TITLE
Feature request: dnsdist: fine grained server health check

### ISSUE THREAD

**Issue by lark** [PowerDNS/pdns#3845]
The use case is that dnsdist is not used to query internal servers, but used as cache server to query external servers, in company office. Yes, like dnsmasq.

The current simple health check policy - once per second - is not friendly.

**Lazy check**

Check (and retries if needed) on a server is only issued when clients query this server. All success responses will reset NEED_CHECK. Enough idle time will make it NEED_CHECK.

**Tunable check interval**

A tunable check interval is good.

**Comment by rgacogne** [comment]
The second part is addressed by 7142.

**Comment by rgacogne** [comment]
And the first part has now been implemented in https://github.com/PowerDNS/pdns/pull/12065
