### ISSUE TITLE
Feature request: dnsdist AddResponseAction() per server or per pool 

### ISSUE THREAD

**Issue by lark** [PowerDNS/pdns#3846]
AddResponseAction() per server or per pool makes configuration simple, when used with AddPoolRule().

Only one (per pool) or some (per server) AddResponseAction() is needed, in case of multiple AddPoolRule("domain", "poolname").

**Comment by lark** [comment]
It seems that this is relative simple: extending DNSQuestion to contain server state, then processResponse() can use server state to get server information or poolname.

**Comment by rgacogne** [comment]
Out of curiosity, what are you trying to achieve? `AddResponseAction()` is very limited for now, and I'm wondering what users would like to be able to do in there.

**Comment by lark** [comment]
A good candidate to replace dnsmasq with ipset functionality. That is, forwarding certain domain queries to certain servers, and then setting ipset set per responses, to interact with other network functionality, such as NAT, routing.

dnsmasq is great but has limitations. There is no failover, no server health check; logging is not flexible, etc.

**Comment by rgacogne** [comment]
Closing as this can be implemented using tags in the current version.
