### ISSUE TITLE
add bulk API writes

### ISSUE THREAD

**Issue by JohnTheodore** [PowerDNS/pdns#3860]
Right now there is no way for me to update say 10k records through the powerdns API. Doing that many individual API calls takes forever. There are hacks to write to mysql directly. Though it would be nice if powerdns supported a bulk api call.

**Comment by zeha** [comment]
Please tell us a bit more about your use case. If I understand you right, you want to modify a large number of zones at once?

**Comment by JohnTheodore** [comment]
We're using powerdns with our hybrid cloud. We make A records and PTR records in powerdns for every node in the environment. So basically I want to make tens of thousands of records, as we add more subnets into our network. The hostnames have FQDNs in powerdns, and they're deterministically set.

**Comment by JohnTheodore** [comment]
So hostname/fqdn ip-100-2-3-4.us-east-1.aws.mycompany.com would resolve to 100.2.3.4, for say a /19, or a /15, etc.

**Comment by zeha** [comment]
That sounds like they'd all end up in the same zone. You can do that today.
