### ISSUE TITLE
dnstop-like tool that acts as a protobuf receiver to dnsdist/recursor

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3883]
Given that you would only run this occasionally, I wonder if it makes sense to add a 'listen' mode to rec/dnsdist for protobuf, where it just dumps protobuf when you connect instead of dnsdist/rec connecting to a receiver.

**Comment by dmachard** [comment]
it will be nice to have the same thing for the dnstap feature too
https://github.com/dmachard/dnstap-receiver/issues/2

**Comment by Habbie** [comment]
I was going to suggest this 'role reversal' might make more sense as a separate tool - then I clicked the link and there's John telling us he has this :)

**Comment by dmachard** [comment]
By the way, I am working on an attempt to make "dnstop" command (not yet released but soon). This tool is based on the dnstap-receiver. It will be easy to make it compatible with the pdns-protobuf-receiver too.

![image](https://user-images.githubusercontent.com/5562930/98484014-e4e38500-220c-11eb-9745-f7f29ff8248a.png)

**Comment by johnhtodd** [comment]
denis' go-dnscollector stuff is pretty much the answer to this ticket  - does this need to remain open?
