### ISSUE TITLE
dnsreplay "unsupported link type 101"

### ISSUE THREAD

**Issue by miesi** [PowerDNS/pdns#3921]
Hi,

when I try to use dnsreplay (built from pdns 3.4.9 tar.gz) to replay files captured with dnscap I receive an error telling me that link type 101 "LINKTYPE_RAW" is not supported.

I've heared that someone stumbled across this 2 years ago and a patch was made available within minutes. Can you please investigate and make this patch available for at least 4.x pdns?

Thanks Thomas

**Comment by rgacogne** [comment]
Hi Thomas,

It seems that the fix is already included in master (since 8bfd25602f0b14a427264900926941b1e9834e11). 4.x alpha and beta releases should have it.
