### ISSUE TITLE
Unitfile for multiple instance and systemd for the powerdns-recursor

### ISSUE THREAD

**Issue by j0ju** [PowerDNS/pdns#3922]
From a small discussion on IRC.
The following first version of a unit file supporting multiple instances has emerged https://gist.github.com/pieterlexis/9ca263d1d900f56e9661da9d2b705f8a.

Please include it in future releases.

**Comment by j0ju** [comment]
This unit file works, but logging is a bit globbered, the timestamp is added twice when loggin via systemd/journald.

Jun  2 15:22:20 host pdns_recursor[21012]: Jun 02 15:22:20 Refreshed . records

It might be a good idea, adding an option not adding a timestamp prefix when logging to stdout under a supervisor.

**Comment by pieterlexis** [comment]
yes, this is also the case with the auth I think.... We'll need to ponder to just stop timestamping ourselves or make it configurable.

**Comment by j0ju** [comment]
An option would be better IMHO, as for debugging running pdns on foreground on a console should log timestamps.
