### ISSUE TITLE
axfrfilter bug in pdns/lua-auth.cc

### ISSUE THREAD

**Issue by jreinmiller** [PowerDNS/pdns#3925]
Looks like there is a bug in pdns/lua-auth.cc that prevents axfrfilter from functioning.
From what I can tell the qname value on line 116 will never contain a value and always causes any axfrfilter script to crash out.

   string qname = rr.qname.toString();

Error:
Jun  1 10:17:39 XXXXXXX pdns_server: Jun 01 10:17:39 Unable to parse record during incoming AXFR of 'domain.com.' (std::exception): Attempt to print an unset dnsname

On version 4.x, even the example axfrfilter script will not run:
https://doc.powerdns.com/md/authoritative/modes-of-operation/

Oh, and related to that, it looks like the function call in the sample script is also incorrect as version 4.x does not pass a priority value to the script.

From sample script:
function axfrfilter(remoteip, zone, qname, qtype, ttl, prio, content)

When using that function call, prio winds up with the content value. From the source in lua-auth.cc, no priority is now being passed.

**Comment by ahupowerdns** [comment]
hi - can you check if this helped? Packages are now building on https://builder.powerdns.com and will appear on https://repo.powerdns.com shortly.

**Comment by jreinmiller** [comment]
Looks like that did it.
I grabbed the RPM off builder and it isn't generating that error when running axfrfilter.
Thanks.
