### ISSUE TITLE
4.0beta1 auth server dies on starting up on preparing statements

### ISSUE THREAD

**Issue by j0ju** [PowerDNS/pdns#3933]
I am currently at Debian Jessie testing 4.0beta from your 4.0.x repository.
>        % dpkg -l pdns-* | grep ^ii
>        ii  pdns-backend-mysql                                      4.0.0~beta1-1pdns.jessie         amd64                            generic MySQL backend for PowerDNS
>        ii  pdns-recursor                                           4.0.0~beta1-1pdns.jessie         amd64                            PowerDNS recursor
>        ii  pdns-server                                             4.0.0~beta1-1pdns.jessie         amd64                            extremely powerful and versatile nameserver

The server dies on startup with:
>        pdns_server[27589]: gmysql Connection failed: Could not prepare statement: insert into domains (type,name,master,account,last_check,notified_serial) values(?,?,?,?,NULL,NULL): INSERT command denied to user 'pdns_ext_ro'@'203.0.113.1' for table 'domains'
>        pdns_server[27589]: Caught an exception instantiating a backend: Unable to launch gmysql connection: Could not prepare statement: insert into domains (type,name,master,account,last_check,notified_serial) values(?,?,?,?,NULL,NULL): INSERT command denied to user 'pdns_ext_ro'@'203.0.113.1' for table 'domains'
>        pdns_server[27589]: Cleaning up
>        systemd[1]: pdns@ext.service: main process exited, code=exited, status=1/FAILURE

The reason is the auth server has only granted SELECT without INSERT, UPDATE, DELETE.
As the content of the database is generated not by PowerDNS.

>        [mysql] > SHOW GRANTS FOR  'pdns_ext_ro'@'203.0.113.1'
>        --- Grants for pdns_ext_ro@203.0.113.1
>        GRANT USAGE ON *.* TO 'pdns_ext_ro'@'203.0.113.1' IDENTIFIED BY PASSWORD '*FOO';
>        GRANT SELECT ON `pdns_ext`.* TO 'pdns_ext_ro'@'203.0.113.1';

PowerDNS 3.4.8 came up with that DB permissions.

**Comment by cmouse** [comment]
This would probably require some way to not prepare statements that are not needed, or do lazy prepare.

**Comment by Habbie** [comment]
Lazy prepare also come up in context with reconnection, so maybe we can fix both in one go.

**Comment by cmouse** [comment]
Quick glance suggests that it might not be too big change. It has to happen on first bind or execute.

**Comment by cmouse** [comment]
Possibly fixed in #3937

**Comment by j0ju** [comment]
Seems to be fixed by #3937.
