### ISSUE TITLE
Feature request: CNAME records in Protocol Buffer Remote Logger

### ISSUE THREAD

**Issue by hasei** [PowerDNS/pdns#3939]
So far the protocol buffer remote logger of the recursor only logs A and AAAA records. CNAME records are not included but they are widely used, especially by CDNs. To have a complete log of the name resolution chain CNAME records are needed as well.

I took a look at the source code and think a good way to start in in the startDoResolve() function of the recursor, where the A and AAAA records are added to the protobuf response.

**Comment by rgacogne** [comment]
Implemented in d9d3f9c13c51c4df5a7863056cae7afd330f374c
