### ISSUE TITLE
api V3 documentation link for api spec pointing to V4 api

### ISSUE THREAD

**Issue by Sylvain303** [PowerDNS/pdns#3950]
In https://doc.powerdns.com/3/httpapi/README/ at the end `api_spec.md` link to V4 doc instead of the V3.

**Comment by Habbie** [comment]
Hello! You can use the edit button [here](https://github.com/PowerDNS/pdns/blob/docs-3X/docs/markdown/httpapi/README.md) to fix this!

**Comment by Sylvain303** [comment]
Cool, fixed. Thanks.

**Comment by Habbie** [comment]
Hi, you also need to send a pull request from your fresh patch-1 branch, otherwise the change does not get to us.

**Comment by Sylvain303** [comment]
OK, in progress I think.
