### ISSUE TITLE
libbotan security upgrade breaks powerdns authorative server

### ISSUE THREAD

**Issue by thebruins** [PowerDNS/pdns#3954]
OS: plain Debian installation (Jessie)
Version: Powerdns authorative server version 3.4.1 with a MySQL backend (installed with apt-get, most recent stable Debian release, specific version details: 3.4.1-4+deb8u5)
Powerdns details: plain, with DNSSEC

Recently a security update for libbotan was released (1.10.8-2+deb8u1) which breaks Powerdns: pdns starts using 100% CPU and becomes unresponsive. No error messages in logs.
When I downgrade libbotan back to 1.10.8-2 everything is fine again.

**Comment by Habbie** [comment]
Also tracked at Debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825849 (which honestly is the right place).

**Comment by Habbie** [comment]
@zeha does this ring a bell for you?

**Comment by thebruins** [comment]
I know, but I figured that maybe some people here would have some pointers as well. Thanks.

**Comment by zeha** [comment]
Any reproduction case would help in looking at this further...

**Comment by Habbie** [comment]
https://lists.debian.org/debian-security-announce/2016/msg00151.html claims that deb8u5 fixes this. Can you be clear about which of these combinations fail:

1. old botan, old pdns
2. old botan, new pdns
3. new botan, old pdns
4. new botan, new pdns

And also can you show your configuration? And, if possible, can you attach gdb to the 100% CPU-process and get stack traces from all threads?

**Comment by thebruins** [comment]
1. old botan, old pdns: ok
2. old botan, new pdns: ok
3. new botan, old pdns: fail
4. new botan, new pdns: fail

Config is attached, both main config and MySQL backend config.

[pdns.txt](https://github.com/PowerDNS/pdns/files/303341/pdns.txt)
[mysqlbackend.txt](https://github.com/PowerDNS/pdns/files/303340/mysqlbackend.txt)

**Comment by cmouse** [comment]
allow-axfr-ips=127.0.0.0/8,::1,x.x.x.x
allow-recursion=127.0.0.1,y.y.y.y
config-dir=/etc/powerdns
daemon=no
guardian=no
include-dir=/etc/powerdns/pdns.d
launch=
security-poll-suffix=
setgid=pdns
setuid=pdns

do you have other stuff under pdns.d than mysqlbackend config?

**Comment by thebruins** [comment]
Yes, there is a second mysql backend for a couple of domains that uses the default Powerdns MySQL config and database schema. Its config file only contains the database credentials.
Plus a couple of files that do not end in .conf and are not loaded.

**Comment by thebruins** [comment]
A few minutes ago I disabled the primary DNSSEC backend, upgraded libbotan and restarted pdns: no failure.
I enabled the DNSSEC backend again, restarted pdns and it immediately started to consume 100% CPU and became mostly unresponsive.

**Comment by cmouse** [comment]
any chance you could attach debugger and run

thread 0
bt full
thread 1
bt full
...

until you run out of threads?

**Comment by thebruins** [comment]
Sure, see attachment

[gdboutput.txt](https://github.com/PowerDNS/pdns/files/303473/gdboutput.txt)

**Comment by zeha** [comment]
I looked a bit at the botan1.10 diff, but couldn't find anything obvious. Also I can't reproduce this locally. Please show more on how to trigger this.

**Comment by thebruins** [comment]
Well, I suppose you could sort of copy our setup: we have a lot of domains but use the same three KSK and ZSK keys for all domains. We have accomplished this by using a simple custom SQL query for 'list-domain-keys-query' (SELECT id, flags, active, content FROM pdns_cryptokeys WHERE domain_id=12) which returns two zone-signing keys (one active, one inactive) and one key-signing key. Just add a few domains and run the pdns-rectify command on those to make sure all DNSSEC fields in the database are correctly filled in for the domains. Start the whole thing up and start querying the DNS server.

This is basically what we have right now and was working fine until the libbotan update.

**Comment by Habbie** [comment]
Is this still a problem?

**Comment by zeha** [comment]
I've closed the Debian bug in 2017, because there was no feedback. As botan is gone in current HEAD, should this be closed?
