### ISSUE TITLE
pdns-recursor forward-zones eats whitespace-separated addresses with no warning

### ISSUE THREAD

**Issue by sim-** [PowerDNS/pdns#3956]
I recently discovered that my forward-zones syntax has been wrong (for years). I only discovered this when running pdns-recursor in foreground mode for another reason. I had configuration similar to:

forward-zones=\
        foo=1.2.3.4 1.2.3.5,\
        bar=1.2.3.4 1.2.3.5

which was silently being parsed as "foo=1.2.3.4,bar=1.2.3.4", thus never using the second address. The correct syntax is with ';' instead of ' '. Perhaps a warning should be emitted for this mistake?

**Comment by Habbie** [comment]
according to @pieterlexis additionally this was parsed into `1.2.3.5=` (empty list of NSes) twice

**Comment by pieterlexis** [comment]
(and we're sorry)
