### ISSUE TITLE
PowerDNS-Admin 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by dfiel** [PowerDNS/pdns#3960]
Installed PowerDNS-Admin using [this](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Install-PowerDNS-Admin-in-Fedora-23) after following [this](http://www.tecmint.com/install-powerdns-poweradmin-mariadb-in-centos-rhel/) tutorial to install PowerDNS server.

When trying to access PowerDNS-Admin, the log displays this error:
` [ERROR] Can not update domain table.While fetching http://127.0.0.1:8081/servers/localhost/zones: 500 Server Error: Internal Server Error `

My configuration is [here](http://pastebin.com/raw/jfNXU6aG), it is the default with only the MySQL and API settings changed.

What am I doing wrong?

**Comment by pieterlexis** [comment]
Can you also share your log from PowerDNS? That should contain hints on what is going wrong. Furthermore, what OS are you using with what version of PowerDNS?

**Comment by dfiel** [comment]
@pieterlexis Where would this log file be? I am running CentOS 7 with powerDNs version 3.4.8-1.el7 from the EPEL repo.

**Comment by pieterlexis** [comment]
PowerDNS logs to syslog, so `/var/log/syslog` or `/var/log/messages`. If there's no error message from PowerDNS in there, set the `loglevel` parameter in your configuration to `9`, restart PowerDNS and trigger the error again to get a log message.

**Comment by dfiel** [comment]
Is this what you are looking for?

`Jun  7 17:41:57 PowerDNS-Admin pdns_server: Jun 07 17:41:57 Reading random entropy from '/dev/urandom'
Jun  7 17:41:57 PowerDNS-Admin pdns[2208]: Reading random entropy from '/dev/urandom'
Jun  7 17:41:57 PowerDNS-Admin pdns[2208]: Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Jun  7 17:41:57 PowerDNS-Admin pdns_server: Jun 07 17:41:57 Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: This is a standalone pdns
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: Listening on controlsocket in '/var/run/pdns.controlsocket'
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: UDP server bound to 0.0.0.0:53
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: TCP server bound to 0.0.0.0:53
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: PowerDNS Authoritative Server 3.4.8 (jenkins@autotest.powerdns.com) (C) 2001-2015 PowerDNS.COM BV
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: Using 64-bits mode. Built on 20160203175745 by mockbuild@buildvm-19-nfs.phx2.fedoraproject.org, gcc 4.8.5 20150623 (Red Hat 4.8.5-4).
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: Listening for HTTP requests on 127.0.0.1:8081
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: Creating backend connection for TCP
Jun  7 17:41:57 PowerDNS-Admin systemd: Started PowerDNS Authoritative Server.
Jun  7 17:41:57 PowerDNS-Admin systemd: Reached target Multi-User System.
Jun  7 17:41:57 PowerDNS-Admin systemd: Starting Multi-User System.
Jun  7 17:41:57 PowerDNS-Admin systemd: Started Stop Read-Ahead Data Collection 10s After Completed Startup.
Jun  7 17:41:57 PowerDNS-Admin systemd: Starting Update UTMP about System Runlevel Changes...
Jun  7 17:41:57 PowerDNS-Admin systemd: Started Update UTMP about System Runlevel Changes.
Jun  7 17:41:57 PowerDNS-Admin systemd: Startup finished in 711ms (kernel) + 2.038s (initrd) + 13.677s (userspace) = 16.427s.
Jun  7 17:41:57 PowerDNS-Admin pdns[2209]: About to create 3 backend threads for UDP
Jun  7 17:41:58 PowerDNS-Admin pdns[2209]: Done launching threads, ready to distribute questions
Jun  7 17:42:03 PowerDNS-Admin systemd: Created slice user-0.slice.
Jun  7 17:42:03 PowerDNS-Admin systemd: Starting user-0.slice.
Jun  7 17:42:03 PowerDNS-Admin systemd: Started Session 1 of user root.
Jun  7 17:42:03 PowerDNS-Admin systemd-logind: New session 1 of user root.
Jun  7 17:42:03 PowerDNS-Admin systemd: Starting Session 1 of user root.
Jun  7 17:43:50 PowerDNS-Admin pdns[2209]: HTTP ISE for "/servers/localhost/zones": Exception: Database error trying to retrieve all domains:Failed to execute mysql_query, perhaps connection died? Err=1: Unknown column 'records.disabled' in 'where clause'
`

**Comment by dfiel** [comment]
Is this what you're looking for? [Image](https://i.gyazo.com/aaedadb64aa13f0c75732140210c6d1e.png)

**Comment by pieterlexis** [comment]
It looks like your database doesn't have the correct fields, please see our [documentation](https://doc.powerdns.com/3/authoritative/backend-generic-mypgsql/#mysql-specifics) on what the correct database schema is and verify this against your database.

Closing this issue as it is a support issue, not a code issue. Please use the [pdns-users](https://www.powerdns.com/mailing-lists.html) for support.
