### ISSUE TITLE
add tests for 0.0.0.0/:: responses

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3965]
All our products support replying, on UDP, from the correct IP address even when bound to a wildcard (on OSes that support it). However, we do not test this. I touched this code today (in #3962) and now I need to remember to test this. Writing tests for this should not be a terribly huge challenge.

No product label as it applies to all - even though the code is shared.

**Comment by omoerbeek** [comment]
dnsdist TestAdvanced already exercises this, so we can probably steal from that code.
