### ISSUE TITLE
remove gsql::isOurDomain

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3982]
182f7513802bffb4ab3dd373eadb8f1a64012e22 improves multi-backend setups, at the cost of a serious performance hit for _all_ setups. Proposal: hide this check behind a gsql parameter that defaults to off.

@cmouse @mind04 @pieterlexis comments welcome.

**Comment by mind04** [comment]
I like to propose 'enable-buggy-backend-behavior' for the config option. 
When a domain_id exists in multiple backends the result of this change is undefined behaviour.

```
WHERE id = ? OR name = ?"
```

Please revert.

**Comment by Habbie** [comment]
Ah yes, that was it. I agree.

**Comment by cmouse** [comment]
I am bit concerned that reverting this whole change will again lead to GSQL backend hoarding every domain to itself.

**Comment by Habbie** [comment]
Which is how things have been for a long time with little complaints. It is by far the best of two evils.
