### ISSUE TITLE
mysql schema broken for default mariadb install

### ISSUE THREAD

**Issue by fliespl** [PowerDNS/pdns#3987]
Schema was taken from the docs: https://doc.powerdns.com/md/authoritative/howtos/#basic-setup-configuring-database-connectivity

```
MariaDB [config_pdns]> CREATE UNIQUE INDEX name_index ON domains(name);
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

MariaDB [config_pdns]> CREATE UNIQUE INDEX namealgoindex ON tsigkeys(name, algorithm);
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

**Comment by rgacogne** [comment]
Would you mind telling us what encoding are you using? The 767 bytes limit varies with the encoding used, allowing up to 255 chars in UTF-8 but 767 in latin1 for example, so there is not much we can do to fix it for everyone. I would suggest you take a look at `innodb_large_prefix`.

**Comment by fliespl** [comment]
Of course (I have changed name to 128)

```
MariaDB [config_pdns]> show create table domains \G;
*************************** 1. row ***************************
       Table: domains
Create Table: CREATE TABLE `domains` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `master` varchar(128) DEFAULT NULL,
  `last_check` int(11) DEFAULT NULL,
  `type` varchar(6) NOT NULL,
  `notified_serial` int(11) DEFAULT NULL,
  `account` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_index` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

```

**Comment by rgacogne** [comment]
Thank you. You are using utf8mb4, so by definition your indexes are limited to 191 chars if you don't enable `innodb_large_prefix`.

**Comment by fliespl** [comment]
@rgacogne thank you very much for explaination :)

I think it's okay to close this now.

**Comment by rgacogne** [comment]
You're welcome, feel free to re-open an issue if needed.

**Comment by zeha** [comment]
Given Debian stretch has switched to MariaDB, I've changed the default schema for Debian in this way:

https://anonscm.debian.org/cgit/pkg-dns/pdns.git/tree/debian/sql/mysql/mysql?id=91332b05862958ff10ab6a106b212f52336dc650

Please consider doing something (similar or not) to improve MariaDB OOTB support :)

**Comment by aj-gh** [comment]
Care should be taken in order not to break MySQL support; when looking at the schema proposed by zeha:
> Column length too big for column 'comment' (max = 21845); use BLOB or TEXT instead

If the column size is reduced to the stated max it'll run into an issue with total row length:
>ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

Tested on MySQL 5.6 but 5.7 should behave similar, as per [http://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html](url):
> Although InnoDB supports row sizes larger than 65,535 bytes internally, MySQL itself imposes a row-size limit of 65,535 for the combined size of all columns

Does this work with MariaDB by the way?
[https://mariadb.com/kb/en/mariadb/xtradbinnodb-storage-formats/](url) states, depending on the storage format used (e.g. "dynamic"):
> The new row size limit is 65,535 bytes.

Based on that I would guess this might also lead to issues depending on the MariaDB config, but I could be wrong there - not sure, but I though I'd mention it.
Maybe it would make sense to switch 'comment' to TEXT?

**Comment by aj-gh** [comment]
Similar to #4202 "PowerDNS with MySQL 5.7 (Percona) column length too big"

**Comment by zeha** [comment]
> Does this work with MariaDB by the way?
> > The new row size limit is 65,535 bytes.

It does create the column; maybe storing that many bytes is not supported then. TEXT might be - as you said - a better idea. I'm certainly no MySQL/MariaDB expert.

**Comment by Habbie** [comment]
Please review and test #5225.

**Comment by aj-gh** [comment]
OK on MySQL 5.7.17.
