### ISSUE TITLE
replace all toString() and <<DNSName<< in logging to toLogString()

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#4002]
to avoid throwing on empty DNSNames

**Comment by pieterlexis** [comment]
see also #3589

**Comment by mind04** [comment]
please add a 4.0.0 milestones to this issue and/or #3589

**Comment by pieterlexis** [comment]
I think it is better to change the `Logger& Logger::operator<<(const DNSName &d)` to do this, so `<<DNSName` just works (and you can't forget it).
