### ISSUE TITLE
two reports of log-fail causing SERVFAIL

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4009]
From one user:
```
> But I got SERVFAIL for www.dnssec-failed.org if I set dnssec=log-fail

dig @localhost www.dnssec-failed.org
...
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 49866
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.dnssec-failed.org.         IN      A
```

and I'm pretty sure another user reported it on IRC as well.

**Comment by pieterlexis** [comment]
this is because `dig` sets +AD by default. And `log-fail` is `process` and a little more, as described [here](https://doc.powerdns.com/md/recursor/dnssec/). I'll add a few words on dig there.
