### ISSUE TITLE
DNSSEC bogus on insecure in multiple TLDs

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#4035]
Examples (dnsviz):
[cdn-01.independent.ie](http://dnsviz.net/d/cdn-01.independent.ie/V20Ksw/dnssec/)
[www.shell.com.ru](http://dnsviz.net/d/www.shell.com.ru/V20MPA/dnssec/)

**Comment by ahupowerdns** [comment]
the independent.ie one resolves correctly now I think. At least no bogus.

**Comment by pieterlexis** [comment]
fixed in master thanks to @ahupowerdns 's fixes
