### ISSUE TITLE
No versions are listed at rec_control

### ISSUE THREAD

**Issue by kometchtech** [PowerDNS/pdns#4045]
**version**
`4.0.0-rc1`

**issue**

```
$ sudo rec_control --version
syntax: rec_control [options] command, options as below: 

  --chroot=...
        switch to chroot jail
  --config-dir=...
        Location of configuration directory (recursor.conf)
  --config-name=...
        Name of this virtual configuration - will rename the binary image
  --help
        Provide this helpful message
  --process=...
        When controlling multiple recursors, the target process number
  --socket-dir=...
        Where the controlsocket will live, /var/run when unset and not chrooted
  --timeout=...
        Number of seconds to wait for the recursor to respond
  --version
        Show the version of this program

In addition, 'rec_control help' can be used to retrieve a list
of available commands from PowerDNS
```

**OS**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie
$ uname -rm
3.4.39-s5p6818 armv7l
```

**Comment by Habbie** [comment]
`rec_control version` should work, but --version would indeed be nice to have.

**Comment by kometchtech** [comment]
Hi, @Habbie 

verified to work rec_control versionf.
For the time being in this for the time being to make sure.

**Comment by mzealey** [comment]
Note that this doesn't work if the recursor is not up, hence --version would be nice to have.

```
# rec_control version
Fatal: Unable to connect to remote '/var/run/pdns_recursor.controlsocket': Connection refused
```

**Comment by zeha** [comment]
Note that there will be possible confusion, which options returns the version of:

- the currently running recursor
- the `pdns_recursor` binary
- the `rec_control` binary

Maybe not having --version on rec_control isn't that bad.

**Comment by mzealey** [comment]
useful to have --version in case there has been a version mismatch between control/recursor or whatever. I think --version would always be understood to be the version of the program being run; but perhaps `rec_control version` command could be renamed `rec_control server-version` or somesuch to make clear.

**Comment by Habbie** [comment]
No, I don't like `server-version`. Proposal: remove `--version` from the `_control --help` texts, and when people type it anyway, tell them about `version`.

**Comment by omoerbeek** [comment]
Both `version` and `--version` work now as expected.
