### ISSUE TITLE
[dnsdist] Feature Request: Option to clear/replace the currently active rules

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#4047]
It would be nice if there was a way to replace the active rules without restarting dnsdist.

Currently, we're trying to achieve that by extracting the rule IDs from ```showRules()``` and looping over them with ```rmRule()``` which is clunky.

a first improvement would be a ```clearRules()``` command to remove all currently active rules.

Even better: A command like ```setRules(<list of rule definitions>)``` (or ```setActions()``` ?, not sure about the correct terminology)  which would allow us atomically replace the currently running ruleset.

The "Crème de la Crème" would be to be able to replace only a specific set of rules. For example, we would like to build a group of temporary rules which react to current abuse patterns and then do something like
```replaceRules('abuseruleset', <ruleDefinitions>)```. This would however require a new concept of a rule group, which is not currently present in dnsdist as far as I know.

**Comment by rgacogne** [comment]
`clearRules()` and `setRules()` have been added in 50ce537a41a4334b7afd5c47f086e582d175ff9b.
For the "crème de la crème" part, I like your idea of having a way to group rules, but perhaps you could open a different issue for it?

**Comment by gryphius** [comment]
thanks a lot @rgacogne , much appreciated! I'll open a new issue for the rule groups
