### ISSUE TITLE
dnsdist: invalid systemd service file

### ISSUE THREAD

**Issue by stirnim** [PowerDNS/pdns#4048]
The script https://github.com/PowerDNS/pdns/blob/master/build-scripts/build-dnsdist-rpm is changing the file https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/dnsdist.service.in during package building. Specifically, Line 43 replaces the occurrence of "dnsdist" with "dnsdist -u dnsdist -g dnsdist". While this is good for "ExecStart" line it also changes the "Documentation" line in the systemd file. However, systemd does not like the new documentation line:

old: Documentation=http://dnsdist.org
new: Documentation=http://dnsdist -u dnsdist -g dnsdist.org

Systemd warning when starting dnsdist:
systemd[1]: [/usr/lib/systemd/system/dnsdist.service:4] Invalid URL, ignoring: -u
systemd[1]: [/usr/lib/systemd/system/dnsdist.service:4] Invalid URL, ignoring: dnsdist
systemd[1]: [/usr/lib/systemd/system/dnsdist.service:4] Invalid URL, ignoring: -g
systemd[1]: [/usr/lib/systemd/system/dnsdist.service:4] Invalid URL, ignoring: dnsdist.org

**Comment by pieterlexis** [comment]
merged in #4049
