### ISSUE TITLE
dnsdist should at least warn when RemoteLogAction() is called w/o protobuf support

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#4078]
There is currently almost no way to know that protobuf is not supported, `newRemoteLogger()` succeeds and opens a connection, but then `RemoteLogAction()` and `RemoteLogResponseAction()` do nothing at all.
At the very least we should output a warning, but I think `newRemoteLogger()` should fail with an error message indicating that protobuf is disabled.

**Comment by jpmens** [comment]
I suggest also mentioning protobuf packages in [installation docs](http://dnsdist.org/download/)

**Comment by rgacogne** [comment]
#4079 makes `RemoteLogAction()` and `RemoteLogResponseAction()` when protobuf support is off. #4251 mentions protobuf and re2 as optional deps in the README and on the download page.
