### ISSUE TITLE
rec_control trigger to reload lua config file

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4085]
my use-case: I'm lazy so I want to store rpz in a flat file; but I want to reload this occasionally as I might do with reloading a backend

I don't see any fn in rec_control that would appear to do such a thing though.

(14:36:52) ahu: there should be
(14:36:56) Habbie: i don't see it though
(14:37:05) ahu: well the infrastructure is there in any case
(14:37:06) jalh: reload-zones doesn't seem to work fyi
(14:37:31) ahu: jalh, it likely is a void

**Comment by mzealey** [comment]
(Would be nice to have this before 4.0 final)

**Comment by mzealey** [comment]
Habbie: I'm not so sure of the pdns internals; but would the commit in #4090 actually reload the RPZ filter stuff correctly, or would it eg merge it ?
(13:09:26) lieter: and have not considered rpz
(13:10:13) jalh: but when I effectively re-run the rpzFile() command what does that do? My guess would be a merge but I'm not sure on the internals
(13:10:14) lieter: I'll have a look at it once I finish my current tast
(13:10:17) lieter: task*
(13:11:19) jalh: or if i change from an rpzFile to rpzMaster in the config file; I imagine that would not unload the previous settings
(13:11:23) jalh: thanks

**Comment by pieterlexis** [comment]
The current implementation blocks when reloading, documented in #4108. We will still need to un-block this post-4.0.0

**Comment by omoerbeek** [comment]
Closing this, as the async issues are dealt with in #4227
