### ISSUE TITLE
rpz blocks subdomains by default

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4086]
pdns 4.0-rc1. Flat RPZ file like:

```
$TTL 2h;
$ORIGIN domain.example.com.
@               SOA powerdns.example.net. hostmaster.example.com ( 1 12h 15m 3w 2h)
                NS powerdns.example.net.
; begin RPZ RR definitions

nxdomain.org        CNAME .
```

```
dig +short @10.10.7.77 foo.nxdomain.org
1.2.3.4
```

Whereas spec says it should only do that if I specif '*.nxdomain.org'.

I actually prefer this way of blocking the whole domain, but it does seem to be against the spec and @Habbie agrees.

**Comment by Habbie** [comment]
Going to bump this to rec-4.0.x as this bug is unlikely to hurt most RPZ users - who expects legal content on a subdomain of a malware domain?

**Comment by mzealey** [comment]
@Habbie concern is more that if someone devs against it like this and forgets to put the wildcards in then a later release will allow the subdomains through. But agreed that it is pointless to expect whitelisting under a domain that is blocked.

**Comment by Habbie** [comment]
Want to PR a line on it for the changelog? :)

**Comment by Habbie** [comment]
rec-4.0.0 milestone just for mentioning this in the changelog as a known issue. Issue itself is 4.0.x.
