### ISSUE TITLE
RPZ lookup from within lua script

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4088]
It would make the lua interface a lot more flexible if there was a way to:

1) Disable RPZ lookups for certain ips/domains eg in preresolve fn: `dq.disableRPZLookup = 1`

2) Do an inline RPZ lookup from within the lua script (or callback, but I think RPZ lookups are inline as they have to be on the local server). eg `local rpz_result = RPZLookup(dq.qname)` or perhaps the `dq` as you need to know if it was a tcp connection etc. Although it would be nice to be able to specify a custom domain or whatever rather than only being able to operate on the current dq object.

**Comment by omoerbeek** [comment]
I think this is mostly covered by the current RPZ code and policy events.
