### ISSUE TITLE
pdns-authoritative 4.0 CentOS 7 RPM

### ISSUE THREAD

**Issue by mschirrmeister** [PowerDNS/pdns#4100]
Hi,

I wanted to install pdns authoritative 4.0 server via RPM packages on CentOS 7. But the folder https://repo.powerdns.com/centos/x86_64/7/auth-40/ is empty.

Maybe just a temporary thing?

Thank you
Marco

**Comment by pieterlexis** [comment]
Packages have been added to the repo. I discovered a bug in our publishing script, will fix tomorrow.

**Comment by pieterlexis** [comment]
Bug in the publishing script is fixed. Thank you for the report!
