### ISSUE TITLE
Recursor 4.0.0-rc1 hangs at startup if protobufServer( "..." ) is set.

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#4105]
I tried to play with protobufServer() in lua-config-file. But with this setting, the Recursor doesn't start anymore. It hangs at "Reading random entropy from":

    # /usr/sbin/pdns_recursor --daemon=no --write-pid=no
    Jul 05 13:20:09 PowerDNS Recursor 4.0.0-rc1 (C) 2001-2016 PowerDNS.COM BV
    Jul 05 13:20:09 Using 64-bits mode. Built using gcc 4.8.5 on Jun 17 2016 12:00:42 by abuild@lamb09.
    Jul 05 13:20:09 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2. 
    Jul 05 13:20:09 Reading random entropy from '/dev/urandom'

**Comment by pieterlexis** [comment]
Hi @paddg, can you supply your lua-config-file and the pdns.conf. With an empty `protobufServer()` and one pointed to a non-listening port, I cannot manage to let it hang.

**Comment by paddg** [comment]
From IRC:
It turned out, the the chosen IP address in the protobufServer have to work! At least it must answering the SYNs with anything. RST or "ICMP unreachable" for instance.

**Comment by rgacogne** [comment]
I'd like to keep getting an error when the server is not reachable at startup, but I should probably add an option to do an asynchronous connection, so we don't _need_ it to be available.
