### ISSUE TITLE
Unable to use a v6 address as master for a slave zone?

### ISSUE THREAD

**Issue by Chealion** [PowerDNS/pdns#4107]
PowerDNS versions tried: 3.3 (default Ubuntu Trusty package) and 4.0rc2 (repo.powerdns.com)
Backend: gmysql
DNSSEC: No
Operating system: Ubuntu 14.04

When attempting to use an IPv6 address as the master address for a slave zone, the following error is seen:

    2016-07-05T12:30:25.125821+00:00 hnl-ns-1 pdns[18056]: While checking domain freshness: While attempting to query freshness of 'test6.chealion.ca': Unable to convert presentation address '2605:fd00:2:1003:216:3eff:fe00:8546:5354'

Using `telnet` and watching via tcpdump confirms the port and address are accessible, but no packets are sent by PowerDNS.

Switching it to a hostname also fails (somewhat expected, I've never seen hostnames used before. Can't find where in the spec it's excluded.)

Switching it to a standard v4 address (eg. 127.0.0.1:5354) does work but due to the environment is unideal.

Port 5354 is used by the master server - miniDNS from the Designate OpenStack project in this case and is up and running.

**Comment by Habbie** [comment]
Hi! That address looks weird - please don't obfuscate data while writings tickets.

But, as I understand it, you want to override a port on a v6 master. I'll see if we have a syntax for that.

**Comment by Chealion** [comment]
Right. I never did verify if it would have worked via port 53. Address has been unobfuscated.

**Comment by Habbie** [comment]
Can you try `[2001:db8::1]:5354`?

**Comment by Chealion** [comment]
The error is no longer present. Issue is the lack of of square brackets?

**Comment by Habbie** [comment]
Yes. What you put in was simply invalid. Because IPv6 uses the : symbol itself, adding a port requires special care - in our case (and in many other applications), the square brackets.

**Comment by Chealion** [comment]
Sorry. Much appreciated; bug is not in powerdns then. 👍
