### ISSUE TITLE
dnspcap2protobuf: option to drop source IP address from generated protobuf

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#4111]
not very urgent likely

**Comment by rgacogne** [comment]
We already have some sort of basic anonymisation mechanism there, I think. The requestor/responder IPv4 addresses seem to be ORed with an optional integer parameter `ind`.

**Comment by omoerbeek** [comment]
Nobody requested this feature, so we're closing it. Please re-open if you have a valid use-case.
