### ISSUE TITLE
Ubuntu xenial repository forces mysql 5.7 - not working with mariadb

### ISSUE THREAD

**Issue by fliespl** [PowerDNS/pdns#4118]
I have added pdns repository in my ubuntu xenial (16.04) to update from alpha2 to rc2.

`deb [arch=amd64] http://repo.powerdns.com/ubuntu xenial-auth-40 main`

Unfortunately it's forcing mysql 5.7 and doesn't support mariadb-server-10.0 (it was replaced on my end).

PowerDNS Authoritative Server 4.0.0-alpha2 installs and works correctly with mariadb.

Is this a bug or simply mariadb support was dropped in release candidates?

**Comment by pieterlexis** [comment]
Interesting, the dependencies have not changed. We depend on libmysqlclient to handle the connections in the MySQL backend and have a 'Suggests: mysql-server', that will never pull in any MySQL server.

Can you show us the exact steps you took to get to this state and the output of the installation where it forces the installation?

**Comment by fliespl** [comment]
Sure:
added repo to apt list,
added pin record,

`apt update`

```
root@bigmike:~# apt list --upgradable
Listing... Done
pdns-backend-mysql/unknown 4.0.0~rc2-1pdns.xenial amd64 [upgradable from: 4.0.0~alpha2-3build1]
pdns-server/unknown 4.0.0~rc2-1pdns.xenial amd64 [upgradable from: 4.0.0~alpha2-3build1]
```

```
root@bigmike:~# apt install pdns-server pdns-backend-mysql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dbconfig-common dbconfig-mysql libdbd-mysql-perl liblua5.3-0
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  mysql-client mysql-client-5.7 mysql-client-core-5.7
Suggested packages:
  mysql-server pdns-recursor
The following packages will be REMOVED
  mariadb-client mariadb-client-10.0 mariadb-client-core-10.0 mariadb-server-10.0
The following NEW packages will be installed
  mysql-client mysql-client-5.7 mysql-client-core-5.7
The following packages will be upgraded:
  pdns-backend-mysql pdns-server
2 to upgrade, 3 to newly install, 4 to remove and 7 not to upgrade.
Need to get 7,859 kB/9,243 kB of archives.
After this operation, 45.0 MB disk space will be freed.
Do you want to continue? [Y/n] 
```

**Comment by pieterlexis** [comment]
right, so yes... we link against libmysqlclient and not against libmariadbclient and ubuntu removes libmariadbclient and removes mariadb-server as a result.

@zeha: Do you know if libmariadbclient is binary compatible with libmysqlclient so we can depend on either? ANd if so, how can you depend on either lib?

**Comment by zeha** [comment]
> right, so yes... we link against libmysqlclient and not against libmariadbclient and ubuntu removes libmariadbclient and removes mariadb-server as a result.
> 

So that in itself sounds wrong, I could take a look if you point me at a log.
> @zeha: Do you know if libmariadbclient is binary compatible with libmysqlclient so we can depend on either? ANd if so, how can you depend on either lib?
> 
AFAIK you should be able to link to either one and use that to talk to a server of another "brand". Pretty sure they'll not be/stay binary compatible.

**Comment by pieterlexis** [comment]
On debian sid, these packages are not in conflict:

```
lieter $ sudo apt-get install mariadb-server pdns-backend-mysql mariadb-client-10.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  dbconfig-common dbconfig-mysql libaio1 libdbd-mysql-perl libdbi-perl
  libhtml-template-perl libmysqlclient18 libterm-readkey-perl
  mariadb-client-core-10.0 mariadb-common mariadb-server-10.0
  mariadb-server-core-10.0 mysql-common
Suggested packages:
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl
  libipc-sharedcache-perl mariadb-test tinyca mysql-server
The following NEW packages will be installed:
  dbconfig-common dbconfig-mysql libaio1 libdbd-mysql-perl libdbi-perl
  libhtml-template-perl libmysqlclient18 libterm-readkey-perl mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server mariadb-server-10.0
  mariadb-server-core-10.0 mysql-common pdns-backend-mysql
0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.7 MB of archives.
After this operation, 143 MB of additional disk space will be used.

```

However they both declare the same conflicts:

Xenial:
```
Replaces: mariadb-client-5.5, mariadb-server-10.0 (<< 10.0.13-1~), mysql-client, mysql-client-5.5, mysql-client-5.6, mysql-client-5.7, virtual-mysql-client
Conflicts: mysql-client-core-5.5, mysql-client-core-5.6, mysql-client-core-5.7
Breaks: mariadb-client-5.5, mariadb-server-10.0 (<< 10.0.13-1~), mysql-client, mysql-client-5.5, mysql-client-5.6, mysql-client-5.7, virtual-mysql-client
```

Debian Jessie:
```
Replaces: mariadb-client-5.5, mariadb-server-10.0 (<< 10.0.13-1~), mysql-client, mysql-client-5.5, mysql-client-5.6, mysql-client-5.7, virtual-mysql-client
Conflicts: mysql-client-core-5.5, mysql-client-core-5.6, mysql-client-core-5.7
Breaks: mariadb-client-5.5, mariadb-server-10.0 (<< 10.0.13-1~), mysql-client, mysql-client-5.5, mysql-client-5.6, mysql-client-5.7, virtual-mysql-client
```

The only difference I see is that the pdns-backend-mysql from Jessie depends on libmysqlclient18 and the one we build for Xenial on "libmysqlclient20 (>= 5.7.11)". However, the alpha from the Xenial repos does not have this issue it's dependencies:

```
Depends: dbconfig-common, dbconfig-mysql, pdns-server (>= 4.0.0~alpha2-3build1), ucf (>= 0.28), debconf (>= 0.5) | debconf-2.0, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libmysqlclient20 (>= 5.7.11), libstdc++6 (>= 5.2)
```

While our package has the following dependencies:
```
Depends: pdns-server (>= 4.0.0~rc2-1pdns.xenial), ucf (>= 0.28), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libmysqlclient20 (>= 5.7.11), libstdc++6 (>= 5.2)
```

I have no clue why that would cause this dependency issue... I am almost inclined to have this be filed at Ubuntu for the MySQL/MariaDB maintainers to figure out and tell us what is wrong...
