### ISSUE TITLE
Carbon issues after upgrading to auth 4.0.0 RC2

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#4120]
After upgrading to auth 4.0.0 RC2 the following messages show up in my syslog:

Jul  6 13:00:21 lan pdns[72642]: Unable to write data to carbon server at 127.0.0.1:2003: failed in write2WithTimeout: Socket is not connected
Jul  6 13:00:51 lan pdns[72642]: Unable to write data to carbon server at 127.0.0.1:2003: failed in write2WithTimeout: Socket is not connected
Jul  6 13:01:21 lan pdns[72642]: Unable to write data to carbon server at 127.0.0.1:2003: failed in write2WithTimeout: Socket is not connected

Version 3.4.9 doesn't have this issue and neither does recursor 4.0.0 RC1.

I'm running FreeBSD 10.3-RELEASE-p5 amd64

The metronome version I'm running is github hash 1a6dd70 

You can check the metronome data via https://metronome.cainites.net

**Comment by rgacogne** [comment]
Reproduced on FreeBSD 10.2. The non-blocking `connect()` returns immediately with `EINPROGRESS` and then `write()` fails with `ENOTCONN`. It could be worked around in `Socket::connect()` by optionally calling `waitForRWData()` with a timeout when `connect()` returns `EINPROGRESS`. It would probably only make sense when we are going to write to the socket right after calling `Socket::connect()`.
