### ISSUE TITLE
`rec_control help` output too big for OSX unix dgram

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4141]
```
$  sudo ./rec_control help
Fatal: Timeout waiting for answer from control channel
```

```
Jul 10 21:00:15 Error dealing with control socket request: Unable to send message over control channel '/var/run/lsocks6iZV6': Message too long
```

Some investigation shows that the message is 2407 bytes. `getsockopt(d_fd, SOL_SOCKET, SO_SNDBUF, ..)` reports a 2048 byte limit. On various Linuxes tested, the message has no trouble passing over the control channel, I understand 128k is a more common limit.

Raising the `net.local.dgram.maxdgram` sysctl from its 2048 default (10.10 and 10.11 at least), then restarting recursor, does fix this.

**Comment by okoeroo** [comment]
Can confirm with version 4.1.12 on MacOS 10.14.4 to experience the same issue. The default is indeed 2048 for net.local.dgram.maxdgram by default. Stretching it to 128k solves the problem.

**Comment by Habbie** [comment]
I suspect #7311 fixed this.

**Comment by omoerbeek** [comment]
It should have. If not, re-open issue please.
