### ISSUE TITLE
auth 4.0.0 may be double counting TCP/IP answers

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#4146]
or perhaps multiple questions per TCP/IP session confuse us
![dubbel](https://cloud.githubusercontent.com/assets/1223657/16724963/74b105e6-4755-11e6-9597-a4322edbed42.png)
This shows upgrade from 3.x.x to 4.0.0

**Comment by rgacogne** [comment]
After skimming over the code, I would bet on {A,I}XFR being the culprit. Counters are now updated in `sendPacket()`, which might get called several times for a single {A,I}XFR answer.
