### ISSUE TITLE
dnsdist downstream sockets can go stale but it never recovers

### ISSUE THREAD

**Issue by yunzheng** [PowerDNS/pdns#4155]
I'm using dnsdist (1.0) with some downstream servers over VPN and sometimes the connected UDP socket can go stale. It does not recover from this state and I have to restart dnsdist to fix it.

Although the downstream server can still be marked UP or DOWN by the `healthChecksThread()` as it does not use connected sockets there.

The UDP `send()` in `udpClientSendRequestToBackend` will actually return an error code of -1 but it's only checked to increase the error counters.

What I expected was that it would reconnect the socket to recover from this error.

I implemented the following `reconnect()` function in the `Downstream` class which I call after increasing the error counters:

```
void reconnect()
{
   shutdown(fd, SHUT_RDWR);
   close(fd);
   if (!IsAnyAddress(remote)) {
      fd = SSocket(remote.sin4.sin_family, SOCK_DGRAM, 0);
      if (!IsAnyAddress(sourceAddr)) {
        SSetsockopt(fd, SOL_SOCKET, SO_REUSEADDR, 1);
        SBind(fd, sourceAddr);
      }
      SConnect(fd, remote);
   }
}
```

The `shutdown()` was needed to signal the blocking `recv()` call in the `responderThread`.

I'm not sure if this is the correct way, but it works well for me.

**Comment by rgacogne** [comment]
Would you happen to know the value of `errno` after `send()` returns -1? I'm guessing `ENETDOWN` or `ENETUNREACH`.
If I understand correctly, closing the socket is not enough to wake the `responderThread` from `recv()`, but `shutdown()` is?

**Comment by rgacogne** [comment]
I've done some tests, and it looks like `send()` might fail with `EINVAL` when the interface the socket was bound to doesn't exist anymore..

**Comment by yunzheng** [comment]
I used the following debug print:

```warnlog("send() returned: %d, errno: %s, from: %s, to: %s, ret, strerror(errno), remote.toStringWithPort(), ss->getName());```

From my logs it would print:

    send() returned: -1, errno: Invalid argument, from: x.x.x.x:31451

So yes, errno is ```EINVAL```. Closing the socket was not enough for ```recv()``` to return, ```shutdown``` was needed as well.

Nice that you are able to reproduce it as well.

**Comment by asgeirn** [comment]
Stumbled on this issue on Ubuntu 22.04 (dnsdist 1.6.1) with backend servers only accessible through VPN.

I hid these backends in a `PoolAvalilableRule`, and this works, but when VPN is up again, all DNS packets to the backends are dropped.  

Some stracing later I figured out that errno is set to `ENETUNREACH` (as it should I suppose).

With the attached patch [reconnect-enetunreach.patch.txt](https://github.com/PowerDNS/pdns/files/9261871/reconnect-enetunreach.patch.txt) I get the following verbose log when querying a domain only valid inside the VPN, and a successful response from `dig`
:
```
aug. 04 19:14:09 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Marking downstream 10.17.112.2:53 as 'up'
aug. 04 19:14:13 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Error sending request to backend 10.17.112.2:53: Network is unreachable
aug. 04 19:14:13 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Got query for XXXXXX|A from 10.0.1.1:42867, relayed to 10.17.112.2:53
aug. 04 19:14:16 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Had a downstream timeout from 10.17.112.2:53 (10.17.112.2:53) for query for XXXXXX|A from 10.0.1.1:42867
aug. 04 19:14:18 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Got query for XXXXXX|A from 10.0.1.1:36833, relayed to 10.17.112.2:53
aug. 04 19:14:18 asgeir-ThinkPad-T15-Gen-2i dnsdist[1537652]: Got answer from 10.17.112.2:53, relayed to 10.0.1.1:36833, took 7261.43 usec
```

**Comment by mnordhoff** [comment]
For what it's worth, it would be better to file a new issue for this. Comments on closed issues may not be seen.

**Comment by mnordhoff** [comment]
That works too. :D
