### ISSUE TITLE
Recursor 4.0.0 SERVFAIL for localhost (A and PTR) if in validation mode

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#4156]
Since `localhost. A` and `1.0.0.127.in-addr.arpa. PTR` are hardcoded in syncres.cc, Recursor responds with SERVFAIL if it is in `dnssec=validate` mode.

**Comment by paddg** [comment]
Workaround: add Negative Trust Anchors for `localhost.` and `127.in-addr.arpa.`. See https://doc.powerdns.com/md/recursor/dnssec/#negative-trust-anchors

**Comment by Habbie** [comment]
Related: #4149
