### ISSUE TITLE
API RrSet type MX prio attr

### ISSUE THREAD

**Issue by adrpp** [PowerDNS/pdns#4172]
Hello,

just wondering about RrSet's prio attribute role for MX rrset type.
Noticed that MX's resource record content must start with prio int. What for is there prio attribute on 
RrSet object ?
Without looking into tests I would assume that setting prio attribute on RrSet object would do the trick, it sounds a bit more native :)

At all, if there is any RrSet type where prio attr makes any sense, it's MX type. So why to have to put prio int into Rr content ?

Affects API ver 4 alpha2

Rgds,
Adrian

**Comment by Habbie** [comment]
@adrpp the v1 api (as deployed in pdns v4) does not have a prio/priority field/attribute. Where are you seeing it?

**Comment by adrpp** [comment]
@Habbie sorry, my bad
