### ISSUE TITLE
PowerDNS 3.4.8 does not listen on IPv6 socket

### ISSUE THREAD

**Issue by aabdnn** [PowerDNS/pdns#4177]
The PowerDNS documentation says that the default value of "local-ipv6" is "::". To me, this means that by default, PowerDNS authoritative server should bind to IPv6 sockets.

However, upon installing the "pdns-3.4.8-1.el7.x86_64" package from EPEL on CentOS 7, and starting pdns, it does not listen on an IPv6 socket:

```
# ss -lntu | fgrep :53
udp    UNCONN     0      0         *:53                    *:*                  
tcp    LISTEN     0      128       *:53                    *:*
```

The only way to get pdns to listen on IPv6 sockets is to explicitly add "local-ipv6" to the config file, so the code and documentation don't agree.

**Comment by Habbie** [comment]
You're right, this was updated in the docs when we changed the default to `::` for 4.x, but this happened before we froze the 3.x docs. Fixed in 88cc8dd69dd5ad46dae7587f3939829ca99da02b. Thanks!
