### ISSUE TITLE
missing pkg-config leads to confusing messages about lua

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4190]
rec 4.0.0

```
configure:18068: checking for LUA
configure:18127: result: no
configure:18068: checking for LUA
configure:18127: result: no
configure:18068: checking for LUA
configure:18127: result: no
configure:18068: checking for LUA
configure:18127: result: no
configure:18245: checking for chosen LUA
configure:18250: error: cannot find lua
```

there is no output of these tests at all. @pieterlexis suggests we should abort if pkg-config is missing at all.

**Comment by rubenk** [comment]
https://github.com/PowerDNS/pdns/blob/master/pdns/recursordist/configure.ac#L35 was supposed to prevent this. Do you perhaps have a pkg.m4 somewhere but no pkg-config?
