### ISSUE TITLE
PowerDNS 4.0 CentOS 7 repo does not contain backend for tinydns

### ISSUE THREAD

**Issue by mooinglemur** [PowerDNS/pdns#4194]
https://repo.powerdns.com/centos/x86_64/7/auth-40/ is missing a package for the tinydns backend.  On IRC, Habbie suggested it may be due to tinycdb not being available in the base repo.  tinycdb is in epel, however, as is PowerDNS v3, including its corresponding tinydns backend rpm.

Habbie suggested I open a ticket to track the issue.

Thanks :)

**Comment by Habbie** [comment]
as @mooinglemur noted, tinycdb is in EPEL. The question here might be whether we allow ourselves to depend on EPEL. If not, maybe we can make an exception for specific backends?
