### ISSUE TITLE
pdnsutil edit-zone adding trailing dot in SOA MNAME

### ISSUE THREAD

**Issue by nivex** [PowerDNS/pdns#4196]
According to [the backend docs](https://doc.powerdns.com/md/authoritative/backend-generic-sql/) the SOA MNAME should not have a trailing dot.
`pdnsutil edit-zone` appears to be adding one:

<pre>
# pdnsutil create-zone test.example.com
Creating empty zone 'test.example.com'

# pdnsutil edit-zone test.example.com
...
Checked 2 records of 'test.example.com', 0 errors, 0 warnings.
Detected the following changes:

+test.example.com 3600 IN NS phoob.example.com
-test.example.com 3600 IN SOA a.misconfigured.powerdns.server hostmaster.test.example.com 1 10800 3600 604800 3600
+test.example.com 3600 IN SOA meeple.example.com hostmaster.test.example.com 1 10800 3600 604800 3600

(a)pply these changes, (e)dit again, (r)etry with original zone, (q)uit: a
Adding empty non-terminals for non-DNSSEC zone

MySQL [pdns]> select id,name,content from records where name="test.example.com" and type="SOA"\G
*************************** 1. row ***************************
     id: 2753
   name: test.example.com
content: meeple.example.com. hostmaster.test.example.com. 1 10800 3600 604800 3600
</pre>

**Comment by Habbie** [comment]
Fixed in #4547
