### ISSUE TITLE
allow multiple trust-anchors for the same name in the recursor

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#4200]
every next addDS() is replacing the values of the previous one. Multiple anchors are necessary during (root) key/algorithm rollovers.

Proposed format
```
-- remove default key
clearDS()
-- add new keys
addDS(".", "first.......")
addDS(".", "next........")
~~~

And maybe add a dnskey2DS() function so it is no longer necessary to convert DNSKEYs with external tools like ldns-key2ds in DS record format.
```
addDS(".", dnskey2DS("...."))
```

**Comment by pieterlexis** [comment]
quick notes:
 * `setDS()` to overwrite
 * more `rec_control` commands to accommodate this change
