### ISSUE TITLE
PowerDNS with MySQL 5.7 (Percona) column length too big

### ISSUE THREAD

**Issue by javiermatos** [PowerDNS/pdns#4202]
Hi,

I have created a database using MySQL 5.7 (Percona) with utf8 encoding. The problem is that when I try to load the schema installed in /usr/share/doc/pdns-backend-mysql/schema.mysql.sql (Ubuntu 16.04) I get the following error:

`ERROR 1074 (42000) at line 15: Column length too big for column 'content' (max = 21845); use BLOB or TEXT instead`

This error is because of a too big column (there are two big columns in that schema for utf8):

```
CREATE TABLE records (
  id                    INT AUTO_INCREMENT,
  domain_id             INT DEFAULT NULL,
  name                  VARCHAR(255) DEFAULT NULL,
  type                  VARCHAR(10) DEFAULT NULL,
  content               VARCHAR(64000) DEFAULT NULL,
  ttl                   INT DEFAULT NULL,
  prio                  INT DEFAULT NULL,
  change_date           INT DEFAULT NULL,
  disabled              TINYINT(1) DEFAULT 0,
  ordername             VARCHAR(255) BINARY DEFAULT NULL,
  auth                  TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
) Engine=InnoDB;
```

What is the recommended way to solve it? Should I use latin1 or set those columns to use TEXT instead of VARCHAR(64000)? Will PowerDNS show an unexpected behavior when moving from big columns from VARCHAR(64000) to TEXT?

**Comment by javiermatos** [comment]
May I suggest to use "CREATE TABLE IF NOT EXISTS" to add "idempotence" when creating the schema in MySQL? I have an ansible script and it fails when the schema is already loaded.

**Comment by Habbie** [comment]
Ran into this same issue `(max = 21845)` on osx.

**Comment by Habbie** [comment]
Closing in favour of #3987. @javiermatos if you still want the `IF NOT EXISTS`, please create another ticket.
