### ISSUE TITLE
Packet cache messes with error reporting to clients

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#4204]
After receiving and parsing a packet in the Authoritative Server, the packetcache is consulted before the EDNS options and versions are checked. This leads e.g. to NOERROR responses to queries with EDNS0 version 1 set (which must be BADVERS).

**Comment by Habbie** [comment]
We should probably change this cache to work like the one in dnsdist (which is inspired on OpenBSD's rebound).
