### ISSUE TITLE
Pdns service stops working periodically and must be restarted

### ISSUE THREAD

**Issue by tesargusmawan** [PowerDNS/pdns#4216]
This is happened in 4.0.0 Alpha 2, but I cannot reproduce the error.

The service stops working, maybe every 1 hour. This is the log message of `service pdns status`:

> Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail 

Restart pdns service solves the problem. I didn't do anything at server-level when the service was running that could cause termination (ex: restart mysql service, or even add zone record).

**Comment by ahupowerdns** [comment]
This is a known issue in Alpha 2. Please try 4.0.0.

**Comment by tesargusmawan** [comment]
Just updated to 4.0.0.

Different error log appeared maybe after 1 hour, though the service can still running:

> Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Could not prepare statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: MySQL server has gone away), aborting

> Backend error (retry once): GSQLBackend lookup query:Could not prepare statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: MySQL server has gone away

Restart pdns service solves the problem, at least in one hour.
