### ISSUE TITLE
PowerDNS Auth 4.0.0 API: MX record not showing TTL.

### ISSUE THREAD

**Issue by TheDJVG** [PowerDNS/pdns#4231]
Hello,

When GETting a zone using the RESTful API I'm 0 getting instead of the right TTL value for the MX record.
The TTL is stored in the database:
>     *************************** 1. row ***************************
             id: 410
      domain_id: 2
           name: example.tld
           type: MX
        content: mx.example.tld
            ttl: 3600
           prio: 10
    change_date: NULL
       disabled: 0
      ordername:
           auth: 1

And the API returns this:

>      "name": "example.tld.",
      "records": [
        {
          "content": "10 mx.example.tld.",
          "disabled": false
        }
      ],
      "ttl": 0,
      "type": "MX"
    }

I'm using gmysql backend.
Let me know if I'm missing some information about this or I'm doing something wrong. I don't see this happening with other record types.

- DJVG

**Comment by zeha** [comment]
How many MX records do you have under example.tld? can you paste your full zone?

**Comment by TheDJVG** [comment]
This is the full zone, exported using pdnsutil edit-zone:

>      $ORIGIN .
     test.dev.example.com      3600    IN      SOA     dev.example.com noc.example.com 2016072430      10800 3600 604800 3600
     test.dev.example.com      3600    IN      A       85.12.6.62
     test.dev.example.com      3600    IN      NS      dev.example.com
     test.dev.example.com      3600    IN      MX      10 dev2.example.com
     test.dev.example.com      3600    IN      MX      20 dev2.example.com
     test.dev.example.com      3600    IN      TXT     "This is a test!"
     test.dev.example.com      3600    IN      TXT     "This is another test!"
     test.dev.example.com      3600    IN      SRV     10 0 443 exchange.example.net

Of course I'm not using example.com but I need to mask it because I can't post the real domain.

**Comment by zeha** [comment]
I tried to reproduce this on current master, but can't.

```
% EDITOR=/bin/cat ../pdns/pdnsutil --config-dir=. edit-zone test.dev.example.com
; Warning - every name in this file is ABSOLUTE!
$ORIGIN .
test.dev.example.com	3600	IN	SOA	dev.example.com noc.example.com 2016072430 10800 3600 604800 3600
test.dev.example.com	3600	IN	A	85.8.6.62
test.dev.example.com	3600	IN	NS	dev.example.com
test.dev.example.com	3600	IN	MX	10 dev2.example.com
test.dev.example.com	3600	IN	MX	20 dev2.example.com
test.dev.example.com	3600	IN	TXT	"This is a test!"
test.dev.example.com	3600	IN	TXT	"This is another test!"
test.dev.example.com	3600	IN	SRV	10 0 443 exchange.example.net
No change to file
```

```
% curl http://127.0.0.1:5556/api/v1/servers/localhost/zones/test.dev.example.com. -H 'X-API-Key: 1234567890abcdefghijklmnopq-key' | jq .
{
  "account": "",
  "dnssec": false,
  "id": "test.dev.example.com.",
  "kind": "Native",
  "last_check": 0,
  "masters": [],
  "name": "test.dev.example.com.",
  "notified_serial": 0,
  "rrsets": [
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "10 0 443 exchange.example.net.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SRV"
    },
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "\"This is another test!\"",
          "disabled": false
        },
        {
          "content": "\"This is a test!\"",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "TXT"
    },
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "10 dev2.example.com.",
          "disabled": false
        },
        {
          "content": "20 dev2.example.com.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "MX"
    },
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "dev.example.com. noc.example.com. 2016072430 10800 3600 604800 3600",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "SOA"
    },
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "dev.example.com.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    },
    {
      "comments": [],
      "name": "test.dev.example.com.",
      "records": [
        {
          "content": "85.8.6.62",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "A"
    }
  ],
  "serial": 2016072430,
  "soa_edit": "",
  "soa_edit_api": "",
  "url": "api/v1/servers/localhost/zones/test.dev.example.com."
}
```

Note that the given example zone has some logic errors, but nevertheless the TTL on test.dev.example.com./MX appears correct in the JSON output.

**Comment by TheDJVG** [comment]
I've tried to re-create the "test" zone and I can't reproduce it either now, weird. I'll try some more things to check if it makes a difference. I should note the zone was edited a lot using the api (changed rrsets) and the edit-zone function of pdnsutil. I'll do some more testing.

**Comment by zeha** [comment]
Thought: ENTs

**Comment by Habbie** [comment]
Closing until we receive a reproduction scenario.
