### ISSUE TITLE
API Zone create - always get a 404 "not found"

### ISSUE THREAD

**Issue by Michamicha** [PowerDNS/pdns#4234]
When creating a new zone by API, I always get a "not found" back, although the path is according to the docs. 
Querying a zone with a GET request is working fine.

(v4.0.0 on Debian Jessie)

**Comment by setharnold** [comment]
Is there anything in the logs?

**Comment by Habbie** [comment]
@michamicha please show us your full request and response, and please mention the version of PowerDNS (Auth, I presume) you are using. Note that between 3.4.x and 4.0.0 the API path changed. Our docs reflect this.

**Comment by Michamicha** [comment]
Nothing, but I found where the 404 comes from. It´s from nginx (which I setup a s ssl reverse proxy).

When calling the pdns API server directly, it gives a connection refused as soon as a POST request is made. GET requests are fine.

**Comment by Michamicha** [comment]
curl -X POST --data '{"name":"example.org.", "kind":"Native", "masters": [], "nameservers": ["ns1.example.org.", "ns2.example.org."]}' -v -H 'X-API-Key: CHANGED' http://127.0.0.1:8001/servers/localhost/zones
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> POST /servers/localhost/zones HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8001
> Accept: */*
> X-API-Key: CHANGED
> Content-Length: 112
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 112 out of 112 bytes
< HTTP/1.1 404 Not Found
< Connection: close
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
* Server PowerDNS/4.0.0 is not blacklisted
< Server: PowerDNS/4.0.0
<
* Closing connection 0

**Comment by Habbie** [comment]
That looks like the 3.x api path

On July 27, 2016 10:59:55 AM GMT+02:00, Michamicha <notifications@github.com> wrote:
>curl -X POST --data '{"name":"example.org.", "kind":"Native",
>"masters": [], "nameservers": ["ns1.example.org.",
>"ns2.example.org."]}' -v -H 'X-API-Key: CHANGED'
>http://127.0.0.1:8001/servers/localhost/zones
>* Hostname was NOT found in DNS cache
>*   Trying 127.0.0.1...
>* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
>> POST /servers/localhost/zones HTTP/1.1
>> User-Agent: curl/7.38.0
>> Host: 127.0.0.1:8001
>> Accept: */*
>> X-API-Key: CHANGED
>> Content-Length: 112
>> Content-Type: application/x-www-form-urlencoded
>>
>* upload completely sent off: 112 out of 112 bytes
>< HTTP/1.1 404 Not Found
>< Connection: close
>< Content-Length: 9
>< Content-Type: text/plain; charset=utf-8
>* Server PowerDNS/4.0.0 is not blacklisted
>< Server: PowerDNS/4.0.0
><
>* Closing connection 0
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/4234#issuecomment-235528228

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by pieterlexis** [comment]
Please use the 4.0.0 API path. This changed from `/` to `/api/v1/` between 3 and 4. So your request should be sent to `/api/v1/servers/localhost/zones`. See [the docs](https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1)

**Comment by Michamicha** [comment]
This results in 500 internal server error, in the daemon.log there is the following:

Jul 27 14:30:43 debian pdns_server[25862]: Jul 27 14:30:43 HTTP ISE for "/api/v1/servers/localhost/zones": Exception: Database error trying to insert new domain 'example.org.': Could not execute mysql statement: insert into domains (type,name,master,account,last_check,notified_serial) values(?,?,?,?,NULL,NULL): Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited
to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by pieterlexis** [comment]
seems pretty clear to me, please check at your MySQL configs. This also mentioned in [our documentation](https://doc.powerdns.com/md/authoritative/backend-generic-mysql/#using-mysql-replication)

**Comment by Michamicha** [comment]
Thx, I upgraded from 3.4.1 and was not aware about this. After issuing the following:

FLUSH TABLES WITH READ LOCK;
FLUSH LOGS;
SET GLOBAL binlog_format = 'MIXED';
FLUSH LOGS;
UNLOCK TABLES;

Everything works fine.
Thx for your help!

Michael
