### ISSUE TITLE
recursive-cache on pdns looks seriously broken (4.0.0)

### ISSUE THREAD

**Issue by CaptainQwark** [PowerDNS/pdns#4238]
Hi, 

I'm running pdns 4.0.0 with a pdns-recursor 4.0.0 behind it. (Yes, I know. Historical reasons :)).
These are the latest 4.0.0 builds from repo.powerdns.com, running on debian Jessie.

default config for pdns plus:
`recursor=127.0.0.1:5300`

default config for recursor plus:
`local-port=5300`

start pdns and pdns-recursor and do this: `watch -n.1 dig @127.0.0.1 -p 53 www.nu.nl` and be amazed by the weird TTL activity. 

The TTL drops down from 60 in 0 just few seconds and after it reaches 0 the counter wraps and gives results like:

```
;; ANSWER SECTION:
www.nu.nl.              4294967285 IN   CNAME   nunl.aws.sanomaservices.nl.
nunl.aws.sanomaservices.nl. 4294967285 IN A     107.178.244.221
```

Setting `recursive-cache-ttl=0`( or 1) fixes the problem. 
running the watch/dig directly on the recursor on port 5300 gives normal results. 

Alex.

**Comment by Habbie** [comment]
Proposed fix: remove the recursive cache.

**Comment by CaptainQwark** [comment]
Sure, that's one option. :) But I'd really like a recursive cache!
Particularly if the recursor is on a different host.
