### ISSUE TITLE
Cannot build 4.0.0 on Debian or Ubuntu

### ISSUE THREAD

**Issue by paulehoffman** [PowerDNS/pdns#4239]
Greetings. Doing a "make all" on either Debian 8.5 x64 or Ubuntu 16.04.1 x64 fails after a while with:

```
  CXXLD    pdnsutil

pdnsutil.o: In function `boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':

/usr/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'

pdnsutil.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':

/usr/include/boost/program_options/detail/value_semantic.hpp:167: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'

. . .
```

This is completely reproducible, and re-running "make install" fails at the same place each time.

**Comment by Habbie** [comment]
Hi Paul! Can you share your `configure` line and perhaps also the output from configure? -Peter

**Comment by pieterlexis** [comment]
it could be possible we fail to detect a library that is always there in the build environments... can we also get a `dpkg -l | grep boost`?

**Comment by paulehoffman** [comment]
Output from configure:

# ./configure --prefix=/root/Target/pdns-4.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for bison... no
checking for byacc... no
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking if bison is the parser generator... no
checking for flex... no
checking for lex... no
checking if the lexer is flex... no
checking whether make sets $(MAKE)... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether we will be linking in LuaJIT... no
checking whether we will be linking in Lua... auto
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for LUA... no
checking for chosen LUA... not found
checking how to run the C++ preprocessor... g++ -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking whether we will enable compiler security checks... yes
checking whether C++ compiler handles -Werror -Wunknown-warning-option... no
checking whether C++ compiler handles -pie... yes
checking whether C++ compiler handles -fstack-protector... yes
checking whether C++ compiler handles --param ssp-buffer-size=4... yes
checking whether C++ compiler handles -D_FORTIFY_SOURCE=2... yes
checking for how to force completely read-only GOT table... -Wl,-z -Wl,relro -Wl,-z -Wl,now
checking for library containing inet_aton... none required
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking for library containing gethostent... none required
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether struct tm is in sys/time.h or time.h... time.h
checking for tm_gmtoff in struct tm... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking whether we will be linking in Botan 1.10... no
checking whether we will be linking in libsodium... no
checking for pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking for ECDSA_do_sign... yes
checking whether NID_X9_62_prime256v1 is declared... yes
checking whether NID_secp384r1 is declared... yes
checking for ragel... no
checking for library containing clock_gettime... none required
checking for Boost headers version >= 1.35.0... yes
checking for Boost's header version... 1_58
checking for the toolset name used by Boost for g++... configure: WARNING: could not figure out which toolset name to use for g++

checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... no
checking whether to enable unit test building... no
checking whether to enable backend unit test building... no
checking whether to enable reproducible builds.... no
checking whether user requires sqlite3... no
checking for pandoc... pandoc
checking for strcasestr... yes
checking for localtime_r... yes
checking for recvmmsg... yes
checking whether to enable verbose logging... no
checking whether to enable PKCS11 support... no
checking whether to enable experimental GSS-TSIG support... no
checking whether we will be building the server... yes
checking whether we will be building and installing the extra tools... no
checking if we need to link in protobuf... auto
checking for PROTOBUF... no
checking for protoc... no
checking for mysql_config... /usr/bin/mysql_config
checking whether to enable ZeroMQ connector in remotebackend... no
checking whether we can build module "bind"... yes
checking whether we can build module "gmysql"... yes
checking whether we can build module "random"... yes
checking whether we can build dynamic module "pipe"... yes
checking systemd/sd-daemon.h usability... no
checking systemd/sd-daemon.h presence... no
checking for systemd/sd-daemon.h... no
checking whether to enable code coverage... no
checking whether to enable AddressSanitizer... no
checking whether to enable MemorySanitizer... no
checking whether to enable ThreadSanitizer... no
checking whether to enable LeakSanitizer... no
checking whether to enable Undefined Behaviour Sanitizer... no
checking whether to enable code malloc-trace... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating modules/Makefile
config.status: creating pdns/Makefile
config.status: creating codedocs/Makefile
config.status: creating docs/Makefile
config.status: creating pdns/pdns.init
config.status: creating ext/Makefile
config.status: creating ext/yahttp/Makefile
config.status: creating ext/yahttp/yahttp/Makefile
config.status: creating ext/json11/Makefile
config.status: creating modules/bindbackend/Makefile
config.status: creating modules/geoipbackend/Makefile
config.status: creating modules/gmysqlbackend/Makefile
config.status: creating modules/godbcbackend/Makefile
config.status: creating modules/goraclebackend/Makefile
config.status: creating modules/gpgsqlbackend/Makefile
config.status: creating modules/gsqlite3backend/Makefile
config.status: creating modules/ldapbackend/Makefile
config.status: creating modules/luabackend/Makefile
config.status: creating modules/mydnsbackend/Makefile
config.status: creating modules/opendbxbackend/Makefile
config.status: creating modules/oraclebackend/Makefile
config.status: creating modules/pipebackend/Makefile
config.status: creating modules/randombackend/Makefile
config.status: creating modules/remotebackend/Makefile
config.status: creating modules/tinydnsbackend/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
configure: Configuration summary
configure: =====================
configure:
configure: Configured with:  '--prefix=/root/Target/pdns-4.0.0'
configure:
configure: CC: gcc
configure: CXX: g++
configure: LD: /usr/bin/ld -m elf_x86_64
configure: CFLAGS: -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -g -O2
configure: CPPFLAGS:
configure: CXXFLAGS:  -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -Wall -g -O2 -std=gnu++11
configure: LDFLAGS: -Wl,-z -Wl,relro -Wl,-z -Wl,now
configure: LIBS:
configure: BOOST_CPPFLAGS:
configure:
configure: Features enabled
configure: ----------------
configure: Built-in modules: bind gmysql random
configure: Dynamic modules: pipe
configure:
configure: OpenSSL ecdsa: yes
configure: SQLite3: no
configure: Lua/LuaJit: no
configure: systemd: no
configure:
#

**Comment by paulehoffman** [comment]
Finding boost:

# dpkg -l | grep boost
ii  libboost-dev:amd64               1.58.0.1ubuntu1                 amd64        Boost C++ Libraries development files (default version)
ii  libboost1.58-dev:amd64           1.58.0+dfsg-5ubuntu3.1          amd64        Boost C++ Libraries development files

**Comment by Habbie** [comment]
Can you try installing `libboost-all-dev`?

**Comment by Habbie** [comment]
I have reproduced the issue with your two boost packages installed, and can confirm that adding `libboost-all-dev` resolves it.

**Comment by paulehoffman** [comment]
Yep, I have verified that as well. Thanks!

Unfortunately, I do not see a way to properly document this on the Boost site, and I suspect than any recipe for "what you need to build from source on X" will change over time. OTOH, if I'm the first one to stumble on this (I couldn't find anything with creative searching), this might not be worth documenting other than in this soon-to-be-closed issue.

**Comment by Habbie** [comment]
We do mention `libboost-all-dev` in README; also on Debian/Ubuntu `apt-get build-dep` can often do the right thing for you. And I see a notification just above this comment that @pieterlexis is making this fail earlier. Thanks for the report.
