### ISSUE TITLE
PowerDNS 4.0.0 Internal sever error when I read zone records from example.com zone

### ISSUE THREAD

**Issue by dorion** [PowerDNS/pdns#4257]
When I try to use the  following API call:
GET /api/v1/servers/localhost/zones/example.com
I give back HTTP 500 Internal Server error

I create this zone with pdnsutil and I can read the zone info by tha pdnsutil.

```
example.com     86400   IN      A       1.2.3.4
example.com     120     IN      MX      25 mail.example.com.
example.com     86400   IN      NS      dns-us1.powerdns.net.
example.com     86400   IN      NS      dns-eu1.powerdns.net.
example.com     86400   IN      SOA     localhost no-reply@example.com 2016072200
localhost.example.com   120     IN      A       127.0.0.1
mail.example.com        120     IN      A       127.0.0.2
www.example.com 120     IN      A       1.1.1.1
``` 

PowerDNS 4.0.0
Backend gMySQL
No DNSSEC
Debian 8.5

Thank you for your help

**Comment by zeha** [comment]
pdnsutil does not accept the zone you've posted. Can you show us the exact zone contents?

Thanks

**Comment by Habbie** [comment]
Closing until there is more data.

**Comment by dorion** [comment]
Missing some field from the SOA record. When I fix them I can read the zone informations. But I can write wrong SOA record with pdnsutils.
