### ISSUE TITLE
Bogus warnings after 'pdnsutil edit-zone' reverse zone

### ISSUE THREAD

**Issue by okket** [PowerDNS/pdns#4260]
I get bogus warnings after `pdnsutil edit-zone <zone>.ip6.arpa` in the form of

```
[Warning] Parsed and original record content are not equal: 
<omitted>.ip6.arpa IN PTR 'sub.domain.tld.' (Content parsed as 'sub.domain.tld')
```
I noted the '.' after the first `sub.domain.tld.` and missing in the parsed version, maybe that is why they are not equal?

**Comment by zeha** [comment]
`pdnsutil edit-zone` operates on data without trailing dots (as noted in the presented zone file in your editor). As such this is probably expected.
