### ISSUE TITLE
Wrong ip for AXFR

### ISSUE THREAD

**Issue by Kind-der-Nacht** [PowerDNS/pdns#4265]
PDNS does not use the "local-adress"-setting for outgoing AXFR requests any more, but uses the servers default ip. AXFR might fail due to missing/wrong rights on the master

**Comment by rgacogne** [comment]
Hi,

It looks like `query-local-address` and `query-local-address6` are used for, respectively, IPv4 and IPv6. Would you mind checking if setting that solves your issue?

**Comment by Kind-der-Nacht** [comment]
Yes that worked, thanks. 

Maybe the "query-local-adress" should default to "local-address" though to match the old behavior.. migrating to pdns4 could cause some problems otherwise..

**Comment by Habbie** [comment]
This behaviour was identical in 3..

**Comment by Kind-der-Nacht** [comment]
Hmm.. can't remember ever setting it before..

**Comment by Habbie** [comment]
Maybe your network setup changed in some way? If it's not set we just leave the choice to the kernel; note that in some setups this means the chosen IP can change after a simple reboot.
