### ISSUE TITLE
SOA-EDIT type unknown

### ISSUE THREAD

**Issue by Kind-der-Nacht** [PowerDNS/pdns#4266]
There is a problem with the SOA-EDIT (possibly due to the whitespace that is not present in the mysql-db).

SOA-EDIT type ' INCEPTION-INCREMENT' for zone *** is unknown.

It still works, but I think that might be due to the "default-soa-edit-signed"-setting.

**Comment by Habbie** [comment]
I'm sorry, I cannot make sense of your ticket. Can you show the relevant config or db content and the full content and location of the error?

**Comment by pieterlexis** [comment]
closing for lack of response.
