### ISSUE TITLE
Bad error report on invalid SOA

### ISSUE THREAD

**Issue by emilstahl** [PowerDNS/pdns#4281]
If your SOA record is invalid like:
`ns1.srv1.dk dns.srv1.dk 20160080400 14400 3600 604800 600`
instead of the correct:
`ns1.srv1.dk dns.srv1.dk 2016080400 14400 3600 604800 600`

PowerDNS refuses to start and you just get this error:
```
Exiting because communicator thread died with STL error: stop
pdns.service: Main process exited, code=exited, status=1/FAILURE
Failed to start PowerDNS Authoritative Server.
```

If you run check-all-zones..
```
root@ns1 ~# pdnsutil check-all-zones
Error: stou
```

Ubuntu 16.04.1 LTS
PowerDNS 4.0.1 from the repo

**Comment by lucasRolff** [comment]
According to RFC1035 (https://www.ietf.org/rfc/rfc1035.txt) - the serial should just be an unsigned 32 bit integer, so could even be a 1 increment if you wanted 👍 

So it's clearly a bug indeed.

**Comment by rgacogne** [comment]
Well, 20160080400 is larger than 2^32 so the error does make sense, but we really need to handle it better.

**Comment by lucasRolff** [comment]
@rgacogne oh ya - guess I my mind switched around the two numbers as the latter being not the date :-)

So it complies to the RFC :-D #sorry
