### ISSUE TITLE
topRule() - problematic if confused with other top functions

### ISSUE THREAD

**Issue by BWC-Michael** [PowerDNS/pdns#4296]
I did not paid attention and thought topRule() reports the most common used rules, like topSlow(), topQueries() etc. do for their tasks.

This is of course not the case, because it moves the last rule to the top.

Maybe it would be "user-friendly" if naming these functions more fool-proof, if possible.

--Michael

**Comment by rgacogne** [comment]
We just got another report of this mistake happening in production so I think we should rename `topRule` as soon as possible.

**Comment by githubkarel** [comment]
topRule() could show the rules hit most by dnsdist. 
But the current functionality should at least be moved to a different command  For which use case is this handy at all?

And consider also:
topCacheHitResponseRule
topResponseRule
topSelfAnsweredResponseRule

which also have a configuration change as a result instead of expected top... responses being more informational commands.

**Comment by phonedph1** [comment]
I will +1 to having something similar to `topRule` still. Either the ability to pass an attribute to rules (similar to uuid) to get something put as the first rule, or a way to tell `mvRule` and friends something like `mvRule(-1,0)` to get the same affect without needing to extract the last rule number each time.... or just `mvRuleToTop()` maybe :)

**Comment by radoeka** [comment]
Ain't it easier and clearer to rename the 'show' commands?  Something like:

- topBandwidth => showMaxBandwidth
- topClients => showMaxClients
- topQueries => showMaxQueries
- topResponses => showMaxResponses
- topSlow => showMaxSlow

The explanation for these command would become:
- showMaxBandwidth: show max-`top` clients that consume the most bandwidth over length of ringbuffer
- showMaxClients: show max-`n` clients sending the most queries over length of ringbuffer
- showMaxQueries: show max 'n' queries, as grouped when optionally cut down to 'labels' labels
- showMaxResponses: show max 'n' responses with RCODE=kind (0=NO Error, 2=ServFail, 3=ServFail), as grouped when optionally cut down to 'labels' labels
- showMaxSlow: show max  `top` queries slower than `limit` milliseconds, grouped by last `labels` labels

BTW: showMaxResponses, has twice ServFail.  Shouldn't there be a clearer explanation for error nr 2 and 3?

**Comment by phonedph1** [comment]
topX is used in recursor and I'm guessing auth though, so changing the problematic `topRule` seems like less of a hit.
