### ISSUE TITLE
Start of pdns_server fails with non-local-bind *and* query-local-address

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#4299]
We would like to start pdns_serever (4.0.1) with `non-local-bind=yes`.  But it fails if we also have `query-local-address=...` set.

`Exiting because communicator thread died with error: Resolver binding to local UDP socket on ...: Cannot assign requested address`

We define `query-local-address` and `query-local-address6` only for AXFRs. We have not set the `recursor` directive.

**Comment by paddg** [comment]
Can you estimate when https://github.com/PowerDNS/pdns/issues/4332 will be released?

**Comment by Habbie** [comment]
It is, of course, in our master packages already. Meanwhile we're trying to round up the last bits for auth 4.1 so we can do a first alpha, hopefully within a week or two!

**Comment by Habbie** [comment]
We could also backport the patch to 4.0. Please let us know :)

**Comment by paddg** [comment]
4.1 is great for us, thanks. It just make thinks easier in a ha environment.
