### ISSUE TITLE
PDNS Auth 4.0.x: API is more strict when it comes to SOA record defaults (TTL) 

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#4321]
While testing the latest NSEdit WebGUI (should be fully 4.x compatible) to manage PowerDNS Auth records I've noticed pdnsutil/pdns_server handles records less strict than the API does.

I can cut-off a SOA record like this:
cainites.net SOA 3600 ns1.cainites.net. hostmaster.cainites.net. 0

but the API expects all the TTL values to be there as well. It would be nice if the API would accept the short form and let pdns_server use the defaults when they're missing from the record.

**Comment by zeha** [comment]
Right now the API strives to only accept data that it would be able to hand out again, and this is a side-effect of that. Could possibly special-case SOA to pass it through `fillSOAData()` though.

**Comment by bakkerl** [comment]
Also during read of data (after a migrated from a earlier version) where no complete SOA records are stored, the API will return a HTTP 500 error.

Would be nice during read to have this data inserted into the records.
And would be nice if a 'pdnsutil check-zone' would throw an warning of non-API compliant data..

**Comment by Habbie** [comment]
> I can cut-off a SOA record like this:
> cainites.net SOA 3600 ns1.cainites.net. hostmaster.cainites.net. 0

Starting with 4.4.0(-alpha), this is no longer allowed anywhere, so I'm closing this.
