### ISSUE TITLE
Issue: Please make possible to truncate every UDP request to force TCP

### ISSUE THREAD

**Issue by Darkudorus** [PowerDNS/pdns#4327]
Configuration Option: "udp-truncation-threshold"
Currently there is a minimum of 512 bytes, please allow setting 0 bytes.
(Yes, this could break some resolvers, but not pdns-recursor.)

https://github.com/PowerDNS/pdns/blob/master/pdns/common_startup.cc#L488
https://github.com/PowerDNS/pdns/blob/master/pdns/pdns_recursor.cc#L649

**Comment by phonedph1** [comment]
Curious what the use case for this is?

**Comment by Darkudorus** [comment]
For internal use and worst case spoofing/amplification defense.

**Comment by ahupowerdns** [comment]
dnsdist can do this for you, and it is the place for spoofing/amplification attack mitigation. http://dnsdist.org/README/#any-or-whatever-to-tc
