### ISSUE TITLE
Strange behavior in forwarding case

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#433]
If forwarding all queries to another recursor:

```
forward-zones-recurse=.=111.222.333.444:53
```

we see permanent this message on recursors stdout:

```
Failed to update . records, RCODE=2
Failed to update . records, RCODE=2
...
```

**Comment by saspol** [comment]
Hello,
I have similar case. Using pdns-resolver to distribute requests to 3 forwarders.
```
forward-zones-recurse=.=127.0.0.1:39323;127.0.0.1:53180;127.0.0.1:17849
```
First few min it works and later have many SERVFAIL on clients, even with manual check all forwarders is ok. Then found this is logs:
```
Sep 15 00:38:26 omahum pdns_recursor[24019]: Failed to update . records, RCODE=2
Sep 15 00:38:26 omahum pdns_recursor[24019]: message repeated 2 times: [ Failed to update . records, RCODE=2]
Sep 15 00:39:13 hostname pdns_recursor[24019]: Failed to update . records, RCODE=2
Sep 15 00:40:07 hostname pdns_recursor[24019]: Failed to update . records, RCODE=2
Sep 15 00:40:50 hostname pdns_recursor[24019]: Failed to update . records, RCODE=2
Sep 15 00:41:31 hostname pdns_recursor[24019]: Failed to update . records, RCODE=2
Sep 15 00:42:18 hostname pdns_recursor[24019]: Failed to update . records, RCODE=2
```
This is your check from previous messages:
```
$ dig +recurse NS . @111.222.333.444
dig: couldn't get address for '111.222.333.444': failure
```
I used dnsmasq before for same job and it works ok on same configuration.
Any suggestion please?
```
PowerDNS Recursor 4.0.0-alpha2 (C) 2001-2016 PowerDNS.COM BV
```

**Comment by Habbie** [comment]
Hello @saspol, you are using an alpha version of our software. Please try a recent release. Furthermore, we tend to miss comments on closed tickets, so please find us on IRC, our mailing lists, or open a new ticket if your troubles remain with a new version.

**Comment by ahupowerdns** [comment]
please see if you can reproduce against an actual 4.0 release, possibly as found through https://repo.powerdns.com/ - we have a hard time debugging 4.0.0-alpha2. 

Thanks!
