### ISSUE TITLE
Where does the recursor match source ip and port?

### ISSUE THREAD

**Issue by ihavequestions** [PowerDNS/pdns#4336]
I'm sorry if this is the wrong place to ask. When receiving a DNS response, where does the recursor check for query.destinationIP == response.sourceIP and query.destinationPort == response.sourcePort? Can you help me locate these checks in the source code?
Any help is appreciated.

**Comment by ahupowerdns** [comment]
hello @ihavequestions, which you do. We leave this to the kernel because we use connected UDP sockets. As an additional benefit, this also gets us ICMP errors on recvmsg. So that's why you can't find it explicitly in PowerDNS. We let the kernel do it.
