### ISSUE TITLE
recursor: reload-lua-script memory leak

### ISSUE THREAD

**Issue by nfnty** [PowerDNS/pdns#4337]
Recursor 4.0.1 leaks memory when reloading lua scripts with large blacklists (~500k entries). Same issue for both DS and tables.

Script: https://gist.github.com/1dec1910a5ce4ad01fee29595e9e5ba8

Initial memory consumption and after reloading:

```
0.  355.2MiB
1.  651.8MiB
2.  715.2MiB
3.  765.7MiB
4.  729.2MiB
5.  778.8MiB
6.  765.3MiB
7.  807.3MiB
8.  838.6MiB
9.  772.5MiB
10. 794.3MiB
11. 794.5MiB
12. 794.5MiB
13. 794.5MiB
14. 811.2MiB
15. 827.0MiB
```

**Comment by ahupowerdns** [comment]
3dcc3fde593c689c8b413f52a9da77668e4e005b was supposed to have addressed this. Can you: 1) double check you are running 4.0.1 and not a development snapshot and 2) provide the files that go with this script to replicate the problem? Can be dummy data, as long as it reproduces the memory leak. Thanks!

**Comment by ahupowerdns** [comment]
On a related note, how do you measure memory usage? It does appear to be going up _and_ down over time. One of the best ways is the built-in metric "real-memory-usage".

**Comment by nfnty** [comment]
Yep, 4.0.1 verified by Pieter Lexis PGP key and built with [PKGBUILD](https://github.com/nfnty/pkgbuilds/blob/master/powerdns-recursor/PKGBUILD). Indeed the behavior is rather strange.

The files are generated by [nfnty/domainblacklist](https://github.com/nfnty/domainblacklist) (invoke with `python3 sync.py $PATH_DESTDIR`)

`real-memory-usage` has the same value as the memory usage reported by `docker stats`.

**Comment by omoerbeek** [comment]
Closed due to inactivity. If this is still an issue, re-open.
