### ISSUE TITLE
Improve datasearching via the API

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#4358]
https://github.com/tuxis-ie/nsedit/pull/106 implemented a way to search inside a zone in nsedit. However, it would be more efficient to improve the search-data-call to search for $data in $zone, specifically.

**Comment by zeha** [comment]
Honestly, I'm not sure what this is asking for. Guess: restrict to search only in a single zone? If so, that could be a lot more efficient, but maybe this does something else?

In any case it needs docs :-)

**Comment by tuxis-ie** [comment]
Yes. The idea is to search in one zone only.

**Comment by Habbie** [comment]
If anybody is still interested in this, please PR it! I'll close this meanwhile.
