### ISSUE TITLE
Cannot set pipe-abi-version

### ISSUE THREAD

**Issue by cabeggar** [PowerDNS/pdns#4366]
When I try to run `sudo service pdns monitor`, the following logs show:

```
Aug 25 16:32:09 Reading random entropy from '/dev/urandom'
Aug 25 16:32:09 [PIPEBackend] This is the pipebackend version 3.3 (Jan 27 2014, 16:33:07) reporting
Aug 25 16:32:09 This is a standalone pdns
Aug 25 16:32:09 Fatal error: Trying to set unexisting parameter 'pipe-abi-version'
```

My config looks like this:

```
launch=pipe
pipe-abi-version=2
pipe-command=/etc/powerdns/pipe-backend.py
```

I've removed other irrelevant configuration in pdns.d/ . If I don't set abi version, everything works fine. Any idea on this one? Thanks!

**Comment by Habbie** [comment]
What version is this? In older versions the setting was called `pipebackend-abi-version`.

**Comment by cabeggar** [comment]
Thanks! It's solved now.
