### ISSUE TITLE
Fix to force amd64 on multi arch enabled systems

### ISSUE THREAD

**Issue by sauttefk** [PowerDNS/pdns#4367]
on multi arch enabled 64-bit systems 
`/etc/apt/sources.list.d/pdns.list`
should be 
`deb [arch=amd64] http://repo.powerdns.com/ubuntu xenial-auth-40 main`
to avoid errors like
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.powerdns.com/ubuntu xenial-auth-40 InRelease' doesn't support architecture 'i386'`

This applies to all the other `sources.list` entries as well.

**Comment by pieterlexis** [comment]
Thank you for your report, the repo.powerdns.com website is updated to reflect this.
