### ISSUE TITLE
Recursor: with dnssec inconsistently answers with NXDOMAIN sometimes (instead of SERVFAIL or answer)

### ISSUE THREAD

**Issue by gertvdijk** [PowerDNS/pdns#4369]
Recursor version 4.0.2.
Relevant entries in my `recursor.conf`:

```
local-address=0.0.0.0
forward-zones=test.gert.lan=192.168.123.45:5300
dnssec=validate
```

Documentation says:

> `validate`
>
> Full blown DNSSEC validation. Send SERVFAIL to clients on bogus responses.

Here's what I see on a resolver after a recursor restart _sometimes_:

```
$ host host1.test.gert.lan; sleep 1; host host2.test.gert.lan
Host host1.test.gert.lan not found: 2(SERVFAIL)
Host host2.test.gert.lan not found: 3(NXDOMAIN)
```

PCAP analysis shows this:

```
1  workstation    -> recursor402    DNS 78 Standard query 0x0192 A host1.test.gert.lan
2  recursor402    -> 192.168.123.45 DNS 89 Standard query 0xc832 A host1.test.gert.lan OPT
3  192.168.123.45 -> recursor402    DNS 105 Standard query response 0xc832 A host1.test.gert.lan A 192.168.45.67 OPT
4  recursor402    -> 192.228.79.201 DNS 70 Standard query 0x5238 DNSKEY <Root> OPT
5  192.228.79.201 -> recursor402    DNS 778 Standard query response 0x5238 DNSKEY <Root> DNSKEY DNSKEY RRSIG OPT
6  recursor402    -> 199.7.83.42    DNS 74 Standard query 0x6f5c DS lan OPT
7  199.7.83.42    -> recursor402    DNS 685 Standard query response 0x6f5c No such name DS lan NSEC lancaster RRSIG NSEC aaa RRSIG SOA a.root-servers.net RRSIG OPT
8  recursor402    -> workstation    DNS 78 Standard query response 0x0192 Server failure A host1.test.gert.lan
9  workstation    -> recursor402    DNS 80 Standard query 0xc27f A host2.test.gert.lan
10 recursor402    -> workstation    DNS 155 Standard query response 0xc27f No such name A host2.test.gert.lan SOA a.root-servers.net
```

Corresponding Recursor logs with `quiet=no` and `loglevel=999`:

```
2 [4/1] question for 'host1.test.gert.lan|A' from <ip-workstation>
2 [4/1] answer to question 'host1.test.gert.lan|A': 0 answers, 0 additional, took 1 packets, 1.491 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
2 [5/1] question for 'host2.test.gert.lan|A' from <ip-workstation>
2 [5/1] answer to question 'host2.test.gert.lan|A': 0 answers, 0 additional, took 0 packets, 0 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=3
```

Some observations from this and more PCAP analysis (too long to post all here):

* Note that `192.168.123.45` is not consulted for `host2.test.gert.lan`. Querying with more hosts (host3, host4, host5, etc.) it appears that it confirms to a pattern: any time when it decides not to query the upstream authoritative server, the Recursor responds with an NXDOMAIN.
* The NXDOMAIN/SERVFAIL answers are cached, all subsequent answers are identical. Recursor logs `question answered from packet cache tag=0 from <ip-workstation>`.
* The above behaviour does not always happen. With about 10 fresh restarts of the Recursor I see about a two situations like above, eight situations like these which are correct I believe:

        $ host host1.test.gert.lan; sleep 1; host host2.test.gert.lan
        Host host1.test.gert.lan not found: 2(SERVFAIL)
        Host host2.test.gert.lan not found: 2(SERVFAIL)

It gets even worse with `recursor.conf` set to process and log failures:

```
local-address=0.0.0.0
forward-zones=test.gert.lan=192.168.123.45:5300
dnssec=log-fail
```

```
$ host -t A host1.test.gert.lan; sleep 1; host -t A host2.test.gert.lan; host -t A host1.test.gert.lan
host1.test.gert.lan has address 192.168.40.1
Host host2.test.gert.lan not found: 3(NXDOMAIN)
host1.test.gert.lan has address 192.168.40.1
```

```
Answer to host1.test.gert.lan|A for workstation:9887 validates as Bogus
```

**Which makes `host2.test.gert.lan` totally negative if requested after a positive result first. Unusable in my situation.**

All of the above not reproducible with `dnssec` not set (`process-no-validate`).

I hope this helps to solve this bug. Let me know what I can do more to aid resolving this.

Also... Would it be possible to have `dnssec=validate` while also using `forward-zones` to fictive domains like in my situation? Maybe some exclusion list? I'd like to validate public DNS while keeping my own non-public TLD (or maybe I should just not want both things).

**Comment by pieterlexis** [comment]
Interesting, I thought we disabled DNSSEC for forward-zones. But it was only for auth-zones (commit 9fc36e9058984600762fa4e708a0688587fa3aba).

As .lan is indeed not delegated, the Bogus response is 'correct' (but confusing). You can use [`addNTA("lan")` or `addNTA("gert.lan")`](https://doc.powerdns.com/md/recursor/dnssec/#negative-trust-anchors) to your [`lua-config-file`](https://doc.powerdns.com/md/recursor/settings/#lua-config-file). Or at runtime using `rec_control add-nta gert.lan`.

That said, we need to find out why the answers are inconsistent.
