### ISSUE TITLE
pdns_recursor manpage inaccurate

### ISSUE THREAD

**Issue by benv666** [PowerDNS/pdns#4372]
After upgrading from pdns_recursor 4.0alpha1 to 4.0.2 it complained about not finding recursor.conf, and tried to open it from /etc/recursor.conf
The man page states the default for --config-dir is /etc/powerdns, which is not the case (start with --config-dir /etc/powerdns made it look in the right place).

**Comment by pieterlexis** [comment]
hi, what OS and where did you get your packages from?

**Comment by benv666** [comment]
Slackware64-current, built from source tarball at https://downloads.powerdns.com/releases/pdns-recursor-4.0.2.tar.bz2 using ./configure with a CONFIG_SITE that sets a bunch of stuff including sysconfdir=/etc

**Comment by pieterlexis** [comment]
hrm, right. Nearly all other distributions set `sysconfdir` to `/etc/powerdns` (and we do as well for our packages). We'll amendthe manpage to say something like ".. the SYSCONFDIR setting at build-time, which usually is /etc/powerdns"
