### ISSUE TITLE
Keep old versions of pdns packages in repo.powerdns.com

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4395]
It's great having the version 4 builds of pdns(-recursor) an repo.powerdns.com - thanks for that!

However is it possible to keep all of the older versions up there rather than deleting them? We are using automated deployment when building new boxes and would like to have fully tested a powerdns version and then pinned it during deployment, rather than having powerdns automatically upgrading whenever there is a new version prior to us having fully tested it with our system?

Thanks!

**Comment by Habbie** [comment]
Does this help? https://downloads.powerdns.com/autobuilt/recursor/deb/

**Comment by pieterlexis** [comment]
to add to that, for RPM repos we keep them, for debian repos this is not possible because of the way debian repos work

**Comment by mzealey** [comment]
@Habbie this looks nice, however are they available via apt the same as the main repo?

**Comment by mzealey** [comment]
Doesn't seem to be impossible; just depends on what repo manager you use eg mini-dinstall supports multiple versions

**Comment by pieterlexis** [comment]
It looks like it is possible to keep these old file around in the repo without them showing up in the `Packages` file when the [`reprepro`](http://mirrorer.alioth.debian.org/reprepro.1.html) switch `−−keepunreferencedfiles` is used. I'll put this on the to do list for the future.

**Comment by pieterlexis** [comment]
By the way, I would recommend using a repository you maintain yourself (with our packages) to fix the engineering issue you have here. If you're using our ansible playbooks, keep `pdns_repo_provider` or `pdns_recursor_repo_provider` on 'os' and add your own repository via your own (small) role.

**Comment by Habbie** [comment]
@pieterlexis ping?

**Comment by pieterlexis** [comment]
We decided this is too much of a hassle.
