### ISSUE TITLE
./configure fails on detecting libboost_program_options

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#441]
According to

http://doc.powerdns.com/compiling-powerdns.html

" If your operating system does not have a Boost package, you don't need to compile all of boost just for PowerDNS. PowerDNS only uses Boost include files, so there is no need to install all of boost. Just untar the Boost distribution file and point instruct ./configure to find it, perhaps like this:

	$ CXXFLAGS=-I/home/bert/download/boost_1_33_0 ./configure ..."

but the ./configure step fails thus:

setenv CXXCPP /usr/sfw/bin/cpp ; ./configure --prefix=/opt/powerdns --with-boost="${HOME}/devel/src/boost_1_38_0" CC=gcc CXX=g++

checking for Boost headers version >= 103400... /export/home/user/devel/src/boost_1_38_0
checking for Boost's header version... 1_38
checking boost/foreach.hpp usability... yes
checking boost/foreach.hpp presence... yes
checking for boost/foreach.hpp... yes
checking for the toolset name used by Boost for g++... gcc34 -gcc
checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... no
configure: error: cannot not find the flags to link with Boost program_options

So the documentation states libraries are not needed, yet the ./configure looks for libboost_program_options-*gcc*.so.

There is a bit of code in ./configure with a series of checks which appears to be the root cause.

OS is SunOS 5.10 u3 (Solaris 10 11/06). The error occurs on both i86pc and sparc platforms.

What do I need to do to fix this?

**Comment by UX-admin** [comment]
pdns 3.4.5 fails to detect Boost properly:

checking for Boost headers version >= 1.35.0... yes
checking for Boost's header version... 
configure: error: invalid value: boost_major_version=''

Boost version is still 1.38.0 (/opt/abcd/include/boost-1_38).  ./configure is called with the following Boost switches:

--with-boost=/opt/abcd/include/boost-1_38 --enable-static-boost

CPPFLAGS="-I/opt/abcd/include/boost-1_38 -I/opt/abcd/include"; export CPPFLAGS

however, the above worked in 3.4.1, with those same settings above:
checking for Boost headers version >= 1.35.0... /opt/abcd/include/boost-1_38
checking for Boost's header version... 1_38
checking boost/foreach.hpp usability... yes
checking boost/foreach.hpp presence... yes
checking for boost/foreach.hpp... yes
checking for the toolset name used by Boost for g++... gcc47 -gcc
checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... yes
checking boost/archive/text_oarchive.hpp usability... yes
checking boost/archive/text_oarchive.hpp presence... yes
checking for boost/archive/text_oarchive.hpp... yes
checking for the Boost serialization library... (cached) yes

**Comment by UX-admin** [comment]
The newer version of m4/boost.m4 introduced this issue:

--- m4/boost.m4.orig    Tue Jun  9 14:28:56 2015
+++ m4/boost.m4 Sun Jul 19 12:00:20 2015
@@ -90,7 +90,6 @@
 (eval "$ac_cpp conftest.$ac_ext") 2>&AS_MESSAGE_LOG_FD |
   grep -v '#' |
   tr -d '\r' |
-  tr -s '\n' ' ' |
   $SED -n -e "$1" >conftest.i 2>&1],
   [$3],
   [$4])

...with the same fix to ./configure, Boost is now detected as before.

**Comment by UX-admin** [comment]
(Github will not let me attach a patch for m4/boost.m4: "Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG.")

**Comment by Habbie** [comment]
You can point to a gist (https://gist.github.com/) or paste the patch inline surrounded by three backticks.

**Comment by UX-admin** [comment]
https://gist.github.com/UX-admin/ba5c5d9076de176a2d9d

**Comment by pieterlexis** [comment]
@UX-admin this fix does not break boost detection on Linux (for me).

We won't incorporate this patch into master (as we're not sure it'll build with boost < 1.54 *and* requires c++ 2011 support), but will merge it for the next 3.4 release.

**Comment by Habbie** [comment]
boost.m4 has been updated a few times since, and we have plenty of success reports from various solaris forks. Please reopen if this is still an issue - and if you want to patch things, please submit as a pull request!
