### ISSUE TITLE
Possible cache hit problem

### ISSUE THREAD

**Issue by Widmo** [PowerDNS/pdns#4434]
Debian 8, standard config.
PowerDNS Recursor, stock config.

Only first hit is done right, second is returned empty. (Dash in domain?)

Reproduce: 
`service pdns-recursor restart`
`dig +short e-novi.pl MX @127.0.0.1`
(return MXes correct)
`watch "dig +short e-novi.pl TXT @127.0.0.1;  echo "---"; dig +short e-novi.pl MX @127.0.0.1;"`
(return MX ONLY)
`service pdns-recursor restart`
(watch return TXT ONLY)

Conclusion: return only first hit.

**Comment by pieterlexis** [comment]
please provide us with the log output with `trace=yes` in the config.

Also, please test the backports version. Stable has 3.6.2 and backports has 3.7.3

**Comment by Habbie** [comment]
Your domain is misconfigured - on the child side it claims to be hosted at ns1-3.az.pl.e-novi.pl and those do not respond to queries at all.

**Comment by Widmo** [comment]
Hi, thanks for reply:
Logs: http://pastebin.com/gWJn1UW8
Last backport used: Sep 07 13:25:44 PowerDNS Recursor 3.7.3

It's not my domain :) 

Any other system without pdns recursor shows correct answer: 
`dig +short e-novi.pl TXT;  echo "---"; dig +short e-novi.pl MX;`

```
"v=spf1 a mx include:_spf.zenbox.pl -all"
---
20 mx1.zenbox.pl.
30 mx2.zenbox.pl.
10 mx3.zenbox.pl.

```

**Comment by Habbie** [comment]
The log indeed shows that those unreachable name servers are the reason. Sorry, this is not a PowerDNS issue. Closing ticket.
