### ISSUE TITLE
Multiple issues with GeoIPBackend 

### ISSUE THREAD

**Issue by mason-chase** [PowerDNS/pdns#4439]
Hi Everyone,

GeoIP back-end has a single YML file as a source which is not reliable for constant reload/rewrite of hundreds of thousands of domains that may belong to large number of users who wish to edit their DNS records constantly.

on each change the entire YML file must be regenerated and reloaded to PowerDNS which can create a lot of overhead.

Not to mentioned the YML file must be in correct format and DNS records must be in compliance otherwise the PowerDNS will crash with "bad file" error upon reload.

Furthermore, the current PowerDNS back-end handling doesn't pass the error YAML parsing error upon loading a bad file.

I have made a minor change to pass through the error message and as well as all loading multiple YML files from entire folder in which all domains or group of domains can be written in multiple files.

Ultimately I will complete the single file or single domain reload and best is to keep all unified format. my suggestion is a single domain per YML file.

Please kindly approve the PUSH request made for this update.

I will submit a clean log without "merge" given the geoipbackend was modified after I made my changes.

Regards

**Comment by cmouse** [comment]
Wonder where the push request went?

**Comment by cmouse** [comment]
#4386

**Comment by mohamadsajedi** [comment]
same issue... is there any update for this?
we need to have seprated yaml files and include them in maater yaml file... something like bind backend

**Comment by cmouse** [comment]
@mohamadsajedi or @mason-chase can you please test the companion merge request?

**Comment by mohamadsajedi** [comment]
thank you my friend @cmouse 
it seems that your merge request does passed all the tests
can you please check that?

**Comment by cmouse** [comment]
check what exactly?

**Comment by esacs2004** [comment]
what's the status on this?
