### ISSUE TITLE
Documentation could be more specific about OpenDBX

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#445]
The current official PowerDNS documentation links to OpenDBX wiki pages, which state:

"The OpenDBX backend is included in the PowerDNS source tree. Additionally, you can get the latest patches for the PowerDNS OpenDBX backend from the download page. You will also need the OpenDBX library to be able to use the OpenDBX backend."

which is unclear as to whether the OpenDBX library sources are included with PowerDNS or not. On operating systems which do not come with OpenDBX libraries by default, the determination of the fact that PowerDNS requires the OpenDBX libraries to be built as a prerequisite is one of trial and error.

Section 11., "OpenDBX backend" could for example state that PowerDNS requires OpenDBX libraries to be built and installed before attempting to build PowerDNS, as PowerDNS built-in code needs to link with the OpenDBX libraries if that backend is selected.

**Comment by Habbie** [comment]
Because @pieterlexis asked on IRC: the status of the OpenDBX backend is "we test it on every commit and thus it works and is supported by us"

**Comment by Habbie** [comment]
libopendbx appears to be unmaintained; we should clarify whether we support libopendbx

**Comment by Habbie** [comment]
@nsendetzky can you say something useful about the state of support libopendbx is in?

**Comment by nsendetzky** [comment]
@Habbie The library is still maintained but only bugfixes have been applied in the past. I'm moving the source now to GitHub so others can contribute easier

**Comment by Habbie** [comment]
Thank you, this will be helpful! I filed a ticket yesterday (see https://github.com/Homebrew/homebrew/pull/40793) but when it's on Github I have people I can ask for help ;)

**Comment by nsendetzky** [comment]
@Habbie The GitHub repository is now https://github.com/nsendetzky/libopendbx
