### ISSUE TITLE
If domains last_check in SQL is not number a vague error is given

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#4450]
If last_check value for a domain contains non-numeric value other than NULL, an error is given.

Example value

``` .sql
INSERT INTO "domains" VALUES(1,'vpn.gwad.fi','NULL','NULL','NATIVE',NULL,NULL);
```

Will produce errors when doing DNSUPDATE, such as

```
Sep 10 11:22:23 gw-fw01 pdns_server: Sep 10 11:22:23 Exception building answer packet for vpn.gwad.fi/SOA (stoul) sending out servfail
```

or

```
pdnsutil rectify-all-zones
Error: stoul
```

**Comment by Habbie** [comment]
A user is reporting `stoul` errors with bindbackend as well, which makes sense - there is no reason for this issue to be limited to gSQL.

**Comment by Habbie** [comment]
> A user is reporting stoul errors with bindbackend as well, which makes sense - there is no reason for this issue to be limited to gSQL.

I should have written more words here - I no longer recall why I said this makes sense for bindbackend to have similar issues.

**Comment by Habbie** [comment]
Current master: `Error: stoul; (invalid argument during std::stoul); data was "NULL"`
