### ISSUE TITLE
could not install on 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by maniaque** [PowerDNS/pdns#4460]
Recently I tried to test new 4.0.x release of PowerDNS Auth from repo.powerdns.com, everything was done as documented at https://repo.powerdns.com

```
ubuntu@limbo:~$ sudo apt install pdns-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pdns-server : Depends: libboost-program-options1.54.0 but it is not installable
               Depends: libbotan-1.10-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

`apt show pdns-server` says this:
`Depends: libboost-program-options1.54.0, libbotan-1.10-0`

But in Xenial Xerus we have this:
- libboost-program-options1.58.0
- libbotan-1.10-1

**Comment by Habbie** [comment]
Can you show your sources.list please?

**Comment by maniaque** [comment]
deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse

**Comment by Habbie** [comment]
Can you try `apt-get update` ?

**Comment by maniaque** [comment]
Done, same result.

**Comment by Habbie** [comment]
I don't see our repo in your sources at all?

**Comment by maniaque** [comment]
It's here, as documented `/etc/apt/sources.list.d/pdns.list`

`deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-auth-40 main`

**Comment by Habbie** [comment]
That says trusty, not xenial.

**Comment by maniaque** [comment]
Oh, damn, looks like my typo. How did I ever got this. Will fix in a minute.

**Comment by maniaque** [comment]
Success, this could be closed. Thanks!
