### ISSUE TITLE
gpgsql-dnssec=no no effect on PowerDNS 4.0.1-1

### ISSUE THREAD

**Issue by raphaeldias** [PowerDNS/pdns#4464]
Hi,

I use gpgsql-dnssec=no but domainmetadata is being consulted leading a internal error:

curl -H 'X-API-Key: XXX' http://10.30.127.3/api/v1/servers/localhost/zones/example.org.

Internal Server Error

Logs

Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=$1 and domainmetadata.kind=$2
Error: GSQLBackend unable to list metadata: Fatal error during query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=$1 and domainmetadata.kind=$2: ERROR:  permission denied for relation domainmetadata

Packages:

ii  pdns-backend-pgsql                   4.0.1-1pdns.jessie             amd64        generic PostgreSQL backend for PowerDNS
ii  pdns-server                          4.0.1-1pdns.jessie             amd64        extremely powerful and versatile nameserver

Related config:

https://doc.powerdns.com/md/authoritative/backend-generic-postgresql/#gpgsql-dnssec

Thanks

**Comment by Habbie** [comment]
This is not a bug - PowerDNS 4 supports various kinds of domain metadata for non-DNSSEC deployments as well.
