### ISSUE TITLE
PTR doesn't get deleted/updated via API

### ISSUE THREAD

**Issue by zralt** [PowerDNS/pdns#4468]
Hy,

Example:
Create an A record with "set-ptr": true via the API. 
If I delete this record via the API, the PTR record doesn't get removed. 
Also, if I re-add that A record with a different IP, a separate PTR record gets created, and not the already existing updated (but I assume this is just a side-result that the PTR is handled independently). 

An option would be nice to delete the PTR also if the main record is removed.

**Comment by Habbie** [comment]
Duplicated in #4656 with more context, so closing this. Thank you for your report!
