### ISSUE TITLE
expunge causes crash

### ISSUE THREAD

**Issue by tdavidscott3** [PowerDNS/pdns#4470]
The following commands will cause dnsdist to fatality die... In short, when you attempt to expunge() cache that no longer exists, it dies.

> normalCache = newPacketCache(100000, 86400, 0, 60, 60)
> getPool(""):setCache(normalCache)
> getPool(""):setCache(normalCache)
> getPool(""):getCache():expunge(0)
> getPool(""):unsetCache()
> getPool(""):getCache():expunge(0)
> dnsdist: ext/luawrapper/include/LuaContext.hpp:1059: LuaContext::registerFunctionImpl(const string&, TFunctionType, LuaContext::tag<TObject>, LuaContext::tag<TRetValue(TOtherParams ...)>) [with TFunctionType = std::_Mem_fn<void (DNSDistPacketCache::*)(long unsigned int)>; TRetValue = void; TObject = DNSDistPacketCache; TOtherParams = {long unsigned int}; std::string = std::basic_string<char>]::__lambda4: Assertion `obj' failed.
> Aborted
> dnsuser@localhost [~] #

**Comment by rgacogne** [comment]
`getPool(""):getCache():expunge(0)` is enough if there is no cache on the default pool, no need to set it then remove it. `getCache()` returns a `null` `shared_ptr` and then the `expunge()` method is called on a `null` `shared_ptr` object. I guess we could check for that case explicitly, I'm not sure whether it's worth the trouble. Note that the `toString()`, `isFull()`, `purgeExpired()` methods have the same behavior.
