### ISSUE TITLE
newServer() IPv6 parse failure?

### ISSUE THREAD

**Issue by tdavidscott3** [PowerDNS/pdns#4471]
Per irc converation...

    ok, your error is caused by newServer({address="[2a01:7a0:10:149:154:159:12:0]", name="c.root"}) and newServer({address="[2a03:4000:2:24f::1]", name="d.root"})
    <rgacogne> just remove the '[' and ']' or add a ':53' after the ']'

Some more testing, shows the following IF set in the dnsdist.conf file

```lua
newServer({address="IPv6"}))   -- without [] and without port will cause dnsdist to halt on startup
newServer({address="[IPv6]"}) -- with [] and without port will cause dnsdist to halt on startup
newServer({address="[IPv6]:P"})  -- with [] and with port works A-OK
```

**Comment by rgacogne** [comment]
The first case "without [] and without port" seems to work fine on master, what version are you using?
With the fix in #4474, dnsdist outputs a useful error message for the rejected addresses, and doesn't exit.
