### ISSUE TITLE
 expected digits at position 0 in 'mta1.abc.com'"

### ISSUE THREAD

**Issue by pshanmu** [PowerDNS/pdns#4479]
I am unable to add the MX record using API. Can some one please help me. - Urgent help reqd.

#curl -X PATCH --data '{"rrsets": [ {"name":"domain1.abc.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"domain1.abc.com", "type":"MX", "content":"mta1.abc.com", "disabled":false, "priority": 10 } ] } ] }' -H 'X-API-Key: 12345' http://10.10.10.1:8081/api/v1/servers/localhost/zones/abc.com | jq .

{
  "error": "Record domain1.abc.com./MX 'mta1.abc.com': Parsing record content (try 'pdnsutil check-zone'): expected digits at position 0 in 'mta1.abc.com'"
}

xx@ns2:~ % pdnsutil check-zone sparrowdesk.com
Checked 7 records of 'sparrowdesk.com', 0 errors, 0 warnings.
xx@ns2:~ %

**Comment by Habbie** [comment]
What version of pdns please?

**Comment by Habbie** [comment]
Also, I noticed you editing the output. Do not ever do that, we cannot support you if you do.

**Comment by pshanmu** [comment]
Sorry, I did this to protect some information.

root@ns2:~ # curl -X PATCH --data '{"rrsets": [ {"name":"cherry.sparrowdesk.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"cherry.sparrowdesk.com", "type":"MX", "content":"mta1.sparrowdesk.com", "disabled":false, "priority": 10 } ] } ] }' -H 'X-API-Key: CherrySGP1' http://10.10.10.1:8081/api/v1/servers/localhost/zones/sparrowdesk.com | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   410  100   178  100   232   3047   3972 --:--:-- --:--:-- --:--:--  4218
{
  "error": "Record cherry.sparrowdesk.com./MX 'mta1.sparrowdesk.com': Parsing record content (try 'pdnsutil check-zone'): expected digits at position 0 in 'mta1.sparrowdesk.com'"
}
root@ns2:~ # 

root@ns2:~ # pdns_control version
4.0.1
root@ns2:~ #

**Comment by Habbie** [comment]
Since pdns 3.4.2, the API does not have a priority field. Please put your priority in the content field, before the name. This is clearly mentioned in https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzoneszone95id

**Comment by pshanmu** [comment]
Sorry, I tried like this. but i still get the problem

root@ns2:~ # curl -X PATCH --data '{"rrsets": [ {"name":"sparrowdesk.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"cherry.sparrowdesk.com", "type":"MX", "content":"10mta1.sparrowdesk.com", "disabled":false } ] } ] }' -H 'X-API-Key: CherrySGP1' http://10.10.10.1:8081/api/v1/servers/localhost/zones/sparrowdesk.com | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   338  100   127  100   211   2674   4443 --:--:-- --:--:-- --:--:--  5410
{
  "error": "Record sparrowdesk.com./MX '10mta1.sparrowdesk.com': Not in expected format (parsed as '10 mta1.sparrowdesk.com.')"
}



root@ns2:~ # curl -X PATCH --data '{"rrsets": [ {"name":"sparrowdesk.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"cherry.sparrowdesk.com", "type":"MX", "content":"10 mta1.sparrowdesk.com", "disabled":false } ] } ] }' -H 'X-API-Key: CherrySGP1' http://10.10.10.1:8081/api/v1/servers/localhost/zones/sparrowdesk.com | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   340  100   128  100   212   4911   8134 --:--:-- --:--:-- --:--:--  9217
{
  "error": "Record sparrowdesk.com./MX '10 mta1.sparrowdesk.com': Not in expected format (parsed as '10 mta1.sparrowdesk.com.')"
}
root@ns2:~ #

**Comment by Habbie** [comment]
This is a support question; please use the mailing lists or our IRC channel.
