### ISSUE TITLE
"While checking domain freshness: Attempt to print an unset dnsname" in logfile

### ISSUE THREAD

**Issue by rvdh** [PowerDNS/pdns#4481]
I was told by @Habbie this shouldn't happen. 

**PowerDNS version**
`PowerDNS Authoritative Server 4.0.1 (C) 2001-2016 PowerDNS.COM BV`
**Where you got the software from (e.g. distribution, compiled yourself)**
`http://repo.powerdns.com/debian`, deb packages.
**Operating System and version**
Debian 8.5.
**Steps to reproduce: How can we reproduce the issue**
I'm afraid I don't know.
**Relevant logs**: 

```
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 4 slave domains need checking, 0 queued for AXFR
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 While checking domain freshness: Attempt to print an unset dnsname
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 While checking domain freshness: Attempt to print an unset dnsname
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 While checking domain freshness: Attempt to print an unset dnsname
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 While checking domain freshness: Attempt to print an unset dnsname
Sep 16 12:16:38 vm006 pdns_server[21598]: Sep 16 12:16:38 Done launching threads, ready to distribute questions
Sep 16 12:16:41 vm006 pdns_server[21598]: Sep 16 12:16:41 Received serial number updates for 0 zones, had 4 timeouts
```

**Comment by pgnd** [comment]
Just noting the "this shouldn't happen." comment, I'm seeing similar "While checking domain freshness: Attempt to print an unset dnsname" messages on a src-build of

    dig chaos txt version.bind @10.1.1.53 -p 15301 +short
        "PowerDNS Authoritative Server 4.0.1-264-g50e4ab3 (built Dec 30 2016 20:47:29 by adm@dns.example.net)"

amidst other issues, after a NOTIFY by bind9 supermaster to pdns4 superslave,

        ...
        Dec 31 16:34:33 dns pdns[25637]: Remote 10.1.1.53 wants 'example1.com|SOA', do = 0, bufsize = 512: packetcache MISS
        Dec 31 16:34:33 dns pdns[25637]: Query: select algorithm, secret from tsigkeys where name=:key_name
        Dec 31 16:34:33 dns pdns[25637]: Received secure NOTIFY for example1.com from 10.1.1.53, allowed by TSIG key 'pdns-key
        Dec 31 16:34:33 dns pdns[25637]: Query: select id,name,master,last_check,notified_serial,type,account from domains where name=:domain
        Dec 31 16:34:33 dns pdns[25637]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=:qtype and name=:qname
        Dec 31 16:34:33 dns pdns[25637]: No serial for 'example1.com' found - zone is missing?
        Dec 31 16:34:33 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:33 dns pdns[25637]: Query: select master from domains where name=:domain and type='SLAVE'
        Dec 31 16:34:33 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:33 dns pdns[25637]: Query: select algorithm, secret from tsigkeys where name=:key_name
        Dec 31 16:34:33 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:33 dns pdns[25637]: 1 slave domain needs checking, 0 queued for AXFR
    >>> Dec 31 16:34:33 dns pdns[25637]: While checking domain freshness: Attempt to print an unset dnsname
        Dec 31 16:34:34 dns pdns[25637]: Remote 10.1.1.53 wants 'example2.com|SOA', do = 0, bufsize = 512: packetcache MISS
        Dec 31 16:34:34 dns pdns[25637]: Query: select algorithm, secret from tsigkeys where name=:key_name
        Dec 31 16:34:34 dns pdns[25637]: Received secure NOTIFY for example2.com from 10.1.1.53, allowed by TSIG key 'pdns-key
        Dec 31 16:34:34 dns pdns[25637]: Query: select id,name,master,last_check,notified_serial,type,account from domains where name=:domain
        Dec 31 16:34:34 dns pdns[25637]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=:qtype and name=:qname
        Dec 31 16:34:34 dns pdns[25637]: No serial for 'example2.com' found - zone is missing?
        Dec 31 16:34:34 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:34 dns pdns[25637]: Query: select master from domains where name=:domain and type='SLAVE'
        Dec 31 16:34:37 dns pdns[25637]: Received serial number updates for 0 zones, had 1 timeout
        Dec 31 16:34:37 dns pdns[25637]: Query: select id,name,master,last_check,notified_serial,type,account from domains where name=:domain
        Dec 31 16:34:37 dns pdns[25637]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=:qtype and name=:qname
        Dec 31 16:34:37 dns pdns[25637]: No serial for 'example1.com' found - zone is missing?
        Dec 31 16:34:37 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:37 dns pdns[25637]: Query: select algorithm, secret from tsigkeys where name=:key_name
        Dec 31 16:34:37 dns pdns[25637]: Query: select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=:domain and domainmetadata.kind=:kind
        Dec 31 16:34:37 dns pdns[25637]: 1 slave domain needs checking, 0 queued for AXFR
    >>> Dec 31 16:34:37 dns pdns[25637]: While checking domain freshness: Attempt to print an unset dnsname
        Dec 31 16:34:40 dns pdns[25637]: Received serial number updates for 0 zones, had 1 timeout
        Dec 31 16:34:40 dns pdns[25637]: Query: select id,name,master,last_check,notified_serial,type,account from domains where name=:domain
        Dec 31 16:34:40 dns pdns[25637]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=:qtype and name=:qname
        Dec 31 16:34:40 dns pdns[25637]: No serial for 'example2.com' found - zone is missing?
        ...

**Comment by aj-gh** [comment]
See issue #5974. I had a similar issue with a master that has issues on EDNS queries - which pdns started to use for SOA checks after we enabled DNSSEC.

**Comment by Habbie** [comment]
Closing this in favour of #5974
