### ISSUE TITLE
SSL certificate name mismatch on https://dnsdist.org

### ISSUE THREAD

**Issue by James-TR** [PowerDNS/pdns#4488]
Hi, I've noticed dnsdist.org doesn't currently have a valid SSL certificate, and attempting to go to https://dnsdist.org results in the browser instead getting the certificate for *.powerdns.com.

This is mostly an issue for people who will habitually just type https:// instead of going straight to dnsdist.org.

**Comment by pieterlexis** [comment]
yes, the IP used has TLS (with SNI) but only for powerdns.com. When this was setup, letsencrypt didn't exist yet. However, as the downloads website does have TLS, adding this to the dnsdist website is very low-priority
