### ISSUE TITLE
[Request] Armhf packages in Ubuntu Xenial

### ISSUE THREAD

**Issue by kometchtech** [PowerDNS/pdns#4501]
It is a request.
You can't introduce compile-time is non-Rspberry Pi ARM boards, running the Ubuntu Xenial have only 1 GB memory for the.
I want available Repository packages corresponding to armhf if possible.

My best regards.

**Comment by pieterlexis** [comment]
Hi,

We do not plan to supply armhf packages for Ubuntu anytime soon (sorry). Adding 2GB of swap will allow you to compile PowerDNS on a raspberry Pi (or other systems).
