### ISSUE TITLE
write-pid ignored when using systemd pdns.service

### ISSUE THREAD

**Issue by fliespl** [PowerDNS/pdns#4522]
I have tried to set pdns to work with monit using it's pid file.

Unfortunately - default systemd file ignores write-pid option. I have set pdns server to start with write-pid=yes (inside /etc/powerdns/pdns.conf config file) this setting is ignored.

This is due to a command line argument used in pdns.service file.
```
ExecStart=@sbindir@/pdns_server --guardian=no --daemon=no --disable-syslog --write-pid=no
```
Is editing pdns.service the only option to get it working correctly or can this be simplified? (worked fine in alpha versions from what I remember)

**Comment by pieterlexis** [comment]
This is indeed correct, commandline arguments always trump the config file. Using a pidfile is not needed when running under systemd (apart from you special case).

**Comment by fliespl** [comment]
@pieterlexis thank you for this clarification.  Appreciate that.

I will switch to use 'with match' instead of 'with pidfile' inside monit config file for now on.

**Comment by windware-ono** [comment]
Ancient thread but here's how to override the systemd config.

`systemctl edit pdns`

and add these lines,
(and set `write-pid=yes` in the pdns.conf)

```
[Service]
ExecStart=
ExecStart=/usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no
```

There's a risk that at some point, if PowerDNS update changes the way it launches itself in the systemd unit file, you should also match it. (Or better if the official unit file just remove `--write-pid=no` as it should be controlled in the config file.)

This creates the PID in `/run/pdns.pid`.
