### ISSUE TITLE
API search breaks on ENTs

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#4534]
<Habbie> rectify-zone adds NULL records
<Habbie> to fill 'holes' in the tree
<Habbie> apparently API search chokes on those
<Habbie> they are called ENTs

Got 500 errors from the API with message ```HTTP ISE for "/api/v1/servers/localhost/search-data": STL Exception: Unknown record was stored incorrectly, need 3 fields, got 0``` in the logs. After removing the following records, search started working again:

```
<Jeeves_> 8862|382|_domainkey.hidingmycustomer.nl||||||0||1
<Jeeves_> 8863|382|_tcp.hidingmycustomer.nl||||||0||1
```

**Comment by zeha** [comment]
@tuxis-ie which version of powerdns is that?

**Comment by tuxis-ie** [comment]
@zeha  4.0.1-1pdns.jessie
