### ISSUE TITLE
Recursion on authoritative zone not working for non-existing records

### ISSUE THREAD

**Issue by jimikoukou** [PowerDNS/pdns#4540]
Hello,
I've read many topics on the subject on the pdns mailing list but none seems to provide a solution.

According to documentation:

> To make sure that the local authoritative database overrides recursive information, PowerDNS first tries to answer a question from its own database. If that succeeds, the answer packet is sent back immediately without involving the recursor in any way. This means that for questions for which there is no answer, PowerDNS will consult the recursor for an recursive query, even if PowerDNS is authoritative for a domain!

This feature is not working, at least not after pdns v.2.x as some say, couldn't find such an old version.
I've tested many versions of 3.x, 4.x and none works.

Assuming a master domain exists on a local pdns, eg. mydomain.com but an A record such as test.mydomain.com does not exist.
The zone mydomain.com and the A record test.mydomain.com exists on a public or another DNS that is set as a recursor on the settings of authoritative pdns.
The query for test.domain.com is not forwarded to the recursor, the answer is "Non-existent domain".
The expected behaviour, as described in the documentation, is that the pdns searches its own zone, sees that the record is missing, forwards the query to its recursor, and replies with its answer.

The only way I could achieve this was by setting up a Recursor in front, send the queries there and redirect the queries and answers accordingly through a LUA script, but then I lose the Dynamic DNS Update functionality which I need, and other features.

**Comment by phonedph1** [comment]
Just to confirm, your example here is really "test.mydomain.com" and "test2.mydomain.com", right? Can you update the ticket to reflect this?

**Comment by pieterlexis** [comment]
Closing due to lack of response and the fact that the built-in recursor for the authoritative server is being removed.
