### ISSUE TITLE
Error building pdns-recursor with clang and GNU libstdc++

### ISSUE THREAD

**Issue by slacka** [PowerDNS/pdns#4563]
When building pdns-recursor with clang I get:

`optional.hpp:678:15: error: no matching member function for call to 'construct'`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/pdns-recursor_4.0.1-1_unstable_clang.log

**Comment by zeha** [comment]
Can confirm with Debian's 4.0.3-3 in sid.

**Comment by rgacogne** [comment]
It seems that clang doesn't like the `boost::optional` part of `gettag()`'s return value. Making it non-optional works but would break existing `gettag()`. This could perhaps be fixed by using a `boost::variant` instead, but I didn't succeed so far.

**Comment by pieterlexis** [comment]
I don't believe this should be an issue. If this is still an issue on master, please re-open
