### ISSUE TITLE
PowerDNS could work or not when disable ipv6

### ISSUE THREAD

**Issue by hxzhaoyf** [PowerDNS/pdns#4568]
hi, I get some problem about IPV6. My OS is CentOS release 6.5 (Final), and disable IPV6. My PowerDNS version is pdns-4.0.1-1pdns.
when starting pdns with :
```
service pdns monitor
```
the output is:
~~~
Oct 14 16:15:58 Reading random entropy from '/dev/urandom'
Oct 14 16:15:58 Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Oct 14 16:15:58 [gmysqlbackend] This is the gmysql backend version 4.0.1 (Jul 29 2016 14:57:20) reporting
Oct 14 16:15:58 This is a standalone pdns
Oct 14 16:15:58 UDP server bound to 0.0.0.0:53
Oct 14 16:15:58 IPv6 Address Family is not supported - skipping UDPv6 bind
Oct 14 16:15:58 TCP server bound to 0.0.0.0:53
Oct 14 16:15:58 Fatal error: Unable to acquire TCPv6 socket: Address family not supported by protocol
~~~

I can't find the config option about disable ipv6 or something else, is any suggestion? Thanks!

**Comment by zeha** [comment]
In general, disabling IPv6 on Linux is not very well supported.

For pdns, you must remove all those ipv6 listening sockets, e.g. local-address6, ...

**Comment by hxzhaoyf** [comment]
@zeha thanks for your relay.
My system must be disable ipv6 so I have to try with other method.
~~~
#################################
# local-address Local IP addresses to which we bind
#
# local-address=0.0.0.0

#################################
# local-address-nonexist-fail   Fail to start if one or more of the local-address's do not exist on this server
#
# local-address-nonexist-fail=yes

#################################
# local-ipv6    Local IP address to which we bind
#
# local-ipv6=::

#################################
# local-ipv6-nonexist-fail      Fail to start if one or more of the local-ipv6 addresses do not exist on this server
#
local-ipv6-nonexist-fail=yes
...
#################################
# do-ipv6-additional-processing Do AAAA additional processing
#
# do-ipv6-additional-processing=yes
~~~
the docs about cofig file setting say:
```
For boolean settings, specifying the name of the setting without a value means yes.
```
but how should I set the option like "local-ipv6=::"? Just commend it? 
Sorry for my poor understand about pdns and dns.

**Comment by hxzhaoyf** [comment]
I delete everything about '::', and change the
```
# local-ipv6=::  
```
with
```
 local-ipv6=
```
and it works.

**Comment by pieterlexis** [comment]
`local-ipv6=` should disable this setting

**Comment by hxzhaoyf** [comment]
@pieterlexis thanks, I have tried your advice setting and it works.

**Comment by istiyakaminsanto** [comment]
> I delete everything about '::', and change the
> 
> ```
> # local-ipv6=::  
> ```
> 
> with
> 
> ```
>  local-ipv6=
> ```
> 
> and it works.

It works for me <3

**Comment by MrCoding** [comment]
Worked for me too!

**Comment by rbgtk** [comment]
Since `local-ipv6` is being deprecated, you must edit the `local-address` instead.

Change

```
# local-address=0.0.0.0, ::
```

To:

```
local-address=0.0.0.0
```

So as to only bind to ipv4
