### ISSUE TITLE
pdns-recursor-4.0.3 compilation error on mtasker_context

### ISSUE THREAD

**Issue by Pascal76** [PowerDNS/pdns#4571]
fedora old release (14 & 17) but with latest gcc (6.2.0) and boost last version (1.62 and tested on 1.60/1.59 too)

It is ko on "mtasker_context":

...
  CXX      arguments.o
  CXX      logger.o
  CXX      misc.o
  CXX      rec_channel.o
  CXX      rec_control.o
  CXX      unix_utility.o
  CXXLD    rec_control
  CXX      base32.o
  CXX      base64.o
  CXX      dns.o
  CXX      dns_random.o
  CXX      dnsrecords.o
  CXX      dnssecinfra.o
  CXX      dnswriter.o
  CXX      ednssubnet.o
  CXX      gettime.o
  CXX      gss_context.o
  CXX      iputils.o
  CXX      json.o
  CXX      lua-recursor4.o
  CXX      lwres.o
  CXX      mtasker_context.o
In file included from mtasker_context.cc:27:0:
mtasker_fcontext.cc:33:23: erreur : 'boost::context::make_fcontext' has not been declared
 using boost::context::make_fcontext;
                       ^~~~~~~~~~~~~
mtasker_fcontext.cc:64:23: erreur : 'boost::context::fcontext_t' has not been declared
 using boost::context::fcontext_t;
                       ^~~~~~~~~~
mtasker_fcontext.cc:65:23: erreur : 'boost::context::jump_fcontext' has not been declared
 using boost::context::jump_fcontext;
                       ^~~~~~~~~~~~~
mtasker_fcontext.cc:67:32: erreur : 'fcontext_t' was not declared in this scope
 static_assert (std::is_pointer<fcontext_t>::value,
                                ^~~~~~~~~~
mtasker_fcontext.cc:67:32: note : suggested alternative:
In file included from mtasker_fcontext.cc:27:0,
                 from mtasker_context.cc:27:
/usr/local/include/boost/context/detail/fcontext.hpp:23:17: note :   'boost::context::detail::fcontext_t'
 typedef void*   fcontext_t;
                 ^~~~~~~~~~
In file included from mtasker_context.cc:27:0:
mtasker_fcontext.cc:67:42: erreur : patron de l'argument 1 est invalide
 static_assert (std::is_pointer<fcontext_t>::value,
                                          ^
mtasker_fcontext.cc:75:5: erreur : 'fcontext_t' does not name a type
     fcontext_t prev_ctx = nullptr;
     ^~~~~~~~~~
mtasker_fcontext.cc: Dans la fonction 'void threadWrapper(intptr_t)':
mtasker_fcontext.cc:96:37: erreur : 'fcontext_t' does not name a type
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),
                                     ^~~~~~~~~~
mtasker_fcontext.cc:96:47: erreur : expected '>' before '*' token
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),
                                               ^
mtasker_fcontext.cc:96:47: erreur : expected '(' before '*' token
mtasker_fcontext.cc:96:48: erreur : expected primary-expression before '>' token
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),
                                                ^
mtasker_fcontext.cc:97:32: erreur : 'fcontext_t' does not name a type
                    static_cast<fcontext_t>(args->prev_ctx), 0);
                                ^~~~~~~~~~
mtasker_fcontext.cc:97:50: erreur : 'struct args_t' has no member named 'prev_ctx'
                    static_cast<fcontext_t>(args->prev_ctx), 0);
                                                  ^~~~~~~~
mtasker_fcontext.cc:109:37: erreur : 'fcontext_t' does not name a type
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),
                                     ^~~~~~~~~~
mtasker_fcontext.cc:109:47: erreur : expected '>' before '*' token
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),
                                               ^
mtasker_fcontext.cc:109:47: erreur : expected '(' before '*' token
mtasker_fcontext.cc:109:48: erreur : expected primary-expression before '>' token
     jump_fcontext (reinterpret_cast<fcontext_t*>(&ctx->uc_mcontext),

**Comment by phonedph1** [comment]
This is fixed in #4511

**Comment by Pascal76** [comment]
can be closed
