### ISSUE TITLE
Pipe backend with fallback on recursor

### ISSUE THREAD

**Issue by elad** [PowerDNS/pdns#4615]
Hello,

I'm writing a pipe backend and want it to fallback on the recursor if it can't answer the query.

My `pdns.local.conf` looks like this:

```
recursor=8.8.8.8
launch=pipe
pipebackend-abi-version=5
pipe-command=/home/admin/pdns-backend.py
```

Queries that should be answered by my backend are working fine. That is, I have the `DATA` lines returning the data I want and `nslookup` shows the appropriate output.

However, it's unclear from [the documentation](https://doc.powerdns.com/md/authoritative/backend-pipe/) how the pipe backend should behave for queries that should be passed on to the recursor. If I respond with `END` I get NXDOMAIN and if I respond with `FAIL` I get SERVFAIL (in `nslookup`).

What am I doing wrong and/or missing?

**Comment by pieterlexis** [comment]
hi, this is a support question. Please use the [mailinglists or IRC for this](https://powerdns.com/opensource.html).

From what I can tell you're using the authoritative server as a recursor. This is a terrible idea. I think a better solution is using the recursor and use the [Lua hooks](https://doc.powerdns.com/md/recursor/scripting/)

**Comment by phonedph1** [comment]
Also potentially the same question in #4540
