### ISSUE TITLE
remove `recursor=` setting from auth?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4616]
This is a discussion ticket.

At least once a week, we talk to a user that is confused about `recursor` because it is not doing what he/she expects. Meanwhile we/I feel that there are very, very few legitimate use cases for `recursor` that cannot be covered by reversing the setup (putting the Recursor in front) or deploying dnsdist. So, some of us would like to entirely remove the `recursor` feature.

If you disagree, please describe, carefully and in detail, your use case, so we can figure out how we can support that.

**Comment by apfohl** [comment]
Hi, as described in issue #4655, it would be nice to have an option for the stub resolver to set an upstream nameserver. Maybe `recursor` is the wrong name for that, but it should definitely be possible.

**Comment by Habbie** [comment]
@apfohl yes, I'd like to keep that around, but would indeed rename the flag for it if we remove `recursor`

**Comment by sndrsmnk** [comment]
Please note that auth fails to do security checks / ALIAS expansion and logs about this with no `recursor=` set:

```
No recursors set, stub resolving (including secpoll and ALIAS) impossible.
Could not retrieve security status update for '4.0.3' on 'auth-4.0.3.security-status.secpoll.powerdns.com.', RCODE = Server Failure
```

**Comment by pieterlexis** [comment]
@sndrsmnk by default, we do parse /etc/resolv.conf. if recursor is set to (empty), we indeed cannot resolve.

**Comment by sndrsmnk** [comment]
> @sndrsmnk by default, we do parse /etc/resolv.conf. if recursor is set to (empty), we indeed cannot resolve.

But having no 'nameserver' in resolv.conf should default to localhost, right?

**Comment by ahupowerdns** [comment]
@tomsommer - noted, but this is what we have chosen since the feature was confusing and made our life very difficult. What I hear is that you would like to be able to provision zones to the PowerDNS Recursor, is that correct?

**Comment by tomsommer** [comment]
That's exactly how we use Auth in our internal DNS structure, for split horizon on thousands of hostnames, with the recursor as fallback for any domains unknown to the auth.

**Comment by ahupowerdns** [comment]
So 1) you can actually provision authoritative zones to the PowerDNS Recursor with the API 2) have you studied https://doc.powerdns.com/authoritative/guides/recursion.html for workarounds?

**Comment by tomsommer** [comment]
1) I was not aware of this, where are the documentation for this? Perhaps this should be added to https://doc.powerdns.com/authoritative/guides/recursion.html as a third option? I know many use PowerDNS as we do, for split horizon.
2) I have, both require manual setup of forwarding zones, which is completely unfeasible to us, unless we move all hostnames to a select amount of domains, which they currently are not.

**Comment by ahupowerdns** [comment]
It is completely unfeasible to provision which zones to forward, but it is feasible to maintain them in MySQL? I'm confused. This ticket is not about "we do not want to change anything". You can add the zones you need forwarded to forward-zones-file. It is not hard to do. If provisioning lines to a file is too hard, I'm not sure what to say.

**Comment by tomsommer** [comment]
We add each hostname to the `domains` table in MYSQL using an internal management tool, thus the Auth will override recursion for these hostnames and return the IP we want for the hostname, this means we currently have thousands of arbitrary hostnames in our Auth, and the Auth is then our DNS Server, also providing recursion for hostnames not found in the Auth.

Hope that makes sense.

I'm just saying this is valid and powerful use-case of PowerDNS, which would be impossible to do in 4.1.0 (said without having found the Recursion API yet)

**Comment by ahupowerdns** [comment]
Try generating the forward-zones-file from your MySQL database, should solve your problem. You can reload that file with "rec_control reload-zones".  For the API, we're double checking if that is actually supported, so don't count on that now.

**Comment by rmccullagh** [comment]
Removing this feature makes migrating from BIND to power dns difficult. Our use case is the same as @tomsommer  - We would like to use the PowerDNS authoritative server, serving domains we have in MySQL, but forward non existent zones to an upstream resolver, like 8.8.8.8. Is there any way we can do this?

**Comment by Habbie** [comment]
Note that in general, comments on closed tickets tend to go unresponded. In this case I noticed, so I can point you to https://doc.powerdns.com/authoritative/guides/recursion.html

I will close conversations on this ticket to avoid any future comments going unanswered. If you have questions, please reach out to us via IRC or mailing list - information at https://www.powerdns.com/opensource.html
