### ISSUE TITLE
AXFR timeouts, can't figure out what timed out

### ISSUE THREAD

**Issue by sndrsmnk** [PowerDNS/pdns#4617]
My pdns server is currently logging a lot of 

>  Received serial number updates for 0 zones, had 4 timeouts

but i can't find out what zones timed out exactly. According to the code there is no 'feature' to log what timed out either. With a higher loglevel i did get:

> TCP Connection Thread died because of network error: Timeout reading data

But still no information on what host it was trying to contact.

Also, 'pdns_control set loglevel X' is not supported at runtime.

(pdns 4.0.1-1pdns.xenial from repo.powerdns.com)

**Comment by cmouse** [comment]
The issue tracker on github is not a support channel, please use either irc://irc.oftc.net/powerdns or contact mailing list pdns-users@mailman.powerdns.org

**Comment by Habbie** [comment]
Fixed in #4953.
