### ISSUE TITLE
PowerDNS Recursor 4.0.3-1pdns.jessie not calling Lua postresolve function on DNSSEC servfail

### ISSUE THREAD

**Issue by Fusl** [PowerDNS/pdns#4618]
Steps to reproduce:

File `recursor.conf`:
```
lua-dns-script=/etc/powerdns/recursor.lua
dnssec=validate
dnssec-log-bogus=yes
```

File `recursor.lua`:
```
function postresolve (dq)
    print ("postresolve called for " .. dq.qname:toString())
    dq.rcode = 0
    return true
end
```

```
> dig sigok.verteiltesysteme.net @127.0.0.1
# returns noerror
> grep "postresolve called for" /var/log/syslog
# shows "postresolve called for sigok.verteiltesysteme.net.
> dig sigfail.verteiltesysteme.net @127.0.0.1
# returns servfail
> grep "postresolve called for" /var/log/syslog
# doesn't show "postresolve called for sigfail.verteiltesysteme.net.
```

My guess is that this is caused by the `goto sendit;` part [here](https://github.com/PowerDNS/pdns/blob/eeb3f06090648be33b78c396cb1957309298f522/pdns/pdns_recursor.cc#L1009) instead of triggering the `postresolve` function provided in the Lua script - before, during or after the dnssec (in)validation - with an empty record set and `dq.rcode` set to `2`.

**Comment by pieterlexis** [comment]
In the current design, DNSSEC validation happens after resolving. postresolve is called earlier than this [here](https://github.com/PowerDNS/pdns/blob/eeb3f06090648be33b78c396cb1957309298f522/pdns/pdns_recursor.cc#L897). Can you change the print to `pdnslog` and retry? I don't see why postresolve shouldn't be called regardless of DNSSEC.

**Comment by Fusl** [comment]
Seems you are totally right here. I have a more complicated Lua script and got confused by the `dq.rcode`. The Lua script replaces data with a previously cached response in case the rcode is `SERVFAIL` and I actually expected the DNSSEC validation to happen before the `postresolve` function is called, but this explains the "issue" I was seeing. Sorry for the hassle :)
