### ISSUE TITLE
API & pdnsutil: trailing dots inconsistencies

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#4621]
NSEdit allows septr to be used, and this works fine. However, the API requires us to append dots to the records. When we create a A/AAAA-record like "kerio.tuxis.nl. IN A 31.3.111.19" the following PTR is created: "19.111.3.31.in-addr.arpa IN PTR kerio.tuxis.nl.".

pdnsutil check-all-zones starts complaining that there is a trailing dot in the PTR record:
[Warning] Parsed and original record content are not equal: 19.111.3.31.in-addr.arpa IN PTR 'kerio.tuxis.nl.' (Content parsed as 'kerio.tuxis.nl')

**Comment by tuxis-ie** [comment]
It looks like pdnsutil edit-zone suffers from this issue as well:
root@webserver:~# pdnsutil check-zone 0.0.10.in-addr.arpa
[Warning] Parsed and original record content are not equal: 28.0.0.10.in-addr.arpa IN PTR 'host01.dadup.dmz.tuxis.net.' (Content parsed as 'host01.dadup.dmz.tuxis.net')

I created this record with pdnsutil, and dit not add the trailing dot myself.

**Comment by zeha** [comment]
If edit-zone gets it wrong, I'd say it's a separate ticket.

**Comment by tuxis-ie** [comment]
This is pretty annoying. Is this anywhere on the roadmap towards fixing?
