### ISSUE TITLE
PowerDNS Recursor 4.0.3-1pdns.xenial always returns SERVFAIL when setting --max-cache-ttl=0

### ISSUE THREAD

**Issue by Fusl** [PowerDNS/pdns#4634]
Setting `--max-cache-ttl=0` makes `pdns-recursor=4.0.3-1pdns.xenial` answer `SERVFAIL` to all kind of queries sent to the recursor. If the recursor is unable to deal with this option set to `0`, we should make it fail when trying to start instead of just silently replying with an error to queries.

**Comment by pieterlexis** [comment]
what is your dnssec= setting?

**Comment by Fusl** [comment]
Doesn't make any difference whether I set it to `off`, `process-no-validate`, `process`, `log-fail` or `validate`.

**Comment by pieterlexis** [comment]
quick update: this issue also manifests itself in the same way on 3.7.3. I am considering to force the minimum of max-cache-ttl to be in the order of 15 seconds, as running without a cache makes no sense operationally (and even if it would, it is not very friendly to the internet as a whole)
