### ISSUE TITLE
current changelog 3.x 4.x split state is confusing

### ISSUE THREAD

**Issue by ZaphodB** [PowerDNS/pdns#4639]
The current state of the documentations changelog is confusing.

Up to PowerDNS Server v3.4.10 the combined changelog at https://doc.powerdns.com/md/changelog/ lists all changes regardless of version i.e. the 4.x changelog location includes both 3.x and 4.x changes but then only https://doc.powerdns.com/3/changelog/ lists v3.4.10 changes which is inconsistent.
@Habbie agreed that it should either bei fully combined or fully split, i for one would prefer the fully combined variant because from a users perspective the single location makes it easier to search for a specific version or change.

Also on a related note i found #2166 which states that people are confused about the combined changelog for Auth Server and Recursor per se.

**Comment by mind04** [comment]
I prefer, remove the changelog in 3.x and point people to a full one in the 4.x doc.

**Comment by Habbie** [comment]
Starting with 4.1 our docs have been split. @pieterlexis shall we close this?

**Comment by pieterlexis** [comment]
The changelog is now split between [recursor](https://doc.powerdns.com/recursor/changelog/index.html) and [auth](https://doc.powerdns.com/authoritative/changelog/index.html) and per major version.
