### ISSUE TITLE
Is any option about interval between two reload in pdns.conf

### ISSUE THREAD

**Issue by hxzhaoyf** [PowerDNS/pdns#4642]
- Program: Authoritative

### Short description
how long the pdns get DNS message from backend?
my pdns config is like:
~~~
log-dns-details=yes
log-dns-queries=yes
logging-facility=0
loglevel=9
query-logging=yes
api-logfile=/data/apps/logs/pdns/pdns.log
disable-syslog=yes

launch=gmysql
gmysql-host=xxx
gmysql-user=xxx
gmysql-dbname=pdns
gmysql-password=xxx

local-ipv6=

api=yes
api-key=aaaa
api-logfile=/data/apps/log/pdns/pdns.log
webserver=yes
webserver-address=127.0.0.1

~~~

I test how long I can get the dns after inserting the DNS message into mysql(by Poweradmin) with a simple script:
~~~
#!/usr/bin/sh
while true
do
  echo `date & nslookup $1 |grep -i address`
  sleep 1
done
~~~
I see the nslookup can not get the dns message immediately. I think pdns will reload dns message periodically, but I'm sorry I can't get the option about interval between two reload in pdns.conf. 

### my problems
* Is any option about interval between two reload in pdns.conf?
* Will pdns reload dns message from mysql when I insert or change a dns message with HTTP API?

Thank you!

### Environment

 - Operating system:  CentOS release 6.5 (Final)
 - Software version: pdns-4.0.1-1pdns.el6.x86_64
 - Software source:Operating system repository

**Comment by Habbie** [comment]
This is a bug tracker, not a support forum. Please see https://www.powerdns.com/opensource.html on how to get community support!
