### ISSUE TITLE
REST API: No validation of 'masters' when adding a zone

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#4645]
- Program: Authoritative 
- Issue type: Bug report 
### Short description

The REST API accepts hostnames and any other invalid input as masters when creating a slave zone, while only IP addresses are allowed here.

### Environment

- Operating system: Ubuntu 16.04
- Software version: PowerDNS Authoritative Server 0.0.1320gf354a19 (master build)
- Software source: PowerDNS repository 
### Steps to reproduce

Reproducible with this curl command:

```
 $ curl -X POST --data '{"name":"test2.example.org.", "kind": "Slave", "masters": ["hostname-not-allowed-here"], "nameservers": ["ns1.example.org.", "ns2.example.org."]}' -v -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones | jq .
```
### Expected behaviour

Server shoudl refuse to add a domain with invalid masters.
### Actual behaviour

The server accept the request and inserts invalid masters:

```
{
  "account": "",
  "dnssec": false,
  "id": "test2.example.org.",
  "kind": "Slave",
  "last_check": 0,
  "masters": [
    "hostname-not-allowed-here"
  ],
  "name": "test2.example.org.",
  "notified_serial": 0,
  "rrsets": [
    {
      "comments": [],
      "name": "test2.example.org.",
      "records": [
        {
          "content": "ns1.example.org.",
          "disabled": false
        },
        {
          "content": "ns2.example.org.",
          "disabled": false
        }
      ],
      "ttl": 3600,
      "type": "NS"
    }
  ],
  "serial": 0,
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
  "url": "/api/v1/servers/localhost/zones/test2.example.org."
}
```
### Usecase

Trying to create a UI that relies on the API for input validation.

**Comment by zeha** [comment]
@zeha you need to look at this

**Comment by zeha** [comment]
Allowed values for masters:

* v4 address
* v6 address
* v4:port
* [v6]:port

Separated by comma/space/tab (but API should delegate this issue to backend).

**Comment by zeha** [comment]
Habbie noted there is a design asymmetry when retrieving vs. setting the master list, also various parts ComboAddressify the results, and other parts do not.

**Comment by zeha** [comment]
#7569 fixed this.
