### ISSUE TITLE
Repository: please ship -dbgsym packages for Debian/Ubuntu

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#4649]
The -dbg packages are kinda deprecated and probably do not have symbols for backends. Maybe switch to the new -dbgsym shinyness, and figure out what to do for Ubuntu.

In Debian itself, the changes were:
- https://anonscm.debian.org/cgit/pkg-dns/pdns.git/patch/debian/rules?id=a82ab4daa85fe590e6dbf2057a75d4d51eefaac0
- https://anonscm.debian.org/cgit/pkg-dns/pdns.git/commit/debian/control?id=3cba7433fc6433535a0381c91be89c1343ba13b4

**Comment by pieterlexis** [comment]
I have a feeling this is supported from stretch onward?

**Comment by zeha** [comment]
To build, it needs the new debhelper (>= 9.20160114~) which is in stretch or j-bpo.
Installing should work on plain jessie+.

**Comment by pieterlexis** [comment]
hrm, our pain mostly come from supporting many distros and versions thereof at the same time. I have some ideas to change this up with templated snippets, but I fear that will mean too much hassle.

**Comment by zeha** [comment]
if you decide to drop the -dbg package for older distros, i think that should be a very minimal change...

**Comment by pieterlexis** [comment]
We now do this after the merge of pdns-builder.
