### ISSUE TITLE
Feature request: Delete PTR when deleting A/AAAA record.

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#4656]
It would be nice to have the possibility to delete a PTR when deleting an A or AAAA record.

Based on: https://github.com/tuxis-ie/nsedit/issues/131

**Comment by zeha** [comment]
Agreed; I suppose inside an rrset object we could add a flag 'delete-ptr' to allow for that.

When doing that, also think about deleting old PTRs when updating an existing record.

**Comment by Halytskyi** [comment]
Any updates about this feature? Thanks.

**Comment by mobilehicklin** [comment]
Hi is it possible to have some response to the ptr question

**Comment by ahupowerdns** [comment]
I think this would be somewhat of a misfeature. We don't know what zone the reverse record lives in, we'd need to hunt it. It might even be in several zones. Do we really want the API to do this? Note that if you filter the API so someone can only edit the zones that are 'theirs', this delete call will touch other zones over which someone has no control. I don't think our API should go there, but perhaps I'm not seeing it right.

**Comment by zeha** [comment]
We have the feature to add the PTR, so this is the mirror of that.
Mostly needs typing in I think.

**Comment by tuxis-ie** [comment]
@ahupowerdns Although your concerns are pretty valid, don't they also apply to setting the PTR? Especially with IPv6, I've seen the PTR end up in another zone than I expected it (probably my fault, but still).

Since the API has no authorization system, but only authentication, you should assume a admin is working on the API whatsoever. The client (such as nsedit) should decide if you want to set/delete PTR's. The API should only provide the option.

**Comment by jwhited** [comment]
> Since the API has no authorization system, but only authentication, you should assume a admin is working on the API whatsoever. The client (such as nsedit) should decide if you want to set/delete PTR's. The API should only provide the option.

The PowerDNS API has no authorization but is built in a way that authorization can exist in a proxy layer on top. Introducing features like this requires the authorization layers to perform the same kind of hunting logic / request body parsing in order to properly enforce zone-level permissions.

**Comment by zeha** [comment]
At this time I think we should remove set-ptr from the API and not implement delete-ptr.

@tuxis-is did you implement delete in nsedit yet? Can you reuse that for set?

**Comment by Habbie** [comment]
> At this time I think we should remove set-ptr from the API and not implement delete-ptr.

:+1:

**Comment by Habbie** [comment]
We are removing set-ptr in 4.3.0. This also means we will not build automatic deletion.
