### ISSUE TITLE
GeoIP backend support name server health check

### ISSUE THREAD

**Issue by dubiety** [PowerDNS/pdns#4661]
- Program: Authoritative 
 - Issue type: Feature request 

### Description

It seems current GeoIP backend or powerdns authority server does not support health check. Is it possible to support health check so when other ask NS record, the authority server can reply only the name servers that is alive?

**Comment by Habbie** [comment]
You can do this with LUA records now, even inside the geoipbackend. https://doc.powerdns.com/authoritative/lua-records/index.html
