### ISSUE TITLE
Recursor option to serve expired cache entries if auth DNS server is unreachable

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4662]
- Program: Recursor
 - Issue type: Feature request

### Short description

Following on from https://github.com/PowerDNS/pdns/issues/3470 which is a similar feature request for dnsdist, is it possible to add an option to serve expired cache entries if auth DNS servers are currently unreachable? Some issues from the recent Dyn outage could perhaps have been avoided had this feature been in place, and following the outage Unbound added this option serving with 0 TTL.

**Comment by KawaiDesu** [comment]
Hello! Any updates on this? Last update was milestone change to 4.3 release in 2018. Today there is already 4.4.

**Comment by omoerbeek** [comment]
While this is an interesting feature,  it is not being considered for implementation by the team in the near future. Basically a lack of time is the main reason. We always welcome PRs though.  I'm moving this to the 4.5 milestone, so it will be reconsidered for that release. No promise, though.

**Comment by KawaiDesu** [comment]
Thanks for the update!

**Comment by pieterlexis** [comment]
Here's the RFC that should be implemented if we choose to do so: [RFC 8767](https://www.rfc-editor.org/rfc/rfc8767.html)

**Comment by omoerbeek** [comment]
Implemented in #11776
