### ISSUE TITLE
DNSKEY missing in ANY tests for signed zone

### ISSUE THREAD

**Issue by aeden** [PowerDNS/pdns#4687]
- Program: Regression Tests
 - Issue type: Bug report

### Short description

In the test any-query, the DNSKEY is not returned, but the zone is signed based on the direct-dnskey test. DNSKEY should be returned.

### Environment
 - Operating system: N/A
 - Software version: HEAD
 - Software source: PowerDNS repository

### Steps to reproduce

Did not run tests, but found while translating tests for my test suite.

### Expected behaviour

I expect DNSSEC records to be returned from a signed zone, even when DNSSEC is not requested.

### Actual behaviour

```
0	example.com.	IN	MX	120	10 smtp-servers.example.com.
0	example.com.	IN	MX	120	15 smtp-servers.test.com.
0	example.com.	IN	NS	120	ns1.example.com.
0	example.com.	IN	NS	120	ns2.example.com.
0	example.com.	IN	SOA	100000	ns1.example.com. ahu.example.com. 2847484148 28800 7200 604800 86400
2	.	IN	OPT	0	
2	ns1.example.com.	IN	A	120	192.168.1.1
2	ns2.example.com.	IN	A	120	192.168.1.2
2	smtp-servers.example.com.	IN	A	120	192.168.0.2
2	smtp-servers.example.com.	IN	A	120	192.168.0.3
2	smtp-servers.example.com.	IN	A	120	192.168.0.4
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
Reply to question for qname='example.com.', qtype=ANY
```

### Other information

N/A

### Usecase

Trying to make DNS great again. ;-)

Kidding, I'm using the powerdns test suite as the basis for my erlang DNS test suite.

### Description

Provide thorough, accurate tests. And continue being awesome!

**Comment by Habbie** [comment]
@aeden thanks!

NSEC is missing as well.

**Comment by Habbie** [comment]
After discussion on IRC, it is agreed that this behaviour is 'wrong' but it is also intentional. Somebody querying for ANY is unlikely to actually be interested in DNSKEY and NSEC while they would make the response a lot bigger.
