### ISSUE TITLE
OS X Sierra unable to use port 53

### ISSUE THREAD

**Issue by melvinchia** [PowerDNS/pdns#4698]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

This is a request for help.

I'm running OS X Sierra 10.12.1 as a server, and trying to run a PowerDNS server on it. Problem is, that port 53 seems to be locked up by the OS somehow. There are no other services listening to Port 53 from a lsof scan. The OS Firewall is disabled.

I also have an Apache httpd server, so I set it up to listen to ports TCP 51-55, and it was able to capture port 53, attempts to view the website on ports 51, 52, 54, and 55 work. Any attempts to view the website on port 53 doesn't yield any results whatsoever.

Does anybody have a fix?

### Environment

 - Operating system: Mac OS X 10.12.1
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by zeha** [comment]
This is a bug tracker, not a support forum. Please see https://www.powerdns.com/opensource.html on how to get community support!
