### ISSUE TITLE
pdnsutil editzone and sorting

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#4699]
- Program: Authoritative
 - Issue type: Bug report/Feature request

### Short description
pdnsutils does try to sort a zone in editzone, but the sorting does not make sense for in-addr.arpa. zones. Eg:
22.0.0.10.in-addr.arpa  3600    IN      PTR
23.0.0.10.in-addr.arpa  3600    IN      PTR
24.0.0.10.in-addr.arpa  3600    IN      PTR
25.0.0.10.in-addr.arpa  3600    IN      PTR
250.0.0.10.in-addr.arpa 3600    IN      PTR
251.0.0.10.in-addr.arpa 3600    IN      PTR
252.0.0.10.in-addr.arpa 3600    IN      PTR
253.0.0.10.in-addr.arpa 3600    IN      PTR
254.0.0.10.in-addr.arpa 3600    IN      PTR
26.0.0.10.in-addr.arpa  3600    IN      PTR     
27.0.0.10.in-addr.arpa  3600    IN      PTR     
29.0.0.10.in-addr.arpa  3600    IN      PTR     

Please sort these zones numerically.

**Comment by pieterlexis** [comment]
superceded by #4699
