### ISSUE TITLE
over-sensitive when reporting retrieve/refresh faults

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#470]
This is Debian bug #397360, http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=397360

Text follows:
I have server B slave a bunch of zones from server A, and every 1-2
days, server B will complain:

  Error trying to retrieve/refresh 'my.zone.net': Timeout waiting
  for answer

I just captured what's going on on A and B at the time with tcpdump:

B:
  IP 82.197.162.59.14354 > 213.203.238.82.53:  38606 SOA? debian-system.info. (36)
  IP 82.197.162.59.19421 > 213.203.238.82.53:  53145 SOA? debian-system.info. (36)
  IP 213.203.238.82.53 > 82.197.162.59.19421:  53145*- 1/0/0 SOA[|domain] 

A:
  IP 82.197.162.59.14354 > 213.203.238.82.53:  38606 SOA? debian-system.info. (36)
  IP 213.203.238.82.53 > 82.197.162.59.14354:  38606_\- 1/0/0 SOA[|domain]
  IP 82.197.162.59.19421 > 213.203.238.82.53:  53145 SOA? debian-system.info. (36)
  IP 213.203.238.82.53 > 82.197.162.59.19421:  53145_\- 1/0/0 SOA[|domain]

As you can see from the query IDs, B sent a query, A answered, but
B did not get this answer (it's UDP after all...). B sends another
request two seconds later, which A again answers; this time, the
answer arrives.

Nevertheless, B has written the above warning to the logs.

I would suggest that it did not write this warning until 2-3 retries
have failed. As it stands, I got the warning but the retrieve/refresh did actually work.

**Comment by pieterlexis** [comment]
I did a quick test and it appears that we do not log this error anymore when a domain times out, we report "Feb 20 22:02:37 Received serial number updates for 0 zones, had 1 timeout"
