### ISSUE TITLE
dnsdist: Allow configuration of timeout for UDP requests

### ISSUE THREAD

**Issue by o1bbridges** [PowerDNS/pdns#4700]
### Short description
We need an option to configure the UDP response timeout when waiting for requests from the back end servers.

### Usecase
We use dnsdist as a load balancer for ENUM requests and some of those can take more than 2 seconds.  We need the ability to configured the UDP timeout to allow for longer request processing.

### Description
Allow longer UDP timeouts.

**Comment by rgacogne** [comment]
Implemented in #4702.
