### ISSUE TITLE
"No SOA found" error when trying to create a (regular) record with API

### ISSUE THREAD

**Issue by hekmon** [PowerDNS/pdns#4705]
- Program: Authoritative
- Issue type: Bug report

### Short description
The title is actually not 100% accurate. The bug only occurs if you try to delete the SOA (which fails) and then try to create a record. The bug is also persistent : even if you drop the zone and recreate it, creating a record still won’t work, the SOA error message will pop in `{"error": "No SOA found for domain 'domain.net.'"}`. Funny thing is : it only last for 60s. If you try again after 60s, it works.

### Environment
 - Operating system: Debian Jessie
 - Software version: v4.0.1
 - Software source: `deb http://repo.powerdns.com/debian  jessie-auth-40 main`
 - Backend : MySQL or SQLite

### Steps to reproduce
1. Create a zone 
2. Create a test record (this one should work)
3. Try to delete the SOA (will fail as expected)
4. Create a test record (this one will never work)

Repeat the step [4]:
* before 60s have elapsed => does not work
* after 60s have elapsed => work as expected

### Expected behaviour
The record should be created without the SOA error message.

### Actual behaviour
Trying to delete the SOA will prevent further attempt to register or modify (REPLACE rrset) a new record during the next 59 seconds even if the zone is dropped and respawned.

### Other information
Deleting the SOA is not something anybody would want : we actually not encountered the bug in production but with our unit tests. It was not easy to isolate and reproduce it but once done, we wrote a small bash script reproducing this issue. It is available here :
https://gist.github.com/Hekmon/6f3be24dff4d33306818b3e421e9aec7

**Comment by zeha** [comment]
Thanks for the detailed bug report.

I've quickly tried to reproduce this with current git master, but it appears to work here.
Can you try with the packages available from https://repo.powerdns.com/debian/dists/jessie-auth-master/ ?
(Note that they will have a version number lower than 4.0.)

**Comment by zeha** [comment]
Don't bother, I've reran the test a few times and now get the error.

**Comment by dachinat** [comment]
Any solutions yet?

**Comment by Habbie** [comment]
We've had some caching improvements around the API, can you please check with 4.3.0-alpha1 or master?

**Comment by Habbie** [comment]
ping

**Comment by hekmon** [comment]
I have re run the old script in the first post which used to trigger the bug but it seems the issue is not here anymore, closing the issue :)
