### ISSUE TITLE
b2b-migrate inexistent in PDNS 3.4.10

### ISSUE THREAD

**Issue by finferflu** [PowerDNS/pdns#4706]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

The documentation [here](https://doc.powerdns.com/3/authoritative/migration/#migrating-from-backend-to-another) states that the following syntax should be used in order to migrate from one backend to another: 

```pdnssec b2b-migrate old new```

However, when I try to run that command, I get the following output:

```Unknown command 'b2b-migrate'```

Upon further inspection, it seems like there is no mention to `b2b-migrate` in the source code.

### Environment

 - Operating system: CentOS 7
 - Software version: 3.4.10
 - Software source: EPEL repository 

### Steps to reproduce

1. Run `pdnssec b2b-migrate old new` (using the appropriate configuration prefixes in place of `old` and `new`);
2. get `Unknown command 'b2b-migrate'`.

### Expected behaviour
The source backend should be migrated to the target backend.

### Actual behaviour

```Unknown command 'b2b-migrate'```

### Other information

Upon further inspection, it seems like there is no mention to `b2b-migrate` in the source code.

**Comment by pieterlexis** [comment]
Ah, this is 4.0.0 and up, I'll amend the documentation. Sorry for the inconvience.

**Comment by finferflu** [comment]
Thanks for clearing that up!
