### ISSUE TITLE
Unable to log to syslog on v4.0.1 Authoritative

### ISSUE THREAD

**Issue by mikalsande** [PowerDNS/pdns#4713]
With the default pdns.service file in PowerDNS Authoritative v4.0.1 on Red Hat Enterprise Linux 7.3 I am unable to get PowerDNS to log to syslog. PowerDNS is started with the following in the systemd unit file.
`ExecStart=/usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --write-pid=no`
Because the `--disable-syslog` option is given on the commandline to the pdns_server program I cannot override the setting in pdns.conf. This keeps me from getting PowerDNS logs through syslog, which works very well at PowerDNS Authoritative v3.4.10.

How are we supposed to get PowerDNS to log? Is syslog no longer supported? Is there an option for logging to a file? How can I get at the PowerDNS logs?

**Comment by rgacogne** [comment]
If you want to log via `syslog`, I would advise providing a replacement unit file without `--disable-syslog` using `systemctl edit --full pdns`. `--disable-syslog` is enabled by default to prevent duplicate logging with `systemd`'s journal.

**Comment by mikalsande** [comment]
Thank you, then at least there is a workable, albeit intrusive, workaround. Is this the officially recommended way to get PowerDNS Authoritative v4 to do syslog? If it is, can it be documented so that other do not have to file an issue?

As a sidenote, I do find it unconventional that the upstream distribution of PowerDNS disables syslog in the init file and the only way to get around it is actually editing the init file. From my point of view it is expected that the default init file does not override configuration options, or at least allows the daemon configuration file to set the desired configuration and behavior.

**Comment by pieterlexis** [comment]
Using an override service file or editing the service file is indeed the recommended (systemd) way.

> As a sidenote, I do find it unconventional that the upstream distribution of PowerDNS disables syslog in the init file and the only way to get around it is actually editing the init file. From my point of view it is expected that the default init file does not override configuration options, or at least allows the daemon configuration file to set the desired configuration and behavior.

We set several settings in the unit-file that give the best experience to most users and so they cannot by accident be overwritten using the config file (commandline options win), like `daemon` and `disable-syslog`
