### ISSUE TITLE
Please include SRPMs in the repos

### ISSUE THREAD

**Issue by seitzbg** [PowerDNS/pdns#4714]
PowerDNS Repos lack SRPMs

### Short description
Please include source RPMs in a path such as: https://repo.powerdns.com/centos/SRPMS

### Usecase
I would like to rebuild powerdns/dnsdist for Fedora Server.

**Comment by pieterlexis** [comment]
Because we use the pdns_builder, we use several environment variables so the SRPMs are not re-buildable
