### ISSUE TITLE
Allow the packet cache to handle queries with multiple questions.

### ISSUE THREAD

**Issue by HoussamElHajoui** [PowerDNS/pdns#4732]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Feature request 

### Short description

It seems like every part of the program correctly handles queries with multiple questions by only choosing the last one. on the other hand, the packet cache doesn't, but chooses to drop such packets, why is that? Adopting such behavior, makes the packet cache the only part inconsistent with others, and also lowers the rate of cache hits.

**Comment by ahupowerdns** [comment]
Packets with multiple questions have been deprecated and no one uses them. If we offer any support for such packets it is a bug. http://maradns.samiam.org/multiple.qdcount.html has some relevant links.

Do you have specific usecase, something that should work? In that case please open another ticket for that usecase.

**Comment by HoussamElHajoui** [comment]
Maybe I didn't use the correct title for this issue. I mean by 'allow multiple questions', to not drop such queries, but like other parts of the program, only handle the last question instead of dropping the packet.

**Comment by Habbie** [comment]
If any part of PowerDNS handles the last question out of multiple, *that* is a bug. Queries with QDCOUNT!=1 should be rejected everywhere.

**Comment by HoussamElHajoui** [comment]
check this out [MOADNSParser::init](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsparser.cc#L241).

**Comment by Habbie** [comment]
Ah, interesting. Sadly the commit history does not say why we do this. @ahupowerdns you wrote that for-loop in ff6a1e7b314bc0763ae61dd45547559c2369eb60 - 11 years ago. Any idea why?

**Comment by ahupowerdns** [comment]
I probably thought it was fine if the packet parser did at least allow us to parse such packets.

However, this might allow people to 'hide' the actual question in some
cases, so we should probably just error out on it directly.

Will PR that up.

**Comment by zeha** [comment]
Reopening this so it doesn't get lost.

**Comment by rgacogne** [comment]
Queries with multiple questions are now dropped by the auth and rec (since 27c0050c6a0b07587b924309299ca2f134c1315f)
