### ISSUE TITLE
dnsdist: Client mode (-c) should not read Lua from configuration file

### ISSUE THREAD

**Issue by madpsy** [PowerDNS/pdns#4741]
When running 'dnsdist -c', by default it reads the same configuration file as the server itself. If the configuration file contains any Lua, client mode fails. Error is:

> Fatal error: Exception thrown by a callback function called by Lua

You can test by adding something like this to dnsdist.conf and then running 'dnsdist -c'.

```
bpf = newBPFFilter(1024, 1024, 1024)
setDefaultBPFFilter(bpf)
dbpf = newDynBPFFilter(bpf)
function maintenance()
        addBPFFilterDynBlocks(exceedQRate(20, 10), dbpf, 60)
        dbpf:purgeExpired()
end
```

In client mode, any Lua in the configration file should be ignored.

**Comment by rgacogne** [comment]
Well, we don't want to ignore every Lua code, but we need to ignore some directive in client mode. Clearly we don't currently ignore `newBPFFilter()` and `newDynBPFFilter()` and we should.
