### ISSUE TITLE
API returns TTL of zero if RRset has a comment

### ISSUE THREAD

**Issue by thomasp-opera** [PowerDNS/pdns#4766]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When performing a GET request to `/api/v1/servers/:server_id/zones/:zone_id`, the TTL for an RRset is incorrectly returned as zero if the RRset has a comment.

### Environment
 - Operating system: Ubuntu 16.10
 - Software version: 4.0.1
 - Software source: PowerDNS repository (repo.powerdns.com)
 - Backend: gpgsql

### Steps to reproduce

1. Set up PowerDNS with gpgsql backend and enable the JSON API.
2. Create example zone that looks like the following:
`{"account": "public", "dnssec": false, "id": "example.com.", "kind": "Master", "last_check": 0, "masters": [], "name": "example.com.", "notified_serial": 2016121209, "rrsets": [{"comments": [], "name": "example.com.", "records": [{"content": "ns1.example.org. hostmaster.example.com. 2016121209 10800 3600 604800 3600", "disabled": false}], "ttl": 3600, "type": "SOA"}, {"comments": [], "name": "example.com.", "records": [{"content": "ns1.example.org.", "disabled": false}, {"content": "ns2.example.org.", "disabled": false}], "ttl": 3600, "type": "NS"}, {"comments": [], "name": "example.com.", "records": [{"content": "1.1.1.1", "disabled": false}], "ttl": 3600, "type": "A"}], "serial": 2016121209, "soa_edit": "INCEPTION-INCREMENT", "soa_edit_api": "INCEPTION-INCREMENT", "url": "api/v1/servers/localhost/zones/example.com."}`
3. Add a comment for eg. the A record (can add it via the API or directly into the database - result is the same).

### Expected behaviour
RRset TTL to be unaffected by addition of comment.

### Actual behaviour
API now returns TTL of 0 for the RRset:
`~$ curl -H 'X-API-Key: ********' http://localhost:8081/api/v1/servers/localhost/zones/example.com.`
`{"account": "public", "dnssec": false, "id": "example.com.", "kind": "Master", "last_check": 0, "masters": [], "name": "example.com.", "notified_serial": 2016121209, "rrsets": [{"comments": [], "name": "example.com.", "records": [{"content": "ns1.example.org. hostmaster.example.com. 2016121209 10800 3600 604800 3600", "disabled": false}], "ttl": 3600, "type": "SOA"}, {"comments": [], "name": "example.com.", "records": [{"content": "ns1.example.org.", "disabled": false}, {"content": "ns2.example.org.", "disabled": false}], "ttl": 3600, "type": "NS"}, {"comments": [{"account": "thomasp", "content": "Testing", "modified_at": 1481559172}], "name": "example.com.", "records": [{"content": "1.1.1.1", "disabled": false}], "ttl": 0, "type": "A"}], "serial": 2016121209, "soa_edit": "INCEPTION-INCREMENT", "soa_edit_api": "INCEPTION-INCREMENT", "url": "api/v1/servers/localhost/zones/example.com."}`

If you delete the comment then the TTL is returned correctly again.

**Comment by sburina** [comment]
Just noticed this too. Luckily, I've searched issues before opening a duplicate. :)
This seriously cripples the automation possibilities.. I hope it gets resolved soon.

**Comment by zeha** [comment]
Testing of PR #4781 would be appreciated.

**Comment by thomasp-opera** [comment]
Tested the patch myself and it does indeed seem to work correctly.
