### ISSUE TITLE
Limit QPS does not work as expected in Red Hat 7.

### ISSUE THREAD

**Issue by devilsmile86** [PowerDNS/pdns#4768]
Hi everyone,

I deployed dnsdist-1.1.0-0.1.beta1.1pdns.el7.x86_64.rpm. I used dnsdist via service and I got an issue with limit QPS in a newServer.

**Environment**
Operating system: Red Hat 7.3

Here is my dnsdist.conf:

```
setKey("kA3JUgAQ2ETE+uEeTWct3qqORr0BCSfIlSHTaYeVEOM=")
controlSocket("127.0.0.1")
setLocal('0.0.0.0')
newServer({address="192.168.10.20:5353", qps=10, order=1, checkName="test.com"})
newServer({address="192.168.10.30", qps=10, order=2, checkName="test.com"})
setServerPolicy(firstAvailable)
```

Result while I sent 1000 queries with command "for a in {0..1000}; do dig test.com @192.168.10.20 +noall > /dev/null; done":

```
> showServers()
#   Name     Address              State     Qps    Qlim Ord Wt    Queries   Drops Drate   Lat Outstanding Pools
0            192.168.10.20:5353      up    64.9      10   1  1        135       0   0.0   0.1           0
1            192.168.10.30:53          up    10.0      10   2  1         31       0   0.0   0.1           0
All                                                       73.0                       166       0
```

I set qps=10 but when it running, Qps increase to 64.9  and it does not reduce to 10. It also hapen with server 192.168.10.30 but it reduce Qps to 10 immediately.
If I set qps of 192.168.10.30 to 0, limit Qps seem not work.

```
> showServers()
#   Name      Address              State     Qps    Qlim Ord Wt    Queries   Drops Drate   Lat Outstanding pools
0              192.168.10.20:5353      up    62.9      10   1  1        693       0   0.0   0.1           0
1              192.168.10.30:53        up      0.0       0   2  1          0       0   0.0   0.0           0
All                                                         62.0                       693       0
```

I had tested with dnsdist 1.0 and got the same issue. Can anyone help me?

Thanks.

**Comment by ahupowerdns** [comment]
hi - firstAvailable will try the 'first' nameserver that is within its QPS limit. If all servers are over limit, it will start doing round robin over all servers. So this behaviour you observe is by design. firstAvailable will not drop traffic for you. If you need that, us a rule for QPS limiting.

**Comment by devilsmile86** [comment]
Thanks for your explains. I'm understand now. I think set QPS to 0 will make it become unlimited, but it means 0 QPS . Do we have a command for reset QPS to default (unlimited)?

And I still have a confuse with firstAvailable policy. Can you help me also?
I still keep these config, when dnsdist running, I change order of  192.168.10.20 to 3 by command "getServer(0).order=3". It will greater than order of 192.168.10.30 is 2. In case I send one by one query it still get result from server(0). If I send 1000 queries, almost queries will go to server have order smaller (192.168.10.30) . Two dns server have the same QPS.
I don't understand here. Does it also the design of firstAvailable ?

**Comment by rgacogne** [comment]
It looks like the description of `firstAvailable` in our documentation is not correct, sorry about that. #4784 fixes that.

**Comment by devilsmile86** [comment]
Thank you.
