### ISSUE TITLE
Supermasters' operation clarification

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#479]
oracle backend documentation states:

"A supernotification will be accepted if an entry is found such that the notification came from ip and nameserver appears in an NS record for that zone."

For somebody configuring automatic provisioning of slaves for the first time, it is unclear whether the above paragraph refers to the supermaster or superslave.

The documentation should explicitly state whether this entry is to be found in the superslave's or supermaster's "supemasters" table.

**Comment by pieterlexis** [comment]
@Habbie The [docs](http://doc.powerdns.com/md/authoritative/backend-oracle/#the-supermasters-table) state that this documentation is relevant only to superslaves. Or is this ticket more about a clarification fro the the concept of supermasters and superslaves in general?

**Comment by pieterlexis** [comment]
both superslave operation in general and how this is implemented per backend is documented at the moment.
