### ISSUE TITLE
unknown command status

### ISSUE THREAD

**Issue by yolleksandr** [PowerDNS/pdns#4811]
Hello.

[root@dnsmanager5 ~]# uname -ro
3.10.0-327.36.3.el7.x86_64 GNU/Linux
[root@dnsmanager5 ~]# pdns_control version
3.4.10
[root@dnsmanager5 ~]# pdns_control status
Unknown command: 'STATUS'

Why?

**Comment by pieterlexis** [comment]
["status : Show usage statistics. This only works if the server is running in guardian mode."](https://doc.powerdns.com/md/manpages/pdns_control.1/). On systemd OS's (like EL 7), the guardian is not used.
