### ISSUE TITLE
ldap-host parameter missing in the online documentation

### ISSUE THREAD

**Issue by tvendelin** [PowerDNS/pdns#4819]
- Program: Authoritative, LDAP backend online documentation
 - Issue type: Bug report

### Short description
It seems there should exist `ldap-host` configuration parameter for LDAP backend, but it is not mentioned at https://doc.powerdns.com/md/authoritative/backend-ldap/#installation

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by Habbie** [comment]
It is there but it is wrongly formatted, and thus easy to miss. Thanks for the report!
