### ISSUE TITLE
dnsdist configure on powerpc fails without clear reason when libatomic is not available

### ISSUE THREAD

**Issue by tjikkun** [PowerDNS/pdns#4825]
I tried to build dnsdist for ppc64 but didn't have libatomic installed. configure failed with:
checking for the Boost unit_test_framework library... no
configure: error: Boost Unit Test library not found

But the actual reason was that libatomic was not available.

**Comment by rgacogne** [comment]
Do you know if we actually need libatomic to build on ppc64? If we do, I think we should explicitly check whether it's available to be able to provide a clear explanation in case it isn't.

**Comment by tjikkun** [comment]
dnsdist builds fine on ppc64 without libatomic
