### ISSUE TITLE
`pdns_control list-zones` incorrectly prepends "./" to 'socket-dir'

### ISSUE THREAD

**Issue by pgnd** [PowerDNS/pdns#4834]
In pdns v4

    dig chaos txt version.bind @127.0.0.1 -p 15301 +short
        "PowerDNS Authoritative Server 4.0.1-264-g50e4ab3 (built Dec 30 2016 20:47:29 by adm@dns.example.net)"

attempting to get a list of zones

    /usr/local/pdns/bin/pdns_control \
     --config-dir=/usr/local/etc/pdns list-zones

returns

    Fatal error: Unable to connect to remote './var/pdns/pdns.controlsocket': No such file or directory

It's not

    './var/pdns/pdns.controlsocket'

but

    /var/pdns/pdns.controlsocket

i.e., *no* leading period ...

    egrep "chroot|sock" /usr/local/etc/pdns/pdns.conf
        socket-dir=/var/pdns
        chroot=./
    ls -al /var/pdns/pdns.controlsocket
        srw-rw---- 1 root pdns 0 Dec 31 20:53 /var/pdns/pdns.controlsocket=

as is, with the prepended ".",

	cd /
    /usr/local/pdns/bin/pdns_control \
     --config-dir=/usr/local/etc/pdns list-zones
		All zonecount:0

**Comment by Habbie** [comment]
Why do you have `chroot=./`? What is it supposed to mean?

**Comment by Habbie** [comment]
Ah, #4843. Closing this one!
