### ISSUE TITLE
dnsdist: improve docs

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4835]
- Program: dnsdist
 - Issue type: documentation improvements

### Short description
https://www.cryptobells.com/load-balanced-dns-with-dnsdist/ points out several ways in which our documentation falls short. We should improve on this.

**Comment by cmouse** [comment]
version: dnsdist-1.1.0-1pdns.xenial

After installing package, there is no instructions on how to configure the service, or no default or example config file provided. man page does not explain how to configure or where the configuration file is.

Some options:
-----------------
- Provide default or example config file in /etc/dnsdist
- Generate default config file on install if missing, with setKey and controlSocket filled in.
- Improve man page to explain how to do quick configuration

**Comment by p0pr0ck5** [comment]
A few thoughts, of some which I addressed in my blog post, others that I think could use some clarification:

* The return type of `exceed*` functions is fairly ambiguous. Documenting the form of the table would be useful.
* The nature of `maintenance()` is slightly unclear. Docs indicate this is called once a second, but the underling mechanism is unknown. Does this fire every second unconditionally, or one second after the end of the previous execution of `maintenance()`? Knowing how this behaves could help inform decisions on recurring behavior that takes several hundred milliseconds to execute (e.g. could we potentially have a backlog and many functions executing simultaneously, or could the start time of the function be delayed by more than one second).
* `expungeByName` does not appear to function like the authoritative `pdns_control purge` command, in which a name can have an appended `$` char to purge all entries for that zone, including sub-domains. Clarification here for those expecting this behavior to be identical would be nice.
* Document that `newPacketCache` appears to allocate all of its required memory at once, and document a rough idea (or a way to calculate) how much memory a given `pc` will require.

**Comment by rgacogne** [comment]
Thank you all for the comments!

> * Provide default or example config file in /etc/dnsdist

Agreed, perhaps we could ship dnsdistconf.lua as `${SYSCONFDIR}/dnsdist.conf.sample`?

> * Generate default config file on install if missing, with setKey and controlSocket filled in.

I'm not very comfortable with that idea. Since the console gives the possibility to execute Lua code as the `dnsdist` user, it makes sense to me to require an explicit action from the administrator to enable it.

> * Improve man page to explain how to do quick configuration

Agreed, perhaps we could reuse parts of http://dnsdist.org/introduction/ ?

> * The return type of `exceed*` functions is fairly ambiguous. Documenting the form of the table would be useful

Documented in #4856. Note that the `ComboAddress` and `NetmaskGroup` objects are documented in the README, so you shouldn't need to refer to the recursor's docs. You also mention 

> match(str) – true if the address passed in str matches

from the recursor docs, but that refers to a `Netmask` object, not a `NetmaskGroup`. The documentation of `NetmaskGroup` in the README correctly states:

> member `match(ComboAddress)`: checks if ComboAddress is matched by this NetmaskGroup

> * The nature of `maintenance()` is slightly unclear.

Agreed, I tried to clarify that in #4856.

> * `expungeByName` does not appear to function like the authoritative pdns_control purge command, which a name can have an appended $ char to purge all entries for that zone, including sub-domains. Clarification here for those expecting this behavior to be identical would be nice.

Indeed, but I'm not sure we want to list the differences between the recursor and the dnsdist's caches. Wouldn't that be more confusing than anything else?

> * Document that `newPacketCache` appears to allocate all of its required memory at once, and document a rough idea (or a way to calculate) how much memory a given `pc` will require.

That's not exactly the case, I tried to explain how it works in #4856.

**Comment by rgacogne** [comment]
> > * Generate default config file on install if missing, with setKey and controlSocket filled in.

> I'm not very comfortable with that idea. Since the console gives the possibility to execute Lua code as the dnsdist user, it makes sense to me to require an explicit action from the administrator to enable it.

After discussing it with @neilcook, we could enable the console by default provided we restrict access to 127.0.0.1 and ::1, and generate a random key at installation time. We would have to make sure that the resulting configuration file is only readable by the `dnsdist` user to prevent local privilege escalation.

**Comment by cmouse** [comment]
> 

> > Provide default or example config file in /etc/dnsdist
> Agreed, perhaps we could ship dnsdistconf.lua as ${SYSCONFDIR}/dnsdist.conf.sample?

Yes.

**Comment by zeha** [comment]
> We would have to make sure that the resulting configuration file is only readable by the dnsdist user to prevent local privilege escalation.

This part is a good idea anyway :)

**Comment by rgacogne** [comment]
It looks like the last parts have finally been addressed in https://github.com/PowerDNS/pdns/pull/12481, so I'm closing this issue.
