### ISSUE TITLE
chroot=./ is an invalid setting but not detected

### ISSUE THREAD

**Issue by pool0022** [PowerDNS/pdns#4843]
I've installed & launched pdns v4.0.1

    systemctl restart pdns
    tail -f pdns.log
        ...
        Jan  2 11:13:41 dns pdns[9606]: No master domains need notifications
        Jan  2 11:13:41 dns pdns[9606]: About to create 3 backend threads for UDP
        Jan  2 11:13:42 dns pdns[9606]: Done launching threads, ready to distribute questions

    dig chaos txt version.bind @10.1.1.53 -p 15301 +short
        "PowerDNS Authoritative Server 4.0.1-264-g50e4ab3 (built Jan  2 2017 11:06:37 by adm@dns.example.net)"

The db exists

    ls -al /var/pdns/powerdns.sqlite3
        -rw-r--r-- 1 pdns pdns 100K Jan  2 10:29 /var/pdns/powerdns.sqlite3

and is accessible, functional,

    sqlite3 /var/pdns/powerdns.sqlite3
    sqlite> select * from supermasters;
        10.1.1.53|dnsext.example.net|admin
    sqlite> select * from domains;
    1|example.com|10.1.1.53|1483381740|SLAVE|1482864727|admin
    sqlite> .exit

pdnsutil reports version

    pdnsutil --version
        pdnsutil 4.0.1-264-g50e4ab3

but fails on any db-related commands, e.g.

    pdnsutil list-all-zones
        Jan 02 11:22:40 Reading random entropy from '/dev/urandom'
        Jan 02 11:22:40 gsqlite3: connection failed: SQLite database '/var/pdns/powerdns.sqlite3' does not exist yet
        Jan 02 11:22:40 Caught an exception instantiating a backend: Unable to launch gsqlite3 connection: SQLite database '/var/pdns/powerdns.sqlite3' does not exist yet
        Jan 02 11:22:40 Cleaning up
        Error: Unable to launch gsqlite3 connection: SQLite database '/var/pdns/powerdns.sqlite3' does not exist yet

as above, the db *does* exist

**Comment by cmouse** [comment]
Are you using chroot?

**Comment by pgnd** [comment]
@cmouse 
> Are you using chroot?

Yes.  Specified in pdns.conf, which -- iiuc -- pdnsutil should be picking up correctly.

**Comment by cmouse** [comment]
Ok. So the real bug here is that pdnsutil does not understand chroots correctly. You can probably workaround this issue by doing
```
mkdir /var/pdns
mount --bind /path/to/chroot/var/pdns /var/pdns
```

**Comment by zeha** [comment]
systemd + chroot is a bad idea, you'll run into other issues (i.e. socket not found etc).

**Comment by pgnd** [comment]
@cmouse 
@zeha

> mkdir /var/pdns
> mount --bind /path/to/chroot/var/pdns /var/pdns

On my system

    ...
    socket-dir=/var/pdns
    chroot=./
    ...

> systemd + chroot is a bad idea, you'll run into other issues (i.e. socket not found etc).

There's no fundamental problem with systemd + chroot whatsoever.

What's simply required is that the chroot is properly instantiated, and that tools are chroot-aware&capable.

E.g., I've run systemd-managed bind9 in a chroot for years, without the slightest problem.

Even here on pdns, running pdns has no problems.  Well, at least none that are reported in logs (yet).  The tools, apparently, may be a different issue ...

Rather than a workaround, this should either be fixed, or chroot(ing) disabled.

**Comment by zeha** [comment]
I've made #4848 about the general issues under systemd, and this specific issue is probably just that "chroot=./" is completely invalid (needs to be full path really).

**Comment by pgnd** [comment]
> "chroot=./" is completely invalid 

If that's the case, then the docs should be changed accordingly; currently @

    "Security Settings"
    https://doc.powerdns.com/md/common/security/#security-settings

        "The default PowerDNS configuration is best chrooted to ./, which boils down to the
         configured location of the controlsocket.  This is achieved by adding the following to
         pdns.conf: chroot=./, and restarting PowerDNS."
