### ISSUE TITLE
DNSdist missing documentation

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#4844]
version: dnsdist-1.1.0-1pdns.xenial

After installing package, there is no instructions on how to configure the service, or no default or example config file provided. man page does not explain how to configure or where the configuration file is.

Some options:
 - Provide default or example config file in /etc/dnsdist
 - Generate default config file on install if missing, with setKey and controlSocket filled in.
 - Improve man page to explain how to do quick configuration

**Comment by Habbie** [comment]
Want to move this to #4835?

**Comment by Habbie** [comment]
Thanks!
