### ISSUE TITLE
chroot option + systemd do not coexist well

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#4848]
There are various issues when running pdns with chroot= set under systemd.

IIRC:

  * notification to systemd fails because the systemd socket is unreachable
  * pdns_control has (with some specific settings) trouble talking to the daemon

Personally, I'd think refusing to start under systemd with chroot set would be good.

**Comment by pieterlexis** [comment]
note:

Should be easy to detect, systemd creates the `NOTIFY_SOCKET` environment variable, we can refuse to start if it is present and `chroot=` is in the config
