### ISSUE TITLE
Please ship all tarballs with a similar layout as git

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#4849]
Right now the pdns tarball looks different than the dnsdist and pdns-recursor tarballs, and they do not mirror the layout in git.

This is painful for at least these:

  * applying/editing patches from git to tarballs
  * maintaining copyright notices (e.g. in debian/copyright)

**Comment by omoerbeek** [comment]
This is not happening soon. Maybe when we change to a different build system...
