### ISSUE TITLE
DNSdist using connected sockets for health check is problematic in dynamic networking environment

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#4853]
- Program: dnsdist
 - Issue type: Bug report

### Short description

Under certain situations, server in DNSdist can be come irrevocably stuck, showing all queries dropped, while the server itself is up:
```
#   Name                 Address                       State     Qps    Qlim Ord Wt    Queries   Drops Drate   Lat Outstanding Pools
0                        194.100.0.100:53                 up     0.0       0   1  1         24       1   0.0  12.7           0 
1                        10.217.1.5:53                    UP     0.0       0   1  1         34      34   0.0   0.0           0 vpn
```

- Operating system: Ubuntu 16.04
 - Software version:  dnsdist-1.1.0-1pdns.xenial
 - Software source: PowerDNS repository

(these are not confirmed steps, because it's damn hard to make it stuck intentionally)
1. Make sure the server gets a request in before health check is done (preferably should fail)
2. Observe temporary failure from dig
3. Now if everything went "right" you have server that is UP but drops all requests for some reason.

I am not 100% sure why this happens, or what is the difference between `up` and `UP`. 

The only way to recover is to restart dnsdist service.

**Comment by cmouse** [comment]
After doing further research with @rgacogne it turns out the problem is source address selection going wrong after VPN connection is brought up. It uses wrong source IP for the queries.

**Comment by cmouse** [comment]
Maybe one solution would be to reopen the socket(s) for the target server on state change from down->up?

**Comment by Habbie** [comment]
> I am not 100% sure why this happens, or what is the difference between `up` and `UP`.

Note that 'UP' means that you told dnsdist to not do health checks for that backend at all.

**Comment by rgacogne** [comment]
I'm closing this for now, please let me know if you encounter the issue which means that the fix was not enough.
