### ISSUE TITLE
Error in carbon thread: Unable to convert presentation address

### ISSUE THREAD

**Issue by grinapo** [PowerDNS/pdns#4867]
- Program: Recursor
 - Issue type: Bug report

### Short description

pdns_recursor[22769]: Error in carbon thread: Unable to convert presentation address 'hostname.sub.example.com'

The host have ipv4 (10.11.12.13) and ipv6 (public) address. The config only contain the hostname, no port.

### Environment
 - Operating system: Debian/stable
 - Software version:    4.0.3-1pdns.jessie   
 - Software source: PowerDNS repository

**Comment by Habbie** [comment]
The carbon address needs to be a literal IP (v4 or v6) with an optional port. Host names are not supported, sorry!

**Comment by grinapo** [comment]
The provided example config should mention that.

**Comment by Habbie** [comment]
Agreed - feel like submitting a patch?

**Comment by grinapo** [comment]
Sir, yes SIR.

**Comment by Habbie** [comment]
🥇
