### ISSUE TITLE
PDNS (2.9.19) doesnt delegate subdomains correct

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#49]
Version PDNDS 2.9.19 (C) 2001-2005 PowerDNS.COM BV (Oct 29 2005, 18:48:34, gcc 4.0.2)

when delegating a subdomain of a domain like:
 test.example.com where PDNS is authoritative for example.com 

the example.com. Zone holds following Entrys for the subdomain delegation (Bind Backend)
  test.example.com. IN NS another.dnsserver.

PDNS doesnt delegate records within the subdomain SOA 'test.example.com' to the correct Nameserver. Putting an MX Record on 'another.dnsserver.' doesnt get resolved.
Only way to archive this is when putting the Record in the example.com. Domain File on the PDNS.

is this a bug ? will it be solved in the future ?

Kind regards
Michael Lang

**Comment by wdoekes** [comment]
@Habbie: you have some spam messages in here..

**Comment by Habbie** [comment]
Removed, thanks!
