### ISSUE TITLE
bind backend missing

### ISSUE THREAD

**Issue by sysadmin75** [PowerDNS/pdns#4902]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Bind backend is missing from 4.0.

### Environment
 - Operating system: CentOS release 6.8 (Final)
 - Software version: pdns-4.0.2-1pdns.el6.x86_64
 - Software source: powerdns-auth-40.repo

### Steps to reproduce
1. yum install epel-release yum-plugin-priorities
2. curl -o /etc/yum.repos.d/powerdns-auth-40.repo https://repo.powerdns.com/repo-files/centos-auth-40.repo
3. yum install pdns
4. /etc/init.d/pdns start
5. $ tail /var/log/messages 
Jan 13 08:55:17 pdnstest pdns[9127]: Loading '/usr/lib64/pdns/libbindbackend.so'
Jan 13 08:55:17 pdnstest pdns[9127]: Unable to load module '/usr/lib64/pdns/libbindbackend.so': /usr/lib64/pdns/libbindbackend.so: cannot open shared object file: No such file or directory
Jan 13 08:55:17 pdnstest pdns[9127]: DNSBackend unable to load module in bind
Jan 13 08:55:18 pdnstest pdns[9123]: Our pdns instance exited with code 1, respawning

### Expected behaviour
Bind backend should be part of the main package or have it's own backend package.

### Actual behaviour
Bind is missing from the main package. (See tail message above).

And bind backend is missing from repo.
 $ yum search pdns
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: ftpmirror.your.org
 * epel: fedora.mirrors.pair.com
 * extras: ftpmirror.your.org
 * updates: ftpmirror.your.org
9 packages excluded due to repository priority protections
================================================================================================ N/S Matched: pdns ================================================================================================
pdns-backend-geo.x86_64 : Geo backend for pdns
pdns-backend-ldap.x86_64 : LDAP backend for pdns
pdns-backend-lua.x86_64 : Lua backend for pdns
pdns-backend-mydns.x86_64 : MyDNS backend for pdns
pdns-backend-mysql.x86_64 : MySQL backend for pdns
pdns-backend-pipe.x86_64 : Pipe backend for pdns
pdns-backend-postgresql.x86_64 : PostgreSQL backend for pdns
pdns-backend-remote.x86_64 : Remote backend for pdns
pdns-backend-sqlite.x86_64 : SQLite backend for pdns
pdns-tools.x86_64 : Extra tools for pdns
fpdns.noarch : Fingerprint DNS servers
pcp-pmda-pdns.x86_64 : Performance Co-Pilot (PCP) metrics for PowerDNS
pdns.x86_64 : A modern, advanced and high performance authoritative-only nameserver
pdns-recursor.x86_64 : Modern, advanced and high performance recursing/non authoritative name server

**Comment by pieterlexis** [comment]
@sysadmin75, We have updated the CentOS 6 repo on repo.powerdns.com with the `4.0.2-2pdns.el6` packages containing the BIND backen
