### ISSUE TITLE
query-local-address(6) validation

### ISSUE THREAD

**Issue by annttu** [PowerDNS/pdns#4914]
- Program: Authoritative, Recursor 
 - Issue type: Bug report 

### Short description

PowerDNS server don't validate query-local-address is an IPv4 address. If a valid IPv6 address is configured to query-local-address, PowerDNS tries to use it (with INET6 socket) to connect to IPv4 addresses causing "No route to host" errors to log.

### Environment

 - Operating system: Centos 7
 - Software version: 4.0.2
 - Software source: PowerDNS repository

### Steps to reproduce

1. Configure a valid IPv6 address to query-local-address and restart powerdns server 
2. Receive NOTIFY or try to use as recursor 
3. See log file for error 

### Expected behaviour

PowerDNS should throw an error on boot if non IPv4 address is configured to query-local-address and if non ipv6 address is configured to query-local-address6.

### Actual behaviour

```
[pid  5670] socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 25
[pid  5670] fcntl(25, F_GETFD)          = 0
[pid  5670] fcntl(25, F_SETFD, FD_CLOEXEC) = 0
[pid  5670] bind(25, {sa_family=AF_INET6, sin6_port=htons(10998), inet_pton(AF_INET6, "a:b:c::d", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
[pid  5670] socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 26
[pid  5670] fcntl(26, F_GETFD)          = 0
[pid  5670] fcntl(26, F_SETFD, FD_CLOEXEC) = 0
[pid  5670] bind(26, {sa_family=AF_INET, sin_port=htons(14409), sin_addr=inet_addr("1.2.3.4")}, 16) = 0
[pid  5670] sendto(25, "redactedredacted"..., 37, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("1.2.3.4")}, 16) = -1 ENETUNREACH (Network is unreachable)
```

**Comment by omoerbeek** [comment]
Wiith the unification of `query-local-address` no longer relevant
