### ISSUE TITLE
pdns check fails to build on armv7hl

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#4919]
Affected version: pdns auth 4.0.2

Overall it's building fine, but building the check (make -j4 -C pdns check) fails only on armv7hl.

g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I.. -pthread  -I../ext/json11 -I../ext/yahttp         -DLDAP_DEPRECATED -DSYSCONFDIR=\"/etc/pdns\" -DPKGLIBDIR=\"/usr/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -c -o test-statbag_cc.o test-statbag_cc.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I.. -pthread  -I../ext/json11 -I../ext/yahttp         -DLDAP_DEPRECATED -DSYSCONFDIR=\"/etc/pdns\" -DPKGLIBDIR=\"/usr/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -c -o test-zoneparser_tng_cc.o test-zoneparser_tng_cc.cc
In file included from /usr/include/boost/test/test_tools.hpp:45:0,
                 from /usr/include/boost/test/unit_test.hpp:18,
                 from test-statbag_cc.cc:7:
test-statbag_cc.cc: In member function 'void misc_hh::test_StatBagBasic::test_method()':
test-statbag_cc.cc:97:30: error: 'native_t' is not a member of 'AtomicCounter {aka std::atomic<long unsigned int>}'
     BOOST_CHECK_EQUAL(sizeof(AtomicCounter::native_t), 4);
                              ^
Makefile:2529: recipe for target 'test-statbag_cc.o' failed
make[3]: *** [test-statbag_cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/boost/iostreams/detail/is_dereferenceable.hpp:12:0,
                 from /usr/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/include/boost/iostreams/stream.hpp:21,
                 from test-zoneparser_tng_cc.cc:10:
/usr/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: #pragma message: NOTE: Use of this header (bool_trait_def.hpp) is deprecated
 # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
                                                                               ^
In file included from /usr/include/boost/type_traits/detail/bool_trait_def.hpp:21:0,
                 from /usr/include/boost/iostreams/detail/is_dereferenceable.hpp:12,
                 from /usr/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/include/boost/iostreams/stream.hpp:21,
                 from test-zoneparser_tng_cc.cc:10:
/usr/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
In file included from /usr/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/include/boost/iostreams/stream.hpp:21,
                 from test-zoneparser_tng_cc.cc:10:
/usr/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
make[3]: Leaving directory '/builddir/build/BUILD/pdns-4.0.2/pdns'
Makefile:2774: recipe for target 'check-TESTS' failed
make[2]: Leaving directory '/builddir/build/BUILD/pdns-4.0.2/pdns'
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
Makefile:2848: recipe for target 'check-am' failed
make[1]: Leaving directory '/builddir/build/BUILD/pdns-4.0.2/pdns'
Makefile:2850: recipe for target 'check' failed
make: Leaving directory '/builddir/build/BUILD/pdns-4.0.2/pdns'
make: *** [check] Error 2

Full buildlog:
https://kojipkgs.fedoraproject.org//work/tasks/6454/17306454/build.log

Should we temporary disable pdns check for armv7hl or could you provide a patch for us?

**Comment by rgacogne** [comment]
I think this is fixed by #4901.

**Comment by rgacogne** [comment]
You might also need #4911.

**Comment by mortenstevens** [comment]
Thank you. I'll check these two patches. But this is not a part of the latest 4.0.3 release (a few minutes ago)?

**Comment by rgacogne** [comment]
No, 4.0.3 was released quickly to fix a functional regression introduced in 4.0.2 and as these two patches only fixed issues in the unit tests and didn't received sufficient testing, they were not included in the release.

**Comment by mortenstevens** [comment]
Thank you. It's building fine after including your patches.
Here is our downstream commit for Fedora: https://src.fedoraproject.org/cgit/rpms/pdns.git/commit/?id=b7aee0704744adf8d22a183c0642e67de0faaca1

And here are the full buildlogs for rawhide:
https://koji.fedoraproject.org/koji/buildinfo?buildID=834387

**Comment by pieterlexis** [comment]
Fixed after merging #4901 and #4911, will be backported
