### ISSUE TITLE
upgrade instruction from 3.4 to 4.0 misses CAA incompatibility

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#4923]
https://doc.powerdns.com/md/authoritative/upgrading/ does not mention that the CAA record replaced the legacy MBOXFW record. Thus, when using an SQL backend with 3.4, the CAA records are stored in the DB with type=MBOXFW (e.g. if PDNS is a SLAVE). After upgrading, fetching the CAA records (which does work fine with 3.4) does not work anymore, as 4.0 searches for CAA, not for MBOXFW.

a) it should be mentioned that zones which use CAA must be retransfered or the type must be changed manually
b) are there other legacy records supported in PDNS? if yes, they should be removed and replaced with a generic type, e.g. type=TYPE257

**Comment by klaus3000** [comment]
I forgot to mention if in PDNS other records were removed/replaced too, that should be mentiond also at the upgrade instructions

**Comment by klaus3000** [comment]
my findings which may cause incompatibilities when upgrading without changing the records in DB:
TYPE256: URL was replaced with URI
TYPE257: MBOXFW was replaced with CAA
TYPE258: CURL was removed
TYPE259: ADDR was removed

TYPE65400: ADDR was added
TYPE65401: ALIAS was added

I wonder if the last 2 internal types are really needed. AFAIK PDNS can handle them fine with using type=TYPE65400

**Comment by klaus3000** [comment]
Probably the most important one to mention is CAA vs. MBOXFW. That one hit us while testing upgrades from 3.4 to 4.0

**Comment by klaus3000** [comment]
After some more analysis I think there is a fundamental problem in PDNS (please correct me if I am wrong) - new PDNS version which added eplicit support for a new record type or incompatible with the dns data used by older version. Let me describe the problem:

Currently PDNS does support ALL resource records (at least the SQL backends) as the records are stored with type=TYPEXXX and content='\# <len> <HEXDATA OF WIRE FORMAT>'.

So for example the WKS record (which is not explicitely supported) '1.1.1.1 6 9 25 530' is stored in the DB as:
```
type=TYPE11
content=\# 72 010101010600400040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020
```
If a newer version of PDNS would add explicit support for WKS, it would correctly treat TYPE11 as WKS, but it would fail to handle this content as for all explicit supported records the parser expects the human readable format, and fails to handle the hex-format.

Hence when upgrading to the newer version PDNS would fail to answer any query for a label where a WKS record exists. One solution would be to update the records in the database or insert them again in the human readable format. But this works only for small setups.

I think many PDNS users use a DB backend and use DB replication to the DB slaves. In such a setup every nameserver and the DB-content must be updated at the same time. E.g. in our setup this would require to update >30 slaves and the master inserting data at the same time, and then retransfer all zones using the new explicitely supported resource record - this is impossible without service interruption.

IMO the better solution would be to try parsing the content as hexdata if the normal parsing triggers an exception.

If you are not planing to solve this issue, please give me a pointer where in the code I could catch this exception for CAA records and reparse them as hexstring.

**Comment by Habbie** [comment]
@klaus3000 thank you for your extensive analysis. Indeed 'types suddenly becoming supported' is a fundamental problem, as noted in #804. We will give this some more thought.

**Comment by klaus3000** [comment]
Any hints for a quick workaround for our 4,0 servers to reparse CAA in wire-format?

**Comment by Habbie** [comment]
If they are slaves, run pdns_control retrieve-zone on them, or bump the serial on the master to force a retransfer. Does that help?

**Comment by klaus3000** [comment]
With DNS slaves (XFR) there would not be a problem as you suggest. The problem is if the "slaves" domain type is "NATIVE" and DB master-slave replication is used. Thus I wanted to spot the line were CAA content is parsed and catch the parsing expcetion and reparse it as hex encoding - but I failed somewhere between B.get() and the record type boilerplates due to lack of C++ knowledge.

**Comment by klaus3000** [comment]
Here is a pull request to fix the missing upgrade documentation: https://github.com/PowerDNS/pdns/pull/4955
