### ISSUE TITLE
unmet dependencies for pdns-server on xenial

### ISSUE THREAD

**Issue by job** [PowerDNS/pdns#4927]
it appears the pdns-server package for Ubuntu 16.04 has unmet dependencies. A local problem or an issue with the packages on `repo.powerdns.com` ?

```
root@ns0:~# apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://nl.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:3 http://nl.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Hit:4 http://nl.archive.ubuntu.com/ubuntu xenial InRelease
Hit:5 http://repo.powerdns.com/ubuntu trusty-auth-40 InRelease
Get:6 http://nl.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [454 kB]
Get:7 http://nl.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [446 kB]
Get:8 http://nl.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [381 kB]
Get:9 http://nl.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [376 kB]
Get:10 http://nl.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [8,084 B]
Get:11 http://nl.archive.ubuntu.com/ubuntu xenial-updates/multiverse i386 Packages [6,880 B]
Fetched 1,875 kB in 1s (980 kB/s)
Reading package lists... Done
root@ns0:~# apt-get install pdns-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pdns-server : Depends: libboost-program-options1.54.0 but it is not installable
               Depends: libbotan-1.10-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@ns0:~#
```

**Comment by jviersel** [comment]
Also, pdns-mysql-backend has broken dependencies. It requires libmysqlclient18, while xenial has libmysqlclient20

`root@ns0:~# apt-get install pdns-backend-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pdns-backend-mysql : Depends: pdns-server (>= 4.0.3-1pdns.trusty) but 4.0.0~alpha2-3build1 is to be installed
                      Depends: libmysqlclient18 (>= 5.5.24+dfsg-1) but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Comment by zeha** [comment]
The packages in the `trusty` repository are for `trusty`, not for `xenial`. Please use the correct repository.

**Comment by job** [comment]
oops! thank you for spotting that!
