### ISSUE TITLE
Bogus lua-config-file is ignored

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#4939]
- Program: Recursor
 - Issue type: Bug report

### Short description
If I point `lua-config-file` to a non-existing path, this appears to be silently ignored and the Recursor just starts up.

### Environment

 - Operating system: Debian 8.0
 - Software version: 4.0.3
 - Software source: repo

**Comment by pieterlexis** [comment]
It was not silently ignored, but the error was logged at a too low loglevel. #5078 has the fix.
