### ISSUE TITLE
Zonetransfer failing (Could not execute mysql statement)

### ISSUE THREAD

**Issue by berkutta** [PowerDNS/pdns#4943]
- Program: GSQLBackend 
 

### Short description

I'm trying to do Zone Transfers from a PDNS Master to a PDNS Slave. But it fails with an MySQL Issue. The PDNS Master & Slave have an Database which got setup with the standard schema. notified_serial is an int.

### Environment

 - Operating system: Ubuntu Xenial
 - Software version: 4.0.0-alpha2
 - Software source: OS Repository

### Expected behaviour
Should transfer the zone to the slave

### Actual behaviour

Spits out the following Error:
`pdns[21927]: gmysql Connection successful. Connected to database 'pdns' on 'localhost'.`
`pdns[21927]: 1 domain for which we are master needs notifications`
`pdns[21927]: Queued notification of domain 'domain.host.' to 87.81.121.97:53`
`pdns[21927]: Exiting because communicator thread died with error: GSQLBackend unable to refresh domain_id 43: Could not execute mysql statement: update domains set notified_serial=? where id=?: Out of range value for column 'notified_serial' at row 1`

**Comment by Habbie** [comment]
Hello! Can you please upgrade via https://repo.powerdns.com/ and tell us if that helps? In terms of development and bug fixes, the version shipped by Xenial is quite old.

**Comment by berkutta** [comment]
Hi, Updated to PowerDNS 4.0.3. The Error is still the same. I can't really make any sense why it spits this error. In my view it's an "direct" issue with the MySQL Database. But the MySQL Database is built with the PowerDNS schema. Can I see the exact MySQL Query which PowerDNS tries to execute?

**Comment by Habbie** [comment]
We do not log the query arguments currently; maybe you can convince mysqld to log them? Also, can you show the domains schema from your server, just to be sure?

**Comment by zeha** [comment]
If we knew the actual domain name on that IP, we could probably guess the value thats going to be in the statement...

**Comment by berkutta** [comment]
My schema looks like the following:
```
CREATE TABLE `domains` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `master` varchar(128) DEFAULT NULL,
  `last_check` int(11) DEFAULT NULL,
  `type` varchar(6) NOT NULL,
  `notified_serial` int(11) DEFAULT NULL,
  `account` varchar(40) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

When I run for example the following query directly on the MySQL Server it runs fine and changes it's value. So I really don't have any clue where to search.
`update domains set notified_serial=7201 where id=9`
(The origin value of this domain of notified_serial was 7200, so PDNS already did something hence the error?)

**Comment by mind04** [comment]
Most likely cause is, the serial field in the SOA record is above INT max (2147483647) for this domain.

**Comment by berkutta** [comment]
@mind04 Yes, that was the issue! Thanks.
