### ISSUE TITLE
pdns_recursor logging without syslog/journald

### ISSUE THREAD

**Issue by abuschmann** [PowerDNS/pdns#4945]
### Please do not work on this issue. I made an error.

 - Program: Recursor
 - Issue type: might be Documentation issue, might be one of the others

### Short description
I am trying to redirect the logging away from journald to a pipe.
This is for debugging another issue, I am not yet clear on.

### Environment
 - Operating system: CentOS 7.3.1611
 - Software version: 4.0.4-1pdns.el7
 - Software source: http://repo.powerdns.com/centos/$basearch/$releasever/rec-40

### Steps to reproduce
```
  cp -p /usr/lib/systemd/system/pdns-recursor.service /etc/systemd/system/
  Edit /etc/systemd/system/pdns-recursor.service: Change:
        ExecStart=/bin/bash -c 'exec /usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog >( exec /usr/sbin/rotatelogs -l -f /var/log/pdns/log.%%Y-%%m-%%d 86400 ) 2>&1'
      Add:
        KillMode=control-group

  mkdir /var/log/pdns
  semanage fcontext -a -t httpd_log_t '/var/log/pdns(/.*)?'
  restorecon -R -v /var/log/pdns
  systemctl daemon-reload
  systemctl restart pdns-recursor.service
```

### Expected behaviour
The logging output from pdns_recursor goes to /var/log/pdns/log._date_

### Actual behaviour
The logging output from pdns_recursor still goes to journald like:
```
Jan 26 12:51:37 testnameserver bash[3802]: Jan 26 12:51:37 2 [283/1] question for 'www.foobar.de|A' from 10.10.10.10
Jan 26 12:51:37 testnameserver bash[3802]: Jan 26 12:51:37 [283] www.foobar.de: Wants DNSSEC processing in query for A
Jan 26 12:51:37 testnameserver bash[3802]: Jan 26 12:51:37 [283] www.foobar.de: Looking for CNAME cache hit of 'www.foobar.de|CNAME'
```

### Other information
Might be related to 
#1396
#1607
Might be a documentation problem: When running under systemd, 
`--daemon=no --disable-syslog`
does not write to stdout/stderr, but ...

You should do _XYZ_ instead.

If this is considered a feature request:

### Usecase
Logging from pdns_recursor without using journald/syslog.
I am looking for a way to get logs which have not been tampered with.
This (for me) is primarely for debugging.

### Description
Output the logs to one of:
- `stdout`
- `stderr`
- a file, with the filename either given on the commandline or in `recursor.conf`

**Comment by pieterlexis** [comment]
> Might be a documentation problem: When running under systemd,
> --daemon=no --disable-syslog
>  does not write to stdout/stderr, but ...

it does, I run pdns-recursor on the commandline all the time.

The journal tells you the output come from the bash process. So this means bash sends these lines to stdout (this is how systemd picks up log lines). I am also not sure if systemd supports subshells and re-parenting `rotatelogs` to init like this.

As we state in #1396, we only support logging via syslog and/or via stdout.

When running on a distro with journald, the (only) recommended way to view logs is `journalctl` and if you want this to end up in different files, you can have journald forward to syslog and use syslog config to separate the data to different files.

> I am trying to redirect the logging away from journald to a pipe.
> This is for debugging another issue, I am not yet clear on.

It is unclear how this would help (also, `journalctl -f -u pdns-recursor | $whatever` allows you to write to a a pipe).

I am closing this issue as separate logging won't be implemented. Furthermore, this feels like a support issue. Please use the [mailing lists or IRC](https://www.powerdns.com/opensource.html) for more help.

**Comment by abuschmann** [comment]
I made an error. The line in `/etc/systemd/system/pdns-recursor.service` needs to be:
`
ExecStart=/bin/bash -c 'exec > >( exec /usr/sbin/rotatelogs -l -f /var/log/pdns/log.%%Y-%%m-%%d 86400 ) ; exec /usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog 2>&1'
`
That creates a viable redirect.
Thank you.

**Comment by istiak101** [comment]
Systemd 240 or newer versions can do this. Add below lines to your service file.

```
StandardOutput=append:/var/log/pdns.log
StandardError=append:/var/log/pdns.log
```
