### ISSUE TITLE
Custom Logging Not Working after upgrade

### ISSUE THREAD

**Issue by bynicolas** [PowerDNS/pdns#4948]
- Program: Authoritative, Recursor . version 4.0.3
 - Issue type: Bug report of the logging facility

### Short description

When using `logging-facility` in version 4.0.3, log entries are not sent to my custom log file. This used to work in 4.0.0-alpha2.

I noticed the `programname` changed from `pdns` to `pdns_server`

I managed to make it work by supplying a custom rule to rsyslog

    :programname, isequal, "pdns_server" {

       /var/log/pdns.log
       stop

    }

which before `local0.*        -/var/log/pdns.log` would work

### Environment

 - Operating system: Ubuntu 16.04.1 LTS
 - Software version: 4.0.3
 - Software source: PowerDNS repository (updated from OS repo) 

### Steps to reproduce

1. Update from 4.0.0-alpha2 to 4.0.3 (maybe the bug was introduced before 4.0.3, but 4.0.0-alpha2 was still working)
2. Change pdns logging to use custom log file by adding `logging-facility=0` to pdns config file
3. Add a custom config to rsyslog at `/etc/rsyslog.d/pdns.conf` containing `local0.*        -/var/log/pdns.log` 
4. Restart rsyslog

### Expected behaviour
Custom log file would be created and containing pdns logs

### Actual behaviour
Custom file is not created. 
Discarding outputs of `local0` statement in `syslog` file is not enforced (i.e. `local0.none           -/var/log/syslog`
Logs are still being printed to `/var/log/syslog`

### Other information

I don't know what else has changed between versions, but at least this did
  Before update `programname`:

  `Jan 26 15:31:40 ns1 pdns[2774]:`

  after update `programname`:

  `Jan 26 15:33:42 ns1 pdns_server[5341]:`

**Comment by pieterlexis** [comment]
Hi,

between alpha2 and 4.0.0, syslog logging was disabled by default on machines with systemd (to prevent duplicate log lines).

Journald will read the log output from stdout and forward to syslog, so no log facility is added.

To re-enable, you'll need to edit the unit-file and remove the `--disable-syslog` statement from the ExecStart line.
