### ISSUE TITLE
--with-modules="ldap" --enable-static-binaries bombs during configure

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#495]
$ ./configure --with-modules="ldap" --with-dynmodules="" --enable-static-binaries

this fails, because it cannot find libldap:

checking for ldap_set_option in -lldap... no
configure: error: ldap library (libldap) not found

Log contains:

x86_64-linux-gnu-g++: error: unrecognized command line option 
           '-all-static'

otoh, the dynamic version:

./configure --with-modules="" --with-dynmodules="ldap"

configures just fine.

**Comment by Habbie** [comment]
We are getting rid of the static stuff.

**Comment by rubenk** [comment]
I'm opening a beer right now! ;)

**Comment by Habbie** [comment]
:beers:
