### ISSUE TITLE
Recursor fails to validate for gov.nl.ca

### ISSUE THREAD

**Issue by nberlee** [PowerDNS/pdns#4994]
### Steps to reproduce
1. Setup a recursor with default dnssec-validation on.
2. Query any record on gov.nl.ca

### Expected behaviour
DNSsec is validated up to the .ca zone, as there is no DS record for gov.nl.ca, return records as expected.

### Actual behaviour
The recursor returns SERVFAIL because recursor or query demands it for Bogus results

### Other information
Domain does not have any validation errors in dnsviz: http://dnsviz.net/d/gov.nl.ca/dnssec/
Debug log (level 9) of the recursor: [gov.nl.ca query of recursor.txt](https://github.com/PowerDNS/pdns/files/766734/gov.nl.ca.query.of.recursor.txt)

**Comment by pieterlexis** [comment]
Fixed in master by #5463
