### ISSUE TITLE
Debian stretch repositories

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#5000]
Debian stretch is frozen, so users may want to try running PowerDNS software on that rather soon.

Please have stretch-xxx repositories matching their current jessie-xxx counterparts.

**Comment by Habbie** [comment]
This is ticket #5000 🎂 🎉

**Comment by ahupowerdns** [comment]
:partyparrot: <- one day this will work

**Comment by pieterlexis** [comment]
[Fixed!](https://twitter.com/lieter_/status/831481819963019264)! Release packages will come once we do a release, as Stretch is up to date.
