### ISSUE TITLE
policy-result-noaction counter incrementing incorrectly?

### ISSUE THREAD

**Issue by tmuncks** [PowerDNS/pdns#5002]
I have a pdns_recursor with rpzMaster statements configured with a defpol of NODATA.
In the "rec_control get-all" stats however, I see increments in policy-result-noaction as well as in policy-result-nodata, which seem strange.
In fact, even without any RPZ stuff in my config, the policy-result-noaction counter increments.
I'm not sure this is actually a bug, but it does seems odd.

**Comment by rgacogne** [comment]
Looking at the code a bit more, `policy-result-noaction` is incremented every time a query has been processed without triggering any policy rule, except if `RPZ` processing was explicitly disabled (for example via `dq.wantsRPZ`), which is fine by me.

**Comment by tmuncks** [comment]
In that case, all is good. Thanks for clearing that up :)
