### ISSUE TITLE
RPZ change summary counters off by one

### ISSUE THREAD

**Issue by tmuncks** [PowerDNS/pdns#5008]
It seems the counters for rpzMaster removals and additions are "off by one".
This is purely cosmetic, of course, but a change set of 42 removals and 0 additions, shows in the log as:
Had 43 RPZ removals, 1 addition.

**Comment by rgacogne** [comment]
Fixed by 00febe394033d2ea53ecbcf135ac94de6ba4be08, now backported to 4.0.x.
