### ISSUE TITLE
Recursor: packetcache-ttl has precedence on max-negative-ttl even when disable-packetcache=true

### ISSUE THREAD

**Issue by killerwhile** [PowerDNS/pdns#5040]
- Program: Recursor
 - Issue type: Bug report

### Short description
In Recursor, max-negative-ttl value is overwritten by packetcache-ttl even when packetcache is disabled.

### Environment
 - Operating system: Centos 7.3
 - Software version: 4.0.4
 - Software source: PowerDNS repository

### Steps to reproduce
1. disable-packetcache=true
2. max-negative-ttl=3 # 3 seconds
3. query a NX domain, such as laksdjflasdjflqwjlajsdlfj12312312.com in a loop every 5 seconds
4. using tcpdump, we can see that only one request is send for the domain every hour
5. keeping disable-packetcache=true, packetcache-ttl=10 # instead of 3600 default value
6. restart pdns-recursor
7. query a NX domain, such as laksdjflasdjflqwjlajsdlfj12312312.com in a loop every 5 seconds
8. using tcpdump, we can see that only one request is send for the domain every 10 seconds.

### Expected behaviour
I would have expected that max-negative-ttl value has precedence over packetcache-ttl, not the invert.

**Comment by pieterlexis** [comment]
the packet cache ttl influencing the records cache ttl makes indeed no sense, we'll invesitgate

**Comment by omoerbeek** [comment]
Using master, I cannot reproduce. `max-negative-ttl` is honoured withh `disable-packetcache=true`
