### ISSUE TITLE
Problems with compiling powerdns using botan

### ISSUE THREAD

**Issue by chriscpritchard** [PowerDNS/pdns#5044]
- Program: Authoritative, Recursor, dnsdist 
Issue type: Bug report

### Short description
When compiling powerDNS on gentoo and "use=botan" I get the following error:
"/bin/sh: line 1: 26208 Aborted                 (core dumped) ./pdns_server --no-config --config 2> /dev/null > pdns.conf-dist" 

and the compilation fails

### Environment
 - Operating system: Gentoo linux
 - Software version: 4.0.3
 - Software source: Portage repository

### Steps to reproduce
1. emerge -av pdns (with USE=botan)

### Expected behaviour
I would expect the software to compile and install as normal.

### Actual behaviour
The software failed to compile when running:
"./pdns_server --no-config --config" with the following error (with debugging enabled):
terminate called after throwing an instance of 'Botan::Invalid_State'
  what():  Could not find a thread-safe mutex object to use
Aborted (core dumped)

### Other information
More digging including the output of "gdb"

[emerge --info.txt](https://github.com/PowerDNS/pdns/files/780672/emerge.--info.txt)
[build log.txt](https://github.com/PowerDNS/pdns/files/780673/build.log.txt)
[ebuild environment.txt](https://github.com/PowerDNS/pdns/files/780685/ebuild.environment.txt)
[emerge -pvq.txt](https://github.com/PowerDNS/pdns/files/780686/emerge.-pvq.txt)
[gdb.txt](https://github.com/PowerDNS/pdns/files/780687/gdb.txt)

**Comment by chriscpritchard** [comment]
Works fine when botan is compiled with thread-safety support in (in gentoo USE="threads" must be enabled for botan)

**Comment by Habbie** [comment]
Thank you for documenting this!
