### ISSUE TITLE
pdnssec could automatically set sane SOA-EDIT values

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#505]
Currently my workflow is as following: 

```
pdnssec secure-zone example.net

pdnssec rectify-zone example.net

pdnssec show-zone example.net
```

Then I have to dive into the backend: 

```
mysql> select id from domains where name='example.net';

id = 99

mysql> insert into domainmetadata (domain_id, kind, content) values (99, 'SOA-EDIT', 'INCEPTION-EPOCH');
```
It would be great if pdnssec sets _some_ value for SOA-EDIT because I wouldn't be suprised that some people who setup DNSSEC, and after 9 days burst into tears. Also it saves me 2 extra lines of typing.

**Comment by jpmens** [comment]
+1 and please also set default for `SOA-EDIT-API` as requested in #2173

**Comment by Habbie** [comment]
Not doing this behaviour change.
