### ISSUE TITLE
Subdomain delegation fails w/ recursor

### ISSUE THREAD

**Issue by sgel83** [PowerDNS/pdns#5055]
I have PDNS setup with Recursor and I am trying to delegate a subdomain to a different name server.

The zone is setup as Native
`+----+---------------------------+--------+------------+--------+-----------------+---------+
| id | name                      | master | last_check | type   | notified_serial | account |
+----+---------------------------+--------+------------+--------+-----------------+---------+
|  5 | metapoc.vims              |        |       NULL | NATIVE |            NULL |         |
+----+---------------------------+--------+------------+--------+-----------------+---------+`

I added an NS record and A record for the DNS server handling the subdomain gvd.
`+-------+-----------+---------------------+------+---------------------+------+------+-------------+----------+-----------+------+-------------+
| id    | domain_id | name                | type | content             | ttl  | prio | change_date | disabled | ordername | auth | instance_id |
+-------+-----------+---------------------+------+---------------------+------+------+-------------+---------
-+-----------+------+-------------+
| 12641 |         5 | gvd.metapoc.vims    | NS   | ns-gvd.metapoc.vims | 3600 |    0 |        NULL |        0 | NULL      |    0 |        NULL |
| 12656 |         5 | ns-gvd.metapoc.vims | A    | 10.0.33.3           | 3600 |    0 |        NULL |        0 | NULL      |    1 |        NULL |
+-------+-----------+---------------------+------+---------------------+------+------+-------------+----------+-----------+------+-------------+`

pdns.conf
`# Autogenerated configuration file template

# PDNS
local-port=53

# Database Information
launch=gmysql
gmysql-host=localhost
gmysql-user=power_admin
gmysql-dbname=powerdns

#RFC 2136 Configuration
dnsupdate=yes
allow-dnsupdate-from=0.0.0.0/0,::/0

#Recursor
recursor=127.0.0.1:54`

recursor.conf
`setuid=pdns-recursor
setgid=pdns-recursor

forward-zones=gvd.metapoc.vims=10.0.33.3
forward-zones-recurse=.=8;8.8.8.8;8.8.4.4
local-port=54
serve-rfc1918=no`

versions
pdns-backend-mysql-4.0.3-1.el6.MIND.x86_64
pdns-4.0.3-1.el6.MIND.x86_64
pdns-recursor-3.7.3-1.el6.x86_64

I also tried w/ and w/o the AUTH flag set to 1 for the NS record.

Each time a query is sent this is the response I get simply returns the NS and A record for the nameserver.

Is there something I am a missing?  Is this a lack of functionality in PDNS?

**Comment by pieterlexis** [comment]
Hi,

There are several weird things with your config. your `forward-zones-recurse` line is wrong. ANd you are running the auth in front of the recursor instead of the other way around.

As this is more of a support question and not a bug (PowerDNS supports delegation), please send you question with the actual configs to the [mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users)
