### ISSUE TITLE
recursor: allow any type of Lua value in dq.data

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#5060]
- Program: Recursor 
 - Issue type: Feature request 

### Short description

The current implementation of `dq.data` limits both keys and values to strings. For keys this is fine, but for values this is quite limiting, as it does not allow passing more complex data, like Lua tables. 

Would it be possible to extend `dq.data` to allow any type of Lua value, including tables? 

### Usecase

I need to maintain complex state between different callback functions. The current string restriction would require either serializing and deserializing the state, which would incur significant overhead. Another option might be storing the state in a global table, but I am concerned that this could cause memory leaks.

### Description

This feature request is related to #4981.

Example code that this feature would enable:

```lua
function gettag(remote, edns, loc, qname, qtype)
    local complex_state_table = get_complex_state()
    ...
    return 1, {'some-policy-tag'}, {state=complex_state_table}
end

function preresolve(dq)
    local state = dq.data.state
    do_something_with(state.foo.bar)
    ...
end
```

It seems that the Lua global state stack is maintained between callbacks. One possible workaround would be to do something like this (not tested):

```lua
states_global = {}

function gettag(remote, edns, loc, qname, qtype)
    local complex_state_table = get_complex_state()
    ...
    local state_id = gen_unique_string_id()
    states_global[state_id] = complex_state_table 
    return 1, {'some-policy-tag'}, {state_id=state_id}
end

function preresolve(dq)
    local state = states_global[dq.data.state_id]
    states_global[dq.data.state_id] = nil -- release the state to prevent memory leaks
    do_something_with(state.foo.bar)
    ...
end
```

But I am not sure if all defined callbacks are guaranteed to be called. If preresolve would not be called here, it would create a memory leak.

The implementation of this ticket could do the equivalent of this code: maintain a global Lua table on the stack, assign a unique ID to a request, and make the whole `dq.data` a reference to the table entry. This would also avoid coping data values between Lua and C++: if I am correct the C++ code only needs to store the stack offset of the whole `dq.data` table value. The calling C++ code is also in a better place to judge when to release this data for a request.

As an optimization, the table entry should only be allocated the first time the Lua code accesses `dq.data`. There is also no need to require `dq.data` to be a table with this implementation, a user would be able to set `dq.data = 42`.

The recursor uses LuaWrapper to access Lua functionality. I am not sure if this wrapper exposes the required functionality.

**Comment by Habbie** [comment]
> But I am not sure if all defined callbacks are guaranteed to be called. If preresolve would not be called here, it would create a memory leak.

You could use a weak ref for that.

**Comment by Habbie** [comment]
#5141 fixes this once merged.

**Comment by Habbie** [comment]
#5141 merged!
