### ISSUE TITLE
RemoteLogResponseAction throws Fatal error: Unable to convert parameter

### ISSUE THREAD

**Issue by jvalentini** [PowerDNS/pdns#5065]
- Program: dnsdist
 - Issue type: Bug report

### Short description
`RemoteLogResponseAction` throws `Fatal error: Unable to convert parameter from no value to St10shared_ptrI9DNSActionE` on `dnsdist-1.1.0` or `master`. This error does not occur for `RemoteLogAction` only the response action.

### Environment

 - Operating system: ubuntu 16.04
 - Software version: dnsdist-1.1.0
 - Software source: compiled yourself

### Steps to reproduce
Using the following Lua config:
```
newServer({address="127.0.0.1:5353", useClientSubnet=true})
webserver("127.0.0.1:8083", "secret", "secret")
l = newRemoteLogger("127.0.0.1:4242")
addAction(AllRule(), RemoteLogAction(l))
addAction(AllRule(), RemoteLogResponseAction(l))
```
1. `cd pdns/dnsdistdist && autoreconf -i && ./configure --with-protobuf && make && make install && dnsdist --supervised -C <path/to/conf>`

### Expected behaviour
No fatal should be thrown and `dnsdist` should log responses to the remote tcp connection.

### Actual behaviour
`Fatal error: Unable to convert parameter from no value to St10shared_ptrI9DNSActionE`

**Comment by ahupowerdns** [comment]
+1 on the quality of this bug report. Thank you, we're working on it now.

**Comment by rgacogne** [comment]
Please do:
`addResponseAction(AllRule(), RemoteLogResponseAction(l))`
instead of:
`addAction(AllRule(), RemoteLogResponseAction(l))`
You should be fine :)

**Comment by jvalentini** [comment]
Thanks, @rgacogne, that worked. Apologies for missing `addResponseAction` in the docs.
