### ISSUE TITLE
dnsdist - problems about QPS for PTR per IP range.

### ISSUE THREAD

**Issue by yudai09** [PowerDNS/pdns#5066]
- Program: dnsdist
 - Issue type: Feature request

### Description

I want to configure QPS limit with PTR per IP range like below.
`addAction(makeRule({"1.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))`
IP range is 0.0.0.0/24

But we have more than 1,000 ranges, it cause problems.
* Dnsdist cosumes so much CPU pewer. 
* The config file becomes huge like below. 
```
addAction(makeRule({"1.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
addAction(makeRule({"2.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
addAction(makeRule({"3.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
...
addAction(makeRule({"255.4.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
```

I have a workaround to ease the performance problem by reducing lines.
```
addAction(makeRule({"1.1.1.in-addr.arpa.","2.1.1.in-addr.arpa.","3.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
addAction(makeRule({"4.1.1.in-addr.arpa.","5.1.1.in-addr.arpa.","6.1.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
...
addAction(makeRule({"253.4.1.in-addr.arpa.","254.4.1.in-addr.arpa.","255.4.1.in-addr.arpa."}),QPSPoolAction(100,"ptr"))
```
But I think it is just workaround, because IP range is larger than 0.0.0.0/24 and the config file is still huge.

Is there any straightforward solution for this?

**Comment by rgacogne** [comment]
The fastest solution is to use only one rule with a single `SuffixMatchNode`. Keep in mind that `dnsdist` configuration is written in `Lua`, so you can easily use variables and loops in your configuration like this:
```
smn = newSuffixMatchNode()

for i=1, 255 do
  for j=1, 255 do
    smn:add(newDNSName(j.."."..i..".1.in-addr.arpa."))
  end
end

addAction(SuffixMatchNodeRule(smn), QPSPoolAction(100,"ptr"))
```
You'll need to adjust that to you needs of course, but that's the general idea.

**Comment by yudai09** [comment]
rgacogne, thank you!

I think your code will limit QPS for all IPs in `smn` altogether.
But I want to limit QPS per each IP ranges.

* altogether way:
100 QPS for 1.1.1.in-addr.arpa., 2.1.1.in-addr.arpa. .. 255.4.1.in-addr.arpa.

*  QPS per each IP ranges:
100 QPS for 1.1.1.in-addr.arpa.
100 QPS for 2.1.1.in-addr.arpa.
100 QPS for 3.1.1.in-addr.arpa.
...
100 QPS for 255.4.1.in-addr.arpa.

Below code will work, but has a performance problem, it consumes so much CPU power.
```
for i=1, 255 do
  for j=1, 255 do
    smn = newSuffixMatchNode()
    smn:add(newDNSName(j.."."..i..".1.in-addr.arpa."))
    addAction(SuffixMatchNodeRule(smn), QPSPoolAction(1000,"ptr"))
  end
end
```

> Keep in mind that dnsdist configuration is written in Lua

I know, but there is not good explanation about those functions...

At least I want to ease perfomance problem.

**Comment by rgacogne** [comment]
Right, a query that doesn't match any rule will have to pass through every single one of them (65k) so the CPU usage is kind of expected. Do you really need a QPS limit per reverse range? One other option would to limit per client subnet, with something like (actual code untested):

```
smn = newSuffixMatchNode()

for i=1, 255 do
  for j=1, 255 do
    smn:add(newDNSName(j.."."..i..".1.in-addr.arpa."))
  end
end

addAction(AndRule({SuffixMatchNodeRule(smn), MaxQPSIPRule(100, 32, 48)}), PoolAction("ptr"))
```

Thus limiting every single IPv4 and /48 IPv6 to a maximum of 100 PTR queries per second before being routed to the `ptr` pool.

**Comment by yudai09** [comment]
> Do you really need a QPS limit per reverse range? 

As measure to a troble occurred early this year, I need to do it...
I'm sorry, I cannot explain the reason why I need to do it becase of poor English writing ability.
I have configured QPS limit per client already.

I wish I could limit QPS for PTR like MaxQPSIPRule.

**Comment by rgacogne** [comment]
So, if I understand correctly, you would need some sort `MaxQPSSuffitMatchRule` that works like the `MaxQPSIPRule` one but for qname instead of source IP. I'm not sure on what we would group then, number of labels instead of prefix length?

**Comment by rgacogne** [comment]
Closing since the issue has been inactive for a long time, and I'm not sure what the initial need was.
