### ISSUE TITLE
Deprecate and remove dnsdist syntactic sugar functions

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#5069]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

Right now there are multiple ways of accomplishing the same things in dnsdist. For instance

```
addQPSLimit(AllRule(), qps) == addAction(AllRule(), QPSAction(qps)) == addAction(MaxQPSRule(qps), DropAction()) 
```

Functions like setDNSSECPool, addDomainSpoof and addPoolRule can be mimicked with a 'normal' set of Rules and Actions. (e.g. `setDNSSECPool` == `addAction(DNSSECRule(), poolAction())`).

Forcing users to to be a little bit more explicit (using addAction, addResponseAction etc.) makes for a cleaner and better to understand configuration.

### Usecase

Simplify initial understanding of how dnsdist's Rules and Actions hang together and ensure understandability of the configuration

**Comment by ahupowerdns** [comment]
so I applaud this in theory, but we should document explicitly that addAction() accepts domain names, ip addresses and even lists of domain names and IP addresses as its first argument. It is (technically) documented now, but it appears in no example!

**Comment by rgacogne** [comment]
Done in #5526.
