### ISSUE TITLE
EDNS Client Subnet *Port Number* feature in Recursor

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5079]
- Program: Recursor 
 - Issue type: Feature request 

### Short description
EDNS Client Subnet can be used internally for CG-NAT mapping resolution, as in "who asked this question". 

The port number should somehow be encoded in "EDNS client subnet with port number", and Lua should be able to see that port number.

This means the feature should also live in dnsdist.

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by Habbie** [comment]
ref https://datatracker.ietf.org/doc/draft-bellis-dnsop-xpf/

**Comment by Habbie** [comment]
Recursor Lua can already extract arbitrary options. Relabeling this to dnsdist.
