### ISSUE TITLE
Docs: Ldap-backend strict mode requires corresponding in-addr.arpa zone with SOA 

### ISSUE THREAD

**Issue by shantikulkarni** [PowerDNS/pdns#5086]
- Program: Authoritative (ldap backend)
 - Issue type: Docs

### Short description
Please update ldap backend documentation to add that an reverse lookup zone with an SOA attribute is now required for strict mode reverse lookups. This was not the case for version 3.3.3 or prior.

### Description
I upgraded from 3.3.3 to git master (cbf3062), and found that my ldap strict mode reverse lookups were broken (either forwarded, or returned refused).  This was confusing because I've been using this tree since ~2.9.x. Eventually I decided to try creating an entry for the xxx.xxx.in-addr.arpa zone it was seeking, with an SOA attribute, and it started working again.  Since this is a change in behavior from earlier versions, I suggest the docs for ldap-backend should include that strict mode reverse lookups will fail without a unless there is a reverse lookup zone corresponding to the address, with a valid SOA attribute.

**Comment by Habbie** [comment]
Agreed! If you want to speed this along, you can go to https://github.com/PowerDNS/pdns/blob/master/docs/markdown/authoritative/backend-ldap.md, edit it yourself, and file a pull request. Otherwise, this ticket you already wrote will make sure somebody will get to it eventually. Thanks!

**Comment by Habbie** [comment]
Fixed in #5098. Thanks!
