### ISSUE TITLE
pdns_recursor tries to parse configfile before --help

### ISSUE THREAD

**Issue by cyclops1982** [PowerDNS/pdns#5108]
- Program: Recursor
 - Issue type: Feature request 

### Short description
pdns_recursor seems to parse the configfile before parsing the arguments. In my case, this results in an error when i do pdns_recursor --help

Example output:
`
[09:57:09] cyclops@jubilee:~$ pdns_recursor --help
Mar 06 09:57:13 Exception: Trying to set unknown parameter 'dnssec-log-bogus'
`

It would be better if --help always worked, so that i can at least find out how to indicate a different config file.

### Environment
 - Operating system:  Ubuntu 16.04
 - Software version: 
`
[10:01:30] cyclops@jubilee:~$ dpkg -l pdns*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                    Version                          Architecture                     Description
+++-=======================================================-================================-================================-====================================================================================================================
un  pdns                                                    <none>                           <none>                           (no description available)
un  pdns-backend                                            <none>                           <none>                           (no description available)
ii  pdns-backend-mysql                                      4.0.0~alpha2-3build1             amd64                            generic MySQL backend for PowerDNS
iF  pdns-recursor                                           4.0.0~alpha2-2ubuntu0.1          amd64                            PowerDNS recursor
ii  pdns-server                                             4.0.0~alpha2-3build1             amd64                            extremely powerful and versatile nameserver
`

### Steps to reproduce
Add a bogus config to the config file
Run pdns_recusor --help

### Expected behaviour
I would like it to return the help or process the arguments before throwing an an error and exisitng. Or, it should throw out the error and show the help

### Actual behaviour
See above.

**Comment by omoerbeek** [comment]
Fixed in the meantime
