### ISSUE TITLE
DNSKEY mismatch

### ISSUE THREAD

**Issue by kaosdrachen** [PowerDNS/pdns#5111]
Program: Authoritative
Issue Type: Bug report.

### Short description
A number of domains secured with DNSSEC fail to validate with SIDN, with the error 

`validation failure <_sidn._dnssec-valcheck._305567375.vheng.nl. A IN>: use of key for crypto failed from 127.0.0.1 for key vheng.nl. while building chain of trust. `

When we checked it with dnsviz.net it turned out that one of our nameservers was returning the wrong DNSKEY value.  As it turned out, that particular nameserver is running the bleeding edge version of pdns-server, version 0.0.1556g39c8af9-1pdns.jessie, and after consulting with the authors on IRC it was concluded that the server or its schema appears to be truncating the output.

As per their request, I'm adding the output of `SELECT * FROM records WHERE domain_id=` from both the slave machine and the master; see the attached  text file.

### Environment
 - Operating system: Debian GNU/Linux 8.0 "Jessie"
 - Software version:  0.0.1556g39c8af9-1pdns.jessie
 - Software source: PowerDNS apt repository, using the Jessie master branch.
### Steps to reproduce
1. Have master server running PostgreSQL and pdns 3.x
2. Have at least one remote server replicating the master database via postgres repmgr.
3. Have said remote server run the Master branch
4. Use ECDSA DNSSEC on a domain.

### Expected behaviour
All servers report the same DNSKEY and DS/RRSIG values for DNSSEC validation purposes, in this case `257 3 14 Dz2dzcHG5P7lOZotF39oQoxzZGYrHjvVjQoT/KOh/hHyV7wsPwUfMoBz czm8Z6oRnqciDIu60y/mcROMNhurD4b+mXmatEqlkjk7cNcCZHVsjjJu vL1bLPzq6CJPaTs=`

### Actual behaviour
The server running Master branch truncates its DNSKEY output, resulting in a wrong signature: `257 3 14 Dz2dzcHG5P7lOZotF39oQoxzZGYrHjvVjQoT/KOh/hHyV7wsPwUfMoBz czm8Z6oRAJ6nIgyLutMv5nETjDYbqw+G/pl5mrRKpZI5O3DXAmR1bI4y bry9Wyz86ugiT2k7`

### Other information
[domainrecords.txt](https://github.com/PowerDNS/pdns/files/821301/domainrecords.txt)

**Comment by Habbie** [comment]
The key is not being truncated, this is not a DB issue. The particular nameserver is neglecting to put a leading 00 on the second half of the public key.

**Comment by kaosdrachen** [comment]
I stand corrected.

**Comment by Habbie** [comment]
To be clear, it's the 3.x boxes that are wrong here. b995f45 looks like the fix, but it was not backported to 3.4.x yet.

**Comment by Habbie** [comment]
I am verifying this theory now and if so, will backport then.

**Comment by Habbie** [comment]
The theory holds. Backport is in #5114, but merging the backport will break existing setups that happen to have such keys. Unsure how to proceed here.

**Comment by Habbie** [comment]
After rubber ducking this against my wife, the most important thing to do is document. If we do nothing, this disparity exists between 'Debian PowerDNS 3.4.4' and just about every other build, including our static 3.4.x packages and 4.x from any source. So we need to document that changing from Debian to almost anything else will change what your DNSKEYs look like. It strongly reminds one of the situation where one of our crypto backends (Botan I think, but the bug was ours) generated correct signatures, but stored the keys incorrectly in the backend - which only came to light if you tried to use that privkey with a Polar build, which would promptly choke on it. Back then, there was a conversion mechanism. For this issue, there is no conceivable conversion, sadly.

**Comment by zeha** [comment]
Some more context on the Debian versions:
* 3.4.1 in stable is built with crypto++, botan, polar
* 3.4.4, 3.4.6, 3.4.7 (in various backports repositories) were built only with botan and polar
* 4.0.x obv. is built with botan and openssl

**Comment by Habbie** [comment]
@zeha but @kaosdrachen had this Crypto++ issue with 3.4.4 bpo - and I see crypto++ at https://packages.debian.org/wheezy-backports/pdns-server

**Comment by zeha** [comment]
@Habbie must have overlooked the library name there, updated my comment

**Comment by pieterlexis** [comment]
3.4 is EOL, closing.
