### ISSUE TITLE
rec: TCP fast open support

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#5128]
- Program: Recursor
 - Issue type: Feature request 

### Short description
It would be nice to have a `fastopen=<queue size>` directive to enable TCP `Fast Open` on the recursor listening sockets. It should default to 0, meaning disabled.

**Comment by Habbie** [comment]
This request is for both incoming (from clients) and outgoing (to auths) fast open support?

**Comment by rgacogne** [comment]
Incoming-only is way more easy than also adding outgoing support. Both would be nice, but the incoming-only would be good a start!

**Comment by rgacogne** [comment]
Reopening since we still don't have outgoing support.

**Comment by omoerbeek** [comment]
Incoming part done, outgoing part dup of #7982
