### ISSUE TITLE
dnsdist, auth, rec: EDNS COOKIE option busts packet cache?

### ISSUE THREAD

**Issue by edmonds** [PowerDNS/pdns#5131]
Hi,

I noticed that with a packet cache enabled:

```lua
pc = newPacketCache(10000, 86400, 0, 60, 60)
getPool(""):setCache(pc)
```

When I queried this dnsdist server with dig 9.11, the result was always a cache miss, unless I specified `+nocookie` to dig. It looks like dnsdist doesn't support the EDNS COOKIE option, so a query with a COOKIE will always bust the packet cache.

This is with the dnsdist Debian package version 1.1.0-2.

**Comment by rgacogne** [comment]
Hi!

You are right, the packet cache currently hashes the whole query so a query with a cookie will almost never match an existing entry. We should skip the actual cookie content while hashing the query, but I haven't gotten around to it.

**Comment by Habbie** [comment]
Auth (as of 4.1.0-RC1) has the same issue in the packetcache.

**Comment by ahupowerdns** [comment]
As a datapoint, we received a report from an authoritative users of dnsdist that the cache hitrate is going down because of more and more EDNS cookies coming in.

**Comment by danielgriggs** [comment]
It would be nice to get a fix for this.

**Comment by cbuijs** [comment]
Any updates on this? I don't noticed any improvement in 1.4.0 on this?

**Comment by rgacogne** [comment]
No, the packet cache in 1.4.0 is still hashing the whole query.
