### ISSUE TITLE
dnsdist API path confusion

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5134]
- Program: dnsdist
 - Issue type: Bug report

### Short description
1. `/jsonstat` without any `?foo` behind it returns 404, should be something else
2. `/jsonstatx` returns 401 Unauthorized, should be 404. Same for `/api/v1/servers/localhost/stat` and `/api/v1/servers/x`

### Environment

 - Operating system: OpenBSD 6.0
 - Software version: 1.1.0
 - Software source: package via OpenBSD current ports, built on 6.0

### Steps to reproduce
1. enable webserver
2. query either of the mentioned paths

### Expected behaviour
Sensible HTTP codes.

### Actual behaviour
Weird HTTP codes.

**Comment by zeha** [comment]
The 401 gets returned when you passed valid authorisation data?

(In general the 401 should stay when auth data is missing or wrong, no matter if the path exists or not.)

**Comment by Habbie** [comment]
> The 401 gets returned when you passed valid authorisation data?

Yes.

> (In general the 401 should stay when auth data is missing or wrong, no matter if the path exists or not.)

Yes :)

**Comment by pieterlexis** [comment]
for the api this should have been fixed in #5089

**Comment by rgacogne** [comment]
`/jsonstat` should probably not be allowed with an API key, but it looks like there is no other way to retrieve the dynamic blocks (`NMG` and `SMT`) and the `BPF` filters.

**Comment by omoerbeek** [comment]
```
curl -v http://aap:geheim@localhost:8083/blabla 404 Not found
curl -v http://aap:wrong@localhost:8083/blabla 401 Unauthorized
curl -v http://aap:geheim@localhost:8083/jsonstat 404 Not Found
curl -v http://aap:geheim@localhost:8083/jsonstat?foo=bar 404 Not Found
```
Seems like the proper http result codes.
Additionally a valid command gives me data.
