### ISSUE TITLE
Auth `./configure --without-mysql` should disable the gmysql module

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#5140]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

The gmysql module is built by default. I expected that `--without-mysql` would skip everything that requires mysql, but instead the configure script still checks for mysql and exits with an error.

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: master 1efb94eda4f8500c3568c149b9ca4ca5fa74e1fc
 - Software source: github

### Steps to reproduce

1. `./configure --disable-mysql`

### Expected behaviour

Do not build any mysql modules.

### Actual behaviour

The configure scripts do no properly check for the value 'no', which is set by `--without-mysql`:

```
checking for no/bin/mysql_config... configure: error: not found
```

**Comment by pieterlexis** [comment]
I think it will be better to throw an error with the essence of "MySQL is required by one or more of the (dyn-)modules, cannot disable MySQL support"

**Comment by wojas** [comment]
Maybe add "(see --with-modules and --with-dynmodules options)" to the message?
