### ISSUE TITLE
pdns-auth: bind backend: Type native not supported

### ISSUE THREAD

**Issue by Whissi** [PowerDNS/pdns#5149]
- Program: Authoritative
 - Issue type: Bug report (documentation)

### Short description
Imagine you are using the bind backend.
Zone files are created somewhere else. You are using rsync. No need for AXFR or other methods.

According to https://doc.powerdns.com/md/authoritative/backend-bind/

> Master/slave/native configuration
> 
> [...]
> 
> Native
> 
> PowerDNS has the concept of "native" zones that have the type native; in the BIND configuration file.
> These zones are neither a master (no notifies are sent) nor a slave zone (it will never be AXFR'd in). This
> means that the replication mechanism for these zone is not AXFR but out of band, e.g. using rsync.
> Changes to native zones are picked up in the same way as master and slave zones, see Operation.
> 
> note: Any zone with no type set (an error in BIND) is assumed to be native.

you should set `type native;` in this use case.

But when you set 
```
zone "example.org" {
        type native;
        file "/var/lib/powerdns/zones.d/example.org";
};
```
in you *named.conf* which will get parsed by pdns you will get a warning like
```
[bindbackend] Warning! Skipping zone 'example.org' because type 'native' is invalid
```
Dropping *type* which seems possible according to the note will result in
```
[bindbackend] Warning! Skipping zone 'example.org' because it has no type specified
```
So the either there's a bug or documentation is wrong/should be improved.

### Environment
 - Operating system: Debian 9 (Stretch)
 - Software version: pdns-{server,backend-bind} 4.0.3-1
 - Software source: Operating system repository

**Comment by Habbie** [comment]
Fixed in #5115 which was merged 5 days ago. Not backported to 4.0.x yet. Shall we leave this ticket open for the backport request?

**Comment by Whissi** [comment]
Debian 9 isn't yet released but freezed. If the Debian maintainer won't pick up the PR you will get similar bug reports in future. While this should be backported you should add a note that this will require version X.

**Comment by Habbie** [comment]
@zeha thoughts?

**Comment by zeha** [comment]
Doesn't look like a bug that would qualify as release-critical to me, so I'd say ... too late unfortunately.

**Comment by pieterlexis** [comment]
I'll update the docs to say 4.1.0
