### ISSUE TITLE
pdns-auth:  Log incoming NOTIFY

### ISSUE THREAD

**Issue by opeter** [PowerDNS/pdns#5154]
- Program: Authoritative
 - Issue type: Feature request 

### Short description
Auth codebase stopped logging incoming (valid) notifies after 2.9.x.

### Usecase
We want to see the exact time when a NOTIFY comes in.

### Description
In 2.9.x it looked like this:
`Mar 15 14:14:39 ns1 pdns[1363]: Received valid NOTIFY for mydomain.de (id=3193255) from master 192.168.100.1: 2017031500 > 2016122100`
But since ~3.x this is not the behavior anymore, from packethandler.cc it looks like that only invalied notifies make it into the logfile.

**Comment by aj-gh** [comment]
Also noticed this; would appreciate a fix.

**Comment by zeha** [comment]
Got changed in 7f3d870ea26d6c244083a2a4eb353bf74c8d4173

**Comment by Habbie** [comment]
Fixed in #9387
