### ISSUE TITLE
Cleanup or remove preprocessor directives for specific GCC versions

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#5158]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request

### Short description
We still have several occurrences of preprocessor directives dealing with old gcc versions -some of them as old as gcc 2.x- while our usage of C++11 now requires at least 4.7, for example for delegating constructors. We should clean that up.

**Comment by zeha** [comment]
I cannot find any of those, maybe #5775 got rid of all of them?

**Comment by pieterlexis** [comment]
yes! 😄
