### ISSUE TITLE
global lua function, setvariable, not available for pdns-recursor 4.0.4

### ISSUE THREAD

**Issue by clubfest** [PowerDNS/pdns#5167]
If pdns-recursor is loaded with a lua script that contains setvariable() call, as documented by the example script in this commit:
https://github.com/PowerDNS/pdns/commit/99c69ed354fcd9db8870804eeb1879493423e095
, then it causes the error:
STL error ...: attempt to call global 'setvariable' (a nil value)

Looking at the source code for pdns-recursor-4.0.4, I noticed that unlike pdns-recursor-3.7.4 (and the pdns server source code pdns-4.0.3 and pdns-3.4.11), it is missing the file, lua-recursor.cc, where the setvariable function is made global.

**Comment by Habbie** [comment]
Please find `dq.variable` in the docs at https://doc.powerdns.com/md/recursor/scripting/.

**Comment by clubfest** [comment]
Sorry, I didn't see that. Thanks for the info!
