### ISSUE TITLE
dnsdist call addLuaResponseAction error

### ISSUE THREAD

**Issue by stutiredboy** [PowerDNS/pdns#5168]
- Program:  dnsdist-1.1.0
 - Issue type: Bug report

### Short description

From [README](http://dnsdist.org/README/) we found below:

```
addLuaResponseAction(x, func): where 'x' is all the combinations from addPoolRule, and func is a function with the parameter dr, which returns an action to be taken on this response packet. Good for rare packets but where you want to do a lot of processing.
```

but when we call `addLuaResponseAction` in dnsdist.conf, we got exception:

```
Fatal error: [string "chunk"]:44: attempt to call global 'addLuaResponseAction' (a nil value)
```

### Other information

I try to grep this keyword `addLuaResponseAction` in the src code, but found nothing.

Is this a bug or my mistake? 

Thanks.

**Comment by Habbie** [comment]
As far as I can see, this is not available in any released version yet. If you want this feature, you may have to switch to our master branch. https://repo.powerdns.com/ has master packages.
