### ISSUE TITLE
PDNS 4.0.3 with MySql backend A records not found

### ISSUE THREAD

**Issue by Patdundee** [PowerDNS/pdns#5179]
Program: PDNS 4.0.3 with MySql backend

Hi Guys
I am still trying to get this one sorted out.
PDNS 4.0.3
Ubuntu Server 16.04
64 bit
PDNS 4.0.3 installed correctly
I have added records for 2 domains via Power Admin to ensure they are there correctly
I have run PDNS Util for both of the domains which correctly shows 7 records and no errors
However if I search for an A record for the domain it says there is none found even though it is there
DNS Query shows no A records
I have opened 109.224.220.19 in my firewall for DNS queries if you would like to try and see the results
Search for A records for kimboscakes.co.uk or derbyshireweddingevents.co.uk

Any ideas please
Many thanks

**Comment by pieterlexis** [comment]
Hi,

This sounds more like a support question than an actual bug. Please send an email to the [pdns-users mailinglist](https://www.powerdns.com/opensource.html) with your full problem description, your configuration (without passwords), output of `dig`, logs, database contents and other relevant information to receive community support.

**Comment by Patdundee** [comment]
Hi Pieter

 

I have tried sending to the mailing list but it never appears. So, I have come back to here 😊

 

I am even happy to pay someone to ssh in and try to resolve this.

 

Kind regards

Patrick
