### ISSUE TITLE
pdns-backend-bind not existing in repo.powerdns.cm

### ISSUE THREAD

**Issue by yohannprigent** [PowerDNS/pdns#5180]
Hi all,

Currently, there seem to be pdns-backend-bind packages in ubuntu repositories, but there is no pdns-backend-bind on repo.powerdns.com. This is very confusing when you read the doc : https://doc.powerdns.com/md/authoritative/installation/#binary-packages
bind-backend seems to be directly bundled with pdns-server today.
Would it be possible to split this bind-backend ?

**Comment by Habbie** [comment]
This was fixed a long time ago.
