### ISSUE TITLE
forward-zone behavior change 

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#5187]
Somewhere between 3.6.x and 4.0.4 the behavior of forward-zones appears to have changed. In the 3.6.x branch it used to keep track of response times of forwarded zones, so if one of your downstreams when down it would actually depreference it and use any alternative. This can be seen in the trace logs on 3.6.x.

In 4.0.4 the behavior seems to always use the first server in your forward-zone list, before trying the next after the 1500ms network timeout (if the system is completely unresponsive).

Is this a regression or a "how we want it to work now"?

We could proxy our forward zones with dnsdist + health checking locally to get around this if it's a design change.

Thanks,

**Comment by phonedph1** [comment]
I should add it does appear to throttle after server-down-max-fails properly. Most people might be running this at the default setting of 0 though.

**Comment by pieterlexis** [comment]
Hi,

I did not know the behaviour was like that before, during the spring-cleaning, forward-zones were fully broken at some point. This was addressed in #3244, but this did not change how we forward. So it must have been broken before or after that. 

I think we could mark this as a regression, but I can't promise a fix soon.

**Comment by pieterlexis** [comment]
I hoped fa1b87ff63cfe5da19be7b3a21e7b355ef86744f would be the culprit, but it isn't.

note:
We track response times based on the nameserver's name (e.g. ns1.example.com) not it's IP address(es). For forwarded servers, we only have one name.

**Comment by phonedph1** [comment]
Totally crazy, but https://github.com/phonedph1/pdns/commit/c6ecf5ce8fd36fdfbd1369ae4e0416c769d4884f would mimic the previous behaviour.

Sadly I don't know enough about the internals (or C++) to make this something decent myself.

**Comment by pieterlexis** [comment]
Nice solution, It will even work for v6 addresses (39 chars max). Maybe storing the nsspeeds as IP addresses makes more sense in general... This needs some pondering.

**Comment by phonedph1** [comment]
Bit less sketchy: https://github.com/PowerDNS/pdns/commit/f42440341a9ea0c276e777562b2e4b0b718517ed

**Comment by phonedph1** [comment]
Fixed by #6168
