### ISSUE TITLE
[Website] Wrong launch name on 'Generic PostgreSQL backend' 4.x page

### ISSUE THREAD

**Issue by 0xf3f** [PowerDNS/pdns#5191]
The launch name on https://doc.powerdns.com/md/authoritative/backend-generic-postgresql/ is 'pgsql' not 'gpgsql'
(Maybe module name is also wrong IDK)

**Comment by pieterlexis** [comment]
you're right, how did we ever miss this? Care to file a PR correcting this?

**Comment by pieterlexis** [comment]
Fixed in #5192
