### ISSUE TITLE
installation of dns-dist 1.1 on ubuntu xenial using apt-get fails 

### ISSUE THREAD

**Issue by thomas-mangin** [PowerDNS/pdns#5213]
### Overview

 - Program: dnsdist
 - Issue type: Bug report

### Short description

Trying to install dnsdist 1.1 on xenial using apt-get and the official repository fails due to an unresolvable dependency on protobuf.

Changing the version to 1.0 works as the protobuf dependency is new to 1.1

### Environment

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

$ uname -a
Linux dns-leeds 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

(apt-get update has been run)

```
#tail -n1 /etc/apt/sources.list
deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-dnsdist-11 main

# apt-get install dnsdist
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 dnsdist : Depends: libprotobuf8 but it is not installable

```

### Expected behaviour

unicorns !

### Actual behaviour

ponies with plastic horns.

### Other information

I am very sad 😭

**Comment by pieterlexis** [comment]
> deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-dnsdist-11 main

Change `trusty` to `xenial` to upgrade to unicorns from ponies

**Comment by thomas-mangin** [comment]
PEBKAC confirmed on another trusty and xenial hosts - sorry for the noise 🤦‍♂️
