### ISSUE TITLE
pdns_recursor core dumps on illumos/SmartOS

### ISSUE THREAD

**Issue by jussisallinen** [PowerDNS/pdns#5216]
- Program: Recursor
 - Issue type: Bug report

### Short description

pdns_recursor dumps core on illumos based systems.

### Environment

 - Operating system: SmartOS
 - Software version: 4.0.4
 - Software source: pkgsrc 2016Q4

### Steps to reproduce

1. pkgin install pdns-recursor
2. svcadm enable svc:/pkgsrc/pdns-recursor:default

### Expected behaviour

Service going online.
### Actual behaviour

svc.startd[31139]: [ID 636263 daemon.warning] svc:/pkgsrc/pdns-recursor:default: Method "/opt/local/sbin/pdns_recursor --daemon" failed due to signal SEGV.

### Other information

This is same behavior as seen in #4579

**Comment by rgacogne** [comment]
If it's the same issue than #4579, it's very likely fixed in master since 28fe507d1acc3b4fe7b5669caac9f4bd4a516093, as the code is shared between the auth, rec and dnsdist.
