### ISSUE TITLE
dnsdist should reopen sockets after interface or routing change

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#5220]
- Program: dnsdist
 - Issue type: Bug report

### Short description
dnsdist opens sockets for doing queries, but if interfaces or routing changes, the sockets are not reopened, meaning that dnsdist queries go out using wrong interface and possibly wrong source IP. This means they get unanswered, but probe queries are still answered as they reopen new sockets. So we end up with non-responsive UP servers.

### Environment
 - Operating system: Ubuntu
 - Software version: 16.04.02 LTS
 - Software source: PowerDNS

### Steps to reproduce
1. Configure DNSDist with two servers, so that the second server requires a, say, VPN connection.
2. Start dnsdist
3. Check that the second server is down
4. Enable the interface (or connect to VPN)
5. Observe the second server is up

### Expected behaviour
Observe the second server won't reply to real queries.

### Actual behaviour
The real queries would be answered.

**Comment by Gunni** [comment]
I have the same problem on v1.3.3.

I have wired and wifi connected at most times which result in a routing table of:

```
default via 10...1 dev wired proto dhcp metric 100
default via 10...2 dev wifi proto dhcp metric 600
```

When I disconnect the wired connection, that route vanishes (dnsdist enters broken state)
When I reconnect wired connection, that route reappears.

I only listen on localhost, and the listening ports are still listening, but lookups are ignored.

I haven't done extensive testing but I can if it is required.

**Comment by cmouse** [comment]
The root cause of this problem is that dnsdist opens a socket, once, and never reopens it. It would need some way to notify dnsdist that now it would need to reopen the sockets it uses to make things work again.

**Comment by rgacogne** [comment]
IMHO reopening the downstream sockets would be so painful that I would advise to restart dnsdist when the network topology changes.
