### ISSUE TITLE
RPZ CNAME wildcard responses - PowerDNS recursor

### ISSUE THREAD

**Issue by c0ntr1but3** [PowerDNS/pdns#5237]
- Program: Recursor
 - Issue type: Feature request
### Short description

"Wildcard" CNAME redirection from RPZ I believe is what rgacogne called it on IRC when I discussed this with him.

Essentially, I have played with BIND where an equivalent of the "defcontent" that can be specified in the lua config file of recursor allows the following format: *.subdomain.domain.tld

This format will result in a query for a domain in the RPZ specified to be returned ahead of the above default CNAME.  i.e. a query for blocked.domain.tld returns a result via CNAME of blocked.domain.tld.subdomain.domain.tld.

This is useful when using a "walled garden" landing page (which only browsers will actually see) as with a small piece of web server "magic" you're able to extract the first portion of the GET or POST etc and advice the user what domain they tried to access and that it is blocked for whatever reason (standard walled garden, I'll not insult anyone with further detail there) :).

Recursor currently responds to the same query with: "*.subdomain.domain.tld", that being the exact content specified in the "defcontent" field of the lua config file for rpzFile or rpzMaster statements.

### Usecase

RPZ wildcard CNAME responses

### Description

An RPZ response that returns a full domain string in the CNAME for "defcontent" in the lua config file.  

As described in the above short description, I want a query for "some.domain-in.rpz" to be returned with a CNAME of "some.domain-in.rpz.subdomain.domain.tld" where the "defcontent" specified in the lua config is "*.subdomain.domain.tld" etc.  Currently it returns the exact content of "defcontent" in the CNAME response without prepending the queried domain.

Also, wherever else this is relevant to implement please.  I am new to PowerDNS and there may be more than way way to achieve this same outcome that can benefit from this wildcard option.

THANKS!! (in advance)

**Comment by rgacogne** [comment]
The feature is described in section 3.6 "The "Local Data" Action (arbitrary RR types)" of `draft-ietf-dnsop-dns-rpz-00`:

> A special form of Local Data involves a CNAME RR with a wildcarded
   target name.  Wildcards are not valid as CNAME targets in ordinary
   DNS zones.  However, a wildcard in an RPZ Local Data CNAME target
   causes the matching QNAME to be prepended to the target in the
   rewritten response, which communicates this QNAME value to the walled
   garden DNS server for that DNS server's logs.
   For example a policy Local Data action of "CNAME *.EXAMPLE.COM"
   applied to a QNAME of "EVIL.EXAMPLE.ORG." will result in a synthetic
   response that starts with the RR
   "EVIL.EXAMPLE.ORG CNAME EVIL.EXAMPLE.ORG.EXAMPLE.COM".  Resolving the
   CNAME target "EVIL.EXAMPLE.ORG.EXAMPLE.COM" into an RRset of the
   originally requested type generally requires sending a request for
   that type and a QNAME of "EVIL.EXAMPLE.ORG.EXAMPLE.COM" to a DNS
   server for the walled garden, "EXAMPLE.COM".  As usual when a CNAME
   is encountered while computing a response, the response from the
   walled garden DNS server concerning "EVIL.EXAMPLE.ORG.EXAMPLE.COM"
   determines the rest of the final rewritten response.
