### ISSUE TITLE
lazy-recursion workaround confusion in 4.x

### ISSUE THREAD

**Issue by thechile** [PowerDNS/pdns#5251]
I am upgrading our PDNS from old 2.x to latest 4.x. One option we currently use is `lazy-recursion` to handle the below type of scenario where we are authoritative for a domain but delegate a subdomain to a 3rd party. In 2.x this works OK as the lazy option sees were authoritative but loosens the constraints and still allows the server to recurs for the client request onward to the 3rd party nameservers and reply with address.

```
domain.com
www   A    1.2.3.4

public-service.domain.com	CNAME	 	useast1-public.aws-service.domain.com

aws-service.domain.com	NS	 	ns-1293.awsdns-33.org
aws-service.domain.com	NS	 	ns-230.awsdns-28.com
aws-service.domain.com	NS	 	ns-1614.awsdns-09.co.uk
aws-service.domain.com	NS	 	ns-1014.awsdns-62.net
```

In 4.x however the lazy option is gone, name resolution for `public-service.domain.com` fails and i'm not really sure what alternative configuration I can do ?

For example against pdns 2.x

```
$ dig public-service.domain.com

;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16600
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;public-service.domain.com.	IN	A

;; ANSWER SECTION:
public-service.domain.com. 29	IN	CNAME	useast1-public.aws-service.domain.com.
useast1-public.aws-service.domain.com. 29 IN	A	1.1.1.1


```

And against 4.x

```
$ dig public-service.domain.com

; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 20549
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;public-service.domain.com.	IN	A

;; ANSWER SECTION:
public-service.domain.com. 30	IN	CNAME	useast1-public.aws-service.domain.com.
```

I don't think this fits in to the usual definition of split-horizon, but it seems like a common enough scenario that there must be a way to configure it in version 4.x. 

Currently the authoritative server binds to 0.0.0.0:53 and both internal and external clients make requests for `public-service.domain.com`

I'm using the following versions

```
pdns-4.0.3-1pdns.el7.x86_64
pdns-backend-geoip-4.0.3-1pdns.el7.x86_64
pdns-recursor-4.0.4-1pdns.el7.x86_64
pdns-backend-mysql-4.0.3-1pdns.el7.x86_64
```

Is there some magic configuration option i'm missing ?

As per [this](https://github.com/PowerDNS/pdns/issues/421) and [this](http://powerdns.13854.n7.nabble.com/Something-like-lazy-recursion-tp12062p12065.html) I tried putting the recursor server first in line of traffic i.e on 0.0.0.0:53 and have the `forward-zones-file` enabled with all the domains hosted on the authoritative listed like `domain.com=127.0.0.1:5300` but this would result in an open recursor as i want anyone to be able to resolve the `forward-zones` and the forward-zones option doesn't take precedence over the recursive servers `allow-from`. i.e if i have only RFC 1918 addresses in `allow-from` and `forward-zones-file` defined, only the `allow-from` can query the `forward-zones`. 

thank you.

**Comment by phonedph1** [comment]
Perhaps an ALIAS record instead of using a CNAME to achieve the same end result? https://doc.powerdns.com/md/authoritative/howtos/#using-alias-records 

It's not entirely clear why you need to do this though. 

Also I will mention https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/  as your fake examples likely hide useful information and it's not clear what you're actually dig'ing against. The first 2.x example not showing aa=1 seems like your current setup should never work on the public internet?
