### ISSUE TITLE
Trivial bug: outdated link to Bert's blog on "Open Source" page

### ISSUE THREAD

**Issue by justinclift** [PowerDNS/pdns#5259]
Just noticed the link to Bert's blog on the "[Open Source](https://powerdns.com/opensource.html)" page goes to the old blog:

* https://powerdns.com/opensource.html

"bert hubert has a [blog](http://blog.netherlabs.nl) that mentions PowerDNS sometimes" → "bert hubert has a [blog](https://bert-hubert.blogspot.co.uk) that mentions PowerDNS sometimes"

* http://blog.netherlabs.nl (old)
* https://bert-hubert.blogspot.co.uk (new)

Obviously not urgent, but probably pretty simple to fix. :smile:

**Comment by Habbie** [comment]
@ahupowerdns ping

**Comment by pieterlexis** [comment]
fixed
