### ISSUE TITLE
GeoIP backend should support libmaxminddb

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#5268]
- Program: Authoritative
 - Issue type: Feature request

### Short description
To support the new GeoIP2 databases, libmaxminddb support should be added to geoipbackend

**Comment by ebdavison** [comment]
I am in need of this now and would be happy to test.  Is there any sort of plan or timeline for this feature yet?

**Comment by ZE3kr** [comment]
Maxmind will discontinue free GeoIP Lite Legacy before 2019. So it need to support GeoIP2 before that date.

https://support.maxmind.com/geolite-legacy-discontinuation-notice/

**Comment by cmouse** [comment]
Thanks for the timeline info, I'll try and see if I could get it done before that.

**Comment by pieterlexis** [comment]
> Thanks for the timeline info, I'll try and see if I could get it done before that.

If you need some m4 for autoconf, let me know!

**Comment by cmouse** [comment]
m4 detection for libmaxminddb would help I think.

**Comment by cmouse** [comment]
@ebdavison, @ZE3kr either of you willing to test the new pull request?
