### ISSUE TITLE
dnsdist addPoolRule, is src or dst address used for netmask type ?

### ISSUE THREAD

**Issue by thechile** [PowerDNS/pdns#5279]
Hi 

In the dnsdist documentation is says 

```
We can similarly add clients to the abuse server:

> addPoolRule({"192.168.12.0/24", "192.168.13.14"}, "abuse")
```

and further down then says..

```
addPoolRule(netmask, pool): send queries to this netmask to that pool
addPoolRule({netmask, netmask}, pool): send queries to these netmasks to that pool
```

The first example sounds like its filtering using the incoming clients IP to direct traffic to the abuse pool, but the `addPoolRule` examples seem to suggest the rule is based on the destination address/netmask. Can you clarify if src or dst address is used please ?

For my use case i have a server with public/private interfaces and i would like to have one dnsdist process running that will listen to both interfaces and the rule would need to use the dst address to determine which pool to send requests to. 

Thank you.

**Comment by rgacogne** [comment]
`addPoolRule()` is based on the source address, but I agree the documentation is a bit misleading, I'll fix that.
 If you want to route based on the destination address you can do something like:
```
mydest = newNMG()                                                                                                                                                                     
mydest:addMask("192.0.2.1/32")
addAction(NetmaskGroupRule(mydest, false), PoolAction("your pool"))
```
