### ISSUE TITLE
Provide better errors (AXFR)

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#528]
For a domain I get the following error when trying to AXFR:
`Unable to AXFR zone 'domein.nl' from remote 'ipv4 address' (resolver): AXFR chunk with a non-zero rcode 9`

This is in the logs on the master. This could mean NOTAUTH or no access if I understand it correct (from Habbie).

**Comment by cmouse** [comment]
Appears this has been fixed by bf491f9b?

**Comment by Habbie** [comment]
For the slave side at least. Closing this.
