### ISSUE TITLE
Failed at step NAMESPACE spawning /usr/sbin/pdns_server: Invalid argument

### ISSUE THREAD

**Issue by alaues** [PowerDNS/pdns#5285]
Hi, after installation I can't start pdns as service

systemctl start pdns.service
Job for pdns.service failed because the control process exited with error code. See "systemctl status pdns.service" and "journalctl -xe" for details.

journalctl -xe
May 02 15:02:55 pdns_server[21052]: Failed at step NAMESPACE spawning /usr/sbin/pdns_server: Invalid argument

but manual start works

CentOS Linux release 7.3.1611 (Core)

**Comment by rgacogne** [comment]
Please provide the exact version of PowerDNS you are using, the distribution and the kernel version, otherwise we just can't help you. At first sight it looks like a version mismatch between your systemd version and your kernel, but I have nothing concrete to work with, so..

**Comment by alaues** [comment]
May 02 15:27:55 PowerDNS Authoritative Server 4.0.3 (C) 2001-2016 PowerDNS.COM BV
May 02 15:27:55 Using 64-bits mode. Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-4) on Jan 17 2017 08:55:46 by buildbot@c17f0608c0cd.
May 02 15:27:55 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
May 02 15:27:55 Features: openssl lua
May 02 15:27:55 Built-in modules:
May 02 15:27:55 Configured with: " '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc/pdns' '--disable-static' '--disable-dependency-tracking' '--disable-silent-rules' '--with-modules=' '--with-lua' '--with-dynmodules= bind gmysql gpgsql godbc pipe remote geoip ldap lua gsqlite3 tinydns mydns random' '--enable-tools' '--enable-unit-tests' '--enable-systemd' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CPPFLAGS=-DLDAP_DEPRECATED' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'"

Thanks.

**Comment by Habbie** [comment]
> Kernel 3.10.0-042stab120.18

That's an OpenVZ kernel

**Comment by rgacogne** [comment]
Yeah, it's very likely that the kernel doesn't support the features required by systemd.
@alaues, you will have to edit the `pdns.service`, issue a `systemctl daemon-reload` then a restart to find out which feature is causing the issue, removing one line at a time. Best guess would be one or several of these:
* PrivateTmp
* PrivateDevices
* CapabilityBoundingSet
* NoNewPrivileges
* ProtectSystem
* ProtectHome
* RestrictAddressFamilies

Please note that you will have the same issue with other software using the same systemd features if you keep using an old kernel with a recent systemd.

**Comment by alaues** [comment]
I commended PrivateDevices, it solved the issue.
Thanks a lot!

**Comment by Cyborgscode** [comment]
Still happening : 

Dez 22 14:57:36 XXXXXXXXXXXXXXX systemd[19560]: pdns.service: Failed at step NAMESPACE spawning /usr/sbin/pdns_server: Too many levels of symbolic links 

Fedora 25 - Kernel 4.13.16-100.fc25.i686+PAE

**Comment by Cyborgscode** [comment]
neither /tmp nor /var/tmp are symbolic links... (which systemd devs pointed out as the cause of the bug , no idea how that could be one, but for them it is.... )

**Comment by Cyborgscode** [comment]
pdns-4.0.3-1.fc25.i686

**Comment by aiso-net** [comment]
I have this issue with CentOS 7 and Power DNS Auth 4.4.:
Failed at step CAPABILITIES spawning /usr/sbin/pdns_server: Invalid argument
I remark out AmbientCapabilities and then I get Unable to bind UDP socket to '0.0.0.0:53': Permission denied

**Comment by jsoref** [comment]
@aiso-net Please file a new bug (you can reference this one, but this is really way too stale).

Include your kernel version, your systemd version, and any other files that might be relevant (the systemd file and your pdns config files come to mind).

Also, indicate how you installed powerdns...

Offhand, https://bugzilla.redhat.com/show_bug.cgi?id=1366968 seems interesting

**Comment by aiso-net** [comment]
Will do, thanks
