### ISSUE TITLE
dnsdist: use readline instead of libedit on linux?

### ISSUE THREAD

**Issue by piwats** [PowerDNS/pdns#5294]
Hello there!

Thank you very much for PowerDNS and dnsdist! You are awesome!

**Concerning dnsdist-1.1.0:**

I am writing a Gentoo specific ebuild, so dnsdist gets into the Gentoo portage tree, too.

There I stumbled upon a problem while building dnsdist, especially in regard to libedit/readline.

Either I do install libedit and its headers, which allows the dnsdist sources to configure without any problems, or I let dnsdist compile against readline (which is the default on Gentoo), by setting the LIBEDIT_CFLAGS and LIBEDIT_LIBS accordingly.

Setting the LIBEDIT_CFLAGS and LIBEDIT_LIBS helps to suppress the error, when libedit is not found.

However, when proceeding, I get  an error telling me that the readline headers are not found.

```
dnsdist.cc:33:31: fatal error: editline/readline.h: No such file or directory
```

The same error should be expected to pop out, should the compilation reach dnsdist-console.cc.

This is due to how the needed headers are defined in dnsdist.cc and dnsdist-console.cc:

In dnsdist.cc it's:

```
#if defined (__OpenBSD__)
#include <readline/readline.h>
#else
#include <editline/readline.h>
#endif
```
and in dnsdist-console.cc:

```
#if defined (__OpenBSD__)
#include <readline/readline.h>
#include <readline/history.h>
#else
#include <editline/readline.h>
#endif
```
If I now patch those two files during the install, so it is going to look like (if it were building on OpenBSD)
```
#include <readline/readline.h>
```
and
```
#include <readline/readline.h>
#include <readline/history.h>
```
everything builds and installs fine and seems to work, too.

In the docs about how to compile, a requirement of libedit/readline is not stated as such, however the configure script does check for libedit. (And, the dnsdist rpm build script requires readline-devel: https://github.com/PowerDNS/pdns/blob/master/build-scripts/build-dnsdist-rpm).

The main question: libedit or readline? (and why is there no --with-readline or comparable switch in configure?)

Thank you very much in advance :)

Ps.: #4072 seems to be related.

**Comment by rgacogne** [comment]
Hi @piwats,

Thank you for taking the time to write an ebuild!
I don't remember the exact details (@zeha?) but we decided at some point to use `libedit` instead of `readline`. It caused an issue on `OpenBSD` because `libedit` wasn't available, hence the current code to build with `readline` there.
I think it would provide a more consistent experience to just use `libedit` on `Gentoo` too, unless there is a good reason not to.

**Comment by piwats** [comment]
@rgacogne, thank you very much for your reply.

I want to be able to offer a USE-flag to choose to use libedit as an option (since it seems to be possible). 

Also, Gentoo uses readline by default, hence, given its minimalist nature, why depend on an extra lib when there is one already present seeming to do the same thing.

**Comment by zeha** [comment]
@rgacogne `readline` is GPLv3.

**Comment by piwats** [comment]
Ooops, my fault. This is the classic GPLv2 linking to GPLv3 Problem.

However, Gentoo is not a binary distribution per se, therefore the same thing done when compiling on OpenBSD (e.g. linking) can be done in the same manner on Gentoo, too. A binary redistribution yields a problem, though - and this is known in Gentoo, too, for there is a 'bindist' USE-flag.

**Comment by piwats** [comment]
Independent from the licensing point of view, are there any changes in functionality or undesirable behavior when compiled against readline?

**Comment by rgacogne** [comment]
I don't think so, no.

**Comment by piwats** [comment]
May I ask you a question not related to libedit/readline, since I'm writing the ebuild for Gentoo:

Do you use the asan, msan, tsan, lsan & ubasn in the production build? (Or let me ask this another way: what are the ./configure options for production use preferred?

**Comment by rgacogne** [comment]
No, please don't enable any sanitizer on a production build. Apart from enabling `dnscrypt` support (provided  that you have `libsodium`) and perhaps `re2` if you have it, I think the defaults are fine.

**Comment by piwats** [comment]
I think I am almost complete with the ebuild, except for one last point:

when building with sodium, protobuf and re2. What should be the default behavior when one of those libraries gets updated? Is it to rebuild dnsdist again?
