### ISSUE TITLE
rec: set protobuf requestorId from Lua

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#5295]
- Program: Recursor 
 - Issue type: Feature request 

### Short description

`dnsmessage.proto` has a `requestorId` field that can be used to log a username or other relevant requestor ID with a request, but it is missing a Lua API to set it.

### Usecase

The requestorId is meant for logging additional information about the requestor. Depending on the setup, this could be a username, MAC address, etc. This is a free format string field.

The field needs to be settable from the Lua code in `gettag()` and other callbacks.

### Description

I am not completely clear when the protobufs are sent out, so I'm not sure which Lua callbacks need to be able to set this field.

Since request for different requestorIds could be served from the same packet cache entry, I believe it has to be set from `gettag()`. Since this callback does not have access to `dq`, it probably has to be added as yet another optional return value:

```lua
function gettag(remote, ednssubnet, local, qname, qtype, ednsoptions)
    ...
    local requestorId = 'foo'
    return 0, policyTags, dqdata, requestorId
end
``` 

If no such value is returned, or its value is `nil`, the requestorId field should not be added to the protobuf.
This change is backward compatible, as existing code does not return this fourth return value.

If it makes sense to add this functionality to other callbacks, it should be added to the `dq` object:

 * `dq:getRequestorId()` would return the current value (not sure we need this call)
 * `dq:setRequestorId(somestring)` would set or replace the value

Example:

```lua
function preresolve(dq)
    dq:setRequestorId('foo')
    ...
end
```

The `requestorId` MUST be set on the response protobuf. Additionally, it COULD be set on the query protobuf, but that one might already have been sent out by the time Lua processes it.

**Comment by rgacogne** [comment]
I think #4569 will address this once merged.

**Comment by rgacogne** [comment]
Closing since #4569 has been merged.
