### ISSUE TITLE
Unattended upgrade on Ubuntu 16.04 using PowerDNS repo

### ISSUE THREAD

**Issue by asosso** [PowerDNS/pdns#5299]
* Program: Authoritative
* Issue type: Bug report

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: 0.0.1632g39cab2d-1pdns.xenial (master branch)
 - Software source: repo.powerdns.com

### Short description

Ubuntu unattended upgrade break **pdns-server** (0.0.1632g39cab2d-1pdns.xenial) because is upgrading to ubuntu package version (4.0.0~alpha2-3build1)
Why the new version from PowerDNS repo is using an inferior number?

### Steps to reproduce

**Step 1**

Ensure repo.powerdns.com configuration

```
root@resolver2:~# cat /etc/apt/sources.list.d/pdns.list
deb [arch=amd64] http://repo.powerdns.com/ubuntu xenial-auth-master main

root@resolver2:~# cat /etc/apt/preferences.d/pdns
Package: pdns-*
Pin: origin repo.powerdns.com
Pin-Priority: 600
```

**Step2** 

Install pdns-server 

```
apt-get install pdns-server pdns-backend-mysql

root@resolver2:~# dpkg -l | grep pdns
ii  pdns-backend-mysql                   0.0.1632g39cab2d-1pdns.xenial              amd64        generic MySQL backend for PowerDNS
ii  pdns-server                          0.0.1632g39cab2d-1pdns.xenial              amd64        extremely powerful and versatile nameserver
```

**Step 3**

Wait a new build from repo.powerdns.com, for example `0.0.1636gdcb1a6f-1pdns.xenial`

**Step 4**

Do `/usr/bin/unattended-upgrade` manually or wait Ubuntu unattended upgrade

### Expected behaviour

pdns-server is upgraded to pdns-server=0.0.*

### Actual behaviour

pdns-server is upgraded to 4.0.0~alpha2-3build1

```
root@resolver2:~# /usr/bin/unattended-upgrade -d -v --dry-run
Initial blacklisted packages:
Initial whitelisted packages:
Starting unattended upgrades script
Allowed origins are: ['o=Ubuntu,a=xenial', 'o=Ubuntu,a=xenial-security']
[...]
adjusting candidate version: 'pdns-backend-mysql=4.0.0~alpha2-3build1'
adjusting candidate version: 'pdns-server=4.0.0~alpha2-3build1'
[...]

```

### Other information

**First pdns install (from apt history log)**

```
Start-Date: 2017-04-22  17:28:40
Commandline: apt-get install pdns-server=0.0.1632g39cab2d-1pdns.xenial pdns-backend-mysql
Install: pdns-server:amd64 (0.0.1632g39cab2d-1pdns.xenial), pdns-backend-mysql:amd64 (0.0.1632g39cab2d-1pdns.xenial), libluajit-5.1-2:amd64 (2.0.4+dfsg-1, automatic), libluajit-5.1-common:amd64 (2.0.4+dfsg-1, automatic), libsodium18:amd64 (1.0.8-5, automatic)
End-Date: 2017-04-22  17:28:43
```

**Unattendend upgrade by ubuntu (from apt history log)**

```
Start-Date: 2017-04-24  15:13:10
Commandline: /usr/bin/unattended-upgrade
Install: dbconfig-mysql:amd64 (2.0.4ubuntu1, automatic), dbconfig-common:amd64 (2.0.4ubuntu1, automatic), liblua5.3-0:amd64 (5.3.1-1ubuntu2, automatic)
Upgrade: pdns-server:amd64 (0.0.1632g39cab2d-1pdns.xenial, 4.0.0~alpha2-3build1), pdns-backend-mysql:amd64 (0.0.1632g39cab2d-1pdns.xenial, 4.0.0~alpha2-3build1)
[...]
End-Date: 2017-04-24  15:13:14
```

**apt-get upgrade it works**

```
root@resolver2:/etc/apt/preferences.d# apt-get upgrade --dry-run | grep pdns

Inst pdns-server [0.0.1632g39cab2d-1pdns.xenial] (0.0.1636gdcb1a6f-1pdns.xenial PowerDNS:repo.powerdns.com [amd64])
Inst pdns-backend-mysql [0.0.1632g39cab2d-1pdns.xenial] (0.0.1636gdcb1a6f-1pdns.xenial PowerDNS:repo.powerdns.com [amd64])
Conf pdns-server (0.0.1636gdcb1a6f-1pdns.xenial PowerDNS:repo.powerdns.com [amd64])
Conf pdns-backend-mysql (0.0.1636gdcb1a6f-1pdns.xenial PowerDNS:repo.powerdns.com [amd64])
```

**Comment by pieterlexis** [comment]
What are your `/etc/apt/preferences.d/*' for all PowerDNS related packages?

**Comment by pieterlexis** [comment]
>  Why the new version from PowerDNS repo is using an inferior number?

We use 0.0.0 for Master packages because of the way we develop the software. Mostly because we ship several products (auth, recursor, dnsdist) from a single source repository.

**Comment by asosso** [comment]
> What are your `/etc/apt/preferences.d/*' for all PowerDNS related packages?

I've only the preference for pdns-* packages 

```
root@resolver2:~# ls /etc/apt/preferences.d/pdns
/etc/apt/preferences.d/pdns
```

```
root@resolver2:~# cat /etc/apt/preferences.d/pdns
Package: pdns-*
Pin: origin repo.powerdns.com
Pin-Priority: 600
```

**Comment by pieterlexis** [comment]
Hrm, interesting. This should be good enough. Can you show me an `apt-cache policy pdns-server`?

I think this issue might stem from the fact that repo.powerdns.com is not in `Unattended-Upgrade::Origins-Pattern` in `/etc/apt/apt.conf.d/50unatteded-upgrades` and makes it ignore the pin set (would be a Debian/Ubuntu bug in apt then). 

Can you add `"origin=repo.powerdns.com"` to the `Unattended-Upgrade::Origins-Pattern` configuration key in `/etc/apt/apt.conf.d/50unatteded-upgrades` and retry?

**Comment by asosso** [comment]
> Can you show me an apt-cache policy pdns-server?

Installed version is `0.0.1636gdcb1a6f-1pdns.xenial`

```
root@resolver2:~# apt-cache policy pdns-server
pdns-server:
  Installed: 0.0.1636gdcb1a6f-1pdns.xenial
  Candidate: 0.0.1640g8c5dc03-1pdns.xenial
  Version table:
     4.0.0~alpha2-3build1 500
        500 http://it.archive.ubuntu.com:80/ubuntu xenial/universe amd64 Packages
     0.0.1640g8c5dc03-1pdns.xenial 600
        500 http://repo.powerdns.com/ubuntu xenial-auth-master/main amd64 Packages
 *** 0.0.1636gdcb1a6f-1pdns.xenial 100
        100 /var/lib/dpkg/status
```

> Can you add "origin=repo.powerdns.com" to the Unattended-Upgrade::Origins-Pattern configuration key in /etc/apt/apt.conf.d/50unatteded-upgrades and retry?

I've inserted in `/etc/apt/apt.conf.d/50unattended-upgrades` the following lines of code

```
Unattended-Upgrade::Origins-Pattern {
        "origin=repo.powerdns.com";
};
```

And re-run **unattended-upgrade**

```
root@resolver2:~# /usr/bin/unattended-upgrade -d -v --dry-run
Initial blacklisted packages:
Initial whitelisted packages:
Starting unattended upgrades script
Allowed origins are: ['o=Ubuntu,a=xenial', 'o=Ubuntu,a=xenial-security', 'origin=repo.powerdns.com']
adjusting candidate version: 'dpkg=1.18.4ubuntu1'
adjusting candidate version: 'libsystemd0=229-4ubuntu10'
adjusting candidate version: 'libudev1=229-4ubuntu10'
adjusting candidate version: 'linux-generic=4.4.0.75.81'
adjusting candidate version: 'linux-headers-generic=4.4.0.75.81'
adjusting candidate version: 'linux-image-generic=4.4.0.75.81'
adjusting candidate version: 'pdns-backend-mysql=4.0.0~alpha2-3build1'
adjusting candidate version: 'pdns-server=4.0.0~alpha2-3build1'
[...]
```

**repo.powerdns.com** is now added to ***Allowed origins***

But the package will upgrade to 4.0.0

```
adjusting candidate version: 'pdns-backend-mysql=4.0.0~alpha2-3build1'
adjusting candidate version: 'pdns-server=4.0.0~alpha2-3build1'
```

**Comment by zeha** [comment]
Origin for powerdns.com packages is `PowerDNS`, not `repo.powerdns.com`.

I'd suggest adding `o=PowerDNS,n=xenial-auth-master` to the unattended-upgrades config.

**Comment by asosso** [comment]
Thank you @zeha 

I've added the following lines to `/etc/apt/apt.conf.d/50unattended-upgrades`

```
Unattended-Upgrade::Origins-Pattern {
        "o=PowerDNS,n=${distro_codename}-auth-master";
};
```

Then i've ran unattended-upgrade

```
root@resolver2:~# dpkg -l | grep pdns
ii  pdns-backend-mysql                   0.0.1636gdcb1a6f-1pdns.xenial              amd64        generic MySQL backend for PowerDNS
ii  pdns-server                          0.0.1636gdcb1a6f-1pdns.xenial              amd64        extremely powerful and versatile nameserver

root@resolver2:~# /usr/bin/unattended-upgrade

root@resolver2:~# dpkg -l | grep pdns
ii  pdns-backend-mysql                   0.0.1640g8c5dc03-1pdns.xenial              amd64        generic MySQL backend for PowerDNS
ii  pdns-server                          0.0.1640g8c5dc03-1pdns.xenial              amd64        extremely powerful and versatile nameserver
```

Great! pdns-server was upgraded to latest release! 

Do you think cloud be useful add this step on https://repo.powerdns.com > Ubuntu > Ubuntu 16.04 "Xenial Xerus"?

**Comment by pieterlexis** [comment]
I don't believe that adding these instructions makes sense. Configuring unattended-upgrades is out of scope for the repo site

**Comment by asosso** [comment]
@pieterlexis unattended upgrades are enabled by default on Ubuntu 16.04. Of course, is out of scope, but it can potentially break an Authoritative PowerDNS server

**Comment by pieterlexis** [comment]
I think you'll have to select that during the installation though :)
