### ISSUE TITLE
[lua-recursor4.o] Error 4

### ISSUE THREAD

**Issue by Xchainer** [PowerDNS/pdns#5301]
- Program: Recursor 
 - Issue type: Bug report

### Short description

When I try to compile the recursor on Ubuntu 14.04 I get the following error:

>   CXX      json.o
>   CXX      lua-recursor4.o
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
> make[2]: *** [lua-recursor4.o] Error 4
> make[2]: Leaving directory `/home/xchainer/pdns/pdns/recursordist'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/home/xchainer/pdns/pdns/recursordist'
> make: *** [all] Error 2

### Environment

 - Operating system: Ubuntu 14.04
 - Software version: 
 - Software source: Master branch 

### Steps to reproduce

1. 
2. 
3.

**Comment by rgacogne** [comment]
Could you please look at your logs? It looks like the kernel killed your compiler, probably because you were out of memory.

**Comment by Xchainer** [comment]
I was indeed out of memory, but this would still be problematic on servers that don't have a lot of RAM memory and the possibility to create swapfiles is disabled.

**Comment by pieterlexis** [comment]
then please use packages, we cannot make the compiler use less memory without substantial changes to the code
