### ISSUE TITLE
dnsdist with setECSOverride not showing client remote IP in pdns_auth logs

### ISSUE THREAD

**Issue by thechile** [PowerDNS/pdns#5302]
Hi,

I am using dnsdist in front of pdns_auth and i would like the client src address to be carried forward to auth so it can be seen in logs and used by geo backend. But from from output of `journalctl -xe -f -u pdns` i still see the the local servers public interface address, `202.xx.xx.xx`, shown as the remote i.e.

```
Remote 202.xx.xx.xx wants 'domaina.com|A', do = 0, bufsize = 512: packetcache HIT
```

I am using below 

```
pdns-4.0.3-1pdns.el7.x86_64
pdns-backend-geoip-4.0.3-1pdns.el7.x86_64
dnsdist-0.0.1551g8c5dc03-1pdns.el7.x86_64
pdns-recursor-4.0.4-1pdns.el7.x86_64
pdns-backend-mysql-4.0.3-1pdns.el7.x86_64
```

With dnsdist config:
```lua
local onfe_ipaddr = "202.xx.xxx.xx"
local hostname    = "xxx-xxx-dns01"

setECSOverride(true)
setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)

newServer{address=onfe_ipaddr .. ":5353", source="eth1", name=hostname .. "-authoritative", order=1, checkName="hosted_zone.com.", useClientSubnet=true, pool="axfr"}
addAction(OrRule({QTypeRule(dnsdist.SOA), QTypeRule(dnsdist.AXFR), QTypeRule(dnsdist.IXFR)}), PoolAction("axfr"))

```

pdns_auth config
```
edns-subnet-processing=yes
```

From what i could find i thought this would preserve incoming clients address so pdns_auth. Did i miss any configuration or misunderstand the options ?

thank you.

**Comment by paddg** [comment]
Did you set `useClientSubnet=true` in `newServer()` ?

**Comment by thechile** [comment]
@paddg yes thanks, i forgot to mention that. I've updated issue with this configuration.

**Comment by paddg** [comment]
> `Remote 202.xx.xx.xx wants ...`
I guess the journal does simply not show the ECS, thogh it is in the query. But I don't know how to make it visible. You could use Wireshark to look into the packets. This is likley not a bug and rather a topic for the pdns-uders mailinglist I fear.

**Comment by thechile** [comment]
i started some ec2 instances in EMEA and NCSA to test a server based in APAC... but regardless of the region i'm testing from it always resolved to the APAC geo result which i assume is because pdns_auth is seeing itself own public address as proxied from dnsdist. 

As soon as i removed dnddist from the chain and put pdns_auth back listening on public_interface:53 then geo lookups work as expected and from EMEA i get the correct emea result.

So either the configuration i am using is wrong or there is a bug. 

I tried turning auth logging up to 9 and log dns queries but i can't see anything useful.

**Comment by thechile** [comment]
bah! sorry. **hangs head in shame** I had `useClientSubnet` on named pool but not default pool. Works now.
