### ISSUE TITLE
API allows CNAMEs to be created when an existing record with the same name is present

### ISSUE THREAD

**Issue by dajones70** [PowerDNS/pdns#5305]
- Program: PowerDNS API 
 - Issue type: Bug report 

### Short description

The PowerDNS API allows for adding a CNAME when a record by the same name already exists.

### Environment

 - Operating system: CentOS 7
 - Software version: pdns-4.0.3-1pdns.el7.x86_64 and others
 - Software source: PowerDNS repository 

### Steps to reproduce

1. Create a test A record 
2. Use the API to add a new record of the same name 
3. PowerDNS API adds it to the backend 

### Expected behaviour

PowerDNS API should not allow a CNAME to be added.

**Comment by degubellini** [comment]
Hi,
just for completion, this is happening too with
- Operating system: Ubuntu 16.04.2 LTS
- Software version:  pdns-server, 4.0.3-1pdns.xenial, amd64
- Software Repository: PowerDNS repository

**Comment by rfc1036** [comment]
Is this related to https://github.com/PowerDNS/pdns/issues/5365 ?

**Comment by Habbie** [comment]
> Is this related to #5365 ?

No - did you mistype the number?

**Comment by rfc1036** [comment]
No, nevermind then.
