### ISSUE TITLE
nodnssec-3.x_to_3.4.0_schema.*sql.sql migrations are buggy

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#5310]
- Program: Authoritative
 - Issue type: Bug report

### Short description

https://github.com/PowerDNS/pdns/commit/b0e315d96a9113e799a4c68c46fcb523d528f3ac is buggy (#1651)
The commit has two main parts:
* modify schema for dnssec to change domainmetadata to varchar(32)
* define default schema for nodnssec with domainmetadata to varchar(32)

Unfortunately, my system (and potentially many others) predates this schema, and isn't dnssec.

That means my code might want to handle varchar(32), but my schema is still stuck at varchar(16).

### Environment

 - Operating system: debian 8.8
 - Software version: pdns-backend-pgsql                                    4.0.3-1pdns.jessie
 - Software source: pdns repo

### Steps to reproduce
1. install very old pdns (pgsql backend)
2. install newer pdns (pgsql backend)
3. run nodnssec-3.x_to_3.4.0_schema.pgsql.sql

### Expected behaviour
schema should support:
```sql
pdns=# insert into domainmetadata(domain_id, kind, content) values(2, 'ALLOW-DNSUPDATE-FROM', '127.0.0.1/32');
```

### Actual behaviour
```sql
ERROR:  value too long for type character varying(16)
```

### Usecase

Trying to prepare for `nsupdate` by declaring domains to be restricted to localhost for updates

**Comment by jsoref** [comment]
Fwiw, https://doc.powerdns.com/3/authoritative/upgrading/#database-schema is also impacted...

**Comment by Habbie** [comment]
Turns out to have been pilot error. Closing.
