### ISSUE TITLE
DNSDIST-MIB::dynBlockNMGSize - Counter or Gauge?

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#5311]
Hi,

I am running 0.0.1551g8c5dc03-1pdns.jessie with SNMP support enabled. It looks very promising (thanks) and I would like to integrate dnsdist into our Cacti environment. While browsing the MIB tree I have noticed that there is also dynBlockNMGSize entry present and it is identified as a Counter type:

`snmpwalk   -v 2c -c dnsdist42 rzt-lvs1  DNSDIST-MIB::dynBlockNMGSize
DNSDIST-MIB::dynBlockNMGSize.0 = Counter64: 47
`
What is the exact meaning of this entry? Is it the number of current entries in dynamically blocked entries? If yes, it the counter type the right one? The value above is just increasing in time. How does it work?

Thanks
A.

**Comment by rgacogne** [comment]
Hi Aleš,

Our MIB defines it as a `CounterBasedGauge64`, so it should be interpreted as a Gauge, not a Counter, but I have heard that some tools lack proper support for that case. Most of the time it's only a cosmetic issue, but I'll be interested in getting any feedback you can have. Unfortunately, as far as I know, `SNMP` doesn't offer a better way of defining a 64-bit Gauge.

It's indeed the number of entries in the Dynamic Block, but including expired ones. The current implementation doesn't remove expired entries for performance reason, they are just ignored, so yes it's just going to keep increasing at the moment.

**Comment by rygl** [comment]
Hi Remi.
Yes, thanks. I have already found in specs that there are some limitations in 64-bit Gauge in `SNMP`. As you say, it is just an cosmetic issue.

Your explanation of entries in the Dynamic Block makes it clear now. Anyway, let me ask a question: The active entries (only) in dnsdist gui are visible so there is a way how to distinguish them from expired ones so wouldn't be possible do the same in SNMP?

Thanks
Regards
Aleš

**Comment by rgacogne** [comment]
> The active entries (only) in dnsdist gui are visible so there is a way how to distinguish them from expired ones so wouldn't be possible do the same in SNMP?

You're right, but it has a cost since it requires walking the internal tree they are stored in, so unless someone really needs that badly I don't think it's worth it. Especially since the same stats are exported by Carbon and the web server, so they might be polled quite frequently.

**Comment by rgacogne** [comment]
Closing this since the initial question has been answered.
