### ISSUE TITLE
Please add logging/dumping options for RPZ 

### ISSUE THREAD

**Issue by tmuncks** [PowerDNS/pdns#5333]
Please consider adding a few logging/dumping options to the RPZ functionality of the recursor, to provide better insight into operation as well as troubleshooting.

Off the bat, here are a few examples of what would be useful, at least to me...

- The ability to log RPZ hits
- The ability to dump the effective RPZ 
- The ability to log IXFR added and removed domains (perhaps this is already available with debug logging?)

/Thomas

**Comment by rgacogne** [comment]
Quick update:
* RPZ hits can be logged via protobuf, including the name of the matched policy (and the type as of #5621)
* Support for dumping RPZ content has been submitted in #5620 
* Added and removed domains were already logged at Debug level, #5622 adds an option to log them at Info level
