### ISSUE TITLE
Recursor git head fails to build on Ubuntu Xenial

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5347]
Since 531bc0d6fcb78e023229b2a8bae816609f4faf27 we fail to build on Ubuntu Xenial. I spent a good 30 minutes before I realized it wasn't just me. This very much looks like a g++ bug in Xenial having to do with thread_local of std::unique_ptr and linking.

 - Program: Recursor
 - Issue type: Bug report

### Short description
Although this is a g++ bug (extremely likely at least), we may have to work around it. A suggestion I've seen is to have a getMT() function so you never need 'extern thread_local std::unique_ptr<MT_t>'.

### Environment
Ubuntu Xenial 16.04.4

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce
Compile from git master.

1. 
2. 
3.

**Comment by ahupowerdns** [comment]
gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66971

**Comment by rgacogne** [comment]
Fixed by #5350.
