### ISSUE TITLE
Compile pdns against LuaJIT 2.1 Beta3 fails

### ISSUE THREAD

**Issue by IngoThierack** [PowerDNS/pdns#5348]
- Program: Authoritative
 - Issue type: Bug report

If i try to compile the pdns against the latest LuaJIT 2.1 i get the following error.

```
  CXX      lua-iputils.o
lua-iputils.cc: In function ‘void luaL_setfuncs(lua_State*, const luaL_Reg*, int)’:
lua-iputils.cc:46:68: error: ‘void luaL_setfuncs(lua_State*, const luaL_Reg*, int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup) {
                                                                    ^
In file included from lua-iputils.cc:28:0:
/opt/lib/LuaJIT/2.1/include/luajit-2.1/lauxlib.h:88:18: error: previous declaration of ‘void luaL_setfuncs(lua_State*, const luaL_Reg*, int)’ [-fpermissive]
 LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
                  ^
```

Issue is known on LuaJIT.
https://github.com/LuaJIT/LuaJIT/issues/325
Conclusion is, this kind of function-namespace should never used outside of the Lua VM. So it look's like it must be fixed in pdns.

### Environment
 - Operating system: Centos 7
 - Software version: 4.0.3
 - Software source: compiled from source

**Comment by ahupowerdns** [comment]
Ingo, could you try https://github.com/PowerDNS/pdns/compare/master...ahupowerdns:lua-namespace-clean?expand=1 ?
