### ISSUE TITLE
Lua newDS:check() method does not match upper level domain if subdomain is added before upper level domain

### ISSUE THREAD

**Issue by sq9mev** [PowerDNS/pdns#5352]
- Program: Recursor
 - Issue type: Bug report

### Short description

Lua newDS:check() method does not match upper level domain if subdomain is added before upper level domain.

### Environment

 - Operating system: Linux
 - Software version: 4.0.4
 - Software source: compiled myself and Archlinux repository as well, own compiled pdns-recursor binary running PLD Linux compiled with ./bootstrap ;./configure --prefix=/opt/… --with-lua; make; make install and  PLD-Linux packet prepared by myself.

### Steps to reproduce
1. Create lua script:

```
domains = newDS()

domains:add("www.example.com")
domains:add("example.com")

function check_domain(domain)
        pdnslog('Checking domain: ' .. domain)
        domainname = newDN(domain)

        if (domains:check(domainname)) then
                pdnslog('Domain ' .. domain .. ' found', pdns.loglevels.Warning)
        else
                pdnslog('Domain ' .. domain .. ' NOT found', pdns.loglevels.Warning)
        end
end

pdnslog('domains in suffix match group: ' .. domains:toString(), pdns.loglevels.Warning)

check_domain("example.com")
check_domain("www.example.com")
check_domain("generic.example.com")
```

2. Run pdns recursor: pdns_recursor  --daemon=no --quiet=no
3. Reload lua script using: reload-lua-script $lua_script_path

### Expected behaviour
I'd expect domains:check(domainname) would return true for all of the three domains added to domains newDS.

### Actual behaviour
Only one domain, www.example.com return true when checked agains domains newDS:

```
May 29 12:32:01 domains in suffix match group: www.example.com., example.com.
May 29 12:32:01 Checking domain: example.com
May 29 12:32:01 Domain example.com NOT found
May 29 12:32:01 Checking domain: www.example.com
May 29 12:32:01 Domain www.example.com found
May 29 12:32:01 Checking domain: generic.example.com
May 29 12:32:01 Domain generic.example.com NOT found
May 29 12:32:01 0 (Re)loaded lua script from '/etc/pdns-recursor/lua/hazard-bug.lua'
```

### Other information
Version 4.0.5-rc1 compiled myself works as expected, but i could not find any issue describing above problem.

**Comment by rgacogne** [comment]
Hi! It has been fixed between 4.0.4 and 4.0.5-rc1 by https://github.com/PowerDNS/pdns/pull/5025 but you would need to know that `newDS()` internally uses a `SuffixMatchNode()` to connect the dot, so it's not easy :-)
