### ISSUE TITLE
Public KSK and ZSK storing

### ISSUE THREAD

**Issue by vsaveliev** [PowerDNS/pdns#5356]
Hi guys,

Sorry me for this question. I work with domain registries directly so I need to use 'pdnsutil add-zone-key ...' with different algorithms. I cannot find an equivalent for this command in your REST API. I can use this command but I don't want to have using a shell command in my code. **Please help me with the question:**

**Where does the program store public KSK and ZSK?** (can I get it from REST API? from **database or some files on file system?** I checked 'cryptokeys' table but found only private KSK and ZSK keys)

Thank you for help.

**Comment by Habbie** [comment]
@vsaveliev hello! When you made a new ticket, you were shown a template for filing your issue. It looks like you just deleted the template and entered your concerns. Can you please update your ticket to use our template? You can find it at https://github.com/PowerDNS/pdns/blob/master/.github/ISSUE_TEMPLATE.md

Closing this ticket until it uses the template, sorry!

**Comment by vsaveliev** [comment]
I found my problem already. Thanks.

**Comment by Habbie** [comment]
Ok! Glad to hear it.
