### ISSUE TITLE
SortList doesn't respect CNAME and A records ordering

### ISSUE THREAD

**Issue by killerwhile** [PowerDNS/pdns#5357]
- Program: Recursor
 - Issue type: Bug report

### Short description

When using the Lua sortList feature, responses with CNAME and A records do not respect  RFC1034 section 4.3.1 (A record last RR). https://github.com/PowerDNS/pdns/issues/4339 and https://github.com/PowerDNS/pdns/pull/4340 reported similar behaviour but it seems to still happen when sortList is used.

### Environment

 - Operating system: Centos7
 - Software version: 4.0.4-1
 - Software source: PowerDNS repository

### Steps to reproduce

1. Create a file `/etc/pdns-recursor/sortList-test.lua` with the following content:
```
-- www.noisette.ch: return 87.98.177.202/32 as the first ip in any case.
addSortList("0.0.0.0/0", {"87.98.177.202/32"})
```

2. Add the following line to your config
```
lua-config-file=/etc/pdns-recursor/sortList-test.lua
```

3. ensure your `/etc/resolv.conf` query the right server

4. Run `getent hosts www.noisette.ch`. This doesn't return anything, but prints the following in syslog: `getent: gethostby*.getanswer: asked for "www.noisette.ch", got "noisette.ch"`

### Expected behaviour
I would expect to have the ip address of the domain returned, just like `nslookup` or `host` 
(which seems more permissive than gethostby) commands do:
```
$ host www.noisette.ch
noisette.ch has address 87.98.177.202
www.noisette.ch is an alias for noisette.ch.
```

### Actual behaviour
tcpdump'ing the traffic shows that the A rr comes before the CNAME record, which is not right.

**Comment by Habbie** [comment]
Sidenote: your getent (so your libc?) is broken and you should report that to your distribution or to upstream.

**Comment by killerwhile** [comment]
@Habbie libc seems to be more picky on the RFC than other tools, but pdns still sort too many RR when used with SortList feature.

**Comment by killerwhile** [comment]
The PR listed above works fine for me. Thanks!
