### ISSUE TITLE
Backport request form custom pgsql connections parameters

### ISSUE THREAD

**Issue by porbas** [PowerDNS/pdns#5364]
- Program: Authoritative
 - Issue type: Feature (backport) request

### Short description
I want custom pgsql connections parameters to allow timeout first configured pgsql backend before DNS client get timeout from powerdns auth server. I hope I can satisfy request via second configured pgsql backend (natively replicated).

There is #4711 merged into master. Could you please backport it into 4.0.x?

I was asked to create this issue in #4711

**Comment by Habbie** [comment]
Are you aware that you can just stick these flags in any of the other pg configuration fields? From memory, something like `gpgsql-host=127.0.0.1 flag1=foo flag2=bar`'

**Comment by porbas** [comment]
I'm not aware. I'll give it a try!

**Comment by porbas** [comment]
@Habbie yes, it works :+1: 

      gpgsql-host=ip.addr.of.postgres connect_timeout=2

Is this "undocumented feature"? Should I worry for it to disappear in future releases?

**Comment by Habbie** [comment]
In 4.0.x this will not disappear. In 4.1.0 you will have #4711!

**Comment by porbas** [comment]
Thanks a lot. This issue can be closed. With this workaround there is no need to backport #4711 into 4.0.x

**Comment by Habbie** [comment]
:+1:
