### ISSUE TITLE
Consistency IPv6 configure options

### ISSUE THREAD

**Issue by blauwblaatje** [PowerDNS/pdns#5368]
- Program: Authoritative, Recursor 
 - Issue type: Feature request 
### Short description
Consistency in IPv6 options

### Usecase
Have consistency in configs between Auth and Rec.

### Description
Authoritative has this option:
```
  --local-ipv6=...
	Local IP address to which we bind
```

where as Recursor accepts IPv6 in `--local-address`.

I think it would be clearer and more logical if both applications use the same options for the same features. 

```
12:24 < Evo--> just random interest question. Why does the authoritative server have the option 
               local-ipv6, but the recursor has ipv6 in local-address? 
12:24 < ahu> because we've been working on this stuff for 18 years now
12:24 < ahu> and we are sadly not always consistent
12:25 < Evo--> fair enough
12:26 < Evo--> I was just wondering :) 
12:27 < lieter> we could try to remove local-ipv6 in auth 4.1
12:27 < ahu> consistency between auth and recursor has never been an explicit goal
12:27 < lieter> sure, but is could point to some code duplication though :)
```

**Comment by Habbie** [comment]
Update: auth 4.3 accepts v4+v6 in local-address, and combines query-local-address and query-local-address6. In 4.4, we'll remove the old options.

**Comment by Habbie** [comment]
Once auth 4.4 is branched, we need to redo #9552 on master for 4.5.

**Comment by omoerbeek** [comment]
Rec part is done in #9554
