### ISSUE TITLE
Adding forwarded zones to the recursor fails with "Could not find domain"

### ISSUE THREAD

**Issue by wrouesnel** [PowerDNS/pdns#5376]
- Program: Recursor
 - Issue type: Bug report

### Short description
I'm trying to add forwarded zones to a recursor with a command like the following:
```json
{
    "id": ".",
    "kind": "Forwarded",
    "name": ".",
    "recursion_desired": true,
    "servers": [
    	"10.11.11.1"
    ]
}
```
i.e. equivalent to if I did the following on the command line - `--forward-zones-recurse=.=10.11.11.1`

But the server keeps kicking back an error and not loading the zone - 
```json
{
  "error": "Could not find domain '.'"
}
```
Which, yes, obvious because there's no root level servers this recursor can contact?

Is there a way to add forward zones with the REST API that'll give me this flexibility?

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: PowerDNS Recursor 4.0.4
 - Software source: PowerDNS repository

### Steps to reproduce
1. Make the necessary directories (I did this inside of docker) - `mkdir -p /run/log /data/recursor`
1. Start `pdns_recursor` with this config file:
```
api-key=changeme
api-logfile=/run/log/pdns-api
api-readonly=no
api-config-dir=/data/recursor

config-dir=/etc/powerdns
config-name=

daemon=no

# Changed from default to allow: 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12
dont-query=127.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32

reuseport=yes

query-local-address=0.0.0.0

# Enables IPv6 support explicitely.
query-local-address6=::

reuseport=yes

# Disabled: will not be reachable.
security-poll-suffix=

# Needed (see dont-query above)
serve-rfc1918=yes

setgid=pdns
setuid=pdns

socket-dir=/var/run
socket-owner=pdns
socket-group=pdns
socket-mode=0774

udp-truncation-threshold=4096

webserver=yes
webserver-address-0.0.0.0
webserver-password=
webserver-port=8080

write-pid=no
```
2. Try and create a zone with the Rest API (I used Postman to do this)
```
{
    "id": "root",
    "kind": "Forwarded",
    "name": ".",
    "recursion_desired": true,
    "servers": [
    	"10.11.11.1"
    ]
}
```

### Expected behaviour
Forward zone is created, loaded and visible under `api/v1/servers/localhost/zones` and DNS queries are forwarded to that zone.

### Actual behaviour
Zone creation failed - 
```
{
  "error": "Could not find domain '.'"
}
```

### Other information
The zone files are created successfully under the `api-config-dir`, but they're not loaded by recursor after the request completes.

### Usecase
I want to be able to fully reconfigure a recursor's query forwarding via the REST API, and start it with no command line parameters describing "upstream" recursors initially.

### Description
Ideally a recursor would start up "blank" and then be given its full forwarding / upstream configuration via the REST API.

**Comment by wrouesnel** [comment]
Okay I have resolved this but it's a documentation problem - since the `api-config-dir` calls the reload functions normally, it also needs a blank `forward-zones` and `forward-zones-recurse` parameter set, and then `include-dir` MUST point to the same location as `api-config-dir` in order to be reloaded.

**Comment by Habbie** [comment]
Agree, docs should be better on this. Your "Could not find domain" error is confusing though, I wonder if we could do better there.
