### ISSUE TITLE
Raspbian architecture error on repositories

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5385]
![image](https://user-images.githubusercontent.com/1223657/26903392-3de6d3b4-4bdd-11e7-94f1-bc8c2585a92f.png)
"Bert architecture shown in the Raspbian install notes should be armhf not amd64"
https://twitter.com/natmorris/status/872573140915945472

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by pieterlexis** [comment]
fixed!
