### ISSUE TITLE
unexpected round robin behavior

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#54]
When I repeatedly query for type all on a host that has multiple A records ie:"dig mx1.hotmail.com any" I get the expected round robin behavior.

When I run the following "dig mx1.hotmail.com a" repeatedly the results are always in the same order.  This is also true when I run "dig hotmail.com mx".

I have configured my packet-cache with a 0 second ttl, in hopes of resolving the behavior, but without success.

My pdns_server and pdns_recursor were built from code downloaded via subversion when changeset 551 was the most current release.

This was brought to my attention by customer's that were having dificulty sending mail to HotMail.  When they use a different resolver (not one of mine) their problems sending to HotMail cease.

If there is more information that I can provide to facilitate this request, please let me know.  I am also willing to allow recursion to an ip for testing on one of my DNS servers if it will help.

I appreciate any help that you may be able to offer.

**Comment by amjkwd** [comment]
> 
> 
> **Author: ahu**
> Fixed in commit 567, this was a 2.9.19 regression.

Hello, my version is 4.0.9 and still got a certain replay from multiple A records. I had read lots of document pages about pdns options since I found the round robin description here https://doc.powerdns.com/authoritative/changelog/pre-4.0.html?highlight=robin#version-2-9-13. But still can't solve my problem. Need help please.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.
