### ISSUE TITLE
Raspbian on repo.powerdns.com - 1.1.x and master

### ISSUE THREAD

**Issue by natm** [PowerDNS/pdns#5418]
- Program: dnsdist 
 - Issue type: Feature request

### Short description

Please can a 1.1.x release be added to the raspbian section on repo.powerdns.com? currently only 1.0.x is available.

Master for raspbian has also not been updated since 2016.

### Environment
 - Operating system: Raspbian GNU/Linux 8 (jessie)
 - Software version: 8 (jessie)
 - Software source:  PowerDNS repository

### Expected behaviour
- 1.1.x section added
- master package for raspbian kept up to date

**Comment by Habbie** [comment]
has been added now. Feedback is welcome!
