### ISSUE TITLE
REST API complains of "no change" if "records" field is not an array

### ISSUE THREAD

**Issue by wrouesnel** [PowerDNS/pdns#5419]
- Program: Authoritative
 - Issue type: Bug report

### Short description
If you send a PATCH request to a zone, rrset objects that do not contain a `"comments"` key will be rejected with an error like `"No change for RRset 71.64.84.10.in-addr.arpa. IN PTR"` despite having a valid `changetype` field.

This is due to the validation here: https://github.com/PowerDNS/pdns/blob/41fb54b887ad2b08a06edd874ecde8d69e2d54f3/pdns/ws-auth.cc#L1408 which requires the `"comments"` field to be specified as an empty array.

### Environment
 - Operating system: Linux x86_64
 - Software version: 4.0.3
 - Software source: PowerDNS Ubuntu Repository

### Steps to reproduce
1. Send a REST request to a PowerDNS zone like follows;
```
{ "rrsets" : [
  {
    "records": {
      "content": "host.example.", 
      "ttl": 60,
      "priority": 0,
      "disabled": false
    }, 
    "changetype": "REPLACE", 
    "type": "PTR", 
    "ttl": 60,
    "name": "71.64.84.10.in-addr.arpa."
  }
]
}
```

### Expected behaviour
The record is either updated, or the error message correctly indicates the reason for the problem (missing "comments" field which must be an array).

### Actual behaviour
Returns the following:
```json
{
  "error": "No change for RRset 71.64.84.10.in-addr.arpa. IN PTR"
}
```

### Other information
See here:
https://github.com/PowerDNS/pdns/blob/41fb54b887ad2b08a06edd874ecde8d69e2d54f3/pdns/ws-auth.cc#L1408

This validation logic suppresses an opportunity to explain the problem in the error message, and seems overly strict for the actual operation (as "comments" may be blank) but in either case is extremely uninformative (as I had to check the source code to figure out why the request was rejected).

The REST API documentation also does not document this requirement.

**Comment by zeha** [comment]
The error message could be better, but in your case the problem is that "records" in your request is not an array. "comments" is allowed to be missing.

**Comment by Habbie** [comment]
Can you update the description given @zeha's comment?

**Comment by wrouesnel** [comment]
Closing due to my fairly obvious error once I wrote it down :)
