### ISSUE TITLE
search-data api call with type argument returning rrsets or comments or both or none

### ISSUE THREAD

**Issue by mimianddaniel** [PowerDNS/pdns#5430]
- Program: Authoritative 
 - Issue type: Feature request 

### Short description

Using search-data for a large number of zones takes forever due to recursive calls per id for records and comments. There should be an option for limiting either record or comment array or both or none as an option in the argument when calling search-data. 
eg: type=z will return zone info only, type=r returns only records and no comments, type=c returns comments only,  and type=a will return all 
'search-data?q=*&max=10000&type=z'  

i have 'working patch' I came up with quickly and by no means it's production ready code as I am not a C++ programmer but it solves my problem querying all the zones to compare when necessary without timing out.
https://jpst.it/104Oo

would be awesome if upstream can modify and implement it properly. 

### Environment

 - Operating system:  centos 
 - Software version:  4.0.1
 - Software source:  PowerDNS repository, compiled yourself and patched for above 

### Steps to reproduce

1. 
2. 
3. 

### Expected behaviour

api/v1/servers/localhost/'search-data?q=*&max=1000000'  | jq . returns all the data without timing out 

### Actual behaviour

times out 
### Usecase

only return top zone data and selectively choose the records 
### Description

only return top zone data

**Comment by Habbie** [comment]
Hello, thank you for your contribution! Can you turn it into a Github Pull Request so we can do proper code review on it? We tend to forget about external patches hidden in issues.
