### ISSUE TITLE
Q: Is `pdnsutil secure-zone -- -example.com` stable?

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#5431]
This is a question I'm posting upon Habbie's request on IRC, so I'm not following the usual guidelines.

If you have a domain that starts with a dash, like -example.com, `pdnsutil secure-zone -example.com` exits with "Error: unrecognised option". `pdnsutil secure-zone -- -example.com` helps. Habbie says this behavior comes form boost::program_options, but I could not find it documented on http://www.boost.org/doc/libs/1_63_0/doc/html/program_options.html.

Is this trick stable / supported?

(`pdns_control notify -example.com` exits with "syntax: notify domain", regardless of adding `--` or surrounding things with quotes. That can be worked around though by using the API.)

**Comment by mind04** [comment]
pdns_control notify '\-example.com'
pdns_control notify '\045example.com'

both translate to -example.com

**Comment by Habbie** [comment]
I'm having trouble identifying the behaviour inside boost::program_options but it definitely is there. Note @mind04's alternative syntaxes that also both work with pdnsutil.

I'm closing this ticket. If you ever find that `--` no longer works, please report it and we will consider it a bug.
