### ISSUE TITLE
Undefined symbol error on Debian 9

### ISSUE THREAD

**Issue by MDXDave** [PowerDNS/pdns#5432]
After upgrade to debian 9, i got the following error when starting powerdns:

> Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so: undefined symbol: _ZN10DNSBackend3getER13DNSZoneRecord

I use MariaDB 10.2.6 and pdns-backend-mysql 0.0.1705g98356ba-1pdns.stretch

How to fix this issue? Had no problem before debian upgrade

**Comment by Habbie** [comment]
Hello,

can you show: 
* `dpkg -l | grep pdns`
* `grep -r module-dir /etc/powerdns`

please?

**Comment by MDXDave** [comment]
Sorry, seems that something goes wrong when updating pdns, because the installed version was for debian jessie. Works now!

**Comment by Habbie** [comment]
:+1:
