### ISSUE TITLE
dnssec validation dnsdist

### ISSUE THREAD

**Issue by H3ik0** [PowerDNS/pdns#5435]
Maybe I'm wrong.

When I want to activate dnssec validation I need to do this:
> newServer({address="2001:888:2000:1d::2", pool="dnssec"})
> newServer({address="2a01:4f8:110:4389::2", pool="dnssec"})
> setDNSSECPool("dnssec")
> topRule()

but then I get:  `Fatal error: invalid key to 'next'
` How can I bind the root.key file?
Thank you.

**Comment by ahupowerdns** [comment]
@H3ik0 - can you come to IRC? Our issue tracker is not very suitable as a support forum. Please see https://www.powerdns.com/opensource.html for how to get there.
