### ISSUE TITLE
auth 4.0.4 libatomic configure error on ppc64

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#5456]
Full buildlog:
https://kojipkgs.fedoraproject.org//work/tasks/5577/20115577/build.log

checking whether the linker accepts -latomic... no
configure: error: Unable to link against libatomic, cannot continue

Any ideas?

Note: This issue affects only ppc64

**Comment by pieterlexis** [comment]
We tried to make the libatomic stuff _better_ (see https://github.com/PowerDNS/pdns/commit/03571f7ac3d5bebb4879849b094e2e03f019cd10), not worse. Can you verify that ppc64 needs libatomic? It could be this is only required for 32 bit ppc?

**Comment by mortenstevens** [comment]
@pieterlexis 
I'm not sure. But I guess we need it. 

Here is the build for ppc64le and that works fine with libatomic.
See: https://kojipkgs.fedoraproject.org//work/tasks/5575/20115575/build.log

**Comment by mortenstevens** [comment]
@pieterlexis 

I have reverted commit 03571f7ac3d5bebb4879849b094e2e03f019cd10 but now it fails to build because of configure: error: ldap library (libldap) not found...

**Comment by Habbie** [comment]
@mortenstevens can you provide config.log for the ldap failure?

**Comment by mortenstevens** [comment]
@Habbie 
I guess this is not possible. We have only API based access to Fedora build servers.  Maybe this issue is related to autoreconf. Here is the downstream patch/changes:

https://src.fedoraproject.org/cgit/rpms/pdns.git/commit/?id=45b67cca332cf46c5867b107a3e9c8f9dd28fbcd

It's building fine on all archs except ppc64 with the new ldap configure error... So I dont't know. See: https://koji.fedoraproject.org/koji/taskinfo?taskID=20125464

Actually we have pdns-4.0.3 in our stable and I guess the best thing is to wait for an upstream patch. If you need to test a patch just send it to me and I can do a scratch build to verify if it works on ppc64.

**Comment by Habbie** [comment]
@mortenstevens can you add a libatomic dependency for ppc64 and see if that builds?

**Comment by tjikkun** [comment]
Since ppc64 doesn't need libatomic, I guess the final fix could be:
```diff
diff --git a/m4/pdns_check_os.m4 b/m4/pdns_check_os.m4
index df05dc2..ba6546d 100644
--- a/m4/pdns_check_os.m4
+++ b/m4/pdns_check_os.m4
@@ -36,7 +36,7 @@ AC_DEFUN([PDNS_CHECK_OS],[
   AM_CONDITIONAL([HAVE_SOLARIS], [test "x$have_solaris" = "xyes"])
 
   case "$host" in
-  mips* | powerpc* )
+  mips* | powerpc-* )
     AC_MSG_CHECKING([whether the linker accepts -latomic])
     LDFLAGS="-latomic $LDFLAGS"
     AC_LINK_IFELSE([m4_default([],[AC_LANG_PROGRAM()])],
```

**Comment by mortenstevens** [comment]
@tjikkun 

Thank you. Good catch. I have updated your patch that it applies cleanly to the 4.0.x branch. https://src.fedoraproject.org/cgit/rpms/pdns.git/plain/pdns-fix-ppc64.patch

It's now building fine.
