### ISSUE TITLE
failed to start on debian 9

### ISSUE THREAD

**Issue by light-angel** [PowerDNS/pdns#5459]
After updateing to debian 9 i cant get pdns to start agen i just keep getting this error in the logs

```
svm44336:~ /etc/init.d/pdns start
[....] Starting pdns (via systemctl): pdns.serviceJob for pdns.service failed because the control process exited with error code.
See "systemctl status pdns.service" and "journalctl -xe" for details.
 failed!
svm44336:~ systemctl status pdns.service
● pdns.service - PowerDNS Authoritative Server
   Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2017-06-25 20:57:32 BST; 690ms ago
     Docs: man:pdns_server(1)
           man:pdns_control(1)
           https://doc.powerdns.com
  Process: 16941 ExecStart=/usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --write-pid=no (code=exited, status=203/EXEC)
 Main PID: 16941 (code=exited, status=203/EXEC)

Jun 25 20:57:32 svm44336.vps.tagadab.com systemd[1]: pdns.service: Main process exited, code=exited, status=203/EXEC
Jun 25 20:57:32 svm44336.vps.tagadab.com systemd[1]: Failed to start PowerDNS Authoritative Server.
Jun 25 20:57:32 svm44336.vps.tagadab.com systemd[1]: pdns.service: Unit entered failed state.
Jun 25 20:57:32 svm44336.vps.tagadab.com systemd[1]: pdns.service: Failed with result 'exit-code'.

"journalctl -xe

-- Unit pdns.service has begun starting up.
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[17132]: pdns.service: Failed at step EXEC spawning /usr/sbin/pdns_server: Operation not permitted
-- Subject: Process /usr/sbin/pdns_server could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The process /usr/sbin/pdns_server could not be executed and failed.
--
-- The error number returned by this process is 1.
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[1]: pdns.service: Main process exited, code=exited, status=203/EXEC
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit pdns.service has failed.
--
-- The result is failed.
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[1]: pdns.service: Unit entered failed state.
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[1]: pdns.service: Failed with result 'exit-code'.
```

Environment

 - Operating system:  upgrade from debian 8 to debian 9
 - Software version: pdns-backend-mysql(4.0.3-1).
pdns-server  (4.0.3-1).

 - Software source: apt-get 

Expected behaviour
upgrade server and start

Actual behaviour
upgrade server and failing to start

### Other information
have 3 other servers with the same setup all upgrade find and working well

**Comment by pieterlexis** [comment]
Hi,

Please show us the output of `dpkg -l | grep pdns` and do not use the init-script on systemd, but use `systemctl` for service control

**Comment by light-angel** [comment]
svm44336:~# dpkg -l | grep pdns
ii  pdns-backend-bind                    4.0.3-1                          amd64        BIND backend for PowerDNS
ii  pdns-backend-mysql                   4.0.3-1                          amd64        generic MySQL backend for PowerDNS
ii  pdns-server                          4.0.3-1                          amd64        extremely powerful and versatile nameserver

**Comment by pieterlexis** [comment]
These are packages from the debian repository. I think something went wrong with the upgrade of the system and not with PowerDNS. I would suggest re-installing the packages and retrying to start it

This error suggests that *something* is hosed after the upgrade.

```
Jun 25 20:58:19 svm44336.vps.tagadab.com systemd[17132]: pdns.service: Failed at step EXEC spawning /usr/sbin/pdns_server: Operation not permitted
```
I am closing this issue as this is not a PowerDNS bug but a (Debian?) support issue.

**Comment by stbuehler** [comment]
AppArmor / SELinux involved? Resource limits on your VM? Try searching for `"Failed at step EXEC spawning" "Operation not permitted"`
