### ISSUE TITLE
dnsdist: MacAddrAction() relies on a stub on !__linux__

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#5467]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

`getMACAddress()` in misc.cc is a stub implementation on everything but `__linux__`.

Therefore `MacAddrAction` can't work on non-linux platforms.

I can see various options to deal with this:

* ifdef-out MacAddrAction on !`__linux__`
* implement getMACAddress everywhere
* document limitations
* ...

**Comment by rgacogne** [comment]
The documentation has been updated, and there is no standard way of getting this information so I guess it's going to stay that way for now.
