### ISSUE TITLE
What DNS does PDNS query if there are multiple DNS domains in the domain?

### ISSUE THREAD

**Issue by quizjungle** [PowerDNS/pdns#5495]
- Program: Recursor 
 - Issue type: Feature questions 

### Short description

What DNS does PDNS query if there are multiple DNS domains in the domain?
For example, Netflix has four authoritative name servers.
dig +short NS netflix.com
ns-1372.awsdns-43.org.
ns-659.awsdns-18.net.
ns-81.awsdns-10.com.
ns-1984.awsdns-56.co.uk.

In this case,
When I look up the netflix.com domain in the PDNS, does the PDNS query through any of the four netflix name servers above?
Or does PDNS query the most responsive nameservers of multiple nameservers and tell me the results?

I want to know if a domain has multiple Auth DNS and PDNS responds sensitively when it contains slow DNS.

Thanks!

**Comment by pieterlexis** [comment]
This is described in [the documentation](https://doc.powerdns.com/md/recursor/internals/#actual-dns-algorithm).

Basically, if we don't know how fast any authoritative server is, we pick one at random and cache the latency in the [nsspeed cache](https://doc.powerdns.com/md/recursor/performance/#recursor-caches). The next time we need to look up something, we grab the fastest nameserver.

Next time, please read the template, as this is a support question that should be asked on the mailing list.

**Comment by quizjungle** [comment]
Pieterlexis, thank you for your reply.
And I apologize for breaking the rules here.
Next time I have a question, I'll use the mailing list.
thank you!
