### ISSUE TITLE
API is not working with ARPA zone?

### ISSUE THREAD

**Issue by bitency** [PowerDNS/pdns#5503]
I'm trying to get a ARPA zone with the PowerDNS api but there are no results.

```
curl -H 'X-API-Key: changeme' http://x:8081/api/v1/servers/localhost/zones/96.72.37.in-addr.arpa. | jq .
```

Internal Server Error

Or with double dot:

```
curl -H 'X-API-Key: changeme' http://x:8081/api/v1/servers/localhost/zones/96.72.37.in-addr.arpa.. | jq .
```

```
{"error": "Unable to parse DNS Name '96.72.37.in-addr.arpa..'"}
```

From the zone list API command:

```
 "url": "api/v1/servers/localhost/zones/96.72.37.in-addr.arpa.",
    "id": "96.72.37.in-addr.arpa.",
    "name": "96.72.37.in-addr.arpa.",
```

PowerDNS version: 4.0.4 
Centos 7.3 64 bit

Fresh install from the PDNS Centos 7 REPO.

**Comment by Habbie** [comment]
Anything in the logs?

**Comment by Habbie** [comment]
Can you run `pdnsutil check-zone 96.72.37.in-addr.arpa` please?

**Comment by mind04** [comment]
96.72.37.in-addr.arpa.. double dot

**Comment by bitency** [comment]
My apologies! White space in the end of the SOA record 👎
