### ISSUE TITLE
dnsdist: getTSEnd() and getTSStart() return wrong timestamps

### ISSUE THREAD

**Issue by bjoe2k4** [PowerDNS/pdns#5507]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

getTSEnd() and getTSStart() are supposed to return unix timestamps of the start- and end-date of the dnscrypt certificates, but the values are wrong.

### Environment

 - Operating system: Archlinux
 - Software version: dnsdist 0.0.g6c3281444
 - Software source: dnsdist-git from AUR

### Steps to reproduce

1. Setup dnsdist with dnscrypt and certificates in place, according to the docs
2. Run the following commands on the console:

```
> showDNSCryptBinds()
#   Address              Provider Name        Serial   Validity              P. Serial P. Validity
0   [::1]:8443           2.dnscrypt-cert.loca 12       2017-07-08 23:14:41   11        2017-07-08 22:37:48

> getDNSCryptBind(0):getCurrentCertificate():getSerial()
12

> getDNSCryptBind(0):getOldCertificate():getSerial()
11
```
So let's check the
### Expected behaviour

```
> getDNSCryptBind(0):getCurrentCertificate():getTSEnd()
1499548481

> getDNSCryptBind(0):getOldCertificate():getTSEnd()
1499546268
```
### Actual behaviour

```
> getDNSCryptBind(0):getCurrentCertificate():getTSEnd()
1095459161

> getDNSCryptBind(0):getOldCertificate():getTSEnd()
2621595993
```

**Comment by zeha** [comment]
Looking at the code, the values are unix timestamps, but in network byte order.

**Comment by Habbie** [comment]
Looking at the values in the ticket, this theory holds up :)

**Comment by bjoe2k4** [comment]
I am certainly no expert, but wouldn't it be more practical to be able to interact with lua's `os.time()` directly? If not, how to convert the values in lua?
