### ISSUE TITLE
Recursor: `dump-cache` does not dump RRSIG records

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#5510]
- Program: Recursor
 - Issue type: Bug report

### Short description
When using `rec_control dump-cache`, the RRSIGs are not dumped to the file. This makes debugging DNSSEC issues very hard.

### Environment

 - Software version: master and 4.0.x

### Expected behaviour
RRSIGs in the cache dump.

### Actual behaviour
No RRSIGs in the cache dump

**Comment by rgacogne** [comment]
Fixed in master by #5511.
