### ISSUE TITLE
powerdns dlz configure 

### ISSUE THREAD

**Issue by zhxiaom5** [PowerDNS/pdns#5531]
so,how to configure powerdns to act like bind dlz.
eg:
some client resolve domain and get a.a.a.a
and other client resolve same domain and get b.b.b.c
do i need to use lua or c to develop it,or powerdns has already support it(i cant search any help assosited to dlz)
thanks

**Comment by pieterlexis** [comment]
Hi,

This sound like a support question, not a bug or feature request. This is not the right place to ask these questions. Please use the [mailinglists](https://mailman.powerdns.com/mailman/listinfo/pdns-users).

Please be as complete as possible with real IP addresses and domain names in your email.
