### ISSUE TITLE
Not able to add CNAME record

### ISSUE THREAD

**Issue by seemakaloor** [PowerDNS/pdns#5544]
Hi,

I am not able to add a CNAME record in powerdns. 

My requirement is to direct 'domain.com'requests to 'www.domain.com'. I have already added a Ä"record for 'www.domain.com'. Now I am trying to add the CNAME record.

I do this from the power admin GUI, in the box for name <>.asista.com, I leave it blank. In the box for content, I provide <www>.asista.com.

But the GUI is returning error that "blank CNAME records are not allowed".

Please guide how to add the CNAME record to direct "domain.com"requests to "www.domain.com".

Regards,
Seema

**Comment by Habbie** [comment]
Hello Seema,

this is not a support forum. You are welcome to come try our IRC channel or mailing lists via https://www.powerdns.com/opensource.html, but please understand that we are PowerDNS, not PowerAdmin.
