### ISSUE TITLE
Invalid DNSSEC signatures for empty responses with DNS 0x20

### ISSUE THREAD

**Issue by jsha** [PowerDNS/pdns#5546]
At Let's Encrypt, we use an Unbound recursive resolver with DNSSEC validation enabled, and [DNS 0x20](https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00) (use-caps-for-id in unbound). We've gotten reports of problems from a couple of users who have PowerDNS as their authoritative resolvers:

https://community.letsencrypt.org/t/powerdns-cant-find-why-caa-servfails/38127
https://community.letsencrypt.org/t/help-diagnosing-caa-failures-ns1-cyso-nl/38461

Specifically, it seems that DNSSEC validation fails when a mixed-case query is made and the response is empty. There's some plausible speculation on our forum and on the [unbound-users mailing list](https://unbound.nlnetlabs.nl/pipermail/unbound-users/2017-July/004836.html) that this is because PowerDNS is signing a response containing the mixed-case qname, rather than downcasing before signing.

Caching seems to play a confounding role: If a downcased CAA query was sent first, the signed, cached response will validate, and subsequent mixed-case queries will get that valid response until it expires.

**Comment by Habbie** [comment]
Hello @jsha, thank you for your report! This was fixed in git master by #5377, which was backported to 4.0.x in #5378 and then released as 4.0.4. In other words, affected users running 4.0.3 or lower should upgrade to 4.0.4 and try again. Users running master should not be affected today.

Will leave this open for a bit in case somebody has conflicting experiences.

**Comment by jsha** [comment]
Thanks for the prompt response! I'll convey this to the affected parties and see if upgrading helps.

**Comment by jsha** [comment]
I've gotten one report from an affected party that upgrading to 4.0.4 fixed it. Closing. Thanks again. As an FYI I've requested Ubuntu [backport the fix into Xenial](https://bugs.launchpad.net/ubuntu/+source/pdns/+bug/1705766), and a helpful community member has filed a [similar bug for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869222).

**Comment by Habbie** [comment]
Those PR numbers were wrong. The backport is https://github.com/PowerDNS/pdns/pull/5289/commits/b91cfe5c069df975176f5fd944540f72fc5d01bb
