### ISSUE TITLE
PowerDNS 4.0.4 fails to build with boost 1.64

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#5547]
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -DSYSCONFDIR=\"/etc/pdns\" -DPKGLIBDIR=\"/usr/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -fasynchronous-unwind-tables -pie  -pthread   -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o dnsreplay base32.o base64.o dnslabeltext.o dnsname.o dnsparser.o dnspcap.o dnsrecords.o dnsreplay.o dnswriter.o ednssubnet.o ednsoptions.o logger.o misc.o nsecrecords.o qtype.o rcpgenerator.o sillyrecords.o statbag.o unix_utility.o -lcrypto  -lboost_program_options 
make[3]: *** [Makefile:2566: dnsbulktest.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:2566: dnstcpbench.o] Error 1
libtool: link: g++ -DSYSCONFDIR=\"/etc/pdns\" -DPKGLIBDIR=\"/usr/lib/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -fasynchronous-unwind-tables -pie -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o dnsreplay base32.o base64.o dnslabeltext.o dnsname.o dnsparser.o dnspcap.o dnsrecords.o dnsreplay.o dnswriter.o ednssubnet.o ednsoptions.o logger.o misc.o nsecrecords.o qtype.o rcpgenerator.o sillyrecords.o statbag.o unix_utility.o  -lcrypto -lboost_program_options -pthread
make[3]: Leaving directory '/builddir/build/BUILD/pdns-4.0.4/pdns'
make[2]: *** [Makefile:2131: all] Error 2
make[2]: Leaving directory '/builddir/build/BUILD/pdns-4.0.4/pdns'
make[1]: Leaving directory '/builddir/build/BUILD/pdns-4.0.4'
make[1]: *** [Makefile:551: all-recursive] Error 1
make: *** [Makefile:483: all] Error 2

Full buildlog
https://kojipkgs.fedoraproject.org//work/tasks/896/20680896/build.log

**Comment by zeha** [comment]
Appears to be a bug in boost: https://svn.boost.org/trac10/ticket/12516

**Comment by mortenstevens** [comment]
@zeha

Thank you. Here is my the Fedora bug against our boost package: https://bugzilla.redhat.com/show_bug.cgi?id=1474105

After patching boost it's fixed and pdns 4.0.4 builds fine against boost 1.64 see the latest buildlogs:

https://koji.fedoraproject.org/koji/buildinfo?buildID=921224

# closed
