### ISSUE TITLE
Please add grpc backend support

### ISSUE THREAD

**Issue by wenerme** [PowerDNS/pdns#5555]
[grpc](https://grpc.io/) is A high performance, open-source universal RPC framework, with official [C](https://github.com/grpc/grpc) implement. Implement a service in gRPC is easier to implement a rest service to match the rest backend.

**Comment by Habbie** [comment]
Hello,

we are having trouble understanding what you are asking. Furthermore, we have a very nice feature request template that you apparently decided to fully ignore. I am closing this, please feel free to file again with more context and information.

**Comment by wenerme** [comment]
gRPC I mean something like remotebackend, remotebackend support http, more like a jsonrpc.

grpcbackend defined a [service protocol](https://developers.google.com/protocol-buffers/docs/proto3#services), and act as a service client, so, we can use the pre-defined service protocol to generate service stub, it's easier to implement a interface instead a restful api.

BTW, grpc's performance is way better than http.
