### ISSUE TITLE
DNSDIST-MIB::blockFilters missing

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#5561]
Hi,
I have noticed that the counter DNSDIST-MIB::blockFilters is not present in the MIB tree any more (0.0.1662g638dd3d-1pdns.jessie). Was it removed intentionally or is it a bug? 

Thanks
With regards
Ales

**Comment by rgacogne** [comment]
Hi Aleš,

The `blockfilter` feature was removed in #5514 because it had become redundant while being slower than most of the alternatives (C++-based rules).

**Comment by rygl** [comment]
Hi Remi, thanks for explanation.
