### ISSUE TITLE
debian/control Build-Depends line lacks curl and pandoc

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5585]
- Program: Authoritative
 - Issue type: Bug report

### Short description
`VERSION=4.0.4 RELEASE=1habbie ./build-scripts/build-auth-debian` fails with
```
checking for curl... no
configure: error: curl program is missing, required for running remotebackend unit tests
```

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: 4.0.4
 - Software source: tarball

### Steps to reproduce
1. set up build env (`build-essential` and everything from Build-Depends)
2. run `build-auth-debian`

### Expected behaviour
Packages come out.

### Actual behaviour
```
checking for curl... no
configure: error: curl program is missing, required for running remotebackend unit tests
```

**Comment by Habbie** [comment]
After installing curl (and disabling make check because no v6 here): `make` fully passes but debian packaging fails for lack of manpages. Installing pandoc and rebuilding fixes that. Note: I did not 'clean' between these build attempts.

**Comment by pieterlexis** [comment]
hrm, pandoc should not be needed in 4.0.x when building from a tarball (as `make dist` fails without pandoc), so I don't want to add it to the Build-Depends, but we could add some info on this in the build-scripts directory

**Comment by Habbie** [comment]
Ah yes, I couldn't immediately figure out how to build from a tarball, that's why I built from git.

**Comment by pieterlexis** [comment]
oh, building the debian package is different from the RPM package (that does get a tarball). I'll sync this up as well
