### ISSUE TITLE
Recursor test suite passes unexpectedly

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#5601]
- Program: Recursor
 - Issue type: Bug report

### Short description
Even if lua-posix module is missing, the recursor test suite passes despite `10.0.3.10` server being down.

### Environment
 - Operating system: Ubuntu 16.04.3
 - Software version: git master
 - Software source:  git + compiled myself

### Steps to reproduce
1. Build powerdns recursor
2. Go to `pdns/regression-tests.recursor`
3. Run tests as normally
4. Verify that 10.0.30.10 is not starting because `lua-posix` is missing.

### Expected behaviour
Test suite should fail.

### Actual behaviour
Test suite passes with 100%.

**Comment by pieterlexis** [comment]
ref #2741

**Comment by rgacogne** [comment]
Fixed by  #6458 (master) and #7303 (rel/rec-4.1.x).
