### ISSUE TITLE
Recursor Not Forwarding to Local Authoritative

### ISSUE THREAD

**Issue by primesoftware** [PowerDNS/pdns#5604]
I have the recursor running on my Arch Linux router and the authoritative serving a local domain on my Raspberry Pi (Raspbian). In my recursor config:

```
#################################
# forward-zones Zones for which we forward queries, comma separated domain=ip pairs
#
forward-zones=localdomain.home=172.16.0.5

#################################
# forward-zones-file    File with (+)domain=ip pairs for forwarding
#
# forward-zones-file=

#################################
# forward-zones-recurse Zones for which we forward queries with recursion bit, comma separated domain=ip pairs
#
forward-zones-recurse=.=138.197.25.214;23.94.5.133
```
For some reason, the local domain queries never get forwarded to my Pi (172.16.0.5). The authoritative server is using the MySQL backend and is properly configured since I things resolve properly on the Pi. Is there a problem in the priority of forward-zones vs forward-zones-recurse?

**Comment by pieterlexis** [comment]
Hi, this sounds like a support question, please use [the mailinglist or IRC](https://doc.powerdns.com/recursor/#getting-support) for this. When asking your question there, please include the config, logmessages (possibly using `trace`) and any other information that might be relevant.
