### ISSUE TITLE
cant run pdns_server on mac 

### ISSUE THREAD

**Issue by roadsigngit** [PowerDNS/pdns#5607]
while i installed the pdns via the command 'brew install pdns', and successfully installed.
but when i start the pdns_server ,it comes the error:

```
Aug 13 18:34:39 Unable to load module '/usr/local/Cellar/pdns/4.0.4/lib/pdns/libgmysqlbackend.so': dlopen(/usr/local/Cellar/pdns/4.0.4/lib/pdns/libgmysqlbackend.so, 2): image not found
Aug 13 18:34:39 DNSBackend unable to load module in gmysql
```

i operate it by 'https://doc.powerdns.com/authoritative/installation.html#mac-os-x'
but when i want to install pdns-backend-$backend , find that thereis no pdns-backend-mysql at all. 
im confused...and asking for help...

**Comment by Habbie** [comment]
related: https://github.com/Homebrew/homebrew-core/pull/16694

**Comment by Habbie** [comment]
Right now pdns in brew comes with gsqlite3, and optionally with postgresql. It should not be hard to expand the offering. Please follow the link in my previous comment and see if you can help out there based on the discussion.

**Comment by pieterlexis** [comment]
Closing this support request.

**Comment by Habbie** [comment]
Please continue discussion on the linked brew ticket.
