### ISSUE TITLE
Multiple ALIAS records

### ISSUE THREAD

**Issue by arunisaac** [PowerDNS/pdns#5624]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Support resolution of multiple ALIAS records to multiple A records.

### Environment
 - Operating system: Debian GNU/Linux 8.9 (jessie)
 - Software version: 4.0.3
 - Software source: Operating system repository (jessie-backports)

### Use case
Serve a website (say, `blog.example.com`) on two separate servers (say, `server1.example.com` and `server2.example.com`, each of which have their own A record) for redundancy and round-robin load balancing.

### Description
I want to have two ALIAS records for `blog.example.com`, one pointing to `server1.example.com`, and the other pointing to `server2.example.com`. When a DNS query requesting A records for `blog.example.com` comes in, the response should be the combined A records of `server1.example.com` and `server2.example.com`. Currently, only the A record of one of `server1.example.com` or `server2.example.com` are returned.

**Comment by Habbie** [comment]
Hello,

the ALIAS feature is being deprecated, to be replaced by https://datatracker.ietf.org/doc/draft-ietf-dnsop-aname/. Your feature request has come up there but it is unsure what the outcome will be. I suggest following the document, and voicing any concerns you have on the IETF dnsop WG mailing list.

**Comment by arunisaac** [comment]
Sure, thanks!

**Comment by arunisaac** [comment]
I've joined the IETF dnsop WG mailing list. But, it would be nice if you could link me to the thread where the feature request was raised.
