### ISSUE TITLE
Update to Travis trusty image

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5638]
- Program: Authoritative, Recursor

Due to confusion around Travis-CI's announcement of their upgrade to Trusty, our rel/rec-3.7.x and rel/auth-3.4.x were not ready when this week the actual upgrade happened. Because of this, .travis.yml on those branches has now received `dist: precise`. At some point, presumably, the precise image will actually go away and we need to be ready for that.

To fix this:
1. wait for Travis to roll out trusty everywhere
2. fork either branch and change `precise` to `trusty`
3. observe inevitable failure
4. fix it
5. PR it

**Comment by pieterlexis** [comment]
3.4 is EOL, closing.
