### ISSUE TITLE
Please provide Fedora (Latest) builds for dnsdist/pdns

### ISSUE THREAD

**Issue by seitzbg** [PowerDNS/pdns#5645]
Ticket created per Lieter on IRC.

 - Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request

### Short description
Would like to see Fedora packages provided along with the current stuff in the Pdns repos.

### Environment

 - Operating system: Fedora 26 x86_64
 - Software version: dnsdist 1.1.0
 - Software source: Fedora

### Steps to reproduce
None

### Expected behaviour
None

### Actual behaviour
None

### Other information
None

### Usecase

Use the latest versions of PDNS on Fedora without waiting for Fedora to upgrade :)

### Description

Install :)

**Comment by Habbie** [comment]
related: #4714

**Comment by Habbie** [comment]
We'd very much welcome a PR updating builder-support with a few files to cover the last one or two Fedora releases, plus rawhide.

**Comment by pieterlexis** [comment]
Fedora is too much of a moving target. we will accept a PR that adds a builder target for fedora versions, but won't maintain a software repo for fedora.
