### ISSUE TITLE
dnsdist - logging-facility support

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#5653]
### Issue type

 - Program: dnsdist
 - Issue type: Feature request

### Short description

Running dnsdist on non-systemd systems it would be handy to be able to set the `logging-facility` in order to separate dnsdist's log messages from the one of the other system deamons.

### References

As a reference see the PowerDNS [`logging-facility`](https://doc.powerdns.com/authoritative/settings.html#logging-facility) configuration setting.

**Comment by rgacogne** [comment]
Postponing this a bit, ping me if you need that soon!
