### ISSUE TITLE
Using useClientSubnet=true affect caching

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#5654]
Hi,

In order to receive the IP of the dnsdist client on the backend resolvers I have tried to use `useClientSubnet=true` in server setting together with `setECSSourcePrefixV4(32)` and `
setECSSourcePrefixV6(56)` in the config. It works fine but was surprised with the impact to the cache hitrate. It went down from previous > 90% to ~30%. Is it an expected behavior? 

Thanks
Aleš

**Comment by rgacogne** [comment]
Hi Aleš,

Yes, it is. We have no way of knowing whether the answer sent by the backend will vary based on the provided `ECS` information, so we cache answers for queries with different `ECS` values separately. I guess we could add an option to add `ECS` information to the forwarded query but ignore it for the cache..

**Comment by rygl** [comment]
Hi Remi,

Thanks for your answer. Anyway if backends do not work with `ECS` it would help.

Anyway it looks like I am trying to use `ECS` not the the best way - with `setECSSourcePrefixV4(32)` to identify the client by his IP on the backends while the purpose of it is a bit different and using XPF in the future would be better. 

Aleš
