### ISSUE TITLE
Make it easier to define maximum client TTL in responses

### ISSUE THREAD

**Issue by aerique** [PowerDNS/pdns#5656]
- Program: Recursor
 - Issue type: Feature request

### Short description

It should be easy to configure maximum client TTL for responses.

There's support in the recursor for this and with Lua we could get there but this is too much of a hassle for customers.

**Comment by ahupowerdns** [comment]
I have just verified that "max-cache-ttl" actually does this

**Comment by zeha** [comment]
Documentation?
