### ISSUE TITLE
Exclude MX records from RPZ Policy

### ISSUE THREAD

**Issue by Snowmanko** [PowerDNS/pdns#5657]
- Program: Recursor
 - Issue type: Feature request

### Short description
I'am unable to exclude MX record from RPZ Policy. In bind it can be achieved without problems.
We would like to block hazard game domains like i.e. bet365.com so we have to block at least two domains : 
- bet365.com
Under this domain there is MX record, even when it is explictly configured, it does not work with PowerDNS Recursor.
- *.bet365.com

+ exclude MX records 

### Environment
 - Operating system: Debian 9
 - Software version: 4.0.4-1+deb9u1
 - Software source: Operating system repository

### Expected behaviour
Exclude MX records from policy or stop ignoring MX records in RPZ

### Actual behaviour
;; QUESTION SECTION:
;bwin.com.			IN	A

;; ANSWER SECTION:
bwin.com.		0	IN	MX	10 mailgate02.itsfogo.com.

Records gets messed up.

BR,

**Comment by rgacogne** [comment]
You could write a few lines of Lua using the `prerpz` hook to disable `RPZ` lookup for `MX` queries, via the `dq:discardPolicy()` method.
Could you please provide your current configuration, as well as the bind configuration you use?

**Comment by Snowmanko** [comment]
Hi @rgacogne ,
thanks for feedback, I will try to research docs and implement prerpz hook with discardPolicy() function.

Moreover, this is setup on powerdns cache server (recursor): 
`root@powerdns:~# cat /etc/powerdns/recursor.conf
allow-from=127.0.0.0/8
allow-from-file=/etc/powerdns/goodclients
local-address=0.0.0.0
local-port=53
quiet=yes
setgid=pdns
setuid=pdns
version-string="caching name server"
lua-config-file=/etc/powerdns/recursorconf.lua`
[configuration is redacted]

`root@powerdns:~# cat /etc/powerdns/recursorconf.lua 
rpzMaster("1.2.3.4", "domain.com-rzp", {policyName="rpz"})`
[configuration is redacted]

1.2.3.4 is IP adress of authoritative bind server which holds domain.com-rzp zone containing all RZP records. This powerdns cache server should download domain.com-rzp as an authoritative zone with axfr and apply RZP responses to clients if RZP domains are matched.

I also have cacheing bind server serving queries to clients. This is related config : 
`zone "domain.com-rzp" {
        type slave;
        masters { 1.2.3.4; 1.2.3.5; };
        file "/var/lib/bind/domain.com-rzp";
        masterfile-format text;
	allow-transfer { none; };
};
response-policy { zone "domain.com-rzp"; };`
[configuration is redacted]

In bind these slave zones on cache server works as expected. On powerdns the same slave zone downloaded with axfr from master authoritative server are acting like I described before.

If you have some additional questions, I am ready to provide answers.

**Comment by rgacogne** [comment]
Could you please post the content of the RPZ zone, or at least relevant parts? I think it might be related to the fact that since `draft-vixie-dns-rpz-03` an RPZ zone can have several types for the same owner name for local data actions (see [1]) and we don't support that yet.

[1]: https://tools.ietf.org/html/draft-ietf-dnsop-dns-rpz-00#section-3.6

**Comment by Snowmanko** [comment]
My RPZ zone is in LDAP but I've attached aXFR request of whole zone.
Hope it will help to identify problem. Content is redacted.

`; <<>> DiG 9.10.3-P4-Ubuntu <<>> axfr domain.com-rzp @10.11.12.13`
`;; global options: +cmd`
`domain.com-rzp.		86400	IN	SOA	auth1.ns.domain.com. hostmaster.domain.com. 2013061341 3600 3600 604800 86400`
`domain.com-rzp.		86400	IN	NS	auth1.ns.domain.com.`
`domain.com-rzp.		86400	IN	NS	auth2.ns.domain.com.`
`domain.com-rzp.		86400	IN	NS	auth3.ns.domain.com.`
`domain.com-rzp.		86400	IN	NS	auth4.ns.domain.com.`
`bwin.com.domain.com-rzp.	3600	IN	MX	10 mailgate01.itsfogo.com.`
`bwin.com.domain.com-rzp.	3600	IN	MX	15 mailgate02.itsfogo.com.`
`bwin.com.domain.com-rzp.	3600	IN	A	1.2.3.4`
`mail2.bet-at-home.com.domain.com-rzp. 3600	IN CNAME rpz-passthru.`
`mail.bet-at-home.com.domain.com-rzp. 3600 IN CNAME	rpz-passthru.`
`bet-at-home.com.domain.com-rzp. 3600 IN	MX	10 mail.bet-at-home.com.`
`bet-at-home.com.domain.com-rzp. 3600 IN	MX	10 mail2.bet-at-home.com.`
`*.bet-at-home.com.domain.com-rzp. 3600 IN	CNAME	*.hazard.rzp.domain.com.`
`bet-at-home.com.domain.com-rzp. 3600 IN	A	1.2.3.4`
`*.williamhill.com.domain.com-rzp. 3600 IN	CNAME	*.hazard.rzp.domain.com.`
`williamhill.com.domain.com-rzp. 3600 IN	MX	10 mxa-0010e301.gslb.pphosted.com.`
`williamhill.com.domain.com-rzp. 3600 IN	MX	10 mxb-0010e301.gslb.pphosted.com.`
`williamhill.com.domain.com-rzp. 3600 IN	A	1.2.3.4`
`bet365.com.domain.com-rzp.	3600	IN	MX	10 mx1.bet365.com.`
`bet365.com.domain.com-rzp.	3600	IN	MX	20 mx2.bet365.com.`
`*.bwin.com.domain.com-rzp.	3600	IN	CNAME	*.hazard.rzp.domain.com.`
`mx1.bet365.com.domain.com-rzp. 3600 IN	CNAME	rpz-passthru.`
`mx2.bet365.com.domain.com-rzp. 3600 IN	CNAME	rpz-passthru.`
`*.bet365.com.domain.com-rzp. 3600	IN	CNAME	*.hazard.rzp.domain.com.`
`bet365.com.domain.com-rzp.	3600	IN	A	1.2.3.4`
`domain.com-rzp.		86400	IN	SOA	auth1.ns.domain.com. hostmaster.domain.com. 2013061341 3600 3600 604800 86400`
`;; Query time: 20 msec`
`;; SERVER: 10.11.12.13#53(10.11.12.13)`
`;; WHEN: Mon Sep 25 03:25:57 CDT 2017`
`;; XFR size: 26 records (messages 1, bytes 709)`

**Comment by rgacogne** [comment]
Thank you! So you indeed have several types for the same owner name for local data actions, and sometimes even several records for the same type. We don't support that yet and IMHO we need to think a bit about how we want to design it.

**Comment by Snowmanko** [comment]
I've discovered that when the order of record is right, it works as expected. But I have to sort records in zone in order that MX'es are on very very top of the whole zone.

**Comment by Snowmanko** [comment]
Thanks!
