### ISSUE TITLE
Recursor 4.0.6 SERVFAIL for all dig request 

### ISSUE THREAD

**Issue by samhernand** [PowerDNS/pdns#5660]
pdns 4.0.4 with recursor (4.0.6) installed under one Ubuntu 16.04 server:

when i dig at 10.176.201.70 (my serve) it works:
; <<>> DiG 9.10.3-P4-Ubuntu <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47154
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       3599653 IN      NS      d.root-servers.net.
.                       3599653 IN      NS      m.root-servers.net.
.                       3599653 IN      NS      l.root-servers.net.
.                       3599653 IN      NS      c.root-servers.net.
.                       3599653 IN      NS      i.root-servers.net.
.                       3599653 IN      NS      j.root-servers.net.
.                       3599653 IN      NS      a.root-servers.net.
.                       3599653 IN      NS      k.root-servers.net.
.                       3599653 IN      NS      b.root-servers.net.
.                       3599653 IN      NS      h.root-servers.net.
.                       3599653 IN      NS      e.root-servers.net.
.                       3599653 IN      NS      f.root-servers.net.
.                       3599653 IN      NS      g.root-servers.net.

;; Query time: 0 msec
;; SERVER: 10.176.201.70#53(10.176.201.70)
;; WHEN: Mon Aug 28 16:19:18 VET 2017
;; MSG SIZE  rcvd: 239

But PDNS Recursor gives SERVFAIL for all requests try to resolve a domain (google.com for this example):

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 44676
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; Query time: 2736 msec
;; SERVER: 10.176.201.70#53(10.176.201.70)
;; WHEN: Mon Aug 28 16:22:51 VET 2017
;; MSG SIZE  rcvd: 43

my syslog shows that there is no root servers that can resolve the domain

www.powerdns.com: No CNAME cache hit of 'www.powerdns.com|CNAME' found
www.powerdns.com: No CNAME cache hit of 'www.powerdns.com|CNAME' found
www.powerdns.com: No cache hit for 'www.powerdns.com|A', trying to find an appropriate NS record
www.powerdns.com: No cache hit for 'www.powerdns.com|A', trying to find an appropriate NS record
www.powerdns.com: Checking if we have NS in cache for 'www.powerdns.com'
www.powerdns.com: Checking if we have NS in cache for 'www.powerdns.com'
www.powerdns.com: no valid/useful NS in cache for 'www.powerdns.com'
www.powerdns.com: no valid/useful NS in cache for 'www.powerdns.com'
www.powerdns.com.: Nameservers: a.root-servers.net.(465.59ms), j.root-servers.net.(465.59ms), m.root-servers.net.(465.59ms),
www.powerdns.com.: Nameservers: a.root-servers.net.(465.59ms), j.root-servers.net.(465.59ms), m.root-servers.net.(465.59ms),
www.powerdns.com.:              k.root-servers.net.(465.59ms), e.root-servers.net.(465.59ms), g.root-servers.net.(465.59ms),
www.powerdns.com.:              k.root-servers.net.(465.59ms), e.root-servers.net.(465.59ms), g.root-servers.net.(465.59ms),
www.powerdns.com.:              h.root-servers.net.(465.59ms), d.root-servers.net.(465.59ms), f.root-servers.net.(896.45ms),
www.powerdns.com.:              h.root-servers.net.(465.59ms), d.root-servers.net.(465.59ms), f.root-servers.net.(896.45ms),
www.powerdns.com.:              c.root-servers.net.(896.45ms), l.root-servers.net.(896.45ms), b.root-servers.net.(974.33ms),
www.powerdns.com.:              c.root-servers.net.(896.45ms), l.root-servers.net.(896.45ms), b.root-servers.net.(974.33ms),
: timeout resolving after 1502.05msec
: Trying to resolve NS 'm.root-servers.net' (3/13)
: Resolved '.' NS m.root-servers.net to: 202.12.27.33
: Trying IP 202.12.27.33:53, asking 'www.powerdns.com|A'
www.powerdns.com: timeout resolving after 1502.03msec
www.powerdns.com: timeout resolving after 1502.03msec
www.powerdns.com: Trying to resolve NS 'k.root-servers.net' (4/13)
www.powerdns.com: Trying to resolve NS 'k.root-servers.net' (4/13)
www.powerdns.com: Resolved '.' NS k.root-servers.net to: 193.0.14.129
www.powerdns.com: Resolved '.' NS k.root-servers.net to: 193.0.14.129
www.powerdns.com: Trying IP 193.0.14.129:53, asking 'www.powerdns.com|A'
www.powerdns.com: Trying IP 193.0.14.129:53, asking 'www.powerdns.com|A'
1 [67/1] answer to question 'www.powerdns.com|A': 0 answers, 1 additional, took 6 packets, 7509.73 ms, 1 throttled, 5 timeouts, 0 tcp connections, rcode=2

**Comment by Habbie** [comment]
It looks like you have serious Internet connection problems - perhaps something is intercepting your DNS. This makes it a support question, so please try the mailing lists or our IRC channel. Details are at https://www.powerdns.com/opensource.html
