### ISSUE TITLE
Wrong default dbname for gmysql in docs

### ISSUE THREAD

**Issue by joshbenner** [PowerDNS/pdns#5668]
- Program: Authoritative (gmysql backend docs)
 - Issue type: Bug report (documentation)

### Short description
The [documented gmysql default for dbname](https://github.com/PowerDNS/pdns/blob/master/docs/backends/generic-mysql.rst#gmysql-dbname) is "pdns", when it is [actually](https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/gmysqlbackend.cc#L72) "powerdns".

**Comment by zeha** [comment]
Related: the generic postgres backend docs also show lots of defaults but in reality they are all empty.
