### ISSUE TITLE
prepared statements return error message if values are null

### ISSUE THREAD

**Issue by stevie-** [PowerDNS/pdns#5675]
- Issue type: Bug report

### Short description

We see in syslog _every minute_ a error message on our pdns setup with mariadb backend.
`Sep  7 08:54:48 dns-00 pdns[23390]: Result field at row 0 column 3 has errno 120`
You have a line for all domains in domains tables (maybe more) with _NULL_ values on at least one of these columns:
```
master
last_check 
notified_serial 
account
```
We **assume** by reading code, that this issue is related to prepared statements.
https://github.com/PowerDNS/pdns/blob/auth-4.0.4/modules/gmysqlbackend/smysql.cc#L237

Also there seems to be no service impact we can see. But to make sure we create this BUG report.

### Environment

 - Operating system:  14.04.1-Ubuntu
 - Software version: 4.0.4
 - Software source: http://repo.powerdns.com/ubuntu/ trusty-auth-40/main amd64 

### Steps to reproduce

These steps create a very tiny setup with no records. But it doesn't matter if records are set, since we see this problem also on servers we complete zones.

1.  install pdns-server=4.0.4 and mariadb-server=10.2.8+maria~trusty
2.  create powerdns tables (schema)
3.  create a zone 
`pdnsutil create-zone test321.net`
4.  check (sys)log for messages
5. optional to set kind to master 
`pdnsutil set-kind test321.net master`
### Expected behaviour

We expect no error messages.

### Actual behaviour

On syslog we see:
Sep  7 07:17:47 dns-00 pdns[23390]: Result field at row 0 column 3 has errno 120 
Sep  7 07:18:47 dns-00 pdns[23390]: Result field at row 0 column 3 has errno 120 
Sep  7 07:19:47 dns-00 pdns[23390]: Result field at row 0 column 3 has errno 120 

### Other information

pdns.conf
```
allow-recursion=127.0.0.1
include-dir=/etc/powerdns/pdns.d
launch=gmysql
setgid=pdns
setuid=pdns
query-local-address=192.168.181.8
gmysql-user=powerdns
soa-refresh-default=900
gmysql-password=SECURE
gmysql-dbname=powerdns
api=yes
local-address=127.0.0.1,192.168.181.8
reuseport=yes
master=yes
soa-retry-default=300
slave=no
webserver=yes
version-string=anonymous
non-local-bind=no
do-ipv6-additional-processing=false
```
```
MariaDB [powerdns]> select * from domains;
+----+-------------+--------+------------+--------+-----------------+---------+
| id | name        | master | last_check | type   | notified_serial | account |
+----+-------------+--------+------------+--------+-----------------+---------+
|  1 | test321.net |        |       NULL | MASTER |               1 |         |
+----+-------------+--------+------------+--------+-----------------+---------+
1 row in set (0.00 sec)
```

**Comment by cmouse** [comment]
can you turn on query logging?

**Comment by stevie-** [comment]
I set
```
log-dns-queries=yes
loglevel=9
```
But I don't see any dns querries (this is a test instance which is not used)
```
Sep  7 09:42:13 dns-00 pdns[23388]: Our pdns instance (23428) exited after signal 9
Sep  7 09:42:13 dns-00 pdns[23388]: Respawning
Sep  7 09:42:14 dns-00 pdns[24662]: Guardian is launching an instance
Sep  7 09:42:14 dns-00 pdns[24662]: Reading random entropy from '/dev/urandom'
Sep  7 09:42:14 dns-00 pdns[24662]: Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
Sep  7 09:42:14 dns-00 pdns[24662]: [gmysqlbackend] This is the gmysql backend version 4.0.4 (Jun 22 2017 20:12:20) reporting
Sep  7 09:42:14 dns-00 pdns[24662]: This is a guarded instance of pdns
Sep  7 09:42:14 dns-00 pdns[24662]: UDP server bound to 127.0.0.1:53
Sep  7 09:42:14 dns-00 pdns[24662]: UDP server bound to 192.168.181.8:53
Sep  7 09:42:14 dns-00 pdns[24662]: UDPv6 server bound to [::]:53
Sep  7 09:42:14 dns-00 pdns[24662]: TCP server bound to 127.0.0.1:53
Sep  7 09:42:14 dns-00 pdns[24662]: TCP server bound to 192.168.181.8:53
Sep  7 09:42:14 dns-00 pdns[24662]: TCPv6 server bound to [::]:53
Sep  7 09:42:14 dns-00 pdns[24662]: PowerDNS Authoritative Server 4.0.4 (C) 2001-2016 PowerDNS.COM BV
Sep  7 09:42:14 dns-00 pdns[24662]: Using 64-bits mode. Built using gcc 4.8.4 on Jun 22 2017 20:38:58 by root@439ad18790ed.
Sep  7 09:42:14 dns-00 pdns[24662]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep  7 09:42:14 dns-00 pdns[24662]: Set effective group id to 117
Sep  7 09:42:14 dns-00 pdns[24662]: Listening for HTTP requests on 127.0.0.1:8081
Sep  7 09:42:14 dns-00 pdns[24662]: Set effective user id to 110
Sep  7 09:42:14 dns-00 pdns[24662]: Doing stub resolving, using resolvers: 192.168.181.25, 192.168.181.61
Sep  7 09:42:14 dns-00 pdns[24662]: Question got answered by 192.168.181.25
Sep  7 09:42:14 dns-00 pdns[24662]: Polled security status of version 4.0.4 at startup, no known issues reported: OK
Sep  7 09:42:14 dns-00 pdns[24662]: Creating backend connection for TCP
Sep  7 09:42:14 dns-00 pdns[24662]: Master/slave communicator launching
Sep  7 09:42:14 dns-00 pdns[24662]: gmysql Connection successful. Connected to database 'powerdns' on ''.
Sep  7 09:42:14 dns-00 pdns[24662]: gmysql Connection successful. Connected to database 'powerdns' on ''.
Sep  7 09:42:14 dns-00 pdns[24662]: About to create 3 backend threads for UDP
Sep  7 09:42:14 dns-00 pdns[24662]: Result field at row 0 column 3 has errno 120
Sep  7 09:42:14 dns-00 pdns[24662]: No master domains need notifications
Sep  7 09:42:14 dns-00 pdns[24662]: gmysql Connection successful. Connected to database 'powerdns' on ''.
Sep  7 09:42:14 dns-00 pdns[24662]: message repeated 2 times: [ gmysql Connection successful. Connected to database 'powerdns' on ''.]
Sep  7 09:42:14 dns-00 pdns[24662]: Done launching threads, ready to distribute questions
Sep  7 09:43:14 dns-00 pdns[24662]: Result field at row 0 column 3 has errno 120
Sep  7 09:43:32 dns-00 pdns[24662]: Remote 127.0.0.1 wants 'test321.net|SOA', do = 0, bufsize = 512: packetcache MISS
Sep  7 09:44:14 dns-00 pdns[24662]: Result field at row 0 column 3 has errno 120
```

**Comment by cmouse** [comment]
can you set `query-logging=yes`

**Comment by stevie-** [comment]
thanks this did the trick
```
Sep  7 09:56:35 dns-00 pdns[31229]: Query: select id,name,master,last_check,notified_serial,type from domains where type='MASTER'
Sep  7 09:56:35 dns-00 pdns[31229]: Result field at row 0 column 3 has errno 120
``

**Comment by ahupowerdns** [comment]
"MySQL error code 120: Didn't find key on read or update"

**Comment by rgacogne** [comment]
So based on the description of the `MYSQL_BIND::error` field at [1], I'm pretty sure we are not using it correctly here: [2]. The warning treats it like an error number but it looks like it can only have two values, 0 or 1. This is consistent with the comments in `mysql/mysql.h`:

```
  error          - where to write a truncation error if it is present.                                                                                                                                                        
                   possible error value is:                                                                                                                                                                                   
                   0  no truncation                                                                                                                                                                                           
                   1  value is out of range or buffer is too small  
```

So this value being set seems to indicate that the third column is too large for the buffer we allocated and has been truncated. It would be interesting to get a `describe domains`, and to see what message is displayed after with this (untested) patch [3] applied.

[1]: https://dev.mysql.com/doc/refman/5.7/en/c-api-prepared-statement-data-structures.html
[2]: https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/smysql.cc#L237
[3]: https://github.com/rgacogne/pdns/commit/2be6b2dcc368ff76842b035b67f7a8170d787889

**Comment by Habbie** [comment]
@stevie- @mortenstevens #5820 was merged and contrary to the text there, I suspect it in fact fixes the issue. Can you please try a master build from repo.powerdns.com versioned 1892g0c71684 or higher and test?

**Comment by mortenstevens** [comment]
@Habbie 
I have rebuild pdns-4.1.0-rc1  but only with patching https://patch-diff.githubusercontent.com/raw/PowerDNS/pdns/pull/5820.patch

Looks good. No SQL errors. Here is the result with log-dns-queries=yes, query-logging=yes and loglevel=9

`Oct 13 17:47:00 localhost.localdomain pdns[10922]: Remote 10.17.10.10 wants 'example.com|NS', do = 0, bufsize = 1680: packetcache MISS
Oct 13 17:47:00 localhost.localdomain pdns[10922]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?
Oct 13 17:47:00 localhost.localdomain pdns[10922]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?
Oct 13 17:47:00 localhost.localdomain pdns[10922]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=?
Oct 13 17:47:00 localhost.localdomain pdns[10922]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=?
Oct 13 17:47:00 localhost.localdomain pdns[10922]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=?`

**Comment by Habbie** [comment]
@mortenstevens thanks!

**Comment by Habbie** [comment]
@stevie- ping

**Comment by stevie-** [comment]
I didn't test your patch. is there a built version avaible which includes your patch? (Ubuntu)

**Comment by mortenstevens** [comment]
@stevie- 
 Just try the latest rc2. Packages for Ubuntu should be also available on https://repo.powerdns.com/

**Comment by Habbie** [comment]
Thanks!
