### ISSUE TITLE
rec: Handle broken NS answers (like the ones from fastly) when looking for zone cuts

### ISSUE THREAD

**Issue by aerique** [PowerDNS/pdns#5681]
- Program: Recursor
 - Issue type: Bug report

### Short description

Some of fastly.net's authoritative servers answer with NODATA when asked fastly.net|NS, which messes up our zone cut detection code, leading to DNSSEC validation failure. They are aware of the issue and the offending servers will be removed, but we need to handle that case more gracefully, especially since it now looks like incapdns.net has the same issue.

**Comment by rgacogne** [comment]
I cannot reproduce the fastly issue anymore, it would be great news if it has indeed been fixed. The incapdns one is still there though.

**Comment by rgacogne** [comment]
Same issue with v0cdn.net..

**Comment by Habbie** [comment]
Actually not the same - incap does empty NOERROR (software issue), v0cdn does auth NODATA (configuration issue); but I understand how these are in the same bucket for us right now.
