### ISSUE TITLE
getAuth() bugfix for DS queries is incomplete

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#5697]
https://github.com/PowerDNS/pdns/pull/5519 fixed some issues in handling of DS queries. I still think this fix is incomplete (only 90% sure as this logic is not easy to reverse engineer and the documentation of the code is sparse).

Consider the scenario where there is only 1 backend and this backend immediately responds with the best match. E.g. target="a.b.c.example.com" and the backend responses with "com".

In this case, shorter=target=a.b.c.example.com. If the query is for DS, PowerDNS would still "chasing next" as the if condition "target != shorter" is wrong. The proper comparison would be target against sd->qname (compare with the zone returned from the backend, not with the zone the backend was asked).

Further, in case of DS queries, I think getAuth() should return false if there is no parent zone found, instead of using the zone which is identical to the queried label:

Hence, I think the proper fix would be:

```diff
found:
+    // DS records must be answered from the parent zone (the zone
+    // which has the delegation). Hence, if we found Authority, we
+    // start again and chase the next zone.
+    // There is one exception: if the first found Authority is not
+    // identical to the queried target, we already have the parent
+    // zone found.
-    if(found == (qtype == QType::DS) || target != shorter) {
+    if(found == (qtype == QType::DS) || target != sd->qname) {
      DLOG(L<<Logger::Error<<"found: "<<sd->qname<<endl);
      return true;
    } else {
      DLOG(L<<Logger::Error<<"chasing next: "<<sd->qname<<endl);
      found = true;
    }

  } while(shorter.chopOff());
+  // DS queries must be answered from the parent zone. If we do not
+  // find a parent zone, return false
+  if (found && (qtype == QType::DS) && (target == sd->qname)) {
+    return false;
+  }
  return found;
}
```

**Comment by klaus3000** [comment]
Please also backport this fixes to 4.0

**Comment by Habbie** [comment]
Can you please demonstrate the bug?

**Comment by klaus3000** [comment]
Not yet! My assumption is based on this comment:

>  // A backend can respond to our authority request with the 'best' match it
>   // has. For example, when asked for a.b.c.example.com. it might respond with
>   // com. We then store that and keep querying the other backends in case one
>   ...

So I came to the conclusion that there are backends which do reply with the best match.
So, if you can tell me a backend which has this behavior (the pgsql backend does not at the moment) I can try to demonstrate the bug.

**Comment by Habbie** [comment]
You'd have to write your own pipebackend script that does this.

**Comment by Habbie** [comment]
Closing this, happy to reopen once demonstrated.

**Comment by klaus3000** [comment]
I do not think that this can be demonstrated with the pipebackend or any other. If I understand it correctly, the getAuth() function of the backend may be "optimzed", i.e. it may return "com" when asked for the authority of "a.b.c.com". The getSOA() function of the backend must return the SOA of "a.b.c.com" or FALSE if not exists. At the moment no backend implements getAuth() - all use the default of DNSBackend which is just a foward to getSOA() - and getSOA can not be optimized. The pipebackend script does not know if the incoming SOA request is a real SOA request or a GetAuth request and hence can not "optimize" the response.
I still believe there is a bug which would be triggered when using an optimized backend. But as there is no optimized I can not demonstrate it.
