### ISSUE TITLE
make dist for auth fails on master

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#5701]
I just wanted to build auth for master for Debian. I used the new rules from build-scripts/README.md
- autoreconf -i
- ./configure --without-modules --without-dynmodules --disable-depedency-tracking
- make dist

the last command fails:

```
make[2]: Entering directory `/home/darilion/software/pdns4-fuer-neue-pakete/github-master-for-DS-bug-demonstration2/docs'
make[2]: *** No rule to make target `pdns_server.1', needed by `distdir'.  Stop.

```

**Comment by Habbie** [comment]
Can you try installing pandoc? configure should have warned about this.

**Comment by klaus3000** [comment]
No warning, pandoc is already installed:
```
# dpkg -l|grep pandoc
ii  pandoc                                 1.12.2.1-1build2                           amd64        general markup converter
ii  pandoc-data                            1.12.2.1-1build2                           all          general markup converter - data files

```

**Comment by Habbie** [comment]
Ah! `configure: WARNING: virtualenv is missing, unable to build manpages.`

**Comment by Habbie** [comment]
I can confirm your issue without virtualenv, and I can also confirm that installing virtualenv (and curl) makes `make dist` work.

**Comment by klaus3000** [comment]
I confirm "apt-get install dh-virtualenv" fixed the problem. Thanks
