### ISSUE TITLE
initial NSEC query returns NSEC 3 times

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5705]
- Program: Recursor
 - Issue type: Bug report

### Short description
```
$ dig nsec www.potaroo.net

; <<>> DiG 9.11.2 <<>> nsec www.potaroo.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 47662
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.potaroo.net.		IN	NSEC

;; ANSWER SECTION:
www.potaroo.net.	6400	IN	NSEC	_443._tcp.www.potaroo.net. A AAAA RRSIG NSEC
www.potaroo.net.	6400	IN	NSEC	_443._tcp.www.potaroo.net. A AAAA RRSIG NSEC
www.potaroo.net.	6400	IN	NSEC	_443._tcp.www.potaroo.net. A AAAA RRSIG NSEC

;; Query time: 1401 msec
;; SERVER: 192.168.0.203#53(192.168.0.203)
;; WHEN: Mon Sep 18 14:26:41 CEST 2017
;; MSG SIZE  rcvd: 185

```

### Environment
 - Operating system: Raspbian 8
 - Software version: 0.0.1729gb3c5004-1pdns.jessie
 - Software source: repo.powerdns.com

### Steps to reproduce
1. configure `dnssec=log-fail`
2. restart recursor
3. query for an existing NSEC record

### Expected behaviour
I get the NSEC record once.

### Actual behaviour
See above.

### Other information
If I add `+dnssec` to my query, the RRSIGs also get triplicated. `+nodnssec +noad` is identical to dig defaults (`+ad`)

**Comment by rgacogne** [comment]
Confirmed, the current code handles NSEC, NSEC3 and RRSIG records separately and doesn't consider that the initial query could have been for a NSEC record: https://github.com/PowerDNS/pdns/blob/master/pdns/syncres.cc#L1938 

So we try every possible IP for every NS, collecting the NSEC records in the process, then fail. I have an ugly fix available [1], but perhaps we should refactor this function a bit.

[1]: https://github.com/PowerDNS/pdns/commit/34af2bc049a6ef8dc5ed1bbe652b768df151dec7
