### ISSUE TITLE
auth 4.1.0-rc1 debian armel build failure

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5707]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Debian reports a build failure for auth 4.1.0-rc1 on Debian armel: https://buildd.debian.org/status/fetch.php?pkg=pdns&arch=armel&ver=4.1.0~rc1-1&stamp=1505470994&file=log

### Environment

 - Operating system: Debian
 - Software version: experimental
 - Software source: our 4.1.0-rc1 tarball

**Comment by Habbie** [comment]
Relevant bits from the build log:
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/arm-linux-gnueabi/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='"4.1.0~rc1-1.Debian"' -pie  -pthread   -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z,relro -o pdns_notify arguments.o base32.o base64.o dns.o dnslabeltext.o dnsname.o dnsparser.o dnsrecords.o dnswriter.o logger.o misc.o notify.o nsecrecords.o qtype.o rcpgenerator.o selectmplexer.o sillyrecords.o statbag.o unix_utility.o -lcrypto   -lboost_program_options 
libtool: link: g++ -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/arm-linux-gnueabi/pdns\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -g -O2 "-fdebug-prefix-map=/<<PKGBUILDDIR>>=." -fstack-protector-strong -Wformat -Werror=format-security "-DPACKAGEVERSION=\"4.1.0~rc1-1.Debian\"" -pie -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -o dumresp dnslabeltext.o dnsname.o dumresp.o logger.o misc.o statbag.o unix_utility.o qtype.o  -pthread
dumresp.o: In function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
dumresp.o: In function `std::__atomic_base<unsigned long long>::fetch_add(unsigned long long, std::memory_order)':
/usr/include/c++/7/bits/atomic_base.h:514: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
```

**Comment by Habbie** [comment]
The email they sent that may have additional useful context:

 * Source package: pdns
 * Version: 4.1.0~rc1-1
 * Architecture: armel
 * State: failed
 * Suite: experimental
 * Builder: arnold.debian.org
 * Build log: https://buildd.debian.org/status/fetch.php?pkg=pdns&arch=armel&ver=4.1.0%7Erc1-1&stamp=1505470994&file=log

Please note that these notifications do not necessarily mean bug reports
in your package but could also be caused by other packages, temporary
uninstallabilities and arch-specific breakages.  A look at the build log
despite this disclaimer would be appreciated however.

**Comment by rgacogne** [comment]
I'm pretty sure we need to link with `-latomic` to fix this, my guess is that we need to update `m4/pdns_check_os.m4` for this architecture.

**Comment by Habbie** [comment]
As discussed on IRC with @zeha, debian/armel is going away soon so this may not be very important.

**Comment by Habbie** [comment]
And also @zeha fixed it.
