### ISSUE TITLE
build packages for raspbian stretch

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5708]
https://builder.powerdns.com/#/builders/60

(also, raspbian stretch is out)

**Comment by pieterlexis** [comment]
These work again, stretch will be supported in the future, we might need some more builders for this.

**Comment by aerique** [comment]
Moved to auth-4.2.0 for Stretch builds.

**Comment by Habbie** [comment]
> Moved to auth-4.2.0 for Stretch builds.

I have updated the title and the labels for this.

**Comment by chrisbertsch** [comment]
Jessie's end of life date is ~June 6th, 2018 so it would be nice to have packages for Stretch.

**Comment by colbin8r** [comment]
I'm running Raspbian Stretch. +1 for a master build for Stretch in addition to the major version (`4.2.x`, etc.).

**Comment by scolby33** [comment]
I would like to +1 for this as well: right now I'm using the Jessie repo on Stretch and it requires a lot of ugly contortions to get the right library versions installed as well.

**Comment by pieterlexis** [comment]
we do this now
