### ISSUE TITLE
API zone endpoint should support an 'rrset' parameter

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#5712]
- Program: Authoritative
 - Issue type: Feature request

### Short description

Right now, requesting zones/:zone_id will also return all RRSets in the zone, which can be slow on large zones. If I only want the 'meta' information, I don't need these.

My suggestion is to add an `rrset` URL parameter that can be set to `false` to not include the RRsets in the response.

A query would look like: `GET /api/v1/servers/localhost/zones/example.com.?rrsets=false HTTP/1.1`

**Comment by zeha** [comment]
👍
