### ISSUE TITLE
Wrongs transfer to additional section

### ISSUE THREAD

**Issue by pavelvasev** [PowerDNS/pdns#5717]
- Program: Authoritative 
 - Issue type: Bug report

### Short description
PowerDNS sends incorrect answers in response to A requests on second NS record.

### Environment
 - Operating system: debian stretch
 - Software version: pdns_server 4.0.3-1 , pdns_pipe_backend 4.0.3-1
 - Software source: debian stretch default apt sources

### Steps to reproduce
1. Configure pdns server to run with pipe backend on 2 machines with names DNS1.SOME.ORG and DNS2.SOME.ORG
1. Delegate SOME.ORG to that 2 machines via glue records.
1. Use settings 
```
out-of-zone-additional-processing=no
``` 
1. Use SOA answer to SOME.ORG zone like this:
```
 DNS1.SOME.ORG. SUPPORT.SOME.ORG. 2017091101 14400 3600 604800 3600
```
1. Run that in production. See that in 1 case of 1000 something going wrong. Clients cannot resolve domain name DNS2.SOME.ORG, saying "invalid hostname".

1. Run `tcpdump udp port 53 -vv -n | grep DNS2.SOME.ORG` on any of dns server machines.

1. See occasional strange UDP packets that PowerDNS sends with "0/0/1" which mean that PowerDNS sends requested information in Additional Section instead of Answer section.

### Example of normal answer
```
 144.76.71.50.53 > 188.138.40.20.39327: [] 31207*- q: A? dns2.lact.ru. 1/0/0 dns2.lact.ru. A 144.76.71.50 (46)
```
/// 1/0/0 means 1 answer, 0 ns records, 0 additional

### Example of wrong answer
```
    s439.pingdom.com.59231 > data3.domain: [] 34100+ A? dns2.lact.ru. (30)
    data3.domain > s439.pingdom.com.59231: [] 34100*- q: A? dns2.lact.ru. 0/0/1 ar: dns2.lact.ru. A 144.76.71.50 (46)
```
//  0/0/1 (0 answers, 0 ns, 1 ar=1 additional record)

### Expected behaviour

PowerDNS should send answers in Answers section. 

### Actual behaviour

DNS clients/recursors see Answer section empty and responds with "invalid hostname", which means that they failed to get ip address.

### Other information

* The problem arises only with DNS2.SOME.ORG. 
* If you disable query cache via `query-cache-ttl=0` option everything becomes OK.

* Maybe the problem grows from this code:
https://github.com/PowerDNS/pdns/blob/rec-4.0.3/pdns/packethandler.cc#L428

* The stated behavior is very ugly. DNS problems which occurs rarely brings puzzle.

**Comment by rgacogne** [comment]
Could you please:
* try upgrading to the latest version of the authoritative server, 4.0.4, and see if the problem still exists? We provide packages at https://repo.powerdns.com
* upload the PCAP of the wrong answer, or at least provide the actual content
* provide more info on what your pipe backend returns, since it's very hard for us to investigate an issue that we can't reproduce.

Thanks!

**Comment by Habbie** [comment]
ping

**Comment by Habbie** [comment]
@pavelvasev ping

**Comment by pavelvasev** [comment]
Sorry @Habbie for being not responsive. I will test it and tell you here.

**Comment by pavelvasev** [comment]
Hi all! Nowadays, after a year of the issue evolved, I tried to reproduce it. Unfortunately I was unable to do that: now it works without issues. I used same *powerdns* version, and even same debian system with all the same packages as one year ago. That's funny and unobvious what have been changed. It seems the issue should be closed, so I do it.
