### ISSUE TITLE
Failover MySQL Server

### ISSUE THREAD

**Issue by rradu92** [PowerDNS/pdns#5720]
I have 2 pdns servers running with the same mysql server, but I have 2 MySQL Master-Master replication scenario for all the cluster webapps and I need to attach the pdns instance to mysql-server1 but if mysql-server1 goes down switch the connection to mysql-server2. I don't know if it is possible, but I can't find anything in the docs or wikis.

I know I can make ns1 connect to mysql server1 and ns2 connect to mysql server2 but I want to make all connections to server1 as all other services and if server1 goes down then switch to server2.

**Comment by pieterlexis** [comment]
This is not possible with PowerDNS itself, use tools like mysql-proxy or haproxy to accomplish this. Closing as this is a support question, please use the [malinglist](https://www.powerdns.com/mailing-lists.html) for this.
