### ISSUE TITLE
doc rework nits

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5724]
Missing from the new docs:
* https://doc.powerdns.com/md/appendix/crypto-notes-export/

**Comment by pieterlexis** [comment]
Broken link to domain metadata:

* https://doc.powerdns.com/authoritative/dnsupdate.html#soa-edit-dnsupdate-settings

**Comment by Habbie** [comment]
https://doc.powerdns.com/authoritative/dnssec/operational.html#epoch wrongly claims that EPOCH is deprecated in 4.1.0.

**Comment by Habbie** [comment]
'convience' misspelling of 'convenience' in a few places

**Comment by pieterlexis** [comment]
https://doc.powerdns.com/authoritative/appendices/types.html

note statement is parsed incorrectly

**Comment by Habbie** [comment]
Missing: https://doc.powerdns.com/md/appendix/compiling-powerdns/

**Comment by zeha** [comment]
The new key also needs to be added to https://doc.powerdns.com/md/appendix/compiling-powerdns/

**Comment by pieterlexis** [comment]
* [x] Missing from the new docs: https://doc.powerdns.com/md/appendix/crypto-notes-export/
* [x] Broken link to domain metadata: https://doc.powerdns.com/authoritative/dnsupdate.html#soa-edit-dnsupdate-settings
* [x] https://doc.powerdns.com/authoritative/dnssec/operational.html#epoch wrongly claims that EPOCH is deprecated in 4.1.0.
* [x] Missing: https://doc.powerdns.com/md/appendix/compiling-powerdns/
* [ ] The new key also needs to be added to https://doc.powerdns.com/md/appendix/compiling-powerdns/

> 'convience' misspelling of 'convenience' in a few places

I only found one instance of this in the dnsdist docs.

**Comment by Habbie** [comment]
> I only found one instance of this in the dnsdist docs.

Confirmed!
