### ISSUE TITLE
Recursor setting "webserver-address" differs from documentation

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#5728]
- Program: Recursor
 - Issue type: Bug

### Short description
[webserver-address](https://doc.powerdns.com/recursor/settings.html?highlight=webserver#webserver-address) says
> IP Addresses, separated by spaces

But the Recursor only picks the first address from this list to listen on.

### Environment

 - Operating system: SLES12
 - Software version: PowerDNS Recursor 4.0.6
 - Software source: PowerDNS repository, compiled myself 

### Steps to reproduce

1. `pdns_recursor --daemon=no --webserver=yes --webserver-address="127.0.0.1 127.0.0.2"`

### Expected behaviour
```
...
Listening for HTTP requests on 127.0.0.1:8082
Listening for HTTP requests on 127.0.0.2:8082
...
```
### Actual behaviour

```
...
Listening for HTTP requests on 127.0.0.1:8082
...
```

**Comment by zeha** [comment]
The old docs did not say that. Also, Auth has the same issue.
