### ISSUE TITLE
Allow database password to be stored in separate file

### ISSUE THREAD

**Issue by velotraveler** [PowerDNS/pdns#5731]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Allow storage of database password in separate file

### Usecase
Preserve password confidentiality when config file is checked into source control repository

### Description

New keyword "gmysql-password-file=FILENAME" where FILENAME contains the database password. 

We want to keep our PowerDNS configuration file in a source code repository, but without this feature that means we'd expose the password to everyone with read access to the repository.  Also, we'd like to have pdns.conf have global read permissions when it's installed on the server so any user can review it, but again that would expose the database password.  Keeping the password in a separate file will allay those concerns, since we can deploy the password file via a different method, and we can adjust the permissions on the password file so it is only readable by the user running PowerDNS.

"gmysql-password" and "gmysql-password-file" should probably be mutually exclusive (i..e. it would be a startup error if both were present in the same config file).

**Comment by zeha** [comment]
You can use include files today.

**Comment by velotraveler** [comment]
Indeed, I can! It's a little clumsy as it needs a separate directory for a single include file, but it works.

**Comment by Habbie** [comment]
@velotraveler shall we close the ticket?

**Comment by velotraveler** [comment]
Yes, thank you.
