### ISSUE TITLE
Option for the API to check if a domain exists

### ISSUE THREAD

**Issue by nlmark** [PowerDNS/pdns#5736]
- Program: Authoritative
 - Issue type: Feature request

### Short description
If you request a domain that does not exist it returns a http status code 422. It would be nice to have a separate check/test for this I believe.

### Usecase
It makes automation easier to see if you have to remove a domain if it exists or add a domain if it doesn't exists.

### Description
A 200 http status code with a short message informing about the status would be nice.

**Comment by pieterlexis** [comment]
Doesn't the /api/v1/server/localhost/zones/example.com. return a 404 if it doesn't exist?

**Comment by rvdh** [comment]
@pieterlexis No, it returns 422.

**Comment by zeha** [comment]
Directly going to that URL is also bad - that relies on knowing the pdns-internal applied transformation of the domain name...

**Comment by pieterlexis** [comment]
so how about `/zones?exists=example.com` that returns a json:
```json
{ 
  "name": "example.com",
  "exists": false
}
```
```json
{ 
  "name": "example.com",
  "exists": true,
  "url": "/zones/example.com."
}
```

**Comment by zeha** [comment]
I think we should "just" have a filter on /zones that limits the result to the one zone. Doesn't need any special "exists" thingy...

**Comment by Habbie** [comment]
> Directly going to that URL is also bad - that relies on knowing the pdns-internal applied transformation of the domain name...

Me pointing this out to @nlmark and others is what led to this ticket, indeed!

**Comment by zeha** [comment]
#6668 did this.
