### ISSUE TITLE
Option for the API to list all zones it has in a backend

### ISSUE THREAD

**Issue by nlmark** [PowerDNS/pdns#5737]
- Program: Authoritative
 - Issue type: Feature request

### Short description
As far as I could see there isn't an option to get all zones it knows about so you can verify the list is correct with another database and remove any zones that are no longer/not wanted. It would be nice to have an option for this without having to get the information directly from the backend (eg using a MySQL query).

### Usecase
It would make it easier to periodically clean the PowerDNS information in an automated way. An alternative could be a search option so you could get it based on the first character of a zone.

### Description
List all zones it knows about.

**Comment by Habbie** [comment]
I'm missing something - isn't this `GET /api/v1/servers/:server_id/zones` ?

**Comment by Habbie** [comment]
ping

**Comment by nlmark** [comment]
That is correct, I probably missed it in the documentation (or I did look for the wrong words). The POST is documented as it creates a new zone and the GET isn't documented (at least I don't see it on https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones ). What is the correct file to write the documentation? I'll probably create some new documentation in it and provide a pull request.

**Comment by Habbie** [comment]
It is documented here https://doc.powerdns.com/authoritative/http-api/zone.html
