### ISSUE TITLE
doc update: add "net.local.dgram.recvspace=65536" to FreeBSD section.

### ISSUE THREAD

**Issue by ghost** [PowerDNS/pdns#5745]
- Program: Recursor 
 - Issue type: Feature request 

### Short description

Update docs and mention that for FreeBSD or for systems with too low datagram receive space setting, it's needed to increase it in order for rec_control to work correctly.

### Environment

 - Operating system: FreeBSD 11.1-STABLE
 - Software version: PowerDNS-recursor 4.0.6
 - Software source: FreeBSD ports collection 

### Expected behaviour

rec_control should work

### Actual behaviour

rec_control produces:
**Fatal: Timeout waiting for answer from control channel**

### Description

Add _net.local.dgram.recvspace=65536_ to FreeBSD-specific section in documentation.

**Comment by cwiggs** [comment]
Do you want this added to docs/installation.rst under the freebsd section?

I can add a section that says to add 'net.local.dgram.recvspace=65536' to /etc/sysctl.conf.

**Comment by RvdE** [comment]
This doesn't work for me on FreeBSD 11.1-RELEASE

**Comment by krionbsd** [comment]
What doesn't work on FreeBSD 11.1-RELEASE? IIRC, net.local.dgram.recvspace exists starting from FreeBSD 5.x

**Comment by RvdE** [comment]
The fix from #4141 works for me, which sets a slightly different sysctl than the one suggested by this issues TS

**Comment by Habbie** [comment]
When rec_control fails to get stats, does `rec_control ping` still work?

**Comment by RvdE** [comment]
Hi,

 

I’ve set net.local.dgram.maxdgram=131072 and left local.dgram.recvspace untouched (default is 4096). Can’t remember having any issues after that.

[(Mon Nov 12 11:39) root@lan ~]# sysctl -a | grep dgram

net.local.dgram.recvspace: 4096

net.local.dgram.maxdgram: 131072

 

Hopefully that’ll work for you as well.

 

Regards,

Ralf

**Comment by drixter** [comment]
Logs from trying to run get-all and ping when it's doesn't work:
https://zerobin.e-utp.net/?7cbad8b9969700ab#XLHL7xM084We/bHQqDHXUZKuuPF3bDVSHIczoriRSTQ=

**Comment by Habbie** [comment]
`sendto(9,"all-outqueries\t120408\nanswers-"...,2051,0,{ AF_UNIX "/var/run/lsockRekRHM" },106) ERR#40 'Message too long'`

so it looks like your `get-all` works until it grows to be too big, in this case, 2051 bytes - can you check for any sysctls set to 2048?

**Comment by drixter** [comment]
root@brix:~ # sysctl -a | grep 2048
kern.ipc.msgseg: 2048
kern.ipc.msgtql: 2048
kern.fscale: 2048
1 PART ada0p1 209715200 512 i 1 o 20480 ty efi xs GPT xt c12a7328-f81f-11d2-ba4b-00a0c93ec93b
            <offset>20480</offset>
   9 (  2048K)  |       0  |       0
   9 (  2048K)  |       0  |       0
vm.background_launder_max: 20480
net.inet.sctp.incoming_streams: 2048
net.graph.recvspace: 20480
net.graph.maxdgram: 20480
debug.sx.delay_max: 2048
debug.rwlock.delay_max: 2048
debug.mtx_spin.delay_max: 2048
debug.mtx.delay_max: 2048
hw.ix.rxd: 2048
hw.ix.txd: 2048
user.bc_dim_max: 2048
user.line_max: 2048
dev.netmap.priv_buf_size: 2048
dev.netmap.buf_size: 2048
dev.netmap.priv_ring_size: 20480
root@brix:~ #

And now changed:
net.local.dgram.recvspace=65536
net.local.dgram.maxdgram=131072

But not restarted pdns-recursor yet.

**Comment by Habbie** [comment]
#4141 says restarting might be necessary.

**Comment by drixter** [comment]
OK, restart of service done, next update in next 48h+, we will if this will help what @RvdE suggested.
