### ISSUE TITLE
Trailing questions from merge of 5716

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5746]
"(just spit balling here) is getDSRecords() ever called in a way there we won't need to know the denialstate? I mean that if we have 'false' DS records we should check this regardless of the fact that we want to know if we are at a zonecut?" [link](https://github.com/PowerDNS/pdns/pull/5716#discussion_r141543481)
![image](https://user-images.githubusercontent.com/1223657/30984413-8ce4a794-a48d-11e7-9a46-5fdbb391cfbc.png)

**Comment by rgacogne** [comment]
There are two cases where we currently do not want to know if we are at a zone cut:
- when we are only looking for `TA` or `NTA` ;
- when we are retrieving `DS` for validating a `DNSKEY` set, and then we only care whether we can get one or more valid `DS`, which would anyway indicate a cut, or not.

So the current beahvior looks good to me :)
