### ISSUE TITLE
Trailing questions from merge of 5716 part 2

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#5747]
"should we check for v.first.first.isPartOf(getSigner(v.second.signatures)) here?" [link](https://github.com/PowerDNS/pdns/pull/5716#discussion_r141553262)

![image](https://user-images.githubusercontent.com/1223657/30984477-b0215d24-a48d-11e7-897e-dfe607287386.png)

**Comment by rgacogne** [comment]
Looking at the code, we should not get there with a validated set if that condition is false. I'll nonetheless add the check because it might catch some mistake, present or future!

**Comment by pieterlexis** [comment]
There is a similar piece of code in the NSEC section of the function as well btw
