### ISSUE TITLE
remote, real-remote is not set at lookup query of remotebackend.

### ISSUE THREAD

**Issue by disco-v8** [PowerDNS/pdns#5751]
Although version is unknown, remote and real-remote are no longer set in SOA. why?

**Comment by rgacogne** [comment]
Could you please indicate which version you are using, and provide some traces or at least a reliable way to reproduce your issue? There is a reason we are providing a template at the opening of a new issue.

**Comment by disco-v8** [comment]
Hello!

# cat /etc/centos-release
CentOS release 6.9 (Final)

# rpm -qa | grep pdns
pdns-0.0.1862g8b3f9b4-1pdns.el6.x86_64
pdns-backend-postgresql-0.0.1862g8b3f9b4-1pdns.el6.x86_64
pdns-backend-remote-0.0.1862g8b3f9b4-1pdns.el6.x86_64
pdns-tools-0.0.1862g8b3f9b4-1pdns.el6.x86_64
pdns-backend-pipe-0.0.1862g8b3f9b4-1pdns.el6.x86_64

# yum info pdns-0.0.1862g8b3f9b4-1pdns.el6.x86_64
Installed Packages
Name        : pdns
Arch        : x86_64
Version     : 0.0.1862g8b3f9b4
Release     : 1pdns.el6
Size        : 8.6 M
Repo        : installed
From repo   : powerdns-auth-master
Summary     : A modern, advanced and high performance authoritative-only nameserver
URL         : https://powerdns.com
License     : GPLv2
Description : The PowerDNS Nameserver is a modern, advanced and high performance
            : authoritative-only nameserver. It is written from scratch and conforms
            : to all relevant DNS standards documents.
            : Furthermore, PowerDNS interfaces with almost any database.

# yum info pdns-backend-remote-0.0.1862g8b3f9b4-1pdns.el6.x86_64
Name        : pdns-backend-remote
Arch        : x86_64
Version     : 0.0.1862g8b3f9b4
Release     : 1pdns.el6
Size        : 442 k
Repo        : installed
From repo   : powerdns-auth-master
Summary     : Remote backend for pdns
URL         : https://powerdns.com
License     : GPLv2
Description : This package contains the remote backend for pdns

Older...
{"method": "lookup", "parameters": {"local": "0.0.0.0", "qname": "example.jp.", "qtype": "SOA", "real-remote": "xxx.xxx.xxx.xxx/32", "remote": "xxx.xxx.xxx.xxx", "zone-id": -1}}

Now...
{"method": "lookup", "parameters": {"local": "0.0.0.0", "qname": "example.jp.", "qtype": "SOA", "real-remote": "0.0.0.0/32", "remote": "0.0.0.0", "zone-id": -1}}

**Comment by rgacogne** [comment]
Looks related to #5512, packet-specific information is not passed to `SOA` lookups anymore. Do you get them on non-`SOA` lookups?

**Comment by disco-v8** [comment]
Oh ... Thanks!!!
I changed to NS query. (real-)remote address.
