### ISSUE TITLE
Unable to build powerdns from source

### ISSUE THREAD

**Issue by mislav-eu** [PowerDNS/pdns#5768]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system:  Debian 7, Wheezy
 - Software version: - 
 - Software source: I'm using this command to get repo:
git clone https://github.com/PowerDNS/pdns.git 

### Steps to reproduce

1.  Clean Debian 7 server, install git command via apt and use 
git clone https://github.com/PowerDNS/pdns.git
2.  Once done, enter folder, and per instructions use:
$ ./bootstrap
$ ./configure --without-lua
$ make
3.  Error will occur

### Expected behaviour
 Successful compile, if possible.

### Actual behaviour
 When I did first make, I received this:

make[2]: Entering directory `/opt/pdns/docs'
echo "You need virtualenv to generate the manpages"
You need virtualenv to generate the manpages
exit 1

Then I fixed it with command "apt-get install python-virtualenv". After new make command I got:
ImportError: No module named setuptools

and this I fixed with:
pip install -U pip setuptools 

after that I got:
make[2]: Entering directory `/opt/pdns/docs'
.venv/bin/python -msphinx -b man . mans manpages/pdns_server.1.rst
/opt/pdns/docs/.venv/bin/python: No module named sphinx
make[2]: *** [pdns_server.1] Error 1

and this is something I can't fix anymore...I've installed sphinx
$ pip install sphinx
Requirement already satisfied: sphinx in /usr/lib/pymodules/python2.7
Requirement already satisfied: Pygments>=1.2 in /usr/lib/python2.7/dist-packages (from sphinx)
Requirement already satisfied: Jinja2>=2.3 in /usr/lib/python2.7/dist-packages (from sphinx)
Requirement already satisfied: docutils>=0.7 in /usr/lib/pymodules/python2.7 (from sphinx)

also dir under /usr/lib/pymodules/python2.7/sphinx/ exists

### Description

So, the question is:
- is it possible to compile from source latest version of pdns from github on Debian Wheezy (7)? I assume that is version is 4.1.x. 

Our idea was to replace current 3.1.x with 4.1.x, but on the same server (and Debian 7 is there), as we want to avoid IP change. Or 4.1.x. compile is only possible in Debian 8/9?

**Comment by Habbie** [comment]
Hello, please direct support questions to our IRC channel or one of our mailinglists. Details at https://www.powerdns.com/opensource.html
