### ISSUE TITLE
PDNS sends randomly refused answer to reqursive querries

### ISSUE THREAD

**Issue by mklimkow** [PowerDNS/pdns#5795]
- Program: Authoritative + Recursor
 - Issue type: Bug report

### Short description
Every day we get errors while sending querries to Powerdns. PDNS sends refused answer while querring google.com (for example).  Refreshing browser few times helps.

### Environment
 - Operating system: (Ubuntu 5.4.0-6ubuntu1~16.04.4, Linux version 4.4.0-83-generic 64 bit
 - Software version:  
    pdns-backend-mysql/now 4.0.4-1pdns.xenial amd64
    pdns-recursor/,now 4.0.6-1pdns.xenial amd64
    pdns-server/,now 4.0.4-1pdns.xenial amd64

 - Software source:  PowerDNS repository, 

 (Lua) scripts that are loaded. - yes

Some statisctcs:

Uptime: 2.04 months
Queries/second, 1, 5, 10 minute averages: 424, 416, 418. Max queries/second: 1.98e+03
Cache hitrate, 1, 5, 10 minute averages: 43.8%, 42.2%, 41.7%
Backend query cache hitrate, 1, 5, 10 minute averages: 81.7%, 81.3%, 81.3%
Backend query load, 1, 5, 10 minute averages: 138, 147, 150. Max queries/second: 386
Total queries: 2028883512. Question/answer latency: 0.056ms

**Comment by Habbie** [comment]
Can you show your (unedited, other than passwords) configuration files and scripts?

**Comment by mklimkow** [comment]
Here you go:
[Config.zip](https://github.com/PowerDNS/pdns/files/1368270/Config.zip)

**Comment by Habbie** [comment]
Ah, `recursor=` in pdns.conf. That is known to not work very well - because of that, we removed it in 4.1 in fact. Please point your recursive clients directly at your recursor.

**Comment by Habbie** [comment]
https://doc.powerdns.com/authoritative/guides/recursion.html has guidance for changing your setup in this way. If you need help, please find us on IRC or the mailing lists, see https://www.powerdns.com/opensource.html

**Comment by mklimkow** [comment]
Thank you for a very quick answer. I'll try to change our config in the way you suggested.
