### ISSUE TITLE
drop Botan 1.10 support

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5797]
- Program: Authoritative, Recursor
 - Issue type: Hardening

### Short description
From https://github.com/randombit/botan/blob/master/news.rst#version-11014-2016-11-28:

> NOTE WELL: Botan 1.10.x is supported for security patches only until 2017-12-31

This means we should start getting rid of PowerDNS deployments linked against Botan 1.10 now. Right now, this means dropping GOST support. We have a PR for Botan 2.x support at #5498 but this won't help the users much - Botan 2 is not present in Debian etc. yet.

Tasks:
1. remove Botan 1.10 support from the code base
2. backport this removal to auth&rec 4.0.x
3. release auth 4.1.0 and rec 4.1.0 without Botan 1.10 support
4. make sure we do auth&rec 4.0.x releases sometime soon so repo.powerdns.com stops pulling in Botan

**Comment by rgacogne** [comment]
Support for Botan 1.10 has been removed in master by #5498, we still need to backport this removal to auth and rec 4.0.x.

**Comment by rgacogne** [comment]
Support for Botan 1.10 has been removed in auth 4.0.5 and rec 4.0.7 in favor of Botan 2.
