### ISSUE TITLE
Incorrect answer on CAA record query

### ISSUE THREAD

**Issue by ikheetleon** [PowerDNS/pdns#5806]
I'm running into issue's with Let's Encrypt and powerdns. I've already been reading about similar bugs which should be fixed in 4.0.4. I'm running pdns-4.0.4-1pdns.el6.x86_64 from the powerdns repository for Centos 6.
When I do a CAA query for a record that does not exist, I get a NOERROR. I would expect an NXDOMAIN.

Example:

[root@colo /]# dig @colo caa www.xxxxxxxx.nl

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> @colo caa www.xxxxxxxx.nl
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **NOERROR**, id: 13050
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.xxxxxxxx.nl.           IN      CAA

;; AUTHORITY SECTION:
xxxxxxxx.nl.        86400   IN      SOA     ns1.yyyyyyy.com. hostmaster.xxxxxxxx.nl. 2017101002 28800 7200 1209600 86400

----------------------------------------------
And if I run the query for an existing record:

[root@colo /]# dig @colo caa xxxxxxxx.nl    

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> @colo caa xxxxxxxx.nl
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32118
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;xxxxxxxx.nl.               IN      CAA

;; ANSWER SECTION:
xxxxxxxx.nl.        86400   IN      CAA     0 issue "letsencrypt.org"
xxxxxxxx.nl.        86400   IN      CAA     0 issuewild "\;"

;; Query time: 9 msec
;; SERVER: 2001:41f0:5082:1::10#53(2001:41f0:5082:1::10)
;; WHEN: Tue Oct 10 20:56:24 2017
;; MSG SIZE  rcvd: 91

Anyhow, because the Let's encrypt validator get's a noerror (but empty response) it will give a SERVFAIL error and won't proceed.

www.xxxxxxxx.nl:Verify error:DNS problem: SERVFAIL looking up CAA for www.xxxxxxxx.nl

Since I'm only using Let's encrypt certificates for this domain, I only want to specify the CAA record in the top level domain and not for every additional A record. If I add the additional CAA for each and every record, it does work. Since that's a lot of extra work (and according to the CAA check that should not have to be done), I want to understand what's going on.
Maybe I'm wrong and it should not give a NXDOMAIN on a non-existing CAA record. If that's the case, I will ask the Let's encrypt community for clues.

**Comment by Habbie** [comment]
Hello!

it appears you edited your dig input and output. We cannot provide support if you do that. Please read https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/ for the background on this.

**Comment by ikheetleon** [comment]
Sorry about that, it's a habbit of not leaking stuff on the internet. Here are the query's without editting.

[root@colo /]# dig @colo caa www.dvid.nl

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> @colo caa www.dvid.nl
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15057
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.dvid.nl.                   IN      CAA

;; AUTHORITY SECTION:
dvid.nl.                86400   IN      SOA     ns1.ofwegen.com. hostmaster.dvid.nl. 2017101009 28800 7200 1209600 86400

;; Query time: 2 msec
;; SERVER: 2001:41f0:5082:1::10#53(2001:41f0:5082:1::10)
;; WHEN: Tue Oct 10 21:53:07 2017
;; MSG SIZE  rcvd: 91

And the correct one:

[root@colo /]# dig @colo caa dvid.nl

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> @colo caa dvid.nl
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34492
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;dvid.nl.                       IN      CAA

;; ANSWER SECTION:
dvid.nl.                3600    IN      CAA     0 issue "letsencrypt.org"

;; Query time: 0 msec
;; SERVER: 2001:41f0:5082:1::10#53(2001:41f0:5082:1::10)
;; WHEN: Tue Oct 10 21:52:38 2017
;; MSG SIZE  rcvd: 59

**Comment by mnordhoff** [comment]
`NXDOMAIN` means that the name does not exist, has no records of any type, and has no subdomains. (Some older, non-DNSSEC authoritative servers disagree about the last one.)

Since `www.dvid.nl.` has an `A` record, it would be incorrect to return `NXDOMAIN`. A `NODATA` `NOERROR` response is correct.

Clearly there's something wrong with the response, and i'm not certain what it is, but it's not that.

**Comment by ikheetleon** [comment]
But the query type is CAA not A.
There is no CAA record for www.dvid.nl

**Comment by rgacogne** [comment]
@mnordhoff is right, `NODATA` is the correct answer here since it means that there is no data for the requested `CAA` type, but other types exist so the name exists. `NXDOMAIN` would mean that there is no records for any type and no subdomains, as clarified in rfc8020 [1].

[1]: https://tools.ietf.org/html/rfc8020

**Comment by ikheetleon** [comment]
So from a DNS point of view, the answer is correct. Than the conclusion would be that Let's encrypt is misinterpreting the answer and therefor not going further up the DNS tree (i.e. dig CAA dvid.nl)?

**Comment by rgacogne** [comment]
No, the DNSSEC proof is not correct, most likely because you didn't rectify your database correctly. Since this is neither a bug report nor a feature request, please continue this conversation on IRC or our mailing-lists: https://www.powerdns.com/opensource.html
