### ISSUE TITLE
omitting default-zsk-algorithm in pdns.conf will result in a warning

### ISSUE THREAD

**Issue by foxxx0** [PowerDNS/pdns#5809]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When the setting `default-zsk-algorithm` is not specified in the pdns.conf it will cause a warning at startup:

`Warning: default-zsk-algorithm set to unknown algorithm: `

### Environment
 - Operating system: Arch Linux x64
 - Software version: pdns auth 4.1.0-rc1 from git with PR 5777 applied
 - Software source: compiled myself, based on the following commit: https://github.com/rgacogne/pdns/commit/e3200e070e7cc4e243676776c41eb806c4edb7a5

### Steps to reproduce
1. remove any `default-zsk-algorithm` lines from your pdns.conf
2. increase the loglevel sufficiently (with 99 the warning is printed for sure)
3. start pdns

### Expected behaviour
I think pdns should rather print "using default `default-zsk-algorithm` value of: $algo" instead of producing a warning.

### Actual behaviour
pdns prints said warning with no information about the actually used `default-zsk-algorithm`.

**Comment by pieterlexis** [comment]
Leaving it empty (as is the default) is actually a correct configuration, as we won't create a KSK/ZSK split.
