### ISSUE TITLE
Systemd unit file --daemon=no caused systemd timeout message

### ISSUE THREAD

**Issue by mortenstevens** [PowerDNS/pdns#5823]
- Program: Authoritative
 - Issue type: Bug report

### Short description
This is not a major issue, but this should not happen. Actually we use type=forking and --daemon for Fedora and RHEL 7. But we like to stay close with upstream: https://github.com/PowerDNS/pdns/blob/master/pdns/pdns.service.in. Seems all good except the daemon=no option. If I change the type to notify and daemon=no this will result in a systemd timeout message. But pdns is running despite the systemd timeout error.

Note: There is another selinux related  issue with NoNewPrivileges=true.  We are not using NoNewPrivileges=true because this results in a selinux error. But I guess this needs to be fixed in our selinux-policy. See bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1305522

### Environment

 - Operating system: Fedora 26, Fedora 27, Fedora rawhide, RHEL 7
 - Software version:  pdns 4.0 pdns-4.1-rc1
 - Software source:  Fedora

### Steps to reproduce

1. dnf/yum install pdns
2. Edit the systemd unit file to type=notify and --daemon=no or import the upstream systemd unit file. I have attached my systemd unit file which we plan to use for Fedora.
3. systemctl daemon-reload
4. systemctl start pdns

### Expected behaviour

No systemd timeout message

### Actual behaviour

[root@fc26 ~]# systemctl start pdns
Job for pdns.service failed because a timeout was exceeded.
See "systemctl  status pdns.service" and "journalctl  -xe" for details.

### Other information
systemd unit file

[pdns.service](https://github.com/PowerDNS/pdns/files/1385569/pdns.txt)

**Comment by zeha** [comment]
Please show the parameters to `configure` and its output, too!

**Comment by mortenstevens** [comment]
@zeha 
See: https://src.fedoraproject.org/rpms/pdns/blob/master/f/pdns.spec

%configure \
--
  | --sysconfdir=%{_sysconfdir}/%{name} \
  | --disable-static \
  | --disable-dependency-tracking \
  | --disable-silent-rules \
  | --with-modules='' \
  | --with-lua \
  | --with-dynmodules='%{backends}' \
  | --enable-tools \
  | --enable-remotebackend-zeromq \
  | --enable-unit-tests \
  | --enable-reproducible

Build log: https://kojipkgs.fedoraproject.org//packages/pdns/4.1.0/0.2.rc1.fc28/data/logs/x86_64/build.log

**Comment by Habbie** [comment]
```
checking systemd/sd-daemon.h usability... no
checking systemd/sd-daemon.h presence... no
checking for systemd/sd-daemon.h... no
```

libsystemd appears to be missing in your build env

**Comment by mortenstevens** [comment]
@Habbie 

I guess this is it. We are actually not using --with-systemd since we used our own systemd unit file. But I guess if we use --daemon=no and type=notify we need to use --with-systemd?

**Comment by Habbie** [comment]
Yes, no notify without it.

**Comment by mortenstevens** [comment]
@Habbie 

All right. I close this, because it's not an upstream bug. But it would be interesting to know if you're able to reproduce the selinux based issue with NoNewPrivileges=true?

**Comment by Habbie** [comment]
@mortenstevens we are happy to try but we need an open ticket or we'll forget.

**Comment by mortenstevens** [comment]
@Habbie 

Thanks. The issue is confirmed by the selinux-policy maintainer. See https://bugzilla.redhat.com/show_bug.cgi?id=1305522

But maybe you consider to disable NoNewPrivileges by default until this selinux issue has been solved.

In the meantime I have updated our pdns builds for Fedora with some spec file fixes and with --enable-systemd to use the upstream systemd support for Fedora. See my Fedora commit here:  https://src.fedoraproject.org/rpms/pdns/c/79d38387eeb476c9bf36a62098410be26da4a5c4

I will reenable NoNewPrivileges if the selinux issue (#1305522) has been solved.

**Comment by mortenstevens** [comment]
@Habbie 
Here is an update: The selinux issue has been resolved with the latest selinux package (selinux-policy-3.13.1-298) for Fedora rawhide. See: https://bugzilla.redhat.com/show_bug.cgi?id=1305522#c8

I have updated PowerDNS to use the upstream systemd unit file.
