### ISSUE TITLE
Zone name does not change with API call.

### ISSUE THREAD

**Issue by dachinat** [PowerDNS/pdns#5829]
I'm using PowerDNS Authoritative Server 4.1.0-rc1

Docs at https://doc.powerdns.com/authoritative/http-api/endpoint-zones.html say:

> PUT /api/v1/servers/:server_id/zones/:zone_id Modifies basic zone data (metadata).
> Changing name renames the zone, as expected.

When I make a request as follows

```
curl -X PUT \
  http://<MY_IP>:<MY_PORT>/api/v1/servers/localhost/zones/<MY_DOMAIN>. \
  -H 'content-type: application/json' \
  -H 'x-api-key: <MY_KEY>' \
  -d '{
      "kind": "Master",
      "name": "<NEW_NAME>."
  }'
```

A type is being hanged to Master however name stays the same.

**Comment by zeha** [comment]
I don't think I've typed in the code to make this work. Would propose to just document `name` as R/O? @pieterlexis?

**Comment by pieterlexis** [comment]
@zeha: yes, added to #5828.

I don't think it makes sense to have a feature like this to be honest. Renaming a whole zone and all rrsets is something that is not done frequently. Although it _could_ make sense for in-addr.arpa and ip6.arpa zones
