### ISSUE TITLE
dnsdist: ComboAddress encryption

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#5840]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

Especially for remote logging it would be great if we could encrypt the IP addresses (ComboAddress) as published here: [ipcrypt](https://github.com/veorq/ipcrypt) (I was reading  [On IP address encryption: security analysis with respect for privacy](https://medium.com/@bert.hubert/on-ip-address-encryption-security-analysis-with-respect-for-privacy-dabe1201b476) from @ahupowerdns)

For instance like this:
`classmethod ComboAddress:encrypt("some 16-byte key")`
`classmethod ComboAddress:decrypt("some 16-byte key")`

**Comment by rgacogne** [comment]
Implemented in #7481.
