### ISSUE TITLE
Create and Ship and official pdns docker image

### ISSUE THREAD

**Issue by ffledgling** [PowerDNS/pdns#5844]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request 

### Short description

PowerDNS is a useful application. It'd be great if it shipped an official version (via docker-hub or similar) of the pdns server that can be run out of the box on containerization platforms.

### Usecase
Using pdns in containerized environments such as Kubernetes, Docker Compose, Docker Swarm etc.

### Description
A preconfigured pdns image that (optionally) ships with pdns and a default (not necessarily production worthy, but configurable) backend that can be used out of the box.

**Comment by tcely** [comment]
What kind of help are you seeking with this? It would help to clarify if the goal is an image for each function or a single image that allows running all of them.

**Comment by zeha** [comment]
Making these decisions is probably part of that help. (I don't see how one combined image is of much use, but there are certainly further questions that will come up...)

**Comment by ffledgling** [comment]
For what it's worth, I had a discussion with on IRC with a few of the devs, and the general sense I got was that due to support concerns an official docker image might not happen.

Reproducing the relevant bits of the conversation here:
```
11:51 < ffledgling> lieter: I'd also opened an issue requesting an official docker container that runs PDNS, do you have an opinion on that?
[...]
12:00 <@ahu> ffledgling: I don't think we'd support "an official docker container"
[...]
13:21 <@ahu> whatever we do
13:21 <@ahu> we end up supporting indefinitely
13:22 <@ahu> and people will open issues for it for the next 5 years
13:22 <@ahu> so before we expand our portfolio
13:22 < lieter> on the other hand, we already support the multitude of packages we publish to out own repos
13:22 <@ahu> we think long and hard
13:22 <@ahu> yes, this only makes it worse
13:23 < lieter> this does add another layer we might not want
13:23 < zeha> hard to see the value when you need to supply lots of your own files anyway
13:23 < zeha> (config, zones...)
```

So I'd probably doubelcheck with @ahupowerdns and @pieterlexis if they really still want this. If not, this should probably be closed with a wont-fix.

**Comment by tcely** [comment]
So I was playing with my own home DNS setup and built images for all three. If anyone wants examples, you can check out:

https://github.com/tcely/dockerhub-powerdns

As to the comment from `zeha` above about the value, I think having an official base image for each binary makes sense as it lets everyone with a docker environment skip over the get source, verify, compile and install steps of getting started with PowerDNS options.

**Comment by ffledgling** [comment]
ping @ahupowerdns  and @pieterlexis ; Thoughts on this thread?

**Comment by zeha** [comment]
I don't have anything to say about this, please disregard my earlier comments.

**Comment by Habbie** [comment]
Indeed we do not want to support an official container. I suggest making a list of docker containers on the github wiki. We can link to it from the docs.

**Comment by blop** [comment]
I think it's a mistake not to provide an official image for docker, it's a popular way to distribute software.
Also, it avoids people from using third party builds that might offer a less qualitative experience.

All it requires is basically 1 Dockerfile which lists the commands you need to perform to install it.
You could use the commands listed in the README and build from the sources, or just install of your existing packages on top of one of the already supported linux distribution.

See the documentation about official repositories : 
https://docs.docker.com/docker-hub/official_repos/#how-do-i-know-the-official-repositories-are-secure

And for example the file used to build the official HAProxy image : 
https://github.com/docker-library/haproxy/blob/6c6d92913f56e05d6985d2f0f2131675de68f915/1.8/Dockerfile

Hope you'll change your mind  ;-)
