### ISSUE TITLE
Performance optimizations in dnswriter.cc

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#585]
d_record is modified extensively using push_back()'s etc, however each one of those results in memory management changes as the vector increases. Putting a simple:

```
d_record.reserve(1024);
```

in `DNSPacketWriter::DNSPacketWriter()` results in a 5% performance increase however I'm not sure if there is a more intelligent way to estimate what the size of `d_record` would be.

Mark Zealey

**Comment by rgacogne** [comment]
`d_record` is gone since e636cab291ad76131abf453cf90d410e09d27b1e, closing.
