### ISSUE TITLE
Provide a swagger API spec for PDNS HTTP API

### ISSUE THREAD

**Issue by ffledgling** [PowerDNS/pdns#5854]
- Program: HTTP API
 - Issue type: Feature request 

### Short description
 PowerDNS provides a REST API for most operations, but there is no standard/de-facto set of client libraries to interact with it. Providing a swagger spec is also great for documentation.

### Expected behaviour
Have a Swagger API

### Actual behaviour
No Swagger API :(

### Other information

\#powerdns OFTC
```
16:44 <@ahu> we'll soon be doing open-api/swagger btw
16:46 < ffledgling> Cool, that might make writing client libraries trivial/much easier :)
17:14 < lieter> ffledgling: a swagger schema based on what is already there is welcome ;)
```

**Comment by pieterlexis** [comment]
fixed for auth in #5862

**Comment by ffledgling** [comment]
@pieterlexis can we close this issue now, or can it only be closed once there's an official release with the swagger spec?

**Comment by zeha** [comment]
@ffledgling Recursor also has an API that would benefit from this.

**Comment by kpfleming** [comment]
It appears that this can be closed, as there is most definitely a Swagger specification for the API now :-)

**Comment by Habbie** [comment]
yes! thanks!
