### ISSUE TITLE
Initial notify using bind-backend not happening for new zones

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#587]
Hi,

Using bind-backend on our hidden master, we noticed that the initial notify to the slave's are not being sent. 

Bind normally sends a notify for all (new) zones to it's slaves on startup and will do that too for any newly created zones, however powerdns doesn't do that. 

Since we use supermaster functionality on the auth. servers, this breaks our setup.

Wouter@Oxilion

**Comment by mitar** [comment]
Any update on this?

**Comment by omoerbeek** [comment]
Known issue with no real solution, as the bind backend has no state.

**Comment by mitar** [comment]
Why not simply on every startup automatically notify for all zones known to powerdns? New or not?
