### ISSUE TITLE
Travis: research and enable -Wshadow

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#5875]
### Short description
We now get shadowed vars warnings via coverity, which is in the 'too late' territory.

> I think we should:
> * enable `-Wshadow` by default, even outside travis
> *  since `-Werror` is super annoying, especially on old compilers, see if the versions of gcc and clang we have on travis support `-Werror=shadow` which turns only warnings about shadowed variables into error, not all warnings.

**Comment by rgacogne** [comment]
FYI, I tried enabling `-Werror=shadow` in Travis but it turns out that the code generated by proto-c doesn't play well with this, at least with the version of proto-c we have in travis. To be continued.

**Comment by rgacogne** [comment]
I also missed a lot of shadowed variables in the `Lua` backend apparently..

**Comment by omoerbeek** [comment]
We have moved to ` -Wall -Wextra -Wshadow` (and more) a long time ago

**Comment by rgacogne** [comment]
Which covers the first point but not the second, unless I'm mistaken?
