### ISSUE TITLE
documentation should clearly indicate migrating page is for authoritative not recursor

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#5886]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
[Documentation](https://www.powerdns.com/documentation.html) has `Migrating to PowerDNS`.

That should mention (authoritative) or something.

I "want to migrate to powerdns" but that link is a red-herring

### Steps to reproduce
1. Decide to "migrate (from dnsmasq) to powerdns recursor"
2. Visit https://www.powerdns.com/documentation.html
3. Read

### Expected behaviour
Link should indicate it's about the authoritative resolver and not the recursor

### Actual behaviour
Obvious and tempting link leads down the wrong rabbit hole.

### Usecase
Migrate from dnsmasq to powerdns recursor

**Comment by pieterlexis** [comment]
The website is updated to fix this issue. Thanks!
