### ISSUE TITLE
missing secpoll TXT for recursor 4.1.0-rc2

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#5887]
- Program: Recursor
 - Issue type: Bug report

### Short description
Secpoll does not work for recursor-4.1.0-rc2

### Environment
 - Operating system: centos 7
 - Software version: 4.1.0-rc2
 - Software source: PowerDNS repository

### Steps to reproduce
start powerdns and check log

### Expected behaviour
no error messages

### Actual behaviour
Error message:
``` Could not retrieve security status update for '4.1.0-rc2' on 'recursor-4.1.0-rc2.security-status.secpoll.powerdns.com', RCODE = Non-Existent domain ``` 

### Other information
rc1 has a secpoll TXT record:
``` 
dig txt recursor-4.1.0-rc1.security-status.secpoll.powerdns.com +short
"1 OK"
``` 

however, rc2 does not:

``` 
dig txt recursor-4.1.0-rc2.security-status.secpoll.powerdns.com

; <<>> DiG 9.8.3-P1 <<>> txt recursor-4.1.0-rc2.security-status.secpoll.powerdns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25302
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;recursor-4.1.0-rc2.security-status.secpoll.powerdns.com. IN TXT

;; AUTHORITY SECTION:
secpoll.powerdns.com.	10074	IN	SOA	pdns-public-ns1.powerdns.com. pieter\.lexis.powerdns.com. 2017102601 10800 3600 604800 10800
```

**Comment by aerique** [comment]
Thanks for your report @gryphius.
