### ISSUE TITLE
recursor DNS64 should not generate AAAA for bogus domains

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#5888]
- Program: Recursor
 - Issue type: Bug report

### Short description
dns64 with enabled dnssec validation should not generate AAAA records when the domain's A result is BOGUS

### Environment
 - Operating system: centos 7
 - Software version: 
``` 
Nov 01 08:29:53 PowerDNS Recursor 4.1.0-rc2 (C) 2001-2017 PowerDNS.COM BV
Nov 01 08:29:53 Using 64-bits mode. Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-11) on Oct 30 2017 14:01:47 by buildbot@3038c79e458f.
``` 

 - Software source: Powerdns Repository

### Steps to reproduce
1. install powerdns recursor:

``` 
yum install epel-release yum-plugin-priorities &&
curl -o /etc/yum.repos.d/powerdns-rec-41.repo https://repo.powerdns.com/repo-files/centos-rec-41.repo &&
yum install pdns-recursor
``` 

2. move away the default recursor.conf and add a simple dnssec-validating config:

```
cat recursor.conf
dnssec=validate
dnssec-log-bogus=yes
``` 

3. start the recursor with this config and verify that dnssec validation is working correctly
```
systemctl restart pdns-recursor

[root@localhost pdns-recursor]# dig @localhost AAAA dnssec-failed.org

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7 <<>> @localhost AAAA dnssec-failed.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 41756
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dnssec-failed.org.		IN	AAAA

;; Query time: 145 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 01 08:14:07 CET 2017
;; MSG SIZE  rcvd: 35

[root@localhost pdns-recursor]# dig @localhost A dnssec-failed.org

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7 <<>> @localhost A dnssec-failed.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30456
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dnssec-failed.org.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 01 08:14:12 CET 2017
;; MSG SIZE  rcvd: 35

```

both A and AAAA questions return SERVFAIL, as expected

the dnssec validation failure is confirmed in the log:

```
Nov 01 08:15:52 localhost.localdomain pdns_recursor[3144]: Answer to dnssec-failed.org|AAAA for 127.0.0.1:51752 validates as Bogus
Nov 01 08:15:57 localhost.localdomain pdns_recursor[3144]: Answer to dnssec-failed.org|A for 127.0.0.1:40686 validates as Bogus
```

4. now create the dns64 configuration as described in: https://doc.powerdns.com/md/recursor/dns64/

```
cat /etc/pdns-recursor/dns64.lua
-- this small script implements dns64 without any specials or customization
prefix = "fe80::21b:77ff:0:0"

function nodata ( dq )
  if dq.qtype ~= pdns.AAAA then
    return false
  end  --  only AAAA records

  dq.followupFunction = "getFakeAAAARecords"
  dq.followupPrefix = prefix
  dq.followupName = dq.qname
  return true
end

-- the ip6.arpa address is the reverse of the prefix address above
function preresolve ( dq )
  if dq.qtype == pdns.PTR and dq.qname:isPartOf(newDN("f.f.7.7.b.1.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa.")) then
    dq.followupFunction = "getFakePTRRecords"
    dq.followupPrefix = prefix
    dq.followupName = dq.qname
    return true
  end
  return false
end
```

```
cat /etc/pdns-recursor/recursor.conf
dnssec=validate
dnssec-log-bogus=yes
lua-dns-script=/etc/pdns-recursor/dns64.lua
```

5. restart the recursor and test the same queries again

```
systemctl restart pdns-recursor


dig @localhost AAAA dnssec-failed.org

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7 <<>> @localhost AAAA dnssec-failed.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37782
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dnssec-failed.org.		IN	AAAA

;; ANSWER SECTION:
dnssec-failed.org.	7200	IN	AAAA	fe80::21b:77ff:45fc:504b

;; AUTHORITY SECTION:
dnssec-failed.org.	3600	IN	SOA	dns101.comcast.org. dnsadmin.comcast.net. 2010101854 900 180 604800 7200

;; Query time: 4361 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 01 08:21:11 CET 2017
;; MSG SIZE  rcvd: 145


dig @localhost A dnssec-failed.org

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7 <<>> @localhost A dnssec-failed.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 62654
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dnssec-failed.org.		IN	A

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 01 08:21:43 CET 2017
;; MSG SIZE  rcvd: 35
```

### Expected behaviour
both queries should return SERVFAIL

### Actual behaviour
only the A query returned SERVFAIL. The AAAA query returned a DNS64 generated response:
``` dnssec-failed.org.	6222	IN	AAAA	fe80::21b:77ff:45fc:504b ```

### Other information
there was a related bugreport in https://github.com/PowerDNS/pdns/issues/4397
As a result there are commits "Don't validate when a Lua hook took the query". I haven't checked what these commits change exactly, but in general I think PowerDNS should *still* validate the upstream response and not generate AAAA from bogus A. 

https://tools.ietf.org/html/rfc6147#section-5.5
> If the data does not validate, the vDNS64 MUST respond with RCODE=2 (Server failure).

**Comment by rgacogne** [comment]
Well, the hard part is that by definition if you alter the content the validation status is not relevant anymore. What we could do, however, is to make the validation status available to some Lua hooks (`nodata`, `nxdomain`, `postresolve`) so that they could decide whether they want to alter a `Bogus` answer. Perhaps we should also provide a way to override the validation status from those hooks.

**Comment by gryphius** [comment]
> Well, the hard part is that by definition if you alter the content the validation status is not relevant anymore.
This applies to the validation status of the synthesiszed answer, yes. The validation status from the upstream AAAA and A responses is relevant. We need to be sure that there was in fact no AAAA from upstream before we even attempt to synthesize AAAA. Otherwise an attacker could "downgrade" a connection from native IPv6 to the NAT64 routing path and obviously forge the target IP,  somewhat defeating the purpose of validating dnssec in a DNS64/NAT64 setup.

> What we could do, however, is to make the validation status available to some Lua hooks (nodata, nxdomain, postresolve) 
sounds good.   https://doc.powerdns.com/md/recursor/dns64/ should probably be updated accordingly with either this change (only synthesize validated NODATA) or -if you decide not to  change the current behavior in the forseeable future for any reason - mention that DNS64+validation does not work as described in rfc6147 section 5.5

**Comment by rgacogne** [comment]
I'll add the validation status as a read-only member of the `DNSQuestion` object in these hooks for now, and then we can update the dns64 doc accordingly.

**Comment by gryphius** [comment]
thanks!
