### ISSUE TITLE
IPv4-only master complains about not reaching dual-stacked slaves on IPv6

### ISSUE THREAD

**Issue by tomsommer** [PowerDNS/pdns#5899]
A master with  `local-ipv6=` and therefore IPv6 disabled, will still try to do IPv6 communication with slaves running both IPv4 and IPv6 (with A and AAAA) records. 

The error in the logs are:
`pdns_server: Nov 02 18:41:02 Error trying to resolve '[x:x:x:x::x]:53' for notifying 'xxxxx.com' to server: Unable to send notify to [xx:xx:xx:xx::xx]:53: Network is unreachable`

`pdns_server: Nov 02 18:41:19 Notification for xxxx.com to [x:xx:x:x::xx]:53 failed after retries
`
The server starts correctly with:
```
Nov  2 15:43:39 ns1 pdns_server: Nov 02 15:43:39 UDP server bound to 0.0.0.0:53
Nov  2 15:43:39 ns1 pdns_server: Nov 02 15:43:39 TCP server bound to 0.0.0.0:53
```

Relates to #4121

**Comment by pieterlexis** [comment]
> A master with local-ipv6= and therefore IPv6 disabled, will still try to do IPv6 communication with slaves running both IPv4 and IPv6 (with A and AAAA) records.

An unset `local-ipv6` means that the auth will accept IPv6 connections (as it is not bound to an IPv6 addresses), but will still do outbound IPv6 connections.

But indeed, this is related to #4121

**Comment by tomsommer** [comment]
Right, but it shouldn't, the master doesn't even have an IPv6-address

**Comment by pieterlexis** [comment]
right, so we try really hard to notify, but it does seem that we don't take into account the fact that there is no v6 available

**Comment by needleshaped** [comment]
> An unset local-ipv6 means that the auth will accept IPv6 connections (as it is not bound to an IPv6 addresses), but will still do outbound IPv6 connections.

To continue above sentence, **solution** is to use set parameter **only-notify=0.0.0.0/0**, so pdns don't even try to notify/resolve IPv6.

In my opinion, issue can be closed.

**Comment by tomsommer** [comment]
This is a great tip, perhaps to be added to the documentation?
