### ISSUE TITLE
Auth-master behind NAT tries to notify itself

### ISSUE THREAD

**Issue by tomsommer** [PowerDNS/pdns#5902]
An Auth-master behind NAT, tries to notify itself and fails

```
Nov  3 14:58:04 ns1 pdns_server: Nov 03 14:58:04 Queued notification of domain 'xxx.se' to xxx.xxx.xxx.xxx:53
Nov  3 14:58:04 ns1 pdns_server: Nov 03 14:58:04 Received NOTIFY for xxx.se from xxx.xxx.xxx.xxx but slave support is disabled in the configuration
Nov  3 14:58:05 ns1 pdns_server: Nov 03 14:58:05 Removed from notification list: 'xxx.se' to xxx.xxx.xxx.xxx:53 Not Implemented
```

**Comment by ahupowerdns** [comment]
We suggest not hosting an authoritative master behind NAT.

**Comment by tomsommer** [comment]
I suggest expanding the documentation for `prevent-self-notification` then

**Comment by pieterlexis** [comment]
a really stupid trick is to add the external ip to the `lo` interface and listen on that too, that will make PowerDNS consider it being 'self'

**Comment by mind04** [comment]
only-notify is your friend

**Comment by tomsommer** [comment]
Except with `only-notify` I have to maintain a list of possible slaves, but yes - that's a valid solution.
