### ISSUE TITLE
pdnsutil rectify-all-zones: Output missing details, line breaks

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#5903]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

In auth 4.1.0-rc2, the new `pdnsutil rectify-all-zones`'s output is missing the detailed information, and most of it is all on one line.

### Environment

 - Operating system: Ubuntu 16.04 (amd64)
 - Software version: 4.1.0-rc2
 - Software source: PowerDNS repository 

### Steps to reproduce

1. Run `pdnsutil rectify-all-zones` 

### Expected behaviour

4.1.0-rc1 did:

    $ sudo pdnsutil rectify-all-zones
    Oct 28 06:45:48 [bindbackend] Done parsing domains, 0 rejected, 2 new, 0 removed
    Rectifying example.com: Erasing NSEC3 ordering since we are narrow, only setting 'auth' fields
    Rectifying example.net: Erasing NSEC3 ordering since we are narrow, only setting 'auth' fields
    Rectified 2 zones.

### Actual behaviour

4.1.0-rc2 does:

    $ sudo pdnsutil rectify-all-zones
    Nov 03 15:12:45 [bindbackend] Done parsing domains, 0 rejected, 2 new, 0 removed
    Rectifying example.com: Rectifying example.net: Rectified 2 zones.

**Comment by rgacogne** [comment]
So 25b1ce1347e677e6c64dbf2312046883ecb8bc0b moved the rectify code into `DNSSECKeeper::rectifyZone()` and while it preserved the error messages in case of failure, those informative ones got lost. We probably should ad these back, writing them to a string so the caller may decided what should be done with it, like is done for the `error` one.
