### ISSUE TITLE
dead links in powerdns 3 auth legacy docs

### ISSUE THREAD

**Issue by setharnold** [PowerDNS/pdns#5906]
Hello, the legacy authoritative server documentation located at https://doc.powerdns.com/3/authoritative/#backends has links to more detailed documentation on specific backends; all 14 currently lead to 404 responses:

"bind": https://doc.powerdns.com/3/authoritative/backend-bind.md
"mysql": https://doc.powerdns.com/3/authoritative/backend-generic-mypgsql.md

etc

Thanks

**Comment by jannyg** [comment]
The version 3 doc source is not located on Github?

**Comment by zeha** [comment]
Links in this form work: https://doc.powerdns.com/3/authoritative/backend-bind/

**Comment by jannyg** [comment]
Yes, i figured that out, but not where the source is located to update the links.

**Comment by pieterlexis** [comment]
in the docs-3x branch
