### ISSUE TITLE
pdns-auth terminates when a TSIG key is not found

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#5931]
It seems PowerDNS-Auth 4.x added support for outgoing NOTIFYs with TSIG. Therefore, in mastercommunicator.cc CommunicatorClass::sendNotification() the TSIG key is fetched from DB. The problem happens when the domainmetadata TSIG-ALLOW-AXFR references a key, but this key is not in the tsigkeys' table. Because B.getTSIGKey() is used without checking the return value (like everywhere else in PowerDNS code). Hence, the unset DNSName tsigalgorithm will be used which throws a fatal exception.

With perfect provisioning this should not happen, but IMO PowerDNS should not terminate if there is a missing key in the DB, better log an error.

So please check the return value of B.getTSIGKey(), any maybe also of B64Decode(), as it is done in slavecommunicator.cc CommunicatorClass::suck().

**Comment by pieterlexis** [comment]
I can see some more un-checked `B64Decode` and `getTSIGKey` calls in the code as well.
