### ISSUE TITLE
Chrome, Webserver & API Key Issues

### ISSUE THREAD

**Issue by aerique** [PowerDNS/pdns#5942]
When starting up a Recursor with a webserver and API key there's some issues with Chrome not refreshing to the proper page.

Start a Recursor as follows `sudo ./pdns_recursor --webserver=yes --webserver-password=bla --webserver-port=8082 --local-port=5354 --quiet=no --api-key=abcde6c7637d6393b19f3def180a8f15`.

Now, with Chrome on Linux, when visiting http://localhost:8082/ one gets an authorization dialog and after logging in one needs to enter the API key and everything works.  However when visiting http://x:bla@localhost:8082/ one gets a different page and after entering the API key, nothing happens.

Also, when visiting http://localhost:8082/ with Chrome on Windows one is apparently **not** prompted!

Also, see @jpmens report in #5920.

**Comment by jpmens** [comment]
The API key requirement in the form means it's difficult to have a one-click URL to access Recursor's Web interface.

Why does Recursor need the API Key there at all? In this respect its behavior is quite inconsistent with _PowerDNS Authoritative_ and with _dnsdist_, both of which do not have this requirement in spite of providing an API.

**Comment by zeha** [comment]
dnsdist has a completely separate webserver implementation, and the code there allows access to the statistics API using the password instead of the API key.
Auth does not use the (statistics) API on its web interface.
