### ISSUE TITLE
instantiating `LuaContext::LuaObject data` looks expensive

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#5959]
- Program: Recursor
 - Issue type: Performance question

### Short description
In at least two places in the Recursor, we instantiate a `LuaObject` to hold user-specified data during query processing. While stepping through `doProcessUDPQuestion` in `lldb`, I got the impression that just the line `LuaContext::LuaObject data;` took measurable time, even if we go on to never do anything with the object.

The other instance is in `struct DNSComboWriter`.

@ahupowerdns suggested making it a `unique_ptr` perhaps. We should measure first though.

**Comment by rgacogne** [comment]
I expected it to be quite cheap based on the content of the object but if it isn't turning it into a `unique_ptr` looks like a good idea to avoid the cost when we don't have any `Lua` hook declared.

**Comment by omoerbeek** [comment]
Where would this cost be? In the `luaL_openlibs(mState)` call inside the `LuaContext` constructor? Is this a one-time cost or for every instantiation?

**Comment by Habbie** [comment]
`openlibs` should not end up being called as part of the `LuaObject` constructor, only in the `LuaContext` constructor which we don't call per question. I don't know where the cost is, though.

**Comment by Habbie** [comment]
It is possible, even, that `lldb` incurred some high cost on this instantiation, and it is not a runtime issue.

**Comment by omoerbeek** [comment]
Ah, mixed up `LuaContext::LuaObject` and  `LuaContext::LuaContext`. Looking at  `LuaContext::LuaObject` I don't see anything that could cost lots of CPU.

**Comment by Habbie** [comment]
@rgacogne felt the same. I did not measure.

**Comment by omoerbeek** [comment]
Likely not an issue. Please re-open if data shows otherwise.
