### ISSUE TITLE
Auth: Inbound notifies for non-auth domains always trigger outbound supermaster checks (slave=yes)

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#5977]
Version: pdns 4.1.0-rc3
Source: PowerDNS repo rpm; buildbot@f7eaa1ea7d5a
OS: Centos 6.9

Observed behavior:
When notifies are received on a slave-enabled server for a domain for which it's not authoritative for it seems to attempt to resolve the SOA serial and NS records via the IP address that sourced the notify even though the supermaster feature is not being used at all. In the best case this just generates a few useless log entries..

Expected behavior:
Some sort of global "off" switch for the supermaster feature; not doing anything at all for misguided notifies (besides logging); especially not connecting outbound?

Ref:
https://github.com/PowerDNS/pdns/blob/4e7fea16f8774e7d9b8abe84f8c70efc39877340/pdns/packethandler.cc#L819

**Comment by Habbie** [comment]
#6021 introduces a `supermaster` flag which will be in 4.2 (and could be backported to 4.1 if needed). #1953 introduces `allow-notify-from` in auth 4.0 and up. Closing this; please let me know if you need a backport of #6021 to 4.1!
