### ISSUE TITLE
AXFR problem - Pdns Authoritative server

### ISSUE THREAD

**Issue by mislav-eu** [PowerDNS/pdns#5983]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

AXFR in new Pdns Authoritative server is creating empty records (NULL) when transferring zones from another PDNS server or from bind zone.

### Environment

 - Operating system: Debian 9
 - Software version:  PowerDNS Authoritative Server 4.1.0-rc3
 - Software source: powerdns repository (http://repo.powerdns.com/debian stretch-auth-41 main) 

### Steps to reproduce

1.  Install Debian 9
2.  Follow instructions on how to add new pdns repository, install pdns (with mysql backend)
3.  Enter mysql, execute the following query:
https://doc.powerdns.com/authoritative/migration.html#using-axfr-to-a-slave-capable-backend
INSERT INTO domains (name,type,master) VALUES ('example.net', 'SLAVE', '198.51.100.101');
(change the example.net to your domain name and IP to your master IP)
4.  Wait a minute until AXFR is over. Check records table and you will see empty additional records.

### Expected behaviour

I would expect no additional records being added after AXFR, just like AXFR was working fine in previous pdns authoritative server.

### Actual behaviour

On AXFR, as explained, there are few additional empty records added, with type, content, etc - NULL. 

### Other information

I've tried to ask community, but specific answer there. One person mentioned this could be DNSSEC related? Is it? Or is it really a bug?  Here is the link to that topic:
https://mailman.powerdns.com/pipermail/pdns-users/2017-November/025055.html

as mentioned there, there is no difference if I do AXFR from old 3.1. pdns server version or if master is bind-alike, same thing occurs.

If some addition logs are needed, let me know.

**Comment by ahupowerdns** [comment]
are you experiencing problems from the NULL entries? They are related to Empty Non Terminals, a DNS oddity. We have to have them.

**Comment by mislav-eu** [comment]
Can you give some short description what are those exactly, because I can't find much on google. Currently there are no problems, but maybe in the future there will be? Thoughts? I have master with e.g. 20 records and then slave 22 records. If then slave becomes master in the future, I would need to test how these empty records are transferred to the new slave/master.

**Comment by ahupowerdns** [comment]
https://doc.powerdns.com/md/authoritative/backend-generic-sql/ has a description. https://github.com/PowerDNS/pdns/issues/127 has some context. In general, you might want to trust that we know what we are doing. The NULLs are there so we can comply with the RFCs.

**Comment by pieterlexis** [comment]
Hi @mislav-eu I think you need to read [the second to last paragraph here](https://doc.powerdns.com/authoritative/backends/generic-sql.html#generic-sql-handling-dnssec-signed-zones). This explains what you are seeing.

**Comment by mislav-eu** [comment]
@ahupowerdns @pieterlexis I apologize, but I didn't have any bad intentions here. I was only looking for some answer/details why is this exactly. I do trust you, that's why I use your program/solution, however I need to give some answer to my superiors. I wouldn't open here new report if I received there this answer. This paragraph gives all the answers I was looking for and I understand now. Thank you very much!
