### ISSUE TITLE
Conceptional Bug with TSIG-signed NOTIFYs

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#5987]
Hi!

Since 4.0 PowerDNS supports signed NOTIFYs. This feature is always-on and uses the TSIG-ALLOW-AXFR domainmetadata. With PDNS < 4.0 TSIG-ALLOW-AXFR was only used to authorize incoming XFR requests and allows mutliple keys. Hence, when using mutliple slaves each slave could use its own TSIG key.

Currently, the signed NOTIFYs always use the first returned TSIG-ALLOW-AXFR key. Hence, every slave receives the same NOTIFY with the same TSIG key. Depending on the slave setup the NOTIFY will be ignored/refused as it uses the wrong TSIG key.

We currently do have issues due to this new feature and had to remove the TSIG signature from NOTIFYs - slaves like unsigned NOTIFYs more than signed NOTIFYs with unknown key.

Hence, if you want to support signed NOTIFYs in a proper way, it would be necessary to have the TSIG key not only per domain, but per domain+slaveIP. And add an option to enable/disable signed NOTIFYs.

**Comment by klaus3000** [comment]
As this is not easy to solve, I suggest to add an option to disable signed NOTIFYs.

send-signed-notify = yes (default)
When sending NOTIFYs to slaves, PowerDNS by default tries to send them with TSIG signed. It uses the first found TSIG-ALLOW-AXFR metadata of the respective domain. In setups with multiple slaves with different TSIG keys this may cause problems as always the first TSIG-ALLOW-AXFR key is used. In such cases it may be better to set send-signed-notify = no.

What do you think? I can provide a patch if this is accepted as solution.

**Comment by Habbie** [comment]
Fixed in #6825
