### ISSUE TITLE
rec: add a periodic maintenance callback to Lua

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#5991]
- Program: Recursor
 - Issue type: Feature request 

### Short description

It would be helpful if the Recursor could call a maintenance function in Lua once per second, if that one is defined.

### Usecase

Currently doing periodic maintenance -- like flushing metrics, or checking a database for changes --
 in a Lua script requires checking on every request if the current time has changed.

This is cumbersome and does not guarantee that it will be actually run every second. For example, if you have a period with no requests, the maintenance function is never run.

### Description

I suggest adding a `maintenance()` callback function to the Lua API that would be called every second. 

Example usage:

```lua
local foo_metric = getMetric("foo")
local foo_count = 0

function maintenance()
    -- This would be called every second
    foo_metric:incBy(foo_count)
    foo_count = 0
    -- Other maintenance ...
end
```

Implementation notes:

* This does not need to offer guarantees that it will be called exactly every second.
* It should be called even if no requests are being handled.
* The maintenance function expects no arguments and returns no values.
* This would need to be called for every Lua state (Recursor OS thread).
* If a script requires less frequent maintenance, the Lua function can check every second if it is time to do maintenance. No need to make this more complicated by making the interval configurable.
* Maybe this needs to be explicitly enabled with an option?

**Comment by Habbie** [comment]
> Maybe this needs to be explicitly enabled with an option?

Recursor, on loading the Lua script, already does a one time lookup of the available functions and keeps a reference to them - so there is no need for an option.
