### ISSUE TITLE
API responds wrong to long requests

### ISSUE THREAD

**Issue by ghost** [PowerDNS/pdns#5992]
> "It takes an awful amount of bytes to create a long request"
> -- Nobody, probably

 - Program: Authoritative
 - Issue type: Bug report

### Short description
When providing a really huge API request to the `zones` endpoint, the API returns an error 400 with the message `Bad Request`.
While the limit should be removed or documented if required for technical reasons, the log message doesn't really help troubleshooting this problem.

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: pdns-authoritative 4.1.0-rc3
 - Software source: PowerDNS repository

### Steps to reproduce
1. Set loglevel to something high (like 9) and enable the API
1. Create a zone "example.com" with valid SOA and NS records
1. Create a huge JSON file to upload: `echo '{ "rrsets": [' > test.json; for l in {a..z}{a..z}{a..z}; do echo "{\"name\":\"$l.example.com.\",\"type\":\"A\",\"records\":[{\"content\":\"1.2.3.4\",\"disabled\":false}],\"ttl\":3600,\"changetype\":\"REPLACE\"}," >> test.json; done; truncate -s-2 test.json; echo ']}' >> test.json`
1. Upload the file: `curl -X PATCH --data @test.json -H "X-API-Key: secretsecretkey" -v http://localhost:8001/api/v1/servers/localhost/zones/example.com.`

### Expected behaviour
I'd expect pdns to accept the data, even though the request is really big.
If it's too big for pdns to handle, I'd expect it to return a HTTP 413 `Payload Too Large`.
I'd also expect pdns to log that it received a request that was too long.

### Actual behaviour
pdns returned a 400 `Bad request` and logged:
```
Nov 25 18:06:27 dns01 pdns_server[20906]: HTTP: Incomplete request
Nov 25 18:06:27 dns01 pdns_server[20906]: HTTP: Error result for "/api/v1/servers/localhost/zones/example.com.": 400
```

### Other information
It looks like the issue is caused by `YAHTTP_MAX_REQUEST_SIZE` which isn't big enough. This means that yahttp/pdns is not able to process requests bigger than that, so pdns should return the proper return code and log message.

**Comment by mind04** [comment]
related #1469

**Comment by Habbie** [comment]
From #1469: try chunked encoding please.

**Comment by Habbie** [comment]
Did chunked encoding help?

**Comment by Habbie** [comment]
ping

**Comment by Habbie** [comment]
Closing this because nobody else has reported this and there has been no response.
