### ISSUE TITLE
`test-syncres_cc.cc` spurious TTL mismatch

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#6036]
- Program: Recursor
 - Issue type: Bug report

### Short description
Travis build 11575.6 failed with:
```
test-syncres_cc.cc(2069): error in "test_cache_min_max_ttl": check (cached[0].d_ttl - now) == SyncRes::s_minimumTTL failed [61 != 60]
test-syncres_cc.cc(2075): error in "test_cache_min_max_ttl": check (cached[0].d_ttl - now) <= SyncRes::s_maxcachettl failed [3601 > 3600]
```

Builds before it are fine and the associated gcc build also passed.

### Environment
Travis

### Steps to reproduce
1. push commits onto master until this randomly happens

### Expected behaviour
Green Travis.

### Actual behaviour
Red Travis.

### Other information
https://travis-ci.org/PowerDNS/pdns/builds/310086306
Copy of build log at https://gist.github.com/Habbie/77e9057c82158e7491db10b8e054cea3

**Comment by rgacogne** [comment]
Fixed by https://github.com/PowerDNS/pdns/pull/6086.
