### ISSUE TITLE
better error reporting when parsing an address fails

### ISSUE THREAD

**Issue by publicarray** [PowerDNS/pdns#6039]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

When binding an IPv6 address with dnscrypt, dnsdist prints `Fatal Lua error: Unable to convert parameter from userdata to Ss`

Example:
```
addDNSCryptBind("2001:19f0:5801:876:5400:ff:fe6f:3bf:443", "2.dnscrypt-cert.dns.seby.io", "/etc/dnsdist/resolver.cert.0", "/etc/dnsdist/resolver.key.0")
```

### Environment

 - Operating system: CentOS 7.4.1708
 - Software version: dnsdist 1.2.0 (Lua 5.1.4 [LuaJIT 2.0.4]) - Enabled features: dnscrypt libsodium protobuf re2 systemd
 - Software source: PowerDNS repository

### Steps to reproduce

Config files 
**Edit removed files**

### Expected behaviour

Accepting IPv6 traffic on the specified address/port

### Actual behaviour

`Fatal Lua error: Unable to convert parameter from userdata to Ss`

**Comment by Habbie** [comment]
> `addDNSCryptBind("2001:19f0:5801:876:5400:ff:fe6f:3bf:443", "2.dnscrypt-cert.dns.seby.io", "/etc/dnsdist/resolver.cert.0", "/etc/dnsdist/resolver.key.0")`

Can you try passing the address as `"[2001:19f0:5801:876:5400:ff:fe6f:3bf]:443"`?

**Comment by publicarray** [comment]
Thanks yes that did it. I thought I tried that before but maybe without the quotes. 

I guess this is now a feature request to have either better error reporting or support for IPv6 addresses as strings without the `[ ]`.

**Comment by Habbie** [comment]
Yes, the reporting should be better. Supporting IPv6 addresses with ports, without [], is absolutely not feasible.

**Comment by publicarray** [comment]
Agreed, Yea maybe not, but I like this syntax: `0:0:0:0:0:0:0:0@443` I suppose it's a bit late to change it now.

**Comment by rgacogne** [comment]
I'm afraid so, especially since in other places like `newServer()`'s `source` parameter, the `@` is used to indicate the interface to use: 
```
192.0.2.1@eth0
```

**Comment by pieterlexis** [comment]
The bracketed IPv6 address + port is also the default to be used according to [RFC 5952 §6](https://tools.ietf.org/html/rfc5952#section-6)

**Comment by Habbie** [comment]
While looking into this, dnsdist 1.2.0 from the upcoming macos brew formula:
```
> newServer('2001:19f0:5801:876:5400:ff:fe6f:3bf:443')
Error creating new server with address 0x7fff5f4bbab0: Unable to convert presentation address '2001:19f0:5801:876:5400:ff:fe6f:3bf:443'
Segmentation fault: 11
```

**Comment by Habbie** [comment]
> While looking into this, dnsdist 1.2.0 from the upcoming macos brew formula:

This one was fixed in 6d54c50c707b733b82ffd773a3619240f97687de

**Comment by publicarray** [comment]
@pieterlexis Thanks for the RFC! There is no way around it I will need remember the syntax. Personally I think `2001:db8::1#80` is better option than `[2001:db8::1]:80`, but that's only a minor inconvenience.

**Comment by rgacogne** [comment]
Seems that everything has been fixed except for the error reporting part which is tracked in #6359.
