### ISSUE TITLE
auth-4.1.0 removing utility.hh leaves timeval unspecified

### ISSUE THREAD

**Issue by tcely** [PowerDNS/pdns#6040]
- Program: Authoritative, dnsdist
 - Issue type: Bug report
### Short description

In da2869bb7a76e96e47054054c650de0eed0d0602 utility.hh was removed from mplexer.hh, pollmplexer.cc, and selectmplexer.cc which causes compilation problems.

### Environment

 - Operating system: Alpine
 - Software version: 4.1.0
 - Software source: compiled from release archive

### Build log
https://hub.docker.com/r/tcely/powerdns/builds/b56akwj9dsw62nudk2xq74r/

**Comment by Habbie** [comment]
selectmplexer.cc includes misc.hh which includes sys/time.h, what am I missing?

**Comment by Habbie** [comment]
Ah, it's the removal from mplexer.hh that causes the trouble for selectmplexer

**Comment by Habbie** [comment]
I tested #6041 with your Dockerfile, it works!

**Comment by tcely** [comment]
Thanks for the quick work on this!
