### ISSUE TITLE
Feature request: Ability to disable recursor caching for specific zones

### ISSUE THREAD

**Issue by qxrftz** [PowerDNS/pdns#6044]
- Program: Recursor
- Issue type: Feature request

### Short description
Some features of authoritative server, such as weight, geoip services are unavailable when the server behind with a recursor, because the recursor cached all records at first time always.

### Usecase
authoritative server(geoip backend) + recursor

### Description
If I can disable recursor caching for specific zones, then the features I mentioned will be available for these zones.

**Comment by cmouse** [comment]
Why not just drop the TTL in geoip backend to something like 5s?

**Comment by qxrftz** [comment]
Your suggestion may be useful to deal with the weight issue, but cannot fix the geoip services issue.

**Comment by cmouse** [comment]
Maybe you could provide some concrete example of the problem you are trying to solve?

**Comment by qxrftz** [comment]
yeah, here are my requirements:
- response different records to client based on request source ip
- response different records to client based on request times
- forward specific zones to internal authoritative server and the deafult to internet dns servers

**Comment by cmouse** [comment]
Ok, so what was the problem that prevented you from fulfilling these requirements?

**Comment by qxrftz** [comment]
We use recursor to forward client request, and use the authoritative server to response internal records. 
This can satisfy my third requirement, but the others cannot be meet, because the recursor cache all records at first request always, on other words, it response different records to client based on request sequence.

**Comment by Habbie** [comment]
How about enabling edns-client-subnet then?

**Comment by qxrftz** [comment]
you means it can fulfilling my requirements? if so, I'll try it.

**Comment by qxrftz** [comment]
I tried it, but not work, any wrong in my config?

- pdns.conf
edns-subnet-processing=yes

- recursor.conf 
edns-subnet-whitelist=172.16.0.0/12
use-incoming-edns-subnet=yes

./dig passport.oa.com @x.x.x.x +client=172.25.10.200

**Comment by Habbie** [comment]
The issue tracker is not for support discussions. Please ask your question on the mailing list or on IRC. See https://www.powerdns.com/opensource.html for more information.

**Comment by qxrftz** [comment]
If edns-client-subnet can fulfilling my requirements, but so many dns client does not support edns, so disabling recursor caching for specific zones is a better way.

**Comment by rgacogne** [comment]
Your clients do not need to support EDNS Client Subnet for your use case, but please use IRC or the mailing list, we will ignore any further comment on this issue.
