### ISSUE TITLE
Unit tests fail when building on a 32-bit Linux

### ISSUE THREAD

**Issue by dteleguin** [PowerDNS/pdns#6050]
- Program: Recursor
 - Issue type: Bug report

### Short description
Unit tests fail when building rec-4.1.0 on a 32-bit Linux (however everything is OK on x86_64).

Earlier versions (4.0.6, 4.0.7) are not affected.

### Environment

 - Operating system: Mageia Linux 6 (i586)
 - Software version: rec-4.1.0
 - Software source: repository package updated to 4.1.0

### Steps to reproduce
build it

### Expected behaviour
successful build

### Actual behaviour
```
Checking bad value for record type SOA test #1
test-negcache_cc.cc(388): error: in "negcache_cc/test_dumpToFile": check line == str has failed [www1.powerdns.com. 600 IN RRSIG NSEC 5 3 600 19631125173144 19631125173144 24567 dummy. data ;
 != www1.powerdns.com. 600 IN RRSIG NSEC 5 3 600 21000101000000 21000101000000 24567 dummy. data ;
]
test-negcache_cc.cc(388): error: in "negcache_cc/test_dumpToFile": check line == str has failed [www2.powerdns.com. 600 IN RRSIG NSEC 5 3 600 19631125173144 19631125173144 24567 dummy. data ;
 != www2.powerdns.com. 600 IN RRSIG NSEC 5 3 600 21000101000000 21000101000000 24567 dummy. data ;
]

*** 2 failures are detected in the test module "unit"
```

### Other information
[test-suite.log](https://pastebin.com/nX5v8VNT)

Most likely has something to do with #6005

**Comment by zeha** [comment]
Can confirm:

https://buildd.debian.org/status/fetch.php?pkg=pdns-recursor&arch=armhf&ver=4.1.0-1&stamp=1512449618&raw=0
https://buildd.debian.org/status/fetch.php?pkg=pdns-recursor&arch=i386&ver=4.1.0-1&stamp=1512445103&raw=0

**Comment by rgacogne** [comment]
The values used for the `Signature Expiration` and `Signature Inception` fields look a lot more larger than the `32-bit unsigned number of seconds elapsed since 1 January 1970 00:00:00 UTC` they are allowed to represent. We have the same values in `test-syncres_cc.cc` with a comment stating: 
> /* the NSEC and RRSIG contents are complete garbage, please ignore them */

We should probably just update these to sensible values.
