### ISSUE TITLE
-O3 always shows up on g++ invocation / inconsistent use of AM_CPPFLAGS/CXXFLAGS

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#6054]
Recursor has `AM_CPPFLAGS=...-O3...` in Makefile.am, which makes for confusing g++ invocations like this one:

```
g++ -DHAVE_CONFIG_H -I.  -I/usr/include/lua5.2 -I./ext/yahttp -pthread     -O3 -Wall -pthread -DSYSCONFDIR=\"/etc/powerdns\"  -I./ext/json11 -I./ext/rapidjson/include -I./ext/yahttp  -I/usr/include/lua5.2 -Wdate-time -D_FORTIFY_SOURCE=2  -pthread -DSYSCONFDIR=\"/etc/powerdns\" -DPKGLIBDIR=\"/usr/lib/mipsel-linux-gnu/pdns-recursor\" -DLOCALSTATEDIR=\"/var/run\" -fPIE -DPIE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -ggdb -O0 -fdebug-prefix-map=/home/zeha/pdns-recursor-4.1.0=. -fstack-protector-strong -Wformat -Werror=format-security -c -o test-dnsname_cc.o test-dnsname_cc.cc
```

dnsdist apparently has `AM_CPPFLAGS=...-O3-...` in configure.ac.

Auth has this in configure.ac, which I think is a lot nicer:

```
: ${CFLAGS="-Wall -g -O2"}
: ${CXXFLAGS="-Wall -g -O2"}
```

Recursor has that too, conflicting with AM_CPPFLAGS ...

**Comment by zeha** [comment]
While having a look at dnsdist 1.4.0-alpha2, I noticed that it now always passes these flags: `-g -O3 -g -O2 `

Looking at the prebuilt `configure` script, it appears to indeed add both. -O3 by the explicit `C(XX)FLAGS` in `configure.ac`, and -O2 by the GCC/GXX detection.

**Comment by pieterlexis** [comment]
I believe this is no longer an issue
