### ISSUE TITLE
Wrap zone PATCH in transaction

### ISSUE THREAD

**Issue by autodiscover** [PowerDNS/pdns#6066]
- Program: Authoritative
 - Issue type: Bug report

### Short description

When writing to the database in the context of PATCHing a zone with multiple RRsets in the `rrsets` JSON payload, an error may occur for a some, but not all of the RRsets. In this case, only some of the RRsets are saved, without a way for the user to determine which ones have been written.

The solution is to make sure that either all or none of the RRsets are saved, by wrapping everything in a transaction, return a corresponding status code.

### Environment

 - Software version: 4.1

### Steps to reproduce
This report is based on an IRC conversation where pdns devs looked at the SQL backend source code. No experiments have been done.

**Comment by pieterlexis** [comment]
note: this should be done in gsqlbackend.cc

**Comment by pieterlexis** [comment]
ref:  #6053

**Comment by peterthomassen** [comment]
https://github.com/PowerDNS/pdns/blob/8f4eca4ac84c3c6fbdaa30485b37baaac092b4cf/pdns/ws-auth.cc#L1600 actually seems to be the transaction in question, so never mind.

I'm leaving this open in case you want to move this to gsqlbackend.cc. I'm not sure how you want to do it, though, since `replaceRRset` only deals with one RRset at a time.

**Comment by ekohl** [comment]
Looks related to https://github.com/PowerDNS/pdns/issues/5967

**Comment by autodiscover** [comment]
From IRC:

> (04:43:39 PM) pt01: [...] "With this PR, most operations are correctly wrapped in transactions" -- which are not?
> (04:43:55 PM) Habbie: tsig key management
> (04:44:09 PM) Habbie: metadata management might also be outside of the rest of the operations

That should solve the problem that I reported initially. Thanks for picking it up!
