### ISSUE TITLE
API /servers/{server_id}/zones/{zone_id}/check always returns "Could not find domain"

### ISSUE THREAD

**Issue by dkoster** [PowerDNS/pdns#6071]
- Program: Authoritative
 - Issue type: Bug report

### Short description
After using: 
$ curl -X GET -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/phlex.net.
I wanted to verify the zone through the API using the check option:
[root@dnstest ~]# curl -v -X GET -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/phlex.net./check
{"error": "Could not find domain 'phlex.net./check.'"}[root@dnstest ~]#

### Environment
 - Operating system: CentOS 6 64bit (fully patched)
 - Software version: powerdns auth 4.1.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. 
[root@dnstest ~]# curl -v -X GET -H 'X-API-Key: changeme' http://127.0.0.1:8081/api/v1/servers/localhost/zones/phlex.net./check
* About to connect() to 127.0.0.1 port 8081 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /api/v1/servers/localhost/zones/phlex.net./check HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:8081
> Accept: */*
> X-API-Key: changeme
>
< HTTP/1.1 422 Unprocessable Entity
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 54
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< Server: PowerDNS/4.1.0
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
* Closing connection #0
{"error": "Could not find domain 'phlex.net./check.'"}
[root@dnstest ~]#

2. The request without /check returns the zone

### Expected behaviour
Not yet known, option should verify the zone.

### Actual behaviour
Returns "Could not find domain"

### Other information
Option is found in the documentation:
https://doc.powerdns.com/authoritative/http-api/zone.html

GET /servers/{server_id}/zones/{zone_id}/check
Verify zone contents/configuration.

**Comment by zeha** [comment]
Closing in favor of #6865.
