### ISSUE TITLE
Enabling LDAP backend needs Kerberos headers

### ISSUE THREAD

**Issue by paultheweird** [PowerDNS/pdns#6075]
- Program: Authoritative
 - Issue type: Bug report

### Short description

While configuring PowerDNS on OpenBSD, we see:
```
checking for krb5.h... no
configure: error: Kerberos header (krb5.h) not found
```
This apparently is caused by enabling the LDAP backend. The OpenBSD port of PowerDNS has had this backend enabled for quite some time, its dependency on kerberos is new.

Could that be made optional?

### Environment

 - Operating system: OpenBSD -current (although I've heard a rumor macOS is also affected)
 - Software version: 4.1.0
 - Software source: https://downloads.powerdns.com/releases/pdns-4.1.0.tar.bz2

### Steps to reproduce

1. `./configure  --disable-shared --with-modules=bind --with-sqlite3 --with-dynmodules=ldap gsqlite3 gmysql gpgsql --without-lua --disable-hardening --without-protobuf --enable-tools --with-mysql=/usr/local --with-pgsql=/usr/local --with-pgsql-includes=/usr/local/include/postgresql --prefix=/usr/local --sysconfdir=/etc/pdns --mandir=/usr/local/man --infodir=/usr/local/info --localstatedir=/var --disable-silent-rules --disable-gtk-doc`
2. ...
3. profit!

(note that adding `--without-ldap` and removing ldap from `--with-dynmodules=` allows `./configure` to run to completion)

### Expected behaviour

`./configure` runs to completion without error and produces a make-able tree.

### Actual behaviour

`./configure` errors out because Kerberos headers are not present on OpenBSD

**Comment by Habbie** [comment]
For related reasons, the LDAP backend also does not build on macOS.

**Comment by omoerbeek** [comment]
Installing heimdal-libs and configuring with CPPFLAGS+=-I/usr/local/heimdal/include make the port compile. I prepare a proper port on OpenBSD. @paultheweird I'll send it separately to you, hope you're still interested.

@Habbie I suspect the kerberos on MacOS is also not installed in /usr/local but somehwere else (if at all).

**Comment by Habbie** [comment]
MacOS ships a very old and broken kerberos, I can install heimdal in /usr/local and should probably try that :)

**Comment by Habbie** [comment]
> MacOS ships a very old and broken kerberos, I can install heimdal in /usr/local and should probably try that :)

`'CPPFLAGS=-I/usr/local/opt/heimdal/include' 'LDAP_LIBS=-L/usr/local/opt/heimdal/libs'` does the trick there.

**Comment by omoerbeek** [comment]
Yep to make it runtime loadable the LDA_LIBS is also needed. I submitted a port diff, will close this once it's committed to OpenBSD.

**Comment by omoerbeek** [comment]
OpenBSD -current now has the ldap dyn backend.
