### ISSUE TITLE
Adding command to pdns_control

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#608]
Add the following commands to pdns_control:

1) pdns_control list_zone --type $type, where $type can be all (default), master or slave; this command return all zones managed by pdns of type $type

2) pdns_control delete $zone; this command will remove a zone (and all related records) from the backend

These commands can be used to create scripts for zone managing, for example for removing zone from superslaves

**Comment by HOSTED-POWER** [comment]
Any sample scripts available? Comment here **(https://github.com/PowerDNS/pdns/issues/467)** says they should, but don't see them at first sight

**Comment by Habbie** [comment]
Please ask support questions on IRC or the mailing list: https://www.powerdns.com/opensource.html
