### ISSUE TITLE
PowerDNS fails on incoming AXFR if zone contains CAA

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#6089]
The problem can be reproduced with PowerDNS 4.0.3 and 4.1.0.

When transferring a big zone the incoming AXFR fails with:
`Unable to parse record during incoming AXFR of 'myzone.org' (MOADNSException): Error parsing packet of 47208 bytes (rd=0), out of bounds: vector::_M_range_check
`
Adding some debug log messages revealed that the exception is always thrown on CAA RRs.

The problem is related to the number of ressource records in a DNS message. When using Bind9.10 as master the above problem arises. When configuring Bind with `transfer-format one-answer` (every RR is wrapped into a single DNS message) it works. It also works when removing the CAA support (type 257) from PowerDNS. Hence, it only happens for CAA records when there are lots of RRs in a single DNS message.

You can reproduce the problem easily: Just transfer the zone `myzone.org` from 83.136.32.171. PowerDNS will throw an exception while `dig @83.136.32.171 myzone.org axfr` works.

**Comment by klaus3000** [comment]
Is there something we can help to address this issue. E.g. some ideas where we should look at? This is hopefully the last showstopper for us before upgrading to 4.x as we host den debian.org zone and they have a quite big zone with plenty of CAAs.

**Comment by Habbie** [comment]
I have figured out why this is. Patch is coming!

**Comment by klaus3000** [comment]
Thanks for the fast patch! I tested the patch and transfering the zone does work now. Thanks, I hope there is no regression ;-)

**Comment by Habbie** [comment]
No problem, thank you for the quick testing. We had an internal review and cannot imagine a regression :)
