### ISSUE TITLE
dnsdist packet cache is not working if all ECS enabled backend servers are down

### ISSUE THREAD

**Issue by M4t7e** [PowerDNS/pdns#6098]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

I wanted to try the setStaleCacheEntriesTTL parameter and found a problem with the packet cache in dnsdist for ECS enabled backend servers. Also for valid and non stale entries, the caching behaves not as expected and is not working if all backend servers are down.

### Environment

 - Operating system: SUSE Linux Enterprise Server 12 SP2  (x86_64)
 - Software version: dnsdist 1.2.0

### Steps to reproduce

1. Configure dnsdist like in the following example configuration:
```
setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)

newServer({address="127.0.0.1", pool={"test"}, useClientSubnet=true})

pc_test = newPacketCache(100000, 86400, 0, 60, 60, true)
getPool("test"):setCache(pc_test)

setStaleCacheEntriesTTL(86400)
addAction(AllRule(), PoolAction("test"))
```
2. Query dnsdist for a DNS record to fill the packet cache and shutdown the backend server.
3. Query dnsdist again for the same record and this will lead to a cache miss.

### Expected behaviour

dnsdist should respond from the packet cache if all backend servers (with "useClientSubnet=true" set) are down. Also the setStaleCacheEntriesTTL should work for that.

### Actual behaviour

If all backend servers (with "useClientSubnet=true" set) are down, dnsdist can't respond directly from the packet cache. It leads to a high rate of cache misses. If "useClientSubnet" is set to "false", it is working.

### Usecase

If all backend servers are down, dnsdist should respond from the packet cache as an emergency mechanism. --> Better to answer with stale entries than not to answer and the service behind is down.

### Description

When using "useClientSubnet=true" for backend servers, the dnsdist packet cache is working. As far as I know by hashing the whole query including the ECS. But if all backend servers are down, dnsdist can't respond from the cache. I assume it's because the ECS is not honored for the query hashing anymore. I can see 100% cache misses in this scenario.

**Comment by rgacogne** [comment]
Are you sending the queries in 2/ and 3/ from the exact same host? I'm asking because when `ECS` is enabled, the packet cache will not reply with the same answer for different `ECS` values since it can't know whether the server used that information to generate the answer.

**Comment by M4t7e** [comment]
Yes, I'm sending the queries from the exact same host with the same source IP. Btw, if I already add the ECS in the query it is working. Just if dnsdist has to add it for the backend servers it is not working. I assume it's because the useClientSubnet parameter belongs to the "newServer" configuration and if there is no backend server available, the cache lookup is done without adding the ECS information.

**Comment by rgacogne** [comment]
Ah, you are right, we only add the `ECS` information if the backend needs it, so if there is no backend the cache lookup will be done without it. I'm not sure how we should handle that case, perhaps by adding an option to specify whether the `ECS` information should be added if we have no backend?

**Comment by M4t7e** [comment]
> I'm not sure how we should handle that case, perhaps by adding an option to specify whether the ECS information should be added if we have no backend?

This could be a good solution. I think that option then belongs to the packet cache?

**Comment by M4t7e** [comment]
@rgacogne: I tested the new feature from #6400 in dnsdist 1.3 and it's working like a charm!
Many thanks for that :smiley:

**Comment by rgacogne** [comment]
Cool, many thanks for the feedback!
