### ISSUE TITLE
Pidfile reused when running multiple Recursor instances

### ISSUE THREAD

**Issue by Cybertinus** [PowerDNS/pdns#6109]
- Program: Recursor
 - Issue type: Bug report

### Short description

When running multiple instances of the recursor on the same machine, the same pid filename is reused (/var/run/pdns_recursor.pid by default). This has the effect that the instance your started last can be found via the pidfile, but not the other ones.

### Environment

 - Operating system: Debian 9.3
 - Software version: Recursor 4.1.0
 - Software source: PowerDNS repository

### Steps to reproduce

1. Have a server with 2 IP addresses
2. Move the recursor.conf to a subdirectory of the normal config directory: mkdir /etc/powerdns/first && mv /etc/powerdns/recursor.conf /etc/powerdns/first/recursor.conf
3. Configure the recursor to bind to the first ip address via configuring the 'local-address' option in /etc/powerdns/first/recursor.conf
4. Copy the configuration to a second directory: cp -a /etc/powerdns/first /etc/powerdns/second
5. Configure the second configuration to use the second ip address by updating the 'local-address' option
6. Start the first Recursor: /usr/sbin/pdns_recursor --config-dir=/etc/powerdns/first/ &
7. Start the second Recursor: /usr/bin/pdns_recursor --config-dir=/etc/powerdns/second/ &
8. Check the pid in /var/run/pdns_recursor.pid and see that this is the pid of the second Recursor and the pid of the first Recursor can't be found anywhere.

### Expected behaviour
I would expect a pidfile per instance.

### Actual behaviour
One pidfile for all instances, containing the pid of the Recursor started last.

**Comment by pieterlexis** [comment]
Hi,

a different pid file can be done in 2 ways:

1. set [`socket-dir`](https://doc.powerdns.com/recursor/settings.html#socket-dir) to something else than `/var/run` in `/etc/powerdns/second/recursor.conf`
2. use [`config-name`](https://doc.powerdns.com/recursor/settings.html#config-name), which is meant for this.
