### ISSUE TITLE
notify-host add :0 port to IP and fails

### ISSUE THREAD

**Issue by evgeniymx** [PowerDNS/pdns#6116]
### Short description
PDNS fail retry for notify host when I'm using the following command:
pdns_contrl notify-host somedomain.com 1.2.3.4

returns to log:

pdns_server: Dec 23 14:38:32 Notification for somedomain.com to 1.2.3.4:0 failed after retries

### Environment
OS: Centos 7
Pdns: 4.0.5
Backend: mysql

### Steps to reproduce
pdns_control notify-host **domain** **ip**

### Expected behaviour
Host 1.2.3.4 recieve notification (but nothing)

### Actual behaviour
pdns_server: Dec 23 14:38:32 Notification for somedomain.com to 1.2.3.4:0 failed after retries

**Comment by Habbie** [comment]
The syntax does not ask for an @ before the IP, but I'm unsure that is your issue. Can you please post completely unedited input and output?

**Comment by evgeniymx** [comment]
Sorry, its mistake, I'm dont use @ before the IP

**Comment by Habbie** [comment]
Your input and output is still heavily edited. Please read https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/

**Comment by evgeniymx** [comment]
I do not quite understand what the problem is

**Comment by Habbie** [comment]
The problem is that we can only help if you show us what you actually typed, what actually happened then, and what actually appeared in your logs.

**Comment by evgeniymx** [comment]
Im type the command:

pdns_contrl notify-host somedomain.com 1.2.3.4

and have this result:

pdns_server: Dec 23 14:38:32 Notification for somedomain.com to 1.2.3.4:0 failed after retries

**Comment by Habbie** [comment]
Last attempt: please copy/paste from your terminal to this ticket. Do not re-type things, do not change things.

**Comment by evgeniymx** [comment]
[root@dns-hosting pdns]# pdns_control version
4.0.5

[root@dns-hosting pdns]# pdns_control notify-host spbxx.com 51.254.218.xx
Added to queue

[root@dns-hosting pdns]# tail -n 50 /var/log/messages | grep spbxx.com
Dec 23 16:18:30 dns-hosting pdns_server: Dec 23 16:18:30 Notification for spbxx.com to 51.254.218.xx:0 failed after retries

[root@dns-hosting ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)


done?

**Comment by Habbie** [comment]
I don't know how to clarify 'unedited' any more than I already did.
