### ISSUE TITLE
Compiling without lua broken

### ISSUE THREAD

**Issue by stbuehler** [PowerDNS/pdns#6123]
- Program: Authoritative
 - Issue type: Bug report

### Short description

```
./configure --with-modules="" --without-lua --enable-unit-tests
make -j8
```

leads to:

```
lua-auth4.o:(.data.rel.ro._ZTV8AuthLua4[_ZTV8AuthLua4]+0x20): undefined reference to `AuthLua4::postPrepareContext()'
lua-auth4.o:(.data.rel.ro._ZTV8AuthLua4[_ZTV8AuthLua4]+0x28): undefined reference to `AuthLua4::postLoad()'
```

### Description

The vtable for AuthLua4 misses the promised `virtual` `override` functions from the header if lua is disabled:
```
  virtual void postPrepareContext() override;
  virtual void postLoad() override;
```

**Comment by Elctro** [comment]
@cmouse

**Comment by Habbie** [comment]
I was about to merge this but now @Elctro has posted this comment - what am I missing? :)

**Comment by Elctro** [comment]
Thanks for a quick fix!
