### ISSUE TITLE
pdnsutil opens urandom too late

### ISSUE THREAD

**Issue by schuppentier** [PowerDNS/pdns#6125]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using chroot, pdns tries to open /dev/urandom **after** chrooting and cannot find it.

### Environment
 - Operating system: Debian 8 jessie
 - Software version: Authoritative server 4.1.0
 - Software source: PowerDNS repository

### Steps to reproduce
0. Configure a chroot like `chroot=/var/empty`
0. Run `pdnsutil list-all-zones`
0. It dies with "Aborted"

### Expected behaviour
I would expect dnssec to be disabled

### Actual behaviour
It crashes:
```
$ pdnsutil list-all-zones
Dec 29 02:47:36 Reading random entropy from '/dev/urandom'
Aborted
$ echo $?
134
```

### Other information
I straced the problem and got this at the end (note urandom and random not being found):
```
chroot("/var/empty")                    = 0
chdir("/")                              = 0
open("/dev/urandom", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/dev/random", O_RDONLY)           = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
tgkill(22777, 22777, SIGABRT)           = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=22777, si_uid=0} ---
+++ killed by SIGABRT +++
```

**Comment by rgacogne** [comment]
Our own `seedRandom()` is called before the call to `chroot()`, but we only call `sodium_init()` and `openssl_seed()` after that, so this might explain this issue.
