### ISSUE TITLE
rec: Bogus for a (secure) CNAME to an insecure  zone cut

### ISSUE THREAD

**Issue by giganteous** [PowerDNS/pdns#6135]
- Program: recursor
 - Issue type: Bug report

### Short description
PowerDNS recursor (4.1, master, 0.0.1929g8ebfeb0)

When the authoritative nameserver includes the CNAME target as glue, and that glue is insecure, PowerDNS fails to see "that".

Example: http://dnsviz.net/d/ugp.rug.nl/dnssec/

### Environment
 - Operating system: Debian stretch
 - Software version: 0.0.1929g8ebfeb0
 - Software source: repo.powerdns.com

### Steps to reproduce
1. start powerdns recursor
2. ask it for "A ugp.rug.nl"
3. observe

### Expected behaviour
An insecure answer

### Actual behaviour
Bogus / Servfail

**Comment by rgacogne** [comment]
Note that two out of 6 nameservers for rug.nl (ns1.surfnet.nl and ns2.surfnet.nl) are not authoritative for ugp.ub.rug.nl and thus don't send the glue we choke on, so we don't fail every time.
