### ISSUE TITLE
dnsdist: Implement cache expungeByName support in the APIs

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#6154]
- Program: dnsdist
 - Issue type: Feature request

### Short description

Currently, the dnsdist APIs do not expose any endpoint to manipulate the records cache (e.g. evict some records). 
This issue aims to request the evaluation of the implementation an endpoint to manipulate via APIs dnsdist's per-pools records cache.

### Usecase & Description

Deploying dnsdist as additional cache/protection layer in front of Authoritative DNS servers require specifically maintenance operations in order to make sure to evict dnsdist records cache everytime a DNS record is updated on the backend Authoritative DNS servers. 

Cache eviction operations are right now are only available via TCP control socket

```
dnsdist -e 'getPool(""):getCache():expungeByName(newDNSName("www.example.net"))'
```

Exposing the same functionality over HTTP RESTful APIs would ease the life-cycle management (via custom HTTP web-hooks) of the records cache without having to artificially lower its maximum TTL configuration into the `dnsdist.conf` file

**Comment by pieterlexis** [comment]
After a small discussion with @rgacogne, we decided that this endpoint should live in a new REST API (v2) that should be defined before working on this. We are not sure whether to use swagger-codegen or use the existing REST infra we have. But defining (parts of) the API needs to happen before implementation.

**Comment by dch** [comment]
I used the control socket previously, but knocked up Just Enough Lua today for this https://github.com/PowerDNS/pdns/issues/10468
