### ISSUE TITLE
Running dnsdist in client mode connects to the snmpd AgentX socket

### ISSUE THREAD

**Issue by sid3windr** [PowerDNS/pdns#6163]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

Running `dnsdist -c` prints the message `NET-SNMP version 5.7.2.1 AgentX subagent connected`. This should likely be reserved for the daemon only, not the client connecting to it.

### Environment

 - Operating system: Debian Jessie
 - Software version: 1.2.0-1pdns.jessie
 - Software source: repo.powerdns.com 

### Steps to reproduce

1. Configure SNMP agentx in the dnsdist config: `snmpAgent(false)`
2. Restart dnsdist
3. Connect to the console with `-c`

### Expected behaviour

No SNMP agent activity should occur.

### Actual behaviour
```
host:~# dnsdist -c
NET-SNMP version 5.7.2.1 AgentX subagent connected
>
```

**Comment by Habbie** [comment]
Looks like `if(client) return;` is missing from `g_lua.writeFunction("snmpAgent" ..`, I think.

**Comment by Habbie** [comment]
> Looks like if(client) return; is missing from g_lua.writeFunction("snmpAgent" .., I think.

At a slightly longer look, this not appear to be enough explanation.
