### ISSUE TITLE
enable DNS-over-TLS in the packages from repo.powerdns.com 

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#6178]
- Program: dnsdist 
 - Issue type: Feature (enable) request

### Short description
I guess this is planned anyway but IRC sez:
>  zeha> gryphius, given its friday evening in CET, i think ticket is a good idea

so here goes:

the automatically built packages on repo.powerdns.com currently do not enable the nice and shiny new DNS-over-TLS feature.

```
Package: dnsdist
Version: 0.0.1945gd24089b-1pdns.xenial
Architecture: amd64

dnsdist --version
dnsdist 0.0.1945gd24089b (Lua 5.1.4)
Enabled features: dnscrypt ebpf libsodium protobuf re2 recvmmsg/sendmmsg snmp systemd

root@dnsdist:~# dnsdist -c
> showTLSContexts()
DNS over TLS support is not present!
```

### Usecase
Have DNS-over-TLS for lazy people that don't want to build their own packages.

### Description
DNS-over-TLS with packages from repo.powerdns.com should just work ™️  

Thanks!

**Comment by zeha** [comment]
Untested and probably incomplete... but might work across all "current" ubuntus

```patch
diff --git a/build-scripts/debian-dnsdist/control.in b/build-scripts/debian-dnsdist/control.in
index 682aed138..587d76719 100644
--- a/build-scripts/debian-dnsdist/control.in
+++ b/build-scripts/debian-dnsdist/control.in
@@ -3,7 +3,7 @@ Section: net
 Priority: optional
 Maintainer: PowerDNS Autobuilder <powerdns.support@powerdns.com>
 Origin: PowerDNS
-Build-Depends: debhelper (>= 9), dh-autoreconf, dh-systemd (>= 1.5), libboost-dev, libedit-dev, libluajit5.1-dev, protobuf-compiler, libprotobuf-dev, lib-snmp-dev, pkg-config @LIBRE2DEV@ @LIBSODIUMDEV@ @LIBSYSTEMDDEV@
+Build-Depends: debhelper (>= 9), dh-autoreconf, dh-systemd (>= 1.5), libboost-dev, libedit-dev, libluajit5.1-dev, protobuf-compiler, libprotobuf-dev, lib-snmp-dev, pkg-config, libgnutls28-dev @LIBRE2DEV@ @LIBSODIUMDEV@ @LIBSYSTEMDDEV@
 Standards-Version: 3.9.7
 Homepage: http://dnsdist.org
 
diff --git a/build-scripts/debian-dnsdist/rules b/build-scripts/debian-dnsdist/rules
index cf0c6c704..1c7256278 100755
--- a/build-scripts/debian-dnsdist/rules
+++ b/build-scripts/debian-dnsdist/rules
@@ -64,6 +64,7 @@ override_dh_auto_configure:
          --libdir='$${prefix}/lib/$(DEB_HOST_MULTIARCH)' \
          --libexecdir='$${prefix}/lib' \
          --with-protobuf=yes \
+         --enable-dns-over-tls \
          --with-net-snmp \
          --with-luajit \
          $(ENABLE_SYSTEMD) \
```

**Comment by giganteous** [comment]
For ppl that are interested, I succesfully built the debian _buster_ dnsdist against stretch using a pretty vanilla cowbuilder/pdebuild infrastructure without changing a line. Busters default is with dns-over-tls.

Most of this wouldn't have been possible without @zeha :smiley:

**Comment by remcovz** [comment]
While you are at it, enable DNS-over-HTTP by default as well ;)

**Comment by Habbie** [comment]
All: your testing of #6884 would be appreciated!

**Comment by gryphius** [comment]
Thanks Habbie!

> All: your testing of #6884 would be appreciated!
I'm running the centos7 package at home. Kdig tests are ok and android P seems to use DNS-over-TLS as well.

**Comment by pieterlexis** [comment]
Fixed in the master packages.
