### ISSUE TITLE
Recursor negative cache preempts other caches

### ISSUE THREAD

**Issue by qxrftz** [PowerDNS/pdns#6186]
### Short description
Recursor negative cache preempts other caches

### Environment
 - Operating system: CentOS 6.9
 - Software version: pdns-recursor-4.1.0-1pdns.el6.x86_64, pdns-4.1.0-1pdns.el6.x86_64
 - Software source: PowerDNS repository
 - Authoritative server backend: geoip

### Steps to reproduce
1. authoritative server has a A record(a.b.c) just for 1.1.1.1, not for 2.2.2.2 
2. client(1.1.1.1) query a.b.c, then it gets a A record
3. client(2.2.2.2) query a.b.c, then it gets a negative record
4. client(1.1.1.1) query a.b.c, then it gets a unexpected record, actually, it gets a negative record

### Expected behaviour
client(1.1.1.1) should get a A record for a.b.c always, in other words, recursor negative cache should not preempt the cache for client(1.1.1.1)

### Actual behaviour
Recursor negative cache preempts the cache for client(1.1.1.1)

### Other information
- Recursor caches after step 2
```
a.b.c. 3587 IN A 1.2.3.4 ; (Indeterminate) auth=1 1.1.1.0/32
; negcache dump from thread follows
;
; main packet cache dump from thread follows
;
```
- Recursor caches after step 3
```
a.b.c. 3185 IN A 1.2.3.4 ; (Indeterminate) auth=1 1.1.1.0/32
b.c. 3593 IN SOA ns1.b.c. root.b.c. 2018011507 60 10 604800 86400 ; (Indeterminate) auth=1 
; negcache dump from thread follows
;
a.b.c. 3593 IN TYPE0 VIA b.c.
; main packet cache dump from thread follows
;
a.b.c. 3593 A  ; tag 0
```

**Comment by pieterlexis** [comment]
This is how a negative cache is supposed to work. If you want the recursor to cache per-subnet, set [`edns-subnet-whitelist`](https://doc.powerdns.com/recursor/settings.html#edns-subnet-whitelist), set the [`relevant settings`](https://doc.powerdns.com/recursor/settings.html#ecs-ipv4-bits) in the recursor.conf and enable [`edns-subnet-processing`](https://doc.powerdns.com/authoritative/settings.html#edns-subnet-processing) in the authoritative server.

If this does not solve you issue, please provide us with an example that shows this issue. This means your recursor.conf, pdns.conf, geoip config etc. As we [provide support in the open](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/). Closing this as it appears to be a support question.

**Comment by qxrftz** [comment]
I enabled ECS and it works.
Please see "Other information" I mentioned, negative cache stored without ecs information and it preempts all other caches, so all of other caches do not work. I dont think this is a expected action.

**Comment by rgacogne** [comment]
As explained in `rfc7871`'s section 7.4, `ECS` was not designed with the goal of mixing negative and positive answers. Our issue tracker is not a good place to discuss this, please try our IRC channel or mailing-lists.

**Comment by cretz** [comment]
For anyone else getting here because ECS-responses are negatively cached without ECS info, the only option I've found is to completely disable negative caching (`max-negative-ttl=0` which effectively disables it, doesn't save any cycles though, still added in code/mem). It appears at one time there was code that would mark a request/response as "variable" that would prevent it from being added to the negative cache, but that doesn't appear to currently apply.
