### ISSUE TITLE
Allow query counters to be sent to a different carbon instance

### ISSUE THREAD

**Issue by mikedamm** [PowerDNS/pdns#6192]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

Given the large volume of metrics created, it would be useful to break out query counters from performance data when sending to carbon. This would make it easier to take in sampled data without having to write a shim that intercepts carbon traffic.

**Comment by rgacogne** [comment]
Closing this since there does not seem to be a lot of interest about it.
