### ISSUE TITLE
manpages have two entries in NAME section

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#6205]
The manpages supplied with pdns 4.1.0 have a somewhat broken NAME section. Example from calidns.1, but is true for others:

```
NAME
       calidns -

       calidns - A DNS recursor testing tool
```

lintian complains about this:

https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html

 - Program: Authoritative 4.1.0, also on master I think
 - Issue type: Bug report

### Environment
 - Operating system: Debian unstable
 - Software version: 4.1.0
 - Software source: tar/git

@Habbie mentions he has reported this to @pieterlexis before :-)

**Comment by pieterlexis** [comment]
Is fixed in master (89d5bbe28a0221f960f7b82d58c55b28acacd864, 939da829ef19f9fd133ba0dd7a8e016b82e94137 and f52b0223fe256de9436bfa71fb3ad968d3e83bde) in #6033. We could backport this to 4.1.x

**Comment by zeha** [comment]
Right, forcibly rebuilding the manpages on master shows it's fixed there. Not sure it's worth fixing in 4.1...

**Comment by Habbie** [comment]
Closing this, 4.2 is about to come out.
