### ISSUE TITLE
Regression: Authoritative server 4.1.0 caches wrong SOA information in certain circumstances, leading to broken responses

### ISSUE THREAD

**Issue by crystallite** [PowerDNS/pdns#6208]
I observe similar behaviour as per #3175 with latest versions of pdns-auth (confirmed for 4.0.3 and 4.1.0) and remote backend. My system is latest Debian 9.

The bug is reproducible when a server has a bit of load (~10-20 requests per second). When negative cache expires for a record, I can see query to a backend for a SOA record, after which subsequent A queries for the same record give empty response.

The issue does not seem to manifest itself when negquery-cache-ttl=0
It is also not reproducible with an old 3.4.4 version, but caching there seems to be working in a radically different way.

**Comment by pieterlexis** [comment]
Hi,

Thanks for the report, can you please provide a minimal database and configuration with instructions on how to reproduce this issue?

Thanks!

**Comment by bortzmeyer** [comment]
It seems that the issue was also noticed by the DNS flag day tests: https://gitlab.isc.org/isc-projects/DNS-Compliance-Testing/issues/34 You'll see how several requests can lead to this situation.

**Comment by Habbie** [comment]
> It seems that the issue was also noticed by the DNS flag day tests: https://gitlab.isc.org/isc-projects/DNS-Compliance-Testing/issues/34 You'll see how several requests can lead to this situation.

That is an unrelated issue that was fixed in 4.1.0.

**Comment by Habbie** [comment]
@crystallite we have no other reports of this issue occurring in 4.0 or 4.1 - can you help us reproduce it?

**Comment by Habbie** [comment]
Related? https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/public-dns-discuss/xXun2c_jsP0/fVOcsZ7YGQAJ

**Comment by ahupowerdns** [comment]
I have probably also just seen this happen. I have a tcpdump running now.

**Comment by iprok** [comment]
Hello! It seems that I'm facing the same issue with pdns 4.2.0rc1. I would like no to post my domains publicly, but can send them in some private way. Or do any other debug that is needed.

**Comment by Habbie** [comment]
Can you please post your pdns.conf and any included config files?

**Comment by Habbie** [comment]
Closing this as we are two major releases further, and we received no feedback. If you still see this problem, please let us know and we will reopen this ticket.
