### ISSUE TITLE
Recursor should refresh . hints immediately after startup

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#6213]
PR #6209 fixed primeHints to be thread-safe, but as @ahupowerdns points out, the root hints should be refreshed immediately. Judging by the code and observed behaviour, this only happens inside `houseKeeping`, which only runs after some delay.

**Comment by rgacogne** [comment]
On the current master and 4.1.x, `houseKeeping` seems to be run immediately after startup. The first call to `MTasker::schedule()` returns `false` and `!(counter%500)` is `true` and `last_rootupdate` is `0`, so we refresh the root hints.

**Comment by omoerbeek** [comment]
Agreed. Re-open if there is evidence the analysis above is incorrect.
