### ISSUE TITLE
GeoIP Backend PDNS startup Failure: Unable to load module

### ISSUE THREAD

**Issue by Nikke1994** [PowerDNS/pdns#6223]
- Program: Authoritative, 
 - Issue type: Bug report

### Short description
PDNS wont start with the Error Message:
Unable to load module '/usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so': /usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.so: undefined symbol: _ZN10DNSBackend3getER13DNSZoneRecord

### Environment

 - Operating system:  Ubuntu 16.04
 - Software version: 
**Result of dpkg -l | grep pdns**
ii  pdns-backend-geoip                   0.0.2088g2f4ccf9-1pdns.xenial              amd64        geoip backend for PowerDNS
ii  pdns-backend-mysql                   4.0.0~alpha2-3build1                       amd64        generic MySQL backend for PowerDNS
ii  pdns-server                          4.0.0~alpha2-3build1                       amd64        extremely powerful and versatile nameserver

**Result of grep -r module-dir /etc/powerdns**
/etc/powerdns/pdns.conf:# module-dir    Default directory for modules

### Steps to reproduce

1. After having a running Installation with mysql Backend do: sudo apt-get install pdns-backend-geoip
2. Edit the pdns.conf, and add geoip to the launch Parameter
3. Edit the pdns.conf and add following parameters:
geoip-database-files=/usr/share/GeoIP/GeoIP.dat,/usr/share/GeoIP/GeoIPv6.dat
geoip-zones-file=/etc/powerdns/zone
4. Create a Zone file with this as template: https://github.com/vikstrous/pdns-geoip-example/blob/master/zone
5. sudo service pdns restart
### Expected behaviour
Would expect pdns to start and answer DNS requests as usual and Requests to the GeoIP Backend as defined

### Actual behaviour
PDNS failed restarting

**Comment by pieterlexis** [comment]
> Result of dpkg -l | grep pdns
> ii pdns-backend-geoip 0.0.2088g2f4ccf9-1pdns.xenial amd64 geoip backend for PowerDNS
> ii pdns-backend-mysql 4.0.0alpha2-3build1 amd64 generic MySQL backend for PowerDNS
> ii pdns-server 4.0.0alpha2-3build1 amd64 extremely powerful and versatile nameserver

Please install the same version of backends and servers, mixing versions is not supported.
