### ISSUE TITLE
RPZ does not refresh after initial failure

### ISSUE THREAD

**Issue by oysteivi** [PowerDNS/pdns#6238]
- Program: Recursor 
 - Issue type: Bug report 

### Short description

When rebooting a server, powerdns recursor seems to have been started before IPv6 was fully available on the server, which made the initial RPZ / rpzMaster() load fail like so:

> Jan 24 16:06:56 dnscache101 pdns_recursor[2071]: Unable to load RPZ zone
> 'aaa.bbb.ntnu.no' from '2001:700:300:aaaa::bbbb': connect: Network is
> unreachable

After this initial failure, the recursor didn't try to refresh the RPZ zone.  Restarting the recursor daemon fixed the issue.

Obviously, the Ubuntu init system is not something PowerDNS developers can fix, but it would be helpful if the recursor would retry later after this initial failure.

Pieter Lexis made the following comment on the powerdns-users mailing list:

> Looking at the code, we indeed do not start an update thread after an
> initial failure. Can you file a ticket about this[1]?

Link to my original list post:

https://mailman.powerdns.com/pipermail/pdns-users/2018-January/025207.html

And Pieter's answer:

https://mailman.powerdns.com/pipermail/pdns-users/2018-January/025208.html

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: 4.1.0
 - Software source: Compiled myself
### Steps to reproduce

1. Have rpzMaster() set up
2. Make the master unavailable - stopping the name daemon seems sufficient
3. restart powerdns recursor.

When just stopping the name daemon, the initial RPZ load fails like quoted futher up, except with "Error connecting: Connection refused" instead of "network is unreachable".  The failure mode of no further update attempts is the same.

### Expected behaviour

I would like for the recursor to retry the RPZ zone load, perhaps according to the "refresh" option to rpzMaster() if set.

### Actual behaviour

The recursor never retries the RPZ zone load.  You have to restart the recursor later when the RPZ master is available.

### Other information

Nothing further.  From Mr. Lexis' comment on the mailing list, he seems to already have a pretty good idea of what needs fixing.

Thanks!

Øystein

**Comment by pieterlexis** [comment]
#6237 is meant to fix this
