### ISSUE TITLE
Doc says addPolicyTag takes one parameter, however running recursor 4.1.1 fails and requires two parameters for this function

### ISSUE THREAD

**Issue by MangeshBhamre** [PowerDNS/pdns#6244]
Program:  Recursor
  Issue type: Bug report

Short description:
Documentation for recursor says addPolicyTag(tag) takes only 1 parameter, however lua script complains that this function takes 2 parameters.  There is no documentation explaining the second parameter for recursor 4.1.1. 

 - Software version: 4.1.1
 - Software source: PowerDNS repository

### Description
Please update documentation for 4.1.1. for addPolicyTag under DNSQuestion

**From lua**
function preresolve(dq)
        dq.addPolicyTag("MAC-ADDR")
      return false
end

**From Logs**
STL error (fonts.gstatic.com/A from 127.0.0.1): [string "chunk"]:11: This function requires at least 2 parameter(s)

**Comment by zeha** [comment]
I'd guess `dq:addPolicyTag("MAC")` will fix your problem...

**Comment by MangeshBhamre** [comment]
Thanks this fixed my issue. I was using .(dot) instead of : (semicolon).

Regards
Mangesh

**Comment by MangeshBhamre** [comment]
Closing this issue as its was coding error and not a documentation issue.
