### ISSUE TITLE
dnsdist - support reloading of configuration

### ISSUE THREAD

**Issue by Kryton4000** [PowerDNS/pdns#6249]
Program: dnsdist v1.2
Issue Type: Feature Request
OS: Centos 7

### Short description
Hi,

I am in the process of implementing dnsdist at work and we generate dnsdist configuration files from etcd/confd and templates which can generate the configuration file on the fly and restarts dnsdist when changes are detected.

Based on this we could be in a situation where all the dnsdist servers could generate a new config and restart at almost the same time and this could lead to a small outage. In addition I also assume all caching is lost whenever a restart happens? 

Based on this I was wondering if there is or could be support to have dnsdist reload its configuration?  this should mean there is no process outage and we can maintain our caches?

**Comment by dmccombs** [comment]
Does sending a `SIGHUP` to `dnsdist` not already accomplish this?

**Comment by zeha** [comment]
No, HUP is not handled specially -> terminate.

**Comment by dmccombs** [comment]
In that case, I'd certainly like to see this as well. It would make it easier to manage a list of downstreams automatically by regenerating a config and reloading it, rather than manipulating the list via the `dnsdist` client. Not having to do a full restart for that would be great.

**Comment by ahupowerdns** [comment]
dnsdist will not get a signal to reload its configuration. The complexity of enabling this is more than dnsdist can bear. We may in the future however get a facility to restart without dropping a single packet.

**Comment by dmccombs** [comment]
@ahupowerdns is there an issue we can subscribe to related to that restart without dropping packets feature for those of us interested in it?

**Comment by fancy-rabbit** [comment]
> @ahupowerdns is there an issue we can subscribe to related to that restart without dropping packets feature for those of us interested in it?

+1 @ahupowerdns is there any place we can get info about restart without dropping packets feature?

**Comment by kaplanben** [comment]
+1
