### ISSUE TITLE
authoritative: weak validation when updating zones via nsupdate 

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#6270]
- Program: Authoritative
 - Issue type: Bug report

### Short description

PowerDNS accepts to add via `nsupdate` a CNAME when an A record already exists for the same host.
Zone transfers are subsequently refused by other DNS servers strictly compliant with RFC 1912 (e.g. Bind).

### Environment

 - Operating system:  EL6
 - Software version: `pdns-4.0.5-1pdns.el6.x86_64`
 - Software source:  PowerDNS repository

### Steps to reproduce

1. Update the `my-domain.com` zone via nsupdate

```bash
# nsupdate
> server 127.0.0.1
> key <OMITTED>
> update add mytestrecord.my-domain.com 600 A 1.2.3.4
> send
> update add mytestrecord.my-domain.com 600 CNAME othertestrecord.my-domain.com
> send
> quit
```
2. Use the `pdnsutil` command to validate the zone

```bash
# pdnsutil check-zone my-domain.com
Feb 15 05:03:04 Reading random entropy from '/dev/urandom'
[Error] CNAME mytestrecord.my-domain.com found, but other records with same label exist.
Checked 69120 records of 'my-domain.com', 1 errors, 0 warnings.
```

### Expected behaviour

The zone update should be refused by PowerDNS.

### Actual behaviour

PowerDNS accepts the Zone update subsequently ZoneTransfers are refused by other DNS servers strictly compliant with RFC 1912.

e.g. with Bind

```
xfer-in: transfer of 'my-domain.com/IN/internal' from <OMITTED>#53: failed while receiving responses: CNAME and other data
```

**Comment by pieterlexis** [comment]
Note: we also need to check what we do if we have a non-CNAME record already in the zone and a CNAME is added
