### ISSUE TITLE
pdns luarec reporting UP state although service is DOWN

### ISSUE THREAD

**Issue by mz118** [PowerDNS/pdns#6271]
- Program: Authoritative
 - Issue type: Bug report

### Short description

There is a problem with our LUA records in latest git luarec version.
Monitoring wether host is UP or DOWN doesn’t work correctly and realiably

### Environment

 - Operating system: RHEL 7.4
 - Software version:  latest luarec branch
 - Software source:  compiled myself with latest luarec branch from github

### Steps to reproduce

In zone (sqlite based) I have:
host.domain       10      IN      LUA     A "ifportup(443, {'192.168.1.3', '192.168.1.2'})"
STATE: DNS configured all components are UP

On 192.168.1.2 I've stopped the service on port 443 (there is openshift service):
[root@192.168.1.2 admin]# date ; systemctl stop atomic-openshift-master-api.service ; date
Thu Feb 15 09:12:56 CET 2018

There is nothing LISTEN on 443
[root@192.168.1.2 admin]# date ; netstat -nlp | grep 443 ; date
Thu Feb 15 09:13:04 CET 2018
Thu Feb 15 09:13:04 CET 2018

STATE: DNS configured, one of components serving 443 is DOWN, service on 192.168.1.2 is DOWN, on 192.168.1.3 is UP

On ns1 I'm tailing logs:
[root@ns1 admin]# tail -f /var/log/messages
...
Feb 15 09:21:59 ns1 pdns[48998]: Lua record monitoring declaring TCP/IP 192.168.1.3:443 UP!
Feb 15 09:21:59 ns1 pdns[48998]: Lua record monitoring declaring TCP/IP 192.168.1.2:443 UP!
...
...
Feb 15 09:25:24 ns1 pdns[49089]: Lua record monitoring declaring TCP/IP 192.168.1.3:443 UP!
Feb 15 09:25:24 ns1 pdns[49089]: Lua record monitoring declaring TCP/IP 192.168.1.2:443 UP!
...

As you can see it doesn’t work - service on 192.168.1.2 on 443 is DOWN, but pdns reporting UP

I've got 2 pdns servers in master-slave 

Master config file:
cat /etc/pdns/pdns.conf:
guardian
daemon
edns-subnet-processing
gsqlite3-database=/etc/pdns/zones/powerdns.sqlite
launch=gsqlite3
gsqlite3-dnssec
local-address=0.0.0.0
local-ipv6=::
log-dns-queries=yes
loglevel=9
setgid=pdns
setuid=pdns
enable-lua-record
master

Slave config file:
cat /etc/pdns/pdns.conf:
guardian
daemon
edns-subnet-processing
gsqlite3-database=/etc/pdns/zones/powerdns.sqlite
launch=gsqlite3
gsqlite3-dnssec
local-address=0.0.0.0
local-ipv6=::
log-dns-queries=yes
loglevel=9
setgid=pdns
setuid=pdns
enable-lua-record
slave

### Expected behaviour

Expected behaviour is reporting actual state of port in pdns
### Actual behaviour

[root@ns1 admin]# tail -f /var/log/messages
...
Feb 15 09:21:59 ns1 pdns[48998]: Lua record monitoring declaring TCP/IP 192.168.1.3:443 UP!
Feb 15 09:21:59 ns1 pdns[48998]: Lua record monitoring declaring TCP/IP 192.168.1.2:443 UP!
...
...
Feb 15 09:25:24 ns1 pdns[49089]: Lua record monitoring declaring TCP/IP 192.168.1.3:443 UP!
Feb 15 09:25:24 ns1 pdns[49089]: Lua record monitoring declaring TCP/IP 192.168.1.2:443 UP!
...

Reporting UP state although service on port is DOWN

### Other information

<!--
Use the part below to file a feature request and delete the bug report part above.

**Comment by chbruyand** [comment]
TCP check has been improved in the latest version available on the luarec branch. This should now work as expected.

**Comment by chbruyand** [comment]
The LUA records branch has been merged to master. Could you update your setup to the last builds ?

**Comment by mz118** [comment]
I've just did it and it works for me. Thanks a lot

**Comment by chbruyand** [comment]
Thanks for your tests ! I'm closing the issue then.
