### ISSUE TITLE
Trace logging for RPZ hits

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#6277]
- Program: Recursor
 - Issue type: Feature request

### Short description
It would be nice for the trace log to contain some more information about RPZ hits.

### Expected behaviour
trace-regex .* for something that ends up hitting an RPZ policy would be nice to log more information about that fact. Potentially the matching entry and action taken, maybe even the zone serial # for the RPZ would be useful to some folks.

### Actual behaviour
Minimal logging is observed:
pdns_recursor[7675]: 0 [40/1] question for 'querylogme.malicious.domain.com|A' from ::1

**Comment by omoerbeek** [comment]
#9376 should fix this.
