### ISSUE TITLE
dnsdist: Add SpoofHINFOAction

### ISSUE THREAD

**Issue by dol** [PowerDNS/pdns#6280]
It would be nice to respond with a HINFO response to an ANY request. This could be done by having a new SpoofHINFOAction action.
This is inspired by https://blog.cloudflare.com/what-happened-next-the-deprecation-of-any/

```
dig cloudflare.com any @ns3.cloudflare.com +norec +short
```

An other solution/idea from the blogpost is to filter the response and only return A,AAAA,CNAME and MX records. This would be an additional Action like FilterAction(type1, type2,...).

**Comment by ahupowerdns** [comment]
Hi @dol - we have no plans of teaching dnsdist about new record types. dnsdist has as core mission not to turn into an actual nameserver. Ponder doing this in the recursor. It knows how.

**Comment by dol** [comment]
@ahupowerdns Ok. Fast response as always. I see your point. I'll try to perform the action on the recursor level.

**Comment by peterthomassen** [comment]
> we have no plans of teaching dnsdist about new record types. dnsdist has as core mission not to turn into an actual nameserver.

The same objective could be achieved by allowing [SpoofRawAction](https://dnsdist.org/rules-actions.html#SpoofRawAction) to accept a qtype (or give raw access to the response record qtype field). This way, dnsdist would not need any more specialization, and no teaching about additional record types would be required, while increasing flexibility. What do you think?

**Comment by rgacogne** [comment]
Teaching `SpoofRawAction` about the qtype would make it possible to use it to provide an answer to `ANY` queries, which I think is the only thing we can't do today with either `SpoofCNAMEAction` or `SpoofRawAction`. I'm not opposed to the idea if someone cares enough to write that code :)
