### ISSUE TITLE
Zone listing via rest api took long time

### ISSUE THREAD

**Issue by wociscz** [PowerDNS/pdns#6285]
Listing all zones via rest api took tremendous long time
If you have more then few zones it became useless - in my scenario over 35k zones and ~30s of time to result api call. Any thing/webui/script which uses this call became useless or just timed out.

Specific call:
`curl -H 'X-API-Key: mykey' http://127.0.0.1:8081/api/v1/servers/localhost/zones`

It looks like powerdns pulls from mysql lot of informations one by one with selects like:
1) first prepare/select: `Prepare	select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=? and domainmetadata.kind=?`

after that for every domains three? selects:
1) `select cryptokeys.id, flags, active, content from domains, cryptokeys where cryptokeys.domain_id=domains.id and name='somedomain.tld';`
2) `select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name='somedomain.tld' and domainmetadata.kind='PRESIGNED'`
3) `Execute SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type='SOA' and name='somedomain.tld'`

So this looks to me like un-optimised query rather than bug.
Is it possible to speed this up? Why we need to fetch so many values from mysql only for listing zones, when we have specific call `http://127.0.0.1:8081/api/v1/servers/localhost/zones/somedomain.tld` for their details?

Another approach - to get zone list quicker - is via search, which is amazingly faster (~10s)
`curl -H 'X-API-Key: mykey' 'http://127.0.0.1:8081/api/v1/servers/localhost/search-data?q=*&max=99999999'`
with this max value i'm getting whole zone informations, but you must parse out object_type:zone from results, because /search-data doesn't allow some kind of "object type" narrowing of search requtest and you will get all infos with records also.

Right now, when i need plain list of all zones, i'm getting it via direct select from mysql, but it looks "ugly" when we have "nice" api over pdns.

As i spotted, maybe this is not a bug, but feature based on some internals, so i'm considering adding some "quicklist" api endpoint to get plain zone list more quickly.

post note: listing all zones via pdnsutil list-all-zones is fast ~1s

pdns-server 4.1.1-1pdns.xenial
pdns-backend-mysql 4.1.1-1pdns.xenial
ubuntu 16.04 xenial (all updates)

**Comment by Habbie** [comment]
Related: #4944, #4628

**Comment by wociscz** [comment]
oh, so main problem is separate connection to database for every domain when zone listing..

**Comment by stokkie90** [comment]
Please fix this problem, where want to use the API.

Amount of zones: ~500000
Version: 4.1.3

When will 4.2.0 be released? Or is it possible to put it in bugfix release?

**Comment by Habbie** [comment]
4.2.0 was released several months ago, closing this!

**Comment by GerritJanYourhosting** [comment]
Is this bug fixed in version 4.2.0? The milestone says it will be fixed in 4.3.0. Please clarify

**Comment by Habbie** [comment]
> Is this bug fixed in version 4.2.0? The milestone says it will be fixed in 4.3.0. Please clarify

Please try 4.3.0 for yourself to see if the performance is acceptable :)

**Comment by zeha** [comment]
This was indeed fixed in 4.2.0; you might want to pass the new flag to the API call depending on your usecase. Please see the mentioned merge requests.
