### ISSUE TITLE
PDNS to support Views

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#63]
I was wondering if powerdns supports the concept of "views" the way ISC Bind does?

I have the following scenario:

PDNS  -----> FW -----> INTERNET -----> CLIENT1
             ^
             |
SERVER-------|

PDNS and SERVER are in the INSIDE Network (DMZ) and have private ip addresses, the problem is that when SERVER asks for a dns record PDNS should answer the A private IP address, but when CLIENT1 asks for the same record, PDNS should answer with the public IP address.

Thanks

Luciano Ramos
TelViso

**Comment by Sharaf5** [comment]
Running many instances of the same application is no the ideal view of any thing

I'm not a C++ developer but I have a look at database structre
![Screenshot_20240328_164148](https://github.com/PowerDNS/pdns/assets/36330265/eb8ac596-c130-465a-b402-4cc35796edfb)

But after nearly 11 years won't anything been changed ?
I could suggest to only have more one table `views` and more one column in `records` called  'views' that have views which is allowed to call for this query if no match retrun an empty response
global view should be the default

I think it's useful feature after all
using `unbound` with `views` I was able to give my local server local responses so nginx go for the desired distination and serve as reverse proxy and SSL terminator while no data is exposed
and clients could resolve separatly
all on top of 3 proccess only firewall, nginx, unbound

That even worked on a very limited resource machine
and I see that `pdns` is more flexable with the abilaty to use database as a backend
I was hopeful that this feature may replace unbound by pdns for me
and maybe make it an alternative to coredns with k8s

**Comment by Habbie** [comment]
Views are actually on our roadmap now, but I don't have details yet.

**Comment by Sharaf5** [comment]
Awsome news
would you open this issue agian once you have more datails
as most forums didn't mention you may support it

**Comment by joemobil** [comment]
Are there any news concerning the DNS Views feature, .e.g a time frame on the roadmap or maybe even an ETA version?

**Comment by omoerbeek** [comment]
Development work on views is progressing (btw not by me). Expected to land in the next major release of the authoritative server.
