### ISSUE TITLE
Additional EDNS options with same `OPTION-CODE` overwrite previous entry

### ISSUE THREAD

**Issue by aerique** [PowerDNS/pdns#6307]
- Program: Recursor
 - Issue type: Bug report

### Short description

When sending a DNS message to the recursor (and possible also to the auth server? (untested)) with multiple EDNS options with the same `OPTION-CODE` (see [RFC 6891](https://tools.ietf.org/html/rfc6891)) earlier EDNS options with `OPTION-CODE` will be overwritten by later ones with the same code and will not be available in a Lua script `gettag` function.

### Environment

 - Operating system: Void Linux rolling release (4.14.12_3, x86_64)
 - Software version: HEAD (as of 2018-02-26) of master branch, commit 32a290946d2ec0f740a437cf58afc8fe1612281c
 - Software source: PowerDNS/pdns:master

### Steps to reproduce

1. Acquire software that can send a DNS message with EDNS options
2. Set two EDNS options with the same `OPTION-CODE` but with different `OPTION-DATA` (as per https://tools.ietf.org/html/rfc6891#section-6.1.2)
3. Create the file `tmp.lua` with the following content:

```
function gettag(remote_ca, edns, loc, qname, qtype, ednsoptions)
    io.stderr:write("--- BEGIN ednsoptions\n")
    for k, v in pairs(ednsoptions) do
       io.stderr:write("- " .. k .. ": " .. v:getContent() .. "\n")
    end
    io.stderr:write("--- END   ednsoptions\n")
    -- NOTE: ednsoptions is only passed if `gettag-needs-edns-options=yes`

    local tag, policytags, dqdata, username = nil, nil, nil, nil
    return tag, policytags, dqdata, username, deviceid_binary
end
```

4. Start recursor as follows: `sudo ./pdns_recursor --loglevel=1 --quiet=no --gettag-needs-edns-options=yes --lua-dns-script=tmp.lua`

### Expected behaviour

I would expect the following to be printed:

```
    --- BEGIN ednsoptions
    - OPTION-CODE: OPTION-DATA-1
    - OPTION-CODE: OPTION-DATA-2
    --- END   ednsoptions
```

### Actual behaviour

The following is printed:

```
    --- BEGIN ednsoptions
    - OPTION-CODE: OPTION-DATA-2
    --- END   ednsoptions
```

### Other information

This line seems to be the problem https://github.com/PowerDNS/pdns/blob/master/pdns/ednsoptions.cc#L98 in assuming there will only every be 1 option with `optionCode`.  However this restriction is not mentioned in [RFC 6891](https://tools.ietf.org/html/rfc6891) *and* Internet Draft [Client ID in Forwarded DNS Queries](https://tools.ietf.org/html/draft-tale-dnsop-edns0-clientid-01) explicitly mentions:

> Multiple ECID options MAY appear in the OPT record.  However, the same IDENTIFIER-TYPE SHOULD not appear more than once, and each ECID option MUST only carry one IDENTIFIER-TYPE and CLIENT-IDENTIFIER pair.

**Comment by rgacogne** [comment]
We might not be able to address this issue without altering the API, because `EDNSOptionView:getContent()` returns a single value, not a table. @Habbie suggested adding a new call that returns a table while keeping the existing behavior, but @wojas also rightly suggested that this might be a good opportunity to refactor the API so we get rid of the need to call C++ methods from Lua.

**Comment by aerique** [comment]
Yes, let me mention this is not a blocker for me since I can continue my work by using different `OPTION-CODE`s.

**Comment by wojas** [comment]
Note that it is possible to make `ednsoptions` a plain Lua table and keep the API compatible at the same time by assigning a metatable to this table.

**Comment by Habbie** [comment]
```
> t = setmetatable({10,20,30}, {__index = {getContent = function(self) return self[1] end } })
> t:getContent()
10
```
