### ISSUE TITLE
Recursor: recursor_cache MemRecursorCache::get entryA / entryAAAA mixup?

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#6319]
Looking at Master - shouldn't this be "entryAAAA" here to work as intended..?
https://github.com/PowerDNS/pdns/blob/9b7f95ab22421a0f5c00a47c3abce621a7d2766c/pdns/recursor_cache.cc#L192

(I know this is a rather short one) ;)

**Comment by rgacogne** [comment]
Yes, you are absolutely right. The good news is that we only use the `QType::ADDR` trick when looking for nameservers, so the impact shouldn't be too bad, but it's still a very nice catch. Thank you!
