### ISSUE TITLE
ALIAS RR type does not work if querying over TCP

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#6328]
- Program: Authoritative
 - Issue type: Bug report

### Environment
 - Operating system: SLES12-SP3
 - Software version: 4.1.0 or 4.1.1
 - Software source: PowerDNS release repository, self compiled

### Steps to reproduce
```
# cat pdns.conf
launch=bind
bind-config=bind.conf
local-address=127.0.0.1
master=yes
expand-alias=yes
resolver=8.8.8.8

# cat bind.conf
zone "example.com" IN {
    type master;
    file "example.com";
};

# cat example.com
example.com. 100 IN  SOA localhost. user.host 2018013029 7200 3600 1209600 3600
example.com. 100 IN NS localhost.
alias.example.com. 100 IN ALIAS www.powerdns.com.
```

1. `# pdns_server --daemon=no --config-dir=. --socket-dir=.`
2. `$ dig +tcp @127.0.0.1 alias.example.com A`

### Expected behaviour
Getting a response from pdns_server

### Actual behaviour
Got this:
`;; communications error to 127.0.0.1#53: end of file
`

pdns_server says this:
`dnsproxy.cc: Error sending reply with sendmsg (socket=19): Bad file descriptor`

**Comment by sriccio** [comment]
Hello, 

I'm facing the same problem with powerdns in Ubuntu 18.04.2 LTS while querying an ALIAS record over tcp. Over udp it's ok.

Installed packages:
```
ii  pdns-backend-mysql                    4.1.1-1                           amd64        generic MySQL backend for PowerDNS
ii  pdns-server                           4.1.1-1                           amd64        extremely powerful and versatile nameserver
ii  pdns-tools                            4.1.1-1                           amd64        Tools for DNS debugging by PowerDNS
```

Ubuntu package maintainer did not update the packages ?

**Comment by Habbie** [comment]
Correct - you can get fresh packages from https://repo.powerdns.com/

**Comment by sriccio** [comment]
Oh, sweet. Thanks for pointing out the repository. Upgrading !
