### ISSUE TITLE
dnsdist loses remote logger thread on daemonizing (-d)

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdns#6329]
- Program:  dnsdist
 - Issue type: Bug report

### Short description

When starting _dnsdist_ with `-d` (`--daemonize`), the program doesn't log to a remote logger. It's as though this action were never specified, though the connect is seen:

```
addAction(AllRule(), RemoteLogAction(newRemoteLogger("10.0.0.1:4242", 2, 2)))
```
In a private conversation with @rgacogne it turns out that:

>  we call daemonize() after creating the remote logger thread
> daemonize() calls fork() and the parent process exits
> so there is no remote logger worker thread anymore

For the record, Remi also says

> same pain for TeeAction and, obviously, dnstap

### Environment

 - Operating system:  SLES12SP3
 - Software version: 1.2.1
 - Software source: OBS package

### Expected behaviour

Logging should occur as without _daemonize_

**Comment by jpmens** [comment]
It has been brought to my attention that using `--daemonize` can almost be considered stupid because _systemd_ et.al. exist, so why would I do this? I did this because _systemd_ (though available on the platform I'm working on) isn't used here for launching "applications" such as _dnsdist_. Having found _dnsdist_ has an option to daemonize I thought I'd use it. That might have been a mistake.

After a bit of consideration, I think the option/code for `--daemonize` should be removed and be done with it.

**Comment by Habbie** [comment]
> After a bit of consideration, I think the option/code for --daemonize should be removed and be done with it.

Yes.
