### ISSUE TITLE
Superslave with bind backend forgets zones data on restart

### ISSUE THREAD

**Issue by hkraal** [PowerDNS/pdns#6333]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using a superslave config zones are being defined multiple times into the `bind-supermaster-config` and on restart every zone result in a `REFUSED` until a zone update is pushed from the master.

### Environment (Master/Slave)
 - Operating system:  Ubuntu 14.04 / CentOS 7
 - Software version: 4.0.5-1 / 4.1.1-1
 - Software source: PowerDNS repository

### Steps to reproduce
1. Have master (currently on 4.0.5-1 but same issue was noticed with 3.4.11) master with MySQL backend, config gist is;
```
guardian=yes
launch=gmysql
gmysql-host=127.0.0.1
gmysql-user=powerdns_user
gmysql-dbname=powerdns_database
gmysql-password=powerdns_password
gmysql-dnssec
master=yes
slave=no
allow-axfr-ips=127.0.0.0/8,::1,$slave_ipv4,$slave_ipv6
cache-ttl=60
local-address=$master_ipv4
local-ipv6=$master_ipv6
```
2. Have slave with superslave/bin combo, config;
```
allow-notify-from=$master_ipv4,$master_ipv6
allow-unsigned-supermaster=yes
bind-dnssec-db=/var/lib/powerdns/bind-dnssec-db.sqlite3
bind-supermaster-config=/var/lib/powerdns/named-superslave.conf
bind-supermaster-destdir=/var/lib/powerdns/zones
bind-supermasters=/etc/pdns/supermasters.conf
launch=bind
master=no
setgid=pdns
setuid=pdns
slave=yes
```
3. Restart pdns on the slave

### Expected behaviour
When I do a dns lookup on the slave I would expect an answer.

### Actual behaviour
I'm getting a `REFUSED` until I push an update from the master. Besides a bunch of added zone definitions I'm not seeing a difference between the data in the /var/lib/powerdns directory so it seems the issue is with the loading of the zones in the first place.

### Other information
With only 14 unique zones on the master (there haven't been more in the past) I'm seeing a lot of duplicate zone definitions;
```
# grep ^zone named-superslave.conf|wc -l
221
# grep ^zone named-superslave.conf | sort -u |wc -l
15
```

An example of the definitions in named-superslave.conf;
```
# Superslave zone 'sdns.nl.' (added: 2018-03-11 21:51:21 +0100) (account: vps05)
zone "sdns.nl" {
        type slave;
        file "/var/lib/powerdns/zones/sdns.nl";
        masters { $master_ipv6; };
};

# Superslave zone 'sdns.nl.' (added: 2018-03-11 21:57:23 +0100) (account: vps05)
zone "sdns.nl" {
        type slave;
        file "/var/lib/powerdns/zones/sdns.nl";
        masters { $master_ipv6; };
};

# Superslave zone 'sdns.nl.' (added: 2018-03-11 21:57:23 +0100) (account: vps05)
zone "sdns.nl" {
        type slave;
        file "/var/lib/powerdns/zones/sdns.nl";
        masters { $master_ipv4; };
};

# Superslave zone 'sdns.nl.' (added: 2018-03-11 23:06:30 +0100) (account: vps05)
zone "sdns.nl" {
        type slave;
        file "/var/lib/powerdns/zones/sdns.nl";
        masters { $master_ipv4; };
};

# Superslave zone 'sdns.nl.' (added: 2018-03-11 23:06:30 +0100) (account: vps05)
zone "sdns.nl" {
        type slave;
        file "/var/lib/powerdns/zones/sdns.nl";
        masters { $master_ipv6; };
};
```

**Comment by Habbie** [comment]
Based on IRC discussion, probably a misconfig. Waiting for confirmation.

**Comment by hkraal** [comment]
Confirmed misconfig, was missing the `bind-config=/etc/pdns/named.conf` in `/etc/pdns/pdns.conf`.
