### ISSUE TITLE
recursor: add a flag to optionally send only questions or responses to the protobufServer

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#6361]
- Program: Recursor
 - Issue type: Feature request

### Short description

Add an optional flag to the `protobufServer` Lua configuration option to enable sending to the remote Protobuf Server only the DNS answers (or the DNS questions) instead of all the DNS traffic: questions and answers.

### Usecase

Adding such additional flags to the protobufServer would allow to filter at source the messages (thus the network pressure and storage/compute requirements) sent to a remote protobufServer storing or analyzing the DNS logs.

**Comment by rgacogne** [comment]
In a perfect world I would also want to be able to mark / unmark a query / response for protobuf export via the `Lua` hooks.
