### ISSUE TITLE
dnsdist: add a flag to optionally send only questions or answers to the RemoteLogger

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#6362]
- Program:  dnsdist 
 - Issue type: Feature request

### Short description

Add an optional flag to the `newRemoteLogger` configuration option to enable sending to the remote Logger only DNS answers (or DNS questions) instead of all the DNS traffic: questions and answers.

### Usecase

Adding such additional flags to `newRemoteLogger` would allow to filter at source the messages (thus the network pressure and storage/compute requirements) sent to a remote logger storing or analyzing the DNS logs.

**Comment by rgacogne** [comment]
You can already select which queries and/or responses are exported via protobuf, since we use the same selectors than for other rules.
