### ISSUE TITLE
Package issue "Unable to launch, no backends configured for querying"

### ISSUE THREAD

**Issue by Romanitch** [PowerDNS/pdns#6365]
Hi, compile latest release on Ubuntu 17.10 x64 .... after try to start ... 
got " Unable to launch, no backends configured for querying" error .... 
get a lot of time to investigation of problem ....
read this .... http://powerdns.13854.n7.nabble.com/PowerDNS-and-Different-Configuration-File-td364.html
and wuala !!! Old old (Jun 28, 2011) issue in progress ... 
"I realized that my config file has Mac line ending (ie. CR). I don't know how did happen, but PowerDNS does not like that."
Jast create new clear pdns.conf and write settings to it .... and pdns server runs correctly !!!

Please correct this !!! (Mac ending line in pdns.conf) 
Many Ubuntu instalations miissed for your product !!!

**Comment by ahupowerdns** [comment]
can you upload your configuration as a zip-file so we can have a look? we're note aware what mac line endings are in 2018.

**Comment by Romanitch** [comment]
This conf file from latest repo install - that generate this error .... after create new (clear) file with same settings - everything is work (yes - I'm check file permissions and other settings) ....
[pdns.conf.zip](https://github.com/PowerDNS/pdns/files/1825982/pdns.conf.zip)
Please check this file in zip or original file located in your repo :)

**Comment by pieterlexis** [comment]
`launch=` is indeed empty, so the error is 'correct'. For some reason, include-dir is not set. I think soemthing is up with the package. What version of Power DNS is this?

**Comment by Romanitch** [comment]
I send file not for settings discuss - read up - 'default conf file' .... I make setings in this default file - and got error - when I just copy settings in new, self created file - everything work fine !!! Today make new instalation on CentOS 7.4 x64 - got same error .... If nobody cannot revolse error - my post will be tutorial to make pdns working ... Write this because lost few hours to search and locate problem - thanks old post - found solution .... For help to comunity :)

**Comment by pieterlexis** [comment]
Yes, which version of the package did you download (4.1.x? master?) so we can investigate this issue

**Comment by Romanitch** [comment]
PowerDNS Authoritative Server 4.1.1 from https://repo.powerdns.com/repo-files/centos-auth-41.repo

**Comment by pieterlexis** [comment]
Ubuntu 17.10, installed as per the instructions on repo.powerdns.com:

```
root@732ff8bfd88e:/# dpkg -l pdns-server
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                    Version                  Architecture             Description
+++-=======================================-========================-========================-====================================================================================
ii  pdns-server                             4.1.1-1pdns.artful       amd64                    extremely powerful and versatile nameserver

root@732ff8bfd88e:/# grep -v '^#\|^$' /etc/powerdns/pdns.conf 
include-dir=/etc/powerdns/pdns.d
launch=
setgid=pdns
setuid=pdns
```
This is correct and what I expected it would be (`/etc/powerdns/pdns.d` contains the default `bindbackend.conf` file) and I can launch the service without an issue.

```
root@732ff8bfd88e:/# /usr/sbin/pdns_server --config-dir=/etc/powerdns
Mar 20 14:06:21 Reading random entropy from '/dev/urandom'
Mar 20 14:06:21 Loading '/usr/lib/x86_64-linux-gnu/pdns/libbindbackend.so'
Mar 20 14:06:21 This is a standalone pdns
Mar 20 14:06:21 Listening on controlsocket in '/var/run/pdns.controlsocket'
Mar 20 14:06:21 UDP server bound to 0.0.0.0:53
Mar 20 14:06:21 UDPv6 server bound to [::]:53
Mar 20 14:06:21 TCP server bound to 0.0.0.0:53
Mar 20 14:06:21 TCPv6 server bound to [::]:53
Mar 20 14:06:21 PowerDNS Authoritative Server 4.1.1 (C) 2001-2017 PowerDNS.COM BV
Mar 20 14:06:21 Using 64-bits mode. Built using gcc 7.2.0 on Feb 16 2018 09:54:37 by root@a98b08644445.
Mar 20 14:06:21 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Mar 20 14:06:21 Polled security status of version 4.1.1 at startup, no known issues reported: OK
Mar 20 14:06:21 Creating backend connection for TCP
Mar 20 14:06:21 [bindbackend] Parsing 0 domain(s), will report when done
Mar 20 14:06:21 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Mar 20 14:06:21 About to create 3 backend threads for UDP
Mar 20 14:06:21 Done launching threads, ready to distribute questions
```

And CentOS 7 as per the repo.powerdns.com instructions:

```
[root@c03bdfeb5f1a /]# yum info pdns
Loaded plugins: fastestmirror, ovl, priorities
Loading mirror speeds from cached hostfile
 * base: mirror.neostrada.nl
 * epel: mirror.neostrada.nl
 * extras: mirror.amsiohosting.net
 * updates: mirror.neostrada.nl
12 packages excluded due to repository priority protections
Installed Packages
Name        : pdns
Arch        : x86_64
Version     : 4.1.1
Release     : 1pdns.el7
Size        : 8.7 M
Repo        : installed
From repo   : powerdns-auth-41
Summary     : A modern, advanced and high performance authoritative-only nameserver
URL         : https://powerdns.com
License     : GPLv2
Description : The PowerDNS Nameserver is a modern, advanced and high performance
            : authoritative-only nameserver. It is written from scratch and conforms
            : to all relevant DNS standards documents.
            : Furthermore, PowerDNS interfaces with almost any database.

[root@c03bdfeb5f1a /]# grep -v '^#\|^$' /etc/pdns/pdns.conf 
daemon=no
guardian=no
launch=
setgid=pdns
setuid=pdns
```

This indeed can not launch the server:

```
[root@c03bdfeb5f1a /]# /usr/sbin/pdns_server --config-dir=/etc/pdns
Mar 20 14:09:43 Reading random entropy from '/dev/urandom'
Mar 20 14:09:43 Unable to launch, no backends configured for querying
```

The error message is very clear though. An administrator should configure the nameserver in such a way that it works for them. So I do not consider this issue a bug of any kind.
