### ISSUE TITLE
Feature request: add grepq functionality to api

### ISSUE THREAD

**Issue by nigel-heaney** [PowerDNS/pdns#6371]
### Usecase
grepq is good but allowing this information to be exposed via the api will allow for more advanced usage and easier to drill down on the information you want to extract programmatically.

### Description
Expose the grepq data via the api either as a flat list and/or provide some query function to the api call to extract all .com etc.

**Comment by rgacogne** [comment]
The rings endpoint has been added in https://github.com/PowerDNS/pdns/pull/13489, closing this.
