### ISSUE TITLE
Recursor no longer compiles with el6 boost

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#6398]
### Short description

the current master version of the recursor no longer compiles with el6 boost. 

```
DEBUG:   CXX      opensslsigners.o
DEBUG:   CXX      pdns_recursor.o
DEBUG: pdns_recursor.cc:30:40: fatal error: boost/container/flat_set.hpp: No such file or directory
DEBUG:  #include <boost/container/flat_set.hpp>
DEBUG:                                         ^
DEBUG: compilation terminated.
DEBUG: make[2]: *** [pdns_recursor.o] Error 1
DEBUG: make[2]: *** Waiting for unfinished jobs....
DEBUG: make[2]: Leaving directory `/builddir/build/BUILD/pdns-recursor-0.0.2048gae1fd33'
DEBUG: make[1]: *** [all-recursive] Error 1
DEBUG: make[1]: Leaving directory `/builddir/build/BUILD/pdns-recursor-0.0.2048gae1fd33'
DEBUG: make: *** [all] Error 2
```

### Environment

 - Operating system: EL6
 - Software version: ae1fd33
 - Software source: git

**Comment by rgacogne** [comment]
`boost::flast_set` requires `boost` >= 1.48, and `EL6` only has 1.44 IIRC, so we can't use it there. Either we detect the `boost` version or `flat_set` support and switch to something else, like an `std::set`, when it's not available, or we just switch to `std::set` no matter what. Does `boost::flat_set` have a huge advantage over a classic set?

**Comment by pieterlexis** [comment]
Note that we ourselves build against boost 1.48 (`boost148-devel`) from EPEL in EL6

**Comment by rgacogne** [comment]
So do we want to require the boost version from EPEL on EL6?

**Comment by pieterlexis** [comment]
> So do we want to require the boost version from EPEL on EL6?

My comment was a datapoint, but I think not requiring EL6 would be nice to the community though

**Comment by chbruyand** [comment]
I'll work on falling back to `std::set` when `boost::flat_set` is not available.

**Comment by mind04** [comment]
the build is still failing 
```
DEBUG: configure: error: cannot find boost/container/flat_set.hpp
```

**Comment by rgacogne** [comment]
Ah, the default action of `BOOST_FIND_HEADER` when the header isn't found it to fail with a fatal error, so we need to override it.

**Comment by chbruyand** [comment]
Sorry I didn't notice that default behaviour. I overrode the `ACTION-IF-NOT-FOUND`  argument of the `BOOST_FIND_HEADER ` so that it only displays a notice.

You may test https://github.com/PowerDNS/pdns/pull/6409

**Comment by mind04** [comment]
#6409 is compiling without issues on el6
