### ISSUE TITLE
Superslave unable to connect

### ISSUE THREAD

**Issue by robetus** [PowerDNS/pdns#6428]
Running 4.1.1 on Centos 7. Have the following listed in the slave db:

```
+-------------------------------+----------------+---------+
| ip                            | nameserver     | account |
+-------------------------------+----------------+---------+
| 23.128.64.142, 2602:fed3:2::6 | ns2.agsdns.net |         |
+-------------------------------+----------------+---------+
```
The account field is left blank but after reading many many posts I have found this to not be a problem. When I manually add the domain to the slaves domains table everything works as it should but the supermaster/superslave operation does not work. I get the error:

```
Unable to find backend willing to host agsdns.net for potential supermaster 23.128.64.142. Remote nameservers:
ns1.agsdns.net
ns2.agsdns.net
ns3.agsdns.net
```
Yes, the slave even lists its own nameserver! and still it will not sync. I'm going to attempt to list everything else I've tried. Apologies if I miss something, there has been a lot:

1. Disabled firewall on both master and slave (no firewall running at all)
2. Disabled selinux
3. Added hostnames of both master and slave to both master and slave for ping test, results: working
4. Domain metadata on master is set to: `SOA-EDIT-API INCEPTION-INCREMENT`
5. AXFR entires on master: `allow-axfr-ips=208.94.241.182/32,2604:5800:0:35::6/128,` yes those are the correct slave IPs, checked many times
6. The slaves hostname matches ns2.asgdns.net
7. Ping test: `dig ns1.agsdns.net @23.130.52.142` on slave is working
8. Tried `pdns_control notify agsdns.net ` on master

Here is my master conf file:
```
allow-axfr-ips=208.94.241.182/32,2604:5800:0:35::6/128
config-dir=/etc/pdns
daemon=yes
disable-axfr=no
guardian=yes
local-address=0.0.0.0
local-port=53
master=yes
slave=no
module-dir=/usr/lib64/pdns
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=pdns
api=yes
api-key=a6dfadsfhDFKJudfhfu7DFJGOs9JpdrQ
webserver=yes
default-soa-edit-signed=INCEPTION-INCREMENT
default-soa-edit=INCEPTION-INCREMENT
default-soa-name=ns1.agsdns.net
default-soa-mail=admin.agsdns.net
launch=gmysql
gmysql-host=localhost
gmysql-port=3306
gmysql-dbname=pdns
gmysql-user=pdns
gmysql-password=Dtdf7LCdYGif2
gmysql-dnssec=yes
```
Here is my slave conf file:
```
config-dir=/etc/pdns
daemon=yes
disable-axfr=yes
guardian=yes
local-address=0.0.0.0
local-port=53
master=no
slave=yes
slave-cycle-interval=60
module-dir=/usr/lib64/pdns
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=pdns
launch=gmysql
gmysql-host=localhost
gmysql-port=3306
gmysql-dbname=pdns
gmysql-user=pdns
gmysql-password=Dtdf7LCdYGif2
gmysql-dnssec=yes
```
There are absolutely no errors with pdns when checking status and logs. All DNS records are entered correctly on the master for agsdns.net. I made sure that the NS record of the slave was entered as shown above and all of the corresponding A and AAAA records have been entered as well. All database entries on the master have been checked and are all propagating and have been entered correctly.

I'm missing something here, I need more sets of eyes.

**Comment by Habbie** [comment]
Hello,

it appears you have
1. left in your api-key and gmysql-password - I suggest changing them now
2. edited relevant information such as IPs and domain names. Please provide real data so we can give useful help.

**Comment by robetus** [comment]
Hi @Habbie I've change everything to the real domain and IPs, everything else was fake form the start. Thank you for letting me know.

**Comment by Habbie** [comment]
The ip field takes single IPs, so you need a row for v4 and a row for v6. If you want the domains entry to pick up both for domains superslaved for ns2.agsdns.net, give these two rows the same account field.

**Comment by robetus** [comment]
Well @Habbie that was it. I got the idea to comma separate from how the slave auto inserts the domains but it's obviously not the same. I was hoping this was going to be a little more challenging :) To anyone else that may come across this in the future the correct way to enter a supermaster on a slave with both an IPv4 and IPv6 address is (account is not necessary):

```
+----------------+----------------+---------+
| ip             | nameserver     | account |
+----------------+----------------+---------+
| 23.128.64.142  | ns2.agsdns.net |         |
| 2602:fed3:2::6 | ns2.agsdns.net |         |
+----------------+----------------+---------+ 
```
