### ISSUE TITLE
Do you have any plans to support split-horizon / split-view / split-brain DNS?

### ISSUE THREAD

**Issue by schittli** [PowerDNS/pdns#6432]
- Program: Authoritative, Recursor, dnsdist
- Issue type: Roadmap-Question / Feature request

Good evening
Thank you very much for offering one of the most useful and powerful DNS Server.

### Usecase
The Subject already asks my question:
**Do you have any plans to support split-horizon DNS?**

It looks like using Dnsdist we could build such a system (I was not able to find an example),
but I guess that we have to setup one PowerDNS Server for each split-view.

It would be much easier if we could add Zones for each view directly in PowerDNS and then 'just' configure the routing.

Thanks a lot for your answer if you know more about this subject.
Kind regards,
Thomas

### Description
We expect the default / usual use cases.

**Comment by Habbie** [comment]
Depending on your needs, you can either use dnsdist as you describe, or use Lua scripting in the Recursor.

Closing this as we treat this as a support question. Please see https://www.powerdns.com/opensource.html for ways to get support!
