### ISSUE TITLE
Problem compiling recursor 4.1.2 on FreeBSD 11 with clang

### ISSUE THREAD

**Issue by ghost** [PowerDNS/pdns#6446]
- Program: Recursor 
 - Issue type: Bug report 

### Short description

Compilation of recursor 4.1.2 fails on FreeBSD 11-STABLE with latest clang:

```
c++ -DHAVE_CONFIG_H -I.  -I/usr/local/include/lua52  -I./ext/yahttp -pthread  -I/usr/local/include  -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -O2 -pipe -I/usr/local/include -I/include -fstack-protector -fno-strict-aliasing -std=c99 -Ufreebsd11 -Dfreebsd11=freebsd11 -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -I/usr/local/lib/perl5/5.24/mach/CORE -I/usr/include -I. -I/usr/local/include  -O3 -Wall -pthread -DSYSCONFDIR=\"/usr/local/etc/pdns\"  -I./ext/json11 -I./ext/rapidjson/include -I./ext/yahttp -I/usr/include -I/usr/local/include/lua52  -isystem /usr/local/include  -pthread -DSYSCONFDIR=\"/usr/local/etc/pdns\" -DPKGLIBDIR=\"/usr/local/lib/pdns-recursor\" -DLOCALSTATEDIR=\"/var/run\" -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 --param ssp-buffer-size=4 -fstack-protector -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -D_GLIBCXX_USE_C99 -isystem /usr/local/include -MT logger.o -MD -MP -MF $depbase.Tpo -c -o logger.o logger.cc &&\
mv -f $depbase.Tpo $depbase.Po

error: error: invalidinvaliderror:  invalid argumentargument '-std=c99'  '-std=c99'not  notallowed argument error with 'C++' :
'-std=c99' not allowed with 'C++'
```

### Environment

 - Operating system: FreeBSD 11.1-STABLE
 - Software version: 4.1.2
 - Software source: ports collection 

### Steps to reproduce

1. compiling powerdns-recursor from ports 
2. 
3. 

### Expected behaviour

Succsessful compilation and run

**Comment by rgacogne** [comment]
Would you mind uploading to some sort of pastebin the output of the `configure` command and the resulting config.log? Because this `-std=c99` is not coming from thin air, but I have no idea from where.

**Comment by jurajlutter** [comment]
See https://files.wilbury.net/s/AuSuvzdybLzKeBQ

**Comment by rgacogne** [comment]
In case someone else encounters the same issue, it turns out that `net-snmp-config --cflags` is responsible for the `-std=c99` flag. Disabling `SNMP` support with `--without-net-snmp` can be used as a workaround for now.

**Comment by Habbie** [comment]
I guess the remaining work here is to note this in the docs?

**Comment by rubenk** [comment]
Wow, this is now the third time I see a project using net-snmp bumping into this.
I really advise against using net-snmp-config, those flags are not meant for external linking.

See https://github.com/acassen/keepalived/commit/057c279fb8433cb298cd8611e2561eeb30ac22fc for the ugly workarounds needed to work around this.

Someone should just fix this in net-snmp I guess.
