### ISSUE TITLE
recursor: allow to specify multiple addresses in the rpzMaster option to ease failover

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#6452]
- Program: Recursor
 - Issue type: Feature request

### Usecase

Automatic failover of the RPZ retrieval.

### Description

Currently the `rpzMaster(address, name, settings)` option allows to specify a single `address` for each RPZ zone.
In case of failure connecting to the given `address`, the whole RPZ zone update fails.

It would be good to be able to:
- add an option to specify the number of retries before giving up with the IXFR
- being able to specify multiple `addresses` to automatically try with an alternative address, once the number of retries has been exhausted.

**Comment by phonedph1** [comment]
Mainly a duplicate of #4996

**Comment by Habbie** [comment]
Fixed in #6733
