### ISSUE TITLE
modules: powerdns do not call backend destructor

### ISSUE THREAD

**Issue by baloo** [PowerDNS/pdns#6453]
Dear pdns maintainers,

On pdns master, I believe the module destructor are never called. This cause a leak of resources in my backend (being unable to free its structures) and I'd like to provide a patch to fix this.

I have been chasing this bug all day, and I ended up in `MultiThreadDistributor` that `pthread_detach(pthread_self())` itself. The infinite loop there never exits and never `delete` the backend.

I'm still reading on POSIX semantics of detached threads and their relation to exit. But I believe because the threads are detached, the thread tasks exits abruptly and is never given a chance to free resources.

I intend to write a patch that:
 - do not detach threads
 - main task signals worker threads they should exit (most likely `pthread_kill`, to make syscalls exit).
 - main task join worker threads.

How does that sound? Am I missing something here? Any suggestions, remarks for a potential implementation are welcome here, obviously.

**Comment by ahupowerdns** [comment]
as explained on IRC, there are many reasons why during an exit we will not explicitly call the destructor of your backend. Even if you fix this gap, many others will be left. So if your backend needs some kind of explicit cleanup that does not happen automatically when the process disappears (or crashes), you will always run into problems.
