### ISSUE TITLE
ixfrdist: starting a new thread to handle TCP connections would be nice

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#6468]
- Program: ixfrdist 
 - Issue type: Feature request

### Short description

Currently `ixfrdist` only uses one thread to handle `UDP` and `TCP` queries, which means that we can only serve one `TCP` client at once. It would be nice to be able to serve more than one.

### Usecase
When serving large zones, the initial `AXFR` might be huge and take a few seconds, during which I would like to be able to handle new `TCP` connections.

**Comment by pieterlexis** [comment]
> rgacogne: I would revert the saddr == ComboAddress("0.0.0.0", 0) and the ACL check btw                                                          
> rgacogne: and then perhaps add a setting to limit the number of concurrent threads
