### ISSUE TITLE
recursor: recover more quickly from bogus data from auth

### ISSUE THREAD

**Issue by giganteous** [PowerDNS/pdns#6488]
- Program: Recursor
 - Issue type: Bug report/Feature request (I leave that open to you)

### Short description
One nameserver install somewhere in .nl did not sign (all) its domains with the proper keys, and
as such, bogus material was cached in our Powerdns Recursor instances.

The large TTL of the unverifyable DNSKEY makes powerdns recover slowly from such an error.

### Usecase
Recover more quickly from a administrative error on a big DNSSEC deploy.

### Description
The recursor should:
- create something to recover slightly quicker (feature)
- not trust the long ttl given in the bogus data as said data is bogus.

**Comment by rgacogne** [comment]
I think this might have been addressed by https://github.com/PowerDNS/pdns/pull/7478 ?
