### ISSUE TITLE
SOA serial not agreeing same

### ISSUE THREAD

**Issue by satya876** [PowerDNS/pdns#6513]
I am trying a multi-server deployment for PowerDNS Authoritative Server, with backend MySQL. However I am using remote database server in the each configuration file. Kindly suggest how we can resolve this issue.

Thank You !!

**Comment by ahupowerdns** [comment]
GitHub is not a support forum. Please find your way to our mailing lists or IRC channel. https://www.powerdns.com/opensource.html
