### ISSUE TITLE
rec_control does not recognize the 'include-dir' configuration directive

### ISSUE THREAD

**Issue by kaosdrachen** [PowerDNS/pdns#6536]
- Program: recursor
 - Issue type: Bug report

### Short description

While tracking an issue with rec_control, I discovered that the program does not recognize or honor the ''include-dir'' directive in /etc/powerdns/recursor.conf and will therefore fail to load any options that are only set in included files.

### Environment
 - Operating system: Debian GNU/Linux 9.4
 - Software version: 4.1.2
 - Software source: PDNS Repository

### Steps to reproduce
1. In recursor.conf, add the statement  
`include-dir=/etc/powerdns/recursor.d/`
2. In /etc/powerdns/recursor.d/local.conf, add the statement 
```
socket-dir=/var/run/pdns-recursor
socket-mode=0775
```

3. As someone not root but in the `pdns` group, run
`rec_control version`

### Expected behaviour
```
pdns@stheno:~$ rec_control version
4.1.2
```

### Actual behaviour
```
pdns@stheno:~$ rec_control version
Fatal: Unable to generate local temporary file in directory '/var/run': Permission denied
```
(It's still looking in the default location of `/var/run/` for sockets and tempfile creation)

### Other information
I consulted with Habbie on IRC and they confirmed that rec_control doesn't look at `include_dir`

According to them a quick grep of pdns_control sources indicate it, too, doesn't check for `include_dir`, but I don't currently have a non-production auth server setup to test.

**Comment by Habbie** [comment]
> I consulted with Habbie on IRC and they confirmed that rec_control doesn't look at include_dir

From a brief look at the source code - I could have missed something, but @kaosdrachen's debugging on IRC appears to have proven it.

**Comment by kaosdrachen** [comment]
I should add that moving the socket-dir= statement to /etc/powerdns/recursor.conf causes rec_control to work as intended, so it's definitely simply failing to include the include-dir files.

**Comment by MissSB** [comment]
Hi there, I've tried to follow instructions above to resolve this error but I do not seem to be making any headway. rec_control version works while root but not using user pdns 
`root@dns:~# rec_control version
4.0.0-alpha2
root@dns:~# sudo -u pdns rec_control version
Fatal: Unable to generate local temporary file in directory '/var/run': Permission denied
`
`root@dns:~# ll /var/run/pdns_recursor.controlsocket 
srwxrwxrwx 1 root pdns 0 Jan  6 11:47 /var/run/pdns_recursor.controlsocket=
`

**Comment by rgacogne** [comment]
Please don't use `4.0.0-alpha2`, it's a quite old alpha version with known issues. If you are using the outdated package provided by your distribution, we recommend switching to our own packages instead: https://repo.powerdns.com

**Comment by MissSB** [comment]
> Please don't use `4.0.0-alpha2`, it's a quite old alpha version with known issues. If you are using the outdated package provided by your distribution, we recommend switching to our own packages instead: https://repo.powerdns.com

Thank you, let me try my luck with a newer version. Is it possible to have this removed from the Linux distro repositories as this is what we get when downloading and installing by default.

**Comment by rgacogne** [comment]
> Is it possible to have this removed from the Linux distro repositories as this is what we get when downloading and installing by default.

We tried, trust me..

**Comment by MissSB** [comment]
Hi! Could use more of your help. I compiled pdns-recursor  (or at least I think I did) from pdns-master files I downloaded from https://repo.powerdns.com/ in pdns-master/pdns-recursordist/ but I seem to have hit a snag with the error below;

`# rec_control help
Fatal: Unable to generate local temporary file in directory '/var/run/pdns-recursor': No such file or directory
`
I would like the socket file to be generated in /var/run/
`# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial`

**Comment by pieterlexis** [comment]
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).
