### ISSUE TITLE
GeoLite2 

### ISSUE THREAD

**Issue by starjoe** [PowerDNS/pdns#6569]
Now the Geoip database file is GeoLite2-City.mmdb. What should I configure in pdns.conf?

**Comment by starjoe** [comment]
> Since v4.2.0, database type is determined by file suffix, or you can use new syntax. New syntax is [driver:]path[;options].

Currently supported options for dat driver (legacy libGeoIP):
mode=standard, memory, index or mmap
Currently supported options for mmdb driver (libmaxminddb):
mode=mmap
language=en (which language to use)

This paragraph can't read，
Can you give an example of trouble?

**Comment by Habbie** [comment]
GitHub tickets are not for support questions. Please see https://www.powerdns.com/opensource.html for how to get help from us.
