### ISSUE TITLE
How to perform geoip parsing based on ISP

### ISSUE THREAD

**Issue by x-hezhang** [PowerDNS/pdns#6587]
When I use geoip as the backend, how to parse according to isp, for example, to resolve the IP address of China Unicom to 1.1.1.1, to resolve the IP address of China Telecom to 2.2.2.2, if anyone knows how to achieve it, please give me leave a message, thank you

**Comment by Habbie** [comment]
Hello!

Github Issues are not for support questions.

Please see https://www.powerdns.com/opensource.html for how to get free & open support.

**Comment by pieterlexis** [comment]
Also, have you read the [GeoIP documentation](https://doc.powerdns.com/authoritative/backends/geoip.html)?
