### ISSUE TITLE
[PIPEBackend] Fatal argument error: Command '...' cannot be executed: No such file or directory

### ISSUE THREAD

**Issue by p30arena** [PowerDNS/pdns#6603]
- Issue type: Bug report/Feature request 

### Short description
[PIPEBackend] Fatal argument error: Command '...' cannot be executed: No such file or directory

### Environment
 - Operating system: Centos 7
 - Software version: 3.4.0
 - Software source: Operating system repository

### Steps to reproduce
pdns.conf
```
setuid=pdns
setgid=pdns
launch=pipe
pipebackend-abi-version=1
pipe-command=/tmp/pdns-pipe-yabco.sock
```

### Expected behaviour
I can connect to the socket manually.

and the file attrs

`srwxrwxrwx 1 pdns pdns 0 May 12 10:49 /tmp/pdns-pipe-yabco.sock`

### Actual behaviour
service pdns start
```
May 12 11:10:26 localhost.localdomain pdns[59617]: [PIPEBackend] Fatal argument error: Command '/tmp/pdns-pipe-yabco.sock' cannot be executed: No such file or directory
May 12 11:10:26 localhost.localdomain pdns[59617]: Caught an exception instantiating a backend: Command '/tmp/pdns-pipe-yabco.sock' cannot be executed: No such file or directory
May 12 11:10:26 localhost.localdomain pdns[59617]: Cleaning up
May 12 11:10:26 localhost.localdomain pdns[59617]: Done launching threads, ready to distribute questions
```

**Comment by zeha** [comment]
pipe-command needs to specify an executable, not a socket.

**Comment by p30arena** [comment]
@zeha Command to launch as backend **or the path to a unix domain socket file**. The socket should already be open and listening before PowerDNS starts.

https://doc.powerdns.com/authoritative/backends/pipe.html

its not important for me anymore, I'm using the remote backend now

**Comment by Habbie** [comment]
Is it possible that your powerdns could not find your socket, perhaps due `PrivateTMP` in the systemd unit file? The pipe backend quietly falls through to 'it must be a command' if it does not see a Unix socket where you specified it.

**Comment by Habbie** [comment]
Also, next time you file an issue, please do not destroy our issue template.

**Comment by p30arena** [comment]
@Habbie 

PrivateTMP, if it is defined in the service then it is it.
I'm surprised, thanks!

also I edited the q and tried my best to conform to the template

**Comment by Habbie** [comment]
> also I edited the q and tried my best to conform to the template

Thank you for that.

> PrivateTMP, if it is defined in the service then it is it.
> I'm surprised, thanks!

Please let us know if that resolves it for you!

**Comment by rgacogne** [comment]
Do you have anything in your logs? The reason why `pdns` exited should be visible in `journalctl -u pdns -n 200` (for the latest 200 lines, you might need to change that).

**Comment by Habbie** [comment]
I'm closing this ticket - please see https://www.powerdns.com/opensource.html for how to get support from us, as this does not appear to be a bug report.

**Comment by p30arena** [comment]
@rgacogne @Habbie the issue is resolved, please add a note to the docs mentioning PrivateTMP

**Comment by Habbie** [comment]
@p30arena unsure where - but if you go to https://github.com/PowerDNS/pdns/tree/master/docs and find the right file (it has the same structure as https://doc.powerdns.com/) there is an edit button.
