### ISSUE TITLE
FAQ points to wiki.powerdns.com which redirects to FromTrac

### ISSUE THREAD

**Issue by ncraike** [PowerDNS/pdns#6616]
- Documentation: FAQ
 - Issue type: Documentation

### FAQ points to wiki.powerdns.com which redirects to "FromTrac"

The [Generic FAQ](https://github.com/PowerDNS/pdns/wiki/FAQ) includes:

> Q: Where did powerdns.org go? And where can I find its contents?
> 
> A: It was registered by another party after a misunderstanding with our registrar. The contents have moved to  http://wiki.powerdns.com

However, if I go to [http://wiki.powerdns.com](http://wiki.powerdns.com) I am redirected to [this page](https://github.com/PowerDNS/pdns/wiki/FromTrac), which is confusing and not the content I was looking for.

I was in fact looking for [A warm welcome to DNS](https://powerdns.org/hello-dns/) which is clearly hosted on powerdns.*org*, but I can't find a copy of anywhere on powerdns.com or in the GitHub wiki.

Is this FAQ Q&A still accurate? Is powerdns.org run by some other party not at all associated with the PowerDNS team, and I should disregard the documentation hosted there? Or is this question and answer just very out of date?

**Comment by Habbie** [comment]
I have updated those bits of the FAQ.
