### ISSUE TITLE
In the case of AXFR, the record number of slave synchronization is more than the master, but the master terminal has no such records.

### ISSUE THREAD

**Issue by x-hezhang** [PowerDNS/pdns#6621]
PDNS Version： 4.1.2

Problem:
When I was doing AXFR, slave synchronized some of the records that didn't appear on the master, why did this happen? When I used the tool dig axfr mydomain to test, it was normal.

![image](https://user-images.githubusercontent.com/31786216/40218323-54e49abc-5aa3-11e8-873e-20564e9c2261.png)

**Comment by jpmens** [comment]
You are showing a screenshot of some unknown software, and you have not provided a `dig` output to prove the issue. What exactly are you expecting developers to do?

**Comment by x-hezhang** [comment]
mysql pdns records table:
![image](https://user-images.githubusercontent.com/31786216/40219655-ea8958f0-5aa8-11e8-9119-699db0b74ab0.png)

**Comment by jpmens** [comment]
ENT

**Comment by x-hezhang** [comment]
@jpmens This record is synchronized from the master side, but there is no record in the records of the master side.

**Comment by jpmens** [comment]
Don't obfuscate data, please. Try to reproduce the issue with a domain name you can share and show the steps you've taken. Dumping individual screen shots here isn't helping. So far you have not provided any information which indicates there is a bug.

**Comment by x-hezhang** [comment]
@jpmens 

I'm sorry。
I have a problem about pdns axfr.  For example,If I have a domain name, called test.com, and I have A record called a.b.test.com, will PDNS automatically create A b.test.com record when the regional transmission starts? In my current system, PDNS adds a number of such records to the database, but both the type and content fields are NULL.

thanks

**Comment by jpmens** [comment]
Those records are added automatically on the slave server, yes. You can use the `pdnsutil check-zone` command to verify that the master and slave zones are correct. On the master you might also run `rectify-zone`.

**Comment by pieterlexis** [comment]
Please read [the documentation](https://doc.powerdns.com/authoritative/backends/generic-sql.html#rules-for-filling-out-dnssec-fields) on this topic. These records are needed for correct DNSSEC serving.

**Comment by x-hezhang** [comment]
@jpmens @pieterlexis thanks
