### ISSUE TITLE
check-zone rejects occluded glue ENT records

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#6622]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

If a zone has a delegation like "`child  NS  a.ns.child`" and the appropriate glue, `rectify-zone` creates an ENT for `ns.child`, but `check-zone` rejects it.

### Environment

 - Operating system: Ubuntu 16.04 (amd64)
 - Software version: 0.0.2301g23de6c0-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce

1. Configure the below zone. (I'm using the bindbackend.)
2. Run "`pdnsutil rectify-zone 5948.mattnordhoff.xyz`"
3. Run "`pdnsutil check-zone 5948.mattnordhoff.xyz`".

Zone file:

    $ORIGIN 5948.mattnordhoff.xyz.
    $TTL 3600
    @                   SOA     ns7.mattnordhoff.net. hostmaster.mn0.us. (
                                                2018051800
                                                3600
                                                1800
                                                2678401
                                                3600
                                        )
    @                   NS      e.ns.mattnordhoff.info.
    @                   NS      e.ns.mattnordhoff.net.
    child                       NS      f.ns.child
    f.ns.child                  A       159.203.186.41
    f.ns.child                  AAAA    2604:a880:400:d0::8a0:a002

### Expected behaviour

Not errors. :-)

### Actual behaviour

    $ sudo pdnsutil rectify-zone 5948.mattnordhoff.xyz
    May 18 07:31:30 [bindbackend] Done parsing domains, 0 rejected, 11 new, 0 removed
    Adding empty non-terminals for non-DNSSEC zone
    $ sudo pdnsutil check-zone 5948.mattnordhoff.xyz
    May 18 07:31:33 [bindbackend] Done parsing domains, 0 rejected, 11 new, 0 removed
    [Error] Following record is auth=0, run pdnsutil rectify-zone?: ns.child.5948.mattnordhoff.xyz IN TYPE0
    [Warning] 'ns.child.5948.mattnordhoff.xyz|TYPE0' in zone '5948.mattnordhoff.xyz' is occluded by a delegation at 'child.5948.mattnordhoff.xyz'
    Checked 7 records of '5948.mattnordhoff.xyz', 1 errors, 1 warnings.

### Other information

Reported by @dkoster in IRC. They're using 4.1.2 and the MySQL backend.

I named the zone "`5948`" because the issue seemed related to #5948.

**Comment by mind04** [comment]
Only skip TYPE0 entries when auth is set to 0 and the occlusion is caused by a delegation

**Comment by Habbie** [comment]
We shouldn't be generating that ENT anyway, unless I'm confused?

**Comment by mind04** [comment]
The ent should always be there. Dns is a tree bla, bla bla ;)
I think your confusion is about nsec3 records related to ents.
These are optional for ents that are only derived from insecure delegations in opt out zones.
https://tools.ietf.org/html/rfc7129#section-5.1

**Comment by mnordhoff** [comment]
@Habbie You were right, this changed in 4.1.2.

I set up a VPS with Ubuntu 18.04, which packages 4.1.1, installed it, and configured the zone.

    # pdnsutil check-all-zones
    May 18 14:59:05 [bindbackend] Done parsing domains, 0 rejected, 1 new, 0 removed
    Checked 6 records of '5948.mattnordhoff.xyz', 0 errors, 0 warnings.
    Checked 1 zones, 0 had errors.

Then I enabled the repository and upgraded to 4.1.2.

    # pdnsutil check-all-zones
    May 18 15:03:19 [bindbackend] Done parsing domains, 0 rejected, 1 new, 0 removed
    [Error] Following record is auth=0, run pdnsutil rectify-zone?: ns.child.5948.mattnordhoff.xyz IN TYPE0
    [Warning] 'ns.child.5948.mattnordhoff.xyz|TYPE0' in zone '5948.mattnordhoff.xyz' is occluded by a delegation at 'child.5948.mattnordhoff.xyz'
    Checked 7 records of '5948.mattnordhoff.xyz', 1 errors, 1 warnings.
    Checked 1 zones, 1 had errors.

Unless it's a difference between the packages or configuration...

**Comment by Habbie** [comment]
> Unless it's a difference between the packages or configuration...

I'm pretty sure it's "Make check-zone error on rows that have content but shouldn’t" from https://doc.powerdns.com/authoritative/changelog/4.1.html#change-4.1.2

**Comment by Habbie** [comment]
> I think your confusion is about nsec3 records related to ents.

No, I'm well aware of the difference. In that situation, we need the ENTs to avoid sending NXDOMAIN for them. For occluded ENTs, no such problem applies.

I'm fine with a fix in either direction, in any case.
