### ISSUE TITLE
PowerDNS API doesn't correctly check mx records format

### ISSUE THREAD

**Issue by asosso** [PowerDNS/pdns#6636]
- Program: Authoritative
 - Issue type: Bug report

### Short description

PowerDNS **API** doesn't throw any errors when insert a MX record like this:

`mydomain.tld. MX 1 mail@mydomain.tld.`

Via cli, pdnsutils shows the warning:

```
$ pdnsutil check-zone mydomain.tld
[Warning] MX record in zone 'mydomain.tld' has non-hostname content 'mail@mydomain.tld.'.
```

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: 4.1.1-1pdns.xenial
 - Software source: pdns-server, pdns-backend-mysql 

### Steps to reproduce

1. Add this RRSET: `mydomain.tld. MX 1 mail@mydomain.tld.`

### Expected behaviour
Throw an error like: `MX record in zone 'mydomain.tld' has non-hostname content 'mail@mydomain.tld.'.`

### Actual behaviour
Record Saved

**Comment by zeha** [comment]
proposal: for 4.2, we could just reject parsing these MX records. Then API doesn't need extra special casing, and the extra code in check-zone can go away.

**Comment by BadikovVV** [comment]
before opening new issue.
I tried to add record MX via API
This is data witch i passed to server via API
{"rrsets": [{"changetype": "REPLACE", "type": "MX", "name": "mk8s.myvvb.local.", "ttl": "3600", 
"records": [{"content": "1  mx.myvvb.local.", "disabled": false}], "comments": [{"content": "Test MX", "account": "", "modified_at": 1679396440}]}]}
And this is the error , itch server returned
b'{"error": "Record mk8s.myvvb.local./MX \'1  mx.myvvb.local.\': Not in expected format (parsed as \'1 mx.myvvb.local.\')"}'

Look at the "content" field in the dictionary
"1  mx.myvvb.local."
Two bytes 0x20 after symbol '1'
After i deleting one byte 0x20 ,error has been disappeared . and new MX records was added
"1  mx.myvvb.local."  - get error
"1 mx.myvvb.local."  - get new MX record
I have looked your documentation again and again , but newer founded correct description for content field to MX record 

Is that a correct behavior of API?
And if 'YES'  - please add description to your documentation for API

**Comment by omoerbeek** [comment]
Please open a new issue. Piggybacking on closed existing issues is unlikely to get attention.
