### ISSUE TITLE
ALIAS RR type still broken if querying over TCP

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#6654]
- Program: Authoritative
 - Issue type: Bug report

### Short description
It seems https://github.com/PowerDNS/pdns/issues/6328 is incomplete. When the query comes in with TCP and ALIAS expansion is performed, the label in the answer section is the ALIAS target instead of the queried label.

### Environment
 - Operating system: Ubuntu 14.04
 - Software version: pdns 4.1.2+8.gdfc00b4-1pdns.trusty 
 - Software source: automatic PDNS builds

### Steps to reproduce
I query the label master.klaus, which is an ALIAS to myip.pernau.at:

`master.klaus. IN ALIAS myip.pernau.at.`

```
$ dig +noall +question +answer @regdev-tst1 master.klaus
;master.klaus.                  IN      A
master.klaus.           30      IN      A       176.9.98.135     --> OK (master.klaus)
$ dig +noall +question +answer @regdev-tst1 master.klaus +tcp
;master.klaus.                  IN      A
myip.pernau.at.         24      IN      A       176.9.98.135    --> WRONG (myip.pernau.at)
```

### Expected behaviour
The left side always should be the queried label, i.e. master.klaus.

### Actual behaviour
When queried via TCP, the left side shows the ALIAS target

### Other information
Also, the backend-query only uses UDP with EDNS0 and without fallback to TCP on "truncate".

**Comment by pieterlexis** [comment]
what backend are you using here?

**Comment by klaus3000** [comment]
pdns-backend-pgsql

**Comment by pieterlexis** [comment]
Confirmed on master
