### ISSUE TITLE
Document commands that do not work after startup

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#6665]
Various commands in dnsdist only work in the configuration file.

At least newRemoteLogger, newFrameStream*Logger come to mind, but there are others as well.

A list of them somewhere would be good, and/or a warning when used from `-c` mode.

Or make them work properly (why don't they in the first place?)

**Comment by rgacogne** [comment]
> Or make them work properly (why don't they in the first place?)

They work for me on master, how do you get that result?

**Comment by zeha** [comment]
> They work for me on master, how do you get that result?

Looks like I did something wrong when testing + reading the code. Sorry for the noise.
