### ISSUE TITLE
ALIAS: Potential interaction with ALIAS and NSEC agressive caching

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#6667]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using ALIAS with DNSSEC where the auth itself does the expansion, the NSEC(3) bitmap for the next record (if it contains and ALIAS) contains (among others) `NSEC RRSIG ALIAS`.

A resolver doing [aggressive NSEC](https://tools.ietf.org/html/rfc8198) could then conclude that A or AAAA does not exist based on its negative cache.

I believe we should _always_ set the A and AAAA on negative responses where the next name has an ALIAS to prevent aggressive resolvers from concluding that the A or AAAA record for that name does not exist.

**Comment by hlindqvist** [comment]
Does this problem also affect the LUA record type?

**Comment by mnordhoff** [comment]
No. LUA NSEC3 records appear to have the right bits. (I didn't check NSEC.)

**Comment by Habbie** [comment]
> I believe we should _always_ set the A and AAAA on negative responses where the next name has an ALIAS

not the next name but the owner name
