### ISSUE TITLE
Is SOA-EDIT working correctly - Use current epoch as SOA value

### ISSUE THREAD

**Issue by thannaske** [PowerDNS/pdns#6670]
- Program: Authoritative
 - Issue type: Bug report / QnA

### Short description
I'm running PDNS as an authoritative resolver for a zone that gets updated over a hundred times a day. This is the reason why I can't use the default SOA increment behaviour as it's limited to 99 updates per day (if I got this correct; please tell me, if I'm wrong).

I've set the SOA-EDIT metadata value to EPOCH in my configuration and on my MySQL backend. Although I'm updating it through the API the SOA just get's increased by one. No actual unix timestamp is set.

### Environment
 - Operating system: Debian 9.4
 - Software source: Official APT repository
 - Software version:
```
root@ns1 /etc/powerdns # pdns_server --version
May 24 20:25:11 PowerDNS Authoritative Server 4.0.3 (C) 2001-2016 PowerDNS.COM BV
May 24 20:25:11 Using 64-bits mode. Built using gcc 6.3.0 20170516.
May 24 20:25:11 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
May 24 20:25:11 Features: botan1.10 openssl lua 
May 24 20:25:11 Built-in modules: 
May 24 20:25:11 Configured with: " '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--sysconfdir=/etc/powerdns' '--with-dynmodules=bind ldap pipe gmysql godbc gpgsql gsqlite3 geoip lua mydns remote random opendbx tinydns' '--with-modules=' '--with-pgsql-includes=/usr/include/postgresql' '--enable-botan1.10' '--enable-tools' '--without-protobuf' '--enable-unit-tests' '--enable-reproducible' '--enable-systemd' '--with-systemd=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/pdns-cB0QhU/pdns-4.0.3=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/pdns-cB0QhU/pdns-4.0.3=. -fstack-protector-strong -Wformat -Werror=format-security -DPACKAGEVERSION='\''"4.0.3-1+deb9u2.Debian"'\'''"
```

### Steps to reproduce
1. Modify configuration according to the following.
```
root@ns1 /etc/powerdns # cat pdns.conf | grep "EPOCH"
default-soa-edit=EPOCH
default-soa-edit-signed=EPOCH
```
2. Add a new zone using the API.
3. Add a new example RR (e.g. test.$domain IN A 127.0.0.1)
4. Modify the domain meta data as well.
```
root@ns1 /etc/powerdns # pdnsutil get-meta $domain
Metadata for '$domain'
API-RECTIFY = 1
SOA-EDIT = EPOCH
SOA-EDIT-API = EPOCH
SOA-EDIT-DNSUPDATE = EPOCH
```
4. Check SOA before update.
5. Update the RR using the API.
6. Check SOA after update. 

### Expected behaviour
The SOA before the update equals a unix timestamp. The SOA after the update equals a unix timestamp that is min. > 2 as the SOA beforehand.

### Actual behaviour
The SOA after the update equals a unix timestamp that is exactly == 1 larger than the value before the update.

-> Am I missing something? I found a few issues that considered to remove deprecated values for the SOA-EDIT metadata field. What is the state of the art way to set your SOA to the current EPOCH time during update using the API?

**Comment by thannaske** [comment]
Thank you for your answer. I tried to reproduce your steps and reseted my config to default. After that I created a new zone, applied the `SOA-EDIT-API == EPOCH` configuration and added a RR for testing purposes.

```
root@ns1 /etc/powerdns # pdnsutil create-zone test.tld
Creating empty zone 'test.tld'

root@ns1 /etc/powerdns # pdnsutil set-meta test.tld SOA-EDIT-API EPOCH
Set 'test.tld' meta SOA-EDIT-API = EPOCH

root@ns1 /etc/powerdns # dig SOA @localhost +short test.tld
ns1.$domain. hostmaster.$domain. 1 10800 3600 604800 3600

# Added the RR for test.test.tld IN A 127.0.0.1 via API

root@ns1 /etc/powerdns # dig A @localhost +short test.test.tld
127.0.0.1

root@ns1 /etc/powerdns # dig SOA @localhost +short test.tld
ns1.$domain. hostmaster.$domain. 2 10800 3600 604800 3600

# Updated the RR to test.test.tld. IN A 127.0.0.2 via API

root@ns1 /etc/powerdns # dig A @localhost +short test.test.tld
127.0.0.2

root@ns1 /etc/powerdns # dig SOA @localhost +short test.tld
ns1.$domain. hostmaster.$domain. 3 10800 3600 604800 3600
```

As you can see now the SOA ist just incrementing. No EPOCH, no YYYYMMDDVV, nothing. What am I missing?

**Comment by thannaske** [comment]
When using your commands 1:1 it actually works. So the mistake must have been made by me. Thank you for your support!

**Comment by tmuncks** [comment]
No problem, glad you got it working.
