### ISSUE TITLE
dnsdist leastOutstanding add Weight

### ISSUE THREAD

**Issue by pr0vieh** [PowerDNS/pdns#6714]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

Hi,

im not shure if this possible at moment but i think its a good idea to add the Weight value to the leastOutstanding policy

the Weight can used to higher up the leastOutstanding value i think
current an leastOutstanding value of 1 is skip to next i think it can help to balance when we can set this leastOutstanding value e.g. 2 and then go next

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by rgacogne** [comment]
I'm closing this since the request is unclear to me, please let me know if you still need this!
