### ISSUE TITLE
d_algorithm should not be initialized from within signers

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#675]
In ed25519signers.cc I've found that d_algorithm is initialized as an unsigned int, which destroys the value from dnssecinfra (??)

Since this isn't hooked up yet I cannot show the exact error it will show, but should be similar to the ".. algo 0" errors reported in #511

**Comment by Habbie** [comment]
@cmouse I think this was yours? Any idea if still valid?

**Comment by cmouse** [comment]
I'll recheck.

**Comment by Habbie** [comment]
I cannot find any remaining instances of us doing this.
