### ISSUE TITLE
Notifications from wrong IPv6 address

### ISSUE THREAD

**Issue by Kaulkwappe** [PowerDNS/pdns#6751]
I have a IPv6 address bound to the MASTER server:

`local-ipv6=2a03:4000:29:xxx::3`

But SLAVE says:

`Received NOTIFY for xxx from 2a03:4000:29:xxx::2 but remote is not permitted by TSIG or allow-notify-from`

How is it possible that `::2` tries to notify when I bound it to `::3`?

`root@ns2 ~ # pdns_server --version`
`Jun 25 13:06:35 PowerDNS Authoritative Server 4.0.3 (C) 2001-2016 PowerDNS.COM BV`
`Jun 25 13:06:35 Using 64-bits mode. Built using gcc 6.3.0 20170516.`

**Comment by Habbie** [comment]
Please try setting `query-local-address6`.

**Comment by Kaulkwappe** [comment]
Thanks a lot, that did the trick :)
