### ISSUE TITLE
Invalid IPv6 address in logs

### ISSUE THREAD

**Issue by Kaulkwappe** [PowerDNS/pdns#6752]
I am not sure why but my logs contain an invalid IPv6 address:

`2a03:4000:29:394::`

The correct IPv6 address is:

`2a03:4000:29:394::3`

### Config

`local-ipv6=2a01:4f9:c010:394::3`
`allow-notify-from=94.16.119.67,2a03:4000:29:394::3`

### Database
TABLE: supermasters
```
2a03:4000:29:394::3
ns1.example.com
```

```
94.16.119.67
ns1.example.com
```

### Logs

`While checking domain freshness: Query to '[2a03:4000:29:394::]:53' for SOA of 'bar.tld.' produced no results (RCode: Query Refused)`

`Jun 25 15:34:44 ns2 pdns_server[15767]: Jun 25 15:34:44 Received serial number updates for 0 zones, had 1 timeout`
`Jun 25 15:35:44 ns2 pdns_server[15767]: Jun 25 15:35:44 1 slave domain needs checking, 0 queued for AXFR`
`Jun 25 15:35:44 ns2 pdns_server[15767]: Jun 25 15:35:44 While checking domain freshness: Query to '[2a03:4000:29:394::]:53' for SOA of 'bar.tld.' produced no results (RCode: Query Refused)`

### Version

I use 4.0.3 (64-bits mode) built using gcc 6.3.0 20170516.

**Comment by Habbie** [comment]
Hello,

please do not edit any log output or configuration data, other than passwords, so that we can try to reproduce the issue.

**Comment by Habbie** [comment]
Also, please try version 4.1.3.

**Comment by Kaulkwappe** [comment]
Do you need the exact IP addresses? Unfortunately I cannot upgrade to version 4.1.3 as I'm using Debian 9.

**Comment by Habbie** [comment]
We need unedited configs and logs, to rule out any editing errors, and yes, that means exact IP addresses.

https://repo.powerdns.com/ has Debian 9 packages for you.

**Comment by Kaulkwappe** [comment]
IP addresses are visible now. Do you need the whole config files (MASTER+SLAVE)?

**Comment by Kaulkwappe** [comment]
Seems it is just too complicated to me. I have no problems with the master but don't understand how the Slave works. Excuse me for interrupting, I won't open further issues.

**Comment by pieterlexis** [comment]
@Kaulkwappe, if the [documentation](https://doc.powerdns.com/authoritative/guides/basic-database.html) does not help you enough and you need help, please use the [mailinglist](https://doc.powerdns.com/authoritative/#getting-support) for this. There are PowerDNS users there that can help answering your questions. Do keep in mind that also there, [real data is mandatory](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/).

**Comment by Kaulkwappe** [comment]
Thanks a lot Pieter. But I think I'll try another solution with zone file editing and will built an API by myself as I don't feel very comfortable with PowerDNS as also some other behaviours or things (like errors by design #6753 or missing TLS support for the API #6521 ) are not comprehensible for me.
