### ISSUE TITLE
Allow-axfr-from and Also-Notify don't appear to have any effect.

### ISSUE THREAD

**Issue by wwparker** [PowerDNS/pdns#6756]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

I have a domain with one master and several slaves. The slaves are listed as authoritative in the zone. The slaves are also set in pdns.conf

  allow-axfr-ips=slave1IPv4 slave2IPv4 slave3IPv4
  also-notify=slave1IPv4, slave2IPv4, slave3IPv4

All but slave1IPv4 was refused acess, so I used 
   
   pdnsutl set-meta domain ALLOW-AXFR-FROM slave1IPv4 slave2IPv4 slave3IPv4

and the transfers were allowed. I have not see an NOTIFYs logged on either the master or the slave.

### Environment

 - Operating system: FreeBSD 11.1
 - Software version: PowerDNS 4.1.1
 - Software source: FreeBSD Ports 

### Steps to reproduce

1.  Edit domain
2. Save Domain
3. Apply domain

### Expected behaviour

Notify requests are send to slaves

### Actual behaviour

No Notify requests are logged or sent

**Comment by Habbie** [comment]
Hello! This looks like a support request (although sometimes we're wrong!). Please see https://www.powerdns.com/opensource.html for information on our mailing lists and IRC channel.

Closing this for now.
