### ISSUE TITLE
Feature Request: disable a domain

### ISSUE THREAD

**Issue by gdelafond** [PowerDNS/pdns#6757]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Be able to disable a domain.

### Usecase
We need to be able to disable domains but not delete them. 

### Description
Today if we disable all records on the domain, it seems to be working but `pdnsutil check-zone` is not happy with that: `[error] No SOA record present, or active, in zone '...'`

The solution found is to add a new field in the `domains` table and change the SQL requests with something like: 
- `ALTER TABLE domains ADD disabled TINYINT(1)  NULL  DEFAULT "0"  AFTER account`
- `gmysql-basic-query=SELECT r.content,r.ttl,r.prio,r.type,r.domain_id,r.disabled,r.name,r.auth FROM records AS r, domains AS d WHERE d.id=r.domain_id and d.disabled=0 and r.disabled=0 and r.type=? and r.name=?`

I think it could be useful to have this feature available "by default".

**Comment by mind04** [comment]
Checkout 'pdnsutil -v check-zone', this will include disabled records in the zone check.

**Comment by Habbie** [comment]
I'm unclear on what is requested here; can we close this ticket given @mind04's comment?

**Comment by zeha** [comment]
I think we have the feature, as given by @mind04's comment.
