### ISSUE TITLE
API rejects MX with hostname

### ISSUE THREAD

**Issue by aTanCS** [PowerDNS/pdns#6761]
- Program: Authoritative
 - Issue type: Bug report

### Short description
API rejects MX record with a hostname:
```Record example.com./MX '10 mail': Not in expected format (parsed as '10 mail.')"```

### Environment

 - Operating system: Debian Stretch
 - Software version: 4.1.3
 - Software source: PowerDNS repository

### Steps to reproduce
1. Insert MX record with a hostname using API

### Expected behaviour
Allow inserting

### Actual behaviour
Inserting is rejected

**Comment by Habbie** [comment]
Please show your full API request and response.

**Comment by Habbie** [comment]
(I suspect you are passing `10 mail`, you should be passing a fully qualified name, so `10 mail.example.com.` for example)

**Comment by aTanCS** [comment]
Yes, it is exactly, '10 mail', mail is a hostname of the same zone. We use this format in BIND. It is not correct?

**Comment by Habbie** [comment]
The API requires full names everywhere.

Closing this as it is not a PowerDNS bug.
