### ISSUE TITLE
Unable to load RPZ zone. Error waiting for answer from. Interrupted system call.

### ISSUE THREAD

**Issue by Homas** [PowerDNS/pdns#6778]
- Program: Recursor
- Issue type: Bug report

### Short description
During startup pdns recursor tries to download RPZ feeds and immediately closes connections.
### Environment
 - Operating system: Ubuntu 18.04 (running in VirtualBox)
 - Software version: 4.1.3
 - Software source: PowerDNS repository

### Steps to reproduce
1. Configure RPZ feed(s) & syslog settings
2. Start/restart service

### Expected behaviour
RPZ feeds are downloaded correctly from a first attempt.

### Actual behaviour
I'm working on RPZ distribution DNS server (https://github.com/Homas/ioc2rpz) and found that pdns recursor tries to pull RPZ feeds during startup and immediately (or a few milliseconds later) close connections with a reason  'Error connecting: Interrupted system call'. After the startup procedure RPZ feeds transferred correctly.
On other side (ioc2rpz and ISC bind) I see that pdns recursor opens a connection and ioc2rpz/bind sends data the connection is closed.
It is not happening in 100% cases but very often (70-90% cases).

Here are the Recursor log:

> Jul  8 07:36:42 ioc2rpz systemd[1]: Starting PowerDNS Recursor...
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: PowerDNS Recursor 4.1.3 (C) 2001-2018 PowerDNS.COM BV
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Using 64-bits mode. Built using gcc 7.3.0 on May 22 2018 14:51:09 by root@caec6e15ff79.
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Reading random entropy from '/dev/urandom'
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
> **Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Loading RPZ zone 'dns-bh.ioc2rpz' from 192.168.56.43:53**
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: With TSIG key 'tkey_1' of algorithm 'hmac-md5'
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Will not send queries to: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: PowerDNS Recursor itself will distribute queries over threads
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Inserting rfc 1918 private space zones
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Listening for UDP queries on 127.0.0.1:53
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Listening for UDP queries on 192.168.56.44:53
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Enabled TCP data-ready filter for (slight) DoS protection
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Listening for TCP queries on 127.0.0.1:53
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Listening for TCP queries on 192.168.56.44:53
> **Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Unable to load RPZ zone 'dns-bh.ioc2rpz' from '192.168.56.43': 'Error waiting for answer from 192.168.56.43:53: Interrupted system call'. (Will try again in 10 seconds...)**
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Set effective group id to 114
> **Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Loading RPZ zone 'dns-bh.ioc2rpz' from 192.168.56.43:53**
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: With TSIG key 'tkey_1' of algorithm 'hmac-md5'
> **Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Unable to load RPZ zone 'dns-bh.ioc2rpz' from '192.168.56.43': 'Error connecting: Interrupted system call'. (Will try again in 10 seconds...)**
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Set effective user id to 112
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Launching 3 threads
> Jul  8 07:36:42 ioc2rpz systemd[1]: Started PowerDNS Recursor.
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Done priming cache with root hints
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: message repeated 2 times: [ Done priming cache with root hints]
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Enabled 'epoll' multiplexer
> Jul  8 07:36:42 ioc2rpz pdns_recursor[8307]: Done priming cache with root hints
> **Jul  8 07:36:52 ioc2rpz pdns_recursor[8307]: Loading RPZ zone 'dns-bh.ioc2rpz' from 192.168.56.43:53**
> Jul  8 07:36:52 ioc2rpz pdns_recursor[8307]: With TSIG key 'tkey_1' of algorithm 'hmac-md5'
> Jul  8 07:36:52 ioc2rpz pdns_recursor[8307]: Loaded & indexed 690 policy records so far
> **Jul  8 07:36:52 ioc2rpz pdns_recursor[8307]: Done: 48600 policy records active, SOA: ns1.ioc2rpz.localdomain. support.ioc2rpz.localdomain. 1531031280 86400 3600 2592000 7200**
> 

Logs from ioc2rpz:
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:41 ioc2rpz tcp child started
> **Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:41 tcp/192.168.56.44:54491 query dns-bh.ioc2rpz 252 1**
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:41 Found Key ... 2018-07-08 07:36:41 Good timestamp ... Valid MAC
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: =ERROR REPORT==== 8-Jul-2018::07:36:41.956208 ===
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: ** Generic server <0.324.0> terminating
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: ** Last message in was {tcp,#Port<0.89>,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                             <<0,108,147,2,0,0,0,1,0,0,0,0,0,1,6,100,110,115,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               45,98,104,7,105,111,99,50,114,112,122,0,0,252,0,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               1,6,116,107,101,121,95,49,0,0,250,0,255,0,0,0,0,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               0,58,8,104,109,97,99,45,109,100,53,7,115,105,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               103,45,97,108,103,3,114,101,103,3,105,110,116,0,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               0,0,91,65,191,10,1,44,0,16,34,190,225,85,182,43,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                               72,8,214,92,24,253,112,238,142,118,147,2,0,0,0,0>>}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: ** When Server state == {state,#Port<0.89>,[<0.82.0>]}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: ** Reason for termination ==
> **Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: ** {{badmatch,{error,closed}},**
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     [{ioc2rpz,send_dns_tcp,3,[{file,"src/ioc2rpz.erl"},{line,88}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {ioc2rpz,send_cached_zone,7,[{file,"src/ioc2rpz.erl"},{line,532}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {ioc2rpz,parse_dns_request,3,[{file,"src/ioc2rpz.erl"},{line,208}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {ioc2rpz,handle_info,2,[{file,"src/ioc2rpz.erl"},{line,58}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: 
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: =CRASH REPORT==== 8-Jul-2018::07:36:41.963206 ===
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:   crasher:
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     initial call: ioc2rpz:init/1
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     pid: <0.324.0>
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     registered_name: []
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     exception error: no match of right hand side value {error,closed}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in function  ioc2rpz:send_dns_tcp/3 (src/ioc2rpz.erl, line 88)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in call from ioc2rpz:send_cached_zone/7 (src/ioc2rpz.erl, line 532)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in call from ioc2rpz:parse_dns_request/3 (src/ioc2rpz.erl, line 208)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in call from ioc2rpz:handle_info/2 (src/ioc2rpz.erl, line 58)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in call from gen_server:try_dispatch/4 (gen_server.erl, line 637)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:       in call from gen_server:handle_msg/6 (gen_server.erl, line 711)
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     ancestors: [ioc2rpz_sup,<0.81.0>]
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     message_queue_len: 1
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     **messages: [{tcp_closed,#Port<0.89>}]**
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     links: [<0.82.0>]
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     dictionary: []
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     trap_exit: false
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     status: running
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     heap_size: 6772
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     stack_size: 27
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     reductions: 58553
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:   neighbours:
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: 
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]: =SUPERVISOR REPORT==== 8-Jul-2018::07:36:41.968075 ===
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     supervisor: {local,ioc2rpz_sup}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     errorContext: child_terminated
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     reason: {{badmatch,{error,closed}},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:              [{ioc2rpz,send_dns_tcp,3,[{file,"src/ioc2rpz.erl"},{line,88}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {ioc2rpz,send_cached_zone,7,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                        [{file,"src/ioc2rpz.erl"},{line,532}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {ioc2rpz,parse_dns_request,3,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                        [{file,"src/ioc2rpz.erl"},{line,208}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {ioc2rpz,handle_info,2,[{file,"src/ioc2rpz.erl"},{line,58}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:               {proc_lib,init_p_do_apply,3,
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                         [{file,"proc_lib.erl"},{line,249}]}]}
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:     offender: [{pid,<0.324.0>},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                {id,ioc2rpz},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                {mfargs,{ioc2rpz,start_ioc2rpz,undefined}},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                {restart_type,temporary},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                {shutdown,1000},
> Jul  8 07:36:41 ioc2rpz aae893a2eeaa[796]:                {child_type,worker}]
> Jul  8 07:36:51 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:51 ioc2rpz tcp child started
> **Jul  8 07:36:51 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:51 tcp/192.168.56.44:54403 query dns-bh.ioc2rpz 252 1
> Jul  8 07:36:51 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:51 Found Key ... 2018-07-08 07:36:51 Good timestamp ... Valid MAC
> Jul  8 07:36:52 ioc2rpz aae893a2eeaa[796]: 2018-07-08 07:36:52 Zone "dns-bh.ioc2rpz" transfer time was 57 milliseconds**

Logs from bind:

**> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee3ffc1020 192.168.56.45#53701/key tkey_1 (at-hosts.ioc2rpz): transfer of 'at-hosts.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee3ffc1020 192.168.56.45#53701/key tkey_1 (at-hosts.ioc2rpz): transfer of 'at-hosts.ioc2rpz/IN': send: socket is not connected**
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee17fc1020 192.168.56.45#53407/key tkey_1 (at-ipv4.ioc2rpz): transfer of 'at-ipv4.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee17fc1020 192.168.56.45#53407/key tkey_1 (at-ipv4.ioc2rpz): transfer of 'at-ipv4.ioc2rpz/IN': **send: socket is not connected**
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fedbda416b0 192.168.56.45#51195/key tkey_1 (notracking.ioc2rpz): transfer of 'notracking.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fedbda416b0 192.168.56.45#51195/key tkey_1 (notracking.ioc2rpz): transfer of 'notracking.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee3ffc1020 192.168.56.45#57115/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee3ffc1020 192.168.56.45#57115/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee33fc7030 192.168.56.45#37413/key tkey_1 (at-hosts.ioc2rpz): transfer of 'at-hosts.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee33fc7030 192.168.56.45#37413/key tkey_1 (at-hosts.ioc2rpz): transfer of 'at-hosts.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee17fc1020 192.168.56.45#55417/key tkey_1 (at-ipv4.ioc2rpz): transfer of 'at-ipv4.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee17fc1020 192.168.56.45#55417/key tkey_1 (at-ipv4.ioc2rpz): transfer of 'at-ipv4.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee57fc1020 192.168.56.45#45787/key tkey_1 (notracking.ioc2rpz): transfer of 'notracking.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fee57fc1020 192.168.56.45#45787/key tkey_1 (notracking.ioc2rpz): transfer of 'notracking.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fedbda416b0 192.168.56.45#33745/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:47 ioc2rpz named[779]: client @0x7fedbda416b0 192.168.56.45#33745/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': send: socket is not connected
> Jul  9 05:50:57 ioc2rpz named[779]: client @0x7fedebfc1020 192.168.56.45#33537/key tkey_1 (notracking.ioc2rpz): transfer of 'notracking.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:57 ioc2rpz named[779]: client @0x7fedfffcd030 192.168.56.45#46345/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:57 ioc2rpz named[779]: client @0x7feddbfc1020 192.168.56.45#35553/key tkey_1 (at-hosts.ioc2rpz): transfer of 'at-hosts.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:50:57 ioc2rpz named[779]: client @0x7fedd3fc1020 192.168.56.45#53467/key tkey_1 (at-ipv4.ioc2rpz): transfer of 'at-ipv4.ioc2rpz/IN': AXFR started: TSIG tkey_1 (serial 1531100580)
> Jul  9 05:51:02 ioc2rpz named[779]: client @0x7fedfffcd030 192.168.56.45#46345/key tkey_1 (dns-bh.ioc2rpz): transfer of 'dns-bh.ioc2rpz/IN': AXFR ended
> 

### Other information
4.1.1 has different strange behaviour. After starting up it made AXFR and immediately after that IXFR. There was a bug "Fix IXFR skipping the additions part of the last sequence" in 4.1.1 this is why I've upgraded to 4.1.3
To check that the issues is not related to any old libs I've deployed a new Ubuntu 18.04 VM and installed PDNS Recursor only from PowerDNS repository 
Just in case I'm running VirtualBox with 3 VMs on Macbook Pro. VMs connected via "Host-only Adapter".

**Comment by rgacogne** [comment]
Thank you for reporting this issue. We clearly should handle the `EINTR` error leading to `Interrupted system call` better in that case, but I'm wondering what kind of signal does the process keep receiving. Would you by any chance be able to `strace` the process during a failing RPZ load?

**Comment by phonedph1** [comment]
We see this too, seems to be the same as type as:

https://bugzilla.redhat.com/show_bug.cgi?id=473907

as commenting out the setuid/setgid lines in our config means it loads cleanly.

**Comment by rgacogne** [comment]
Right, IIRC this is the `SIGRT_1` trick used to let other threads know that they need to switch credentials when `set*id()` has been called from a thread because `POSIX` requires that all threads use the same credentials but Linux actually handles it per thread, or something like that. This probably means we should either delay the Lua parsing until after we have dropped our privileges (but that means making sure we don't need special privileges at that time) or delay the creation of the `RPZ` and `protobuf` threads until after we have dropped our privileges.
