### ISSUE TITLE
API: api-readonly flag is ignored for rectify zone call

### ISSUE THREAD

**Issue by dkoster** [PowerDNS/pdns#6781]
- Program: Authoritative
 - Issue type: Bug report

### Short description
The powerdns config flag: api-readonly=yes is ignored by the api call "Rectify zone".
So instead of an "405 Method Not Allowed" it returns a "200 OK" and the zone is rectified.

### Environment
 - Operating system: CentOS 7 (fully patched) 
 - Software version: pdns-4.1.3-1
 - Software source: PowerDNS repository

### Steps to reproduce
1. Set the config flag to "api-readonly=yes"
2. Run the rectify zone api call

### Expected behaviour
The call should return a "405 Method Not Allowed" on all data changing actions

### Actual behaviour
In this case the api call is executed and the zone is rectified instead of the "405 Method Not Allowed".

**Comment by pieterlexis** [comment]
ReadOnly has been removed in master (#6845)
