### ISSUE TITLE
How to answer ANY query??

### ISSUE THREAD

**Issue by wonter** [PowerDNS/pdns#6797]
- Program: Authoritative
 - Issue type: Bug report/Feature request

### Short description

I'm trying to write my own backend, and i have read this two docs [backend-writers-guide](https://doc.powerdns.com/authoritative/appendices/backend-writers-guide.html) and [what-is-a-powerdns-backend-and-how-do-i-make-it-send-an-nxdomain](https://blog.powerdns.com/2015/06/23/what-is-a-powerdns-backend-and-how-do-i-make-it-send-an-nxdomain/).

But i still have a question that is how to answer ANY query in code?

[backend-writers-guide](https://doc.powerdns.com/authoritative/appendices/backend-writers-guide.html) told me:
>When a server receives a question for this ANY type, it should reply with all record types available.

But i don't know the details in the code.In other word, how to construct `DNSResourceRecord &r`.

**Comment by Habbie** [comment]
Hello!

Good to hear you are writing your own backend! However, our GitHub tickets are not a support forum. Please see https://www.powerdns.com/opensource.html for how to reach us via IRC or mailing list so we can help you out.
