### ISSUE TITLE
bogus dnssec validation for unsigned domains

### ISSUE THREAD

**Issue by neonknight** [PowerDNS/pdns#6799]
- Program: Recursor
 - Issue type: Bug report

### Short description
many bogus dnssec entries in log for domains that are not dnssec signed. problem is not reliably reproduceable for a given hostname. 

### Environment
 - Operating system: CentOS release 6.10 (Final)
 - Software version: pdns-recursor-4.1.3-1pdns.el6
 - Software source: repo.powerdns.com

### Steps to reproduce
- recursor.conf
```
setuid=pdns-recursor
setgid=pdns-recursor
root-nx-trust=yes
allow-from=127.0.0.0/8, <redacted>
disable-packetcache=yes
dnssec=log-fail
dnssec-log-bogus=yes
forward-zones-file=/etc/pdns-recursor/forward.conf
local-address=127.0.0.1, <redacted>
lua-config-file=/etc/pdns-recursor/recursor.lua
max-negative-ttl=10
packetcache-servfail-ttl=30
packetcache-ttl=30
threads=4
```
- recursor.lua sets NTA for a local domain:
`addNTA("<redacted>", "do not validate local zone");`

- forward.conf redirects some local domains to internal authoritative servers and some blacklists to a local rbldnsd:
```
redacted.dom=red.act.ed.ip, red.act.ed.ip
redacted.in-addr.arpa=red.act.ed.ip, red.act.ed.ip
redacted.in-addr.arpa=red.act.ed.ip, red.act.ed.ip

zen.spamhaus.org=127.0.0.1:530
dbl.spamhaus.org=127.0.0.1:530
sbl-xbl.spamhaus.org=127.0.0.1:530
pbl.spamhaus.org=127.0.0.1:530
sbl.spamhaus.org=127.0.0.1:530
```

### Expected behaviour
domain googlemail.com is unsigned, therefore it should not validate as bogus.

### Actual behaviour
log shows entries such as:
 - Answer to aspmx5.googlemail.com|A for redacted:45913 validates as Bogus
 - Answer to pdns12.domaincontrol.com|A for redacted:53415 validates as Bogus

however, this does not happen every time the recursor needs to resolve one of these host names!

### Other information
n/a

**Comment by rgacogne** [comment]
Hi! Can you please include the content of the /etc/pdns-recursor/forward.conf file ?

**Comment by neonknight** [comment]
@rgacogne done

**Comment by rgacogne** [comment]
It's almost impossible for us to understand what's going on with obfuscated data, see https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/

In the meantime, I'd suggest trying with `root-nx-trust` set to `no` since I suspect an interaction issue between your forwards and DNSSEC validation. If that doesn't fix the issue we are going to need the real configuration, some traces of DNSSEC failures (using `trace` or `rec_control trace-regex ...`) along with the relevant cache dumps (`rec_control dump-cache ...`) to understand what's going on.

**Comment by neonknight** [comment]
Thank you for the hints. I have a hard time imagining it's caused by the forwards, as the forwarded domains are not affected by the Bogus messages. Unfortunately I can't just disable the forwards to confirm this as this is a live production server.

This is what I have been able to accomplish so far:

- Set root-nx-trust to no and restarted the resolver. This did not improve the situation. But I noticed that after a restart of the resolver it takes several minutes until the first "Bogus" messages appear.

- I noticed that once a host name reported to be Bogus is removed from cache future resolving attempts will be correct.

- I tried to trace a few host names/domains that fail regularly, but I have not been successful. Indeed once I start tracing a host name or domain, as soon as the next full stack lookup from root server happens, no more "Bogus" messages appear for the traced domain. Therefore so far I have only been able to acquire a partial trace for a host name that that has been failing before I enabled the trace:
```
Jul 20 14:20:56 cache1 pdns_recursor[7816]: 1 [6423907/1] question for 'pdns11.domaincontrol.com|A' from 127.0.0.1
Jul 20 14:20:56 cache1 pdns_recursor[7816]: [6423907] pdns11.domaincontrol.com: Wants DNSSEC processing, auth data in query for A
Jul 20 14:20:56 cache1 pdns_recursor[7816]: [6423907] pdns11.domaincontrol.com: Looking for CNAME cache hit of 'pdns11.domaincontrol.com|CNAME'
Jul 20 14:20:56 cache1 pdns_recursor[7816]: [6423907] pdns11.domaincontrol.com: No CNAME cache hit of 'pdns11.domaincontrol.com|CNAME' found
Jul 20 14:20:56 cache1 pdns_recursor[7816]: [6423907] pdns11.domaincontrol.com: Found cache hit for A: 216.69.185.55[ttl=69386] 
Jul 20 14:20:56 cache1 pdns_recursor[7816]: [6423907] pdns11.domaincontrol.com: updating validation state with cache content for pdns11.domaincontrol.com to Bogus
```

My suspicion is that there's some kind of cache corruption or race condition going on. Alternatively I would assume the resolver gets rate limited by some root server or TLD root server... This is just a quick intermediate report. I will continue to play hide-and-seek with Bogus trace attempts and report back as soon as I have something better.

**Comment by neonknight** [comment]
I could resolve it. My gut feeling told to add NTA for all the domains in forward.conf. Apparently due to the aggressive cache settings we queried the root servers for inexisting DS records until we got into some rate limits. Just, there was nothing indicating this anywhere in the logs, even using various trace options (e.g. trace=fail)
