### ISSUE TITLE
Is it possible to add Ubuntu armhf builds?

### ISSUE THREAD

**Issue by seitzbg** [PowerDNS/pdns#6801]
- Program: dnsdist, auth, recursor
 - Issue type: Feature request

### Short description
Is it possible to add Ubuntu armhf builds?

### Usecase
Run official dnsdist/pdns packages on Ubuntu armhf.

### Description
Please provide Ubuntu armhf builds for dnsdist (and others) like you do for Raspbian.

**Comment by pieterlexis** [comment]
armhf does not have 64-bit time_t, closing.
