### ISSUE TITLE
Clarify behavior of dnsdist when addXPF is enabled and an XPF record is provided by the client

### ISSUE THREAD

**Issue by clokep** [PowerDNS/pdns#6814]
This came from an IRC conversation, I'll include that at the bottom of the ticket. Also thanks for working on dnsdist and PowerDNS! 👍 

 - Program: dnsdist
 - Issue type: Bug report (I think?)

### Short description

Typically if a HTTP reverse proxy injects the `X-Forwarded-For` header to an HTTP request then it also strips any instance of that sent by the client to avoid it being forged. It is unclear what dnsdist's behavior is with respect to the XPF record added when `addXPF` is enabled.

From IRC, @Habbie said "it should rewrite but i think it currently appends".

### Expected behaviour

When `addXPF` is enabled, any XPF record incoming to dnsdist is removed and replaced with the XPF as calculated by dnsdist.

### Actual behaviour

This is unclear, but it seems to append. Taking a look at the code, it seems like `addXPF` only appends.

### Other information
IRC conversation:

1:39:19 PM - clokep_tb: Habbie: Hi! I had a follow-up question about XPF / dnsdist; I didn't see it documented anywhere, but does dnsdist strip any received XPF records to ensure that clients can't forge them?
2:13:15 PM - ph1: clokep_tb: Isn't that a valid use case (using them without stripping them out)?
2:14:14 PM - clokep_tb: ph1: For HTTP it is usually considered a security vulnerability.
2:14:29 PM - clokep_tb: I.e. it can be used easily for abuse.
2:14:39 PM - ph1: I agree
2:14:55 PM - ph1: but I can also picture people doing weird things that would need it, but the defualt I guess probably should be "rip it off"
2:15:37 PM - ph1: I'm guessing if something came in to dnsdist with it dnsdist would probably re-write it anyways but I haven't tried it.
2:15:41 PM - clokep_tb: I guess I'm asking if there's an option for it then. :)
2:16:04 PM - clokep_tb: Right, I'm curious if it rewrites it or appends it.
2:36:56 PM - Habbie: it should rewrite but i think it currently appends

**Comment by rgacogne** [comment]
The current behavior is indeed to append a new `XPF` record without checking whether an existing one is already there. Rewriting would mean parsing the existing one, and might be tricky if the address family doesn't match and the record is not the last one.
I'd suggest writing a rule dropping or refusing any incoming query containing a `XPF` record instead, as specified in section 3.2 of the current draft [1].

[1]: https://tools.ietf.org/html/draft-bellis-dnsop-xpf-04#section-3.2

**Comment by clokep** [comment]
Dropping queries that seem abusive makes sense and definitely seems simpler than my proposal above. I don't really think any of the parts of section 3.2 really refer to this, however. I believe all of those conditions can be met, but you still want to do extra handling of the packet.

Regardless, would it make sense to add a rule to dnsdist that does this automatically if enabling `addXPF`? It seems like it would be good to have a "secure by default" implementation instead of assuming people have read the RFC.

**Comment by rgacogne** [comment]
> Dropping queries that seem abusive makes sense and definitely seems simpler than my proposal above. I don't really think any of the parts of section 3.2 really refer to this, however. I believe all of those conditions can be met, but you still want to do extra handling of the packet.

Agreed, if you want to allow incoming queries with an existing `XPF` value (section 3.3 is probably more relevant then).

> Regardless, would it make sense to add a rule to dnsdist that does this automatically if enabling addXPF? It seems like it would be good to have a "secure by default" implementation instead of assuming people have read the RFC.

Right, I agree we might want to implement an option to drop incoming queries with existing `XPF` records, and perhaps a second one to preserve existing records from white-listed clients.
In the meantime, if you need a solution today https://dnsdist.org/rules-actions.html#RecordsTypeCountRule might do.
