### ISSUE TITLE
'pdns_control list-zones' zones prints zones out twice

### ISSUE THREAD

**Issue by imreoolberg** [PowerDNS/pdns#6829]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

I noticed 'pdns_control list-zones' had couple of zones printed out twice. And good people on irc #powerdns (esp. ahu) suggested to see if these zones have more than one SOA record. And indeed they had. After deleting all but one, everything seems to be back to normal.

### Environment

 - Operating system: Ubuntu 16.04 amd64
 - Software version: 4.0.3-1pdns.xenial
 - Software source: repo.powerdns.com 

### Steps to reproduce

1. open master zone in edit-zone
2. add next SOA which is different for example by serial number
3. save
4. look at 'pdns_control list-zones'

### Expected behaviour

Actually i would expect that zone could contain exactly one SOA record (or at least 'pdns_control list-zones' shows the zone not twice).

### Actual behaviour

edit-zone permits to enter more than one SOA record and check-zone sees no error. 'pdns_control list-zones' shows zones twice.

### Other information

Since i use postgresql backend I looked also into postgresql database and saw that in general everything is ok but there are too several SOA entries found (but i didnt notice it until ahu on irc suggested it might have to do with it).

Also, since i use nsedit i have in zones this metadata

Metadata items: 
	SOA-EDIT	INCEPTION-INCREMENT
	SOA-EDIT-API	INCEPTION-INCREMENT

**Comment by zeha** [comment]
`SELECT DISTINCT` comes to mind. But this is really a data issue.

**Comment by rgacogne** [comment]
I think we should warn about the duplicate `SOA` with `check-zone`, and it would be nice to refuse it in `edit-zone` and the `API`. I'm not too worried about the behavior of `list-all-zones` once we have a duplicate `SOA`.

**Comment by zeha** [comment]
Warning/refusing makes sense. I think we should add DISTINCT to the list-*-zones SQL queries anyway (but not to list-*-records...).

**Comment by zeha** [comment]
I had a look at adding DISTINCT but that's just not going to work.
