### ISSUE TITLE
API - Validate existing record before replace/update

### ISSUE THREAD

**Issue by gnalawade** [PowerDNS/pdns#6833]
- Program: Authoritative
 - Issue type:  Bug/Feature

### Short description
There is no way to validate if existing A record present and fail if so. I see if new A record with different IP but same name would replace existing IP.  I know there is way to use custom validator before placing request but wanted to check if PowerDNS API level checks is good idea

### Environment
 - Operating system: CentOS 7.4
 - Software version:  PDNS-4.0.5
 - Software source: PowerDNS repository

### Steps to reproduce

1. PATCH body: {"rrsets": [{"records": [{"disabled": false, "name": "test100.example.net.", "set-ptr": true, "content": "192.168.10.10", "type": "A", "priority": 0}], "changetype": "REPLACE", "type": "A", "name": "test100.example.net.", "ttl": 3600}]}
2. PATCH body: {"rrsets": [{"records": [{"disabled": false, "name": "test100.example.net.", "set-ptr": true, "content": "192.168.10.11", "type": "A", "priority": 0}], "changetype": "REPLACE", "type": "A", "name": "test100.example.net.", "ttl": 3600}]}
3. PATCH body: {"rrsets": [{"records": [{"disabled": false, "name": "test100.example.net.", "set-ptr": true, "content": "192.168.10.12", "type": "A", "priority": 0}], "changetype": "REPLACE", "type": "A", "name": "test100.example.net.", "ttl": 3600}]}

### Expected behaviour
Step#2 fail since record already exists

### Actual behaviour
It is replacing existing IP with new IP 

### Usecase
Typo or mistaken to update A record with same existing name but different IP.  Especially for large DNS updates

### Description
There may be option to use custom validation before making API call as well

**Comment by peterthomassen** [comment]
I'd expect PATCH to behave at it does; the requested feature is the typical behavior of POST.

**Comment by Habbie** [comment]
I do not understand what you are asking for. You ask pdns to replace the RRset; it does so. What is the problem?

**Comment by peterthomassen** [comment]
I think the request is to have "add this if RRset does not exist", as opposed to "add or overwrite if exists".

Typically, POST is "add if does not exist", and PATCH is "add or overwrite".

**Comment by Habbie** [comment]
I'd rather solve this through #6247, so I'm closing this one.
