### ISSUE TITLE
function postresolve in dns64.lua script

### ISSUE THREAD

**Issue by ebrodskiy** [PowerDNS/pdns#6836]
- Program: Recursor 
 - Issue type: Bug report 

### Short description

I am adding dns64.lua script in pdns-recursor. And it works excellent.
But when I make a little modification, to see generated IPv6 in log, for domains with only A record. I get "STL error" in logs.

### Environment

 - Operating system: Linux dns64-host01 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04.5 LTS)
 - Software version: PowerDNS Recursor 4.1.3
 - Software source:  http://repo.powerdns.com/ubuntu xenial-rec-41 main

### Steps to reproduce

1. 
Create basic dns64.lua script from example (https://doc.powerdns.com/recursor/lua-scripting/hooks.html?highlight=cache#dns64) and add it to recursor.conf 

2. 
Make next  additions to dns64.lua script.

generally I add function postresolve:

function postresolve( dq )
     local records = dq:getRecords()
     for k, v in pairs(records) do
         pdnslog ("result: id - "..k..", name - "..v.name:toString()..", data -  "..v:getContent(), pdns.loglevels.All)
     end
end

But I got the same error when I added function postresolve without any content:

function postresolve( dq )
end

3. 

### Expected behaviour

When you try to resolv AAAA record for ukr.net (for examle) you should see next strings in log:

Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 1, name - ukr.net., data -  ns1.fwdcdn.net. hostmaster.ukr.net. 2018080301 36000 3600 604800 86400
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 2, name - ukr.net., data -  64:ff9b::d42a:4cfd
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 3, name - ukr.net., data -  64:ff9b::d42a:4cfc

and generated AAAA record (for example):
;; ANSWER SECTION:
ukr.net.                86400   IN      AAAA    64:ff9b::d42a:4cfd
ukr.net.                86400   IN      AAAA    64:ff9b::d42a:4cfc

### Actual behaviour

You can see next lines, including last line with error record:
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 1, name - ukr.net., data -  ns1.fwdcdn.net. hostmaster.ukr.net. 2018080301 36000 3600 604800 86400
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 2, name - ukr.net., data -  64:ff9b::d42a:4cfd
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: result: id - 3, name - ukr.net., data -  64:ff9b::d42a:4cfc
Aug  9 00:07:31 dns64-host01 pdns_recursor[47696]: STL error (ukr.net/AAAA from 127.0.0.1): Trying to cast a lua variable from "nil" to "b"

and no generated AAAA response.

**Comment by zeha** [comment]
`postresolve` really needs a return value.
But this looks more like a support question and not a bug, which is what the GitHub tickets are meant for. Please see https://www.powerdns.com/opensource.html for how to reach the project via IRC or mailing list so we can help you out.
