### ISSUE TITLE
search-data API missing "max" query parameter

### ISSUE THREAD

**Issue by thechile** [PowerDNS/pdns#6840]
I was using the `GET /servers/{server_id}/search-data` endpoint and the documentation mentions the *max* query parameter. But it didn't work during my testing and when i looked it doesn't seem to be implemented. 

* https://github.com/PowerDNS/pdns/blob/master/pdns/ws-recursor.cc#L328
* https://doc.powerdns.com/authoritative/http-api/search.html

Maybe i'm looking in the wrong place or issuing the query wrong ? I was using:

`curl -s -H "X-API-Key: 123456" http://127.0.0.1:8081/api/v1/servers/localhost/search-data?q=abc.com&max=10`

**Comment by rgacogne** [comment]
You are looking at the implementation of the API in the recursor, while reading the documentation of the Authoritative Server.
The `max` parameter is implemented in the Auth, see https://github.com/PowerDNS/pdns/blob/master/pdns/ws-auth.cc#L1810

Also, you deleted the issue template so we have no idea what product or version you are using and therefore can't help you. Please don't do that.

**Comment by thechile** [comment]
OK sorry, that was stupid. Also, it works fine after i quoted the URL.. bash was interpreting the `&`. Silly mistakes.
