### ISSUE TITLE
Make Recursor more robust against misconfigured nameservers

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#685]
The Recursor stopps processing in case of "Refused". But why not asking the other nameservers of the domain before giving up?

Attached a patch to achieve this.

**Comment by Habbie** [comment]
@paddg any idea if this is still relevant today?

**Comment by paddg** [comment]
Hello Peter, please throw it away. For a long time there has not been a case where public resolvers have resolved while we have failed. Thanks!

**Comment by Habbie** [comment]
Thanks @paddg
