### ISSUE TITLE
DNSSEC with powerdns as SLAVE loses PRESIGNED on second / third / forth transfer

### ISSUE THREAD

**Issue by alexblhr** [PowerDNS/pdns#6852]
- Program: Authoritative
 - Issue type: Bug report

### Environment

 - Operating system: CentOS 6 , Debian 9.5
 - Software version: 4.1.3 , also with GIT latest
 - Software source: Repo for 4.1.3 , Repo for Git latest , + tried also to compile from GIT

### Steps to reproduce
1. Set PowerDNS with gmysql ( with gmysql-dnssec=yes )  as SLAVE to any DNSSEC signed zone master
2. Transfer the zone once by updating the SOA -> PREGISNED 1 is set into the database
3. Transfer the zone again by updating the SOA -> PRESIGNED is deleted from the database
Zone is now broken because its not longer containing DNSKEY/RRSIG records

Can reproduce 1/4 times

### Expected behaviour
DNSSEC transfers working with PRESIGNED

### Actual behaviour
PowerDNS loses PRESIGNED 1 which causes it to no longer process the zone as DNSSEC - deleting DNSKEY/RRSIG records for example

### Other information

I believe that maybe the issue is on this line

https://github.com/PowerDNS/pdns/blob/65ed9c6139776437df45f566ab32e4876e918ed4/pdns/slavecommunicator.cc#L488

Because hadPresigned is always true for PREGISNED 1 zones it always deletes the PRESIGNED 1 from the DB on SOA update

**Comment by alexblhr** [comment]
Well i must be wrong about which part of the code it is then

The zone is signed , that is not the case ... I sign it myself
I can't reproduce the issue with bind<->bind
NSEC records are always present

Transfer , DNSSEC works , PRESIGNED 1 present in DB :

```
Aug 13 22:34:57 testserver test[90163]: Domain 'test.com' is fresh, but RRSIGs differ, so DNSSEC is stale, serial is 2018080610
Aug 13 22:35:00 testserver test[90163]: Initiating transfer of 'test.com' from remote '192.168.1.2'
Aug 13 22:35:00 testserver test[90163]: Starting AXFR of 'test.com' from remote 192.168.1.2
Aug 13 22:35:00 testserver test[90163]: Adding NSEC3 hashed ordering information for 'test.com'
Aug 13 22:35:00 testserver test[90163]: Backend transaction started for 'test.com' storage
Aug 13 22:35:00 testserver test[90163]: AXFR done for 'test.com', zone committed with serial number 2018080610
```

Consecutive transfer, DNSSEC stops working , PRESIGNED 1 now deleted by PowerDNS from DB , what you might notice as interesting is that it says "our serial 0" I'm not sure if this is relevant , it also doesn't detect the different RRSIG records

```
Aug 13 22:36:24 testserver test[90163]: Domain 'test.com' is stale, master serial 2018080612, our serial 0
Aug 13 22:36:27 testserver test[90163]: Initiating transfer of 'test.com' from remote '192.168.1.2'
Aug 13 22:36:27 testserver test[90163]: Starting AXFR of 'test.com' from remote 192.168.1.2
Aug 13 22:36:27 testserver test[90163]: AXFR started for 'test.com'
Aug 13 22:36:27 testserver test[90163]: AXFR of 'test.com' from remote 192.168.1.2 done
Aug 13 22:36:27 testserver test[90163]: Backend transaction started for 'test.com' storage
Aug 13 22:36:27 testserver test[90163]: AXFR done for 'test.com', zone committed with serial number 2018080612
```

**Comment by rgacogne** [comment]
Are these traces from 4.1.3? And there was nothing between these two lines on the first trace?

```
Aug 13 22:35:00 testserver test[90163]: Starting AXFR of 'test.com' from remote 192.168.1.2
Aug 13 22:35:00 testserver test[90163]: Adding NSEC3 hashed ordering information for 'test.com'
```

If so, I'm missing something there. The first line is just before the call to `doAxfr()`, and we have a similar line right after which is not here. It might happen if we encountered an exception, but then we can't reach `Adding NSEC3 hashed ordering information for...`, or if the first call to `AXFRRetriever::getChunk()` return `false` but I don't see how that might happen either..

**Comment by alexblhr** [comment]
That is from GIT latest. As i said issue happens with both 4.1.3 and git latest
Is there any way to build PowerDNS with debug mode so it produces more info in the logs that the highest loglevel ?

**Comment by rgacogne** [comment]
You did not answer my second question, because even on master the trace doesn't look right.

**Comment by alexblhr** [comment]
Sorry for missing your second question
There is nothing between those lines related to the domain in question

Should there be anything and what is it missing ?
Im just grepping the logs grep "domain" /var/log/syslog and , loglevel=9 , and my SystemLogRateLimitInterval is 0 so no lines are being skipped by rsyslogd

**Comment by rgacogne** [comment]
The following lines should be there:
```
AXFR started for 'test.com'
AXFR of 'test.com' from remote 192.168.1.2 done
```

They are present in the second trace, and I just can't see how they can be missing from the first one.

**Comment by alexblhr** [comment]
I don't get how the missing lines from the first transfer are relevant when the first one is working and the second one isn't ?

**Comment by rgacogne** [comment]
It's relevant because we need to understand what's going on in order to help you, and right now it makes no sense to me, so I want to make sure I'm working with unedited logs, otherwise we are just wasting time. Please read https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/ if it doesn't make sense.

**Comment by alexblhr** [comment]
I do understand your open source support policy.
Logs are not edited. I have no clue why they are like that...
My question is legit - how tare they relevant , not why they are relevant.
You replied to why they are , not how.

**Comment by Habbie** [comment]
Does this problem still exist in 4.2.0-rc1 or today's master?

**Comment by Habbie** [comment]
closing this as there has been no response, and nobody else has mentioned seeing this problem.
