### ISSUE TITLE
Sometimes segmentation fault if starting with a faulty lua script

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#689]
Sometimes I get a segfault if I try to start pdns_recursor 3.5-rc1 (AND earlier) with a faulty lua script.

To force the error, simply type

```
echo x > test.lua
/usr/sbin//pdns_recursor --daemon=no --lua-dns-script=test.lua --threads=8
```

Try this many times and you will (hopefully) see.

My system is a SLES11-SP2 x86_64. The Recursor was built at OBS:
[https://build.opensuse.org/package/show?package=pdns-recursor&project=home%3Apaddg]

**Comment by ahupowerdns** [comment]
We're not going to address this in 3.x, in 4.x Lua has been changed so completely, and we haven't had any reports of such crashes, that I assume this has been solved.
