### ISSUE TITLE
ldap-dnssec parameter missing (DNSSEC support with LDAP backend)

### ISSUE THREAD

**Issue by hostingnuggets** [PowerDNS/pdns#6899]
Using PowerDNS 4.0.3 as authoritative server with an LDAP backend I have noticed that there is no such config parameter called `ldap-dnssec` analog to `gpgsql-dnssec` for a PostgreSQL backend.

Does this mean that DNSSEC with LDAP as backend is not supported?

If DNSSEC with LDAP backend is supported, is DNSSEC enabled by default? and if not how do I disabled it?

Sorry for all this questions but I could not find anything in the official docs...

**Comment by pieterlexis** [comment]
There is no DNSSEC suppor tin the LDAP backend. Please help us and @goestreicher by testing #6533.

**Comment by hostingnuggets** [comment]
@pieterlexis thank you for your fast answer. One more question: then if there is no DNSSEC support for the LDAP backend which I am using, how is it possible I get this DNSSEC related log entry from time to time:

`Should not get here (ftp.mydomain.tld|1): please run pdnsutil rectify-zone mydomain.tld`

As far as I understand it is not possible to run pdnsutil rectify-zone when using an LDAP backend.

**Comment by pieterlexis** [comment]
This seems like a suppor tissue, pleas eupdate to 4.1.4 and see if the problem persists. If it does, please take this to the mailinglists

**Comment by hostingnuggets** [comment]
Cheers!
