### ISSUE TITLE
Optimization of backend queries

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#691]
For the vast majority of queries, PacketHandler::getBestReferralNS()  goes for all subdomains between the query and the SOA looking for an NS entry and then assuming nothing is found, an ANY lookup is performed in the same way. Given that for most backends a lookup is expensive it would make sense to merge the two bits of code so that it looks something like the following pseudo code:

```
vector any_entry;
vector ns_entry;
do {
  if( any_entry )
    if( ns_entry = do_ns_query )
      break;
  else {
    any_entry = do_any_query;
    if( ns_entry = get_ns_entries( any_entry ) )
      break;
  }
} while(chopoff(subdomain) && not_reached_SOA)
```

Mark

**Comment by zeha** [comment]
This is kinda #9483?

**Comment by Habbie** [comment]
Indeed!
