### ISSUE TITLE
auth: truncated responses are not empty

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#6912]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When pdns_server decides that the answer section of a packet would not fit in the maximum response size (based on the EDNS bufsize [if present] and udp-truncation-threshold), it rolls back the last record added, and sets the TC flag. It then sends all the records that did fit - which clients will ignore. This wastes bandwidth.

(On a sidenote, the `20` in `if(pw.size() + 20U > (d_tcp ? 65535 : getMaxReplyLen())) { // 20 = room for EDNS0` appears to be wrong; without any options, the OPT RR is smaller; with options, like EDNS subnet, I suspect it could be bigger).

### Environment
 - Operating system: any
 - Software version: git master at c6420f2a62dc0e91a3b94cf28c148690e918de65
 - Software source: git, compiled

### Steps to reproduce
1. start the regression tests (I used `bind` mode here)
2. `dig  +bufsize=600 a toomuchinfo-b.example.com @127.0.0.1 -p 5300    +tries=1 +timeout=500 +ignore`

### Expected behaviour
An empty TC response is sent.

### Actual behaviour
A 582 bytes big TC response is sent.

### Other information
Truncation happens for bufsizes 863 and below. The response is 854 bytes, or 843 bytes without EDNS. 843+20=863, so for this query, the magic `20` above should have been `11`, which indeed is the minimal OPT RR size according to RFC6891.

In dnspacket.cc, around line 321, we see:
```
        if(pw.size() + 20U > (d_tcp ? 65535 : getMaxReplyLen())) { // 20 = room for EDNS0
          pw.rollback();
          if(pos->dr.d_place == DNSResourceRecord::ANSWER || pos->dr.d_place == DNSResourceRecord::AUTHORITY) {
            pw.getHeader()->tc=1;
          }
```

I think that when we set TC, we should be calling `truncate()` on `pw`, instead (or after) `rollback`. I did not test this change yet.

**Comment by dannybeut** [comment]
This has created issues for us when using Python clients. They are not as "smart" as most other DNS clients and they will not retry with TCP. I think the reason that records are returned even if the truncate bit is set is for backwards compatibility with these less robust clients that don't follow the "SHOULD"s in the RFC.

**Comment by Habbie** [comment]
Hi @dannybeut,

two things:
* you are responding on a closed ticket. Such replies, if not ignored at first, tend to never get answered
* this ticket is about the auth, which your Alpine clients are not (should not be, anyway) talking to.

If you have a real concern between Alpine and our Recursor, we're happy to discuss that (even if it's an Alpine issue, perhaps we can help), but would prefer to do it outside of GitHub tickets. You can find our IRC and mailing list details at https://www.powerdns.com/opensource.html

**Comment by dannybeut** [comment]
Thank you so much for the reply and for the help...I will address this issue through the preferable channels.
