### ISSUE TITLE
API bug with TXT records (spf, dkim, dmarc)

### ISSUE THREAD

**Issue by clusterx** [PowerDNS/pdns#6916]
PDNS server (latest)
Debian 9

When using webserver API and TXT records are added like SPF, DKIM or DMARC I see am error 500 in PHP and also a test with JQ shows:
parse error: Invalid numeric literal at line 1, column 9

this happens only with TXT records, I would like to use the API in whmcs but it does not work aslong valid TXT records exist.

**Comment by Habbie** [comment]
The error suggests you are sending invalid JSON. This does not sound like a bug in PowerDNS. Please see https://www.powerdns.com/opensource.html for various ways to get free, public support from us.
