### ISSUE TITLE
[Feature] Certbot Plugin+API for Letsencrypt wildcard domains.

### ISSUE THREAD

**Issue by RSpliet** [PowerDNS/pdns#6944]
- Program: ? (Authoritative, Recursor, dnsdist) 
 - Issue type: Feature request 

### Short description

It seems that letsencrypt/certbot has started supporting certs for wildcard domains if ownership of the domain can be proven through a DNS challenge/response. It would be nice for certbot to have a plugin that configures PowerDNS automatically with the right response, to easily automate the process of wildcard domain request/renewal. I presume this would require an API to allow certbot to communicate directly with PowerDNS or indirectly through poweradmin. Is this something that can be achieved with pdns?

### Usecase

I'd like to automate requesting wildcard domain certificate from letsencrypt through certbot, requiring me to prove ownership of the domain by means of a DNS challenge/response.

### Description

I'd like PowerDNS to expose an API that can be used by a (to be developed) certbot-dns-pdns plugin, which will allow me to automate the process of proving ownership of a domain to Letsencrypt. The exact procedure from the point of view of Letsencrypt is presumably not dissimilar to the "manual" method [described on the Certbot website](https://certbot.eff.org/docs/using.html#dns-plugins).

**Comment by mnordhoff** [comment]
You should be able to do this today using [RFC 2136 dynamic updates](https://tools.ietf.org/html/rfc2136), [Certbot's certbot-dns-rfc2136 plugin](https://certbot-dns-rfc2136.readthedocs.io/en/latest/) and [PowerDNS's dynamic update support](https://doc.powerdns.com/authoritative/dnsupdate.html).

Someone could also write a Certbot plugin for [PowerDNS's HTTP API](https://doc.powerdns.com/authoritative/http-api/index.html) but it's not necessary.

**Comment by zeha** [comment]
PowerDNS Auth has an API today that lets you create records as needed, that should just work.

This looks more like a support question and not a bug, which is what the GitHub tickets are meant for. Please see https://www.powerdns.com/opensource.html for how to reach the project via IRC or mailing list so we can help you out.

**Comment by Approach** [comment]
Well, GitHub tickets are meant for bugs and feature requests both; among other things

**Comment by Habbie** [comment]
> Well, GitHub tickets are meant for bugs and feature requests both; among other things

Yes, but this ticket is neither. We already have the requested feature.

**Comment by Approach** [comment]
eeeeh I wouldn't say so. it should really be a command in pdnsutil or pdns_control imo.  pdns only has the ability to let someone implement this with specific knowledge. i for one request this feature be built-in as other methods have been inconsistent across platform and it would be trivial for powerdns. the vast majority of those who want a data-driven authoritative DNS server will want this feature as an optional flag during installation

**Comment by Habbie** [comment]
pdnsutil, like the REST API, also has the needed functionality already.

I am closing conversation on this ticket; again, please use our mailing list or IRC channel if you need help.
