### ISSUE TITLE
4.0.4 recursor, SERVFAIL debugging

### ISSUE THREAD

**Issue by bitsofinfo** [PowerDNS/pdns#6947]
Running pdns-recursor 4.0.4

In the web interface UI we see many "Servfail Domain" entries listed
with counts

For some of these names/domains we have set trace-regex from the command
line.

The issue is that we can find nothing in the logs showing any SERVFAIL
errors, but only successful cache hits and lookups yet this number
increments.

How can we get to the bottom of this or see the reasons and debug
information that is generating these SERVFAILs?

**Comment by Habbie** [comment]
Hello,

this looks like a support question, not a bug report. Please see https://www.powerdns.com/opensource.html to get help on our mailing list or IRC channel.
