### ISSUE TITLE
rec: Adding NTA doesn't invalidate existing cache

### ISSUE THREAD

**Issue by giganteous** [PowerDNS/pdns#6949]
- Program: Recursor
 - Issue type: Feature request

### Short description
Call a cleanup hook when the NTA's change using:
 * rec_control add_nta foo.bar.edu
 * rec_control reload-lua-config

### Usecase
Currently I need to know what domains I added to the config when reloading the lua config, or just bluntly call a loop around all my negative anchored domains.

### Description
Chat from IRC:
```irc
09:16|     kaisan: note, interactions with adding NTA and invalidating existing cache hasn't been optimized it seems.
09:18|     Habbie: ah
09:24|     lieter: we don't clean the cache for that name?
09:24|     Habbie:   broadcastAccFunction<uint64_t>(boost::bind(pleaseWipePacketCache, who, true));
09:24|     Habbie: but no pleaseWipeCache
09:30|     Habbie: also no automatic dnsdist-side cleanup, i suppose
```

**Comment by rgacogne** [comment]
It looks like we only clear the packet cache but not the record cache when adding or removing (N)TA indeed.
