### ISSUE TITLE
dnsdist: detached signature created by unlisted key

### ISSUE THREAD

**Issue by tcely** [PowerDNS/pdns#6953]
- Program: dnsdist
 - Issue type: Bug report

### Short description

https://dnsdist.org/install.html lists four keys. None of these are the key used to create the detached signature.

**Comment by Habbie** [comment]
Just to be sure, what key/fingerprint are you seeing for which signature?

**Comment by tcely** [comment]
```
gpg: key 0xA208ED4F8AF58446: public key "Remi Gacogne <remi.gacogne@powerdns.com>" imported
gpg: Good signature from "Remi Gacogne <remi.gacogne@powerdns.com>" [unknown]
gpg: aka "Gacogne, Remi <remi.gacogne@open-xchange.com>" [unknown]
Primary key fingerprint: D630 0CAB CBF4 69BB E392 E503 A208 ED4F 8AF5 8446
gpg: binary signature, digest algorithm SHA512, key algorithm rsa2048
```

Build log: https://hub.docker.com/r/tcely/dnsdist/builds/bl2noud7yzzgssmcsmlahxw/

**Comment by zeha** [comment]
@rgacogne key is also missing from the linked powerdns-keyblock.asc.

**Comment by rgacogne** [comment]
The doc is wrong, it lists the keys allowed to sign releases for the authoritative server and the recursor, which mine is not, and I'm pretty sure I signed every dnsdist releases.

**Comment by tcely** [comment]
@rgacogne `dnsdist-1.0.0` was signed using RSA key `0x5E50715BF2FFE1A7`. All the later versions are signed using RSA key `0xA208ED4F8AF58446`.

The easiest thing to do is just add the missing key to that page and the linked `powerdns-keyblock.asc` file.
