### ISSUE TITLE
api return error

### ISSUE THREAD

**Issue by liangmanxing** [PowerDNS/pdns#6955]
I use the API to add domian(pdns version is 4.1.0)
The information submitted is as follows:
Always return the field name: name does not exist

headers={'x-api-key': "manxing"}
url='http://192.168.3.111:8081/api/v1/servers/localhost/zones'
pdns_data={"rrsets":[{"name":"test.com.","kind":"Native","masters":[],"nameservers":[],"soa_edit_api":"","account":""}]}
request_host= requests.post(url=url,headers=headers,data=json.dumps(pdns_data))
print request_host.text

result is like that:
[root@pgsql-01 pdns_api]# ./python_web.py 
{"error": "Key 'name' not present or not a String"}
,,,,,,,,sos,,,,,,,,,ask for help,,,,

**Comment by pieterlexis** [comment]
You are indeed not sending a proper zone object (which needs a 'name' field). See the [docs](https://doc.powerdns.com/authoritative/http-api/zone.html#zone) for more info.

It also seems that you have not read or used the provided template, this is a support question that should be taken to the [mailinglist](https://www.powerdns.com/mailing-lists.html) and is not a bug.

**Comment by liangmanxing** [comment]
Yes, that's my use problem
I want to ask, where can I find the template?
I'm done with it：https://doc.powerdns.com/authoritative/http-api/zone.html
