### ISSUE TITLE
dnsdist: add scratch space for mutating TCP responses

### ISSUE THREAD

**Issue by gibson042** [PowerDNS/pdns#6964]
- Program: dnsdist
 - Issue type: Feature request

### Short description
When a TCP query is received, dnsdist allocates a buffer for it with 512 bytes of scratch space at the end [to support in-place mutation](https://github.com/PowerDNS/pdns/blob/6cb39a3855b3a1d9d0a65c5999e9ebd044b7f8fb/pdns/dnsdist-tcp.cc#L316-L318). But when a _response_ is received, the buffer defaults to [having no headroom at all](https://github.com/PowerDNS/pdns/blob/6cb39a3855b3a1d9d0a65c5999e9ebd044b7f8fb/pdns/dnsdist-tcp.cc#L563-L570). Since response mutation is also a valid use of this software, I think the two cases should be handled symmetrically.

This is not an issue for UDP traffic, in which the buffer is always 4096 bytes.

### Usecase
Add data to TCP responses before sending them out.

### Description
Reserve 512 bytes of space in every TCP response buffer for adding data, as already happens in the request buffer.

**Comment by rgacogne** [comment]
I'm not opposed to the idea but I'm not sure we currently do have any code adding something to a response. Do you have something specific in mind?

**Comment by gibson042** [comment]
Not directly, but [dnsdist-lua-bindings-dnsquestion.cc](https://github.com/PowerDNS/pdns/blob/6cb39a3855b3a1d9d0a65c5999e9ebd044b7f8fb/pdns/dnsdist-lua-bindings-dnsquestion.cc#L101) suggests an intention to have DNSResponse functionally inherit from DNSQuestion, which supports adding EDNS Client Subnet. And I could imagine using response mutation for things like TSIG termination or adding per-hop EDNS options.

**Comment by rgacogne** [comment]
Right, I don't really see a scenario where adding ECS to a response would make sense, but fixing TSIG or some EDNS option might indeed be a nice idea at some point.

**Comment by rgacogne** [comment]
https://github.com/PowerDNS/pdns/pull/9616 will fix this as a nice side-effect.
