### ISSUE TITLE
Update debs for raspbian

### ISSUE THREAD

**Issue by scolby33** [PowerDNS/pdns#6978]
- Program: Authoritative, dnsdist 
 - Issue type: Feature request 

### Short description

The Raspbian repo still only has pdns 4.1.3 and dnsdist 3.1.0 available.

I attempted to look through the Buildbot history to see what has happened, but I'm not familiar enough with that system to make an effective search for the particular release build.

### Environment

 - Operating system: Raspbian Stretch but using the PDNS Jessie repos (#5708)
 - Software version: pdns 4.1.3; dnsdist 3.1.0 I'd like to upgrade
 - Software source: PowerDNS repository

### Expected behaviour

The newest released version be available in the repositories.

### Actual behaviour

Only old versions available

**Comment by pieterlexis** [comment]
Looks like those builds were not finished when these packages were published and we forgot, I'll update them now

**Comment by scolby33** [comment]
Thanks! Just out of my own curiosity, how did you find the relevant builds on builder.powerdns.com?

**Comment by pieterlexis** [comment]
https://downloads.powerdns.com/autobuilt_browser/# has them

**Comment by pieterlexis** [comment]
Done! Thanks for reporting.
