### ISSUE TITLE
GeoDNS backend is not working

### ISSUE THREAD

**Issue by rohith7171** [PowerDNS/pdns#6983]
Dear Sir,

I am implementing a DNS server. I choose powerDNS 4.1.4 as it has following cool features.

 1) Poweradmin web interface: 
2) Choice of back-end: 
3) Choice of replication: 
4) Ability to make alterations without restarting:
5) GeoIP backend for GeoDNS: 

My plan is to setup mysql backedn and geodns backend together, so that some required domains can use geodns backend. 
I have done above settings today. Mysql backed works perfectly. But Geodns backend is not working.
**Here is my issue.**

I have setup one domain for GeoDNS backend as follows.
Need to resolve mydomain.com to a.b.c.d for requests coming from India and to e.f.g.h for request coming from USA.  Request from other country must go to  w.x.y.z.
However when I request from IN or USA, it is going to w.x.y.z. That means all requests are going to w.x.y.z.

**PowerDNS(4.1.4) configuration file for GeoDNS**

launch=geoip,gmysql
geoip-database-files=/usr/share/GeoIP/GeoIP.dat
#geoip-database-file6
geoip-zones-file=/etc/powerdns_geo/geo.yml
gmysql-host=localhost
gmysql-user=powerdns_user
gmysql-password=changeme
gmysql-dbname=powerdns

**Geoip zone file**
cat /etc/powerdns_geo/geo.yml
domains:
- domain: mydomain.com
  ttl: 300
  records:
    mydomain.com:
      - soa: ns1.roothands.com hostmaster.mydomain.com 2014090125 7200 3600 1209600 3600
      - ns: ns1.mydomain.com     
      - ns: ns2.mydomain.com
      - mx: 10 mx.mydomain.com
      -  a: w.x.y.z

    IND.AS.service.mydomain.com:
      -  a: a.b.c.d
      

    USA.NA.service.mydomain.com:
      -  a: e.f.g.h

  services:
    service.mydomain.com: '%co.%cn.service.mydomain.com'

I think IND.AS.service.mydomain.com and USA.NA.service.mydomain.com are acting like a subdomain.

Kindly help me to resolve this issue as this is very critical task for me. Please please please!!!

Thanks

**Comment by Habbie** [comment]
Hello,

this looks like a support question. We do not take support questions as GitHub tickets. Please see https://www.powerdns.com/opensource.html to find us on IRC or our mailing lists. When you do, please also first read https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/
