### ISSUE TITLE
IXFRDist Features

### ISSUE THREAD

**Issue by oliken** [PowerDNS/pdns#6992]
Hi!
Do you plan to develop this features?:

 

1.    ixfrdist NOTIFY support (Catch DNS NOTIFY from master and update AFXR/Send DNS NOTIFY to some hosts)
2.    ixfrdist TSIG support (between master and ixfrdist and between ixfrdist and some hosts)
3.    ixfrdist refresh time vs actual SOA expire only

This features may permits to replace the limitation of PowerDNS to send IXFR.

**Comment by pieterlexis** [comment]
Hi,

These ideas have been discussed. Can you please open a separate issue for each using the feature request template so this can be tracked?
