### ISSUE TITLE
Ixfrdist Notify Support

### ISSUE THREAD

**Issue by oliken** [PowerDNS/pdns#6994]
- Program: ixfrdist
 - Issue type: Feature request

### Short description
It would be nice if IXFRDist support NOTIFY, Catch DNS NOTIFY from master and update AFXR/Send DNS NOTIFY to some hosts.

### Usecase
When ixfrdist is use with auth server, this feature permit to initiate AXFR only when necessary.

### Description
ixfrdist can catch NOTIFY from master/auth, and can initiate AXFR transfer zone and SOA check only when there is modification on master server vs check SOA expiration check only.
This feature may permit to replace the limitation of PowerDNS to send IXFR.

**Comment by Woet** [comment]
Seems like you skipped two sections for the feature request template.

```
<!--
Use the part below to file a feature request and delete the bug report part above.
-->
### Usecase
<!-- Tell what you're trying to achieve, without describing _what_ the requested feature should do -->

### Description
<!-- Describe as extensively as possible what you want the software to do -->
```

**Comment by isnuryusuf** [comment]
### Usecase


### Description
- currently ixfrdist doesnt support automatic zone update after get notify from master, we need to restart ixfrdist service to get complete up-to-date zone record from master, cause every we start ixfrdist, it will check serial on master and compare to local-copy. so every time serial has update, we need to restart the ixfrdist service

- after ixfrdist have same zone record and serial from master, they cannot notify slave member, at the slave side, we need to restart the pdns-slave/other dns service, so slave can get update from ixfrdist

if we have scenario like this
- pdns master with mysql backend and milion of record
- ixfrdist outsite pdns master server to distribute record using IXFR
- lot of pnds slave connecting to ixfrdist server

> lot of pdns slave direct connecting to pdns master where handle milion of record and pdns currently doenst support IXFR transfer, it will consume lot of Bandwidth and High SQL query (at the database backend)
- the main goal is to make PDNS master to support IXFR, but ixfrdist is nice when can translate from AXFR to IXFR to lot of PDNS slave

**Comment by Habbie** [comment]
handling of incoming notify is done in #13322
