### ISSUE TITLE
force C++11 compiler flags

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#7041]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Robustness

### Short description
#7040 fixes breakage resulting from GCC supporting C++14, while compiling against a Boost version that was not ready for that. Forcing GCC to C++11 works around that breakage. Given that this source tree is C++11 and not 14, we should always explicitly compile as C++11 so we do not accidentally introduce any C++14 features.

One suggested approach: ax_cxx_compile_stdcxx_11.m4 currently leaves out C++11 flags if the compiler supports C++11 without them. We should make it add the flags (and then still test) explicitly.

**Comment by pieterlexis** [comment]
Or perhaps only force them on older boost?

**Comment by Habbie** [comment]
> Or perhaps only force them on older boost?

That doesn't prevent us from accidentally introducing C++14 stuff.

**Comment by omoerbeek** [comment]
Obsolete
