### ISSUE TITLE
pdns-builder Ubuntu packages put ixfrdist service in pdns-server, not pdns-ixfrdist

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#7061]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

The new pdns-builder packages put the ixfrdist systemd service files in the `pdns-server` package, but ifxrdist itself is in the `pdns-ixfrdist` package.

If you install `pdns-server` but not `pdns-ixfrdist`, the service will get enabled and fail to start because `/usr/bin/ixfrdist` doesn't exist.

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: 0.0.15270+0.g5121e0a434-1pdns.xenial
 - Software source: PowerDNS repository 

### Steps to reproduce

1. In my case, `sudo apt full-upgrade`. I assume `sudo apt install pdns-server` would do it.
2. `sudo cat /var/log/syslog`. :P

### Expected behaviour

No `ixfrdist` service installed.

### Actual behaviour

`ixfrdist` service installed.

    $ dpkg -S ixfrdist
    pdns-server: /lib/systemd/system/ixfrdist.service
    pdns-server: /lib/systemd/system/ixfrdist@.service

### Other information

Logs:

    Oct 12 14:41:36 jane systemd[1]: Started PowerDNS IXFR Distributor.
    Oct 12 14:41:36 jane ixfrdist[8448]: ixfrdist.service: Failed at step EXEC spawning /usr/bin/ixfrdist: No such file or directory
    Oct 12 14:41:36 jane systemd[1]: ixfrdist.service: Main process exited, code=exited, status=203/EXEC
    Oct 12 14:41:36 jane systemd[1]: ixfrdist.service: Unit entered failed state.
    Oct 12 14:41:36 jane systemd[1]: ixfrdist.service: Failed with result 'exit-code'.
    Oct 12 14:41:37 jane systemd[1]: ixfrdist.service: Service hold-off time over, scheduling restart.
    Oct 12 14:41:37 jane systemd[1]: Stopped PowerDNS IXFR Distributor.

**Comment by mnordhoff** [comment]
This also happens on Debian.

**Comment by pieterlexis** [comment]
closed in #7085
