### ISSUE TITLE
LDAP backend rRSIGRecord ignored

### ISSUE THREAD

**Issue by sooslaca** [PowerDNS/pdns#7063]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

if I add an rRSIGRecord into LDAP database and using PDNS with LDAP as a backend, these records are not coming through. Neither in AXFR or into specific query like
```
dig A example @192.168.1.1 +noadditional +dnssec +multiline
```

### Environment

 - Operating system: Ubuntu 18.04LTS
 - Software version: 4.1.4
 - Software source: PowerDNS repository 

### Steps to reproduce

1. Add an rRSIGRecord to LDAP
2. do an axfr for the zone

### Expected behaviour

See RRSIG in dig output

### Actual behaviour

Everything else comes through except RRSIG

### Other information

I followed instructions here https://doc.powerdns.com/md/authoritative/dnssec/#From-existing-DNSSEC-non-PowerDNS-setups-pre-signed
It mentions that I need to set zone to pre-signed but obviously as LDAP backend does not support DNSSEC it's failing which is expected I think.
Can we make backend not support DNSSEC to already be pre-signed?

### Usecase

DNSSEC with LDAP backend, I would calculate keys and RRSIGs manually.

**Comment by Habbie** [comment]
> Can we make backend not support DNSSEC to already be pre-signed?

No, sorry; even to support just presigned, a lot of extra work is needed in a backend.

Please see if https://github.com/PowerDNS/pdns/pull/6533 makes this work for you. If it does not, please comment there. Closing this.

**Comment by sooslaca** [comment]
I might not get what pre-signed is.
All I would like to see is and LDAP attribute to come as a DNS record. Is that the one?
Like and aRecord as become DNS A record.

Checked the PR, it’s only ‘tree’ mode as I see. Doesn’t work for me :(

**Comment by Habbie** [comment]
> I might not get what pre-signed is.

Pre-signed means the signatures are in the database, instead of PowerDNS calculating them 'live'.

Note that we generally do not respond to questions on closed tickets; I'm closing conversation on this ticket now to make that extra clear. You are welcome on our IRC channel or mailing lists via https://www.powerdns.com/opensource.html
