### ISSUE TITLE
pdns-builder Ubuntu package upgrade: dpkg warning: unable to delete /etc/insserv.d

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#7066]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

The older repo.powerdns.com packages create the file `/etc/insserv.d/pdns-server `. When upgrading to a pdns-builder package, the directory and file aren't deleted, and the warning "`dpkg: warning: unable to delete old directory '/etc/insserv.d': Directory not empty`" is printed.

Ubuntu's 4.0.0~alpha2-3build1 package doesn't create the file.

A fresh install of 0.0.15270+0.g5121e0a434-1pdns.xenial doesn't create the file.

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: Upgrading from 0.0.2463gc40b447-1pdns.xenial to 0.0.15270+0.g5121e0a434-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce

1. `sudo apt install ./pdns-server_0.0.2463gc40b447-1pdns.xenial_amd64.deb`
2. Enable PowerDNS repository
3. `sudo apt full-upgrade`

### Expected behaviour

No warning to be displayed, maybe `/etc/insserv.d` and `/etc/insserv.d/pdns-server` to be deleted.

### Actual behaviour

The directory and file are not deleted, the warning is displayed. :P

### Other information

```
$ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libbotan-1.10-1 liblua5.3-0
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  pdns-backend-bind
The following packages will be upgraded:
  pdns-server
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,054 kB of archives.
After this operation, 45.1 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://repo.powerdns.com/ubuntu xenial-auth-master/main amd64 pdns-server amd64 0.0.15270+0.g5121e0a434-1pdns.xenial [1,961 kB]
Get:2 http://repo.powerdns.com/ubuntu xenial-auth-master/main amd64 pdns-backend-bind amd64 0.0.15270+0.g5121e0a434-1pdns.xenial [92.4 kB]
Fetched 2,054 kB in 13s (154 kB/s)
(Reading database ... 91571 files and directories currently installed.)
Preparing to unpack .../pdns-server_0.0.15270+0.g5121e0a434-1pdns.xenial_amd64.deb ...
Removing unchanged configuration file /etc/default/pdns
Removing unchanged configuration file /etc/powerdns/pdns.conf
Removing unchanged configuration file /etc/powerdns/pdns.d/pdns.local.conf
Removing unchanged configuration file /etc/powerdns/pdns.d/pdns.simplebind.conf
Unpacking pdns-server (0.0.15270+0.g5121e0a434-1pdns.xenial) over (0.0.2463gc40b447-1pdns.xenial) ...
dpkg: warning: unable to delete old directory '/etc/insserv.d': Directory not empty
Selecting previously unselected package pdns-backend-bind.
Preparing to unpack .../pdns-backend-bind_0.0.15270+0.g5121e0a434-1pdns.xenial_amd64.deb ...
Unpacking pdns-backend-bind (0.0.15270+0.g5121e0a434-1pdns.xenial) ...
Processing triggers for systemd (229-4ubuntu21.4) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up pdns-server (0.0.15270+0.g5121e0a434-1pdns.xenial) ...
Installing new version of config file /etc/init.d/pdns ...
Setting up pdns-backend-bind (0.0.15270+0.g5121e0a434-1pdns.xenial) ...
Processing triggers for systemd (229-4ubuntu21.4) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for pdns-server (0.0.15270+0.g5121e0a434-1pdns.xenial) ...
```

```
$ ll /etc/insserv.d/pdns-server 
-rw-r--r--  1 root root   28 Sep 30 10:57 pdns-server
$ cat /etc/insserv.d/pdns-server 
$named +pdns +pdns-recursor
```

If you install 0.0.2463gc40b447-1pdns.xenial and then `sudo apt purge pdns-server`, the directory and file are deleted. If you instead `sudo apt remove pdns-server`, they're not.

**Comment by mnordhoff** [comment]
On Debian 9, this also happens:

    Unpacking pdns-server (0.0.15270+0.g5121e0a434-1pdns.stretch) over (0.0.2463gc40b447-1pdns.stretch) ...
    dpkg: warning: unable to delete old directory '/etc/resolvconf/update.d': Directory not empty
    dpkg: warning: unable to delete old directory '/etc/resolvconf': Directory not empty
    dpkg: warning: unable to delete old directory '/etc/insserv.d': Directory not empty

**Comment by pieterlexis** [comment]
it looks like subsequent updates don't show this message

**Comment by mkddas76** [comment]
Unpacking pdns-server (0.0.15270+0.g5121e0a434-1pdns.stretch) over (0.0.2463gc40b447-1pdns.stretch) ...
dpkg: warning: unable to delete old directory '/etc/resolvconf/update.d': Directory not empty
dpkg: warning: unable to delete old directory '/etc/resolvconf': Directory not empty
dpkg: warning: unable to delete old directory '/etc/insserv.d': Directory not empty

@same problem sowing my kali pc, anyOne send me the solution..

**Comment by SullivanKnox** [comment]
> 976 77 47 2
> 
> Unpacking pdns-server (0.0.15270+0.g5121e0a434-1pdns.stretch) over (0.0.2463gc40b447-1pdns.stretch) ... dpkg: warning: unable to delete old directory '/etc/resolvconf/update.d': Directory not empty dpkg: warning: unable to delete old directory '/etc/resolvconf': Directory not empty dpkg: warning: unable to delete old directory '/etc/insserv.d': Directory not empty
> 
> @same problem sowing my kali pc, anyOne send me the solution..

Did you find a fix?
