### ISSUE TITLE
Add "hidden" DNSKEY type

### ISSUE THREAD

**Issue by RobinGeuze** [PowerDNS/pdns#7079]
- Program: Authoritative
 - Issue type: Feature request 

### Short description
For DNSSEC Algorithm rollovers it is necessary to be able to add a DNSKEY to sign the zone with that does not yet appear in the actual zone yet. Thus it would be nice to add a hidden DNSSEC key.

### Usecase
I would like to be able to rollover to a new algorithm without having to go insecure.

### Description
I want to be able to add a DNSKEY to a zone without it appearing in the zone but that is used for signing the zone.

**Comment by Habbie** [comment]
As @RobinGeuze has opened a PR for this himself, I'll close this.
