### ISSUE TITLE
Build process hard requires man pages?

### ISSUE THREAD

**Issue by akamensky** [PowerDNS/pdns#7102]
- Program: Authoritative
 - Issue type: Bug report `(I guess it is bug report see below why)`

### Short description
When building without virtualenv installed the configure show following warning:
```
checking for virtualenv... no
configure: WARNING: virtualenv is missing, unable to build manpages.
```
And the first thing it does is fail build because no virtualenv. It either should SKIP man pages build if no virtualenv detected or configure should FAIL if there is no virtualenv (1st is more sane solution as not everyone wants/needs spend half an hour building man pages with python, on my machine it is by far longest part of build)

### Environment
 - Operating system: Alpine
 - Software version: git tip
 - Software source: git repo

### Steps to reproduce
1. Build on machine without virtualenv

### Expected behaviour
Configure passes and build passes

### Actual behaviour
Configure passes, build fails

**Comment by pieterlexis** [comment]
Hi!

This is indeed expected behaviour. To prevent accidentally creating a source tarball without manpages. The [README](https://github.com/PowerDNS/pdns#compiling-authoritative-server) also mentions the need for virtualenv.

As a workaround, it is possible to run `make -C ext; make -C pdns`.
