### ISSUE TITLE
dnsdist.init.centos6 file is useless since dnsdist 1.3.0

### ISSUE THREAD

**Issue by lehha** [PowerDNS/pdns#7124]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
file dnsdist.init.centos6 doesnt work correctly in 1.3.2:
> Starting dnsdist.../usr/bin/dnsdist: invalid option -- 'd'
> Starting dnsdist.../usr/bin/dnsdist: invalid option -- 'p'

After removing them from init.d script, dnsdist cant run in daemon mode - him wrote on screen and doesnt deattach from terminal

### Environment

 - Operating system: CentOS release 6.10 (Final)
 - Software version: dnsdist 1.3.2
 - Software source: PowerDNS repository

### Steps to reproduce
1. install from repo.powerdns.com
2. wget https://raw.githubusercontent.com/PowerDNS/pdns/master/pdns/dnsdistdist/contrib/dnsdist.init.centos6
3. try to run that

### Expected behaviour
run dnsdist in background

### Actual behaviour
Him run in foreground:
> /etc/init.d/dnsdist start
> Starting dnsdist...Added downstream server 127.0.0.1:54
> Listening on 0.0.0.0:53
> dnsdist 1.3.2 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
> ACL allowing queries from: 0.0.0.0/0
> Console ACL allowing connections from: 127.0.0.1/8, ::1/128
> Marking downstream local (127.0.0.1:54) as 'up'
> > Webserver launched on 0.0.0.0:8083

**Comment by Habbie** [comment]
daemon support was removed from dnsdist some time ago - apparently we forgot to remove or adjust `contrib/dnsdist.init.centos6`. Is there any reason you cannot use the upstart service definition?

**Comment by lehha** [comment]
It will be cool if script for upstart will be in repository.

**Comment by Habbie** [comment]
> It will be cool if script for upstart will be in repository.

The upstart file is in the package you installed. You can also see it here: https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdistdist/contrib/dnsdist.upstart.conf

**Comment by lehha** [comment]
Wow! I've see him, works fine! Thanks!

**Comment by Habbie** [comment]
Ok! I'm hijacking this ticket for cleanup of dnsdist.init.centos6 then.

**Comment by pieterlexis** [comment]
> Ok! I'm hijacking this ticket for cleanup of dnsdist.init.centos6 then.

I _think_ we switched to upstart in master, please check before releasing dnsdist 1.3.4

**Comment by rgacogne** [comment]
Closing as I believe this has been fixed.
