### ISSUE TITLE
database inconsistent eventually

### ISSUE THREAD

**Issue by urajio** [PowerDNS/pdns#7136]
- Program: Authoritative
 - Issue type: Bug report

### Short description

In our organization, the database is updated every few minutes. This process changes the id of almost all entries.
As far as I understand, one DNS request causes two SQL requests, one looking for the domain id in the domain table, the second looking for a record for this id in the records table.
Sometimes the database is updated between these two SQL requests, and if the domain id is changed, the second request does not find a record. This result is cached and for some time all clients receive a NXDOMAIN.

### Environment

 - Operating system: Centos 7
 - Software version: PowerDNS Authoritative Server 4.1.4, PostgreSQL 10
 - Software source: PowerDNS repository

**Comment by ahupowerdns** [comment]
Even completely disabling the query cache is no guarantee the ID won't change in the middle of a lookup. So I don't think there is anything you could do to make this safe. This may also happen over different database connections, so even if you had some kind of transaction open it may not be as consistent as you want it to be.

**Comment by urajio** [comment]
Can you do this in one SQL query? Or procedure?

**Comment by Habbie** [comment]
> Can you do this in one SQL query? Or procedure?

Not without rewriting half of PowerDNS. We suggest changing your import flow to keep the IDs stable. If you want to discuss more, please reach out via IRC or our mailing lists, details are at https://www.powerdns.com/opensource.html
