### ISSUE TITLE
No such file or directory error when installing pdns-recursor w/ masked service

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#7144]
- Program: Recursor
 - Issue type: Bug report

### Short description
error during installation w/ masked service

### Environment
 - Operating system: 
Ubuntu 18.04.1 LTS

 - Software version: 
4.1.4-1pdns.bionic

 - Software source:
        500 http://repo.powerdns.com/ubuntu bionic-rec-41/main amd64 Packages

### Steps to reproduce
1. `systemctl mask pdns-recursor`
2. `apt install pdns-recursor`

### Expected behaviour
Stuff, but no "No such file or directory" messages

### Actual behaviour
```
Failed to preset unit: Unit file /etc/systemd/system/pdns-recursor.service is masked.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on pdns-recursor.service: No such file or directory
```

Note: the first line seems more or less reasonable, the second line feels less reasonable.

### Usecase
I was running dnsmasq on 127.1 and didn't want pdns-rec to start right away -- I wanted to check its configuration, stop dnsmasq, and start pdns-rec in a controlled manner.

### Description
Not trigger `error: ...` messages

@pieterlexis / @zeha

**Comment by pieterlexis** [comment]
Soem notes: we use `dh-systemd` and don't do any other service tricks in postinst.

**Comment by zeha** [comment]
@zeha: I wanted to have a look at the `deb-systemd-helper` if this is a known issue and/or maybe fixed in newer versions.

**Comment by jsoref** [comment]
Signs that samba has worked around this:
https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1610361
https://salsa.debian.org/samba-team/samba/commit/61eaeba2a7a2df61b681b4ea545811569de421d0

I can't find any signs that this was usefully reported to debian helpers...

**Comment by omoerbeek** [comment]
Closed for lack of activity. Please re-open if needed.
