### ISSUE TITLE
Problem with dnsmessage.proto

### ISSUE THREAD

**Issue by makoa12** [PowerDNS/pdns#7154]
### Short description

I want to send logs from pdns-recursor (4.1) to an external system. I've learned that I may can do this by using `protobufServer`. I already have set up a lua configuration file and can receive data at the target system, but only in a binary format, "described" [here](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsmessage.proto).

### Usecase

I want that data logged in a database in a human readable format. Before I can do that, I need to understand and parse that data. All I have is [this](https://github.com/PowerDNS/pdns/blob/master/pdns/dnsmessage.proto) "description". I have 190 bytes per log entry and a really hard time to get something out of it. The format description defines some fields as `bytes`. That implies that I have to deal with an array of `byte`. But there is no information about how many bytes!

### Description

Example:

```
[...]
required Type type = 1;
optional bytes messageId = 2;      // UUID, shared by the query and the response
optional bytes serverIdentity = 3; // ID of the server emitting the protobuf message
optional SocketFamily socketFamily = 4;
[...]
```

- `type`: For all I know, this could be 1 byte, or 2. I don't know that.
- `messageId`: The type is `bytes`, but at least the comment mentions "UUID", so this might be 16 bytes?
- `serverIdentity`: The type is defined as `bytes`. I'm completely lost here. How many bytes? Where begin the next field `socketFamily`?
- `socketFamily`: Same problem as with `type`. I don't know how much bytes are used by enums.

The next problem is, that I don't know the values for all the enum constants.

Example:

```
enum Type {
    DNSQueryType = 1;
    DNSResponseType = 2;
    DNSOutgoingQueryType = 3;
    DNSIncomingResponseType = 4;
}
```

The first byte of my 190 byte message is `0x00`. The enum `Type` doesn't define a value with the ordinal `0`. So I assume the values in the format definition are just (dummy) increments, starting from `1`? Even if I assume that an enum value uses 2 bytes, then I have the value `0x0049` (`73`). Same problem: the format description defines the ordinals `1`, `2`, `3`, `4`, but no `73`.

From my perspective, this look more like a documentation issue. But if there is a tool or a script or something else that already can parse that binary block into something more readable, that's also fine by me.

Right now I'm unable to implement that external logging because the format description causes a lot of questions?

Am I missing something?

**Comment by Habbie** [comment]
The format description is supposed to be compiled by `protoc` or consumed by a Protobuf-compatible library.

Closing this as it is not a problem report. We're happy to help you out via IRC or our mailing lists - find details at https://www.powerdns.com/opensource.html

**Comment by Habbie** [comment]
By the way, this might help a bit: https://github.com/PowerDNS/pdns/blob/master/contrib/ProtobufLogger.py
