### ISSUE TITLE
dnsdist: health-check using icmp echo

### ISSUE THREAD

**Issue by 1848** [PowerDNS/pdns#7163]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Add option for dnsdist to do health checks using icmp echo requests

### Usecase
Allow more generic health checking (maybe with additional features, see below)

### Description
I have this feature working on my fork. So this is rather a question if this is useful in general.
If so I will do some code cleanups (C dev here, need to make code more C++-like) and create a PR for this.

Idea is as follows.
Create a new server like:
`newServer({ checkMethod="ping", cm_ping_set_weight=true, cm_ping_weight_mul=2, cm_ping_weight_base=100,[snip]`
Please note that those option names are placeholders ;)

upCheck() will now check for checkMethod(). If its not set to "ping" it will do the usual dns lookup.
Otherwise it will "ping" the remote server.
Additional feature: Set server weight base on rtt like weight = weight_base + rtt * weight_multiplier.

Let me know if this is worth a PR.

Best regards

**Comment by rgacogne** [comment]
So would you mind explaining a bit why you wanted this? I could understand setting the server weight based on the DNS response time over UDP, for example, but I'm not sure why you would prefer the ICMP response time over the DNS one?

**Comment by 1848** [comment]
When I think about health checking the first protocol which comes in my mind is icmp because it is more usual for measuring rtt and more lightweight than a dns query.
This could lead to smaller overhead if one uses many servers and and a short checking interval.

I am aware that there might be even better solutions (maybe some kind of health-check protocol which gets exchanged to query metrics [e.g. load] from the remote server which could be used to calculate better weight values) but I think this could be too overkill and not an easy thing to create.

I understand when you dont see a big improvement over the current solution, thats why I did not create a PR for this yet.

I could also do some changes to my modification and create a PR for only allowing to set weight based on dns query time if you find this useful and dont want the other thing.
