### ISSUE TITLE
pdns-recursor dnssec issues with default Debian 9 install

### ISSUE THREAD

**Issue by firthmj** [PowerDNS/pdns#7169]
- Program: Recursor
 - Issue type: Bug report

### Short description

On installing pdns-recursor with minimal configuration (only changing "local-address" from the default of localhost only) on Debian 9, many queries appear to fail with SERVFAIL

Adding "dnssec=off" to the configuration file allows the queries to resolve, but seems like a bad thing to have to set.

### Environment

 - Operating system: Debian 9 (stretch) with latest system patches
 - Software version: 4.0.4 (from Debian repositories) or 4.1.6-1pdns (from PowerDNS repository)
 - Software source: Tried both from default Debian repository, and latest version from PowerDNS repository 

### Steps to reproduce

1. apt-get install pdns-recursor
2. edit /etc/powerdns/recursor.conf to change the "local-address" parameter to also include system's Ethernet IP address
3. (for example) dig isc.org soa @hostname (replace hostname with actual hostname)

Same result for local queries sent to @localhost

### Expected behaviour

The "dig" command would return the SOA record for the isc.org domain

### Actual behaviour

The "dig" command just indicates that the server returned "SERVFAIL":

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.isc.org @XXXXX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 64900
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.isc.org.			IN	A

;; Query time: 1784 msec
;; SERVER: 10.69.80.56#53(10.69.80.56)
;; WHEN: Thu Nov 08 17:00:49 GMT 2018
;; MSG SIZE  rcvd: 40

This example was using "dig" on a remote Ubuntu system, which is why the output has "ubuntu" in it - the server being queried was Debian 9.

### Other information

This failure is only for certain domains - at least "isc.org" and "gnu.org" are failing, but others are working (e.g. "bbc.com")

As mentioned above, adding "dnssec=off" to the configuration file makes the queries to the failing domains start working.

I do have a PCAP of the DNS packets to/from the machine running pdns-recursor for a few queries, but want to make sure I'm not doing something stupid first.

I haven't managed to get much useful debug logs from pdns-recursor, but maybe I am not setting it up right.

**Comment by phonedph1** [comment]
You can get a full trace log by doing ```rec_control trace-regex domain.com``` (or just ```.*``` for everything). Logs will go to your syslog or journal to check out.

**Comment by phonedph1** [comment]
OTOH this is probably more a support question, so hoping on IRC might be a better idea. The query response time from your failing dig seems to imply you're getting some network timeouts, and possibly something is breaking EDNS or similar for you.

**Comment by rgacogne** [comment]
> You can get a full trace log by doing rec_control trace-regex domain.com (or just .* for everything). 

That, or just set trace=yes in the configuration before starting the recursor so we know for sure that every relevant information will be in the logs. It will be very verbose, though, you probably don't want to run it like that for long.

**Comment by firthmj** [comment]
Hi,

Attached is the log of a query attempt for the SOA for "isc.org". Before the query, I restarted the recursor and ran "" to enable tracing for that domain. In the log I have replaced the server's hostname with "XXhostnameXX", and replaced the first three octets of our internal IP addresses with "IPa.IPb.IPc" for privacy reasons. If a developer wants me to directly sent them the unmodified log, let me know.

Interestingly, queries for "gnu.org", which were failing yesterday when I hadn't disabled the default DNSSEC processing are working today - is it possible that there is a genuine problem with the DNSSEC data for some domains that cause them to fail? If you want, I can upload the (now successful) trace for gnu.org.
[isc.org_dns_failure.txt](https://github.com/PowerDNS/pdns/files/2565445/isc.org_dns_failure.txt)

**Comment by pieterlexis** [comment]
These settings are explained in the regression tests, but it would make sense to put them more clearly in the docs.

```
        udp-truncation-threshold      edns-outgoing-bufsize
                  |                           |
    +------+      v      +----------+         v             +------------+
    | stub | <=========> | recursor | <===================> | responders |
    +------+             +----------+                       +------------+
```

**Comment by firthmj** [comment]
I do agree that there must be something broken in my network for the packets not to be fragmented properly, but I think it is probably fairly common for Internet connections (even from large ISPs) to have issues with large UDP packets.

Having something obvious in the installation notes that the default is larger than Ethernet MTU and may cause problems if fragmentation is not working 100% correctly in your network would be useful.

In answer to Pieter's post - does that mean "udp-trunction-threshold" is the value between the clients and my recursive server? Is there any benefit from setting it higher than "edns-outgoing-bufsize" - is there a case where "edns-outgoing-bufsize" packets coming back from responders would generate packets that are larger back to the "stub resolver"?

**Comment by firthmj** [comment]
I guess this issue can be closed as it isn't/wasn't a code bug, but still feel the documentation could be clearer

**Comment by JcChimjj** [comment]
I guess this issue can be closed as it isn't/wasn't a code bug, but still feel the documentation could be clearer

**Comment by JcChimjj** [comment]
＃7169
