### ISSUE TITLE
Recursor rpz-client-ip and rpz-ip with RPZ zone on AUTH (mysql)

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#7170]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description

Hi I'm running an RPZ zone on my AUTH server (rpz.mypdns.cloud) and all is fine as long as i stick to domain.tld.rpz.mypdns.cloud in accordance to [basic.rpz](https://github.com/PowerDNS/pdns/blob/9bb64785797d4b4829be3debc477458a7f81e7bd/pdns/basic.rpz)

Now if I add an ip like ``94.176.2.170.rpz-client-ip.rpz.mypdns.cloud CNAME rpz-drop`` to the auth db, then recursor refuse to load the rpzMaster with the following message:
Unable to load RPZ zone 'rpz.mypdns.cloud' from '127.0.0.1:5300': 'No 'zz' label found in an IPv6 RPZ name shorter than 9 elements: 94.176.2.170'.

and the second i delete the IP related record, the zone loads perfect again

### Environment

 - Operating system: Ubuntu bionic 18.04 LTS
 - Software version: pdns-server0.0.15424+0.g27dd1e38df-1pdns.bionic | pdns-recursor 0.0.15426+0.gccddcc9729-1pdns.bionic | pdns-backend-mysql 0.0.15424+0.g27dd1e38df-1pdns.bionic
 - Software source: 
POWERDNS repo

### Steps to reproduce

1. described above
2. in recursor.lua rpzMaster("[::1]:5300", "rpz.mypdns.cloud", {defpol=Policy.NXDOMAIN})
3. 

### Expected behavior

Have exspected the rpz.mypdns.cloud rpz zone to be loaded

### Actual behavior

Additional info
pdnsutil check-zone rpz.mypdns.cloud
Checked 83028 records of 'rpz.mypdns.cloud', 0 errors, 0 warnings.
This is with the ip.rpz-ip CNAME .

**Comment by phonedph1** [comment]
You still need to put the netmask on there. It's currently (I think) seeing ```94``` and since that is ```> 32```  trying to parse your address as IPv6 (which obviously doesn't work).

Try ```32.94.176.2.170.rpz-client-ip.rpz.mypdns.cloud``` maybe?

Reference: https://tools.ietf.org/id/draft-vixie-dns-rpz-04.html

**Comment by spirillen** [comment]
Hi phonedph1 that's only the (one way) but of curse i try it (tested and working), but what started this error and "playing" with diff variations in the ip secment whas that the
; IP Trigger NXDOMAIN Action
; any answer containing IP range
32.2.0.0.10.rpz-ip CNAME .
did tricker the very same problem, AND that if i have this zone running as bindbackend the actually do work as described in the various docs and articles Habbie have made

Based on the test and the ietf ref, I still think it would be the best to have the auth handle the rpz zones in a equal way as bind. So I think this issue should change from ``Bug report`` into ``feature request`` 

Note: I do understand the correctness in following the iett rules, but for new users, and daily usage I do see the bindbackend way as the easiest...

So This leaves me with another doc to mod :) nice

**Comment by spirillen** [comment]
RP moved to #7436
