### ISSUE TITLE
Postgresql Backend: using lastval is dangerous to get the last sequence value

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#7175]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I found this issue while trying "pdnsutil secure-zone". pdnsutil does:
1. Create and insert the new key: ''insert into cryptokeys (domain_id, flags, active, content) select ...''
2. uses ''select lastval()'' to retrieve the ''id'' of the currently inserted row.

The bug is, that PDNS assumes that the INSERT action only changes the sequence of the cryptokeys.id column. This may be wrong. There can be additional sequences be changed, eg. due to triggers on tables.

For example we use Slony for database replication. Slony is trigger based and uses plenty of sequences internally. Hence, lastval() returns a value of some Slony internal sequence instead of the cryptokey's id.

AFAIS, the above scenario is the only place where ''lastval'' is currently used. Hence, it could be changed to ''currval('cryptokeys_id_seq')''. Whereas I am not sure that the sequence has the same name on every installation. Or a config option to specify the sequence name? Or replaceing lastval with some other SELECT query to fetch the id?

Another workaround would be to document how a zone can be signed manually, instead of using pdnsutil. BTW: what is the preferred programatical way to enable DNSSEC? Ie. can it be done via the API?

Thanks
Klaus

**Comment by terrorobe** [comment]
Furthermore the current implementation is prone to race conditions if there's ever multiple writers to the database.

Sequences are by their nature not isolated, if there's multiple writers inserting to the database at the same time, subsequent sequence reads will only return the latest value.

The only safe way to get the ID of the row you inserted is either using `INSERT RETURNING` or doing a `SELECT` on the data you just inserted.

**Comment by Habbie** [comment]
#10392
