### ISSUE TITLE
There is a memory leak at the powerdns geoip backend

### ISSUE THREAD

**Issue by xuxiaomo** [PowerDNS/pdns#7184]
- Program: Authoritative
- Version: 4.1.3
- Issue type: Bug Report

### Description
I'm using powerdns authoritative 4.1.3 geoip backend. I configured a number of domains, the most of which had over 1000 records. Geoip database has approximately 30,000 + subnet records.

When I use it, I find that the server's memory has been growing, and the reset has not decreased. I had to restart the service once a day.
![image](https://user-images.githubusercontent.com/11468896/48396794-95216e80-e756-11e8-8c3d-19959f3156b0.png)

I also found that the memory growth rate is proportional to the number of accesses, I suspect that the geoip back end caches requests and responses, but does not free memory properly. Here is the average number of requests on both servers.
![image](https://user-images.githubusercontent.com/11468896/48396829-b5e9c400-e756-11e8-8bd6-4754bb1686e1.png)

What information do I need to provide to fix this problem?

**Comment by Habbie** [comment]
PowerDNS provides several other metrics, including several about cached items. Could you show those too, or, preferably, point your pdns at https://metronome.powerdns.com/ for a day or two so we can see for ourselves?

**Comment by xuxiaomo** [comment]
Hello, my [powerdns HK instance](https://metronome.powerdns.com/?server=pdns.hk_xiaomo01.auth&beginTime=-7200) has pointed to metronome.powerdns.com
![image](https://user-images.githubusercontent.com/11468896/48401637-90fc4d80-e764-11e8-98c2-222414932f86.png)
@Habbie

**Comment by rgacogne** [comment]
FWIW, the memory usage indeed seems to be increasing much faster than the packet, query or key/signature/key caches.

**Comment by rgacogne** [comment]
Any chance you could upgrade to 4.1.5 to see if the problem is still present? We do provide packages on https://repo.powerdns.com if that helps.

**Comment by xuxiaomo** [comment]
I have updated to 4.1.5, it's still pointing to the [original address](https://metronome.powerdns.com/?server=pdns.hk_xiaomo01.auth&beginTime=-900)
```
[root@HK-powerdns01 ~]# pdns_server --version
Nov 14 09:15:50 PowerDNS Authoritative Server 4.1.5 (C) 2001-2018 PowerDNS.COM BV
Nov 14 09:15:50 Using 64-bits mode. Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-28) on Nov  6 2018 17:54:28 by buildbot@869ed7fab750.
Nov 14 09:15:50 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Nov 14 09:15:50 Features: sodium openssl lua PKCS#11
Nov 14 09:15:50 Built-in modules: 
Nov 14 09:15:50 Configured with: " '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc/pdns' '--disable-static' '--disable-dependency-tracking' '--disable-silent-rules' '--with-modules=' '--with-luajit' '--with-dynmodules= bind gmysql gpgsql godbc pipe remote geoip ldap lua gsqlite3 tinydns mydns random' '--enable-tools' '--enable-libsodium' '--enable-unit-tests' '--enable-experimental-pkcs11' '--enable-systemd' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CPPFLAGS=-DLDAP_DEPRECATED' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'"
```

**Comment by xuxiaomo** [comment]
Now that doesn't look good, memory is increasing, but the size of the cache isn't increasing
![image](https://user-images.githubusercontent.com/11468896/48454768-92288b80-e7f3-11e8-93ac-77c2fce7c586.png)
![7 _x1 8jd8g 1ig k8zhd0k](https://user-images.githubusercontent.com/11468896/48454727-6b6a5500-e7f3-11e8-88a0-987497b4d7df.png)

**Comment by pieterlexis** [comment]
This indeed looks like a leak. Can you share your full configuration or another way of reproducing this issue?

**Comment by xuxiaomo** [comment]
Sorry, I can't share my configuration, but I will try to reproduce the problem with other configurations, which will take some time.

**Comment by xuxiaomo** [comment]
After some experimentation, I finally found the cause of the memory leak, and the fact that the memory growth is proportional to the request rate leads me to the final answer.

## Environment
* Operating system: CentOS Linux release 7.2.1511 (Core) 
* Powerdns Version: pdns-4.1.5-1pdns.el7.x86_64
* Software source: PowerDNS repository

## Repeat steps
### 1. Memory leak due to edns-subnet configuration
When ```edns-subnet-processing=yes```, every request that USES the dig with the client parameter causes memory to increase.
### 2. Close edns-subnet configuration
I turned off the edns-subnet configuration, but memory keeps increasing. So I suspect that geoip backend will cache the response data based on the source IP even if the edns option is not turned on.
### 3. Reproduce the problem
#### (1)Simulate different source IP request dns servers, observe memory usage.
```
Client:
(venv) [root@client tmp]# python attack.py -host=10.77.77.59 -domain test.test.com -dev eno16777984 -count=1000 -randomip=true

Server:
[root@server tmp]# pdns_control show real-memory-usage
8273920
[root@server tmp]# pdns_control show real-memory-usage
8372224
[root@server tmp]# python
Python 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 8372224 - 8273920
98304
>>> 
```
#### (2)Use the same IP to access the server.
```
Client:
(venv) [root@client tmp]# python attack.py -host=10.77.77.59 -domain test.test.com -dev eno16777984 -count=1000 -randomip=false

Server:
[root@server tmp]# pdns_control show real-memory-usage
9199616
[root@server tmp]# pdns_control show real-memory-usage
9199616
```
#### (3)Conclusion
So geoip backend will cache the response data based on the source IP even if the edns option is not turned on. I think caching is good, but I didn't find it a relevant configuration to control the maximum cache size.
### 4. Config and test script
[TestConfig.zip](https://github.com/PowerDNS/pdns/files/2594097/TestConfig.zip)

**Comment by chbruyand** [comment]
Thanks @xuxiaomo for your detailed report!
