### ISSUE TITLE
dnsdist: incorrect check-config behaviour

### ISSUE THREAD

**Issue by chbruyand** [PowerDNS/pdns#7185]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

`check-config` mode actually relies on the same behaviour than `client` mode to run. However, all objects won't be properly created while launched under `check-config` as it will be inhibited by the `client` mode.
We should separate the two modes and ensure proper behaviour.

**Comment by rgacogne** [comment]
Postponing to 1.5.0 since it might break some setups.
