### ISSUE TITLE
dnsdist: rmPool() is not a function in global scope

### ISSUE THREAD

**Issue by dol** [PowerDNS/pdns#7189]
Program: dnsdist
Issue type: Missing implementation

### Short description
In the docs about pools of [dnsdist](https://github.com/PowerDNS/pdns/blob/5792b628909e51d2ca7a0907924f7a62312466d0/pdns/dnsdistdist/docs/reference/config.rst#pools) the addPool()/rmPool() function is documented. But at least in 1.3 the rmPool() function in the global scope is not possible.

See comment: https://github.com/PowerDNS/pdns/commit/5d31a326617f6d262455a318a64d57f120a64696#r31271671

### Steps to reproduce
```
addPool("foobar")
Error: [string "return addPool("foobar")"]:1: attempt to call global 'addPool' (a nil value)>
rmPool("foobar")
Error: [string "return rmPool("foobar")"]:1: attempt to call global 'rmPool' (a nil value)>
```

**Comment by rgacogne** [comment]
Thanks! FWIW I think we should just remove the mention of `rmPool()` from the documentation, because removing pools at runtime might not be too gracefully handled by, for example, rules that reference them.
