### ISSUE TITLE
Replace "Trying to insert non-zone data" by soft exclude of bad RR

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#719]
Hello,

I'm successfully migrated very big Bind9 (160 000 zones) instance to PowerDNS today, it's work prefectly, thank you!

But there are one bad issue with powerdns bind backend.

At example, we have following named zone (jc.andreyber.ru) with small bug:
$TTL  3600
jc.andreyber.ru.    IN   SOA   ns3.fastvps.ru. support.fastvps.ru. (2013032207 10800 3600 604800 86400)
jc.andreyber.ru.    IN   NS   ns1.selectel.org.
jc.andreyber.ru.    IN   NS   ns2.selectel.org.
jc.andreyber.ru.    IN   NS   ns3.selectel.org.
jc.andreyber.ru.    IN   MX   10 mail
jc.andreyber.ru IN   CNAME  justclick.ru.
justclick.ru.  IN   A    5.9.77.28

As you can see, record justclick.ru. in out of bound our zone. If we try to run Bind 9 with this zone we got warning:
Mar 22 10:10:13 mail-relarn named[667]: master/jc.andreyber.ru:11: ignoring out-of-zone data (justclick.ru)

But all records except buggy still works fine! But in Powerdns's BIND backend we got full zone excluding. I think it's more clever remove only buggy record, not whole zone.

I'm using 2.9.22 version, but this issue still exists in 3.2 also:
throw AhuException("Trying to insert non-zone data, name='"+bdr.qname+"', qtype="+qtype.getName()+", zone='"+bb2.d_name+"'");

Thank you!

Backend: BIND
OS: Debian 6 x86_64

**Comment by perlancar** [comment]
Sorry to comment on an old issue, but I just tried 4.2.0rc2 (from repo.powerdns.com) and this old behavior is still there. A zone that is "Trying to insert non-zone data" is still excluded in whole, despite only one record has this error.

**Comment by Habbie** [comment]
Hi! Comments on old issues will be ignored and forgotten. If you have a fresh problem in a fresh version of powerdns, please file a fresh ticket. But before you do that, please try `bind-ignore-broken-records=yes`.

**Comment by perlancar** [comment]
> Hi! Comments on old issues will be ignored and forgotten. If you have a fresh problem in a fresh version of powerdns, please file a fresh ticket. But before you do that, please try `bind-ignore-broken-records=yes`.

Sorry, please ignore my comment (which has been deleted). I read this issue before reading some others. Thanks for the response.
