### ISSUE TITLE
Cannot set API-RECTIFY vi api

### ISSUE THREAD

**Issue by marioprezent** [PowerDNS/pdns#7193]
I try to set API-rectify to 1 after enabling dnssec to prevent running rectify after every modification request.
I successfully managed to do this via pdnsutil set-meta example.com API-RECTIFY 1, however since our dns setup is remotely, I like to do this via an api call. As far as I read the API documentation it is possible.

 - Program: Authoritative
 - Issue type: Bug report/Feature request 

I try to POST the API-RECTIFY metadata but it says :
Unsupported metadata kind 'API-RECTIFY'
curl -i -X POST -H 'X-API-Key: oursecret' -d '{"kind": "API-RECTIFY", "metadata": ["1"], "type": "Metadata"}' http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com/metadata
For debugging I tried an get of the metadata but it returned Unsupported metadata kind as well. As far as I can see in de code, API-RECTIFY should be a valid metakind. I found it in the protectedoptions vector in : pdns/ws-auth.cc function isValidMetadataKind.
curl -i -X GET -H 'X-API-Key: oursecret' 
http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com/metadata/API-RECTIFY
{"error": "Unsupported metadata kind 'API-RECTIFY'"}

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: tested with both : PowerDNS/4.1.4, PowerDNS/4.1.5
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-=======================================================================================
ii  pdns-backend-mysql                        4.1.5-1pdns.xenial        amd64                     generic MySQL backend for PowerDNS
ii  pdns-server                               4.1.5-1pdns.xenial        amd64                     extremely powerful and versatile nameserver

 - Software source: Powerdns repo

### Expected behaviour
I would expect API-RECTIFY could be changed

Could you tell or I try to do something not implemented or am I calling the API wrong? Thanks in advance.

**Comment by pieterlexis** [comment]
This needs to be set using the zone endpoints. It is documented in the [Zone object](https://doc.powerdns.com/authoritative/http-api/zone.html#zone)

e.g. PUTting this to `/api/v1/servers/localhost/zones/example.com.`

```json
{
  "api_rectify": true
}
```

Or when POSTing a new zone to e.g. `/api/v1/servers/localhost/zones`

```json
{
  "name": "zone.example.",
  ....
  "api_rectify": true
}
```
