### ISSUE TITLE
active dnsdist secpoll check

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#7194]
From IRC:
> <winfried_> good morning, In Recursor we can active check security status with "get security-status" in Auth we can "show security-status" but how to check in in dnsdist?
> <winfried_> because I'd like to write an Icinga plugin for that
> <cmouse> winfried_: 1.3.3 has security status support at least.
> <winfried_> cmouse: yes, but hw to check *active*?
> <lieter> winfried_: I don't think we expose it, checking ;)
> <lieter> winfried_: we indeed do not expose this, can you make a ticket?

 - Program: dnsdist 
 - Issue type: Feature request

### Short description
We'd like to write a Nagios/Icinga plugin to check active the Secpoll status of dnsdist. Unfortunately dnsdist does not provide a command to display the Secpoll status.
 
### Usecase
Possibility to issue a dnsdist command from a Nagios plugin script to determine the Secpoll status. It should print "1", "2" or "3" like the Recursor `security-status`.

### Description
It could look like
```
# dnsdist -e 'showSecurityStatus()'
1
```

**Comment by rgacogne** [comment]
It would also be nice to be able to retrieve the status via the `API`, and to expose it to `SNMP`, `carbon` and `prometheus` statistics.
