### ISSUE TITLE
[WARNING] UDP query from xxxx is not allowed, dropping

### ISSUE THREAD

**Issue by isnuryusuf** [PowerDNS/pdns#7208]
- Program: ixfrdist
 - Issue type: [WARNING] UDP query from xxxx is not allowed, dropping

### Short description
trying to load serial on pdns master and got : 
[WARNING] UDP query from xxxx is not allowed, dropping  on ixfrdist

### Environment

 - Operating system: centos7
 - Software version: pdns-ixfrdist-0.0.15489-0.g19d56bb157.1pdns.el7.x86_64 and pdns-4.0.5-1pdns.el7.x86_64 (diffrent server with ixfrdist)
 - Software source: binary distribution under centos7 repo

### Steps to reproduce

1. increase serial on pdns master
2. check log on ixfrdist
3. 

### Expected behaviour
can you please give some information, there is problem on my firewall?

**Comment by Habbie** [comment]
Can you show:
- your pdns config
- your ixfrdist config
- your unedited ixfrdist log

please?

**Comment by isnuryusuf** [comment]
sure, thnks for asking

### pdns.conf
```
cache-ttl=20
daemon=no
domain-metadata-cache-ttl=60
guardian=no
launch=
local-ipv6=
log-dns-details=yes
log-dns-queries=yes
loglevel=9
max-tcp-connections=500
query-logging=yes
security-poll-suffix=
setgid=pdns
setuid=pdns
local-address=127.0.0.1,192.168.13.20
recursor=127.0.0.1:5300
allow-axfr-ips=127.0.0.0/8
also-notify=127.0.0.1:5300
log-dns-queries=yes
master=yes

launch=gmysql
gmysql-host=localhost
gmysql-user=xxxx
gmysql-dbname=zzz
gmysql-password=xxxx
gmysql-timeout=0

include-dir=/opt/xxxx/pdns/
```


### ixfrdist.yml
```
listen:
  - '10.10.0.12:53'

acl:
  - '127.0.0.0/8'
  - '10.10.0.0/24'
  - 'xx.xx.xx.xx/24'

axfr-timeout: 180
keep: 500
tcp-in-threads: 32
work-dir: 'ixfrdist.dir'
failed-soa-retry: 3

domains:
  - domain: zzzzzz
    master: zz.zzx.xx.xx

```

**Comment by isnuryusuf** [comment]
other comment

https://github.com/PowerDNS/pdns/issues/6994#issuecomment-439589975

**Comment by rgacogne** [comment]
so, is `ip-pdns-master` in:
```
acl:
  - '127.0.0.0/8'
  - '10.10.0.0/24'
  - 'xx.xx.xx.xx/24'
```
?

**Comment by isnuryusuf** [comment]
thnsk for your comment, appreciate your effort

so i need to put ip-pdns-master on ixfrdist acl right?

thnks, i`ll try

BR

**Comment by isnuryusuf** [comment]
From the documentation 
https://doc.powerdns.com/authoritative/manpages/ixfrdist.yml.5.html

i found ACL is for list permitted  slave IP Address, is that true?

thnks

**Comment by isnuryusuf** [comment]
@Habbie any suggestion, really appreciate your effort

thnks

**Comment by Habbie** [comment]
We cannot help with xx.xx IP addresses - please post unedited configs and logs (just remove passwords).

**Comment by isnuryusuf** [comment]
thnks you, i just edit the previous command and put ip address

**Comment by Habbie** [comment]
We, again, cannot help with redacted configs and logs.
