### ISSUE TITLE
PowerDNS with bind backend did not show rejected zones in pdns_control bind-list-rejects

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#721]
Hello,

We have one buggy zone, which show in pdns_control rediscover output:
Ok Done parsing domains, 1 rejected, 1 new, 0 removed

But if we try use command for get more information about zone:
pdns_control bind-list-rejects

We got blank answer, it's bug, because in log or in  error shown correctly:
pdns_control BIND-DOMAIN-STATUS|grep art-dias.ru
art-dias.ru:     error at Wed Mar 27 12:50:13 2013 parsing 'art-dias.ru' from file '/etc/bind/art-dias.ru': Trying to insert non-zone data, name='artdias.ru', qtype=A, zone='art-dias.ru'

Mar 27 12:50:11 ns1 pdns[494]: Rediscovery was requested
Mar 27 12:50:12 ns1 pdns[494]: [bindbackend] Parsing 169614 domain(s), will report when done
Mar 27 12:50:13 ns1 pdns[494]: [bindbackend] error at Wed Mar 27 12:50:13 2013 parsing 'art-dias.ru' from file '/etc/bind/art-dias.ru': Trying to insert non-zone data, name='artdias.ru', qtype=A, zone='art-dias.ru'
Mar 27 12:50:15 ns1 pdns[494]: [bindbackend] Done parsing domains, 1 rejected, 2 new, 0 removed

Thank you!

PowerDNS 3.2, official package for Debian.

**Comment by pieterlexis** [comment]
`pdns_control bind-list-rejects` works as expected on master
