### ISSUE TITLE
api_rectify as default

### ISSUE THREAD

**Issue by tjikkun** [PowerDNS/pdns#7231]
- Program: Authoritative
 - Issue type: Feature request

### Short description
We would like the possibility to have api_rectify set as default.

### Usecase
After a modification of any record where the domain has DNSSec, we would like to have a still working DNSSec domain.

### Description
We use the PowerDNS API to modify our domains. We also use DNSSec on all our domains. After modifications we always want to run rectify, if needed. Currently it is possible to modify the domain object (or set on creation) API-RECTIFY to 1. Since we would need to set it always, I hope it is possible to either switch api_rectify to be on by default (since I figure most of the time this is what you want) and/or to provide an option to set the default for this.

**Comment by pieterlexis** [comment]
Adding an option `api-rectify` with a default value of `yes` makes sense.
