### ISSUE TITLE
No DNSSEC validation in case of "--forward-zones-recurse"

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#7234]
- Program: Recursor
 - Issue type: Bug report

### Short description
If I forward queries to a full DNSSEC validating Resolver, answers are always NOERROR even if I ask for dnssec-failed.org.

### Environment
 - Operating system: SUSE Linux Enterprise 12 SP3
 - Software version: PowerDNS Recursor 4.1.8
 - Software source: self compiled

### Steps to reproduce
Start the Recursor:
`pdns_recursor --config-dir=. --socket-dir=. --daemon=no --forward-zones-recurse=.=8.8.8.8 --dnssec=validate`

Send a query against it:
```
dig dnssec-failed.org @127.0.0.1

; <<>> DiG 9.10.4-P5 <<>> dnssec-failed.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17625
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dnssec-failed.org.             IN      A

;; ANSWER SECTION:
dnssec-failed.org.      7199    IN      A       69.252.80.75

;; Query time: 133 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 28 10:27:47 CET 2018
;; MSG SIZE  rcvd: 62
```
### Expected behaviour
If I run a Recursor with `--dnssec=validate` and `--forward-zones-recurse=.=` to a full validating Resolver I'd expect a SERVFAIL in case of a bogus DNSSEC domain.

### Actual behaviour
The answer status is NOERROR in each case. Even the AD bit is set in the answer if I ask for `dnssec-failed.org`

**Comment by M4t7e** [comment]
I have seen the same behavior when forwarding some zones to an OpenNIC DNS resolver. Thanks for reporting @paddg!

**Comment by rgacogne** [comment]
We did a lot of cleanup in that area, would you happen to know if this issue still remains in 4.2.0?

**Comment by paddg** [comment]
Yes I can confirm, it is fixed. Tested wit 4.2.0 and 4.1.12. Thanks @rgacogne!
