### ISSUE TITLE
Add support for JOURNAL_MODE when using SQLite3 backend

### ISSUE THREAD

**Issue by piula** [PowerDNS/pdns#7251]
- Program: Authoritative
 - Issue type:Feature request 

### Short description

For using powerdns with an SQLite database, it would be helpful if "PRAGMA JOURNAL_MODE" could be supported.

### Environment

 - Operating system: Linux Arch x64
 - Software version: 4.1.1
 - Software source: docker hub psitrax/powerdns

### Usecase

I run powerdns in a docker container and bind mount the SQLite database file into the container. However, for each update, a *-journal file needs be created. Therefore, the parent directory (the one containing the database file) has also to be mounted into the container.

With JOURNAL_MODE=MEMORY, this would be not necessary at all. With JOURNAL_MODE=TRUNCATE, it would be sufficient to mount both the database and the journal file.

### Description

Suggestion: Add a gsqlite3-pragma-journal-mode configuration option to allow defining the journal mode to be used. (Has to be set on each connection.)

Possible values are: DELETE | TRUNCATE | PERSIST | MEMORY | WAL | OFF

For compatibility, gslite3-pragma-journal-mode should default to DELETE.

Whichever value is set, it should be forwarded to the SQLite3 engine immediately after opening any new database connection, i.e. "PRAGMA JOURNAL_MODE=xxx;" should be sent.

**Comment by Habbie** [comment]
We should do this, and default to WAL.

**Comment by mnordhoff** [comment]
Less important, should this setting apply to the bind-dnssec-db? should that have a separate setting?

**Comment by Habbie** [comment]
> Less important, should this setting apply to the bind-dnssec-db? should that have a separate setting?

Both backends would have to declare and pass the option, I suppose.
