### ISSUE TITLE
dnsdist: different names for the dnsdist 1.3.3 debug packages in Debian 9

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#7252]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

With the 1.3.3 release, the name of the debug symbols packages for Debian Stretch have been renamed from `dnsdist-dbg` to `dnsdist-dbgsym`.
Note that in Jessie and all the Ubuntu derivates the debug packages are still named `dnsdist-dbg`.

This behavior appears not to be documented and, as a result, updating the dnsdist debug symbols packages or installing these using the name `dnsdist-dbg` used for all the debian-like distributions results in

```
root@debian-9:/# apt-get install dnsdist-dbg
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dnsdist-dbg : Depends: dnsdist (= 1.3.2-1pdns.stretch) but 1.3.3-1pdns.stretch is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Environment

 - Operating system: Debian
 - Software version: Stretch
 - Software source: PowerDNS repository

### Expected behaviour

I would expect a consistent naming convention on the debug symbols packages across all the Debian-like distributions and the new name of the packages to be documented as a breaking change.

### Actual behaviour

The installation of the debug symbols packages, using for instance http://github.com/powerdns/dnsdist-ansible, is broken on Stretch.

**Comment by stbuehler** [comment]
Afaict `...-dbgsym` is the "future".  Also the packages from debian (including stretch) are already named `...-dbgsym` and are in a separate repository (see http://ftp.debian.org/debian/pool/main/d/dnsdist/ and http://debug.mirrors.debian.org/debian-debug/pool/main/d/dnsdist/).

Also see https://wiki.debian.org/AutomaticDebugPackages for some background.

**Comment by atosatto** [comment]
Hi @stbuehler thanks for the very useful references. 
This issue refers to repo.powerdns.com. We should probably do something similar to ftp.debian.org then.

**Comment by atosatto** [comment]
Yeah, currently we have a bit of confusion because for xenial and bionic we ship the package as `dnsdist-dbg`.

**Comment by rgacogne** [comment]
Closing this as I believe we fixed it for current packages.
