### ISSUE TITLE
dnsdist: missing debug packages for Ubuntu 18.04 

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#7253]
- Program: dnsdist 
 - Issue type: Bug report 

### Short description

Apparently, since the release 1.3.3 of dnsdist we're not distributing correctly debug symbols packages for Ubuntu Bionic.

### Environment

 - Operating system: Ubuntu
 - Software version: 18.04
 - Software source: PowerDNS repository

### Expected behaviour

Being able to install dnsdist's debug symbols packages with `dnsdist-dbg`.

### Actual behaviour

In https://repo.powerdns.com/ubuntu/dists/bionic-dnsdist-13/main/binary-amd64/Packages are missing debug symbols packages for dnsdist 1.3.3.
While in https://repo.powerdns.com/ubuntu/dists/bionic-dnsdist-master/main/binary-amd64/Packages
the debug symbols packages appears outdated.

**Comment by rgacogne** [comment]
Closing this as I believe we fixed it for current packages.
