### ISSUE TITLE
change_date missing from schema in docs

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#7254]
https://doc.powerdns.com/authoritative/backends/generic-mysql.html, which aims to be for both 4.1 and master (and thus 4.2) has had `change_date` removed (as it is gone in 4.2). As a result the schema on that page is broken for 4.1.

**Comment by commx** [comment]
The same issue is valid for the gpgsqlbackend.

**Comment by Habbie** [comment]
Yes, and several others.
