### ISSUE TITLE
addTLSLocal

### ISSUE THREAD

**Issue by Warok21** [PowerDNS/pdns#7273]
- Program: dnsdist
- Issue type: Bug

### Short description
Environment
Operating system: Linux 16.04
Software version: dnsdist 1.3.3 (Lua 5.1.4)
### Steps to reproduce
(Copied from :https://pki-tutorial.readthedocs.io/en/latest/simple/index.html to create my keys)

```
$ cat /etc/dnsdist/dnsdist.conf 
addTLSLocal('127.0.0.1', '/home/adriano/ca/signing-ca/01.pem', '/home/adriano/certs/simple.org.key')
newServer("130.59.31.248:853")
```

> dig @127.0.0.1 example.com

### Expected behaviour
dig returning a response

### Actual behaviour
dig give the following results

>  dig @127.0.0.1 -p853 google.ch +tcp
> ;; WARNING: can't receive reply from 127.0.0.1@853(TCP)
> ;; WARNING: failed to query server 127.0.0.1@853(TCP)
>

**Comment by rgacogne** [comment]
As far as I know, `dig` doesn't speak `DNS over TLS`, so unless I'm mistaken you are sending a plaintext query to a `DNS over TLS` server which can't possibly work.

**Comment by Warok21** [comment]
So, I have to use stubby to test my queries?

**Comment by paddg** [comment]
kdig from Knot does support dot afaik 

Am 10. Dezember 2018 16:58:07 MEZ schrieb Warok21 <notifications@github.com>:

**Comment by rgacogne** [comment]
Closing since it looks like a support question, please see https://www.powerdns.com/opensource.html
