### ISSUE TITLE
pdns_control notify * only notifies for MASTER domains, even when slave-renotify is set

### ISSUE THREAD

**Issue by alebeta90** [PowerDNS/pdns#7285]
- Program: Authoritative
 - Issue type: Feature request

### Short description

When I execute the command:
`pdns_control notify \*`

It is sending notifications only about the master zones, but in my configuration file I have enable renotify to also send slave zones notifications. It would be great if I could send with notify * the slave zones also. Then I can propagate the zones quicker among all my dns servers

### Expected behaviour

propagate slaves zones too

### Actual behaviour

propagate just master zones

Thanks in advance!

**Comment by alebeta90** [comment]
Pull request #7293

**Comment by Habbie** [comment]
Fixed in #7293
