### ISSUE TITLE
*FAILURE* no valid transports or upstreams available!

### ISSUE THREAD

**Issue by Warok21** [PowerDNS/pdns#7302]
- Program: dnsdist
- Issue type: Failure

Short description
### Environment
Operating system: Ubuntu 16.04
Software version: dnsdist 1.3.3 (Lua 5.1.4)

### Steps to reproduce

`cat /etc/dnsdist/dnsdist.conf:`

> addLocal("160.98.31.165")
> addTLSLocal('160.98.31.165:853', '/etc/letsencrypt/xxx/fullchain.pem', '/etc/letsencrypt/xxx/privkey.pem')
> newServer({address='1.1.1.1'})
> getServer(0):setUp()
> addACL('160.98.0.0/16')
> setACL('160.98.0.0/16')

### Client :
Windows 10
Content of stubby.yml:

> resolution_type: GETDNS_RESOLUTION_STUB
> dns_transport_list:
> GETDNS_TRANSPORT_TLS
> tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
> tls_query_padding_blocksize: 128
> edns_client_subnet_private : 1
> round_robin_upstreams: 1
> idle_timeout: 10000
> listen_addresses:
> 127.0.0.1
> 0::1
> upstream_recursive_servers:
> address_data: 160.98.31.165
> tls_auth_name: "cn that I used in the command"
> tls_pubkey_pinset:
> digest: "sha256"
> value: computed hash

### Expected behaviour
Client making the connection with the server
### Actual behaviour

>    *FAILURE* no valid transports or upstreams available!
> Could not schedule query: None of the configured upstreams could be used to send queries on the specified transports
>

**Comment by ahupowerdns** [comment]
Github is not a support forum. We told you before. Please either send email to the list or attempt to explain your problem again on our IRC channel.
