### ISSUE TITLE
Does TSIG support for all queries from clients?

### ISSUE THREAD

**Issue by whitetiger21022014** [PowerDNS/pdns#7309]
Hello,
In BIND9, the is an option: all clients can query to BIND9 forwarder server with only one TSIG
that syntax like:
	allow-recursion { key secret-key; };
     	allow-query { key secret-key; };

So may I use one TSIG key for **DNSDIST or PowerDNS Recursor**? it means one TSIG key for all domains 
I don't use TSIG for Dynamic DNS update
Thanks,
John

**Comment by pieterlexis** [comment]
There is no TSIG support to allow/disallow recursion or queries in the recursor (or dnsdist). 

Can you use the template provided to turn this issue into a feature request so we can decide on whether we want to implement this?

**Comment by whitetiger21022014** [comment]
Thanks, I just post
