### ISSUE TITLE
Feature request: per-domain DNSUPDATE control

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#7313]
- Program: Authoritative
 - Issue type: Feature request

### Usecase
I would like to be able to *require* TSIG keys for DNSUPDATEs for domains, and disallow DNSUPDATEs for domains which do not have TSIG keys defined.

### Description
If DNSUPDATE is enabled at the server level, all domains are enabled for DNSUPDATE. It is possible to additionally require TSIG keys for DNSUPDATEs to specific domains, but there does not appear to be a way to disable non-TSIG DNSUPDATE for specific domains. When the server receives a DNSUPDATE for a domain which does not have a TSIG key defined, a message is emitted in the log about the lack of a TSIG key but the request is accepted regardless.

At the moment it appears that the only way to control this behavior is to set ALLOW-DNSUPDATE-FROM in the domain metadata to an invalid address, so that requests will never match and will be denied.

**Comment by Habbie** [comment]
I believe https://doc.powerdns.com/authoritative/dnsupdate.html#lua-dnsupdate-policy-script covers this if one is willing to type a policy script.

**Comment by Habbie** [comment]
Hello Kevin, did you ever get around to seeing if my documentation link covers your purposes?

**Comment by kpfleming** [comment]
It does, but I've also completely forgotten why I wanted to do this in the first place :-)
