### ISSUE TITLE
TSIG for queries/recursion from clients

### ISSUE THREAD

**Issue by whitetiger21022014** [PowerDNS/pdns#7318]
- Program: Recursor, dnsdist
 - Issue type: Feature request

### Usecase
TSIG for queries/recursion from clients

### Description
 Only one TSIG key for DNSDIST or PowerDNS Recursor

TSIG provides authentication for client, so only client has TSIG can connect to that DNS server
In PowerDNS Recursor, if Lua scripting (function postresolve ) appends extra record like HINFO/TXT to A record, other DNS server (BIND/Unbound) will trunk HINFO/TXT record

**Example TSIG for BIND9**
key "secret-key-test" {
        algorithm hmac-md5;
	secret "zzzzzzzzzzzzzzzzzzzzzzz==";
};

allow-recursion { key secret-key-test; };
allow-query { key secret-key-test; };

And Test: dig +multiline -y secret-key-test:zzzzzzzzzzzzzzzzzzzzzzz==@127.0.0.1 external-domain.com. A

**Comment by cmouse** [comment]
Hi, do you have any practical usecase for this?

**Comment by whitetiger21022014** [comment]
Hi, 
- I tested on BIND9, and also Unbound. But do not get HINFO
BIND9 (https://gitlab.isc.org/isc-projects/bind9) answser "Named only caches the expected records in responses which it then returns."
- Knot Resolver get HINFO, but Knot Resolver does not full support for TSIG for client
(https://knot-resolver.readthedocs.io/en/stable/modules.html , TSIG, "This just selects rule based on the key name, it doesn’t verify the key or signature yet.") 

Powerdns recorsor's lua
function postresolve(dq)
    dq:addAnswer(pdns.HINFO, "hello test","")
     ................

**BIND 9 forwarders all to Powerdns recorsor**
/etc/bind/named.conf
  forward only;
  forwarders {
            127.0.0.1 port 5999;
    };

**dig @127.0.0.1 -p 5999 cnn.com     (5999 is port of powerdns recursor)**
;; ANSWER SECTION:
cnn.com.                60      IN      A       151.101.129.67
cnn.com.                60      IN      A       151.101.65.67
cnn.com.                60      IN      A       151.101.193.67
cnn.com.                60      IN      A       151.101.1.67
**_cnn.com.                3600    IN      HINFO   "hello test" ""_**


**dig @127.0.0.1 -p 53 cnn.com       (53 is port of BIND9)**
;; ANSWER SECTION:
cnn.com.                60      IN      A       151.101.129.67
cnn.com.                60      IN      A       151.101.65.67
cnn.com.                60      IN      A       151.101.193.67
cnn.com.                60      IN      A       151.101.1.67
