### ISSUE TITLE
SOA-EDIT isn't applied to serials in non-apex negative responses

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#7361]
- Program: Authoritative
 - Issue type: Bug report

### Short description

When using `SOA-EDIT`, the edited serial number is used for important things, like `SOA` queries and zone transfers.

However, the backend database's original serial number is used for the `SOA` record in `NXDOMAIN` responses, and for NODATA responses that are _not_ for the zone apex.

Zone apex NODATA responses also use the edited serial number.

I'm using DNSSEC; both `SOA` records are apparently signed correctly.

The `SOA` serial number in a negative response doesn't matter for anything, but creative resolvers will cache it as the zone's real `SOA` record.

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: 0.0.15744+0.g7c94d361cd and 0.0.15793+0.g732fda289a
 - Software source: PowerDNS repository

### Steps to reproduce

1. `dig +dnssec +norecurse dns-l.mn9.us @ns2.mattnordhoffdns.org`
2. `dig +dnssec +norecurse dns-l.mn9.us soa @ns2.mattnordhoffdns.org`
3. `dig +dnssec +norecurse foo.dns-l.mn9.us aaaa @ns2.mattnordhoffdns.org`
4. `dig +dnssec +norecurse nxdomain.dns-l.mn9.us @ns2.mattnordhoffdns.org`
5. Configure the zone below.
6. `sudo pdnsutil set-meta dns-l.mn9.us SOA-EDIT INCEPTION-INCREMENT`
7. `sudo pdnsutil set-nsec3 dns-l.mn9.us "1 0 0 -"`
8. `sudo pdnsutil secure-zone dns-l.mn9.us`

### Expected behaviour
The edited serial number everywhere.

### Actual behaviour
Both serial numbers.

### Other information

Related code?

https://github.com/PowerDNS/pdns/blob/c6bdd149edbac84eca602bd0b20a96866f11ae0a/pdns/packethandler.cc#L969-L1007

https://github.com/PowerDNS/pdns/blob/c6bdd149edbac84eca602bd0b20a96866f11ae0a/pdns/packethandler.cc#L1425-L1435

Zone:

```
$ORIGIN dns-l.mn9.us.
$TTL 3600
@			SOA	pdns0.mattnordhoff.net. rname.mn0.us. (
						2019011002
						3600
						1800
						432000
						3600
					)
@			NS	ns1.linode.com.
@			NS	ns2.linode.com.
@			NS	ns3.linode.com.
@			NS	ns4.linode.com.
@			NS	ns5.linode.com.
@			NS	ns2.mattnordhoffdns.org.
@			NS	ns3.mattnordhoffdns.com.
foo			A	192.0.2.0
```

**Comment by Habbie** [comment]
Failing test: 
https://gist.github.com/Habbie/20224bb3cb7c65c5561b7dc994c90e05
