### ISSUE TITLE
dnsscope lost its histogram abilities due to bad ifdef

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7362]
dnsscope used to be able to do cool histogram stuff. It now checks for a suitable Boost version before offering those features, but the #ifdef it uses isn't defined anywhere, so it never happens.

**Comment by rgacogne** [comment]
Oh crap, did I mess up my fix in https://github.com/PowerDNS/pdns/pull/7291 ?

**Comment by Habbie** [comment]
It's defined on my system..

**Comment by Habbie** [comment]
> Oh crap, did I mess up my fix in #7291 ?

Perhaps it didn't make it to 4.1.x?

**Comment by ahupowerdns** [comment]
Let me double check. Perhaps I need to autoreconf harder. I am on master.

**Comment by Habbie** [comment]
I tested this way:
```diff
--- a/pdns/dnsscope.cc
+++ b/pdns/dnsscope.cc
@@ -24,6 +24,7 @@
 #include "config.h"
 #endif
 #if HAVE_BOOST_GE_148
+#error GE_148
 #include "histog.hh"
 #endif
```

because dnsscope doesn't currently build on macOS for unrelated reasons.

**Comment by rgacogne** [comment]
> Perhaps it didn't make it to 4.1.x?

I don't think we backported this feature to 4.1.x, did we?

**Comment by Habbie** [comment]
> I don't think we backported this feature to 4.1.x, did we?

Ah, we didn't.

**Comment by ahupowerdns** [comment]
After an explicit autoreconf, it all works. Apologies for the noise!
