### ISSUE TITLE
TLSA Wildcard and Subdomains

### ISSUE THREAD

**Issue by OliverNeu** [PowerDNS/pdns#7365]
I have installed the newest Version of 4.1 and have insert a TLSA Wildcard entry:
*.mydomain.tld
Than I check this:
`dig _443._tcp.mydomain.tld IN TLSA +short`
The result: I get the TLSA entry.

When I check a Subdomain where not set in DNS:
`dig _443._tcp.mysubdomain.mydomain.tld IN TLSA +short`
I found the TLSA entry.
When I create a A and AAAA record for mysubdomain, and check the TLSA again, so I don't find the TLSA entry.
For this one I must create a second TLSA for *.mysubdomain.mydomain.tld

Is this a bug with PowerDNS? I think the Wildcard *.mydomain.tld must find the subdomain not only if it is not set in DNS

Sorry for my bad english.

**Comment by Habbie** [comment]
This is not a bug in PowerDNS. For more help, please find us on IRC or ask the mailing list. Details are at https://www.powerdns.com/opensource.html
