### ISSUE TITLE
Does pdns recorsor support  for forwarding edns0 from internal DNS?

### ISSUE THREAD

**Issue by whitetiger21022014** [PowerDNS/pdns#7372]
Hi,
I setup pdns recursor as below

computer ----->  [[ dns#1 **(edns0 for MAC address )**  --> pdns recursor#2 ]]  ---> To  Internet  ---> Pdns recursor#3 -> 8.8.8.8

If dns#1 sends directly to pdns#3, at pdns#3 I can get MAC address (tag ednsoptions[65073])
If dns#1 sends to #dns2 (pdns#2), at pdns#3 I can't see any  ednsoptions packet (?)
If I replace pdns#2 to dnsnist software, at pdns#3 I can get MAC address (tag ednsoptions[65073])

So does pdns recorsor support (like transparent proxy dns)  for edns0 for forwarding edns0 packet from internal DNS or not?
Thank so much
John

/etc/powerdns/recursor.conf at pdns recursor #2
local-port=5353
forward-zones-recurse=.=22.22.xx.xx
local-address=0.0.0.0
allow-from=0.0.0.0/0
max-cache-entries=0
trace=on
log-common-errors=yes
export-etc-hosts=0

**Comment by ahupowerdns** [comment]
Hi John, 
Our github issues are not a support forum. Please see https://www.powerdns.com/opensource.html for how to get help. Meanwhile, you might want to look at dnsdist, which may do what you want. The recursor may also do it, but I'd need to to more. 

   Bert
