### ISSUE TITLE
Add dynamic rule to dnsdist based on uncached query response rate

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#7380]
### Short description
It should be possible to trigger a dynamic block event on clients that are asking for large volumes of uncached results.

### Usecase
Certain hosts create large volumes of uncached queries when directed at dnsdist instances in front of recursive resolvers. These requests might be due to exfiltration tools, or automated scripts that are fetching a giant replay list of previously recorded cache-busting DNS queries, or one of any number of attack models that are intended to be harmful to the recursive resolver by filling the cache with long-lived worthless data. These are valid queries sent at a "reasonable" rate that does not trigger other dynamic rule clamping behavior, but the queries have the unusual behavior in that the results are predictably (high percentage value) uncached.

Large recursive resolver operators would be able to slow down or isolate clients that exceed a certain percentage of query volume that is "uncached" from dnsdist's perspective. This would limit the damage they could inflict on the cache, or on the back-end recursive resolvers from a CPU and memory perspective if they can be isolated to a different pool.

### Description

The desire is to have a trigger that allows slowdown of responses, shifting to a different pool, truncation responses, or any of the other DNSAction results that exist currently.

Using the dnsdist packet cache as a comparison source to determine "uncached" vs "cached" results is sufficient.

It may be necessary to put some conditional tests in before applying these rules. Instances such as when dnsdist is first started and has an empty packet cache might make this rule trigger inappropriately. Timers, or better yet, absolute values of counts of existing cache entries in the dnsdist memory set might be used to gate each rule.

Extra credit: If an arbitrary value TTL re-write could be executed on these results, that might be additionally useful. This would create artificially short cache durations for results sent to hosts that are querying garbage, even if the TTL on the garbage results is very high. This prevents a certain set of denial-of-service attacks from being more harmful. This is almost a separate request of "Add TTL modification to the DNSAction list"

**Comment by johnhtodd** [comment]
This concept is quite similar to https://github.com/PowerDNS/pdns/pull/8274/files

**Comment by rgacogne** [comment]
I'm moving this to the 1.7.0 milestone because I'm planning to release the first 1.6.0 alpha very soon and it's too late for this feature to make it. Still after thinking a bit more about it, I think we might be able to implement something very close by using the fact that all queries make it into the ring buffers, as well as cache misses, but not cache hits. So we coud trigger if at least N queries have been received from a client and the ratio of uncached / cached responses is higher than X. Making sure that the cache is not empty is a very good point, which is a bit complicated by the fact that we might have several caches but I guess we can take a cache as a parameter when adding the rule.
Perhaps it would also make sense to be able to act on the latency of the (uncached?) responses?

**Comment by johnhtodd** [comment]
I think latency is interesting, but that is mixing the information that this model was considering for detection.  Having a separate rule that looks at response latency seems like a better idea than trying to associate uncached results with latency.  It is easy to create extremely fast flows of cache-busting queries that would cause "harm" to memory and CPU, so tying the two together into a single rule seems unwise.  Instead of a timer, perhaps a percentage of memory would need to be full before the rule would be considered?  That could be statically defined in the config and would be predictable more than a timer.

Also: I used terms incorrectly in my description - this isn't a "blocking" rule - it's a matching rule that can then be used to slow, block, truncate, etc. as I descrbe - a minor point, but poor wording choice on my part.
