### ISSUE TITLE
Null records after rectify breaks wildcards

### ISSUE THREAD

**Issue by CSharpRU** [PowerDNS/pdns#7381]
- Program: Authoritative
 - Issue type: Bug report?

### Short description

https://doc.powerdns.com/authoritative/backends/generic-sql.html#rules-for-filling-out-dnssec-fields

There in the documentation you can find some behaviour that breaks wildcard records: "If you have a zone example.com, and a host a.b.c.example.com in it, rectify-zone (and the AXFR client code) will insert b.c.example.com and c.example.com in the records table with type NULL (SQL NULL, not ‘NULL’)."

For example in case if there is record with null type, e.g. c.domain.com, and there is A record for *.domain.com and you are doing dig c.domain.com - ip will not be returned.

### Environment

 - Operating system: CentOS 7
 - Software version: 4.1.5
 - Software source: Operating system repository

### Steps to reproduce

1. Create zone with a.b.c.domain.com record.
2. Rectify it.
3. Add wildcard A record *.domain.com
4. Dig c.domain.com

### Expected behaviour

An IP is returned.

### Actual behaviour

Nothing is returned.

**Comment by mnordhoff** [comment]
Yes, that's correct. Wildcards apply to names that do not exist. Empty non-terminals are names that exist.

You have to do something else, like add `c.domain.com`, `*.c.domain.com` `b.c.example.com` and `*.b.c.example.com` `A` records.

**Comment by mnordhoff** [comment]
And `a.b.c.example.com` and `*.a.b.c.example.com`. :)
