### ISSUE TITLE
"The INCEPTION, INCEPTION-WEEK and EPOCH SOA-EDIT metadata values are marked as deprecated and will be removed in 4.1"

### ISSUE THREAD

**Issue by james-stevens** [PowerDNS/pdns#7384]
According to https://doc.powerdns.com/authoritative/changelog/4.0.html

"The INCEPTION, INCEPTION-WEEK and EPOCH SOA-EDIT metadata values are marked as deprecated and will be removed in 4.1"

We're running 4.1.X and EPOCH is still there and appears to have been fixed and working correctly.

I can't find any reference to EPOCH in https://doc.powerdns.com/authoritative/changelog/4.1.html

We would really like to use EPOCH - do you plan to keep it now ???

**Comment by Habbie** [comment]
This was a mistake in the 4.0 changelog, we will remove EPOCH from that sentence to avoid future confusion. EPOCH is not going away.
