### ISSUE TITLE
Recursor needs 'bounded hashing' query distribution over threads

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7386]
As noted in #7385 the recursor can distribute queries over threads, and does so using a hash. It is however entirely possible that incoming queries do not hash evenly over the threads. In some circumstances (again, see 7385), this is almost guaranteed.

We could of course do round-robin distribution over threads but that would lose us some locality of reference.

We are luckily not the first ones to run into this problem!

Several excellent pages describe an algorithm that hashes queries 'consistently' to workers, but starts distributing queries more widely if the chosen worker is overloaded.

Good links are:

 * https://medium.com/@dgryski/consistent-hashing-algorithmic-tradeoffs-ef6b8e2fcae8
 * https://medium.com/vimeo-engineering-blog/improving-load-balancing-with-a-new-consistent-hashing-algorithm-9f1bd75709ed

In the Recursor, this would likely work by using the MThread numProcesses() function as a metric of how busy a thread is. If this turns out to be too expensive, the number of queries in the pipe could potentially be used.

**Comment by rgacogne** [comment]
Implemented in https://github.com/PowerDNS/pdns/pull/7507, closing.
