### ISSUE TITLE
dnsdist needs a 'bounded hashing' server selection policy

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7387]
See #7386, but then for dnsdist. Could use number of outstanding queries as metric, or QPS. Or perhaps configurable.

In short, this means we hash a query and pick the same server for the same query UNLESS this server is receiving too large a share of traffic or is too busy.

**Comment by rgacogne** [comment]
It might make sense to have "bounded" versions of `whashed` and `chashed`, btw.
