### ISSUE TITLE
 a bug about that gmysql

### ISSUE THREAD

**Issue by wellwang1993** [PowerDNS/pdns#7395]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by wellwang1993** [comment]
sorry，it's my fault，i just think the package should have the gmysql like the sqllite. and I wanna know how should I do？
thanks




| |
西安理工大-王黎-简历
|
|
邮箱：wellwang1993@163.com
|

签名由 网易邮箱大师 定制

On 01/20/2019 20:21, bert hubert wrote:

Closed #7395.

**Comment by Habbie** [comment]
Edit the brew formula to add mysql support, or compile your own pdns_server manually.

**Comment by wellwang1993** [comment]
Fine,i will try tomorrow,thank you so much，i 'm very pleasure to receive your email,it's my honor




| |
西安理工大-王黎-简历
|
|
邮箱：wellwang1993@163.com
|

签名由 网易邮箱大师 定制

On 01/21/2019 00:10, Peter van Dijk wrote:

Edit the brew formula to add mysql support, or compile your own pdns_server manually.

**Comment by wellwang1993** [comment]
i edit the pdns，use --with-modules=gmysql,but it dosenot start work




| |
西安理工大-王黎-简历
|
|
邮箱：wellwang1993@163.com
|

签名由 网易邮箱大师 定制

On 01/21/2019 00:14, wellwang1993 wrote:
Fine,i will try tomorrow,thank you so much，i 'm very pleasure to receive your email,it's my honor




| |
西安理工大-王黎-简历
|
|
邮箱：wellwang1993@163.com
|

签名由 网易邮箱大师 定制

On 01/21/2019 00:10, Peter van Dijk wrote:

Edit the brew formula to add mysql support, or compile your own pdns_server manually.

**Comment by Habbie** [comment]
For support, please use IRC or our mailing lists, see https://www.powerdns.com/opensource.html

**Comment by wellwang1993** [comment]
fine，thank you so much




| |
西安理工大-王黎-简历
|
|
邮箱：wellwang1993@163.com
|

签名由 网易邮箱大师 定制

On 01/21/2019 16:05, Peter van Dijk wrote:

For support, please use IRC or our mailing lists, see https://www.powerdns.com/opensource.html
