### ISSUE TITLE
A bug about libgmysqlbackend.so

### ISSUE THREAD

**Issue by wellwang1993** [PowerDNS/pdns#7396]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Short description

the os is Mac,i use 'brew instal pdns'.when I finished, i find ,there is no libgmysqlbackend.so,but only have libgsqlite3backend.so	and libpipebackend.so.    thus I can't use gmysql
what should I do.
my email is wellwang1993@163.com
thanks

### Environment

 - Operating system: MAC 10.14
 - Software version: 4.1.4
 - Software source: 
Operating system repository
brew instal pens

### Steps to reproduce

1. 
brew instal pdns
2. 
there only have  libgsqlite3backend.so	and libpipebackend.so
3. 

### Expected behaviour

I hope there has libgmysqlbackend.so

**Comment by jpmens** [comment]
This is not a bug. If you had looked at `brew info` you would have seen there is no dependency to MySQL and hence so support in this package for Mysql.

```
$ brew info pdns
pdns: stable 4.1.4 (bottled), HEAD
Authoritative nameserver
https://www.powerdns.com
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdns.rb
==> Dependencies
Build: pkg-config ✔
Required: boost ✘, lua ✔, openssl ✔, sqlite ✔
```
