### ISSUE TITLE
qsizeq stats sometimes wrong

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#7398]
- Program: Authoritative,
 - Issue type: Bug report

### Short description
The value of qsize-q is sometimes wrong (ie once a minute).

Sample output:
```
while true; do pdns_control list| tr ',' '\n'|grep qsize; sleep 0.5; done
qsize-q=0
qsize-q=0
qsize-q=0
qsize-q=0
qsize-q=0
qsize-q=18446744073709551615
qsize-q=0
qsize-q=0
....
....
qsize-q=0
qsize-q=0
qsize-q=0
qsize-q=0
qsize-q=18446744073709551615
qsize-q=0
qsize-q=0
```

18,446,744,073,709,551,615 is actually 2^64 − 1

So, maybe a problem with a race condition decreasing the counter to -1?

### Environment

 - Operating system:  Ubuntu 14.04
 - Software version: pdns 4.1.2
 - Software source: compiled yourself

### Steps to reproduce
while true; do pdns_control list| tr ',' '\n'|grep qsize; sleep 0.5; done

**Comment by rgacogne** [comment]
Looks like we decrease `d_queued` just after the `read()` call from the pipe and increase it just after the `write()` to the pipe, so yes, there is likely a small race. I'd suggest increasing before the `write()`, and decreasing in the unlikely event that it fails.
