### ISSUE TITLE
pdns 4.1.5 lua script fails with "attempt to call global 'matchnetmask' (a nil value)"

### ISSUE THREAD

**Issue by AndrewV666** [PowerDNS/pdns#7409]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

Calling matchnetmask(remoteip, "1.2.3.4") in axfrfilter() function failed with "attempt to call global 'matchnetmask' (a nil value)" exception.

### Environment

 - Operating system: CentOS 7
 - Software version: 4.1.5
 - Software source: PowerDNS repository 

### Steps to reproduce

1.  Create script axfrfilter.lua:
```
function axfrfilter(remoteip, zone, record)
  if record:qtype() == pdns.SOA then
    pdnslog("AXFR from "..remoteip:toString().." for "..qname)
    if matchnetmask(remoteip, "1.2.3.4") then
      pdnslog("modify SOA ")
-- Some extra code here
    end
  end
  return -1
end
```
2. 
Call 
pdns_control retrieve some_zone 
to initiate a zone transfer.

### Expected behaviour

matchnetmask() function should be exported by pdns to lua environment as it was before (in 4.0.x).

### Actual behaviour

Error message in logs:
"Unable to parse record during incoming AXFR of 'xxx' (std::exception): [string "chunk"]:4: attempt to call global 'matchnetmask' (a nil value)"

**Comment by Habbie** [comment]
Given the lack of other reports about this issue since, I'm inclined to consider this just a documentation issue, or to simply close this ticket as any users would have adjusted their scripts by now.
