### ISSUE TITLE
dnsdist: mvRule() can only moves rules up not down

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#7425]
- Program: dnsdist 
 - Issue type: (maybe) Bug report, docs update 

### Short description

according to the [docs](https://dnsdist.org/rules-actions.html?highlight=regex#mvRule) you can move rules around, but what it does not say, is, it seems like that you actually only can move rules _up_ not down as i understand that... 

> to can be one larger than the largest rule, in which case the rule will be moved to the last position

...is indicating.

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 0.0.15920.0.g9b53e78e94
 - Software source: PowerDNS repository

### Steps to reproduce

1. `mvRule(2, 3)`
2. `mvRule(3, 2)`

### Expected behaviour

according to docs, i would expect it wouldn't matter what direction i would move a rule? up vs down

### Actual behaviour

`mvRule(2, 3)` is not moving the rule
`mvRule(3, 2)` do move the rule

**Comment by Habbie** [comment]
> `mvRule(2, 3)` is not moving the rule

You're asking dnsdist to move rule 2 into the position right before rule 3. It is already there. `mvRule(2, 4)` would in fact move the rule down.
