### ISSUE TITLE
LUA: Last character removed from content field after axfrfilter

### ISSUE THREAD

**Issue by marknl** [PowerDNS/pdns#7429]
- Program: Authoritative
- Issue type: Bug report

### Short description
It seems that when you change the content of a record during the axfrfilter function in lua, the last character is removed from the content field.

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: pdns-server-4.1.5-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce
1. Create the following lua script:
```lua
function axfrfilter(remoteip, zone, record)
    if record:qtype() == pdns.NS then
        resp = {}
        resp[1] = {
            qname = record:qname():toString(),
            qtype = record:qtype(),
            ttl = record:ttl(),
            content = 'ns1.domain.net'
        }
        return 0, resp
    end
```
2. pdns_control retrieve mydomain.net
3. check mysql records with: select * from records where domain_id = <domain_id>.

### Expected behaviour
I expect the content field in the database contains 'ns1.domain.net'

### Actual behaviour
The content field contains 'ns1.domain.ne'

### Other information
If you add a space to `content` during the lua function, a correct value will be saved, like so:

`content = 'ns1.domain.net '`

Then the database field contains the correct value, but ofcourse, that's not how it should work.

**Comment by mind04** [comment]
I have encountered the same problem  yesterday.

Workaround:
```
-- Workaround for a bug in 4.1.5 and lower
  content = rr:content()
  if rr:qtype() == pdns.SRV or rr:qtype() == pdns.MX or rr:qtype() == pdns.CNAME or rr:qtype() == pdns.DNAME or rr:qtype() == pdns.NS or rr:qtype() == pdns.PTR
  then
    if content == '.' or string.sub(content, -1) ~= '.'
    then
      content = content .. '.'
    end
  end
    
  local ret={}
  ret[1]={qname=rr:qname():toString(), qtype=rr:qtype(), content=content, ttl=rr:ttl()}
  return 0, ret
```
The problem is setContent() is removing the last dot even when there is no trailing dot present in the name.

**Comment by tik-stbuehler** [comment]
The interesting part is that this didn't happen reliably; the source of entropy is `AuthLua4::axfrfilter` which initializes `DNSResourceRecord rec` based on the order of the keys in the lua hash. So if `qtype` wasn't set yet, `setContent` wouldn't remove the last character, and after the fix won't always remove the trailing dot.

Reopen or open a new bug?

**Comment by rgacogne** [comment]
I wonder if this would fix it (untested):
```
diff --git pdns/lua-auth4.cc pdns/lua-auth4.cc
index f990f18b4..7c963cae5 100644
--- pdns/lua-auth4.cc
+++ pdns/lua-auth4.cc
@@ -117,21 +117,27 @@ bool AuthLua4::axfrfilter(const ComboAddress& remote, const DNSName& zone, const
 
   const auto& rows = std::get<1>(ret);
 
-  for(const auto& row: rows) {
-    DNSResourceRecord rec;
-    for(const auto& col: row.second) {
-      if (col.first == "qtype")
-        rec.qtype = QType(boost::get<unsigned int>(col.second));
-      else if (col.first == "qname")
-        rec.qname = DNSName(boost::get<std::string>(col.second)).makeLowerCase();
-      else if (col.first == "ttl")
-        rec.ttl = boost::get<unsigned int>(col.second);
-      else if (col.first == "content")
-        rec.setContent(boost::get<std::string>(col.second));
-      else
-        throw PDNSException("Cannot understand "+col.first+" in axfr filter response on row "+std::to_string(row.first));
+  try {
+    for(const auto& row: rows) {
+      DNSResourceRecord rec;
+
+      const auto& map = row.second;
+      rec.qtype = QType(boost::get<unsigned int>(map.at("qtype")));
+      rec.qname = DNSName(boost::get<std::string>(map.at("qname")));
+      rec.qname.makeUsLowerCase();
+      if (map.count("ttl")) {
+        rec.ttl = boost::get<unsigned int>(map.at("ttl"));
+      }
+      rec.setContent(boost::get<std::string>(map.at("content")));
+
+      out.push_back(rec);
     }
-    out.push_back(rec);
+  }
+  catch (const std::exception& e) {
+    throw PDNSException("Cannot understand axfr filter response: " + std::string(e.what()));
+  }
+  catch (const PDNSException& e) {
+    throw PDNSException("Cannot understand axfr filter response: " + e.reason);
   }
 
   return true;
```

**Comment by tik-stbuehler** [comment]
Looks good to me. I guess if it compiles it should be fine :)
