### ISSUE TITLE
pdns-geoip does not work behind pdns-recursor

### ISSUE THREAD

**Issue by PalinuroSec** [PowerDNS/pdns#7443]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
Hello, i have configured a hybrid geo-autoritative+recursor server.

On older pdns versions i was able to expose pdns and get geoip requests resolved properly and non-authoritative requests forwarded to the recursor.

Now i have to put pdns behind pdns-recursor, and the geoip backend does not work anymore even if i configured edns support properly on both pdns and pdns-recursor.

### Environment
 - Operating system: Ubuntu Server 18.04
 - Software version:  pdns-server 4.1.1-1 / pdns-recursor 4.1.1-2
 - Software source: Operating system repository

### Steps to reproduce

example pdns.conf
```
guardian=yes
include-dir=/etc/powerdns/pdns.d
launch=
master=yes
setgid=pdns
setuid=pdns
edns-subnet-processing=yes
slave-renotify=yes
version-string=anonymous
expand-alias=yes
resolver=127.0.0.53
local-port=8053
local-address=127.0.0.53
```

recursor.conf
```
allow-from=0.0.0.0/0, ::/0
dnssec=process-no-validate
hint-file=/etc/powerdns/root.hints
local-address=0.0.0.0, ::
local-port=53
quiet=yes
security-poll-suffix=
setgid=pdns
setuid=pdns
ecs-ipv4-bits=24
ecs-ipv6-bits=56
edns-subnet-whitelist=0.0.0.0/0, ::
gettag-needs-edns-options=yes
use-incoming-edns-subnet=yes
forward-zones=domain.tld=127.0.0.53:8053
```

### Expected behaviour
edns tags should be forwarded to the backend and processed as expected.

if incoming packets already contain an edns tag, it should be forwarded as is (except for ecs bits trimming)

### Actual behaviour

the geo-backend works properly (with edns too) when run alone, but it stops working when it is proxied behind pdns-recursor.

**Comment by pieterlexis** [comment]
> i have configured a hybrid geo-autoritative+recursor server.

This sounds you are trying to do resolution and authoritative hosting on the same IP, please see [this page](https://doc.powerdns.com/authoritative/guides/recursion.html) on how to do this properly and [this one](https://dnsdist.org/advanced/ecs.html) on how to handle incoming ECS data with dnsdist. I am closing this issue as this does not seem like a but but a support question. Please see [this site](https://www.powerdns.com/opensource.html) on how to get support from the mailing-lists and/or IRC.
