### ISSUE TITLE
dnsdist 1.3.3: NET SNMP support missing in Debian Stretch packages

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#7449]
- Program:  dnsdist
 - Issue type: Bug report

### Short description
After upgrading to dnsdist 1.3.3 in Debian Stretch gathering SNMP statistics from the daemon is not working any more. dnsdist reports that is is not compiled with NET SNMP support.

Feb 04 13:02:23 rzt-lvs2 dnsdist[21730]: NET SNMP support is required to use snmpAgent()

### Environment

 - Operating system: Debian 9.6 
 - Software version: dnsdist 1.3.3-1pdns.stretch
 - Software source: https://repo.powerdns.com/debian/dists/

### Expected behaviour
dnsdist is compiled with NET SNMP support.

### Actual behaviour

The previous version 1.3.2-1pdns.stretch installed from PowerDNS repo works fine.

Thanks
Ales Rygl

**Comment by rgacogne** [comment]
I _think_ we don't build with SNMP support anymore since we moved to `pdns-builder`, at least it doesn't look like we install `libsnmp-dev` there. Might be related to https://github.com/PowerDNS/pdns/pull/5493 but perhaps @pieterlexis would remember better than I do?

**Comment by pieterlexis** [comment]
It could be indeed that it got lost in translation. I took the downstream debian directory and added new features.

**Comment by zeha** [comment]
IIRC this is because of libssl linkage?

**Comment by pieterlexis** [comment]
except we don't link in openssl into dnsdist afaik

**Comment by pieterlexis** [comment]
We do link in OpenSSL becuase we enabled DoT in the packages by default. For jessie we could do snmp support in jessie (as there is no OpenSSL conflict there) but for stretch we need to make a choice:

1. Keep SNMP disabled so DoT works
2. Attempt to only link in gnutls for DoT and re-enable snmp support 

I am leaning towards 1, as OpenSSL is more performant compared to gnutls and statistics can be gathered in other ways as well (webserver, prometheus, console, carbon)

**Comment by rygl** [comment]
Hi, you are right, there are other ways how to get stats on the other hand, SNMP is here for a long time an definitely will be. We have about ten dnsdist instances for different purposes and abandoning SNMP means quite a lot of work with integration.

Is there a way how to keep it?

**Comment by zeha** [comment]
@pieterlexis IIRC DoT needs libssl 1.1?
If it works with libssl1.0, you could get away with it on stretch by Build-Depending on libssl1.0-dev, libsnmp-dev.

Otherwise my suggestion is to wait for buster.

**Comment by rgacogne** [comment]
DoT should work with libssl 1.0, so building against libssl1.0-dev on stretch might be a solution..

**Comment by rygl** [comment]
Hi. Congrats to the 1.4.0!
I was looking forward to SNMP support ;-) Unfortunately it has not been put back...
Are there any plans to do it in any future non-alpha versions?

**Comment by pieterlexis** [comment]
> DoT should work with libssl 1.0, so building against libssl1.0-dev on stretch might be a solution..

but then we lose TLS 1.2 support (as that is present in OpenSSL 1.1 and not 1.0). I prefer having TLS 1.2 and skip SNMP on stretch. In Debian Buster, net-snmp is linked to OpenSSL 1.1, so we'll re-enable it for buster.

**Comment by rgacogne** [comment]
You probably meant 1.3, right? TLS 1.2 was added in 1.0.1.

**Comment by pieterlexis** [comment]
uhm, yes :)

**Comment by Habbie** [comment]
As this is hard to resolve for stretch, and buster is out now, I suggest closing this ticket.
