### ISSUE TITLE
recursor Unable to load RPZ zone 'rpz.mypdns.cloud' from '127.0.0.1:53'

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#7452]
- Program: Recursor, (maybe also some Authoritative)
 - Issue type: Bug report

### Short description

journal -xefu pdns-recursor | grep rpz
```
Loading RPZ zone 'whitelist.rpz.mypdns.cloud' from [2a01:4f8:1c1c:abe4::53]
Feb 05 17:01:51 pdns_recursor[3457]: Loaded & indexed 0 policy records so far for RPZ zone 'whitelist.rpz.mypdns.cloud'
Feb 05 17:01:51 pdns_recursor[3457]: Unable to load RPZ zone 'whitelist.rpz.mypdns.cloud' from '[2a01:4f8:1c1c:abe4::53]': 'Adding a QName-based filter policy of kind rpz-passthru. but a policy of kind rpz-passthru. already exists for the following QName: .'. (Will try again in 60 seconds...)
Feb 05 17:01:51 pdns_recursor[3457]: Loading RPZ zone 'rpz.mypdns.cloud' from [2a01:4f8:1c1c:abe4::53]
Feb 05 17:01:51 pdns_recursor[3457]: Loaded & indexed 0 policy records so far for RPZ zone 'rpz.mypdns.cloud'
Feb 05 17:01:51 pdns_recursor[3457]: Unable to load RPZ zone 'rpz.mypdns.cloud' from '[2a01:4f8:1c1c:abe4::53]': 'Adding a QName-based filter policy of kind . but a policy of kind . already exists for the following QName: .'. (Will try again in 60 seconds...)
```

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 0.0.15970.0.g70093b3d00
 - Software source: PowerDNS repository

### Steps to reproduce

1. add in recursor.lua
```
rpzMaster({"[2a01:4f9:c010:2166::53]:53","[2a01:4f8:1c1c:abe4::53]:53"}, "whitelist.rpz.mypdns.cloud", {defpol=Policy.NoAction, refresh="60"})
rpzMaster({"[2a01:4f9:c010:2166::53]:53","[2a01:4f8:1c1c:abe4::53]:53"}, "rpz.mypdns.cloud", {defpol=Policy.NXDOMAIN, refresh="60", defttl="604800", axfrTimeout="600"})

```
2. restart pdns-recursor
3. sedund test also fails, in recursor.lua add:
```
rpzFile("/etc/powerdns/whitelist.rpz.mypdns.cloud", {})
rpzFile("/etc/powerdns/rpz.mypdns.cloud", {})
```
2. restart pdns-recursor

### Other information

This is started after the code changes in issue #7296 

To obtain a full version of the rpz zones please use dig axfr
`dig axfr rpz.mypdns.cloud @2a01:4f8:1c1c:abe4::53 >> /etc/powerdns/rpz.mypdns.cloud`
Alternative ip's for the rpz.zone hosted on an Authoritative server please try
`ns0.dns.matrix.rocks or ns1.dns.matrix.rocks`

PS: rec_control reload-zones is not working for rpz zones

A little irc quote for recalling the convensation of the issue:
> so the good news is that I do load the rpz.mypdns.cloud RPZ 
> the bad news is that I do load the rpz.mypdns.cloud RPZ
> ok, defpol=Policy.NoAction makes everything go bad for me
so the default policy overrides any target, including the custom ones
> so rpz.mypdns.cloud.       345600  IN      A       116.203.32.67 turns into rpz.mypdns.cloud.       345600  IN      CNAME .
> and rpz.mypdns.cloud.       345600  IN      A       95.216.209.53 into rpz.mypdns.cloud.       345600  IN      CNAME .
> and then we complain that you have two CNAMEs for rpz.mypdns.cloud.
> it never made sense to me that the "default" policy was overriding everything
> and it's even more painful now
> the more I think about it, the more I'm convinced it should not apply to custom policies
IN TYPE0 . ?
> i thought TYPE# records need to be hex encoded
> oh
> it's the non-empty terminal record

Since this issue have broken down my entire services, I would be extremely happy for any good idea for a workaround on this one, as dig axfr && restart recursor seems like a sad way to get new rpz zones re-loaded

**Comment by Habbie** [comment]
> PS: rec_control reload-zones is not working for rpz zones

Please try `rec_control reload-lua-config`.

**Comment by spirillen** [comment]
> > PS: rec_control reload-zones is not working for rpz zones
> 
> Please try `rec_control reload-lua-config`.

Hi @Habbie That worked as exspected :)
