### ISSUE TITLE
lmdb backend RPM packages missing

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7456]
Our builders do not yet build RPMs for the lmdb backend.

**Comment by mzealey** [comment]
Would appreciate these... :)

**Comment by pieterlexis** [comment]
#7977 was merged, packages for master are in the repo (EL 7 only, no lmdb in EL6 epel) and it is backported so 4.2.0 will come with lmdb backend in packages

**Comment by mzealey** [comment]
@pieterlexis what was blocking el6 - it does appear to be in epel? https://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/l/

**Comment by Habbie** [comment]
Our LMDB C++ wrapper needs Boost 1.53.

**Comment by Habbie** [comment]
Reopened for el7 RPM publishing issues as mentioned in #7977

**Comment by pieterlexis** [comment]
Fixed!

```
pieter@repo1:/srv/repo/centos/x86_64/7/auth-master$ ls *lmdb*
pdns-backend-lmdb-4.2.0-0.rc2.master.186.g1a4847819.1pdns.el7.x86_64.rpm
```
