### ISSUE TITLE
mydns backend has very suspect while statement

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#7474]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

This line very looks very much like an endless loop (unless size() has a side effect).

https://github.com/PowerDNS/pdns/blob/master/modules/mydnsbackend/mydnsbackend.cc#L311

### Description

This should be an if statement.

**Comment by rgacogne** [comment]
Indeed, and I wouldn't be surprised to learn we have more issues in there..
