### ISSUE TITLE
PowerDNS Recursor 4.2-alpha (Ubuntu 18.10/cosmic) lacks include-dir=/etc/powerdns/recursor.d in /etc/powerdns/recursor.conf

### ISSUE THREAD

**Issue by Eihrister** [PowerDNS/pdns#7497]
- Program: Recursor 4.2-alpha on cosmic (maybe bionic, too? not tested) 
 - Issue type: Bug report/Feature request (you pick.. could be counted as both) 

### Short description

pdns-recursor 4.2-alpha's `/etc/powerdns/recursor.conf` lacks `include-dir=/etc/powerdns/recursor.d`.
Upgrades from Ubuntu's own 4.1 to PowerDNS's 4.2 break when upgrading as local configuration is no longer loaded.

### Environment

 - Operating system: Ubuntu 18.10 (cosmic)
 - Software version: 4.2.0~alpha1-1pdns.cosmic
 - Software source: repo.powerdns.com

### Steps to reproduce

1. Install pdns-server from Ubuntu 18.10's own official repository.
2. Note the `include-dir=/etc/powerdns/recursor.d` in `/etc/powerdns/recursor.conf`.
3. Configure the official PowerDNS repository for 18.10 as described on http://repo.powerdns.com/ (I used the 18.04 bionic example, with `s/bionic/cosmic/`.
4. Note the missing `include-dir=/etc/powerdns/recursor.d` in `/etc/powerdns/recursor.conf`.

### Expected behaviour

I expected the upgrade to go without issues (including my local configuration).

### Actual behaviour

Local configuration from the original install was not included, and therefore my instance was down after the upgrade.

**Comment by omoerbeek** [comment]
This is fixed by  https://github.com/PowerDNS/pdns/pull/8418 which is in the rec-4.3.x branch. Is a backport needed/wanted?

**Comment by omoerbeek** [comment]
Closed due to lack of feedback
