### ISSUE TITLE
recursor needs more ecs metrics to expose subnet response sizes

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7498]
### Short description
The PowerDNS recursor support EDNS Client Subnet for outgoing queries. Sometimes ECS auths send back answers for large subnets (/16, for example), but sometimes this also goes down to /25 for highly fragmented networks.

Short of doing a cache dump or a packet capture we currently do not expose what kind of masks we get back from authoritatives.

Although finer grained data would be nice, counters that expose 'ecs-v4-response-bits-32', through to 'ecs-v4-response-bits-1' are a good start. And of course the 128 counters for IPv6....

### Usecase
The usecase is to help debug sudden changes in ECS traffic that happen for no reason.

**Comment by ahupowerdns** [comment]
we might make this an API-only metric btw, I'm not looking forward to sending everyone 160 new metrics every 30 seconds that will mostly be 0.. We already have the concept of 'metrics you have to ask for specifically'. We may have to make this a carbon setting perhaps. Unsure.

**Comment by rgacogne** [comment]
Implemented in #7504.
