### ISSUE TITLE
Recursor Lua's DNSName:equal() does not work as documented

### ISSUE THREAD

**Issue by ncraike** [PowerDNS/pdns#7510]
- Program: Recursor
 - Issue type: Bug report

### Short description
Within the Recursor's Lua scripting, `DNSName:equal()` doesn't accept other `DNSName` values as a parameter, but does seem to accept strings. The Recursor documentation describes [`DNSName:equal`](https://doc.powerdns.com/recursor/lua-scripting/dnsname.html#DNSName:equal) as accepting a `name` parameter of type `DNSName`.

### Environment
 - Operating system: CentOS Linux 7.5
 - Software version: PowerDNS Recursor 4.1.3, Lua 5.1
 - Software source: RPM built from [source tar from PowerDNS.com](https://downloads.powerdns.com/releases/pdns-recursor-4.1.3.tar.bz2).

### Steps to reproduce
Compare a `DNSName` to itself or any other `DNSName` in the Recursor scripting context.

For example, configure the recursor to load this Lua script:
```lua
function preresolve(dq)
    pdnslog("Is example.com. equal to itself?")
    local result = newDN("example.com."):equal(newDN("example.com."))
    pdnslog("result is " .. tostring(result))

    return false
end
```

### Expected behaviour
The script has no affect on DNS queries. Recursor logs should include:
```
Is example.com. equal to itself?
result is true
```

### Actual behaviour
Recursor logs include an STL error and the query fails:
```
Is example.com. equal to itself?
STL error (myexample.com/A from 192.168.32.2): Unable to convert parameter from userdata to Ss
```

### Other information
The Authority's reference documentation for [`DNSName`](https://doc.powerdns.com/authoritative/lua-records/reference/dnsname.html#DNSName) describes `:equal` taking the `name` parameter as a string instead. If a string value is given, the scripting doesn't produce an error, and it *seems* to compare to the `DNSName` correctly. I'm unsure if Authority and Recursor Lua scripting both use the same implementation of `DNSName`.

Using `DNSName:equal()` with a string instead of another `DNSName` does seem to be how the type is used in example code [in other issues](https://github.com/PowerDNS/pdns/issues/4552#issuecomment-356083098).

**Comment by pieterlexis** [comment]
I think you trying to print `result` (a bool) makes this go haywire. Can you try

```lua
function preresolve(dq)
    pdnslog("Is example.com. equal to itself?")
    local result = newDN("example.com."):equal(newDN("example.com."))
    if (result) then
       pdnslog("result is true")
    else
       pdnslog("result is false")
    end
    return false
end
```

**Comment by rgacogne** [comment]
A quick glance at the code suggests that we indeed only define `DNSName:equal(const std::string&)`, be it in master or in 4.1.x.
