### ISSUE TITLE
pdsnsutil fails with Error: Making temporary filename in /tmp/pdnsutil-XXXXXX: No such file or directory

### ISSUE THREAD

**Issue by giannipace** [PowerDNS/pdns#7514]
- Program: Authoritative
 - Issue type: Bug report

### Short description

PowerDNS Authoritative is configured with chroot, e.g.:
chroot=/etc/powerdns

pdnsutil edit-zone fails with the following error:
pdnsutil --config-dir=/etc/powerdns/ edit-zone test-zone.com
Error: Making temporary filename in /tmp/pdnsutil-OQSFRY: No such file or directory 

### Environment

 - Operating system:  CentOS release 6.9
 - Software version:  pdns-4.1.3
 - Software source: PowerDNS repository

### Steps to reproduce

1.  Configure PowerDNS Authoritative with chroot
2. run "pdnsutil edit-zone ZONE" 

### Expected behaviour
pdnsutil edit-zone successfully executed 

### Actual behaviour
Error: Making temporary filename in /tmp/pdnsutil-OQSFRY: No such file or directory

**Comment by cmouse** [comment]
Make sure your chroot has /tmp?

**Comment by giannipace** [comment]
Ok, thanks. I added directory /etc/powerdns/tmp and now I got the following error:

`pdnsutil –config-dir=/etc/powerdns/ edit-zone test-zone.template`
Error: Editing file with: ‘vim /tmp/pdnsutil-o6b2oA’, perhaps set EDITOR variable: Success

**Comment by pieterlexis** [comment]
try `EDITOR=vim pdnsutil –config-dir=/etc/powerdns/ edit-zone test-zone.template`

**Comment by giannipace** [comment]
Yes we  tried but the output is the same:

```
EDITOR=vim pdnsutil --config-dir=/etc/powerdns/ edit-zone test-zone.template
Error: Editing file with: 'vim /tmp/pdnsutil-dZFPui', perhaps set EDITOR variable: Success
```

**Comment by rgacogne** [comment]
That's most likely because you don't have any editor in the chroot.
I think the conclusion here is that if you want to use `pdnsutil` with `chroot` enabled, you need to set up a proper chroot environment and not just an existing directory.

**Comment by Habbie** [comment]
I don't think there's any work to do here, closing the ticket.
