### ISSUE TITLE
pdns and pdns-recursor issues with systemd templates

### ISSUE THREAD

**Issue by tmuncks** [PowerDNS/pdns#7515]
When I install pdns or pdns-recursor from the repo on my Ubuntu 18.04, I end up with the normal service file as well as a template service file for running multiple instances:

```
/lib/systemd/system/pdns-recursor.service
/lib/systemd/system/pdns-recursor@.service

/lib/systemd/system/pdns.service
/lib/systemd/system/pdns@.service

```

For whatever reason, an "instance" is launched from the template service on either package, causing me to end up with two additional services, I did not ask for:
```
pdns-recursor@multi-user.service
pdns@multi-user.service
```

This may be a Systemd thing, because I see this happening for a lot of other services too. However, the service definition for these template services do not have a start condition on the existence of the configuration file, so they always start on boot - and with a default configuration.

That means that - unless I'm lucky - my main service won't start on boot.

Can we stop the multi-user service from being created AND add a contition to the service definitions?

```
ConditionPathExists=/etc/powerdns/pdns-%i.conf
ConditionPathExists=/etc/powerdns/recursor-%i.conf
```

Something like that?

**Comment by tmuncks** [comment]
So the multi-user instances seems to appear, because the raw template services gets enabled as services during install. 
These files:
```
/etc/systemd/system/multi-user.target.wants/pdns@.service
/etc/systemd/system/multi-user.target.wants/pdns-recursor@.service
```
...should never exist, but they do right after installation.

And that causes the @multi-user.service services appear at runtime and the services gets started with no configuration - but enough to keep the real service from starting properly.

**Comment by pieterlexis** [comment]
what version of the auth and recursor are you installing?

**Comment by tmuncks** [comment]
Latest version in the 4.1 branches currently: 
```
pdns-recursor-4.1.11-1pdns.bionic
pdns-server-4.1.6-1pdns.bionic
```
I'm not tied to 4.1, so if it makes sense, I can upgrade. I suspect this is something different though.

**Comment by pieterlexis** [comment]
I don't see this issue with Recursor 4.1.11-1pdns.bionic:

```
root@pieter-bionic-test:~# apt-get install pdns-recursor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libboost-context1.65.1 libluajit-5.1-2 libluajit-5.1-common libprotobuf10 libsensors4 libsnmp-base libsnmp30 libsodium23
Suggested packages:
  lm-sensors snmp-mibs-downloader
Recommended packages:
  pdns-doc
The following NEW packages will be installed:
  libboost-context1.65.1 libluajit-5.1-2 libluajit-5.1-common libprotobuf10 libsensors4 libsnmp-base libsnmp30 libsodium23 pdns-recursor
0 upgraded, 9 newly installed, 0 to remove and 22 not upgraded.
Need to get 3819 kB of archives.
After this operation, 14.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://repo.powerdns.com/ubuntu bionic-rec-41/main amd64 pdns-recursor amd64 4.1.11-1pdns.bionic [1563 kB]
[...]
Setting up pdns-recursor (4.1.11-1pdns.bionic) ...
Creating user and group pdns...done
Created symlink /etc/systemd/system/multi-user.target.wants/pdns-recursor.service → /lib/systemd/system/pdns-recursor.service.
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.12) ...

root@pieter-bionic-test:~# ls -l /etc/systemd/system/multi-user.target.wants | grep pdns
lrwxrwxrwx 1 root root 41 Feb 27 08:27 pdns-recursor.service -> /lib/systemd/system/pdns-recursor.service
```

Similarly, I don't see this after installing the Authoritative Server 4.1.6-1pdns.bionic:

```
Setting up pdns-server (4.1.6-1pdns.bionic) ...

Creating config file /etc/powerdns/pdns.conf with new version

Creating config file /etc/default/pdns with new version

Creating config file /etc/powerdns/pdns.d/pdns.local.conf with new version

Creating config file /etc/powerdns/pdns.d/pdns.simplebind.conf with new version
Created symlink /etc/systemd/system/multi-user.target.wants/pdns.service → /lib/systemd/system/pdns.service.
```

```
root@pieter-bionic-test:~# ls -l /etc/systemd/system/multi-user.target.wants | grep pdns
lrwxrwxrwx 1 root root 32 Feb 27 08:31 pdns.service -> /lib/systemd/system/pdns.service
```

Can you show us exactly *how* you installed these packages (did you do it by hand, did you use some config management?) as I think the issue is not in the packages.

I so like the idea of adding `ConditionPathExists` to the instance service templates though!

**Comment by tmuncks** [comment]
This was done following the instructions on the powerdns repository website - I'll try to outline a way to reproduce. Perhaps I'll learn something in then process...

**Comment by pieterlexis** [comment]
Closing because of lack of response
