### ISSUE TITLE
auth: API-Key per account or zone

### ISSUE THREAD

**Issue by timja** [PowerDNS/pdns#7521]
- Program: Authoritative
 - Issue type: Feature request 

### Short description

Could the api-key authentication be supported to allow for either:
- api-key per account
- api-key per zone
- maybe both?

There are other solutions trying to workaround powerdns not supporting this:
1. https://github.com/ngoduykhanh/PowerDNS-Admin/pull/440
2. https://github.com/catalyst/powerdns-auth-proxy
I searched and couldn't find another issue for this

### Usecase
Have one authoritative DNS server but not give out the API key to multiple consumers, with the api key they could change each others records which they shouldn't be able to do

### Description
For me I would like to be able to create api-keys per account, per-zone would also work too but I don't specifically need that.

**Comment by Habbie** [comment]
Hello @timja,

there are no plans for this. As you say, third party solutions for this exist. We suggest using one of those.

Sorry!

**Comment by My1** [comment]
problem is that obviously tho those third party solutions have full access to the thing tho. having a bit more fine grained control could be neat
