### ISSUE TITLE
Clarify differences between goracle and oracle backends

### ISSUE THREAD

**Issue by ankitkothana** [PowerDNS/pdns#7532]
- Program: Authoritative, Recursor, dnsdist 

### Short description
Went through the documentation regarding support of Generic Oracle and Oracle database. However, it is unclear what is the difference between usage of these 2 backends as both of them require Oracle Server in backend. Could you please clarify differences between these 2 backends and which one is recommended for usage and why.

**Comment by Habbie** [comment]
https://doc.powerdns.com/authoritative/backends/generic-oracle.html says:

> Warning
>
> The Oracle backends depend on non-free software that requires significant resources from us to support. Consequently, we can not provide free support to users of this backend. Before deploying PowerDNS with an Oracle database, please head to our commercial support page.
