### ISSUE TITLE
AAAA NS address is not queried while it is available 

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#7542]
- Program: Recursor 
 - Issue type: Bug report

### Short description

A case where an available AAAA address of a nameserver is not tried, even after the query on the A address fails. 

### Environment

 - Operating system: Linux
 - Software version: Ubuntu 18.04.1 LTS
 - Software source: compiled myself from master 

### Steps to reproduce

dig @127.0.0.1 www.m6k.nl

### Expected behaviour

Three NS addresses tried (2x A, one time AAAA).

### Actual behaviour

Two NS addresses tried (2x A).

### Other information

[log-www.m6k.nl.txt](https://github.com/PowerDNS/pdns/files/2935916/log-www.m6k.nl.txt)

**Comment by rgacogne** [comment]
So it looks like the recursor never sends an outgoing `AAAA` query for a nameserver as long as it gets an `A`. It does look into the records cache for `AAAA` records that might have been picked up as glues, but will only send an outgoing query for `AAAA` if it didn't get any `A` records.

**Comment by rgacogne** [comment]
That code looks untouched since 3.7.x, did not look at older versions.

**Comment by omoerbeek** [comment]
This is a deliberate policy not to burden the common IPv4 case with waiting for AAAA records to arrive.

We might consider asking for AAAA expcicitly if the A records did not work out, or have a much more complex solution querying A and AAAA records simultaneously.

But given the current adoption of IPv6 not really a bug.

**Comment by omoerbeek** [comment]
As an exercise, I have refactored the `SyncRes::getAddrs()` method [here](https://github.com/omoerbeek/pdns/commits/syncRes-getAddrs-loop-unroll). The unrolled loop is easier on the eyes IMO.

**Comment by rgacogne** [comment]
> As an exercise, I have refactored the `SyncRes::getAddrs()` method [here](https://github.com/omoerbeek/pdns/commits/syncRes-getAddrs-loop-unroll). The unrolled loop is easier on the eyes IMO.

Please PR that version (although I'm not a bit fan of the `if (true)` but I can live with it ;)) :+1:

**Comment by omoerbeek** [comment]
https://github.com/PowerDNS/pdns/pull/7548

**Comment by AdamMajer** [comment]
With the default config, the recursor still doesn't find IPv6 only domains. For example, xn--bungsgeln-22a9w.de . It then takes a bit of debugging to arrive here that IPv6 is never queried.

**Comment by Habbie** [comment]
> With the default config, the recursor still doesn't find IPv6 only domains. For example, xn--bungsgeln-22a9w.de . It then takes a bit of debugging to arrive here that IPv6 is never queried.

Does It work if you add `::` to `query-local-address` (or, in any released version, `query-local-address6`)?

**Comment by AdamMajer** [comment]
Yes, adding `::` makes it work when I just add that to `query-local-address`. The default is 0.0.0.0 so only IPv4 are queried. I think it would be better if this worked by default.

**Comment by omoerbeek** [comment]
Fixed since a while.
