### ISSUE TITLE
`delegation-only` should be removed from the recursor

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#7544]
- Program: Recursor
 - Issue type: Feature removal request

### Short description
As far as we know, `delegation-only` is not used on the internet. It also makes for some hairy code in the syncres. It should die.

**Comment by xiaolong-666** [comment]
Hi @omoerbeek I want to solve it if it still works, but have some problems: 
Does it only need to be deleted `delegation-only` from between `pdns/pdns_recursor.cc` and `regression-tests.recursor/TODO`?
Or all files containing `delegation-only` need to be removed?
I am still in the learning stage, hoping to share a power for open source, thanks

**Comment by omoerbeek** [comment]
Hello @xiaolong-666, the idea is not only to remove the setting, but also the associated code, metrics and documentation. That means changes in `pdns_recursor.c`, `syncres.cc`, `ws-recursor.cc` and a few more files. Removing whole files is a bit too much.

**Comment by xiaolong-666** [comment]
@omoerbeek Maybe I made a mistake, it is no longer used anywhere, so all files containing `delegation-only` must be changed.
Including `regression-tests.recursor/TODO`, `pdns/pdns_recursor.cc` , `docs/settings.rst` and a few more files.
Is that so?

**Comment by omoerbeek** [comment]
> @omoerbeek Maybe I made a mistake, it is no longer used anywhere, so all files containing `delegation-only` must be changed.
> Including `regression-tests.recursor/TODO`, `pdns/pdns_recursor.cc` , `docs/settings.rst` and a few more files.
> Is that so?

Yes. All the places where it is used should be changed.

**Comment by xiaolong-666** [comment]
> > @omoerbeek Maybe I made a mistake, it is no longer used anywhere, so all files containing `delegation-only` must be changed.
> > Including `regression-tests.recursor/TODO`, `pdns/pdns_recursor.cc` , `docs/settings.rst` and a few more files.
> > Is that so?
> 
> Yes. All the places where it is used should be changed.

Ok i will finish it as soon as possible, thanks
