### ISSUE TITLE
API Search failed with "Commands out of sync; you can't run this command now"

### ISSUE THREAD

**Issue by Bodenhaltung** [PowerDNS/pdns#7545]
- Program: Authoritative
 - Issue type: Bug report

### Short description
As mentioned on IRC, a search through the PowerDNS api shows with MySQL 8 (in this Case "percona-server 8.0.13_4-1" and "mariadb-libs 10.3.13-3" (dependency from libgmysqlbackend.so) a error.

### Environment

 - Operating system: ArchLinux
 - Software version: powerdns 4.1.6-1, percona-server 8.0.13_4-1, mariadb-libs 10.3.13-3
 - Software source: https://www.archlinux.org/packages/community/x86_64/powerdns/

### Steps to reproduce
1. API Search with MySQL 8

### Expected behaviour
Search Response. ;-)

### Actual behaviour
>  Mar 07 10:10:08 devsrv pdns_server[28673]: HTTP Request "/api/v1/servers/localhost/search-data": Authentication by API Key failed
> Mar 07 10:10:19 devsrv pdns_server[28673]: Query: select domains.id, domains.name, records.content, domains.type, domains.master, domains.notified_serial, domains.last_check, domains.account from domains LEFT JOIN records ON records.domain_id=domains.id AND records.type='SOA' AND records.name=domains.name WHERE records.disabled=0 OR ?
Mar 07 10:10:19 devsrv pdns_server[28673]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE name LIKE ? OR content LIKE ? LIMIT ?
Mar 07 10:10:19 devsrv pdns_server[28673]: Query: SELECT domain_id,name,type,modified_at,account,comment FROM comments WHERE name LIKE ? OR comment LIKE ? LIMIT ?
Mar 07 10:10:19 devsrv pdns_server[28673]: HTTP ISE for "/api/v1/servers/localhost/search-data": Exception: GSQLBackend unable to execute query: Could not get next result from mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE name LIKE ? OR content LIKE ? LIMIT ?: Commands out of sync; you can't run this command now`

> ldd /usr/lib/powerdns/libgmysqlbackend.so
        linux-vdso.so.1 (0x00007fff5ebcd000)
        libmariadb.so.3 => /usr/lib/libmariadb.so.3 (0x00007f1f0a3f6000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f1f0a1df000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1f0a1da000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1f0a1b9000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f1f0a129000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f1f09e55000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1f09cc4000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f1f09b3f000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1f0997b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1f09961000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1f0a46d000)

**Comment by Habbie** [comment]
Compiling pdns 4.1.6 or master on Arch, against that same libmariadbclient, reproduces the API search issue. Tested with Percona, Maria 10.2.12, 10.3.13, MySQL 8.0.15 servers running on macOS.

**Comment by Habbie** [comment]
After upgrading the maria libs on macOS from 10.2.12 to 10.3.13, pdns on macOS fails too.

This is not an Arch issue.
