### ISSUE TITLE
After the port is modified to 5300, the master and slave nodes cannot synchronize.

### ISSUE THREAD

**Issue by jiangby123** [PowerDNS/pdns#7547]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

**Comment by Habbie** [comment]
Hello,

this is the third useless, empty ticket you have opened. Every time before, we have pointed you to our [documentation](https://doc.powerdns.com/) and our [support channels](https://www.powerdns.com/opensource.html). Please use those to reach out to us if you need help.

Please do not post issues on our GitHub again unless you have an actual bug to report. Thank you.

**Comment by jiangby123** [comment]
> 你好，
> 
> 这是你打开的第三张无用的空票。之前，我们已经向您指出了我们的[文档](https://doc.powerdns.com/)和[支持渠道](https://www.powerdns.com/opensource.html)。如果您需要帮助，请使用这些与我们联系。
> 
> 除非您有实际的错误报告，否则请不要再次在我们的GitHub上发布问题。谢谢。

Give you trouble
I just follow the configuration in the documentation, the support email is sent, but no reply

**Comment by Habbie** [comment]
> the support email is sent, but no reply

When and where did you send the email?

**Comment by jiangby123** [comment]
> > 支持电子邮件已发送，但没有回复
> 
> 您何时何地发送电子邮件？

![image](https://user-images.githubusercontent.com/47846791/54104196-e510f900-4409-11e9-9fd1-e62954caa94d.png)

**Comment by Habbie** [comment]
I see an email from you just now. Let's hope somebody replies!

I'm closing conversation on this ticket.
