### ISSUE TITLE
Error: GSQLBackend unable to feed record

### ISSUE THREAD

**Issue by eric-gunn** [PowerDNS/pdns#7557]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

pdnsutil encounters an error when trying to create a new zone:

```
pdnsutil create-zone example.com ns1.example.com
Creating empty zone 'example.com'
Error: GSQLBackend unable to feed record: Could not prepare statement: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values (?,?,?,?,?,?,?,?,?,NULL): Unknown column 'change_date' in 'field list'
```

### Environment

 - Operating system: Ubuntu 16.04
 - Software version:
```
PowerDNS Authoritative Server 4.1.6 (C) 2001-2018 PowerDNS.COM BV
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
```
 - Software source: PowerDNS repository

### Steps to reproduce

**Note:** 
Database configured according to the following instructions:
https://doc.powerdns.com/authoritative/guides/basic-database.html

**Configuration files:**
[pdns_config.zip](https://github.com/PowerDNS/pdns/files/2949863/pdns_config.zip)

1. `root@ubuntu:~# pdnsutil create-zone example.com ns1.example.com`

### Expected behaviour

pdnsutil should create zones without error.

### Actual behaviour

```
pdnsutil create-zone example.com ns1.example.com
Creating empty zone 'example.com'
Error: GSQLBackend unable to feed record: Could not prepare statement: insert into records (content,ttl,prio,type,domain_id,disabled,name,ordername,auth,change_date) values (?,?,?,?,?,?,?,?,?,NULL): Unknown column 'change_date' in 'field list'
```

**Comment by rgacogne** [comment]
Sorry, it looks like we missed at least one occurrence in https://github.com/PowerDNS/pdns/pull/7268 :-/

If you look at the documentation for your exact backend you should have a link to the proper schema for 4.1.x, as this one is for 4.2.0. For example if your backend is gmysql, https://doc.powerdns.com/authoritative/backends/generic-mysql.html#default-schema will lead you to https://github.com/PowerDNS/pdns/blob/rel/auth-4.1.x/modules/gmysqlbackend/schema.mysql.sql

**Comment by eric-gunn** [comment]
@rgacogne, that was it. Thank you!
