### ISSUE TITLE
dnsdist master LuaAction to set RCODE fails with EDNS queries

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7563]
The following dnsdist.conf snippet:
```
function servfailaction()
    return DNSAction.Refused, ""  
end
addLuaAction(NotRule(RDRule()), servfailaction)
```
Works fine on queries with no EDNS. With EDNS however, it returns the following:
```
;; ->>HEADER<<- opcode: QUERY, status: ?261, id: 15605
```

Without EDNS, the result is ok, except that we echo the AD bit which may not be the greatest thing to do. 

I looked into this but it appears to be Weird how this could happen.

**Comment by ahupowerdns** [comment]
The weirdness may reside in 'dig' getting the extended RCODE and that we don't zero it or something like that.

**Comment by ahupowerdns** [comment]
If I try without Lua, it gets even weirder:

```
addLuaAction(NotRule(RDRule()), RCodeAction(dnsdist.SERVFAIL))
```
Leads to the output of:
```
> LuaAction failed inside lua, returning ServFail: attempt to call a userdata value
```
This also happens for dnsdist.REFUSED.

**Comment by rgacogne** [comment]
> addLuaAction(NotRule(RDRule()), RCodeAction(dnsdist.SERVFAIL))

addAction(NotRule(RDRule()), RCodeAction(dnsdist.SERVFAIL))

**Comment by ahupowerdns** [comment]
[weird.zip](https://github.com/PowerDNS/pdns/files/2952474/weird.zip)
