### ISSUE TITLE
HTTP Remote Backend wrong host

### ISSUE THREAD

**Issue by fredericosilva** [PowerDNS/pdns#7573]
- Program: Authoritative
 - Issue type: Bug report

### Short description

I'm observing a really strange scenario where pdns is making http calls to the wrong url 'remote-connection-string=http'.

### Environment

 - Operating system: Alpine 3.9.2
 - Software version: 4.1.5
 - Software source: Operating system repository

### Steps to reproduce

1. using the following config file
```
$cat pdns.conf

launch=remote
remote-connection-string=http:url=http://192.168.0.87:3000/dnsapi
```
2.  query (this makes a query to google.com:80/SOA)
```
dig test@google.com @localhost
```
3. sniff http calls
```
GET /SOA HTTP/1.1
Accept: application/json
Connection: Keep-Alive
Host: google.com.
User-Agent: YaHTTP v1.0
X-Remotebackend-Local: 0.0.0.0
X-Remotebackend-Real-Remote: 0.0.0.0/0
X-Remotebackend-Remote: 0.0.0.0
X-Remotebackend-Zone-Id: -1
...

HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1564
Date: Wed, 13 Mar 2019 14:44:40 GMT

```

**Comment by pieterlexis** [comment]
the `@` in the name might confuse things, cna you show the sniff for `dig @loclahost test.google.com`?

**Comment by fredericosilva** [comment]
@pieterlexis that works properly, the problem is the ```@```. I thought it might have some internal/undocumented usage.

**Comment by rgacogne** [comment]
Thank you for reporting this!
Looking at the code, I think I see where the issue lies. Let's see if @cmouse wants to have a look first, otherwise I'll handle it.

**Comment by ad-m** [comment]
It seems that the crafted DNS requests allows using unauthorized requests to temporarily break authorative DNS server, it mean DoS. Should there be a CVE for the issue assigned? Is this issue bug-bounty eligible?

**Comment by ad-m** [comment]
It should be emphasized that this affects other DNS server responses, not just one specific one. We note the problem that it allowed to disrupt the DNS server and affect the operation of the DNS server for other requests from other clients. In the extreme case, I imagine that this allows the request to be directed to a malicious backend, and consequently to modify any DNS response, and consequently to a phishing attack, or pass DNS validation and obtaining an SSL certificate.

**Comment by ahupowerdns** [comment]
We are aware @ad-m, thank you. Please also see https://doc.powerdns.com/recursor/common/security-policy.html
