### ISSUE TITLE
DNS compression should be case-sensitive

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#7581]
- Program: Authoritative
 - Issue type: Bug report

### Short description
PowerDNS is case-insensitive when performing label compression. For example, when XFR a zone, the case of hostnames on the right side (rdata) may be changed and slaves may answer with different case than the master.

### Environment
 - Operating system: Ubuntu 14.04
 - Software version: 4.1.5
 - Software source: self compiled

### Steps to reproduce
1. Add a rdata hostname with capital letters
2. Add a rdata hostname (with common lables) with lowercase letters
3. Perform AXFR, the rdata received is not identical to the rdata configured above

### Expected behaviour
Case of rdata should be preserved.

### Actual behaviour
Case of rdata may be changed, according to the first version of a label

### Other information
I tested with Bind9. Bind 9 preserves the case by using case-sensitive label compression. See also https://indico.dns-oarc.net/event/20/contributions/265/attachments/254/471/ISC-case-sensitivity.pdf Slide 12.

### Zone as configured in PDNS-DB:
```
example.com.	SOA	sec1.rcode0.net. rcodezero-soa.ipcom.at. 2019031507 10800 3600 604800 3600	3600
example.com.	NS	sec1.rcode0.net.	3600
example.com.	NS	sec2.rcode0.net.	3600
example.com.	MX	100 MAIL.GOOGLE.COM.	86400
example.com.	MX	30 MAIL.GOOGLE.org.	86400
www.example.com.	CNAME	www.foobar.com.	86400
www2.example.com.	CNAME	www.example.ORG.	86400
```

You see, the CNAME always use the inverse case of the MX for the TLD (com/org)

Now, when transferring the domain, the rdata of MX and CNAME gets changed:

```
; <<>> DiG 9.10.3-P4-Debian <<>> axfr example.com
; (1 server found)
;; global options: +cmd
example.com.            3600    IN      SOA     sec1.rcode0.net. rcodezero-soa.ipcom.at. 2019031508 10800 3600 604800 3600
example.com.            3600    IN      NS      sec1.rcode0.net.
example.com.            3600    IN      NS      sec2.rcode0.net.
example.com.            86400   IN      MX      100 MAIL.GOOGLE.com.
example.com.            86400   IN      MX      30 MAIL.GOOGLE.org.
www2.example.com.       86400   IN      CNAME   www.example.org.
www.example.com.        86400   IN      CNAME   www.foobar.com.
example.com.            3600    IN      SOA     sec1.rcode0.net. rcodezero-soa.ipcom.at. 2019031508 10800 3600 604800 3600
;; XFR size: 8 records (messages 3, bytes 433)
```

```
example.com.            86400   IN      MX      100 MAIL.GOOGLE.com.
```

Here rdata should be MAIL.GOOGLE.COM. The lowercase com. is inherited from "example.com."

```
www2.example.com.       86400   IN      CNAME   www.example.org.
```

Here the rdata should be www.example.ORG., but "org." is inherited from the the MX rdata "MAIL.GOOGLE.org."

**Comment by pieterlexis** [comment]
Hi Klaus,

Does this lead to any operational issues other than "this looks ugly"?

**Comment by klaus3000** [comment]
Yes - first time we saw that. There seems to some applications which are strict (and buggy) about rdata (in this case CNAME) and during inbound AXFR the case was changed to uppercase as this customer had entered the MX targets with capital case on his master.

**Comment by pspacek** [comment]
Hi, here is opinion from another DNS software vendor:
This is clearly bug in the client and should be fixed there. Knot DNS also does case-insensitive compression, and moreover lower cases all data while loading zone.

Adding workarounds to server side is counterproductive because it increase costs to everyone else except the party who implemented DNS incorrectly. That is not good for the overall ecosystem.

**Comment by Habbie** [comment]
> Yes - first time we saw that. There seems to some applications which are strict (and buggy) about rdata (in this case CNAME) and during inbound AXFR the case was changed to uppercase as this customer had entered the MX targets with capital case on his master.

Can you clarify this some more? Is the buggy application an AXFR client? Or some application that talks to a resolver? Can you perhaps tell us what the buggy application is?

**Comment by klaus3000** [comment]
@pspacek I see your point, although in my opinion it is not a workaround while deciding to use case sensitive or insensitive compressen. Hopefully you do not lowercase inside TXT records.

@Habbie The problem came up when the customer added CNAMEs for Zendesk, as described here: https://support.zendesk.com/hc/en-us/articles/203683886-Allowing-Zendesk-to-send-email-on-behalf-of-your-email-domain#topic_sx4_wqp_l2b
I do not know what the exact problem was, I will try to find out more details.

**Comment by klaus3000** [comment]
Answer from the customer: "It was a validation for Zendesk that failed so the client couldn't set it up."

So, I would implement it like Bind, but probably there are more important bugs to fix.

**Comment by Habbie** [comment]
> @pspacek I see your point, although in my opinion it is not a workaround while deciding to use case sensitive or insensitive compressen. Hopefully you do not lowercase inside TXT records.

Of course not!

> The problem came up when the customer added CNAMEs for Zendesk

So there was a resolver in between - perhaps that makes it a resolver question, not an auth question?

> I do not know what the exact problem was, I will try to find out more details.

Please do - so far there it nothing in here that would convince us to make our packets bigger to cater to some unknown bug in a piece of client software.

> So, I would implement it like Bind, but probably there are more important bugs to fix.

I looked around a bit. Knot DNS and Resolver, Unbound, 8.8.8.8 - none of them preserve case, all preferring to compress as efficiently as possible even if it causes case mixing. That, plus RFC4343 which clearly says that compression goes before case preservation, tells me there is no PowerDNS bug here.

**Comment by omoerbeek** [comment]
In general compression is based on the case-insensitive identity of labels. But https://tools.ietf.org/html/rfc5936 section 3.4 states AXFRs are special and should do a cases-sensitive compression.

**Comment by omoerbeek** [comment]
Collected some more data.

I'm using the term "case-preserving" and "case-squashing" here, since the bind document is very confusing in this regard. What bind calls "case-insensitive compression" I'm calling "case-preserving". 

* bind is case-preserving by default for both queries and AXFRs. There is a config option `no-case-compress` that changes this behavior for queries only, AXFRs are always case preserving.

* nsd always squashes to lowercase for both queries and AXFRs. I have found no config option to tune this.

Not that matching is always performed while equating upper and lower case (i.e. case-insensitive in the regular, not bind docs meaning).

**Comment by zeha** [comment]
Given the milestones have been moved - is this something that the PowerDNS Auth actually wants to do, or would patches be rejected anyway?

**Comment by Habbie** [comment]
I'd rather take a patch to always lowercase everything :)

**Comment by Habbie** [comment]
Closing this in favour of #4690.
