### ISSUE TITLE
Travis build failure: Hash Sum mismatch

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#7600]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Bug report

### Short description
Travis CI performs `apt-get update` which relies on apt. Historically, apt suffers from a [race condition](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/972077) which means that it will randomly/occasionally fail to update because some of the files will change between reads.

### Environment
 - Operating system: ubuntu 14 (because the ubuntu 16 pr hasn't been merged ...)
 - Travis CI

### Steps to reproduce
1. Create a PR (spelling ones like #7598 are good examples)
2. Wait for Travis to run
3. See [Travis fail](https://travis-ci.org/PowerDNS/pdns/jobs/508578188)

### Expected behaviour
Build should pass, it's a spelling fix...

### Actual behaviour
```sh
$ sudo apt-get -qq update
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get -qq update" failed and exited with 100 during .
```

### Other information
There's a "fix" for this called `Acquire-By-Hash` and it was [backported to trusty](https://blog.packagecloud.io/eng/2016/10/17/apt-by-hash-backport-ubuntu-trusty-precise/)

### Usecase
PRs w/ CI in Travis

### Description

**Comment by omoerbeek** [comment]
Travius is out
