### ISSUE TITLE
Raspbian Stretch Builds for Current Stable Versions

### ISSUE THREAD

**Issue by scolby33** [PowerDNS/pdns#7606]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: request 

### Short description

It would be great to have packages built for Raspbian Stretch for the current stable versions instead of just the master/unreleased versions.

If possible, please add builds for:

- Raspbian 9 (Stretch) Authoritative Server 4.1 series
- Raspbian 9 (Stretch) dnsdist 1.3 series
- Raspbian 9 (Stretch) PowerDNS Recursor 4.1 series

Thank you!

**Comment by pieterlexis** [comment]
Adding support for this in the build infra used for recursor 4.1 and auth 4.1 is a lot of work. For the upcoming 4.2 releases of both products, there will be Raspbian Stretch packages. For the upcoming dnsdist 1.3.4, we will have Raspbian Stretch packages.

**Comment by scolby33** [comment]
I understand! Thank you for the prompt reply.
