### ISSUE TITLE
mysql and pipe backend in a row

### ISSUE THREAD

**Issue by 7c** [PowerDNS/pdns#7612]
I am using pdns-server-4.0.7 on 5 servers. ns1 is the mysql master and ns2.3.4.5 do replicate. I am using mysql backend and pipe backend.

Imagine a notadded.com  which points to ns1..5 but is not added to the mysql as a domain.
I have a backend configuration like this:

```
# MySQL Configuration
#
# Launch gmysql backend
launch=gmysql

# gmysql parameters
gmysql-host=127.0.0.1
gmysql-port=3306
gmysql-dbname=pdns
gmysql-user=pdns
gmysql-password=*****
gmysql-dnssec=yes
# gmysql-socket=

# Pipe Backend
pipe-command=/opt/pdnspipe3/pdnspipe3.js
pipe-abi-version=1
launch+=pipe
```

if i dig notadded.com @ns1 i am getting refused

`** server can't find host-1-2-3-4-ru.au***.com: REFUSED`

```
$ dig host-1-2-3-4-ru.auzc.com @ns1.biz

; <<>> DiG 9.10.3-P4-Ubuntu <<>> host-1-2-3-4-ru.auzc.com @ns1.biz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 18313
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;host-1-2-3-4-ru.au***.com.	IN	A

;; Query time: 105 msec
;; SERVER: 52.14.102.132#53(52.14.102.132)
;; WHEN: Thu Mar 21 11:31:12 UTC 2019
;; MSG SIZE  rcvd: 53
```

I am not sure if my expectation is wrong but.... i assumed that pdns goes in the order of backends. First mysql (not found) then next it should go to pipe backend and ask for that. I am logging every query on pipe backend but there is no question about requested host from notadded.com. So the refused comes from mysql backend.

My idea was to be able to answer to notadded domains from pipe backend if mysql does not have this domain inside. Isnt it the way how backends should work? especially launch+= implies this behaviour.

**Comment by Habbie** [comment]
What @cmouse said. When you go to IRC or the mailing list for support, please do not edit anything, like dig output, except to hide passwords.
