### ISSUE TITLE
dnsdist: LMDBRule

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#7618]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

It would be very nice to be able to do a fast lookup into a `LMDB` database and route the query based on the results. Now the hard part is to make it generic enough that we can select the key, for example to do a lookup based on the exact source IP address or a qname if we want, but also decide what to do with the result of the lookup.
Since we have tag-based routing in dnsdist now, I wonder if the lookup should just return a tag and let subsequent rules do the needful based on that tag.

**Comment by neilcook** [comment]
tag-based routing seems like a good idea to me.

**Comment by neilcook** [comment]
There is also the issue that dnsdist only knows about IP addresses, and for filtering scenarios we'd probably want to do routing based on the user. This implies that we'd need to be able to do one lookup based on e.g.source IP address, and then a second lookup based on the result of the first lookup, i.e. use the result of the first lookup as the key to the second lookup.

**Comment by rgacogne** [comment]
Right, so the LDMBRule needs to be able to use the content of a tag as the lookup key, seems doable.

**Comment by zeha** [comment]
One larger dnsdist user currently has custom code returning the data as a tag, so they'd like that.

**Comment by Habbie** [comment]
> One larger dnsdist user currently has custom code returning the data as a tag, so they'd like that.

From a CDB, to be clear - but that's a minor detail on the scale of this idea.

**Comment by rgacogne** [comment]
Implemented in #8139.
