### ISSUE TITLE
Patch: IP_PMTUDISC_OMIT on IPv4/UDP for mitigating fragment attack

### ISSUE THREAD

**Issue by hdais** [PowerDNS/pdns#7619]
- Program: Authoritative
 - Issue type: Feature request (patch attached)

### Description
Linux 3.15 introduced a new socket option [IP_PMTUDISC_OMIT](https://lists.openwall.net/netdev/2014/02/26/4) which makes sockets ignore PMTU information and send packets with DF=0. With this sockopt fragmentation is allowed if and only if the packet size exceeds the outgoing interface MTU or the packet encounters smaller MTU link in network. Note that FreeBSD already has same semantics without setting the option.

By preventing forged PMTU information, setting IP_PMTUDISC_OMIT to DNS responder's IPv4/UDP socket mitigates [DNS fragmentation attacks](https://ripe67.ripe.net/presentations/240-ipfragattack.pdf). Some DNS implementations already have this feature: [Unbound](https://github.com/NLnetLabs/unbound/commit/470b7bda8763c36a7db255d1d981f3ae06d41ba0), [NSD](https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=4235), [BIND9](https://www.isc.org/blogs/bind-april-2017/)

Patches for pdns-4.1.8 , 4.2.0-rc1 to set IP_PMTUDISC_OMIT to IPv4/UDP sockets (if available) attached. It would be appreciated if this patch be applied to mainline.

### Environment
 - Operating system: Linux
I have tested this patch on Ubuntu 18.04.

### Patches
[pdns-4.1.8-pmtudisc_omit.patch.txt](https://github.com/PowerDNS/pdns/files/2999144/pdns-4.1.8-pmtudisc_omit.patch.txt)
[pdns-4.2.0-rc1-pmtudisc_omit.patch.txt](https://github.com/PowerDNS/pdns/files/2999148/pdns-4.2.0-rc1-pmtudisc_omit.patch.txt)

**Comment by rgacogne** [comment]
See #7410.

**Comment by rgacogne** [comment]
Closing since we just merged #7410.
