### ISSUE TITLE
don't be too verbose about short response packets

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#762]
During some bulktest runs, there are lots of lines that look like

```
May 03 11:04:10 Unable to parse packet from remote server 188.165.57.96: Error parsing packet of 12 bytes (rd=0), out of bounds: vector::_M_range_check
```

These packets are too short to contain anything useful; we should only log them when log-common-errors is set.

**Comment by pieterlexis** [comment]
This error is already behind log-common-errors since forever (aab4adb093). Can it be that log-common-errors is/was enabled for these tests?

**Comment by rgacogne** [comment]
Note that https://github.com/PowerDNS/pdns/pull/6503 will discard this kind of packets earlier, and will only log about it when `quiet` is not set.
