### ISSUE TITLE
Loadbalancing Server Policies per Pool

### ISSUE THREAD

**Issue by bizkut** [PowerDNS/pdns#7659]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

Hi, is it possible to assign setServerPolicy() per Pool and not as a global? Thank you.

### Environment

 - Operating system: Ubuntu
 - Software version: 18.04
 - Software source: PowerDNS repository 

### Steps to reproduce

1. 
2. 
3.

**Comment by ahupowerdns** [comment]
GitHub is not a support forum for PowerDNS. Please head to https://www.powerdns.com/opensource.html and explain your problem there.
