### ISSUE TITLE
Powerdns master don't update slave, with error: Received NOTIFY for “example.com” which we are not authoritative (Refused)

### ISSUE THREAD

**Issue by petarkozic** [PowerDNS/pdns#7660]
Please someone if can help me. Two days I reading documentation and trying but I can't find solution for this problems.

I have powerdns "cluster" with one master and three slaves servers which works last few years without problems. After some update, I don't right know how, I have problem with replication from master to slave.

When I add new zone to master or/and change that new zone I get error in log of slaves server: Received NOTIFY for "example.com" which we are not authoritative (Refused)

This don't happen on domain which already added before, because I supposed that some update kill my communication ?

I tried to find some useful info in the documentation but without success. I checked all firewall rules for anyway, there is no issue.

I'm using mysql as backend on all servers.

Here is a config for my master (ns1):
```
launch=gmysql
gmysql-host=localhost
gmysql-port=3006
gmysql-dbname=powerdns_db
gmysql-user=db_user
gmysql-password=some_password

soa-minimum-ttl=3600
soa-refresh-default=10800
soa-retry-default=3600

allow-axfr-ips=ns2.ip.adress,ns3.ip.address,ns.4.ip.address
config-dir=/etc/powerdns
daemon=yes
disable-axfr=no
guardian=yes
local-address=0.0.0.0
local-port=53
log-dns-details=on
loglevel=5
module-dir=/usr/lib/x86_64-linux-gnu/pdns
master=yes
slave=no
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=powerdns
include-dir=/etc/powerdns/pdns.d

api=yes
api-key=some_key
```

Here is a config of my slave servers:
```
launch=gmysql
gmysql-host=localhost
gmysql-port=3006
gmysql-dbname=powerdns_db
gmysql-user=db_user
gmysql-password=some_password

soa-minimum-ttl=3600
soa-refresh-default=10800
soa-retry-default=3600

config-dir=/etc/powerdns
daemon=yes
disable-axfr=yes
guardian=yes
local-address=0.0.0.0
local-port=53
log-dns-details=on
loglevel=5
module-dir=/usr/lib/x86_64-linux-gnu/pdns
master=no
slave=yes
slave-cycle-interval=60
setgid=pdns
setuid=pdns
socket-dir=/var/run
version-string=powerdns
#include-dir=/etc/powerdns/pdns.d

api=yes
api-key=some_key
```

This setup works as I said for a few years. Now I get a message in the log: Received NOTIFY for "example.com" which we are not authoritative (Refused)

But if I

dig example.com I get valid NS record:
```
;; ANSWER SECTION:
example.com.            3600    IN  NS  ns4.my-domain.net.
example.com.            3600    IN  NS  ns3.my-domain.net.
example.com.            3600    IN  NS  ns1.my-domain.net.
example.com.            3600    IN  NS  ns2.my-domain.net.
```

**Comment by gertvdijk** [comment]
Which version are you using? Depending on that, the following may apply to you.

I noticed that supermaster/superslave feature is now turned off by default ([added to docs in this pending PR](https://github.com/PowerDNS/pdns/pull/7645/commits/52c74538093b13b63e94bf9efc48bd425fff9d39)), meaning that NOTIFYs sent to slaves which are not configured as a slave for that zone, you will get the message you're receiving right now.

Your options are:
* explicitly enable supermaster/superslave support
* provision all slaves with newly added zone, just like you do with the master, but as type=Slave
* move to native replication (MySQL)

**Comment by TiagoTT** [comment]
I have hit a similar problem and found that the `superslave` setting was missing (like it is missing on the configuration files pasted in this issue).

See: https://doc.powerdns.com/authoritative/settings.html#superslave

Before this setting existed and with the default value this setting had before version 4.2.0, the `superslave` feature would be enabled. But in version 4.2.0 the default value changed and the `superslave` feature became disabled by default.

**Comment by JellyBool** [comment]
@TiagoTT Where should I put `superslave` settings? On Master or Slave?
