### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by jayuniversal** [PowerDNS/pdns#7664]
I just wanted to know if PowerDNS auto updates after releases if so how long does it take?

**Comment by Habbie** [comment]
PowerDNS does not auto-update, but your RPM or Debian-based distribution might auto-update. If you combine that with https://repo.powerdns.com/, you might end up with automatic PowerDNS updates.

For further support questions, please find us on IRC or our mailing lists via https://www.powerdns.com/opensource.html

**Comment by jayuniversal** [comment]
Thanks for your quick reply you mind telling me where i can check to see?

**Comment by Habbie** [comment]
For further support questions, please find us on IRC or our mailing lists via https://www.powerdns.com/opensource.html
