### ISSUE TITLE
gmysql-thread-cleanup option documented incorrectly

### ISSUE THREAD

**Issue by aaronm-cloudtek** [PowerDNS/pdns#7680]
- Program: Authoritative
 - Issue type: Bug report (documentation)

### Short description
The documentation for the Generic MySQL backend incorrectly gives the parameter name `gmysql-thread-closer`, but it should really be `gmysql-thread-cleanup`.

### Environment
N/A

### Steps to reproduce
N/A

### Expected behaviour
N/A

### Actual behaviour
N/A

### Other information
N/A

**Comment by Habbie** [comment]
Fixed in #7684
