### ISSUE TITLE
Multiple checks for newServer

### ISSUE THREAD

**Issue by WilliamDEdwards** [PowerDNS/pdns#7682]
- Program: dnsdist
 - Issue type: Feature request

### Short description
I would like to add multiple checks to servers to determine server availability. Currently, I have this:

`newServer({address="address", qps=100, checkType="AAAA", checkType=DNSClass.CHAOS, checkName="zone.nl.", mustResolve=true, pool="primary"})`

### Usecase
In case `zone.nl` stops resolving because it has been deleted, no servers would be available, even though other zones do resolve. I could add different checks to servers to resolve different zones, but that would get confusing.

### Description
Therefore, it'd be great if multiple checks can be executed to determine server availability. For example, dnsdist could try to resolve 4 zones, and only if 3 out of 4 can't be resolved, the server is marked down.

**Comment by rgacogne** [comment]
I'm closing this feature request since no-one seemed interested enough to work on it, and as far as I know this has not been requested by anyone else.
