### ISSUE TITLE
gsql getAllDomainMetadata() does not get all domain metadata

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7705]
For reasons which probably made sense at the time, the gsql getAllDomainMetadata() call filters out DNSSEC related metadata (PRESIGNED, NSEC3PARAM, NSEC3NARROW). This in turn makes that these items are not shown in the pdnsutil show-zone meta display. It shows them in other ways though.

It also means that b2b-migrate does not migrate these vital settings, leading to broken servers.

A quick scan of the code appears to show no harm would be done by simply removing this filtering from `getAllDomainMetadata()`.

**Comment by Habbie** [comment]
Fixed in #7706
