### ISSUE TITLE
Auth 4.2 supermaster setting clarification

### ISSUE THREAD

**Issue by jbacker** [PowerDNS/pdns#7720]
Two minor things regarding the 4.2 Auth nameserver.

In 4.2, you specifically require to enable 'supermaster' in the configuration file if you want to run as a superslave. This might be confusing (i.e. you enable support for notifies from supermasters, but it reads as if the machine should be supermaster itself, which isn't something you configure). Perhaps change wording to 'superslave' instead to clarify?

Also, very minor issue, the repository page shows 4.2 as if it would be an actual release - Given its still a release candidate, perhaps add this to the repository name as well, so people grab 4.1 for production instead. :)

**Comment by Habbie** [comment]
Additionally, our upgrade notes do not mention this issue yet.

Also, the description for the option simply is wrong: `::arg().setSwitch("supermaster", "Act as a supermaster")="no";` - that should say 'Act as a superslave'.

**Comment by Habbie** [comment]
We need to decide if we can rename the option at this point, with rc1 already out there. I would really like to rename it to `superslave`.

**Comment by Habbie** [comment]
> Given its still a release candidate, perhaps add this to the repository name as well

Then they'd have to change it on release - I'd rather add a few words to the html on the repo site.

**Comment by jbacker** [comment]
> Then they'd have to change it on release - I'd rather add a few words to the html on the repo site.

Ah, yep, that's what I meant indeed.
