### ISSUE TITLE
Extend SpoofAction to handle any QType

### ISSUE THREAD

**Issue by christofchen** [PowerDNS/pdns#7721]
- Program: dnsdist
 - Issue type: Feature request

### Short description

DNSDIST should provide a means to define a spoof response for any QType, not just A/AAAA/CNAME.

### Usecase

I use dnsdist to simulate DNS responses to a subset of names/adresses of machines inside an address-translated test environment and forward the remainder to downstream outside the test environment.  
Some applications e.g. NFS check PTR records to "authenticate" access and i need to suppy the "NAT" response. Rewriting SRV, MX and TXT seems to come next...

### Description
Currently `SpoofAction` supports A/AAAA and CNAME records. Unfortunately PTR is missing.
`SpoofAction` should be extended to allow returning PTR (and other) records. 

To avoid a new spoof function for each qtype, a new 
`GenericSpoofAction(DNSQType,  string [, string...]) `  
could provide an interface to replace SpoofAction and SpoofCNAMEAction eventually.

**Comment by Habbie** [comment]
To avoid teaching dnsdist about 100 types, how about a variant that expects the user to put in wire format data? Knot Resolver appears to be getting away with that for its users.

**Comment by jaredmauch** [comment]
I'd like this as well so I can reply to queries like this:
```
21:03:58.000756 CR 100.65.15.10 UDP 120b "_aaplcache._tcp.localdomain." IN TXT
21:03:58.000756 CR 100.65.15.10 UDP 121b "_aaplcache2._tcp.localdomain." IN TXT
21:03:58.000756 CR 100.65.15.10 UDP 121b "_aaplcache4._tcp.localdomain." IN TXT
21:03:58.000756 CR 100.65.15.10 UDP 121b "_aaplcache1._tcp.localdomain." IN TXT
21:03:58.000756 CR 100.65.15.10 UDP 121b "_aaplcache3._tcp.localdomain." IN TXT
``` with information about my local cache.
