### ISSUE TITLE
Can't strat PDNS Server

### ISSUE THREAD

**Issue by LHY2355** [PowerDNS/pdns#7739]
I can't start my pdns server
### Environment

 - Operating system: CentOS7.6
 - Software version: latest
### Steps to reproduce
/usr/sbin/pdns_server --daemon=no --guardian=no --loglevel=9

### Expected behaviour
I hope it works

### Actual behaviour
[root@centos-s-1vcpu-1gb-ams3-01 pdns]# /usr/sbin/pdns_server --daemon=no --guardian=no --loglevel=9
Apr 21 17:35:49 Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Apr 21 17:35:49 Unable to load module '/usr/lib64/pdns/libgmysqlbackend.so': libmysqlclient.so.18: cannot open shared object file: No such file or directory
Apr 21 17:35:49 DNSBackend unable to load module in gmysql

**Comment by Habbie** [comment]
Hello! This looks like a supper question, and our GitHub tickets are only for bugs and feature requests. Please ask for help via IRC or our mailing list - details are at https://www.powerdns.com/opensource.html
