### ISSUE TITLE
various make/configure issues

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#774]
- [x] we don't spot missing ragel, bison and flex
- [x] if flex is missing, configure generates bogus Makefile commands for (f)lex
- [x] make testrunner only works after a make, due to polarssl not being built in the first case

**Comment by pieterlexis** [comment]
I think the testrunner item can be closed because we no longer ship polar?

**Comment by Habbie** [comment]
Yes, and indeed `make testrunner` works directly after configure on current master.
