### ISSUE TITLE
Memory leaks in pdns-recursor 4.2

### ISSUE THREAD

**Issue by vias79** [PowerDNS/pdns#7742]
First off, thanks for a great software! Experiencing memory leaks with 4.2 which needs to be looked at.

 - Program: Recursor
 - Issue type: Bug report

### Short description
Memory leaks in pdns-recursor 4.2

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 4.2.0~alpha1-1pdns.bionic
 - Software source: PowerDNS repository

### Steps to reproduce
1. echo "deb [arch=amd64] http://repo.powerdns.com/ubuntu bionic-rec-42 main" > /etc/apt/sources.list.d/pdns.list
2. curl https://repo.powerdns.com/FD380FBB-pub.asc | sudo apt-key add - &&
sudo apt-get update &&
sudo apt-get install pdns-recursor
3. This is the recursor.conf file in /etc/powerdns (omitted IPs and passwords)

allow-from-file=/etc/powerdns/allowed.net
local-address=127.0.0.1, HOST_EXTERNAL_IP, HOST_EXTERNAL_IP #2, HOST_EXTERNAL_IP #3, HOST_EXTERNAL_IPv6, HOST_EXTERNAL_IPv6 #2, HOST_EXTERNAL_IPv6 #3, ::1
local-port=53
log-common-errors=yes
logging-facility=7
max-cache-entries=2000000
query-local-address=HOST_EXTERNAL_IP
query-local-address6=HOST_EXTERNAL_IPv6
quiet=yes
server-down-max-fails=16
setgid=pdns
setuid=pdns
threads=4
write-pid=yes
webserver=yes
api-key=MYSUPERBESTPASSWORD12345
webserver-port=8082
webserver-address=HOST_EXTERNAL_IP
distributor-threads=4
pdns-distributes-queries=yes

### Expected behaviour
Stable operation and better performance due to distributor-threads support.

### Actual behaviour
In this picture you can see when we tried the upgrade. Previous was 4.1.8 I believe.

Week graph:
![image](https://user-images.githubusercontent.com/4582087/56584297-c9d60380-65db-11e9-8f7f-920b1b4a87af.png)
Day graph:
![image](https://user-images.githubusercontent.com/4582087/56584333-dfe3c400-65db-11e9-9cd4-95a5db842b5a.png)

After a restart "service pdns-recursor restart" the memory usage dropped.

### Other information
This is on a server receiving 10k queries/s.

**Comment by rgacogne** [comment]
Thank you for reporting this! I believe this has been fixed by https://github.com/PowerDNS/pdns/pull/7731, any chance you would be willing to test the master branch?

**Comment by vias79** [comment]
Tried using the master branch but I can't seem to get it to upgrade.

echo "deb [arch=amd64] http://repo.powerdns.com/ubuntu bionic-rec-master main" > /etc/apt/sources.list.d/pdns.list
curl https://repo.powerdns.com/CBC8B383-pub.asc | sudo apt-key add - &&
sudo apt-get update &&
sudo apt-get install pdns-recursor

pdns-recursor is already the newest version (4.1.12-1pdns.bionic).

also tried apt-get dist-upgrade but that didn't work either.

root@resolver# apt update
Hit:1 http://se.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://se.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://se.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://repo.powerdns.com/ubuntu bionic-rec-master InRelease [1,803 B]
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Fetched 1,803 B in 1s (3,285 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@resolver# apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by pieterlexis** [comment]
Please do `cp /etc/pdns-recursor/recursor.conf /tmp; apt-get remove -y pdns-recursor && apt-get -y install pdns-recursor; cp /tmp/recursor.conf /etc/pdns-recursor/recursor.conf`. We use a low version number (0.0.0) for master builds.

**Comment by vias79** [comment]
Ah ok, now it's upgraded to master branch:
ii  pdns-recursor                         0.0.16518+0.g55da465e5d-1pdns.bionic amd64        PowerDNS Recursor

Will update after a few hours how it works.

**Comment by vias79** [comment]
Seems stable, will let it run overnight and update.

**Comment by vias79** [comment]
Yes, I'm closing this. The bug is fixed in the Master branch.
![image](https://user-images.githubusercontent.com/4582087/56728878-20664d80-6754-11e9-9f8d-c3aaf3140697.png)

**Comment by ahupowerdns** [comment]
hi @vias79 - thanks for the great bug reporting and testing!
