### ISSUE TITLE
Misinterpretation of IPv6 in forward-zones/forward-zones-recurse configuration

### ISSUE THREAD

**Issue by theo19** [PowerDNS/pdns#7743]
- Program: Recursor 
 - Issue type: Bug report 

### Short description
The configuration recursor.conf is not properly processed for non-bracket IPv6 adresses, even when in most other places processing IPv6 adresses, including when mixing IPv4 and IPv6 without special indication for IPv6 works fine.

### Environment

 - Operating system: uname -a says: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Software version: PowerDNS Recursor 4.1.1 (C) 2001-2017 PowerDNS.COM BV
 - Software source:  
```
curl https://repo.powerdns.com/CBC8B383-pub.asc | sudo apt-key add -
apt-get update
```
Later in the install i see
```
<13>Apr 23 14:35:26 dns-resolver-dev2: Get:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 pdns-recursor amd64 4.1.1-2 [1424 kB]
<13>Apr 23 14:35:27 dns-resolver-dev2: Fetched 1546 kB in 0s (43.8 MB/s)
[...]
<13>Apr 23 14:35:27 dns-resolver-dev2: Selecting previously unselected package pdns-recursor.
<13>Apr 23 14:35:27 dns-resolver-dev2: Preparing to unpack .../pdns-recursor_4.1.1-2_amd64.deb ...
<13>Apr 23 14:35:27 dns-resolver-dev2: Unpacking pdns-recursor (4.1.1-2) ...
[...]
<13>Apr 23 14:35:27 dns-resolver-dev2: Setting up pdns-recursor (4.1.1-2) ...
```

### Steps to reproduce

1.  Stop pdns_recursor
2. Insert configuration into /etc/powerdns/recursor.conf as follows
```
#################################
# forward-zones-recurse Zones for which we forward queries with recursion bit, comma separated domain=ip pairs
# forward-zones-recurse=
# this fails by getting misconfiguration live without throwing an error
forward-zones-recurse=testthis.net=2003:1234::f561;2003:1234::f562
```
2. Start pdns_recursor
3. Check which adresses were chosen for forwarding by looking into syslog
4. Stop pdns_recursor 
5. Modify configuration as follows
```
forward-zones-recurse=testthis.net=[2003:1234::f561];[2003:1234::f562]
```
6. Start pdns_recursor
7. Check which addresses were chosen for forwarding by looking into syslog

### Expected behavior
Expected is that pdns_recursor 
a) will bind to the same address in both choices of configuration
b) would throw an error if there is ambiguity in configuration

When no errror coccurs, syslog shows that configuration for forwarding chose a pair of proper IPv6 addresses:
```
Apr 23 13:41:20 bn831x5a-idns4-lab pdns_recursor[2683]: Redirecting queries for zone 'testthis.net' with recursion to: [2003:1234::f561]:53, [2003:1234::f562]:53
```
### Actual behavior
When choosing this line - which should be expected to work the same way as elsewhere in the configuration file, that is: Without having to embrace the IPv6 address with edged brackets.

```
forward-zones-recurse=testthis.net=2003:1234::f561;2003:1234::f562
```
but syslog shows that configuration for forwarding has seemingly tried to interpret part of config as IPv4 address, and omitted the portion it did not understand, without throwing an error:

```
Apr 23 13:40:04 bn831x5a-idns4-lab pdns_recursor[2627]: Redirecting queries for zone 'testthis.net' with recursion to: 0.0.7.211:1234, 0.0.7.211:1234
```

### Other information

The same inconsistent behavior is observed for forward-zones and forward-zones-recurse

### Usecase

I try to have the resolver instance resolve data from a three independent pairs of IPv6-only 
on premise internal DNS Authoritiative services 

### Description

Consistently accept IPv6 addresses without requiring user to put brackets around them in some places in recursor.conf whereas such brackets are not required in other places of same file

**Comment by theo19** [comment]
Thanks for picking this up ; i agree that preventing a misinterpretation of an ipv6 address as ipv4 is certainly also an enhancement, but i'd really think not throwing an error is a bug even, no matter if i figured out a workaround ;-)

**Comment by Habbie** [comment]
That's fair - we should either reject it, or do the right thing. This is silent failure.

**Comment by theo19** [comment]
Thanks. Notably 2003 = 7*256+211 - so that wrongly triggered piece of code seem to do some calculation based on 8 bit segments a la IPv4, and then seemingly picks the next colon separated 16 bit of the IPv6 address as the IPv4 port.

**Comment by omoerbeek** [comment]
Issue is in `reczones.cc::parseIPAndPort()`. There the splitting of an address is too simplistic.
