### ISSUE TITLE
Missing zone-lastchange-query option in PDNS auth 4.2

### ISSUE THREAD

**Issue by olegwtf** [PowerDNS/pdns#7747]
`gmysql-zone-lastchange-query` option doesn't work in PDNS auth 4.2 rc1 and I can't find any information about removement or deprecation of this option.

If it was removed what will be the alternative? We used it this way:

```
gmysql-zone-lastchange-query=select unix_timestamp(max(change_date)) from records where domain_id=?
```

**Comment by Habbie** [comment]
It is removed, but we have not written the upgrade notes for 4.2 yet. It was mentioned in https://blog.powerdns.com/2018/12/14/powerdns-authoritative-server-4-2-0-alpha1-lua-records-ixfrdist-swagger/

We have no concrete alternative to propose. SQL triggers might be a workable approach.
