### ISSUE TITLE
Development plan to match the domain name mechanism？

### ISSUE THREAD

**Issue by mengxifl** [PowerDNS/pdns#7754]
such as this

abcRandom1.examlle.com    ->  abc*.example.com

abcRandom2.examlle.com    ->  abc*.example.com

like a Regular match rules.

**Comment by pieterlexis** [comment]
The [RegexRule](https://dnsdist.org/rules-actions.html#RegexRule) could help you here:

```lua
addAction(RegexRule("abc.*\\.example\\.com"), DropAction())
```

**Comment by mengxifl** [comment]
> 
> 
> The [RegexRule](https://dnsdist.org/rules-actions.html#RegexRule) could help you here:
> 
> ```lua
> addAction(RegexRule("abc.*\\.example\\.com"), DropAction())
> ```
---
i konw i must use dnsdist.

addAction(RegexRule("abc.*\\.example\\.com"), SpoofAction({IP[172.16.254.5]}))

thanks a lot
