### ISSUE TITLE
bind backend hybrid does not retry on failed mysql connection

### ISSUE THREAD

**Issue by SebastianS90** [PowerDNS/pdns#7760]
- Program: Authoritative
 - Issue type: Bug report

### Short description

When using the bind backend with `bind-hybrid=yes` in combination with gmysql, then temporary connection errors to the database prevent the zone to be served until powerdns is restarted (even if the mysql connection is again possible).

### Environment
 - Operating system: Debian 9.9
 - Software version: PowerDNS Authoritative Server 4.0.3
 - Software source: Debian package version `4.0.3-1+deb9u4`

### Steps to reproduce

1. Set `launch=bind,gmysql` and `bind-hybrid=yes`
2. Start both powerdns and the mysql server simultaneously
3. Observe powerdns log, try to query some zones

### Expected behaviour

All zones should be available when both powerdns and mysql server are up and running.

### Actual behaviour

Some zones are not available (servfail).

On startup:

```
19:06:28 [bindbackend] Parsing 34 domain(s), will report when done
19:06:28 Master/slave communicator launching
19:06:32 gmysql Connection failed: Unable to connect to database: Can't connect to MySQL server on '10.0.0.1' (111 "Connection refused")
19:06:32 Caught an exception instantiating a backend: Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.0.0.1' (111 "Connection refused")
19:06:32 Cleaning up
19:06:32 [bindbackend] error at 2019-04-27 19:06:32 +0000 parsing 'example.com' from file '/etc/powerdns/zones/example.com': Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.0.0.1' (111 "Connection refused")
19:06:39 gmysql Connection failed: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.: 
19:06:39 Caught an exception instantiating a backend: Unable to launch gmysql connection: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:
19:06:39 Cleaning up
19:06:39 [bindbackend] error at 2019-04-27 19:06:39 +0000 parsing 'example.net' from file '/etc/powerdns/zones/example.net': Unable to launch gmysql connection: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:
19:06:39 [bindbackend] Done parsing domains, 2 rejected, 34 new, 0 removed
```
(Note that only 2 out of 34 zones failed to load. The database was not yet available for them, all others worked fine and got their dnssec metadata from the mysql db.)

When querying the affected zone later:
```
19:47:23 Backend reported condition which prevented lookup (Zone for 'example.com' in '/etc/powerdns/zones/example.com' temporarily not available (file missing, or master dead)) sending out servfail
```

The error stays until I restart powerdns or use `pdns_control bind-reload-now example.com` to reload the zone. Then everything works, without touching the database or any zone files.
Powerdns / bind backend should retry to load the zones when it failed due to some temporary connection problem with the database.

The setting `bind-check-interval` does not influence this issue, even after `thouch`ing the zonefile and waiting for the interval to pass, the server still fails.

**Comment by pieterlexis** [comment]
Hi,

Thanks for you report, would you be able to test this in 4.1 (https://repo.powerdns.com has the packages) and see if this is still the case. Or even better, test the 4.2 packages (also on https://repo.powerdns.com)!

Thanks

**Comment by SebastianS90** [comment]
I'll give it a try with 4.2 and let you know.

**Comment by Habbie** [comment]
> `19:06:39 gmysql Connection failed: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:`

This is not a temporary problem...

**Comment by SebastianS90** [comment]
Sorry for the delay here. I finally found the time to setup a testing environment and try it out with newer versions.

Firstly, regarding the `Please add '(gmysql-)innodb-read-committed=no'` message: It comes from [here](https://github.com/PowerDNS/pdns/blob/rec-4.2.0-rc1/modules/gmysqlbackend/smysql.cc#L492).
Powerdns first does a connection attempt with setting the isolation level to RC. If that attempt fails, then it does a second attempt without setting the isolation level. If this attempt now succeeds, then one possibility is that the database does not support RC, so powerdns prints out this message. But another possibility is that the first attempt failed because the mysql server was not yet available and the second succeeded because the server is now available (which is what triggered it in my log output above).

If all zones get rejected, then pdns just fails and the systemd unit tries to start it again. Assuming that the sql connection can eventually be established, that is not a problem.
But when only some zones are rejected, then pdns is started successfully, but sends out servfails for the rejected zones without ever trying to load them again. So to hit this issue you need something that comes with some delay/timeout and not fails the connection immediately, because otherwise all zones will get rejected before you can resolve the connectivity problem can get resolved.

A good way do reproduce it is as follows:
- Configure multiple zones in the bind backend, at least 3
- Configure `bind-hybrid=yes` together with a `gmysql-host` on a different server, lets say `10.10.101.2`.
- Pick an IP from your local subnet that does not answer (i.e. no machine is running there), let's say `192.168.0.42`
- Add a route for the mysql server to that non-existing ip: `ip route add 10.10.101.2 via 192.168.0.42`
- Start powerdns, wait a few seconds until you see the first rejected zone in the log, then remove the bogous route: `ip route del 10.10.101.2`

That way, the first few connection attempts by powerdns time out with `no route to host`, but later ones will succeed. A real-life setup where this occurs is that the database is on one vserver, pdns on another one, and both start in parallel.

I could reproduce that problem with `4.2.0~rc1-1pdns.stretch` from `repo.powerdns.com` as well with `4.2.0~rc1+master.811.g2e3e774d6-1pdns.stretch`

`4.2.0~rc1-1pdns.stretch`:
```
Loading '/usr/lib/x86_64-linux-gnu/pdns/libbindbackend.so'
Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
This is a standalone pdns
Listening on controlsocket in '/var/run/pdns.controlsocket'
UDP server bound to 0.0.0.0:53
UDPv6 server bound to [::]:53
TCP server bound to 0.0.0.0:53
TCPv6 server bound to [::]:53
PowerDNS Authoritative Server 4.2.0-rc1 (C) 2001-2019 PowerDNS.COM BV
Using 64-bits mode. Built using gcc 6.3.0 20170516 on Mar 19 2019 03:50:54 by root@e061487a3eab.
PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Creating backend connection for TCP
[bindbackend] Parsing 31 domain(s), will report when done
Master/slave communicator launching
gmysql Connection failed: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
Caught an exception instantiating a backend: Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
Cleaning up
[bindbackend] error at 2019-06-09 12:47:22 +0000 parsing 'example.com' from file '/etc/powerdns/zones/example.com.zone': Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
gmysql Connection failed: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:
Caught an exception instantiating a backend: Unable to launch gmysql connection: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:
Cleaning up
[bindbackend] error at 2019-06-09 12:47:25 +0000 parsing 'example.net' from file '/etc/powerdns/zones/example.net.zone': Unable to launch gmysql connection: Please add '(gmysql-)innodb-read-committed=no' to your PowerDNS configuration, and reconsider your storage engine if it does not support transactions.:
[bindbackend] Done parsing domains, 2 rejected, 31 new, 0 removed
No master domains need notifications
Only asked for 1 backend thread - operating unthreaded

[then I did a query for the rejected zone:]
Backend reported condition which prevented lookup (Zone for 'example.com' in '/etc/powerdns/zones/example.com.zone' temporarily not available (file missing, or master dead)) sending out servfail
```


`4.2.0~rc1+master.811.g2e3e774d6-1pdns.stretch`:
```
Loading '/usr/lib/x86_64-linux-gnu/pdns/libbindbackend.so'
Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
This is a standalone pdns
Listening on controlsocket in '/var/run/pdns.controlsocket'
UDP server bound to 0.0.0.0:53
UDPv6 server bound to [::]:53
TCP server bound to 0.0.0.0:53
TCPv6 server bound to [::]:53
PowerDNS Authoritative Server 4.2.0-rc1.811.master.g2e3e774d6 (C) 2001-2019 PowerDNS.COM BV
Using 64-bits mode. Built using gcc 6.3.0 20170516 on Jun  7 2019 20:34:54 by root@5394756390ee.
PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Creating backend connection for TCP
[bindbackend] Parsing 31 domain(s), will report when done
Master/slave communicator launching
gmysql Connection failed: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
Caught an exception instantiating a backend: Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
Cleaning up
[bindbackend] error at 2019-06-09 13:20:17 +0000 parsing 'example.com' from file '/etc/powerdns/zones/example.com.zone': Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on '10.10.101.2' (113 "No route to host")
[bindbackend] Done parsing domains, 1 rejected, 31 new, 0 removed
No master domains need notifications
Only asked for 1 backend thread - operating unthreaded
Only asked for 1 backend thread - operating unthreaded

[then I did a query for the rejected zone:]
Backend reported condition which prevented lookup (Zone for 'example.com' in '/etc/powerdns/zones/example.com.zone' temporarily not available (file missing, or master dead)) sending out servfail
```


My workaround right now is the following cronjob:
```
*/5 * * * * root for zone in $(pdns_control bind-list-rejects | awk '{print $1}') ; do pdns_control bind-reload-now "$zone" ; done
```
It lists the failed zones and reloads them. After every reboot, this cronjob reproducably finds one or two zones that need to be reloaded because the mysql server was not yet available when pdns started.
