### ISSUE TITLE
Recursor 4.1.12 leaks memory

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#7771]
- Program: Recursor
 - Issue type: Bug report

### Short description
It appears that 4.1.12 might be leaking memory on long-term basis. Node with average of 70 kpq/s and 2k validations/s is leaking memory about 4G per month. 

### Environment
 - Operating system: 14.04 ubuntu LTS
 - Software version: 4.1.12
 - Software source: PowerDNS repository

### Steps to reproduce
1. Run PowerDNS recursor for a month

### Expected behaviour
Memory usage should not be increasing constantly.

### Actual behaviour
Memory usage increases.

![memory usage](https://user-images.githubusercontent.com/1204643/57092962-56d43780-6d15-11e9-835a-59aee9c7d964.png)

As a curiosity, it seems memory leak has been happening over several software versions over the years.

![long term memory usage](https://user-images.githubusercontent.com/1204643/57093033-85eaa900-6d15-11e9-886f-ed2f6c0c972e.png)

### Other information
Cache can be ruled out due to cache usage being fairly constant.

![cache entries](https://user-images.githubusercontent.com/1204643/57093062-94d15b80-6d15-11e9-84d0-4a648a739d3c.png)

smaps breakdown
-------------------
```
===============================================================================
Private    Private     Shared     Shared
 Clean   +  Dirty   +  Clean   +  Dirty   =  Total   : library
===============================================================================
    0 kB + 3451432 kB +     0 kB +     0 kB = 3451432 kB : [anonymous]
 5204 kB +    96 kB +     0 kB +     0 kB =  5300 kB : pdns_recursor
    0 kB +  1996 kB +     0 kB +     0 kB =  1996 kB : [heap]
    0 kB +    24 kB +  1512 kB +     0 kB =  1536 kB : libc-2.19.so
    0 kB +   152 kB +  1300 kB +     0 kB =  1452 kB : libcrypto.so.1.0.0
  848 kB +    40 kB +     0 kB +     0 kB =   888 kB : libstdc++.so.6.0.19
  856 kB +    20 kB +     0 kB +     0 kB =   876 kB : libprotobuf.so.8.0.0
   96 kB +     8 kB +   460 kB +     0 kB =   564 kB : libm-2.19.so
  408 kB +    12 kB +     0 kB +     0 kB =   420 kB : libluajit-5.1.so.2.0.2
    0 kB +    40 kB +   204 kB +     0 kB =   244 kB : libperl.so.5.18.2
    0 kB +     8 kB +   140 kB +     0 kB =   148 kB : ld-2.19.so
    0 kB +    12 kB +   108 kB +     0 kB =   120 kB : libnetsnmp.so.30.0.2
    0 kB +     8 kB +    92 kB +     0 kB =   100 kB : libpthread-2.19.so
   88 kB +     4 kB +     0 kB +     0 kB =    92 kB : libgcc_s.so.1
    0 kB +     8 kB +    68 kB +     0 kB =    76 kB : libnetsnmpagent.so.30.0.2
    0 kB +     8 kB +    64 kB +     0 kB =    72 kB : libnsl-2.19.so
    0 kB +     8 kB +    60 kB +     0 kB =    68 kB : libz.so.1.2.8
    0 kB +     8 kB +    40 kB +     0 kB =    48 kB : libnss_files-2.19.so
    0 kB +     8 kB +    32 kB +     0 kB =    40 kB : libcrypt-2.19.so
    0 kB +     8 kB +    32 kB +     0 kB =    40 kB : libwrap.so.0.7.6
    0 kB +     8 kB +    28 kB +     0 kB =    36 kB : libnss_sss.so.2
    0 kB +    20 kB +     0 kB +     0 kB =    20 kB : [stack]
    0 kB +     8 kB +    12 kB +     0 kB =    20 kB : libdl-2.19.so
    4 kB +     8 kB +     0 kB +     0 kB =    12 kB : libboost_context.so.1.54.                                                                                                                                                             0
    0 kB +     0 kB +     4 kB +     0 kB =     4 kB : [vdso]
    0 kB +     0 kB +     0 kB +     0 kB =     0 kB : [vvar]
    0 kB +     0 kB +     0 kB +     0 kB =     0 kB : [vsyscall]
===============================================================================
 7504 kB + 3453944 kB +  4156 kB +     0 kB = 3465604 kB : Total
```

Configuration file
```
recursor.conf:

allow-from=0.0.0.0/0,::/0
any-to-tcp=yes
carbon-ourname=<removed>
carbon-server=127.0.0.1
config-dir=/etc/powerdns/
daemon=no
dont-query=127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fe80::/10
local-address=127.0.0.1 ::1 <revmoed>
log-common-errors=off
max-mthreads=4096
max-tcp-clients=512
minimum-ttl-override=120
query-local-address=<removed>
query-local-address6=<removed>
quiet=yes
security-poll-suffix=secpoll.powerdns.com.
server-id=<removed>
setgid=nogroup
setuid=nobody
threads=16
version-string=<removed>
dnssec=validate
```

**Comment by omoerbeek** [comment]
@cmouse anything in the config that could matter?

**Comment by omoerbeek** [comment]
I have been doing test runs using 4.1.14 both with `dnssec=validate` and `dnssec=off`. In both cases I can see a small memory leak, that becomes clear when running for about a week continuously handling queries.

Running a slightly modified 4.1.14 using valgrind does report  any leak even when running for a while (2 days).

The modifications involve a controlled thread shutdown (since valgrind only reports on exit). It could be the controlled shutdown is cleaning up allocations that an "ever" running thread does not clear.  I'll try to come up with a way to find these kind of leaks.

As an aside: the reported configuration uses 16 worker threads. That only make sense if the machine it is running on has at least 16 cores.  Any idea on the hardware used? The general advise is to use `min(8, #cores)` for this setting. Note that the recursor uses a record cache per thread, so limiting the number of threads will both reduce memory consumption and increase cache hit ratio as well.

**Comment by cmouse** [comment]
the machine has 16 cores.

**Comment by cmouse** [comment]
HP ProLiant DL360 G7 - 2 x Intel(R) Xeon(R) CPU X5650 @ 2.67GHz, 6*2GB memory

**Comment by omoerbeek** [comment]
I'm closing this, since at least some leaks were plugged. Resubmit report if leaks are still showing up.
