### ISSUE TITLE
dnsdist: expose the security status as a metric

### ISSUE THREAD

**Issue by atosatto** [PowerDNS/pdns#7775]
- Program: dnsdist
 - Issue type: Feature request

### Short description

DNSdist does not like to be exposing via API / Prometheus Metrics / Carbon the status of the security pool status.

### Expected behaviour

Expose the result of security status polling as a metrics available via API / Prometheus Metrics / Carbon. 

### Actual behaviour

Security polling status is only reported in the log messages

```
May 04 13:00:10 myhost dnsdist[1267]: Polled security status of version 1.3.3 at startup, no known issues reported: OK
```

but it is currently not exposed as a metric.

**Comment by paddg** [comment]
It looks like this has already been implemented by @pieterlexis
https://github.com/PowerDNS/pdns/pull/7197

**Comment by pieterlexis** [comment]
THis is the case in 1.4:

https://github.com/PowerDNS/pdns/blob/5510ebdcdc8afd25cb0f45c129f41b2f79600e9a/pdns/dnsdist.hh#L391

```
nc -lk 2003 | grep security
dnsdist.perzik.main.security-status 0 1556978258
```

and in prometheus:
```
# HELP dnsdist_security_status Security status of this software. 0=unknown, 1=OK, 2=upgrade recommended, 3=upgrade mandatory
# TYPE dnsdist_security_status gauge
dnsdist_security_status 0
```
