### ISSUE TITLE
dnsdist: expose version number as metric

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7777]
If our metrics mentioned the version number running, or perhaps part of the git hash, this would facilitate debugging. Compare our uptime metric which discovers accidental reloads.

**Comment by rgacogne** [comment]
For the record, we do this in our prometheus metrics now.

**Comment by rgacogne** [comment]
Closing as this is done in prometheus already, and we have not yet found how to do it right in Carbon.
