### ISSUE TITLE
recursor: expose version number as metric

### ISSUE THREAD

**Issue by ahupowerdns** [PowerDNS/pdns#7778]
If our metrics mentioned the version number running, or perhaps part of the git hash, this would facilitate debugging. Compare our uptime metric which discovers accidental reloads.

**Comment by pieterlexis** [comment]
This is exposed in prometheus in the `pdns_recursor_info` metric since 4151ddba2d2d07f83bc7eb8214c9611e4fa06a3e

**Comment by omoerbeek** [comment]
I was looking into doing this for the rec 4.5.0 milestone, and then found out we do not have metrics of type string. Since the currently available VERSION is a string, I have to see how to approach this.,

**Comment by omoerbeek** [comment]
An  ugly way is to encode the version info into a uin64_t:
major minor patch commitid
properly shifted to the left etc. The hex value would be somewhat readable, but when converted to decimal it becomes a mess.
e.g. `0.0.20676.0.HEAD.gfaee4a6ea1.dirty` would become `50c4faee4a6ea1` (20676 = 0x50c4)
and `4.5.1` would become `405010000000000` (no commitid available).
Decimal representation would be `22734580155575969` and `289638850546892800`

This is all too ugly I think we want a proper strings in the metrics

**Comment by pieterlexis** [comment]
We can also ignore this problem for any metrics _but_ prometheus. As both carbon and SNMP are (afaik) not suitable for strings

**Comment by omoerbeek** [comment]
Yeah, that's fine with me.
