### ISSUE TITLE
rec, dnsdist: Unable to install master version on Debian Buster

### ISSUE THREAD

**Issue by gertvdijk** [PowerDNS/pdns#7781]
- Program: Recursor 
 - Issue type: Bug report

### Short description

Using PowerDNS APT repositories, experiencing package dependency conflict:

     libstdc++6 : Breaks: pdns-recursor (< 4.1.11-1) but 0.0.16688+0.gbfd0a2aa58-1pdns.buster is to be installed

### Environment

 - Operating system: Debian Buster
 - Software version: current version in `deb [arch=amd64] http://repo.powerdns.com/debian buster-rec-master main` repository
 - Software source: see above

### Steps to reproduce

1. From [repo.powerdns.com](https://repo.powerdns.com/), follow *Debian 10 (Buster)* -> *PowerDNS Recursor - master branch*

### Expected behaviour
Installation to be successful.

### Actual behaviour
The PowerDNS recursor is published with version `0.0.16688+0.gbfd0a2aa58-1pdns.buster` in the repository, causing confusion with other Debian packages.

APT conflict with dependency `libstdc++6`, because *that* package has a *Breaks* line `pdns-recursor (<< 4.1.11-1)`, but the pdns-recursor package is published with that strange `0.0.*` version string.

### Other information

The Authoritative server package is also packaged with the strange version string, but doesn't suffer from this issue.

I've tracked it down to [Debian bug 866354](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866354). It appears pdns-recursor was added to that package's Breaks for ensuring a smooth transition of upgrading from stretch to buster.

### Usecase

Early evaluation for upgrading environment to Debian Buster. First found myself a bit disappointed that the latest stable release isn't built for Buster, so I resorted to master for the sake of the broader-than-PowerDNS test.

**Comment by pieterlexis** [comment]
The only real solution here is to switch to a 'last tag plus X' version scheme. However, this is somewhat complicated by the fact that we ship 3 product with 3 different versions from the same repo (and branch, when talking about master).

Rewriting `builder-support/gen-version` in e.g. python (i.e. not shell-script) and have pdns-builder pass the enabled modules ('recursor', 'dnsdist', 'authoritative') via an environment variable. Using this variable, it would be possible to generate a proper version number, falling back to 0.0.X when more than one module is enabled.

**Comment by gertvdijk** [comment]
> The only real solution here is to switch to a 'last tag plus X' version scheme. However, this is somewhat
> complicated by the fact that we ship 3 product with 3 different versions from the same repo (and 
> branch, when talking about master).

(Without having paid any look at your current release/build automation yet.) Suggestion, something that I've done in the past in this situation:
* Prefix the tags of all subprojects from the repository, e.g. `rec-1.2.3`. You do that already, no?
* Put a tag on the commit directly after branching off master for a stable release. e.g. `rec-1.3.0-dev` as soon as you start to branch off a 1.2.x.
* Use clever patterns with `git-describe`, in `--match`/`--exclude` to match the right tag for the situation, although when building of a branch you should always hit the nearest tag close to the product.

**Comment by pieterlexis** [comment]
That is better articulated than I did. Apart from the second step (which does not fit our current development methodology is what I had in mind.

**Comment by zeha** [comment]
This also affects dnsdist `(<< 1.3.3-3)`.

**Comment by zeha** [comment]
The really hard problem here is figuring out the "next best version number thats higher than what Debian might have" though.

**Comment by pieterlexis** [comment]
> The really hard problem here is figuring out the "next best version number thats higher than what Debian might have" though.

I think I'll pick 'last release for the product' plus commits e.g.:

* 1.4.0-alpha2.123.g12abcdef
* 4.3.0.12.g234567890

**Comment by zeha** [comment]
Okay, dots appear to sort better than dashes. 👍

**Comment by appliedprivacy** [comment]
Is there any timeline when this will be merged?
