### ISSUE TITLE
https://github.com/PowerDNS/pdns/pull/7772 breaks recursor regression test

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#7785]
Above commit breaks a recursor regression test: `test_basicNSEC.py:basicNSEC.testSecureDNAMEToInsecureCNAMEAnswer`

Resursor test log is attached. It is not  clear yet if this is an auth or recursor bug, but the first suspect would be auth.

The recursor tests uses the auth process. Bisecting the auth code lead to the above commit.
[recursor.log](https://github.com/PowerDNS/pdns/files/3148528/recursor.log)

@mind04 any clue?

**Comment by Habbie** [comment]
auth+rec at 5510ebdcd breaks; auth+rec at the previous merge commit, 5d270e867, works. Auth at the parent (5d270e867) and rec at the breaking commit (5510ebdcd) works. Just confirming that the cause is an auth change (which does not mean it's an auth bug).

**Comment by Habbie** [comment]
Here's an auth test - https://gist.github.com/Habbie/e462e2e58c00ae027dab78646b7b66b6

With `./start-test-stop 5300 gsqlite3`, at 5510ebd and up, you get:
```
+./tests/secure-cname-to-insecure/drillchase.out:|---Bogus DNSSEC signature:
+./tests/secure-cname-to-insecure/drillchase.out:No trusted keys found in tree: first error was: Bogus DNSSEC signature
+./tests/secure-cname-to-insecure/unbound-host.out:cname-to-insecure.example.com is an alias for www.insecure.dnssec-parent.com. (BOGUS (security failure))
+./tests/secure-cname-to-insecure/unbound-host.out:www.insecure.dnssec-parent.com has address 192.0.2.88 (BOGUS (security failure))
```

The reason is that the CNAME RRSIG, that signs the CNAME, after 5510ebd also signs `0	www.insecure.dnssec-parent.com.	IN	A	120	192.0.2.88`

**Comment by Habbie** [comment]
The comment at https://github.com/PowerDNS/pdns/blob/master/pdns/dnssecsigner.cc#L134 is a lie.

**Comment by Habbie** [comment]
Here's a patch that (taken out of context so maybe I'm wrong!) makes the test above pass - https://gist.github.com/Habbie/1761b84b8b3671173db3d52787571f45

However, this patch is wrong. It will, for example, break if the CNAME comes from a parent zone.

**Comment by Habbie** [comment]
https://gist.github.com/Habbie/5418a7226b47d322c4550b66c997444b
https://gist.github.com/Habbie/d372718bf00c766c264eb020cad5bdea

Just stashing some more related work here while we expect a surgical patch from @mind04

**Comment by omoerbeek** [comment]
Actually the problem PR might be #7523
