### ISSUE TITLE
Triple database connection on incoming IXFR requests

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#7795]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I currently debug a problem where I hit the connection limit on my database. Watchting the logs, it seems that for incoming IXFR, every XFR thread opens 3 DB connections - although IXFR is just a fallback to AXFR.

### Environment
 - Operating system: Ubuntu 14.04
 - Software version: 4.1.5
 - Software source: self compiled .deb package

### Expected behaviour
Only open a single DB connection

### Actual behaviour
For IXFR PDNS opens 3 DB connections

### Logs for AXFR and IXFR
Incoming AXFR: dig @1.2.3.29 nxdomain.at axfr
```
: AXFR of domain 'nxdomain.at' initiated by 1.2.3.27
: AXFR of domain 'nxdomain.at' allowed: client IP 1.2.3.27 is in allow-axfr-ips
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: AXFR of domain 'nxdomain.at' to 1.2.3.27 finished
```

Incoming IXFR with different serial: dig @1.2.3.29 nxdomain.at ixfr=0
```
: IXFR of domain 'nxdomain.at' initiated by 1.2.3.27 with serial 0
: AXFR of domain 'nxdomain.at' allowed: client IP 1.2.3.27 is in allow-axfr-ips
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: IXFR fallback to AXFR for domain 'nxdomain.at' our serial 2019031507
: AXFR of domain 'nxdomain.at' initiated by 1.2.3.27
: AXFR of domain 'nxdomain.at' allowed: client IP 1.2.3.27 is in allow-axfr-ips
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: AXFR of domain 'nxdomain.at' to 1.2.3.27 finished
```

Incoming IXFR with identical serial: dig @1.2.3.29 nxdomain.at ixfr=2019031507
```
: IXFR of domain 'nxdomain.at' initiated by 1.2.3.27 with serial 2019031507
: AXFR of domain 'nxdomain.at' allowed: client IP 1.2.3.27 is in allow-axfr-ips
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: gpgsql Connection successful. Connected to database 'pdns' on ''.
: IXFR of domain 'nxdomain.at' to 1.2.3.27 finished
```

**Comment by rgacogne** [comment]
It looks like `TCPNameserver::doIXFR()` creates several `UeberBackend` objects. I wonder if we could only use one, or even use `s_P->getBackend()` instead.

**Comment by zeha** [comment]
I had the same impression that we should get away there with either one new `UeberBackend` or `s_P->getBackend()`. Although doAXFR explicitly uses a new `UeberBackend` to check for authority. When falling back to AXFR it might be nice if we could reuse an existing `UeberBackend`.
