### ISSUE TITLE
StartLimitIntervalSec setting in wrong unit file section

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#7804]
- Program: Authoritative, Recursor, dnsdist, ixfrdist
 - Issue type: Bug report

### Short description
The `StartLimitInterval=` setting does not exist according to `systemd.unit(5)` and `systemd.service(5)`. If `StartLimitIntervalSec=` was meant, it is in the wrong section. Should be in `[Unit] ` instead of `[Service]`.

I just happened to see that, and I didn't run any tests.

**Comment by rgacogne** [comment]
This is fun:
- `StartLimitInterval` was limited to services (and hence had to go in the `[Service]` section) up to 229, then was extended to all unit types (and moved to `[Unit]` although still supported in the `[Service]` section): https://github.com/systemd/systemd/commit/6bf0f408e4833152197fb38fb10a9989c89f3a59
-  `StartLimitInterval` was renamed to `StartLimitIntervalSec` in 230 (but is still parsed correctly today, see https://github.com/systemd/systemd/blob/master/src/core/main.c#L738 ).

So for now this option is still supported as it is, so until we decide to drop support for systemd < 230 perhaps we should keep it as it is?

**Comment by paddg** [comment]
Yes funny. And confusing. Thanks for the clarification, that's okay.
