### ISSUE TITLE
DoH at 1.4.0 - Alpha 2

### ISSUE THREAD

**Issue by TorstenJahnke** [PowerDNS/pdns#7809]
- **Program:** dnsdist 1.4.0 - Alpha 2
 - **Issue type:** DoH not working

 - **Operating system:** Debian 9
 - **Software version:**  latest patch
 - **Software source:** PowerDNS repository

**### Short description**
I was trying to use the DoH Service but for some reasons its not working or may be I don't understand the documentation.

**### Settings in config:**
addDOHLocal("10.10.10.20:443", "/etc/chain.pem", "/etc/key.pem",{dns-query})
(the value "dns-query" should be the destination for DoH Service)

**Comment by Habbie** [comment]
Our Debian 9 packages sadly do not have DoH support right now, because the required dependencies are not available (except in backports). I believe our Debian 10 packages do support DoH - would that be an option for you?

**Comment by Habbie** [comment]
However, your config line also appears to contain some errors - can you tell us what error you got, just to be sure?

**Comment by TorstenJahnke** [comment]
Within Debian I receive no errors. DNSDIST will start and now I understand why it's not responding.
Which OS currently supports DoH Service on DNSDIST?

**Comment by Habbie** [comment]
> Within Debian I receive no errors.

There really should be an error, perhaps in the journal for dnsdist.

**Comment by TorstenJahnke** [comment]
No. There are no error with this line.
Of cause there are additional settings within the config. I have only copy here the DoH related setting.

**Comment by Habbie** [comment]
> There really should be an error, perhaps in the journal for dnsdist.

@rgacogne tells me we most likely indeed fail to log this error

**Comment by TorstenJahnke** [comment]
Running now Debian 9 with upgrade to 10
DoT Address = sdns.asecdns.ch (its working & public available)
DoH Address = sdns.asecdns.ch/dns-query (not working)

`setLocal('x.x.x.x:5300')
setACL('0.0.0.0/0')
addACL('::0/0')
addACL('159.69.247.133')
addACL('2a01:4f8:c010:1acc::133')

addTLSLocal("159.69.247.133", "/etc/fullchain.pem", "/etc/privkey.pem",{ doTCP=true, reusePort=true})
addTLSLocal("[2a01:4f8:c010:1acc::133]", "/etc/fullchain.pem", "/etc/privkey.pem",{ doTCP=true, reusePort=true})

addDOHLocal("159.69.247.133:443", "/etc/fullchain.pem", "/etc/privkey.pem",{dns-query})
addDOHLocal("[2a01:4f8:c010:1acc::133]:443","/etc/fullchain.pem", "/etc/privkey.pem",{dns-query})

setMaxTCPClientThreads(500000)

useClientSubnet=true
setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)

setStaleCacheEntriesTTL(86400)

>>> FORWARD SERVER HERE <<<<`

**The Journal file:**
May 10 18:12:18 debian9 dnsdist[577]: Configuration '/etc/dnsdist/dnsdist.conf' OK!
May 10 18:12:18 debian9 dnsdist[577]: Configuration '/etc/dnsdist/dnsdist.conf' OK!
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Added downstream server x.x.x.x:53
May 10 18:12:19 debian9 dnsdist[591]: Listening on x.x.x.x:5300
May 10 18:12:19 debian9 dnsdist[591]: Listening on 159.69.247.133:853 for TLS
May 10 18:12:19 debian9 dnsdist[591]: Listening on [2a01:4f8:c010:1acc::133]:853 for TLS
May 10 18:12:19 debian9 dnsdist[591]: Listening on 159.69.247.133:443 for DoH
May 10 18:12:19 debian9 dnsdist[591]: Listening on [2a01:4f8:c010:1acc::133]:443 for DoH
May 10 18:12:19 debian9 dnsdist[591]: dnsdist 1.4.0-alpha2 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GP$
May 10 18:12:19 debian9 dnsdist[591]: ACL allowing queries from: 0.0.0.0/0, ::/0, 2a01:4f8:c010:1acc::133/128, 159.69.247.133/32
May 10 18:12:19 debian9 dnsdist[591]: Console ACL allowing connections from: 127.0.0.1/8, ::1/128
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver1 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver2 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver3 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver4 (x.x.x.x)) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver5 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver6 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver7 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver8 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver9 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver10 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver11 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Marking downstream resolver12 (x.x.x.x) as 'up'
May 10 18:12:19 debian9 dnsdist[591]: Polled security status of version 1.4.0-alpha2 at startup, no known issues reported: OK

**Comment by Habbie** [comment]
> addDOHLocal("159.69.247.133:443", "/etc/fullchain.pem", "/etc/privkey.pem",{dns-query})

'{dns-query}' is a syntax error here, is that really literally what you put in?

**Comment by Habbie** [comment]
>  May 10 18:12:19 debian9 dnsdist[591]: Listening on 159.69.247.133:443 for DoH

Given that we see this, I don't think we're looking at a bug here. The GitHub issue tracker really is only for bugs and feature requests. Can I ask you to find us on IRC or the pdns-users mailing list? Details for both are at https://www.powerdns.com/opensource.html

**Comment by TorstenJahnke** [comment]
> > addDOHLocal("159.69.247.133:443", "/etc/fullchain.pem", "/etc/privkey.pem",{dns-query})
> 
> '{dns-query}' is a syntax error here, is that really literally what you put in?

https://i.imgur.com/WIQBm5Q.png

It was because of the config recommendation from this URL:

https://dnsdist.org/reference/config.html#dohfrontend

addDOHLocal(address, certFile(s), keyFile(s)[, urls[, options]])

**Comment by Habbie** [comment]
That URL assumes some Lua experience (which is not entirely fair). I recommend `"/dns-query"` instead.

**Comment by TorstenJahnke** [comment]
> That URL assumes some Lua experience (which is not entirely fair). I recommend `"/dns-query"` instead.

When I use this settings "/dns-query" then dnsdist will not start. There will be an error too:

Fatal error: [string "chunk"]:10: unexpected symbol near '/'

**Comment by TorstenJahnke** [comment]
> > May 10 18:12:19 debian9 dnsdist[591]: Listening on 159.69.247.133:443 for DoH
> 
> Given that we see this, I don't think we're looking at a bug here. The GitHub issue tracker really is only for bugs and feature requests. Can I ask you to find us on IRC or the pdns-users mailing list? Details for both are at https://www.powerdns.com/opensource.html

I now online at IRC  #powerdns because that's faster then mail. ;)

**Comment by Habbie** [comment]
After discussion on IRC, there appears to be no bug, just documentation that could be better. I've asked @TorstenJahnke to tell us what we should change in the docs to make them better.

**Comment by christianbur** [comment]
Hello,

I'm also trying to test DoH, but I can't get it to work. 
I always get the error "Unable to find the DNS parameter".

I find the error message in the [source code](https://github.com/PowerDNS/pdns/blob/7fd64d1c0cd321ebbfd0f04c0a49c3ed5f2b0266/pdns/dnsdistdist/doh.cc#L398), and also something with "?dns=", but how the correct URL to test should look like I unfortunately do not find .



```
addACL('0.0.0.0/0')
addACL('::/0')

-- DNS over UDP/TCP
addLocal('0.0.0.0:53', {doTCP=true, reusePort=true})
addLocal('[::]:53',    {doTCP=true, reusePort=true})

-- DNS over TLS
addTLSLocal("0.0.0.0:853", {"/dnsdist_certs/rsa/fullchain.cer", "/dnsdist_certs/ecdsa/fullchain.cer"}, {"/dnsdist_certs/rsa/test.de.key", "/dnsdist_certs/ecdsa/test.de.key"}, { doTCP=true, reusePort=true})
addTLSLocal("[::]:853",    {"/dnsdist_certs/rsa/fullchain.cer", "/dnsdist_certs/ecdsa/fullchain.cer"}, {"/dnsdist_certs/rsa/test.de.key", "/dnsdist_certs/ecdsa/test.de.key"}, { doTCP=true, reusePort=true})

-- DNS over HTTPS
addDOHLocal("0.0.0.0:443", {"/dnsdist_certs/rsa/fullchain.cer", "/dnsdist_certs/ecdsa/fullchain.cer"}, {"/dnsdist_certs/rsa/test.de.key", "/dnsdist_certs/ecdsa/test.de.key"}, "/dns-query", {reusePort=true})
addDOHLocal("[::]:443",    {"/dnsdist_certs/rsa/fullchain.cer", "/dnsdist_certs/ecdsa/fullchain.cer"}, {"/dnsdist_certs/rsa/test.de.key", "/dnsdist_certs/ecdsa/test.de.key"}, "/dns-query", {reusePort=true})		

newServer({address="172.22.3.54:53", name="pdns-unbound", pool="pool-unbound"})

-- pool selection
addAction(AndRule({ OrRule({DSTPortRule(53)}), makeRule({"172.16.0.0/12", "100.64.100.0/24"}) }),  PoolAction("pool-unbound"))
addAction(DSTPortRule(853), PoolAction("pool-unbound"))
addAction(DSTPortRule(443), PoolAction("pool-unbound"))
```
DNS Port 53 -> OK
DNS over TLS -> OK
DNS over HTTPs -> ERROR

```
# DOH with 1.1.1.1
# curl -k -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=example.com&type=A"
{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": true,"CD": false,"Question":[{"name": "example.com.", "type": 1}],"Answer":[{"name": "example.com.", "type": 1, "TTL": 10533, "data": "93.184.216.34"}]}

DOH with own dns server
# curl -k -H "accept: application/dns-json" "https://ns1.test.de:4433/dns-query?name=example.com&type=A"
Unable to find the DNS parameter

DOH with own dns server (with ?dns=)
# curl -k -H "accept: application/dns-json" "https://ns1.test.de:4433/dns-query?dns=example.com&type=A"
The DNS query could not be parsed
```

**Comment by TorstenJahnke** [comment]
I have exactly the same problem but for some reasons its working within NEBULO App (Playstore) and Firefox. When I'm using INTRA App (Playstore) its not working.

With this the server is working:

> addDOHLocal("10.0.0.1:443","/etc/letsencrypt/live/sdns.asecdns.ch/fullchain.pem","/etc/letsencrypt/live/sdns.asecdns.ch/privkey.pem","/dns-query",{serverTokens="h2o/dnsdist", tcpFastOpenSize=0, reusePort=true})

**Comment by christianbur** [comment]
I can also query the standard DoH server used by Firefox with curl without any problems, so there is something wrong with our config or the dnsdist doh implementation. 

```
curl -k -H "accept: application/dns-json" "https://mozilla.cloudflare-dns.com/dns-query?name=example.com&type=AAAA"
{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": true,"CD": false,"Question":[{"name": "example.com.", "type": 28}],"Answer":[{"name": "example.com.", "type": 28, "TTL": 9781, "data": "2606:2800:220:1:248:1893:25c8:1946"}]}
```

**Comment by TorstenJahnke** [comment]
I already reported this.

**Comment by Habbie** [comment]
> I'm also trying to test DoH, but I can't get it to work.

There is no JSON in DoH. You are not sending valid DNS queries. The JSON schema that Cloudflare and Google use (https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/) has not been standardised and we do not currently support it.

I'm closing this ticket because it appears to be a confusing mess of 3 problems now, none of which appear to be dnsdist bugs. If there are any bugs or issues, please file new tickets.

**Comment by christianbur** [comment]
but how can you then test the doh implementation of dnsdist with a cli tool (for monitoring)?

**Comment by Habbie** [comment]
I do my testing with `curl --doh-url ...`.

**Comment by Habbie** [comment]
I'm closing conversation on this ticket. Bugs or feature request, please file a new ticket. Any other question, please find us on IRC or mailing list, see https://www.powerdns.com/opensource.html
