### ISSUE TITLE
add support for OCSP stapling

### ISSUE THREAD

**Issue by appliedprivacy** [PowerDNS/pdns#7812]
- Program: dnsdist 
 - Issue type: Feature request

### Short description

Adding support for OCSP stapling would:

* reduce latency (no need to contact OCSP server)
* improve privacy (no need to disclose the visit to the 3rd party OCSP server)

### Expected behaviour

DoH and DoT should support OCSP stapling.
And maybe enable it by default?

### Actual behaviour

DoH listener does not appear to support OCSP stapling.
(DoT status not tested)

### Other information

h2o appears to support it:

https://h2o.examp1e.net/index.html 

Key Features: automatic OCSP stapling

**Comment by rgacogne** [comment]
I agree it would be a very nice feature to have and we will ponder it in later versions. I don't think it would make sense for dnsdist to open up a HTTP connection to the OCSP server itself, but IMHO we should consider implementing the ability to load the OCSP stapling response from a file at startup and to reload it at runtime from the console, like haproxy does.

**Comment by appliedprivacy** [comment]
Thanks for considering this feature request.

> I don't think it would make sense for dnsdist to open up a HTTP connection to the OCSP server itself

Can you elaborate why it would not make sense to implement OCSP stapling like i.e. a webserver does? (nginx will fetch the necessary data from the OCSP server)

**Comment by rgacogne** [comment]
> Can you elaborate why it would not make sense to implement OCSP stapling like i.e. a webserver does? (nginx will fetch the necessary data from the OCSP server)

It would mean teaching dnsdist how to extract the `OCSP` endpoint from the certificate, how to do an `HTTP` query and parse an `HTTP` response, how to construct an `OCSP` query and parse an `OCSP` response, and keep track of the `OCSP` response expiry and refresh times. All of this, while doable, is in my opinion not the best use of our time and would increase the complexity and thus surface attack of dnsdist. I think loading an `OCSP` stapling response from a file and letting an external program do the needful would be a nice middle ground, but of course other people might disagree.
