### ISSUE TITLE
Latency issues when doing lookups (versions > 4.1.x)

### ISSUE THREAD

**Issue by toweroy** [PowerDNS/pdns#7815]
- Program: Authoritative
 - Issue type: Bug report

### Short description

When upgrading versions of `pdns`, the newer versions have a ~10x latency increase for large DNS record type lookups after caching values in PowerDNS. Most time seems to be spent in pdns/distributor and pdns/tcpConnect according to perf. I have tried several configurations (Ubuntu - PowerDNS) and have only found issues in versions of PowerDNS later than `4.x.x`, this does not seem to be caused by an Ubuntu upgrade.

The only change in configuration done among versions has been to update the `pipebackend-abi-version` to `pipe-abi-version`, using `1` as the value for all.

### Environment

 - Operating system: Ubuntu 14.04 (Trusty) and Ubuntu 18.04 (Bionic)
 - Software version: _(See matrix table below)_ 
 - Software source: _(See matrix table below)_

#### Versions tested matrix

Ubuntu Version | Pdns-server Version | Aprox. Query Latency
-- | -- | --
Bionic | 4.1.1 (from powerdns repo)| 800 ms
Bionic | 4.1.8 (from powerdns repo)| 790 ms
Bionic | 4.2.1 (from powerdns repo)| 780 ms
Bionic | 3.4.11 (From source: git-auth-3.4.11-3-ge907ecc47+) | 20 ms
Trusty | 3.4.2 (from powerdns repo)| 18 ms

### Steps to reproduce

1. Send a `dig <srv-address> -t srv @<target-test-machine>`
2. Measure latency returned by `dig`
3. Repeat

### Expected behaviour
Latency between versions should be around the same values in the tenths of miliseconds.

### Actual behaviour
Latency for newer versions of `pdns`(> `4.x.x`) increases considerably.

#### Example queries done in different versions of `pdns`

_**NOTE:** Same behaviour among different Ubuntu versions_

**Test query on pdns-server 3.4.11**

```
dig <srv-record> -t srv @<pdns-hostname>
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> 
<...>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48467
;; flags: qr aa rd; QUERY: 1, ANSWER: 800, AUTHORITY: 0, ADDITIONAL: 781
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1200
;; QUESTION SECTION:
<...>

;; ANSWER SECTION:
<...>

;; Query time: 19 msec
;; SERVER: <...>
;; WHEN: <...>
;; MSG SIZE  rcvd: 65514
```

**Test query on pdns-server 4.1.1**
```
dig <srv-query> -t srv @<pdns-hostname>
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> 
<...>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12481
;; flags: qr aa rd; QUERY: 1, ANSWER: 800, AUTHORITY: 0, ADDITIONAL: 781
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1200
;; QUESTION SECTION:
<...>

;; ANSWER SECTION:
<...>

;; Query time: 835 msec
;; SERVER: <...>
;; WHEN: <...>
;; MSG SIZE  rcvd: 65514
```

**Test query on pdns-server 4.1.8**
```
dig <srv-query> -t srv @<pdns-hostname>
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> 
<...>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23298
;; flags: qr aa rd; QUERY: 1, ANSWER: 800, AUTHORITY: 0, ADDITIONAL: 781
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1200
;; QUESTION SECTION:
<...>

;; ANSWER SECTION:
<...>

;; Query time: 792 msec
;; SERVER: <...>
;; WHEN: <...>
;; MSG SIZE  rcvd: 65514
```

**Comment by Habbie** [comment]
Is the data coming from the pipebackend? If so, can you see if 4.x is doing a lot more queries to your pipebackend for the SRV query?

**Comment by toweroy** [comment]
@Habbie so the first query made does go to the backend (which has had no changes between pdns versions) but that is not accounted for in the previously posted measurements. So this latencies are for expected cached queries coming from pdns. 

One thing we did notice is that in newer versions of pdns (> 4.x.x) the backend receives `ANY` queries which would translate to `A`, `AAAA`, `SRV` and `SOA` lookups which is a difference between major versions. But this still didn't explain why, after querying for the same record several times before its TTL is expired, there is such a delay latency.

**Comment by Habbie** [comment]
Thanks!

I wonder if this is because of record deduplication within an RRset inside PowerDNS, that code has changed since 3.4.

**Comment by toweroy** [comment]
@Habbie is there a way to verify this record deduplication on our side?

**Comment by Habbie** [comment]
> @Habbie is there a way to verify this record deduplication on our side?

Reading code, doing deeper profiling, etc. I'll try to look at it soon.

**Comment by Habbie** [comment]
I have so far not managed to reproduce this wild performance difference. Can you show me something I can reproduce here?

**Comment by tommyulfsparre** [comment]
@Habbie thanks for investigating this! 
I tried to reduce this down to something that is reproducible here: https://github.com/tommyulfsparre/powerdns-repro. 

This actually performs worse as there is no difference between a cached query and a query that hits the pipe backend. The query time avg.  around `1.7 sec` for both a cached and uncached query. So maybe something is off with this setup?

**Comment by mind04** [comment]
Please repeat you tests with the current master packages. For non dnssec zones they should perform a lot better with large rrsets.

https://github.com/mind04/pdns/blob/master/pdns/dnssecinfra.cc#L342 The serializing will make dedup super slow for large rrsets.

**Comment by tommyulfsparre** [comment]
@mind04 the [container](https://github.com/tommyulfsparre/powerdns-repro/blob/master/Dockerfile#L1) in the repro repo is at version:
```bash
May 24 07:24:34 PowerDNS Authoritative Server 4.1.8 (C) 2001-2018 PowerDNS.COM BV
```

which seems to have the latest changes?

**Comment by Habbie** [comment]
No, please test with master!

**Comment by tommyulfsparre** [comment]
Nice! On master I get `2 ms` for an uncached query and `0 ms` for a cached.

**Comment by Habbie** [comment]
Wonderful! We'll be releasing auth 4.2.0 soon. Do you agree that we can close this ticket?

**Comment by toweroy** [comment]
@Habbie agreed. Thank you all for the help.
