### ISSUE TITLE
synchronise dnsdist help/completion with registered globals

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#7828]
Generated with https://gist.github.com/Habbie/8619e19f9c8ad048a2472202bdadfea8

I'd love to somehow make this part of CI, but for now, here's the output:

# duplicate entries in g_consoleKeywords
* [ ] setPoolServerPolicy
* [ ] topCacheHitResponseRule
# registered globals not present in g_consoleKeywords
* [ ] DNSAction
* [ ] DNSClass
* [ ] DNSCryptExchangeVersion
* [ ] DNSOpcode
* [ ] DNSQType
* [ ] DNSRCode
* [ ] DNSResponseAction
* [ ] DNSSECRule
* [ ] DNSSection
* [ ] DisableECSAction
* [ ] ECSOverrideAction
* [ ] ECSPrefixLengthAction
* [ ] EDNSOptionCode
* [ ] HTTPHeaderRule
* [ ] HTTPPathRule
* [ ] LuaAction
* [ ] LuaResponseAction
* [ ] MacAddrAction
* [ ] NetmaskGroupRule
* [ ] NoneAction
* [ ] NotRule
* [ ] OpcodeRule
* [ ] OrRule
* [ ] PoolAvailableRule
* [ ] ProbaRule
* [ ] QClassRule
* [ ] QNameSetRule
* [ ] QPSAction
* [ ] QPSPoolAction
* [ ] RDRule
* [ ] RecordsCountRule
* [ ] RecordsTypeCountRule
* [ ] SetECSAction
* [ ] SkipCacheAction
* [ ] SpoofCNAMEAction
* [ ] SuffixMatchNodeRule
* [ ] TCPRule
* [ ] TrailingDataRule
* [ ] addBPFFilterDynBlocks
* [ ] addDynBlockSMT
* [ ] dnsdist
* [ ] errlog
* [ ] getAction
* [ ] getRespRing
* [ ] getSlowResponses
* [ ] getStatisticsCounters
* [ ] getTopBandwidth
* [ ] getTopQueries
* [ ] getTopResponses
* [ ] help
* [ ] includeDirectory
* [ ] infolog
* [ ] makeIPCipherKey
* [ ] makeRule
* [ ] newBPFFilter
* [ ] newCA
* [ ] newDynBPFFilter
* [ ] newNMG
* [ ] setCacheCleaningDelay
* [ ] setCacheCleaningPercentage
* [ ] setDefaultBPFFilter
* [ ] setPoolServerPolicyLua
* [ ] setRoundRobinFailOnNoServer
* [ ] setWHashedPertubation
* [ ] statNodeRespRing
* [ ] warnlog
# g_consoleKeywords entries not registered as global
* [ ] setDNSSECPool

**Comment by rgacogne** [comment]
Looking into it, thanks!
