### ISSUE TITLE
pdns make wrong with geoip modules

### ISSUE THREAD

**Issue by ZTzha** [PowerDNS/pdns#7839]
- Operating system:  centos7
1. ./configure -prefix=/usr/local/pdns --enable-lua-records --with-modules='geoip bind gmysql lua lua2 random gpgsql'
2. make

WRONG:
Making all in modules
make[2]: 进入目录“/root/pdns-4.2.0-rc1/modules”
Making all in geoipbackend
make[3]: 进入目录“/root/pdns-4.2.0-rc1/modules/geoipbackend”
  CXX      geoipinterface-dat.lo
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCountry(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:79:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:79:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:85:62: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                              ^
geoipinterface-dat.cc:85:68: 错误：‘GeoIP_id_by_addr_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                    ^
geoipinterface-dat.cc:92:110: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                              ^
geoipinterface-dat.cc:92:116: 错误：‘GeoIP_region_by_addr_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                    ^
geoipinterface-dat.cc:103:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCountryV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:111:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:111:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:117:65: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                 ^
geoipinterface-dat.cc:117:71: 错误：‘GeoIP_id_by_addr_v6_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                       ^
geoipinterface-dat.cc:124:113: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                 ^
geoipinterface-dat.cc:124:119: 错误：‘GeoIP_region_by_addr_v6_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                       ^
geoipinterface-dat.cc:135:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCountry2(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:143:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:143:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:149:62: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                              ^
geoipinterface-dat.cc:149:68: 错误：‘GeoIP_id_by_addr_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                    ^
geoipinterface-dat.cc:156:109: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion,geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                             ^
geoipinterface-dat.cc:156:115: 错误：‘GeoIP_region_by_addr_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion,geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                   ^
geoipinterface-dat.cc:167:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCountry2V6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:175:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:175:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:181:65: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                 ^
geoipinterface-dat.cc:181:71: 错误：‘GeoIP_id_by_addr_v6_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                       ^
geoipinterface-dat.cc:188:113: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                 ^
geoipinterface-dat.cc:188:119: 错误：‘GeoIP_region_by_addr_v6_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                       ^
geoipinterface-dat.cc:199:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryContinent(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:207:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:207:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:213:62: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                              ^
geoipinterface-dat.cc:213:68: 错误：‘GeoIP_id_by_addr_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                    ^
geoipinterface-dat.cc:220:110: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                              ^
geoipinterface-dat.cc:220:116: 错误：‘GeoIP_region_by_addr_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                    ^
geoipinterface-dat.cc:231:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryContinentV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:239:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:239:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:245:65: 错误：‘tmp_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                 ^
geoipinterface-dat.cc:245:71: 错误：‘GeoIP_id_by_addr_v6_gl’在此作用域中尚未声明
       if ((id = GeoIP_id_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl)) > 0) {
                                                                       ^
geoipinterface-dat.cc:252:113: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                 ^
geoipinterface-dat.cc:252:119: 错误：‘GeoIP_region_by_addr_v6_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                       ^
geoipinterface-dat.cc:263:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryName(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:271:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:271:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:276:69: 错误：‘tmp_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                     ^
geoipinterface-dat.cc:276:75: 错误：‘GeoIP_name_by_addr_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryNameV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:291:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:291:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:296:72: 错误：‘tmp_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                        ^
geoipinterface-dat.cc:296:78: 错误：‘GeoIP_name_by_addr_v6_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                              ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryASnum(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:310:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:310:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:314:69: 错误：‘tmp_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                     ^
geoipinterface-dat.cc:314:75: 错误：‘GeoIP_name_by_addr_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryASnumV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:331:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:331:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:335:72: 错误：‘tmp_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                        ^
geoipinterface-dat.cc:335:78: 错误：‘GeoIP_name_by_addr_v6_gl’在此作用域中尚未声明
       char* result = GeoIP_name_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl);
                                                                              ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryRegion(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:352:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:352:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:357:110: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                              ^
geoipinterface-dat.cc:357:116: 错误：‘GeoIP_region_by_addr_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                    ^
geoipinterface-dat.cc:368:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryRegionV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:376:5: 错误：‘GeoIPLookup’在此作用域中尚未声明
     GeoIPLookup tmp_gl = {
     ^
geoipinterface-dat.cc:376:17: 错误：expected ‘;’ before ‘tmp_gl’
     GeoIPLookup tmp_gl = {
                 ^
geoipinterface-dat.cc:381:113: 错误：‘tmp_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                 ^
geoipinterface-dat.cc:381:119: 错误：‘GeoIP_region_by_addr_v6_gl’在此作用域中尚未声明
       std::unique_ptr<GeoIPRegion, geoipregion_deleter> gir(GeoIP_region_by_addr_v6_gl(d_gi.get(), ip.c_str(), &tmp_gl));
                                                                                                                       ^
geoipinterface-dat.cc:392:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCity(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:405:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryCityV6(std::string&, GeoIPNetmask&, const string&)’中:
geoipinterface-dat.cc:418:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryLocationV6(GeoIPNetmask&, const string&, double&, double&, boost::optional<int>&, boost::optional<int>&)’中:
geoipinterface-dat.cc:436:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
geoipinterface-dat.cc: 在成员函数‘virtual bool GeoIPInterfaceDAT::queryLocation(GeoIPNetmask&, const string&, double&, double&, boost::optional<int>&, boost::optional<int>&)’中:
geoipinterface-dat.cc:454:27: 错误：‘struct GeoIPRecordTag’没有名为‘netmask’的成员
         gl.netmask = gir->netmask;
                           ^
make[3]: *** [geoipinterface-dat.lo] 错误 1
make[3]: 离开目录“/root/pdns-4.2.0-rc1/modules/geoipbackend”
make[2]: *** [all-recursive] 错误 1
make[2]: 离开目录“/root/pdns-4.2.0-rc1/modules”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/root/pdns-4.2.0-rc1”

**Comment by Habbie** [comment]
I cannot reproduce this problem. Can you tell me about your exact environment, which packages you installed, etcetera?

Also, can you please set your error messages to English (LC_ALL=C should do the trick) next time? Thank you!

**Comment by Habbie** [comment]
Timed out.
