### ISSUE TITLE
Recursion continuing (and servfailing) after finding matching records.

### ISSUE THREAD

**Issue by austintrose** [PowerDNS/pdns#7866]
- Program: Recursor
- Issue type: Bug report

### Short description
Recursor is asked to resolve `www.actionindoorsports.com`. It eventually gets to asking `ns1.oursecureserver.co.nz`, which responds with the following records:

```
www.actionindoorsports.com. 3600 IN CNAME   actionindoorsports.com.
actionindoorsports.com. 3600    IN  A   103.96.117.8
actionindoorsports.com. 86400   IN  NS  alien.xtra.co.nz.
actionindoorsports.com. 86400   IN  NS  terminator.xtra.co.nz.
;; Received 140 bytes from 103.96.117.6#53(ns1.oursecureserver.co.nz) in 326 ms
```

Now, given that a matching CNAME + A record are present, I assumed the recursor would have successfully resolved the query. Instead, the recursor ultimately responds to the query with a `SERVFAIL`. The nameservers `alien.xtra.co.nz` and `terminator.xtra.co.nz` are refusing traffic, so I assume that the recursor is returning a `SERVFAIL` because it could not reach them.

### Environment

 - Operating system: 14.04.6 LTS
 - Software version: 4.1.13
 - Software source: `deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-rec-41 main`

### Steps to Reproduce

I am running the recursor privately in a VM on my host. There is no custom `lua-dns-script` configured / interfering with the resolution. I have attached the configuration file.

Unfortunately, I am only noticing this issue as a result of downtime and/or misconfiguration with the nameservers responsible for `www.actionindoorsports.com`, which are outside of my control. In case they fix/change the behavior in the meantime, I have attached a myriad of query / response examples I ran with my local Recursor while investigating. 

Hopefully the examples will make it easy enough to determine how the Recursor was acting. If they aren't enough to reproduce the issue, let me know, and I can probably set up some infrastructure to mimic the results seen from `ns1.oursecureserver.co.nz` and `alien.xtra.co.nz / terminator.xtra.co.nz` at the time.

I have attached `recursor_examples.zip` containing:
- `recursor.conf` 
- `query_examples.txt`, which contains the results of the following queries (note that `10.10.6.81` is my local Recursor 4.1.13):
    - `dig @10.10.6.81 actionindoorsports.com +trace`
    - `dig @10.10.6.81 www.actionindoorsports.com +trace`
    - `dig @10.10.6.81 www.actionindoorsports.com`
    - `dig @10.10.6.81 actionindoorsports.com`
    - `dig @ns1.oursecureserver.co.nz www.actionindoorsports.com`
    - `dig @ns1.oursecureserver.co.nz actionindoorsports.com`
    - `dig @alien.xtra.co.nz actionindoorsports.com`
    - `dig @alien.xtra.co.nz www.actionindoorsports.com`

[recursor_examples.zip](https://github.com/PowerDNS/pdns/files/3242506/recursor_examples.zip)

### Expected behaviour
Recursor responds to `dig @10.10.6.81 www.actionindoorsports.com` with `NOERROR` using the matching `A record` which came up during recursion.

### Actual behaviour
Recursor responds to query with `SERVFAIL`.

### Usecase
Reduce number of `SERVFAIL` from the recursor wherever possible.

**Comment by austintrose** [comment]
Tagging @clokep since we were investigating this issue together.

**Comment by ahupowerdns** [comment]
On master this works fine for the first query & later it will fail because we trusted the wrong NS records supplied. Now checking 4.1.13.

**Comment by ahupowerdns** [comment]
In 4.1.13 it indeed fails because the CNAME referral is detected together with the referral, and somehow 4.1.13 thinks it should follow the referral. This would normally work, except that this referral point to nameservers that don't work.

So the summary is that this domain is misconfigured and will break in 4.2 "eventually" and in 4.1 "immediately". While we could likely fix this in the 4.1 train, our efforts at fixing misconfigured domains is a lot less than fixing correctly configured domains. So it may be a while. Meanwhile, can we interest you in 4.2?

**Comment by clokep** [comment]
@ahupowerdns Thanks for taking a look at this! We haven't had a chance to play with 4.2 yet, but usually try to upgrade rather quickly once a release is out.

From your comments though it sounds like on 4.2 this will still fail after the first query? Or am I misunderstanding?

**Comment by ahupowerdns** [comment]
4.2 will make this work for the first hour, and then it will fail for 23 hours. Fundamentally it can't work because the domain kills itself with its misconfiguration.

**Comment by austintrose** [comment]
Thank you for the quick and thorough response, @ahupowerdns!

Glad to know this is an unavoidable issue with their configuration, and that PowerDNS is acting as intended. We have gone ahead and reached out to what contact emails we could find, to notify them of the issue.
