### ISSUE TITLE
secpoll code assumes all non-release versions start with "0.0."

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#7895]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Bug report

### Short description

The new master builds log (for Authoritative):

`Jun  8 01:50:15 clover pdns_server[18483]: Could not retrieve security status update for '4.2.0-rc1.811.master.g2e3e774d6' on 'auth-4.2.0-rc1.811.master.g2e3e774d6.security-status.secpoll.powerdns.com.', RCODE = Non-Existent domain`

dnsdist and Recursor are (I believe) similar. The code that decides whether to log "Could not retrieve security status update ..." or the less alarming "Ignoring/Not validating response, this is a non-release version." checks whether the version number starts with "0.0.".

### Environment
 - Operating system: Ubuntu 16.04 x86-64
 - Software version: pdns-server 4.2.0~rc1+master.811.g2e3e774d6-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce

1. 
2. 
3. 

### Expected behaviour
"`Not validating response, this is a non-release version.`"

### Actual behaviour
"`Could not retrieve security status update for`..."

### Other information

https://github.com/PowerDNS/pdns/blob/2e3e774d6b76717012e420563b7c628e3b6e899f/pdns/secpoll-auth.cc#L65-L69

https://github.com/PowerDNS/pdns/blob/2e3e774d6b76717012e420563b7c628e3b6e899f/pdns/secpoll-recursor.cc#L81-L84

https://github.com/PowerDNS/pdns/blob/2e3e774d6b76717012e420563b7c628e3b6e899f/pdns/dnsdistdist/dnsdist-secpoll.cc#L195

https://github.com/PowerDNS/pdns/blob/2e3e774d6b76717012e420563b7c628e3b6e899f/pdns/dnsdistdist/dnsdist-secpoll.cc#L236-L240

**Comment by Habbie** [comment]
As I suspect the fix will be somewhat more complex than `find("0.0.")...`, this might be a good opportunity to put that logic in a shared function.
