### ISSUE TITLE
auth: remove SOA autofilling

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#7919]
- Program: Authoritative
 - Issue type: Feature removal

### Short description
Proposal: in 4.3.0, remove these settings:
```
# default-soa-mail	mail address to insert in the SOA record if none set in the backend
# default-soa-mail=
# default-soa-name	name to insert in the SOA record if none set in the backend
# default-soa-name=a.misconfigured.powerdns.server
# soa-expire-default	Default SOA expire
# soa-expire-default=604800
# soa-minimum-ttl	Default SOA minimum ttl
# soa-minimum-ttl=3600
# soa-refresh-default	Default SOA refresh
# soa-refresh-default=10800
# soa-retry-default	Default SOA retry
# soa-retry-default=3600
```

This would close #6248, #5382, #4321, #3518.

It is my suspicion that not many users rely on the feature, or at least, that most of those that do, could also pretty easily live without, now that we've been pushing the API for a while.

@mind04 mentions that PowerAdmin users might be relying on this feature; we should check that and maybe help them change that.

**Comment by mind04** [comment]
Related #7918

**Comment by pieterlexis** [comment]
If we do this, we'll need to add a `fill-unfilled-soas` command to the pdnsutil in 4.2.x, so users can prepare their databases. For 4.3.0 we could keep that command, but then the user will have to specify the values on the commandline (e.g. `fill-unfilled-soas ns1.example. hostmaster.domain.example. 10800 3600 604800 3600`)

**Comment by Habbie** [comment]
@franklouwers points out that `pdnsutil create-zone` also uses these settings, so we either keep the settings but stop using them outside of `create-zone`, or we empower the `create-zone` user to control these values some other way.

**Comment by franklouwers** [comment]
As explained on irc: I like the fact that `pdnsutil create-zone` inserts a "sane" SOA by default, and that we can control what "sane defaults" it uses.

So while I understand this issue is mostly about autofilling non-complete SOAs, I would still like create-zone to use those parameters to create SOAs. I would propose the first option then.

**Comment by mind04** [comment]
What is against creating a zone without records? 
I prefer an empty zone over a magic default zone that always need editing.

A much better solution, for example, is to add an import a zone file option to create-zone.

**Comment by zeha** [comment]
> What is against creating a zone without records?

The SOA's "disabled" field is used to disable the zone; and I think without the SOA record, various core bits don't "see" the zone. So at least that record has to exist.

**Comment by Habbie** [comment]
I don't have time for this for 4.3.0; postponing until 4.4.0. Will need to bump that number in settings.rst.
