### ISSUE TITLE
Recursor: unused lambda capture in unit tests

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#7949]
- Program: Recursor
 - Issue type: Bug report/Feature request 

### Short description
Compiler warning when compiling `test-syncres_cc8.cc`

### Environment

 - Operating system: Arch Linux
 - Software version: git (d26856a32e7506817c291c49d8eb5a60129dd751)
 - Software source: git

### Steps to reproduce
```
autoreconf -fi
CC=clang CXX=clang++ LD=lld ./configure --enable-unit-tests
make
```

### Expected behaviour
No warnings.

### Actual behaviour
```
test-syncres_cc8.cc:701:51: warning: lambda capture 'fixedNow' is not used [-Wunused-lambda-capture]
  sr->setAsyncCallback([target,&queriesCount,keys,fixedNow](const ComboAddress& ip, const DNSName& domain, int type, bool doTCP, bool sendRDQuery, int EDNS0Level, struct timeval* now, boost::optional<Netmask>& srcmask, boost::optional<const ResolveContext&> context, LWResult* res, bool* chained) {
                                                 ~^~~~~~~~
1 warning generated.
```

**Comment by fwSmit** [comment]
I'm on it!

**Comment by fwSmit** [comment]
I also managed to reproduce your problem on Arch linux by first changin the directory to pdns/pdns/recursordist and then executing the reproduce commands

**Comment by pieterlexis** [comment]
> This issue does not only exist for the test-syncres_cc8.cc file. When running your reproduce commands in the root of the repository I got these errors

see #7948

**Comment by fwSmit** [comment]
I copied what you did in #7952 and it seems to work for this issue as well.

**Comment by fwSmit** [comment]
I'm making a pull request right now
