### ISSUE TITLE
Feature request: API key permissions

### ISSUE THREAD

**Issue by boarder981** [PowerDNS/pdns#7959]
- Program: Authoritative
 - Issue type: Feature request

### Short description
It would be very useful to have the ability to define granular API permissions and/or support for multiple API keys with access to different resources/paths (i.e. list zones, access to view/edit records in one or more zones, etc)

### Use Case
I have an application that creates and deletes DNS records for two specific zones via the PowerDNS API.  Currently I need to provide my app the "god" API key, which is not only a potential security risk, but allows for accidental record manipulation in other zones (for example, if there's a code bug).

I would like the ability to define a RBAC-like permission scheme for my PowerDNS API.  That way I can let my app view and edit records in only specific zones, and prevent access to others.  Perhaps the ability to support multiple API keys, each with its own access definition.  JSON config could look something like this:

```
{
  "api_keys": [
    {
      "name": "key1",
      "value": "my-secret-api-key-1",
      "list_all_zones": true,
      "allowed_record_types": [
        "A",
        "CNAME",
        "TXT"
      ],
      "allowed_methods": [
        "GET",
        "POST",
        "PATCH",
        "DELETE"
      ],
      "zones": [
        "z1.example.com",
        "z2.example.com"
      ]
    },
    {
      "name": "key2",
      "value": "my-secret-api-key-2",
      "list_all_zones": false,
      "allowed_record_types": [
        "A",
        "TXT"
      ],
      "allowed_methods": [
        "GET"
      ],
      "zones": [
        "z3.example.com"
      ]
    }
  ]
}
```

Of course this is a very simple example.  I propose keeping a "god" access key, but at least this would allow the ability to give a certain level of access without potentially compromising your entire environment.

**Comment by pieterlexis** [comment]
Sorry, this is not part of the API design or mission statement, as requirements differ between every user of the PowerDNS Authortative Server You are encouraged to write your own (tiny) proxy or use one of the open source or commercially available frontends to get this functionality.

In this case, your application should take care that it does not do any wrong HTTP requests. Or you could put a proxy in front of the API that only allows access for the allowed methods to the allowed zones.

**Comment by Habbie** [comment]
https://github.com/catalyst/powerdns-auth-proxy is one such proxy.
