### ISSUE TITLE
auth: Dynamically check for execinfo.h instead of relying on guardrail macros

### ISSUE THREAD

**Issue by James-TR** [PowerDNS/pdns#7987]
- Program: Authoritative
 - Issue type: Bug report

### Short description
RE: #7980

> That patch is interesting. execinfo.h is supported under musl, but no good way to detect since it defines no macros. The long term solution is to test for it using configure.

_Originally posted by @neheb in https://github.com/openwrt/packages/pull/9304#issuecomment-505534814_

We should be dynamically checking if execinfo.h is available instead of relying on macros within the code. This could be done similar to how the check_os libatomic check was engineered.

### Environment

 - Operating system: OpenWRT
 - Software version: Trunk
 - Software source: OpenWRT

### Steps to reproduce

1. Compile against UCLIBC without the patch in #7980 
2. Compile against musl-libc

### Expected behaviour
The build will succeed and only pull in execinfo.h if it's supported on the platform being compiled against

### Actual behaviour
The build will fail on uclibc since it defines the __GLIBC__ macro. musl-libc won't pull this in at all, but will build fine otherwise.

**Comment by Habbie** [comment]
What we do today works for glibc and musl. If another libc comes along and causes trouble, we will deal with that again. There's no need to introduce complexity.
