### ISSUE TITLE
dnsdist 1.4.0 beta on Debian9 DoH error

### ISSUE THREAD

**Issue by ookangzheng** [PowerDNS/pdns#8002]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

When I configure DoH, I got this error
`Read configuration from '/etc/dnsdist/dnsdist.conf'
Fatal Lua error: [string "chunk"]:6: Unable to convert parameter from table to N5boost8optionalINS_7variantINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJSt6vectorISt4pairIiS7_ESaISA_EEEEEEE`

### Environment

 - Operating system: Debian9
 - Software version: 1.4.0 beta
 - Software source: from Debian dnsdist - version 1.4.X

### Steps to reproduce
dnsdist.conf DoH conf 
`addDOHLocal("[::]:443", "/etc/letsencrypt/archive/xx.com/fullchain1.pem", "/etc/letsencrypt/archive/xx.blahdns.com/privkey1.pem",{urls="/dns-query", doTCP=true, reusePort=true })
`

### Expected behaviour
everyting works correctly

**Comment by Habbie** [comment]
> `addDOHLocal("[::]:443", "/etc/letsencrypt/archive/xx.com/fullchain1.pem", "/etc/letsencrypt/archive/xx.blahdns.com/privkey1.pem",{urls="/dns-query", doTCP=true, reusePort=true })`

urls is not a named argument - can you try (untested) `addDOHLocal("[::]:443", "/etc/letsencrypt/archive/xx.com/fullchain1.pem", "/etc/letsencrypt/archive/xx.blahdns.com/privkey1.pem", "/dns-query", {doTCP=true, reusePort=true })` please?

**Comment by ookangzheng** [comment]
It works
Can I do something like this?
Sharing port 443 with DoH and DoT 
DoH will use when detect SNI dot-de.blahdns.com, otherwise will use DoT instead

```
addDOHLocal("[::]:443", "/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem", "/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem","/dns-query", {doTCP=true, reusePort=true })
addDOHLocal("0.0.0.0:443", "/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem", "/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem","/dns-query", {doTCP=true, reusePort=true })

addTLSLocal('0.0.0.0:853', '/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem', '/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem', { doTCP=true , reusePort=true})
addTLSLocal("[::]:853", '/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem', '/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem', { doTCP=true, reusePort=true})
addTLSLocal('0.0.0.0:443', '/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem', '/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem', { doTCP=true , reusePort=true})
addTLSLocal("[::]:443", '/etc/letsencrypt/archive/dot-de.blahdns.com/fullchain1.pem', '/etc/letsencrypt/archive/dot-de.blahdns.com/privkey1.pem', { doTCP=true, reusePort=true})
```

**Comment by Habbie** [comment]
We do not currently support sharing DoT and DoH on the same port. Please feel free to file a new ticket requesting that feature. As your problem has been resolved, I'm closing this ticket.
