### ISSUE TITLE
No Response to API Call

### ISSUE THREAD

**Issue by Rikairchy** [PowerDNS/pdns#8018]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I am able to successfully retrieve zone information from the API. Making a call to replace a record does not elicit a response as expected. The record is not updated, either.

### Environment

 - Operating system: CentOS 7.6
 - Software version: pdns-4.1.8-1.el7.x86_64
 - Software source: EPEL

### Steps to reproduce
Configuration:
```
api=yes
api-key=api_key
api-logfile=/var/log/pdns.log
launch=gmysql
gmysql-host=localhost
gmysql-user=db_user
gmysql-password=db_pass
gmysql-dbname=db_name
setgid=pdns
setuid=pdns
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=127.0.0.1/8,::1,1.2.3.4/32
```
1. Execute:

```
curl -H 'X-API-Key: api_key' \
    http://127.0.0.1:8081/api/v1/servers/localhost/zones/domain.tld. | jq .
```

2. Receive zone information

3. Execute:

```
curl -X PATCH --data '{"rrsets": [{
  "name": "sub.domain.tld.",
  "type": "A",
  "ttl": 86400,
  "changetype": "REPLACE",
  "records": [ {
    "content": "10.0.10.1",
    "disabled": false
  }]
}]}' -H 'X-API-Key: api_key' \
http://127.0.0.1:8081/api/v1/servers/localhost/zones/domain.tld.  | jq .
```

### Expected behaviour
The A record in question be updated, a successful response sent by the API

### Actual behaviour
No response from the API. The A record is not updated

### Other information
Current setup is two Authoritative servers. Sync is set via MariaDB on the backend. I have confirmed that there are no replication issues, just in case that might have something to do with it. Manual changes are propagated in under a second (single entries tested).

**Comment by Habbie** [comment]
> No response from the API. The A record is not updated

Please run `curl` with `-v` and without `| jq .`

**Comment by Habbie** [comment]
Also, unless you actually called your zone `domain.tld`, please provide real, unedited input and output.

**Comment by Rikairchy** [comment]
```
[root@ns1 log]# curl -v -X PATCH --data '{"rrsets": [{
>   "name": "dynamic.homelab.services.",
>   "type": "A",
>   "ttl": 86400,
>   "changetype": "REPLACE",
>   "records": [ {
>     "content": "10.0.10.1",
>     "disabled": false
>   }]
> }]}' -H 'X-API-Key: apikey' http://127.0.0.1:8081/api/v1/servers/localhost/zones/homelab.services.
* About to connect() to 127.0.0.1 port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PATCH /api/v1/servers/localhost/zones/homelab.services. HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8081
> Accept: */*
> X-API-Key: apikey
> Content-Length: 186
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 186 out of 186 bytes
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 0
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Server: PowerDNS/4.1.8
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
* Closing connection 0
[root@ns1 log]#
```

**Comment by Habbie** [comment]
> `< HTTP/1.1 204 No Content`

This should mean success. Can you show zone contents before and after your PATCH?

**Comment by Rikairchy** [comment]
I'm not sure how to query for one record directly, so I shall remove the other records:

```
[root@ns1 log]# curl -H 'X-API-Key: apikey' http://127.0.0.1:8081/api/v1/servers/localhost/zones/homelab.services. | jq .
```

```
...
    {
      "comments": [],
      "name": "dynamic.homelab.services.",
      "records": [
        {
          "content": "71.217.44.202",
          "disabled": false
        }
      ],
      "ttl": 86400,
      "type": "A"
    },
...
```
```
[root@ns1 log]# curl -v -X PATCH --data '{"rrsets": [{
>   "name": "dynamic.homelab.services.",
>   "type": "A",
>   "ttl": 86400,
>   "changetype": "REPLACE",
>   "records": [ {
>     "content": "10.0.10.1",
>     "disabled": false
>   }]
> }]}' -H 'X-API-Key: apikey' \
> http://127.0.0.1:8081/api/v1/servers/localhost/zones/homelab.services.
* About to connect() to 127.0.0.1 port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PATCH /api/v1/servers/localhost/zones/homelab.services. HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8081
> Accept: */*
> X-API-Key: apikey
> Content-Length: 186
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 186 out of 186 bytes
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 0
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Server: PowerDNS/4.1.8
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
* Closing connection 0
```

```
[root@ns1 log]# curl -H 'X-API-Key: apikey' http://127.0.0.1:8081/api/v1/servers/localhost/zones/homelab.services. | jq .
```
```
...
    {
      "comments": [],
      "name": "dynamic.homelab.services.",
      "records": [
        {
          "content": "71.217.44.202",
          "disabled": false
        }
      ],
      "ttl": 86400,
      "type": "A"
    },
...
```

**Comment by Habbie** [comment]
I have followed every step of what you did, and I do see the changed record.

**Comment by Habbie** [comment]
Are you running a simple mysqld, or some cluster? Can you show before/after with SQL queries against your database?

**Comment by Rikairchy** [comment]
I could provide the server address if you'd like to test against it directly.

**Comment by Rikairchy** [comment]
> Are you running a simple mysqld, or some cluster? Can you show before/after with SQL queries against your database?

I'm using two MariaDB databases. ns2 is set to use the database on ns1 as master. I did not set up any further clustering aside from that. Only changes I have made is the pdns prep and the poweradmin prep. Other than that, it should be standard A record entries.

**Comment by Habbie** [comment]
> I could provide the server address if you'd like to test against it directly.

That might be useful, but I do not have time for that today. As this is looking like a support question now, I'm closing this ticket. Please find us on IRC (European day time is best). Details are at https://www.powerdns.com/opensource.html
