### ISSUE TITLE
Output of ADDITIONAL SECTION wrong

### ISSUE THREAD

**Issue by weidnerd** [PowerDNS/pdns#8022]
Hello!

I am running an authoritative PowerDNS (4.1.10, Ubuntu Xenial).
I have noticed that the IP addresses of the name servers are displayed in the Additional Section. But one of them is wrong. **Where are these addresses configured?**
I have now deactivated the output via out-of-zone-additional-processing=no, because I had problems with the e-mail state.

Greetings and thanks!

Daniel

**Comment by franklouwers** [comment]
Dear Daniel,

Could you please provide the output you're getting and indicate how it would be wrong according to you? Without any info, this is impossible to debug.

**Comment by weidnerd** [comment]
dig ANY +additional foerster-kunststoff.de. @dns1.fkt-dns.de.

;; Truncated, retrying in TCP mode.

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.el6_10.3 <<>> ANY +additional foerster-kunststoff.de. @dns1.fkt-dns.de.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53697
;; flags: qr aa rd; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 5
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;foerster-kunststoff.de.		IN	ANY

;; ANSWER SECTION:
foerster-kunststoff.de.	3600	IN	A	193.31.25.211
foerster-kunststoff.de.	3600	IN	CAA	0 iodef "mailto:hostmaster@weidner.bayern"
foerster-kunststoff.de.	3600	IN	CAA	0 issue "\;"
foerster-kunststoff.de.	3600	IN	CAA	0 issuewild "swisssign.com"
foerster-kunststoff.de.	3600	IN	MX	10 mail.foerster-kunststoff.de.
foerster-kunststoff.de.	3600	IN	MX	20 exchange.foerster-kunststoff.de.
foerster-kunststoff.de.	3600	IN	NS	dns1.fkt-dns.de.
foerster-kunststoff.de.	3600	IN	NS	dns2.fkt-dns.de.
foerster-kunststoff.de.	3600	IN	NS	dns3.fkt-dns.de.
foerster-kunststoff.de.	3600	IN	TLSA	3 1 1 A1F16787E83C598DA12D5BC5026BC6EF08D37856959800FA47957FEA ED327CC3
foerster-kunststoff.de.	3600	IN	TXT	"v=spf1 a mx a:host1.weidner.bayern ip4:85.232.30.184/29 ip4:193.31.25.211 -all"
foerster-kunststoff.de.	3600	IN	SOA	dns1.fkt-dns.de. hostmaster.weidner.bayern. 2019070401 10800 3600 1209600 3600

;; ADDITIONAL SECTION:
mail.foerster-kunststoff.de. 3600 IN	A	85.232.30.185
exchange.foerster-kunststoff.de. 3600 IN A	85.232.30.186
dns1.fkt-dns.de.	3600	IN	A	188.68.51.26
dns2.fkt-dns.de.	3600	IN	A	185.16.61.192
dns3.fkt-dns.de.	3600	IN	A	**184.233.106.228**

;; Query time: 107 msec
;; SERVER: 188.68.51.26#53(188.68.51.26)
;; WHEN: Thu Jul  4 09:09:17 2019
;; MSG SIZE  rcvd: 553
`
184.233.106.228 should be 185.233.106.228

**Comment by franklouwers** [comment]
```
~ ❯❯❯ dig ANY  dns3.fkt-dns.de. @dns1.fkt-dns.de
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.10.6 <<>> ANY dns3.fkt-dns.de. @dns1.fkt-dns.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4338
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;dns3.fkt-dns.de.		IN	ANY

;; ANSWER SECTION:
dns3.fkt-dns.de.	3600	IN	A	184.233.106.228

;; Query time: 23 msec
;; SERVER: 2a03:4000:6:d214::22#53(2a03:4000:6:d214::22)
;; WHEN: Thu Jul 04 09:15:33 CEST 2019
;; MSG SIZE  rcvd: 60
```

Your dns1.fkt-dns.de server claims that dns3.fkt-dns.de (for which it is authoritative) has A 18**4**.233.106.228. If the real ip should be 18**5**.233.106.228, then my first action would be to double/tripple check that the fkt-dns.de doesn't contain a typo...

**Comment by weidnerd** [comment]
You're right. I've searched in a complete wrong direktion.
