### ISSUE TITLE
dnsdist file-descriptor count does not stop growing

### ISSUE THREAD

**Issue by appliedprivacy** [PowerDNS/pdns#8039]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

The fd-usage grows linearly over time and doesn't stop growing.

Depending on load the fd-usage grows by 500 - 2.5k per day.

### Environment

 - Operating system: Debian 10
 - Software version: 1.4.0~beta1-1pdns.buster
 - Software source:  PowerDNS repository

setup looks like this: nginx -> dnsdist -> unbound (all run on the same machine)
(it does not matter whether dnsdist is behind nginx or not)

### Steps to reproduce
 
1. setup dnsdist to accept DoH requests
2. send DoH requests to dnsdist
3. watch fd-usage counter

### Expected behaviour

fd-usage does not grow linearly.

### Actual behaviour

fd-usage does not stop growing over time.

### Other information

https://mailman.powerdns.com/pipermail/dnsdist/2019-July/000578.html
potentially related:
https://github.com/PowerDNS/pdns/pull/7927

**Comment by Habbie** [comment]
Can you provide the lsof output that was asked for on the mailinglist?

**Comment by appliedprivacy** [comment]
https://paste.debian.net/1090711/

dnsdist listeners
----------
443: DoH
5199: control socket
8083: webserver

**Comment by rgacogne** [comment]
I just merged #7927 and we should have updated packages in a short while. It would be great if you could upgrade and let us know if the situation stays the same :-)

**Comment by appliedprivacy** [comment]
We did an upgrade today and the problem appears to be solved. Very much appreciated!
1.4.0~beta1+master.313.gf24faa22f-1pdns.buster -> 1.4.0~beta1+master.331.ge71f84066-1pdns.buster
