### ISSUE TITLE
Query to '<SupermasterIP>' for SOA of 'hkv-grossrinderfeld.de' did not return a SOA

### ISSUE THREAD

**Issue by alorbach** [PowerDNS/pdns#8040]
- Program: Authoritative,
 - Issue type: Bug report

### Short description
powerdns not able to parse SOA of particular domain: "hkv-grossrinderfeld.de"

### Environment
 - Operating system: Debian 9.9
 - Software version: Master branch from https://repo.powerdns.com/
 - Software source: https://repo.powerdns.com/

### Steps to reproduce
We have a hidden Supermaster server with about 50 domains. 
**Only the domain "hkv-grossrinderfeld.de" causes this error:** 
"While checking domain freshness: Query to 'SupermasterIP' for SOA of 'hkv-grossrindefeld.de' did not return a SOA"
**Later this error:** 
"Unable to retrieve SOA for hkv-grossrindefeld.de, this was the first time. NOTE: For every subsequent failed SOA check the domain will be suspended from freshness checks for 'num-errors x 60 seconds', with a maximum of 3600 seconds. Skipping SOA checks until 1562585785"

**Many other Domains work like:** 
hkvgrossrindefeld.de
abc-abcdeabcdeabcde.de
abc-test.de
testdomain123.de

Configuration for the domains are: 
zone  "hkv-grossrindefeld.de" {
type slave;
file  "/etc/powerdns/zones/hkv-grossrindefeld.de";
masters { SupermasterIP; };
};

zone  "hkvgrossrindefeld.de" {
type slave;
file  "/etc/powerdns/zones/hkvgrossrindefeld.de";
masters { SupermasterIP; };
};

zone  "abc-abcdeabcdeabcde.de" {
type slave;
file  "/etc/powerdns/zones/abc-abcdeabcdeabcde.de";
masters { SupermasterIP; };
};

**Comment by Habbie** [comment]
Can you try `dig SOA hkv-grossrinderfeld.de @supermasterIP` and paste the output? Please do not change anything in the output.

**Comment by alorbach** [comment]
omg our fault lol ... it was a stupid typo.
