### ISSUE TITLE
SRVFAIL/NXDOMAIN ratio dynamic rule triggers

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#8045]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description
Add exceedServFailsRatio and exceedNXDOMAINsRatio dynamic block triggers

### Usecase
We see clients sending DDoS attack traffic to authoritative servers (we have dnsdist in front of recursive resolvers) by creating lots of random subdomain traffic that is valid, yet results in NXDOMAIN. Ultimately this leads to SERVFAIL from the target overloaded auth as a result of DDoS. There exist the dynamic rules of exceedServFails and exceedNXDOMAINs, but these can't be applied aggressively in our circumstance since we see legitimate traffic (large ISP forwarding caches, for instance) mixed in with bad actors and those two dynamic rules if applied across all clients will start throttling traffic to those legitimate origins as well as bad actors. What we'd like to do is examine the ratio of NOERROR to [servfail,nxdomain] as a rule, so that the bad actors are more easily tagged and managed without causing problems on larger legitimate customer traffic origins. This is not a cure-all; attackers may start sending legitimate traffic along with attack traffic to improve their ratios, but security is an incremental process and increasing the cost to the attacker is the goal.

### Description
New dynamic rules that use a ratio of bad:good queries would be useful:

exceedServFailsRatio(percentage, seconds, min queries)
exceedNXDOMAINRatio(percentage, seconds, min queries)

percentage: the percentage of traffic that is failing, as compared to NOERROR results

seconds: the number of seconds in which the sample comparison is performed

min queries: the minimum number of queries per second (overall) that must be generated by the target within the sample window to qualify for the rule. This prevents a low-volume client from getting triggered on a small number of bad queries that might occur naturally. (maybe a default value of 5 here?)

**Comment by johnhtodd** [comment]
Update: this is in response to attacks (which are still ongoing, at a very large scale) such as ExploderBot - https://www.researchgate.net/publication/328355903_ExploderBot_A_Slow_Drip_System

**Comment by rgacogne** [comment]
Implemented in #8274.
