### ISSUE TITLE
Fatal Lua error: [string "chunk"]:6: attempt to call global 'addDOHLocal' (a nil value)

### ISSUE THREAD

**Issue by misaka00251** [PowerDNS/pdns#8046]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

After upgrade Debian 9 to Debian 10, dnsdist is not working anymore.

### Environment

 - Operating system: Debian 10
 - Software version: dnsdist 1.3.3 (Lua 5.2.4)
 - Software source: Debian packages 

### Steps to reproduce

1. My `dnsdist.conf` file:
```
newServer({address="1.1.1.1", qps=10})
addDOHLocal("0.0.0.0", "/etc/nginx/ssl/example.com.crt", "/etc/nginx/ssl/example.com.key", "/dns-query", ciphersTLS13)
```
2. start the service

### Expected behaviour

dnsdist runs smoothly.

### Actual behaviour

```
Fatal Lua error: [string "chunk"]:6: attempt to call global 'addDOHLocal' (a nil value)
```

### Usecase

Use DoH in firefox.

**Comment by paddg** [comment]
DoH was added for 1.4.0. You have 1.3.3 https://dnsdist.org/reference/config.html?highlight=adddohlocal

Latest 1.4.0 is 1.4.0-beta1 https://dnsdist.org/changelog.html

**Comment by misaka00251** [comment]
XD Oops, Sorry!

**Comment by pieterlexis** [comment]
https://repo.powerdns.com/ has 1.4.0 for buster
