### ISSUE TITLE
recursor: Build failures on arc700 on OpenWRT

### ISSUE THREAD

**Issue by James-TR** [PowerDNS/pdns#8048]
- Program: Recursor
 - Issue type: Bug report

### Short description
Recursor is failing to build on arc700 on OpenWRT

Compile log: https://gist.github.com/James-TR/24a592896ab7760a408ea3facb07bd81

Relevant lines:
```
In file included from pdns_recursor.cc:53:
syncres.hh: In static member function 'static void SyncRes::pruneNSSpeeds(time_t)':
syncres.hh:451:3: error: unrecognizable insn:
   }
   ^
(insn 18 17 19 5 (set (reg:SI 166)
        (plus:SI (plus:SI (reg:SI 25 r25)
                (reg:SI 168))
            (const_int 20 [0x14]))) "syncres.hh":443 -1
     (expr_list:REG_EQUAL (const:SI (plus:SI (symbol_ref:SI ("_ZN7SyncRes10t_sstorageE") [flags 0xe0] <var_decl 0x7fe52faa8ab0 t_sstorage>)
                (const_int 20 [0x14])))
        (nil)))
during RTL pass: vregs
syncres.hh:451:3: internal compiler error: in extract_insn, at recog.c:2304
```

### Environment

 - Operating system: OpenWRT
 - Software version: 4.1.14
 - Software source: Compiling from OpenWRT packages feed

### Steps to reproduce
This should be reproducible by building against an arc700 target in the OpenWRT buildroot

### Expected behaviour
Code should compile without errors

### Actual behaviour
Code does not compile

### Other information
I'll be opening an issue in the OpenWRT packages repo for advice on how to aproach this

**Comment by rgacogne** [comment]
Smells like a compiler bug related to thread local storage, I'm not sure there is a lot we can do about it :'(

**Comment by James-TR** [comment]
Ok, I'll see what the peeps in openwrt/packages#9431 can find on the build bots. @ahupowerdns  suggested on IRC to add `-O0` to the Makefile possibly work around this in my build env

**Comment by James-TR** [comment]
I'm closing this issue as OpenWRT doesn't have much interest in going further since GCC8 is the first to support ARC. GCC9 may bring in fixes.
