### ISSUE TITLE
auth 4.2.0rc2 tar file seems to miss syncres.hh file

### ISSUE THREAD

**Issue by miesi** [PowerDNS/pdns#8062]
- Program: Authoritative
 - Issue type: Bug report

### Short description
while compiling devpollmplexer.cc gcc 8.3 complains
```
devpollmplexer.cc:36:10: fatal error: syncres.hh: No such file or directory
 #include "syncres.hh"
```

I can not find syncres.hh in the tar file downloaded from https://downloads.powerdns.com/releases/

### Environment

 - Operating system: SunOS 5.11 illumos-61233e713d, Linux fc30 5.1.16
 - Software version: 4.2.0rc2
 - Software source: https://downloads.powerdns.com/releases/

### Steps to reproduce
1. wget https://downloads.powerdns.com/releases/pdns-4.2.0-rc2.tar.bz2
2. tar jxvf pdns-4.2.0-rc2.tar.bz2 | grep syncres.hh

### Expected behaviour
syncres.hh on stdout

### Actual behaviour
no output, so file is not contained in tar.bz2

### Usecase
compile software

**Comment by Habbie** [comment]
>  #include "syncres.hh"

Can you try removing that line?

**Comment by miesi** [comment]
with #include "syncres.hh" removed, it compiles without issues.

How would you like to go on?

**Comment by Habbie** [comment]
> How would you like to go on?

a PR would be very welcome :)

**Comment by miesi** [comment]
Because this is on illumos, I'll first try it on Linux fc30 whether this also happens there. Please give me some minutes.

**Comment by Habbie** [comment]
> Because this is on illumos, I'll first try it on Linux fc30 whether this also happens there. Please give me some minutes.

devpollmplexer cannot be built on Linux, don't waste your time :)

**Comment by miesi** [comment]
PRs have been merged.
