### ISSUE TITLE
pkgs: Build for Raspbian Buster

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#8073]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request

### Short description
Supply packages for Raspbian Buster (just like Debian Buster, except using the Raspbian Docker images for builds).

### Usecase
Use up-to-date versions (especially Authoritative 4.2 when it is released) on Raspbian Buster systems.

**Comment by kpfleming** [comment]
It appears that 'master' builds are now available for Raspbian Buster, as I've just installed auth-master and it's working :-) Thanks!

**Comment by Habbie** [comment]
Thank you for confirming!

**Comment by kpfleming** [comment]
I'm not sure this is done yet though, because there aren't any packages for the 4.2 release.

**Comment by Habbie** [comment]
I believe that should happen automatically starting with the next release (4.2.0-rc2), but I'll leave this open just in case.

**Comment by Habbie** [comment]
`ii  pdns-server                          4.2.0~rc3-1pdns.buster      armhf        extremely powerful and versatile nameserver`

and stretch should work too!
