### ISSUE TITLE
AXFR + TSIG + ECS with dnsdist and pdns_auth backend fails with broken error

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#8098]
- Program: Recursor (maybe dnsdist)
 - Issue type: Bug report

### Short description
My setup consists of a dnsdist and a single pdns-authoritative backend. I have configured tsig for AXFRs, and everything runs fine when I perform a tsig-based dig axfr.

When I enable ECS in dnsdist, the dig +axfr returns a nasty error.

### Environment
 - Operating system: Centos 7
 - Software version: pdns-auth 4.1.latest + dnsdist 1.3.latest
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install the components, dnsdist on port 53, pdns-auth on 5300, dnsdist configured with:
`newServer({ name="a1", address="127.0.0.1:5300"})`
2. Enable axfr, create a zone, create a tsig key, assign to zone
3. Ensure you can use dig axfr with the tsig key
4. Change dnsdist config to:
`newServer({ name="a1", address="127.0.0.1:5300", useClientSubnet=true})`
5. dig axfr still works without tsig
6. when I try axfr WITH the tsig key, I get this:
```
hello@i1-r1 ~]$ dig axfr example.tld @35.228.242.29 -y 'hmac-sha1:testkey:xkS1J57nDi18rku+t8VlSNPwo9wmhjgZW6kP3N/tUL0='
;; communications error to 35.228.242.29#53: end of file
```
### Expected behaviour
axfr digs should work, just as before setting `useClientSubnet=true`

### Actual behaviour
EOF communications error in dig

### Other information
Will update the ticket later with a pcap

### Usecase
Enable ECS without breaking tsig axfr. Ultimate goal: log the ECS client ip when doing the tsig-based axfr instead of just the dnsdist ip.

### Description
Work :)

**Comment by franklouwers** [comment]
To clarify, this ticket is **not** about:

* Should we be able to use the ECS info in an ACL to allow/disallow axfr
* Should we handle TSIG in dnsdist

**Comment by Habbie** [comment]
> ### Expected behaviour
> 
> axfr digs should work, just as before setting `useClientSubnet=true`

This is impossible. The best expected behaviour we should be able to provide is that dig gives you an rcode (NOTAUTH) from the auth.

**Comment by franklouwers** [comment]
Yes, agree (after learning that the ecs is added to signed part). Still wouldn't drop an ugly error with logging :)
