### ISSUE TITLE
forward-zones recursor option takes multiple IPs for a domain.

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#81]
It would be helpful if the recursor could forward zones to multiple IPs.

For example I can say:

forward-zones=foozone.com=10.0.0.2

But what if 10.0.0.2 is down? I would like to forward requests to
another IP if the first fails, so something like this:

forward-zones=foozone.com=10.0.0.2;192.168.1.2

**Comment by atlanteg** [comment]
Can I use powerdns recursor as only-forwarding caching nameserver and with several forwarders for HA (or load-balancing) ?
Something like: forward-zones-recurse=<ANY(ALL)>=IP1-of-first-recursiveDNS;IP2-of-second-recursiveDNS
And how to configure it that way?

Thanks.

**Comment by Habbie** [comment]
@atlanteg this is a closed issue, and our bug tracker is not a support forum. Please see https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/ for an extensive description of the ways in which you can get support.

**Comment by atlanteg** [comment]
OK

**Comment by ankse** [comment]
Hello, how can set BIND forward PDNS SERVER?

i set 
zone "server.163.org" { type forward; forwarders { 10.0.0.1 port 53; }; };

but no use.
