### ISSUE TITLE
dnsdist: cache-maxTTL not used on NXDOMAIN responses

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#8102]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
When dnsdist caches an NXDOMAIN response, it uses the SOA TTL from the authority section without applying the maxTTL setting from the cache.

### Environment
 - Operating system: Ubuntu 14.04/18.04
 - Software version: dnsdist 1.3.3-2pdns
 - Software source: PowerDNS repository

### Steps to reproduce
dnsdist is used in front of an authoritative name server:
`cache = newPacketCache(500000, 10, 10, 60, 60, true)`

Send query which causes NXDOMAIN:
```
dig @localhost foo.nic.at
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53462

;; AUTHORITY SECTION:
nic.at.                 900     IN      SOA     ns4ext.univie.ac.at. domain-admin.univie.ac.at. 2019071706 3600 1800 1209600 900

```

Dump the cache:
```
; dnsdist's packet cache dump follows
;
foo.nic.at. 898 A ; key 2074219428, length 105, tcp 0, added 1563550354

```
### Expected behaviour
The TTL should be limited to maxTTL setting of the cache=10s.

### Actual behaviour
It seems maxxTTL is not used for NXDOMAIN responses. It works fine for other responses.

**Comment by rgacogne** [comment]
Did you try using `maxNegativeTTL`[1] instead?

[1]: https://dnsdist.org/reference/config.html?highlight=maxnegativettl#newPacketCache

**Comment by klaus3000** [comment]
Using maxNegativeTTL works as expected - I missed it as it is missing in the function definition on https://dnsdist.org/reference/config.html

**Comment by klaus3000** [comment]
I forgot to say thanks for the fast support :-)
