### ISSUE TITLE
dnsdist: cache:dump() is not documented

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#8103]
- Program: dnsdist
 - Issue type: Bug report

### Short description
The usefule cache:dump() feature is not documented - I found it by googling in the issues.

Please add it to: https://dnsdist.org/guides/cache.html

**Comment by rgacogne** [comment]
It is documented in the config reference: https://dnsdist.org/reference/config.html?highlight=dump#PacketCache the caching guide does not list all possible methods or parameters, as opposed to the reference.

**Comment by klaus3000** [comment]
Maybe add a warning on top of the guide that only the reference guide lists all parameters and options.
