### ISSUE TITLE
dnsdist: support DoT and DoH downstream servers

### ISSUE THREAD

**Issue by Chaz6** [PowerDNS/pdns#8104]
- Program: dnsdist
 - Issue type: Feature request

### Short description
It would be useful to allow a more flexible downstream configuration, allowing use of DNS-over-TLS and DNS-over-HTTPS servers.

### Usecase
Allow use of encrypted downstream dns servers for privacy protection. For instance, many platforms such as Android Pie only allow the use of a single server, so this would allow multiple servers to be used with health checks and balancing policies.

### Description
An example configuration snippet follows:-

`newServer({url="https://dns.google:443/dns-query", source="[2001:db8::53]@eth1", type=doh, name="google-doh"})`
`newServer({address="unicast.censurfridns.dk:853", type=dot, name="cfd-dot"})`
`newServer({address="8.8.8.8:53", type=udp, name="google-udp"})`
`newServer({address="8.8.8.8:53", type=tcp, name="google-tcp"})`

**Comment by rgacogne** [comment]
DNS over TLS toward backends will likely happen in 1.5.0 as I already have a branch with preliminary support for it. DNS over HTTPS toward backends seems a lot more unlikely to happen at the moment.

**Comment by appliedprivacy** [comment]
the DoT part is also in #6454

**Comment by keimond** [comment]
`newServer({url="https://dns.google:443/dns-query", type=doh, name="google-doh"})`
produces
`Fatal Lua error: [string "chunk"]:1: Caught exception: boost::bad_get: failed value get using boost::get`
with 1.4.0-rc3
I'm on CentOS 7, my boost package is boost-1.53.0-27.el7.x86_64... I'm curious if anyone might know off hand why I'm getting that error ?

**Comment by omoerbeek** [comment]
Read @rgacogne wrote.The feature is not yet available. DoT might happen in dnsdist 1.5, DoH likely not.

**Comment by keimond** [comment]
Wow yeah sorry should have read that more than once... well that works DoT is better than no encryption!

**Comment by stintel** [comment]
> DNS over TLS toward backends will likely happen in 1.5.0 as I already have a branch with preliminary support for it. DNS over HTTPS toward backends seems a lot more unlikely to happen at the moment.

@rgacogne any progress on that branch? I just gave 1.5.0-rc1 a try but seems your work didn't make it in there.

**Comment by rgacogne** [comment]
It did not make it into 1.5.0, sorry about that. It will definitely happen in 1.6.0, though, and I hope to have it in an alpha soon after the final 1.5.0 release.

**Comment by stintel** [comment]
> It did not make it into 1.5.0, sorry about that. It will definitely happen in 1.6.0, though, and I hope to have it in an alpha soon after the final 1.5.0 release.

No worries. Good to hear it will land in 1.6.0, thanks for the update and keep up the good work!

**Comment by johnhtodd** [comment]
While it may not be part of the commonly-used specifications currently utilized by centralized resolvers (yet) it may be useful for many enterprise (and even large DNS shops) to have a username and password pairing for access control or customized views.  (Certainly for DoH, less clear on DoT implementation)

**Comment by stintel** [comment]
> It did not make it into 1.5.0, sorry about that. It will definitely happen in 1.6.0, though, and I hope to have it in an alpha soon after the final 1.5.0 release.

No worries. Good to hear it will land in 1.6.0, thanks for the update and keep up the good work!

**Comment by fxkai** [comment]
i know, 1.6.0alpha is out only for some hours now, but i wonder wether the DoT downstream feature will make it in the release (or did i miss to find it in 1.6.0alpha)?

**Comment by rgacogne** [comment]
I'm sorry to say that my priorities shifted and that DoT downstream has been postponed to 1.7.0. The good news, however, is that it was postponed because we want to support it in a proper way, where it's not limited to queries coming over TCP or DoT but can also be used for queries coming over UDP, DoH, and likely DoQ in the future. That requires a bit more work because we need to handle truncation and EDNS UDP Payload Size, but I will start working on that feature very soon!

**Comment by Chaz6** [comment]
That is good news! Thank you for the update.

**Comment by rgacogne** [comment]
Ongoing work for this feature in https://github.com/PowerDNS/pdns/pull/10338

**Comment by rgacogne** [comment]
Implemented in #10338 and #10635.
