### ISSUE TITLE
Deleted record results in nsec and does not fallback to wildcard

### ISSUE THREAD

**Issue by nberlee** [PowerDNS/pdns#8114]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

When having a wildcard  record, and a record within the wildcard (override), powerdns services all records as expected. When deleting the more specific override, rectify the zone, powerdns will try to prove the non existice of the override instead of service the wildcard record.

### Environment

 - Operating system: Debian Stretch
 - Software version: 4.1.10
 - Software source: PowerDNS repository 

### Steps to reproduce

A zone with:
```
*.test.example.com A 127.0.0.1
tobedeleted.test.example.com A 127.0.0.2
```
Is working fine. `something.test.example.com` resolves to `127.0.0.1`, and `tobedeleted.test.example.com` resolves to `127.0.0.2`

Now delete `tobedeleted.test.example.com` and rectify the zone. 

### Expected behaviour

When querying tobedeleted.test.example.com should now result in `127.0.0.1`
### Actual behaviour

It proves its non existince of `tobedeleted.test.example.com`
### Other information

The rectify cli command is done with an older PowerDNS version, maybe thats my issue?

**Comment by pieterlexis** [comment]
> The rectify cli command is done with an older PowerDNS version, maybe thats my issue?

Please verify that using the *provided* `pdnsutil`, also what backend are you using and what other records exist?

**Comment by nberlee** [comment]
Backend is mysql. pdnsutil from 4.1.10 excibits the same issue
I couldn't replicate it in another zone , but found a record in the database which isn't showed by `pdnsutil list-zone` but is probably the problem
```
| 1808 |         8 | _tcp.tobedeleted.test.example.com               | NULL  | NULL                                                                                 |  NULL | NULL |        NULL |        0 | 1gph9b1ddenmu9s6ki9qh16bnvdgm4m9 |    1 |
```
I am uncertain how this could happen...   Is it safe to delete it using SQL or is there a better way to delete it using pdnsutil?

**Comment by pieterlexis** [comment]
NULL records are needed for Empty Non-Terminals, having this record means there is $something._tcp.tobedeleted.test.example.com record in the zone. So the fact that the wildcard does not match is correct, as tobedeleted.test.example.com is an ENT, and this is how wildcards in DNS works.

**Comment by nberlee** [comment]
For future reference, how can I see NULL records? as there not in `pdnsutil list-zone`

**Comment by pieterlexis** [comment]
> For future reference, how can I see NULL records? as there not in pdnsutil list-zone

In the database, please see the [documentation on DNSSEC and the database](https://docs.powerdns.com/authoritative/backends/generic-sql.html#handling-dnssec-signed-zones).

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).
