### ISSUE TITLE
builder.powerdns.com does not appear to build rel/auth-4.2.x, rel/auth-rec-4.2.x

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#8136]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description
`build-authoritative-pdns-builder(-armhf)` appears to only trigger on `master`. 

### Environment
https://builder.powerdns.com/

### Steps to reproduce
1. push/merge to rel/auth-4.2.x

### Expected behaviour
Buildbot does a pdns-builder build.

### Actual behaviour
It does not appear to be doing that.

### Other information
I think I've narrowed it down to somewhere around this code from our buildbot config (sorry readers, the full config is private right now) in `35-schedulers-pdns-builder.cfg`:
```
for module in pdns_builder_modules:
    sname = module + '-pdns-builder'
    bnames = ['build-' + module + '-pdns-builder']
    bnames_armhf = ['build-' + module + '-pdns-builder-armhf']

    c['schedulers'].append(schedulers.SingleBranchScheduler(
        name=sname,
        builderNames=bnames,
        treeStableTimer=120,
        change_filter=util.ChangeFilter(
            project='PowerDNS/pdns',
            branch='master'),
        properties={
            'build_targets': pdns_builder_targets
        }))
```

The ForceScheduler in the same file does not limit the branch so we can work around it through that right now.

**Comment by pieterlexis** [comment]
Added a pdns-builder config for rel/* branches and deployed
