### ISSUE TITLE
400 Oops! Bad request The server refused to process your request and return a 400 error. 

### ISSUE THREAD

**Issue by chandertechavidity** [PowerDNS/pdns#8137]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system: Ubuntu 18 Bionic LTS
 - Software version: V4.1.1
 - Software source: 

### Steps to reproduce

1. 
Create new domain using PowerDNS-Admin interface
2. 
3. 

### Expected behaviour

Domain should be created.
### Actual behaviour

Failed with error code 400
### Description

Jul 28 22:05:39 tadns pdns_server[2459]: Done launching threads, ready to distribute questions
Jul 28 22:08:33 tadns gunicorn[911]: [2019-07-28 22:08:33,102] [INFO] | User "admin" logged in successfully. Authentication request from 192.168.101.1
Jul 28 22:08:43 tadns gunicorn[911]: [2019-07-28 22:08:43,020] [DEBUG] | Starting new HTTP connection (1): tadns.techavidity.com:80
Jul 28 22:08:43 tadns gunicorn[911]: [2019-07-28 22:08:43,034] [DEBUG] | http://tadns.techavidity.com:80 "POST /api/v1/servers/localhost/zones HTTP/1.1" 400 30
Jul 28 22:08:43 tadns gunicorn[911]: [2019-07-28 22:08:43,035] [ERROR] | Cannot add domain techavidity.com.
Jul 28 22:08:43 tadns gunicorn[911]: [2019-07-28 22:08:43,035] [DEBUG] | Traceback (most recent call last):
Jul 28 22:08:43 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 124, in fetch_json
Jul 28 22:08:43 tadns gunicorn[911]:     assert('json' in r.headers['content-type'])
Jul 28 22:08:43 tadns gunicorn[911]: AssertionError
Jul 28 22:08:43 tadns gunicorn[911]: The above exception was the direct cause of the following exception:
Jul 28 22:08:43 tadns gunicorn[911]: Traceback (most recent call last):
Jul 28 22:08:43 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/models.py", line 1023, in add
Jul 28 22:08:43 tadns gunicorn[911]:     urljoin(self.PDNS_STATS_URL, self.API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
Jul 28 22:08:43 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 126, in fetch_json
Jul 28 22:08:43 tadns gunicorn[911]:     raise RuntimeError('Error while fetching {0}'.format(remote_url)) from e
Jul 28 22:08:43 tadns gunicorn[911]: RuntimeError: Error while fetching http://tadns.techavidity.com/api/v1/servers/localhost/zones

**Comment by Habbie** [comment]
Hello! PowerDNS-Admin is not our software - please see at https://github.com/ngoduykhanh/PowerDNS-Admin
