### ISSUE TITLE
pdns-recursor DNS resolve failed on IPv6 only VPS

### ISSUE THREAD

**Issue by ookangzheng** [PowerDNS/pdns#8147]
- Program: Recursor
 - Issue type: Bug report

### Short description

I install on https://ipv6onlyhosting.com/en-us/cms/ VPS, Debian 10, IPv6 only.
When I dig google.com, it return SERVFAIL. I install on IPv4, IPv6 VPS, everything works

my recursor.conf: https://privatebin.net/?05f04ee9807b5564#F8TK7x49yy4Xvhx44FjAdFxCtsKkYW6whtcpfWDRReqS

### Environment
 - Operating system: Debian 10 64bit
 - Software version: 4.2
 - Software source: PowerDNS repository

### Steps to reproduce
1. Start pdns-recursor
2. `dig google.com @::1 -p 5353`
3. return `SERVFAIL`

### Expected behavior
Expect DNS resolution works on IPV6 only VPS.

### Other information
I tried on Vultr VPS which have IPv4, v6. DNS resolution works

**Comment by Habbie** [comment]
> my recursor.conf: https://privatebin.net/?05f04ee9807b5564#F8TK7x49yy4Xvhx44FjAdFxCtsKkYW6whtcpfWDRReqS

Please don't use expiring pastebins.

Your config does not contain `query-local-address6`, which has this comment:

```
# query-local-address6	Source IPv6 address for sending queries. IF UNSET, IPv6 WILL NOT BE USED FOR OUTGOING QUERIES
```

So, please set that. If that does not help, please comment and we will reopen the ticket!
