### ISSUE TITLE
4.1.x for Debian Buster

### ISSUE THREAD

**Issue by Kraeutergarten** [PowerDNS/pdns#8155]
- Issue type: Feature request

### Short description
Debian provides the version 4.1.6 for Debian Buster, is there a reason for not adding 4.1.x to repo.powerdns.com for Debian Buster?

**Comment by Habbie** [comment]
The reason is that every combination of release train/distro version involves overhead and continuous work for us.

repo.powerdns.com has auth-4.2.0-rc2 for buster; we hope to do -rc3 next week, and 4.2.0 within a few more weeks.
