### ISSUE TITLE
Authoritative server 4.1.10 memory leak with bind backend

### ISSUE THREAD

**Issue by sthaug** [PowerDNS/pdns#8161]
- Program: Authoritative server version 4.1.10 
 - Issue type: Bug report 

### Short description

- Pdns configured as slave nameserver for the "no" zone, with a BIND server as master. The "no" zone is reasonably large - currently 3512726 lines and 354990510 bytes as stored by Pdns. The "no" zone contains DNSSEC information.
- Pdns configured with bind backend.
- When the master name server sends a notify, the "no" zone is transferred and stored. However, I can also see from "ps" that the memory size of the pdns process increases with more than a Gigabyte for each transfer of the zone from the master. Eventually the pdns process is killed because the system runs out of swap.

### Environment

 - Operating system: FreeBSD 11.3-STABLE and FreeBSD 12.0-STABLE (same problem for both).
 - Software version: Pdns authoritative 4.1.10.
 - Software source: Operating system repository (installed by the FreeBSD pkg system)

### Steps to reproduce

1. Install Pdns. "pkg install powerdns-4.1.10_3"
2. Create Sqlite3 database (because DNSSEC): pdnsutil create-bind-db /usr/local/etc/pdns/data/bind-dnssec-db.sqlite3
3. Configure Pdns to run as slave for the "no" domain using bind backend:
% diff pdns.conf-dist pdns.conf
10a11
> allow-axfr-ips=127.0.0.0/8, 193.69.2.2
20a22
> allow-notify-from=193.75.4.22
250a253,255
> launch=bind
> bind-config=/usr/local/etc/pdns/named.conf
> bind-dnssec-db=/usr/local/etc/pdns/data/bind-dnssec-db.sqlite3
260a266
> local-address=127.0.0.1,193.75.4.59
270a277
> local-ipv6=::1
495a503
> slave=yes
625a634
> xfr-max-received-mbytes=0

4. Add BIND config file: 
% cat /usr/local/etc/pdns/named.conf
options {
        directory "/usr/local/etc/pdns";
};

zone "no" { type slave; masters { 193.75.4.22; }; file "slave/no"; };

5. Start Pdns.

6. Observe memory usage regularly with the "ps" command.
### Expected behaviour

Large increase in memory usage the first time the "no" zone is transferred. Only very small increases thereafter, as new "no" subdomains are added.
### Actual behaviour

Dramatic increase in memory usage, e.g. "VSZ RSS" numbers:
Aug 5 10:10:15 7996788 7690468
Aug 5 10:11:15 8675820 8268724
Aug 5 10:12:15 9314832 8908928

**Comment by sthaug** [comment]
Some more examples of zone transfer from master vs memory usage:
1. Restart of server ("no" zone not transferred since it was up to date):
Aug  5 06:48:00 lab4 pdns[15037]: PowerDNS Authoritative Server 4.1.10 (C) 2001-2018 PowerDNS.COM BV
Aug  5 06:48:00 lab4 pdns[15037]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.

Memory usage (VSZ and RSS):
Aug 5 06:48:08 290832 274772
Aug 5 06:49:08 1159100 1130448

2. Zone transfer:
Aug  5 07:46:43 lab4 pdns[15037]: Domain 'no' is stale, master serial 2019080521, our serial 2019080483
Aug  5 07:46:43 lab4 pdns[15037]: Initiating transfer of 'no' from remote '193.75.4.22'
Aug  5 07:46:43 lab4 pdns[15037]: Starting AXFR of 'no' from remote 193.75.4.22:53
Aug  5 07:46:43 lab4 pdns[15037]: AXFR started for 'no'
Aug  5 07:47:10 lab4 pdns[15037]: AXFR of 'no' from remote 193.75.4.22:53 done
Aug  5 07:47:10 lab4 pdns[15037]: Backend transaction started for 'no' storage
Aug  5 07:49:23 lab4 pdns[15037]: Zone 'no' (/usr/local/etc/pdns/slave/no) reloaded
Aug  5 07:49:24 lab4 pdns[15037]: AXFR done for 'no', zone committed with serial number 2019080521

Memory usage:
Aug 5 07:46:10 1159316 1130648
Aug 5 07:47:10 2616108 2445384
Aug 5 07:48:10 3304964 3127896
Aug 5 07:49:10 4498004 4329796
Aug 5 07:50:10 4576584 4410104

3. Zone transfer:
Aug  5 08:11:14 lab4 pdns[15037]: Domain 'no' is stale, master serial 2019080522, our serial 2019080521
Aug  5 08:11:14 lab4 pdns[15037]: Initiating transfer of 'no' from remote '193.75.4.22'
Aug  5 08:11:14 lab4 pdns[15037]: Starting AXFR of 'no' from remote 193.75.4.22:53
Aug  5 08:11:14 lab4 pdns[15037]: AXFR started for 'no'
Aug  5 08:11:41 lab4 pdns[15037]: AXFR of 'no' from remote 193.75.4.22:53 done
Aug  5 08:11:41 lab4 pdns[15037]: Backend transaction started for 'no' storage
Aug  5 08:13:54 lab4 pdns[15037]: Zone 'no' (/usr/local/etc/pdns/slave/no) reloaded
Aug  5 08:13:55 lab4 pdns[15037]: AXFR done for 'no', zone committed with serial number 2019080522

Memory usage:
Aug 5 08:11:11 4576692 4410288
Aug 5 08:12:11 6372688 6067500
Aug 5 08:13:11 7077356 6763164
Aug 5 08:14:11 7996536 7690256

4. Zone transfer:
Aug  5 10:10:30 lab4 pdns[15037]: Domain 'no' is stale, master serial 2019080529, our serial 2019080522
Aug  5 10:10:30 lab4 pdns[15037]: Initiating transfer of 'no' from remote '193.75.4.22'
Aug  5 10:10:30 lab4 pdns[15037]: Starting AXFR of 'no' from remote 193.75.4.22:53
Aug  5 10:10:30 lab4 pdns[15037]: AXFR started for 'no'
Aug  5 10:10:56 lab4 pdns[15037]: AXFR of 'no' from remote 193.75.4.22:53 done
Aug  5 10:10:56 lab4 pdns[15037]: Backend transaction started for 'no' storage
Aug  5 10:13:07 lab4 pdns[15037]: Zone 'no' (/usr/local/etc/pdns/slave/no) reloaded
Aug  5 10:13:08 lab4 pdns[15037]: AXFR done for 'no', zone committed with serial number 2019080529

Memory usage:
Aug 5 10:10:15 7996788 7690468
Aug 5 10:11:15 8675820 8268724
Aug 5 10:12:15 9314832 8908928
Aug 5 10:13:15 9379836 8974172

5. Zone transfer:
Aug  5 12:10:12 lab4 pdns[15037]: Domain 'no' is stale, master serial 2019080530, our serial 2019080529
Aug  5 12:10:12 lab4 pdns[15037]: Initiating transfer of 'no' from remote '193.75.4.22'
Aug  5 12:10:12 lab4 pdns[15037]: Starting AXFR of 'no' from remote 193.75.4.22:53
Aug  5 12:10:12 lab4 pdns[15037]: AXFR started for 'no'
Aug  5 12:10:38 lab4 pdns[15037]: AXFR of 'no' from remote 193.75.4.22:53 done
Aug  5 12:10:38 lab4 pdns[15037]: Backend transaction started for 'no' storage
Aug  5 12:12:50 lab4 pdns[15037]: Zone 'no' (/usr/local/etc/pdns/slave/no) reloaded
Aug  5 12:12:51 lab4 pdns[15037]: AXFR done for 'no', zone committed with serial number 2019080530

Memory usage:
Aug 5 12:10:20 9379988 8974324
Aug 5 12:11:20 10312492 9806408
Aug 5 12:12:20 10744264 10236484
Aug 5 12:13:20 10778400 10270764

**Comment by sthaug** [comment]
Another possibly relevant comment: This server is currently not receiving queries at all - it is *only* transferring the "no" zone from the master (y.nic.no - 193.75.4.22).

**Comment by sthaug** [comment]
Any suggestions on how I can troubleshoot this further?

**Comment by zeha** [comment]
Could you maybe try this with 4.2.0-rc3?

**Comment by sthaug** [comment]
I've now tried 4.2.0 (release version), and I'm experiencing the same problem. Memory leak with the bind backend. I'm using a somewhat smaller zone for testing (oslo.no, around 2500 lines and 280 kByte as stored by pdns). Running a script to check the size of the pdns_server-instance process every minute, I see the process RSS growing with several hundre kBytes every time the zone is AXFRed from the master (every two hours):

Sep 15 12:04:34 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091424
Sep 15 14:04:50 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091425
Sep 15 16:05:35 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091426
Sep 15 18:04:38 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091427
Sep 15 20:05:24 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091428
Sep 15 22:05:11 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091429
Sep 16 00:04:50 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091430
Sep 16 02:05:37 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091431
Sep 16 04:04:56 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091608
Sep 16 06:05:39 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091609
Sep 16 08:05:14 lab3 pdns[5010]: AXFR done for 'oslo.no', zone committed with serial number 2019091610

The following shows date/time, VSZ, RSS, and RSS diff from previous (when the RSS diff is > 50 kByte):

Sep 15 12:05:05 63796 27492 2312
Sep 15 14:05:09 64664 28416 756
Sep 15 14:35:10 65960 29540 1072
Sep 15 16:06:13 67108 30580 964
Sep 15 18:05:17 67364 31112 468
Sep 15 20:06:21 68024 31756 544
Sep 15 22:05:26 68692 32484 676
Sep 16 00:05:29 69524 33228 676
Sep 16 02:06:34 70188 33956 652
Sep 16 04:05:37 71032 34720 704
Sep 16 06:05:41 71636 35364 576
Sep 16 08:05:45 72280 36072 640

And we see that it is clearly correlated with the time of the zone transfers.

I'd be happy to share the complete logs if that is of interest.

**Comment by sthaug** [comment]
The ps logs normally show a VSZ / RSS difference of zero, but right around the zone transfer we see growth in VSZ / RSS. Example from the last date/time given above:

Sep 16 08:00:45 71664 35408 0
Sep 16 08:01:45 71664 35408 0
Sep 16 08:02:45 71664 35412 4
Sep 16 08:03:45 71664 35416 4
Sep 16 08:04:45 71796 35432 16
Sep 16 08:05:45 72280 36072 640
Sep 16 08:06:45 72412 36080 8
Sep 16 08:07:45 72412 36080 0
Sep 16 08:08:45 72412 36084 4
Sep 16 08:09:45 72412 36084 0
Sep 16 08:10:45 72412 36084 0

**Comment by rgacogne** [comment]
Thanks for reporting this! Would you be able to send metrics to our public metronome server for a while? You can do that by setting `carbon-server=37.252.122.50` and `carbon-ourname` to the name you want to see appearing https://metronome.powerdns.com/?server=All&beginTime=-7200

**Comment by sthaug** [comment]
Now sending to the metronome server as “norselab” (the norse1 – norse5 recursive servers are also mine).

Note that this is a lab installation, currently only doing zone transfer of “oslo.no” when it gets notified, which is typically every 2 hours. It isn’t expected to regularly get any queries (though I’m sure there will be some “background query noise” now that it is reachable from the Internet).

If you’d like me to generate some query traffic I can certainly do that. But the memory leak I have reported appears without any query traffic at all – it seems correlated with the zone transfers.

**Comment by sthaug** [comment]
With some hours of statistics sent to the metronome server, we can clearly see the memory leak in the metronome graph also.

**Comment by sthaug** [comment]
Now almost a week of statistics. The memory leak seems to continue in a more or less linear fashion, with bumps every 2 hours (correlated with zone transfers).

**Comment by rgacogne** [comment]
Thanks, that's very helpful as it allows us to rule out a few things like some cache not cleaning up, for example. I tried to reproduce this issue and didn't succeed, but I was testing on Arch and with a different zone file. I can try to reproduce on FreeBSD, but it doesn't look like I can AXFR the zone you are using. Do you think you could try to reproduce it with a public zone, so I can make sure I'm using the exact same configuration?

**Comment by sthaug** [comment]
I can definitely let you AXFR the zone oslo.no, if you can give me the IP address of the server you want to AXFR from.

It’s not like there’s anything secret in the zone. Norid (responsible for .no and for instance oslo.no) likes to limit who can AXFR – but is well aware that even with NSEC3 there are ways to enumerate the zone.

As for the FreeBSD box itself, it’s running FreeBSD 12, with everything installed from packages (pkg install …). If you’re interested I could also let you have login there.

Regards,

Steinar Haug, AS2116

**Comment by sthaug** [comment]
If you'd like me to use a public zone - any suggestion for a suitable one that can be AXFRed?

**Comment by Habbie** [comment]
> I tried to reproduce this issue and didn't succeed, but I was testing on Arch and with a different zone file. I can try to reproduce on FreeBSD, but it doesn't look like I can AXFR the zone you are using.

I cannot reproduce on Debian. I have reproduced the leak on FreeBSD. Investigating!

**Comment by sthaug** [comment]
And if you'd like to AXFR the oslo.no zone I can make it available, just need your IP. But if you've already reproduced it with a different zone you may not need it.

**Comment by Habbie** [comment]
The leak does not appear to happen with the gsqlite3 backend.

**Comment by sthaug** [comment]
I have now run 4.2.0 for a while with the patch from #8350 manually applied - and everything looks good! No more memory leaks as far as I can see. Thanks!

**Comment by omoerbeek** [comment]
Thanks for the confirmation.

**Comment by carlos-n** [comment]
Is this issue solved in 4.2.1 or 4.2.2 ????
Thanks in advance.

**Comment by sthaug** [comment]
As far as I know you need 4.3.0 or newer.

**Comment by rgacogne** [comment]
#8350 has been backported to 4.2.x, and the ChangeLog mentions that issue should be fixed in 4.2.2.

**Comment by carlos-n** [comment]
I have updated to 4.2.2 and keep having the same leak as in 4.2.1.
I attach comparison graphs of used memory of the pdns process for the same type of server, same configuration with the same traffic and these versions of the software.
These servers run bind and pipe backends.


![pdns-memory-leak](https://user-images.githubusercontent.com/35890618/84654555-b4264a80-af0f-11ea-9ee1-bc6822e9c366.jpg)

Other servers running pdns-4.1.4-1 with the same configuration doesn't have the problem.
I'm going to try 4.3.0.

Should i open a new issue for this problem ????

**Comment by omoerbeek** [comment]
> I have updated to 4.2.2 and keep having the same leak as in 4.2.1.
> I attach comparison graphs of used memory of the pdns process for the same type of server, same configuration with the same traffic and these versions of the software.
> These servers run bind and pipe backends.
> 
> ![pdns-memory-leak](https://user-images.githubusercontent.com/35890618/84654555-b4264a80-af0f-11ea-9ee1-bc6822e9c366.jpg)
> 
> Other servers running pdns-4.1.4-1 with the same configuration doesn't have the problem.
> I'm going to try 4.3.0.
> 
> Should i open a new issue for this problem ????

Please open a new issue with all relevant info, including platform. This especially is important since this particular leak only occurs on *BSD.

**Comment by sthaug** [comment]
Just for your information, we're now running one of the authoritative servers for .no on 4.3.0 with the bind backend. Working very well for 3 weeks now, no sign of memory leaks. You can see the graphs here:

https://metrics.powerdns.com/?server=pdns.norse.auth&beginTime=-43200
