### ISSUE TITLE
pdns-recursor parsing fails every once in a while

### ISSUE THREAD

**Issue by kernel5017** [PowerDNS/pdns#8167]
Recursor version 4.1/4.2
 Issue type: Bug report

### Short description
recursor parsing fails every once in a while

### Environment
 - Operating system: centos7
 - Software version: recursor4.1/4.2
 - Software source:  yum install 

### Steps to reproduce
recursor parsing fails every once in a while
setuid=pdns-recursor
setgid=pdns-recursor
disable-syslog=no
dnssec=process-no-validate
dnssec-log-bogus=yes
forward-zones-recurse=.=114.114.114.114
log-common-errors=yes
logging-facility=0
threads=36
local-address=0.0.0.0
local-port=53
log-common-errors=yes
log-timestamp=yes
logging-facility=0
loglevel=9
network-timeout=1500
root-nx-trust=yes
setgid=pdns-recursor
setuid=pdns-recursor
trace=on

That is, all internal DNS requests are forwarded to 114.114.114.114 recursive server。

When my computer visits https://weibo.com, 70-80% of the images fail to load.But when my computer was directly configured to 114.114.114.114, nothing went wrong.

So I wrote a for loop and kept asking weibo.com. I found that failure would occur every once in a while, and the failure would last for 2-3 minutes, but during this period, there was no problem with my host ping 114.114.114.114.

The following is the log when parsing fails：
Jul 29 16:14:18 19 [1149/1] question for 'weibo.com|A' from 10.3.138.27
Jul 29 16:14:18 [1149] weibo.com: Wants DNSSEC processing, auth data in query for A
Jul 29 16:14:18 [1149] weibo.com: Looking for CNAME cache hit of 'weibo.com|CNAME'
Jul 29 16:14:18 [1149] weibo.com: No CNAME cache hit of 'weibo.com|CNAME' found
Jul 29 16:14:18 [1149] weibo.com: No cache hit for 'weibo.com|A', trying to find an appropriate NS record
Jul 29 16:14:18 [1149] : got TA for '.'
Jul 29 16:14:18 [1149] : setting cut state for . to Secure
Jul 29 16:14:18 [1149] weibo.com: initial validation status for weibo.com is Indeterminate
Jul 29 16:14:18 [1149] weibo.com: Cache consultations done, have 1 NS to contact
Jul 29 16:14:18 [1149] weibo.com: Domain has hardcoded nameserver
Jul 29 16:14:18 [1149] weibo.com: Resolved '.' NS (empty) to: 114.114.114.114
Jul 29 16:14:18 [1149] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:14:19 [1149] weibo.com: timeout resolving after 1621.67msec
Jul 29 16:14:19 [1149] weibo.com: Failed to resolve via any of the 1 offered NS at level '.'
Jul 29 16:14:19 [1149] weibo.com: failed (res=-1)
Jul 29 16:14:19 19 [1149/1] answer to question 'weibo.com|A': 0 answers, 0 additional, took 1 packets, 1621.67 netw ms, 1622.34 tot ms, 0 throttled, 1 timeouts, 0 tcp connections, rcode=2
Jul 29 16:14:19 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:14:20 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:14:20 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:14:21 19 question answered from packet cache tag=0 from 10.3.138.27
......
......
Jul 29 16:15:18 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:15:18 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:15:19 19 [1151/1] question for 'weibo.com|A' from 10.3.138.27
Jul 29 16:15:19 [1151] weibo.com: Wants DNSSEC processing, auth data in query for A
Jul 29 16:15:19 [1151] weibo.com: Looking for CNAME cache hit of 'weibo.com|CNAME'
Jul 29 16:15:19 [1151] weibo.com: No CNAME cache hit of 'weibo.com|CNAME' found
Jul 29 16:15:19 [1151] weibo.com: No cache hit for 'weibo.com|A', trying to find an appropriate NS record
Jul 29 16:15:19 [1151] : got TA for '.'
Jul 29 16:15:19 [1151] : setting cut state for . to Secure
Jul 29 16:15:19 [1151] weibo.com: initial validation status for weibo.com is Indeterminate
Jul 29 16:15:19 [1151] weibo.com: Cache consultations done, have 1 NS to contact
Jul 29 16:15:19 [1151] weibo.com: Domain has hardcoded nameserver
Jul 29 16:15:19 [1151] weibo.com: Resolved '.' NS (empty) to: 114.114.114.114
Jul 29 16:15:19 [1151] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:15:20 [1151] weibo.com: timeout resolving after 1541.96msec
Jul 29 16:15:20 [1151] weibo.com: Failed to resolve via any of the 1 offered NS at level '.'
Jul 29 16:15:20 [1151] weibo.com: failed (res=-1)
Jul 29 16:15:20 19 [1151/1] answer to question 'weibo.com|A': 0 answers, 0 additional, took 1 packets, 1541.96 netw ms, 1542.66 tot ms, 0 throttled, 1 timeouts, 0 tcp connections, rcode=2
Jul 29 16:15:20 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:15:21 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:15:21 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:15:22 19 question answered from packet cache tag=0 from 10.3.138.27
...
...
...
Jul 29 16:16:19 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:16:19 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:16:20 19 [1154/1] question for 'weibo.com|A' from 10.3.138.27
Jul 29 16:16:20 [1154] weibo.com: Wants DNSSEC processing, auth data in query for A
Jul 29 16:16:20 [1154] weibo.com: Looking for CNAME cache hit of 'weibo.com|CNAME'
Jul 29 16:16:20 [1154] weibo.com: No CNAME cache hit of 'weibo.com|CNAME' found
Jul 29 16:16:20 [1154] weibo.com: No cache hit for 'weibo.com|A', trying to find an appropriate NS record
Jul 29 16:16:20 [1154] : got TA for '.'
Jul 29 16:16:20 [1154] : setting cut state for . to Secure
Jul 29 16:16:20 [1154] weibo.com: initial validation status for weibo.com is Indeterminate
Jul 29 16:16:20 [1154] weibo.com: Cache consultations done, have 1 NS to contact
Jul 29 16:16:20 [1154] weibo.com: Domain has hardcoded nameserver
Jul 29 16:16:20 [1154] weibo.com: Resolved '.' NS (empty) to: 114.114.114.114
Jul 29 16:16:20 [1154] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:16:20 [1154] weibo.com: Got 4 answers from (empty) (114.114.114.114), rcode=0 (No Error), aa=0, in 4ms
Jul 29 16:16:20 [1154] weibo.com: accept answer 'weibo.com|A|180.149.138.56' from '.' nameservers? ttl=1, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:20 [1154] weibo.com: accept answer 'weibo.com|A|180.149.134.142' from '.' nameservers? ttl=1, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:20 [1154] weibo.com: accept answer 'weibo.com|A|180.149.134.141' from '.' nameservers? ttl=1, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:20 [1154] weibo.com: OPT answer '.' from '.' nameservers
Jul 29 16:16:20 [1154] : got initial zone status Indeterminate for record weibo.com
Jul 29 16:16:20 [1154] weibo.com: determining status after receiving this packet
Jul 29 16:16:20 [1154] weibo.com: answer is in: resolved to '180.149.138.56|A'
Jul 29 16:16:20 [1154] weibo.com: answer is in: resolved to '180.149.134.142|A'
Jul 29 16:16:20 [1154] weibo.com: answer is in: resolved to '180.149.134.141|A'
Jul 29 16:16:20 [1154] weibo.com: status=got results, this level of recursion done
Jul 29 16:16:20 [1154] weibo.com: validation status is Indeterminate
Jul 29 16:16:20 19 [1154/1] answer to question 'weibo.com|A': 3 answers, 0 additional, took 1 packets, 4.106 netw ms, 4.822 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
Jul 29 16:16:21 19 [1155/1] question for 'weibo.com|A' from 10.3.138.27
Jul 29 16:16:21 [1155] weibo.com: Wants DNSSEC processing, auth data in query for A
Jul 29 16:16:21 [1155] weibo.com: Looking for CNAME cache hit of 'weibo.com|CNAME'
Jul 29 16:16:21 [1155] weibo.com: No CNAME cache hit of 'weibo.com|CNAME' found
Jul 29 16:16:21 [1155] weibo.com: No cache hit for 'weibo.com|A', trying to find an appropriate NS record
Jul 29 16:16:21 [1155] : got TA for '.'
Jul 29 16:16:21 [1155] : setting cut state for . to Secure
Jul 29 16:16:21 [1155] weibo.com: initial validation status for weibo.com is Indeterminate
Jul 29 16:16:21 [1155] weibo.com: Cache consultations done, have 1 NS to contact
Jul 29 16:16:21 [1155] weibo.com: Domain has hardcoded nameserver
Jul 29 16:16:21 [1155] weibo.com: Resolved '.' NS (empty) to: 114.114.114.114
Jul 29 16:16:21 [1155] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:16:21 [1155] weibo.com: Got 4 answers from (empty) (114.114.114.114), rcode=0 (No Error), aa=0, in 18ms
Jul 29 16:16:21 [1155] weibo.com: accept answer 'weibo.com|A|180.149.134.142' from '.' nameservers? ttl=7, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:21 [1155] weibo.com: accept answer 'weibo.com|A|180.149.134.141' from '.' nameservers? ttl=7, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:21 [1155] weibo.com: accept answer 'weibo.com|A|180.149.138.56' from '.' nameservers? ttl=7, place=1 YES! - This answer was received from a server we forward to.
Jul 29 16:16:21 [1155] weibo.com: OPT answer '.' from '.' nameservers
Jul 29 16:16:21 [1155] : got initial zone status Indeterminate for record weibo.com
Jul 29 16:16:21 [1155] weibo.com: determining status after receiving this packet
Jul 29 16:16:21 [1155] weibo.com: answer is in: resolved to '180.149.134.142|A'
Jul 29 16:16:21 [1155] weibo.com: answer is in: resolved to '180.149.134.141|A'
Jul 29 16:16:21 [1155] weibo.com: answer is in: resolved to '180.149.138.56|A'
Jul 29 16:16:21 [1155] weibo.com: status=got results, this level of recursion done
Jul 29 16:16:21 [1155] weibo.com: validation status is Indeterminate
Jul 29 16:16:21 19 [1155/1] answer to question 'weibo.com|A': 3 answers, 0 additional, took 1 packets, 18.734 netw ms, 19.443 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
Jul 29 16:16:22 19 question answered from packet cache tag=0 from 10.3.138.27
Jul 29 16:16:23 19 question answered from packet cache tag=0 from 10.3.138.27

Oddly enough, the same configuration had similar problems with 4.1 and 4.2, but with master there were no problems at all, no parsing failures.

### Expected behaviour
failure should not normaly occur

### Actual behaviour
 parsing fails

**Comment by rgacogne** [comment]
Looking at the logs I don't see anything related to a parsing failure but instead that the recursor got not response from 114.114.114.114 after more than 1.5s, which seems to indicate either an intermittent network issue or an issue at 114.114.114.114:

```
Jul 29 16:14:18 [1149] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:14:19 [1149] weibo.com: timeout resolving after 1621.67msec
[...]
Jul 29 16:15:19 [1151] weibo.com: Trying IP 114.114.114.114:53, asking 'weibo.com|A'
Jul 29 16:15:20 [1151] weibo.com: timeout resolving after 1541.96msec
```

**Comment by omoerbeek** [comment]
Can you check that nameserver logs?

A possibility could be that the nameserver on 114.114.114.114 gets overloaded and a rate-limiting mechanism kicks in.

**Comment by omoerbeek** [comment]
Yo replied to this topic in another issue. Please report here in the proper, so that all information rekated to an issue is in one page.

If we need to study a 4.2 issue, it would help if you post the 4.2 logs as well. From that we can maybe learn what is going on and compare that to the master case.

**Comment by kernel5017** [comment]
> Can you check that nameserver logs?
> 
> A possibility could be that the nameserver on 114.114.114.114 gets overloaded and a rate-limiting mechanism kicks in.
The issue has been closed by you. Can I reply here?Or do I need to resubmit a ?

**Comment by kernel5017** [comment]
> You replied to this issue in another issue. Please report here in the proper issue, so that all information related to an issue is in one page.
> 
> If we need to study a 4.2 issue, it would help if you post the 4.2 logs as well. From that we can maybe learn what is going on and compare that to the master case.

The issue has been closed by you. Can I reply here?Or do I need to resubmit a ?

**Comment by omoerbeek** [comment]
This issue has not been closed.  You can still provide the logs asked for.

**Comment by Habbie** [comment]
Please provide the logs we asked for!

**Comment by omoerbeek** [comment]
Closing for lack of feedback
