### ISSUE TITLE
Outstanding query counter sometimes does not decrement

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#8185]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Outstanding queries counter does not decrement sometimes

### Environment
1.4 master, including patch from #8113 

### Steps to reproduce
We cannot reliably reproduce at this time. Perhaps this is due to a burst of outstanding queries? 

### Expected behaviour
Outstanding queries should be reduced as they are answered or error out.

### Actual behaviour
In some circumstances, outstanding queries do not decrement, leading to permanent incorrect policy application until restart.

### Other information
Update on issue from closed #8113 : we still see the problem occurring even after this change.

Here is an example from one of our systems that is showing this behavior. Pool2 is not decrementing the outstanding counters correctly. The cause for the failure to decrement is unknown. We do not have reproduce-able trigger circumstances, but do see it happening often and is causes build-up that renders the outstanding policy ineffective.

#   Name                 Address                       State     Qps    Qlim Ord Wt    Queries   Drops Drate   Lat Outstanding Pools
0   pool1-1              [::1]:22000                      up     0.0     200 100 100     106824    1465   0.0  95.2           0 ECS
1   pool1-2              [::1]:22000                      up     0.0     200 100 100     105157    1386   0.0 198.1           0 ECS
2   pool2-1              [::1]:22001                      up     0.0     200 100 100    8631534  277646   0.0 791.4         178 DP
3   pool2-2              [::1]:22001                      up     0.0     200 100 100    9479246  284874   0.0 778.3         210 DP
4   pool2-3              [::1]:22001                      up     0.0     200 100 100    8438413  289073   0.0 873.3         206 DP
5   pool2-4              [::1]:22001                      up     0.0     200 100 100    5540786  276649   0.0 876.9         218 DP
6   pool3-1              [::1]:22002                      up     0.0     200 100 100   14124029  231884   0.0 221.0          14 DP
7   pool3-2              [::1]:22002                      up     0.0     200 100 100   13324160  229408   0.0 215.8          18 DP
8   pool3-3              [::1]:22002                      up     0.0     200 100 100   13429779  221635   0.0 366.4           5 DP
9   pool3-4              [::1]:22002                      up     0.0     200 100 100   13751142  226417   0.0 254.5           3 DP
All                                                              0.0                  86931070 2040437

**Comment by bop1991** [comment]
Like

**Comment by rgacogne** [comment]
This issue appears to have been fixed in 1.4.0-rc5. I am closing this report, but I will re-open it should the issue arises again.
