### ISSUE TITLE
Feature Request: Configuring Supported Versions of TLS

### ISSUE THREAD

**Issue by brisulli** [PowerDNS/pdns#8203]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description

We would like to be able to configure what versions of TLS can be negotiated. We have a specific requirement to not let TLS version < 1.2 be negotiated. 

### Usecase

We do not want the TLS negotiation to select a version less than 1.2. 

### Description

We would like to be able to configure what versions of TLS are allowed to be negotiated.

**Comment by Habbie** [comment]
Duplicate of #8202?

**Comment by brisulli** [comment]
My bad .. I guess someone saw my post and added the feature request. I should have followed the directions and searched, my bad!
