### ISSUE TITLE
rec: Lua feature flags

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns#8205]
- Program: Recursor (perhaps also dnsdist)
 - Issue type: Feature request

### Short description

Currently it is not always easy to detect from Lua if we are running on a recursor that has certain features enabled or has a certain bugfix.

I suggest adding a global `pdns_features` table to the global Lua namespace with keys that can be checked in Lua code. Every time a certain feature would be added or a bug fixed that would be useful to test for, as key is added to this table.

### Usecase

PR #8001 fixed an issue where setting the `deviceName` would overwrite the `deviceId` in the protobuf instead.

There is however no way to test for the presence of this bugfix and the bug is not fixed in the current 4.2.0. Lua code cannot safely use the API to set the deviceName if it's running on a recursor that runs on an unfixed version, while it would be able to on a newer. The API itself did not change, so we cannot check for the presence of the function call to decide if we can call it.

Exposing the version is not very useful, as this would not give any meaningful results when running development versions from git.

### Description

Add an easy way to define feature flags in the Lua namespace. For example, for PR #8001 and the backport in #8101, we would effectively set the following global:

```lua
pdns_features = {
    PR8001_devicename = true,
}
```

Adding these flags needs to be convenient and should be done every time we add a significant Lua feature we might want to test for.

**Comment by omoerbeek** [comment]
Done.
