### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [PowerDNS/pdns#8212]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [GSQLBackend](https://github.com/PowerDNS/pdns/blob/e2cf2f96341648024ce6ea64cbc7fd685970d180/pdns/backends/gsql/gsqlbackend.hh#L41 "Destructor for GSQLBackend")
- [LdapBackend](https://github.com/PowerDNS/pdns/blob/9bb64785797d4b4829be3debc477458a7f81e7bd/modules/ldapbackend/ldapbackend.cc#L108 "Constructor for LdapBackend")
- [SingleThreadDistributor](https://github.com/PowerDNS/pdns/blob/1a4847819d1be96451353213d4dea6b0a1223805/pdns/distributor.hh#L79 "Destructor for SingleThreadDistributor")

**Comment by cmouse** [comment]
did you intend to open this as pull request?

**Comment by elfring** [comment]
Not yet.

How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by Habbie** [comment]
> How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html)?

Hello! This conversation is not really suitable for a ticket in this form, certainly not under this subject line. We do welcome pull requests cleaning up things, and we also welcome pull requests that make it easier for us to clean up things.
