### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [PowerDNS/pdns#8214]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/PowerDNS/pdns/blob/ab6603746ff2df310710f2b2ee665b5933e22eac/configure.ac#L46 "Update candidate")?

**Comment by Habbie** [comment]
Hello,

please stop opening (automated?) issues, ignoring our issue template, and ignoring my comments on other tickets pointing out that these tickets are not useful to us.

**Comment by elfring** [comment]
You might need more time to become aware of the usefulness for provided information.

Do you care for safer build checks because of variations for this software library?

**Comment by Habbie** [comment]
> You might need more time to become aware of the usefulness for provided information.

Thank you for that insight. You are now blocked from interacting with our repositories on GitHub.
