### ISSUE TITLE
Support ESNI and/or HTTPSSVC Resource Record

### ISSUE THREAD

**Issue by HLFH** [PowerDNS/pdns#8215]
- Program: Authoritative
 - Issue type: Feature request 

### Short description
The request is about supporting ESNI and/or HTTPSSVC DNS Resource Record as mentioned in the [ESNI Internet Draft](https://tools.ietf.org/html/draft-ietf-tls-esni-04#section-4.1) and the [HTTPSSVC Internet Draft](https://tools.ietf.org/html/draft-nygren-httpbis-httpssvc).

### Use case
Any browser correctly supporting ESNI (none at the moment, [Firefox only does it with DoH support](https://bugzilla.mozilla.org/show_bug.cgi?id=1500289 )) will be able to send a ClientHello message with an encrypted server_name to an HTTP server supporting ESNI (h2o built with picotls) thanks to the publishing of the DNS RR related to ESNI when pdns-auth will support it.

### Description
PDNS should support ESNI DNS Resource Record and/or HTTPSSVC Resource Records.
But openssl currently does not support [ESNI](https://github.com/openssl/openssl/issues/7482)...Only a [specific branch](https://github.com/sftcd/openssl) supports it.

[BIND9 might soon support HTTPSSVC RR](https://gitlab.isc.org/isc-projects/bind9/issues/1132) (under review process).

**Comment by Habbie** [comment]
It looks like they don't have assigned numbers yet, or am I missing something?

**Comment by wioxjk** [comment]
Any updates regarding this? :)

**Comment by zeha** [comment]
See #9369.

**Comment by Habbie** [comment]
https://doc.powerdns.com/authoritative/changelog/4.4.html#change-4.4.0-alpha1

> the SVCB and HTTPS record types are supported, with limited additional processing

(via #9369)
