### ISSUE TITLE
www.gpo.gov does not validate

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#8220]
- Program:  Recursor 
 - Issue type: Bug report 

### Short description

www.gpo.gov does not validate because dig @ns1.gpo.gov www.gpo.gov ds
responds with an NSEC3 record. 

### Environment

 - Operating system: OpeNBSD
 - Software version: master build as of 20 August 2019
 - Software source: compiled myself

### Steps to reproduce

1. dig www.gpo.gov (with dnssec validation turned on)

### Expected behaviour

Validated result, like other nameservers do.
Note that striclty speaking the NSEC3 response is not OK. Other NS implementation do not seem to suffer, though.

### Actual behaviour

SERVFAIL

### Other information

Trace log attached.

**Comment by omoerbeek** [comment]
[log.txt](https://github.com/PowerDNS/pdns/files/3519779/log.txt)

**Comment by rgacogne** [comment]
In my humble opinion we are right to go bogus after receiving the answer to the `www.gpo.gov.|DS` query. We could change our zone cuts detection mechanism to not use `DS` queries, but in the past it has proven to be as brittle as the current code when dealing with broken zones.

**Comment by Habbie** [comment]
Completely agreed, to be clear.

**Comment by mnordhoff** [comment]
#10057 might help this?

**Comment by rgacogne** [comment]
It does but I don't guarantee something else with that domain will not break!
