### ISSUE TITLE
Web-server monitoring issues

### ISSUE THREAD

**Issue by kernel5017** [PowerDNS/pdns#8221]
- Program: Recursor
 - Issue type: Bug report

### Short description
In web-server monitoring indicators are as follows:
     Version: PowerDNS recursor 4.2.0-rc1.598.master.g8338a7195, uptime: an hour, Number of 
     queries: 334937620 (115585 qps)
     Over-capacity-drops: 1100904, too old: 0
     Packet cache hitrate: 100.00%, Average response time: 0 ms, CPU Usage: 354.20%

But in the table on the right, domain's number column and servfail domain column are at the highest of 277 and don't grow.And remote's number column statistics are also inaccurate.QPS 100K+,number shouldn't be this many.

### Environment

 - Operating system: centos7
 - Software version:  PowerDNS recursor 4.2.0-rc1.598.master.g8338a7195(Other versions have the same problem)
 - Software source: PowerDNS repository

**Comment by omoerbeek** [comment]
A few questions:

1. Is the recursor actually doing it's job and is this a monitoring issue only?

2. Anything particular in the log? With 4.2, there is a `webserver-loglevel` setting (https://docs.powerdns.com/recursor/settings.html#webserver-loglevel) that can be set to `detailed`.

3. Are there any numbers or graphs in the web page updated or none at all? 

4. When observed from the OS, is the recursor also using 300%+ CPU? How many queries would you estimate the recursor is handling?

5. What does `rec_control get-all` show? Are these numbers reflecting reality?

6. Please  provide your `recursor.conf` settings file.

**Comment by kernel5017** [comment]
1.Recursor parsing is normal, but there is a problem with monitoring data (actually I think there is a problem, I posted a post earlier(https://github.com/PowerDNS/pdns/issues/8167), you replied that there is a problem with my network environment or DNS forwarding server.But I'm in a virtual machine installed version 4.2 and version of the master, the same network environment and the configuration, number of servfail in version 4.2 is the master version of servfail number more than dozens of times, my laptop DNS configured to version 4.2, even can't browse weibo.com and some other pictures more websites, but the laptop DNS configuration into the master version, without any problems)

2.I didn't turn on log, because the server crashed when I turned on log during the stress test

3.The dynamic graph in the web page is normal, but the table on the right is not updated, and the number column of queries table is 277.remote is also inaccurate, only a few thousand, but my QPS is 100K+.

4.Looking at the CPU on the operating system is also 300%+, my server CPU is 24 cores, 300%+ is not a problem.My goal is not to test how high QPS can be, but to test the number of servfail for version 4.2 and master

5.rec_control shows:
all-outqueries	1786814
answers-slow	674357
answers0-1	396795
answers1-10	888594
answers10-100	164882
answers100-1000	31618
auth-zone-queries	0
auth4-answers-slow	674332
auth4-answers0-1	30747
auth4-answers1-10	892686
auth4-answers10-100	157426
auth4-answers100-1000	31623
auth6-answers-slow	0
auth6-answers0-1	0
auth6-answers1-10	0
auth6-answers10-100	0
auth6-answers100-1000	0
cache-entries	1034
cache-hits	369741
cache-misses	1786505
case-mismatches	0
chain-resends	1169219
client-parse-errors	0
concurrent-queries	0
cpu-msec-thread-0	4386620
cpu-msec-thread-1	2808
cpu-msec-thread-10	1503389
cpu-msec-thread-11	1568709
cpu-msec-thread-12	2206
cpu-msec-thread-13	1493392
cpu-msec-thread-14	2625
cpu-msec-thread-15	2612
cpu-msec-thread-16	2586
cpu-msec-thread-17	2791
cpu-msec-thread-18	2825
cpu-msec-thread-19	2663
cpu-msec-thread-2	1603373
cpu-msec-thread-20	861984
cpu-msec-thread-21	2464
cpu-msec-thread-22	816300
cpu-msec-thread-23	2670
cpu-msec-thread-24	867663
cpu-msec-thread-25	790719
cpu-msec-thread-26	855842
cpu-msec-thread-27	1554628
cpu-msec-thread-28	1467342
cpu-msec-thread-29	2229
cpu-msec-thread-3	2499
cpu-msec-thread-30	819490
cpu-msec-thread-31	1492768
cpu-msec-thread-32	824761
cpu-msec-thread-33	2564
cpu-msec-thread-34	820488
cpu-msec-thread-35	2593
cpu-msec-thread-36	2682
cpu-msec-thread-4	2273
cpu-msec-thread-5	2815
cpu-msec-thread-6	2873
cpu-msec-thread-7	2892
cpu-msec-thread-8	2955
cpu-msec-thread-9	2920
dlg-only-drops	0
dnssec-authentic-data-queries	0
dnssec-check-disabled-queries	0
dnssec-queries	0
dnssec-result-bogus	2
dnssec-result-indeterminate	0
dnssec-result-insecure	0
dnssec-result-nta	0
dnssec-result-secure	0
dnssec-validations	2
dont-outqueries	0
ecs-queries	0
ecs-responses	0
edns-ping-matches	0
edns-ping-mismatches	0
empty-queries	0
failed-host-entries	0
fd-usage	270
ignored-packets	0
ipv6-outqueries	0
ipv6-questions	0
malloc-bytes	0
max-cache-entries	1000000
max-mthread-stack	15504
max-packetcache-entries	500000
negcache-entries	0
no-packet-error	0
noedns-outqueries	0
noerror-answers	710045290
noping-outqueries	0
nsset-invalidations	0
nsspeeds-entries	29
nxdomain-answers	0
outgoing-timeouts	577885
outgoing4-timeouts	577885
outgoing6-timeouts	0
over-capacity-drops	2323152
packetcache-entries	17
packetcache-hits	708480548
packetcache-misses	4479430
policy-drops	0
policy-result-custom	0
policy-result-drop	0
policy-result-noaction	2156246
policy-result-nodata	0
policy-result-nxdomain	0
policy-result-truncate	0
qa-latency	0
query-pipe-full-drops	0
questions	712959128
real-memory-usage	5167263744
rebalanced-queries	0
resource-limits	0
security-status	0
server-parse-errors	0
servfail-answers	590680
spoof-prevents	0
sys-msec	9172095
tcp-client-overflow	0
tcp-clients	0
tcp-outqueries	0
tcp-questions	0
throttle-entries	0
throttled-out	1821
throttled-outqueries	1821
too-old-drops	0
truncated-drops	0
udp-in-errors	0
udp-noport-errors	1444895
udp-recvbuf-errors	0
udp-sndbuf-errors	0
unauthorized-tcp	0
unauthorized-udp	0
unexpected-packets	0
unreachables	10974
uptime	6307
user-msec	12735704
variable-responses	0
x-our-latency	0
x-ourtime-slow	32
x-ourtime0-1	2143037
x-ourtime1-2	173
x-ourtime16-32	101
x-ourtime2-4	1121
x-ourtime4-8	11221
x-ourtime8-16	561

6.config file
setuid=pdns-recursor
setgid=pdns-recursor
disable-syslog=yes
dnssec=process-no-validate
dnssec-log-bogus=yes
forward-zones-recurse=.=114.114.114.114
log-common-errors=yes
logging-facility=0
threads=36
local-address=0.0.0.0
local-port=53
log-common-errors=yes
log-timestamp=yes
logging-facility=0
loglevel=3
network-timeout=1500
root-nx-trust=yes
setgid=pdns-recursor
setuid=pdns-recursor
trace=on
webserver=yes
webserver-address=0.0.0.0
webserver-password=123
api-key=123

packetcache-servfail-ttl=0

By the way of https://github.com/PowerDNS/pdns/issues/8167。
When I replied to this post, I received your reply to #8167.thanks

Let me describe it briefly:
I created a recursor server that is set to recursor for all office computers in the company.
After using it for about half an hour, all the employees reported problems with the Internet access, especially the inability to open pictures. This is also the case with me. If there are many pictures in a website, almost 80% of the pictures cannot be opened.After that, I paused recursor servers and changed the 4.2 version to master, with the same profile.After the replacement, the above problems are gone.But the master version is still in beta and cannot be used in a formal environment, so I would like to know what caused it.

In the previous post, your colleague replied that there was something wrong with my network or dns114.114.114.114, but I configured other DNS with the same problem.And the network environment of two virtual machines under the same host should be the same. The 4.2 version has problems, and the master version has almost no problems. How can this be?

You said 114.114.114.114 the server is overloaded or has reached a rate limit.However, when I switched the DNS of the company to bind, there was never any problem that the website could not be opened, and my bind server was also forwarded to 114.114.114.114. There was never any problem that the picture could not be opened, so I thought there was no problem with my network.

**Comment by kernel5017** [comment]
g

> A few questions:
> 
> 1. Is the recursor actually doing its job and is this a monitoring issue only?
> 2. Anything particular in the log? With 4.2, there is a `webserver-loglevel` setting (https://docs.powerdns.com/recursor/settings.html#webserver-loglevel) that can be set to `detailed`.
> 3. Are there any numbers or graphs in the web page updated or none at all?
> 4. When observed from the OS, is the recursor also using 300%+ CPU? How many queries would you estimate the recursor is handling?
> 5. What does `rec_control get-all` show? Are these numbers reflecting reality?
> 6. Please  provide your `recursor.conf` settings file.

1.Recursor parsing is normal, but there is a problem with monitoring data (actually I think there is a problem, I posted a post earlier(#8167), you replied that there is a problem with my network environment or DNS forwarding server.But I'm in a virtual machine installed version 4.2 and version of the master, the same network environment and the configuration, number of servfail in version 4.2 is the master version of servfail number more than dozens of times, my laptop DNS configured to version 4.2, even can't browse weibo.com and some other pictures more websites, but the laptop DNS configuration into the master version, without any problems)

2.I didn't turn on log, because the server crashed when I turned on log during the stress test

3.The dynamic graph in the web page is normal, but the table on the right is not updated, and the number column of queries table is 277.remote is also inaccurate, only a few thousand, but my QPS is 100K+.

4.Looking at the CPU on the operating system is also 300%+, my server CPU is 24 cores, 300%+ is not a problem.My goal is not to test how high QPS can be, but to test the number of servfail for version 4.2 and master

5.rec_control shows:
all-outqueries	1786814
answers-slow	674357
answers0-1	396795
answers1-10	888594
answers10-100	164882
answers100-1000	31618
auth-zone-queries	0
auth4-answers-slow	674332
auth4-answers0-1	30747
auth4-answers1-10	892686
auth4-answers10-100	157426
auth4-answers100-1000	31623
auth6-answers-slow	0
auth6-answers0-1	0
auth6-answers1-10	0
auth6-answers10-100	0
auth6-answers100-1000	0
cache-entries	1034
cache-hits	369741
cache-misses	1786505
case-mismatches	0
chain-resends	1169219
client-parse-errors	0
concurrent-queries	0
cpu-msec-thread-0	4386620
cpu-msec-thread-1	2808
cpu-msec-thread-10	1503389
cpu-msec-thread-11	1568709
cpu-msec-thread-12	2206
cpu-msec-thread-13	1493392
cpu-msec-thread-14	2625
cpu-msec-thread-15	2612
cpu-msec-thread-16	2586
cpu-msec-thread-17	2791
cpu-msec-thread-18	2825
cpu-msec-thread-19	2663
cpu-msec-thread-2	1603373
cpu-msec-thread-20	861984
cpu-msec-thread-21	2464
cpu-msec-thread-22	816300
cpu-msec-thread-23	2670
cpu-msec-thread-24	867663
cpu-msec-thread-25	790719
cpu-msec-thread-26	855842
cpu-msec-thread-27	1554628
cpu-msec-thread-28	1467342
cpu-msec-thread-29	2229
cpu-msec-thread-3	2499
cpu-msec-thread-30	819490
cpu-msec-thread-31	1492768
cpu-msec-thread-32	824761
cpu-msec-thread-33	2564
cpu-msec-thread-34	820488
cpu-msec-thread-35	2593
cpu-msec-thread-36	2682
cpu-msec-thread-4	2273
cpu-msec-thread-5	2815
cpu-msec-thread-6	2873
cpu-msec-thread-7	2892
cpu-msec-thread-8	2955
cpu-msec-thread-9	2920
dlg-only-drops	0
dnssec-authentic-data-queries	0
dnssec-check-disabled-queries	0
dnssec-queries	0
dnssec-result-bogus	2
dnssec-result-indeterminate	0
dnssec-result-insecure	0
dnssec-result-nta	0
dnssec-result-secure	0
dnssec-validations	2
dont-outqueries	0
ecs-queries	0
ecs-responses	0
edns-ping-matches	0
edns-ping-mismatches	0
empty-queries	0
failed-host-entries	0
fd-usage	270
ignored-packets	0
ipv6-outqueries	0
ipv6-questions	0
malloc-bytes	0
max-cache-entries	1000000
max-mthread-stack	15504
max-packetcache-entries	500000
negcache-entries	0
no-packet-error	0
noedns-outqueries	0
noerror-answers	710045290
noping-outqueries	0
nsset-invalidations	0
nsspeeds-entries	29
nxdomain-answers	0
outgoing-timeouts	577885
outgoing4-timeouts	577885
outgoing6-timeouts	0
over-capacity-drops	2323152
packetcache-entries	17
packetcache-hits	708480548
packetcache-misses	4479430
policy-drops	0
policy-result-custom	0
policy-result-drop	0
policy-result-noaction	2156246
policy-result-nodata	0
policy-result-nxdomain	0
policy-result-truncate	0
qa-latency	0
query-pipe-full-drops	0
questions	712959128
real-memory-usage	5167263744
rebalanced-queries	0
resource-limits	0
security-status	0
server-parse-errors	0
servfail-answers	590680
spoof-prevents	0
sys-msec	9172095
tcp-client-overflow	0
tcp-clients	0
tcp-outqueries	0
tcp-questions	0
throttle-entries	0
throttled-out	1821
throttled-outqueries	1821
too-old-drops	0
truncated-drops	0
udp-in-errors	0
udp-noport-errors	1444895
udp-recvbuf-errors	0
udp-sndbuf-errors	0
unauthorized-tcp	0
unauthorized-udp	0
unexpected-packets	0
unreachables	10974
uptime	6307
user-msec	12735704
variable-responses	0
x-our-latency	0
x-ourtime-slow	32
x-ourtime0-1	2143037
x-ourtime1-2	173
x-ourtime16-32	101
x-ourtime2-4	1121
x-ourtime4-8	11221
x-ourtime8-16	561

6.config file
setuid=pdns-recursor
setgid=pdns-recursor
disable-syslog=yes
dnssec=process-no-validate
dnssec-log-bogus=yes
forward-zones-recurse=.=114.114.114.114
log-common-errors=yes
logging-facility=0
threads=36
local-address=0.0.0.0
local-port=53
log-common-errors=yes
log-timestamp=yes
logging-facility=0
loglevel=3
network-timeout=1500
root-nx-trust=yes
setgid=pdns-recursor
setuid=pdns-recursor
trace=on
webserver=yes
webserver-address=0.0.0.0
webserver-password=123
api-key=123

packetcache-servfail-ttl=0

By the way of https://github.com/PowerDNS/pdns/issues/8167。
When I replied to this post, I received your reply to #8167.thanks

Let me describe it briefly:
I created a recursor server that is set to recursor for all office computers in the company.
After using it for about half an hour, all the employees reported problems with the Internet access, especially the inability to open pictures. This is also the case with me. If there are many pictures in a website, almost 80% of the pictures cannot be opened.After that, I paused recursor servers and changed the 4.2 version to master, with the same profile.After the replacement, the above problems are gone.But the master version is still in beta and cannot be used in a formal environment, so I would like to know what caused it.

In the previous post, your colleague replied that there was something wrong with my network or dns114.114.114.114, but I configured other DNS with the same problem.And the network environment of two virtual machines under the same host should be the same. The 4.2 version has problems, and the master version has almost no problems. How can this be?

You said 114.114.114.114 the server is overloaded or has reached a rate limit.However, when I switched the DNS of the company to bind, there was never any problem that the website could not be opened, and my bind server was also forwarded to 114.114.114.114. There was never any problem that the picture could not be opened, so I thought there was no problem with my network.

**Comment by omoerbeek** [comment]
Please do not mix the discussion of the two issues.

This issue is about the web server monitoring page.

**Comment by omoerbeek** [comment]
Looking at your stats, it looks like you are overloading the recursor. Indications are `outgoing-timeouts 577885` and `over-capacity-drops 2323152`. The latter could also explain why the web server thread is not functioning., it is beaing starved of resources.

So far this looks not like a bug, but a question of tuning and sizing.  Please refer to the support channels available (irc and mailing list) to get help. See https://www.powerdns.com/opensource.html

**Comment by kernel5017** [comment]
> Looking at your stats, it looks like you are overloading the recursor. Indications are `outgoing-timeouts 577885` and `over-capacity-drops 2323152`. The latter could also explain why the web server thread is not functioning., it is beaing starved of resources.
> 
> So far this looks not like a bug, but a question of tuning and sizing. Please refer to the support channels available (irc and mailing list) to get help. See https://www.powerdns.com/opensource.html
Thank you for your reply. I will conduct the test after tuning. Thank you.

**Comment by kernel5017** [comment]
> Looking at your stats, it looks like you are overloading the recursor. Indications are `outgoing-timeouts 577885` and `over-capacity-drops 2323152`. The latter could also explain why the web server thread is not functioning., it is beaing starved of resources.
> 
> So far this looks not like a bug, but a question of tuning and sizing. Please refer to the support channels available (irc and mailing list) to get help. See https://www.powerdns.com/opensource.html

Thank you for your reply. I will conduct the test after tuning. Thank you.

**Comment by kernel5017** [comment]
> Looking at your stats, it looks like you are overloading the recursor. Indications are `outgoing-timeouts 577885` and `over-capacity-drops 2323152`. The latter could also explain why the web server thread is not functioning., it is beaing starved of resources.
> 
> So far this looks not like a bug, but a question of tuning and sizing. Please refer to the support channels available (irc and mailing list) to get help. See https://www.powerdns.com/opensource.html

Hello, I did a test just now, one DNS request per second. Surely the load of the server will not be overloaded this time, right?
CPU usage was 1%, but the number column of queries in web-server web pages grew to 277.
The number of queries keeps growing, but the number column stops growing to 277.
Is there something wrong with my configuration?
