### ISSUE TITLE
PowerDNS Recursor RPZ CNAME resolution.

### ISSUE THREAD

**Issue by oliken** [PowerDNS/pdns#8233]
. Program: PowerDNS Recursor 4.2.0 with RZP zone
. Issue type: Feature request

### Usecase
Recursor try A record resolution locally on the RPZ Zone before the external DNS resolution.

### Description

Hi,
We're using pdns recursor with RPZ resolution for our company internal name resolution. In some of our Zones are CNAMEs.
Getting the A records works fine. But when looking up a CNAME, the answer only contains the CNAME.
The recursor seems to try to resolve the CNAME result only with external DNS not with the internal RPZ zone. If there is a A record on external DNS they work, if not, they only return CNAME without telling again RPZ Zone. 
Is there a way for the recursor pdns to try A record resolution locally on the RPZ Zone before the external DNS resolution?

Is there a way to have a complete resolution with recursor?

Full Example (if we have this entries on the RPZ zone):

```
*.devs.gesc.galilee.fr	CNAME	devs.gesc.galilee.fr
devs.gesc.galilee.fr		A	192.168.171.188	
```
```
$ dig @pcc.rpz.dns.galilee.fr *.devs.gesc.galilee.fr
;; ANSWER SECTION:
*.devs.gesc.galilee.fr. 3600	IN	CNAME	devs.gesc.galilee.fr.

$ dig @pcc.rpz.dns.galilee.fr devs.gesc.galilee.fr
;; ANSWER SECTION:
devs.gesc.galilee.fr. 3600	IN	A	192.168.171.188
```
```
With a BIND RPZ zone for example i have this result:
$ dig @pcc.rpz.dns.galilee.fr *.devs.gesc.galilee.fr
;; ANSWER SECTION:
*.devs.gesc.galilee.fr. 3600	IN	CNAME	devs.gesc.galilee.fr.
devs.gesc.galilee.fr. 3600	IN	A	192.168.171.188
```

Is there a way for the recursor pdns to try A record resolution locally on the RPZ Zone before the external DNS resolution?

Thanks in advance.
Best regards.

**Comment by omoerbeek** [comment]
At the moment, the code that handles CNAME chasing explicitly goes "outside" and skips looking into the RPZ (`handleRPZCustom()` in `pdns_recursor.cc`). The code is structured in such a way that it is not easy to change that. Will need to be looked at further.

**Comment by omoerbeek** [comment]
@rgacogne comments:

Re-reading the RPZ specs, I'm wondering if this is the right thing to do. Especially based on Section 6 1:

    RPZ rules do not apply to synthetic data generated by using RPZ
    rules. For example, if RPZ supplies a CNAME pointing to a walled
    garden, RPZ policies will not be used while following that CNAME. If
    RPZ supplies local data giving a particular A record, RPZ policies
    will not apply to that response IP address.

So it looks like what you want is *explicitly* out-of-spec.
