### ISSUE TITLE
Some dq methods return empty data or cause hangs in DnstapLogAction's alterFunction

### ISSUE THREAD

**Issue by dmccombs** [PowerDNS/pdns#8306]
- Program: dnsdist
 - Issue type: Bug report

### Short description
When passing an `alterFunction` parameter to `DnstapLogAction`, some methods of `dq` return unexpectedly empty data (like `dq:getTrailingData` on `1.4.0-rc2`) or cause the query to hang entirely, not be logged, and timeout (like with `dq:len` on `1.3.3` or `1.4.0-rc2`). It's as if `DnstapLogAction` is running the `alterFunction` before the `dq` object is fully initialized.

### Environment
 - Operating system: Linux kernel version 5.2.14
 - Software version: `1.3.3` and/or `1.4.0-rc2`
 - Software source: Compiled using source from PowerDNS github.

### Steps to reproduce
1. Include the following in your configuration to attempt to set the dnstap Extra field to include the query length when logging queries:
```
function addDnstapExtra(dq, tap)
    tap:setExtra("length: " .. dq:len())
end

rl = newFrameStreamUnixLogger("/var/run/dnsdist/dnstap.sock")
addAction(AllRule(), DnstapLogAction("testing", rl, addDnstapExtra))
```
2. Query the address/port you have dnsdist listening on.
3. Observe no response is sent, and the query times out, with nothing being logged.

### Expected behaviour
Query is answered normally, and a dnstap message is passed to the frame stream unix logger containing the length of the query in the Extra field.

### Actual behaviour
Query is not answered, and no dnstap message is sent. No error log message is written to dnsdist's daemon log either.

**Comment by rgacogne** [comment]
Note that `len` is not a method of the `DNSQuestion` object, but a member, so your example should be:

```
function addDnstapExtra(dq, tap)
    tap:setExtra("length: " .. dq.len)
end

rl = newFrameStreamUnixLogger("/var/run/dnsdist/dnstap.sock")
addAction(AllRule(), DnstapLogAction("testing", rl, addDnstapExtra))
```

Which seems to be working for me. By the way, running your initial example with `-v` does result in the following message on master:

> [string "chunk"]:2: attempt to call method 'len' (a number value)

**Comment by dmccombs** [comment]
My mistake, you're correct, `dq.len` works fine. It seems like it's something specific to `dq:getTrailingData()`, then, which is a little more complicated to test. I'll open a new bug with steps to test and show that returning empty data in the `alterFunction`, but not elsewhere.

**Comment by dmccombs** [comment]
Actually, the `dq:getTrailingData()` problem just seems to be encoding and how I was printing it out. Sorry for the false alarm!
