### ISSUE TITLE
Using text field instead of VARCHAR for content

### ISSUE THREAD

**Issue by xaoseric** [PowerDNS/pdns#8310]
In the documentation, for mysql, it says to use a VARCHAR with a length of 64000, would it work with a text field and utf8mb collation tables? or would it not work?

**Comment by pieterlexis** [comment]
I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).
