### ISSUE TITLE
slave-cycle-interval does not work as expected

### ISSUE THREAD

**Issue by Cicco0** [PowerDNS/pdns#8323]
- Program: Authoritative, 
- Issue type: Bug report

### Short description
The slave-cycle-interval value should lead to a freshness check at regular intervals, which should also be displayed in the log. For currently unknown reasons, this does not work. I can't rule out the possibility that I made the mistake.

### Environment
 - Operating system: CentOS Linux release 7.6.1810
 - Software version: PowerDNS Authoritative Server 4.1.13
 - Software source: PowerDNS 

### Steps to reproduce
**/etc/pdns/pdns.conf**
```
local-address=10.38.49.22
local-ipv6=

launch=gsqlite3
gsqlite3-database=/var/lib/pdns/sqlite.db
gsqlite3-dnssec=yes

gsqlite3-supermaster-query=select account from supermasters where ip=:ip and nameserver='*'
gsqlite3-supermaster-name-to-ips=select ip,account from supermasters where nameserver='*' and account=:account

# set port for powerdns
local-port=5300

setgid=pdns
setuid=pdns

slave=yes

slave-cycle-interval=60
```

### Expected behaviour
The following entry should be found in the log every slave-cycle-interval.
```No new unfresh slave domains, 0 queued for AXFR already, 0 in progress```

### Actual behaviour
Apparently the check is not being performed. The log file only shows the following:
```
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Received NOTIFY for example\.com from 10.38.49.10 for which we are not authoritative
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Created new slave zone 'example\.com' from supermaster 10.38.49.10
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: 1 slave domain needs checking, 0 queued for AXFR
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Received serial number updates for 1 zone, had 0 timeouts
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Domain 'example\.com' is stale, master serial 1, our serial 0
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Initiating transfer of 'example\.com' from remote '10.38.49.10'
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Starting AXFR of 'example\.com' from remote 10.38.49.10:53
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: AXFR started for 'example\.com'
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: AXFR of 'example\.com' from remote 10.38.49.10:53 done
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: Backend transaction started for 'example\.com' storage
Sep 19 17:19:15 dns-auth02.lab.lan pdns_server[3769]: AXFR done for 'example\.com', zone committed with serial number 1
```

**Comment by Habbie** [comment]
Can you please check the logs a few minutes -after- you added your domain?

**Comment by mind04** [comment]
The check for unfresh domains is performed every slave-check-interval. The message will show up every soa refresh interval. (when there is an actual 'unfresh' domain)

**Comment by Habbie** [comment]
Thanks @mind04, then it looks like there's nothing wrong here.

**Comment by Cicco0** [comment]
Right, I completely overlooked that in this case. Since the refresh is 86400, it takes 24 hours.

I assumed that the slave checks every 60 seconds whether a zone is out of sync and then initiates another transfer.
