### ISSUE TITLE
PowerDNS fails to start, Unable to open /etc/powerdns/pdns.conf

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#8333]
- Program: pdns-backend-mysql/unknown,now 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic amd64  
pdns-server/unknown,now 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic amd64
 - Issue type: Bug report

### Short description
After updating to above version powerdns fails to start
### Environment

 - Operating system: ubuntu 18.04
 - Software version: master
 - Software source: PowerDNS repository

### Steps to reproduce
Upgrade pdns+backend-mysql Master version: 4.2.0~rc2+master.709.g9de6bc5ac-1pdns.bionic 
### Expected behaviour
Continued using working running config

### Actual behaviour
-- Unit pdns.service has begun starting up.
Sep 22 19:06:19 auth1 pdns_server[18159]: Sep 22 19:06:19 Unable to open /etc/powerdns/pdns.conf
Sep 22 19:06:19 auth1 pdns_server[18159]: Unable to launch, no backends configured for querying
Sep 22 19:06:19 auth1 systemd[1]: pdns.service: Main process exited, code=exited, status=99/n/a
Sep 22 19:06:19 auth1 systemd[1]: pdns.service: Failed with result 'exit-code'.
Sep 22 19:06:19 auth1 systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
### Other information

/etc/powerdns/pdns.conf
```lua
include-dir=/etc/powerdns/pdns.d
setgid=pdns
setuid=pdn
```

/etc/powerdns/pdns.d/pdns.conf
```lua
allow-axfr-ips=127.0.0.0/8,::1
allow-dnsupdate-from=127.0.0.0/8,::1
allow-notify-from=0.0.0.0/0,::/0
allow-unsigned-notify=yes
allow-unsigned-supermaster=yes
also-notify=[]
any-to-tcp=yes
api-key=
api=yes
axfr-lower-serial=yes
carbon-instance=auth
carbon-interval=30
carbon-namespace=pdns
carbon-ourname=auth1
carbon-server=37.252.122.50
config-name=auth1.fi.matrix.rocks
daemon=yes
default-ksk-algorithm=ECDSAP384SHA384
default-ksk-size=0
default-soa-mail=
default-soa-name=ns0.dns.matrix.rocks
default-ttl=3600
default-zsk-algorithm=ECDSAP384SHA384
default-zsk-size=0
disable-axfr=no
disable-syslog=no
distributor-threads=1
dname-processing=no
dnsupdate=yes
domain-metadata-cache-ttl=60
edns-subnet-processing=yes
expand-alias=yes
forward-dnsupdate=yes
forward-notify=[]
launch=gmysql
local-address-nonexist-fail=yes
local-address=127.0.0.1,
local-ipv6-nonexist-fail=yes
local-ipv6=
local-port=53
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
loglevel=4
master=yes
prevent-self-notification=yes
query-local-address6=::
query-local-address=0.0.0.0
resolver=
reuseport=no
send-signed-notify=yes
server-id=
setgid=pdns
setuid=pdns
slave-renotify=yes
slave=yes
soa-expire-default=604800
soa-minimum-ttl=60
soa-refresh-default=10800
soa-retry-default=3600
tcp-control-port=53000
tcp-control-range=127.0.0.0/8,
tcp-control-secret=
tcp-fast-open=1
version-string=anonymous
webserver-address=0.0.0.0
webserver-allow-from=
webserver-port=8081
webserver=yes
write-pid=yes
xfr-max-received-mbytes=0
```

**Comment by rgacogne** [comment]
Likely related to #7956, what are the permissions on /etc/powerdns/pdns.conf? Can you make it readable by the `pdns` user if it's not already the case?

**Comment by spirillen** [comment]
Hi @rgacogne 

```
ll /etc/powerdns/pdns.conf
-rw------- 1 root root 17245 Sep 22 18:43 /etc/powerdns/pdns.conf
```

just for fast test:

```shell
chmod 666 /etc/powerdns/pdns.conf
```

Startup result=
```
#systemctl restart pdns
Job for pdns.service failed because the control process exited with error code.
See "systemctl status pdns.service" and "journalctl -xe" for details.
#systemctl start pdns
Job for pdns.service failed because the control process exited with error code.
See "systemctl status pdns.service" and "journalctl -xe" for details.
```

**Comment by spirillen** [comment]
PS: found current workaround... set all conf files to `chmod 666`

So you could be write that this is related to the abofe ref...

**Comment by rgacogne** [comment]
Since the merge of that PR all configuration files need to be readable by the `pdns` (or equivalent) user indeed.

**Comment by pieterlexis** [comment]
#8329 has some words on this. I think the postinstall script should always chown if the current ownership is root:root

**Comment by mnordhoff** [comment]
And also `chmod` -- new installations set the default `pdns.conf` permissions to `660`, but older ones will be using `600`.

**Comment by AysadKozanoglu** [comment]
**notice**: if you dont use named (bind) as backend than do following

check if the config file for named (bind) exists on 
ls  /etc/powerdns/pdns.d/bind.conf

if the config file exits than please delete the config file for named (bind) 

<pre>
rm  /etc/powerdns/pdns.d/bind.conf

systemctl stop  pdns.service
systemctl start pdns.service
systemctl sta

tus pdns.service
</pre>

**Comment by mitar** [comment]
My issue was that config file inside `pdns.d` was not named `*.conf` so it was not being picked up by PowerDNS.

**Comment by information-security** [comment]
As others noted, file permissions could be the main cause. For me, following commands fixed the issue:

```shell
chown -R root:pdns /etc/pdns 
chmod 750 /etc/pdns
 chmod 640 /etc/pdns/*.conf
```

**Comment by forgondolin** [comment]
In my case, on pdns 4.7, it starts, but, for some reason it keeps pointing to a wrong config file.

**Comment by spirillen** [comment]
@forgondolin in that case you should open up a new issue as this one is solved, also have you tryed to ask the good peoples on [IRC](https://www.powerdns.com/opensource.html) for help debugging your issue? there are always plenty of help to get.
