### ISSUE TITLE
pdns_recursor cannot bind IPv6 link local address

### ISSUE THREAD

**Issue by iddq** [PowerDNS/pdns#8335]
- Program: Recursor
 - Issue type: Bug report

pdns_recursor cannot bind IPv6 link local address

local-address=fe80::48d4:78ff:fec0:746c

Sep 23 10:09:38 Exception: Resolver binding to server socket on port 53 for fe80::48d4:78ff:fec0:746c: Invalid argument

Sep 23 10:10:16 PowerDNS Recursor 4.1.9 (C) 2001-2018 PowerDNS.COM BV
Sep 23 10:10:16 Using 64-bits mode. Built using gcc 5.4.0 20160609 on Jan 21 2019 09:30:34 by root@d69aa17e1917.
Sep 23 10:10:16 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep 23 10:10:16 Features: sodium openssl lua
Sep 23 10:10:16 Configured with: " '--host=' '--build=' '--prefix=/usr' '--sysconfdir=/etc/powerdns' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--libdir=${prefix}/lib/' '--libexecdir=${prefix}/lib' '--with-luajit' '--with-protobuf=yes' '--with-net-snmp' '--enable-systemd' '--with-systemd=/lib/systemd/system' '--enable-libsodium' 'build_alias=' 'host_alias=' 'CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security'"

**Comment by Habbie** [comment]
> Sep 23 10:09:38 Exception: Resolver binding to server socket on port 53 for fe80::48d4:78ff:fec0:746c: Invalid argument

The error message is correct - that is not a valid address. It is lacking a scope. Can you try with a scope, like `%eth0`?

**Comment by Habbie** [comment]
I tested this myself, it works:
```
./pdns_recursor --local-port=5300  --socket-dir=. --local-address=fe80::3ee1:a1ff:fe4c:dcac
...
...
Sep 23 10:52:23 Listening for UDP queries on [fe80::3ee1:a1ff:fe4c:dcac%enx3ce1a14cdcac]:5300
```

**Comment by iddq** [comment]
Yes, you are right. Thanks for the help.
