### ISSUE TITLE
Issue with "zz" abbreviation for IPv6 RPZ triggers

### ISSUE THREAD

**Issue by simon-spamhaus** [PowerDNS/pdns#8338]
- Program: PowerDNS
 - Issue type: Bug report

One of our engineers has spent some time tracking down an issue with PowerDNS, RPZ and IPv6 triggers: 'My semi-educated guess is that PowerDNS has a problem parsing IPv6
triggers when the beginning octets are abbreviated with "zz".'

To replicate, fire up PowerDNS and load a single rpz zone:

```
$TTL 300

@              IN SOA  need.to.know.only.  hostmaster.spamhaus.org. (
                       1000000000 ; Serial number
                       60         ; Refresh every 1 minutes
                       60         ; Retry every minute
                       432000     ; Expire in 5 days
                       60 )       ; negative caching ttl 1 minute
               IN NS   LOCALHOST.

21.0.248.44.5.rpz-ip         IN CNAME .
64.0.0.0.0.0.1.0.0.rpz-ip    IN CNAME .
64.zz.2.0.0.rpz-ip        IN CNAME .
dbltest.com            IN CNAME .
*.dbltest.com            IN CNAME .
```

Using this zone, powerdns works.

Add in one additional record:

```
80.0.0.0.1.zz.rpz-ip        IN CNAME .
```

PowerDNS will not be happy.

Remove that one record. Restart. PowerDNS now runs.

To test assumption that PowerDNS has a problem parsing IPv6 triggers when the beginning octets are abbreviated with "zz", edit that single record and remove the shortener to give:

```
80.0.0.0.1.0.0.0.0.rpz-ip    IN CNAME .
```

Happy PowerDNS.

In theory, the trigger `80.0.0.0.1.zz.rpz-ip` is identical to `80.0.0.0.1.0.0.0.0.rpz-ip`
"under the hood". The only difference is that the `zz` abbreviation, which equates to `::` in the address, caused powerdns to die when that entry was loaded.

Since other ipv6 triggers including the zz abbreviation worked, the anomaly here was that the zz was at the beginning of the address.

**Comment by omoerbeek** [comment]
Please try the fix in the PR I submitted a few minutes ago.

**Comment by deteque** [comment]
Hi Omoerbeek,

I pulled your code using "git clone https://github.com/omoerbeek/pdns.git" and compiled it and ran it in a docker image.  We're still seeing the same error:
 
Sep 24 09:03:29 Asked to run with pdns-distributes-queries set but no distributor threads, raising to 1
Sep 24 09:03:29 PowerDNS Recursor 0.0.17676.0.master.g3d6fb5df5f (C) 2001-2019 PowerDNS.COM BV
Sep 24 09:03:29 Using 64-bits mode. Built using gcc 8.3.0 on Sep 24 2019 09:00:01 by root@6116b46a85e9.
Sep 24 09:03:29 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep 24 09:03:29 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Sep 24 09:03:29 Enabling IPv6 transport for outgoing queries
Sep 24 09:03:29 Loading RPZ from file '/etc/powerdns/bogons.ip.dtq'
Sep 24 09:03:29 Unable to load Lua script from '/etc/powerdns/deteque-rpz.lua': Issue parsing '80.0.0.0.1.zz.rpz-ip' '.' at on line 16 of file '/etc/powerdns/bogons.ip.dtq': Unable to convert '1:0:0:0' to a netmask
Sep 24 09:03:29 STL Exception: Exception thrown by a callback function called by Lua

**Comment by Habbie** [comment]
> I pulled your code using "git clone https://github.com/omoerbeek/pdns.git" and compiled it and ran it in a docker image. We're still seeing the same error:

Did you checkout the `rec-rpz-load-zz` branch?

**Comment by deteque** [comment]
Hi Habbie,

git clone -b rec-rpz-load-zz https://github.com/omoerbeek/pdns.git
 
/usr/sbin/pdns_recursor --version:
PowerDNS Recursor 0.0.17677.0.recrpzloadzz.g301148e6d7 (C) 2001-2019 PowerDNS.COM BV

Program Output:

Sep 24 21:58:41 Loading RPZ from file '/etc/powerdns/bogons.ip.dtq'
Sep 24 21:58:41 Unable to load Lua script from '/etc/powerdns/deteque-rpz.lua': Issue parsing '80.0.0.0.1.zz.rpz-ip' '.' at on line 16 of file '/etc/powerdns/bogons.ip.dtq': Unable to convert '1:0:0:0' to a netmask

**Comment by phonedph1** [comment]
FWIW that branch and the sample reproducer fixes it for me:

```
Sep 25 03:50:07 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Sep 25 03:50:07 Loading RPZ from file '/rpz'
Sep 25 03:50:07 Done loading RPZ from file '/rpz'
Sep 25 03:50:07 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
```

reverting the top commit and building - fails as expected:

```
Sep 25 03:55:56 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Sep 25 03:55:56 Loading RPZ from file '/rpz'
Sep 25 03:55:56 Unable to load Lua script from '/rpz.lua': Issue parsing '80.0.0.0.1.zz.rpz-ip' '.' at on line 16 of file '/rpz': Unable to convert '1:0:0:0' to a netmask
Sep 25 03:55:56 STL Exception: Exception thrown by a callback function called by Lua
```

**Comment by omoerbeek** [comment]
> Hi Habbie,
> 
> git clone -b rec-rpz-load-zz https://github.com/omoerbeek/pdns.git
> 
> /usr/sbin/pdns_recursor --version:
> PowerDNS Recursor 0.0.17677.0.recrpzloadzz.g301148e6d7 (C) 2001-2019 PowerDNS.COM BV
> 
> Program Output:
> 
> Sep 24 21:58:41 Loading RPZ from file '/etc/powerdns/bogons.ip.dtq'
> Sep 24 21:58:41 Unable to load Lua script from '/etc/powerdns/deteque-rpz.lua': Issue parsing '80.0.0.0.1.zz.rpz-ip' '.' at on line 16 of file '/etc/powerdns/bogons.ip.dtq': Unable to convert '1:0:0:0' to a netmask

1) Please make double sure you are starting the correct executable, not only for showing the version number but also for the actual test run.
2) Take your testfile, zip it and attach, so that we have an exact copy.

**Comment by deteque** [comment]
Testing was done in a docker image.  The Dockerfile and configs used for the testing are attached.

[powerdns-pr.zip](https://github.com/PowerDNS/pdns/files/3650828/powerdns-pr.zip)

**Comment by franklouwers** [comment]
Hi Deteque,

I cannot reproduce your issue with the Zipfile you provided (note that there is a typo on the CMD line in your Dockerfile that will even prevent pdns from starting).

Could you show us your exact Dockerfile as you tested it, and can you confirm that you built it with the --no-cache option, to guarantee a "fresh" git clone?

Here's my output:

```
Step 13/13 : CMD ["/usr/sbin/pdns_recursor","--daemon=no","--socket-dir=/etc/powerdns" ]
 ---> Running in 7db88f5ddbaf
Removing intermediate container 7db88f5ddbaf
 ---> f4c1f4a2911c
Successfully built f4c1f4a2911c
Successfully tagged pdns_8338:latest
~/D/powerdns-pr ❯❯❯ docker container run -it pdns_8338
Sep 25 08:13:21 Unable to open /etc/powerdns/recursor.conf
Sep 25 08:13:21 Unable to parse configuration file '/etc/powerdns/recursor.conf'
Sep 25 08:13:21 Asked to run with pdns-distributes-queries set but no distributor threads, raising to 1
Sep 25 08:13:21 PowerDNS Recursor 0.0.17677.0.recrpzloadzz.g301148e6d7 (C) 2001-2019 PowerDNS.COM BV
Sep 25 08:13:21 Using 64-bits mode. Built using gcc 8.3.0 on Sep 25 2019 08:06:47 by root@cd1a20f365b1.
Sep 25 08:13:21 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep 25 08:13:21 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Sep 25 08:13:21 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
Sep 25 08:13:21 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
Sep 25 08:13:21 Will not send queries to: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
Sep 25 08:13:21 PowerDNS Recursor itself will distribute queries over threads
Sep 25 08:13:21 Inserting rfc 1918 private space zones
Sep 25 08:13:21 Listening for UDP queries on 127.0.0.1:53
Sep 25 08:13:21 Enabled TCP data-ready filter for (slight) DoS protection
Sep 25 08:13:21 Listening for TCP queries on 127.0.0.1:53
Sep 25 08:13:21 Launching 1 distributor threads
Sep 25 08:13:21 Launching 2 worker threads
Sep 25 08:13:21 Done priming cache with root hints
Sep 25 08:13:21 Done priming cache with root hints
Sep 25 08:13:21 Done priming cache with root hints
Sep 25 08:13:21 Enabled 'epoll' multiplexer
Sep 25 08:13:21 Done priming cache with root hints
Sep 25 08:13:22 Not validating response for security status update, this is a non-release version
```

**Comment by franklouwers** [comment]
Hmm, it seems you're not even loading the config file in your Dockerfile.

**Comment by franklouwers** [comment]
With the modified Dockerfile and your supplied config files properly loaded, I cannot reproduce the bug:

```
~/D/powerdns-pr ❯❯❯ docker container run -it pdns_8338
Sep 25 08:44:46 Asked to run with pdns-distributes-queries set but no distributor threads, raising to 1
Sep 25 08:44:46 PowerDNS Recursor 0.0.17677.0.recrpzloadzz.g301148e6d7 (C) 2001-2019 PowerDNS.COM BV
Sep 25 08:44:46 Using 64-bits mode. Built using gcc 8.3.0 on Sep 25 2019 08:34:43 by root@7c79b1735f3f.
Sep 25 08:44:46 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep 25 08:44:46 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
Sep 25 08:44:46 Enabling IPv6 transport for outgoing queries
Sep 25 08:44:46 Loading RPZ from file '/etc/powerdns/bogons.ip.dtq'
Sep 25 08:44:46 Done loading RPZ from file '/etc/powerdns/bogons.ip.dtq'
Sep 25 08:44:46 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10
Sep 25 08:44:46 Will not send queries to: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
Sep 25 08:44:46 PowerDNS Recursor itself will distribute queries over threads
Sep 25 08:44:46 Inserting rfc 1918 private space zones
Sep 25 08:44:46 Listening for UDP queries on 127.0.0.1:53
Sep 25 08:44:46 Enabled TCP data-ready filter for (slight) DoS protection
Sep 25 08:44:46 Listening for TCP queries on 127.0.0.1:53
Sep 25 08:44:46 STL Exception: Error: Unable to parse group ID pdns
```

*Note* that it errors out because you specify group pdns but that group doesn't exist, but it does load the RPZ file. When using the official 4.2 repo packages, it fails to load the RPZ file.

**Comment by deteque** [comment]
In our test platform we had a bind mounted directory that contained the config files.  The started script included the -v option.  I modified the Dockerfile to copy the files into the image's /etc/powerdns directory and built with --no-cache (which I had not done initially).  I was able to get the rpz zone file to load successfully!
