### ISSUE TITLE
duplicate RRs after API updates

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#8374]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When RRs are added/replaced via API, then there are overlapping requests for the same zone (ie slow pdns/backend), we often see duplicate RRs.

### Environment
 - Operating system: Ubuntu 14.04
 - Software version: 4.1.5 (changlog does not indicate that a newer version has fixed this)
 - Software source: compiled myself

### Steps to reproduce
Our web frontend sent 2 identical PATCH requests for the same zone, with changetype=REPLACE for each label+type. Here are the logs of our web frontend:
```
Oct  2 09:50:34 t6zyt3uf: Request PATCH zones/example.com. {"rrsets":[{"comments":[],"name":"example.com.","records":[{"content":"\"v=spf1 mx ip1:130.2.69.48 -all\"","disabled":false}],"ttl":3600,"type":"TXT","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"50 mail.example.com.","disabled":false},{"content":"10 mail10.example.com.","disabled":false}],"ttl":3600,"type":"MX","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"sec1.rcode0.net. rcodezero-soa.ipcom.at. 2019100201 10800 3600 604800 3600","disabled":false}],"ttl":3600,"type":"SOA","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"sec2.rcode0.net.","disabled":false},{"content":"sec1.rcode0.net.","disabled":false}],"ttl":3600,"type":"NS","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"1.2.3.4","disabled":false}],"ttl":3600,"type":"A","changetype":"REPLACE"}]}
Oct  2 09:50:35 04guqnzn: Request PATCH zones/example.com. {"rrsets":[{"comments":[],"name":"example.com.","records":[{"content":"\"v=spf1 mx ip1:130.2.69.48 -all\"","disabled":false}],"ttl":3600,"type":"TXT","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"50 mail.example.com.","disabled":false},{"content":"10 mail10.example.com.","disabled":false}],"ttl":3600,"type":"MX","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"sec1.rcode0.net. rcodezero-soa.ipcom.at. 2019100201 10800 3600 604800 3600","disabled":false}],"ttl":3600,"type":"SOA","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"sec2.rcode0.net.","disabled":false},{"content":"sec1.rcode0.net.","disabled":false}],"ttl":3600,"type":"NS","changetype":"REPLACE"},{"comments":[],"name":"example.com.","records":[{"content":"1.2.3.4","disabled":false}],"ttl":3600,"type":"A","changetype":"REPLACE"}]}
Oct  2 09:50:41 t6zyt3uf: Response 204
Oct  2 09:50:44 04guqnzn: Response 204

```
### Expected behaviour
The zone should like like as defined in the body of the PATCH request

### Actual behaviour
The TXT spf record was inserted into the database twice.

### Other information
We suspect that PDNS iterate over the PATCH body and performs a "DELETE + INSERT" for each label+type. We suspect that both PATCH requests are processed in parallel and the "DELETE+INSERT" for the TXT happend almost at the same time, ie: DELETE1->DELETE2->INSERT1->INSERT2". This way it can happen that the resource records are added twice.

Maybe there should be some kind of serialization for updates on the same zone, or at least on the same label+type level.

We also experience duplicate SOA records when there are concurrent PATCH requests on the same zone. We suspect this happens through SOA-EDIT-API=1 which triggers a concurrent the SELECT+DELETE+INSERT for the SOA.

**Comment by Habbie** [comment]
4.2.0-rc2 has:

> auth API, pdnsutil: improve backend transaction correctness
>
> References: pull request 7891

Which should fix this. Can you test 4.2.0 please?

**Comment by pieterlexis** [comment]
related: #7128

**Comment by Habbie** [comment]
> related: #7128

Duplicate, even!

**Comment by klaus3000** [comment]
Oh, I missed this other bug report. Unfortunately I will take some time until we switch to 4.2.0 on our production system (we do not have the problem on our test systems, as they are not that heavy loaded). Feel free to close the issue, I can reopen it if it happens with 4.2 again. thanks

**Comment by Habbie** [comment]
Thanks Klaus!
