### ISSUE TITLE
Running multiple virtual instances

### ISSUE THREAD

**Issue by hvanoch** [PowerDNS/pdns#8386]
Hi, 

I can start both instances separately, but not together. When I do that I get the error that the address (53) is already in use.

I hoped that both instances could still listen on port 53. 
With the config I hoped I could specify the webserver server config and thus api keys.  So every customer has its own api key.

Do I need to listen to a different dns port too?

Then I probably also need some kind of dns proxy/ load balancer that listen on port 53 which forwards the requests to the right local dns port?

Thanks in advance.

**Comment by Habbie** [comment]
Hello,

(1) we have an issue template for a reason; please do not blindly discard it
(2) this looks like a support question. Please find us on IRC or our mailing lists via https://www.powerdns.com/opensource.html, thanks!
