### ISSUE TITLE
Documentation: Please clarify the difference between DelayAction and DelayResponseAction

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#8392]
- Program: dnsdist
 - Issue type: Bug report (documentation only)

### Short description
The description of [DelayAction](https://dnsdist.org/rules-actions.html?highlight=responseaction#DelayAction) and [DelayResponseAction](https://dnsdist.org/rules-actions.html?highlight=responseaction#DelayResponseAction) in the manual is exactly identically. Can you please document the difference in the manual? I assume DelayAction delays the query packets right before forwarding them to the backend and DelayResponseAction delays the answer packet to the client. But I'm not sure.

**Comment by rgacogne** [comment]
The descriptions are identical because they do the exact same thing :) The only difference is that DelayAction is a DNSAction so it can be used on queries, and DelayResponseAction is a DNSResponsAction so it can be used on responses. They both delay the answer packet sent by dnsdist to the client.
