### ISSUE TITLE
Error while parsing SOA data for slave zone

### ISSUE THREAD

**Issue by glardone** [PowerDNS/pdns#8397]
- Program: Authoritative
- Issue type: Bug report

### Short description
I configured a domain as a slave (on PDNS 4.2) of a master (PDNS 4.1), but I get this error:
`pdns_server[1541]: Error while parsing SOA data for slave zone 'testdomain.com', skipping`

### Environment
 - Operating system: Ubuntu 18.04.3 LTS
 - Software version: 4.2
 - Software source: PowerDNS repository (repo.powerdns.com/ubuntu bionic-auth-42)

With other slaves (PDNS 4.1) I don't have this problem.

**Comment by glardone** [comment]
Hello,
the command `pdnsutil check-zone testdomain.com` get this error:
[Error] Unable to get domain information for zone 'testdomain.com'

The SOA Record in the database is:
`ns1.consul.to postmaster.consul.to 2019100202 10800 3600 604800 3600`

**Comment by Habbie** [comment]
Can you show full database contents for the domain on the slave? domains table, records table at least.

**Comment by glardone** [comment]
I found the issue: missing "disabled" field in the "records" table.
Sorry!
