### ISSUE TITLE
Please add Centos 8 repo

### ISSUE THREAD

**Issue by ruben-herold** [PowerDNS/pdns#8399]
hi,

it would be nice if you could create packages and a repo for centos 8 release.

**Comment by rodehoed** [comment]
Yes please. +1 for me 🤩

**Comment by Habbie** [comment]
#8400 (merged) is 50% of this. Repo coming soon!

**Comment by ruben-herold** [comment]
Thx for the fast feedback. As discussed on irc I run in the moment the epel packages, but dnsdist is not in epel.

**Comment by pieterlexis** [comment]
I've added centos-8 as a build target, so master packages for CentOS 8 will be deployed automatically after a merge on master. After a the backport of #8400 we can also publish release packages.
