### ISSUE TITLE
auth: Support proxy protocol for incoming queries

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8403]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Basically support the other side of #8401, to be able to provide the original source and destination addresses and ports, as well as any TLVs data, to the `Lua` hooks. We might also want to be able to rewrite the source and destination address passed to the rest of the code, including backends.

We should be careful to only accept these from whitelisted hosts.

**Comment by discostur** [comment]
Would be really cool to have that implemented 👍

**Comment by unixfox** [comment]
While waiting for PowerDNS to have a native PROXY Protocol support I use MMProxy for preserving the original IP which is needed when doing AXFR transfers.

**Comment by discostur** [comment]
Any news on this? I saw that dnsdist already supports proxy_protocol for outgoing connections. Would be really nice to have support in pdns, too.

**Comment by Habbie** [comment]
> Any news on this? I saw that dnsdist already supports proxy_protocol for outgoing connections. Would be really nice to have support in pdns, too.

I really hope to do it for 4.5 - so within six months. Hopefully on master a bit before that!

**Comment by discostur** [comment]
@Habbie i can see 4.5 is on track but this ticket is not yet selected for the release ... do you see any hope for this to get ready for 4.5?

Working with dnsdist in front of auth and using proxy_protocol would be a game changer ;)

**Comment by Habbie** [comment]
Sorry, no work done yet. If we're lucky, somebody delivers it before auth 4.5.0 beta1, but I don't know if anybody will.
