### ISSUE TITLE
add content to existing record with api

### ISSUE THREAD

**Issue by sfoutrel** [PowerDNS/pdns#8423]
PDNS authoritative 4.0.3
Hello,
I am using the api to do automation and did not find a way to add content to an existing record
like adding a NS server in an existing zone or adding another ip to a name.
with PATCH I can only do REPLACE or DELETE.

Did I miss something  ??

Thanks for your help.

**Comment by Habbie** [comment]
Hello,

1. we have a template for issue reporting, please use it next time.
2. this is a support question. For free and open support, please find our IRC channel or mailing list via https://www.powerdns.com/opensource.html
