### ISSUE TITLE
Error sending reply with sendto

### ISSUE THREAD

**Issue by pavel-odintsov** [PowerDNS/pdns#844]
Hello,

We use powerdnd from offical powerdns.com repo.

pdns_server --version
Version: 3.2, compiled on Jan 17 2013, 09:33:38 with gcc version 4.4.5

We have alot of record like this:
May 31 13:43:44 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument
May 31 13:43:48 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument
May 31 13:43:48 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument
May 31 13:43:53 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument
May 31 13:44:00 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument
May 31 13:44:06 ns4 pdns[25236]: Error sending reply with sendto (socket=4): Invalid argument

How to fix it?

**Comment by nbari** [comment]
just in case I had this issue in a FreeBSD jail, the solution was to specify jail IP, something like:

Only ipv4 no ipv6:

    local-address=X.X.X.X
    local-ipv6=

Host with ipv4 and ipv6:

     local-address=X.X.X.X
     local-ipv6=2001::1

**Comment by Habbie** [comment]
@nbari as a general remark, note that we tend to forget about comments on closed tickets. That said, were your failures related to port zero as well?

**Comment by nbari** [comment]
Hi @Habbie I was getting the error `Error sending reply with sendto` but after defining the addresses of the jail error was fixed

**Comment by Habbie** [comment]
@nbari hmm, that sounds like a different actual bug. Please feel free to file a new ticket with all relevant details!
