### ISSUE TITLE
auth: document how to access qname and qtype from LUA records

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#8443]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

The documentation should describe how to access the qname and the qtype when dealing wih lua records. I was doing a lua function on a wildcard and had trouble finding out how to get the qname.

### Environment

 - Operating system: *
 - Software version: master
 - Software source: 

### Steps to reproduce

1. Read the docs
2. Scratch head
3. Ask a colleague

### Expected behaviour

No head scratching and no need to ask a colleague.

**Comment by smck83** [comment]
Are you able to provide an example of how you were able to access qname and qtype from a lua record?

**Comment by omoerbeek** [comment]
Click the link of the Open PR above, and then check the "Files Canged" tab.
