### ISSUE TITLE
dnsdist: SpoofAction TTL

### ISSUE THREAD

**Issue by dimsua** [PowerDNS/pdns#8446]
Hello
In dnsdist when we use SpoofAction always return TTL 60, and we cannot increase them with addResponseAction and as i correctly understand this is hardcoded value in dnsdist-lua-actions.cc (0, 0, 0, 60,   // TTL)
Is it possible to implement in feature release some options for customs ttls?

**Comment by Habbie** [comment]
Hello,

1. we have an issue template. You destroyed it. Please do not do that.
2. GitHub tickets are not for support requests. Please find us on IRC or our mailing lists via https://www.powerdns.com/opensource.html
