### ISSUE TITLE
Possible memory leak in authoritative server 4.1/4.2

### ISSUE THREAD

**Issue by brenc** [PowerDNS/pdns#8449]
- Program: Authoritative
 - Issue type: Bug report

### Short description

We've been using PowerDNS for several years. Recently we made a few changes and have started to see what appears to be a memory leak in pdns_server.

Here is the memory graph for one of the DNS instances:

![dns-memory](https://user-images.githubusercontent.com/12928053/67316074-6f0b5f00-f4cd-11e9-8eab-b1a04830f308.png)

`top` output:

![image](https://user-images.githubusercontent.com/12928053/67318148-b6471f00-f4d0-11e9-91e8-b3f482886965.png)

I have to restart `pdns_server` every two weeks or so.

### Environment

 - Operating system: Debian 9 (Stretch) x86_64
 - Software version: dnsdist 1.3.3, pdns 4.2.0 (also seen in 4.1.13)
 - Software source: PowerDNS repository

### Steps to reproduce

We used to run pdns_server on the public IP with the recursor listening on localhost to resolve ALIAS records. We never had a problem running pdns_server this way. Our internal name servers still run this way without issue.

Now we run dnsdist on the public IP and both the auth and recursor on localhost. We did this so we could rate limit DNS requests using dnsdist. For some reason this seems to trigger a memory leak in pdns_server.

Our current setup on each server looks like this:

`dnsdist [public IP] -> auth [localhost:54] -> recursor [localhost:53]`

We're using the OpenDBX backend to external MySQL servers (we will be moving to the generic MySQL backend soon).

Just letting the server run for couple weeks reproduces this issue. I've attached all relevant configs.

Let me know if there is anything else I can provide.

[recursor.conf.txt](https://github.com/PowerDNS/pdns/files/3757832/recursor.conf.txt)
[pdns.conf.txt](https://github.com/PowerDNS/pdns/files/3757844/pdns.conf.txt)
[dnsdist.conf.txt](https://github.com/PowerDNS/pdns/files/3757835/dnsdist.conf.txt)

**Comment by Habbie** [comment]
> We're using the OpenDBX backend to external MySQL servers (we will be moving to the generic MySQL backend soon).

It would be extremely useful to know if the leak persists after that move.

**Comment by brenc** [comment]
OK I'll get that swapped out today or tomorrow and report back in a couple weeks.

**Comment by Habbie** [comment]
> OK I'll get that swapped out today or tomorrow and report back in a couple weeks.

It is appreciated, thank you!

**Comment by brenc** [comment]
So it looks like the memory leak is still present:

![image](https://user-images.githubusercontent.com/12928053/67709468-02d8a180-f98c-11e9-81ce-258ff0db11c0.png)

![image](https://user-images.githubusercontent.com/12928053/67709638-55b25900-f98c-11e9-8584-c3fa0e6b87a1.png)

Please let me know what else I can do to help.

**Comment by rgacogne** [comment]
Would you be able to export some metrics to our public metronome (carbon) server at https://metronome1.powerdns.com/?

You would need to set:
```
carbon-server=37.252.122.50
carbon-ourname=<the name that will appear in the drop-down list>
```

**Comment by brenc** [comment]
Sure. You'll see them under `ng-ns1/2` for both dnsdist and auth.

**Comment by rgacogne** [comment]
Thanks, that's very helpful! I'm a bit surprised by the number of entries in the auth's packetcache (57k and counting) while the dnsdist's one only has ~3.6k entries. Note that the auth's one is almost useless since dnsdist's one handle most of the cacheable answers anyway, but that should not matter. Could you try setting `max-packet-cache-entries` to a lower number, like 20k or so, just to see if that helps?
My first thought was that dnsdist adding ECS to incoming queries would be causing a lot of different packet cache entries to be inserted in the auth, but according to your configuration you don't use ECS so that doesn't work.

**Comment by brenc** [comment]
Yeah that is odd. I see it increments at a steady rate too. I have set `max-packet-cache-entries` to 20K.

**Comment by brenc** [comment]
Looks like with that setting the packet cache has leveled out, but memory use continues to rise as it did before:

![image](https://user-images.githubusercontent.com/12928053/68091360-61969300-fe44-11e9-88ff-e839b47fa327.png)

![image](https://user-images.githubusercontent.com/12928053/68091373-84c14280-fe44-11e9-824a-10710724849d.png)

**Comment by rgacogne** [comment]
OK, it's good to have been able to rule the packet cache out of the equation, but it indeed really looks like a leak now :-/ Would you mind posting the updated configuration now that you have switched to the generic MySQL backend? I don't see anything unusual in your configuration so far.

**Comment by brenc** [comment]
Yeah the weird thing is our internal servers use nearly an identical config and they run fine. The only difference is that we frontend the external servers with dnsdist.

Here's the updated pdns config.

[pdns.conf.txt](https://github.com/PowerDNS/pdns/files/3810814/pdns.conf.txt)

**Comment by paddg** [comment]
`distributor-threads=100`
I wonder if that means, up to 100 caches and up to 100 db connections?

**Comment by Habbie** [comment]
Is there any chance this could be #6231 ? Our Debian Stretch packages link against mariadb 10.1.41 which I suspected is affected by that bug.

Can you test with `gmysql-thread-cleanup=yes`?

**Comment by brenc** [comment]
I've added `gmysql-thread-cleanup=yes` that to the config.

Seems bizarre that this is _only_ an issue when dnsdist is sitting in front of the auth server.

**Comment by brenc** [comment]
So far so good! Looks like memory usage is holding steady.

**Comment by Habbie** [comment]
> Seems bizarre that this is _only_ an issue when dnsdist is sitting in front of the auth server.

I do not have an immediate explanation for that.

**Comment by brenc** [comment]
Looks like memory usage is continuing to creep up:

![image](https://user-images.githubusercontent.com/12928053/68814131-9fae6680-063d-11ea-95a3-3a084ea80027.png)

![image](https://user-images.githubusercontent.com/12928053/68814051-637b0600-063d-11ea-9ff6-51655b61ba14.png)

Please let me know what else I can do to help troubleshoot this.

**Comment by brenc** [comment]
You can see here that it's taking longer to use all available memory now that I set `gmysql-thread-cleanup=yes`:

**Comment by brenc** [comment]
You can see here that it's taking longer to use all available memory after I set `gmysql-thread-cleanup=yes` but it looks like the memory leak is still present:

![image](https://user-images.githubusercontent.com/12928053/69178077-7e7ec780-0ace-11ea-884e-be01a59d3b05.png)

**Comment by brenc** [comment]
Here's something else I noticed: it looks like each time there's a spike in TCP questions there's a spike in memory usage:

![image](https://user-images.githubusercontent.com/12928053/69178352-09f85880-0acf-11ea-82c0-eb60562ce254.png)

![image](https://user-images.githubusercontent.com/12928053/69178395-1aa8ce80-0acf-11ea-8592-0b5e9418653e.png)

The only corresponding spike I see in dnsdist is this:

![image](https://user-images.githubusercontent.com/12928053/69179546-52b11100-0ad1-11ea-876d-939206b46d05.png)

I grep'ed the logs for both dnsdist and pdns_server for anything suspicious around the time of the spikes and I did find several denied AXFR requests, but that's it.

**Comment by rgacogne** [comment]
That's quite interesting as having dnsdist in front of the auth will make things very different for the authoritative server since dnsdist will do TCP connection pooling. So it will try to keep an existing outgoing TCP connection to the backend open and reuse it when the next incoming TCP connection arrives. Would you be able to issue a `showTCPStats()` on the dnsdist console? It would also be interesting to see if the issue remains with dnsdist 1.4.0 which has a completely rewritten TCP stack.
By the way, I noticed that your authoritative server configuration has `max-tcp-connections-per-client` which is not a good idea since all TCP connections will appear to come from dnsdist.

**Comment by brenc** [comment]
OK - I upgraded to dnsdist 1.4. I also removed the `max-tcp-connections-per-client` and related settings as those were from pre-dnsdist days. We'll see if this persists. Will let the servers run for a bit before gathering TCP stats.

**Comment by brenc** [comment]
Looks like the memory leak is still there:

![image](https://user-images.githubusercontent.com/12928053/70395428-1ed85580-19c4-11ea-99b4-2445afecc06e.png)

Also, is the public Metronome server down? I haven't been able to connect to it for over a week.

**Comment by cmakaloclifford** [comment]
Version: PowerDNS Authoritative Server 4.2.1
Backend: BIND (files)
OS: Ubuntu 18.04.3 LTS (64-bit)

Issue: We can see memory leak as well, although no database backend, or nothing in front either, just plain vanilla install and BIND files backend. 

I have attached a graph showing our free memory on both servers. As you can see the free memory decreases over time, until service restart. You can see the spikes, it's where we have restarted the service and the machine gets all the free memory back.

![Name Server 1](https://user-images.githubusercontent.com/1741470/73462960-d6fafc80-437c-11ea-9312-804da05267a3.png)

![Name server 2](https://user-images.githubusercontent.com/1741470/73462958-d6fafc80-437c-11ea-996c-e637e31d0503.png)

**Comment by Habbie** [comment]
> Also, is the public Metronome server down? I haven't been able to connect to it for over a week.

Looks up from here, what IP are you sending metrics to, and what URL are you trying to use to look at the graphs?

**Comment by rgacogne** [comment]
> Issue: We can see memory leak as well, although no database backend, or nothing in front either, just plain vanilla install and BIND files backend.

Is this a new installation or an upgrade from a previous version?

> I have attached a graph showing our free memory on both servers. As you can see the free memory decreases over time, until service restart. You can see the spikes, it's where we have restarted the service and the machine gets all the free memory back.

Would you be able to share other metrics? What we see here is indeed the memory usage increasing, it would be nice to know whether it's correlated to the growth of various caches (packet, records, meta-data, keys, rings ...), for example, or if anything weird happened at the same time.

**Comment by brenc** [comment]
> Looks up from here, what IP are you sending metrics to, and what URL are you trying to use to look at the graphs?

`carbon-server=37.252.122.50`

URL: https://metronome1.powerdns.com/

Resolves to: `2a02:2770:8::2635:0:1`

![image](https://user-images.githubusercontent.com/12928053/73484962-ddcb4480-4367-11ea-8615-3923efd7e60a.png)

Worked fine until several weeks ago.

**Comment by mnordhoff** [comment]
What happens if you click OK?

I get that alert sometimes, but everything works anyway.

Looking at the JavaScript, the alert happens if you don't download the 1.5 MB list of servers in 2.5 seconds. But if you still successfully download it, and it just takes a little longer, everything should be fine.

**Comment by cmakaloclifford** [comment]
> > Issue: We can see memory leak as well, although no database backend, or nothing in front either, just plain vanilla install and BIND files backend.
> 
> Is this a new installation or an upgrade from a previous version?
> 
It's a completely new installation, no upgrade from previous version.
 
> > I have attached a graph showing our free memory on both servers. As you can see the free memory decreases over time, until service restart. You can see the spikes, it's where we have restarted the service and the machine gets all the free memory back.
> 
> Would you be able to share other metrics? What we see here is indeed the memory usage increasing, it would be nice to know whether it's correlated to the growth of various caches (packet, records, meta-data, keys, rings ...), for example, or if anything weird happened at the same time.

I have no other metrics at the time unfortunately. But I will get back to you if we can see something strange. The thing is though that it starts to eat up the memory immediately after restart. 

Do you want us to send metrics to you for investigation? If so, let us know how to send it to you.

**Comment by rgacogne** [comment]
> It's a completely new installation, no upgrade from previous version.

OK, thanks, I was wondering whether it was a regression or a new issue, but we'll know once we figure it out :)

> Do you want us to send metrics to you for investigation? If so, let us know how to send it to you.

Would you mind sending metrics to our public metronome server at https://metronome1.powerdns.com/ ? You'd need to set the following settings:
* `carbon-server=37.252.122.50` ;
* `carbon-ourname=` to a short unique name, that does not have to mean anything.

**Comment by brenc** [comment]
> What happens if you click OK?

The dropdown is always empty.

Now I'm not getting the alert popup but the jQuery request to get a list of available servers is failing with a 400 bad request. It does look like it's loading the list in the dropdown, but along with the 400 error I see some goofiness in the dropdown:

![image](https://user-images.githubusercontent.com/12928053/73572142-adea7280-4435-11ea-8beb-60e09f5fef63.png)

I can now see stats again though.

As to the original topic of this ticket, I'm still seeing a memory leak:

![image](https://user-images.githubusercontent.com/12928053/73572379-43860200-4436-11ea-866a-1cf5b882dfb9.png)

But the leak has slowed quite a bit since we made those config changes a while back.

**Comment by cmakaloclifford** [comment]
> > It's a completely new installation, no upgrade from previous version.
> 
> OK, thanks, I was wondering whether it was a regression or a new issue, but we'll know once we figure it out :)
> 
> > Do you want us to send metrics to you for investigation? If so, let us know how to send it to you.
> 
> Would you mind sending metrics to our public metronome server at https://metronome1.powerdns.com/ ? You'd need to set the following settings:
> 
> * `carbon-server=37.252.122.50` ;
> * `carbon-ourname=` to a short unique name, that does not have to mean anything.

Hi! Now you should be able to see metrics from our servers.
They identify themselves as:
"pdns.kalle-1.auth" and "pdns.kalle-2.auth"

I hope this can help you in fixing the memory leak issues.

**Comment by rgacogne** [comment]
After investigating with Valgrind, Leak Sanitizer and Heaptrack, this really looks like memory fragmentation rather than a memory leak. This is probably made worse by the fact that cache entries are often allocated from one thread and freed from a different one, especially with short-lived threads like the TCP or API ones.

The following configuration change has been found to improve the situation in at least one occurrence (with `MALLOC_ARENA_MAX=1`, but `MALLOC_ARENA_MAX=2` might be a better trade-off depending on the type of work load), it would be nice to know if it works for others:

Run `systemctl edit pdns` and, in the editor that will open, insert the following lines:
```
[Service]
Environment="MALLOC_ARENA_MAX=2"
```

Then save and close the editor, run `systemctl daemon-reload` and restart the PDNS
authoritative server with `systemctl restart pdns`.

This will greatly reduce the number of separate memory zones used when allocating memory reducing memory fragmentation. This will however increase the contention between threads when allocating memory, so it might have a noticeable impact on CPU usage, depending on the exact work load.

**Comment by brenc** [comment]
@rgacogne - I put this change in today. So far I'm not seeing any increased CPU usage. I'll report back in a few weeks. Thanks for looking into this.

**Comment by brenc** [comment]
OK - looks like the memory leak is still present:

![image](https://user-images.githubusercontent.com/12928053/80019523-44f72180-849d-11ea-8edf-4b6c0a535ac1.png)

These appears to be correlated with a spike in queries. If you look at the Metronome graphs for pdns.ng-ns3.auth, one week period, you can see the memory allocations happening right around a spike in queries, query cache size, database queries/s, etc.

**Comment by krzkowalczyk** [comment]
I've got the same issue, with memory leak with version 4.2.0. It grows in memory consumption around 1GB per month.

**Comment by rgacogne** [comment]
Any chance you could give 4.3.0 a try? We did a lot of work to remove potential memory issues in there, it would be very interesting to know if the issue persist after that.

**Comment by brenc** [comment]
I upgraded our systems to 4.3.0 today. Will report back in a few weeks.

**Comment by brenc** [comment]
Looks like the memory leak is no longer present in 4.3.0:

![image](https://user-images.githubusercontent.com/12928053/87824547-1938cd00-c83b-11ea-9593-e3d453a82dc5.png)

By now the systems would have been nearly out of memory. I will close the ticket. Thanks!

**Comment by rgacogne** [comment]
Thanks a lot for reporting this issue and testing 4.3.0, that's very much appreciated!
