### ISSUE TITLE
createReverse6() wildcards combine badly with ENTs

### ISSUE THREAD

**Issue by ruben-herold** [PowerDNS/pdns#8478]
- Program: Authoritative
 - Issue type: Bug report

### Short description
createReverse6() seems to fail if another record in the same chunk

### Environment
 - Operating system: Centos8
 - Software version:  4.2.0
 - Software source: EPEL

### Steps to reproduce
Created a zone with the content:

```
@	SOA	Active	3600	ns1.rcs-networks.com. hostmaster.rcs-networks.com. 2019101401 10800 3600 604800 3600	
@	NS	Active	3600	dns.insecure.pw.
@	NS	Active	3600	ns1.rcs-networks.com.
*	LUA	Active	3600	PTR "createReverse6('%33%.ip.rcs-networks.com')"

```

This workes:

```
host 2a0c:a981:1000::4 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer 2a0c-a981-1000--4.ip.rcs-networks.com.
```

If I add:

`1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1	PTR	Active	3600	test.de.`

to the zone I got this:

```
ruben@work:[~] > host 2a0c:a981:1000::1 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer test.de.
ruben@work:[~] > host 2a0c:a981:1000::4 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

Host 4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.8.9.a.c.0.a.2.ip6.arpa not found: 3(NXDOMAIN)
ruben@work:[~] > host 2a0c:a981:2000::4 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer 2a0c-a981-2000--4.ip.rcs-networks.com.
```

After remove the entry I got 

```
ruben@work:[~] > host 2a0c:a981:1000::1 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer 2a0c-a981-1000--1.ip.rcs-networks.com.
ruben@work:[~] > host 2a0c:a981:1000::4 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer 2a0c-a981-1000--4.ip.rcs-networks.com.
ruben@work:[~] > host 2a0c:a981:2000::4 ns1.rcs-networks.com
Using domain server:
Name: ns1.rcs-networks.com
Address: 2a0c:a980:1000:4::10#53
Aliases: 

4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.1.8.9.a.c.0.a.2.ip6.arpa domain name pointer 2a0c-a981-2000--4.ip.rcs-networks.com.
ruben@work:[~] > 

```

**Comment by Habbie** [comment]
I bet this is an ENT issue. Will take a closer look soon.

**Comment by ruben-herold** [comment]
any news on this?

**Comment by Habbie** [comment]
I looked into this now. This is correct behaviour. The existence of that record avoids the wildcard expansion. You're not the first to run into this, and we do not have a good solution for it yet, sorry.

**Comment by Habbie** [comment]
I've updated the title and am reopening this because, while it's not a bug, the question comes up a few times a month and this is a good place for discussing workarounds.

**Comment by Habbie** [comment]
One workaround: a longer LUA record, on the wildcard, that also knows about the exceptions.

**Comment by ruben-herold** [comment]
@Habbie can you give a short example for this?

**Comment by zejar** [comment]
I've also stumbled across this issue. @Habbie could you please explain your workaround?

**Comment by mgielissen** [comment]
The same problem is with wildcard:
*	PTR	Active	3600	hosted-by.rcs-networks.com
It works only when there is no other PTR record.

**Comment by Habbie** [comment]
While working on another problem, I noticed an undocumented feature:

```
"createReverse6('%33%', {['2001::db8']='example.powerdns.com'})"
```

the second, undocumented, parameter to `createReverse6` (and `createReverse`) takes a table containing a collection of exceptions.

I'll add this to the docs soon.

**Comment by Habbie** [comment]
documented in #10463

**Comment by flaf** [comment]
Hi.

I know this issue is closed and I know it's not a bug because PowerDNS just strictly implements the RFC 1034 (the existence of a record can stop the wildcard expansion). But how to solve the problem if, in a big network, we simply want to set a default/dynamic PTR record for absent names in zone? For instance, for the zone 10.in-addr.arpa (ie 10.0.0.0/24). As workaround, we have to set 65536 (256 x 256) wildcard records in my zone, like this:

```
*.0.0.10.in-addr.arpa  3600    IN      LUA     PTR "createReverse('ip-%5%.domain.tld')"
*.1.0.10.in-addr.arpa  3600    IN      LUA     PTR "createReverse('ip-%5%.domain.tld')"
*.2.0.10.in-addr.arpa  3600    IN      LUA     PTR "createReverse('ip-%5%.domain.tld')"
...
*.255.255.10.in-addr.arpa  3600    IN      LUA     PTR "createReverse('ip-%5%.domain.tld')"
```
And for a IPv6 networks...

Indeed, we can set no PTR record in the zone and use the `exception` argument of the function `createReverse` but in a big zone with lot of PTR records, it seems to me a not acceptable workaround too.

Are there another workarounds, more convenient for a big reverse zone?

Thanks for your help.
