### ISSUE TITLE
syslog program name for multiple PDNS instances with systemd

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#8490]
- Program: Authoritative
 - Issue type: Bug report?

### Short description
With initV, I could easily spawn multiple PDNS processes by just create a symlink in init.d, ie:
/etc/init.d/pdns-2 -> /etc/init.d/pdns

This second process would appear in syslog with programname "pdns-2" instead of "pdns".

I just started a second PDNS server on with systemd:
systemctl start pdns@2

Unfortunately both PDNS server show up in syslog as "pdns_server" and hence I can not differentiate the log messages. It would be great to have the second process show up as "pdns_server-2", similar as before.

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: 4.1.13
 - Software source: self compiled

**Comment by klaus3000** [comment]
I have not tested yet, but maybe using `SyslogIdentifier=pdns_server_%i` in the pdns@.service file is sufficient.

**Comment by Habbie** [comment]
Could you test that? :)

**Comment by klaus3000** [comment]
OK :)

**Comment by klaus3000** [comment]
```
[Service]
SyslogIdentifier=pdns_server_%i
```
Works great. Please add it to your systemd service file.

**Comment by Habbie** [comment]
ah - but wouldn't that add a `_` to the main instance?

**Comment by klaus3000** [comment]
I think the main instance does not use "pdns@.service" but just "pdns.service". So the change only affects pdns@ services, not the main instance.

**Comment by zeha** [comment]
pdns@.service is created from pdns.service, so more creative `sed` has to be applied :)

**Comment by klaus3000** [comment]
Oha, then it should as simple as the other adoptions, ie (untested):

in ./pdns/pdns.service.in:
 [Service]
+SyslogIdentifier=pdns_server

and in pdns/Makefile.am:
 pdns@.service: pdns.service
         $(AM_V_GEN)sed -e 's!/pdns_server!& --config-name=%i!' \
           -e 's!Authoritative Server!& %i!' \
+          -e 's!SyslogIdentifier=pdns_server!&_%i!' \
           < $< > $@

**Comment by zeha** [comment]
PR'd in #9187.

**Comment by zeha** [comment]
Small difference: the instance identifier will be `pdns_server-2` - dash instead of underscore.
This appears to be consistent with the sysvinit-script behaviour.
