### ISSUE TITLE
API: unable to unset NSEC3PARAM via API

### ISSUE THREAD

**Issue by ArnoSen** [PowerDNS/pdns#8502]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When I send an empty value for `nsec3param` to `PUT /servers/{server_id}/zones/{zone_id}` , the value of `nsec3param` remains unchanged.

### Environment

 - Operating system: 
 - Software version: 4.1.5
 - Software source: Operating system repository

### Steps to reproduce
<!-- Tell us step-by-step how the issue can be triggered. Please include your configuration files and any (Lua) scripts that are loaded. 
1. Create a secure zone and assign an NSEC3PARAM value
2. Pull zone info using GET /servers/{server_id}/zones/{zone_id}
3. Edit the JSON and set the value for nsecparam to an empty string
4. Send above JSON as payload to `PUT /servers/{server_id}/zones/{zone_id}`

### Expected behaviour
I would expect the value for NSEC3PARAM to be emptied and the secure zone falls back to using NSEC.

### Actual behaviour
The parameter was not changed.

### Other information
I also tried DELETE /servers/{server_id}/zones/{zone_id}/metadata/NSEC3PARAM and PUT DELETE /servers/{server_id}/zones/{zone_id}/metadata/NSEC3PARAM with a payload but neither did work.

**Comment by ArnoSen** [comment]
is there any update on this issue?

**Comment by Habbie** [comment]
Not yet!

Things you can do to make it easier for us to work on this:
- verify that the issue still happens in 4.2.0
- verify that the issue still happens in master
- show a `curl` session that demonstrates the issue

**Comment by Habbie** [comment]
Duplicated in #8651 which has demonstration. Closing this.
