### ISSUE TITLE
LUA record not returned correctly after AXFR

### ISSUE THREAD

**Issue by zarya** [PowerDNS/pdns#8517]
- Program: Authoritative
 - Issue type: Bug report

### Short description
LUA variable record is not reassembled correctly after AXFR transfer

### Environment
 - Operating system: Deb 10
 - Software version: 4.2.0-1pdns.buster
 - 1 master 2 slaves via AXFR

### Steps to reproduce
``` '193.93.24.31','46.54.227.93'}``` turned in to ```'193.93.24.3" "1','46.54.227.93' ```
1. A long (more then 255) LUA record with variables
2. AXRF the record to a slave
3. Slave returns ip 193.93.24.3 when the variable is used in pickclosest

### Expected behavior
Slave returns 193.93.24.31

### Actual behavior
Slave returns 193.93.24.3

### Other information
in the dns wire protocol (including AXFR), we use the TXT encoding for the LUA code and the TXT encoding has a 255 byte chunk limit so we split it

https://github.com/PowerDNS/pdns/blob/master/pdns/dnsrecords.cc#L174
i suspect removing that line will make your slave work

### Workaround
you see on the slave the code has been split in bad places on " "
on the master, you could split on good places with " " like, right after a comma or ) once you do that, the slave should get that same split

**Comment by pieterlexis** [comment]
@Habbie do we want to do this (not add a space)? It _might_ break multi-line LUA records in primaries

**Comment by pieterlexis** [comment]
the other option could be to do a different `xfr*` func in the recordtext writer

**Comment by Habbie** [comment]
> @Habbie do we want to do this (not add a space)? It _might_ break multi-line LUA records in primaries

Yes, so I don't like that either. I'm tempted to treat this as a doc issue.

**Comment by pieterlexis** [comment]
> Yes, so I don't like that either. I'm tempted to treat this as a doc issue.

"Don't have segments larger than 255 bytes on the primary" does not sound well though :)

**Comment by Habbie** [comment]
>  I'm tempted to treat this as a doc issue.

"Please split your TXT at sensible places if you are going to XFR it". I also want to make multiline LUA easier to work with in `pdnsutil` so that would fix the splits automatically for a lot of users.

**Comment by Habbie** [comment]
> "Don't have segments larger than 255 bytes on the primary" does not sound well though :)

It's a very normal thing to say to programmers about line lengths ;)

**Comment by Habbie** [comment]
I'll fix some docs.
