### ISSUE TITLE
Auth 4.3.0-alpha1 wishlist

### ISSUE THREAD

**Issue by pieterlexis** [PowerDNS/pdns#8535]
This issue to to track the things I'd like for 4.3.0-alpha1

- [x] #8486
- [x] #8441
- [ ] #8435
- [x] #8419
- [ ] #8355
- [ ] #8249 

And perhaps some more...

Peter:
- [x] #8536

**Comment by Habbie** [comment]
Upgrade guide needs to mention that we dropped setuid, and permissions on /etc/powerdns need to be correct.

**Comment by Habbie** [comment]
I have put milestones (alpha1 and alpha2) on the three unmerged ones. Closing this.
