### ISSUE TITLE
Auth feature request: ability to publish RFC8078 "DELETE" CDS/CDNSKEY records

### ISSUE THREAD

**Issue by gryphius** [PowerDNS/pdns#8545]
- Program: Authoritative,
 - Issue type: Feature request

### Short description
[RFC8078](https://tools.ietf.org/html/rfc8078#page-7) +[errata](https://www.rfc-editor.org/errata/eid5049) describes special `CDS` and `CDNSKEY` records

`CDS 0 0 0 00`
`CDNSKEY 0 3 0 AA==`

which signal that the entire DS RRset at the parent must be removed.

It would be nice if there was a simple way to automatically publish these records, for example using a new metadata option or possibly using a special value for `PUBLISH-CDS`/ `PUBLISH-CDNSKEY` metadata.

### Usecase
When signed zones are transferred to different nameserver it is often necessary to go unsigned, because the gaining operator may not support DNSSEC or because a secure handover is not supported bei either party.
With this option, going unsigned would work more easily for zones where the parent supports RFC8078.

Currently, PowerDNS supports publishing these records when inserted manually, using the [direct-dnskey](https://doc.powerdns.com/authoritative/settings.html#direct-dnskey) setting. However this currently does not work with non-native replication (due to #6988 ) and it requires several steps/api calls, making automation more error prone.

### Description

Using new metadata option ( something like `PUBLISH-CDS-DELETE` , `PUBLISH-CDNSKEY-DELETE` both booleans) this would publish the records mentioned above and ignore all other synthesized `CDS` or `CDNSKEY` records.

Maybe we could also define special values for the existing `PUBLISH-CDS`/`PUBLISH-CDNSKEY` metadata. In the `CDS` case this would work quite simple by setting the value `0` as algorithm number. I'm not sure if this could lead to confusion in the `CDNSKEY` case however, as this is a boolean value and '0' could be interpreted as `Do not publish CDNSKEY records` instead of `Publish the DELETE CDNSKEY Record`

**Comment by crami** [comment]
If anyone is willing to implement this, please contact me.We can probably arrange some compensation.

**Comment by Habbie** [comment]
https://doc.powerdns.com/authoritative/changelog/4.4.html#change-4.4.0-alpha1

> the SVCB and HTTPS record types are supported, with limited additional processing

(via #9369)
