### ISSUE TITLE
[Solved]Is it possible to create a forwarded zone through api?

### ISSUE THREAD

**Issue by jasonjoo2010** [PowerDNS/pdns#8553]
- Program: Recursor
- Issue type: Bug report(Probably)

### Short description
Forwarded kind of zone can not be created through recursor's api interface.

### Environment
 - Operating system: Docker / Mac / Centos 7.3 (All tried)
 - Software version: 4.1.11
 - Software source: https://hub.docker.com/r/flowguard/powerdns-recursor

### Usecase
In a stateless node management in cluster environment we start several recursors in different nodes and make them consistent through api interface.

### Steps to reproduce
Boot up command line:
```shell
/usr/sbin/pdns_recursor --local-address=0.0.0.0:53 --disable-syslog=no --client-tcp-timeout=30 --max-cache-ttl=600 --server-down-max-fails=20 --server-down-throttle-time=30 --packetcache-ttl=120 --packetcache-servfail-ttl=15 --network-timeout=5000 --minimum-ttl-override=30 --webserver=yes --api-key=asdf --webserver-address=0.0.0.0 --webserver-allow-from=0.0.0.0/0 --forward-zones --forward-zones-recurse --api-config-dir=/var/zones --include-dir=/var/zones
```

The key parameters:
```shell
--webserver=yes --api-key=asdf --api-config-dir=/var/zones --include-dir=/var/zones
```
Which we found we must append the empty `forward-zones` and `forward-zones-recurse` to make the zone files created through api loaded.

But I tried various ways & JSON body but was unable to create a `forwarded` zone through api. A forwarded zone file was generated successfully but it didn't work. So I want to figure out if it is possible to do it through API interface or it's designed to create zones only `Native`.

Request:

POST http://recursorIP:8082/api/v1/servers/localhost/zones

```json
{"kind":"Forwarded","name":"example.com.","recursion_desired":true,"servers":["10.213.72.189"],"type":"Zone"}
```

Response:

Recursor always return the message with status code 422
```json
{
  "error": "Could not find domain 'yoloho4.com.'"
}
```

It will be success when change kind property into `Native`.

### Expected behaviour
Forwarded zone can be created through api.

### Actual behaviour
Zone file can be created as `/var/zones/zone-example.com..conf` with content 

```
# Generated by pdns-recursor REST API, DO NOT EDIT
forward-zones-recurse+=example.com.=10.213.72.189:53
```

But it make no effect when reload.

Related logs after invoking the api:
```
Nov 19 10:05:31 Reloading zones, purging data from cache   <<<<< reload
Nov 19 10:05:31 Parsing authoritative data for zone 'yoloho.com.' from file '/var/zones/zone-yoloho.com..zone'          <<<< zone file created as "Native"
Nov 19 10:05:31 Parsing authoritative data for zone 'yoloho1.com.' from file '/var/zones/zone-yoloho1.com..zone'       <<<< zone file created as "Native"
```

Forwarded zone file with ".conf" postfix is ignored.

### Conclusion(Update)
Issue is solved.

The basic principle is that the command line arguments have a higher priority to configuration in file(Override). And it will not change even you trigger the `reloading` of configuration.

And the affected configuration in this issue `forward-zone-recursive` is taken as configuration in files (zone files) but not kind of data file. So if `--forward-zone-recursive` is given in command line then whatever you write in configuration file or update through api interface they are `overridden` to the value in command line. So if you want them work as you want you should remove them from command line. The arguments having similar behaviors include:

* --forward-zones
* --forward-zones-file
* --forward-zones-recurse
* --auth-zones
* --export-etc-hosts
* --serve-rfc1918

**Comment by jasonjoo2010** [comment]
Recursor always return the message with status code 422:

```json
{
  "error": "Could not find domain 'yoloho4.com.'"
}
```

**Comment by jasonjoo2010** [comment]
If I just change the `kind` into `Native` it will success at once.

**Comment by omoerbeek** [comment]
We have a template for issues, please use it. It helps you to provide a better issue report.

It is not clear what product your are referring to and important details like a version and the exact json body is missing.

**Comment by jasonjoo2010** [comment]
> We have a template for issues, please use it. It helps you to provide a better issue report.
> 
> It is not clear what product your are referring to and important details like a version and the exact json body is missing.

I am sorry it was so late last night after struggling for almost whole day and I didn't provide enough information. I have updated the issue and please check it again.

Thanks.

**Comment by omoerbeek** [comment]
Please check #5421

**Comment by omoerbeek** [comment]
I locally confirmed that the problem is the command line options indeed. Move the `forward-zones` and `forward-zones-recurse` to a config file and it works for me. I'll make sure the docs mention this.

**Comment by jasonjoo2010** [comment]
> Please check #5421

Oh I have checked it last night but I missed the most important conclusion.

So there still exists the issue (or call it tips need attention)?
And is there other similar configuration items beside `forward-zones` and `forward-zones-recursive`?

Maybe introduce a warning in booting logs is a good idea.

**Comment by omoerbeek** [comment]
This applies to  the 7 options mentioned in 
https://github.com/PowerDNS/pdns/blob/master/pdns/reczones.cc#L322

Basically, the command line will override the values in the config file, dynamic or not.

**Comment by jasonjoo2010** [comment]
Great.

The gap understanding the `overriding` algorithm between configuration and command line arguments is that the `zone files` are actually `configuration file` but not `special zone data file`. Because it's written using the gramma appending of specific configuration item (`+=`). It's quite easily understood after you know they are also parts of configuration and arguments have a higher priority to them.

After all it can be understood now though it doesn't make sense.
And I will update the conclusion to the end of issue body to provide convenience to possible comers and close this issue.

Thanks
