### ISSUE TITLE
boost.m4 doesn't detect gcc 9.2

### ISSUE THREAD

**Issue by rubenk** [PowerDNS/pdns#8566]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Environment

 - Operating system: Fedora Rawhide
 - Software version: git master, dndist 1.4.0, gcc-9.2.1-1.fc32.3.x86_64

### Steps to reproduce

1. do a build
2. ./configure outputs `checking for the toolset name used by Boost for g++... configure: WARNING: could not figure out which toolset name to use for g++
`

To be frank I have no idea why Boost needs to "check for the toolset name" and what the impact is if it cannot detect this. Having to keep updating this macro for every minor gcc version is stupid..

**Comment by pieterlexis** [comment]
please open this issue in https://github.com/tsuna/boost.m4 :)
