### ISSUE TITLE
rec: Export DNSSEC validation status in protobuf messages

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8587]
- Program: Recursor
 - Issue type: Feature request

### Short description
It would be nice to have the DNSSEC validation status exported to our protocol buffer messages, in order to know whether the answer was validated or not, and the exact validation status if it was.

**Comment by omoerbeek** [comment]
I'd have to check when the validation status is available. I'm not sure if it is on the "get reply from auth" moment, which is the spot we generate the protobuf message for that case.

On the "generate client response" spot the validation status should be available I guess.

**Comment by rgacogne** [comment]
It's clearly not available for the outgoing queries / incoming responses case, but I don't think that's the one who matters. It's available for the outgoing responses case.
