### ISSUE TITLE
 "udp-truncation-threshold" only effective when there no OPT

### ISSUE THREAD

**Issue by hankai17** [PowerDNS/pdns#8588]
- Program: Recursor 
 - Issue type: Feature request

### Description

In my option, the maxanswersize in each dns transaction which contains OPT should unaffected by the "udp-truncation-threshold".  "udp-truncation-threshold" only effective when there no OPT

**Comment by Habbie** [comment]
Hello,

I'm afraid we do not understand what you mean. Can you perhaps show your config, and some `dig` output that shows the problem?

**Comment by hankai17** [comment]
https://github.com/PowerDNS/pdns/pull/8590

**Comment by hankai17** [comment]
I think that we should refer to client's request dns payload size(If there has edns opt in dns request).

Consider that situation:  DNS Server defines truncation threshold 512 and 
Client defines payload size 700 (That means dns server should not send a tc flag even if package more than 512). DNS Server should only use UDP to send response.

**Comment by Habbie** [comment]
If the server has a 512 limit, and the client defines payload size 700, we use the 512 limit.

**Comment by hankai17** [comment]
Is there  https://github.com/PowerDNS/pdns/blob/3bfbc96877bb666b5d7751efbde5a6eb313e8a76/pdns/pdns_recursor.cc#L1135

the 512 should equal to

https://github.com/PowerDNS/pdns/blob/3bfbc96877bb666b5d7751efbde5a6eb313e8a76/pdns/pdns_recursor.cc#L4691

**Comment by Habbie** [comment]
No, the code is correct already.
