### ISSUE TITLE
open-tcp-connections metric "Unknown"

### ISSUE THREAD

**Issue by stefreak** [PowerDNS/pdns#8593]
- Program: Authoritative
 - Issue type: Bug report

### Short description
According to the performance monitoring documentation there should be a metric named `open-tcp-connections`
https://doc.powerdns.com/authoritative/performance.html#open-tcp-connections

If I run `pdns_control show open-tcp-connections` the output is just `Unknown`.

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: `4.1.13-1pdns.bionic`
 - Software source: PowerDNS repository

### Steps to reproduce
1. pdns_control show open-tcp-connections

### Expected behaviour
I expect to see the number of open tcp connections

### Actual behaviour
pdns_control writes `Unknown` to stderr.

**Comment by Habbie** [comment]
This metric was added very recently; right now, it's only in master builds, and it will be in 4.3.0. Sorry!
