### ISSUE TITLE
Feature request: use a zone specific default TTL that is provided by the database backend

### ISSUE THREAD

**Issue by rz60** [PowerDNS/pdns#8596]
#8494

- Use case:
  One could change the default TTL for all records (of the records table in the default schema) just in one specific zone more efficiently, e.g. without updating every single record to a zone-specific TTL-value that is defined behind the database backend (inside the database logic).  This is useful for large zones, prevents a higher write load and also helps simplifying the database code.

- Description:

  Current state:
  There is only one system-wide default TTL value for all records whose TTL is null, regardless of which zone they belong to (parameter 'default-ttl' in pdns.conf).  In order to allow a zone-specific default TTL that differs from the system-wide default TTL, all records of the zone must be updated to this zone-specific default TTL.  This causes an unnecessary high write load and complicates the code.

  Goal:
  From my point of view there are 2 ways to implement a zone specific default TTL:
  1. Obtain the default TTL from the MINIMUM field of the SOA record. (This field is also being used as negative cache TTL).  For all records in the zone with a TTL value of NULL this MINIMUM TTL will be used.
  2. A new attribute, for example as new domainmetadata.kind 'DEFAULT-TTL' in the database backend, could serve as a default TTL for this zone and being used for all records in that zone with a TTL value of NULL.  Only for records in zones having not this kind defined in their domainmetadata, the system-wide (or server-wide) default-ttl is being used.

  Pros and Cons:
  (I.) seems to be the simplest way, but there are no distinct values possible for 'default TTL' and 'negative cache TTL'.
  (II.) might be more expensive to implement but offers to choose a different default TTL than the SOA minimum value (negative cache TTL).  Hence this would be the better, more flexible solution.

**Comment by Habbie** [comment]
>     * Hence this would be the better, more flexible solution.

The cost is a higher permanent read load - to save a one time high write load. I don't think this tradeoff makes sense.

I'll leave this open for a bit in case anybody disagrees with me, but I'm tempted to close this as wontfix, sorry!

**Comment by Habbie** [comment]
I discussed with a few other developers and we believe you should handle this in your database. Sorry!
