### ISSUE TITLE
Support dnssec protocol for ldap backend

### ISSUE THREAD

**Issue by KVInventoR** [PowerDNS/pdns#8606]
Hi, We are using the latest version of pdns server and have an issue with implementation dnssec for LDAP backend.
We would like to have a support for dnssec for ldap or use hybrid infrastructure when records are stored in ldap and dnssec keys in mysql backend, is it possible to implement?

Thanks

**Comment by pieterlexis** [comment]
Please see, test and update #6533

**Comment by Habbie** [comment]
What @pieterlexis said! Please comment in #6533 if you have any remarks on that work. Thank you!
