### ISSUE TITLE
abaton.secure-store.at cannot be resolved

### ISSUE THREAD

**Issue by swoga** [PowerDNS/pdns#8619]
- Program: Recursor
 - Issue type: Bug report

### Short description
`abaton.secure-store.at` cannot be resolved.

### Environment

 - Operating system: Debian Stretch
 - Software version: 4.2.1
 - Software source: PowerDNS repository

### Steps to reproduce
Query `abaton.secure-store.at`

### Expected behaviour
`abaton.secure-store.at. 139     IN      A       185.51.196.67`

### Actual behaviour
`SERVFAIL` is returned

### Other information
The domain can be resolved with an older version of the recursor (I tried 4.0.4 which I had available from the debian repo) and also with `dig +trace`, `1.1.1.1`, `8.8.8.8`.

[log.txt](https://github.com/PowerDNS/pdns/files/3945687/log.txt)
[pcap.zip](https://github.com/PowerDNS/pdns/files/3945690/pcap.zip)

**Comment by jostreff** [comment]
Tested with unbound-1.9.5 - also works.

**Comment by rgacogne** [comment]
```
Dec 10 16:42:29 [1] abaton.secure-store.at: Got 2 answers from ns1.secure-store.at (185.51.196.67), rcode=0 (No Error), aa=0, in 25ms
Dec 10 16:42:29 [1] Removing record 'abaton.secure-store.at|A|185.51.196.67' in the answer section without the AA bit set received from abaton.secure-store.at
Dec 10 16:42:29 [1] Removing record 'abaton.secure-store.at|A|185.51.196.67' in the answer section without the AA bit set received from abaton.secure-store.at
```

The authoritative servers for this domain are sending authoritative answers without the `AA` bit set, which is invalid.

**Comment by omoerbeek** [comment]
https://dnsviz.net/d/abaton.secure-store.at/dnssec/
Shows the nameservers for this domain do not respond with an autoritative answer. Rec 4.2. regards this as invalid.

**Comment by pieterlexis** [comment]
![Screenshot_2019-12-10_16-44-01](https://user-images.githubusercontent.com/731232/70544454-60a40000-1b6c-11ea-8b8b-434816b485db.png)

**Comment by swoga** [comment]
Thank you all for your lightning fast response :)
I didn't try DNSViz, because I thought it only helps with DNSSEC problems, good too know.
