### ISSUE TITLE
Support local-ipv6 as 'deprecated' in pdns-auth 4.3.x instead of removing it

### ISSUE THREAD

**Issue by kpfleming** [PowerDNS/pdns#8624]
- Program: Authoritative
 - Issue type: Feature request

### Short description
The announcement of the first alpha release of pdns-auth 4.3.x indicates that the `local-ipv6` configuration setting will be removed, and that the `local-address` setting will be upgraded to support both IPv4 and IPv6 addresses. Unfortunately this will make upgrading existing systems difficult, at best.

### Usecase
I manage pdns-auth servers on Debian systems, using Ansible. When pdns-auth 4.3.x is released, I would make these changes:

1. Reconfigure `apt` to use the 4.3.x repository instead of the 4.2.x repository.
1. Apply the updated Ansible playbook. This would apply the `apt` reconfiguration, then upgrade the `pdns-auth` package, in the process restarting the `pdns-auth` service.

With the planned configuration change, this upgrade will fail as the service won't restart, because my configuration has `local-ipv6` settings.

Alernatively, I could attempt this path:

1. Reconfigure `apt` to use the 4.3.x repository instead of the 4.2.x repository.
1. Change the configuration file to move the IPv6 address(es) into `local-address` configuration settings.
1. Apply the updated Ansible playbook. This would apply the `apt` reconfiguration, apply the `pdns-auth` reconfiguration, then upgrade the `pdns-auth` package, in the process restarting the `pdns-auth` service.

Unfortunately in this scenario if anything causes the package upgrade to fail, I'll again be left without a running service, as the 4.2.x service won't start with IPv6 addresses in the `local-address` configuration setting.

### Description
The 4.3.x release series should continue to support `local-ipv6`, merging its contents with `local-address` as if the user has done that merge themselves, but generating a warning at startup that `local-ipv6` is deprecated and will be removed in the 4.4.x release series. This will allow for smooth upgrades, even allowing users to downgrade to 4.2.x if they find that 4.3.x causes problems for them.

**Comment by Habbie** [comment]
#8749
