### ISSUE TITLE
dnsdist: Metric for "FrameStreamLogger: queue full, dropping."

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8629]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
It would be nice to have a metric for the "FrameStreamLogger: queue full, dropping." case, instead of an error message.

**Comment by zeha** [comment]
Same code is used by the Recursor, so I guess it should also grow a metric for it.

**Comment by johnhtodd** [comment]
Yes, please.  This is filling up lots of logfiles.
