### ISSUE TITLE
BUG: API, PUT to zone to update master_tsig_key_ids fails if there's more than one key name

### ISSUE THREAD

**Issue by james-stevens** [PowerDNS/pdns#8645]
- Program: Authoritative / RestAPI / mariadb v10.4.8 backend (using mysql plugin)
 - Issue type: Bug report

### Short description
You can only add one TSIG to `master_tsig_key_ids` using the API
The system reports that the second TSIG does not exist, even when it does - this can be proved by 
(1) running `pdnsutil list-tsig-keys` and 
(2) adding the key on its own

### Environment
 - Operating system: Linux, Slackware 14.2
 - Software version: 4.2.0
 - Software source: compiled yourself (with no changes to supplied src)

### Steps to reproduce
Use the API to try and add more than one `master_tsig_key_ids`

`curl` commands given below. Same effect when calling the RestAPI from Javascript.

```
# curl -X PUT -v -H 'X-API-Key: Dev-Key' -H "Content-Type: application/json" -d '{ "master_tsig_key_ids": ["james.tsig.","dog.key."] }'    'http://127.1.0.1:8081/api/v1/servers/local
*   Trying 127.1.0.1...
* Connected to 127.1.0.1 (127.1.0.1) port 8081 (#0)
> PUT /api/v1/servers/localhost/zones/jrcs.uk HTTP/1.1
> Host: 127.1.0.1:8081
> User-Agent: curl/7.49.1
> Accept: */*
> X-API-Key: Dev-Key
> Content-Type: application/json
> Content-Length: 53
>
* upload completely sent off: 53 out of 53 bytes
< HTTP/1.1 422 Unprocessable Entity
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 62
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< Server: PowerDNS/4.2.0
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
* Closing connection 0
{"error": "A TSIG key with the name 'dog.key' does not exist"}

# curl -X PUT -v -H 'X-API-Key: Dev-Key' -H "Content-Type: application/json" -d '{ "master_tsig_key_ids": ["dog.key."] }'    'http://127.1.0.1:8081/api/v1/servers/local              
*   Trying 127.1.0.1...
* Connected to 127.1.0.1 (127.1.0.1) port 8081 (#0)
> PUT /api/v1/servers/localhost/zones/jrcs.uk HTTP/1.1
> Host: 127.1.0.1:8081
> User-Agent: curl/7.49.1
> Accept: */*
> X-API-Key: Dev-Key
> Content-Type: application/json
> Content-Length: 39
>
* upload completely sent off: 39 out of 39 bytes
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Length: 0
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Server: PowerDNS/4.2.0
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
<
* Closing connection 0

# pdnsutil list-tsig-keys
barry.key. hmac-sha512. Olt8VfOpMZtV496Exgwm1OH7D9ehhEDQcuAUDVGqzIMYX9QVusKyvzwdBkDLGMgXxkBHPMGhbAtt62BTzBE0aA==
shane.tsig. hmac-sha256. 25FKFlw1bYg4R9eMJo8sdC2AV7Z4KKw1H5R+XvG9D8c7iDURSyk9ovUZr72I7/a58SoKqzyIdNOKh5YEIoU7aA==
james.tsig. hmac-sha512. el/V6As15UzVgSSzZGQzWOqFsOxrydNi3hkzNtWv/VUjsqpewTx5tdXqWMyog3RnmlSPUxj7VaofzgX8vmC7tA==
fred.tsig. hmac-sha512. KGBJcVMHrwfFJfCAA/f9sk91L83PVMqOVe/PhkumdoAXpYonK/bHn9fZofHP5Y82cAF5pjptg2QULuR8eRcVTA==
name.tsig. hmac-sha512. Qe0OtoIHBW1Xv+v4k09vdB171WMjl1ZSj+DSsDahgZBRHwuIJGPmt1rYmjBITYQEeXZbKB89HmlQ4X6x7JgywQ==
slave-tsig. hmac-sha256. +a7k8W8ajnv8mSFOX/9wwkkAIH3LANed6DaeQ4jm09aMhtIoqRC6TlH3D1ke61H2AI/j4GhEUDvaeJEvT9nt+g==
some.tsig.key. hmac-md5. nM60hh/9aodOA/67kNJFnSLuoyqyKNRtuoczjqYw9vU=
dog.key. hmac-sha1. 1LogMoBNRJptmcdQG5D4D4fZT4AyYKIzSIz7RvkH7pc=
```

NOTE: although, in the failed error message, it has dropped the trialing `.` from `dog.key.` it always does this, so I suspect this is just an affectation of how it logs the key name.

### Expected behaviour
Both keys should be added for TSIG-ALLOW-AXFR
Works fine with one TSIG - see above

### Actual behaviour
You can add one master key using the API, but not more than one

### Other information
Code to handle `master_tsig_key_ids` is at `pdns/ws-auth.cc line 774 of 2287` - there is no obvious difference in the handling of the first key and subsequent keys.

The error is triggered by the code
```
      B.getTSIGKey(keyname, &keyAlgo, &keyContent);
      if (keyAlgo.empty() || keyContent.empty()) {
        throw ApiException("A TSIG key with the name '"+keyname.toLogString()+"' does not exist");
```
but neither of these can be really true, becuase I can add the key on its own fine - this implies the failure is in the way it loads the key. May be the MySQL connection state isn't finished correctly?

Adding multiple TSIG Keys works fine, if you use `pdnsutil activate-tsig-key <zone> <key> master`

No logging related to this issue from pdns or mariadb.

**Comment by james-stevens** [comment]
Adding multiple TSIG Keys works fine, if you use `pdnsutil activate-tsig-key <zone> <key> master`

**Comment by rgacogne** [comment]
It looks like we don't clear the value of `keyAlgo` and `keyContent` between two iterations of the loop, and `GSQLBackend::getTSIGKey()` will try to match the algorithm in `keyAlgo` if it's set. Since your two keys have a different algorithm (`hmac-sha512.` vs `hmac-sha1.`) the second one doesn't match.

**Comment by james-stevens** [comment]
Well done - nice find - sounds an easy fix :)
