### ISSUE TITLE
Default max-qperq too low for QNAME minimization?

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#8646]
- Program: Recursor
 - Issue type: Bug report

### Short description
The default `max-qperq` setting is 50. (And `max-recursion-depth` is 40, but I don't know what that does.) I'm concerned that may not be enough for QNAME minimization, DNSSEC validation, cold caches, and fun things like IPv6 reverse DNS.

An `ip6.arpa` name has, what, 34 labels. From a cold cache, to resolve a secure name that exists, that's 34 `A` queries, `34` DS queries, a half dozen `DNSKEY` queries... you're already over 70 queries without resolving any nameservers or sending a single actual `PTR` query.

A hot cache should run fine, but resolvers may `SERVFAIL` some queries when they're warming up.

Should it be increased to something like 100? Or more?

### Environment
 - Operating system: Ubuntu 16.04 x86-64
 - Software version: 4.3.0~beta1+master.19.gfa178d8fd-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce
1. `sudo systemctl restart pdns-recursor`
2. `dig -x 2620:57:4011:1452::62`

### Expected behaviour
`NXDOMAIN`.

### Actual behaviour
`SERVFAIL`.

Retrying it a minute later after the `SERVFAIL` cache clears works.

### Other information
My example IP is a random IP that doesn't even have a `PTR` record. To pick something more traditional, the (signed) root server IPs 2001:500:1::53, 2001:7fd::1 and 2001:500:9f::42 appear to be suitable.

**Comment by mnordhoff** [comment]
> From a cold cache, to resolve a secure name that exists, that's 34 A queries, 34 DS queries, a half dozen DNSKEY queries... you're already over 70 queries without resolving any nameservers or sending a single actual PTR query.

@phonedph1 points out that the QNAME minimization algorithm would not make 34 `A` queries. It starts jumping 3 labels at a time. So it would only do, I don't know, ~15?

But you still get 34 `DS` queries, and easily over 50 queries total.

**Comment by phonedph1** [comment]
`pdns_recursor: Sending SERVFAIL to 127.0.0.1:46062 during resolve of '2.6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.5.4.1.1.1.0.4.7.5.0.0.0.2.6.2.ip6.arpa' because: more than 50 (max-qperq) queries sent while resolving 2.5.4.1.1.1.0.4.7.5.0.0.0.2.6.2.ip6.arpa`

**Comment by phonedph1** [comment]
I guess the RFC is pretty spot on when it says it might have performance problems on a cold cache. 82 queries and nearly 6 seconds.

```
$ rec_control get all-outqueries
37
$ dig -x 2620:57:4011:1452::62 @localhost

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> -x 2620:57:4011:1452::62 @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 5957
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;2.6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.5.4.1.1.1.0.4.7.5.0.0.0.2.6.2.ip6.arpa. IN PTR

;; AUTHORITY SECTION:
0.4.7.5.0.0.0.2.6.2.ip6.arpa. 3600 IN   SOA     ns.uniregistry.com. ops.uniregistry.com. 2019112115 3600 300 604800 3600

;; Query time: 5403 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Dec 19 11:21:52 MST 2019
;; MSG SIZE  rcvd: 159

$ rec_control get all-outqueries
119
$
```

**Comment by phonedph1** [comment]
This also seems to cause problems on things that have multiple CNAMEs on signed domains. 

```
during resolve of 'blog.kimpex.com' because: more than 50 (max-qperq) queries sent while resolving sites.hubspot.net
during resolve of 'info.redarrow.ca' because: more than 50 (max-qperq) queries sent while resolving hs-sites.origin.hubspot.net
during resolve of 'www.policyworks.com' because: more than 50 (max-qperq) queries sent while resolving hs-sites.origin.hubspot.net
```
