### ISSUE TITLE
recursor: Infinite DNAME recursion

### ISSUE THREAD

**Issue by jeremy-clerc** [PowerDNS/pdns#8660]
- Program: Recursor
 - Issue type: Bug report

### Short description
DNAME on same domain, which expands it, `example.com. DNAME prod.example.com.` leads to infinite recursion of the DNAME. (See 'Actual behaviour' for output).

### Environment
 - Operating system: centos-7, alpine (builder)
 - Software version: from 4.2.0-0.beta1 to HEAD
 - Software source: Compiled via builder scripts from github sources

### Steps to reproduce

1. Configure authoritative server (using any version):

pdns-authoritative.conf:
```
socket-dir=/var/run/authoritative
setgid=pdns
setuid=pdns
launch=bind
bind-check-interval=0
bind-config=/etc/pdns/bind.conf
dname-processing=yes
loglevel=5
log-dns-queries=yes
cache-ttl=60
```

bind.conf
```
zone "example.com" { type master; file "/etc/pdns/zones/example.com"; };
zone "prod.example.com" { type master; file "/etc/pdns/zones/prod.example.com"; };
```

example.com
```
$ORIGIN	example.com.
$TTL	600

example.com.	SOA	dns-auth-docker-prod.example.com.	mail.example.com.	1577433258	900	600	86400	0
example.com.	600	NS	dns-auth-docker-prod.example.com.
prod.example.com.	600	NS	dns-auth-docker-prod.example.com.
dns-auth-docker-prod.example.com.	600	A	172.17.0.2
example.com.	DNAME	prod.example.com.
```

prod.example.com
```
$ORIGIN	prod.example.com.
$TTL	600

prod.example.com.	SOA	dns-auth-docker-prod.example.com.	mail.example.com.	1577433258	900	600	86400	0
prod.example.com.	600	NS	dns-auth-docker-prod.example.com.
abc	600	A	127.0.0.1
```
2. Configure pdns-recursor (version >= 4.2.0-0.beta1)

forward.conf
```
+example.com=<auth server>
+prod.example.com=<auth server>
```

recursor-recursor.conf
```
socket-dir=/var/run/recursor
setgid=pdns-recursor
setuid=pdns-recursor

allow-from=0.0.0.0/0
dont-query=127.0.0.0/8
edns-outgoing-bufsize=8192
forward-zones-file=/etc/pdns-recursor/forward.conf
local-address=0.0.0.0
local-port=53
```

3. `dig abc.example.com @recursor`

### Expected behaviour
```
# dig abc.example.com. @172.17.0.3

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> abc.example.com. @172.17.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44043
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;abc.example.com.			IN	A

;; ANSWER SECTION:
abc.example.com.		581	IN	CNAME	abc.prod.example.com.
abc.prod.example.com.	581	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 172.17.0.3#53(172.17.0.3)
;; WHEN: Fri Dec 27 11:07:42 UTC 2019
;; MSG SIZE  rcvd: 79
```
### Actual behaviour
```
# dig abc.example.com. @172.17.0.3

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> abc.example.com. @172.17.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 41337
;; flags: qr rd ra; QUERY: 1, ANSWER: 32, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;abc.example.com.			IN	A

;; ANSWER SECTION:
abc.example.com.		600	IN	CNAME	abc.prod.example.com.
abc.prod.example.com.	600	IN	CNAME	abc.prod.prod.example.com.
abc.prod.prod.example.com.	600	IN	CNAME	abc.prod.prod.prod.example.com.
abc.prod.prod.prod.example.com. 600	IN	CNAME	abc.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.example.com. 600 IN	CNAME	abc.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.example.com. 600 IN CNAME abc.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME	abc.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.example.com.	600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600	IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN	CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com. 600 IN CNAME	abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.	600 IN CNAME abc.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.
example.com.		600	IN	DNAME	prod.example.com.

;; Query time: 1 msec
;; SERVER: 172.17.0.3#53(172.17.0.3)
;; WHEN: Fri Dec 27 08:20:00 UTC 2019
;; MSG SIZE  rcvd: 824
```

[tracing.log](https://github.com/PowerDNS/pdns/files/4005168/tracing.log)

### Other information

With git bisect, I believe this was introduced by commit d30b54935bc9037bdded105812ef232a133433f0 from https://github.com/PowerDNS/pdns/pull/6341

**Comment by Habbie** [comment]
```
$ named-checkzone example.com example.com 
zone example.com/IN: NS 'dns-auth-docker-prod.example.com' is below a DNAME 'example.com' (illegal)
zone example.com/IN: not loaded due to errors.
```

Your setup is illegal, and if there's a bug here, it's that the Auth did not reject your zonefile (we are tracking a related Auth DNAME bug in #1361).

The recursor is behaving correctly (although perhaps it would be good if it servfailed earlier).

**Comment by jeremy-clerc** [comment]
Removed the A and NS delegation to be compliant with rfc6672 even though it is not what makes the recursor loop.
```
$ORIGIN	example.com.
$TTL	600

example.com.	SOA	dns-auth-docker-prod.example.com.	mail.example.com.	1577433258	900	600	86400	0
example.com.	600	NS	dns-auth-docker-prod.example.com.
example.com.	DNAME	prod.example.com.
```
It is allowed at the apex.

imho, the recursor should detect it already handled the DNAME and move on, instead of appending the suffix forever.
Without cache, it works as expected, first one is synthetized as CNAME, which is resolved correctly.

**Comment by Habbie** [comment]
> imho, the recursor should detect it already handled the DNAME and move on, instead of appending the suffix forever.

Move on to what? What is the response you expect from the Recursor?

**Comment by jeremy-clerc** [comment]
1. abc.example.com
2. DNAME processing, synthetize to CNAME abc.prod.example.com
3. abc.prod.example.com already ends with prod.example.com, do not process example.com DNAME
4. Resolve  CNAME abc.prod.example.com

**Comment by jeremy-clerc** [comment]
I am thinking for step 3, something like:

```
if (qname.isPartOf(rec->begin()->d_content->getZoneRepresentation())
  continue;
```
When a entry is found for a dname: https://github.com/PowerDNS/pdns/blob/master/pdns/syncres.cc#L1199

**Comment by Habbie** [comment]
Let's talk about code when we settled on the right behaviour. What would the right `dig` output look like to you?

**Comment by jeremy-clerc** [comment]
Something like expected behaviour:

```
abc.example.com.		581	IN	CNAME	abc.prod.example.com.
abc.prod.example.com.	581	IN	A	127.0.0.1
```

As the end user I should not see the DNAME as it is synthetized.

**Comment by Habbie** [comment]
> abc.prod.example.com.	581	IN	A	127.0.0.1

This is forbidden to exist, as there is a DNAME overlapping it.

**Comment by jeremy-clerc** [comment]
Understood.

As it worked before, looks like we used a glitch which made us believe it was a valid usage :(

So the loop is expected and having records below `prod.example.com` is not allowed because of the DNAME at example.com level.

One thing to note is it kind of can be bypassed when declaring `example.com` and `prod.example.com` as two different zones:

The auth server will be happy to answer (same with bind9):
```
;; ANSWER SECTION:
example.com.            600     IN      DNAME   prod.example.com.
abc.example.com.                600     IN      CNAME   abc.prod.example.com.
abc.prod.example.com.   600     IN      A       127.0.0.1
```

Though the recursor rejects the CNAME because of the DNAME, and the A because we are authoritative for `prod.example.com` (but queried `example.com`).

I'll talk to my teammates if they have another understanding of this. In the meantime, feel free to close as working as intended.

Thanks for the quick responses.

**Comment by Habbie** [comment]
Thanks! Closing this.

**Comment by Annih** [comment]
From my understanding of the [RFC](https://tools.ietf.org/html/rfc6672), a given authoritative server must not have RR below a DNAME, but nothing technicaly forbid 2 different authoritative servers to do so (especially in internal organization using special setup like split-horizon or blackhole). 
Anyway, even if the setup is not valid, I don't think this is the job of the recursor to validate the config of upstream authoritative servers. Its job is to resolve name in a kind of deterministic and standard way.

In our current case the answer seems pretty standard, the new DNAME implementation is clearly compliant with the RFC. However IMHO there are 3 things that I think could be addressed following the release of the new DNAME support:
1. something that was working before is not working anymore
2. result of `dig abc.prod.example.com` is inconsistent; it fails if the `DNAME` for example.com is cached; otherwise it succeeds.
3. response from zone example.com is impacting behavior of zone prod.example.com

For **1.**, you could argue that the setup is invalid, but even so the "API" has been broken with release 4.2 by a side effect of this feature without warning/informing customers, having a way to get back to former behavior could be interesting.

I think the worst is **2.**  as it is potentially dangerous; I don't see how to fix it other than fixing **3.**

For **3.** it is maybe subjective but if `example.com.` is handled by server `X` and `prod.example.com.` by server `Y` I don't expect my `service.prod.example.com` to be answered using cached info from `X`. That being said, implementing a cache per (forwarded) zone might be a bit complex to just fix current DNAME case, given the facts that in theory only DNAME and wildcards may "span" multiple subzones and that in practice wildcards are not cached (only the matching result).

So @Habbie do you think that:
* a PR adding a setting to disable `dname-support` would be accepted?
* a PR implementing a cache per zone is a good idea and could be accepted? (I'm giving it a try 😄)

Finally, do you see a better way to "rewrite" all queries not matching a given list of subzones to a specific one? *i.e*.  `a.example.com` rewritten to `a.prod.example.com` but `b.prod.example.com` stays untouched.
I guess lua could work, but DNAME was simpler. 😞 

@jeremy-clerc said, thank you for the quick answers and the time spent on this issue.

**Comment by Habbie** [comment]
Hello, you responded to a closed ticket that reported no bug. Your response contains a mix of feature requests and support questions. For feature requests, please file another ticket (but please understand that it makes no sense to disable 'DNAME support' in the recursor); for support questions, please use our IRC channel or our mailing lists, via https://www.powerdns.com/opensource.html

**Comment by Habbie** [comment]
I am closing conversation on this ticket to avoid any further confusion.
