### ISSUE TITLE
`dont-throttle-names` and `dont-throttle-netmasks` are not parsed as a comma separated list

### ISSUE THREAD

**Issue by costypetrisor** [PowerDNS/pdns#8676]
- Program: Recursor 
 - Issue type: Bug report

### Short description

I'm trying to use `dont-throttle-names` and `dont-throttle-netmasks` but I see they are not parsed as a comma separated list, as the documentation clearly states: https://doc.powerdns.com/recursor/settings.html#dont-throttle-names

### Environment

 - Operating system: CentOS 7 (Amazon Linux 2 actually)
 - Software version: 4.2.1
 - Software source: PowerDNS repository: https://repo.powerdns.com/centos/x86_64/7/rec-42/ 

### Steps to reproduce

1. Edit your `/etc/pdns-recursor/recursor.conf` and add:
```
dont-throttle-names= yourdomain.org,yourotherdomain.org,amazonaws.com
dont-throttle-netmasks=10.1.1.1,10.8.8.8
```
2. Start your PowerDNS recursor service
3. journalctl logs will show an error like: `Exception: Unable to convert 'yourdomain.org,yourotherdomain.org,amazonaws.com' to a netmask`  regardless if you use `dont-throttle-names` or `dont-throttle-netmasks` or together

### Expected behaviour
`dont-throttle-names` and `dont-throttle-netmasks` to work

### Actual behaviour
It's not splitting the values of `dont-throttle-names` and `dont-throttle-netmasks`.

### Other information

I suspect that the 3rd parameter to `stringtok` is not set to `","` [here](https://github.com/PowerDNS/pdns/blob/183b80e8c9ed6921d40b388092786da0c09a0bdf/pdns/pdns_recursor.cc#L4056) and [here](https://github.com/PowerDNS/pdns/blob/183b80e8c9ed6921d40b388092786da0c09a0bdf/pdns/pdns_recursor.cc#L4063)

Actually because the default value of the 3rd parameter `delimiter` of `stringtok` is `" \r\n"`, I managed to get it working by replacing `,` with a space:
```
# dont-throttle-names= yourdomain.org yourotherdomain.org amazonaws.com
dont-throttle-netmasks=10.1.1.1 10.8.8.8
```
But in this example, I have to keep `dont-throttle-names` commented because `delimiter` is `" \r\n"`

**Comment by omoerbeek** [comment]
Fixed by #8686
