### ISSUE TITLE
Request: JSON-RPC for “HTTP” API

### ISSUE THREAD

**Issue by FGasper** [PowerDNS/pdns#8678]
- Program: Authoritative
 - Issue type: Feature request

### Short description
It would be nice to avoid the HTTP overhead when dealing with PowerDNS’s API. In the same way that the remote-backend API is exposed via multiple transports, it would be nice to have access to the same functionality that the HTTP API exposes but via JSON-RPC instead.

### Usecase
I’d like to avoid loading an HTTP library to interact with PowerDNS. It seems also that a JSON-RPC solution would be faster/simpler than HTTP.

### Description
I envision something like:
1) A configuration directive to give either a UNIX socket or a TCP port to listen on.
2) Requests and responses are a stream of JSON text sequences (https://tools.ietf.org/html/rfc7464). Alternatively, use a framing protocol—perhaps borrowing the one from WebSocket. Alternatively still, use SOCK_SEQPACKET sockets (SCTP), but that might not work on Windows.
3) Documentation updated to map what are now “HTTP API” calls to their JSON-RPC equivalents.

**Comment by zeha** [comment]
I guess it might have been a valid choice when the API was conceived, but now it's a bit late for this -- esp. that this wouldn't be a new "transport", but would also include a new API "usage model". Therefore a completely new API would have to be designed and implemented.
Are there hard numbers on how this is going to be better?

**Comment by FGasper** [comment]
I don’t have such numbers, no. “Completely new API” does sound like more effort than the likely gains.

One _potential_ benefit to JSON-RPC is that the implementation would also lend itself to pub/sub workflows. So, e.g., if something wanted to subscribe to zone update events, that could happen … which isn’t “RPC” but would work with the notion of a transport mechanism that facilitates arbitrary 2-way communication (in addition to RPC).

**Comment by james-stevens** [comment]
I don't work for OX, so this is just my personal opinion.

To me this doesn't seem worth the effort when compared with the benefit you would already get by adding support for unix-sockets to the existing interface. The additional benefit seems relatively marginal and the extra support effort required to maintain two different interfaces is not insignificant.

If you want to be notified when a zone changes, there is already a DNS mechanism for this - although you don't get told what changed, just that there was a change. An HTTP callback could also be used to achieve the same effect, using the existing paradigm.
