### ISSUE TITLE
Unable to launch, no backends configured for querying

### ISSUE THREAD

**Issue by istiyakaminsanto** [PowerDNS/pdns#8703]
-- The result is RESULT.
Jan 15 07:37:01 dedi-par-56595 systemd[1]: pdns.service: Service hold-off time over, scheduling restart.
Jan 15 07:37:01 dedi-par-56595 systemd[1]: pdns.service: Scheduled restart job, restart counter is at 3834.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit pdns.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jan 15 07:37:01 dedi-par-56595 systemd[1]: Stopped PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pdns.service has finished shutting down.
Jan 15 07:37:01 dedi-par-56595 systemd[1]: Starting PowerDNS Authoritative Server...
-- Subject: Unit pdns.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pdns.service has begun starting up.
Jan 15 07:37:01 dedi-par-56595 pdns_server[23002]: Jan 15 07:37:01 Reading random entropy from '/dev/urandom'
Jan 15 07:37:01 dedi-par-56595 pdns_server[23002]: Jan 15 07:37:01 Unable to launch, no backends configured for querying
Jan 15 07:37:01 dedi-par-56595 pdns[23002]: Reading random entropy from '/dev/urandom'
Jan 15 07:37:01 dedi-par-56595 pdns[23002]: Unable to launch, no backends configured for querying
Jan 15 07:37:01 dedi-par-56595 systemd[1]: pdns.service: Main process exited, code=exited, status=99/n/a
Jan 15 07:37:01 dedi-par-56595 systemd[1]: pdns.service: Failed with result 'exit-code'.
Jan 15 07:37:01 dedi-par-56595 systemd[1]: Failed to start PowerDNS Authoritative Server.
-- Subject: Unit pdns.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit pdns.service has failed.
-- 
-- The result is RESULT.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
