### ISSUE TITLE
dnsdist: assigning a new value to DNSQuestion.len doesn't do anything

### ISSUE THREAD

**Issue by slavc** [PowerDNS/pdns#8711]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

On response processing path, dnsdist ignores any value assigned into DNSQuestion.len field and sends on a buffer of the original size anyway.

### Environment

 - Operating system: Fedora 31
 - Software version: commit d650d4b76b2bd7280b96153f9cd1f7b9becf1a84
 - Software source: compiled myself

### Steps to reproduce

1. Build dnsdist.
2. Create a configuration file `dnsdist.lua`, with the following contents:
```lua
addLocal("0.0.0.0", {reusePort=true})

setECSOverride(true)
setECSSourcePrefixV4(32)
setECSSourcePrefixV6(128)

function onresponse(dq)
	print('qname='..dq.qname:toString())
	print('  old_len='..dq.len)
	dq.len = 12 -- size of DNS message header
	print('  new_len='..dq.len)
	return DNSAction.None
end

addResponseAction(AllRule(), LuaResponseAction(onresponse))

newServer({address="8.8.8.8", useClientSubnet=false})
```
3. Start dnsdist up using the command `sudo ./dnsdist -C dnsdist.lua`
4. Start Wireshark and listen on the loopback interface.
5. Try to resolve www.google.com using the command `host -t a www.google.com 127.0.0.1`

### Expected behaviour
* `host` command fails because the DNS response contains only the header.
* In Wireshark, it can be seen that the DNS response only contains the header.

### Actual behaviour

* `host` command completes successfully, displaying multiple IPv4 addresses of www.google.com.
* In Wireshark, it can be seen that the DNS response was not modified, i.e. is not shortened to the size of a DNS header.

**Comment by Habbie** [comment]
Hi, dnsdist is not designed to send garbage packets. What problem are you trying to solve?

**Comment by slavc** [comment]
Hello,
I have a Lua module which modifes the contents of DNS response via the DNSQuestion.dh pointer.
After that, the DNS response is either the same size or smaller, so I need dnsdist to truncate the buffer it sends.
BTW, the setter for DNSQuestion.len does appear to be implemented: https://github.com/PowerDNS/pdns/blob/master/pdns/dnsdist-lua-bindings-dnsquestion.cc#L39

**Comment by Habbie** [comment]
Ok, but, what problem are you solving? What's the goal?

**Comment by rgacogne** [comment]
I confirm that you can set `DNSResponse.len` from `Lua` but we ignore it later in the process, as opposed to what we do with `DNSQuestion.len` for queries. We never intended to do much manipulation of answers from `dnsdist`, and in my personal opinion we are unlikely to reconsider without knowing what you are trying to achieve.

**Comment by slavc** [comment]
Basically, I need to modify the contents of DNS response, replacing the payload (i.e. everything except for the DNS header) of the message with my own payload. In my case, the resulting DNS response is either the same size as the original, or smaller, so it's never going to be larger than the original.

I _have_ to do this on dnsdist, due to having to integrate and extend existing systems, otherwise, if it were a greenfield project, I'd do it on a caching recursive resolver instead, e.g. on PowerDNS Recursor.

**Comment by phonedph1** [comment]
If you are replacing the payload completely why can't you intercept the query and re-direct it to something that can provide an appropriate response of your choosing rather than trying to mangle it on the way back?

**Comment by rgacogne** [comment]
If you don't need to intercept the response but can act on the query, https://github.com/PowerDNS/pdns/pull/8722 might be of interest to you.

**Comment by slavc** [comment]
@phonedph1 Hm, that's an interesting idea, and nice from a developer's point of view, however I think it won't fly because of the additional cost - that's one more thing that uses CPU time, needs to be deployed, monitored, maintained...

**Comment by slavc** [comment]
@rgacogne thanks - I do need to act on the response, and I cannot use any other selector/action other than `addResponseAction(AllRule(), LuaResponseAction(onresponse))` because selectors in dnsdist are static and get hard-coded in the configuration file, whereas I need to make the decision on whether and how to modify the response dynamically, based on policies which keep changing all the time, and so I make this decision in my custom Lua module.

**Comment by rgacogne** [comment]
I believe this has been fixed as a side-effect of https://github.com/PowerDNS/pdns/pull/9616.
