### ISSUE TITLE
rec: Inconsistency in logging between lua and protobuf

### ISSUE THREAD

**Issue by neilcook** [PowerDNS/pdns#8712]
- Program: Recursor
 - Issue type: Bug report

### Short description
Just a quick email to say that we're seeing an inconsistency in the PowerDNS (4.3.0 beta 2) output between lua and protobuf. When we request a domain that is listed in a whitelist RPZ, the response.appliedPolicy is not being set in the protobuf output. The lua scripting environment does appear to see the policy set, as shown by logging dq.appliedPolicy.policyName. Is it possible to confirm if this is a known and / or expected behaviour? Our assumption is that any RPZ policy matching applied and recorded in dq.appliedPolicy.policyName should also be reflected in the protobuf 'response' output.

### Environment

 - Operating system: Not sure, Centos I think
 - Software version: 4.3.0 beta2
 - Software source: PowerDNS repository

### Steps to reproduce
See above.

**Comment by rgacogne** [comment]
From a quick look at the code, I would expect the policy name to be present in the protobuf message. I have not tested, however, so I can't rule out the possibility that this is a bug.
The content of the RPZ would be useful to reproduce the issue.

**Comment by neilcook** [comment]
Will ask for the RPZ

**Comment by neilcook** [comment]
Reproduction:
Add whitelist entry for test qname in an RPZ file:  
/etc/pdns-recursor/rpz_white1:
$TTL 2h;
$ORIGIN rpz_white1.
@               SOA nsd.example.net. hostmaster.example.com ( 1 12h 15m 3w 2h)
                   NS nsd.example.net.
 test.example CNAME rpz-passthru.
 *.test.example CNAME rpz-passthru.

Enable RPZ loading and protobuf in recursor configuration:
/etc/pdns-recursor/recursor_config.lua:

rpzFile("/etc/pdns-recursor/rpz_white1", {policyName="white1"})
-- Assume pdns-logger component is co-located, listening on 4242
protobufServer('127.0.0.1:4242',
               { timeout=5,
                 maxQueuedEntries=10000,
                 reconnectWaitTime=5,
                 taggedOnly=false,
                 asyncConnect=false,
                 logQueries=false,
                 logResponses=true })

Add logging of applied-policy in LUA (preresolve)
/etc/pdns-recursor/lua_dns_script:
...
function preresolve(dq) 
    pdnslog("preresolve: " .. dq.qname:toString() .. "|" .. dq.appliedPolicy.policyName)
end
Send DNS request for test qname to pdns-recursor
dig @localhost -p 53 test.example

Check contents of triggered protobuf message, via localhost print 4242.
msg.response.appliedpolicy does not appear to be set?

Some further details as per the support website:

Platform: CentOS Linux release 7.7.1908 (Core)
Environment: Staging
Category: DNS
Product: OX PowerDNS Recursor Platform 4.3.0-beta2

**Comment by rgacogne** [comment]
Thanks, Neil! I think I know what's going on, the value is overridden when we check the filtering policies after the resolution has been completed. The `Lua` snippet is done in `preresolve` so it has not been overridden yet.
It has likely been fixed by #8705 but I'll check.

**Comment by neilcook** [comment]
Great, thanks Remi!

**Comment by rgacogne** [comment]
I can indeed reproduce the issue in 4.3.0-beta2 but it works as expected on master!

**Comment by neilcook** [comment]
Strange but good :) Can we add a regression test for this behaviour maybe?

**Comment by omoerbeek** [comment]
AFAIKS, there is a test for this case in `test_Protobuf.py ProtobufRPZTest`
