### ISSUE TITLE
Performance issues while forwarding root zone to cache DNS server

### ISSUE THREAD

**Issue by jonascrecencio** [PowerDNS/pdns#8741]
When I set the point zone (.) to be forwarded to an external cache DNS server, the requests seems to be declined by pdns due to some limits of queries.

What could be wrong?

Is It a performance related bug?

**recursor.conf**
>setuid=pdns-recursor
>setgid=pdns-recursor
>local-address=0.0.0.0:53,
>allow-from=127.0.0.0/8, 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12,
>max-cache-ttl=86400
>max-negative-ttl=5
>forward-zones-file=/etc/pdns-recursor/zones.conf

**/etc/pdns-recursor/zones.conf**
>example1.com=192.168.55.251:53,
>example2.com=192.168.55.251:53,
>.=8.8.8.8, 1.1.1.1,

**Journal log**
>pdns_recursor[18889]: Exception while performing security poll: more than 50 (max-qperq) queries sent while resolving 0.security-status.secpoll.powerdns.com

**Comment by Habbie** [comment]
>  .=8.8.8.8, 1.1.1.1,

Try `+.=8.8.8.8, 1.1.1.1,'.

Our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by mnordhoff** [comment]
> max-negative-ttl=5

**That's** not going to help performance, though.
