### ISSUE TITLE
auth API (doc issue): Retrieve all zone names and serials (edited_serial) without zone contents

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#8748]
- Program: Authoritative
 - Issue type: Feature request

### Short description
We would like to retrieve a list of all zone names and corresponding serials (edited_serial) from the pdns API, without retrieving all the record contents.

### Usecase
To extract the state of all zones, one needs all zone names and serials. This helps, for example, with the implementation of catalog zones (enriched with serials).

### Description
One way of doing this would be a query parameter to the `zones/` endpoint, like `rrsets=false` or similar. When given, the objects in the returned JSON array would not contain the `rrsets` field (and ideally, pdns would also save all the associated database queries).

A more generic way would be passing `fields` query parameter. In my usecase, I would then issue `GET .../zones/?fields=name,edited_serial`.

**Comment by Habbie** [comment]
```
$ http :8081/api/v1/servers/localhost/zones X-API-Key:nslordapikey
[
  {
    "account": "",
    "dnssec": false,
    "edited_serial": 1,
    "id": "example.net.",
    "kind": "Native",
    "last_check": 0,
    "masters": [],
    "name": "example.net.",
    "notified_serial": 0,
    "serial": 1,
    "url": "/api/v1/servers/localhost/zones/example.net."
  },
```

I don't follow - what are you missing from this?

**Comment by peterthomassen** [comment]
I actually did not try that out, but went by the documentation which says that `zones` returns a list of `Zone` objects, and those are (in the documentation) defined to contain an `rrsets` field. I turns out that it is only returned at the `zones/{id}` endpoint, not at the `zones` endpoint.

So, it's actually a documentation issue. Feel free to close if unnecessary. (I should have checked - sorry!)

**Comment by Habbie** [comment]
> So, it's actually a documentation issue.

Renamed and relabeled. Help welcome!

**Comment by peterthomassen** [comment]
#8750
