### ISSUE TITLE
pdnsutil activate-tsig-key doesn't detect non-existent zones

### ISSUE THREAD

**Issue by spheron1** [PowerDNS/pdns#8758]
- Program: Authoritative
 - Issue type: Bug report

### Short description
`pdnsutil activate-tsig-key` doesn't detect when it's called on a DNS zone which doesn't exist

### Environment

 - Operating system: Ubuntu 18.04.3 LTS
 - Software version: 4.2.1
 - Software source: PowerDNS repository

### Steps to reproduce

1. Run `pdnsutil activate-tsig-key` with a DNS zone which does not exist

### Expected behaviour

`pdnsutil activate-tsig-key` would check if the DNS zone exists and report a failure if it does not exist.

### Actual behaviour

```
~# pdnsutil generate-tsig-key testkey hmac-sha256
Create new TSIG key testkey hmac-sha256 SBFGgz2AeTn1qjqMks/Y0LqXnXx2kF9Dp8DwtlzELea2e5Uok1hZH21ZKY5jd0eBYHRu3gG2BStOisBzfQ2kzA==
~# pdnsutil activate-tsig-key example.com testkey master
Enabled TSIG key testkey for example.com
~# pdnsutil activate-tsig-key example.org testkey slave
Enabled TSIG key testkey for example.org
~# pdnsutil get-meta example.com TSIG-ALLOW-AXFR
Invalid zone 'example.com'
~# pdnsutil get-meta example.org AXFR-MASTER-TSIG
Invalid zone 'example.org'
```

**Comment by Habbie** [comment]
This feels like a duplicate but I can't find it..

**Comment by Habbie** [comment]
> This feels like a duplicate but I can't find it..

#5787 is similar, but was fixed.
