### ISSUE TITLE
Getting all records from dns question "additional section" to support dnscrypt "query_meta"

### ISSUE THREAD

**Issue by eterry1388** [PowerDNS/pdns#8759]
- Program: dnsdist
 - Issue type: Feature request

### Short description
I'd like to use `dnsdist` to read the additional section of a dns question.

### Usecase
I am using `dnscrypt`, which has a `query_meta` option that (as far as I can tell) adds to the additional section of a dns question request.  I'd like to be able to see the `query_meta` in `dnsdist`.

### Description
I have opened an issue with `dnscrypt` here: https://github.com/DNSCrypt/dnscrypt-proxy/issues/1168.  I hope between that one and this one, I can figure out what needs to be done.  I am adding this as a "feature request" as I believe it's currently not possible in `dnsdist` (based on my testing and looking through documentation).  Is `:getRecords()` what we need in `dnsdist`?  Thank you!

**Comment by rgacogne** [comment]
There is currently no way to look at any record in a DNS query in dnsdist. I'm afraid we are unlikely to add support for this regular queries don't have any records, except for the meta OPT RR.

**Comment by eterry1388** [comment]
Is there support in the PowerDNS Recursor? If so, can you point me in the right direction?

**Comment by eterry1388** [comment]
I attempted to try this:

```lua
function preresolve(dq)
  local records = dq:getRecords()
  for k,v in pairs(records) do
    pdnslog(k, v.name:toString(), v:getContent())
  end

  return false
end
```

But there was no records, even though `tcpdump` showed that there was.

**Comment by omoerbeek** [comment]
The return value of `getRecords()` only gets filled with results, not with the records from the question.
