### ISSUE TITLE
Notification failed after retries

### ISSUE THREAD

**Issue by Meigl89** [PowerDNS/pdns#8790]
Hi,

we are implementing powerdns at the moment and during our tests we faced the following scenario:

- We created entries (via powerdnsadmin) on NS01 and before that we disabled the service on NS02
- After creating some entries, we can see the following in the logfile:

> Queued also-notification of domain 'domain.com' to IP:53

But a few seconds later we received:

> Notification for domain.com to IP:53 failed after retries

If we enable the service on ns02 again, the changes will not be transmitted, only new domains, created after the service has been started.

Is there a way to trigger something to get the current versions of the zones to have a correct redundancy? 

Thanks in advance,
Michael

**Comment by Habbie** [comment]
Hello Michael,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
