### ISSUE TITLE
dnsdist docs refer to dnsdist.TYPE instead of DNSQType.TYPE

### ISSUE THREAD

**Issue by stirnim** [PowerDNS/pdns#8798]
- Program: dnsdist
 - Issue type: Bug report

### Short description
The documentation for the matching action QTypeRule() lists the built-in QTypes in the old format: "dnsdist.A, dnsdist.TXT and dnsdist.ANY". See https://dnsdist.org/rules-actions.html?highlight=addaction#QTypeRule

### Environment
 - Online documentation, https://dnsdist.org/rules-actions.html?highlight=addaction#QTypeRule

### Expected behaviour
The documentation for the matching action QTypeRule() should list the built-in QTypes in the new format such as DNSQType.A, DNSQType.TXT and DNSQType.ANY

**Comment by Habbie** [comment]
@rgacogne do you want this changed now? or when 1.5.0 is here?

**Comment by rgacogne** [comment]
It would be good to use the new format as soon as possible IMHO.
