### ISSUE TITLE
dns update across dnsdist

### ISSUE THREAD

**Issue by solune** [PowerDNS/pdns#8805]
Here is my config:
[isc-dhcp] ----dns update---->[dnsdist--->pdns authoritative]
the isc dhcp server(v4.4.2) send a dns update query with a tsig key(hmac-md5). (I see it with tcpdump/wireshark).
When the authoritative get the request, it said : "UPDATE (9470) from 127.0.0.1 for my-domain.com: TSIG key required, but packet does not contain key. Sending REFUSED"

my dnsdist config is:
```
newServer({address='127.0.0.1:5300', pool='auth'})
addAction(OpcodeRule(DNSOpcode.Update), PoolAction("auth") )
```
my authoritative config:
```
allow-dnsupdate-from=127.0.0.0/8
dnsupdate=yes
```

I miss something or there is a bug  ?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
