### ISSUE TITLE
auth: lmdb crash

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#8837]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When provisioning many slave zones on auth with lmdb backend, auth dies. (I have been using the API to create slave zones and then trigger AXFRs.)

### Environment
 - Operating system: Debian stretch
 - Software version: 4.2.1
 - Software source: PowerDNS repository

### Steps to reproduce
1. Use script to provision slave zones via API and trigger AXFR (e.g. https://github.com/desec-io/desec-slave/blob/762a71a/replicator/run.py#L127)
2. After provisioning around 14,000 zones this way, the below crash happens.

### Expected behaviour
No error

### Actual behaviour
    mdb.c:5647: Assertion 'mc->mc_flags & C_INITIALIZED' failed in mdb_cursor_next()
    Feb 18 14:18:22 Got a signal 6, attempting to print trace:
    Feb 18 14:18:22 pdns_server(+0x2bee09) [0x5617db45fe09]
    Feb 18 14:18:22 /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fb6a4b21060]
    Feb 18 14:18:22 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fb6a4b20fff]
    Feb 18 14:18:22 /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fb6a4b2242a]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/liblmdb.so.0(+0xf0e2) [0x7fb69f9090e2]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/liblmdb.so.0(+0x652e) [0x7fb69f90052e]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/liblmdb.so.0(+0x64c3) [0x7fb69f9004c3]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/liblmdb.so.0(mdb_cursor_get+0x298) [0x7fb69f8ff058]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/pdns/liblmdbbackend.so(_ZN11LMDBBackend19deleteDomainRecordsERNS_20RecordsRWTransactionEjt+0x190) [0x7fb69fb40700]
    Feb 18 14:18:22 /usr/lib/x86_64-linux-gnu/pdns/liblmdbbackend.so(_ZN11LMDBBackend16startTransactionERK7DNSNamei+0xcf) [0x7fb69fb43a9f]
    Feb 18 14:18:22 pdns_server(_ZN17CommunicatorClass4suckERK7DNSNameRK12ComboAddress+0x25af) [0x5617db48e00f]
    Feb 18 14:18:22 pdns_server(_ZN17CommunicatorClass19retrievalLoopThreadEv+0x658) [0x5617db2c8098]
    Feb 18 14:18:22 pdns_server(+0x12c019) [0x5617db2cd019]
    Feb 18 14:18:22 /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4) [0x7fb6a4e944a4]
    Feb 18 14:18:22 /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fb6a4bd6d0f]

### Other information
I tried several times, and the issue does not seem to be related to a specific zone.

What other information can I provide?

**Comment by rgacogne** [comment]
Wild guess, but Debian Stretch has LMDB 0.9.18 and this looks a bit like https://www.openldap.org/lists/openldap-bugs/201604/msg00045.html which was fixed by https://github.com/LMDB/lmdb/commit/4d2154397afd90ca519bfa102b2aad515159bd50 in 0.9.19.

**Comment by peterthomassen** [comment]
That was it - the problem went away with LMDB 0.9.21 (Ubuntu bionic).

**Comment by peterthomassen** [comment]
thanks :)

**Comment by rgacogne** [comment]
Thanks a lot for reporting the issue and confirming that an upgrade solved it!
