### ISSUE TITLE
Recursor frequently logs errors about trying to read past the end of the buffer (12 >= 12)

### ISSUE THREAD

**Issue by hrak** [PowerDNS/pdns#8861]
- Program: Recursor
 - Issue type: Bug report

### Short description
We are seeing frequent syslog entries `Trying to read past the end of the buffer (12 >= 12)` on two of our resolvers.

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.1.15-1pdns.xenial
 - Software source: PDNS repo

### Steps to reproduce
Not exactly sure what is triggering this

### Expected behaviour
no log entries about this error

### Actual behaviour
```
Feb 25 15:11:10 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:11:15 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:11:50 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:11:55 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:12:31 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:12:36 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:13:11 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:13:16 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:13:52 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
Feb 25 15:13:57 nscache4 pdns_recursor[4156]: Error processing or aging answer packet: Trying to read past the end of the buffer (12 >= 12)
```

**Comment by pieterlexis** [comment]
> Software version: 4.1.15-1pdns.xenial

Please update to 4.2 and let us know if the problem occurs there as well

**Comment by rgacogne** [comment]
My guess is an invalid header-only query, still we should not log any error for this and silently drop the packet instead. It would be good to know if this is still occurring in 4.2.x  indeed.

**Comment by rgacogne** [comment]
I can reproduce this issue on master, although in my case I need several unlikely conditions including a hash collision, but perhaps it can happen in other cases. I'll open a PR with a fix.

**Comment by omoerbeek** [comment]
👍
