### ISSUE TITLE
LMDB backend doesn't build on FreeBSD

### ISSUE THREAD

**Issue by RalfvdEnden** [PowerDNS/pdns#8872]
- Program: Authoritative
 - Issue type: Bug report

### Short description

Trying to build pdns-auth with the LMDB backend enabled caused building issues

### Environment

 - Operating system: FreeBSD 12.1-amd64
 - Software version: 4.3.0-beta2
 - Software source: PowerDNS repository

### Steps to reproduce

1. 
2. 
3. 

### Other information

Habbie supplied a patch that fixes the issue. I recall it came from his own repo.

diff --git a/ext/lmdb-safe/lmdb-safe.cc b/ext/lmdb-safe/lmdb-safe.cc
index f4874261f..c29d29147 100644
--- ext/lmdb-safe/lmdb-safe.cc
+++ ext/lmdb-safe/lmdb-safe.cc
@@ -6,7 +6,10 @@
 #include <string.h>
 #include <map>

-using namespace std;
+using std::string;
+using std::runtime_error;
+using std::tuple;
+using std::weak_ptr;

 static string MDBError(int rc)
 {

**Comment by yds** [comment]
with the above ext/lmdb-safe/lmdb-safe.cc patch, 4.3.0-beta2 w/LMDB now build on FreeBSD 12.1
