### ISSUE TITLE
missing backslashes in https://doc.powerdns.com/recursor/manpages/rec_control.1.html

### ISSUE THREAD

**Issue by setharnold** [PowerDNS/pdns#8885]
- Program: Recursor
 - Issue type: Bug report

### Short description

The manpage for rec_control is rendered without important backslashes on the website: https://doc.powerdns.com/recursor/manpages/rec_control.1.html

Note the section about tracing: 

>  In addition, since this is a regular expression, to exclusively match queries for ‘www.powerdns.com’, one should escape the dots: ‘^www.powerdns.com.$’.

**Comment by omoerbeek** [comment]
Backslashes are still eaten...
