### ISSUE TITLE
pdns Resolver tries to bind to 0.0.0.0, but why?

### ISSUE THREAD

**Issue by kommulu** [PowerDNS/pdns#8904]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I am setting up powerdns as a public dns-server for my domains and use your ansible-role for that, which works great (had to tweak it a little for CentOS 8).
PowerDNS tries to bind it's resolver to 0.0.0.0, but can not do that, because SELinux is active.
Here is my config:
```cat /etc/pdns/pdns.conf 
config-dir=/etc/pdns
setuid=pdns
setgid=pdns
allow-axfr-ips=xxxx
api=yes
api-key=xxxx
dnsupdate=no
local-address=xxxx
local-port=53
master=yes
security-poll-suffix=secpoll.powerdns.com.
slave=no
version-string=anonymous
webserver=yes
webserver-address=xxx
webserver-allow-from=xxxx
webserver-port=8081

launch=

launch+=gmysql
gmysql-dbname=xxxx
gmysql-host=xxxx
gmysql-password=xxxxx
gmysql-user=xxxxx
```

I do not really get why it even tries to bind to 0.0.0.0, as I have set specific addresses to bind to.

PowerDNS exits then with this message:
`Exiting because communicator thread died with error: Resolver binding to local UDP socket on 0.0.0.0: Permission denied`
### Environment

 - Operating system: CentOS 8
 - Software version: 4.3.0-beta2
 - Software source: PowerDNS repository

### Steps to reproduce

1. Setup PowerDNS with the provided config on CentOS 8, with SELinux active
2. Try to start PowerDNS
3. Get mentioned error

### Expected behaviour
PowerDNS binds to the configured IP's and operates normally.

### Actual behaviour
PowerDNS tries to bind to 0.0.0.0 additionally and therefor crashes because SELinux says no.

### Other information
Disabling SELinux solves the problem, but that is not an option for me.
There has to be a way to make PowerDNS stop trying to bind to 0.0.0.0

Any help is very much appreciated.

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
