### ISSUE TITLE
dnsdist: Ponder DNS over HTTP3 support

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8914]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
h2o recently added a very experimental support for HTTP3, it would be nice to see whether we can easily integrate that into dnsdist.

**Comment by rgacogne** [comment]
It is now very likely that we will ditch h2o in a future release in favor of nghttp2, let's see if adding HTTP/3 support is easier then.

**Comment by rgacogne** [comment]
Let's see how https://github.com/PowerDNS/pdns/issues/9897 goes, but if we end up selecting Quiche it looks like DoH3 will be fairly easy to add.

**Comment by Harvester57** [comment]
Hi @rgacogne, now that quiche was added in https://github.com/PowerDNS/pdns/pull/13280, do you have further plans regarding HTTP/3 support ?

Looks like Quad9 are waiting for this implementation before than can enable it for their DNS resolvers: https://www.reddit.com/r/Quad9/comments/11zio1d/comment/jdcldj5/?utm_source=share&utm_medium=web2x&context=3

Thanks !

**Comment by rgacogne** [comment]
We are currently working on DNS over HTTP/3, at this point I'm still unsure whether it will be ready for 1.9.0 final.

**Comment by rgacogne** [comment]
Implemented in https://github.com/PowerDNS/pdns/pull/13556
