### ISSUE TITLE
Service is not reloaded on systemd during %post on updates

### ISSUE THREAD

**Issue by atoomic** [PowerDNS/pdns#8922]
### Short description

the builder-support/specs/dnsdist.spec is using `%systemd_post` in the `%post` section, but unfortunately on several distro that macro does not enforce a reload of systemd.

We should consider adding `systemctl daemon-reload` on update otherwise any change to the service file will be ignored by systemd.

```
%post
...
%if 0%{?rhel} >= 7
%systemd_post %{name}.service
%endif
```

Example on CentOS7 for the macro `%systemd_post`
```
> rpm --eval "%systemd_post foo"

if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset foo >/dev/null 2>&1 || :
fi
```

### Expected behaviour
call `systemctl daemon-reload` on reload

**Comment by rgacogne** [comment]
Fixed in #8923.
