### ISSUE TITLE
Ubuntu repos not up to date for 4.3.0 version

### ISSUE THREAD

**Issue by gvecchicert** [PowerDNS/pdns#8926]
### Expected behaviour
After 4.3.0 release annoucement, binary packages from Ubuntu repos should be updated to 4.3.0 version

### Actual behaviour
Ubuntu packages are still for 4.3.0~beta2 version

**Comment by pieterlexis** [comment]
The auth is still at 4.3.0-beta2 and the recursor repositories contain the right versions (4.3.0)

**Comment by gvecchicert** [comment]
When will the auth one be updated?

**Comment by pieterlexis** [comment]
When a new version is released, somewhere in the coming weeks.

Please remember that the Auth and Recursor version numbers are independent of eachother

**Comment by gvecchicert** [comment]
Hi Pieter,

I'm really sorry, I didn't get that 4.3.0 was only for recursor.
