### ISSUE TITLE
DDNS + TSIG + MySQL backend dyn updates work only with hmac-md5 keys

### ISSUE THREAD

**Issue by Neven1986** [PowerDNS/pdns#8930]
Hello,

I'm is using 4.3.0-beta2 Auth Server with Dynamic Updates.
The problem which I have is that updates are only working with **hmac-md5** keys.

Since I haven't managed to find clear statement that only hmac-md5 is supported for dynamic updates, could somebody answer me if this is really the case or I'm missing something when using hmac-sha* keys?

`Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id:  42639
;; flags:; ZONE: 1, PREREQ: 0, UPDATE: 1, ADDITIONAL: 1
;; ZONE SECTION:
;adp.example.com.		IN	SOA

;; UPDATE SECTION:
demo1.adp.example.com. 86400	IN	A	7.16.11.122

;; TSIG PSEUDOSECTION:
dp_automation.		0	ANY	TSIG	hmac-md5.sig-alg.reg.int. 1584144145 300 16 Km93Ch3vpwDXxnqMEslcHw== 42639 NOERROR 0

update_completed()
; TSIG error with server: expected a TSIG or SIG(0)
show_message()

Reply from update query:
;; ->>HEADER<<- opcode: UPDATE, status: REFUSED, id:  42639
;; flags: qr aa; ZONE: 1, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;adp.example.com.		IN	SOA
`

Thank you in advance,
Neven

**Comment by dwfreed** [comment]
Your output indicates you're sending the signature as if the hmac-md5 algorithm was used, not hmac-sha1 or other SHA* based HMACs.  You may want to look into what is performing the TSIG signing to ensure it knows your key is meant to be used with a SHA* based HMAC function.

**Comment by Neven1986** [comment]
Thank you @dwfreed,

it seems that for some reason "nsupdate" which I use doesn't take "-y" switch into consideration.
I tried now on other 2 virtual machines and from there it works.

Sorry should do that sooner...

Thank you,
Neven
