### ISSUE TITLE
getDomainInfo method of of remote-backend not working

### ISSUE THREAD

**Issue by ordinaryorange** [PowerDNS/pdns#8931]
- Program: Authoritative (with pdns-backend enabled)
 - Issue type: Bug report

### Short description
Upon a HTTP `POST` to `api/v1/servers/localhost/zones`, pdns-backend issues a `getDomainInfo` method call, with the domain name _(e.g. 'foo.com')_ from the `POST` call.
No matter what JSON is returned to pdns-backend by my unix socket, it closes the unix socket and indicates a failure to the HTTP API, at which point a HTTP 422 error is returned to the client.

### Environment

 - Operating system: Docker Container (Debian 10)
 - Software version: PDNS Authoritive and remote-backend 4.1.6 
 - Software source: Debian Package Repo

### Steps to reproduce

1. make a `POST` request to the web API to `api/v1/servers/localhost/zones` (domain passed in `POST` body JSON is assumed not to be in the backend)
2. remote-backend sends `Initialise` method (JSON formatted) to the underlying implementation (unix connector in my case)
3. return JSON response `{"result":true}`
4. remote-backend sends `getDomanInfo` method (again JSON formatted)
5. [Docs](https://doc.powerdns.com/authoritative/backends/remote.html#getdomaininfo) are not clear as to what to return in this situation, but no matter what JSON response is returned to pdns-backend, the HTTP response to the `POST` call is a HTTP 422 error. (with varying body JSON as discussed below)

### Expected behaviour
Option 1:
If the domain is not present in the backend, then a JSON response to the `getDomainInfo` method of `{ "result": {}}` should be the most logical response. i.e. indicating that the domain as specified in `getDomainInfo` is not present in the underlying persistent storage.
After such response, a further method call by pdns-backend should then be received indicating that the domain needs to be created in the underlying persistent storage. 

Option 2:
The backend implementation discovers that such a domain does not exist, creates the record and returns a response such as `{ "result": { "zone": "foo.com" }}`

### Actual behaviour
upon sending the domain "foo.com" in the HTTP `POST` the following JSON were attempted in response to the "getDomainInfo" method.
```
{"result":{}}
{"result":""}
{"result":null}
{"result":false}
{"result":true}
{"result": {"zone":{}}}
{"result":{"zone":""}}
{"result":{"zone":null}}
{"result":{"zone":"foo.com"}}
```
All of which ultimately return the HTTP 422, and all result in pdns-backend closing the unix socket.
If the `zone` attribute is not present in the backend response, the HTTP response body is `{"error": "Key 'zone' not present or not a String"}`
If the `zone` attribute is included in the backend response, the HTTP response body is `{"error": "Domain 'foo.com.' already exists"}`
If the backend response is `{"result":false}` the HTTP response body is `{"error": "Creating domain 'foo.com.' failed"}`

### Other information
Despite setting loglevel=9 in the pdns config, nothing special is emitted. Here are the logs
```
Jan 25 00:38:34 Listening on controlsocket in '/var/run/pdns.controlsocket'
Jan 25 00:38:34 Guardian is launching an instance
Jan 25 00:38:34 Reading random entropy from '/dev/urandom'
Jan 25 00:38:34 Loading '/usr/lib/x86_64-linux-gnu/pdns/libremotebackend.so'
Jan 25 00:38:34 [RemoteBackend] This is the remote backend version 4.1.6
reporting
Jan 25 00:38:34 This is a guarded instance of pdns
Jan 25 00:38:34 UDP server bound to 0.0.0.0:53
Jan 25 00:38:34 UDPv6 server bound to [::]:53
Jan 25 00:38:34 TCP server bound to 0.0.0.0:53
Jan 25 00:38:34 TCPv6 server bound to [::]:53
Jan 25 00:38:34 PowerDNS Authoritative Server 4.1.6 (C) 2001-2018
PowerDNS.COM BV
Jan 25 00:38:34 Using 64-bits mode. Built using gcc 8.3.0.
Jan 25 00:38:34 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it according to the terms of
the GPL version 2.
Jan 25 00:38:34 Listening for HTTP requests on 0.0.0.0:8081
Jan 25 00:38:34 Doing stub resolving, using resolvers: 172.18.112.1,
192.168.1.1
Jan 25 00:38:34 Question got answered by 192.168.1.1
Jan 25 00:38:34 Could not retrieve security status update for
'4.1.6-3.Debian' on
'auth-4.1.6-3.Debian.security-status.secpoll.powerdns.com.', RCODE =
Non-Existent domain
Jan 25 00:38:34 Creating backend connection for TCP
Jan 25 00:38:34 About to create 3 backend threads for UDP
Jan 25 00:38:35 Done launching threads, ready to distribute questions
Jan 25 00:38:56 HTTP: Handling request "/api/v1/servers/localhost/zones"
Jan 25 00:38:56 Reconnecting to backend
Jan 25 00:38:57 closing socket connection
Jan 25 00:38:57 HTTP: Result for "/api/v1/servers/localhost/zones": 200,
body length: 2
Jan 25 00:38:57 HTTP: Handling request
"/api/v1/servers/localhost/statistics"
Jan 25 00:38:57 HTTP: Result for "/api/v1/servers/localhost/statistics":
200, body length: 3954
Jan 25 00:39:50 HTTP: Handling request "/api/v1/servers/localhost/zones"
Jan 25 00:39:50 Reconnecting to backend
Jan 25 00:39:50 closing socket connection
Jan 25 00:39:50 HTTP: Result for "/api/v1/servers/localhost/zones": 422,
body length: 46
```

There are a few issues here - 
1. `getDomainInfo` appears to be faulty
2. [Docs](https://doc.powerdns.com/authoritative/backends/remote.html#getdomaininfo) on `getDomainInfo` is unclear on what to return when the domain cannot be found
3. A `setDomainInfo` method is not present in the [docs](https://doc.powerdns.com/authoritative/backends/remote.html#getdomaininfo), suggesting that the pdns-backend implementation is incomplete

If you need me to test anything to help with this issue, just ask.
I'm somewhat roadblocked without some help on this .

**Comment by Habbie** [comment]
Does this code from the unittest help? https://github.com/PowerDNS/pdns/blob/master/modules/remotebackend/unittest.rb#L184

**Comment by Habbie** [comment]
> A `setDomainInfo` method is not present in the [docs](https://doc.powerdns.com/authoritative/backends/remote.html#getdomaininfo), suggesting that the pdns-backend implementation is incomplete

The pdns backend API does not have a `setDomainInfo` call.

**Comment by ordinaryorange** [comment]
Thanks for the suggestions. Some comments 
1. I've edited my original question slightly, to correct the API URL's which I misquoted, and I've clarified the HTTP response bodies better.
2. I had a look at the unit test. I tested returning exactly as they do but got the same result.
3. If the pdns backend does not have a `setDomainInfo` call (or equivalent) then I can only assume a backend implementation upon receiving a `getDomainInfo` call with a zone which is not present in the underlying storage, must then add that zone to the storage.
Whilst easily implementable, it does mean the `getDomainInfo` method has multiple purposes (i.e. retrieving zones and adding new zones)
The [backend API docs](https://doc.powerdns.com/authoritative/backends/remote.html#methods) do include some methods with names that don't start with **_get_** suggesting separation of non "getter" operations.

The [getDomainInfo docs](https://doc.powerdns.com/authoritative/backends/remote.html#getdomaininfo) say that 

> If your return value has no zone attribute, the backend will signal error

And I have confirmed this to be true in my testing.

However no matter what is returned in the `zone` attribute e.g. `""`, `"."`, `"foo.com"`, `"foo.com."` pdns-backend appears to tell the pdns HTTP API that a record was found, and the HTTP API then tells the client `{"error": "Domain 'foo.com.' already exists"}`

I cannot see any other way to tell pdns-backend that the record did not exist and has just been created in the `getDomainInfo` result schema.
So I think pdns-backend has an issue where it is incorrectly responding to a HTTP API call to "add" a new domain

**Comment by zeha** [comment]
You're really not supposed to create a zone as response to a getDomainInfo call. I'm not sure why you think that would be true.

And yes, the API might actually call getDomainInfo to see if the zone that you're creating already exists, so at that point, it shouldn't return a zone.

**Comment by dwfreed** [comment]
`{"result":false}` is the correct response to a `getDomainInfo()` when the domain doesn't exist in the backend.  Remote-backend doesn't implement `createDomain()`, which is why creating the domain fails when `{"result":false}` is the response to `getDomainInfo()` for that domain.

**Comment by ordinaryorange** [comment]
@dwfreed  you are spot on. I was just searching the code and discovered the [call](https://github.com/PowerDNS/pdns/blob/4626f43f311b2c7c40951aa0e452b40463c451a1/pdns/ws-auth.cc#L1667) from the web API. And yes, remote-backend does not implement it.

That would explain why `CreateDomain()` is not in the docs. I mistakenly thought remote-backed was a complete implementation. `CreateDomain()` is the _**"setter"**_ method I was thinking should exist.

I'd be happy to contribute, but I'm not a C guy and would have no idea how to implement this.
Whats the modus operandi of this project in terms of getting things like this resolved when one cannot help directly ?
How far off 'fully implemented' is remote-backend ?
Is it missing many other methods ?

I can offer my help with the remote-backend documentation and/or putting up my implementation for others to use, which I'd be happy to do once complete. Further adding to the pdns ecosystem.

**Comment by ordinaryorange** [comment]
@zeha yes it appears the API calls `getDomainInfo` to determine if a domain exists before proceeding. The implementation expects a `false` as a return value. Which probably is not the best approach. To me a return of `false` indicates the remote-backend implementation failed to process the call. In this case of `getDomainInfo` if the operation succeeds, but the zone simply does not exist, so a response of `"zone": {}` or `"zone": ""` seems more appropriate to delineate from a failed operation ?

**Comment by Habbie** [comment]
> I'd be happy to contribute, but I'm not a C guy and would have no idea how to implement this.

The code in remotebackend.cc is suffiently simple and repetitive that it is likely you'll find your way. Otherwise, a well-written feature request (probably one separately from this ticket which is more like a support conversation) can help a willing volunteer to solve the problem, if they feel like it.

In any case, this conversation should probably move to IRC or the mailing list. You have not reported any bugs, and the `createDomain` feature request should be another ticket, so I'm closing this one. You can find details about our IRC channel and mailng lists at https://www.powerdns.com/opensource.html
