### ISSUE TITLE
QNAME minimization appears to have problems with NSEC3 wildcard records

### ISSUE THREAD

**Issue by terryfroy** [PowerDNS/pdns#8935]
We recently upgraded our PowerDNS Recursor 4.2.1 hosts to PowerDNS Recursor 4.3.0.

Our config is very simple:

```
allow-from=::1/128
dnssec=validate
local-address=[::1]:5300
query-local-address=192.0.0.1
query-local-address6=2001:db0::1
```

dnsdist 1.4.0 runs on the same host and passes DNS queries through to the instance of PowerDNS Recursor; we use dnsdist to add DoH and DoT capabilities and blindly pass through all DNS queries straight to PowerDNS Recursor.

One of our customers has a wildcard A record in their DNS (which we also host, on PowerDNS Authoritative Server 4.2.1); the record is *.dev.cromwellstudios.co.uk and any query for an A record within that wildcard will return an RFC1918 address.

The parent domain is DNSSEC-signed and passes all checks via dnsviz.net.

A sample hostname, foo.dev.cromwellstudios.co.uk, resolves perfectly fine with PowerDNS Recursor 4.2.0 with the above configuration but stopped resolving once we upgraded to PowerDNS Recursor 4.3.0.

Digging through the changelog notes, I turned off QNAME minimization by adding the following option to the config:

`qname-minimization=no`

The wildcard record now resolves correctly on PowerDNS Recursor 4.3.0.

While I do not think there is an issue with the zone configuration itself, I include the output of 'pdnsutil show-zone cromwellstudios.co.uk' for your perusal:

```
admin@ns1 ~]# pdnsutil show-zone cromwellstudios.co.uk
This zone is owned by admin
This is a Native zone
Metadata items: 
	NSEC3PARAM	1 1 1 ab
	SOA-EDIT	INCEPTION-EPOCH
	SOA-EDIT-API	SOA-EDIT-INCREASE
Zone has hashed NSEC3 semantics, configuration: 1 1 1 ab
keys: 
<snip all the keys>
```

**Comment by mnordhoff** [comment]
FWIW, I don't have 4.3.0 installed, but I can resolve `foo.dev.cromwellstudios.co.uk` with QNAME minimization on in a recent master build, 63544077f.

(I did not try clearing the cache and doing it more than once or anything.)

**Comment by Habbie** [comment]
I also cannot reproduce the issue. Terry, can you get a trace? (`trace=yes` in recursor.conf, `--trace` on the recursor commandline, or using `rec_control trace-regex)

**Comment by Habbie** [comment]
Incidentally, your NSEC3PARAM sets the optout flag, which is quite likely not what you want - it does not really make sense outside of 'big TLD zones with few secure delegations and no wildcards'.

**Comment by omoerbeek** [comment]
Also no issues on a couple of rec 4.3.0 here with validation on. Trace much appreciated.

**Comment by terryfroy** [comment]
I cannot reliably reproduce this issue enough to be able to say that the issue is with PowerDNS Recursor; on some occasions, the wildcard hostname would resolve just fine but regular A records in a different zone, with the same NSEC3 parameters, would show the same symptoms.

As an aside, I have adjusted the NSEC3 parameters for the zone(s) to '1 0 1 ab' (which I understand from the documentation is the default when switching from NSEC to NSEC3) and I have not been able to reproduce the issue **at all** now.

I am not sure what all of this means but I am providing my findings here just in case it means something to a developer.

**Comment by omoerbeek** [comment]
Closed for lack of activity. Re-open if needed.
