### ISSUE TITLE
clarify += usage in recursor (and auth?) settings chapter

### ISSUE THREAD

**Issue by gvecchicert** [PowerDNS/pdns#8965]
From PowerDNS Recursor Settings documentation page (https://doc.powerdns.com/recursor/settings.html#forward-zones), forward-zones seems to accept only multiple domain/address pairs in a single line in order to setup multiple domains for forwarding.
From "Migrating from using recursion on the Authoritative Server to using a Recursor" documentation page (https://doc.powerdns.com/authoritative/guides/recursion.html), forward-zone recursor setting seems to accept also the format "forward-zones+=" after the first "forward-zones=" in order to setup multiple domains for forwarding.

**Comment by omoerbeek** [comment]
Done in chapter heading.
