### ISSUE TITLE
dnsdist: needs --daemon to supplement --supervised

### ISSUE THREAD

**Issue by rootwyrm** [PowerDNS/pdns#8981]
- Program: dnsdist
 - Issue type: Feature request

### Short description
The behavior of the `--supervised` flag is fundamentally incompatible with every init system save two, particularly in that it does not detach the process and continues to use stdout. dnsdist needs a `--daemon` flag that suppresses stdout and cleanly detaches after launch. Any work around for this results poorly supervised or completely unsupervised running.

### Usecase
Using dnsdist on multiple non-systemd operating systems and distributions. (e.g. AIX, FreeBSD, Alpine Linux, Docker)

### Description
`dnsdist --daemon -C ${dnsdist_config} -u ${dnsdist_user} -g ${dnsdist_group}` should spawn a dnsdist process with all stdout suppressed, which should delay exit until the security check lookup. The return status should be 0 regardless of the pass/vulnerable status, but should exit non-zero if the lookup _fails_ for any reason (e.g. SERVFAIL, timeout, etc.)

**Comment by Habbie** [comment]
On FreeBSD, running dnsdist with `/usr/sbin/daemon` [works](https://svnweb.freebsd.org/ports/head/dns/dnsdist/files/dnsdist.in?revision=525141&view=markup). In Docker, processes are expected to not daemonize themselves.

We removed the `--daemon` flag on purpose, see commit b82a127e4553c1840edc341d13ae30506a5dbc7e.

**Comment by rgacogne** [comment]
I believe a proper solution to this issue exists, so I'm closing this.
