### ISSUE TITLE
Avoid "Lua Record Exception: Script took too long" 

### ISSUE THREAD

**Issue by paddg** [PowerDNS/pdns#8990]
- Program: Authoritative
 - Issue type: Feature request or bug report, I don't know

### Short description
I'm trying to initialize a Lua state on first query. To be more precise, I'm trying to read lines of a file into a Lua table. But if this read loop is too long (> a few hundred), a Lua exception happens.

### Usecase
The goal is to have a static Lua table, which can be used to create generic RRs out of a Lua function. But if the initialization takes too long, a exception happens. It would be good, to have a possibility to prevent that exception for happening in this case.

### Description
You can reproduce the problematic behavior this way
```
config  IN      LUA     LUA        (
  " local function init()       "
  "   N = 246                   "
  "   for i=1,N do print(i) end "
  " end                         "
  " init()                      "
)

test  IN  LUA  A   ";include('config') return pickrandom({'3.3.3.3','4.4.4.4'})"
```
Tested cases:

**N=100**
It works

**N=246**
Error: `Lua record reported: [string "include('config') return pickrandom({'3.3.3.3..."]:1: Caught exception: Script took too long`

**N=1000**
Error: `Failed to load include record for LUArecord config.test.com: Exception thrown by a callback function: Trying to cast a lua variable from "string" to "NSt15__exception_ptr13exception_ptrE"`

**Comment by cmouse** [comment]
What would you expect to happen?

**Comment by Habbie** [comment]
`lua-records-exec-limit` is set to 1000 by default, you could up that - but I think you are asking if you can increase it for -only- the initialisation?

**Comment by Habbie** [comment]
Would something like a cdb database make more sense here?

**Comment by paddg** [comment]
@Habbie, I missed that `lua-records-exec-limit` setting, thanks, that helps already. But yes, only initialization takes long usually and if possible, that would be a useful feature I think.

I'm not sure whether a database makes more sense in my case. The needed Lua table would have around 100k rows and do not change frequently. So it wouldn't hurt much to re-initialize that Lua RRs each time it changes.

Also, my Linux distro (Suse Enterprise) does not provide the needed Lua cdb binding out of the box.

**Comment by Habbie** [comment]
The way `include` works right now, the table would be initialised on every query; with some minor code changes and https://doc.powerdns.com/authoritative/lua-records/index.html#shared-lua-state-model you could avoid that.

**Comment by Habbie** [comment]
(`if mytable == nil then .... init ..... end`)

**Comment by paddg** [comment]
Yes, thanks, I know. I left that out to give a simple example of the problem.

**Comment by Habbie** [comment]
Shall we close this? I don't really see a useful way to have different runtime limits for different chunks of code without changing how things work (which we might do at some point!)

**Comment by paddg** [comment]
Yes of course we can close this, thanks!
