### ISSUE TITLE
Master/Slave Replication - Connection refused

### ISSUE THREAD

**Issue by CloudyHub** [PowerDNS/pdns#9020]
Hello,
I've an issue to synchronize Supermaster with Slave, the log show issue of connection refused.

Starting AXFR of 'xxxxxxxxx' from remote xx.xx.xx.xx:53
Unable to AXFR zone 'xxxxxxxxx' from remote 'xx.xx.xx.xx' (resolver): Error connecting: Connection refused

- Program: Authoritative
- Issue type: Replication
- Operating system: Master CentOS / Slave Ubuntu
- Software version: Latest
- Software source: OS Repository

tcpdump -n 'host <Master_IP> and port 53'

IP <Slave_IP>12807 > <Master_IP>.53: 18905 SOA? <DomainName>. (29)
IP <Master_IP>.53 > <Slave_IP>.12807: 18905*- 1/0/0 SOA (92)
IP <Slave_IP>.48397 > <Master_IP>.53: Flags [S], seq 3622920061, win 64240, options [mss 1460,sackOK,TS val 2541649995 ecr 0,nop,wscale 7], length 0
IP <Master_IP>.53 > <Slave_IP>.48397: Flags [R.], seq 0, ack 3622920062, win 0, length 0

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those. When you ask for support there, please do not edit your logs or tcpdump output. We can only help you if you show us your real data.

We are closing this ticket. Comments will likely be ignored.
