### ISSUE TITLE
PowerDNS 4.1.1 Zone is not DNSSEC signed, not rectifying.

### ISSUE THREAD

**Issue by mikejohnsonjr** [PowerDNS/pdns#9021]
- Program: Authoritative
 - Issue type: Bug report

### Short description
"Zone is not DNSSEC signed, not rectifying." when querying api

### Environment

 - Operating system: Ubuntu
 - Software version: 4.1.1
 - Software source: 

### Steps to reproduce

```
>>> from powerdns_manager.models import Record
>>> zone = 'centertainment.zeal'
>>> url = 'http://157.245.3.175:8081/api/v1/servers/localhost/zones/%s/rectify' % (zone)
>>> import requests
>>> headers = {'X-API-Key':'redacted'}
>>> r = requests.put(url,headers=headers)
>>> r
<Response [422]>
>>>
```

### Expected behaviour
DNSSEC is not required for rectify-zone

### Actual behaviour
Attempt to rectify zone, got 422 error

**Comment by Habbie** [comment]
Fixed in #9183
