### ISSUE TITLE
Cannot parse SRV records

### ISSUE THREAD

**Issue by robetus** [PowerDNS/pdns#9022]
### Software 
- Program: Authoritative
 - Issue type: Bug report

Cannot parse SRV records, error:
`Parsing record content (try 'pdnsutil check-zone'): expected digits at position 8 in '100 443 mail.example.com'`

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.3.0
 - Software source: PowerDNS repository

### Steps to reproduce

`pdnsutil add-record example.net _autodiscover._tcp srv "100 443 mail.example.com"`

### Expected behaviour

SRV record added.

### Actual behaviour
Error as stated above.

### Other Information
Syntax as shown by powerdns:
`Syntax: pdnsutil add-record ZONE name type [ttl] "content" ["content"...]`

**Comment by Habbie** [comment]
From https://www.ietf.org/rfc/rfc2782.html:

```
The format of the SRV RR

   Here is the format of the SRV RR, whose DNS type code is 33:

        _Service._Proto.Name TTL Class SRV Priority Weight Port Target
```
You forgot one number. If i add it, the command works :)

**Comment by robetus** [comment]
A couple attempts with no success:

```
pdnsuser@ns23:~# pdnsutil add-record _autodiscover._tcp.example.com 3600 SRV 0 10 443 mail.example.net
Apr 11 07:22:58 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Domain '_autodiscover._tcp.example.com' does not exist
```
and
```
pdnsuser@ns23:~# pdnsutil add-record _autodiscover._tcp.example.com SRV 0 100 443 mail.example.net
Error: Unknown DNS type '0'
```

Source for the last one: https://doc.powerdns.com/authoritative/appendices/types.html#srv
Is a bind backend required for SRV records? The first attempt looks like it worked but it didn't add any record to the database.

**Comment by Habbie** [comment]
You cannot use `add-record` with the bind-backend. Your second attempt is missing quotes.

Example that works:
```
$ pdnsutil add-record example.net _autodiscover._tcp srv "50 100 443 mail.example.com"
New rrset:
_autodiscover._tcp.example.net. 3005 IN SRV 50 100 443 mail.example.com
```

Furthermore:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

**Comment by robetus** [comment]
I honestly thought this might've been a bug, sorry about that. Parsing this record can be tricky though, hopefully someone else finds use out of this. Thanks for you help.

**Comment by Habbie** [comment]
No problem, have a good weekend!
