### ISSUE TITLE
PowerDNS: gmysql-ssl

### ISSUE THREAD

**Issue by Yngve0** [PowerDNS/pdns#9023]
I need to use a Mariadb 10.3-server where TLS is required for as backend for PowerDNS 4.3.0-1pdns.bionic

The CLI-command "mysql --ssl-mode=REQUIRED" works against this database.

I have tried to add "gmysql-ssl=yes" to my pdns.local.gmysql.conf but connection is rejected with 

"Caught an exception instantiating a backend: Unable to launch gmysql connection: Unable to connect to database: Can't connect to MySQL server on 'mariadb.mydomain.local' (101)"

Where should I start digging?

**Comment by zeha** [comment]
https://mariadb.com/kb/en/operating-system-error-codes/ claims: 101 = ENETUNREACH.

However this GitHub issue tracker is for bug reports and not suitable as a support forum; I believe https://www.powerdns.com/opensource.html lists the official support contacts, i.e. IRC and mailing lists; your question is probably better helped there.
