### ISSUE TITLE
pdnsutil for RPZ

### ISSUE THREAD

**Issue by spirillen** [PowerDNS/pdns#9035]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Splited from #9032 by request from @Habbie 

### Usecase
I'm primarily using the `pdnsutil add-record zone etc.` to add new records. The pdnsutil should recognize this type of errors (See #9032 ) an perhaps recognized by any of the rpz-(clint)-ip or drop syntax.
But there is unfortunately already a bug....

### Reproduce
```
pdnsutil add-record zone "32.222.186.190.92.rpz-client-ip.rpz" CNAME "rpz-drop."
```

Now take a look in the DB and you'll see that the ending dot for the `rpz-drop` is missing. Again the rpz syntax might tricer a different check of the records added

### Reproduce
```
pdnsutil add-record zone "32.222.186.190.92.rpz-client-ip.rpz" CNAME "rpz-drop."
```

Now take a look in the DB and you'll see that the ending dot for the `rpz-drop` is missing. Again the rpz syntax might tricker a different check of the records added.

**Don't forget to see #9032 to have it all make seance**...

**Comment by Habbie** [comment]
> Now take a look in the DB and you'll see that the ending dot for the `rpz-drop` is missing. Again the rpz syntax might tricer a different check of the records added

Again, this is not a problem. We've been over this.
