### ISSUE TITLE
4.3 auth repo package does not chown /etc/powerdns/pdns.d

### ISSUE THREAD

**Issue by lpmhouben** [PowerDNS/pdns#9037]
- Program: Authoritative,
 - Issue type: Bug report

### Short description
Upgrading auth from 4.2 to 4.3 via the pdns repo does not chown /etc/powerdns/pdns.d or its contents

### Environment
 - Operating system: Debian 10 'Buster'
 - Software version: 4.3
 - Software source: PowerDNS repository at http://repo.powerdns.com/debian buster-auth-43

### Steps to reproduce

1. Install PowerDNS 4.2 or earlier from repo.
2. /etc/powerdns/pdns.d/ is created as ownership root.root
3. Upgrade repo to 4.3, then upgrade the auth server.

### Expected behaviour
/etc/powerdns/pdns.d and all files in it are chowned to pdns.pdns

### Actual behaviour
/etc/powerdns/pdns.d was not chowned.

### Other information
Discussed in IRC today around noon CET, submitting as bug issue as recommended.

**Comment by zeha** [comment]
Why is the ownership of `/etc/powerdns/pdns.d/` relevant? It's permissions are 0755, so the running pdns-server will be able to read its contents.

**Comment by zeha** [comment]
If there's something done about this, it should be restricted to upgrades **from older versions** (<= 4.3.0 I guess) - to avoid  "i reinstalled the package now and it works but it didn't before" confusion ...

**Comment by Habbie** [comment]
As per @zeha's first comment, this appears to only be a problem if the user has changed permissions from the defaults, and then upgrades from <4.3 to 4.3. I don't want to put in a blanket `chown` for the few users that have been meddling with permissions anyway.

**Comment by Habbie** [comment]
Because most people are on way newer versions now, I'm closing this.
