### ISSUE TITLE
auth: IPSECKEY support broken

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#9055]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Can't add IPSECKEY records

### Environment
 - Operating system: Ubuntu bionic
 - Software version: 4.2.1
 - Software source: PowerDNS repository

### Steps to reproduce
Record contents in this description are taken from the example in RFC 4025.

1a. Send an API request to create a record of type IPSECKEY, with "10 1 2 192.0.2.38 AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==" in the "content" field of the rrsets payload
1b. `pdnsutil add-record petertest123.dedyn.io test.petertest123.dedyn.io IPSECKEY 900 "10 1 2 192.0.2.38 AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ=="`

### Expected behaviour
As IPSECKEY support is documented (https://doc.powerdns.com/authoritative/appendices/types.html), the record should be added smoothly.

### Actual behaviour
Case 1a: "Unknown record was stored incorrectly, need 3 fields, got 5"
Case 1b: Error: Unknown DNS type 'IPSECKEY'

**Comment by zeha** [comment]
Looks like `reportOtherTypes` neglects to call `IPSECKEYRecordContent::report()`?

**Comment by peterthomassen** [comment]
The issue is still present in pdns auth 4.4.0, both via API (case 1a) and pdnsutil (case 1b). Looks like #9337 didn't fix it?

**Comment by mnordhoff** [comment]
@peterthomassen See #9919 and #9954.

**Comment by rgacogne** [comment]
Unfortunately it was broken again after that, in #8638, see https://github.com/PowerDNS/pdns/pull/9919

**Comment by Habbie** [comment]
And then please see this comment https://github.com/PowerDNS/pdns/pull/9954#issuecomment-759293903

sorry
