### ISSUE TITLE
Additional data for RPZ logging/protobuf

### ISSUE THREAD

**Issue by FrancisTurner** [PowerDNS/pdns#9058]
In order to provide details for reporting and/or troubleshooting it would be helpful if there was an option to report the actual zone record that caused an RPZ hit.

In bind syslogs you have a "via blahblah.." stanza in the log line that does this e.g.
```
17-Mar-2020 09:34:49.887 rpz: info: client 192.168.123.10#53112 (casasur.cl): rpz QNAME NODATA rewrite casasur.cl via casasur.cl.phishy.di000001.rpz.threatstop.local
```

This allows a reporting tool to look at the via section and get more information on it. It also allows troubleshooting where you (for example) discover that you were blocking *.cl instead of *.cn

For RPZ hits that work on dnames, such as in the example above, the qname is (plus or minus a *.) enough of a hint that it is relatively simple (if hacky) to identify the line with a suitable regex on the text form of the zone but this does not work at all for hits based on IP, NSIP or NSDNAME . 
e.g. if I have a hit based on NSIP a bind server tells me this
```
19-Mar-2020 09:00:45.878 rpz: info: client 192.168.123.12#55929 (peccsr.com): rpz NSIP CNAME rewrite peccsr.com via 29.120.82.251.162.rpz-nsip.phishy.di000001.rpz.threatstop.local
```

I can see no way that power dns would be able to give me the equivalent information. I've looked at the lua scripting to see if there's a way to get access to this information but as far as I can see the appliedPolicy part of the DNSQuestion object that lua scripting has access to just reports the policyName but not the line within the policy that caused the rewrite.

Ideally there would be a rpz flag that would allow this data to be output in the protobuf but it would be OK if it were an option in the DQ object so I could write a lua handler to process it.

**Comment by omoerbeek** [comment]
#9376 should fix this
