### ISSUE TITLE
Rectify via API not allowed for slave zones

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#9066]
- Program: Authoritative
 - Issue type: Bug report

### Short description

PowerDNS supports signing of slave zones. For this, slave zones need to be recitified. This works fine on incoming AXFR. If an existing slave zone is switched from unsigned to signed (signed on the PDNS slave), the zone needs to be rectified locally. This work fine with pdnsutil, but not via the REST API.

### Environment
 - Operating system: Ubuntu
 - Software version: 4.1 and trunk
 - Software source: self compiled

### Steps to reproduce
1. add a slave zone
2. add keys for the slave zone (we add them manually directly to cryptokeys table)
3. rectify via API

### Expected behaviour
Zone should be rectified

### Actual behaviour
Recitify is rejected: 
https://github.com/PowerDNS/pdns/blob/0ddde5f/pdns/ws-auth.cc#L1866

### Other information
A workaround would be to retransfer the zone, but this is unreliable as the master may not be available when DNSSEC is enabled for this zone.

**Comment by zeha** [comment]
Possible fix in #9183.
