### ISSUE TITLE
Publish Swagger API spec through built-in web server

### ISSUE THREAD

**Issue by bootc** [PowerDNS/pdns#9074]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Please register a web handler that returns the Swagger API spec with the `host` and `schemes` keys set correctly.

### Usecase
It's great that there is a usable Swagger API spec available, but consuming it with some client libraries is quite hard: I have to keep a local copy of the file, load it, override the `host` and `schemes` to point at my endpoint, then "connect". Many clients (such as [Bravado](https://github.com/Yelp/bravado#example-with-basic-authentication)) work best if the spec is published - just supply authentication and the spec URL and off you go.

### Description
Publish a JSON web server endpoint (at e.g. `/api/v1/swagger.json`) that returns a JSON-encoded version of the contents of `docs/http-api/swagger/authoritative-api-swagger.yaml` that corresponds to the current build of PowerDNS.

**Comment by Habbie** [comment]
#8911

**Comment by bootc** [comment]
Ah apologies I didn't find that PR before. Glad to see it in the pipeline!
