### ISSUE TITLE
dnsdist: in metrics, frontend label has wrong IPv6 formatting

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#9075]
- Program: dnsdist
 - Issue type: Bug report

### Short description
`addLocal("[::]:53")` leads to metrics like `dnsdist_frontend_queries{frontend=":::53",...}`

### Environment
 - Operating system: Ubuntu
 - Software version: 1.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
trivial

### Expected behaviour
`dnsdist_frontend_queries{frontend="[::]:53"}`

### Actual behaviour
see above

**Comment by rgacogne** [comment]
I believe we should change this but I'm a bit reluctant to do that now that 1.5.0 reached the release candidate state, I think I'll change that in 1.6.0.
