### ISSUE TITLE
auth: Please avoid installing .la files

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#9086]
- Program: Authoritative
 - Issue type: Feature request

### Short description

Currently `make install` installs these libtool files:

- usr/lib/x86_64-linux-gnu/pdns/librandombackend.la
- usr/lib/x86_64-linux-gnu/pdns/libremotebackend.la
- usr/lib/x86_64-linux-gnu/pdns/libldapbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libpipebackend.la
- usr/lib/x86_64-linux-gnu/pdns/libgeoipbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libtinydnsbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libgodbcbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.la
- usr/lib/x86_64-linux-gnu/pdns/liblmdbbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libbindbackend.la
- usr/lib/x86_64-linux-gnu/pdns/libgsqlite3backend.la
- usr/lib/x86_64-linux-gnu/pdns/libgpgsqlbackend.la

As newer versions of debhelper complain about files installed into the temporary install directory, but not into the final packages, I've now added a `find ... -delete` hack, but it'd be nicer if `make install` wouldn't install these files in the first place.

### Usecase

Easier downstream packaging.

**Comment by Habbie** [comment]
via https://stackoverflow.com/questions/7104494/building-so-module-with-autotools-libtool-without-la-and-a-variants-being-ins :

> The Debian/Ubuntu packagers have decided to exclude .la files from their packages because the second reason isn't appropriate on Linux and they would prefer you didn't build static binaries in the first place. On other platforms, which libtool is designed to support, the .la files may be needed for linking or running the program.

so, I'm not sure we should drop them?

**Comment by zeha** [comment]
Nothing ever wants to link against those .so libs. They are "plugins" after all. This is true across all platforms.

I don't see what the .la files could do for pdns_server when loading the .so's (on non-Linux), but I wouldn't know either.

**Comment by Habbie** [comment]
I found the source of my confusion about libtool and `dlopen` in 306e0ce0b03eeb3fb855fb7de815cbbd5342e7da - so, I now agree, the .la files can go. However, I don't yet know how to prevend their installation.

**Comment by zeha** [comment]
See #1590, where we all agreed this can be a downstream problem for now.

Maybe, in a far distant future, when libtool isn't a thing anymore, this solves itself.
