### ISSUE TITLE
Not accepting \; in TXT records

### ISSUE THREAD

**Issue by nlmark** [PowerDNS/pdns#909]
When adding a TXT record to a domain and after that trying to get it using dig TXT <name> it returns SERVFAIL if the TXT record in the MySQL database (gmysql backend) has a \; in it. The information below is how I confirmed this was the problem (domain name is replaced with example.net). The DKIM key is also altered and a part is replaced with YYY (per Y 1 character).

With "\;" in the database:
shell# dig TXT api._domainkey.example.net

; <<>> DiG 9.8.1-P1 <<>> TXT api._domainkey.example.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45357
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api._domainkey.example.net.  IN      TXT

;; Query time: 241 msec
;; SERVER: 91.199.167.10#53(91.199.167.10)
;; WHEN: Sat Jul 13 11:59:00 2013
;; MSG SIZE  rcvd: 46

After replacing "\;" in the database with ";":
shell# dig TXT api._domainkey.example.net

; <<>> DiG 9.8.1-P1 <<>> TXT api._domainkey.example.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23925
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api._domainkey.example.net.  IN      TXT

;; ANSWER SECTION:
api._domainkey.example.net. 900 IN    TXT     "v=DKIM1\;k=rsa\;g=*\;s=email\;h=sha1\;t=s\;p=MIGfMA0GCSqGSIb3DQEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYg1aUAoi8TJgxq2MJqCaMyj5kAm3Fdy2tzftPCV/lbdiJqmBnWKjtwIDAQAB"

;; Query time: 72 msec
;; SERVER: 91.199.167.10#53(91.199.167.10)
;; WHEN: Sat Jul 13 12:00:27 2013
;; MSG SIZE  rcvd: 314

**Comment by Olesya1985** [comment]
Hello, can you please help to fix this bug in 2.9? We can't upgrade now due to internal limitations(have to migrate to Centos6 first).

**Comment by Habbie** [comment]
I'm sorry, we are not going to do that - please read https://blog.powerdns.com/2015/05/22/powerdns-2-x-end-of-life-statement/

**Comment by Olesya1985** [comment]
Ok, thank you

**Comment by Olesya1985** [comment]
One more question - 3.3 could not be installed on Centos 5?

**Comment by Habbie** [comment]
Hi, this is not a support forum, please try the mailing list or IRC.

**Comment by Olesya1985** [comment]
Understood, thanks again.
