### ISSUE TITLE
missing definition for column "published" in table "domains" 

### ISSUE THREAD

**Issue by paulgiordano** [PowerDNS/pdns#9094]
The modules\xxxx\xxxxbackend.cc refer to column "published" which is not in the schema definition, nor is there a schema change registered to add the column.

**Comment by jsoref** [comment]
afaict `published` is on `cryptokeys`, can you point to a place where it's being pulled from `domains`?

https://github.com/PowerDNS/pdns/commit/3391829938b4544a59c93c4734532ce2fdc311bf#diff-9e876ee3939f228eeb7d22ee7c6225f8R135

**Comment by mnordhoff** [comment]
(N.b. most of the .sql files have been modified since 3391829938b4544a59c93c4734532ce2fdc311bf. If you're doing something, use the current ones, not the original ones from that commit.)

**Comment by paulgiordano** [comment]
In the modules/gsqlite3backend/gsqlte3backend.cc, for example, there's "list_domain_keys_query" line 131. This is live on the powerdns repo's.

**Comment by jsoref** [comment]
>    declare(suffix, "list-domain-keys-query","", "select cryptokeys.id, flags, active, published, content from domains, cryptokeys where cryptokeys.domain_id=domains.id and name=:domain");

`published` comes from `cryptokeys`

https://github.com/PowerDNS/pdns/blob/master/modules/gsqlite3backend/schema.sqlite3.sql#L72-L77

**Comment by Habbie** [comment]
Hello Paul,

we have an issue template, that asks important questions such as 'What did you do' and 'What happened' and 'What did you expect to happen instead'. Next time, please use the template so we know what your actual problem is!
