### ISSUE TITLE
secpoll.powerdns.com can't be resolved

### ISSUE THREAD

**Issue by Flip76** [PowerDNS/pdns#9098]
In my syslog I can see entries like:

May 12 08:33:35 openhab pdns_recursor[3258]: Exception while performing security poll: more than 50 (max-qperq) queries sent while resolving secpoll.powerdns.com

Has secpoll.powerdns.com been removed?

**Comment by cmouse** [comment]
No, it's there. Can you provide your config? You are hitting max-qperq limit.

**Comment by Flip76** [comment]
Sure, my recursor.conf:

```
allow-from=127.0.0.0/8, 192.168.2.0/24
daemon=no
forward-zones-recurse=test.domain.com=127.0.0.1:5300
forward-zones-recurse+=8.2.168.192.in-addr.arpa=127.0.0.1:5300
forward-zones-recurse+=.=192.168.2.1
forward-zones-recurse+=in-addr.arpa=192.168.2.1
local-address=127.0.0.1
local-port=53
log-common-errors=yes
serve-rfc1918=no
```

```
[09:18:49] # nslookup secpoll.powerdns.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
*** Can't find secpoll.powerdns.com: No answer

```

```
[09:19:01] # ping secpoll.powerdns.com
ping: secpoll.powerdns.com: No address associated with hostname

```

Also tried it through different VPNs but I can't get the domain resolved...

**Comment by pieterlexis** [comment]
> `forward-zones-recurse+=.=192.168.2.1`

That nameserver is probably tripping.

I am closing this issue at it appears a support question and not a bug or issue. If you require further support, please post your issue with all configuration information and logs to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).

**Comment by Flip76** [comment]
I don't think that the ns 192.168.2.1 is tripping... Just tried it on my phone (on mobile coverage, no VPN - just pure mobile data):

** server can't find secpoll.powerdns.com
NXDOMAIN

**Comment by pieterlexis** [comment]
There is no A or AAAA record for secpoll.powerdns.com. But you should get NODATA, not NXDOMAIN. But as stated before: this is a local config or network problem, not a bug. Please use the channels provided for support.
