### ISSUE TITLE
no remote-ip-address passed to backend pipe

### ISSUE THREAD

**Issue by vonHerman** [PowerDNS/pdns#9108]
Hi, 

I recently migrated from PowerDNS 4.0 to 4.1 and the fact that suprised me was that remote-ip-address is no longer properly passed to backend pipe script. It seems that now PowerDNS server always returns 0.0.0.0 no matter which api-version I am using. I have already tried version 4.1.0 and 4.2.1 with the same result no matter the ABI version I use.

**Comment by Habbie** [comment]
Hello,

can you please redo this ticket using the appropriate `.md` template from https://github.com/PowerDNS/pdns/tree/master/.github/ISSUE_TEMPLATE ? Thanks!

(Doing so should cause you to show your config, your backend script, the requests you saw with 4.0, and the requests you are seeing with 4.1)

**Comment by vonHerman** [comment]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I recently migrated from PowerDNS 4.0 to 4.1 and the fact that suprised me was that remote-ip-address is no longer properly passed to backend pipe script. It seems that now PowerDNS server always returns 0.0.0.0 no matter which api-version I am using. I have already tried version 4.1.0 and 4.2.1 with the same result no matter the ABI version I use.

### Environment

 - Operating system: Ubuntu 18.04, Ubuntu 20.04
 - Software version: PowerDNS 4.1.0, PowerDNS 4.2.1
 - Software source: official Ubuntu repo

### Steps to reproduce
1. configure pipe-command to any type of backend pipe (already tried with perl and python) but any would do. You can add something like 'print STDERR "$ip\n"; ' to the example from: https://doc.powerdns.com/authoritative/backends/pipe.html
2. make request to the server
3. check the syslog

### Expected behaviour
In case of ABI version 1 6th element should contain IP address of the requesting machine 

### Actual behaviour
the string passed to pipe script always contains '0.0.0.0'

**Comment by vonHerman** [comment]
i'll close the this report and open the new one, just to keep things cleean

**Comment by Habbie** [comment]
> i'll close the this report and open the new one, just to keep things cleean

thanks - for future reference, there is an edit button!
