### ISSUE TITLE
LetsEncrypt certificate validation

### ISSUE THREAD

**Issue by sebastiannielsen** [PowerDNS/pdns#9110]
- Program: Authoritative
 - Issue type: Feature request

### Short description
A suggestion to ship this little script I made with the main distribution, for LetsEncrypt certificate provisioning.
It could possible be tied-in with the certbot distribution as a plugin by modifying the script, but currently, the pdns-certbot script is self-contained.

### Usecase
DNS-01 validation in LetsEncrypt

### Description
https://github.com/sebastiannielsen/pdns-certbot

It uses the pipe configuration option along with a regex, to have pdns-certbot only respond on DNS queries for _acme-challenge.* , while still hybrid-signing it with DNSSEC.

The good thing with the script is that it uses a simple text file to communicate with powerDNS, while still having the scope of the text file very limited (only valid for DNS requests starting on _acme-challenge.).
It uses short cache times (4 seconds) to avoid that it caches and/or issues wrong challenge responses,

The downside is that it doesn't care about for which domain the challenge response is valid for, so it simply issues all responses for all domains, making the script both simpler and less resource intensive. This of course means its only suitable for small setups where the letsencrypt installation has 60 domains or less per run.

**Comment by Habbie** [comment]
Hello Sebastian,

if we ship it, we need to maintain it, and we would rather not do that. Our (under-advertised) GitHub wiki would be a good place; we can think about something in the docs to point there perhaps.

**Comment by Prototik** [comment]
DNSUPDATE (aka rfc2136) works like a charm in my case, it supported by almost every acme client with dns-01 validation. I don't see any reason to include any other solution for this,

**Comment by sebastiannielsen** [comment]
@Prototik I would say that I wouldn't recommend DNSUPDATE for situations where the DNS server and the certificate requester is present on the same machine. In that case, its more secure to do the communication internally, without resorting to any form of sockets or TCP/UDP communication.

**Comment by Habbie** [comment]
We would, in fact, recommend DNSUPDATE there.

I have now looked at your script and I see it involves launching two backends. This is not a recommended setup (the docs should be clearer about that).

Please feel free to still put a link on the wiki. Closing this ticket!
