### ISSUE TITLE
rec: trace=fail setting isn't in RST docs

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#9132]
- Program: Recursor
 - Issue type: Bug report

### Short description
The C++ config documentation describes `trace` as such:

https://github.com/PowerDNS/pdns/blob/5e71c4330b31ca90c7d6fe7ee673d2095d8ffe02/pdns/pdns_recursor.cc#L4873

The RST docs describe it as a bool:

https://doc.powerdns.com/recursor/settings.html#trace

So one includes the `fail` value and one doesn't.

Glancing at the code, the `fail` setting does seem to exist. Is it deprecated? Should it be documented? Should there be a warning about using it or something?

**Comment by omoerbeek** [comment]
The `trace=fail` mode does work, but its use is limited. Only if the resolve itself causes a `ServFail` the trace is printed. On a DNSSEC validation failure or other failure the trace is not printed.

It is also a relatively expensive mode, since each query will collect trace information that is discarded in almost all cases.

So I'm inclined to say we start to deprecating this trace mode.

**Comment by setharnold** [comment]
This came from a conversation on IRC. I don't understand DNS well enough to clearly state the problem, and it also involved user misconfiguration, which complicates things.

My understanding is the recursor got a bogus response, cached that, and then failed resolutions that needed that information, and started returning SERVFAIL.

Turning on trace at this point missed the actual cause of the problem, which wasn't logged.

Spending some cpu time to filter what gets logged feels useful to me. I've gotten the impression the vast majority of dns recursors are quite bored and have very little to do.

Logging everything all the time is probably too much. Probably typical users wouldn't know where to start to find problems. But if the software could be configured to log the errors, as they happen, it's possible the misconfiguration would have been easier to spot.

Thanks

**Comment by omoerbeek** [comment]
You'd be surprised how much work collecting trace information can be compared to do the "real" work...
I'm still undecided if we should deprecated `trace=fail` and remove it later or document it with a very clear warning about performance impact.

**Comment by setharnold** [comment]
If the tracing framework is going to remain regardless of `trace=fail`, then I'd like to suggest keeping `trace=fail` and document the performance problem it brings along. If removing `trace=fail` allows code clean-ups, well, I can appreciate that.
