### ISSUE TITLE
recursor: records exported via export-etc-hosts=yes return NXDOMAIN after a request to a forwarded zone

### ISSUE THREAD

**Issue by jjakob** [PowerDNS/pdns#9136]
- Program: Recursor
 - Issue type: Bug report

### Short description
Zones from /etc/hosts when using 'export-etc-hosts=yes' return NXDOMAIN after a request for any valid zone that gets forwarded via forward-zones-recurse. Requests for the entry from /etc/hosts return NXDOMAIN after that until recursor is restarted.

### Environment

 - Operating system: Debian Buster
 - Software version:  4.2.1-1pdns.buster
 - Software source: http://repo.powerdns.com/debian buster-rec-42 main

### Steps to reproduce
1) restart pdns-recursor
```
foo@bar# sudo systemctl restart pdns-recursor
```
2) test the hosts entry - works as expected
```
foo@bar# dig @10.183.1.1 filesvr.lekgp

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @10.183.1.1 filesvr.lekgp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22110
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;filesvr.lekgp.			IN	A

;; ANSWER SECTION:
filesvr.lekgp.		86400	IN	A	10.183.1.21

;; Query time: 12 msec
;; SERVER: 10.183.1.1#53(10.183.1.1)
;; WHEN: Wed May 20 23:24:02 CEST 2020
;; MSG SIZE  rcvd: 58
```
3) do a request for google.com
```
foo@bar# dig @10.183.1.1 google.com

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @10.183.1.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50198
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		67	IN	A	216.58.214.238

;; Query time: 20 msec
;; SERVER: 10.183.1.1#53(10.183.1.1)
;; WHEN: Wed May 20 23:24:08 CEST 2020
;; MSG SIZE  rcvd: 55
```
4) do a request for the entry from /etc/hosts again - it returns NXDOMAIN
```
foo@bar# dig @10.183.1.1 filesvr.lekgp

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @10.183.1.1 filesvr.lekgp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58726
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;filesvr.lekgp.			IN	A

;; AUTHORITY SECTION:
.			955	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2020052001 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 10.183.1.1#53(10.183.1.1)
;; WHEN: Wed May 20 23:24:09 CEST 2020
;; MSG SIZE  rcvd: 117
```

#### Configuration:
/run/powerdns/recursor.conf
```
### Autogenerated by dns_forwarding.py ###

# XXX: pdns recursor doesn't like whitespace near entry separators,
# especially in the semicolon-separated lists of name servers.
# Please be careful if you edit the template.

# Non-configurable defaults
daemon=yes
threads=1
allow-from=0.0.0.0/0
log-common-errors=yes
non-local-bind=yes
query-local-address=0.0.0.0
query-local-address6=::

# cache-size
max-cache-entries=10000

# negative TTL for NXDOMAIN
max-negative-ttl=3600

# ignore-hosts-file
export-etc-hosts=yes

# listen-on
local-address=10.183.1.1

# dnssec
dnssec=log-fail

# forward-zones / recursion
#
# statement is only inserted if either one forwarding domain or nameserver is configured
# if nothing is given at all, powerdns will act as a real recursor and resolve all requests by its own
#
forward-zones-recurse=.=77.111.1.1;77.111.1.77
```

/etc/hosts
```
### Autogenerated by VyOS ###
### Do not edit, your changes will get overwritten ###

# Local host
127.0.0.1       localhost
127.0.1.1       rt-lekgp.lekgp rt-lekgp

# The following lines are desirable for IPv6 capable hosts
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

# From DHCP and "system static host-mapping"
10.183.1.21	filesvr.lekgp	
10.183.1.1	router.lekgp	 router  ntp  ntp.lekgp 
```

### Expected behaviour
The requests for entries from /etc/hosts don't stop working after a request for google.com.

### Actual behaviour
The entries from /etc/hosts return NXDOMAIN.

### Other information
Adding `root-nx-trust=no` has no effect.
Adding a NTA via `lua-config-file` with `addNTA("lekgp", "A comment")` fixes it.

**Comment by rgacogne** [comment]
I believe this is the expected behaviour. With DNSSEC validation enabled we need to request the DS for `lekgp.` during the resolution process, and in doing so we learn from the root that this name doesn't exist. We could pick that up immediately and return `NXDOMAIN` the first time already but this is an edge case caused by forwarding everything to a different resolver, which prevents us from getting a `AA=1` answer. That's why the `NXDOMAIN` answer is only sent for the second query and those that come after, I don't think the `google.com` query is needed.
Adding a `NTA` prevents DNSSEC validation and therefore the need to fetch the `DS`, thus we never learn that the name doesn't exist. In my opinion this is the right way to handle that case.

I have to add that forwarding everything except for a few names to a different resolver is a very weird setup, meaning that you are not doing any recursion in the recursor. I'm not sure what the exact use-case is, but it might be better handled with dnsdist, for example.
