### ISSUE TITLE
rec: query for DS . returns Servfail

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#9144]
- Program: Recursor
 - Issue type: Bug report

### Short description
Queries for 'DS .' get a Bogus result.

### Environment
 - Operating system: Debian Buster amd64
 - Software version: git master @ 89dded66af94fea626a6b32efdbb18ba53f22c3d
 - Software source: `make`

### Steps to reproduce
1. run recursor with `dnssec=validate`
2. ask it for `DS .`

### Expected behaviour
NODATA+ad bit.

### Actual behaviour
Servfali!

### Other information
`May 25 13:52:58 [1] The DS for . is signed by itself, going Bogus`

**Comment by rgacogne** [comment]
FWIW, 8.8.8.8 also goes Servfail from here. 1.1.1.1 returns a NODATA without the AD bit set.

**Comment by mnordhoff** [comment]
9.9.9.11 (BIND) returns NODATA **with** the AD bit set.

OpenDNS also returns SERVFAIL.

So there's precedent for pretty much literally anything. :-)

**Comment by Habbie** [comment]
>  1.1.1.1 returns a NODATA without the AD bit set.

1.1.1.1 gives me either AD=1 NODATA (presumably Unbound) or Servfail (presumably PowerDNS).
