### ISSUE TITLE
make clean does not bring back original state of unpacked tarball

### ISSUE THREAD

**Issue by Zugschlus** [PowerDNS/pdns#915]
Gist https://gist.github.com/Zugschlus/5995727 shows me
- unpacking pdns 3.3 tar.gz
- checking in the resulting directory into a new git
- ./configure --with-modules='' --with-dynmodules='' --without-lua --enable-unit-tests
- make
- make clean
- git status

the resulting git status shows gazilions of .deps directories and Makefiles that have not been properly cleaned up by make clean.

Usually, make clean is expected to bring the source tree back into a pristine state. It would be great if PowerDNS would do things that way.

**Comment by omoerbeek** [comment]
Please re-open if you still have issues.
