### ISSUE TITLE
rec: CNAME to self from cache doesn't instantly give up

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#9153]
- Program: Recursor
 - Issue type: Bug report

### Short description
When the Recursor encounters a self-referential CNAME (www.example.com. IN CNAME www.example.com.), when it's fresh, it immediately detects the condition, logs "status=got a CNAME referral to self, returning SERVFAIL" and returns SERVFAIL.

When the CNAME is from the cache, it keeps trying, eventually reaches the max depth, gives up, and returns SERVFAIL.

This doesn't do much harm, except for using some CPU cycles, putting the CNAME in the response 8 times, and polluting your logs if you have tracing on.

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: 4.4.0~alpha1+master.127.gbcbc0a729-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce
[Edit: The domain was fixed, so this no longer reproduces it.]
1. `dig www.les-play.com`
2. `dig www.les-play.com`

(My version of dig has cookies, so it bypasses the packet cache.)

### Expected behaviour
Immediate SERVFAIL, 0-1 CNAME records in response.

### Actual behaviour
More complicated processing, 8 CNAME records in response.

### Other information
`trace-regex 'les-play\.com\.$'` log: https://mn0.us/nET3XYU21r-_BZ8Z_GnrHfu/syslog.txt (2 MB, 14,000 lines)

```
$ dig www.les-play.com

; <<>> DiG 9.17.1-1+ubuntu16.04.1+isc+3-Ubuntu <<>> www.les-play.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 51869
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.les-play.com.              IN      A

;; ANSWER SECTION:
www.les-play.com.       300     IN      CNAME   www.les-play.com.

;; Query time: 39 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon May 25 15:46:26 UTC 2020
;; MSG SIZE  rcvd: 59

$ dig www.les-play.com

; <<>> DiG 9.17.1-1+ubuntu16.04.1+isc+3-Ubuntu <<>> www.les-play.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 29388
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.les-play.com.              IN      A

;; ANSWER SECTION:
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.
www.les-play.com.       293     IN      CNAME   www.les-play.com.

;; Query time: 1983 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon May 25 15:46:35 UTC 2020
;; MSG SIZE  rcvd: 157
```

(It takes about 6 ms when trace-regex is off.)

**Comment by freewood** [comment]
Hello. I am not sure, but I think I have a similar bug with recursor version 4.3.1
Some queries for outlook.office.com returns SERVFAIL. Trace shows that recursor interrupt resolving because of too deep recursion: "recursing (CNAME or other indirection) too deep, depth=19"
max-recursion-depth set in default - 40.
[Here](https://pastebin.com/LVMK8rd4) is end of trace output, cannot paste it whole because it contains 25000 lines, but I can send it if needed.
So there is questions. Is it a similar bug, is it a bug at all, should I create new issue?
Thank you.

**Comment by mnordhoff** [comment]
This issue is about how the Recursor processes CNAME loops, like if Microsoft had:

```
outlook.office.com.     60      IN      CNAME   outlook.office.com.
```

(Which they don't.)

Your problem is orthogonal -- Microsoft doesn't have a loop, their setup is just excessively complicated.

The ideal solution to your problem would be for Microsoft to simplify their stuff. You could create a new issue requesting that the PowerDNS team increase the default depth limit, catering to Microsoft's questionable behavior, but I don't know how they would respond.

**Comment by mnordhoff** [comment]
pieterlexis noticed that this issue also applies to longer CNAME loops.

When fresh, they're inefficient.

When cached, they're even more inefficient!

**Comment by mnordhoff** [comment]
FWIW, I put up a CNAME loop at `cname-loop.mattnordhoff.net` for now. It's **not** a self-referential CNAME because that's scary.

**Comment by omoerbeek** [comment]
Thanks, made one myself as well;-)... Working on a fix. I looks like we want to throw an exception  since returning `ServFail` isn't picked up in some cases, related to the comment I added in `doResolveNoQNameMinimization()` near the `doCNAMECacheCheck()` call.
