### ISSUE TITLE
addLocal fails for IPv6 link-local address

### ISSUE THREAD

**Issue by mnejedlo-tds** [PowerDNS/pdns#9158]
- Program: dnsdist
 - Issue type: Bug report

### Short description

When the IP address passed to addLocal() is an IPv6 link-local address, startup fails with an "Invalid argument" error.  Explicitly specifying the interface parameter to addLocal() does not fix the problem.

### Environment

 - Operating system: Linux (RedHat Enterprise 7.4)
 - Software version: 1.4.0
 - Software source: PowerDNS repository

### Steps to reproduce

1. addLocal("fe80::250:56ff:feae:4fe8") in dnsdist.conf
2. (attempt to) start dnsdist

### Expected behaviour

dnsdist starts up, listening on specified link-local IPv6 address

### Actual behaviour

dnsdist fails to start, with the error "Fatal error: binding socket to [fe80::250:56ff:feae:4fe8]:53: Invalid argument"

### Other information

addLocal() for IPv6 addresses that are not link-local works as expected, with or without the interfaces parameter.
 
I tried adding the interface (i.e. "{interface=ens192}") parameter to addLocal() with the link-local address, but that did not fix the problem.

I looked at strace, and found that sin6_scope_id was set to 0 (default/unspecified), when it needs to be an explicit scope for a link-local address.  Adding "{interface=ens192}" to addLocal did not cause sin6_scope_id to be set correctly.
`socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 21
setsockopt(21, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
setsockopt(21, SOL_IP, IP_FREEBIND, [1], 4) = 0
bind(21, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "fe80::250:56ff:feae:4fe8", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)
futex(0x7f52133b9190, FUTEX_WAKE_PRIVATE, 2147483647) = 0
sendto(4, "<27>May 26 20:05:17 dnsdist[6494]: Fatal error: binding socket to [fe80::250:56ff:feae:4fe8]:53: Invalid argument", 113, MSG_NOSIGNAL, NULL, 0) = 113`

When I searched the dnsdist code for sin6_scope_id I only found it referenced in two places, and in both cases it is explicitly set to 0.

I'm not totally certain that sin6_scope_id is the fundamental problem though, as the ipv6(7) man page documents the error for invalid sin6_scope_id as ENODEV, but strace shows the error as EINVAL.  Perhaps EINVAL is used when sin6_scope_id=0, since 0 is a valid scope id but useless in this circumstance.

Dnsdist should at minimum use the interface parameter to set sin6_scope_id (any time the interface parameter is present, regardless of if the IPv6 address is link-local).

In an ideal world, dnsdist would search available interfaces for the specified IPv6 address and set sin6_scope_id accordingly, only failing when the IP in question appeared on none or multiple interfaces (In the multiple interfaces case, the argument could be made for binding on all interfaces where the IP appears)

**Comment by TimStallard** [comment]
Specifying an interface with the `%` syntax works OK here (on 1.5.0~rc1-1pdns.buster, on a debian buster machine):
```
$ grep fe80 /etc/dnsdist/dnsdist.conf
setLocal("fe80::1%eth0.3")
$ sudo ss -tuplen | grep dnsdist
udp   UNCONN 0      0                [fe80::1]%eth0.3:53              [::]:*     users:(("dnsdist",pid=29607,fd=4)) uid:108 ino:253083454 sk:31 v6only:1 <->    
tcp   LISTEN 0      128              [fe80::1]%eth0.3:53              [::]:*     users:(("dnsdist",pid=29607,fd=11)) uid:108 ino:253083455 sk:32 v6only:1 <->   
```
May be worth testing on your version?

**Comment by mnejedlo-tds** [comment]
Forgot to put in my troubleshooting notes, in addLocal() I also tried putting the interface into the IPv6 address field using % and @ notation (i.e. 'addLocal("fe80::250:56ff:feae:4fe8@ens192")'), but that failed as well with `Fatal Lua error: [string "chunk"]:1: Unable to convert parameter from userdata to Ss`

**Comment by Habbie** [comment]
Can you show the full error from an attempt with `%`?

**Comment by Habbie** [comment]
> In an ideal world, dnsdist would search available interfaces for the specified IPv6 address and set sin6_scope_id accordingly, only failing when the IP in question appeared on none or multiple interfaces (In the multiple interfaces case, the argument could be made for binding on all interfaces where the IP appears)

This is not a valid approach - the same link local address could exist on multiple interfaces (like in @TimStallard's example with `fe80::1`)

**Comment by mnejedlo-tds** [comment]
I swear I tested the % syntax yesterday, but it just worked for me now.

I acknowledged the multiple interfaces case in the text quoted and suggested either binding on all interfaces where the IP was configured (preferred), or failing only when multiple interfaces are found for that IP.  Finding all interfaces where an link-local IP is defined is definitely possible.

At bare minimum, a documentation fix is needed for the % syntax, and I strongly feel that it should do the right thing when passed the interface parameter.  What to do when with a link-local address when no interface is specified is a place where reasonable people can disagree, but I think auto detecting which interfaces are available for that IP is the most user-friendly option.

**Comment by Habbie** [comment]
You're right, I managed to ignore the bit between (), sorry.

**Comment by rgacogne** [comment]
I added an example of IPv6 link-local address to the documentation in https://github.com/PowerDNS/pdns/pull/12532
I also tested why setting up the interface name via the ``interface`` parameter did not work, but it turns out to be working for me (ie, IPv6 link-local address works with something like: `addLocal("fe80::1", { interface="eth0" })`) with dnsdist 6f61219ccb99e16f188c2a166dee70f28f0abb62 on Linux 6.1.10.
