### ISSUE TITLE
Cannot resolve hostname downloadirpf.receita.fazenda.gov.br

### ISSUE THREAD

**Issue by ploquets** [PowerDNS/pdns#9161]
I don't know why, but our recursor is not answering queries with this 
downloadirpf.receita.fazenda.gov.br

Could you guys please take a look ?

**Comment by phonedph1** [comment]
This replies without `aa=1` which is considered invalid.

```
$ dig downloadirpf.receita.fazenda.gov.br  @centauro.serpro.gov.br +norec

; <<>> DiG 9.10.6 <<>> downloadirpf.receita.fazenda.gov.br @centauro.serpro.gov.br +norec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15666
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;downloadirpf.receita.fazenda.gov.br. IN	A

;; AUTHORITY SECTION:
downloadirpf.receita.fazenda.gov.br. 14400 IN NS slb-sefaz.fazenda.gov.br.

;; ADDITIONAL SECTION:
slb-sefaz.fazenda.gov.br. 300	IN	A	161.148.201.5
slb-sefaz.fazenda.gov.br. 300	IN	A	189.9.122.8

;; Query time: 303 msec
;; SERVER: 2804:150:c000:204::11#53(2804:150:c000:204::11)
;; WHEN: Wed May 27 13:01:12 MDT 2020
;; MSG SIZE  rcvd: 120
```

**Comment by Habbie** [comment]
Thanks @phonedph1! Closing this as it's not a Recursor bug.

**Comment by phonedph1** [comment]
I provided the wrong example, but the point still stands

```
$ dig downloadirpf.receita.fazenda.gov.br  @slb-sefaz.fazenda.gov.br. +norec

; <<>> DiG 9.10.6 <<>> downloadirpf.receita.fazenda.gov.br @slb-sefaz.fazenda.gov.br. +norec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17389
;; flags: qr; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1400
;; QUESTION SECTION:
;downloadirpf.receita.fazenda.gov.br. IN	A

;; ANSWER SECTION:
downloadirpf.receita.fazenda.gov.br. 0 IN A	161.148.231.16

;; Query time: 317 msec
;; SERVER: 161.148.201.5#53(161.148.201.5)
;; WHEN: Wed May 27 13:02:14 MDT 2020
;; MSG SIZE  rcvd: 115

```

**Comment by phonedph1** [comment]
Previous discussion about this: https://github.com/PowerDNS/pdns/issues/8150

**Comment by ploquets** [comment]
I don't know why, because bind and unbound are resolving it ok...
And the common open recursors like Google, CloudFlare, OpenDNS are resolving this aswell.

How can I workaround this issue?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by mnordhoff** [comment]
> I don't know why, because bind and unbound are resolving it ok...
> And the common open recursors like Google, CloudFlare, OpenDNS are resolving this aswell.

The authoritative servers are malfunctioning, but most resolvers are more forgiving about this bug.

> How can I workaround this issue?

You should fix the authoritative servers.
