### ISSUE TITLE
not the same timestamp in protobuf DNSQueryType and DNSResponseType (queryTime)

### ISSUE THREAD

**Issue by dmachard** [PowerDNS/pdns#9165]
- Program: dnsdist
 - Issue type: Bug report

### Short description
My dnsdist is configured to send protobuf DNSQuery and  DNSResponse to my receiver

I am observing issue on timestamp, a difference between the DNS request and DNS response

```
<Message(PBDNSMessage)>
    <EnumField(id=1, required)>:Type.DNSQueryType
    <BytesField(id=2, optional)>:b'f\x17\xdc\xfaIyA\xe6\xb0X\x16\x9e0#\x1cI'
    <EnumField(id=4, optional)>:SocketFamily.INET
    <EnumField(id=5, optional)>:SocketProtocol.UDP
    <BytesField(id=6, optional)>:b'\n\x00\x00\xeb'
    <BytesField(id=7, optional)>:b'\n\x00\x00a'
    <UInt64Field(id=8, optional)>:43
   <UInt32Field(id=9, optional)>:1590641437
   <UInt32Field(id=10, optional)>:754837
    <UInt32Field(id=11, optional)>:33223
    <MessageField(id=12, optional)>:
        <Message(DNSQuestion)>
            <StringField(id=1, optional)>:www.google.com.
            <UInt32Field(id=2, optional)>:1
            <UInt32Field(id=3, optional)>:1
```

PBDNSMessage.timeSec: <UInt32Field(id=9, optional)>:1590641437
PBDNSMessage.timeUsec: <UInt32Field(id=10, optional)>:**754837**

Bellow the PBDNSMessage with DNSResponse Type for the same previous DNS query. The section DNSResponse provides a query timestamp but it'not the same of the previous timestamp. do you known why ?
It's so confusing:/

```
<Message(PBDNSMessage)>
    <EnumField(id=1, required)>: Type.DNSResponseType
    <BytesField(id=2, optional)>:b'f\x17\xdc\xfaIyA\xe6\xb0X\x16\x9e0#\x1cI'
    <EnumField(id=4, optional)>:SocketFamily.INET
    <EnumField(id=5, optional)>:SocketProtocol.UDP
    <BytesField(id=6, optional)>:b'\n\x00\x00\xeb'
    <BytesField(id=7, optional)>:b'\n\x00\x00a'
    <UInt64Field(id=8, optional)>:59
    <UInt32Field(id=9, optional)>:1590641437
    <UInt32Field(id=10, optional)>:886186
    <UInt32Field(id=11, optional)>:33223
    <MessageField(id=12, optional)>:
        <Message(DNSQuestion)>
            <StringField(id=1, optional)>:www.google.com.
            <UInt32Field(id=2, optional)>:1
            <UInt32Field(id=3, optional)>:1
    <MessageField(id=13, optional)>:
        <Message(DNSResponse)>
            <UInt32Field(id=1, optional)>:0
            <MessageField(id=2, repeated)>:
                <Message(DNSRR)>
                    <StringField(id=1, optional)>:www.google.com.
                    <UInt32Field(id=2, optional)>:1
                    <UInt32Field(id=3, optional)>:1
                    <UInt32Field(id=4, optional)>:218
                    <BytesField(id=5, optional)>:b'\xac\xd9\x12\xc4'
                 **<UInt32Field(id=5, optional)>:1590641437
                 <UInt32Field(id=6, optional)>:754824**

```

PBDNSMessage.DNSResponse.queryTimeSec: <UInt32Field(id=5, optional)>:1590641437
PBDNSMessage.DNSResponse.queryTimeUsec: <UInt32Field(id=6, optional)>:**754824**

### Environment

 - Operating system: Dndsit running on CentOS Linux release 7.2.1511 (Core)
 - Software version: dnsdist 1.4.0
 - dnsdist configuration

### Steps to reproduce

1. Configure a remote logger as below
```
rl = newRemoteLogger("10.0.0.97:6003")
addAction(AllRule(),RemoteLogAction(rl))
addResponseAction(AllRule(),RemoteLogResponseAction(rl))
```

2. Make a resolution and take a look in the remote logger

### Expected behaviour

the PBDNSMessage.DNSResponse.queryTime in the DNSResponseType message should be the same of the PBDNSMessage.timeSec/timeUsec provided in the corresponding DNSQueryType message

### Actual behaviour

PBDNSMessage.DNSQueryType
    PBDNSMessage.timeSec: <UInt32Field(id=9, optional)>:1590641437
    PBDNSMessage.timeUsec: <UInt32Field(id=10, optional)>:**754837**

PBDNSMessage.DNSResponseType
   PBDNSMessage.DNSResponse.queryTimeSec: <UInt32Field(id=5, optional)>:1590641437
   PBDNSMessage.DNSResponse.queryTimeUsec: <UInt32Field(id=6, optional)>:**754824**

**Comment by dmachard** [comment]
a more readable example of the issue

```

type: DNSQueryType
messageId: "\216\342\201\213\000OG\023\202:\305Ds\'~\246"
serverIdentity: "localhost.localdomain"
socketFamily: INET
socketProtocol: UDP
from: "\n\000\000\353"
to: "\n\000\0007"
inBytes: 47
timeSec: 1590579299
timeUsec: 778436
id: 60477
question {
  qName: "www.nextimpact.com."
  qType: 1
  qClass: 1
}
requestorId: ""
deviceId: ""
deviceName: ""
fromPort: 48755
toPort: 53

type: DNSResponseType
messageId: "\216\342\201\213\000OG\023\202:\305Ds\'~\246"
serverIdentity: "localhost.localdomain"
socketFamily: INET
socketProtocol: UDP
from: "\n\000\000\353"
to: "\n\000\0007"
inBytes: 63
timeSec: 1590579299
timeUsec: 778463
id: 60477
question {
  qName: "www.nextimpact.com."
  qType: 1
  qClass: 1
}
response {
  rcode: 0
  rrs {
    name: "www.nextimpact.com."
    type: 1
    class: 1
    ttl: 180
    rdata: "\330\031\373\207"
    udr: false
  }
  queryTimeSec: 1590579299
  queryTimeUsec: 778294
}
requestorId: ""
deviceId: ""
deviceName: ""
fromPort: 48755
toPort: 53

```

**Comment by rgacogne** [comment]
> Bellow the PBDNSMessage with DNSResponse Type for the same previous DNS query. The section DNSResponse provides a query timestamp but it'not the same of the previous timestamp. do you known why ?

The values of the `timeSec` and `timeUsec` are set when the protobuf message is generated, which is a few microseconds after the time the DNS query or response was received. The time in `DNSResponse.queryTimeSec` and `DNSResponse.queryTimeUsec` is set to the time the query was received, to include the processing time between the (`DNSResponse.queryTimeSec`, `DNSResponse.queryTimeUsec`) and (`timeSec`, `timeUsec`).
Now, if that matters that much to you, you can get the time the DNS query was received in the protobuf message corresponding to the query, since the `DNSResponse.queryTimeSec` and `DNSResponse.queryTimeUsec` fields are set in a `DNSQueryType` message as well and should match the ones from the `DNSResponseType` message.
Out of curiosity, would you mind explaining why you need the timestamps to match exactly?

**Comment by dmachard** [comment]
in fact I just want to calculate the latency between the request and the response, when I saw that there are several different arrivals timestamp for the request, I wonder if it was normal or a bug.
With the explanation it's clear now :)

**Comment by rgacogne** [comment]
I'm closing this for now as I think the current behaviour is fine, but please feel free to comment if you disagree and I will re-open :)
