### ISSUE TITLE
office.com delegation hell hits recursion limit (too deep, depth=17)

### ISSUE THREAD

**Issue by grinapo** [PowerDNS/pdns#9197]
- Program: Recursor (probably dnsdist too)
 - Issue type: Bug report (but maybe it's just an extreme case)

### Short description
`outlook.office.com` has half a dozen `CNAME`s, continuously changing and spread over a dozens of (constantly changing) nameservers. Coupled with 10-60 seconds TTLs. This is a recent change I guess, about 1-2 weeks old.

The result is that preiodically recursor hits the recursion limit on `CNAME`s and fails, and cache and dnsdist caches the result, which in turn result the user to lose its preciously slow Microsoft™ services.

Boils down to:
```
2020-06-03_14:19:08.75812 Jun 03 16:19:08                  ns1-ms-acdc.office.com: recursing (CNAME or other indirection) too deep, depth=17
2020-06-03_14:19:08.75820 Jun 03 16:19:08                 QM ns1-ms-acdc.office.com.|A child=ns1-ms-acdc.office.com: Step3 Final resolve: Server Failure/0
```

### Environment
 - Operating system: debian/buster/amd64
 - Software version:  4.3.1-1pdns.buster
 - Software source: pdns repo

### Steps to reproduce
**bad:**
```$ dig outlook.office.com a @rns3.tolna.net

; <<>> DiG 9.16.2-Debian <<>> outlook.office.com a @rns3.tolna.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 24003
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outlook.office.com.            IN      A

;; ANSWER SECTION:
outlook.office.com.     51      IN      CNAME   substrate.office.com.
substrate.office.com.   166     IN      CNAME   substrate.ms-acdc.office.com.
substrate.ms-acdc.office.com. 51 IN     CNAME   afd-k.office.com.
afd-k.office.com.       51      IN      CNAME   outlook-office-com.k-0002.k-msedge.net.
outlook-office-com.k-0002.k-msedge.net. 170 IN CNAME outlook.ha.office365.com.
outlook.ha.office365.com. 51    IN      CNAME   outlook.ms-acdc.office.com.
```

**good:**
```
;; ANSWER SECTION:
outlook.office.com.     15      IN      CNAME   substrate.office.com.
substrate.office.com.   252     IN      CNAME   substrate.ms-acdc.office.com.
substrate.ms-acdc.office.com. 15 IN     CNAME   afd-k.office.com.
afd-k.office.com.       15      IN      CNAME   outlook-office-com.k-0002.k-msedge.net.
outlook-office-com.k-0002.k-msedge.net. 130 IN CNAME outlook.ha.office365.com.
outlook.ha.office365.com. 15    IN      CNAME   outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 31  IN      CNAME   VIE-efz.ms-acdc.office.com.
VIE-efz.ms-acdc.office.com. 7   IN      A       40.101.71.98
VIE-efz.ms-acdc.office.com. 7   IN      A       40.101.76.114
VIE-efz.ms-acdc.office.com. 7   IN      A       52.97.160.178
VIE-efz.ms-acdc.office.com. 7   IN      A       40.101.53.242
```

### Expected behaviour
Preferably not `SERVFAIL`, but I am not even sure microsoft have managed to create valid combinations. Well, at least worths another look.

### Other information
I am not sure raising the limit would help, but would be glad if more eyes are thrown on the problem.

**Comment by omoerbeek** [comment]
Looks like a duplicate of #9192, which has fix I just committed today.

**Comment by grinapo** [comment]
> Looks like a duplicate of #9192, which has a fix I just committed today.

It seems to have fixed that, indeed. Thanks. Let's hope it gets propagated to a release since it actually screws up most microsoft s**t people are bent to use.
