### ISSUE TITLE
Optionally disable additional processing

### ISSUE THREAD

**Issue by tommyulfsparre** [PowerDNS/pdns#9199]
- Program: Authoritative  
 - Issue type: Feature request

### Short description

Add an option to disable additional processing, like the existing `do-ipv6-additional-processing`.
### Usecase

We have have a need to serve large (close to exceeding the size of a TCP packet) records through our DNS infrastructure. As our internal resolvers doesn't use the additional section we would to like to have the option to disable this in PowerDNS to limit the size of the response.  

### Description

When setting `do-additional-processing` to false (defaults to true) the additional section will not be filled in by PowerDNS.

**Comment by pieterlexis** [comment]
> We have have a need to serve large (close to exceeding the size of a TCP packet) records through our DNS infrastructure. As our internal resolvers doesn't use the additional section we would to like to have the option to disable this in PowerDNS to limit the size of the response.

What kind of records are you serving over TCP that exceed 64k?

PowerDNS will truncate additional sections if they won't fit in the packet (on UDP at least).

**Comment by Habbie** [comment]
> PowerDNS will truncate additional sections if they won't fit in the packet (on UDP at least).

We changed that in #7873, we now TC if additionals did not fit as well.

**Comment by tommyulfsparre** [comment]
@pieterlexis internal records, we have probably outgrown DNS for this usecase but the theory is that this would give us some runway. Forgot to mention that we are running version `4.3.0`. 

(I was about to open another issue regarding a change in behaviour from `4.3.0` and the old version we where running. If the response from the backend exceeds 64k PowerDNS will not return a response the old version would truncate but still respond. )

**Comment by Habbie** [comment]
It is unlikely we will add this option. In fact, I wonder if it's time to remove `do-additional-ipv6-processing` as well!

**Comment by tommyulfsparre** [comment]
@Habbie Got it. We don't mind doing the change ourself but if the project don't want it we understand and will look at other options.
