### ISSUE TITLE
dnsdist tab-completion issue

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#9210]
- Program: dnsdist
 - Issue type: Bug report

### Short description
There is a problem with dnsdist and libedit involving tab-completion and the completion of ()'s.

### Environment
 - Operating system: Debian Buster (10.4), latest updates, amd64
 - Software version: dnsdist 1.5.0-rc.2
 - Software source: PowerDNS repository

### Steps to reproduce
1. Setup dnsdist with minimal/no config
2. Launch `dnsdist -c` to enter the console
3. start typing `dumpS` then hit tab, followed by a return.

### Expected behaviour
`> dumpStats()` autocompletes and shows the stats when hitting return.

### Actual behaviour
`> dumpStats\(\)` autocompletes. (notice the extra `\`). When hitting enter, you'll get:
```
> dumpStats\(\)
Error: [string "dumpStats\(\)"]:1: '=' expected near '\': >
```

### Other information
After discussion on irc, @rgacogne pointed out that this is due to a bug in certain `libedit` versions. There might not be much we can do about it. Even if that's the case, this ticket is still valid to document the bug to others.

```
ii  libedit2:amd64                       3.1-20181209-1               amd64        BSD editline and history libraries
```

**Comment by rgacogne** [comment]
Just for the record, it works well with libedit `20191231_3.1-1` (Arch). I recall it used to fail at some point, likely with `20181209-3.1-1`.

**Comment by zeha** [comment]
Another datapoint: dnsdist 1.4.0-1+b3 with libedit2 3.1-20191231-1 appears to auto-complete successfully on bullseye/sid.

**Comment by rgacogne** [comment]
I'm closing this issue since it is outside our control, but I will of course re-open if needed.
