### ISSUE TITLE
Configure DNSKEY TTL

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#9220]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Currently, PDNS sets the DNSKEY TTL of synthesized reponses to the negative-TTL of the zone. Short negative TTLs are not uncommon, hence this may result in short DNSKEY TTL.

I just learned in the DNS-OARC online meeting that "Recursive resolvers trim dependent signed RRsets to no more than their parent". Which means resolvers stop caching when the zones DNSKEY TTL expires.

Is there a specific reason why the DNSKEY TTL uses the zone's negative-TLL?

I think it may be useful to have a pdns.conf option to override the default value, ie: dnskey-ttl=86400.

**Comment by mnordhoff** [comment]
Note:

> If you want a ‘normal’ TTL (3600, 86400, etc.) for your DNSKEY but a low TTL on negative answers, set your SOA minimum TTL to the high number, and set the TTL on the SOA record itself to the low TTL you want for negative answers. Note that [before 4.3.0] the NSEC/NSEC3 records proving those negatives will get the high TTL in that case, and this may affect subsequent resolution in resolvers that do aggressive NSEC caching (RFC 8198).

https://doc.powerdns.com/authoritative/dnssec/operational.html#some-notes-on-ttl-usage

**Comment by klaus3000** [comment]
I was not aware that a low SOA TTL has impact on the negative caching of resolvers. Anyways, we are a secondary DNS service and we sign our customer zones. Hence, when we slave a zone we do not have control over the SOA.

**Comment by Habbie** [comment]
> I just learned in the DNS-OARC online meeting that "Recursive resolvers trim dependent signed RRsets to no more than their parent".

I also saw that claim. I asked him what resolvers he had actually seen doing that, but sadly he did not respond.

PowerDNS Recursor does not do this; I don't know if any resolvers do.

**Comment by Habbie** [comment]
Given the notes that @mnordhoff linked to, I'm leaning towards closing this. Any objections?

**Comment by aldem** [comment]
>set your SOA minimum TTL to the high number

As far as I know, "SOA minimim" is deprecated in favor of "SOA negative" in [RFC 2308](https://tools.ietf.org/html/rfc2308) ("4 - SOA Mimimum Field"):
>  Despite being the original defined meaning, the first of these, the  minimum TTL value of all RRs in a zone, has never in practice been used and is hereby deprecated.

and a bit later:
> The remaining of the current meanings, of being the TTL to be used  for negative responses, is the new defined meaning of the SOA minimum field.

Thus, I believe that this field must not be used as a RR TTL at all.

**Comment by zeha** [comment]
@klaus3000 If I understood you right, this is a problem because you're a secondary operator.

I think we need to clarify the usecase a little bit more:
- Is this "hidden master" + secondary is online signing, acting as the "public masters"?
- 3rd-party public master + secondary as presigned?
- Something else?

**Comment by zeha** [comment]
After private discussion, lets go with @Habbie's suggestion of closing this for now.
