### ISSUE TITLE
Recursor: forward-zones=.=127.0.0.1:5353 seems to bypass caching (breaking RFC7706 implementation attempt)

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#9227]
- Program: Recursor
 - Issue type: Bug report

### Short description
Pointing the root zone to a local auth in order to implement some sort of RFC7706 "local root server on loopback" solution using "forward-zones=.=127.0.0.1:5353" does not seem to work as it looks like replies are not cached. Every inbound lookup attempt seems to go out to the configured destination even though previous replies have already indicated that, for example, ".com can be found at x.gtld-servers.net and this won't change for another 86400 seconds".
This breaks any attempts of RFC7706 implementation using the "forward-zones" statement as it just plain overloads the local auth instance (of course depending on the amount of inbound client queries). The overall behavior might be intentional for "forward-zones" but the documentation is not very distinct regarding reply caching and I do have some doubts there.
In any case it would be good if we could forward root queries to a local target either using "forward-zones" or a similar setting. Bonus points for being able to fully slave the root zone out of the box (#3042).

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: Recursor 4.3.1
 - Software source: PowerDNS repository

### Steps to reproduce

1. Set up local root zone slave auth instance
2. Point recursor towards the local instance for "." using "forward-zones=.=127.0.0.1:5353"
3. Send a bunch of queries for .com domains and watch local lookup traffic towards the local auth instance

### Expected behaviour

A single query for the first domain getting back NS replies for .com
(likely multiplicated by the number of threads plus some DS and other queries)

### Actual behaviour

All inbound queries are basically being sent to the local auth instance

### Other information
Issue opened as requested, as discussed with the team.

**Comment by phonedph1** [comment]
Does using `auth-zones` work better for you? I've not tried it myself but the suggestion of changing how `forward-zones` works would likely break a lot of existing expectations for people. I think the confusion might come from BIND supporting both modes (forwards and stub zones, IIRC).

**Comment by aj-gh** [comment]
`auth-zones` does not support DNSSEC.
Not sure if changing (or fixing?) `forward-zones` would break that much given there is TTL for stuff that is supposed to change on short(er) notice. In addition I would assume that BIND caches as well.
For recursion there is also `forward-zones-recurse`.
