### ISSUE TITLE
set account on inital insert when adding a zone via the API

### ISSUE THREAD

**Issue by MikeAT** [PowerDNS/pdns#9232]
- Program: Authoritative
 - Issue type: Feature request

### Short description

When adding a zone via the PowerDNS API PowerDNS (with the SQL-Backend)  does a insert (with type=NATIVE) and sets the additional information (like the account field and type) with several UPDATE-statements later on.

We are running varoius PowerDNS instances from one backend, each PowerDNS is assigned to one or more accounts so inserting domains with undefined account-field leads to unassigned domains (until the account is set).  We have a workaround in place to handle this case, but it would be great if we could remove it and PowerDNS tries to limit the UPDATE-queries done for a "add zone" and puts as much information as possible in the INSERT statement.

Thx,
Michael

**Comment by zeha** [comment]
Got some feedback: a single transaction doesn't help with ON INSERT/UPDATE triggers, which are of relevance here.

**Comment by zeha** [comment]
Implemented!
