### ISSUE TITLE
Add 'dump-running-config' feature to rec_control 

### ISSUE THREAD

**Issue by lpmhouben** [PowerDNS/pdns#9235]
- Program: Recursor
 - Issue type: Feature request

### Short description
Dump the current running config of the recursor into a named file.

### Usecase
Diagnostic; if you're not sure whether a config option got silently overridden by an included file you overlooked. 

### Description
Dump a full readout of the config as currently loaded into the recursor process, preferably in the format of a config file and sorted alphabetically for easy searching.

I've been asked by @Habbie on IRC to note that auth 4.3 already has the functionality.

**Comment by omoerbeek** [comment]
Implemented by #11907
