### ISSUE TITLE
Backend reported condition which prevented lookup

### ISSUE THREAD

**Issue by tobiascapin** [PowerDNS/pdns#9286]
After some hours of run, the dns service stops serving

### Environment
Ubuntu 16.04.6 LTS 64bit
PowerDNS Authoritative Server 4.0.0-alpha2
Using 64-bits mode. Built using gcc 5.3.1 20160330.

### Steps to reproduce
1. Wait

This is the logged error:

```
pdns[7187]: Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
pdns[7187]: message repeated 34 times: [ Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail]

```
There are not custom queries, and I'm using the standard configuration with mysql.

When I restart the service, the problem is solved for a while.

**Comment by rgacogne** [comment]
Please upgrade to a non-alpha version.. We provide packages at https://repo.powerdns.com/ since Ubuntu can't be bothered to provide a stable version. I would also advise upgrading to a newer branch as 4.0.x is end-of-life.
