### ISSUE TITLE
Recursor: RPZ refresh interval are ignored and zones are reloaded every second

### ISSUE THREAD

**Issue by ancarpan** [PowerDNS/pdns#9299]
- Program: Recursor
- Issue type: Bug report

### Short description
RPZ configure as per:

```
[root@system ~]# cat  /etc/pdns-recursor/rpz.lua 

-- RPZ Security Zones
rpzMaster("192.168.1.12", "rpz.ageverification", {})
```
The zone itself is:
```
# pdnsutil list-zone rpz.ageverification. 
$ORIGIN .
rpz.ageverification	3600	IN	SOA	a.misconfigured.powerdns.server hostmaster.rpz.ageverification 1 10800 3600 604800 3600
```
Expected behaviour is: RPZ reload at TTL expiry.
What happens: logs show zone being reloaded every second

### Environment
 - Operating system: ]# CentOS Linux release 7.5.1804 (Core) 
 - Software version: pdns-recursor-4.3.1-1pdns.el7.x86_64
 - Software source: http://repo.powerdns.com/centos/$basearch/$releasever/rec-43

**Comment by omoerbeek** [comment]
This issue is also present on master. The problem occurs if no cache file is used. I that case the refresh time is only picked up once a new update comes.
