### ISSUE TITLE
[docs] dnsdist webserver parameters are global

### ISSUE THREAD

**Issue by stirnim** [PowerDNS/pdns#9311]
- Program: dnsdist
 - Issue type: Bug report

### Short description
webserver parameters (password, apikey, custom headers, acl) are global to all webserver instances.
This behaviour is not expected when reading the documentation https://dnsdist.org/reference/config.html#webserver-configuration. It would be useful if the documentation could state this behaviour.

### Environment
 - Operating system: CentOS 7.6
 - Software version: dnsdist 1.5.0-rc4
 - Software source: compiled myself

### Steps to reproduce
The following configuration sets different ACLs per webserver instance. However, as the parameters are globally applied "::/0" is cleared.
```
webserver("[2001:620:0:1006:21a:4aff:fede:ee3d]:8853","supersecret", "", {}, "::/0")
webserver("[::1]:8853","supersecret", "", {}, "127.0.0.1, ::1")
```

### Expected behaviour
Either apply webserver parameters per webserver instance or state in the documentation that parameters (password, apikey, custom headers, acl) are global to all webserver instances. For example:

> All webserver parameters except `listen_address` are global to all webserver instances.

**Comment by rgacogne** [comment]
Setting a 1.5.0 milestone to fix the documentation, and we should make these parameters per-instance in 1.6.0.
