### ISSUE TITLE
dofile: Caught exception: Script took too long

### ISSUE THREAD

**Issue by sddwt** [PowerDNS/pdns#9321]
- Program: Authoritative
 - Issue type: Bug report

### Short description

When using dofile function, it throws the exception:
Caught exception: 
Jul 10 21:11:34 Lua record reported: /reader.lua:41: Caught exception: Script took too long

### Environment

 - Operating system:  Centos7
 - Software version:  4.2.2
 - Software source:  PowerDNS repository,

### Steps to reproduce

1. I added a lua recoed: return dofile('/reader.lua') 
2. reader.lua is about 60 lines
3. error

### Expected behaviour

I hope it can run more codes to achieve what I need.

**Comment by Habbie** [comment]
Can you try setting `lua-records-exec-limit` in pdns.conf to a bigger number? The default is 1000.

**Comment by sddwt** [comment]
> Can you try setting `lua-records-exec-limit` in pdns.conf to a bigger number? The default is 1000.

Thanks, I just find the setting is working now.
I will close this issue.
Thank you for your job.
