### ISSUE TITLE
IP Range support.

### ISSUE THREAD

**Issue by sddwt** [PowerDNS/pdns#9324]
- Program: Authoritative 
 - Issue type: Feature request

### description

Hi,
We have tested a large number of CIDR matching by LUA,
We found the response time is increasing so rapidly.
By using IP RANGE, the number of indexs can be much more less at least 1/3. So will the match time.
Due to the efficiency of some algorithm such as B tree, its time cost is O(log(N)).
N is smaller, the cost will be less.
### Usecase

Imporve the efficiency.

**Comment by Habbie** [comment]
Can you try https://doc.powerdns.com/authoritative/lua-records/reference/netmask.html#netmaskgroup-class ?

**Comment by sddwt** [comment]
> Can you try https://doc.powerdns.com/authoritative/lua-records/reference/netmask.html#netmaskgroup-class ?

Yeah, we tried view and netmask.
IP Range like 47.235.0.0 - 47.246.255.255.
But pdns only use cidr.
Thanks for reply.

**Comment by sddwt** [comment]
> Can you try https://doc.powerdns.com/authoritative/lua-records/reference/netmask.html#netmaskgroup-class ?

It can also be the problem of machine.
The test machine is 2 core 4g,
If you can take it into consider, that's will be very nice. :)

**Comment by Habbie** [comment]
I'm sorry, I'm not sure what you are asking for. Your IP range can be converted into a few CIDR ranges, and then you can use NMG.

**Comment by sddwt** [comment]
> CIDR

Yes, you are right,
But actually, IP range is much more smaller than CIDR.
I think this will make the NMG cost less time.

**Comment by Habbie** [comment]
If NMG is too slow, it sounds like you're doing something inefficient with them.

With that said:

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by cmouse** [comment]
Hi!

You might be interested to know that your IP range deaggregates in 5 cidr masks.
```
deaggregate 47.235.0.0 - 47.246.255.255
47.235.0.0/16
47.236.0.0/14
47.240.0.0/14
47.244.0.0/15
47.246.0.0/16
```

PowerDNS NetmaskGroup can handle these directly, there is no need to split them into smaller ranges.

There will be no more replies.
