### ISSUE TITLE
/metrics endpoint does not work for me (auth 4.3.0)

### ISSUE THREAD

**Issue by vudex** [PowerDNS/pdns#9325]
- Program: Authoritative 4.3.0
 - Issue type: Bug report

### Short description
/metrics endpoint gives me 404. Though I can retrieve json metrics through API at 
http://server:8081/api/v1/servers/localhost/statistics

### Environment

 - Operating system: docker container build with alpine 3.12
 - Software version: docker 19.03.11
 - Software source: Compiled myself 

### Other information
my pdns.conf contains
-------------------------
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-password=testpasswd
webserver-allow-from=10.0.0.0/8,172.16.0.0/12,127.0.0.0/8

api=yes
api-key=apipasswd

When trying to curl /metrics
-------------------------------
curl -i -v -u=#:testpasswd http://10.58.216.2:8081/metrics
* About to connect() to 10.58.216.2 port 8081 (#0)
*   Trying 10.58.216.2...
* Connected to 10.58.216.2 (10.58.216.2) port 8081 (#0)
* Server auth using Basic with user '=#'
> GET /metrics HTTP/1.1
> Authorization: Basic PSM6MjdzZTNFN3VZZHZT
> User-Agent: curl/7.29.0
> Host: 10.58.216.2:8081
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Connection: close
Connection: close
< Content-Length: 9
Content-Length: 9
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Server: PowerDNS/4.3.0
Server: PowerDNS/4.3.0

< 
* Closing connection 0

**Comment by rgacogne** [comment]
Prometheus support was introduced by https://github.com/PowerDNS/pdns/pull/9182 and is not present in any released version yet. We need to update the documentation :-/

**Comment by vudex** [comment]
Oh, I see then. Ty very much for quick reply.

**Comment by rgacogne** [comment]
Re-opening so we don't forget to update the documentation!
