### ISSUE TITLE
dnsdist certificate issue.

### ISSUE THREAD

**Issue by pizu** [PowerDNS/pdns#9347]
Hi,

am using dnsdist v1.4 and v1.5 on 2 os ubuntu 20.04 servers, both configurations are the same and permissions are the same.

on v1.4 the below line in config works without issues and on v1.5 it doesn't work.

addDOHLocal('x.x.x.x','/etc/ssl/certs/cert.pem', '/etc/ssl/private/cert.key')

error:

Jul 20 11:16:52 ztndns01 dnsdist[23280]: 140011540819264:error:0200100D:system library:fopen:Permission denied:../crypto/bio/bss_file.c:288:fopen('/etc/ssl/private/cert.key','r')
Jul 20 11:16:52 ztndns01 dnsdist[23280]: 140011540819264:error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:290:
Jul 20 11:16:52 ztndns01 dnsdist[23280]: 140011540819264:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:../ssl/ssl_rsa.c:540:
Jul 20 11:16:52 ztndns01 dnsdist[23280]: Fatal error: Error setting up TLS context for DoH listener on 'x.x.x.x:443': An error occurred while trying to load the TLS server private key file: /etc/ssl/private/cert.key
Jul 20 11:16:52 ztndns01 systemd[1]: dnsdist.service: Main process exited, code=exited, status=1/FAILURE

permissions:

-rw-r--r-- 1 root root 1704 Jul 16 15:47 cert.pem
-rw-r--r-- 1 root root 1704 Jul 16 15:47 cert.key

can someone help?

Thanks.

**Comment by Habbie** [comment]
Please see the bit that says 'changed in 1.5.0' at https://dnsdist.org/reference/config.html?highlight=adddohlocal#addDOHLocal

Closing this ticket.

**Comment by Habbie** [comment]
Sorry, my comment was totally wrong.

**Comment by Habbie** [comment]
I suspect your problem is because of https://dnsdist.org/changelog.html#change-76fbba81c341e235d2938e050a4780d1

**Comment by Habbie** [comment]
With that said:

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We have closed this ticket. Comments will likely be ignored.

**Comment by pizu** [comment]
Thanks for your help and for next time will use the irc as suggested.
