### ISSUE TITLE
Update apline pkg to latest (4.3.0) - would be great if this is automated

### ISSUE THREAD

**Issue by anborg** [PowerDNS/pdns#9350]
I want to use alpine pdns, would be great to have latest package there 
https://pkgs.alpinelinux.org/package/edge/community/x86/pdns

```
#FROM alpine
#RUN apk add --no-cache pdns  # From the url, looks like it is 4.2 not 2.3
#RUN apk add --no-cache pdns-backend-sqlite3
```

Is there an official pdns docker image that we can pull specific version ? 

```
FROM pdns/pdns:4.3.3  # Is there an official pdns docker image that we can pull specific version ? 
#RUN apk add --no-cache pdns-backend-sqlite3
#RUN apk add --no-cache pdns-backend-lmdb
RUN apk add --no-cache sqlite
COPY local.conf /etc/pdns/conf.d/local.conf
COPY init.sql /init.sql
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by jsoref** [comment]
@J0WI appears to be involved: https://github.com/alpinelinux/aports/commits/master/community/pdns/APKBUILD

**Comment by Habbie** [comment]
Looks like the upgrade was done, so I'm closing this. We'll take contributions for automation.
