### ISSUE TITLE
[dnsdist] rule-truncate / trunc-success entry in statistics 

### ISSUE THREAD

**Issue by thibmac** [PowerDNS/pdns#9357]
- Program:  dnsdist 
 - Issue type: Feature request

### Short description
This is a request to add an entry in the dnsdist statistics which how many queries answers were truncated. 

### Usecase
dnsdist statistic shows how many queries were answered with the truncate bit after it matches a rule.

### Description
Dnsdist would count how many queries were answered with the truncate bit because of a rule. This value would be stored in the "rule-truncate" entry.
There is already the same kind of statistics with rule-drop, rule-refused, etc... 
trunc-failures also counts how many of these truncated answers failed to deliver, a statistic showing how many queries were successfully truncated would also do the job.

**Comment by rgacogne** [comment]
Implemented in #9992.
