### ISSUE TITLE
PowerDNS master does not update slave

### ISSUE THREAD

**Issue by hmahdiany** [PowerDNS/pdns#9386]
- Program: pdns
 - Issue type: problem

### Short description
Hi guys,
I have a problem in my powerDNS servers. Every time I add a new record by pdnsutil command slave servers don't sync with master but if I add a  new record via poweradmin web pannel they sync with each other as well. Why is this happening?

I get this errors in my master server:
Aug 17 10:14:07 mysqld: 2020-08-17 10:14:07 6056 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active
Aug 17 10:14:07  mysqld: 2020-08-17 10:14:07 6056 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active
Aug 17 10:14:07  mysqld: 2020-08-17 10:14:07 6056 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active
Aug 17 10:14:07  mysqld: 2020-08-17 10:14:07 6056 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active
Aug 17 10:14:07mysqld: 2020-08-17 10:14:07 6056 [ERROR] Transaction not registered for MariaDB 2PC, but transaction is active

I know this is not the correct place to ask this question but I would be thankful if you helped me. This is really important for me.
### Environment

 - Operating system: centos 7
 - Software version: pdns-4.1.11-1
 - Software source: Operating system repository

### Expected behaviour
After adding record by pdnsutil all slave servers should by sync with master server

### Actual behaviour
Only  if I add a  new record via poweradmin web pannel they sync with each other as well.

**Comment by Habbie** [comment]
> I know this is not the correct place to ask this question but I would be thankful if you helped me. This is really important for me.

If you know this, you could have gone to the right place immediately, and we would have been helping you now...


Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by hmahdiany** [comment]
Thank you,
I did not know about other ways to ask my questions.
