### ISSUE TITLE
Missing Stats for dns-over-tls (DoT)

### ISSUE THREAD

**Issue by hmajid2301** [PowerDNS/pdns#9392]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

When it receives dns-over-tls (DoT) traffic from a DNS client these don't seem to show up in the dumpStats() function in the
console. It works fine with dns-over-https (DoH).

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: `dnsdist 1.4.0 (Lua 5.2.4): Enabled features: cdb dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt ebpf fstrm ipcipher libsodium lmdb protobuf re2 recvmmsg/sendmmsg snmp systemd`
 - Software source: OS Repostiory

### Steps to reproduce

1. Send DoT traffic to the dnsdist server i.e. `dnsperf -c 5000 -T 16 -l 930 -d queries.txt -s <dns-dist-server-ip> -S 1 -Q 1200`
2. connect to console `dnsdist -k "xxxx" -c 0.0.0.0:5199`
3. run `dumpStats()`

I get the following output:

```
dumpStats()
acl-drops                         0    latency0-1                         0
cache-hits                        0    latency1-10                        0
cache-misses                      0    latency10-50                       0
cpu-sys-msec                   1262    latency100-1000                    0
cpu-user-msec                  6109    latency50-100                      0
downstream-send-errors            0    no-policy                          0
downstream-timeouts               0    noncompliant-queries               0
dyn-block-nmg-size                0    noncompliant-responses             0
dyn-blocked                       0    queries                            0
empty-queries                     0    rdqueries                          0
fd-usage                         52    real-memory-usage          340680704
frontend-noerror                  0    responses                          0
frontend-nxdomain                 0    rule-drop                          0
frontend-servfail                 0    rule-nxdomain                      0
latency-avg100                    0.0  rule-refused                       0
latency-avg1000                   0.0  rule-servfail                      0
latency-avg10000                  0.0  security-status                    0
latency-avg1000000                0.0  self-answered                      0
latency-count                     0    servfail-responses                 0
latency-slow                      0    special-memory-usage       100438016
latency-sum                       0    trunc-failures                     0
                                       uptime                           805
```

However if I check the downstream dns server it sends traffic to, it's receiving DNS traffic from this DNSDist server.

### Expected behaviour

I would expect to see stats filled out such as those related to latency. 

### Actual behaviour

The stats are empty.

**Comment by rgacogne** [comment]
I'm afraid I can't reproduce the issue on either 1.4.0 or master. Note that I used a different DoT client (custom Python script) because my version of `dnsperf` kept crashing and I did not feel like investigating that right now..

**Comment by hmajid2301** [comment]
can you share the custom python script I'll have a quick test with my setup thanks.

**Comment by rgacogne** [comment]
```python
#!/usr/bin/env python
import dns
import dns.message
import socket
import ssl
import struct

query = dns.message.make_query('powerdns.com.', 'A', 'IN', use_edns=True)

#sslctx = ssl.create_default_context(cafile="/tmp/ca.pem")
sslctx = ssl.create_default_context()
sslctx.check_hostname = False
sslctx.verify_mode = ssl.CERT_NONE

while True:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

    sslsock = sslctx.wrap_socket(sock, server_hostname='127.0.0.1')

    wire = query.to_wire()
    sslsock.connect(("127.0.0.1", 8443))
    sslsock.send(struct.pack("!H", len(wire)))
    sslsock.send(wire)

    data = sslsock.recv(2)
    if data:
        (datalen,) = struct.unpack("!H", data)
        data = sslsock.recv(datalen)
        if data:
            message = dns.message.from_wire(data)
```

**Comment by rgacogne** [comment]
> So from what I understand at the moment because DoT makes a TCP connection to the downstream server. We don't see any of the latency stats being logged.

Indeed, incoming DoT queries are sent to the downstream server via a TCP connection. We might make it possible in the future to send these via UDP but it opens a can of worms with regard to EDNS buffer size and truncation.
And as correctly stated by phonedph1 the internal latencies are only updated for responses sent over UDP (and cache hits), not for TCP, mostly because quite a number of backends unfortunately treat TCP as a third-rate citizen.

> I assume DoH then makes a UDP connection to the downstream server, hence we do see the latency logs for that?

You are right, DoH queries are sent to the backend via UDP datagrams. It's a bit less complicated than for DoT because DoH clients are mostly new tools instead of existing DNS clients, and has worked fine so far, although I wouldn't be surprised to see some truncation issue at some point.

**Comment by hmajid2301** [comment]
Ok thanks for clarifying we will have to see what we can do to get around this. Luckily we expect more DoH traffic as compared with DoT!
