### ISSUE TITLE
Inconsistent Error Message for OPENPGPKEY Record Parsing

### ISSUE THREAD

**Issue by nils-wisiol** [PowerDNS/pdns#9418]
- Program: Authoritative 
 - Issue type: Bug report

### Short description
When setting an OPENPGPKEY record using the API, pdns does not accept records if the presentation format given contains spaces. However, it says "parsed as <value without spaces>". If the value without spaces is sent to begin with, it is accepted.

### Environment
 - Operating system: Ubuntu
 - Software version: 4.3
 - Software source: apt-get

### Steps to reproduce
1. Send an OPENPGPKEY record containing spaces to the API, e.g. `mG8EXtVIsRMFK4EEACIDAwQSZPNqE4tSxLFJYhX+uabSgMrhOqUizJhk Lx82` - it will be rejected
1. Take the "parsed as" value from the error message (in above example, `mG8EXtVIsRMFK4EEACIDAwQSZPNqE4tSxLFJYhX+uabSgMrhOqUizJhkLx82`) and send it to the API with everything else unchanged - it will be accepted

I created a docker-compose application to reproduce the error, code and detailed instructions can be found at https://github.com/nils-wisiol/pdns-openpgpkey

### Expected behaviour
One of:
- pdns accepts values for OPENPGPKEY that contain spaces
- pdns shows the spaces in the error message

### Actual behaviour
Value was rejected, but working value was shown in error message.

### Other information
I could not find any source saying spaces are allowed in OPENPGPKEY presentation format. However, dnspython adds spaces when converting OPENPGPKEY records from wire format to presentation format.

**Comment by Habbie** [comment]
> Value was rejected, but working value was shown in error message.

This is the expected API behaviour. The input is parsed; then represented again; if that representation does not match the input, it is rejected.

**Comment by Habbie** [comment]
> I could not find any source saying spaces are allowed in OPENPGPKEY presentation format. However, dnspython adds spaces when converting OPENPGPKEY records from wire format to presentation format.

I also cannot find a source so I asked the OPENPGPKEY RFC author https://twitter.com/Habbie/status/1298642657829425152

**Comment by Habbie** [comment]
Closing this as there is no bug (unless spaces turn out to be forbidden).

**Comment by letoams** [comment]
Why is the presentation format used to parse the data instead of the wire format?
If the consumer does not accept spaces, why would code from the same sourcecode add spaces to create the presentation format?

The RFC states it is just the base64 blob with no spaces, but since base64 contains no spaces, implementations that consume presentation format should just assume the spaces can be removed before decoding the (now valid) base64

**Comment by Habbie** [comment]
> Why is the presentation format used to parse the data instead of the wire format?

Our HTTP API uses presentation format because it is way more convenient for the API users.



> The RFC states it is just the base64 blob with no spaces, but since base64 contains no spaces, implementations that consume presentation format should just assume the spaces can be removed before decoding the (now valid) base64

Thanks - so would you say that dnspython is wrong in putting in spaces when generating presentation format?

**Comment by Habbie** [comment]
ah, Nils already posted at https://github.com/rthalley/dnspython/issues/577 - your input would probably be welcome there, Paul.

**Comment by Habbie** [comment]
Already sorted there as well. Thanks for dropping by!

**Comment by nils-wisiol** [comment]
thanks for the fast replies, guys :rocket:
