### ISSUE TITLE
pdns_control should reference pdnsutil at least in see also

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/pdns#9436]
- Program: Authoritative
 - Issue type: Feature request

### Short description
I know that there's a thing to validate zones, so I started in `man pdns_control` (https://doc.powerdns.com/authoritative/manpages/pdns_control.1.html) and I didn't get there 

### Description
At the very least a simple `see also` entry for `pdnsutil` would be helpful.

**Comment by Habbie** [comment]
Fixed in #9437
