### ISSUE TITLE
Unnecessary requests to intermediate levels of the hard-coded domain.

### ISSUE THREAD

**Issue by brlumen** [PowerDNS/pdns#9438]
- Program: Recursor
 - Issue type: Bug report

### Short description
Performing unnecessary operations in the process of processing a hard-coded domain leading to sending part of the requests to other servers.

### Environment
 - Operating system: Oracle Linux Server release 8.2
 - Software version: 4.4.0-beta1
 - Software source: PowerDNS repository

### Steps to reproduce

1. Add the forwarding "baz.bar.com = ip_yuo_auth_internal_server" to your recursive server config in any way you want;
2. Enable request tracing: rec_control trace-regex '.*\.bar.com\.$'
3. Send a request to the recurser: "dig bar.baz.com @recursor_ip";
4. In the recursor log, we observe requests to all servers of intermediate levels of the bar.baz.com domain if they are not in the cache.

### Expected behaviour
The recurser must immediately send a request to the server, which is specified in the "forward-zones" directive or in the "forward-zones-file".

### Actual behaviour
The recurser queries the entire chain of authoritative servers of the parent zones (".", "Com", "baz") trying to find the current NS up to the subdomain "bar", but regardless of whether it succeeded or not, reaching the "bar" level it detects that the domain is hardcoded and further communication is performed with the server specified in the "forward-zones" or "forward-zones-file" directives.

### Other information
The behavior does not appear if you turn off qname minification.
You also need to take into account that in 4.4.0-beta1, the cache of ns records for subdomains that fall under the path of hard-coded domains finally started working. I would like this behavior to remain operational.

P.S.: Please edit the title of this issue if you find a more appropriate phrase.

**Comment by omoerbeek** [comment]
@brlumen can you test the PR? Thanks!

**Comment by brlumen** [comment]
@omoerbeek I'll try to test it tomorrow.
