### ISSUE TITLE
On WSL1 "Error sending reply with sendmsg"

### ISSUE THREAD

**Issue by MerryDan** [PowerDNS/pdns#9453]
PowerDNS does not work on WSL1

Environment
Operating system: Windows 10 (1909) WSL Update 4.19.104 running Ubuntu 20.04
Software version: PowerDNS 4.2.1-1build2 (original Ubuntu deb)
Software source: Ubuntu website

Steps to reproduce:
 - Install PowerDNS on WSL-Ubuntu with mysql plugin and basic options (default schema, simple domain and A record, setup as master binding to 0.0.0.0 or 127.0.0.1)
 - Send DNS lookup request

Expected behaviour
 - Returns a response

Actual behaviour
 - Get no response

Other information
 - Get in Syslog the following: pdns[14250]: Error sending reply with sendmsg (socket=4, dest=127.0.0.1:49827): Invalid argument

**Comment by MerryDan** [comment]
PowerDNS does not work on WSL

pdns[14250]: Error sending reply with sendmsg (socket=4, dest=127.0.0.1:49827): Invalid argument

**Comment by Habbie** [comment]
PowerDNS worked fine on WSL1 when I tried it. Can you please rewrite your issue using https://github.com/PowerDNS/pdns/blob/master/.github/ISSUE_TEMPLATE/bug_report.md ?

**Comment by Habbie** [comment]
Closing this because there was no response.

**Comment by MerryDan** [comment]
I changed port from 53 to 54 and appeared to work. Could probably be put down to "anti-virus issue"
