### ISSUE TITLE
lua record cannot be added   'LUA' doesn't look like a qtype  bugreport  

### ISSUE THREAD

**Issue by networkprofession** [PowerDNS/pdns#9476]
[root@mysrv1 pdns]# pdnsutil edit-zone examplezone.com

www    IN    LUA    A    "pickclosest({'192.0.2.1','192.0.2.2','198.51.100.1'})"

Problem: Parsing zone content on line 21 of file '/tmp/pdnsutil-T88eax': 'LUA' doesn't look like a qtype, stopping loop on line 21 of file '/tmp/pdnsutil-T88eax'
There was a problem with your zone
Options are: (e)dit your changes, (r)etry with original zone, (a)pply change anyhow, (q)uit:

[root@mysrv1 pdns]# pdns_control version
4.4.0-alpha0.961.master.g89eac9ce8

enable-lua-records=yes

**Comment by zeha** [comment]
Hi,

you have reported an issue ignoring the issue template. This makes triaging it a lot harder.

However, your issue looks like a support question. Support questions are best handled in the PowerDNS online communities: IRC and mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.
