### ISSUE TITLE
PowerDNS does not chroot with bind-backend

### ISSUE THREAD

**Issue by 3FOX** [PowerDNS/pdns#948]
Hello,

PowerDNS with bind-backend works fine but when chroot is enabled
I got this error message:

Debian 7/64
PowerDNS 3.2

pdns.conf
bind-dnssec-db=/var/db/bind-dnssecdb
chroot=/var/spool/powerdns

Creating backend connection for TCP
Caught an exception instantiating a backend, cleaning up
Exiting because of STL error: Error opening
DNSSEC database in BIND backend: SQLite database '/var/db/bind-dnssecdb' does not exist yet

I tried this too

pdnssec create-bind-db /var/spool/powerdns/bind-dnssecdb

pdns.conf
bind-dnssec-db=/var/spool/powerdns/bind-dnssecdb
chroot=/var/spool/powerdns

Creating backend connection for TCP
Caught an exception instantiating a backend, cleaning up
Exiting because of STL error: Error opening
DNSSEC database in BIND backend: SQLite database '/var/spool/powerdns/bind-dnssecdb' does not exist yet

Also, I checked this http://doc.powerdns.com/html/security.html#idp8658480

I tried this too

chown pdns:pdns /var/spool/powerdns

Finally I tried chroot=./ as well.

Does anyone know how to run PowerDNS-Bind-Backend and chroot enabled?

**Comment by pieterlexis** [comment]
Chrooting with the BIND backend works:

```
$ sudo ./pdns/pdns_server --config-dir=../pdns-conf/bindchroot --slave 
Dec 18 17:15:49 Reading random entropy from '/dev/urandom'
Dec 18 17:15:49 This is a standalone pdns
Dec 18 17:15:49 Listening on controlsocket in '/home/lieter/src/PowerDNS/pdns-conf/bindchroot/pdns.controlsocket'
Dec 18 17:15:49 UDP server bound to 0.0.0.0:5300
Dec 18 17:15:49 TCP server bound to 0.0.0.0:5300
Dec 18 17:15:49 PowerDNS Authoritative Server 0.0.issue2429txtwithwithoutquotes.g812632e.dirty (C) 2001-2015 PowerDNS.COM BV
Dec 18 17:15:49 Using 64-bits mode. Built using gcc 5.3.0 on Dec 18 2015 12:09:11 by lieter@ananas.home.plexis.eu.
Dec 18 17:15:49 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Dec 18 16:15:49 Chrooted to '/home/lieter/src/PowerDNS/pdns-conf/bindchroot'
Dec 18 16:15:49 Not validating response for security status update, this a non-release version.
Dec 18 16:15:49 Master/slave communicator launching
Dec 18 16:15:49 Creating backend connection for TCP
```

The path for `bind-dnssec-db` is relative to the chroot, so it should be `/bind-dnssecdb`
