### ISSUE TITLE
rec: Different runtime dirs for virtual services (#9397) introduced slight incompatibility with older systemd releases

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#9485]
- Program: Recursor
 - Issue type: Bug report

### Short description
#9397 (based on #9073) introduced different runtime directories for virtual services. systemd then creates runtime directories in the format _/var/run/pdns-recursor-&lt;instance&gt;_ however this relies on the _RUNTIME_DIRECTORY_ environment variable being set by systemd to be properly passed to recursor. On systemd releases &lt;240 such as on Ubuntu 18.04 this is not set causing recursor to default to _/var/run/pdns-recursor_ instead of _pdns-recursor-&lt;instance&gt;_.
This causes recursor to exit with a socket-directory problem error and needs to be manually fixed, for example by specifying `socket-dir` in the instances configuration - which is unexpected.

### Environment

 - Operating system: Ubuntu 18.04.5 LTS
 - Software version: 4.3.4
 - Software source: PowerDNS repo, pdns-recursor 4.3.4-1pdns.bionic

### Steps to reproduce

1. Start virtual service instance on systemd &lt;240, e.g. Ubuntu 18.04, without specifying `socket-dir`
2. (Compare to 4.3.3 behavior - but yes, this had other issues)

### Expected behaviour
Recursor running just fine.

### Actual behaviour
Recursor quits:
`Problem with socket directory /var/run/pdns-recursor: it does not exist or cannot access; see https://docs.powerdns.com/recursor/upgrade.html#x-to-4-3-0-or-master`

### Other information
As discussed with the team it's not sure if this can be fixed or would just get documented as known issue with virtual hosting / virtual services under older systemd releases.

**Comment by phonedph1** [comment]
This looks like it probably bites EL7 too but 'works' so long as you have the non-instance one running. 

Side note: rec_control --config-name=xx checks /var/run/pdns-recursor/pdns_recursor-foo.controlsocket .. can this even take the runtime directory into account?
