### ISSUE TITLE
Confusion when DNSSEC key(s) exist for PRESIGNED zone

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#9489]
- Program: Authoritative
 - Issue type: Bug report

### Short description
If a PRESIGNED DNSSEC secured zone has key(s) attached to it, they are used to sign the zone. This is not indicated by `pdnsutil show-zone` output which shows only the AXFR'd keys from primary. To figure out you have such key(s) one has to do `pdnsutil list-keys`.

### Environment
 - Operating system: Debian 9.13
 - Software version:  PowerDNS Authoritative Server 4.2.2
 - Software source: PowerDNS

### Steps to reproduce
1. Add keys for a zone
2. Configure zone as slave
3. AXFR presigned zone

### Expected behaviour
Not sure what should happen, but at least `pdnsutil show-zone` should indicate what the keys are that are used.

### Actual behaviour
PowerDNS tools indicate that zone is using presigned data, and correctly show the presigned key from master. Yet the server uses existing DNSSEC keys to live sign the record data.

### Other information
Supporting live signing on slaves could be used to avoid an extra unsigned master, and could be used to support NSEC3 NARROW slaving?

**Comment by klaus3000** [comment]
Recently I reviewed the logic for 4.1, and with 4.1 (if I read the code correct), presigned data was used with higher priority. So when "PRESIGNED" domainmetadata was found, the keys were not used. Seems that changed with 4.2.

**Comment by mind04** [comment]
The problem is in most likely addDNSKey() https://github.com/PowerDNS/pdns/blob/master/pdns/packethandler.cc#L152 The code is not checking for the presence of PRESIGNED. This is also true for CDNSKEY and CDS.
