### ISSUE TITLE
AXFR and IXFR requests are logged at Error level

### ISSUE THREAD

**Issue by tih** [PowerDNS/pdns#9514]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When normal (expected) AXFR and IXFR requests arrive, they are logged at Error level, which causes console noise. There are also log entries that are made at the Warning level, that I would suggest be at Info.  I suspect that the logging related to AXFR and IXFR was accidentally left in a state that was useful during development, and would suggest that someone go through the pdns/tcpreceiver.cc file, and check all the Logger:: calls there.

### Environment
 - Operating system: NetBSD-current
 - Software version: git HEAD from master branch as per 2020-09-23
 - Software source: locally built from a clone of the PowerDNS git repo

### Steps to reproduce
1. Observation.

### Expected behaviour
Normal operations should not trigger Warning or Error log entries.

### Actual behaviour
In the log entries shown here, the "127.0.0.1" is because I use dnsdist to filter the requests, and it then performs the actual xfer call into the authoritative server locally. The requests are really from the secondary server for the zone, at my provider.

Sep 23 11:07:30 barsoom pdns[1775]: IXFR of domain 'hamartun.priv.no' initiated by 127.0.0.1:63701 with serial 2020091701
Sep 23 11:07:30 barsoom pdns[1775]: AXFR of domain 'hamartun.priv.no' allowed: client IP 127.0.0.1:63701 is in allow-axfr-ips
Sep 23 11:07:30 barsoom pdns[1775]: IXFR of domain 'hamartun.priv.no' to 127.0.0.1:63701 finished

The first and last of these are at Error level, which causes them to be printed on the console with my syslogd configuration. The middle one is at Warning level, which doesn't, but I still think the level is wrong; allowing an IP that's explicitly allowed is normal operations, and deserves a simple Info level log entry.

### Other information
None.

**Comment by klaus3000** [comment]
Comment from an administrator: Very often I have to look up the logs and inspect XFRs. When do they start, when do they finish. Both, on master and slave. Because often customers complain that zones were not fetched, or zones could not be fetched. Hence, if log levels are changes, the default PowerDNS log level should log XFR related tasks. Thanks

**Comment by Habbie** [comment]
@tih I agree with Info. Do you want to write a PR? :)

@klaus3000 that suggests that either you need to run at a higher log level than default, or we need more fine grained logging controls. I would entertain a PR for better controls if somebody made one.

**Comment by tih** [comment]
My suggested modifications are in PR #9658 .

**Comment by klaus3000** [comment]
I am fine with #9658. I run PDNS at Info log level.

**Comment by Habbie** [comment]
Closed in #9688
