### ISSUE TITLE
dnsdist Feature Request: DoH should work without Certificate

### ISSUE THREAD

**Issue by TorstenJahnke** [PowerDNS/pdns#9535]
I was not able to get this running because it seems for DoH is hardcoded a certifcate required. It would be awesome if it is possible do disable the need of certificate with a disable flag. If you run multiple instances behind haproxy or Windows IIS then this would increase the performance.

At the moment only Google's m13253 Server Project will support this DoH without certificate.

**Comment by rgacogne** [comment]
Running with DNS over plain HTTP is already supported by not passing any certificate or file to `addDOHLocal` [1].

[1]: https://dnsdist.org/reference/config.html#addDOHLocal
