### ISSUE TITLE
Problem with forward-zones in new recursor version

### ISSUE THREAD

**Issue by Kirecom** [PowerDNS/pdns#9538]
- Program: Recursor
 - Issue type: Bug report

### Short description
SERVFAIL on domains with forward zones with no explaination

### Environment

 - Operating system: Debian 10
 - Software version: 4.3.4, 4.2.4, 4.4.0 rc-1, 4.5.0 alpha0
 - Software source: PDNS Repo

### Steps to reproduce

1. Upgraded to a newer version from PDNS repo
2. Config is set up to forward-zones for some domains
3. It goes in servfail without send any query to the elected DNS servers for those domains

### Expected behaviour
It should forward the query to the right dns, but it doesn't happen. All newer versions from PDNS repo give me this problem

### Actual behaviour
 dig xx.xxx.xxx (elected forward domain) @10.0.0.1

; <<>> DiG 9.10.6 <<>> xxx.xxx.xxx @10.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 39906
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;xxx.xxx.xxx.		IN	A

;; Query time: 39 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Sun Sep 27 21:04:10 CEST 2020
;; MSG SIZE  rcvd: 49

### Other information
Software installed from Debian repos doesn't have this problem. Only all softwares from PDNS repo.

I'm available for every further info.

Thank you!

**Comment by pieterlexis** [comment]
Please provide the full config, including domain names so we can debug this issue. See our [policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/) on Open Source support.

**Comment by Kirecom** [comment]
# Autogenerated configuration file template
#################################
# allow-from    If set, only allow these comma separated netmasks to recurse
#
# allow-from=127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10

#################################
# allow-from-file       If set, load allowed netmasks from this file
#
# allow-from-file=

#################################
# any-to-tcp    Answer ANY queries with tc=1, shunting to TCP
#
# any-to-tcp=no

#################################
# api-config-dir        Directory where REST API stores config and zones
#
# api-config-dir=

#################################
# api-key       Static pre-shared authentication key for access to the REST API
#
# api-key=

#################################
# api-logfile   Location of the server logfile (used by the REST API)
#
# api-logfile=/var/log/pdns.log

#################################
# api-readonly  Disallow data modification through the REST API when set
#
# api-readonly=no

#################################
# auth-zones    Zones for which we have authoritative data, comma separated domain=file pairs 
#
# auth-zones=

#################################
# carbon-interval       Number of seconds between carbon (graphite) updates
#
# carbon-interval=30

#################################
# carbon-ourname        If set, overrides our reported hostname for carbon stats
#
# carbon-ourname=

#################################
# carbon-server If set, send metrics in carbon (graphite) format to this server IP address
#
# carbon-server=

#################################
# chroot        switch to chroot jail
#
# chroot=

#################################
# client-tcp-timeout    Timeout in seconds when talking to TCP clients
#
# client-tcp-timeout=2

#################################
# config-dir    Location of configuration directory (recursor.conf)
#
config-dir=/etc/powerdns

#################################
# config-name   Name of this virtual configuration - will rename the binary image
#
# config-name=

#################################
# cpu-map       Thread to CPU mapping, space separated thread-id=cpu1,cpu2..cpuN pairs
#
# cpu-map=

#################################
# daemon        Operate as a daemon
#
# daemon=no

#################################
# delegation-only       Which domains we only accept delegations from
#
# delegation-only=

#################################
# disable-packetcache   Disable packetcache
#
# disable-packetcache=no

#################################
# disable-syslog        Disable logging to syslog, useful when running inside a supervisor that logs stdout
#
# disable-syslog=no

#################################
# dnssec        DNSSEC mode: off/process-no-validate (default)/process/log-fail/validate
#
# dnssec=process-no-validate

#################################
# dnssec-log-bogus      Log DNSSEC bogus validations
#
# dnssec-log-bogus=no

#################################
# dont-query    If set, do not query these netmasks for DNS data
#
# dont-query=127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32

#################################
# ecs-ipv4-bits Number of bits of IPv4 address to pass for EDNS Client Subnet
#
# ecs-ipv4-bits=24

#################################
# ecs-ipv6-bits Number of bits of IPv6 address to pass for EDNS Client Subnet
#
# ecs-ipv6-bits=56

#################################
# ecs-scope-zero-address        Address to send to whitelisted authoritative servers for incoming queries with ECS prefix-length source of 0
#
# ecs-scope-zero-address=

#################################
# edns-outgoing-bufsize Outgoing EDNS buffer size
#
# edns-outgoing-bufsize=1680

#################################
# edns-subnet-whitelist List of netmasks and domains that we should enable EDNS subnet for
#
# edns-subnet-whitelist=

#################################
# entropy-source        If set, read entropy from this file
#
# entropy-source=/dev/urandom

#################################
# etc-hosts-file        Path to 'hosts' file
#
# etc-hosts-file=/etc/hosts

#################################
# export-etc-hosts      If we should serve up contents from /etc/hosts
#
# export-etc-hosts=off

#################################
# export-etc-hosts-search-suffix        Also serve up the contents of /etc/hosts with this suffix
#
# export-etc-hosts-search-suffix=

#################################
# forward-zones Zones for which we forward queries, comma separated domain=ip pairs
#
forward-zones=kirecom.net=127.0.0.1:54,ncainfra.cloud=192.168.100.201,nca.cloud=192.168.100.201

#################################
# forward-zones-file    File with (+)domain=ip pairs for forwarding
#
# forward-zones-file=

#################################
# forward-zones-recurse Zones for which we forward queries with recursion bit, comma separated domain=ip pairs
#
forward-zones-recurse=.=8.8.8.8;8.8.4.4

#################################
# gettag-needs-edns-options     If EDNS Options should be extracted before calling the gettag() hook
#
# gettag-needs-edns-options=no

#################################
# hint-file     If set, load root hints from this file
#
# hint-file=
hint-file=/usr/share/dns/root.hints

#################################
# include-dir   Include *.conf files from this directory
#
# include-dir=
include-dir=/etc/powerdns/recursor.d

#################################
# latency-statistic-size        Number of latency values to calculate the qa-latency average
#
# latency-statistic-size=10000

#################################
# local-address IP addresses to listen on, separated by spaces or commas. Also accepts ports.
#
local-address=10.0.0.1

#################################
# local-port    port to listen on
#
local-port=53

#################################
# log-common-errors     If we should log rather common errors
#
# log-common-errors=no

#################################
# log-rpz-changes       Log additions and removals to RPZ zones at Info level
#
# log-rpz-changes=no

#################################
# log-timestamp Print timestamps in log lines, useful to disable when running with a tool that timestamps stdout already
#
# log-timestamp=yes

#################################
# logging-facility      Facility to log messages as. 0 corresponds to local0
#
# logging-facility=

#################################
# loglevel      Amount of logging. Higher is more. Do not set below 3
#
# loglevel=6

#################################
# lowercase-outgoing    Force outgoing questions to lowercase
#
# lowercase-outgoing=no

#################################
# lua-config-file       More powerful configuration options
#
#lua-config-file=/etc/powerdns/recursor.lua

#################################
# lua-dns-script        Filename containing an optional 'lua' script that will be used to modify dns answers
#
# lua-dns-script=

#################################
# max-cache-entries     If set, maximum number of entries in the main cache
#
max-cache-entries=1500000

#################################
# max-cache-ttl maximum number of seconds to keep a cached entry in memory
#
max-cache-ttl=15

#################################
# max-mthreads  Maximum number of simultaneous Mtasker threads
#
# max-mthreads=2048

#################################
# max-negative-ttl      maximum number of seconds to keep a negative cached entry in memory
#
# max-negative-ttl=3600

#################################
# max-packetcache-entries       maximum number of entries to keep in the packetcache
#
# max-packetcache-entries=500000

#################################
# max-qperq     Maximum outgoing queries per query
#
# max-qperq=50

#################################
# max-recursion-depth   Maximum number of internal recursion calls per query, 0 for unlimited
#
# max-recursion-depth=40

#################################
# max-tcp-clients       Maximum number of simultaneous TCP clients
#
# max-tcp-clients=128

#################################
# max-tcp-per-client    If set, maximum number of TCP sessions per client (IP address)
#
# max-tcp-per-client=0

#################################
# max-tcp-queries-per-connection        If set, maximum number of TCP queries in a TCP connection
#
# max-tcp-queries-per-connection=0

#################################
# max-total-msec        Maximum total wall-clock time per query in milliseconds, 0 for unlimited
#
# max-total-msec=7000

#################################
# max-udp-queries-per-round     Maximum number of UDP queries processed per recvmsg() round, before returning back to normal processing
#
# max-udp-queries-per-round=10000

#################################
# minimum-ttl-override  Set under adverse conditions, a minimum TTL
#
# minimum-ttl-override=0

#################################
# network-timeout       Wait this number of milliseconds for network i/o
#
# network-timeout=1500

#################################
# no-shuffle    Don't change
#
# no-shuffle=off

#################################
# non-local-bind        Enable binding to non-local addresses by using FREEBIND / BINDANY socket options
#
# non-local-bind=no

#################################
# nsec3-max-iterations  Maximum number of iterations allowed for an NSEC3 record
#
# nsec3-max-iterations=2500

#################################
# packetcache-servfail-ttl      maximum number of seconds to keep a cached servfail entry in packetcache
#
# packetcache-servfail-ttl=60

#################################
# packetcache-ttl       maximum number of seconds to keep a cached entry in packetcache
#
# packetcache-ttl=3600

#################################
# pdns-distributes-queries      If PowerDNS itself should distribute queries over threads
#
# pdns-distributes-queries=yes

#################################
# processes     Launch this number of processes (EXPERIMENTAL, DO NOT CHANGE)
#
# processes=1

#################################
# query-local-address   Source IP address for sending queries
#
# query-local-address=0.0.0.0

#################################
# query-local-address6  Source IPv6 address for sending queries. IF UNSET, IPv6 WILL NOT BE USED FOR OUTGOING QUERIES
#
# query-local-address6=

#################################
# quiet Suppress logging of questions and answers
#
quiet=yes

#################################
# reuseport     Enable SO_REUSEPORT allowing multiple recursors processes to listen to 1 address
#
# reuseport=no

#################################
# root-nx-trust If set, believe that an NXDOMAIN from the root means the TLD does not exist
#
# root-nx-trust=yes

#################################
# security-poll-suffix  Domain name from which to query security update notifications
#
# security-poll-suffix=secpoll.powerdns.com.
security-poll-suffix=

#################################
# serve-rfc1918 If we should be authoritative for RFC 1918 private IP space
#
# serve-rfc1918=yes

#################################
# server-down-max-fails Maximum number of consecutive timeouts (and unreachables) to mark a server as down ( 0 => disabled )
#
# server-down-max-fails=64

#################################
# server-down-throttle-time     Number of seconds to throttle all queries to a server after being marked as down
#
# server-down-throttle-time=60

#################################
# server-id     Returned when queried for 'id.server' TXT or NSID, defaults to hostname
#
# server-id=

#################################
# setgid        If set, change group id to this gid for more security
#
setgid=pdns

#################################
# setuid        If set, change user id to this uid for more security
#
setuid=pdns

#################################
# signature-inception-skew      Allow the signture inception to be off by this number of seconds
#
# signature-inception-skew=0

#################################
# single-socket If set, only use a single socket for outgoing queries
#
# single-socket=off

#################################
# snmp-agent    If set, register as an SNMP agent
#
# snmp-agent=no

#################################
# snmp-master-socket    If set and snmp-agent is set, the socket to use to register to the SNMP master
#
# snmp-master-socket=

#################################
# soa-minimum-ttl       Don't change
#
# soa-minimum-ttl=0

#################################
# socket-dir    Where the controlsocket will live, /var/run when unset and not chrooted
#
# socket-dir=

#################################
# socket-group  Group of socket
#
# socket-group=

#################################
# socket-mode   Permissions for socket
#
# socket-mode=

#################################
# socket-owner  Owner of socket
#
# socket-owner=

#################################
# spoof-nearmiss-max    If non-zero, assume spoofing after this many near misses
#
# spoof-nearmiss-max=20

#################################
# stack-size    stack size per mthread
#
# stack-size=200000

#################################
# statistics-interval   Number of seconds between printing of recursor statistics, 0 to disable
#
# statistics-interval=1800

#################################
# stats-ringbuffer-entries      maximum number of packets to store statistics for
#
# stats-ringbuffer-entries=10000

#################################
# tcp-fast-open Enable TCP Fast Open support on the listening sockets, using the supplied numerical value as the queue size
#
# tcp-fast-open=0

#################################
# threads       Launch this number of threads
#
threads=15

#################################
# trace if we should output heaps of logging. set to 'fail' to only log failing domains
#
# trace=off

#################################
# udp-truncation-threshold      Maximum UDP response size before we truncate
#
# udp-truncation-threshold=1680

#################################
# use-incoming-edns-subnet      Pass along received EDNS Client Subnet information
#
# use-incoming-edns-subnet=no

#################################
# version-string        string reported on version.pdns or version.bind
#
# version-string=PowerDNS Recursor 4.1.11

#################################
# webserver     Start a webserver (for REST API)
#
# webserver=no

#################################
# webserver-address     IP Address of webserver to listen on
#
# webserver-address=127.0.0.1

#################################
# webserver-allow-from  Webserver access is only allowed from these subnets
#
# webserver-allow-from=127.0.0.1,::1

#################################
# webserver-password    Password required for accessing the webserver
#
# webserver-password=

#################################
# webserver-port        Port of webserver to listen on
#
# webserver-port=8082

#################################
# write-pid     Write a PID file
#
# write-pid=yes


Here it is.

Forwarders are in a local net connected by IPSEC VPN.

Thanks

**Comment by omoerbeek** [comment]
Can you please specify *exactly* which version does not work for you? Thanks

**Comment by Kirecom** [comment]
The versions are specified in the first post, I Updated to 4.2.4 from PDNS Repo when the issue started.

I tried with all other versions and the only one not giving me issues is the one coming from Debian default repos.

Thanks

**Comment by omoerbeek** [comment]
> The versions are specified in the first post, I Updated to 4.2.4 from PDNS Repo when the issue started.
> 
> I tried with all other versions and the only one not giving me issues is the one coming from Debian default repos.
> 
> Thanks

That does not tell me which version works for you. I could go and lookup the version from debian but you have the number right at hand. Why make it more difficult than needed for us?

**Comment by Kirecom** [comment]
Sorry, 4.1.11 is the version that works for me.

I take all the latest versions to test, so my intention isn't to make anything more difficult. It's just the first time I post something to ask help troubleshooting an issue after years using PDNS products successfully. Be patient pls! :(

Sorry for the inconvenience, I remain available for info and tests.

**Comment by pieterlexis** [comment]
Can you check if there's any config in `/etc/powerdns/recursor.d`?

And are you able to provide a trace for a failing lookup. This can be done by setting `trace=yes` in the config and restarting. You can also set tracing for a specific domain at runtime by running `rec_control trace-regex 'kirecom\.net\.$'` and looking in the log.

**Comment by Kirecom** [comment]
Hi, 

recursor.d folder is empty.

kirecom.net forward zone does not give me any error. On 127.0.0.1:54 forward is ok.

I have error on ncainfra.cloud for example, that forwards to 10.4.4.201:53.

dig mysql.ncainfra.cloud @10.0.0.1

; <<>> DiG 9.10.6 <<>> mysql.ncainfra.cloud @10.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 19184
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mysql.ncainfra.cloud.		IN	A

;; Query time: 40 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Sep 28 12:26:36 CEST 2020
;; MSG SIZE  rcvd: 49

Rec control gives me this output.

rec_control trace-regex 'mysql.\ncainfra\.cloud\.$'
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok

But dig to 10.4.4.201 is ok.

 dig mysql.ncainfra.cloud @10.4.4.201

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> mysql.ncainfra.cloud @10.4.4.201
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35075
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;mysql.ncainfra.cloud.          IN      A

;; ANSWER SECTION:
mysql.ncainfra.cloud.   14      IN      A       192.168.100.5

;; Query time: 34 msec
;; SERVER: 10.4.4.201#53(10.4.4.201)
;; WHEN: lun set 28 12:28:28 CEST 2020
;; MSG SIZE  rcvd: 65


This is what i get. Please tell me if i could do more tests to troubleshoot.

Thank you so much!

**Comment by pieterlexis** [comment]
> Rec control gives me this output.

perfect, now query that server and check the logs for the trace :)

**Comment by Kirecom** [comment]
This i what i get into syslog...

Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: 6 [3/1] question for 'mysql.ncainfra.cloud|A' from 10.0.0.2:64972
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Wants DNSSEC processing, auth data in query for A
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Looking for CNAME cache hit of 'mysql.ncainfra.cloud|CNAME'
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Looking for DNAME cache hit of 'mysql.ncainfra.cloud|DNAME' or its ancestors
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: No CNAME or DNAME cache hit of 'mysql.ncainfra.cloud' found
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: No cache hit for 'mysql.ncainfra.cloud|A', trying to find an appropriate NS record
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: initial validation status for mysql.ncainfra.cloud is Indeterminate
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Cache consultations done, have 1 NS to contact
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Domain has hardcoded nameserver
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud.: Nameservers: -192.168.100.201:53(17.58ms)
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Resolved 'ncainfra.cloud' NS (empty) to: 192.168.100.201
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Trying IP 192.168.100.201:53, asking 'mysql.ncainfra.cloud|A'
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Got 2 answers from (empty) (192.168.100.201), rcode=0 (No Error), aa=0, in 17ms
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] Removing record 'mysql.ncainfra.cloud|A|192.168.100.5' in the answer section without the AA bit set received from ncainfra.cloud
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: OPT answer '.' from 'ncainfra.cloud' nameservers
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: determining status after receiving this packet
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: Failed to resolve via any of the 1 offered NS at level 'ncainfra.cloud'
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] mysql.ncainfra.cloud: failed (res=-1)
Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: 6 [3/1] answer to question 'mysql.ncainfra.cloud|A': 0 answers, 1 additional, took 1 packets, 17.645 netw ms, 18.389 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=2

**Comment by pieterlexis** [comment]
>  Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] Removing record 'mysql.ncainfra.cloud|A|192.168.100.5' in the answer section without the AA bit set received from ncainfra.cloud

Is the server you forward to an auth? If so, it does not set the AA-bit (but it should).

If it is a recursor, you'll need to move this forward config to `forward-recurse`.

In recent versions, we made checking the AA-bit (Authoritative Answer) more strict.

**Comment by Kirecom** [comment]
Thank you, i fixed moving it to forward-zones-recurse in this way

forward-zones-recurse=kirecom.net=127.0.0.1:54,ncainfra.cloud=192.168.100.201;192.168.100.204,nca.cloud=192.168.100.201;192.168.100.204,.=8.8.8.8;8.8.4.4 (i added a second dns)

Now it's working as expected! :D

$ dig mysql.ncainfra.cloud  @10.0.0.1

; <<>> DiG 9.10.6 <<>> mysql.ncainfra.cloud @10.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8314
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mysql.ncainfra.cloud.		IN	A

;; ANSWER SECTION:
mysql.ncainfra.cloud.	15	IN	A	192.168.100.5

;; Query time: 37 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Sep 28 13:24:46 CEST 2020
;; MSG SIZE  rcvd: 65


Thank you so much!

**Comment by pieterlexis** [comment]
You're welcome!

**Comment by laurretang** [comment]
> > Sep 28 12:45:45 KIRECOM1 pdns_recursor[14576]: [3] Removing record 'mysql.ncainfra.cloud|A|192.168.100.5' in the answer section without the AA bit set received from ncainfra.cloud
> 
> Is the server you forward to an auth? If so, it does not set the AA-bit (but it should).
> 
> If it is a recursor, you'll need to move this forward config to `forward-recurse`.
> 
> In recent versions, we made checking the AA-bit (Authoritative Answer) more strict.

Hi, Pieterlexis. 
I have an idea, which can we change "forward-zones" or "forward-zones-recurse" dynamicly through some Lua script?
For that, we can decide to send domains to some one ns server. Especial when a subdomain can be handled by different ns servers.

**Comment by Habbie** [comment]
Hello! You are replying to a closed ticket. Comments on closed tickets tend to get forgotten. Please see my previous reply to you for more information on how to file bugs, request features, or get help.
