### ISSUE TITLE
recursor lua: setting rcode NXDOMAIN lost when followupFunction is followCNAMERecords

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#9547]
- Program: Recursor 4.3.0
 - Issue type: Bug report

### Short description

```
function preresolve(dq)
dq.rcode = pdns.NXDOMAIN
dq.followupFunction = "followCNAMERecords"
dq.variable = true
return true
end
```

returns

```
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 62032
;; Flags: qr rd ra; QUERY: 1; ANSWER: 0; AUTHORITY: 0; ADDITIONAL: 1
```

If I disable the followupFunction line it correctly returns `NXDOMAIN`.

I would have expected that if there were no CNAMEs in the response the followupFunction should not change the other parameters specified?

**Comment by Habbie** [comment]
Why are you setting the followupFunction if you don't have CNAMEs?

**Comment by mzealey** [comment]
Some codepaths do set CNAMEs so we were just setting it for everything

**Comment by rgacogne** [comment]
Reproduced on master. I guess that's because `followCNAMERecords()` returns 0 when there is no CNAME to follow, overriding the existing rcode.

**Comment by mzealey** [comment]
is documented at https://doc.powerdns.com/recursor/lua-scripting/dq.html

**Comment by omoerbeek** [comment]
In the case of no CNAME reords I think it make sens to return the original rcode.
