### ISSUE TITLE
Ability to set DNS Extended errors via LUA in recursor

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#9548]
- Program: Recursor
 - Issue type: Feature request

### Short description

When building DNS request filtering software it would be nice to be able to implement https://tools.ietf.org/id/draft-ietf-dnsop-extended-error-05.html#rfc.section.4.5.1 however it doesn't appear there is any way to set these headers in the recursor from lua at present. I guess a more general way of setting EDNS options would probably be the best way forwards?

Unmerged PR #7636 appears to do something roughly along these lines for dnsdist.

**Comment by omoerbeek** [comment]
Closed by #9673
