### ISSUE TITLE
After adding a PTR entry, several higher-level networks are created.

### ISSUE THREAD

**Issue by dturcinovic** [PowerDNS/pdns#9567]
after creating a record for an IPv6 address several reverse entries are added automatically. 

### Is this intentional? 

0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa
4.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.0.1.8.8.f.0.0.0.a.2.ip6.arpa	PTR	jascha.de	3600	0	NULL	0	NULL	1	NULL	NULL

**Comment by phonedph1** [comment]
Yes, this is to support empty non-terminals. 

Ask on the mailing list or IRC if you need more information.

**Comment by pieterlexis** [comment]
What @phonedph1 said: https://doc.powerdns.com/authoritative/backends/generic-sql.html#rules-for-filling-out-dnssec-fields
