### ISSUE TITLE
Clients can not update DDNS using PDNS Authorative/Recursor 4.2.1 running on the same host on the same interface

### ISSUE THREAD

**Issue by agoulak** [PowerDNS/pdns#9575]
- Program: Authoritative, Recursor
 - Issue type: Bug report

### Short description

Clients can not update DDNS using PDNS Authorative/Recursor 4.2.1 running on the same system on the same interface.
If we configure 2 external IPs on the same interface, and have Authoritative use one of them, listening on port 53, and Recursor use another one on port 53 – DDNS works fine.

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.2.1
 - Software source: 
OS repository

### Steps to reproduce

1. pdns and pdns-recursor running on the same host, single interface, single IP, configured similar to Scenario 1 here https://doc.powerdns.com/authoritative/guides/recursion.html - DDNS does not work
2. we add additional IP to the same interface, configure pdns listen on port 53 on one interface, pdns-recursor listen on port 53 on the other interface - DDNS works fine
3. DHCP is running on a separate host, using isc-dhcp-server 4.4.1-

**Comment by Habbie** [comment]
Hi! As you also found out via IRC meanwhile, right now your options indeed are 'two IPs' or 'dnsdist'.

Closing this.
