### ISSUE TITLE
Delete zone error

### ISSUE THREAD

**Issue by Rudramandipudi** [PowerDNS/pdns#9598]
An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.
The following query generated an error:

DELETE 
FROM records_zone_templ 
WHERE domain_id='21339'

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'powerdns.records_zone_templ' doesn't exist

**Comment by pieterlexis** [comment]
PowerDNS does not have such a table. This might be a third-party web-frontend.
