### ISSUE TITLE
pdns-recursor forward to IDN zone 

### ISSUE THREAD

**Issue by run-stop** [PowerDNS/pdns#9600]
I have a working pdns-recursor (version 4.2.2) configuration that is forwarding requests for several local zones to my pdns server (version 4.3.0). For standard zones defined in latin1 character set, everything works as expected.
Now, I'm trying to create few zones defined in ASCII-Compatible Encoding (ACE) form (as domains contain unicode letters. Forwarding for these zones, unfortunately does not work.

My pdns-recursor configuration looks like this:
```
...
forward-zones=lab1.net=192.168.1.2:53
forward-zones+=lab2.net=192.168.1.2:53
forward-zones+=xn--3-7sbd2b.xn--e1apq=192.168.1.2:53
...

```
The first two zones work as expected. The third one does not get forwarded. Direct DNS query to pdns server in ACE format works as expected.
Any suggestions on how to fix this?

**Comment by pieterlexis** [comment]
This works for me on master (the forwarding, I do get a servfail because there is nothing listening :smile:):

```
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: using forwarder as NS
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: initial validation status for xn--3-7sbd2b.xn--e1apq is Indeterminate
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: Cache consultations done, have 1 NS to contact
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: Domain has hardcoded nameserver
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq.: Nameservers: -192.168.1.2:53(0.00ms)
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: Resolved 'xn--3-7sbd2b.xn--e1apq' NS (empty) to: 192.168.1.2
Oct 12 19:03:30 [1] xn--3-7sbd2b.xn--e1apq: Trying IP 192.168.1.2:53, asking 'xn--3-7sbd2b.xn--e1apq|A'
Oct 12 19:03:32 [1] xn--3-7sbd2b.xn--e1apq: timeout resolving after 1501.41msec
Oct 12 19:03:32 [1] xn--3-7sbd2b.xn--e1apq: Failed to resolve via any of the 1 offered NS at level 'xn--3-7sbd2b.xn--e1apq'
Oct 12 19:03:32 [1] xn--3-7sbd2b.xn--e1apq: failed (res=-1)
Oct 12 19:03:32 [1] QM xn--3-7sbd2b.xn--e1apq.|A child=xn--3-7sbd2b.xn--e1apq: Step3 Final resolve: Server Failure/0
Oct 12 19:03:32 3 [1/1] answer to question 'xn--3-7sbd2b.xn--e1apq|A': 0 answers, 1 additional, took 1 packets, 1501.41 netw ms, 1503.6 tot ms, 0 throttled, 1 timeouts, 0 tcp connections, rcode=2
```

can you show us a trace of this going wrong?

**Comment by run-stop** [comment]
@pieterlexis, looking at your log, I figured that I could turn on "trace" mode for pdns-recursor, and found two errors in my configuration:
1) An extra character in the recursor config file (difficult to spot).
2) Missing forward command for the reverse lookup zone.

Everything works now.
Thank you very much for your help!
