### ISSUE TITLE
lua functions: documentation missing (eg getRawLabels())

### ISSUE THREAD

**Issue by franklouwers** [PowerDNS/pdns#9608]
- Program: Recursor,
 - Issue type: Bug report

### Short description
Documentation is missing for some of the Lua-exposed functions.

### Environment

(Issue is documentation, so environment not relevant)

 - Operating system: all
 - Software version: master
 - Software source: PowerDNS repository

### Steps to reproduce
1. Try to find documentation for the lua function `getRawLabels()`

### Expected behaviour
1. Find Documentation for the `getRawLabels()` functions (https://github.com/PowerDNS/pdns/blob/master/pdns/lua-base4.cc#L65)

### Actual behaviour
1. No documentation was found

### Other information
Might need to review all Lua exposed functions at https://github.com/PowerDNS/pdns/blob/master/pdns/lua-base4.cc#L65 and check if basic documentation exists...

**Comment by omoerbeek** [comment]
Looks like we can steal from the auth docs here.
