### ISSUE TITLE
dnsdist ebpf dropping names longer than 72 chars

### ISSUE THREAD

**Issue by rage4** [PowerDNS/pdns#9626]
- Program: dnsdist
 - Issue type: Bug report

### Short description
dnsdist with eBPF enabled drops the UDP connection when query name is longer than 72 chars

### Environment
 - Operating system: Ubuntu 16.04 LTS x64
 - Software version: dnsdist 1.5.1
 - Software source: PowerDNS repository

### Steps to reproduce
Add following statement to dnsdist.conf

```
bpf = newBPFFilter(1024, 1024, 1024)
setDefaultBPFFilter(bpf)
```
run any .ip6.arpa. query
 
### Expected behaviour
dnsdist should correctly return the PTR value

### Actual behaviour
dnsdist drops the UDP connection

### Other information
it works correctly when using TCP

**Comment by Habbie** [comment]
I observed (externally from @rage4's machine) that a long v4 in-addr.arpa query also fails. The cutoff appears to be around 72 chars indeed.

**Comment by rgacogne** [comment]
I can reproduce the issue using our 1.5.1 packages on 16.04 and 20.04, but not on Arch. I'm guessing this is related to the removal of `BPF_LL_OFF` [1], and that somehow the issue arises when the eBPF byte code was generated with a different kernel version than the one in use, although it seems more complicated than that.

[1]: https://lists.openwall.net/netdev/2015/06/04/26
