### ISSUE TITLE
recursor returning exit code 0 when "reloading failed"

### ISSUE THREAD

**Issue by lotke** [PowerDNS/pdns#9634]
- Program: Recursor 
 - Issue type: Bug report

### Short description
When there is an error in zone and when you issue rec_control reload-zones
It returns "reloading failed, see log" and it returns exit code 0

### Environment

 - Operating system: Fedora 32
 - Software version: PowerDNS Recursor 4.3.1 
 - Software source: Official Fedora repo, pdns-recursor-4.3.1-1.fc32.x86_64

### Steps to reproduce

1.  Add auth-zones=testingzone.com=/etc/pdns-recursor/zone/testingzone.com.txt
2. Create testingzone.com.txt
testingzone.com.     3600    IN      SOA     testingzone.com. root.testingzone.com. 2035453389 7200 3600 86400 3600
testingzone.com.     1       IN      A       127.0.0.1
3. Start pdns recursor
4. Modify testingzone.com.txt by adding additional . (dot) to A record
testingzone.com.     3600    IN      SOA     testingzone.com. root.testingzone.com. 2035453389 7200 3600 86400 3600
testingzone.com..     1       IN      A       127.0.0.1
5. issue rec_control reload-zones ; echo $?
6. It will return this
reloading failed, see log
0

### Expected behaviour

It should return exit code 1
### Actual behaviour

rec_control reload-zones ; echo $?
reloading failed, see log
0

**Comment by omoerbeek** [comment]
It's a general issue, the recursor only returns a string and no separate error code. When continuing my work on  #9468 I'll solve this as well.

**Comment by omoerbeek** [comment]
#9468 closes this now.
