### ISSUE TITLE
x-our-latency is counter but should be gauge ?

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#9638]
https://github.com/PowerDNS/pdns/blob/c1fdf910b8fac26233157ee85d0d6e895c6ec9f8/pdns/recursordist/rec_metrics.hh#L401-L403

I believe this is a typo and it should be gauge like `qa-latency`?

**Comment by omoerbeek** [comment]
Not sure. The one is an average measured latency while the other is a cumulative amount of time spend. The latter can only increase while the former can go up and down.

**Comment by mzealey** [comment]
Both seem to be generated the same way?

```
pdns/pdns_recursor.cc:    g_stats.avgLatencyUsec=(1-1.0/g_latencyStatSize)*g_stats.avgLatencyUsec + (float)newLat/g_latencyStatSize;
pdns/pdns_recursor.cc:      g_stats.avgLatencyOursUsec=(1-1.0/g_latencyStatSize)*g_stats.avgLatencyOursUsec + (float)newLat/g_latencyStatSize;
pdns/pdns_recursor.cc:      g_stats.avgLatencyUsec=(1-1.0/g_latencyStatSize)*g_stats.avgLatencyUsec + 0.0; // we assume 0 usec
pdns/pdns_recursor.cc:      g_stats.avgLatencyOursUsec=(1-1.0/g_latencyStatSize)*g_stats.avgLatencyOursUsec + 0.0; // we assume 0 usec
```

**Comment by omoerbeek** [comment]
The description in `rec_metrics.hh` is confusing/wrong then. I'll take a closer look.

**Comment by omoerbeek** [comment]
Yes, it's a gauge, but please adapt the comment as well to be like the one in `qa-latency`
