### ISSUE TITLE
Add RPZ action to Protobuf message

### ISSUE THREAD

**Issue by nicko2n** [PowerDNS/pdns#9653]
- Program: Recursor
 - Issue type: Feature request

### Short description
In https://github.com/PowerDNS/pdns/issues/9058, the RPZ protobuf message was extended to include the RPZ trigger.
It would be useful to also add the Policy Kind (RPZ action) to the messages, similarly to what's done here:
https://github.com/PowerDNS/pdns/blob/rel/rec-4.4.x/pdns/filterpo.cc#L553

### Usecase
This would allow reviewing the log of a policy hit to understand what action was taken.

I will submit a pull request for the feature.

**Comment by omoerbeek** [comment]
I'd prefer an enum type PolicyKind in the protobuf definition, as is done for PolicyType.
