### ISSUE TITLE
Add the ability to give records from the cache with the original ttl, and not with the residual.

### ISSUE THREAD

**Issue by brlumen** [PowerDNS/pdns#9657]
- Program: Recursor
 - Issue type: Feature request

### Short description
Add the ability to give records from the cache with the original ttl, and not with the residual.

### Usecase
I would like to more evenly distribute the load on the recurser by caching responses on the client side.

### Description
In my case, there are 1-2 recursive servers that serve requests from ~ 8000 clients.
Clients have a local cache, but in the current implementation, the recursive server gives the leftover ttl for cache entries. This causes the client-side cache to run almost in sync with the recurser cache.
When the RR lifetime expires on the client, it sends a request to the recurser, and since the ttl of this RR expired synchronously for all ~ 8000 clients, they will send a request to the recurser
 almost simultaneously.
My suggestion should help "spread" the load over time, since the RR in the client's cache will not expire synchronously on all clients, and will largely depend on when the client asked for this RR.
I went through the RFCs, but I could not find an unambiguous position on this issue.
If I did not take into account something or my proposal contradicts something, then please feel free to close this issue.

Thank you for your attention and thank you for your work!

**Comment by mnordhoff** [comment]
Other approached to this issue have been discussed in #7535, FWIW.

**Comment by Habbie** [comment]
@brlumen please post your text as a comment on #7535. I'm closing this one.
