### ISSUE TITLE
auth: add LMDB to API testing

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#9666]
With #9664 and #9665 applied, the LMDB backend no longer crashes during normal or API testing, but some API tests fail.

With just #9665 applied, we still crash, so it appears 9665 is hiding some other issue beyond what 9664 fixes.

Also, `pdnsutil secure-zone example.com` segfaults if the zone does not exist.

**Comment by Habbie** [comment]
Part of the API failures are explained by `disabled` not working at all in LMDB.

**Comment by Habbie** [comment]
This also makes sense (although it fixes nothing) - or a rewrite of that function:
```diff
diff --git a/modules/lmdbbackend/lmdbbackend.cc b/modules/lmdbbackend/lmdbbackend.cc
index daba3ae16..87f0f480e 100644
--- a/modules/lmdbbackend/lmdbbackend.cc
+++ b/modules/lmdbbackend/lmdbbackend.cc
@@ -241,7 +241,9 @@ std::string serToString(const vector<DNSResourceRecord>& rrs)
 static inline size_t serOneRRFromString(const string_view& str, DNSResourceRecord& rr)
 {
   uint16_t len;
+  if (str.size() < 2) throw std::out_of_range("serialized RR is too short for length prefix");
   memcpy(&len, &str[0], 2);
+  if (str.size() < (2 + len + 7)) throw std::out_of_range("serialized RR is too short for full content length");
   rr.content.assign(&str[2], len);    // len bytes
   memcpy(&rr.ttl, &str[2] + len, 4);
   rr.auth = str[2 + len + 4];
```

**Comment by Habbie** [comment]
A useful testcase for 9664/9665:
```
$ cat tests/pdnsutil-delete-nonpresent-rrset/command 
#!/bin/sh

$PDNSUTIL --config-dir=. --config-name=lmdb list-zone minimal.com 2>&1
echo $?

$PDNSUTIL --config-dir=. --config-name=lmdb delete-rrset minimal.com test A

$PDNSUTIL --config-dir=. --config-name=lmdb list-zone minimal.com 2>&1
echo $?
```

**Comment by zeha** [comment]
> Part of the API failures are explained by `disabled` not working at all in LMDB.

When I last looked at the LMDB code, `disabled` was all wrong on the LMDB side. Not just "not implemented".

**Comment by pieterlexis** [comment]
@Habbie I think we can close this?

**Comment by Habbie** [comment]
> @Habbie I think we can close this?

Thanks, instead I've updated the title to reflect the part we haven't done yet :)
