### ISSUE TITLE
Auth: Export ringbuffer events also as counters

### ISSUE THREAD

**Issue by aj-gh** [PowerDNS/pdns#9675]
- Program: Authoritative
 - Issue type: Feature request

### Short description
Auth maintains various events in ringbuffers. For about two of them matching metric counters exist while for the remaining ones they seem to be missing.

### Usecase

Graphing of `nxdomain-queries` and `unauth-queries` via carbon exports

### Description

`servfail-queries` exists as a ringbuffer and has `servfail-packets` as matching metric.
I seem to be missing the same for `nxdomain-queries` and `unauth-queries` - would be nice if that could be added.

**Comment by Habbie** [comment]
noerror-queries also appears to lack a related counter.
