### ISSUE TITLE
Serial number gets incremented twice, but not synced to backend

### ISSUE THREAD

**Issue by bjmgeek** [PowerDNS/pdns#9726]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

I can increase the serial and it shows a number. That number is also written to the backend (i.e. the database).  However, when querying the server, or in an AXFR to a secondary, the number is 2 higher.

### Environment

 - Operating system: Linux
 - Software version: 4.1.6-3
 - Software source:  debian buster
I'm using the gsqlite backend.

### Steps to reproduce

1. Increase the serial number with pdnsutil edit-zone or pdnsutil increase-serial
2. look in the database for the SOA record:
root@lab:~# sqlite3 pdns.sqlite3 "select * from records where type='SOA' and name='meadowfen.farm'"
3. query the server with dig:
root@lab:~# dig +short @127.0.0.1 meadowfen.farm soa

config file:
 allow-axfr-ips=
 disable-axfr=no
api=yes
api-key=XXXXXX
launch+=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=on
gsqlite3-pragma-foreign-keys=on
slave=on

launch=
log-dns-details=yes
master=yes
security-poll-suffix=
setgid=pdns

### Expected behaviour
The serial number from the database should match the SOA record returned by the server

### Actual behaviour
The serial number returned by the server is 2 higher than the one in the database.

### Other information
```
root@lab:~# dig +short @127.0.0.1 meadowfen.farm soa
ns2.meadowfen.farm. bminton.meadowfen.farm. 2020111325 10800 3600 604800 86400
root@lab:~# sqlite3 pdns.sqlite3 "select * from records where type='SOA' and name='meadowfen.farm'"
25566|4|meadowfen.farm|SOA|ns2.meadowfen.farm. bminton.meadowfen.farm. 2020111323 10800 3600 604800 86400|7200|0||0|farm meadowfen|1

```

**Comment by omoerbeek** [comment]
I suppose you have a DNSSEC signed zone in live-signing mode. In that case auth will increase serials on it's own. https://docs.powerdns.com/authoritative/dnssec/operational.html#possible-soa-edit-values

**Comment by Habbie** [comment]
Yes, this looks like you have SOA-EDIT set to INCEPTION-INCREMENT.

Closing this as it looks like correct behaviour. If you have more questions, please find us on IRC or the pdns-users mailing list. Details for both are at https://www.powerdns.com/opensource.html

**Comment by bjmgeek** [comment]
The problem is not the increment-by-two behavior, but that the value stored in the database doesn't match what's being served.  So, for instance, if the serial number of a zone is 2020111001 and I use increase-serial it stores 2020111002 in the database, but serves 2020111003.  Then, the next time I call increase-serial, it sees 2020111002, and increases it to 2020111003.
So, I get that when the zone is re-signed, the idea is to increment the serial number served to clients, but why would the new value not be stored in the database?  That way tools like edit-zone would show the current value.

**Comment by Habbie** [comment]
This is how SOA-EDIT works. It never writes the new number back to the database - it calculates a new one whenever this is necessary. This way, it can also work on readonly db replication secondaries etc.

**Comment by bjmgeek** [comment]
In that case, I would like to propose a feature request for the show-zone utility to show the actual serial number being served.  
Here's the output of show-zone:
root@lab:~# pdnsutil show-zone meadowfen.farm
This zone is owned by internal
This is a Master zone
Last SOA serial number we notified: 2020111323 == 2020111323 (serial in the database)

But, that's not the number we're serving:
root@lab:~# dig +short @127.0.0.1 meadowfen.farm soa
ns2.meadowfen.farm. bminton.meadowfen.farm. 2020111325 10800 3600 604800 86400

and my downstream (non-powerdns) server sees 2020111325.

**Comment by Habbie** [comment]
> In that case, I would like to propose a feature request for the show-zone utility to show the actual serial number being served.

That makes sense to me! Can you make a new ticket for that?

**Comment by bjmgeek** [comment]
I've created https://github.com/PowerDNS/pdns/issues/9739 for that feature request.

**Comment by Habbie** [comment]
Thanks!
