### ISSUE TITLE
SAD DNS attack

### ISSUE THREAD

**Issue by dtouzeau** [PowerDNS/pdns#9736]
What is the best way to protect PowerDNS against SAD DNS attack ?

[https://thehackernews.com/2020/11/sad-dns-new-flaws-re-enable-dns-cache.html](url)

**Comment by Habbie** [comment]
PowerDNS already implements the connected sockets suggested in the SAD DNS paper. The other part of the fix is the kernel patch referred in the paper - so talk to your OS vendor.

**Comment by dtouzeau** [comment]
thanks !!

**Comment by rgacogne** [comment]
For what it's worth, the PowerDNS Recursor also has a mechanism to detect and foil attempts at guessing the QID, see https://docs.powerdns.com/recursor/settings.html#spoof-nearmiss-max
