### ISSUE TITLE
rec: qname minimization chases CNAMEs on intermediate names

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#9742]
- Program: Recursor
 - Issue type: Bug report

### Short description
While looking up `a.b.c.example.com`, recursor with QM also asks for `c` and `b.c`. If any of those have a CNAME, we uselessly chase that CNAME.

### Environment
 - Software version: any

### Steps to reproduce
1. tcpdump or enable trace or monitor queries some other way
2. ask for `terminal.cname.ent.experiments.powerdns.space`

### Expected behaviour
No query to the example.com NSes.

### Actual behaviour
Queries to the example.com NSes

**Comment by Habbie** [comment]
Duplicate of #8699

**Comment by omoerbeek** [comment]
Fixed by #9790
