### ISSUE TITLE
Cannot start second PDNS instance independently of first.

### ISSUE THREAD

**Issue by aashish791** [PowerDNS/pdns#9750]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When trying to start second pdns instance service independently, it is getting failed because the socket directory(/var/run/pdns) is not getting created.

### Environment
 - Operating system: Centos 7.8
 - Software version: 4.4.0-0
 - Software source: PowerDNS repository

### Steps to reproduce
1. When we start 1st pdns instance, it creates a socket directory and then we can start 2nd pdns instance which works fine.
2. Stop all pdns instance and then try to start 2nd pdns instance which fails due to missing socket directory as it was removed when we stopped 1st instance.

### Expected behaviour
All pdns instance should start/stop on its own.

Logs:

1) Nov 19 12:59:34 dns-aus-3 pdns-second[218250]: This is a standalone pdns
Nov 19 12:59:34 dns-aus-3 pdns-second[218250]: Unable to create socket directory (/var/run/pdns/) and it does not exist yet

**Comment by pieterlexis** [comment]
Please expand on _how_ you start the second instance. And have you read the systemd section of https://doc.powerdns.com/authoritative/guides/virtual-instances.html#starting-virtual-instances-with-systemd ?

**Comment by aashish791** [comment]
Config file name of 2nd instance: /etc/pdns/pdns-second.conf
Command used to start: sudo systemctl start pdns@second 

Systemd file content:

`[Unit]
Description=PowerDNS Authoritative Server %i
Documentation=man:pdns_server(1) man:pdns_control(1)
Documentation=https://doc.powerdns.com
Wants=network-online.target
After=network-online.target mysqld.service postgresql.service slapd.service mariadb.service

[Service]
ExecStart=/usr/sbin/pdns_server --config-name=%i --guardian=no --daemon=no --log-timestamp=no --write-pid=no
SyslogIdentifier=pdns_server-%i
User=pdns
Group=pdns
Type=notify
Restart=on-failure
RestartSec=1
StartLimitInterval=0
RuntimeDirectory=pdns-%i

# Sandboxing
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_CHOWN
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_CHOWN
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
# Setting PrivateUsers=true prevents us from opening our sockets
ProtectHome=true
# ProtectSystem=full will disallow write access to /etc and /usr, possibly
# not being able to write slaved-zones into sqlite3 or zonefiles.
ProtectSystem=full
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target`

I have gone through the doc but there no mention of any configuration related to the socket directory. 

Let me know if any additional information is needed.

**Comment by pieterlexis** [comment]
You're probably running into #9485, which happens on older systemd versions.

can you add a drop-in at `/etc/systemd/system/pdns@.service.d/runtimedir.conf` with this content:

```
[Service]
ExecStart=--socket-dir=/var/run/pdns-%i
```

then do a `systemctl daemon-reload` and try again?

**Comment by aashish791** [comment]
Let me give it a try.

**Comment by aashish791** [comment]
Instead of creating a new systemd service file I add in the existing systemd file which I pasted above.

Before:

`ExecStart=/usr/sbin/pdns_server --config-name=%i --guardian=no --daemon=no --log-timestamp=no --write-pid=no`

After:

`ExecStart=/usr/sbin/pdns_server --config-name=%i --guardian=no --daemon=no --log-timestamp=no --write-pid=no --socket-dir=/var/run/pdns-%i`

The above changes worked fine on the server and now I am able to start 2nd instance independently.

Thanks for quick help.

**Comment by pieterlexis** [comment]
excellent!

If you need further support, please send an email to the [pdns-users mailinglist](https://mailman.powerdns.com/mailman/listinfo/pdns-users), or join us on [IRC](ircs://irc.oftc.net:6697/#powerdns).
