### ISSUE TITLE
Need help in understanding receiver-threads & distributor-threads paramter for Auth DNS server

### ISSUE THREAD

**Issue by aashish791** [PowerDNS/pdns#9769]
- Program: Authoritative
 - Issue Type: Bug report

### Short description
Setting the receiver-threads value to 10 does not utilize CPU resources optimally.

### Environment
 - Operating system: CentOS 7.8
 - Software version: 4.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
1) Set receiver-threads=10 and disabled distributor-threads parameter to see if all 10 CPU cores have been utilized.
2) We have 64 CPU core server on which we are running 4 virtual instances, so we need the optimal value of receiver-threads & distributor-threads parameters so as to fully utilize the server resources.
3) With this setting I am only getting DNS QPS as 1k.
4) Please suggest as to what will be the optimal value for receiver-threads & distributor-threads and how will this impact the HIT/MISS ratio.

Logs:

> 
123875 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.04 pdns_server                                                                      47 33   0:00
123876 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.27 pdns/ctrlListen                                                                  47  5   0:00
123877 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.00 pdns/ctrlListen                                                                  47 49   0:00
123878 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.00 pdns/webserver                                                                   47 50   0:00
123879 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.26 pdns/statHelper                                                                  47 11   0:00
123881 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.00 pdns/tcpnameser                                                                  47 52   0:00
123882 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.15 pdns/receiver                                                                    47  4   0:02
123883 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.23 pdns/receiver                                                                    47 10   0:02
123884 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.09 pdns/receiver                                                                    47 40   0:02
123885 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.01 pdns/receiver                                                                    47  7   0:02
123886 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.30 pdns/receiver                                                                    47  9   0:02
123887 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:17.37 pdns/distributo                                                                  47  4   0:17
123888 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.09 pdns/receiver                                                                    47  3   0:02
123889 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:19.41 pdns/distributo                                                                  47  7   0:19
123890 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.09 pdns/receiver                                                                    47  6   0:02
123891 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:15.05 pdns/distributo                                                                  47 19   0:15
123892 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.16 pdns/receiver                                                                    47  8   0:02
123893 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:18.67 pdns/distributo                                                                  47 19   0:18
123894 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.09 pdns/receiver                                                                    47 14   0:02
123895 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:17.63 pdns/distributo                                                                  47 28   0:17
123896 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:23.78 pdns/distributo                                                                  47  4   0:23
123897 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:02.10 pdns/receiver                                                                    47  5   0:02
123898 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:22.59 pdns/distributo                                                                  47 19   0:22
123899 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:00.14 pdns/carbonDump                                                                  47  1   0:00
123900 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:16.90 pdns/distributo                                                                  47 10   0:16
123901 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:18.07 pdns/distributo                                                                  47 26   0:18
123902 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:15.18 pdns/distributo                                                                  47 15   0:15
123915 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:17.12 pdns/distributo                                                                  47 11   0:17
123916 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:19.82 pdns/distributo                                                                  47 11   0:19
123917 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:15.05 pdns/distributo                                                                  47 20   0:15
123921 pdns      20   0 3534384  50372   5988 S  0.0  0.0   0:18.42 pdns/distributo                                                                  47  3   0:18

**Comment by Habbie** [comment]
> Software version: 4.4.0

We haven't released 4.4.0 yet..

Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
