### ISSUE TITLE
Security status domain for '4.4.0-beta1' not found

### ISSUE THREAD

**Issue by xelatirdan** [PowerDNS/pdns#9772]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Error message in power-dns logs:
```
Failed to retrieve security status update for '4.4.0-beta1' on 'auth-4.4.0-beta1.security-status.secpoll.powerdns.com.': RCODE was Non-Existent domain
```

### Environment
 - Operating system: Debian 10
 - Software version: PowerDNS Authoritative Server 4.4.0-beta1 (C) 2001-2020 PowerDNS.COM BV
 - Software source: PowerDNS repository

### Steps to reproduce
Install new version from official debian repo
```
deb [arch=amd64] http://repo.powerdns.com/debian buster-auth-44 main
```

### Expected behaviour
This error don't appear

**Comment by Habbie** [comment]
Thank you for noticing and reporting! We have published the updated zone now. The negative TTL of 10800 means it might take a few hours before you notice.
