### ISSUE TITLE
GSQLBackend unable to find before/after (after): Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '>')

### ISSUE THREAD

**Issue by Daniel15** [PowerDNS/pdns#9777]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Several (but not all) of my DNS servers are throwing this error quite frequently:

```
Backend reported permanent error which prevented lookup (GSQLBackend unable to find before/after (after) for domain_id 8 and qname 'n7': Could not execute mysql statement: select ordername from records where ordername > ? and domain_id=? and disabled=0 and ordername is not null order by 1 asc limit 1: Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '>'), aborting
```

Collation on the ordername looks fine, it's set to `latin1_bin` as per the documented PowerDNS schema:
```
Create Table: CREATE TABLE `records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `domain_id` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `content` varchar(64000) DEFAULT NULL,
  `ttl` int DEFAULT NULL,
  `prio` int DEFAULT NULL,
  `change_date` int DEFAULT NULL,
  `disabled` tinyint(1) DEFAULT '0',
  `ordername` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `auth` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `nametype_index` (`name`,`type`),
  KEY `domain_id` (`domain_id`),
  KEY `ordername` (`ordername`)
) ENGINE=InnoDB AUTO_INCREMENT=17266 DEFAULT CHARSET=latin1
```

And if I run the same query in the MySQL CLI, it also works fine:

```
mysql> select ordername from records where ordername > 'n7' and domain_id=8 and disabled=0 and ordername is not null order by 1 asc limit 1;
+-----------+
| ordername |
+-----------+
| ns1       |
+-----------+
1 row in set (0.00 sec)
```

I'm only seeing this on some of my DNS servers, not all of them. 

I originally thought it was because I set UTF-8 as the default collation on my MySQL server, since most apps these days use UTF-8:
```
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
```

However, this turned out to not be the case, as I was able to repro on a server that was no configured this way.

I've been doing some more digging, and as far as I can tell, this error only happens after upgrading from MySQL 8.0.21 to 8.0.22. I upgraded MySQL client, server and libraries on a server that was previously not experiencing this error, and the same error started happening. However, I'm unable to find anything in [the MySQL changelogs](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-22.html) that would explain this.

### Environment
 - Operating system: Debian testing (bullseye)
 - Software version: PowerDNS 4.3.1, MySQL 8.0.21 or 8.0.22
 - Software source: PowerDNS repository

### Steps to reproduce
Can repro by sending DNSSEC request to the server:
```
dig . DNSKEY | grep -Ev '^($|;)' > keys
dig @lux01.d.sb +sigchase +trusted-key=./keys check-error-logs.daniel15.com. A
```

Results in:
```
Backend error: GSQLBackend unable to find before/after (after) for domain_id 8 and qname 'check-error-logs': Could not execute mysql statement: select ordername from records where ordername > ? and domain_id=? and disabled=0 and ordername is not null order by 1 asc limit 1: Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '>'
```

Example MySQL config:
```
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log
bind-address = 127.0.0.1
mysqlx_bind_address = 127.0.0.1
performance_schema = off
server_id = 5
```

Example PowerDNS config:
```
api=yes
api-key=************************************************************
default-soa-mail=dns@d.sb
default-soa-name=n5.d.sb
expand-alias=yes
launch=
local-address=127.0.0.1,104.244.77.121,198.251.90.202,198.251.90.2
local-ipv6=::1,2605:6400:30:f800::1
resolver=8.8.8.8
security-poll-suffix=
setgid=pdns
setuid=pdns
version-string=Daniel15-Web (https://d.sb/)
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=127.0.0.1,::1,10.123.1.0/24
webserver-port=38545

launch+=gmysql
gmysql-dbname=dns
gmysql-user=dns
gmysql-password=************************************************************
gmysql-dnssec=yes
gmysql-socket=/var/run/mysqld/mysqld.sock
```

### Expected behaviour
No error

### Actual behaviour
Error occurs

**Comment by Habbie** [comment]
Sounds like #9652, but in a different spot than reported there. Can you try https://github.com/PowerDNS/pdns/issues/9652#issuecomment-718749895 ? And/or, can you try version 4.4.0-beta1?

**Comment by Daniel15** [comment]
Changing the default character set /collation to latin1 is likely to break more things than it solves for me, as all other apps that use this same MySQL server use UTF-8. I can try the beta version - is it available as a Debian package?

**Comment by mnordhoff** [comment]
It should be available from https://repo.powerdns.com/.

I see 4.4.0-beta1 debs were built; I assume they're available in the "version 4.4.X" repositories.

**Comment by mnordhoff** [comment]
Scratch that. They're not built for Bullseye, though. You could probably rebuild it yourself, but...

**Comment by Habbie** [comment]
> Changing the default character set /collation to latin1 is likely to break more things than it solves for me

You can put it in `[pdns]` in my.cnf and put `gmysql-group=pdns` in pdns.conf

**Comment by zeha** [comment]
> Scratch that. They're not built for Bullseye, though. You could probably rebuild it yourself, but...

In a few hours, 4.3.1-2 will appear in Debian unstable, which is 4.3.1-1 + #9714. Maybe this is useful to @Daniel15.

**Comment by Daniel15** [comment]
> 
> 
> > Changing the default character set /collation to latin1 is likely to break more things than it solves for me
> 
> You can put it in `[pdns]` in my.cnf and put `gmysql-group=pdns` in pdns.conf.

@Habbie Looks like this worked for me. Thank you! 😃

**Comment by Daniel15** [comment]
Closing this issue as there's a viable workaround.

**Comment by Habbie** [comment]
thanks Daniel!
