### ISSUE TITLE
SpoofAction constructor with (single-ip, options) does not work

### ISSUE THREAD

**Issue by hhoffstaette** [PowerDNS/pdns#9783]
- Program: dnsdist
 - Issue type: Bug report

### Short description
Since 1.5 it should be possible to pass an options table to a SpoofAction constructor in order to set the TTL of the generated record. However this does not seem to work as expected:
```
dnsdist> SpoofAction("192.168.100.223", {ttl=3600})
Error: Unable to convert parameter from table to N5boost8optionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE> 
```
On the other hand supplying a list of two or more addresses plus the trailing options works fine.

### Environment
 - Operating system: Linux (Gentoo)
 - Software version: 1.5.1
 - Software source: package / built from source (gcc-10.2, boost-1.74)

### Steps to reproduce
1. SpoofAction("192.168.100.223") -> works
2. SpoofAction("192.168.100.223", {ttl=3600}) -> does __not__ work
3. SpoofAction("192.168.100.223", "192.168.100.223", {ttl=3600}) -> works, but with duplicated entry

### Other information
I suspect the function untangling the arguments has problems distinguishing between a single string and a list of strings, [here](https://github.com/PowerDNS/pdns/blob/9b2276a50f8955ed355106679ef0d4d620747d67/pdns/dnsdist-lua-actions.cc#L1607). I don't understand enough about Lua/C++ value coercion and how boost::variant works to fix this myself though.

**Comment by pieterlexis** [comment]
in the docs the syntax is `SpoofAction({ip|ips}[, options])`, in the code it looks like `SpoofAction({ip|ips}[, ip[, options]])`. I wonder what the second argument is all about.

**Comment by rgacogne** [comment]
I honestly don't know because we also take a list.. Let's get rid of it for 1.6.0?

**Comment by phonedph1** [comment]
If anyone runs into this before they are on an updated version, @rgacogne pointed out this work around `SpoofAction("10.10.10.10", nil, {aa=true})`
