### ISSUE TITLE
auth: Add support for CSYNC record type

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#9802]
- Program: Authoritative
 - Issue type: Feature request

### Short description
It would be great if pdns auth supported CSYNC records (RFC 7477).

### Usecase
In combination with RFC 8901 (which requires no additional support in pdns), CSYNC records facilitate transferring authority over a zone to another DNS provider without incurring any insecure time period.

### Description
RFC 7477 introduces the CSYNC record type, which contains a serial field, some flags, and a record type bit map (as in ~RRSIG~ NSEC). It would be great if such records could be provisionen in pdns auth, including through the API.

@ulrichwisser @nils-wisiol

**Comment by Habbie** [comment]
Are you only asking for support for the type? Or are you also looking for features similar to PUBLISH-CDNSKEY? (I assume that question makes sense in CSYNC context).

**Comment by peterthomassen** [comment]
The contents of the CSYNC record reflect domain-specific settings that are, for the most part, not synthesized. So, I'd be fine with this being a regular record.

The only part of that may be synthesized (and where something like PUBLISH-CSYNC would make sense) is the SOA part, which tell clients what to do after processing a CSYNC response. One could discuss whether it should be possible to automatically set it to the zone serial (interplays with SOA-EDIT etc.), possibly with some offset. I have no opinion about this, but it's possible that @ulrichwisser has some thoughts on this.

As far as I'm concerned, the plain CSYNC record would be sufficient for now, although I can see that going that route may complicate integrating CSYNC synthesis later on.

**Comment by Habbie** [comment]
> As far as I'm concerned, the plain CSYNC record would be sufficient for now, although I can see that going that route may complicate integrating CSYNC synthesis later on.

I don't think that will be a problem. It always starts with just the type - I just wanted to make sure I wasn't missing something big by assuming we can start with just the type :)

**Comment by ulrichwisser** [comment]
For starters only the type would be really good. In the long run support for PUBLISH-CSYNC would be needed.

**Comment by Habbie** [comment]
Type implementation in #10078.
