### ISSUE TITLE
docs should mention/describe += syntax for config items

### ISSUE THREAD

**Issue by dcarmean-impulse** [PowerDNS/pdns#9809]
- Program: DOCS (Authoritative, Recursor) (unknown re: dnsdist)
 - Issue type: Bug report

### Short description

I discovered by trial/error that I could append to a list-type config item using += syntax in lieu of line-continuation \ syntax. Specifically using new-domain-whitelist+=

### Environment

 - Operating system: Centos Stream 8
 - Software version: pdns-recursor-4.3.5-1.el8.x86_64
 - Software source: EPEL

### Steps to reproduce

1. Search for '+=' in doc.powerdns.com
2. don't find it
3. try it anyway

### Expected behaviour

Feature documented

### Actual behaviour

It works :)

**Comment by omoerbeek** [comment]
It is mentioned in https://docs.powerdns.com/authoritative/settings.html (intro), but it should also be there for rec.
