### ISSUE TITLE
[Docker Hub] Missing docker images for releases

### ISSUE THREAD

**Issue by dminuoso** [PowerDNS/pdns#9814]
Hi, 

currently the official docker hub group at https://hub.docker.com/r/powerdns/ has active projects for the master branch, but those only track the latest (which is very unstable and can change at a moments notice).

I see there's some projects for the 4.4 branch like https://hub.docker.com/r/powerdns/pdns-auth-44 but these do not have any images pushed to them.

It would be nice to have stable official images to pull. It would make testing against PowerDNS much easier in our CI.

**Comment by aerique** [comment]
We're currently working on integrating the Docker images into our release process, so that with each (final?) release the Docker images will be updated as well.
