### ISSUE TITLE
auth does not run with asan

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#9835]
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==20439==ERROR: AddressSanitizer: SEGV on unknown address 0x562cae3d24e0 (pc 0x7fde13afa6a7 bp 0x7ffc30ff9860 sp 0x7ffc30ff95a8 T0)
==20439==The signal is caused by a WRITE memory access.
    #0 0x7fde13afa6a6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1206a6)
    #1 0x562cade59f04 in __static_initialization_and_destruction_0 /home/peter/projects/powerdns/pdns/pdns/apidocfiles.h:4
    #2 0x562cade5a0b6 in _GLOBAL__sub_I__ZN13AuthWebServerC2Ev /home/peter/projects/powerdns/pdns/pdns/ws-auth.cc:2333
    #3 0x562cae28a244 in __libc_csu_init (/home/peter/projects/powerdns/pdns/pdns/pdns_server+0x173e244)
    #4 0x7fde1367d029 in __libc_start_main ../csu/libc-start.c:264
    #5 0x562cad485689 in _start (/home/peter/projects/powerdns/pdns/pdns/pdns_server+0x939689)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1206a6) in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&)
==20439==ABORTING
```

This was introduced in #8911. When this is fixed, we should try enabling asan (and ubsan) in CircleCI for auth.

**Comment by rgacogne** [comment]
Does this need any particular configuration to happen? I don't get a crash building master on Arch with `--enable-asan` (with g++, not clang++, if that matters).

**Comment by Habbie** [comment]
no, it even happens during the creation of `pdns.conf-dist`. The log above is from `g++` 4:8.3.0-1 on Debian 10. It crashes in CircleCI too (using clang 8) but I don't have a log from it.

If it does not crash for you, that might match the theory from somebody on IRC that 'this makes no sense and somebody is lying'.

**Comment by rgacogne** [comment]
That's weird.. For the record I'm building with: `./configure --with-dynmodules='bind gmysql geoip gpgsql gsqlite3 ldap lmdb pipe random remote tinydns' --with-modules='' --with-sqlite3 --enable-tools --disable-dependency-tracking --enable-unit-tests --enable-remotebackend-zeromq --enable-fuzz-targets --enable-experimental-pkcs11 --enable-ixfrdist --enable-asan`

I was wondering whether ASAN was actually enabled so I inserted a defect and it was correctly detected:
```
==24641==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffe15610c38 at pc 0x557e2890253b bp 0x7ffe15610470 sp 0x7ffe15610460
```

**Comment by Habbie** [comment]
I'll reproduce and post my configure.

**Comment by Habbie** [comment]
My backtrace above is from `'--with-modules=bind geoip gmysql godbc gpgsql gsqlite3 ldap lmdb lua2 pipe random remote tinydns' '--enable-unit-tests' '--enable-backend-unit-tests' '--enable-tools' '--enable-ixfrdist' '--enable-dns-over-tls' '--enable-experimental-pkcs11' 'CFLAGS=-O0 -ggdb3' 'CXXFLAGS=-O0 -ggdb3' '--enable-asan'` on Debian 10.

**Comment by Habbie** [comment]
> My backtrace above is from `'--with-modules=bind geoip gmysql godbc gpgsql gsqlite3 ldap lmdb lua2 pipe random remote tinydns' '--enable-unit-tests' '--enable-backend-unit-tests' '--enable-tools' '--enable-ixfrdist' '--enable-dns-over-tls' '--enable-experimental-pkcs11' 'CFLAGS=-O0 -ggdb3' 'CXXFLAGS=-O0 -ggdb3' '--enable-asan'` on Debian 10.

s/modules/dynmodules/ crashes in the same way.

**Comment by omoerbeek** [comment]
The issue occurs in the generated .asm, not in the string construction. I do not understand yet how.
This diff works around the issue, only a few mem leaks remain.

```
diff --git a/pdns/ws-auth.cc b/pdns/ws-auth.cc
index df0124f09..905bdc03b 100644
--- a/pdns/ws-auth.cc
+++ b/pdns/ws-auth.cc
@@ -48,6 +48,8 @@
 #include "threadname.hh"
 #include "tsigutils.hh"
 #include "ext/incbin/incbin.h"
+#undef INCBIN_SECTION
+#define INCBIN_SECTION ".section .data\n"
 
 using json11::Json;
```

**Comment by Habbie** [comment]
This also fixes it:
```
diff --git a/pdns/incfiles b/pdns/incfiles
index c2a99c0d0..39fd82f39 100755
--- a/pdns/incfiles
+++ b/pdns/incfiles
@@ -8,4 +8,4 @@ do
 	c=$(echo $a | tr "/.-" "___")
 	echo "INCBIN(${c}, \"${a}\");"
 	echo "static const string g_${c}{(const char*)g${c}Data, g${c}Size};"
-done
+done
```

Both this fix and Otto's work because the problem is as follows:
* INCBIN sets `.section rodata`
* the compiler sets `.bss` for storing the const string
* the next INCBIN call sets `.section rodata` again
* the compiler omits `.bss` for the second const string - presumably because it assumes it is already in BSS

**Comment by Habbie** [comment]
However, both fixes are workarounds for what really is a bug in incbin. Otto pointed out that this data is not binary anyway, so perhaps we should stop using incbin altogether.

**Comment by zeha** [comment]
> However, both fixes are workarounds for what really is a bug in incbin. Otto pointed out that this data is not binary anyway, so perhaps we should stop using incbin altogether.

If we end up with an incascii, fine, but a generalised thing like this is IMO better than having more copies for "mkpubsuffixcc" (which should also go away IMO).

**Comment by Habbie** [comment]
mkpubsuffixcc is a special case - the input data is not in the form we want. That said, I'd also like it to go away :)
