### ISSUE TITLE
Auth "4.5.0+master.0.g…" package built, newer "4.5.0~alpha0…" ones have lower version

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#9842]
- Program: Authoritative
 - Issue type: Bug report

### <s>Short</s> description
On November 29, the builder built Auth packages with the erroneous version number "4.5.0.0.master.g2717eea26". It's now building packages with correct versions like 4.5.0-alpha0.62.master.g44be51bbd.

However, Debubuntu considers the newer packages to have a lower version number, so 1.) reprepro is not publishing them at all, 2.) even if it did, users would probably have to force apt to "downgrade" them.

I don't entirely know what's happening on CentOS -- the erroneous package got built and presumably published, but I don't know which versions the publisher or users' package managers consider "newer".

There is also a "4.4.0.0.relauth44x.g036db2db4" package, but I don't know if that's a bad thing.

dnsdist and Recursor look fine, I believe.

The build that did it: https://builder.powerdns.com/#/builders/99/builds/1555

Example of a recent publish job, where all the Debuntu "Add the ... packages to the repository" logs show the new build being skipped: https://builder.powerdns.com/#/builders/110/builds/1552

See the bottom of the directory listing: https://downloads.powerdns.com/autobuilt/auth/ or https://downloads.powerdns.com/autobuilt_browser/#/auth

For reference:

```
$ pdns_server --version
Dec 09 15:31:12 PowerDNS Authoritative Server 4.5.0.0.master.g2717eea26 (C) 2001-2020 PowerDNS.COM BV
Dec 09 15:31:12 Using 64-bits mode. Built using gcc 5.4.0 20160609 on Nov 29 2020 20:48:06 by root@dcde1b886723.
Dec 09 15:31:12 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Dec 09 15:31:12 Features: libcrypto-ecdsa libgeoip lua lua-records PKCS#11 protobuf sodium 
Dec 09 15:31:12 Built-in modules: 
Dec 09 15:31:12 Configured with: " '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--sysconfdir=/etc/powerdns' '--with-dynmodules=bind ldap pipe gmysql godbc gpgsql gsqlite3 geoip lua2 remote random tinydns' '--with-modules=' '--enable-tools' '--with-libsodium' '--with-lua=luajit' '--with-protobuf' '--enable-unit-tests' '--enable-experimental-pkcs11' '--enable-lua-records' '--enable-ixfrdist' '--enable-systemd' '--with-systemd=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'"
$ dpkg -l | rg pdns-server
ii  pdns-server                          4.5.0+master.0.g2717eea26-1pdns.xenial          amd64        extremely powerful and versatile nameserver
```

**Comment by pieterlexis** [comment]
it looks like this is solved

**Comment by mnordhoff** [comment]
This happened again with 4.6.0.

Latest build: 4.6.0-alpha0.24.master.gecdd26ecb https://builder.powerdns.com/#/builders/97/builds/1759
Repo: 4.6.0+master.0.g0acc352c2 from 5 days ago. https://repo.powerdns.com/ubuntu/pool/main/p/pdns-recursor/

**Comment by pieterlexis** [comment]
hrm.

This smells like a bug in the pdns-builder when making a debian version number on a pre-release tag _without_ IS_RELEASE

**Comment by pieterlexis** [comment]
Old packages have been cleanup and replaced
