### ISSUE TITLE
Support dnstap for dnsdist by default for Debian OS

### ISSUE THREAD

**Issue by KVInventoR** [PowerDNS/pdns#9849]
I tried to run command:
`fsul = newFrameStreamTcpLogger("localhost:8000")`

on latest version of dnsdist which I installed from official repo, but got an error:
`Caught exception: fstrm with TCP support is required to build an AF_INET FrameStreamLogger`

`
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
`

I have version
`ii  dnsdist                              1.6.0~alpha0+master.197.g47dacd8e0-1pdns.stretch amd64        DNS loadbalancer`

**Comment by rgacogne** [comment]
The version (0.3.0) of libfstrm shipped in Debian Stretch is simply too old, TCP support was added in 0.4.0. I'm afraid there is nothing we can do about it.
