### ISSUE TITLE
Exclude TXT record in PDNS configuration

### ISSUE THREAD

**Issue by aashish791** [PowerDNS/pdns#9851]
- Program: Authoritative
 - Issue type: Bug report

### Short description
We need to exclude a TXT record in the PowerDNS configuration.

### Environment
 - Operating system: CentOS 7.8
 - Software version: 4.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
1) We recently migrated PowerDNS from version 3.4 to 4.4.0 after which TXT records stopped working but this also impacted other DNS records and they too stopped working. Since our customer connects is high at the moment and we cannot rollback to the previous version, so we are thinking to disable TXT record from serving to the customer and only allow other DNS records to serve to the customer.
2) Let us know if there is any way in the configuration to exclude a particular DNS record or any hotfix for the TXT issue.
3) In the earlier version of PowerDNS (3.4), the other DNS record was working correctly even if there was an issue with TXT record formatting. Not sure what changed in the new PowerDNS version.

### Expected behaviour
Other DNS records should work even if the TXT record is incorrectly added.

### Actual behaviour
Incorrectly configured TXT record stopped other DNS records from getting served.

**Comment by omoerbeek** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your
question looks like a support question. Support questions are handled
in our other online communities: IRC and our mailing lists. Please see
https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.
