### ISSUE TITLE
Misconfigured TXT record doesn't allow other DNS record to work

### ISSUE THREAD

**Issue by aashish791** [PowerDNS/pdns#9863]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Misconfigured TXT record doesn't allow other DNS record to work

### Environment
 - Operating system: CentOS 7.8 
 - Software version: 4.4.0
 - Software source: PowerDNS repository

### Expected behaviour
Other DNS record should work even if TXT record is incorrectly added.

### Actual behaviour
Logs:

`Dec 14 05:55:52 dns-aus-1 pdns[43142]: Exception building answer packet for upyourun.com/TXT (Parsing record content (try 'pdnsutil check-zone'): Data field in DNS should start with quote (") at position 26 of '"google-site-verification"content="7LyE8PFC9_v-I3hwWwdduItKIzb_awFsIKhcEcdKNIM"') sending out servfail`

`[aashish.c@dns-aus-1 ~]$ dig upyourun.com @162.251.82.247

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> upyourun.com @162.251.82.247
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 26202
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;upyourun.com.			IN	A

;; Query time: 0 msec
;; SERVER: 162.251.82.247#53(162.251.82.247)
;; WHEN: Mon Dec 14 06:31:52 GMT 2020
;; MSG SIZE  rcvd: 41

[aashish.c@dns-aus-1 ~]$ dig upyourun.com @162.251.82.247 NS

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> upyourun.com @162.251.82.247 NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 31499
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;upyourun.com.			IN	NS

;; Query time: 0 msec
;; SERVER: 162.251.82.247#53(162.251.82.247)
;; WHEN: Mon Dec 14 06:31:54 GMT 2020
;; MSG SIZE  rcvd: 41

[aashish.c@dns-aus-1 ~]$ dig upyourun.com @162.251.82.247 TXT

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> upyourun.com @162.251.82.247 TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9391
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;upyourun.com.			IN	TXT

;; Query time: 0 msec
;; SERVER: 162.251.82.247#53(162.251.82.247)
;; WHEN: Mon Dec 14 06:31:57 GMT 2020
;; MSG SIZE  rcvd: 41
`

Please do not close this ticket without any update.

**Comment by cmouse** [comment]
Your RRset is broken, why should it continue working?

**Comment by cmouse** [comment]
4.4 always internally looks up all records fror a name, which is why you are seeing this.

**Comment by mnordhoff** [comment]
There have also been changes to `TXT` record parsing and error handling in many releases.

**Comment by aashish791** [comment]
Thanks for the response.

Can you please suggest about how can we mitigate this issue as other records have stopped working because of misconfigured TXT value?

Can you provide me correct TXT record parser tool which is accepted by powerdns so that I can try updating the records from the backend?

**Comment by Habbie** [comment]
Hello,

our GitHub issue tracker is for bug reports and feature requests. Your question looks like a support question. Support questions are handled in our other online communities: IRC and our mailing lists. Please see https://www.powerdns.com/opensource.html for information about those.

We are closing this ticket. Comments will likely be ignored.

**Comment by Habbie** [comment]
I just noticed that this is the fourth time we've had to tell you that GitHub is for bugs and feature requests, not for support tickets. Please respect this.

> Please do not close this ticket without any update.

This is not okay. We are not your support department.
