### ISSUE TITLE
Make @ possible through API

### ISSUE THREAD

**Issue by bene4ka** [PowerDNS/pdns#9867]
- Program: dnsdist 
 - Issue type: Feature request

### Short description
Current versions of PDNS allows us to use '*' symbol in names, but it rejects all names starting with '@'.
An example. If I add NS entry with @ alias:
`{"error": "Name '@.sub.example.net.' contains unsupported characters"}`
PDNS-admin allows us to make @-entries (seems like this going through DB), but no way I can do it through API.

### Usecase
To meet the requirements of RFC 1035 (To denote the current origin).

### Description
My suggestion is to add _else if_ statement in **ws-api.cc**, _apiCheckQNameAllowedCharacters_ function.
A current function is:
```
void apiCheckQNameAllowedCharacters(const string& qname) {
  if (qname.compare(0, 2, "*.") == 0) apiCheckNameAllowedCharacters(qname.substr(2));
  else apiCheckNameAllowedCharacters(qname);
}
```
Function which Should be ok from my point of view:
```
void apiCheckQNameAllowedCharacters(const string& qname) {
  if (qname.compare(0, 2, "*.") == 0) apiCheckNameAllowedCharacters(qname.substr(2));
  else if (qname.compare(0, 2, "@.") == 0) apiCheckNameAllowedCharacters(qname.substr(2));
  else apiCheckNameAllowedCharacters(qname);
}
```
You can fix it in your way. I'll be happy, if you add this feature to powerdns.

Looking forward for your feedback.

**Comment by zeha** [comment]
Hi,

there was a template pre-filled for you when filing this issue, which has a number of important questions. Please use it.

For now this appears to be a ticket without a use case, and requesting a feature in violation of the current DNS standards.

**Comment by bene4ka** [comment]
> Hi,
> there was a template pre-filled for you when filing this issue, which has a number of important questions. Please use it.
> For now this appears to be a ticket without a use case, and requesting a feature in violation of the current DNS standards.

Please look at RFC 1035:
```
@               A free standing @ is used to denote the current origin.
```
Are you sure this is an violation? Btw, CoreDNS/Bind let us to make @-entries, pdns-admin let us to make @-entries. But pdns API not.

**Comment by pieterlexis** [comment]
`@` only has mostly relevance in zone files, the API does not work that way

**Comment by zeha** [comment]
As @pieterlexis said, the APi does not work this way. It's not a "BIND zone file" editor.

If you want to say `sub.example.net.`, just use that as the name. `@.sub.example.net.` is pointless.

**Comment by Habbie** [comment]
Indeed, we will not implement this, sorry.
