### ISSUE TITLE
auth: direct-dnskey ignored for AXFR (always "yes")

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#9868]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When `direct-dnskey` is unset or set to `no`, AXFR responses will include additional CDS records from the backend.

### Environment
 - Operating system: Ubuntu bionic
 - Software version: 4.3.1
 - Software source: PowerDNS repository

### Steps to reproduce
1. default setup
2. add a CDS record to a domain
3. query an AXFR for the domain and observe the extra CDS record

### Expected behaviour
The correct behavior would be to omit additional CDS records.

### Actual behaviour
extra CDS records included in output

### Other information
The behavior is correct when querying the CDS type explicitly.

I have not been able to test the behavior for DNSKEY/CDNSKEY records (due to a formatting problem in my local setup). The `direct-dnskey` setting affects those types as well, so it could be the case that the bug applies for them, too.

**Comment by Habbie** [comment]
Marking this 4.5.0 for now until I understand the impact. (Not having a milestone at all will make me forget to look at this even more.)

**Comment by zeha** [comment]
Small datapoint: on a secondary, with direct-dnskey=yes, these RRs are ignored on the incoming AXFR.

**Comment by Habbie** [comment]
Moved to 4.4.

**Comment by Habbie** [comment]
Fixed for 4.4.0 in #9873
