### ISSUE TITLE
boost.m4 does not contain modern toolchain tests

### ISSUE THREAD

**Issue by omoerbeek** [PowerDNS/pdns#9871]
boost.m4 is too old, eg. clang 10 on OpenBSD is detected as 
```
checking for the toolset name used by Boost for c++... gcc42 -gcc               
```
At lest for rec I do not see immediate consequences of this misdetection, but better safe than sorry.
Also newest versions of gcc are missing in the checks.

**Comment by omoerbeek** [comment]
A quick check of upstream (https://raw.githubusercontent.com/tsuna/boost.m4/master/build-aux/boost.m4)shows it is not having clang 9 & 10 or gcc 10 tests.

**Comment by pieterlexis** [comment]
https://github.com/tsuna/boost.m4
