### ISSUE TITLE
auth: AXFR ACL does not look at edns client subnet

### ISSUE THREAD

**Issue by mschrieck** [PowerDNS/pdns#9892]
Hi,

I think thr actual AUTH Server do not respect EDNS client subnet.

In tcpreceiver.cc ->doConnection 'remote' is always Set from connection. Only later the client subnet is used for logging purpose.

Would be great if remote is set from EDNS client subnet for ACL checks, if its configured.

Regards
Marco

 - Program: Authoritative
 - Issue type: Bug report

**Comment by mnordhoff** [comment]
Works for me, using `LUA` records and the bind backend.

```
$ dig +norec +subnet=2001:db8::/48 +tcp ecs.lua-e-f.mattnordhoff.net txt @ns10.mattnordhoff.net
<snip>
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; CLIENT-SUBNET: 2001:db8::/48/48
;; QUESTION SECTION:
;ecs.lua-e-f.mattnordhoff.net.  IN      TXT

;; ANSWER SECTION:
ecs.lua-e-f.mattnordhoff.net. 60 IN     TXT     "2001:db8::/48"
<snip>
```

**Comment by mschrieck** [comment]
If you read it out in the lua Script then yes.

If you try an AXFR then permission check is done via remote adresse.
Thats only in TCP.

**Comment by pieterlexis** [comment]
I think the ACL should never look at the subnet, as it can be attacker-provided. I think taking the address from the PROXY protocol would be better for the ACL

**Comment by Habbie** [comment]
Hello Marco, we never intended for ECS to affect any ACLs in the auth. We do have that planned for the PROXY protocol (#8403) but that work has not started yet.

**Comment by mnordhoff** [comment]
There may be a different way to accomplish what you're trying to do. If you want to discuss it on the pdns-users mailing list or #powerdns IRC channel, we may be able to help.

(Okay, maybe not me, but everyone else may be able to help!)

https://www.powerdns.com/opensource.html
