### ISSUE TITLE
broken link in recursor hooks documentation

### ISSUE THREAD

**Issue by setharnold** [PowerDNS/pdns#9893]
- Program: Recursor
 - Issue type: Bug report

### Short description

./pdns/recursordist/docs/lua-scripting/hooks.rst

https://docs.powerdns.com/recursor/lua-scripting/hooks.html

> Once a script is loaded, PowerDNS looks for several functions in the loaded script. All of these functions are optional.

The word 'functions' is a broken link. It's entirely possible it's supposed to be self-referential but may not be super-useful.

### Environment
Web documentation.

### Steps to reproduce

1. load https://docs.powerdns.com/recursor/lua-scripting/hooks.html in a browser of your choice
2. click the word 'functions' in this section: https://docs.powerdns.com/recursor/lua-scripting/hooks.html#writing-lua-powerdns-recursor-scripts
3. weep at 404

Thanks

**Comment by omoerbeek** [comment]
Fixed, thanks!
