### ISSUE TITLE
Provide an gmysql-charset option

### ISSUE THREAD

**Issue by Whissi** [PowerDNS/pdns#9898]
Hi,

the fix for #9652 isn't enough from my POV.

You are forcing admins to switch defaults for mysqld back to latin1.
Overwriting just for pdns when using system user via `.my.cnf` is not really feasible.

I think the best and correct way to address this issue is to provide `gmysql-charset` option and let pdns set used charset on connect like any other good application should do.

**Comment by mind04** [comment]
There is no need to change defaults. Use `gmysql-group` to switch form client to something else and put your pdns specific options in this new group in `.my.cnf `

**Comment by Habbie** [comment]
Indeed - we are not forcing anything, we are just no longer taking bad hints from the environment. @mind04's solution is the right one, I feel. Closing this.

**Comment by Habbie** [comment]
We'd happily take a PR for the gmysql docs that explicitly mention 'charset' so Google will find this trick, by the way.
