### ISSUE TITLE
auth/lmdb: on first run after 4.4 upgrade, new zones are considered "empty"

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#9903]
- Program: Authoritative
 - Issue type: Bug report

### Short description
I observed that on the first run after upgrading pdns auth with lmdb backend to version 4.4.0, new zones created after the upgrade were considered empty and continually triggered AXFRs. **But,** zones actually were not empty: `pdnsutil show-zone / list-zone` showed the expected contents, and queries were answered properly.

As far as I can tell, the problem went away by shutting down and restarting auth.

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
I'm not sure whether the issue can be reproduced reliably. I will comment here if I encounter the problem on other instances as well.

The configuration is here: https://github.com/desec-io/desec-frontend-node/blob/ec1a713dca87f79591e03b072a76dfb5bf76a5f9/ns/conf/pdns.conf.var
Before the upgrade, there was an additional `soa-minimum-ttl=60`, which we removed (it is now unsupported).

### Expected behaviour
Zone emptiness status should be detected correctly.

### Actual behaviour
Zones that are not empty and otherwise function correctly are claimed empty, so that thousands or AXFRs per day are triggered per affected zone. This happened more frequently than once per minute, although `slave-cycle-interval` is not configured. This caused hundreds of thousands of AXFRs per day, leading to significant extra traffic.

### Other information
Opened ticket according to discussion on IRC.

@nils-wisiol

**Comment by Habbie** [comment]
> I'm not sure whether the issue can be reproduced reliably.

I can reproduce it semi-reliably, I get an 'empty' every 2 or 3 startups.

**Comment by Habbie** [comment]
This happens if the slavecommunicator thread is -not- the first one to get to the LMDB file to upgrade it.

**Comment by Habbie** [comment]
When you add a domain, do you use pdnsutil, or the API in the running affected process?

**Comment by Habbie** [comment]
Also, if it ever happens again, can you share `lsof` output for the affected process?

**Comment by peterthomassen** [comment]
> When you add a domain, do you use pdnsutil, or the API in the running affected process?

API.

We are going to upgrade a few more nodes this month. Shall post `lsof` if the issue appears.

**Comment by Habbie** [comment]
I filed #9933 which fixes the similar-but-different issue I've reproduced.

**Comment by Habbie** [comment]
I have not been able to reproduce your specific case :(

**Comment by Habbie** [comment]
Based on `lsof` output from @peterthomassen, I believe #9933 will in fact fix that situation too. Closing this.
