### ISSUE TITLE
rec: dq.appliedPolicy.policyName doesn't seem to work anymore

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#9916]
- Program: Recursor
 - Issue type: Bug report

### Short description
dq.appliedPolicy.policyName stopped working sometime between 4.3.6 and 4.5.x (this ticket uses 4.5 but I have a 4.4.2 system which exhibits this as well). 

### Environment
 - Operating system: AWS Linux 
 - Software version: pdns-recursor-4.5.0-0.alpha0.master.599.g8586e6c4c.1pdns.el6.x86_64
 - Software source: PowerDNS repo

### Steps to reproduce
1. Setup RPZ filtering and lua script to print dq.appliedPolicy.policyName
2. trace-regex the entry
3. Run query, observe trace log is correct but output from lua is not. 

```
[root@slurp pdns-recursor]# grep rpz recursor.conf; more rpz.lua rpz-filtering.lua safe-browsing.zone 
# log-rpz-changes	Log additions and removals to RPZ zones at Info level
# log-rpz-changes=no
lua-config-file=/etc/pdns-recursor/rpz.lua
lua-dns-script=/etc/pdns-recursor/rpz-filtering.lua
::::::::::::::
rpz.lua
::::::::::::::
rpzFile("/etc/pdns-recursor/safe-browsing.zone", {policyName="safe-browsing"})
::::::::::::::
rpz-filtering.lua
::::::::::::::
function preresolve(dq)
        -- Debug logs
        pdnslog(dq.qname:toString() .. " to  " .. dq.localaddr:toString())
        pdnslog(dq.qname:toString() .. " policy name " .. dq.appliedPolicy.policyName)
        pdnslog(dq.qname:toString() .. " policy kind " .. dq.appliedPolicy.policyKind)

        return false
end
::::::::::::::
safe-browsing.zone
::::::::::::::
$ORIGIN .
$TTL 300
@       SOA localhost. localhost. ( 1 12h 15m 3w 2h)
        IN NS localhost.
;
pdns IN CNAME google.com.
```
### Expected behaviour
1. Lua dq.appliedPolicy.policyName prints 'safe-browsing' and policy kind (this is from pdns-recursor-4.3.6-1pdns.el6.x86_64)

```
Jan  6 22:22:08 slurp pdns_recursor[4237]: 1 [8/1] question for 'pdns|A' from 127.0.0.1:33621
Jan  6 22:22:08 slurp pdns_recursor[4237]: pdns. to  127.0.0.1
Jan  6 22:22:08 slurp pdns_recursor[4237]: pdns. policy name safe-browsing
Jan  6 22:22:08 slurp pdns_recursor[4237]: pdns. policy kind 5
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: Wants DNSSEC processing, auth data in query for A
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: Looking for CNAME cache hit of 'google.com|CNAME'
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: Looking for DNAME cache hit of 'google.com|DNAME' or its ancestors
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: No CNAME or DNAME cache hit of 'google.com' found
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: Found cache hit for A: 172.217.3.206[ttl=298] 
Jan  6 22:22:08 slurp pdns_recursor[4237]: google.com: updating validation state with cache content for google.com to Insecure
Jan  6 22:22:08 slurp pdns_recursor[4237]: Starting validation of answer to pdns|A for 127.0.0.1:33621
Jan  6 22:22:08 slurp pdns_recursor[4237]: Answer to pdns|A for 127.0.0.1:33621 validates as Insecure
```

### Actual behaviour
1. "Blank" 

```
Jan  6 22:15:01 slurp pdns_recursor[3731]: 1 [3/1] question for 'pdns|A' from 127.0.0.1:43090
Jan  6 22:15:01 slurp pdns_recursor[3731]: pdns. to  127.0.0.1
Jan  6 22:15:01 slurp pdns_recursor[3731]: pdns. policy name 
Jan  6 22:15:01 slurp pdns_recursor[3731]: pdns. policy kind 0
Jan  6 22:15:01 slurp pdns_recursor[3731]: pdns|A: RPZ Hit; PolicyName=safe-browsing; Trigger=pdns; Hit=pdns; Type=QName; Kind=Local Data
Jan  6 22:15:01 slurp pdns_recursor[3731]: pdns: status=got a CNAME referral, starting over with google.com
```

**Comment by phonedph1** [comment]
`dq.appliedPolicy.policyKind = pdns.policykinds.NoAction` also doesn't seem apply anymore either - which is perhaps not surprising because it seems to print the wrong value anyways right now as well.

**Comment by rgacogne** [comment]
What you are seeing is that the exact moment we are evaluating RPZ rules has changed in #9414, in order to match more closely to the RPZ specifications. One of the consequences, described in https://docs.powerdns.com/recursor/lua-config/rpz.html#evaluation-order and https://docs.powerdns.com/recursor/lua-scripting/hooks.html#modifying-policy-decisions, is that the RPZ rules have no longer been evaluated when `preresolve` is called. I really thought we made that change clear in the documentation, but it does not seem to be the case, we should fix that.

If you need to act on/log a RPZ hit, I would advise using the new `policyEventFilter` hook instead of `preresolve`.

**Comment by phonedph1** [comment]
Doh. Thanks @rgacogne - I somehow totally missed this.

**Comment by omoerbeek** [comment]
Agreed this needs more prominent docs plus a note in the upgrade guide. The example in https://docs.powerdns.com/recursor/lua-scripting/hooks.html#modifying-policy-decisions needs a >= 4.4.0 version.
