### ISSUE TITLE
Peer Authentication does not work for pdnsutil

### ISSUE THREAD

**Issue by KHIT93** [PowerDNS/pdns#9963]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using pdns with the PostgreSQL backend configured for peer authentication against unix sockets, the pdns server, name resolution and API work fine, but the pdnsutil commandline tool reports this error:
```
Jan 12 07:48:40 gpgsql Connection failed: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"

Jan 12 07:48:40 Caught an exception instantiating a backend: Unable to launch gpgsql connection: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"

Jan 12 07:48:40 Cleaning up
Error: Unable to launch gpgsql connection: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"
```

### Environment

 - Operating system: Ubuntu 20.04.1
 - Software version: 4.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. Install PowerDNS with the postgresql backend configured
2. Create `pdns` user in PostgreSQL and allow access to the given database if not owned by pdns user
3. Configure it like this in `/etc/powerdns/pdns.d/pgsql.conf
```
launch+=gpgsql
gpgsql-host=/run/postgresql/
gpgsql-port=5432
gpgsql-dbname=wpaas
gpgsql-user=pdns
gpgsql-dnssec=yes
gpgsql-prepared-statements=yes
```
4. Create the 4.4 schema in the database
5. Check that server starts and that API works
6. Try to query something using `pdnsutil`

### Expected behaviour
It would be expected that pdnsutil works with peer authentication when the pdns server and API does

### Actual behaviour
```
Jan 12 07:48:40 gpgsql Connection failed: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"

Jan 12 07:48:40 Caught an exception instantiating a backend: Unable to launch gpgsql connection: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"

Jan 12 07:48:40 Cleaning up
Error: Unable to launch gpgsql connection: Unable to connect to database, connect string: dbname='wpaas' user='pdns' host='/run/postgresql/' port='5432': FATAL:  Peer authentication failed for user "pdns"
```

**Comment by Habbie** [comment]
If I understand it correctly, peer authentication relies on the UID of the connecting process. `pdnsutil` runs as whatever user you invoke it under. Can you try running `pdnsutil` under your `pdns` user?
