### ISSUE TITLE
signed wildcard expansions might get cached for too long

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#9967]
In DNSSEC, a wildcarded name (say, `*.example.com`) is served as two things together:
* the wildcard, expanded (`hello.example.com`), with the original signature over `*.example.com`
* a NSEC(3) proof showing that `hello.example.com` does not exist and thus the wildcard expansion is legit

All of these records have TTLs, and so do their RRSIGs. The proof, and thus the expansion, is only valid for the lowest of all these TTLs (the TTLs themselves also being capped by signature expiry).

It appears that our Recursor, however, caches wildcards (plus NSEC(3) proofs) for the TTL of the expanded wildcard. If somebody validates downstream from us, we might serve them an expanded wildcard with expired proofs.

Thus, we should limit the caching of expanded wildcards to the lowest TTL involved in the expansion and the proof.

Note from @rgacogne: 

> we should likely take authorityRecs into account here: https://github.com/PowerDNS/pdns/blob/master/pdns/syncres.cc#L3104

**Comment by rgacogne** [comment]
I have not tested, but it looks like the current code would serve the expanded wildcard by setting the same TTL on the NSEC(3) proofs, even though it was not taken into account when computing the initial TTL. So:
- if the TTL of the NSEC(3) proofs was larger than the one of the expanded wildcard, all is fine ;
- otherwise we are artificially raising the TTL of the NSEC(3) proof which is bad.

**Comment by vcunat** [comment]
I expect that's most risky when an aggressively caching resolver forwards to you.

**Comment by Habbie** [comment]
> I expect that's most risky when an aggressively caching resolver forwards to you.

or when we raise the TTL beyond an RRSIG expiry

**Comment by vcunat** [comment]
I think the usual reaction should be to take minimum of the expiry and TTL, but it's still a little risky.

**Comment by Habbie** [comment]
> I think the usual reaction should be to take minimum of the expiry and TTL, but it's still a little risky.

Yes, but if -we- don't do that, the downstream validator cannot get valid data from us.
